### ISSUE TITLE
Orca does not start anymore (Mac OS ARM)

### ISSUE THREAD

**Issue by fre-lax** [SoftFever/OrcaSlicer#1000]
**Describe the bug**
Since today, Orca Slicer does not start:
![image](https://user-images.githubusercontent.com/77488729/236828275-ccfa0708-65de-4f3a-823c-034c33aadd68.png)

Operating System:
![image](https://user-images.githubusercontent.com/77488729/236828657-dc44a312-ba08-4608-9fd1-cc68dcd41953.png)

**Comment by fr3ak2402** [comment]
@fre-lax 

So on my Mac mini runs the official release of V 1 .6.2 without problems

Chip: Apple M2 Pro
Memory: 32GB
macOS: Ventura 13.3.1 (a)

**Comment by fre-lax** [comment]
@fr3ak2402
The error first occurred with V1.6.1 today. I updated it to V1.6.2 but same issue. I also installed V.1.6.1 again but it did not help.

**Comment by fre-lax** [comment]
@fr3ak2402 This worked!
It crashed once again (when starting the live stream) but not for some time now.

Thank you!

It used to crash before infrequently, when it was opened for a long time, though.

**Comment by fr3ak2402** [comment]
@fre-lax 
No problem.

If you still have a problem with the OrcaSlicer, feel free to ask again.

**Comment by MUCRalle** [comment]
Hi,
I can't install orca slicer on MacBook Air M1, because file is not searchable. Needs update.
Is there a solution? 
Thank you.

**Comment by Schrops67** [comment]
Wich Orca 1.8 version to use for Mac am 1 ?
