### ISSUE TITLE
Closing the app after saving the project incorrectly asks about unsaved changes

### ISSUE THREAD

**Issue by julie777** [SoftFever/OrcaSlicer#1006]
**Describe the bug**

I am working on a project and save it with `<ctrl>s`. 
I close Orca Slicer using the X in the upper right corner of the window.
I receive the message below.

![image](https://user-images.githubusercontent.com/5090005/236904363-ad8bec3e-2aa6-442e-870c-6c3c5a616023.png)

The project should not have unsaved changes, because I just saved. Looking at the file menu "Save Project" is disabled indicating that Orca Slicer does not think the project has been modified since the last save.

![image](https://user-images.githubusercontent.com/5090005/236904263-1a4e9835-f449-4c15-a737-9ac53d0a46f2.png)

Note:
I tried multiple times to reproduce this in Bambu Studio and could not, even using a copy of the same project.

**3mf File for This Bug**
If it is related to slicing, please append the 3mf file. It could be extremely helpful to solve the issue.

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**

**Printer model**
P1P

**Desktop (please complete the following information):**
 - OS: Windows]
 - Version 1.6.2

**Comment by rickbeec** [comment]
This issue still exists in 2.1.1 exactly as @julie777  describes.

**Comment by Mostwood** [comment]
Maybe I'm missing something but I still have this issue in 2.3.2
