### ISSUE TITLE
Issue with .6 mm nozzle and 1 mm line outer wall on 1.6.2

### ISSUE THREAD

**Issue by TownDrunk** [SoftFever/OrcaSlicer#1009]
**Describe the bug**
I've been using 1 mm line widths and .3 mm layers with my .6 mm nozzle for the last 2 months. My "fast" profile used the same print speeds as the .4 mm profile. It worked great.

Then something changed with 1.6.2. I noticed my prints were much running slower, and I had a LOT of heavy stringing on the inside of my prints. I even had prints failing due to the print head striking junk from the seams.

When watching it print, I noticed that the inside walls were printing slowly, then the outside wall would print very quickly (too quickly) and leave junk where the seam started. The problem resolved when I used .62 for the outer wall.

**3mf File for This Bug**
(attached)

**To Reproduce**
Slice and print with PLA. Notice the other wall prints too fast when using 1 mm line width. You should only need to print a couple of layers.

**Expected behavior**
Clean print with speeds set by the browser. Not too fast. Not too slow. 

**Screenshots**
![image](https://user-images.githubusercontent.com/66140355/236941833-3599a73b-48cc-4c6b-9598-c048b43d2745.png)

![image](https://user-images.githubusercontent.com/66140355/236945221-2d979143-67b9-4c15-8ac3-ea8b1433d16f.png)

![2023-05-08 16 44 06](https://user-images.githubusercontent.com/66140355/236943075-5e6e83ac-04e5-42e9-b2dd-9b872a7aad6a.jpg)

![2023-05-08 16 44 17](https://user-images.githubusercontent.com/66140355/236943084-fd0d1a3e-e241-49ff-8083-7f6ab95d8856.jpg)

[Mushroom_Dot_BUG.zip](https://github.com/SoftFever/OrcaSlicer/files/11425374/Mushroom_Dot_BUG.zip)

**Printer model**
Bambu X1C, AMS

**Desktop (please complete the following information):**
Device name	Surface-Laptop
Processor	AMD Ryzen 7 Microsoft Surface (R) Edition   2.30 GHz
Installed RAM	32.0 GB (30.0 GB usable)
System type	64-bit operating system, x64-based processor

**Comment by hliebscher** [comment]
i think 1mm line with is to big for this 0.6 nozzle ...
