### ISSUE TITLE
[Feature Request] Only Z hop for a range of layers

### ISSUE THREAD

**Issue by gbyleveldt** [SoftFever/OrcaSlicer#1015]
Is it possible to make z hops only for a range of layers like in Superslicer? It’s useful when doing multicolour prints using a single nozzle with manual filament changes for different objects occupying the same space

Basically, it’ll only z-hop from layer 1 to 3 (for example) so it doesn’t crash into previous print. Ideally I don’t want to leave z-hop enabled all the time to prevent stringing

**Comment by hliebscher** [comment]
You can add a second filament with z Hop enabled in filament overwrite Settings and change this for your Layers that you need

**Comment by gbyleveldt** [comment]
Thanks for your advice. I’m trying to think how I can make that work for my application but coming up empty. I’m aware of the filament overrides but making it work (if I can) would be clunky. Maybe I’m not understanding your suggestion properly?

**Comment by blastrock** [comment]
Prusa Slicer allows enabling Z-hop only on a range of height (Only lift Z "above Z" and "below Z"). Another use I have for that is to disable z-hop on first layer as it causes adhesion issues with some filaments for me.
