### ISSUE TITLE
Generic filament profiles have disappeared

### ISSUE THREAD

**Issue by FlyingLemming** [SoftFever/OrcaSlicer#1016]
**Describe the bug**
Within the Filament Selection Dialogue, all but one of the Generic profiles have successively changed their names to "SecKit Generic [...]". Ticking those profiles does not add them to the list of available filaments. Some of those profiles have been active and working fine before. After deselecting them in the list, they renamed themselves as described and became unaccessible.

**Screenshots**
<img width="829" alt="Bildschirmfoto 2023-05-09 um 14 30 22" src="https://github.com/SoftFever/OrcaSlicer/assets/41480875/ded8221f-fec4-4ec4-9c35-7188337417f4">

**Printer model**
Bambu Lab X1-C

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 13.3.1 (a)

**Comment by fr3ak2402** [comment]
@FlyingLemming 

These filaments are only intended for the SecKit printers and should only be used with these printers.

In addition, these filaments are displayed with all printers, which is also not correct. Since these filaments were created especially for the SecKit printers, they should also only be displayed with the SecKit printers.

This error with the display of the SecKit filaments has already been fixed and will be delivered with the next version.

**Comment by FlyingLemming** [comment]
It is version 1.6.2

Alright, I was not aware of this manufacturer. My thoughts regarding "SecKit" went into a different direction – I was thinking about some macOS security system placing the profiles under quarantine or something like that... 🫣

Anyway, in that case I am wondering why all Generic profiles except PETG-CF have been disappearing from my selection dialogue one by one. If I need such a profile now, I have to duplicate it into a user preset in Bambu Studio and sync it to Orca Slicer via the cloud.

**Comment by fr3ak2402** [comment]
@SoftFever 

After I fixed this bug in my V1.6.2, I was able to add all Generic filaments again and the SecKit filaments were no longer displayed on the Bambu X1C.

I just tested this in the latest nightly build of version V1.6.3 beta and the error is no longer present.

The SecKit filaments are gone and the Generic filaments are all back.

![Screenshot 2023-05-09 155831](https://github.com/SoftFever/OrcaSlicer/assets/96239814/3c0c717b-81a6-4944-a47a-609574763d10)

I have selected a few to add.

![Screenshot 2023-05-09 155859](https://github.com/SoftFever/OrcaSlicer/assets/96239814/0b7dbb1d-96e2-427c-bc22-870e6cabbcca)

After I have confirmed all have also been successfully created.

![Screenshot 2023-05-09 155925](https://github.com/SoftFever/OrcaSlicer/assets/96239814/4de49a96-d61f-45f1-bc31-db6288da5804)

**Comment by fr3ak2402** [comment]
@FlyingLemming 

The Generic PLA-CF is related to the following reason, the SecKit printer can not process this filament or has not been maintained. Therefore, this is not affected by this error.

I have the above times the whole executed in the version V1.6.3 of the OrcaSlicer, there the error is fixed again and works again as usual.

Don't worry, I also use the OrcaSlicer under macOS normally and had the same problem.

**Comment by FlyingLemming** [comment]
@fr3ak2402 
Now everything is coming together and starting to make sense. Thanks for the explanation and the fix! 😃
