### ISSUE TITLE
Line width for Support Interface and for Overhangs

### ISSUE THREAD

**Issue by rsilvers129** [SoftFever/OrcaSlicer#102]
If you add line width for Support Interface and also for Overhangs (or anything over support interface) then we can make those lines thinner, such as 0.3mm thick. That will make support peel off easier which will allow for a 0.1mm Top Z Distance. I tested this and it works. For that matter, a way to have the fan(s) come on a certain percent when doing any area that support interface contacts the part so that it doesn't stick as well.

**Comment by SoftFever** [comment]
Could you share some more information about the settings?
Some photos or a sample project will be beneficial.

We already have the `Top interface spacing`  setting to achieve a similar goal unless I missed something here.

**Comment by rsilvers129** [comment]
Not interface spacing and not support line width. Just Support "Support Interface line width" and "Overhang Line Width."

I promise this will be a major breakthrough.

If you print support interface and overhangs with a 0.30 to 0.37mm line width, the support will peel off, even if there is only a 0.1mm support gap. Problem is, the slicer has no way to set the support interface line width.

For now, the best I can simulate it is to set the Internal Solid Infill and Inner Wall line width to 0.35mm to come close to this. It makes support come off as easily with a 0.1mm gap as it currently does with normal settings and a 0.2mm gap. I have tested it.

![Capture](https://user-images.githubusercontent.com/4177461/220479944-ff017e08-915e-4030-874d-aaadf338e583.JPG)

**Comment by Bonaparte1446** [comment]
that could be very useful also using material support, hope that could be add. thank
