### ISSUE TITLE
[Feature Request] Custom Tool Change Gcode

### ISSUE THREAD

**Issue by Xcorpia07** [SoftFever/OrcaSlicer#1022]
The issue is that there is a filament change with M600 but the tool change is made after the movement prior to the purge tower, which makes it impossible to easily modify this area of ​​the gcode.

I wish Orcaslicer could bring over the multimaterial features of PrusaSlicer or SuperSlicer. Since in my printer without AMS, but with ERFC I need a specific gcode for material changes and purges.

Like me there are many multimaterial ERFC users who would be very grateful for this function.

**Additional context**

![image](https://github.com/SoftFever/OrcaSlicer/assets/35557316/a1749c99-8d7e-409d-83c9-3352509c550e)

![image](https://github.com/SoftFever/OrcaSlicer/assets/35557316/1ef89e6c-fdc4-4967-9246-2982310fc024)

![image](https://github.com/SoftFever/OrcaSlicer/assets/35557316/9d9b286d-e204-484a-8ae6-06bb7743e283)

**Comment by hliebscher** [comment]
Witch Code do you need?
Can you Place at filament End Gcode or filament Start Gcode 
It was executed every change

**Comment by Xcorpia07** [comment]
I need is to change the output of the tool change. so that it runs some previous macros without having to modify the whole system.

 I've also seen that Orcaslicer doesn't ram the purge tower. Nor any adjustment of tips. Since bambu lab uses a cutter on extruder.

**Comment by PatrikTheDev** [comment]
How did you add multiple extruders to your printer model in Orca? As far as I know it’s impossible to create a custom multimaterial printer (multi material with a single nozzle) because the menu isn’t present (at least on my machine)

**Comment by Xcorpia07** [comment]
Just by adding new filaments in the filaments section. You can add the same material and then change the color, the operation is the same as Bambu Studio, you can see the manual for it.

![image](https://github.com/SoftFever/OrcaSlicer/assets/35557316/ee8dbcdb-e554-4276-940f-82c1f25cfe29)

**Comment by Chaos-Seed** [comment]
Agreed @Xcorpia07, This would make Orca Slicer the go-to for me and a lot of others using ERCF. Thank you for raising the Feature Request!

**Comment by mojotaker** [comment]
Yes please add multi material support for ercf. Thank you.
