### ISSUE TITLE
Windows not rendering properly...

### ISSUE THREAD

**Issue by neogenix** [SoftFever/OrcaSlicer#1025]
**Describe the bug**
When I load OrcaSlicer 1.6.2 it doesn't render window level text. 

**To Reproduce**
Run on OrcaSlicer

**Screenshots**
![image](https://github.com/SoftFever/OrcaSlicer/assets/141967/f136ad20-5ac6-4de2-b9b7-63eec453ba3b)

**Printer model**
X1 Carbon

**Desktop (please complete the following information):**
 - OS: Windows 10 running Atlas. 
 - Version: Atlas OS

**Comment by SoftFever** [comment]
@neogenix 
You will need to install two dependencies.
Please refer to: https://github.com/SoftFever/OrcaSlicer#how-to-install

**Comment by neogenix** [comment]
> @neogenix You will need to install two dependencies. Please refer to: https://github.com/SoftFever/OrcaSlicer#how-to-install

Update: 

Both were installed, but I repaired the Visual C++ item, and that fixed it. Thanks!!
