### ISSUE TITLE
[Feature Request] Supporting dense layer from superslicer 

### ISSUE THREAD

**Issue by max-cz** [SoftFever/OrcaSlicer#1026]
**Is your feature request related to a problem? Please describe.**
Solid layer cannot be supported with low infill

**Describe the solution you'd like**
Add supporting dense layer as on Superslicer

**Comment by rfnovo** [comment]
On the same topic, the "Above the bridge" flow ratio is also a valuable option to improve top layer quality over infill, when using < 5 top layers.

**Comment by rfnovo** [comment]
Just to add an example, here is the same model, printed with the same parameters (20% infill, 3 walls, 3 top, 3 bottom), only difference is that one was sliced in Super Slicer with dense layer and 120% above bridge and you can clearly see the difference of quality in the top layer. 
![SuperSlicer](https://github.com/SoftFever/OrcaSlicer/assets/11941836/b0e78980-f014-424f-aae7-ad9f22cca075)
![Orca](https://github.com/SoftFever/OrcaSlicer/assets/11941836/f34e7149-41f6-40bb-872e-92497ed6cbc6)

**Comment by max-cz** [comment]
I'm not talking about bridges.

Even if I use 120% this(as example) will not be supported:
![afbeelding](https://github.com/SoftFever/OrcaSlicer/assets/49396891/c8b17d6a-7f06-433b-96f5-5db6be21d7ac)

While in SS it create a "net" to support the solid infill:
![afbeelding](https://github.com/SoftFever/OrcaSlicer/assets/49396891/d39a9b23-1178-40c0-bcb9-15e75b823c02)

This is under infill options, and it very useful with low infill.
![afbeelding](https://github.com/SoftFever/OrcaSlicer/assets/49396891/20ba97d9-af2b-4810-912e-2e8a281193e8)

**Comment by rfnovo** [comment]
I know, but this setting also affect the top layer quality because as the name implies it add an extra support for the top (dense) layer. Maybe I should had create a separate post for the above bridge flow. Sorry if it seems I tried to hijack your post. 
![image](https://github.com/SoftFever/OrcaSlicer/assets/11941836/39d2b026-ac31-4e46-8259-5d16eb880164)
![image](https://github.com/SoftFever/OrcaSlicer/assets/11941836/34e477b6-77df-4c20-b86e-7c1ba7584c5c)

**Comment by max-cz** [comment]
No worries, its related to top solid layers, and could maybe be easy to implement together.

**Comment by 3Dxdream** [comment]
It is strange, that this "feature" is missing in such a nice slicer. Printing and changing path direction in midair, without any anchoring (infill or perimeter), is, to be honest, a slicing fail. I hope for a fix, otherwise OrcaSLicer is not usable, at least for me.
These bridge lines or first solid layer lines must be anchored to the underlying infill lines or perimeters (should be profile settings).
And there should never be a printed line (perimeters, bridges, infill, ....) which changes direction in the air. This could be devastating for the whole print!

**Comment by max-cz** [comment]
> It is strange, that this "feature" is missing in such a nice slicer. Printing and changing path direction in midair, without any anchoring (infill or perimeter), is, to be honest, a slicing fail. I hope for a fix, otherwise OrcaSLicer is not usable, at least for me. These bridge lines or first solid layer lines must be anchored to the underlying infill lines or perimeters (should be profile settings). And there should never be a printed line (perimeters, bridges, infill, ....) which changes direction in the air. This could be devastating for the whole print!


Superslicer is the only one I know that has this the way to "fix" it increase the infill density, but it come at the cost of more material use.

**Comment by 3Dxdream** [comment]
> > It is strange, that this "feature" is missing in such a nice slicer. Printing and changing path direction in midair, without any anchoring (infill or perimeter), is, to be honest, a slicing fail. I hope for a fix, otherwise OrcaSLicer is not usable, at least for me. These bridge lines or first solid layer lines must be anchored to the underlying infill lines or perimeters (should be profile settings). And there should never be a printed line (perimeters, bridges, infill, ....) which changes direction in the air. This could be devastating for the whole print!
> 
> Superslicer is the only one I know that has this. The way to "fix" it increase the infill density, but it come at the cost of more material use.

I am using Superslicer and Cura. In Cura it's in the setting :"Top/Bottom --- Skin Expand Distance", where you can fill in a larger number in [mm] to get a properly applied supporting layer (spans over the whole area between perimeters) for the first solid layer.
Increasing the infill density, is not only more material usage, higher print time, more weight,.... but also no correct fix. The dangling molten plastic lines are just shorter. They too melt and accumulate at the nozzle surface an cause unnecessary printing artifacts.

**Comment by 3Dxdream** [comment]
Finally, there is hope!
https://github.com/SoftFever/OrcaSlicer/issues/1165

**Comment by DAKarp** [comment]
+1 This is the one lacking feature preventing me from switching from SuperSlicer to OrcaSlicer 🤞

**Comment by mlewis-everley** [comment]
> 

Same here! I have tried OrcaSlicer and it is pretty awesome, but no dense infill and no brim ears (I know this is on the roadmap) means I cannot use it :-(

**Comment by mlewis-everley** [comment]
So, the latest release of Orca has a variant of dense infill that I am testing now (but seems to work well). As far as I am concerned this issue is probably closed? What do you think @max-cz ?

**Comment by max-cz** [comment]
> So, the latest release of Orca has a variant of dense infill that I am testing now (but seems to work well). As far as I am concerned this issue is probably closed? What do you think @max-cz ?

Yes, we can close it, Extend sparse infill seem pretty close to this.
Thanks

**Comment by TheAnimatrix** [comment]
Superslicer's version is still superior. Orca gives me layer tearing even on the latest version like this
![image](https://github.com/user-attachments/assets/79b43636-4bee-4f5d-8c20-0d07ec8692cb)

**Comment by julian-weinert** [comment]
Support Dense Layers is far superior. It solves additional problems and improves top surface quality by a LOT.
@mlewis-everley would you please reopen this issue and consider implementing the feature?
I'm really struggling getting the same quality over large areas with OrcaSlicer, even when I add an additional top layer. It simply doesn't do nearly as well.
