### ISSUE TITLE
Retraction Test 1.6.3 beta

### ISSUE THREAD

**Issue by TechDude23** [SoftFever/OrcaSlicer#1029]
**Describe the bug**
The tower needs two bottom shell layers also it has manifold errors but they will repair maybe export the stl repaired file and add it back to Orca folder.    

The the retraction step rings do not match the retraction settings or how will you read it correctly ?  

**Expected behavior**
If I set it to .2 mm steps and retraction length 2 mm I get 14 rings and it should be 10 rings.   
 
**Printer model**
Bambu Lab X1
**Desktop 
Window 10

**Comment by SoftFever** [comment]
@TechDude23
Can you try the latest dev build? 
By right, it should have 11 rings/notches in case of 0.2mm/2mm

**Comment by TechDude23** [comment]
Ya same link as before ?
