### ISSUE TITLE
Slice gap closing radius & Classic wall generator V1.6.3

### ISSUE THREAD

**Issue by TechDude23** [SoftFever/OrcaSlicer#1031]
Slice gap closing radius with classic wall generator bug and stl file is ok. 

![Gap](https://github.com/SoftFever/OrcaSlicer/assets/128856354/16270159-1399-4f55-a31f-3bafaae60d14)

[stl file](https://files.printables.com/media/prints/35766/stls/353764_1894b1e6-c546-44a7-b07b-ce674effe081/tier.stl)

Window 10
Version 1.6.2 has the problem with more bars 
Version 1.6.3 is better but still needs 0.001 to fix classic wall bars

**Comment by SoftFever** [comment]
I can't repro the issue with default setting.
It would be easier to save and share the project in the future. The project file contains both the model and the settings.
![Screenshot 2023-05-11 at 7 47 21 AM](https://github.com/SoftFever/OrcaSlicer/assets/103989404/d38a2bc4-48df-4da4-832e-9e58a8eb2e00)

**Comment by TechDude23** [comment]
[Link](https://forum.bambulab.com/t/gap-infill-anomaly/12742)

This might help more
