### ISSUE TITLE
Only 1 wall on top surface won't work properly

### ISSUE THREAD

**Issue by rfnovo** [SoftFever/OrcaSlicer#1034]
Using Orca Slicer 1.62, with the "Only one wall on top surfaces" enabled, but it seems the setting is only applied to in the utmost top layer:  

![image](https://github.com/SoftFever/OrcaSlicer/assets/11941836/6e4b55da-24a1-4333-884f-573375839fdb)

**Comment by TechDude23** [comment]
Looks like they have fixed it with 1.6.3 you can download the beta version or try a modifier might work on the older V 1.6.2 

![Box](https://github.com/SoftFever/OrcaSlicer/assets/128856354/6629584a-4ff6-41bf-b9d1-32d0e56a5f63)

**Comment by liftbag** [comment]
> Looks like they might have fixed it with 1.6.3 you can download the beta version or try a modifier might work on the older V 1.6.2
> 
> Is this on the Bambu Lab X1 ?
> 
> ![Box](https://user-images.githubusercontent.com/128856354/237550039-6629584a-4ff6-41bf-b9d1-32d0e56a5f63.JPG)

Maybe you are on classic wall generator? The issue is related to the arachne wall generator.
This is Orca Slicer 1.6.3-beta.

<img width="1748" alt="Screenshot 2023-05-11 alle 14 31 39" src="https://github.com/SoftFever/OrcaSlicer/assets/14921654/07a6b658-7ae1-411b-9efa-de79a964c351">

**Comment by liftbag** [comment]
One of the most duplicate issues at the moment  #379 #459 #547 #582 #709 #763
