### ISSUE TITLE
Title bar not adhering to Linux window manager

### ISSUE THREAD

**Issue by DonutCables** [SoftFever/OrcaSlicer#1039]
**Describe the bug**
App is providing its own title bar instead of using the title bar provided by the window manager. This mostly means duplicated window buttons (minimize, maximize, close).

**To Reproduce**
Run the app on Linux

**Expected behavior**
App utilizes the title bar provided by the system window manager, example from Firefox
![image](https://github.com/SoftFever/OrcaSlicer/assets/19825893/67477b65-b94b-4fa7-86b6-bfd1a029e20f)

**Screenshots**
![image](https://github.com/SoftFever/OrcaSlicer/assets/19825893/ae2b1d65-a27d-419b-8b1f-8aa1a1ca07e9)

**Desktop (please complete the following information):**
 - OS: LinuxMint 21.1 Cinnamon/Mutter

**Comment by Canaill51** [comment]
Still same issue on Ubuntu 24.04 LTS, Mint 22.2/22.3 with latest released Orcaslicer

Please reopen this issue, in order to fix this concern.
