### ISSUE TITLE
Overhang and Bridge Cooling

### ISSUE THREAD

**Issue by NexGen-3D-Printing** [SoftFever/OrcaSlicer#1042]
**Describe the bug**
When I enable "Force Cooling For Overhangs and Bridges" The fan will come on as expected, then stay on for the entire layer, and will not turn off until the next layer, this for high temp filaments sensitive to part cooling injects a weak layer in the model cause very low layer adhesion.

**3mf File for This Bug**
Will upload a file with issue later.

**To Reproduce**
Force Cooling For Overhangs and Bridges

**Expected behavior**
Expected result would be the same as Cura, fan on for the bridge or overhang, then off for the rest of the layer.

**Screenshots**

**Printer model**
Orca Arena X1 0.4

**Desktop (please complete the following information):**
 - OS: Winblows 11
 - 1.6.2

**Comment by NexGen-3D-Printing** [comment]
Okay, now this bug has extended to the support interface cooling in beta version 1.6.3

I had to disable that as once the fan comes on for the support interface, it stays on for the entire layer of that model, then when the print head retracts and goes to another model, the fan shuts off, does this in RepRap and Klipper, compromises the part when printing sensitive materials, so I have chose to disable the fan features completely now, it just does not work the same as Cura does.

**Comment by kvnper** [comment]
I've encountered this too, it destroys some prints due to too much cooling

**Comment by NexGen-3D-Printing** [comment]
> 

Can confirm there are others experiencing this issue, I think most people don't notice as most print PLA or PETG, but it really effects ABS, PA and PC based filaments, its a real shame, as everything else in this slicer is really good, very impressed with it.

**Comment by asychev** [comment]
I can confirm that, ridiculously annoying bug which REALLY ruins some ABS prints
![image](https://github.com/SoftFever/OrcaSlicer/assets/19927701/bcecf9e7-dbed-434d-9a77-3e7de00afc0d)
Quite often I simply can't use Orca just because of that

**Comment by asychev** [comment]
@SoftFever any chance this can get your attention?

**Comment by SoftFever** [comment]
@asychev could you attch the project file?

**Comment by SoftFever** [comment]
@asychev 
Looks okay on my machine
You have the fan speedup value set to 1 second:
![image](https://github.com/SoftFever/OrcaSlicer/assets/103989404/222e7810-e65b-418c-86b0-02e2ef75aebf)
Turn if off we will get this:
![image](https://github.com/SoftFever/OrcaSlicer/assets/103989404/8005f21e-39c3-4aac-a288-905aeca0e599)

**Comment by asychev** [comment]
@SoftFever This setting cause the issue 
![image](https://github.com/SoftFever/OrcaSlicer/assets/19927701/9be53e4f-1866-43c1-8322-05a194031e75)

**Comment by SoftFever** [comment]
I tested the project file you shared.
It has the force cooling enabled as I can see.
![image](https://github.com/SoftFever/OrcaSlicer/assets/103989404/334c42f4-ce09-4736-94a6-c248f8071c75)

**Comment by asychev** [comment]
Maybe you are right, I indeed have fan speed up setting enabled and set to 1s, forgot about it.
@NexGen-3D-Printing maybe you have the same issue?

**Comment by SoftFever** [comment]
Please always attach project file.
It's really hard and time consuming to guess from screenshots when there could be multple factors affect the result

**Comment by asychev** [comment]
[1042-2.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/12162248/1042-2.3mf.zip)
Layers 67 and 70, layer time looks similar, but fan speed is different

**Comment by SoftFever** [comment]
@asychev 
This is how auto cooling/fan works:
The shorter the layer time, the higher the fan speed it needs; and vice versa.
If you switch to the layer time view, you will notice that those layers have longer layer times compared to other layers.

Reference: https://github.com/SoftFever/OrcaSlicer/releases/tag/v1.4.1

**Comment by SoftFever** [comment]
I recommend constant fan speed for cooling-sensitive filaments like ABS

**Comment by asychev** [comment]
@SoftFever Okay, seems like I got it finally. Thanks for you time, much appreciated
