### ISSUE TITLE
Bridge density setting affects anchoring of bridges

### ISSUE THREAD

**Issue by mjonuschat** [SoftFever/OrcaSlicer#1043]
Setting a bridge density smaller than 100% causes bridges to be extruded mid-air / not being anchored to walls.

This is visible in the  preview as well (50% and 25%):
![Screenshot 2023-05-11 at 20 03 45](https://github.com/SoftFever/OrcaSlicer/assets/203423/5072caca-18da-4330-b5af-6a82d970ada1)
![Screenshot 2023-05-11 at 20 07 39](https://github.com/SoftFever/OrcaSlicer/assets/203423/2ee68af4-e7ec-4df7-b579-3050c4e6fa9b)

How to reproduce:
Reduce bridge density to less than 100%, slice object with bridges, check preview

Version: OrcaSlicer 1.6.2 (Release) on AppleSilicon

**Comment by mjonuschat** [comment]
Project file that reproduces the issue:

[Xol 2 - Faceplate.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/11458585/Xol.2.-.Faceplate.3mf.zip)

**Comment by SoftFever** [comment]
@mjonuschat 
Thanks for reporting this.
Will fix it in the 1.6.3 official release.

**Comment by mjonuschat** [comment]
Will do, the preview is looking good, I'll send a test-job later today to verify.

**Comment by mjonuschat** [comment]
Prints come out nicely with the nightly build, thanks for the quick fix!
