### ISSUE TITLE
On Print start (bambu cloud), slicer does not automatically go to device tab.

### ISSUE THREAD

**Issue by psiberfunk** [SoftFever/OrcaSlicer#1047]
Normally during a print start for the Bambu series printers (X1C in this example), after the popup dialog here the user clicks "send".  Then, after sending the job via the Bambu Cloud, the dialog says going to the device tab in 3...2...1...  and then switches to the device tab after the job is uploaded.
![image](https://github.com/SoftFever/OrcaSlicer/assets/19777571/01304d88-c451-44fd-b343-ccef0a8bc20d)

However, in recent versions of orcaslicer, this has broken.. the job is properly uploaded, the dialog disappears, but the app **does not switch** to the proper tab.  Instead if just goes back to the prepare/preview screen.

It seems like whatever function is supposed to switch tabs is not getting called properly ?  I suspect this has something to do with the differences between the Bambu network plugin and some changes made to Orcaslicer.  This still works as expected on mainline Bambu slicer.

**Comment by bani6809** [comment]
i repro this bug as well. never switches to the device tab.

**Comment by psiberfunk** [comment]
yea, I agree seems a dupe of #1044

**Comment by psiberfunk** [comment]
this is fixed by this commit.

**Comment by mydevpeeps** [comment]
confirmed this goes to device tab in 1.6.3.
