### ISSUE TITLE
Profiles not loading

### ISSUE THREAD

**Issue by Pmant** [SoftFever/OrcaSlicer#1060]
**Describe the bug**
Filament profiles and potentially also printer/printing profiles are saved to the **default** user folder but are only loading from the **user id** folder. 

**To Reproduce**
Probably happens when using Bambu printer in LAN-Mode with OrcaSlicer logged into Bambu Account. I am also using a customized X1C profile instead of the system default. 

**Expected behavior**
Profiles should save to and load from the same folder.
Maybe related issues #692 #739. 

**Printer model**
X1C

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1.6.3-beta

**Comment by hliebscher** [comment]
then is the pointer to default folder ... and not to customer from bambu
