### ISSUE TITLE
Missing Minimal filament extrusion length skirt option

### ISSUE THREAD

**Issue by wight554** [SoftFever/OrcaSlicer#1068]
**Is your feature request related to a problem? Please describe.**
It's way easier to have constant minimum skirt than setting it per object (e.g for larger objects you need less loops than for smaller ones)

**Describe the solution you'd like**
Add an option to set minimal filament extrusion length

**Describe alternatives you've considered**
It's possible to change number of loops for each new project but that's bad UX imo

**Additional context**
 Available in PrusaSlicer

![image](https://github.com/SoftFever/OrcaSlicer/assets/26501410/95dbea13-c993-488f-8bc9-a85c376fb633)

**Comment by netweaver1970** [comment]
+1

**Comment by wight554** [comment]
Ended up using PRIME_NOZZLE from [here ](https://www.reddit.com/r/VORONDesign/comments/qztck1/comment/hlpoxq3) for now. But this option would be much better

**Comment by racemaniac** [comment]
also a +1 for me, really missing this setting

**Comment by Meningitix** [comment]
+1

**Comment by Eldenroot** [comment]
+1

**Comment by TANKIST73** [comment]
I use this option, in PrusaSlicer, to clean the nozzle. There is a great lack of this in Orca.

**Comment by jpbnto** [comment]
i need this setting too. hopefully it will be added feature.

**Comment by Charlie6089** [comment]
+1

**Comment by igiannakas** [comment]
PR above implements this feature. Please head over to the PR, download the build file from the actions tab and test the feature. Feedback welcome, in the PR above directly please.

**Comment by jpbnto** [comment]
> PR above implements this feature. Please head over to the PR, download the build file from the actions tab and test the feature. Feedback welcome, in the PR above directly please.

thank you

**Comment by Eldenroot** [comment]
Hi, please could you take a look, thank you 

#3718 

@igiannakas

**Comment by igiannakas** [comment]
@Eldenroot saw this when searching for issues. Again the code seems to be there, the option just removed. I may implement this next if there is enough of a need. Personally I haven’t used draft shields with orca having an enclosed Voron + BBL but I can see the rationale. In the meantime you just check how many layers the model is and set your skirt height to the same number of layers.

**Comment by igiannakas** [comment]
So... I've implemented it too @Eldenroot

**Comment by Eldenroot** [comment]
Thank you. It is not good that some useful features are just hidden. Because variability is a key, we have different printers etc.

What else could be easily enabled and could be useful?

**Comment by igiannakas** [comment]
> Thank you. It is not good that some useful features are just hidden. Because variability is a key, we have different printers etc.
> 
> What else could be easily enabled and could be useful?

Not much more from what I see immediately - the majority of available options are enabled. There are a couple related to multi extruder printing but I bet that these are not able to just be switched on as there is backing code that is more likely than not missing.
