### ISSUE TITLE
Crash while cancelling calibration

### ISSUE THREAD

**Issue by wight554** [SoftFever/OrcaSlicer#1069]
**Describe the bug**
When trying to prevent creating new calibration project by clicking cancel in popup, application still tries to create new project and crashes immediately 

**3mf File for This Bug**
Any would work

**To Reproduce**

1. Add some changes to current object
2. Click calibration and select Flow Rate -> Pass 1
3. See popup that lets you: 1) save 2) discard 3) cancel, click cancel
4. Calibration models generated, but application crashes

**Expected behavior**
Should not proceed calibration

**Screenshots**

![image](https://github.com/SoftFever/OrcaSlicer/assets/26501410/3369436b-354c-4186-8151-0435dae98544)

**Printer model**
Ender 3

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 1.6.2

**Comment by wight554** [comment]
Got the log:
```
1:57:52: OrcaSlicer got an unhandled exception: invalid stof argument
1:57:52: OrcaSlicer got an unhandled exception: invalid stof argument
```

**Comment by hliebscher** [comment]
at Mac M1  Orca 1.6.3 works and you have only 2 buttons -> save and cancel
the best way for calibration is an empty plate
delete all objects then make calibration...

**Comment by wight554** [comment]
> at Mac M1 Orca 1.6.3 works and you have only 2 buttons -> save and cancel the best way for calibration is an empty plate delete all objects then make calibration...

In my case I've accidentally clicked calibration and wanted to cancel it, but instead of cancelling it, got crash and lost all my config changes
