### ISSUE TITLE
Fault in the model after opening X-Y hole size compensation

### ISSUE THREAD

**Issue by ChiMufeng** [SoftFever/OrcaSlicer#1076]
This is a new issue that I discovered today. The model has been checked and there are no issues. I wanted to add a small component to this gyroscope, but I did not reserve the size. I wanted to enable X-Y hole size compensation to alleviate the installation pressure. However, when I finished slicing, I found that the model had serious faults. When I restored the X-Y hole size compensation value to 0, this problem disappeared, I would like to inquire if there is a way to enable X-Y hole size compensation without this fault issue
![Snipaste_2023-05-16_07-20-23](https://github.com/SoftFever/OrcaSlicer/assets/76713900/2d648078-7680-4433-89d4-723f039aee49)

**Comment by ChiMufeng** [comment]
这是模型文件
[666.zip](https://github.com/SoftFever/OrcaSlicer/files/11482580/666.zip)

**Comment by ChiMufeng** [comment]
This is the model file
[666.zip](https://github.com/SoftFever/OrcaSlicer/files/11482581/666.zip)

**Comment by ChiMufeng** [comment]
![Snipaste_2023-05-16_07-30-43](https://github.com/SoftFever/OrcaSlicer/assets/76713900/ca91ed1a-8f5e-4cb2-9570-af148aac46d8)

**Comment by hliebscher** [comment]
it is the same at Mac M1 Orca 1.6.3beta 
bigger values produce more overhang lines as error in arachne and classic
value 0 then it is OK 

![xy](https://github.com/SoftFever/OrcaSlicer/assets/9274162/555cb866-f633-4767-9bfa-49c47aa9aa0d)

**Comment by hliebscher** [comment]
at this areas the complete layers lost...  
![lost](https://github.com/SoftFever/OrcaSlicer/assets/9274162/f4436e10-7f45-4282-8bec-10d54489c6ba)

**Comment by hliebscher** [comment]
@SoftFever  can you look at this problem again ?

**Comment by SoftFever** [comment]
Looks like it has trouble detecting holes when there are nested holes.
