### ISSUE TITLE
Custom filament profile deleted when upgrading BBL DLLs

### ISSUE THREAD

**Issue by julie777** [SoftFever/OrcaSlicer#1077]
**Describe the bug**

I wanted to make sure that I had the most recent DLLs (Because I am a firmware beta tester).

After the update process my custom filament definition file was missing.

**3mf File for This Bug**
If it is related to slicing, please append the 3mf file. It could be extremely helpful to solve the issue.

**To Reproduce**

- I saved my project
- closed Orca Slicer 
- deleted the DLLs from the plugin directory
- and then restarted Orca. 
- It told me that it was downloading the DLLs. 
- I opened my project and noticed that instead of the custom filament profile that was set for the project, it showed generic PLA. 
    ![image](https://github.com/SoftFever/OrcaSlicer/assets/5090005/29995fc3-9701-45b6-a05c-6f78f0868136)
- I clicked on it and my profile was no longer in the list. 
- I checked the user profiles directory and they were all there except the one that was in use by the project.
- The actual filament settings in the project are still correct, but now just differences from Basic Pla. I am very glad about this part because I spent hours running calibration tests to create that profile.

**Expected behavior**

All of my custom profiles should not be affected.

**Screenshots**

**Printer model**

**Desktop (please complete the following information):**
 - OS:  Windows]
 - Version 1.6.2

**Comment by julie777** [comment]
I just repeated the process to see if it happened again. This time it did not delete my filament profile. It did remind me that the first time when it was downloading the DLLs, I notice that it was showing me logged in to my BBL account. I logged out as soon as I noticed it. 

I did check my preferences and I have it set to not sync.
![image](https://github.com/SoftFever/OrcaSlicer/assets/5090005/267c3593-c5af-41b7-abad-2c4f423e4b0a)

**Comment by julie777** [comment]
I logged in and tried to repeat the process the same way as the first time. I did not reproduce the problem.

**Comment by hliebscher** [comment]
as firmware beta tester pls test with the latest OrcaSlicer 1.6.3.beta or the org. BambuStudio to compare if the bug is only at OrcaSlicer
and the Bambu DLL are closed Source and Softfever use this only..

**Comment by Pmant** [comment]
This sounds similar to the problems I had recently with profiles not loading #1060. Check the other user folders under `C:\Users\<user>\AppData\Roaming\OrcaSlicer\user`.

**Comment by hliebscher** [comment]
before any deleting of the dll copy all our user files to an other  folder
without dll no connection is possible and Orca use the default folder and load the network plugin
