### ISSUE TITLE
Retraction calibration towers

### ISSUE THREAD

**Issue by cmerkle** [SoftFever/OrcaSlicer#1082]
Please consider adding the ability to create retraction speed and distance towers via the calibration menu, similarly to how temperature towers can currently be generated. This seems to be the main calibration that is currently missing from Orca Slicer and the only reason I ever revert back to Cura.

Super Slicer and the Cura Auto Towers plugin currently implement this. Personally, I prefer the Cura auto towers method and would love to see it rolled into Orca Slicer.

**Comment by Learoy1** [comment]
There is a search function. 

<img width="422" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/80989694/dd7c7ae0-0698-4fd5-95aa-c9652ad8b4f0">

https://github.com/SoftFever/OrcaSlicer/issues/439

https://github.com/SoftFever/OrcaSlicer/issues/802

https://github.com/SoftFever/OrcaSlicer/issues/92
