### ISSUE TITLE
Camera stream does not work on Ubuntu

### ISSUE THREAD

**Issue by RobRobM** [SoftFever/OrcaSlicer#1084]
**Describe the bug**
When starting the camera stream on Ubuntu I get an error message that the codecs are missing (see screenshot). All necessary codecs are installed.

**To Reproduce**
Press the play button in the device tab to start the camera feed and the error message appears.

**Expected behavior**
The camera stream should appear.

**Screenshots**
![error message](https://github.com/SoftFever/OrcaSlicer/assets/19664209/1d10b5b1-60e7-4427-b74a-5f7745de07a3)

**Printer model**
Bambu Labs X1C

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 23.04

**Comment by hliebscher** [comment]
and with BambuStudio works? have you installed the required codecs?

**Comment by RobRobM** [comment]
Yes I have. I even tried reinstalling them.
