### ISSUE TITLE
Flowrate Calibration model too big for small build plates

### ISSUE THREAD

**Issue by DavMem** [SoftFever/OrcaSlicer#1094]
**Describe the bug**

**3mf File for This Bug**
If it is related to slicing, please append the 3mf file. It could be extremely helpful to solve the issue.

**To Reproduce**
Slice Flowrate Calibration pass 1 or 2 for Voron 0

**Expected behavior**
The test model does not fit the build plate

**Screenshots**
![Screenshot 2023-05-19 at 08 47 40](https://github.com/SoftFever/OrcaSlicer/assets/126317099/ccabfc72-9a6b-4345-9004-3fb8eba9d7cb)

![Screenshot 2023-05-19 at 08 50 08](https://github.com/SoftFever/OrcaSlicer/assets/126317099/beebb7d4-32f2-4929-94e8-4da850717c70)

**Printer model**
Voron 0.1/0.2
**Desktop (please complete the following information):**
 - OS:macos ventura

**Comment by fourtwizzy** [comment]
Have you tried just scaling it? I set this to 50% and it shrunk them all. Just leave the uniform scaling check box and then just change say the x value to 75 percent. The rest will follow suit.
![scale](https://github.com/SoftFever/OrcaSlicer/assets/1735941/540706d0-c544-41d8-98cb-19cd4b910002)
