### ISSUE TITLE
flow at first layers.

### ISSUE THREAD

**Issue by Ziv831** [SoftFever/OrcaSlicer#1095]
i need to set up a lower first-layer flow. 

when I print with PETG, my 2 first layer need a smaller flor rate' if it is possible.

**Comment by hliebscher** [comment]
it is easy ... add a high range modifier than can you change anything... layer hight flow 
go to prepare / select model / right click and ad the modifier....

**Comment by Ziv831** [comment]
Thanks :)

**Comment by Ziv831** [comment]
Ok, that work fine,  but I meant that in the global process, it would be a "first layer flow " modifier 
Just like in Cura slicer,  I find it very useful. 

Ziv

**Comment by hliebscher** [comment]
flow first layer can you define under quality

**Comment by PowerWiesel** [comment]
> it is easy ... add a high range modifier than can you change anything... layer hight flow go to prepare / select model / right click and ad the modifier....

thx for the workaround - I would have never found this myself :laughing: 



> flow first layer can you define under quality

where? Was the option removed in the meantime?
![image](https://github.com/SoftFever/OrcaSlicer/assets/11167590/8a74a5fd-2032-4779-b582-ad275baa717d)



> Ok, that work fine, but I meant that in the global process, it would be a "first layer flow " modifier Just like in Cura slicer, I find it very useful.
> 
> Ziv

100% 
While I really like some of the Orca features, I really miss some Cura features - like flow rate settings for every line type and of course first layer.

**Comment by nuxeh** [comment]
Bottom surface flow appears to only affect the solid infill, and not the perimeters, i can provide screenshots to prove so, but i assure you that it's the case from what i've seen. I would really like to tweak first layer flow from settings, including walls, without having to use a height range modifier. I see word online that there is an "initial layer flow" concept in developer settings, but for the life of me I can't find it, despite having enabled developer settings.

**Comment by nuxeh** [comment]
Also, I can't any obvious way to change flow ratio with a height range modifier, either

**Comment by haski369** [comment]
Would like this too, it was very useful in Cura

**Comment by nuxeh** [comment]
I've been working on, and using, a post processing script as a workaround for this, [here](https://github.com/nuxeh/flow-scale.py), in case it's of use to anyone

**Comment by eightheads** [comment]
I'd really like to see this available in Orca as well. Adjustment of first layer flow would help with various build plate types.

**Comment by nuxeh** [comment]
This is what I do now... Works nicely as a workaround, except that you need to edit the custom gcode to change the flow, but it's workable. Below would be added to "before layer change" gcode in printer settings, for 1.05:

```
{if layer_num == 0}M221 S105{endif}
{if layer_num == 1}M221 S100{endif}
```

**Comment by xamindar** [comment]
I can't believe this is a not planned feature in orca. It is absolutely important to have for PETG. My printer needs a 80% flow rate for proper dimensions and no over extrusion (E steps are perfect already), but the first layer still needs to be a bit higher for good bed adhesion.

**Comment by grandoth** [comment]
> I can't believe this is a not planned feature in orca. It is absolutely important to have for PETG. My printer needs a 80% flow rate for proper dimensions and no over extrusion (E steps are perfect already), but the first layer still needs to be a bit higher for good bed adhesion.

I followed the link to #11000 from nuxeh and found #10641. It looks like per filament settings are being evaluated too! Part level should be in 2.3.2. I found it in the release notes for the Beta. I haven't tried it yet.

**Comment by valerii-bokhan** [comment]
> It looks like per filament settings are being evaluated too!

Hi, yes the PR is there - https://github.com/OrcaSlicer/OrcaSlicer/pull/15086 I would appreciate if someone can test it 🙏
