### ISSUE TITLE
Parts shifting after cutting and saving

### ISSUE THREAD

**Issue by Basti77** [SoftFever/OrcaSlicer#1097]
**Describe the bug**
To print RC flight parts it is necessary to print different heights with different settings.
This is done by cutting parts.

The peculiar thing is that the parts shift after they have been loaded and spread.
How can this be prevented and automatically rearranged? 
<img width="566" alt="verrückt" src="https://github.com/SoftFever/OrcaSlicer/assets/8112783/537a4ad9-6de7-4071-a3e6-a8946d9555e3">

**3mf File for This Bug**
If it is related to slicing, please append the 3mf file. It could be extremely helpful to solve the issue.

**To Reproduce**
this behaviour happens all the time. and also with Bambu Studio.

**Expected behavior**

**Screenshots**
[fuse.mf.zip](https://github.com/SoftFever/OrcaSlicer/files/11520104/fuse.mf.zip)

**Printer model**
p1p
**Desktop (please complete the following information):**
 - OS: Win 10
 - Version 22H2

**Comment by hliebscher** [comment]
the best way is use high range modifier to change any settings for this area
witch Orca version?  
i have cut other parts that working fine after reload all parts at the same position
