### ISSUE TITLE
Flow rate test pass 2 layer 1 artifacts

### ISSUE THREAD

**Issue by HookyQR** [SoftFever/OrcaSlicer#1098]
**Describe the bug**
Small issue, but obvious.

Extra inner walls drawn on first layer of Flowrate test - pass 2 with first layer < 0.29mm.

Present at first layer hight of 0.289 and below, but not at 0.29

**3mf File for This Bug**
If it is related to slicing, please append the 3mf file. It could be extremely helpful to solve the issue.

[Flowrate Test - Pass2.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/11521688/Flowrate.Test.-.Pass2.3mf.zip)

**To Reproduce**
Slice per attached 3mf

**Expected behavior**
No extra inner walls

**Screenshots**

![CleanShot 2023-05-20 at 14 14 35](https://github.com/SoftFever/OrcaSlicer/assets/14353068/564d0bb9-8d3b-4231-b906-e51768237ff9)

**Printer model**
Tronxy X5SA
 
**Desktop (please complete the following information):**
 - OS: MacOS
 - Version Ventura 13.2 (22D49)
 - Orca version: 1.6.1

**Comment by hliebscher** [comment]
At first take the latest Version or Beta 1.6.3

**Comment by SoftFever** [comment]
@HookyQR 
OS will automatically set layer height based on the profile.
Did you modify the layer height after the test was generated?

**Comment by HookyQR** [comment]
@SoftFever 
Both yes and no. The artefacts are there with the default (0.25 initial layer + 0.2 layer). I then modified and re-sliced to find out when they went away.

Checked with 1.6.3 beta and it's still there.

**Comment by HookyQR** [comment]
Note that all 3 artefacts are the same, just transposed. 🤷

**Comment by HookyQR** [comment]
I've taken a look at the source file in blender, and there's nothing there that could cause this, so I'm assuming it's a quirk of the slicer. 🤷
