### ISSUE TITLE
Cannot slice complex part with tree supports

### ISSUE THREAD

**Issue by mmakam2** [SoftFever/OrcaSlicer#1102]
I've left it for many hours and it won't complete slicing. No errors, but it just keeps going.

![image](https://github.com/SoftFever/OrcaSlicer/assets/25559970/71df12d1-a543-4b2b-98ff-ccf8670891d9)
![image](https://github.com/SoftFever/OrcaSlicer/assets/25559970/530fa849-f594-4f81-a128-82151de79d62)

**Comment by hliebscher** [comment]
@mmakam2 can you add your 3mf file as zip than we can test it?
