### ISSUE TITLE
Buildplate appears black

### ISSUE THREAD

**Issue by echolot79** [SoftFever/OrcaSlicer#1109]
**Describe the bug**
-- on the 1.6.3 beta my buildplate appears black 
I´m using a Neptune 3 Pro but the black Plate appears at all Printers in the Settings 
  on 1.6.2 everything was fine 

Update: It has something to do with the Active state "layer" of the plate. If a add more buildplates all are fine but the active one gets an black layer every time

left 1.6.2  right 1.6.3 beta 

![Unbenannt-6](https://github.com/SoftFever/OrcaSlicer/assets/134237675/a9ef813d-401e-4661-83e6-68dfea840029)

**Desktop (please complete the following information):**
 - OS: Windows 11 pro 64bit 
 - Version 22H2

**Comment by Landhus** [comment]
I'm having the same issue as well.

**Comment by maximoehre** [comment]
Same issue still on 1.7.0 with Neptune 4 Pro

**Comment by ReverendRhyme** [comment]
Same issue on 1.7.0 on Anycubic Vyper and Ender 3 series.

**Comment by itzner** [comment]
I could fix the issue by deleting the bed texture file in C:\Program Files\OrcaSlicer\resources\profiles\<manufacturer>, as described in #1187

**Comment by Ltek** [comment]
Sam problem on 1.7.0 with Artillery X2... deleting the texture file removed the black but did not replace it with the custom bed texture for the X2

**Comment by Ltek** [comment]
1.8 and this is still not fixed?

**Comment by hjoungjoo** [comment]
I'm using 1.9.0 and I'm in the same black state on AMD Ryzen 5 3400G.
I expect improvement in the next version.
