### ISSUE TITLE
Print host Repetier Server not working when the host is not called Repetier-Server

### ISSUE THREAD

**Issue by ChristianReil** [SoftFever/OrcaSlicer#1116]
When selecting Repetier as Print Host Upload it wants to see the Repetier to be called Repetier-Server.
This works for standard installs but often Repetier is Branded and have their own name like CR3D-Server due that the Repetier connection wont work as it doesnt pass the version check.

Suggested to have or a naming box or a checkbox to skip the check.

the same problem existed a long time ago with SuperSlicer, everything is also described in this issue.:
https://github.com/supermerill/SuperSlicer/issues/1376

**Comment by SoftFever** [comment]
@ChristianReil 
Fixed. 
You can download the nightly build here: https://github.com/SoftFever/OrcaSlicer/actions/runs/5059776967
