### ISSUE TITLE
[Feature Request] Non-planar slicing

### ISSUE THREAD

**Issue by tpimh** [SoftFever/OrcaSlicer#1118]
There are currently several implementations of non-planar slicing. The resulting G-code is using layers that are not flat, effectively using the Z-axis of the printer. The obvious benefits are better surface finishing even if the top of model if not flat and reduced need for support structures, but there might be more. Nozzle geometry should be taken into account.

More information can be found here: https://github.com/supermerill/SuperSlicer/discussions/1741

**Comment by TexZeTech** [comment]
I would love to play with Non-planar in a slicer that is actively getting updated. 

*_**making custom hotend intensifies**_*

**Comment by Dmeerev** [comment]
Any updates?

**Comment by JMVS** [comment]
Is this of any help? Non-Planar in PrusaSlicer https://github.com/EiNSTeiN-/PrusaSlicer

**Comment by n3roGit** [comment]
Reopen :D
