### ISSUE TITLE
Add alternate extra wall

### ISSUE THREAD

**Issue by timied07** [SoftFever/OrcaSlicer#112]
Cura has a setting that adds an extra wall every other layer. So when you choose to print with 2 walls, it actually prints 2,3,2,3,2,3,...

I've found this helps with print time, added stiffness/strength, and really helps with the infill to wall connection points.

**Comment by oleksii-suprun** [comment]
It looks like this request is the same as #349

**Comment by Eldenroot** [comment]
This is implemented :)
