### ISSUE TITLE
Display PA and flow values after lidar inspection

### ISSUE THREAD

**Issue by tobilab** [SoftFever/OrcaSlicer#1121]
The acquired values for the PA and flow using the X1Cs lidar should be displayed somewhere so that one can use these values for e.g. using them within a filament profile.

**Comment by rovili** [comment]
This is part of the firmware and not the Slicer. BambuLab doesn't provide the results of the calibration.
Also, the flow calibration of the BambuLab doesn't calibrate the flow, only pressure advance.
