### ISSUE TITLE
Retraction test shows error  "53 non manifold edges"

### ISSUE THREAD

**Issue by Manfredo1952** [SoftFever/OrcaSlicer#1124]
**Describe the bug**
Initiate retraction test in 1.6.3b , this error shows up
I found the file in the package content of the app and opened in OrcaSlicer, no error report comes up.
Further tresting.. when I tell Slicer  "end retraction length 4mm " no error shows up

 
**Screenshots**
![image](https://github.com/SoftFever/OrcaSlicer/assets/56330568/ea06ef5d-2362-4277-843a-7e3ff26cf9f0)

**Printer model**
Bambu X1C

**Desktop (please complete the following information):**
 - OS: OSX, iMac, Intel
 - Version 11.7.7

**Comment by hliebscher** [comment]
but it works fine 
We once had a similar problem with the temperature tower.

**Comment by lucasvillalta** [comment]
how to solve this?
