### ISSUE TITLE
Discussing the future of Orca

### ISSUE THREAD

**Issue by julie777** [SoftFever/OrcaSlicer#1126]
I have been waiting to bring this up. I have had a vision about the future of the 3D printing ecosystem for some time now and I have been keeping notes based on using all of the various tools, different printers, different slicers, and so on.

When I first started using Orca Slicer, it was because of the built in calibration. It seemed to be just @SoftFever owning it, managing it, and doing all the development. I asked about the project goals and never got a response. 

Over time many printers were added. There was more and more activity and now the plan to change how profiles are managed makes it feel like the time is right to see if anyone feels like I do and wants to do something bigger. 

What I would like to do is design a better tool-chain and overall user experience from end to end. Do it in a way that directly supports all types of users, novice that just wants to print models they download up to the small business running a print farm. (I don't care about industrial printing. I believe that they have their own bubble that supports $50,000 printers and processes.)

I would like us to consider using Orca as a "brand" and a name for the community around this project.

I have been trying to think of a good name for a Reddit community to discuss the future, share ideas and start to build out a better system. By no means do I mean start from scratch. Instead incorporate the best from what exists and work with a plan to avoid wasting effort. 

Some examples of how the ecosystem could be improved.
  - a filament profile library - I see posts every day asking about the best settings for some filament
  - a machine profile library - this might not be directly portable to other slicers, but it would contain the machine information that everyone needs regardless of their slicer
  - a library of custom G code that optimizes certain things
  - a set of tools that work together, but is separate and can be used by itself. Some examples
      - the G code viewer that is part of Prusa Slicer. 
      - a packager and publisher that can automate the process of collecting the required files and uploading them to thangs, or Printables
      - a profile manager that can show dependencies and allow user to easily manage all of there custom profiles, diff and transfer, rename,create, delete.
  - an IDE that ties everything together. BBL is trying to do this with Bambu Studio, but I for one am not satisfied with their approach. I think we can do better.

I have spent time working on some profile management for myself because a change in firmware might cause a change in the system profile's gcode, which could cause my custom G code to have issues.
I have also been working to reverse engineer BBL gcode that they have not documented and add it to a master list that compares what various brands and firmware supports.
None of what I have been working on has been pushed to GitHub yet. 

If there is enough interest it this type of big picture master plan to help the community, I propose we create a Reddit community and start discussing the ideas.

What do you all think?

**Comment by julie777** [comment]
It just occurred to me that when you read this, the first question you will have is "why do I care what she thinks?". 

I am going to go update my GitHub profile so there will be more about me there, but I think I should give you a short summary of what I could bring to the Orca group.

I am a semi-retired software engineer. I have time now to work on OS projects that I feel passionate about. I contributed to the success of many commercial products and I know what it takes to create a great product, to maintain it and to make users happy. My last commercial product was SlingTV, which I contributed to at all levels from architecture to deployment automation.

**Comment by julie777** [comment]
This should be move to discussion

**Comment by SoftFever** [comment]
@julie777 
Thanks for sharing your thoughts.
I've considered the idea of an online profile repository, but I haven't had the time to work on it yet.
If you or any other developer is interested in working on it, that would be great, and we can continue the discussion in the [Dev](https://github.com/SoftFever/OrcaSlicer/discussions/categories/dev) section.

As an open-source project, there isn't and won't be an aggressive development plan for OrcaSlicer. I develop and maintain it in my spare time. All contributors so far are the same.
There isn't any so-called "closed" Orca group. 
Any developer can contribute to the project at their own comfortable pace and at any time. 
For small changes or features, pull requests (PRs) are sufficient.
If there are any significant proposed changes, it is necessary to have a discussion thread in [Dev](https://github.com/SoftFever/OrcaSlicer/discussions/categories/dev) beforehand.

If, in the future, OrcaSlicer attracts enough consistent contributors, I am open to adding collaborators or maintainers to the repository. Alternatively, we can consider moving it to an organization account for more convenient sharing of work.

PS. Lastly, I want to emphasize that OrcaSlicer will stay true to its principles(open source community project)
