### ISSUE TITLE
Add back all the documentation links that BBL removed

### ISSUE THREAD

**Issue by julie777** [SoftFever/OrcaSlicer#1129]
**Describe the bug**

I am submitting this as a bug because I think this is very important!

One of the **best features** of Prusa Slicer was that every setting had a tool tip and a **link** to the **Prusa Slicer documentation** page. 
In addition `<ctrl>F` did a global search of the application to allow finding settings and preferences. 

BBL did not want to link to any Prusa web pages so they removed the links and only added links when they added something with a page on their wiki. (They actually did not want to release the source to Bambu Studio.)  They also added a new search that finds almost nothing. It has never found a setting for me.

BBL did a disservice to the users that Orca Slicer can correct.

**3mf File for This Bug**
If it is related to slicing, please append the 3mf file. It could be extremely helpful to solve the issue.

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**

**Printer model**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Windows]

**Comment by hliebscher** [comment]
@julie777  That is definitely not a bug as it is labeled. 
We have Quick Infos for all settings with mouse over and a translation for many languages
