### ISSUE TITLE
Retraction calibration

### ISSUE THREAD

**Issue by MIG003** [SoftFever/OrcaSlicer#1131]
/On orcaslicer 1.6.3 beta ,  when using  retraction tower calibration in gcode file generated  there is no "SET_RETRACTION " to change retraction length .
I use klipper
[Retraction test.zip](https://github.com/SoftFever/OrcaSlicer/files/11549107/Retraction.test.zip)

**Comment by hliebscher** [comment]
witch printer ? or profile ? can you upload your 3mf file as zip that we can reproduce?

**Comment by MIG003** [comment]
I have updated my publication whith 3mf file

**Comment by hliebscher** [comment]
its the same ... it works not with firmware retraction
at first you have to disable firmware retraction in printer settings.
than print the test 
note the value with no stinging
add the value in your printer start code or firmware retraction settings in klipper

**Comment by MIG003** [comment]
Thank you

**Comment by vaninva** [comment]
> 
Have you solved this problem about UNKNOW COMMAND G10 G11 ？
