### ISSUE TITLE
Printers not showing in list

### ISSUE THREAD

**Issue by Radbmx** [SoftFever/OrcaSlicer#1135]
When selecting the BIQU series printers in the add/remove printers section they do not actually add to my drop down after hitting confirm.  All other printers do work.

using the 1.6.3 beta pre release. on a windows 64bit computer.

**Comment by fr3ak2402** [comment]
@Radbmx 
Yes I know, the BIQU printer profiles are unfortunately not functional and I have already fixed this. The change will be implemented in the next few days.

**Comment by mydevpeeps** [comment]
Will it be in the 1.6.4 beta or was it fixed already?

**Comment by fr3ak2402** [comment]
@mydevpeeps 
has already been fixed with the BIQU printers
