### ISSUE TITLE
retraction tower error in 1.6.3 beta: Error: 53 non-manifold edges

### ISSUE THREAD

**Issue by gavntery** [SoftFever/OrcaSlicer#1136]
I just add the retraction tower from menu. And it show the error.

System: MacOS 13.3.1
OrcaSlicer Version: 1.6.3-beta

**Comment by hliebscher** [comment]
it is the same in https://github.com/SoftFever/OrcaSlicer/issues/1124

**Comment by SoftFever** [comment]
duplicated.
Close
