### ISSUE TITLE
Tree support issues @ V1.6.3 beta

### ISSUE THREAD

**Issue by astrovern64** [SoftFever/OrcaSlicer#1138]
1) When you click Slice Plate, the useful (where relevant) "Warning: It seems object X has large overhangs" message no longer appears.

2) Slicing with "tree(auto)" supports can sometimes create floating supports (see attached image & 3mf).

Printer: Bambu Lab P1P
Desktop: macOS Ventura 13.4
![jpeg-optimizer_Screenshot 2023-05-25 at 11 22 59](https://github.com/SoftFever/OrcaSlicer/assets/101368551/a6f8f81c-a49d-459f-bcbf-d01eb4178596)

[Saw Guard - Final 20230522_1700.3mf.txt](https://github.com/SoftFever/OrcaSlicer/files/11563821/Saw.Guard.-.Final.20230522_1700.3mf.txt)

**Comment by hliebscher** [comment]
it is the same in #1124
