### ISSUE TITLE
Project file does not open and produces errors

### ISSUE THREAD

**Issue by epeer** [SoftFever/OrcaSlicer#1141]
**Describe the bug**
I was working on a project with 16 plates in studio. After printing 10 plates going on to the 11th I got a error message “can’t process file” and “can’t send file to printer, internal error”
I quit studio and tried opening the project file again and got the error messages in the attached screenshots. 
Seems like the file is corrupted. 
I can still open the file with zip/rar software and I see all the stl files and images and settings files there but cannot open with studio to modify or print. 

**3mf File for This Bug**
[Clock Time Slider.zip](https://github.com/SoftFever/OrcaSlicer/files/11569522/Clock.Time.Slider.zip)
Changed the extension to .zip for upload, but it is a .3mf file

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**
![348999019_559378309646341_274650890782924434_n](https://github.com/SoftFever/OrcaSlicer/assets/5785129/bba1212f-24ac-4713-acc3-e6ce18486888)
![349640125_3523335791283691_6952910131037435733_n](https://github.com/SoftFever/OrcaSlicer/assets/5785129/c8a64b0e-6c52-4cb9-92cb-5417b13a8753)

**Printer model**
Bambu Lab X1C with AMS

**Desktop (please complete the following information):**
Windows 10 64 bit

**Comment by SoftFever** [comment]
@epeer 
Thanks for the project file, I will take a look

**Comment by SoftFever** [comment]
That's also what I found.
This bug will be fixed in 1.6.3 official release.
