### ISSUE TITLE
Trojan.Malware.300983.susgen (Surely false positive)

### ISSUE THREAD

**Issue by mm108** [SoftFever/OrcaSlicer#1144]
Pretty sure that this is a false positive but I thought that I should highlight it. And thank you for the amazing work you did with this Slicer.
![Trojan Malware 300983 susgen](https://github.com/SoftFever/OrcaSlicer/assets/10776430/fd3fe13b-7d49-40d5-b406-58c8bf2f31d3)

**Comment by SoftFever** [comment]
Thank you for reporting it.
All Orca prebuilt binaries are built on GitHub runners automatically with the CICD script. It's very unlikely infected by the virus.

**Comment by mm108** [comment]
Thank you so much. I will be closing this now as this is pretty much a case of false positive from MaxSecure. 
Cheers.
