### ISSUE TITLE
{first_layer_height} placeholder not working

### ISSUE THREAD

**Issue by Exerqtor** [SoftFever/OrcaSlicer#1148]
I've been using {first_layer_height} as part of my start G-code for ages now in both SuperSlicer and PrusaSlicer, but for some reason this placeholder don't seem to have been ported over to OrcaSlicer.

Don't know if this has been done with intent or if it's a bug, would be cool to have in anyways though!

**Comment by fr3ak2402** [comment]
This is not a bug, this parameter has a different name in OrcaSlicer.

Use this and it will work.

[initial_layer_print_height]
