### ISSUE TITLE
Option to NOT Cut Filament In AMS After Print Is Finished

### ISSUE THREAD

**Issue by djngnear** [SoftFever/OrcaSlicer#115]
**Is your feature request related to a problem? Please describe.**

I would love to have an option to keep filament loaded in the hotend after a print.  A lot of times I'd like to use the same loaded filament after a print only to have it automatically cut and unloaded.

**Describe the solution you'd like**

Maybe have the setting on the Print Plate dialog box when sending it to the printer?

**Describe alternatives you've considered**

I don't know a work around to keep it loaded in the hotend.

**Additional context**

**Comment by steven850** [comment]
You can easily do that in your printer profile. Open up the profile you want, like the 0.2mm standard profile. Then go to machine end code. And look for the following

> G1 X100 F12000 ; wipe
> ; pull back filament to AMS
> M620 S255
> G1 X20 Y50 F12000
> G1 Y-3
> T255
> G1 X65 F12000
> G1 Y265
> G1 X100 F12000 ; wipe
> M621 S255
> M104 S0 ; turn off hotend

simply delete from  M620 up to M104 so it looks like this  

> G1 X100 F12000 ; wipe
> ; pull back filament to AMS
> M104 S0 ; turn off hotend

now save the profile as 0.2mm Leave filament or something like that. So whenever you print with that profile it will leave the filament loaded at the end of the print.

**Comment by djngnear** [comment]
Thank you! I will definitely do that. I'd still like the option...
