### ISSUE TITLE
Ruler

### ISSUE THREAD

**Issue by rkarlsba** [SoftFever/OrcaSlicer#1150]
When importing a model, sometimes it could be very nice to have a ruler of sorts to measure the distance between two points. Could this be added?

**Comment by liftbag** [comment]
I vote for porting the measure tool from PrusaSlicer, where it is present starting from version 2.6.0-alpha2 and which has been further improved in apha6.

**Comment by SoftFever** [comment]
Gonna port PS 2.6 measurement tool in the future.
That should cover this use case I believe.

**Comment by ZerkerEOD** [comment]
Has this been added yet?

**Comment by cpasoft** [comment]
> Has this been added yet?

Not yet. Hopefully soon. 💪🙏

**Comment by GTreaper** [comment]
Big + on this

**Comment by EyalRotem** [comment]
@SoftFever  - is there any idea when will this be implemented?

**Comment by SoftFever** [comment]
> @SoftFever - is there any idea when will this be implemented?

I’ve put a PullRequest with the initial port.
But we changed the plan after discussing with @Noisyfox 
He will port the whole related PrusaSlicer framework so that we can port most new PS tools in one go as both of us think Prusa’s tool(cut and text) is better

**Comment by EyalRotem** [comment]
> > @SoftFever - is there any idea when will this be implemented?
> 
> I’ve put a PullRequest with the initial port. But we changed the plan after discussing with @Noisyfox He will port the whole related PrusaSlicer framework so that we can port most new PS tools in one go as both of us think Prusa’s tool(cut and text) is better

That’s great news. So it is planned for say.. the next minor release? 1.9.0?
Or possibly through 1.8.x updates?

**Comment by cpasoft** [comment]
> 
> But we changed the plan after discussing with @Noisyfox He will port the whole related PrusaSlicer framework so that we can port most new PS tools in one go as both of us think Prusa’s tool(cut and text) is better

I love that... Of course Prusa's cutting and text tools are better...

**Comment by SoftFever** [comment]
Most likely 1.9

**Comment by Noisyfox** [comment]
Here are some progress:

![image](https://github.com/SoftFever/OrcaSlicer/assets/1537155/c266e33e-e5ac-4fb5-8764-73a02d28bc6b)

![image](https://github.com/SoftFever/OrcaSlicer/assets/1537155/decced7f-7b87-4282-b97f-aa9d2d4d2122)

**Comment by xros** [comment]
> Here are some progress:
> 
> ![image](https://private-user-images.githubusercontent.com/1537155/279423641-c266e33e-e5ac-4fb5-8764-73a02d28bc6b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5NTkwMDAsIm5iZiI6MTcwMDk1ODcwMCwicGF0aCI6Ii8xNTM3MTU1LzI3OTQyMzY0MS1jMjY2ZTMzZS1lNWFjLTRmYjUtODc2NC03M2EwMmQyOGJjNmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjZUMDAzMTQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmVjMTJiYmZlOTllOWFhMmY4NjlmOTNjMDY4MDVmMzUzNTcxZmE5NTkwZDAyN2RhZTI3Y2RhNmVlOTU3ODc2MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.77nzVagGcKBkA1T9reSeRixwb4tyYrebI5uDEtWWEEk)
> 
> ![image](https://private-user-images.githubusercontent.com/1537155/279423508-decced7f-7b87-4282-b97f-aa9d2d4d2122.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5NTkwMDAsIm5iZiI6MTcwMDk1ODcwMCwicGF0aCI6Ii8xNTM3MTU1LzI3OTQyMzUwOC1kZWNjZWQ3Zi03Yjg3LTQyODItYjk3Zi1hYTlkMmQ0ZDIxMjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjZUMDAzMTQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGUzNmE5MWEwMzMyYzQ1YzdlOTlmZTVkZDVhMmY2MDI4NDg5YzQyYjk5NWRhZjQ2YjRlMjgzNGRjYmExNzI5YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.rhIdC53f1Ev2guvMMKSbADMPQBBENVsPa-B-AI8TegI)
> 
> No ETAs but I'll do as quickly as I can.

Please add the rule! This is very useful!
 Thanks. It looks so good!

**Comment by cpasoft** [comment]
> > Here are some progress:
> > ![image](https://private-user-images.githubusercontent.com/1537155/279423641-c266e33e-e5ac-4fb5-8764-73a02d28bc6b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5NTkwMDAsIm5iZiI6MTcwMDk1ODcwMCwicGF0aCI6Ii8xNTM3MTU1LzI3OTQyMzY0MS1jMjY2ZTMzZS1lNWFjLTRmYjUtODc2NC03M2EwMmQyOGJjNmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjZUMDAzMTQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmVjMTJiYmZlOTllOWFhMmY4NjlmOTNjMDY4MDVmMzUzNTcxZmE5NTkwZDAyN2RhZTI3Y2RhNmVlOTU3ODc2MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.77nzVagGcKBkA1T9reSeRixwb4tyYrebI5uDEtWWEEk)
> > ![image](https://private-user-images.githubusercontent.com/1537155/279423508-decced7f-7b87-4282-b97f-aa9d2d4d2122.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5NTkwMDAsIm5iZiI6MTcwMDk1ODcwMCwicGF0aCI6Ii8xNTM3MTU1LzI3OTQyMzUwOC1kZWNjZWQ3Zi03Yjg3LTQyODItYjk3Zi1hYTlkMmQ0ZDIxMjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjZUMDAzMTQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGUzNmE5MWEwMzMyYzQ1YzdlOTlmZTVkZDVhMmY2MDI4NDg5YzQyYjk5NWRhZjQ2YjRlMjgzNGRjYmExNzI5YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.rhIdC53f1Ev2guvMMKSbADMPQBBENVsPa-B-AI8TegI)
> > No ETAs but I'll do as quickly as I can.
> 
> Please add the rule! This is very useful! Thanks. It looks so good!

It is already added. It will be avaliable on next release, or you just download the last nightly.

**Comment by xros** [comment]
> > > Here are some progress:
> > > ![image](https://private-user-images.githubusercontent.com/1537155/279423641-c266e33e-e5ac-4fb5-8764-73a02d28bc6b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5NTkwMDAsIm5iZiI6MTcwMDk1ODcwMCwicGF0aCI6Ii8xNTM3MTU1LzI3OTQyMzY0MS1jMjY2ZTMzZS1lNWFjLTRmYjUtODc2NC03M2EwMmQyOGJjNmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjZUMDAzMTQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmVjMTJiYmZlOTllOWFhMmY4NjlmOTNjMDY4MDVmMzUzNTcxZmE5NTkwZDAyN2RhZTI3Y2RhNmVlOTU3ODc2MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.77nzVagGcKBkA1T9reSeRixwb4tyYrebI5uDEtWWEEk)
> > > ![image](https://private-user-images.githubusercontent.com/1537155/279423508-decced7f-7b87-4282-b97f-aa9d2d4d2122.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5NTkwMDAsIm5iZiI6MTcwMDk1ODcwMCwicGF0aCI6Ii8xNTM3MTU1LzI3OTQyMzUwOC1kZWNjZWQ3Zi03Yjg3LTQyODItYjk3Zi1hYTlkMmQ0ZDIxMjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjZUMDAzMTQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGUzNmE5MWEwMzMyYzQ1YzdlOTlmZTVkZDVhMmY2MDI4NDg5YzQyYjk5NWRhZjQ2YjRlMjgzNGRjYmExNzI5YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.rhIdC53f1Ev2guvMMKSbADMPQBBENVsPa-B-AI8TegI)
> > > No ETAs but I'll do as quickly as I can.
> > 
> > 
> > Please add the rule! This is very useful! Thanks. It looks so good!
> 
> It is already added. It will be avaliable on next release, or you just download the last nightly.

Thanks I will download the nightly build now. :) wonderful

**Comment by Noisyfox** [comment]
It will be in 1.9

**Comment by ajaytanna** [comment]
Thank you very much.

**Comment by samstone86** [comment]
Is it available from nightly build ?

**Comment by Noisyfox** [comment]
> Is it available from nightly build ?

yes

**Comment by stef1949** [comment]
> > Is it available from nightly build ?
> 
> yes

YIPEEEE :3
