### ISSUE TITLE
Option to do outer wall first, except for when there's an overhang?

### ISSUE THREAD

**Issue by mathewsamueldesign** [SoftFever/OrcaSlicer#1152]
I am trying to get better outer wall quality. Many people say printing the outer wall first is better for quality, but there's the issue with overhangs and printing in thin air. Is it possible to add an option where it prints outer walls first, except for when there's an overhang? When there's an overhang, it's probably better to print inner first.

**Comment by liftbag** [comment]
It could be a good idea, even if I fear that a different finish between the two areas could be highlighted.

**Comment by SoftFever** [comment]
My immediate thought is:
We will have to split the outer perimeters many times to perform such switch operations.
That will result in creating many many extra z seams @_@

**Comment by RaphiSpoerri** [comment]
Can we reopen this issue? I really want this feature.

**Comment by RaphiSpoerri** [comment]
@SoftFever 


> My immediate thought is: We will have to split the outer perimeters many times to perform such switch operations. That will result in creating many many extra z seams @_@

We could avoid that problem by printing the entire layer with the inner walls first if the layer contains any overhangs above a given threshold angle.
