### ISSUE TITLE
Aligned seams aren't aligned... and why is there no 'corner priority' option? 

### ISSUE THREAD

**Issue by nirurin** [SoftFever/OrcaSlicer#1154]
As you can see, this is set to be aligned, but the seams are all over the place. 
If I change to 'back' it then aligns the seam into a single corner... which makes me wonder why aligned doesn't do the same thing? 
Do some options prioritise corners, while others don't? 
If so, why isn't there an "aligned-corner" option, when that's the option that people use 99% of the time? 

![Screenshot 2023-05-27 231533](https://github.com/SoftFever/OrcaSlicer/assets/3751273/a73cca56-9cd7-4c3f-9bfb-bfdcef02d5fc)
 
[Paladins-Io-Bow V2Arm_Skeleton.zip](https://github.com/SoftFever/OrcaSlicer/files/11583126/Paladins-Io-Bow.V2Arm_Skeleton.zip)

**Comment by SoftFever** [comment]
`Aligned` has corner priority by default.
In your case, you are using negative parts to cut the part, which confused the seam placement algo(it's potentially a bug still)

I suggest using the cut tool as a workaround:
![image](https://github.com/SoftFever/OrcaSlicer/assets/103989404/2b85fc1c-e932-4ae4-ad53-df7bc0c8eb66)

**Comment by nirurin** [comment]
Ahh ok I see. I thought the cut tool could only do horizontal cuts not vertical ones. I'll give it a try
