### ISSUE TITLE
Nozzle Temperature Control

### ISSUE THREAD

**Issue by TechDude23** [SoftFever/OrcaSlicer#1163]
We need a way to change the nozzle temperature with speed changes or layer height.

[Matte to Glossy Shift](https://forum.bambulab.com/t/matte-glossy-pla-shift/14428?u=3dtech )

Custom G-code works but we should have an easy orca slicer solution.

Bambu Lab & others high speed printers.

All OS
1.6.3 Beta 

Temperature layer control 
![Temp control](https://github.com/SoftFever/OrcaSlicer/assets/128856354/20df4a94-d750-4ce6-8f7a-23604f23d42b)

**Comment by julie777** [comment]
Does the height modifier allow changing temp?

**Comment by TechDude23** [comment]
Hi Julie777, Yes it can be done by layer # or in mm using custom G-code in Orca if the Orca team can do something like the sample above by layer number or in mm height then you would have better control of the nozzle and bed temps. 

I will put some G-code samples up on Bambu community forum so we will have something for now to use :)

**Comment by knw257** [comment]
I'd like this feature added because the built-in temperature tower in Orca has a base that's a bit too small, and keeps getting knocked over during printing, so I'd like an easy way to use alternative temperature towers and easily be able to set the nozzle temp per layer

**Comment by straccio** [comment]
Hi to all. I'm interested in these kind of control.
I think that type of control must be made through volumetric change at temperature.

The need to increase the temperature of the nozzle is needed by high flow request to maintain "fluid" the material.

I immagine a test based on flow rate at different temperatures in order to have some fixed points of the curve and have a function that adapt the temperature of the nozzle on flow request.

**Comment by Buzut** [comment]
I’d say this is even more needed to fight heat creep when flow is greatly reduced (bridging, overhang, ironing).

if we can’t get an automatic feature based on flow rate, considering adding it in the height range modifier would already by a huge life saver.

**Comment by sb53systems** [comment]
Hi all,  
Here's a script created to prove the effectiveness of an automatic solution to this common problem..  
  
https://github.com/sb53systems/G-Code-Flow-Temperature-Controller  
  
I hope the Slicers will incorporate an equivalent solution!  
Happy smart 3D Printing.

**Comment by carlosjln** [comment]
Right now I'm needing this feature to set a temp override within a height range modifier where only for this portion I've set faster printing speed for the inner perimeters and would benefit from improved flow.
