### ISSUE TITLE
icon missing in Windows system

### ISSUE THREAD

**Issue by botio** [SoftFever/OrcaSlicer#1173]
**Describe the bug**
Keeping showing error windows about the icon missing after I turned the one drive sync down for good, even though I reinstalled for many times with deleting /Appdata/roaming/orcaslicer

**3mf File for This Bug**
not related

**To Reproduce**
just reopen the app

**Expected behavior**
tell me how to reinstall correctly. Thank you

**Screenshots**
<img width="434" alt="2023-05-29 124735" src="https://github.com/SoftFever/OrcaSlicer/assets/4170675/7cf75870-4502-4431-a397-92f58b372f51">

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by SoftFever** [comment]
@botio 
Could you please try extracting OrcaSlicer to a regular directory (not in OneDrive) and try it again?

**Comment by botio** [comment]
I did extract the folder on Desktop or Downloads (which is not in OneDrive) for sure. 

Just don't understand why even I redo the extraction at a different location still jumps out the error windows, even though I did delete everything in /Appdata/roaming/orcaslicer

**Comment by hliebscher** [comment]
@botio 
Desktop and Downloads are shared in OneDrive

**Comment by botio** [comment]
I did say I have turned the OneDrive down, and it still shows the error window right? In the "Describe the bug" part?

**Comment by botio** [comment]
okay, find the way to fix it just by dragging the folder to D: .... wish there is a way to do the clean uninstalling.
