### ISSUE TITLE
Texture for print bed is offset (still)

### ISSUE THREAD

**Issue by Otann** [SoftFever/OrcaSlicer#1175]
**Describe the bug**
When I load the texture for the print bed, the coordinate arrows are offset

**To Reproduce**
- Create the printer with a square bed (Voron 2.4 350x350 in my case)
- Load a square texture (1750x1750 px)

**Expected behavior**
- The coordinates start at the corner of the texture
- Like it does in PrusaSlicer
<img width="336" alt="Screenshot 2023-05-29 at 13 25 37" src="https://github.com/SoftFever/OrcaSlicer/assets/683786/9093e51e-3f93-4f71-89c0-31a2048ebbdb">

**Screenshots**
<img width="444" alt="Screenshot 2023-05-29 at 13 25 47" src="https://github.com/SoftFever/OrcaSlicer/assets/683786/fca4c22b-9e99-48df-8f2d-2b25fab44de6">

<img width="727" alt="Screenshot 2023-05-29 at 13 26 49" src="https://github.com/SoftFever/OrcaSlicer/assets/683786/34004344-cbfb-4bb4-9f13-84f45145754a">

**Desktop (please complete the following information):**
 - OS: MacOS 12.6.1
 - Version 1.6.3

**Comment by SoftFever** [comment]
@Otann 
Can you shared the texture? I can't repro with my texture(and the default Voron texture)

**Comment by Otann** [comment]
of course

![Voron 350x350](https://github.com/SoftFever/OrcaSlicer/assets/683786/24220452-47fe-4400-9c5f-6d657d68e444)

**Comment by yourbuddydinec** [comment]
Same thing is happening to me with a custom image and seems the exact same offset in the y axis.

**Comment by clovisd** [comment]
I'm able to see the custom Print Bed on my AMD Radeon GPU, however my scaling appears broken / offset.

Examples between Orca Slicer & Prusa Slicer with the same STL and bed SVG:
![image](https://github.com/SoftFever/OrcaSlicer/assets/1336589/823b3c09-4502-4ff4-8b32-46692529a4db)
![image](https://github.com/SoftFever/OrcaSlicer/assets/1336589/f73a7640-26db-459b-92f8-c998f6444e2d)

On the latest version of Orca Slicer vs latest version of Prusa Slicer.

**Comment by clovisd** [comment]
This ticket also seems to show the offset issue with the XYZ green/blue/red arrows: https://github.com/SoftFever/OrcaSlicer/issues/1463

**Comment by kluupom** [comment]
Same Here,
Bed is off, and in Addition no Textures work, so it is always as shown in [https://github.com/SoftFever/OrcaSlicer/issues/1463](#1643)
Just a Black Bed :(

**Comment by Otann** [comment]
I believe this is still an issue. Should we just keep commenting here to provide an activity for github bot?

**Comment by yourbuddydinec** [comment]
Yeah. Would be nice to get it fixed but I'm sure its low on the priority list. But good idea to keep letting em know it's still an issue

**Comment by SoftFever** [comment]
Confirmed it's a bug

**Comment by SoftFever** [comment]
Fixed in main branch.
![image](https://github.com/SoftFever/OrcaSlicer/assets/103989404/6cb476b0-6d84-4126-9001-346f0d955803)

The fix should be included in nightly build in about an hour from now: https://github.com/SoftFever/OrcaSlicer/releases/tag/nightly-builds

**Comment by Otann** [comment]
@SoftFever a hero! a legend!
