### ISSUE TITLE
Network plugin problem

### ISSUE THREAD

**Issue by paajuf** [SoftFever/OrcaSlicer#1178]
**Is your feature request related to a problem? Please describe.**
After unzip 1.6.3 orca-slicer and start app.. -> Problem with download plugin
**Describe the solution you'd like**
Can help with this problem ? 

WINDOWS 11 64
1.6.2 working without any problems .. 
![network plugin ](https://github.com/SoftFever/OrcaSlicer/assets/134946474/249e4df3-a6a7-4783-93ca-7855c9ab1a47)

**Comment by mikedixonphoto** [comment]
> Having the same issues.... Found a workaround.

Well, care to share what the workaround was? I'm having the same problem, even after going back to 1.6.2

**Comment by ccollinscj** [comment]
> > Having the same issues.... Found a workaround.
> 
> Well, care to share what the workaround was? I'm having the same problem, even after going back to 1.6.2

Yes,  I have the latest Bambu Slicer install 1.6.2.4  I simply copy the C:\Users\{your user name }\AppData\Roaming\BambuStudio\plugins to C:\Users\{your user name}\AppData\Roaming\OrcaSlicer\plugins which over wrote the bambu_network.dll and bambusource .dll which are newer dll's 4/26/2023.
