### ISSUE TITLE
[Feature Request]: Submit OrcaSlicer to Winget Repository

### ISSUE THREAD

**Issue by kylek29** [SoftFever/OrcaSlicer#1179]
**Describe the solution you'd like**
Winget is Microsoft's version of an application repository and is growing in usage (I believe it's installed by default on Win11+), it brings the simplicity of Linux's "apt/yum" command to download/install/rollback to the Windows OS. Along with that is a streamlined update process via the Winget update manager and user tools like WingetUI ( https://github.com/marticliment/WingetUI ).

**Additional context**
This would simplify the update procedure for end users so they can maintain the latest version of the slicer across different channels (stable, beta). Integration is normally simple (create manifest and push it to the Winget repository) and once published, can probably be automated in the Github CI/CD pipeline for new releases.

Package Manager Information:

- https://github.com/microsoft/winget-pkgs
- https://learn.microsoft.com/en-us/windows/package-manager/package/

**Comment by SheepCommander** [comment]
huh

**Comment by robertbaker** [comment]
please reopen or keep my issue open
