### ISSUE TITLE
Lost HALF USER Filament and USER presets 

### ISSUE THREAD

**Issue by Tyler8299** [SoftFever/OrcaSlicer#1185]
Machines show up as expected
I found the machine and filament user presets in appdata folder but when i import the json folders it seems to do nothing. 
![Screenshot 2023-05-29 162858](https://github.com/SoftFever/OrcaSlicer/assets/121695166/ee4dea3e-fe41-48d8-b793-db831507a534)
![Screenshot 2023-05-29 162922](https://github.com/SoftFever/OrcaSlicer/assets/121695166/99b859b0-821e-4bb3-a5c1-167cf2c757a1)

**Comment by Tyler8299** [comment]
Logging out and back in, Rolling back to BETA did not help. seems my worse fear is always the user presets when upgrading.

**Comment by fr3ak2402** [comment]
Look here: #1182
