### ISSUE TITLE
auto Fix non-manifold issues 

### ISSUE THREAD

**Issue by cameronaaron** [SoftFever/OrcaSlicer#1188]
Is your feature request related to a problem? Please describe.
I have a .stl file which reports this (see report below) when opening in Studio

Describe the solution you'd like
I have an iMac / MacOS system - can you transfers the possibilty to fix the model from Windows to MAC version ?

Describe alternatives you've considered
Blender or Meshlab, but I don't want to get into that, ...complicated..

![230539051-af7c331c-6825-4f2f-aadf-048af3481353-1](https://github.com/SoftFever/OrcaSlicer/assets/5474198/db853a35-64e7-4380-9b55-60d2a036be11)

**Comment by SoftFever** [comment]
It's bad to rely on Windows service to repair a model.
Will move back to Netfabb (the one that PrusaSlicer uses) in the future.
