### ISSUE TITLE
Height range modifiers are not saved

### ISSUE THREAD

**Issue by lhndo** [SoftFever/OrcaSlicer#1195]
**Describe the bug**
Height range modifiers are not saved with the project

**To Reproduce**
Add a height range modifier with some changes, save the project and reload.
Height range modifiers are missing

**Desktop:**
 - OS: Windows 10

**Comment by julie777** [comment]
I reported this to Bambu Studio shortly after they released the feature.

**Comment by jlew715** [comment]
Same issue here. Really frustrating to have to recreate the height range modifiers each time you re-open a project!

**Comment by cpasoft** [comment]
Confirmed

**Comment by chenrongyu** [comment]
same issue!!  this is a big problem for me, hope this bug will be fixed soon

**Comment by jbeardon** [comment]
Same issue and it's a real pain as I use height range modifiers a lot - this has been fixed in Bambu studio

**Comment by nordurljosahvida** [comment]
same issue on win11 1.6.3

**Comment by cpasoft** [comment]
This was solved a long time ago. Please close!
