### ISSUE TITLE
Wiki link broken

### ISSUE THREAD

**Issue by julie777** [SoftFever/OrcaSlicer#1196]
**Describe the bug**
On the wiki home page the link to "how to build orca slicer" is broken.

**3mf File for This Bug**
If it is related to slicing, please append the 3mf file. It could be extremely helpful to solve the issue.

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**

**Printer model**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Windows]

**Comment by hliebscher** [comment]
@julie777 
As a developer, you can easily make the necessary adjustments by modifying the file https://github.com/SoftFever/OrcaSlicer/blob/main/doc/Home.md and creating a pull request (PR). That would be a first step. Similarly, there is a lot of unnecessary text in the bug report, as I have described before. If you are not comfortable doing it yourself, we can work on it together.
