### ISSUE TITLE
Hi, so i switched from cura to orcaslicer with my ender 3s1. but sice the 1.6.3 version released there is a layershift at always the same hight. when i use cura thzere isn't so there has to be a bug in the slicer 

### ISSUE THREAD

**Issue by Nefnief-tech** [SoftFever/OrcaSlicer#1214]
**Describe the bug**

**3mf File for This Bug**
If it is related to slicing, please append the 3mf file. It could be extremely helpful to solve the issue.

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**

**Printer model**

**Desktop (please complete the following information):**
[3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/11617021/3mf.zip)

 - OS: [e.g. iOS, Windows]

**Comment by DKS-18** [comment]
more than likely it is either the acceleration settings in orca slicer are too high for your printer or the z hop isn't enabled or is a value too small that is causing the print head to clip the print and have a layer shift

**Comment by PhilBaz** [comment]
@Nefnief-tech 

Yes, this is most likely not a slicer bug. But rather you have either a part of the print that's curling and catching the nozzle, or you have instructed Orca to outrun what your motors are capable of and are getting lost steps.

You should close this issue.
