### ISSUE TITLE
OverHang Speed Issue when using 'Classic' Wall Mode

### ISSUE THREAD

**Issue by ProjectKerr** [SoftFever/OrcaSlicer#1217]
Using Bambu P1P Printer - Issue only apparent on latest release of OrcaSlicer 

Using 'Classic' Wall Generator I get a weird Slow Down leading up to Overhangs, Disappears If I change to 'Arachne' or turn off 'Slow down for overhangs' 
First pic is Orcaclicer
Second Pic is BambuSlicer (same settings)
![Orca-Slicer](https://github.com/SoftFever/OrcaSlicer/assets/135166623/69c3bd99-0311-4a5c-b2af-785c71107325)
![BS](https://github.com/SoftFever/OrcaSlicer/assets/135166623/cd1aa283-60f1-4f6a-bf8b-90c753f88bf4)

**Comment by cpasoft** [comment]
I confirm this... 
![imagen](https://github.com/SoftFever/OrcaSlicer/assets/29692062/04737636-5871-4481-badb-1619dc37c825)

Also, if you set the classic mode on the overhang speed section, something more weird happens...
![imagen](https://github.com/SoftFever/OrcaSlicer/assets/29692062/ae709a87-2b39-4641-9a26-b09013951bda)

**Comment by cpasoft** [comment]
The same with arachnee and classic mode on
![imagen](https://github.com/SoftFever/OrcaSlicer/assets/29692062/010f70f3-3491-4bd5-8b49-7b015cf199e1)
