### ISSUE TITLE
Program crashes when trying to slice with a raft

### ISSUE THREAD

**Issue by jthe111** [SoftFever/OrcaSlicer#1221]
**Describe the bug**
As the title describes, when trying to slice any files (both simple geometries and complex geometries) with a raft, the program just crashes right to desktop. It will slice up to 50% completed then crash. Sometimes it will throw up a "Access Permission" error and sometimes it crashes right to desktop.

**3mf File for This Bug**
Happens on various files. I have sliced various versions of cinderwings crystal dragons and a MTG boulder deck case since updating. This issued was never present on 1.6.2

**To Reproduce**
Grab a file, add any number of raft layers and various raft spacing options. It will commence to slice but then it will crash.

**Expected behavior**
No crash and a sliced file ready for importing to my printer 

**Screenshots**

**Printer model**
Ender 3 base (all metal extruder and stock hotend)

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Version [1.6.3]

**Comment by alldaywarrior** [comment]
same here #1260

**Comment by viruz82** [comment]
This already exists in 1.6.3-beta.

**Comment by Targolo** [comment]
Hi,

Same thing for me on most of the projects when I add a raft. I have a P1P and I am using the BBL 0.2mm standard profile + raft.
I've tried on Orca Slicer 1.6.3 and also on version 1.6.2.4 and 1.6.0 of Bambu Studio.
Attached is a sample project.
[Arms.zip](https://github.com/SoftFever/OrcaSlicer/files/11796729/Arms.zip)

**Comment by Mr-Jay-420** [comment]
same here.

**Comment by HunterG6700** [comment]
Same here
