### ISSUE TITLE
Calibration Parts (PA Test) not working for RepRap Firmware (RRF)

### ISSUE THREAD

**Issue by ChristianReil** [SoftFever/OrcaSlicer#1228]
The PA Test is not working für RRF, because the Command M900 K??? is not supportet in RRF. Use M572 S??? instead! 

![image](https://github.com/SoftFever/OrcaSlicer/assets/91415917/80df4431-0e82-4135-9f8b-ad8976cd6bb8)

![image](https://github.com/SoftFever/OrcaSlicer/assets/91415917/ce95faa0-7f8f-45dd-a592-e7e7c6ab1e14)

Thank you a lot! :-)

**Comment by ChristianReil** [comment]
Any Chance to fix this?

**Comment by VrtlBrown** [comment]
I'm also finding this problem for the temp calibration, the g-code is not produced to change temperatures and instead prints the entire tower at one temperature. Switching the g-code flavour between RepRap and Marlin changes this behaviour.

Can this be fixed, for us Duet users?

**Comment by ChristianReil** [comment]
I hope there would be a solution :-)

**Comment by vminkov73** [comment]
Prusa MK4 IS, Prusa MINI, Prusa XL  , all Prusa models with buddy boards , have the same issue 
M900 Kxxx is not supported and replaced with M572 Sxxx
