### ISSUE TITLE
Share filament across printers

### ISSUE THREAD

**Issue by jonathanalevi** [SoftFever/OrcaSlicer#1230]
When I add a filament, I should have the option to make that filament profile available to all printers. Right now, it only adds them per printer. There should be a way to detach it.

**Comment by jonathanalevi** [comment]
(Currently, I cannot use my filament profiles except with one printer!)

**Comment by KennyVB** [comment]
make this please! having multiple printes sucks when having a lot of filament names in spoolman etc.
