### ISSUE TITLE
Slicer crashing whenever I try to slice a file

### ISSUE THREAD

**Issue by manoelbgn** [SoftFever/OrcaSlicer#1231]
**Describe the bug**
Since I update to version 1.6.3, whenever I try to slice a file the app crash with a message "A fatal error ocurred. Divided by zero" and the slicer closes

**3mf File for This Bug**
There is no 3mf since this bug happens before the slice finish

**To Reproduce**
1. Open the app;
2. Add a file on table;
3. Select to Slice;

**Expected behavior**
The file should be sliced and I should be able to see the preview;

**Screenshots**
![image](https://github.com/SoftFever/OrcaSlicer/assets/19255406/02791118-ad1a-4dcc-9905-c8974f4239a0)

**Printer model**
Kingroon KP3S

**Desktop:**
 - Alienware m15 R7
 - OS: Windows 11
 - Version 22H2

**Comment by alldaywarrior** [comment]
Got the same problem #1260
