### ISSUE TITLE
OrcaSlicer worse quality than BambuStudio with same settings

### ISSUE THREAD

**Issue by Photogad** [SoftFever/OrcaSlicer#1235]
**Describe the bug**
Recently my print quality suffered (previous good prints with Orca) and the only thing much I changed recently was updating Orca to the latest release 1.6.3-BETA. I decided to run a side-by-side OrcaCube sliced in Orca and BambuStudioto see if it was slicer problem or something else.
To my surprise, for some reason BambuStudio does much better quality on walls than Orca, even with exact same settings and profiles (Bambu default profiles). Yes, I adjusted the Bambu Studio to enable Arachne (like in Orca). Aside from enable arachne in Bambu Studio, all other profile settings are Bambu defaults.

**To Reproduce**
1. Slice in OrcaSlicer using default Bambu profiles for the X1 Carbon. Print.
2. Slice in BambuStudio using default Bambu profiles for X1 Carbon, but enable Arachne. Print.

**Expected behavior**
The prints should look very much the same, not different.

**Screenshots**
![20230601_114735](https://github.com/SoftFever/OrcaSlicer/assets/18505956/3ad964d1-bad2-49a7-afbc-4f30b46eeb5a)
![20230531_200026](https://github.com/SoftFever/OrcaSlicer/assets/18505956/af9bbb11-bb7e-4580-a989-69bfd7e0daec)

**Printer model**
bambu x1 carbon

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 1.6.3-BETA
 
 **EDIT: I just noticed 3 days ago OrcaSlicer released 1.6.3 official, not  BETA. I will update again and hope maybe this was just a problem with the beta version; however I don't see any fixes listed in the update notes that would affect this.**

**Comment by Photogad** [comment]
I just noticed 3 days ago OrcaSlicer released 1.6.3 official, not BETA. I will update again and hope maybe this was just a problem with the beta version; however I don't see any fixes listed in the update notes that would affect this.
Running another test print now with the 1.6.3 official release, deleted the beta.

**Comment by Photogad** [comment]
While my next test print is printing, I wonder if any of the following scenarios can apply:

1. Because I am using Arachne, is it possible that the cooling settings for Arachne is Bambu Studio are better than the OrcaSlicer version? The "Slow Down for Overhangs" if I remember correctly, originally were disabled in Bambu Studio and were not an option, @SoftFever added it first to OrcaSlicer, and then BambuStudio copied him and added it to their slicer, but I wonder if maybe they did some further optimizations?

2. Although I am using the default Bambu Profiles for bother Slicers, I wonder if perhaps there are some specific OrcaSlicer settings that don't exist in Bambu Studio that are affecting the quality. Example:  There are some speed settings in OrcaSlicer that don't exist in BambuStudio, how did OrcaSlicer determine what the defaults should be for those?

**Comment by RaySajuuk** [comment]
Same here.

However, I contacted support with the generic 3mf file and pictures of the line artifacts.
I then got a file from them to print and take pictures. Three rectangular towers near each lead screw.
And they told me it is normal nothing wrong with the machine.
