### ISSUE TITLE
Option(s) to disable gap infill completely (top surface, bottom surface, infill, and all other)

### ISSUE THREAD

**Issue by rlabusiness** [SoftFever/OrcaSlicer#124]
**Is your feature request related to a problem? Please describe.**
My top surfaces are very smooth and flat... until the printer hits the gcode to lay down gap infill after printing the normal solid infill. I've gotten around this for non-top surfaces by setting a non-zero number in "Strength > Infill > Filter out tiny gaps", but the top surface is still gap-infilled.

**Describe the solution you'd like**
Checkboxes to enable/disable gap fill for top, bottom, infill, and all other layers independently

**Describe alternatives you've considered**
I've tried to get around this by setting gap infill speed to 0, but it didn't seem to work. I can't seem to find a solution.

**Additional context**
Screenshots attached. The gap infill is shown as tiny white lines at the edge of the red "top surface".

<img width="403" alt="Screen Shot 2023-01-05 at 10 18 26 PM" src="https://user-images.githubusercontent.com/6774974/210935662-477c0586-7ca6-4b67-8f0d-efb95a132762.png">

<img width="1552" alt="Screen Shot 2023-01-05 at 10 13 40 PM" src="https://user-images.githubusercontent.com/6774974/210935696-2cc2980c-2845-4b4a-99b7-58c528036052.png">

**Comment by The-Futur1st** [comment]
You can try Monotonic infill instead of Monotonic line.
