### ISSUE TITLE
Decopling the first solid fill after a sparse infill speed and bridge speed

### ISSUE THREAD

**Issue by cpasoft** [SoftFever/OrcaSlicer#1240]
Now, if you have the slow down for overhangs feature enabled, the first layer of solid fill after a sparse fill is marked as a bridge and printed at that speed, which is too slow.

It would be better to have a different speed for this type of layer.

For example, in this piece:
![imagen](https://github.com/SoftFever/OrcaSlicer/assets/29692062/da3ef7a7-7acf-4a2e-a665-7b83dd06f12a)

The next layer is an authentic bridge, and the speed is right (10mm/s)
![imagen](https://github.com/SoftFever/OrcaSlicer/assets/29692062/1f1fdfeb-c3c7-465d-be6c-70c7654eb453)

But now, after the sparse fill, the next layer is detected as a bridge as well...
![imagen](https://github.com/SoftFever/OrcaSlicer/assets/29692062/38ca28ad-816c-4bc0-b33a-cfed420e0e43)

And printed at 10mm/s, which is very slow for this kind of layer...
![imagen](https://github.com/SoftFever/OrcaSlicer/assets/29692062/07823b8f-0e2f-492c-88e9-4e9a4aefd94c)

**Comment by Annuit20** [comment]
Jup that slow down for no reason imo.
At SuperSlicer it's called "internal bridge infill" and it use same angle and speed as solid infill.

**Comment by cpasoft** [comment]
> Jup that slow down for no reason imo. At SuperSlicer it's called "internal bridge infill" and it use same angle and speed as solid infill.

It's better to have a different speed, because if the infill is very sparse, "small bridges" are formed, but obviously smaller than a real bridge. This is why is better a different speed than the solid infill speed...

**Comment by Annuit20** [comment]
Yeah tbh I just look up my SS speeds but in SS you can set a different speed for these: internal bridges speed.

**Comment by cpasoft** [comment]
This was already implemented
