### ISSUE TITLE
slicer changes one layer to a single wall

### ISSUE THREAD

**Issue by julie777** [SoftFever/OrcaSlicer#1245]
I am not sure it this is a bug, or a failure to understand something on my part. I do know that it seems very strange.

At one point in the preview the line width changes to be the entire width of the object wall thickness. I have simulated the G code and the layer below and the layer above both have two walls and they are the same width. The model wall is always the same thickness.

![image](https://github.com/SoftFever/OrcaSlicer/assets/5090005/153246c5-7966-458b-bbaf-ee59af59b840)

In addition, I cut the object and removed all of the other plates to be able to provide the simplest illustration of the issue. The cut succeeded with no errors. Slicing had no errors. But when I switch back to preview the non-manifold error shows up. If I repair it then the slicer does not create the single perimeter layer. 

I just left the non-manifold in the project as it does not affect the issue that I am reporting, and you might want to see why the horizontal cut produced the non-manifold shape.

Even stranger, I just removed the last extra object from the project and now the non-manifold error is gone.

Just remove the extra zip suffix.
[bad layer.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/11629843/bad.layer.3mf.zip)

**Comment by Menaxerius** [comment]
I've experience the same with this File: 
Even worse, I get entire missing layers. 
![image](https://github.com/SoftFever/OrcaSlicer/assets/25470894/1327ae01-f444-4478-b74f-93e19c50cd81)
No Problem with Bambu Studio. 
Thats the File: 
[Y-Splitter.zip](https://github.com/SoftFever/OrcaSlicer/files/11673579/Y-Splitter.zip)
Note: I've Resized it via Orca to 91%, not sure if that might be part of the reason.
