### ISSUE TITLE
Generating Gcode Preview

### ISSUE THREAD

**Issue by leezoneline** [SoftFever/OrcaSlicer#1247]
**Is your feature request related to a problem? Please describe.**
In the latest version of Prusa Slicer, there's a feature called G-code thumbnails which can generate costum size of thumbnails of the G-code and preview that on File Explorer or some printers.
**Describe the solution you'd like**
There's an python script on https://github.com/mriscoc/Ender3V2S1/wiki/How-to-generate-a-gcode-preview can make old versions of Prusa Slicer to generate thumbnails. I hope that can work but it cannot use in Orca Slicer.
**Describe alternatives you've considered**
This feature can define the size and fomarts of thumbnails.
**Additional context**
![image](https://github.com/SoftFever/OrcaSlicer/assets/122147135/9722045f-0ee4-4a14-9752-19f1ee861e22)
This is the similar result that i want to have in Orca Slicer.

**Comment by GiuseppeSiragusa** [comment]
FOR ELEGOO GIGA SIDE?

**Comment by leezoneline** [comment]
> FOR ELEGOO GIGA SIDE?
> 

For creality ender3
