### ISSUE TITLE
Orca Slicer spontaneously turns off dark mode

### ISSUE THREAD

**Issue by julie777** [SoftFever/OrcaSlicer#1250]
**Describe the bug**

I have had this happen a couple times now. I have no idea what is causing it. I just walked back from the printer and found it looking strange and terrible. I checked preferences and dark mode was off.

I will try to find a way to reproduce it.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 1.6.3

**Comment by julie777** [comment]
I was in the process of creating an issue describing how terrible the UI looks when dark mode is off and went back and turned it off to do a screen capture. It looked fine.

So, even though somehow the preference had automatically switched showing that dark mode was off, the display was not back in light mode. Instead it was in what looked like a color inverted dark mode. This made it mostly black and white and hard to look at. For example, in the settings panel, all the value fields had a black rectangle for the background.

**Comment by netweaver1970** [comment]
Happened to me as well. To me, it was (most likely) after a full hibernate + subsequent come-back of the laptop (Win10, Intel embedded video chip + extra nvidia graphics chip)

**Comment by Splitpulse** [comment]
I can also say this happened to me. It seems to be when theirs a refresh from sleep mode, another installation, or randomly being on other apps.

**Comment by beamonster** [comment]
Same here. Windows 10. Orca Sliver 1.6.3. I noticed this bug long ago on Bambu Slicer. Seems to mostly occur after waking up from sleep or hibernation.

**Comment by julie777** [comment]
I have sleep disabled. I also have hibernate turned off when plugged in, which is almost all the time. I cannot recall what the conditions were when it last happened to me.

**Comment by jwyse** [comment]
Bump to remove the stale tag; I'd really love to see this issue addressed.  Thanks.

**Comment by jwyse** [comment]
Bump to remove stale tag.
