### ISSUE TITLE
Klipper: Unknown command G3 & G17

### ISSUE THREAD

**Issue by djeZo888** [SoftFever/OrcaSlicer#1253]
I have used OrcaSlicer to slice some print model for custom Klipper modded printer. The print came out just fine, but I was getting bunch of:

`
...
Unknown command:"G3"
Unknown command:"G17"
...
`

Is this a problem, a setting I should enable/disable when slicing?
Thanks

**Comment by hliebscher** [comment]
Have you the latest version and enable Arc support?

**Comment by djeZo888** [comment]
Arc fitting is disabled - that is default Klipper profile in OrcaSlicer.

**Comment by djeZo888** [comment]
Oh, I just found this comment on reddit:

`Regarding the G3/G17 gcode, there are two solutions: 1. Enable gcode_arcs in klipper config. 2. Change Z Hop type to normal (spiral uses G3 I believe).`

And one of the big reasons for using OrcaSlicer is Spiral Z Hop - I have it enabled. So I have to make sure that my klipper supports these commands.

**Comment by tehbiga** [comment]
I'm having this same issue after just switching to Orca Slicer and realized even with Z Hop set to `Normal` it uses arcs when I have arc fitting disabled. I considered just enabling arc support in Klipper, but then realized it's just Orca still doing arc based Z Hop when set to `Normal`.

I don't want Z Hop anyway so I just set the distance to zero and it stopped generating g-code for hops.

**Comment by danshoop** [comment]
Issue persists. Should be reopened.

**Comment by guilhermepozo** [comment]
same here, G3 command everytime

**Comment by oernster** [comment]
Looked up klipper gcodes: here you are...

[gcode_arcs]
The following standard G-Code commands are available if a gcode_arcs config section is enabled:

Arc Move Clockwise (G2), Arc Move Counter-clockwise (G3): G2|G3 [X<pos>] [Y<pos>] [Z<pos>] [E<pos>] [F<speed>] I<value> J<value>|I<value> K<value>|J<value> K<value>
Arc Plane Select: G17 (XY plane), G18 (XZ plane), G19 (YZ plane)

**Comment by gfBarreto** [comment]
Provavelmente já encontraram a solução, mas resolvi informar que estava tendo o mesmo erro aqui...
Lembrei que foi depois de ajustar no orca, em retração, deixei em auto e provavelmente estava fazendo movimentos arc.
