### ISSUE TITLE
Nerfed Arc Generation:  Inner Perimeters are not getting arcs on Orcaslicer

### ISSUE THREAD

**Issue by psiberfunk** [SoftFever/OrcaSlicer#1256]
**Describe the bug**
Under the conditions in the attached project file, and I suspect many conditions, the slicer is NOT generating arcs like it should for inner perimeters, only for outer perimeters.  I have observed this behavior in 1.6.3 but just regression tested and found it also in 1.5.0 and 1.4.5 as well!  Importantly, _Bambu Slicer 1.6.2.4_ handles this properly, generating both inner and outer perimeter G2/G3 arcs.  This has the potential to significantly degrade print quality vs Bambu Slicer on their machines, as it is well known that their motion controller performs better with arcs vs G1 in curved segments.

**_This is not a slicing/arc-fitting resolution/input file issue_**, because rigorous comparison with Bambu slicer with the same settings and file, as well as changing the resolutions does not resolve the problem.  Extensive proof of this is attached as described below

**3mf File for This Bug**
See attached ZIP file with:
[ArcPerimeterIssue.zip](https://github.com/SoftFever/OrcaSlicer/files/11641691/ArcPerimeterIssue.zip)

- Chillmaster_VFR21_ArcsOnOUTERPerimetersOnly_OrcaProject.3mf   (project file for loading into orca/bambu that demonstrates the behavior)
- Screenshots below also in ZIP
- Source STEP file, so that you may see that this is not a file import resolution issue.

**To Reproduce**

- Open the attached project file in OrcaSlicer 1.6.3 and slice, observe, as shown in the screenshots below, that G2/G3 arcs are generated on outer perimeters but NOT inner perimeters.
- Slice the same project file in Bambu Slicer.  Observe, as shown in the screenshot, that G2/G3 arcs are generated for BOTH Inner+outer perimeters.

**Expected behavior**
Orca should slice this file like Bambu does, providing arcs for inner+outer perimeters for the circular features in the file.

**Screenshots**
Screenshots here show Orca with no inner perimeter arcs, but Bambu with inner-perimeter G2/G3 arcs.
![image](https://github.com/SoftFever/OrcaSlicer/assets/19777571/6dff8a42-db0a-49bf-b0fc-bd8983dc74c2)
![image](https://github.com/SoftFever/OrcaSlicer/assets/19777571/3a6eddd6-90d7-4877-9054-597b6878a021)

**Printer model**
- Bambu X1  (but i'm not sure this is printer-specific)

**Desktop (please complete the following information):**
 - OS: Windows
 - Multiple versions, problem exists in v1.6.3,  v1.5.0, v1.4.5  (only tested these 3 before I gave up)

**Comment by cpasoft** [comment]
I confirm this bug...
