### ISSUE TITLE
Remove System Profiles and Printers after adding own

### ISSUE THREAD

**Issue by abstractFlo** [SoftFever/OrcaSlicer#126]
**Is your feature request related to a problem? Please describe.**
It would be cool, if we can remove system printer and profiles after adding a custom one based on a system printer

**Describe the solution you'd like**
Uncheck the printer inside the Wizard.

**Comment by m4R-T1n** [comment]
thats right , would be nice to remove unwanted printers to clean it up. you can manualy remove the part with the printer from the "BambuStudio.conf" file in the appdate/roaming/bambustudio-softfever folder.
remove this part to remove the ender printer. (make sure to export proliles if something goes wrong :) )

    "models": [
        {
            "model": "Creality Ender-3 V2",
            "nozzle_diameter": "0.4",
            "vendor": "Creality"
        }
    ],
