### ISSUE TITLE
Critical error, restart program over and over again

### ISSUE THREAD

**Issue by alldaywarrior** [SoftFever/OrcaSlicer#1260]
Slicing object with .12 and .08mm layer height and 3 raft layers gives critical error and asks me to restart program.
Doing what the error tells me to do does not work and it sometimes give me different errors. Never had this before. The file that I try to print is made by myself and is safe. I have enough memory so that couldnt be it. It is a very small object.

**To Reproduce**
Setting layerheight to .08 or .12mm and raft 3 layers.

**Screenshots**
![image](https://github.com/SoftFever/OrcaSlicer/assets/27778908/1634a931-9971-407d-8994-75c0602430a0)
![image](https://github.com/SoftFever/OrcaSlicer/assets/27778908/1e15d697-5747-40fc-8213-1ce1a1245406)

UPDATE:
Even 1 raft layer and all resolutions make the program crash over and over again. 
The model can be sliced without raft but when enabling raft it instantly crashes

**Printer model**
Bambulabs p1p
**Desktop (please complete the following information):**
 - Windows 10 version 21H2
 - Orcaslicer 1.6.3

**Comment by hliebscher** [comment]
do you have a saved 3mf that you can send as zip?

**Comment by HunterG6700** [comment]
I have the same issue when slicing with a raft.
