### ISSUE TITLE
Bug:  Incorrect G-Code Generation in Version 1.6.3  

### ISSUE THREAD

**Issue by philippwaller** [SoftFever/OrcaSlicer#1261]
**Issue Description:**
In the current version 1.6.3 of the software, I have observed a bug related to G-Code generation. The software generates G-Code instructions that command the printer to move along paths that are not defined in the model. This issue occurs specifically in the OrcaSlicer, while the BambuSlicer does not exhibit the same problem.

**Steps to Reproduce:**
Install and launch version 1.6.3 of the software.
Load the provided STL file.
Slice the model using the OrcaSlicer.
Review the generated G-Code instructions.

**Expected Behavior:**
The generated G-Code should accurately represent the model geometry, with no extraneous or unexpected movement commands.

Actual Behavior:
The generated G-Code contains instructions for the printer to traverse paths that are not present in the model.

**Attachments:**
OrcaSlicer
<img width="628" alt="Bildschirm­foto 2023-06-03 um 14 37 14" src="https://github.com/SoftFever/OrcaSlicer/assets/1090452/e21d3377-b52c-489a-b1e7-105dbaf53a2c">

BambuSlicer
<img width="628" alt="Bildschirm­foto 2023-06-03 um 14 38 57" src="https://github.com/SoftFever/OrcaSlicer/assets/1090452/c1d8b26b-4ba1-44df-8c22-333837de9d8a">

[Sample File.stl](https://www.dropbox.com/s/v1fvkono53ahkji/Github%20Issue%20SoftFever%20OrcaSlicer%201261.stl?dl=0)

**Comment by RaySajuuk** [comment]
I sliced your file in OrcaSlicer Nightly ([c675d97](https://github.com/SoftFever/OrcaSlicer/commit/c675d979a746390a3243eadf97781fb34525aa27)) did not see any issues.

![SCR-20230603-krsz](https://github.com/SoftFever/OrcaSlicer/assets/1126364/7b459417-ae52-46a1-a9e5-7404441fb6f3)

**Comment by philippwaller** [comment]
I just tried the latest snapshot and I get the same result. The problem will be resolved with the next release. Thank you very much.

**Comment by RaySajuuk** [comment]
Go to the action tab to download the latest nightly build or compile it independently. Or you can compile it yourself.
