### ISSUE TITLE
Whats the difference between filament_flow_ratio and print_flow_ratio?

### ISSUE THREAD

**Issue by shom** [SoftFever/OrcaSlicer#1263]
Are the functions the same? Is there a priority?

**Comment by tome9111991** [comment]
filament_flow_ratio is for the filament.
print_flow_ratio can be set for each object individually, is normally set to 1 which then corresponds to the filament_flow_ratio. filament_flow_ratio

**Comment by SoftFever** [comment]
> filament_flow_ratio is for the filament.
> print_flow_ratio can be set for each object individually, is normally set to 1 which then corresponds to the filament_flow_ratio.

Well explained 👍
