### ISSUE TITLE
Gap infill overextrudes and causes zits. Need a way to set flow ratio for specific line types

### ISSUE THREAD

**Issue by shayded-exe** [SoftFever/OrcaSlicer#1266]
My print looks beautiful up until the gap infill seen below.

![image](https://github.com/SoftFever/OrcaSlicer/assets/1417838/3d2a8870-4de4-48f8-b3ca-2fca7eb13e4a)

It overextrudes causing stringing and zits that start accumulating.

I've already calibrated my EM/PA. If I could set a lower flow ratio specifically for the gap infill it would fix my problems.

This is similar to #334, except I don't want to get rid of the gap infill, just reduce it by 1-2%.

**Comment by mikeq3** [comment]
I still see this issue was this fixed?
