### ISSUE TITLE
Set model name when sending to Bambu X1

### ISSUE THREAD

**Issue by Zodiase** [SoftFever/OrcaSlicer#1268]
Orca Slicer 1.6.3.

## Problem

For example, I set a custom project name ("Snapfinity 5x5 HT 0.4 PLA") when sending to printer:
<img width="460" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/1815174/3f1b00a0-28d9-49d5-94ad-960867797fc2">

When I go to the printer, in the Files grid view I can see my custom project name "Snapfinity 5x5 HT 0.4 PLA". But because the grid view can only show so long of a name, I tap the file to open it to see its name.

This is where I see **"1x4"** as its name. Sorry I don't have a photo of it at the moment.

I couldn't for my life understand where that came from as I don't recall naming anything that way. Eventually I recalled perhaps the first model I dragged into the project had name "1x4.step". And I was able to find the "Project" tab (which I never used before) where it clearly says **"Model name: 1x4"**.
<img width="712" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/1815174/6760c592-f90e-4674-9174-d843fb4b4bb4">

## Expectation

I'm not sure what the use of the "Project" tab is as it doesn't appear anything is editable. Also it doesn't quite make sense to use that "Model name" when I send any of my 4 plates to the printer.

I'd like the projects sent to the printer to use the custom name I set in the "Send to Printer SD card" interface. This is not just the name displayed in the grid view but also the name displayed when I tap and open it.

## Current workaround

1. I name the model file "Snapfinity 5x5 HT 0.4 PLA.step"
2. Create a new project in OrcaSlicer.
3. Drag the model file in.
4. Slice and send to Printer with name "Snapfinity 5x5 HT 0.4 PLA".

This is how I get "Snapfinity 5x5 HT 0.4 PLA" in the Files grid view and "Snapfinity 5x5 HT 0.4 PLA.gcode.3mf" when I tap and open it.

**Comment by Zodiase** [comment]
Oddly, I tried to write a reproduction but I couldn't get the "Model name" in the Project tab to change to anything non-empty, no matter what I have tried so far.

**Comment by CoReYeDe** [comment]
Would like to reopen, because i have the same behavior..
STL exported from Fusion360, imported to orcaslicer..
Dont know, where this Information is get from and how to change it.
Also "Bambu Weihnachtshütte" - What is this?

![image](https://github.com/SoftFever/OrcaSlicer/assets/22613068/b9b128d9-2d94-44ee-a382-e05f5778fd2b)
![image](https://github.com/SoftFever/OrcaSlicer/assets/22613068/7b13bbe5-7fd6-4671-b51a-32239db898f7)
![image](https://github.com/SoftFever/OrcaSlicer/assets/22613068/ea9842a7-6117-409a-95b7-055ea53635ea)
