### ISSUE TITLE
Wrong extrusion if detect overhangs walls is active

### ISSUE THREAD

**Issue by abstractFlo** [SoftFever/OrcaSlicer#127]
**Describe the bug**
Currently i print some parts for an MK3S Bear Upgrade. If i enable "Detect Overhang Walls" then there is a false extrusion near an overhang

**3mf File for This Bug**
If it is related to slicing, please append the 3mf file. It could be extremely helpful to solve the issue.
[psu_upper_mount_black.3mf.txt](https://github.com/SoftFever/BambuStudio-SoftFever/files/10365185/psu_upper_mount_black.3mf.txt)

* Remove .txt extension: Only for uploading it here

**To Reproduce**
1. Open 3mf File and slice
2. Look at layer 79 in preview
3. Look at overhang
4. Go to Quality -> remove "Detect overhang walls"
5. Slice and look. The line is gone

**Screenshots**
![image](https://user-images.githubusercontent.com/4614586/211122159-35a4fa21-1172-4544-9add-6b007f9f2299.png)
![image](https://user-images.githubusercontent.com/4614586/211122233-2b30fdae-f703-4616-8c7b-85dee0881f9e.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10
 - Latest build for bambu studio fork

**Comment by SoftFever** [comment]
Thanks.
I'm able to repro this issue.

**Comment by hliebscher** [comment]
the bug is only with classic arachne works at mac

**Comment by hliebscher** [comment]
crazy if you go back from arachne to classic then it works without the bug...
![crazy](https://user-images.githubusercontent.com/9274162/211145410-d47a74d1-43c1-40e8-926a-2cc1715240cf.jpg)

**Comment by SoftFever** [comment]
I can reproduce this bug with BambuStudio 1.4.0.18
It's an upstream bug.
The key to reproducing this is setting the `default` and `Outer wall` width to 0.4.

I'm going to open to the ticket in their repo. They probably can fix it fast.

**Comment by SoftFever** [comment]
@hliebscher this is most likely because when we switch back to classic from Arachne, the slow down for overhangs remain unchecked :(

**Comment by SoftFever** [comment]
Fixed in b10799027012a6c530da78987e5d416f8fcfd5c4
Nightly build are available now: https://github.com/SoftFever/BambuStudio-SoftFever/actions
