### ISSUE TITLE
Height Range Modifier Causes Inability to Change Color/Filament from Color 1 and can't be removed after beeing added

### ISSUE THREAD

**Issue by jaddel** [SoftFever/OrcaSlicer#1272]
**Describe the bug**
Height Range Modifier Causes Inability to Change Color/Filament from Color 1 and can't be removed after beeing added

**3mf File for This Bug**

I happens with any file.

**Screenshots**
<img width="465" alt="Screenshot 2023-06-05 at 10 33 52" src="https://github.com/SoftFever/OrcaSlicer/assets/46263124/2cbebabd-7013-43a3-a1dd-1a3dc146b4e4">

**Printer model**
X1C

**Desktop (please complete the following information):**

Mac OSX Ventura M1

Orca Slicer 1.6.3

**Comment by aferrick1** [comment]
In addition you cannot add more than one height range modifier to an object as you can in Bambu Slicer
![image](https://github.com/SoftFever/OrcaSlicer/assets/72628586/563c6cbb-1796-41c0-9ba2-88b146fb6dbf)
