### ISSUE TITLE
Can we add a universal search feature like in the bar on PrusaSlicer? Coming from other slicers it can be hard to remember what settings are where.

### ISSUE THREAD

**Issue by dvomang** [SoftFever/OrcaSlicer#1275]
**Is your feature request related to a problem? Please describe.**
I would like to be able to search within any setting when searching in Orca. If I forgot where pressure advance is, or line width etc I could search for them globally.

**Describe the solution you'd like**
![image](https://github.com/SoftFever/OrcaSlicer/assets/3137075/8ba45cdf-0cc1-4eea-92a5-c58ff8d7b421)

**Comment by liftbag** [comment]
> **Is your feature request related to a problem? Please describe.** I would like to be able to search within any setting when searching in Orca. If I forgot where pressure advance is, or line width etc I could search for them globally.


The search feature is already present, but not universal. You can search in the process presets, but not in the filament or printer settings. In fact it could be a useful improvement for those switching to Orca Slicer for the first time.

<img width="434" alt="Screenshot 2023-06-07 alle 08 24 03" src="https://github.com/SoftFever/OrcaSlicer/assets/14921654/b861f12e-414f-4c47-a19b-4ff26675398a">

**Comment by dvomang** [comment]
Not related to a bug.

I just think it would make more sense if all of the settings were searchable rather than just the processes. There are so many settings and sometimes it’s easier to just search for what you are looking for rather than hunt through every setting looking for it.

**Comment by julie777** [comment]
I have to agree with @dvomang, being able to search all settings at the same time using `<ctrl>F` like Prusa Slicer is so much better. I hate having to search in 3 places and two of them require opening a separate dialog.

BTW, I submitted this request to Bambu Studio quite some time ago.

**Comment by jeronbernal** [comment]
this would be a great feature! i agree, it would really help with switching slicers

**Comment by YanceyA** [comment]
I too would like this feature.

**Comment by bvrielink** [comment]
Coming from Prusa Slicer I really miss the CTRL-F function. Hope it will be added.

**Comment by alfondehesa** [comment]
Same here. Would love the CTRL-F function to search all settings (for processs, filament and printer all together).

**Comment by swdwi2** [comment]
Same here.  Miss this feature switching from superslicer
