### ISSUE TITLE
Bad image error? or system issue

### ISSUE THREAD

**Issue by choice3d** [SoftFever/OrcaSlicer#1278]
I get this error when trying to open V1.6.3

![image](https://github.com/SoftFever/OrcaSlicer/assets/135681614/2a4d2a32-eb0f-4ba3-8c0c-4975d0fb9862)

V1.6.2 ran perfectly well.

Running Windows 10

**Comment by psiberfunk** [comment]
This works perfectly fine on windows 11.  Have you tested in win 11? Windows 10 is maintenance mode only at this stage … I wouldn’t be shocked if Windows 10 users don’t start getting more errors like this

**Comment by Konamiman** [comment]
I'm getting the exact same error with v2.4.2 in Windows 11. The program won't even start after a fresh install.
