### ISSUE TITLE
Add delay timer to start print to control the time when the print finishes.

### ISSUE THREAD

**Issue by jadflat** [SoftFever/OrcaSlicer#1280]
Would it be possible to add a delay timer to start the print after sending to the printer?

For example, it's 11PM and I have a 4 hour print with a pause to insert some magnets 3.5 hours into the print. If the prints starts straight away it'll be sitting on the printer for a number of hours until I wake up to attend to it. 

Adding a delay to the start would allow the print to finish/pause at a desired time instead.

**Comment by kylek29** [comment]
If you're in layer-printing mode (as opposed to per-object mode), you can insert a "Pause" command by dragging the layer-height  (on the preview window) slider on the right side to the height you want, then right-clicking the "+" of that slider, and selecting "add Pause" (or a custom GCode).

Some notes about this feature:
- If you're in Per-Object printing mode, it will appear as grayed out (I don't think they ever finished it for that mode?)
- If you don't have a pause command in your printer profile, it will also appear as grayed out.


![image](https://github.com/SoftFever/OrcaSlicer/assets/15932180/e866c1bc-4f70-4aff-a149-f2d4c84ed423)
