### ISSUE TITLE
Inserting PAUSE Gcode before PRINT_END Gcode

### ISSUE THREAD

**Issue by PhilBaz** [SoftFever/OrcaSlicer#1282]
**Describe the bug**

Its inserting PAUSE Gcode before PRINT_END Gcode

**3mf File for This Bug**
If it is related to slicing, please append the 3mf file. It could be extremely helpful to solve the issue.

**To Reproduce**
Steps to reproduce the behavior

slice

**Expected behavior**

No pause Gcode

**Screenshots**
![jhkhjh](https://github.com/SoftFever/OrcaSlicer/assets/21558241/dfd08c59-5e21-49b5-af5d-b9825c355aa3)

**Printer model**

Voron 2.4

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Windows]

Windows 10

**Comment by PhilBaz** [comment]
Ahhh, this is the filament end Gcode. But I'm only using one filament ?

**Comment by hliebscher** [comment]
You can add a if command like if tool changes >0 then ....
Ignore pause with 1 filament 
Sample in snapmaker j1 filament gcode

**Comment by PhilBaz** [comment]
@hliebscher 

Can you paste the code here? I looked but couldn't find it. It goes right in the filament end Gcode box? Didn't know we could put conditionals in there.

Thank you!

**Comment by hliebscher** [comment]
@PhilBaz 

{if total_toolchanges < 1};  one extruder /Filament
;nothing
{else}; more extruders
PAUSE_BEEP
{endif}

**Comment by PhilBaz** [comment]
@hliebscher 

Thank you!  

I don't know if I should close this issue or leave it open to be addressed as a setting or in the documentation?
