### ISSUE TITLE
Klipper KAMP does not work with PA Line calibration

### ISSUE THREAD

**Issue by TheBest6337** [SoftFever/OrcaSlicer#1284]
**Describe the bug**
I have KAMP installed on my printer if I slice the Calibrate Pressure Advance lines thing then it just purges in the Middle of the Bed and not near the Pressure Advance lines.

**To Reproduce**
1. Calibrate Pressure Advance
2. Send to printer with KAMP setup
3. See that its only making a Mesh in the Middle and purging in the middle and not where to whole test is done

**Expected behavior**
KAMP only Meshes a small cube in the middle of the bed and purges in the middle

**Comment by psiberfunk** [comment]
Could you explain how KAMP’s errant behavior is caused by the slicer’s valid GCODE ?

**Comment by TheBest6337** [comment]
> 

Yeah thats the problem but it would be nice if it would work with KAMP aktivated
