### ISSUE TITLE
Tool change system/multi extruder not supported

### ISSUE THREAD

**Issue by vito30x** [SoftFever/OrcaSlicer#1292]
I use a Custom made printer with a Tool change system like the BTT Hermit Crab.
I would love to see on Orca a funktion to add multiple extruder and Nozzles sizes for a custom printer.
Szenario in my case is.. I have a Bowden and Direct setup with the Hermit Crab tool change plate. Also a Revo quick Nozzle change setup. In Orca I can just use a single nozzle size and extruder.
Any plans to implement this?

**Comment by Rob65** [comment]
I would also love this feature. If being implemented, please also consider to add overrides for speed/acceleration/jerk. Especially for tool changer with different (weight) tools, this would be very nice.

You might be able set up multiple filament/extruder combos and add the code for this in the advanced tab by adding custom G-code. That is not the most user friendly way but this may work.

**Comment by hliebscher** [comment]
this is the bambustudio problem ... they have only 1 Toolhead/extruder in software... so if you use multicolor only one nozzle size is supported

**Comment by Rob65** [comment]
This is a very bad comment. If the fact that this is not supported in bambustudio means this will not be implemented in OrcaSlicer then I see limited use for OrcaSlicer.

**Comment by vito30x** [comment]
> this is the bambustudio problem ... they have only 1 Toolhead/extruder in software... so if you use multicolor only one nozzle size is supported

I was hoping that this will implemented, because it´s a hybrid also from Prusa slicer and there you can setup multi extruder and nozzle sizes.

**Comment by hliebscher** [comment]
I hope softfever make this possible ... 
i need this for my IDEX Printers

**Comment by EiNSTeiN-** [comment]
This would be useful :+1:

**Comment by danik-ik** [comment]
This seems to be exactly the feature that will turn me away from the Orca slicer at the selection stage. However, I will keep an eye on the situation as it develops.
