### ISSUE TITLE
'A G-code path goes beyond plate boundaries' after exporting and importing sliced 3mf for Prusa

### ISSUE THREAD

**Issue by Darthmonkey** [SoftFever/OrcaSlicer#1293]
**Describe the bug**
After adding items to the build plate, then 'Export plate sliced file' as 3mf, then importing them into a new Orcaslicer instance, an error shows stating 'A G-code path goes beyond plate boundaries' when using the Prusa profile.

**3mf File for This Bug**
If it is related to slicing, please append the 3mf file. It could be extremely helpful to solve the issue.

**To Reproduce**
Steps to reproduce the behavior
1. Change the Printer to 'Prusa on Octoprint'
2. Add 3mf files to a build plate
3. Ctrl-G to export the plate sliced files as 3mf
4. Close Orcaslicer
5. Double click the 3mf file to open in Orcaslicer.
6. Receve the error 'A G-code path goes beyond plate boundaries'

**Expected behavior**
Steps 1-5 above, but without the error.

**Screenshots**

**Printer model**
Prusa Mk3s on OctoPrint

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Windows]
Windows 11

**Comment by SoftFever** [comment]
@Darthmonkey 
Is it convenient to share the project file as well as the sliced file?

**Comment by Darthmonkey** [comment]
Sorry, I'm not completely sure what you mean by sliced file or project files. I have tried to interpret the best I could.
https://1drv.ms/f/s!AkvX-bEguFc_jNoekuZ5kufP2BNk4Q?e=rkHXdH
