### ISSUE TITLE
[Bug] - Timelapses being recording regardless

### ISSUE THREAD

**Issue by ondrovic** [SoftFever/OrcaSlicer#1297]
**Describe the bug**
Timelapses being generated regardless of option when starting a print, I just cleared out 85 timelapse 

**3mf File for This Bug**
n/a

**To Reproduce**
1. Import file into slicer
2. Slice print
3. Send plate to printer
    * make sure uncheck Timelapse option
4. Let print complete (not sure if this is necessary)
5. Navigate to Device -> Media -> All Files
   * Observe there is a new timelapse recording for the print

**Expected behavior**
If timelapse option is no enabled it shouldn't have created a new recording

**Screenshots**
n/a
**Printer model**
X1C

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Version: 22H2
 - OS Build: 22621.1702

**Orca Slicer:**
- Version: 1.6.3

**Comment by julie777** [comment]
@ondrovic Does the X1 have multiple directories for video files like the P1P?

I just realized that you can see the media from Orca Slicer. On the P1P the media tab is always empty.

This might not be any help, but I will just report how the P1P is working.

I have both a timelapse directory and a cam directory and both have AVI files in them. I never enable timelapse on the start of print dialog.

I just checked and the timelapse directory has 70 files with the first one from March and the most recent on May 23rd.

The cam directory has 31 files with the oldest created in February and the most recent on May 15th.

I am currently printing and I cannot find any file being used for the live stream, so it appears that it is being streamed from memory.
