### ISSUE TITLE
macOS: Help menu should be the last item

### ISSUE THREAD

**Issue by m7r** [SoftFever/OrcaSlicer#130]
On macOS the  help menu should be always the last item on the right.
Is it possible to switch the location?

<img width="414" alt="Menu" src="https://user-images.githubusercontent.com/4331597/211162221-00982b78-dd4b-49f1-a714-21ab2a6f0cb6.png">

**Comment by shaneshort** [comment]
@SoftFever this looks to have been done, probably fine to close this?
