### ISSUE TITLE
Issue slicing certain models

### ISSUE THREAD

**Issue by Edzi11** [SoftFever/OrcaSlicer#1302]
[arm chair model.zip](https://github.com/SoftFever/OrcaSlicer/files/11696940/arm.chair.model.zip)
### Discussed in https://github.com/SoftFever/OrcaSlicer/discussions/1299

<div type='discussions-op-text'>

<sup>Originally posted by **Edzi11** June  8, 2023</sup>
As stated I'm having some issues slicing certain models when using supports. It freezes after getting to 65%. The only time it doesn't
 is when I'm using slim tree supports or default normal supports. Oddly enough cura has no issue with the models and slices it within minutes. Attached is the model that isnt working correctly. File is about 1.8mb and about 40k triangles but I have sliced bigger files in cura without issue. any suggestions as I want this to be my main slicer but not if it cant slice every file i throw at it like cura does

![model](https://github.com/SoftFever/OrcaSlicer/assets/123626106/09fb7b4d-71a0-49f8-8c9b-bb3791101655)
</div>

**Comment by hliebscher** [comment]
it works with 1.6.3 Mac it takes 3 sec !      but the stl model has errors

**Comment by hliebscher** [comment]
![tree](https://github.com/SoftFever/OrcaSlicer/assets/9274162/ec0b6b11-04d5-4689-a732-f9091710d968)

**Comment by Edzi11** [comment]
Yes I did notice I had a few manifold errors but on Windows you can repair
it within the slicer. Do me a favor when generating the supports using slim
supports change the diameter of the supports to five and the distance to
two. Let me know if it's still generates for you. So if I don't change any
variables on the supports and just use the default tree support slim it
does generate but it takes a solid 20 minutes to do so. But changing the
settings I just advised doesn't slice for me even after an hour
