### ISSUE TITLE
Orca slicer support is solid, printing 100% infill

### ISSUE THREAD

**Issue by manpres2** [SoftFever/OrcaSlicer#1303]
Hi,

I recently started using ORCA slicer and have experience with Cura and prusha slicer. I have tried to find the option if i can reduce the infill for the supports but its always printing solid and even shows solid in the preview. I don't see an option to change this. I want prusha like tree support if there is an option in the slicer.
![Capture](https://github.com/SoftFever/OrcaSlicer/assets/86102386/c7de2a7d-4aff-4eef-a45c-6359d1e2b3a6)

**Comment by atl285** [comment]
Change the Support **style** to which tree style you want:
![support_style](https://github.com/SoftFever/OrcaSlicer/assets/15815417/44abd744-48e4-4d3c-a3bc-3d10508af297)

**Comment by hellfirehd** [comment]
I am seeing the same thing. 

- Version: v1.6.3
- Type: Tree (auto)
- Style: Tree Slim

![image](https://github.com/SoftFever/OrcaSlicer/assets/61830/9fc43c9d-d114-4394-aeb4-2ab31cb17b34)
![image](https://github.com/SoftFever/OrcaSlicer/assets/61830/c3a0cf62-c780-4586-b363-6b1352b891ca)

**Comment by fellipute** [comment]
same here, any clues?

**Comment by atl285** [comment]
After changing Support **Type** and **Style** in OrcaSlicer 1.6.3 it looks fine for me:
![tree-support](https://github.com/SoftFever/OrcaSlicer/assets/15815417/27e2be08-f47e-4eb6-9397-c4758b22d539)

**Comment by manpres2** [comment]
![image](https://github.com/SoftFever/OrcaSlicer/assets/86102386/424ded8b-cfeb-41df-b592-b563e01cd095)
  its still same

**Comment by lin-ycv** [comment]
v1.9 still an issue
![image](https://github.com/SoftFever/OrcaSlicer/assets/60565737/8cfffa4e-0bf5-4b45-a7c1-0ac8fa68bebc)
