### ISSUE TITLE
Printer Add: Creality non-S series

### ISSUE THREAD

**Issue by BeardedDG** [SoftFever/OrcaSlicer#1306]
Would like to see the non S series of creality Ender printers. Such as the Ender 3 Pro.

**Comment by karcaw** [comment]
What does it take to add a new Profile?  I may be able to work on it.

**Comment by karcaw** [comment]
but its still an issue...

**Comment by cochcoder** [comment]
I am currently making some profiles for the Ender 3 Pro, would you say that the same settings used for the non-pro Ender 3 work good for the pro version? I can't find any differences online and I only have a Ender 3.

**Comment by karcaw** [comment]
yes, i based my profile on the ender 3 s1 bits that were in there, and made sure the motion ability numbers matched what I could see in Cura and Prusa....

**Comment by cochcoder** [comment]
I'll make a PR, for the Ender-3 Pro, as soon as the one I have right now gets merged

**Comment by cochcoder** [comment]
I have opened a PR that copies the in-built profile for the Ender-3 and uses it for the Ender-3 Pro. I did this as I can't find any information online that gives settings significantly different than the current Ender-3 profile.
