### ISSUE TITLE
Absolut Extrusion create to much volumetric flowrate

### ISSUE THREAD

**Issue by abstractFlo** [SoftFever/OrcaSlicer#1308]
**Describe the bug**
If i enable absolut extrusion inside the printer settings and slice my model, the volumetric flow rate is unexpected high. I have ignore this for some time, but my print ist canceld about 58%. Klipper says to much cross section extrusion. I have default a value of 15, but klipper wants 83 before canceled. If i activate relative extrusion, all is fine.

The preview of the sliced model shows the right volumetric flow rate.

**3mf File for This Bug**
[wrong_volumetric_flowrate.zip](https://github.com/SoftFever/OrcaSlicer/files/11709288/wrong_volumetric_flowrate.zip)

**To Reproduce**
uncheck relative extrusion inside the printer settings

**Expected behavior**
Same volumetric flow rate no matter which extrusion mode is set.

**Screenshots**
![image](https://github.com/SoftFever/OrcaSlicer/assets/4614586/1acedf72-8e9e-4300-bb54-1a73564e9fd2)
![image](https://github.com/SoftFever/OrcaSlicer/assets/4614586/2f007878-f807-4b55-a449-f59a0618fcce)

**Printer model**
Voron 0.2

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Orca Version: 1.6.3

**Comment by abstractFlo** [comment]
It's only for this model in my case, any other model works perfectly with absolut extrusion mode

**Comment by Habag111** [comment]
![obraz](https://github.com/SoftFever/OrcaSlicer/assets/80962238/5c92c516-fe35-4db6-8d50-8fbdbd4033db)
![obraz](https://github.com/SoftFever/OrcaSlicer/assets/80962238/36a3f272-1970-4818-aea8-da82402da7c6)

I'm experiencing the same issue. It's so bad klipper errors out "Stepper too far in past". Using absolute extrusion eliminated the problem. I'm using orca 1.6.3 on windows 10. The .stl I used was kevinakasams tolerance test https://github.com/kevinakasam/KlackEnder-Probe/blob/main/STL/Tolerance_Test.stl

**Comment by justr0st** [comment]
> Using absolute extrusion

You mean using **relative** extrusion
