### ISSUE TITLE
Set process preset per-plate

### ISSUE THREAD

**Issue by shayded-exe** [SoftFever/OrcaSlicer#1309]
**Is your feature request related to a problem? Please describe.**
I like to set up multiple build plates for different parts in the same project. Usually I'm putting multiple of the same part on a plate and I want each plate to print with its own settings.

Currently I either have to remember to switch presets when changing plates, or set per-object settings on every object on the plate which is extremely arduous and not easily updated because you cannot set per-object presets (only individual settings).

**Describe the solution you'd like**
In the plate settings dialog where you can name the plate, I would like to be able to select a process preset.

**Additional context**
For example, here I have two build plates. Spools and filaments. I have process presets saved for each. When going to print, it is very easy to accidently have the wrong preset selected and mess up your entire print. If presets could be set per-plate, this problem would be avoided and it would greatly improve the multi-plate workflow.

![image](https://github.com/SoftFever/OrcaSlicer/assets/1417838/e2a72c41-7799-42f1-83ad-c5395ff4076c)

**Comment by julie777** [comment]
I have another use case. Often while iterating on a design, I export a part from Fusion 360 and then import it into Orca. Because the project has many plates, I have the set the specific to the new object to the object. 

When I am ready to iterate again, I delete the object from the plate and then import the new STL. Because settings were attached to the object, I now have to got through the process to set all the settings again, for the new instance of the same object.

**Comment by shayded-exe** [comment]
> I have another use case. Often while iterating on a design, I export a part from Fusion 360 and then import it into Orca. Because the project has many plates, I have the set the specific to the new object to the object.
> 
> When I am ready to iterate again, I delete the object from the plate and then import the new STL. Because settings were attached to the object, I now have to got through the process to set all the settings again, for the new instance of the same object.

You can actually get around this by right clicking on your object in the slicer and doing "Replace with STL"! Or if you just overwrite the same file you can do "Reload from disk".

**Comment by hliebscher** [comment]
@shayded-exe  i use multiple instances with different print settings so it is also possible use different printers at the same time and easy name of the 3mf like parts or settings...

**Comment by julie777** [comment]
@shayded-exe Thanks!
