### ISSUE TITLE
height range modifier

### ISSUE THREAD

**Issue by StephInoP** [SoftFever/OrcaSlicer#1314]
**Describe the bug**
I added a height range modifier to the model, set it up and done. When re-open the slicer, height range modifier is gone.
Not in the project anymore. I have tried it many times, so i confirm there is a problem here.

**Printer model**
Bambulab X1 Carbon

**Desktop (please complete the following information):**
Mac OS Monterey

**Comment by Stargo44** [comment]
Same issue with me height range modifie are not saved or not loaded.
 Windows 10

**Comment by foto-boss** [comment]
I confirm. Ranges are not saved.

**Comment by hliebscher** [comment]
same as #1195  #1071

**Comment by OmiCron07** [comment]
Bambu Lab is able to save and load the height modifier. Orca does not save the height modifier, nor load it even if present.

Bambu Lab:
![image](https://github.com/SoftFever/OrcaSlicer/assets/31325575/c8b0191e-8493-4c1b-8a13-ac227d092ced)

Orca:
![image](https://github.com/SoftFever/OrcaSlicer/assets/31325575/4d1c69b4-2651-4a8b-936a-f91993af23d8)

**Comment by MotoFreak** [comment]
having the same issue as well just like the others.  Just add a height modifier and save and reload project, and its gone!
