### ISSUE TITLE
OpenSCAD Customizer 

### ISSUE THREAD

**Issue by EternityForest** [SoftFever/OrcaSlicer#1315]
**Is your feature request related to a problem? Please describe.**

There's been some upstream discussion on OpenSCAD customization, but it seems unlikely to happen upstream, and there's not currently many good ways to customize things.

**Describe the solution you'd like**

Link to upstream discussion, he has a pretty good proposal: https://github.com/prusa3d/PrusaSlicer/issues/9687

Seems like it would be fairly easy to implement, you could have an OpenSCAD folder inside of a .3mf file, unpack it to a temp dir, show a customizer screen, call the OpenSCAD binary, and load the output instead of the main .3mf.content.

Ideally, you could save any presets the user changed back into the .3mf file or as a new file, and save the pre-sliced model as the new "default" model of the  file.

**Describe alternatives you've considered**

Not sure there really is any alternative for less tech savvy end users at the moment aside from the Thingiverse customizer.  Seems like everyone just does everything with OpenSCAD manually.

**Additional context**

**Comment by imagesurgery** [comment]
Poking because +1!
