### ISSUE TITLE
Сhoice of the filaments order.

### ISSUE THREAD

**Issue by foto-boss** [SoftFever/OrcaSlicer#1316]
The choice of the order of printing of the colors of the filament in the layer is very necessary. Starts with the wrong filament from which I need.

**Comment by hliebscher** [comment]
witch printer and witch os?

**Comment by foto-boss** [comment]
bambu x1 carbon with AMS
Windows 10 pro

**Comment by hliebscher** [comment]
Is this with Bambustudio the same?

**Comment by foto-boss** [comment]
Yes, exactly the same on the latest version.
It worked better in earlier versions. But there was no direct choice for the user.

**Comment by foto-boss** [comment]
So they didn't fix it. You have to use version 1.6.2
