### ISSUE TITLE
Mainsail Webcam Video Buggy - Linux

### ISSUE THREAD

**Issue by cplmayo** [SoftFever/OrcaSlicer#1318]
**Describe the bug**
Mainsail/Crowsnest webcam stream flashes gray; appears to be a rendering or stream issue. Not present on Win10.

**3mf File for This Bug**
N/A

**To Reproduce**
Add device network settings, click device tab, observe webcam stream.

**Expected behavior**
N/A

**Screenshots**
I wasn't able to capture an image but I uploaded a video to YT: https://youtu.be/zISOWKUqIy8

**Printer model**
Voron 2.4r2 350mm

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: Distributor ID: Pop, Description: Pop!_OS 22.04 LTS  Release: 22.04

**Comment by zuhra031** [comment]
Also on MacOS, OrcaSlicer v1.6.4-beta2


Desktop (please complete the following information):

    OS: MacOS 
    Version: 13.4.1 (22F82), M1
