### ISSUE TITLE
line width depending on nozzle width

### ISSUE THREAD

**Issue by delStipe** [SoftFever/OrcaSlicer#1321]
**Additional context**
Is it possible to set the width of the line to depend on the percentage of the width of the nozzle, as solved in SuperSlicer.
  Then those parameters would change automatically...

Hvala :)
  
![Bez naslova](https://github.com/SoftFever/OrcaSlicer/assets/128221865/c77154e6-6e0e-4d22-aa99-c6a176d99182)

**Comment by jeremytodd1** [comment]
Fully agree. How SS handles the percentages is much better than how PS handles the percentages.

With SS I can easily make profiles for different nozzle sizes. With PS it's a pain, to the point where I don't even bother.

**Comment by MaikelKelder** [comment]
I second this, this is for me the main reason to keep using SS, since in Orca I dont like this fixed setting.

**Comment by julie777** [comment]
> Fully agree. How SS handles the percentages is much better than how PS handles the percentages.
> 
> With SS I can easily make profiles for different nozzle sizes. With PS it's a pain, to the point where I don't even bother.

@jeremytodd1 
Just curious, do you mean you can "easily make profiles for different nozzle sizes" or can you use the same profile because line sizes change automatically based on nozzle size?

**Comment by MaikelKelder** [comment]
The last, changing the nozzle in printer setting sets automatically the
line widths in print settings.

**Comment by jagerman** [comment]
Bad bot.
