### ISSUE TITLE
Bridging use Overhangspeed

### ISSUE THREAD

**Issue by tome9111991** [SoftFever/OrcaSlicer#1322]
Hi
With some objects I have the problem that instead of the bridging speed the overhang speed is used for bridging.
I don't have this issue in  BS.

![overhang](https://github.com/SoftFever/OrcaSlicer/assets/57866234/646aa6f2-99e2-472c-92b8-f6bc468514b0)

Project:
[project.zip](https://github.com/SoftFever/OrcaSlicer/files/11714384/project.zip)

EDIT:
No issue with Overhang speed Classic Mode

**Comment by steven850** [comment]
Im seeing this same issue, but im also seeing it with classic not just arachne.

**Comment by steven850** [comment]
It cant make up its mind on this one 
![Bridge speed change](https://github.com/SoftFever/OrcaSlicer/assets/43098060/5feb5420-4154-4af7-b69f-b55d6643ffb4)
