### ISSUE TITLE
Add 0.6 profiles

### ISSUE THREAD

**Issue by tshank-godaddy** [SoftFever/OrcaSlicer#1333]
I would like 0.6 nozzle presets for Prusa Mini and Mk3s

**Comment by fr3ak2402** [comment]
I have already implemented this, in the next version all printers will have multiple Nozzel profiles....

To be exact they will all have a 0.2,0.4,0.5,0.6,0.8 Nozzle. Also the Prosa printers

**Comment by tshank-godaddy** [comment]
Awesome!

**Comment by fr3ak2402** [comment]
Yes, I have been working on it for a while...

The following PR (#1176) already contains all the profiles, at the moment I am in the process of creating new printer profiles for the OrcaSlicer.

**Comment by susesKaninchen** [comment]
I cant find the Prusa profiles with 0.6, can anyone help me out?
