### ISSUE TITLE
UI Issue in Printer/Filament Panels

### ISSUE THREAD

**Issue by KyGunsAndRadio** [SoftFever/OrcaSlicer#1335]
**Describe the bug**
UI Elements within the Printer and Filament collapsible panels become misaligned after collapsing and expanding.

**To Reproduce**
Select Prepare.
Collapse both Printer and Filament panels on the left.
Re-expand both panels.
All the text/elements are jumbled up under Printer, with nothing showing under Filament. 
Repeating the process again will sometimes clear things up.

**Expected behavior**
Items to display normally under each panel.

**Screenshots**
![image](https://github.com/SoftFever/OrcaSlicer/assets/89168030/5462c07f-82c2-4362-b8e9-490715a65417)

**Printer model**
Voron V0.1

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Version: 21.1
 - Cinnamon Desktop
 - AppImage v1.6.3

**Comment by blueeagle69** [comment]
And one here too :)
![image](https://github.com/SoftFever/OrcaSlicer/assets/9963876/df0c6371-6757-4033-87b7-d0f8a771b606)
