### ISSUE TITLE
Purge/wipe towers

### ISSUE THREAD

**Issue by brueter** [SoftFever/OrcaSlicer#1337]
### Discussed in https://github.com/SoftFever/OrcaSlicer/discussions/1336

<div type='discussions-op-text'>

<sup>Originally posted by **brueter** June 13, 2023</sup>
Wondering if theres any possibility of adding purge/wipe towers similar to what superslicer has. For MMU units like the ERCF on units without anywhere to purge filament other than the plate having a purge tower seems like a good solution. Superslicer has this implemented already and has automatic volume calculation based on "pigmentation" values for each filament. This pigmentation calculation is nice but is very difficult to calculate compared to how simple calculating purge volume is currently in bambu/orca. If these volumes could be used to automatically calculate the purge tower volumes it would be ideal.

Below is the code I believe superslicer is using for their tower generation, let me know if this isn't correct and I can try and find the correct reference.
https://github.com/supermerill/SuperSlicer/blob/master/src/libslic3r/GCode/WipeTower.cpp
https://github.com/supermerill/SuperSlicer/blob/master/src/libslic3r/GCode/WipeTower.hpp
https://github.com/supermerill/SuperSlicer/blob/master/src/slic3r/GUI/WipeTowerDialog.cpp
https://github.com/supermerill/SuperSlicer/blob/master/src/slic3r/GUI/WipeTowerDialog.hpp</div>

**Comment by sorted01** [comment]
I was looking if i can find a request like that. Thank you for bringing this up. I would love that feature <3

**Comment by Surion79** [comment]
I would love that feature as well <3

**Comment by jeanres** [comment]
I would love this feature as well

**Comment by adolfotregosa** [comment]
Count me in too. Wipe tower would be great a addition.

**Comment by Nofuss73** [comment]
I would love this feature too..

**Comment by Cheo7811** [comment]
I always wondered why it was not present since it is implenented in Prusa slicer and Superslicer

**Comment by petrude** [comment]
I would like this feature as well. Orca Slicer is an awesome slicer.  Do not want to switch to another slicer to use ERCF.

**Comment by brueter** [comment]
Seems like this gas gotten a lot of activity and would benefit a lot of people, is there a good way to get in contact with devs to possibly get this going?

> ### Discussed in #1336
> Originally posted by **brueter** June 13, 2023 Wondering if theres any possibility of adding purge/wipe towers similar to what superslicer has. For MMU units like the ERCF on units without anywhere to purge filament other than the plate having a purge tower seems like a good solution. Superslicer has this implemented already and has automatic volume calculation based on "pigmentation" values for each filament. This pigmentation calculation is nice but is very difficult to calculate compared to how simple calculating purge volume is currently in bambu/orca. If these volumes could be used to automatically calculate the purge tower volumes it would be ideal.
> 
> Below is the code I believe superslicer is using for their tower generation, let me know if this isn't correct and I can try and find the correct reference. https://github.com/supermerill/SuperSlicer/blob/master/src/libslic3r/GCode/WipeTower.cpp https://github.com/supermerill/SuperSlicer/blob/master/src/libslic3r/GCode/WipeTower.hpp https://github.com/supermerill/SuperSlicer/blob/master/src/slic3r/GUI/WipeTowerDialog.cpp https://github.com/supermerill/SuperSlicer/blob/master/src/slic3r/GUI/WipeTowerDialog.hpp

**Comment by brueter** [comment]
Seems like this is getting a lot of attention and would help a lot of people, is there a good way to possibly get in contact with the devs?

**Comment by jeanres** [comment]
I am happy to take a whirl at implementing this, if the devs are ok with this being done?

**Comment by brueter** [comment]
> I am happy to take a whirl at implementing this, if the devs are ok with this being done?

Don't see why they wouldn't want it implemented, if you need any help with testing feel free to reach out on discord, my username is zchem

**Comment by jeremytodd1** [comment]
I'm also looking forward to having a purge block feature brought to Orca.

I plan to build a Tradrack later in the year. Knowing that I wont currently be able to use Orca for it though, because of the lack of a purge block,  is not a good feeling.

**Comment by brueter** [comment]
Looks like this may have been added with the "purge in prime tower" option, correct me if I'm wrong but if this is the case I can close this as completed!

**Comment by Surion79** [comment]
The functionality requires to calculate correct purge tower size depending on purge settings. If the tower has always the same size for all kind of prints, the functionality is not what is requested. So please do not close this until it is verified by multiple ercf users.ThanksAm 06.10.2023 um 02:00 schrieb Juniper Rueter ***@***.***>:﻿
Looks like this may have been added with the "purge in prime tower" option, correct me if I'm wrong but if this is the case I can close this as completed!

**Comment by brueter** [comment]
Looks like you may be correct, hopefully this will be easier with this new update though!

**Comment by Surion79** [comment]
Still requesting this festure. It is important for Single Extruder MMU

**Comment by CristianGTR97** [comment]
Please add this feature

**Comment by brueter** [comment]
Still wondering if this can be implemented, does anyone have ideas for getting this done?

**Comment by igiannakas** [comment]
I believe this already is implemented:

![image](https://github.com/SoftFever/OrcaSlicer/assets/59056762/7e90a592-00d1-437d-9c0b-3b49d6b32752)

![image](https://github.com/SoftFever/OrcaSlicer/assets/59056762/c644e4d5-74ce-4e73-a097-90c170936348)

The purge tower changes size depending on the purge volume needed. The purge volume needed can either be entered in the filament flushing volumes table or auto calculated based on filament colour.

See above - reducing the purge values reduces the amount of material on the prime tower. Same for the opposite. Clicking recalculate calculates these values based on colour.

**Comment by igiannakas** [comment]
There was a bug where the flush volumes were not displayed correctly in the prime tower statistics but this PR here fixes it: https://github.com/SoftFever/OrcaSlicer/pull/5223

**Comment by CombatVolcano** [comment]
Please. Do anything to improve this. 
Why do you hide the 'purging volumes' button EVER AT ALL EVER? EVER? EVER?

**Comment by igiannakas** [comment]
It’s not hidden - it’s in the flushing volume settings. What am I missing?
