### ISSUE TITLE
As of firmware 01.05.02.00 Playing Video will resize video window and push AMS controls off screen

### ISSUE THREAD

**Issue by ChaosBlades** [SoftFever/OrcaSlicer#1339]
**Describe the bug**
As of the firmware version that released today 01.05.02.00 starting the live camera will slightly widen the video player and cut off the AMS window. I tried closing and re-opening OrcaSlicer with the same result.

**To Reproduce**
1. Upgrade to latest firmware
2. Start Live View

**Screenshots**
![Screenshot from 2023-06-13 18-23-08](https://github.com/SoftFever/OrcaSlicer/assets/7530545/b991be1b-cf52-418b-bab3-087b910b6e5a)

**Printer model**
Bambu Labs X1 Carbon with AMS

**Desktop (please complete the following information):**
 - OS: Pop!_OS 22.04 LTS x86_64
 - Version 1.6.3

**Comment by ChaosBlades** [comment]
After starting another print I can't reproduce the issue. This issue may only occur on multi color prints. I'll keep testing.

**Comment by igiannakas** [comment]
> After starting another print I can't reproduce the issue. This issue may only occur on multi color prints. I'll keep testing.

Its happened to me before on MacOS even with the previous firmware - the firmware version has nothing to do with this but rather the gui layout.

**Comment by ChaosBlades** [comment]
I'm not able to reproduce this anymore even on multi color prints.

I'll leave it up to SoftFever on whether this get closed or or left open. It might be a Bambu issue.
