### ISSUE TITLE
Patterntype for Solid and top layer

### ISSUE THREAD

**Issue by TerrorzwergOlli** [SoftFever/OrcaSlicer#134]
Would be nice to implement something like SuperSlicer did:  The option to set line not to be connected to each other.
![image](https://user-images.githubusercontent.com/89738323/211170511-a3ba3c1f-52d4-4491-ac4e-04dada29f97e.png)

This realy  helps with top finish. Espacally in small areas.
Result looks like this:
![image](https://user-images.githubusercontent.com/89738323/211170551-71fec9c8-c452-4220-971d-857d9c0187ab.png)

**Comment by ShryuKt** [comment]
Hi,

I'm a big fan of those options
I already ask for them in #50

**Comment by pemerick07** [comment]
This is very helpful when trying to print strong dense parts that aren't over extruded at the interface between infill and perimeters.

**Comment by SoftFever** [comment]
You can achieve the same effect by changing `Top surface pattern` to `Monotonic line`
![image](https://user-images.githubusercontent.com/103989404/211228181-df80a019-4740-4ffa-93e9-97d78f71d4cf.png)

For comparison, this is `Monotonic`
![image](https://user-images.githubusercontent.com/103989404/211228109-65bcd467-f5d1-4a31-b7a1-f21be4423b2f.png)

**Comment by TerrorzwergOlli** [comment]
> You can achieve the same effect by changing `Top surface pattern` to `Monotonic line` ![image](https://user-images.githubusercontent.com/103989404/211228181-df80a019-4740-4ffa-93e9-97d78f71d4cf.png)
> 
> For comparison, this is `Monotonic` ![image](https://user-images.githubusercontent.com/103989404/211228109-65bcd467-f5d1-4a31-b7a1-f21be4423b2f.png)

I tried  this before (I thought maybe this is the option) but it haven't change anything
![image](https://user-images.githubusercontent.com/89738323/211228399-5eeab560-bfe6-4d92-a75a-d07b2199ac5f.png)

**Comment by TerrorzwergOlli** [comment]
funny enough: in the x1 profile it works

**Comment by TerrorzwergOlli** [comment]
@SoftFever I am unsing 1.4.2 and here is the project file maybe it is a bug?
[flow_test.zip](https://github.com/SoftFever/BambuStudio-SoftFever/files/10369910/flow_test.zip)
