### ISSUE TITLE
Unable to change speeds during print

### ISSUE THREAD

**Issue by shughey00** [SoftFever/OrcaSlicer#1341]
Unable to change speeds via Orca Slicer once print starts.
Example...started a print at 100% then changed speed to sport about 20 seconds into printing. Whent to reduce speeds maybe 10 minutes into printing but orca slicer will not allow this.You can select a different speed but it won't actauuly change.

**Comment by julie777** [comment]
It is working for me on Windows 10 with a P1P. (I am running in LAN only mode.)

**Comment by shughey00** [comment]
It comes and goes..depends sort of on the sequence I do it it seams. then again can always be a windows thing...I use the wifi
