### ISSUE TITLE
Disable arachne at the first layer

### ISSUE THREAD

**Issue by xcqq** [SoftFever/OrcaSlicer#1343]
The idea is comming when I get a bed first layer when I print a model. The brim and outer wall has a good quality, but the inner wall failed to stick plate.
Here is the example:
<img width="594" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/18913791/14b20b25-859b-4d0e-8fec-21cb5b12bfaa">
The brim and outer wall all using the default line width. But for the inner wall, the line width is changed to a smaller one because of the arachne wall gernerator. The line width is smaller than the nozzel width. In this case, the print start from inner wall, so it's hard for the inner wall to stick the print plate.
Maybe we can disable arachne at the first layer, and enable it for the following layer.

**Comment by julie777** [comment]
Just for my information, does arachne use the line width settings as a max and min, or use the nozzle size to create a max and min?

**Comment by xcqq** [comment]
> Just for my information, does arachne use the line width settings as a max and min, or use the nozzle size to create a max and min?

AFAIK, the slicer don't have this kind of checking. And maybe arachne need to use a wall width which smaller than nozzle size to improve the print quality?

**Comment by kylek29** [comment]
I've noticed a lot of quirks with Arachne, especially with the first layer. On some of my models, Arachne skips any "gap fill" procedures, creating pin-holes on the first layer.

So being able to selectively turn it off on the first layer might be a temporary solution -- I haven't found any setting that addresses these deficiencies, and it seems to be a well-known issue if you Google it.
