### ISSUE TITLE
Add printer screen text not displaying correctly on Ubuntu (Not a problem on Windows 10)

### ISSUE THREAD

**Issue by e-dreyer** [SoftFever/OrcaSlicer#1344]
**Describe the bug**
With the Ubuntu implementation the text in the "Add physical printer" scree is invisible or just not there. I as an experienced user from PursaSlicer and using OrcaSlicer on Windows 10, could still use it. But it could give problems for other users

**To Reproduce**
Add a new physical printer in Linux Ubuntu using the lastes AppImage and the text will be missing.

**Expected behavior**
That the missing label explaining the required input to be visiable

**Screenshots**
![image](https://github.com/SoftFever/OrcaSlicer/assets/87576808/ef73c891-2ef4-41df-8b2f-646f1d277e44)

**Printer model**
Creality CR6-SE (I don't think it is related to my printer or Klipper setup)

**Desktop (please complete the following information):**
 - OS: Linux
 - -  Version: Ubuntu 22.04.2 LTS

**Comment by neclimdul** [comment]
Tested this in 1.8.0 rc2 and its still broken. Can't tell what I'm suppose to add to the form to make it work.

**Comment by StayPirate** [comment]
This is happening to me as well on Archlinux and the official Appimage

**Comment by iromero91** [comment]
still happens on Debian 12 and the latest official Appimage, Forcing light mode just makes different text be invisible.

**Comment by StayPirate** [comment]
v2.1.0 fixed this problem for me on Archlinux.  If other people here confirm, then this issue can be closed.

**Comment by neclimdul** [comment]
Waiting for the appimage fix or the flatpak release then I'll test it. Kinda of hard to test on Ubuntu like the original report ATM.
