### ISSUE TITLE
Mainsail and Klipper interface in the Device tab freeze and become onrepsonsive.

### ISSUE THREAD

**Issue by e-dreyer** [SoftFever/OrcaSlicer#1345]
**Describe the bug**
The Mainsail Klipper interface stops working. It stil works in an external browser and on my phone. I just happens every now and then and I struggle to reproduce it

**To Reproduce**
Use the Mainsail config is the primary interface for the printer and then it eventually freezes. Especially when switching tabs

**Expected behavior**
I expect it to work perfectly just like the normal Web UI would work.

**Screenshots**
In this screenshot you can see many progress bars that have gone on for hours and I can't click anything. Restarting fixes it temporarily.
![image](https://github.com/SoftFever/OrcaSlicer/assets/87576808/2f898e3e-baad-4b8f-99ed-593a6caa0d44)

**Printer model**
Creality CR6 6E

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version Ubuntu 22.04.2 LTS

**Comment by properlypurple** [comment]
This actually happens with Octoprint as well, so it seems like this might have something to do with the embedded browser, and not any particular web interface.
