### ISSUE TITLE
Items in the "Print plate" roll down do nothing 

### ISSUE THREAD

**Issue by fleutot** [SoftFever/OrcaSlicer#1354]
**Describe the bug**
After slicing, I click on the down arrow beside the green button "Print plate". I then choose one option, for example "Export G-code file".

Nothing happens.

**Desktop (please complete the following information):**
 - Ubuntu 22.10, which uses gtk4. In window manager xmonad, which is non-reparenting.
 - OrcaSlicer 1.6.3

EDIT: the button text does change as expected in gnome.

**Comment by julie777** [comment]
@fleutot 
It is a terrible interface. When you select an item in the drop down, instead of being a menu item that does something like you expect, it is actually changing what the button does. The label in the Print Plate button should change to Export G-Code and then you have to click the button.

**Comment by fleutot** [comment]
I really wish that UI devs would refrain from doing their own UI design. I'm having loads of troubles with custom dropdowns, transparency, and what not. Right now I cannot use Bambu/OrcaSlicer in full screen, the dropdown menus don't show up. 

I wish for an option that makes the UI only use standard GTK elements. That would also be more respectful of the choices I make for my OS interface, and keep things consistent.

**Comment by fleutot** [comment]
I mean, this is cleay broken:

https://github.com/SoftFever/OrcaSlicer/assets/178409/176f0133-118d-4566-8735-871ffcb6daac
