### ISSUE TITLE
Prusa Slicer infill anchor length

### ISSUE THREAD

**Issue by errhoss** [SoftFever/OrcaSlicer#136]
I'm trying to print the Vector Finesse (https://shop.vectorfinesse.com/) open back headphones and it requires that infill anchor be set to 0 otherwise it connects the end of the infill and doesn't look or sound right. 

![image](https://user-images.githubusercontent.com/69829229/211178452-56a95a01-045c-4b6e-8642-e79053b73b71.png)
I'd like the "Length of the infill anchor" setting available in SoftFever. 

It will work if you slice in Prusa slicer and then print from SD card, but I can't do multi color and the quality is lacking.

This is what it looks like from Bambu studio/SoftFever
![image](https://user-images.githubusercontent.com/69829229/211178496-7bc9efa0-820c-4e14-a4b2-a5eba78a999c.png)

This is what it should look like with the infill anchor set to 0
![image](https://user-images.githubusercontent.com/69829229/211178507-630f7313-c687-4ae9-88e9-72f5d327e5ea.png)

**Comment by errhoss** [comment]
Just to be clear I'd like access to both "length of the infill anchor" and "maximum length of the infill anchor" if possible.

**Comment by millpreet** [comment]
me 3, encountered exact same issue.
