### ISSUE TITLE
Wrong Overhang Speed Detection with Classic Wall Generator  

### ISSUE THREAD

**Issue by lhndo** [SoftFever/OrcaSlicer#1363]
**Describe the bug**
Unwanted overhang detection/slowdown in classic slicing mode

**3mf File for This Bug**
[Y Front Try 3.zip](https://github.com/SoftFever/OrcaSlicer/files/11774232/Y.Front.Try.3.zip)

**To Reproduce**
Load the file, hit slice,
Switch Gcode preview mode to Speed. 
Observe strange slowdown.
Turn overhang speed detecting off, or switch wall mode to Arachne, slice and observe that the issue is gone.

**Expected behavior**
No false overhang triggers

**Screenshots**
![2023_06_16_2599_orca-slicer](https://github.com/SoftFever/OrcaSlicer/assets/42773937/089e1e3e-be48-4c47-9082-38dbe61a020e)

![2023_06_16_2600_orca-slicer](https://github.com/SoftFever/OrcaSlicer/assets/42773937/e2c60f7c-ae55-411d-8275-367f3b7a1f54)

**Printer model**
Ender 3

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 1.6.3

**Comment by midicdj1000** [comment]
I can confirm that when Classic wall generator is enabled overhangs are not calculated very well.
