### ISSUE TITLE
Change filament issue

### ISSUE THREAD

**Issue by Alexx40in** [SoftFever/OrcaSlicer#1377]
When adding a filament change command, another m600 command is added to the beginning of the g-code file, and an extruder change command is added to the change position.
When manually replacing the filament, this is a drive to that. that the extruder stops feeding plastic.
Please make it possible to carry out manual replacement of plastic extruder changes
P.S. Yes,
you can manually enter the m600 command, but you want to use a filament from another manufacturer that differs in diameter, temperature, etc. apply these settings after changing the filament

**Comment by Alexx40in** [comment]
> you can use any filament and temp but only one nozzle/filament diameter pls add a second to process and change the parameter. but nozzle diameter is in printer settings

I don't understand very well what you are asking me to do.

When adding a filament change command, PrusaSlicer inserts the m600 command
Orca slicer adds extruder change command T0 to start and filament change position T1
This does not take into account the fact that the printer does not have a second extruder.

**Comment by hyprodimus** [comment]
I found this bug too. When you add something like M600 to the Change Filament G-code section, it will add that command tot he start of the G-code which is pretty annoying.

**Comment by bhast2** [comment]
I have the same problem when I add the m600 code to the machine gcode it puts an m600 at the begin of the print and it tries to changes the filament after the purge line is printed
How can this be fixed??

**Comment by Bazeone** [comment]
I have the same issue and would like not to have to manually edit the file and remove the first M600 command.

**Comment by l8nite** [comment]
+1 on this issue, ran into it yesterday.

**Comment by Luigisvc** [comment]
Same issue here can I open a BUG report?, as appears no one from DEV noticed this topic here

**Comment by sguth-affirm** [comment]
@SoftFever fyi

**Comment by bpkenn** [comment]
I had the same issue today

**Comment by wmariz** [comment]
Workaround: https://github.com/SoftFever/OrcaSlicer/issues/2230#issuecomment-1750086127

**Comment by SoftFever** [comment]
Hey guys,

I can't repro the issue with the latest dev build.
Can you attach a project file?

**Comment by Bazeone** [comment]
> Hey guys,
> 
> I can't repro the issue with the latest dev build. Can you attach a project file?

[color_change_bin.zip](https://github.com/SoftFever/OrcaSlicer/files/12829390/color_change_bin.zip)

**Comment by bpkenn** [comment]
I reproduced the pause at the start by:

- Set Printer settings -> Machine G-Code -> Change filament G-code to value of "M600" or even "PAUSE"
- Add second filament
- change object color 2nd filament

I am assuming that since I'm manually swapping the filament, i already have the 2nd filament color loaded and ready to print, but Orca is assuming AMS type setup.  Is it possible to have a "manual MMU override" that will just run the change filament gcode only at the layers we add a filament change?

**Comment by Ocraftyone** [comment]
> Is it possible to have a "manual MMU override" that will just run the change filament gcode only at the layers we add a filament change?

I am currently working on a feature like this. Should hopefully be complete if a few days.

**Comment by ToXIc69** [comment]
> I have the same problem when I add the m600 code to the machine gcode it puts an m600 at the begin of the print and it tries to changes the filament after the purge line is printed How can this be fixed??

exactly my issue.. after the purge line (in my start macro) it runs my m600 which pauses and retracts filament.

**Comment by Bazeone** [comment]
still an issue with version 1.9.0.
quick workaround:
{if layer_z != 0}M600{endif}
{if layer_z != 0}G1 E0.4 F1500 ; prime after color change{endif}
for a Prusa.

**Comment by Luigisvc** [comment]
This bug is already solved, please check on your Orca 1.90 and mark this option below, this will correct the behavior for printers without multimaterial feeders. 

![image](https://github.com/SoftFever/OrcaSlicer/assets/21157066/46be4e35-d667-4487-97c5-0cd164a70700)


Also put a M600 command in the Machine Gcode . Or another command if you use klipper 

![image](https://github.com/SoftFever/OrcaSlicer/assets/21157066/dda8320f-3caf-4fb8-84f7-29ea4a127d0e)

**Comment by ToXIc69** [comment]
thanks ill try it out

**Comment by Naahuel** [comment]
> This bug is already solved, please check on your Orca 1.90 and mark this option below, this will correct the behavior for printers without multimaterial feeders.
> 
> ![image](https://private-user-images.githubusercontent.com/21157066/305579199-46be4e35-d667-4487-97c5-0cd164a70700.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MTYxNTgsIm5iZiI6MTcxMjcxNTg1OCwicGF0aCI6Ii8yMTE1NzA2Ni8zMDU1NzkxOTktNDZiZTRlMzUtZDY2Ny00NDg3LTk3YzUtMGNkMTY0YTcwNzAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDAyMjQxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkYzI5N2VhMzIzYjcxMTNlMmZiNjU2NWJkZTg1MTlmNWIzMDk4ZDA3OWI4N2RhMWM0NGZhOGFkOGU3NWM0OWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jXGoy0P_wv0VpdpdfFg8j3X6oh5v_vLA0wlLZ8NUHww)
> 
> Also put a M600 command in the Machine Gcode . Or another command if you use klipper
> 
> ![image](https://private-user-images.githubusercontent.com/21157066/305579555-dda8320f-3caf-4fb8-84f7-29ea4a127d0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MTYxNTgsIm5iZiI6MTcxMjcxNTg1OCwicGF0aCI6Ii8yMTE1NzA2Ni8zMDU1Nzk1NTUtZGRhODMyMGYtM2NhZi00ZmI4LTg0ZjctMjllYTRhMTI3ZDBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDAyMjQxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmNWYzNGY0ZWQzMmY2ODA4Mjg5OGM3MmQ2NWY5ZTEyNDI0YzhiNTNjMmFhMzY1NWEwYzU5Y2RhODhiZmM4ODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aJOqHonPk079Zsqnuc-hDWAbR_zOWTno771iwbAJYiw)

This fixed it for me on Orcaslicer 2.0.0, it drove me nuts. I had to manually remove the m600 command at the beginning, now it works as it should.
