### ISSUE TITLE
Crealtiy D1 Sermoon profile.

### ISSUE THREAD

**Issue by ripvega** [SoftFever/OrcaSlicer#1383]
I've just installed Orca and my printer is not in the list.

Where should I be looking for a profile to add?

If one is not available, does anyone here have a set of tested settings they could share?

Thank you.

**Comment by Joecowboy** [comment]
> I've just installed Orca and my printer is not in the list.
> 
> Where should I be looking for a profile to add?
> 
> If one is not available, does anyone here have a set of tested settings they could share?
> 
> Thank you.

Did you create a profile for your Creality Sermoon D1?  If so would you be able to share it?  This should be added to this repo.  Are you using Klipper with your Creality Sermoon?  If so, what are your Gcode Macros you setup for OrcaSlicer?  I know this is an old thread but never was answered.  Thanks inn advance.
