### ISSUE TITLE
Choose Starting Colour for Multi Colour Prints

### ISSUE THREAD

**Issue by WillJohns0n** [SoftFever/OrcaSlicer#1386]
If you have a print with multiple colours in the first layer, the slicer seems to select starting colour based on the purge volumes. I suggest an option to override this and so the user can choose the starting colour. This would be very useful for people who do multiple colour changes in the first few layers, allow to optimise which elements are printed first and minimise the number of filament changes without having to spoof the purge volumes.

I believe that Prusa Slicer selects the starting colour based on the order of the components in the object list. Something like this would be great in Orca Slicer

**Comment by eafq78** [comment]
and??
will be useful to add emboss text and use the first filament to do flush then emboss then change filament, in this way you only need to switch 1 time
