### ISSUE TITLE
TempTower in Calibrationmenu

### ISSUE THREAD

**Issue by John3Di** [SoftFever/OrcaSlicer#139]
i would like to see a etmptower in your calibrationmenu and maybe the ringing_tower.stl with ready2go configs.

thanks for you great fork!! i lost the superslicer and found something much better. :-)

**Comment by IkarusX1978** [comment]
not only the temptower is missing!
There are a lot more ...
Bed level test
CaliCat
3D Bechy
and so on ...

would be nice to s ee them soon in the best slicer of the world!
