### ISSUE TITLE
Need help building Orca Slicer on Windows

### ISSUE THREAD

**Issue by julie777** [SoftFever/OrcaSlicer#1390]
After previous attempts using VS 2022 which I already had installed, yesterday I decided to try and make it easy and follow the guide.
I installed VS 2019 community edition and did a git pull to make sure I was up to date. Then I removed all the remnants from previous build attempts. I followed the very sparse build instructions "build_release.bat" from an x64 native tools command prompt.

It was not easy and there needs to be more help in the instructions so that more people will be able to contribute to the project.

Building deps kept failing on openSSL. After struggling trying to understand how cmake works and how files are created and copied during the process I had wasted most of the day. (I have never used cmake before.) It would be nice if there was some documentation showing how to build individual components and how the entire build works.

After a break, and some googling, it occurred to me that I was seeing some crazy long paths in the build output. So I started over and cloned the project into a directory in the root. This shortened the paths significantly and the build seemed to be doing better. I was still having problems and I noticed that buried in the output was a note about perl not being able to create proper Windows style paths with '\'. That led to more searching and finding that although I had installed Strawberry Perl, git for windows perl was being used because Strawberry Perl was at the end of the path. I changed the PATH variable and got past that problem.

Notes:
- documentation needs to include requirement for Strawberry Perl and information about correcting the path. I expect that every Windows user will have the same problem because they will be using git for windows to clone the repo
- the build produces a massive amount of output, which is fine, but it does not stop when there is an error. This causes the build to fail hours later, and the error may still be in the command prompt buffer, but it may be gone because the buffer can only be configured to be 9999 lines long.
- the documentation needs to provide information to allow the user to change the number of processors used. Currently the build just creates so many processes that the CPU is pegged at 100% and doing anything else is difficult. This includes trying to search for information about how to fix build problems
- there should be a way to run the build at a lower (background) priority so that regardless of how many processes are running the foreground applications can be responsive

Now I have a build that appears to have completed, meaning that at the end of build_release.bat the last line has no error indicated. However, it also does not have a message saying the build completed okay. It ends with
```
  -- Up-to-date: C:/code/OrcaSlicer/build/OrcaSlicer/TKXSBase.dll
  -- Up-to-date: C:/code/OrcaSlicer/build/OrcaSlicer/freetype.dll
```

In addition, there are hundreds of warnings about truncation of double to float, size_t to int64, macro redefinition, reinterpret_cast, and others. There are also warnings in the crypto code build. I have no idea if I have a usable build or not. Given that I am building on 64 bit Windows and using the x64 native tools command prompt, I would not expect all the type errors.

There are other warnings, such as `warning C4129: '/': unrecognized character escape seq
uence [C:\code\OrcaSlicer\build\src\slic3r\libslic3r_gui.vcxproj]` and many that scrolled off the screen.

Note:
- documentation needs to provide information about build commands, such as "make clean" and using `tee` to capture the output.
- the documentation should describe where build artifacts get put
- the documentation should show how to build a debug version and run it in the debugger

I will not count the days I wasted trying to build with VS2022, but I am on day 2 trying to do it the easiest way possible and it is still not easy, like it could be.

**Comment by fr3ak2402** [comment]
@julie777 

I can't get this to work either, for a week....

Have already tried many things, a VM, different computers... each time I get errors when running and always different ones.

No idea that also not under VS 2019....
