### ISSUE TITLE
Exclude object on Bambu

### ISSUE THREAD

**Issue by rkarlsba** [SoftFever/OrcaSlicer#1394]
I own a Bambu X-1 Carbon with an AMS and it'd be very nice to see exclude object or similar in OrcaSlicer. Is this possible to implement?

**Comment by abstractFlo** [comment]
exclude objects has nothing to do with the slicer the slicer only labled the objects and the printer firmware can evaluate this and make some exclusions.

The Bambu Printer does not have this feature like any other popular klipper based printer

**Comment by kylek29** [comment]
As abstractFlo said, that needs a firmware change on the X-1C printers. It's a feature I've wanted to (to be able to select per-object reprints). The way it'd work (I'd assume) is that the Slicer would drop a hint in the GCode to segment the file between objects (I *think* it already has this ability or does this anyways) and the firmware would handle the rest.

I'd suggest making the suggestion here: https://forum.bambulab.com/

**Comment by Schokobecher** [comment]
This is now available in [BambuStudio v1.7.0](https://github.com/bambulab/BambuStudio/releases/tag/v01.07.00.53).
The printer needs to be on FW V01.06

**Comment by Schokobecher** [comment]
The mentioned firmware and BambuStudio version is now out of Beta

**Comment by rkarlsba** [comment]
Any idea how to update the printer?
<img width="934" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/4253147/71c0d3a4-bb7d-44b7-9cd6-a86e9a8281bd">

**Comment by rkarlsba** [comment]
Never mind - I rebooted the printer and it found it.

**Comment by rkarlsba** [comment]
But I can't find a way to cancel an object. Nothing in the GUI - nothing I can find anywhere.

**Comment by Schokobecher** [comment]
I'm pretty sure the current version of OrcaSlicer hasn't back ported the feature yet

**Comment by drewrox2009** [comment]
first time i needed this feature, it notifies me that i need a newer version of bambu slicer.

**Comment by rkarlsba** [comment]
AFAICT, there's no way to ignore/exclude objects from either BambuStudio nor OrcaSlicer. The possibility is there, though, on the printer console and in BambuHandy. This would be very nice to get into OrcaSlicer, since I obviously need it sometimes (like just now when things started to peel off th ebuildplate at layer five or something - just dirty buildplate, but some of those 12 objects could have been saved).

**Comment by rkarlsba** [comment]
This must be reopnened and fixed. It doesn't fix anything that the bug report is old.
