### ISSUE TITLE
More Advanced Internal Solid Infill Control

### ISSUE THREAD

**Issue by ruredi87** [SoftFever/OrcaSlicer#1396]
**Is your feature request related to a problem? Please describe.**
Yes. Orcaslicer adds unnecessary internal solid infill near walls. Infill prints last in order, so it does not needed near sloping walls. It causing waste of time and material. Some times slicer creating internal infill using rectelinear pattern. This causes even more time to print.

**Describe the solution you'd like**
Superslicer solves it with "NO SOLID INFILL OVER : X WALLS" option. This option causes to more advanced control of internal solid infill. If we use value of "1" slicer does not add solid infill over 1 perimeter. This solves problem.

![no internal infill superslicer](https://github.com/SoftFever/OrcaSlicer/assets/79092546/990497a9-53d1-413d-a69d-0b9a12da9812)
![Orca slicer internal infill](https://github.com/SoftFever/OrcaSlicer/assets/79092546/51782f12-36fb-4eaa-a97e-21d89ed929aa)
![solution](https://github.com/SoftFever/OrcaSlicer/assets/79092546/47cc7364-70ad-41db-b5de-4bedb34cff79)

[Cat_bowl_deep internal infill test.zip](https://github.com/SoftFever/OrcaSlicer/files/11827363/Cat_bowl_deep.internal.infill.test.zip)

**Comment by tome9111991** [comment]
You have tried to disable infill_anchor ?

**Comment by ruredi87** [comment]
> You have tried to disable infill_anchor ?

I tried, it does not work. Only way to prevent from it to disable infill completely .

**Comment by rlabusiness** [comment]
I believe I'm having surface quality issues caused by this as well. The extra solid infill printed over top of sparse infill when the outer surface is a slope appears to build up one layer at a time and cause inconsistencies in the surface/outer wall (photo attached).

![Screen Shot 2024-01-01 at 2 14 47 PM](https://github.com/SoftFever/OrcaSlicer/assets/6774974/fb7ba85f-c154-4758-b827-a5fb07c3e04a)

**Comment by mstrblueskys** [comment]
> > You have tried to disable infill_anchor ?
> 
> I tried, it does not work. Only way to prevent from it to disable infill completely .
> 
> You can see on superlicer screenshot. Infill anchor is enabled but ss doesnot generate internal solid infill which respects to "NO SOLID INFILL OVER : X WALLS"

How do you disable solid infill completely?
