### ISSUE TITLE
Adding a post processing script causes the profile to be deleted on next restart

### ISSUE THREAD

**Issue by quantumfrost** [SoftFever/OrcaSlicer#1397]
Like the title says , if you add a script to the "post-processing scripts" section in a process profile, the profile's json file is deleted on the next restart.

A profile should never be deleted without user consent under any circumstance. If there is a problem reading it due to a bug or malformed json, it should be marked invalid or moved to a different directory.

**Comment by foreachthing** [comment]
And I thought I was going carazyyy!!! 😵
