### ISSUE TITLE
Spiral vase mode for objects

### ISSUE THREAD

**Issue by Alexx40in** [SoftFever/OrcaSlicer#1399]
I really like the ability to place my project on several plates

However, if the project has a model that prints in spiral vase mode, I can't include it in the project
Please add the ability to add a spiral vase mode to individual objects with a condition: that this is the only object on the plate

And one more wish. I would like to apply the settings not only to individual objects, but also to a separate plate as a whole

**Comment by Dynom** [comment]
Upvoted. Currently the workaround is creating two projects, one with vase mode and one without. Which works, but the multi-plate system works so well for multi-part projects, that it would be fantastic to have this as a per-plate option.

**Comment by LupusTheCanine** [comment]
That would be great.

**Comment by B-Man1** [comment]
Please implement this. It would be great
