### ISSUE TITLE
[FR] Disable Thumbnail

### ISSUE THREAD

**Issue by foreachthing** [SoftFever/OrcaSlicer#1400]
#### Describe the solution you'd like
I'd like to be able to disable the thumbnail generator. Since our printer does not support it and we only print from SD-card, we don't need thumbnails.

#### Describe alternatives you've considered
* Manually removed the thumbnail code from gcode files.
* changed thumbnails size to 0x0 -> Error.
* changed thumbnails size to 1x1 -> still produces code.

#### Printer
* Ultimaker 2

**Comment by cron410** [comment]
![image](https://github.com/SoftFever/OrcaSlicer/assets/3082899/d62e1234-1f40-4f03-8df7-9f7c1c21a1a1)

This seems to work for me. 

When I export the gcode, there's no encoded image within the file, the whole THUMBNAIL_BLOCK is gone.

**Comment by foreachthing** [comment]
@cron410 , ok!!! Now I feel silly ... because that's what I tried first. But OrcaSliced did not let me remove this value. Now it works ...
Thanks!
