### ISSUE TITLE
Windows 7 x64 SP1 support 

### ISSUE THREAD

**Issue by trengtor** [SoftFever/OrcaSlicer#1401]
Hi

Could you add W7 x64 SP1 support?

**Comment by TexZeTech** [comment]
Hi trengtor,

Honestly, if you are using Windows 7 in 2023 I would recommend dumping it and going to some flavor of Linux like [Ubuntu LTS 20.04.2](https://ubuntu.com/download/desktop/thank-you?version=22.04.2&architecture=amd64) just so you don't have to worry about security. 

I will also take a wild guess here and say I don't think anyone is going to want to port this to Windows 7 as that OS had its support end in 2020 so it is way end of life at this point.
