### ISSUE TITLE
OrcaSlicer shows nothing when connecting to Fluidd web interface

### ISSUE THREAD

**Issue by pandel** [SoftFever/OrcaSlicer#1403]
Hi!

I am running fluidd (https://github.com/fluidd-core/fluidd) in a Docker container on a Synology NAS, which connects to Moonraker on a Raspberry Pi. If I set the web URL (the same I use in a normal web browser) for fluidd under "Device UI" I only get a white page with nothing on it. I am running on latest Klipper and Moonraker. fluidd per se is working great, it simply does not show inside OrcaSlicer.

OrcaSlicer with Mac OS Ventura 13.4.1.

Regards,
Holger

**Comment by TexZeTech** [comment]
I'm willing to bet it's the same bug I opened https://github.com/SoftFever/OrcaSlicer/issues/920

**Comment by FryGuyFlies** [comment]
Having this issue on a rooted KE.
