### ISSUE TITLE
OSX doesn't like the insides of the 1.6.3 signed zip

### ISSUE THREAD

**Issue by ccoupe** [SoftFever/OrcaSlicer#1406]
After unzipping the download and double clicking the file, osx says it cannot check it for malicious software. There are no obvious ways to get around the problem.

 Mac Mini M1 , 13.4.1 (22F82)

**Comment by atl285** [comment]
Do right click on the App-Icon and choose **open**. Then dismiss the dialog and do right click on the App-Icon again and choose **open** again. Now a 3rd option should allow open the App.

**Comment by ccoupe** [comment]
@atl285 Thank You. I hope I can remember this.
