### ISSUE TITLE
Divide by Zero error using lightning infill when extrusion widths are set to 0. Was resolved in prusa 2.5.0

### ISSUE THREAD

**Issue by dvomang** [SoftFever/OrcaSlicer#1410]
**Describe the bug**
When trying to use lightning infill with extrusion widths set to zero, an error occurs saying divide by 0 error.

**3mf File for This Bug**
If it is related to slicing, please append the 3mf file. It could be extremely helpful to solve the issue.

**To Reproduce**
0 for extrusion widths, lightning infill

**Expected behavior**

**Screenshots**

Here is the prusaslicer thread on the issue and the fix.

https://github.com/prusa3d/PrusaSlicer/issues/8437

**Comment by sleewok** [comment]
I am getting this error as well on v1.7
