### ISSUE TITLE
Auto Orient / Rotate model on import

### ISSUE THREAD

**Issue by iitsalex** [SoftFever/OrcaSlicer#1412]
**Is your feature request related to a problem? Please describe.**
Superslicer has a feature to auto-orient / rotate models on import. It's very handy for those of us who use different infill angles than 45 degrees.

**Describe the solution you'd like**
A printer setting to set the angle at which models should be imported at.

**Describe alternatives you've considered**
No real alternatives besides manually rotating every single model I import (no bueno).

**Additional context**

![image](https://github.com/SoftFever/OrcaSlicer/assets/20635452/db7fb06f-6994-4472-956d-4bfd232f056f)
![image](https://github.com/SoftFever/OrcaSlicer/assets/20635452/84ba23ee-60da-4d73-9bbc-0bf0ab3aeedd)

**Comment by tastyratz** [comment]
I would really love to see this as well! Especially since we can't perform what seems like ANY bulk or repeat operations on parts by selecting all at once from what I can tell.

**Comment by iitsalex** [comment]
Started work on this. Have it working already. Just making some minor changes before putting it in CR.

**Comment by iitsalex** [comment]
Just updated the CR for latest build.
