### ISSUE TITLE
Zhop/Lift Z - options to select when it is active

### ISSUE THREAD

**Issue by jeremytodd1** [SoftFever/OrcaSlicer#1419]
**Is your feature request related to a problem? Please describe.**
Disabling zhop entirely is a great way to eliminate stringing as well as shortening the print time by a considerable amount. The downside is that doing this will leave marks on top layers as the doesn't lift at all.

**Describe the solution you'd like**
Both SuperSlicer and PrusaSlicer have solutions that allows you to change when zhop is active.

SuperSlicer:
![zhop](https://github.com/SoftFever/OrcaSlicer/assets/6227771/ca55df4e-8943-4fde-808f-fcd0a2a64a84)

PrusaSlicer:
![zhopprusa](https://github.com/SoftFever/OrcaSlicer/assets/6227771/13f623a2-8504-46cd-9210-471503933cff)

Currently SuperSlicer has an extra option to set it for "only on top (layers)" which is perfect. Having that variable available would be amazing as well.

**Comment by gbyleveldt** [comment]
I’ve reported this before - I hope it’ll be implemented soon. But I’m seeing other more important issues they’re trying to sort out

**Comment by leandrolima-nyc** [comment]
The matter was previously addressed in issue #741, but no actions have been taken thus far.  You presented a more effective report, the issue should be merged rather than closing it outright.
