### ISSUE TITLE
Windows waking from sleep mode will cause Orca Slicer dark mode to be disabled

### ISSUE THREAD

**Issue by megablue** [SoftFever/OrcaSlicer#1424]
**Describe the bug**
Windows waking from sleep mode will cause Orca Slicer dark mode to be disabled

**To Reproduce**
turn on dark mode on orca slicer, put windows to sleep, wake it up, dark mode is gone and unchecked in the option.

Windows 11 Pro 22H2.

**Comment by hendrikhaehnel** [comment]
Probably related:
https://github.com/bambulab/BambuStudio/issues/1889
https://github.com/bambulab/BambuStudio/issues/1738
