### ISSUE TITLE
Gcode Printer Start

### ISSUE THREAD

**Issue by seven-sam** [SoftFever/OrcaSlicer#1426]
Hi,

I am using this starter code on SuperSlicer

START_PRINT EXTRUDER_TEMP={first_layer_temperature[initial_extruder] + extruder_temperature_offset[initial_extruder]} BED_TEMP=[first_layer_bed_temperature] MATERIAL=[filament_type] CHAMBER=[chamber_temperature] SIZE={first_layer_print_min[0]}_{first_layer_print_min[1]}_{first_layer_print_max[0]}_{first_layer_print_max[1]} INITIAL_TOOL={initial_extruder}

I would like to use it here, but I have an error, because I imagine that it is not the same variable or syntax.

is there a list of all this?

THANKS

Sam

**Comment by TexZeTech** [comment]
This is what mine uses 

```START_PRINT EXTRUDER_TEMP=[nozzle_temperature_initial_layer] BED_TEMP=[bed_temperature_initial_layer_single]``` 

I'm also assuming you are using klipper & using a very basic open-frame single extruder printer with just a hot end and heated bed. 

I also don't know what the macro on your printer looks like.

I would recommend looking at things like the Voron start code and the like.

I agree though a list of variables would be nice. 

I think the list from [Bambu's wiki](https://wiki.bambulab.com/en/p1/manual/extension-board-gcode-placeholder-reference) should be relevant.... maybe.
