### ISSUE TITLE
[FR]Fan Speedup at Overhangs/Bridging

### ISSUE THREAD

**Issue by tome9111991** [SoftFever/OrcaSlicer#143]
Hello,
i'm looking for a feature to increase the fan speed before a overhang or briding starts.
maybe you can set a time 2sec or 5mm for exemple. depending on what is easier to implement.

within these values ​​the fan started 2sec or 5mm before.

**Comment by psiberfunk** [comment]
What you're looking for here is really the fan spin-up / prespin setting from SuperSlicer I think:   https://github.com/supermerill/SuperSlicer/issues/157  
**printer -> fan startup delay**

**Comment by psiberfunk** [comment]
e.g. this would ideally be ported from there, and so @SoftFever doesn't have to re-write it from scratch.

**Comment by tome9111991** [comment]
yes works nice in susl

**Comment by leofaoro** [comment]
I raised this issue in the BS github: https://github.com/bambulab/BambuStudio/issues/978
