### ISSUE TITLE
ASW-X2 - filament sensor doesn't work as expected

### ISSUE THREAD

**Issue by sakomoto987** [SoftFever/OrcaSlicer#1432]
**Describe the bug**
When the printer is running out of filament, the print fails after providing a new spool of filament.
All my four ASW-X2 has the same issue. 

**To Reproduce**
Launch a print
Cut the filament to switch the filament detector to red
Feed new filament
Play the print
Observe the printer doing wrong.

**Expected behavior**
We expect the noozle go to the last position when the filament was running out

**Printer model**
ASW-X2 : Artillery Sidewinder X2

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Version: the lastest.

**Comment by cron410** [comment]
This sounds like a Klipper config issue (assuming you use it), or more specifically a Klipper macro issue.
