### ISSUE TITLE
Crash report on quit application

### ISSUE THREAD

**Issue by Macmagoo** [SoftFever/OrcaSlicer#1434]
**Describe the bug**
Closing the OrcaSlicer application gives a crash report.

**3mf File for This Bug**
It is not related to slicing.

**To Reproduce**
Close the application.

**Expected behavior**
Application closes and doesn't produce a crash report.

**Screenshots**
![Screenshot 2023-06-27 at 13 32 57](https://github.com/SoftFever/OrcaSlicer/assets/90116319/7896e2b5-65db-41f5-bf98-897f87aa538e)

**Bambu X1C**

**Desktop (please complete the following information):**
 - OS:  iOS
 - Version Ventura 13.4.1

**Comment by Mario-vminion** [comment]
i had the same ... on the m1
