### ISSUE TITLE
[Feature Request] Port Organic Supports from PrusaSlicer

### ISSUE THREAD

**Issue by meltiseugen** [SoftFever/OrcaSlicer#1436]
**Is your feature request related to a problem? Please describe.**
I would like to use the organic supports from PrusaSlicer in OrcaSlicer

**Describe the solution you'd like**
Have a new option for support type tree -> support style -> organic

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Dustmuffins** [comment]
These are known as Tree supports in Orcaslicer

**Comment by stonemandave** [comment]
You will need to tweak the settings quite a bit to imitate Prusaslicer.

**Comment by YanceyA** [comment]
> These are known as Tree supports in Orcaslicer

Organic supports are an evolution and different from tree supports in Orcaslicer (which are ported from Cura). Organic should be ported over when the developer has time to review and pull the 2.6 Prusaslicer changes into the Orcaslicer code. 2.6 has heaps of great features to pull over.

**Comment by Dustmuffins** [comment]
> Organic supports are an evolution and different from tree supports in Orcaslicer (which are ported from Cura).

After messing around with tree supports more in Orcaslicer, I see what you mean. The organic supports in Prusaslicer are much nicer to use and easier to remove.

**Comment by YanceyA** [comment]
I would be willing to offer a modest bounty [~100usd] for this feature port if it could be implemented "soon".

**Comment by eugenmeltis3pg** [comment]
> I would be willing to offer a modest bounty [~100usd] for this feature port if it could be implemented "soon".

I would top that with another 50usd.
So now, it would be 150usd for the organic supports.

**Comment by SoftFever** [comment]
Hey guys,

Out of curisity, have you guys got a chance to try the slim tree style? 
@eugenmeltis3pg @YanceyA @Dustmuffins 
![image](https://github.com/SoftFever/OrcaSlicer/assets/103989404/665d45c8-a6b4-4ca1-aa2e-ae5feccd5934)

**Comment by Dustmuffins** [comment]
When I slice with that style, I get unsupported areas with printing in thin air due to not having any interface.

![image](https://github.com/SoftFever/OrcaSlicer/assets/17961638/40731faf-213c-4d56-af04-395559bc739c)

But I do get properly supported sections using my above settings:

![image](https://github.com/SoftFever/OrcaSlicer/assets/17961638/08894abc-8407-4872-a2c4-50cc7986a542)

**Comment by Dustmuffins** [comment]
Another bit of info I'd like to add on why I think Organic supports are a worthy inclusion:

I frequently get these strange bugs with the ported Cura Tree supports in Orcaslicer:

![image](https://github.com/SoftFever/OrcaSlicer/assets/17961638/d549d823-9961-4765-bd1e-ad15464bb1c2)

While Prusaslicer doesn't do this:
![image](https://github.com/SoftFever/OrcaSlicer/assets/17961638/6a1de982-462d-4501-b968-6bf8652f8ab4)

One thing I definitely prefer about the tree supports is the ability to use variable layer height, which organic doesn't support in Prusaslicer. 
![image](https://github.com/SoftFever/OrcaSlicer/assets/17961638/8db5519d-c612-4a4c-9a7b-9079293afc7e)


If there was a way to modify organic to be able to do this, that would be the perfect support for 90% of my cases IMO. It may be prohibitively difficult though, or else I'd imagine prusaslicer would already do it.

However, as great as Prusaslicer is, Orcaslicer is just so incredible so I've been putting up with this slight annoyance 😁
