### ISSUE TITLE
slicing is extremely slow on X1C and CR M4 with sonic pad

### ISSUE THREAD

**Issue by thenabizzy** [SoftFever/OrcaSlicer#1441]
The slicing process has gotten very very slow for these 2 printers. I am unsure if I need to clear cache or upgrade something. I have a 5900X, RTX 3090 and 128GB DDR4 ram. 

Is there somewhere I can clear cache or something? I have restarted the application and the computer to no avail.

**Comment by SoftFever** [comment]
How large is the model?
