### ISSUE TITLE
Incomplete/buggy slicing of models

### ISSUE THREAD

**Issue by SgtBaxter** [SoftFever/OrcaSlicer#1447]
**Describe the bug**
When slicing certain models in 1.6.3, holes appear in the models in walls. 

**3mf File for This Bug**
If it is related to slicing, please append the 3mf file. It could be extremely helpful to solve the issue.

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**
I expect the models to slice as they appear in Bambu Studio 1.6.2.4, which slices the same file correctly.

**Screenshots**
Attached, comparison between Orca 1.6.3 and Bambu Studio 1.6.2.4

**Printer model**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version [22H2](url)
[Darth_Vader_Lightsaber.zip](https://github.com/SoftFever/OrcaSlicer/files/11926156/Darth_Vader_Lightsaber.zip)

![Orca Slicer](https://github.com/SoftFever/OrcaSlicer/assets/138307292/0915befa-4390-4d6f-8d9a-f2a806f0be73)
![Bambu Slicer](https://github.com/SoftFever/OrcaSlicer/assets/138307292/20c37416-f106-4b4e-8d46-2ea30efd1b45)

**Comment by fourtwizzy** [comment]
Maybe try the latest nightly build, found [here.](https://github.com/SoftFever/OrcaSlicer/suites/13981754607/artifacts/779840870)

I'm not having the same issue with Orca Slicer  v1.6.3 nightly

![Screenshot](https://github.com/SoftFever/OrcaSlicer/assets/1735941/dff20032-bbda-4dc7-83bd-e27c13e05a9b)

**Comment by RadsWa** [comment]
I am also seeing this but to a much greater extent, and only on the 1.6.3 official release, it is not happening in the beta.
the one with the gaps in the middle is the release version.

![Screenshot 2023-07-05 110848](https://github.com/SoftFever/OrcaSlicer/assets/73009320/ce757914-33a4-41e4-a631-22c98744cb07)
This is how is should look.
![image](https://github.com/SoftFever/OrcaSlicer/assets/73009320/6b624dce-5181-4d91-8f4e-5052f3fa36eb)
 I have not tried to print it to see if its graphical or actual as yet.

**Comment by SgtBaxter** [comment]
I can confirm that it does print as displayed. Unfortunately, I tossed the
pieces and realized I didn't take photos of them.
