### ISSUE TITLE
[Feature Request] Increase layer time without slowing down the print speed

### ISSUE THREAD

**Issue by Festivejelly** [SoftFever/OrcaSlicer#1457]
**Is your feature request related to a problem? Please describe.**

Print artefacts shows on black PLA if slowing down the print...and it turns shiny.

I get optimal results on around 150mm/s on the outer wall.

If the layer time is less than 10 seconds then more artefacts show up in the print.

Here in comes in the issue.... how do you keep printing at a high speed but also have the layer time stay above 10 seconds without slowing down.

**Describe the solution you'd like**

Maybe its possible to re trace the inner walls without printing any material, but keeping the fans on. Which will result in cooling and keeping the layer time above a specified amount.

This way even really small parts could get the same amount of cooling time as bigger parts without needing to slow down the toolhead when its printing. This should result in a more uniform look to the layers at least with black PLA.

**Describe alternatives you've considered**
I've tried keeping the layer time high by increasing the infill ratio/and/or infil print speed for those layers. Its a very manual process and results in wasted material.

**Additional context**
Ive done some testing on my hypothesis of altering the layer time without altering the speed. I did this by increasing the infill. 
![image](https://github.com/SoftFever/OrcaSlicer/assets/2408274/583f1c6a-f45a-4bce-bafb-c0e227916cdb)

**Comment by kylek29** [comment]
Orca has the setting "Slow Print Down for Better Layer Cooling" in Filament -> Cooling. 

I think PrusaSlicer has something like this (minimum layer time), but with a minimum time value you can set (not positive). You might try to find that feature in PS and if it exists, you post back here so maybe someone can port it.

**Comment by Festivejelly** [comment]
The problem with slowing down is that it introduces artefacts. The cura implementation kinda works... but I think a better solution would be to slowly move the head across the inner wall to pad out the layer time so the smaller features still have large enough layer time without needing to slow down the printing movements.

**Comment by kylek29** [comment]
> The problem with slowing down is that it introduces artefacts. The cura implementation kinda works... but I think a better solution would be to slowly move the head across the inner wall to pad out the layer time so the smaller features still have large enough layer time without needing to slow down the printing movements.

Yeah, it's always odd having two differing methods, both with advantages / disadvantages and dependent on their individual software. Possibly a implementation similar to Cura's method, but with a toggle to switch between the two (kinda like you can switch between Arachne/Classic). There are a few other features like this I've come across where Cura does it differently.

**Comment by Festivejelly** [comment]
> Yeah, it's always odd having two differing methods, both with advantages / disadvantages and dependent on their individual software. Possibly a implementation similar to Cura's method, but with a toggle to switch between the two (kinda like you can switch between Arachne/Classic). There are a few other features like this I've come across where Cura does it differently.

Moving away from the print at an ideal time might work... but I think my idea of kinda coasting on the inner wall would solve the oozing issues and would ensure the part is evenly cooled.

Ive manged to do this by manually editing the gcode and it has the desired effect but its a pain in the backside to do and requires a lot of copy pasting.

Maybe implementing both would be an advantage.

"Coast over inner perimeter" : "Coast over inner perimeter to cool print if layer time less than X"
"Move away from print" : "Move away from print if layer time less than X"

If I get some free time soon ill have a crack at implementing it.

**Comment by santelelle** [comment]
I am having the same issue presented here.
Would be a big fan of the "Move away from print" (and retract filament) option, which should not be too hard to implement.

**Comment by Festivejelly** [comment]
FYI ive also raised this on the Bambu Slicer github:

https://github.com/bambulab/BambuStudio/issues/2126#issuecomment-1683338980
