### ISSUE TITLE
Add a translation into Russian.

### ISSUE THREAD

**Issue by stasyan68** [SoftFever/OrcaSlicer#1462]
Translation files in the attachment. Thanks
[RU.zip](https://github.com/SoftFever/OrcaSlicer/files/11950030/RU.zip)

**Comment by iStarComLab** [comment]
> Translation files in the attachment. Thanks
> [RU.zip](https://github.com/SoftFever/OrcaSlicer/files/11950030/RU.zip)

Thank you for your hard work! Checked on 1.6.3 everything is ok!

**Comment by stasyan68** [comment]
> > Файлы перевода во вложении. Спасибо
> > [RU.zip](https://github.com/SoftFever/OrcaSlicer/files/11950030/RU.zip)
> 
> Спасибо вам за вашу тяжелую работу! Проверено на 1.6.3, все в порядке!


I failed to build binaries for Windows. Can you help?

**Comment by iStarComLab** [comment]
> > > Файлы перевода во вложении. Спасибо
> > > [RU.zip](https://github.com/SoftFever/OrcaSlicer/files/11950030/RU.zip)
> > 
> > 
> > Спасибо вам за вашу тяжелую работу! Проверено на 1.6.3, все в порядке!
> 
> I failed to build binaries for Windows. Can you help?

Sorry, but I only use Macos!

**Comment by Alexx40in** [comment]
> Translation files in the attachment. Thanks [RU.zip](https://github.com/SoftFever/OrcaSlicer/files/11950030/RU.zip)

Создал папку RU, положил туда файлы - в списке языков русский не появился
___
I created a folder RU, put files there - Russian did not appear in the list of languages

**Comment by stasyan68** [comment]
> > Файлы перевода во вложении. Спасибо [RU.zip](https://github.com/SoftFever/OrcaSlicer/files/11950030/RU.zip)
> 
> Создал папку RU, положил туда файлы - в списке языков русский не появился
> 
> Я создал папку RU, поместил туда файлы - русский не появился в списке языков

Это так не работает, нужно скомпилировать .EXE, а перед этим добавить данные файлы в исходный код. у меня не получается(

**Comment by iStarComLab** [comment]
та же тема https://github.com/SoftFever/OrcaSlicer/issues/757

**Comment by iStarComLab** [comment]
РЕШЕНО!
