### ISSUE TITLE
wall_infill_order behaving incorrectly, flips wall order

### ISSUE THREAD

**Issue by unixcarbide** [SoftFever/OrcaSlicer#1473]
**wall_infill_order behaving incorrectly, flips wall order**
When using `wall_infill_order` in the `outer/inner/infill` or `inner/outer/inner/infill` settings, the settings are reversed at various laayers, nearly randomly.

The result can produce stripes of a sort of *blob-banding*, whereby the layer inner/outer order is reversed for one layer.
These *blob-bands* do not continue around the entire print, they just taper out.

https://github.com/SoftFever/OrcaSlicer/assets/130264439/738d9546-95ff-485e-92af-f8f65488f1b1
<img width="865" alt="Screenshot 2023-07-05 at 11 00 15 PM" src="https://github.com/SoftFever/OrcaSlicer/assets/130264439/bebaf5b1-4454-4a89-834c-923d7d414477">
<img width="864" alt="Screenshot 2023-07-05 at 11 00 29 PM" src="https://github.com/SoftFever/OrcaSlicer/assets/130264439/d474d51f-8c14-4b21-8054-93d55d9350a6">
<img width="867" alt="Screenshot 2023-07-05 at 11 00 45 PM" src="https://github.com/SoftFever/OrcaSlicer/assets/130264439/b71646b3-b419-40c9-8eeb-0f30e6bfba70">
<img width="854" alt="Screenshot 2023-07-05 at 11 01 03 PM" src="https://github.com/SoftFever/OrcaSlicer/assets/130264439/45da9b8a-3b60-459b-b5ee-57c1077fc437">

**3mf File for This Bug**
With a seam on the "back", it is easy to flip through the `wall_infill_order` settings, and to see all the various unretract and seam positions.
[1cm_tower_with_seam.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/11963771/1cm_tower_with_seam.3mf.zip)

**To Reproduce**
Steps to reproduce the behavior
Load a file like the tower with seam I have attached.
[tower_with_seam.stl.zip](https://github.com/SoftFever/OrcaSlicer/files/11963775/tower_with_seam.stl.zip)
Set the seam to "Back", (or any big flat vertical wall).
Try different settings of `wall_infill_order`, what OrcaSlicer shows in the sliced view, will print with *blob bands*.

**Expected behavior**
The `wall_infill_order` setting `outer/inner/infill` behaves exactly as expected, (in contrast to `inner/outer/infill` which does not behave as expected).

Here is an image just after I figured this out:
![IMG_4594](https://github.com/SoftFever/OrcaSlicer/assets/130264439/abc779a9-0904-4532-b3c6-50c53b2bbc36)

**Screenshots**
bad,
<img width="833" alt="Screenshot 2023-07-05 at 3 39 14 PM" src="https://github.com/SoftFever/OrcaSlicer/assets/130264439/3e9c09f0-12cf-4b99-b88e-4d56ee633a00">
good,
<img width="899" alt="Screenshot 2023-07-05 at 5 41 06 PM" src="https://github.com/SoftFever/OrcaSlicer/assets/130264439/750559ce-9a12-4960-b3cc-e9f3dc5d3aea">

**Printer model**
FLSun SR, stock-ish V6 hotend with volcano nozzle.  Extruder is a bowden setup, with OMG v2 extruder.
Running Klipper.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 13.2.1
 - OrcaSlicer 1.6.3

**Comment by unixcarbide** [comment]
One anecdotal note, (I have not replicated for this test):

After looking back at some old prints, when I was a SuperSlicer user, I found exactly the same artifacts in box like objects.  I believe this could be an issue going back to some common ancestor in the software.

**Comment by The760** [comment]
I am having a very similar issue in #1468 

I went back into the slicer to check for anything weird going on around certain layers, and it seems that the issue is indeed that the wall order is getting flipped around from what I have it set on.

**Comment by Noisyfox** [comment]
I think this is an issue of the Arachne wall generator. I could not reproduce this issue using Classic.
