### ISSUE TITLE
Pressure Advance;  Enhancing Number Differentiation and Removal, Adjusting PA Range

### ISSUE THREAD

**Issue by leandrolima-nyc** [SoftFever/OrcaSlicer#1474]
There are two notable challenges when dealing with the result:  the difficulty of removing them from the build plate and the potential lack of adherence to certain surfaces and materials.  

To overcome these challenges, implementing a few improvements can be beneficial. 

Firstly, adding an additional layer beneath the number row will not only make it easier to remove but also enhance visual separation and clarity. Secondly, introducing a vertical line at the beginning and end, connecting all the lines would facilitate overall removal.

Furthermore, to make the Pressure Advance (PA) more versatile, the range should be adjustable, aligning it with other calibration features.

Another challenge is the occasional difficulty in differentiating the results from one another.

To gain a comprehensive understanding of these challenges and explore effective solutions, Ellis3dp.com offers valuable insights. In particular, the article on Pressure Linear Advance provides guidance on resolving the aforementioned issues. For a more efficient approach and a deeper understanding, it is highly recommended to refer to the following link: https://ellis3dp.com/Pressure_Linear_Advance_Tool/

It is hoped that the approach presented by Ellis3dp.com could potentially replace the current design or, at the very least, serve as a valuable reference for enhancing the existing system. 

<img width="471" alt="Safari 2023-07-05 at 11 35 40PM@2x" src="https://github.com/SoftFever/OrcaSlicer/assets/70433062/80ce0ded-8e72-411f-87e1-09c96a43f4ad">

**Comment by jeremytodd1** [comment]
Issue is being worked on in issue 640.
Please close.

**Comment by leandrolima-nyc** [comment]
Duplicate of #640
