### ISSUE TITLE
Export Config As a Bundle

### ISSUE THREAD

**Issue by enewun** [SoftFever/OrcaSlicer#148]
**Is your feature request related to a problem? Please describe.**
When exporting your configuration only the ones you currently have selected are exported. There is no way to export all filament, nozzle, and process user presets together at once.

**Describe the solution you'd like**
When exporting, export all user presets at once and not just the current ones you have selected for the plate.

**Describe alternatives you've considered**
I tried finding where my user presets are stored on my computer, macos, but I was not able to. I was thinking in the meantime I could just manually copy and paste these files.

**Additional context**
When exporting in PrusaSlicer it exports everything as a "config bundle". Having this same ability would make it easier to make backups at user presets.

**Comment by SoftFever** [comment]
User settings are located at: %appdata%\BambuStudio-SoftFever\user
