### ISSUE TITLE
If manual pressure advance is enabled does it override LiDar PA or vice versa?

### ISSUE THREAD

**Issue by Photogad** [SoftFever/OrcaSlicer#1482]
Simply but dumb question. If I set a pressure advance value in the filament and have it enabled, does it override the LiDar scan pressure advance, or is it vice versa?

I'm hoping the LiDar overrides it, not that the manual value overrides the LiDar. I would like to set a manual PA value and leave it turned on, but use LiDar most of the time --- if I want the manual PA value, I would uncheck LiDar calibration before printing. Does it work that way or reverse??
:(

**Comment by fourtwizzy** [comment]
To the best of my knowledge Bambu Lab uses a default K value of 0.02. Obviously this can be manually changed using the pressure advance setting. If you uncheck the manual PA settings, it would be calibrated based on LiDar, and the k value would be adjusted accordingly.

I do not believe it over writes the PA settings in the slicer, rather you can only choose one setting. Either manual PA but turning off the LiDar calibration, or automatic calibration using the LiDar sensor.

LiDar, if enabled always takes precedence over the manual PA values.
