### ISSUE TITLE
Custom Filament Presets Not saving

### ISSUE THREAD

**Issue by Draakul69** [SoftFever/OrcaSlicer#1489]
**Describe the bug**
The custom filaments I created and saved are not showing up on relaunch of app

**To Reproduce**
Save new filament, close app or open another instance of either bambustudio or orcaslicer, find new filament created not saved.

**Expected behavior**
Save the new filament presets

**Printer model**
Bambulab X1

**Desktop (please complete the following information):**
OS: Windows 10

**Comment by JonLaRue** [comment]
Confirm I am having similar issues.
