### ISSUE TITLE
Feature request: Time when finished 

### ISSUE THREAD

**Issue by leofaoro** [SoftFever/OrcaSlicer#149]
Hi, woudl it be possible to add a field in the device status showing the time when a print is expected to complete? thanks

**Comment by SoftFever** [comment]
Can you provide more details?
I believe both Bambu and Klipper already support this feature

**Comment by leofaoro** [comment]
Sure. Just show the time when the print is expected to be completed, in addition to the time left. This is in the "printing progress" box in the "device" tab. See below for mockup

<img width="927" alt="image" src="https://user-images.githubusercontent.com/1944817/211641140-28288e67-d0f9-48fc-8554-694aac2bd421.png">

**Comment by ymilord** [comment]
In Superslicer it had an option via M117 to display the time remaining. Is that still possible?
