### ISSUE TITLE
[Klipper] N.O. Layer not showing in Klipper 

### ISSUE THREAD

**Issue by blacktoz** [SoftFever/OrcaSlicer#1495]
**Describe the bug**
I am using Mainsail, with Moonraker interface on a rp2040, and no informations can be seen with Orcaslicer, such as slicer time, and the most important for me, the Layer number, it shows layer 0 of 0.

**3mf File for This Bug**
Welp, this bug happens to every .stl / .3mf that I've used

**To Reproduce**
Slice the file, upload it to klipper, launch the print, and layer number won't show and other informations about the slicing.

**Expected behavior**
Sliced files should show these informations

**Screenshots**
![image](https://github.com/SoftFever/OrcaSlicer/assets/34444000/959eabf4-3b3d-4002-98ac-7ee3d441da23)
![image](https://github.com/SoftFever/OrcaSlicer/assets/34444000/6804e5e9-5923-46f2-892b-666e851a502b)

What should it show : 
![image](https://github.com/SoftFever/OrcaSlicer/assets/34444000/27a4568c-d001-4611-b071-f4190411a01f)
![image](https://github.com/SoftFever/OrcaSlicer/assets/34444000/050409c9-996d-47d4-a26b-dacf9b8a4aff)

**Printer model**
Creality Ender 3 

**Desktop (please complete the following information):**
 - Arch Linux
 - 6.4.2
 - OrcaSlicer 1.6.3

**Comment by Sineos** [comment]
See https://docs.mainsail.xyz/overview/slicer/prusaslicer#layer-count

**Comment by SoftFever** [comment]
Orca Slicer is not recognized by Moonraker judging from your screenshot.
Most likely your Moonraker is not up to date.
Can you update it and check again?

`3. Klipper users, please update Moonraker to the latest version so that it can recognize OrcaSlicer and parse metadata like thumbnails.`

**Comment by blacktoz** [comment]
> See https://docs.mainsail.xyz/overview/slicer/prusaslicer#layer-count

Thanks, that worked perfectly



> Orca Slicer is not recognized by Moonraker judging from your screenshot. Most likely your Moonraker is not up to date. Can you update it and check again?
> 
> `3. Klipper users, please update Moonraker to the latest version so that it can recognize OrcaSlicer and parse metadata like thumbnails.`

Yeah, it has been a while that I haven't updated these packages, i'll do that, thanks!
