### ISSUE TITLE
start and end g code

### ISSUE THREAD

**Issue by Buythepound** [SoftFever/OrcaSlicer#1497]
Ender 3v2 with Sonic Pad, Sprite Pro and CR Touch. Just installed OrcaSlicer what an improvement over Cura, print came out excellent. My issue is with the start and end g code, how do I get to it? The print fails right after heat up before the first move. I get a message that I need to home axis. When I do I'm able to print but it's without ABL and no purge line. When the model is complete the nozzle just sets there not lifting, presenting or turning off heaters. it's probable something I'm doing wrong, but I don't see a way to fix this. In Cura you could go into Machine setting and write into the start and end g code.

**Comment by foreachthing** [comment]
First, click here:
<img width="560" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/10420187/f02eee21-853b-48a7-bb56-0f4f90ab44e6">

Then, enable **Advanced** mode and edit your "Machine G-code":
<img width="551" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/10420187/68c02cec-17a1-4024-8677-0b4075a8d6c0">
