### ISSUE TITLE
RatRig V-Core 3 300

### ISSUE THREAD

**Issue by vserverid** [SoftFever/OrcaSlicer#1498]
**Describe the bug**
The setupassistant dose not show any Filament after choosing Printer.

**Screenshots**
![Printer](https://github.com/SoftFever/OrcaSlicer/assets/72889486/53f6941b-a33e-4cd2-80ad-c3aa667ea6d9)
![filament](https://github.com/SoftFever/OrcaSlicer/assets/72889486/f4b90adc-28b3-41e5-837e-33e62a8a6b78)
![choose](https://github.com/SoftFever/OrcaSlicer/assets/72889486/89d49696-beb4-41d2-9d51-219077d5fae5)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 22H2

**Comment by joaobarros** [comment]
Confirmed the issue for at least V-Minion and V-Cores 3 300 and 500mm
Had to include Klipper generic printer to be able to have filament profiles.
