### ISSUE TITLE
"Keep fan always on" will prevent the aux fan from starting.

### ISSUE THREAD

**Issue by XSvFury** [SoftFever/OrcaSlicer#1500]
Hi, 

It seems the "keep fan always on" option will prevent the "m106 p2 s255" command from being included in the g-code file. If unselected, the command will be present (and the aux fan will work as intended). 

Just in case there is some other conflict I am unaware of, I have included screenshots of my printer and filament settings.
![Printer settings](https://github.com/SoftFever/OrcaSlicer/assets/20117962/ed084df3-7ef3-49a8-872f-f757510c3247)
![Filament Settings](https://github.com/SoftFever/OrcaSlicer/assets/20117962/749b8856-fc29-4fa3-8085-cae325ff0bdc)

**Comment by Kylemraley** [comment]
Curious if this affects chamber fan as well. I have my p3 gcode set to run chamber fan at full speed. I have this “keep fan on” setting checked, but regardless of my gcode edits it will only run at 40%. When I manually change in my device tab, it sets itself to 10%. Will only go to 40% and no higher when I turn off chamber fan, then back on.

**Comment by shyblower** [comment]
This bug is still present in 1.6.4-beta3

**Comment by KD7LRJ** [comment]
Confirmed this is still an issue with OS 1.7.0.

![image](https://github.com/SoftFever/OrcaSlicer/assets/2763408/5922d99f-3ab0-47b6-9748-36886417b0df)

![image](https://github.com/SoftFever/OrcaSlicer/assets/2763408/46928f3f-2b0f-4207-86bc-82828585edb1)

[Hexagon Diffusion_pr03 - Copy.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/13079773/Hexagon.Diffusion_pr03.-.Copy.3mf.zip)
