### ISSUE TITLE
Avoid Crossing Wall: Travel Along an Inner Perimeter Loop, Not Outer

### ISSUE THREAD

**Issue by CCS86** [SoftFever/OrcaSlicer#1504]
SuperSlicer has a nice change to the "Avoid crossing wall" / "Avoid Printeds Parts" behavior, where instead of traveling along the outer perimeter, it used an inner perimeter intead:

![image](https://github.com/SoftFever/OrcaSlicer/assets/12439543/54f8b516-2bd0-4275-b2eb-e15497466b3c)

The issue with using the outer perimeter is that because of the high speed and possibly more coarse segmentation, shortcutting the path can occur, and this destroys the surface finish.

**Comment by CCS86** [comment]
?

**Comment by igiannakas** [comment]
This has been resolved in 1.9
