### ISSUE TITLE
Jerk Control Not Working (RepRapFirmware)

### ISSUE THREAD

**Issue by CCS86** [SoftFever/OrcaSlicer#1505]
With Jerk Control enabled using RRF output, only 2 jerk commands appear in the whole gcode output (M205)

![image](https://github.com/SoftFever/OrcaSlicer/assets/12439543/250ef765-b1a8-4147-a858-df524d1efc23)

![image](https://github.com/SoftFever/OrcaSlicer/assets/12439543/71c3b588-f999-476d-a4fc-70a3ad4555ab)

[Orca_Jerk.3mf.txt](https://github.com/SoftFever/OrcaSlicer/files/11996604/Orca_Jerk.3mf.txt)

**Comment by CCS86** [comment]
?

**Comment by BR7408** [comment]
I found the exact same issue. M205 command generated is X7 Y7, no matter what jerk settings I put in the console, unless I set default jerk to 0.

Is this going to get fixed any time soon? It would be a huge benefit to have variable jerk capability on RepRap.

**Comment by igorscheffer** [comment]
I had a similar problem, I discovered it was the printer settings. for example, the maximum jerk was set to 9, so when I put something higher in the filament configuration it wouldn't
