### ISSUE TITLE
FR: Filament Spool Weight

### ISSUE THREAD

**Issue by CCS86** [SoftFever/OrcaSlicer#1506]
Superslicer has a great feature where you enter the spool weight and it gives you a second calculated weight output which includes the spool. This makes managing prints much easier:

![image](https://github.com/SoftFever/OrcaSlicer/assets/12439543/dbc9552d-54af-49f6-b23a-e6d47ff184c6)

**Comment by Ogerix88** [comment]
I miss that feature too, unfortunately.
