### ISSUE TITLE
P1P Chamber Fan

### ISSUE THREAD

**Issue by Kylemraley** [SoftFever/OrcaSlicer#1510]
I have installed a chamber fan on my P1P and can’t get it to run at the speed I want.

Customized orcaslicer config.json, as well as p3 s255 g code in my machine and filament settings. I have removed all code that makes the chamber fan dependent on bed temp. 

When printing, the chamber fan is running as expected, but will only run at 40%. If I manually increase through my device tab, it will drop down and stay at 10%. If I turn chamber fan off and back on it holds at 40% again.

I have bumped all p3 Gcode to s255 to try to run full speed, doesn’t work.

Any ideas as to how I can get the chamber fan to run at the speed I want?

**Comment by Abyss8** [comment]
Using AUX(chamber too) fan manually is a nightmare..
When i set something after a while when ui refresh that thing is reversed. No control, only gcode on layer can do something.
