### ISSUE TITLE
[PA Test] - Lines not in center of bed

### ISSUE THREAD

**Issue by foreachthing** [SoftFever/OrcaSlicer#1520]
**Describe the bug**
Test created, does not fit on plate/platter/bed.

EDIT: This is only when using a custom bed shape!

**To Reproduce**
Calibration -> PA-Clibration
![image](https://github.com/SoftFever/OrcaSlicer/assets/10420187/665e4bc4-896c-4e0e-8018-60c0a6dee0a1)

**Expected behavior**
Test lines on center of bed so it can be printed.

**Screenshots**
![image](https://github.com/SoftFever/OrcaSlicer/assets/10420187/e88b149a-912e-4544-8475-4eec4f6bc873)

**Printer model**
Ultimaker 2

**Desktop (please complete the following information):**
 - OS: Windows 10
 - OrcaSlicer 1.6.3

**Comment by SoftFever** [comment]
Can you show me how do you define the bed shape?

**Comment by foreachthing** [comment]
Please find attached a project file, bed shape (stl) and bed texture (svg).
[OrcaSlicer_PA-Test.zip](https://github.com/SoftFever/OrcaSlicer/files/12079876/OrcaSlicer_PA-Test.zip)

![image](https://github.com/SoftFever/OrcaSlicer/assets/10420187/a0f948bf-86a0-475c-8cd7-fb5082ccda18)


If you need more information, please let me know.
Thanks!

**Comment by foreachthing** [comment]
This is still an issue in 1.8.
