### ISSUE TITLE
Avoid crossing wall option ignored intermittently

### ISSUE THREAD

**Issue by silentone** [SoftFever/OrcaSlicer#1524]
Travel moves while printing infill are randomly crossing outer walls when Avoid crossing wall option (with no max detour) is enabled. I tried tweaking many other options and couldn't identify any related setting. Here are screenshots on two layers that are similar. First, it travels around the walls on both ends, then on another layer, it travels across the wall on one end.
![travel inside model screen](https://github.com/SoftFever/OrcaSlicer/assets/61305/9fa1ab11-2c5a-4cae-9ddf-1337a2ef84e8)

![travel across walls screen](https://github.com/SoftFever/OrcaSlicer/assets/61305/1f57fa03-ad17-470b-974b-e33491a66ba2)

[wall crossing test 3MF.zip](https://github.com/SoftFever/OrcaSlicer/files/12034105/wall.crossing.test.3MF.zip)

**Comment by stopanko** [comment]
Confirmed! This is happening for me only for 0.5 + nozzle size in a settings.   
Have tried Bambu Too. It's doing some circular motions outside with the same setting too.

@SoftFever Could you confirm is this is a Bambu bug or Orca.

![image](https://github.com/SoftFever/OrcaSlicer/assets/3759349/2d03d27d-c1a1-4731-991c-b987989befef)
Will add model and Sliced codes in a file.
[travels_crossing_outer_walls.zip](https://github.com/SoftFever/OrcaSlicer/files/12841540/travels_crossing_outer_walls.zip)

**Comment by BlueByLiquid** [comment]
I have had this same problem
