### ISSUE TITLE
Orca Slicer not starting if shut down on second monitor.

### ISSUE THREAD

**Issue by Belthax** [SoftFever/OrcaSlicer#1531]
**Describe the bug**
If i close Orca Slicer on my second monitor it will not be able to start the program untill i go into the config file and replace this line with the main screen location.

"window_mainframe": "360; 120; 1200; 800; 0",

If i do not do this it will just stand on the second screen locked up and look like its loading.

**To Reproduce**
Shut down Orca Slicer when it is on your second monitor and then starting it up again.

**Expected behavior**
Start the program as it usually do.

**Printer model**
Bambu Lab P1P

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 21H2
 - Orca Slicer 1.6.3

**Comment by aaronnguyen** [comment]
For anyone else running into this issue.
I just set my secondary monitor as my main display and was able to open orca slicer successfully.

**Comment by SuprDlux** [comment]
+1 bump. link to same bug here: https://github.com/bambulab/BambuStudio/issues/179 

years this has been unpatched...
