### ISSUE TITLE
Add Snapmaker 2.0 Printer Profile

### ISSUE THREAD

**Issue by elektro-hub** [SoftFever/OrcaSlicer#155]
Please add support for Snapmaker 2.0.
I have both Printers Bambu X1 Carbon and the Snapmaker 2.0. 
I would love to use both of them in the BambuStudio and not messing with Cura or the original Luban witch is terrible for 3d Printing.

**Comment by hliebscher** [comment]
You can USE any Model and then edit  the Name and size and type to Marlin legacy
edit your Start Code and ist works
![sm350](https://user-images.githubusercontent.com/9274162/211573791-a99618a4-28d8-4741-824d-ee440c63b7c0.jpg)

**Comment by erebus04** [comment]
https://github.com/SoftFever/BambuStudio-SoftFever/pull/171
