### ISSUE TITLE
API for using slicer

### ISSUE THREAD

**Issue by Allaux** [SoftFever/OrcaSlicer#1551]
Hello,
Is possible to use an HTTP API for using slicer,

**Comment by jeremytodd1** [comment]
What is your intention?

**Comment by coopbri** [comment]
Hey, I would love this feature as well. It would be super cool to be able to extend the ecosystem around Orca Slicer by consuming an API served by it. Maybe a daemon could run headless so the slicer desktop app doesn't have to be running
