### ISSUE TITLE
Bed temperature of first layer carrying on to the rest of the layers

### ISSUE THREAD

**Issue by Glenn1963** [SoftFever/OrcaSlicer#1552]
### Discussed in https://github.com/SoftFever/OrcaSlicer/discussions/1492

<div type='discussions-op-text'>

<sup>Originally posted by **Studioscale** July  8, 2023</sup>
i set the slicer up so that the first layer would be 120 and the rest 110 but its printing the whole thing at 120. The extruder is doinf it correctly, reducing from 250 to 240 for the second layer on, but not the bed temp. Am I doing something wrong here?
![Orca temp](https://github.com/SoftFever/OrcaSlicer/assets/130306639/5e9e3365-a02d-4480-b4cd-2b8f6945ea20)
![orca temp screen](https://github.com/SoftFever/OrcaSlicer/assets/130306639/968a44bd-b2f8-4115-85ec-0a5c43dc6ba3)
[3DBenchy_ABS_43m38s.txt](https://github.com/SoftFever/OrcaSlicer/files/11990942/3DBenchy_ABS_43m38s.txt)
</div>

**Comment by Glenn1963** [comment]
As I described in #1492 , changing the Layer change machine G-code seems to disable generating the bed temperate change M140 code. Just changing the Other layers temperature will allow the code to be generated normally again.

**Comment by btCRO** [comment]
And today I found that disabling automatic brim would forgot to set M140 at second layer in 100% of situation I'we tried.
Yesterday I found if you change speed without saving and reloading M140 is missing from secon layer.
