### ISSUE TITLE
Extrusion Multiplier for each Feature Type / Line Type

### ISSUE THREAD

**Issue by arshish1612** [SoftFever/OrcaSlicer#1558]
**Is your feature request related to a problem? Please describe.**
Unable to control flow rates / extrusion multipliers for different feature types. Currently you can only adjust the default multiplier and the top Solid Infill. However there is a need to set the flow rate for different layers. This is available in Cure and is extremely useful in getting prints perfectly dialled in.

**Describe the solution you'd like**
Using Cura as a reference, a section to se the extrusion multiplier for different line features.
![image](https://github.com/SoftFever/OrcaSlicer/assets/8477844/3bed29ca-a912-43e9-a9fe-714789f3db40)

**Describe alternatives you've considered**
In PrusaSlicer you have a substitute GCode which is OK but Cura implements it better

**Additional context**

**Comment by The760** [comment]
Would absolutely love to see this.

**Comment by arshish1612** [comment]
@lukasmatena Would you be aware if anyone has had a look at this pls.

**Comment by arshish1612** [comment]
Bump Bump Bump

**Comment by arshish1612** [comment]
Any likelihood of seeing this?

**Comment by lambonick** [comment]
> Please open this issue. Its absolutely necessary

I 2nd that!

**Comment by arshish1612** [comment]
I wonder why this has not even been acknowledged by the devs as yet..

**Comment by DustanGiles** [comment]
Bump

**Comment by sonmoku** [comment]
Necessary feature for tweaking lightweight mechanical parts, lowering gas permeability and other cases

Please consider it - Love the Slicer, Thank you!

**Comment by arshish1612** [comment]
Why is this Closed? Unless the Status os Opened again no one is going to see our comments to this. Should we create a new Issue?

**Comment by arshish1612** [comment]
Ive created a new issue so this gets looked at: 
https://github.com/SoftFever/OrcaSlicer/issues/3977
