### ISSUE TITLE
Second and First plateau Top Layer

### ISSUE THREAD

**Issue by Dinchy87** [SoftFever/OrcaSlicer#1560]
I have a strange if I slice a Stair or anything that has multiple Top Layers on different Heights the second an all above Top Layer I see the inner wall  so it makes not a top layer like it should.

And I cannot see any option to turn this off. In the Bambu Studio slicer it slices the file and each Top layer as it should.

What am I not seeing?!

Both are sliced on a Macbook Pro M2

here is an example of Orcaslicer
<img width="955" alt="Bildschirmfoto 2023-07-18 um 19 30 00" src="https://github.com/SoftFever/OrcaSlicer/assets/10762985/145a79ae-2b83-4d7e-9468-34a5928d53d3">

and here an example of Bambu Studio

<img width="1040" alt="Bildschirmfoto 2023-07-18 um 19 41 10" src="https://github.com/SoftFever/OrcaSlicer/assets/10762985/bae883d8-078c-4e2a-88a2-eb61b84fec45">

Do you see the inner wall rings there? I think they should not be there.

Here is also the 3mf file of this scene.
[StairTest.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/12086243/StairTest.3mf.zip)

**Comment by jeremytodd1** [comment]
Issue is being worked on in issue 582. 

Please close. In the meantime, disabling Arachne will get your single perimeters for top layers again.

**Comment by Noisyfox** [comment]
> In the Bambu Studio slicer it slices the file and each Top layer as it should.

If you look more closely you'll notice that when Arachne is selected the "Only one wall on top surfaces" options is disabled in BBS.
