### ISSUE TITLE
Temperature Tower sliced with inconsistent layer height, floating layers

### ISSUE THREAD

**Issue by simonbuehler** [SoftFever/OrcaSlicer#1564]
**Describe the bug**
hi,

when inserting the temp tower the slicer varies layer height - why? - which leads to floating layer and bad prints "missing" lines

**To Reproduce**
insert temp tower

**Expected behavior**
same layer height

**Screenshots**
![grafik](https://github.com/SoftFever/OrcaSlicer/assets/78061/c2518d47-0ef5-40df-8fa8-a11ff884fe50)

**Printer model**
p1p

**Desktop (please complete the following information):**
 - OS: win
 - Version 1.6.3

**Comment by SoftFever** [comment]
I can't repro this issue.
Can you save the project and share?

**Comment by simonbuehler** [comment]
i really tried hard to reproduce but can't. restarting has helped but is bad for debugging, closing for now and in case i find out i'll reopen
