### ISSUE TITLE
Outer_Only Brim also encompassing insides

### ISSUE THREAD

**Issue by arshish1612** [SoftFever/OrcaSlicer#1565]
**Describe the bug**
When you select Outer_Only brim, the inner areas also get covered by the Brim 

**3mf File for This Bug**
3mf is attached
[BrimIssue.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/12096515/BrimIssue.3mf.zip)

**To Reproduce**
Use the attached file and select "Outer_Only: Brim. The inner sections are not excluded form the Brim

**Expected behavior**
Inner sections should not get covered by the Brim

**Screenshots**
Attached:
![image](https://github.com/SoftFever/OrcaSlicer/assets/8477844/f16d2892-c3ed-4f91-a30a-10fd05eec8b5)

**Printer model**
FlSun V400

**Desktop (please complete the following information):**
 -Macbook Air 13 M1 - 13.4.1 (c)

**Comment by Noisyfox** [comment]
I think the problem is that there is a very thing opening on the side of the hole which makes it not really an inner area.

**Comment by arshish1612** [comment]
But this does not happen with PrusaSlicer... So something is not right

**Comment by Noisyfox** [comment]
The key is the value of the "Slice gap closing radius", which is 0.049 in PrusaSlicer by default, which will remove the crack and make that hole an inner area. If you change this settings to 0 (which is BBS/Orca's default value) you will have brim in that area too:
![image](https://github.com/SoftFever/OrcaSlicer/assets/1537155/c8741379-6142-4542-9cd7-e4b552a4fa75)
![image](https://github.com/SoftFever/OrcaSlicer/assets/1537155/2551e10b-bfab-4438-9423-8ff6dd510157)

On the other hand, if you set that value to 0.049 in BBS/Orca then it will do what you want:
![image](https://github.com/SoftFever/OrcaSlicer/assets/1537155/fac6c105-f26f-4f1d-b379-384537aa9423)

**Comment by arshish1612** [comment]
Awesome. Thanks for the fix.
