### ISSUE TITLE
Feature request: Jerk / SQV settings for infill

### ISSUE THREAD

**Issue by Prutsium** [SoftFever/OrcaSlicer#157]
Can we get also a Jerk / SQV settings for Infill here?
![image](https://user-images.githubusercontent.com/42968695/211656028-4f23a5b4-0f45-424a-a242-4c01557b500d.png)

As i run Klipper on a fast printer and print alot of Gyroid i want to increase the SQV for infill. In superslicer i used the variable extrusion role but as this isnt possible here it would make sense to bring it under the Jerk settings.

Thanks

**Comment by cron410** [comment]
I fond this macro set somewhere online years ago. Might help you. 

[fast_infill.cfg.txt](https://github.com/SoftFever/BambuStudio-SoftFever/files/10407655/fast_infill.cfg.txt)

**Comment by Prutsium** [comment]
> I fond this macro set somewhere online years ago. Might help you.
> 
> [fast_infill.cfg.txt](https://github.com/SoftFever/BambuStudio-SoftFever/files/10407655/fast_infill.cfg.txt)

I know that route. Was using that route long ago but since Slicer has all the info and Prusa/Superslicer can do this themselves based on the parameter extrusion role just 2 lines would be needed.
![image](https://user-images.githubusercontent.com/42968695/212255804-ae138c7c-e093-4b38-a6cd-b8689483bfbf.png)

But it would be great to have it in the uniform way of BambuSlicer (Softfever) as the Jerk / SQV settings in my 1st post.

**Comment by SoftFever** [comment]
Good idea.
Added in b7bdb65f

**Comment by Prutsium** [comment]
Thanks! Makes the slicer more usable for Klipper users!

**Comment by The-Futur1st** [comment]
@SoftFever Please consider to add same parameter for acceleration just to be consistent. I have also thought about acceleration control for bridging perimeters. I did not make tests of that, but from my predictions it can be helpful with filled filaments like PP-GF30 or similar(such filaments usually very difficult with bridges and force you to print bridges with very low speeds 15-20mm/s)
