### ISSUE TITLE
Multiple filament slots does not change the actual filament settings

### ISSUE THREAD

**Issue by Naninani** [SoftFever/OrcaSlicer#1570]
**Describe the bug**
When creating a new profile out of the predefined ones and change some setting is the "Settings Override" section, the new profile settings override the ones in the existing system presets. This happens only if there are multiple Filaments slots added from the "Add one filament" option.

**3mf File for This Bug**
If it is related to slicing, please append the 3mf file. It could be extremely helpful to solve the issue.

**To Reproduce**
1. Backup all existing profiles.
2. Wipe all profiles.
3. Logout if logged in (issues repo both logged in or out)
4. Uninstall Orca.
5. Install again.
6. Select Generic PETG.
7. Edit the Settings Override of Filament settings.
8. Set Z hop type to Slope
9. Set the Wipe Distance to 10mm
10. Save present to new one with name 1.
11. Add Primitive Cube
12. Add additional filament slot.
13. In slot 1 chose filament 1, in slot 2 chose Generic PETG
14. Slice with 1 and enable the Travel and Wipe to see the lines.
15. Set to slot 2 with the Generic PETG and slice again.
16. What happens is that it does not actually switch to slot 2 settings, but choses the settings from slot 1.
17. This happens only if there are more than 2 added filament slots. If you chose Generic PETG from slot 1, the settings are correctly updated.

**Expected behavior**
It should correctly update the settings for the different filament slots.
This is an extremely nasty bug that I managed to reproduces in both Orca and Bambu slicers. It actually ruined tons of prints for me and I spent countless hours figuring out why my prints are so off when using different filament slots.

**Screenshots**
<img width="801" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/1681582/1a0646a9-cc1e-44e5-9f48-6d8f3d7d496c">
<img width="369" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/1681582/29e2e06e-74a2-4fca-abf8-46923e1445b8">
<img width="489" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/1681582/ced148c0-7ac4-4537-97e3-9627fd2fd7f6">
<img width="428" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/1681582/91fe188c-aed4-434a-a0f1-229c0a9e79fe">
<img width="1372" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/1681582/6f91f65d-45a6-4324-9b83-b1a3334f531d">
<img width="1388" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/1681582/6ccb42ea-35cf-46de-8f8a-e7ed78f86a1b">
<img width="1386" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/1681582/b84c7d66-98c7-429a-995d-1485ef46b132">
<img width="1388" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/1681582/16630e97-5593-4ee8-b442-b8b1b65198d4">

**Printer model**

**Desktop (please complete the following information):**
 - OS: [Mac]
 - Version [1.6.3]

**Comment by psiberfunk** [comment]
If this replicates in upstream, is it logged there too ?  if so, please link here, or log it there as well ?  It would be easier for @SoftFever if Bambu fixed this and he pulls it in IMO.

**Comment by Naninani** [comment]
https://github.com/bambulab/BambuStudio/issues/2098

**Comment by Naninani** [comment]
@SoftFever are you able to repo this on your end? This seems to be a rly bad bug.

**Comment by Naninani** [comment]
@SoftFever, this issue has been fixed in Bambu Studio: 1.7.6.92. Do you plan to port the latest changes?

**Comment by SoftFever** [comment]
> @SoftFever, this issue has been fixed in Bambu Studio: 1.7.6.92. Do you plan to port the latest changes? <img alt="image" width="854" src="https://user-images.githubusercontent.com/1681582/278720712-67ef3892-a879-4c6c-b8d3-0f9d4ea5a3dd.png">

Hi 
Can you try the latest V1.8.0 beta release? Let me know if the bug presists.

**Comment by Naninani** [comment]
@SoftFever its fixed - I tested the latest 1.8 release. Closing this bug.
