### ISSUE TITLE
first layer temp

### ISSUE THREAD

**Issue by uvalml** [SoftFever/OrcaSlicer#1573]
When removing the heat-up G-code from the start G-code in the 3D printer slicer settings, the preview section shows that the slicer is unable to recognize the initial layer, resulting in it displaying "0" for the initial layer temperature.

To Reproduce
Open the 3D printer slicer software.
Access the printer settings.
Navigate to the "Start G-code" section.
Remove the heat-up G-code from the existing script.
Save the changes and proceed to slice the 3D model.
Expected behavior
Upon removing the heat-up G-code from the start G-code, the slicer should still be able to determine the initial layer temperature from the settings provided, without relying on the G-code for this information.

Printer model

Printer: Voron 2.4

OS: Windows 11

Additional Information
The issue seems to be specific to the slicer software's handling of heat-up G-code in the start G-code script. The slicer should be able to infer the initial layer temperature from the provided settings, even after removing the redundant heat-up G-code. This behavior would ensure a streamlined slicing process and avoid potential conflicts arising from duplicate G-code instructions.

**Comment by ErdbeermarmeladebrotmitHonig** [comment]
I have exactly the same problem ...
Am I missing anything? My config always worked and now stopped working ...
