### ISSUE TITLE
layer line width ?!

### ISSUE THREAD

**Issue by uvalml** [SoftFever/OrcaSlicer#1574]
Describe the bug
Currently, when setting the line width as a percentage in the slicer software, the percentage is calculated based on the layer height instead of the nozzle width. This behavior is unexpected and counterintuitive for users, as they would naturally assume that the percentage refers to the nozzle width.

To Reproduce

Open the slicer software and load a 3D model for printing.
Access the print settings, specifically the line width configuration.
Choose the "Percentage" option for line width and input a specific percentage value (e.g., 150%).
Slice the 3D model with the chosen settings and send the G-code to the Voron 2.4 3D printer.
Observe the printing process and inspect the printed object.
Expected behavior
When selecting the line width as a percentage, users would reasonably expect the slicer to calculate the width based on the nozzle diameter of the Voron 2.4 printer or any other 3D printer model being used. For example, setting the line width to 150% should result in a line width 1.5 times the nozzle diameter. This behavior aligns with typical user expectations and ensures consistent and accurate extrusion during printing.

Printer model

Printer: Voron 2.4
Desktop (please complete the following information):

OS: Windows 11
Additional Information
The current implementation of calculating the line width percentage from the layer height, instead of the nozzle diameter, is counterintuitive and affects all users. This behavior can lead to confusion and unintended print results. Implementing the percentage calculation based on the nozzle diameter would greatly improve the slicer's usability and ensure consistent extrusion across different 3D printer models and operating systems. This feature request aims to provide a more intuitive and universally applicable solution that aligns with standard printing practices and user expectations across the 3D printing community.

**Comment by jeremytodd1** [comment]
There is currently a pull request for this feature. 

https://github.com/SoftFever/OrcaSlicer/pull/1578

Please close.
