### ISSUE TITLE
FR: 2in1out hotend 

### ISSUE THREAD

**Issue by stenc55** [SoftFever/OrcaSlicer#1581]
I have modified Sapphire SP5 with with 2 extruders that share Thaici 2in1out hotend. Super easy to set in PS or SS (Single extruder multi material option), but in Orca there is no option to set parameters for switching extruders/ forming tips/ changing filaments. 
I guess something could be coded in switching filaments section of profile, but I can't write the code. 
I have Switch filament macro written in Klipper, but it is static. Printhead does not move while changing filament. I could make it move while purging filament, but I can't insert wipe tower position in macro or vice versa, I can't insert purging parameters into wipe tower generated in slicer?

I would like setup similar to PrusaSlicer. Cooling tube parameters, filament ramming and forming tips parameters and wipe tower parameters. 
Until I solve this problem unfortunately Orca Slicer is not usable for me.
![image](https://github.com/SoftFever/OrcaSlicer/assets/68291385/9c071843-fadc-48c0-aeba-870532a4ab99)
![image](https://github.com/SoftFever/OrcaSlicer/assets/68291385/612fdc2b-db2c-4a94-9756-acc903d3ae71)
![image](https://github.com/SoftFever/OrcaSlicer/assets/68291385/c0031025-fdfc-4fcf-92a3-cd9aaa955524)

**Comment by TexZeTech** [comment]
Question for you. Have you tried 

![image](https://github.com/SoftFever/OrcaSlicer/assets/7254540/1725e8ae-f492-4b3d-afa7-2ca977433d10)
and havinging custom gcode set up in the second filament? Something like `extruderchange 2` or the like to call the macro in klipper? I think you can get the functionality you want in Orcaslicer.

**Comment by stenc55** [comment]
I have 2 filaments set up.
Problem is, Orca slicer only know how to use AMS configuration, I believe. When I try filament change, it will stop with nozzle still in print, perform filament retract (with that forming tip) and only then it will move to purge tower, swap extruders and load new filament. 
While forming tip it will push some old filament out of nozzle and then move filament in/out several times to make a tip.
I can't set it to move to purge tower and then perform everything necessary for filament swap.
in picture, T0 code should be in place of ;CP TOOLCHANGE WIPE
![image](https://github.com/SoftFever/OrcaSlicer/assets/68291385/93594a0f-4f4a-482c-90a6-3e7e57ddca58)

**Comment by TexZeTech** [comment]
So playing around a little more. My first suggestion was WAY off the mark. 

I cannot test it out besides just looking at the gcode generated.

Here is what I have poked about and I think would work for what you need. 

Again this would be dependent on your macro setup. 

![image](https://github.com/SoftFever/OrcaSlicer/assets/7254540/d5e47f2b-0139-4ea4-a5f7-f1076c7a1d12)


![image](https://github.com/SoftFever/OrcaSlicer/assets/7254540/4a187045-cabb-4344-9399-414910935b79)

I legitimately hope this solves your issue.

**Comment by stenc55** [comment]
Thank you.
I was thinking same way, but I still don't know how to cancel T0/T1 command that is inserted after filament start gcode. Or at least comment it out.  Can commenting out a line be done?

**Comment by TexZeTech** [comment]
I found something that might work, it goes without saying you will have to mod the macro to suit your system.

It would help if you upload your config(s) as well.

https://klipper.discourse.group/t/switching-between-extruders/2020/19

https://github.com/ld3300/Klipper_Configs/blob/master/configs/extruders.cfg

I don't think the T0, T1, etc is an issue personally as I can use a macro to use that for more control personally.

I did find though that if I try to use the support/raft interface as a separate filament selection I didn't get any T# .... that has to be a bug.

**Comment by stenc55** [comment]
Thank you again. I will play with this when I have time, right now there are biblical floods in my country.

**Comment by TexZeTech** [comment]
> Thank you again. I will play with this when I have time, right now there are biblical floods in my country.

Ooooof well stay safe and no problem.

**Comment by stenc55** [comment]
Implemented with one small issue, described in #2235
