### ISSUE TITLE
Feature: viewport zoom % and/or measuring tool

### ISSUE THREAD

**Issue by marnovo** [SoftFever/OrcaSlicer#1590]
**Is your feature request related to a problem? Please describe.**

You always have to be guessing dimensions scale when working in the slicer, or at best be selecting certain objects and the scale tool to have an idea of real dimensions (this works for outer dimensions only).
If you "zoom in" the view to a scale that matches your display size/ppi to real life, you are actually able to see and even measure these dimensions manually, but this means every time being able to get to an specific zoom level that you'll never be able to replicate without trial and error using some reference.
This is particularly important when you're assembling, scaling parts with inner dimensions you care about, etc.

**Describe the solution you'd like**

Two ideas come to mind. 1 seems easier and more straightforward to implement. 2 is nicer but more advanced.
1. Be able to visualize the % zoom you are at in the view pane, and ideally be able to set this % manually, even better if able to set a "default".
2. A "measure" tool to click two points/edges/faces and get a measurement, akin to what's available in other 3D tools.

**Describe how it would work**

1. Viewport zoom setting:
1.1. Example from Photoshop implementation: https://www.photoshopessentials.com/basics/photoshop-zoom/
1.2.  Example from Office implementation: https://www.excel-easy.com/examples/zoom.html
1.3. Ideally you can also save the % setting to open every time (or 1:1, fit, etc) 

2. Measurement tool examples:
2.1. https://support.shapr3d.com/hc/en-us/articles/7874465678236-Measurements
2.2. https://help.autodesk.com/view/fusion360/ENU/?guid=SLD-MEASURE

**Describe alternatives you've considered**

Right now I use a calibration cube and a transparent overlay I printed to put over the display and manually zoom in/out via trial and error to match these, then "knowing" the viewport is at "real life" zoom scale and use manual measurement tools like squares over the display to measure things.

**Additional context**
Edit: Seems a measurement tool has already been implemented in Prusaslicer 2.6.0, so maybe just bring that over: https://github.com/prusa3d/PrusaSlicer/releases/tag/version_2.6.0-alpha2

**Comment by Eldenroot** [comment]
Good idea!
