### ISSUE TITLE
Improvement: A "base temperature" in the setting filament menu instead of manually enter in the gCode. 

### ISSUE THREAD

**Issue by staxborn** [SoftFever/OrcaSlicer#1604]
**Is your feature request related to a problem? Please describe.**
When writing gcode under the _"Machine Start G-code"_, you can either choose **_"M104 S[nozzle_temperature_initial_layer]"_** or manually enter **_"M104 S170"_** (if you decide, for example, that PLA should have a base temperature of 170 degrees). 

This manually entered setting is easy to forget when switching between different filaments (PLA/PETG/ABS etc...).

**Describe the solution you'd like**
Just like you set the bed and nozzle temperatures, you should be able to enter a "base temperature" to start with as well. 

Following this, you can perform "Auto Bed Leveling" gCode under the _"Machine Start G-code"_ using either the command **_"G29"_** or **_"M420 S1"_**. This minimizes oozing during the Auto bed leveling process. 
After auto bed leveling, you can add code to raise the extruder, for example, by 150 units (G1 Z150), and then proceed with the "M109 S[nozzle_temperature_initial_layer]" command.

For example the gcode could be : **_"M104 S[nozzle_base_temperature] ; Start nozzle heating to desired base temperature, e.g. 170°C._"** instead of **_"M104 S[nozzle_temperature_initial_layer] ; start nozzle heating but don't wait"_**

_**Having such a function would be very helpful. It eliminates waiting time and minimizes oozing during the printing process.**_

**Describe alternatives you've considered**
Always have to choose Machine Start G-code settings and manually enter the gCode: **_"M104 S [temperature]"**_ every time when switching between filaments (PLA/PETG/ABS) for a change of the "base temperature" instead of the settings is already made for different filaments (PLA/PETG/ABS etc).

**Additional context**
The setting as today for the "start nozzle heating":
![image](https://github.com/SoftFever/OrcaSlicer/assets/57374491/0e4dedd7-ecc8-4158-870d-4824261efcfa)

The setting after the improvement:
![image](https://github.com/SoftFever/OrcaSlicer/assets/57374491/0013cc2f-11e4-46aa-a00b-ef91eac2d5e3)

**Comment by ppamment** [comment]
I usually go with something like 

M104 S{nozzle_temperature_initial_layer[initial_no_support_extruder]-30} 

It achieves roughly achieves the same goal - something reasonably lower than the print temp but still hot.

{if filament_type[initial_no_support_extruder]=="PLA"}
M104 S170
{elsif filament_type[initial_no_support_extruder]=="PETG"}
M104 S180
{elseif (filament_type[initial_no_support_extruder]=="ABS") | | (filament_type[initial_no_support_extruder]=="ASA")}
M104 S220
{else}
M104 S150
{endif}

Should do exactly what you're asking.

Changing M190 to M140 so as not to wait for the bed to heat also speeds things up for me. It has plenty of time to get up to temp even at 100+ while the printer does it's startup dance.
