### ISSUE TITLE
Adding the P1S as a printer config / option

### ISSUE THREAD

**Issue by nirurin** [SoftFever/OrcaSlicer#1605]
Doesn't really need any more details. P1S as a printer option.

**Comment by Error-106** [comment]
I found the configuration file containing P1S from AppData\Roaming\BambuStudio\ota
You just need to copy it to OrcaSlicer\resources\profiles replacement
[ota.zip](https://github.com/SoftFever/OrcaSlicer/files/12182978/ota.zip)

**Comment by nirurin** [comment]
> I found the configuration file containing P1S from AppData\Roaming\BambuStudio\ota You just need to copy it to OrcaSlicer\resources\profiles replacement [ota.zip](https://github.com/SoftFever/OrcaSlicer/files/12182978/ota.zip)

Does this mean that it will auto grab the custom profiles for p1s from the server that I have made on bambu studio? The same as it would for p1p and x1c profiles

**Comment by Error-106** [comment]
Bambu Studio will attempt OTA at startup
OrcaSlicer should not attempt to update
You can copy the Bambu Studio OTA configuration file to OrcaSlicer, if only temporarily

**Comment by Brian-Jackson** [comment]
What does if only temporarily mean?  Since it is an OTA update for Bambu does that mean in order to update Orca we would need to do this again to get a new version with any changes that Bambu makes?

**Comment by Error-106** [comment]
I'm not sure OrcaSlicer has a license to use BamBu Studio's OTA profiles
You can use it temporarily and wait for OrcaSlicer to update their configuration file
