### ISSUE TITLE
All filament profiles, as well as processes save as in-project instead of user

### ISSUE THREAD

**Issue by SwagDad99** [SoftFever/OrcaSlicer#1622]
**Describe the bug**
When I create a project, or open an existing project, and then later save it, all filaments save as in-project profiles, instead of User profiles.  The global process does as well.  When I try to slice it without changing the filaments, or process, it gives an error for the start g-code for the filament.  After fixing the filament, it gives an error for the process, saying it is too thin.;  Did I set it too small?

It happens every time I open the project, even if I fix it, and then save it.

**3mf File for This Bug**
I tried to attach "Divided Cup v3.3mf", but it says that file type is not supported... It does not list '.zip' as supported either...

**To Reproduce**
Create a project
Change filament to a User profile
Change Process to  User process
Slice the project
Save the project.
Close Orca
Re-open Orca
Load the project

**Expected behavior**
The project should open, and you should be able to continue where you left off.  As it works now, I have to remember all of my settings, change them to be correct, and THEN slice and print.

**Screenshots**

**Printer model**
X1C

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 11 Home

**Comment by FillPavS** [comment]
I also have problems with the project after opening. If I change any settings like number of walls, speed, number of bottom layers, top and any others, then save the project and load it, then all settings will be lost and the ones saved by default in the process profile will be used.

Windows 10
