### ISSUE TITLE
Filaments cannot be deleted

### ISSUE THREAD

**Issue by PrintModz** [SoftFever/OrcaSlicer#1623]
The problem here is that no filaments can be completely erased. Even previously created filaments cannot be removed from the slicer.

I have deleted all unnecessary files directly from the slicer and also from the configuration folder, but both without success. The filaments remain available and this is quite annoying.

Is there already a solution for this?

**Comment by SoftFever** [comment]
It's probably keep syncing back from the cloud.
Do you login an account?
