### ISSUE TITLE
Combing Not in Skin

### ISSUE THREAD

**Issue by LoboThirteen** [SoftFever/OrcaSlicer#1628]
Is it possible to implement a function known from Cura Slicer?  "Combing Not in Skin".  I print without Z-Hop because I don't actually need it with my RatRig.  Unfortunately, this often messes up the top layer, for example the inner bottom of a cylinder.

Attached is a link where the combining function is described.

https://all3dp.com/2/combing-mode-cura-simply-explained/

**Comment by jeremytodd1** [comment]
This feature will be in the next release. The work on it just wrapped up on this a few days ago, actually (in pull request 1562)

You can already use the feature if you download the latest nightly.  It's called Z Lift Enforcement and it does have an option to only be used on top layers.

![orca_zlift](https://github.com/SoftFever/OrcaSlicer/assets/6227771/8d2aa6fe-7c4c-407d-8490-86f9bb94a56f)

Please close this issue as it is no longer needed.

**Comment by LoboThirteen** [comment]
Cool, thank you for the quick reply!! 😊

**Comment by LoboThirteen** [comment]
Problem solved...
