### ISSUE TITLE
Z Scale In Printer Profile

### ISSUE THREAD

**Issue by s28400** [SoftFever/OrcaSlicer#1629]
To get good dimensional accuracy out of my x1c, I must scale parts around 1% larger in Z direction. Unfortunately this has to be done for every part at the model level which is annoying and leads to errors if forgotten.

It would be really helpful to have a global scale setting for the printer configuration or slicer profile. That way the slicer will scale parts without having to scale the models manually. It might also be nice to have X and Y scaling like this but I have not had an issue with x and y on my printer.

I have also considered scaling parts in my CAD but this leads to confusion when referencing the part for dimensions later or for other manufacturing methods.

**Comment by Alexx40in** [comment]
I have the same problem with my X1C.
Due to an incorrect steps-per-unit parameter in the firmware, I have to scale the model by 100.3% in the XY axes and 100.5% in the Z axis
And my case is not the only one where the manufacturer records incorrect motor steps in the firmware.
