### ISSUE TITLE
Draft shield w/ Brim feature PLEASE!

### ISSUE THREAD

**Issue by bginvestor** [SoftFever/OrcaSlicer#1630]
Printing in ABS w/o enclosure needs a Draft shield w/ Brim feature.  Can you please include a brim feature w/ skirt loops?  Thank you.

**Comment by epicylon** [comment]
Draft shield is essential for those printing ABS w/o an enclosure (yes, there's still some of us that doesn't have an enclosure). Please consider adding it to OrcaSlicer.
