### ISSUE TITLE
Height range modifier not retained in save

### ISSUE THREAD

**Issue by cutmoney** [SoftFever/OrcaSlicer#1631]
**Describe the bug**
Saving a file that has a height range modifier applied to an object does not save the height range layers.

**3mf File for This Bug**
Reproducible on every file.

**To Reproduce**
Add a height range modifier to an object. Save. Close. Reopen.

**Expected behavior**
Height range modifier and layers should be retained in the save data.

**Screenshots**

**Printer model**

**Desktop (please complete the following information):**
MacOS 13.4.1, MacBook Pro 2022

**Comment by Leorizer** [comment]
I have the same problem i am realy anoyed by this

Slicer version 1.6.3 

(Windows 10)
