### ISSUE TITLE
Pattern selection for Bridge infill

### ISSUE THREAD

**Issue by bengone1** [SoftFever/OrcaSlicer#1637]
The Bridge Infill pattern is fixed which works for most objects but when printing a spoked or hub pattern the linear pattern will end up running lengthwise along some of the unsupported areas. You can rotate it but that just changes the spoke overhang left unsupported. 

**Describe the solution you'd like**
The ability to disable bridging, select concentric, or Archimedean patterns

This seems to be unresolved in the PrusaSlicer as there are quite a few posts online with no solution.

<img width="412" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/13228862/b0b99266-4a7e-4789-865b-22544d9a9f21">

**Comment by SoftFever** [comment]
Interesting.
I experimented with it a few months back.
I didn't add it eventually as I planned to do more experiments. And also was not sure how many users atually need this.
Could you share your model?
![image](https://github.com/SoftFever/OrcaSlicer/assets/103989404/29121870-065a-4f9e-8df4-06abc61a2e7f)

**Comment by bengone1** [comment]
Sure thing, https://www.printables.com/model/450634-nintendo-switch-game-holder-updated-for-correct-st
