### ISSUE TITLE
Build height default incorrect for a Voron Trident 350 with 0.4mm nozzle

### ISSUE THREAD

**Issue by oernster** [SoftFever/OrcaSlicer#1641]
https://github.com/SoftFever/OrcaSlicer/blob/main/resources/profiles/Voron/machine/Voron%20Trident%20350%200.4%20nozzle.json#L18C24-L18C27

The above link has an incorrect build height and this caused me to break my Tap and snap off the build rail attachment by accident.  User error I know but it really needs to be fixed.  Furthermore, the expected height for a Trident 350 is 250 but the likely max is 245.

Therefore, please can you set it to 245mm for the build height.

**Comment by neeamradia** [comment]
This issue likely exists with the 300 and 200 trident profiles too.

**Comment by AlbinoDeer** [comment]
All builds should be 250mm (stock Voron config)

**Comment by SoftFever** [comment]
@oernster 
Ouch!
Somehow I was under the impression that Trident is similar to 2.4 but with about 10-20 mm less Z height.
Boy, I was wrong.

Hope your printer is fine now (hey, it's battle proven now ;)

**Comment by SoftFever** [comment]
Fixed.

**Comment by shaneshort** [comment]
It's worth noting that the LDO spec trident has a much higher Z volume, which may be where you got your information from. I don't know if it's worth having an extra profile for it or not though.
