### ISSUE TITLE
Overhangs now only in classic mode? Speed is not uniform

### ISSUE THREAD

**Issue by FillPavS** [SoftFever/OrcaSlicer#1642]
**Describe the bug**
Part of the overhang perimeter now uses the bridge speed and part of the overhang speed. This happened before if you turn on the classic mode. If you do not use the classic mode, then the speed of the perimeters of the overhangs was taken from the "Overhangs speed" for the entire perimeter. It worked fine. Now the choice of the classic mode is gone and it seems to me that it is used by default.

**3mf File for This Bug**
(https://cloud.mail.ru/public/KubT/nNmSkiLFP)

**To Reproduce**
Slice my model and see the speed

**Expected behavior**
The same speed must be applied to the entire perimeter on the overhang otherwise it causes artifacts. This worked before

**Screenshots**
Last version from Actions - https://github.com/SoftFever/OrcaSlicer/actions/runs/5707259516
![Снимок экрана (142)](https://github.com/SoftFever/OrcaSlicer/assets/17209082/9113df17-45f2-4ec3-8209-f8483c17682e)
![Снимок экрана (143)](https://github.com/SoftFever/OrcaSlicer/assets/17209082/7c39d48e-23e7-4e87-82cb-de476f782539)

Version before - https://github.com/SoftFever/OrcaSlicer/actions/runs/5656154238
without classic mode
![Снимок экрана (141)](https://github.com/SoftFever/OrcaSlicer/assets/17209082/cd24bb2c-ffa6-4d5d-9662-d13b699bedf7)

with classic mode
![Снимок экрана (140)](https://github.com/SoftFever/OrcaSlicer/assets/17209082/4fa1e8ea-dcbb-48ce-bcee-1e61888e2e6d)

**Printer model**
Bambu Lab X1C

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Last version from Actions - https://github.com/SoftFever/OrcaSlicer/actions/runs/5707259516

**Comment by nagisasatoru36** [comment]
I was creating a profile for my FLSUN Super Racer and speed seemed inconsistant as well. I check the FLSUN V400 profile and the speed behaviour is strange :

![Orca_speed](https://github.com/SoftFever/OrcaSlicer/assets/28569461/3c2517ae-8949-4321-9e4a-d079ed694895)

That infill speed is just ridiculous and doesn't match profile speed.

**Comment by FillPavS** [comment]
@nagisasatoru36 You have a different problem. In the filament settings, on the cooling tab, uncheck "Slow printing down for better layer cooling". But then the plastic may not have time to cool down and this will affect the quality of the print.

**Comment by nagisasatoru36** [comment]
> @nagisasatoru36 You have a different problem. In the filament settings, on the cooling tab, uncheck "Slow printing down for better layer cooling". But then the plastic may not have time to cool down and this will affect the quality of the print.

That woud not slow down the print that much anyway especially those infill at 30mm/s.
But just by removing ironing without touching filament cooling resolve the issue! Very strange behaviour : 

![Orca_speed_fix](https://github.com/SoftFever/OrcaSlicer/assets/28569461/0b82ef2c-0230-4eda-a6de-b7d0dad24ce2)

**Comment by Noisyfox** [comment]
> > @nagisasatoru36 You have a different problem. In the filament settings, on the cooling tab, uncheck "Slow printing down for better layer cooling". But then the plastic may not have time to cool down and this will affect the quality of the print.
> 
> That woud not slow down the print that much anyway especially those infill at 30mm/s. But just by removing ironing without touching filament cooling resolve the issue! Very strange behaviour :
> 
> ![Orca_speed_fix](https://user-images.githubusercontent.com/28569461/257138149-0b82ef2c-0230-4eda-a6de-b7d0dad24ce2.png)

Could you share your project file?
