### ISSUE TITLE
Add multi-extruder setup support

### ISSUE THREAD

**Issue by allenzha** [SoftFever/OrcaSlicer#1643]
**Is your feature request related to a problem? Please describe.**

My printer extruder structure is IDEX dual extruder head similar to BCN3D, I found that OrcaSlicer does not provide support for multi-extruder setup, and I would like to add support for multi-extruder setup.

**Describe the solution you'd like**

Add multi-extruder setup support

**Describe alternatives you've considered**

**Additional context**

**Comment by charlieburgos** [comment]
buenas, yo igual tengo un equipo dual extruder  y es necesario hoy en dia ya integrar en un laminador tan bueno como es orcaslice, la posibilidad de trabajar con dual extrusion, cambio color y pintado de partes in situ como lo hace prusa. 
me gusta mucho el laminador porque es muy eficiente, sin embargo en este punto es necesario puedan integrarlo por favor.
