### ISSUE TITLE
RatRig MCU shutdown

### ISSUE THREAD

**Issue by LoboThirteen** [SoftFever/OrcaSlicer#1653]
I have a very strange problem with the linked file. I can actually print everything on my RatRig, but when I want to print the backplate or frontplate of this file, my BTT Smart Filamentsensor is triggered in layer 2 or 3 and in layer 4 or 5 the printer makes an emergency stop with the message in the screenshot. I can slice the same file in Prusaslicer and then my RatRig prints it without any problems.

Slicer: Orca Slicer 1.6.3
Printer: RatRig V-Core 3 400
Printer Mainboard: BTT Octopus Pro 446
Raspberry Pi 3 B+

https://www.printables.com/de/model/302516-logitec-c270-focus-adjustment

![Screenshot 2023-08-01 112931](https://github.com/SoftFever/OrcaSlicer/assets/76623273/51ce365e-0a38-49a3-9bd7-f9559c4f10f0)

**Comment by Noisyfox** [comment]
Seems to be a similar issue as https://github.com/SoftFever/OrcaSlicer/issues/804
