### ISSUE TITLE
Weird flow rate behaviour

### ISSUE THREAD

**Issue by stanpete78** [SoftFever/OrcaSlicer#1657]
**Describe the bug**
In 1.6.3: If I turn off "Use relative E distances", the flow rate seems to be broken. Going up to several thousand mm3/s

**To Reproduce**
Turn off the E distances option.

**Expected behavior**
It should be correct.

**Screenshots**
see below. First one with, second one without relative E distances.

**Printer model**
Voron 2.4

<img width="492" alt="relative" src="https://github.com/SoftFever/OrcaSlicer/assets/73825064/ac9e73a8-57c9-4b21-815f-27432ebca53e">
<img width="587" alt="non-relative" src="https://github.com/SoftFever/OrcaSlicer/assets/73825064/c0ca328e-968d-4a0c-9b4f-886de2619b90">

**Comment by Habag111** [comment]
Turning off "fan speed up time" in printer settings seems to fix it for me.
