### ISSUE TITLE
Cannot drag and drop .stl or other files into OrcaSlicer

### ISSUE THREAD

**Issue by s3anami** [SoftFever/OrcaSlicer#1658]
**Describe the bug**
Cannot drag and drop .stl or other files into OrcaSlicer, have to go through the import menu to bring them in.
I could previously drag and drop, I can drag and drop in bambu studio as well.

**Expected behavior**
Let me drag and drop a file into the slicer

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 22621.1992

**Comment by Elrohir80** [comment]
I know it's closed but the same thing happened to me and I solved it by unchecking "run this as administrator"
