### ISSUE TITLE
**Layer Shift with Anycubic Korba Max**

### ISSUE THREAD

**Issue by MoeFuGithub** [SoftFever/OrcaSlicer#1659]
I am using Ancubic Korba Max with orca slicer. It is great mostly. But sometimes it shifts layers. It seems to happen when there are many pieces and over a wide area of space. It does not happen with just one or few pieces. It happend multiple times. All in the same fashion.

**Comment by foreachthing** [comment]
Here's another one: https://github.com/SoftFever/OrcaSlicer/issues/1651

**Comment by MoeFuGithub** [comment]
thanks, i left messages there too.
