### ISSUE TITLE
Per-Printer/Per-Nozzle Settings

### ISSUE THREAD

**Issue by ls-2037** [SoftFever/OrcaSlicer#1661]
**Is your feature request related to a problem? Please describe.**
Is it possible to set filament parameters per printer/nozzle size. Printing profiles are stored separately for each printer, so changing from a 0.4mm nozzle to a 0.6mm nozzle switches you to a different set of profiles. Filament settings are stored universally for all printers. However, some calibration values, such as PA, flow rate, and temperatures, would be different for different printers.

**Describe the solution you'd like**
Other slicers have macros you can insert into the filament start and end GCode to only run a line if you're using a certain printer/nozzle size. This allows (for example) different K values for PA.

It would be nice to have a user interface to manage this, but does OrcaSlicer include any such GCode macros? I haven't been able to find anything in the documentation, but I may not have looked in the right place.

**Comment by falo2k** [comment]
Adding to this as I'd at least like to see flow rate configurable per-printer.  My filament settings remain common across printers, but each may have a different hotend allowing for significantly different ceilings of flow rate (even a simply HF vs UHF).
