### ISSUE TITLE
Cable puck model - print mid air

### ISSUE THREAD

**Issue by asychev** [SoftFever/OrcaSlicer#1662]
**Describe the bug**
[Cable puck model](https://www.printables.com/model/55627-cable-puck-print-in-place-cable-management) - print mid air

**3mf File for This Bug**
[cable-puck-bug.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/12243241/cable-puck-bug.3mf.zip)

**To Reproduce**
Slice, check layer 144

**Expected behavior**
Model prints properly

**Screenshots**
![image](https://github.com/SoftFever/OrcaSlicer/assets/19927701/86da9c00-bc7d-483b-86e0-c747e649c1b5)

**Printer model**
Voron V0.2

**Desktop (please complete the following information):**
 - OS: macOS 13.4.1
 - Version 1.6.3

**Comment by TexZeTech** [comment]
Can confirm on 1.6.4-beta as well.

Linux app image.

layer 144 
gcode line # 126805 (59 on the second slider)
for the end of that line.


I used 0.2mm layer height
Changing to 0.28 didn't affect it.
this was with inner/outer/infill  using Archne generation


I changed it to infill/outer/inner ...... that _might_ work but ya this is a weird bug.

G'luck with that one.

**Comment by TexZeTech** [comment]
an individual named DT (in discord) brought a model up that has the same thing happens.
[Cap.stl.zip](https://github.com/SoftFever/OrcaSlicer/files/12266276/Cap.stl.zip)

Well Wire & myself are going to be a bunch of degenerates and try printing it off, will update with the results after.

**Comment by TexZeTech** [comment]
After lookin in prusha slicer and cura this looks like standard behavour and Softfever even wipped up an example.

![image](https://github.com/SoftFever/OrcaSlicer/assets/7254540/e55647d0-6331-4b68-b1e2-c560e81266f0)
https://discord.com/channels/1137181739773603922/1137241442281074778/1137277852962787338

[not-a-bug.zip](https://github.com/SoftFever/OrcaSlicer/files/12266399/not-a-bug.zip)

**Comment by asychev** [comment]
@TexZeTech Model has more than 100 makes on Printables, I do not believe everyone do some tricks to print it

**Comment by TexZeTech** [comment]
Install Cura slicer, Prussia slicer, super slicer, repeater host, bambu studio and post your results.
