### ISSUE TITLE
Mintion Beagle Cam

### ISSUE THREAD

**Issue by Levin08** [SoftFever/OrcaSlicer#1666]
It would be great if the Beagle Cam could be integrated as well, as it would allow me to use all printers with a single slicer.

I'm not sure what the issue is, as I'm not experienced in programming or figuring out gcode. From what I see on the camera, it doesn't seem to detect the layer height. 
![Screenshot - (42)](https://github.com/SoftFever/OrcaSlicer/assets/141300862/0b280c33-7788-4537-8591-f3e895d4aaaf)

I don't know if this is a bug or just not supported, as it seems to work with other slicers.

Other than that, I would be delighted if the Beagle Cam's problem or settings could be integrated, or if there is already a solution, I would love to know about it.

**Comment by SoftFever** [comment]
@Levin08 
Looks like Beagle Cam is not an open source project?
It would require them to add support to OrcaSlicer.

**Comment by Levin08** [comment]
Thank you for your effort, but I've already written an email myself and I am testing the beta. Thank you very much.

**Comment by SwineFlew931** [comment]
> Thank you for your effort, but I've already written an email myself and I am testing the beta. Thank you very much.

How is this working out for you? I just Downloaded Orca and am working on profiles. I contacted Mintion, got the Beta and have it on both of my Beagles. Currently printing temp tower calibrations. It seems to be working fine. Any issues for you?
