### ISSUE TITLE
Dynamic overhang fan speeds in 1.6.4 seem to be not working properly

### ISSUE THREAD

**Issue by EklDuderino** [SoftFever/OrcaSlicer#1669]
**Describe the bug**
In 1.6.4 with dynamic overhang cooling settings enabled at 50%, fan speed is not increased for overhangs like in 1.6.3

**To Reproduce**
Slice file with 50% settings for overhang cooling in 1.6.3 and 1.6.4, same file, same settings.

**Expected behavior**
Fan speeds increase for overhangs similarly in both versions 

**Screenshots**
![fansettings](https://github.com/SoftFever/OrcaSlicer/assets/125110007/d8468ae2-e8ce-4a76-8b9e-6ee35b639636)

**Printer model**
Neptune 3 Plus
**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by SoftFever** [comment]
@EklDuderino 
Thanks for reporting.
Is it convient to share the project?

**Comment by EklDuderino** [comment]
It is a paid for file, so I am unable to share. I will attempt to recreate the issue with a project I can share. Thank you.

**Comment by EklDuderino** [comment]
> @EklDuderino Thanks for reporting. Is it convient to share the project?

I cannot reproduce the issue. Both versions seem to be enforcing fan speed similarly on overhangs now. Must have been an error on my part. Although I am getting a single red 100% line in 1.6.4 on every print I slice. Probably not a big deal, just strange.
![fansettingss](https://github.com/SoftFever/OrcaSlicer/assets/125110007/0a8c819f-ce66-4c9b-af53-ae355308d398)

**Comment by SoftFever** [comment]
I noticed that too.
Gonna spend some  time to investigate it tonight.

**Comment by pennystockss** [comment]
Same here, sliced a model and no overhang slow down. If I slice it with Classic, it does slow down on overhangs. But sliced with Arachne it does not slow down whatsoever.

**Comment by SoftFever** [comment]
@pennystockss when version are you using? can you share the project file?

**Comment by pennystockss** [comment]
@SoftFever 1.6.4 beta 2. After some messing around it looks like when you turn supports on, it ignores the slow down. But only on Arachne. So:

Arachne: Fine
Arachne + Support: No slow down
Classic +-Support: Fine

![Benchy](https://github.com/SoftFever/OrcaSlicer/assets/60720749/3e0e3945-8e99-4e9d-bf01-4c708e933b70)
![classic suppport](https://github.com/SoftFever/OrcaSlicer/assets/60720749/8f65146b-4182-4340-899d-f07e1a88415e)
![Benchy Support](https://github.com/SoftFever/OrcaSlicer/assets/60720749/99195dfe-3d40-495c-bc7b-650c68a341a9)

**Comment by SoftFever** [comment]
> @SoftFever 1.6.4 beta 2. After some messing around it looks like when you turn supports on, it ignores the slow down. But only on Arachne. So:
> 
> Arachne: Fine Arachne + Support: No slow down Classic +-Support: Fine
> 
> ![Benchy](https://user-images.githubusercontent.com/60720749/258658685-3e0e3945-8e99-4e9d-bf01-4c708e933b70.jpg) ![classic suppport](https://user-images.githubusercontent.com/60720749/258658688-8f65146b-4182-4340-899d-f07e1a88415e.jpg) ![Benchy Support](https://user-images.githubusercontent.com/60720749/258658689-99195dfe-3d40-495c-bc7b-650c68a341a9.jpg)

This is different issue.
Could you log a bug for this?
I will fixed in next release

**Comment by pennystockss** [comment]
@SoftFever Opps this one is for fan speed only. Ok will make new issue for print speed slowdowns.

**Comment by pennystockss** [comment]
@EklDuderino Is it a color print by chance? I'm noticing weird fan speeds if the print is colored.

**Comment by EklDuderino** [comment]
> @EklDuderino Is it a color print by chance? I'm noticing weird fan speeds if the print is colored.

All screenshots I uploaded were for single color prints
