### ISSUE TITLE
Any plans to release a Flatpak version of OrcaSlicer?

### ISSUE THREAD

**Issue by IgnisFlamme** [SoftFever/OrcaSlicer#1670]
It would be great because downloading .AppImages from Github whenever I want to update is a pain.

**Comment by pottedplant** [comment]
Also the AppImage does not work on all distros or at least requires to manually install a bunch of stuff. `flatpak` for e.g. PrusaSlicer just works for me.

**Comment by m0d3rnX** [comment]
Reopen, the AppImage isn't running on at least Arch and OpenSUSE.

**Comment by kinghat** [comment]
looks like bambu was flatpak'd: https://github.com/flathub/com.bambulab.BambuStudio

**Comment by JaneSmith** [comment]
As a Fedora Silverblue user, I'd love a Flatpak version. Flatpak is basically the native package manager on my distro. Currently only Cura and PrusaSlicer are available (and I guess Bambu Studio as of very recently).

**Comment by hz61p1** [comment]
I second that flatpak is preferable

**Comment by StayPirate** [comment]
same here

**Comment by xpcone** [comment]
AppImage ist not working on openSuse, Arch, Gentoo, Fedora

**Comment by woolmonkey** [comment]
Yes please Appimages suck they are universal at all.

**Comment by advlogic** [comment]
Completely agree.  A Fedora package would be great as well.

**Comment by kejar31** [comment]
may be a little late to the request but yes, please release a flatpack rather than appimage

**Comment by TobiZog** [comment]
I'd like to see a Flatpak version of Orca Slicer too!

**Comment by powpingdone** [comment]
#4175 @TobiZog

**Comment by Anthony-Bec** [comment]
for some reason appimages dont work for me in kde neon

**Comment by chrisf4lc0n** [comment]
> Reopen, the AppImage isn't running on at least Arch and OpenSUSE.

I have the same issue with AppImage and Arch, try to run it from the console and see what dependencies are missing, I cannot remember what was missing but there were 2, once installed it has started without any issues.

**Comment by Prazgreen1** [comment]
This has been implemented in a nightly build. This will likely come in the next stable release with it becoming available on Flathub. At least, that is my guess.

**Comment by Prazgreen1** [comment]
just note that until it is in an official Flathub repo, you will have to uninstall and manually reinstall, but at least it is a  less painful Flatpak, because as someone who used to run the Appimage, I can easily say that Appimages SUCK. Also, with the recent drama around them, I would rather stay completely care from that packaging format if I can.

**Comment by Prazgreen1** [comment]
I do know Flatpak is currently here, but it might not work as some people, myself included, have had some issues likely related to gstreamer that breaks the print camera viewer in Orca Slicer's flatpak for some systems. I am currently daily-driving Fedora Workstation 41. I'll see if anything changes with GNOME and/or GNOME Xorg
