### ISSUE TITLE
OrcaSlicer does not comment Travel moves in outputted gcode

### ISSUE THREAD

**Issue by samwiseg0** [SoftFever/OrcaSlicer#1674]
**Describe the bug**
Currently OrcaSlicer does not comment travel moves in its outputted gcode. It does comment other feature types such as `;TYPE:Outer wall`. 

**3mf File for This Bug**
N/A

**To Reproduce**
* Add any STL to orca slicer. 
* Slice. 
* Observe that `;TYPE:Outer wall` and other types are generated as comments but `;TYPE:Travel` is not. 

**Expected behavior**
Travel moves should be be commented in the gcode. This will allow post processing scripts to better understand when moves are just for travel vs. other feature types. 

**Screenshots**
N/A

**Printer model**
N/A

**Desktop (please complete the following information):**
N/A

**Comment by SoftFever** [comment]
Travel moves don't need to be labelled as any G0/G1 command without `E` are travle moves
