### ISSUE TITLE
1.6.4-beta fails to connect to printer with TLS errors: "error:1012606B:elliptic curve routines:EC_POINT_set_affine_coordinates:point is not on curve"

### ISSUE THREAD

**Issue by samwiseg0** [SoftFever/OrcaSlicer#1675]
**Describe the bug**
Connecting to a server using TLS fails to connect and be able to upload a gcode file. There was no issue on version 1.6.3.

There is no issue viewing the web interface from the device tab. 

Full error:
```
Could not connect to OctoPrint: curl:SSL connect error:
error:1012606B:elliptic curve routines:EC_POINT_set_affine_coordinates:point is not on curve
[Error 35]
Note: OctoPrint version at least 1.1.0 is required.
```

**3mf File for This Bug**
N/A

**To Reproduce**
Not entirely sure the specifics as I have checked with other folks that use TLS and they have not experienced the same issue. I have also taken a packet capture and it indicates that the error is after the server key exchange and Orca sends back a fatal error to the webserver.

![2023-08-03_17-48](https://github.com/SoftFever/OrcaSlicer/assets/2241731/d225d426-4134-47db-ac15-74c50df26882)

**Expected behavior**
OrcaSlicer connects to a printer running TLS

**Screenshots**
v1.6.3
![2023-08-03_17-33](https://github.com/SoftFever/OrcaSlicer/assets/2241731/bd1503bc-7f36-45ab-bdf0-80e7f660f3a1)

v1.6.4
![2023-08-03_17-35](https://github.com/SoftFever/OrcaSlicer/assets/2241731/94f26c88-6dcf-472e-ab41-4cd66b96f4f2)

**Printer model**
N/A

**Desktop (please complete the following information):**
 - OS: MacOS 13.4.1 (c) (22F770820d)

Edit: This maybe related? https://github.com/openssl/openssl/issues/18225

**Comment by SoftFever** [comment]
Hmm, that's odd. I didn't update OpenSSL.

One recent change that might be relevant is PR #1157. 
Maybe @ammmze can shed some light on this matter?

If you can compile from source, try reverting that change to see if the issue persists. 
It would be very helpful to pin-point the issue as I don't have the eviroment setup to test this.

**Comment by ammmze** [comment]
Hmm, I'm not sure how disabling ATS would cause that error. But I'll do some digging when I can get to my computer. 

Another potentially relevant issue:
* https://github.com/openssl/openssl/issues/20937

**Comment by ammmze** [comment]
So far I have **not** been able to reproduce this. My cert is issued by Let's Encrypt, so I am not using a custom CA cert.

I am running on an M1 Macbook running MacOS 13.5.

Also for reference:

```
$ clang --version
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: arm64-apple-darwin22.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

```
$ xcodebuild -version
Xcode 14.3.1
Build version 14E300c
```

**Comment by ammmze** [comment]
I also just tested this on another Macbook, running an Intel processor and it worked fine as well. Also on MacOS 13.5.

The clang and xcode versions were the same, but OpenSSL version was different FWIW:

```
$ openssl version
OpenSSL 3.1.1 30 May 2023 (Library: OpenSSL 3.1.1 30 May 2023)
```

**Comment by samwiseg0** [comment]
@ammmze @SoftFever I plan on building it from source and testing. 

In the meantime I can privately share with you a public URL that should show you the error. I can PM you via discord. I joined the OrcaSlicer discord. Feel free to PM me as my username is the same. I tried looking for your usernames but they maybe different.

**Comment by ammmze** [comment]
I will try to do some more debugging tonight, but just to keep everybody updated, I have been able to re-produce the error when using the url provided via PM. So that rules out the possibility that it is isolated to the one machine running OrcaSlicer. 

Another thing I noticed is that despite receiving the error, the webview in the device tab still renders the page just fine. So the error isn't blocking the web view. So that seems even more unlikely that the issue was caused by disabling ATS as I think ATS really only applies to the web view in OrcaSlicer. I imagine that the error we are seeing would be a problem for everything else outside the webview though, so obviously ignoring the error is NOT an option.

**Comment by SoftFever** [comment]
Thank you both!

By the way, I'd like to clarify that OrcaSlicer currently doesn't have an official social platform. 
However, I'm in the process of setting up a Discord server.
Will keep you posted!

**Comment by samwiseg0** [comment]
I have good news and bad news.

Good news is after building dependencies and OrcaSlicer from source the issue is fixed. 

Bad news is I am not sure what is the root cause. 

![2023-08-04_22-26](https://github.com/SoftFever/OrcaSlicer/assets/2241731/795ef46f-3194-439c-90dc-b94a58f45b7c)
![2023-08-04_22-27](https://github.com/SoftFever/OrcaSlicer/assets/2241731/a30e23d6-fcd2-402c-b53b-6ca6de592106)

I had a hard time building when I was trying to used the cached dependencies that were in the GitHub workflow.  https://github.com/SoftFever/OrcaSlicer/blob/main/.github/workflows/build_mac_arm64.yml#L55-L59

Building everything from scratch seems to have done the trick. 

```
% clang --version
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin22.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
```
% xcodebuild -version
Xcode 14.2
Build version 14C18
```
```
% openssl version
OpenSSL 3.1.2 1 Aug 2023 (Library: OpenSSL 3.1.2 1 Aug 2023)
```

Please let me know what details you may need to track this down.

**Comment by ammmze** [comment]
On mobile right now, but Interesting, I was able to build as well but I still had the issue. Going back to https://github.com/openssl/openssl/issues/20937#issue-1704871000 they mentioned it being an issue on apple clang 14.0.3 which I  have. They mentioned rolling back to clang 14.0.0 (what you have) and the issue went away. So I guess we need to see how we can build it on 14.0.0.

**Comment by ammmze** [comment]
Looks like there is a setup code action we can use to set xcode version.

https://github.com/openssl/openssl/issues/20937#issue-1704871000

**Comment by samwiseg0** [comment]
> On mobile right now, but Interesting, I was able to build as well but I still had the issue. Going back to [openssl/openssl#20937 (comment)](https://github.com/openssl/openssl/issues/20937#issue-1704871000) they mentioned it being an issue on apple clang 14.0.3 which I have. They mentioned rolling back to clang 14.0.0 (what you have) and the issue went away. So I guess we need to see how we can build it on 14.0.0.

I checked the github build log and it looks like it is already using `14.0.0`.
![2023-08-04_23-57](https://github.com/SoftFever/OrcaSlicer/assets/2241731/bad62bfd-efb2-42b7-89ef-1ec8f1b7ad74)

**Comment by ammmze** [comment]
Hmm...I wonder if the deps were also built on 14.0.0. It looks like the deps are built separately and then extracted during the studio build.

**Comment by samwiseg0** [comment]
That was my thought as well. I tried to use the prebuilt dependencies but that did not work out. I kept getting build errors.

**Comment by ammmze** [comment]
I see there is a relatively new GitHub workflow to build dependencies and that looked to use 14.0.0, but I'm not sure those are used here. The date for deps used in the beta are from 2 days ago and the most recent deps build was like 2 weeks ago.

**Comment by samwiseg0** [comment]
Yep. Looks like they were all built 3 days ago but not by the gihub workflow. 

https://github.com/SoftFever/FileSharing/releases/tag/2023.08

**Comment by SoftFever** [comment]
No, the dependencies were not built by the CICD.
I’m currently away from my computer, so I can’t check the version at the moment.

**Comment by SoftFever** [comment]
> I have good news and bad news.
> 
> Good news is after building dependencies and OrcaSlicer from source the issue is fixed.
> 
> Bad news is I am not sure what is the root cause.
> 
> ![2023-08-04_22-26](https://user-images.githubusercontent.com/2241731/258558154-795ef46f-3194-439c-90dc-b94a58f45b7c.png) ![2023-08-04_22-27](https://user-images.githubusercontent.com/2241731/258558158-a30e23d6-fcd2-402c-b53b-6ca6de592106.png)
> 
> I had a hard time building when I was trying to use the cached dependencies that were in the GitHub workflow. I suspect these may have been built on macOS 12?https://github.com/SoftFever/OrcaSlicer/blob/main/.github/workflows/build_mac_arm64.yml#L55-L59
> 
> Building everything from scratch seems to have done the trick.
> 
> ```
> % clang --version
> Apple clang version 14.0.0 (clang-1400.0.29.202)
> Target: arm64-apple-darwin22.5.0
> Thread model: posix
> InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
> ```
> 
>  ```
> % xcodebuild -version
> Xcode 14.2
> Build version 14C18
> ```
> 
>  ```
> % openssl version
> OpenSSL 3.1.2 1 Aug 2023 (Library: OpenSSL 3.1.2 1 Aug 2023)
> ```
> 
> Please let me know what details you may need to track this down.
> 
> Edit: To add. I did try beta2 and that one was still broken.

To use the pre-built depa binaries, one will need to place the Orca Slicer in the same absolute path as the GitHub action runner uses.
/Users/runner/ something like that, you can find it in the action log

**Comment by samwiseg0** [comment]
@SoftFever Thank you for that info. That made the build succeed!

I think we are getting closer. That broke TLS again with the same error. Looks like the dependencies maybe being built with that clang version that has an issue?

```
Could not connect to OctoPrint: curl:SSL connect error:
error:1012606B:elliptic curve routines:EC_POINT_set_affine_coordinates:point is not on curve
[Error 35]
Note: OctoPrint version at least 1.1.0 is required.
```

**Comment by ammmze** [comment]
I'm in the process of:

- [x] downloading xcode 14.2 (grabbed it via https://xcodereleases.com/?scope=release)
- [x] using `sudo xcode-select -s /path/to/downloaded/Xcode.app/` to temporarily switch to that
- [ ] re-building the app

**Comment by samwiseg0** [comment]
The working and broken builds can be found [here](https://drive.google.com/drive/folders/1hVsEM7w1kkBaFgyssy9ATWz4inJ3voyx?usp=sharing).

**Comment by ammmze** [comment]
Okay, after rebuilding the entire thing with 14.2, it looks we have success. I now get a 401 Unauthorized (which is expected given I don't have the credentials, just the url).

**Comment by SoftFever** [comment]
Cool.
So, the conclusion is that both 14.0 and 14.2 work?

I just checked, and the deps binaries are built with Xcode 14.3.1 and Apple-clang 14.0.3.

I'll modify the workflow file for dependencies later so that we can use the binaries it built.
I hope it will work; I don't remember whether it's the Mac where I was having issues using the binaries built by CICD.

**Comment by ammmze** [comment]
Sorry it's kind of confusing because the versions are so close between xcode and apple-clang

The gist is:
* Xcode 14.2 contains Apple-clang 14.0.0 and that DOES works 👍🏻 
* Xcode 14.3.1 (and presumably 14.3) contains Apple-clang 14.0.3 and that DOES NOT work 👎🏻

**Comment by SoftFever** [comment]
> Sorry it's kind of confusing because the versions are so close between xcode and apple-clang
> 
> The gist is:
> 
> * Xcode 14.2 contains Apple-clang 14.0.0 and that DOES works 👍🏻
> * Xcode 14.3.1 (and presumably 14.3) contains Apple-clang 14.0.3 and that DOES NOT work 👎🏻

Great!

**Comment by SoftFever** [comment]
@ammmze @samwiseg0 
The CICD can't reliably build deps yet.

But I managed to build the apes with clang 14.0.0 and updated them.
When you got time, do you mind to give this build a test? https://github.com/SoftFever/OrcaSlicer/actions/runs/5775802841

**Comment by samwiseg0** [comment]
@SoftFever I can confirm this build works! Thank you for your efforts!

**Comment by SoftFever** [comment]
> @SoftFever I can confirm this build works! Thank you for your efforts!

Cheers! All credit goes to you and @ammmze 🥇

**Comment by ammmze** [comment]
Awesome! Great work everyone!

**Comment by SoftFever** [comment]
My bad.
I missed this.
Let me add this.

**Comment by SoftFever** [comment]
Added.
It's an amazing team work. Thank you @samwiseg0 and @ammmze 
![image](https://github.com/SoftFever/OrcaSlicer/assets/103989404/e0a42886-76c9-41f3-a083-d78f778cdf35)
