### ISSUE TITLE
PA Pattern: Extra cube being added

### ISSUE THREAD

**Issue by R4toLoko** [SoftFever/OrcaSlicer#1679]
First of all, thank you so much for everybody involved on this this PR.

I have been following that PR and did notice the little cube being added.
It looks like the PR was merged with it.
It would be cool for the non-beta release to remove that.

![image](https://github.com/SoftFever/OrcaSlicer/assets/35049512/7f0d3c33-6c86-4d27-9ac1-8a5f22da9800)

Thank you

**Comment by TexZeTech** [comment]
I found I had to add a second cube to the right side just so I can have [KAMP](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging)  probe the area correctly. 

So ideally it would still pull the dimensions of the final code generated and remove that cube from it.

**Comment by R4toLoko** [comment]
I use [Frix-x](https://github.com/Frix-x/klippain/tree/main) instead and indeed, now that you mentioned it and to actually print and no mesh is performed and Mainsail shows a small cube which I believe is that little cube I mentioned.

![image](https://github.com/SoftFever/OrcaSlicer/assets/35049512/0940a78d-1ebb-4566-a73f-16604ff98ffc)

Also, it does not respected the profile's speed.
It hurts seeing the printer at 30mm/s when it was supposed to be 105mm/s

![image](https://github.com/SoftFever/OrcaSlicer/assets/35049512/4a06b50d-f5c9-4f9f-abec-df630d1c14b9)

Ohh that is why and no idea why that 30mm/s is there:

![image](https://github.com/SoftFever/OrcaSlicer/assets/35049512/c503f67d-4025-465b-ba1f-7eea7d40a9d2)

Even if I change that, the letters are locked to 30mm/s
![image](https://github.com/SoftFever/OrcaSlicer/assets/35049512/9dd47c05-1393-46fe-9812-479bb1b7eb62)

I hope this will be fixed, it should not alter the speed/acceleration whatsoever.

**Comment by R4toLoko** [comment]
The little cube is still showing and the mesh is working as expected.
The slower first layer is a minor thing so I am closing this.
