### ISSUE TITLE
Wrong Temperature Displayed and Temperature Run Away

### ISSUE THREAD

**Issue by Newcal** [SoftFever/OrcaSlicer#1682]
**Describe the bug**
After changing the Start Gcode in My Klipper Profile or using RatRig Vcore 3.1 profile, the temperature displayed is 0 (from first layer to the last layer) - This morning after sending the g-code to the ratrig, I had a violent temp runaway - Not sure if it related to the bug...

**3mf File for This Bug**
If it is related to slicing, please append the 3mf file. It could be extremely helpful to solve the issue.
(https://drive.google.com/file/d/1TE14QAeAuFu4As82sr5fdrY3OqPKY_1J/view?usp=drive_link)

**To Reproduce**
the use of the vcore500mm printer profile or the change of the start gcode of My Klipper printer profile

**Expected behavior**
The display of the temp shows 0

**Screenshots**
<img width="903" alt="Screenshot 2023-08-04 at 1 12 51 pm" src="https://github.com/SoftFever/OrcaSlicer/assets/18645222/48b9d577-e232-4cd8-b641-e8eda9650bcd">

**Printer model**
RatRig Score 500

**Desktop (please complete the following information):**
 - OS: Mac
 - Version 1.6.3
Thank you

**Comment by SoftFever** [comment]
I don't have access to your model.

It displays 0 is most likely you set nozzle and bed temperature in print_start macro.
In that case OrcaSlicer won't know the actual temp you set in the macro.

**Comment by streetgt** [comment]
@SoftFever can we have a fix on this? Using custom start G-Code show temp as 0. Are you able to port this feature from SuperSlicer for example?

Best regards
