### ISSUE TITLE
Speed in percent

### ISSUE THREAD

**Issue by gcastle2007** [SoftFever/OrcaSlicer#1684]
Unfortunately, I did not see how to set the print speed in percent. The idea is to calculate the print speed based on the speed volumetrics. Is it possible to add this functionality?

**Comment by erentar** [comment]
I also think this is a crucial feature which needs to be implemented.
The speed settings in the slicer acts as a speed limit not to be exceeded, when the volumetric flow rate allows.
It is crucial for part quality to be able to reduce all speeds in ratio of the maximum speed set by the volumetric flow rate.
