### ISSUE TITLE
Filaments cannot be deleted

### ISSUE THREAD

**Issue by PrintModz** [SoftFever/OrcaSlicer#1685]
**Describe the bug**
I had already noted it, but even in the new version no filaments can be deleted. In addition, specially created materials cannot be deleted either. This does not work via the slicer and also not via the configuration folder.

**3mf File for This Bug**
If it is related to slicing, please append the 3mf file. It could be extremely helpful to solve the issue.

**To Reproduce**
Create filament and try to delete

**Expected behavior**
It should be possible to delete your own materials when you no longer need them.

**Screenshots**

**Printer model**
any

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 11

**Comment by Grasshopper333** [comment]
I'm currently on version 1.6.4-beta, for me deleting profiles works without any problems. It also works on 1.6.3
![image](https://github.com/SoftFever/OrcaSlicer/assets/104302206/6685056c-313e-4815-ab38-edce992e5ea9)

**Comment by SoftFever** [comment]
> I'm currently on version 1.6.4-beta, for me deleting profiles works without any problems. It also works on 1.6.3 ![image](https://user-images.githubusercontent.com/104302206/258423829-6685056c-313e-4815-ab38-edce992e5ea9.png)

Same here

**Comment by kylek29** [comment]
I had this issue as well -- on my end, I believe I had to uncheck the option to File > Preferences > "Auto Sync User Presets (Printer/Filament/Process)" option. I believe when I originally troubleshot it, I determined it was a sync issue where the Bambu server would just rewrite the deleted profile.
