### ISSUE TITLE
Wrong behavior when using "Force cooling for overhang and bridge"

### ISSUE THREAD

**Issue by Grasshopper333** [SoftFever/OrcaSlicer#1686]
**Describe the bug**
When using the "Force cooling for overhang and bridge" option the fan randomly doesn't turn off for a few layers.

**3mf File for This Bug**
[WrongFanSpeed.zip](https://github.com/SoftFever/OrcaSlicer/files/12260731/WrongFanSpeed.zip)

**To Reproduce**
Activate the "Force cooling for overhang and bridge" option.

**Expected behavior**
The fan should turn off right after the overhang 

**Screenshots**
Current behavior on version 1.6.4-beta
![image](https://github.com/SoftFever/OrcaSlicer/assets/104302206/27f7d516-f7e4-4a67-a079-b8cb7eb550ec)

Expected behavior on version 1.6.3
![image](https://github.com/SoftFever/OrcaSlicer/assets/104302206/8b58d8fc-c985-4dbc-a78b-7fb837f3df95)

**Desktop**
 - OS: Windows
 - Version:  Windows 10 Home

**Comment by SoftFever** [comment]
Thanks for reporting it.
it should have been fixed in Beta 2

**Comment by Grasshopper333** [comment]
It looks to be working now.
Thank you for the fast fix.
