### ISSUE TITLE
Printer Icon Application Crash Issue

### ISSUE THREAD

**Issue by rohanrohan** [SoftFever/OrcaSlicer#1693]
**Describe the bug**

Clicking the icon for the printer in the top left throws a error: "Unhandled unknown exception; terminating the application". The icon is right beneath the home button.

**3mf File for This Bug**
If it is related to slicing, please append the 3mf file. It could be extremely helpful to solve the issue.

**To Reproduce**
Steps to reproduce the behavior

Click the 3D printer icon, in the Printer Section.

**Expected behavior**

Not sure. On Bambu Studio it brings up Custom Printer Setup.

**Screenshots**

![image](https://github.com/SoftFever/OrcaSlicer/assets/33439902/a5cfc4f1-d752-43a3-b697-1b28f5fc6e91)

**Printer model**

Ender 3 Pro

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Windows]

1.6.4 Beta
Windows 11

**Comment by SoftFever** [comment]
Thanks reporting the issue.
I can confirm the issue.

**Comment by SoftFever** [comment]
I won't call it a proper fix.
But I will disabled the button as it's not useful in its current state anyway.
