### ISSUE TITLE
When maximized Orca Slicer window extends over the Taskbar and into the Left Monitor

### ISSUE THREAD

**Issue by DIYPERSPECTIVE** [SoftFever/OrcaSlicer#1697]
**Describe the bug**
Orca Slicer window extends onto the left of the monitor (2x 1920x1080p monitor setup) and onto the taskbar. No such issue with the Bambu Studio slicer. But it always was (at least for a couple of months when I started using it) on the Orca Slicer.

**To Reproduce**
Maximize it and open any browser maximized on top to see the issue more clearly. Also, you will need a multi-monitor setup.

**Expected behavior**
Should not overlap with other screens and onto the taskbar when maximized

**Screenshots**
![IMG_20230805_100336](https://github.com/SoftFever/OrcaSlicer/assets/139345648/38e13940-bc94-430c-8e3e-818c7e3f45d0)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by foreachthing** [comment]
Not happening on Win11 and Orca 1.6.3, left 1680 x 1050 and right 1920 x 1200.
Maybe try to update your graphics driver?!

**Comment by DIYPERSPECTIVE** [comment]
> Not happening on Win11 and Orca 1.6.3, left 1680 x 1050 and right 1920 x 1200. Maybe try to update your graphics driver?!

It's up to date. I don't have this issue with the Bambu Studio slicer, it is clearly something in the Orca that makes this bug. I don't remember if I ever saw a bug like this ever with any program. I would just rescale the window but Orca doesn't save the window size and position on exit.

**Comment by bani6809** [comment]
Windows 10, dual 4k displays, I don't get this bug with orca 1.6.3

**Comment by DIYPERSPECTIVE** [comment]
Issue FIXED with v1.6.6
