### ISSUE TITLE
No Object_height in klipper

### ISSUE THREAD

**Issue by persano** [SoftFever/OrcaSlicer#1703]
I would like to know if someone know how to add this variable to the gcode. I have not seen it anywhere

It works with other slicers but never worked for me with orca slicer. This is not new, it happened to me since the first time I started using the slicer. It is a minor thing, but it is great to have more information regarding the files you are printing

![imagen](https://github.com/SoftFever/OrcaSlicer/assets/55957230/86eda065-5eb3-41f1-95ba-de6fea8b8805)

**Comment by SoftFever** [comment]
Thanks for reporting it.
Will take a look

**Comment by SoftFever** [comment]
Hi @persano 
can you share your gcode?
also what's your Moonraker version? And what frontend are you using, fluidd or mainsail?

It works fine on my machien with Mainsail


![Image](https://github.com/SoftFever/OrcaSlicer/assets/103989404/5d5df326-daac-4fa8-9b35-8fd416aa0f2e)

**Comment by persano** [comment]
@SoftFever here is the GCODE. 

[Uploading xyzCalibration_cube_PLA_22m57s.zip…]()

**Comment by Sineos** [comment]
Try https://docs.mainsail.xyz/overview/slicer/prusaslicer

**Comment by persano** [comment]
> Try https://docs.mainsail.xyz/overview/slicer/prusaslicer

![imagen](https://github.com/SoftFever/OrcaSlicer/assets/55957230/c9d9894b-abe0-4cf3-8c3b-71b332f5cf69)

**Comment by persano** [comment]
Here is the modified file, @Sineos 

[xyzCalibration_cube_PLA_25m25s.zip](https://github.com/SoftFever/OrcaSlicer/files/12315833/xyzCalibration_cube_PLA_25m25s.zip)

**Comment by Sineos** [comment]
![grafik](https://github.com/SoftFever/OrcaSlicer/assets/4459312/86550c31-5461-4936-8c03-1116ee470f5d)

Strange. Generally it works on my end, however your file indeed does not show any height. Sorry, no idea, but I'd suppose it is some setting thing

**Comment by SoftFever** [comment]
@Sineos @persano 
I think I found something.

Moonraker rely on the custom layer change gcode to calc object height.
Probably your machine profile don't have that one or you removed it.

Put this in before layer change gcode
```
;BEFORE_LAYER_CHANGE
;[layer_z]
G92 E0
```
and this in Layer change gcode
```
;AFTER_LAYER_CHANGE
;[layer_z]
```
![image](https://github.com/SoftFever/OrcaSlicer/assets/103989404/c928bc2a-086e-4b07-b4ed-db18e29f2de4)

It should fix the issue.
Let me know what machine profile are you using, I will fix it.

**Comment by persano** [comment]
> @Sineos @persano I think I found something.
> 
> Moonraker rely on the custom layer change gcode to calc object height. Probably your machine profile don't have that one or you removed it.
> 
> Put this in before layer change gcode
> 
> ```
> ;BEFORE_LAYER_CHANGE
> ;[layer_z]
> G92 E0
> ```
> 
> and this in Layer change gcode
> 
> ```
> ;AFTER_LAYER_CHANGE
> ;[layer_z]
> ```
> 
> ![image](https://user-images.githubusercontent.com/103989404/260027881-c928bc2a-086e-4b07-b4ed-db18e29f2de4.png)
> 
> It should fix the issue. Let me know what machine profile are you using, I will fix it.

Creality Ender 3 V2, which I used as a base for my Creality CR6. Both run marlin by default but I am using klipper with my machine.

And I can confirm that with the BEFORE_LAYER_CHANGE part now I can see it!

![imagen](https://github.com/SoftFever/OrcaSlicer/assets/55957230/2d950c6b-0f49-4b8e-bef0-398966fe37fc)

![imagen](https://github.com/SoftFever/OrcaSlicer/assets/55957230/5bf93eb5-3f36-418b-99b7-96c5f37cee40)

**Comment by SoftFever** [comment]
Cool, thanks for the confirmation.
