### ISSUE TITLE
Brim descripiton - outer only 

### ISSUE THREAD

**Issue by szafranski** [SoftFever/OrcaSlicer#1706]
Hi,

Just wanted to let know that "Outer only" brim name is probably wrong (seems like a variable or sth, not a GUI description:

![image](https://github.com/SoftFever/OrcaSlicer/assets/23621888/321897b6-d537-4b51-af13-511a6d429461)

**Comment by Eldenroot** [comment]
it is fixed

**Comment by Mario-vminion** [comment]
when you have a  small gap and its not a closed inner circle the brim will be in and outside...i had selected only outside
![IMG_5249](https://github.com/SoftFever/OrcaSlicer/assets/100128032/05aa1c31-451c-4d8f-b509-d9444bae8fc7)
