### ISSUE TITLE
Orcaslicer will not preview above layer 1 in calibration test

### ISSUE THREAD

**Issue by tastyratz** [SoftFever/OrcaSlicer#1708]
**Describe the bug**
I am running the new 1.64 beta 2 on W10 22H2.

If I generate a PA calibration tower and slice, the preview automatically goes down to layer 1 and will not allow me to adjust the slider to show other layers.
I do not see this behavior if I slice a normal part outside of that calibration. A PA pattern test does not have this problem.

This also impacts the estimated time/filament as well for the test.
PA tower image inside of Mainsail appears correct and shows 256 layers while the preview does not.
It does, however, only print the first layer as it appears in the preview. even though it's reporting all 256 layers at the printer.
I can not generate a successful pressure advance tower in 1.64 B2.

**Comment by tastyratz** [comment]
Screenshot for posterity 
![image](https://github.com/SoftFever/OrcaSlicer/assets/657895/6a7e0b88-5a3e-467a-8da8-433aca6fe90c)

**Comment by SoftFever** [comment]
@tastyratz 
Thanks for reporting it.
I probably should have enable the `detect thin walls`
Could you try to enable this option manually? that should fix the issue
![image](https://github.com/SoftFever/OrcaSlicer/assets/103989404/631097f0-ce6a-43e8-910b-c1cdf2685ee8)

**Comment by tastyratz** [comment]
> @tastyratz Thanks for reporting it. I probably should have enable the `detect thin walls` Could you try to enable this option manually? that should fix the issue ![image](https://user-images.githubusercontent.com/103989404/258614436-631097f0-ce6a-43e8-910b-c1cdf2685ee8.png)

Unfortunately, the checkbox for detect thin walls is grayed out for me. It's something I've been noticing lately but from what I can read online that option typically ends up creating more weird artifacts than improving quality so I wasn't worried.
I don't see anything in a tooltip saying why or when that option might not be selectable. What would make it grayed out?

**Comment by tastyratz** [comment]
Curiously, this option is also not selectable for me on my 1.63 install on my laptop however I am able to generate a successful tower without it there

![image](https://github.com/SoftFever/OrcaSlicer/assets/657895/aced65aa-ef74-45f3-93c7-52dd8aace2e2)

**Comment by Habag111** [comment]
"detect thin walls" is available only for classic wall generation, not arachne (at least that's how I understand it). turning it on fixes the PA tower for me as well (it should be enabled by default when calibrating with the PA tower imo)

**Comment by SoftFever** [comment]
I will revert the changes I made in beta 2 for PA tower.
It did a poor job when line width is not around 0.45

**Comment by tastyratz** [comment]
I was able to get this to generate btw by checking detect thin walls. This is not automatically checking when switching to classic mode from Arachne.

This checkbox should probably also have a tooltip text addition along the lines of "This option is not compatible with Arachne and can only be checked when using the Classic Wall Generator".
