### ISSUE TITLE
Elegoo Neptune 4 Pro

### ISSUE THREAD

**Issue by jkjerde** [SoftFever/OrcaSlicer#1722]
Please add Elegoo Neptune 4 Pro to the printers

Thanks

**Comment by exen904** [comment]
You can easily do that yourself by changing the print size possible

**Comment by DVSVIDEO** [comment]
> Please add Elegoo Neptune 4 Pro to the printers
> 
> Thanks

Add your own. You have the possibility to adjust the size of the bed, the Z height. Then copy the settings from the other slicer and you're done.
