### ISSUE TITLE
Filter out gaps

### ISSUE THREAD

**Issue by inline6power** [SoftFever/OrcaSlicer#1751]
Is there a way to filter out gaps like superslicer does? I have tried everything from detect narrow walls ect. Pic below is of the same part at the same layer height. Super does an a amazing job at this and just can’t get rid of it on certain parts![image](https://github.com/SoftFever/OrcaSlicer/assets/1999950/850a4847-19df-4e55-8890-d1ff133b60a0)

**Comment by kylek29** [comment]
Are we talking about the gaps on the red portion? The small holes that are present in the OrcaSlicer side?

If so, I've noticed this as well, it's related to Arachne (going back years across different slicers) -- if you switch to Classic, those go away. Did you have Arachne selected in SuperSlicer? Maybe it's doing something to fix that.

**Comment by inline6power** [comment]
> Are we talking about the gaps on the red portion? The small holes that are present in the OrcaSlicer side?
> 
> 
> 
> If so, I've noticed this as well, it's related to Arachne (going back years across different slicers) -- if you switch to Classic, those go away. Did you have Arachne selected in SuperSlicer? Maybe it's doing something to fix that.

I am talking about orca not utilizing gap fill as super slicer does. You can see in super the white gap fill is a continuous line. Where as on orca it stops and adds yellow internal wall. This is witu classic calls not Arachne. Both are set to the same standard

**Comment by dartrax** [comment]
Having the same question!

**Comment by mojotaker** [comment]
Having the same issue, its as if gap fill does not exist in Orca slicer

**Comment by DennisRoschke** [comment]
Same

**Comment by erlis** [comment]
You set the Gap Fill speed to zero and it disable gap fill, set a speed and then you have gap fill. I think we need the check box back! If I remember correctly this is how was in Prusa Slicer long time ago, but they added a check box...

**Comment by dartrax** [comment]
The title and the first post is misleading here.
The question is not how to disable Gap fill.
The question is:

> I am talking about orca not utilizing gap fill as super slicer does. You can see in super the white gap fill is a continuous line. Where as on orca it stops and adds yellow internal wall.

![image](https://github.com/SoftFever/OrcaSlicer/assets/15105943/0123c42f-7b13-4026-a339-f7723ea6fbbf)

> You set the Gap Fill speed to zero and it disable gap fill, set a speed and then you have gap fill. I think we need the check box back! If I remember correctly this is how was in Prusa Slicer long time ago, but they added a check box...

Gap fill speed mustn't be set to zero. Instead, use the "Filter out tiny gaps" threshold - even better than a check box ;-)
