### ISSUE TITLE
Orcaslicer angle referencing the bed, not the part. Impacts shell patterns, infill direction

### ISSUE THREAD

**Issue by tastyratz** [SoftFever/OrcaSlicer#1754]
**Describe the bug**
Orcaslicer is not pinning the angle of things like infill direction and shell surface patterns to the part. I.E. with an infill angle of 45 degrees and a part rotated 135 degrees the infill is actually produced as straight lines. This is something I first noticed on monotonic surface patterns. It's especially visible if you have any odd rotations not in 45 deg increments like 120 deg.

**To Reproduce**
Rotate any part and inspect the sliced preview

**Expected behavior**
Things like infill and surface pattern angle should be pinned to part, not bed. This can create strange unexpected results both cosmetically and structurally

**Screenshots**
Example SS of Orca
![image](https://github.com/SoftFever/OrcaSlicer/assets/657895/2ce38270-cb8e-4658-997a-2c9ff964c77b)

**Printer model**

**Desktop (please complete the following information):**
This has been confirmed in both 1.64B2 and 1.63 on Windows 1022H2. 
It also happens in Superslicer and apparently Prusaslicer. 

I found this https://github.com/prusa3d/PrusaSlicer/issues/1529
and really like the idea of a per object pattern option of "angle reference" being per object/per bed to satisfy this. Otherwise, any rotated parts are going to be visually and structurally different and that won't be intuitive.

**Comment by SoftFever** [comment]
There is pros and cons.
But what you wanted can be done by simply rotating the model?

**Comment by tastyratz** [comment]
You are correct, rotating the model is both the fix and the problem.
The challenge is that it's not intuitive or an expected result. If I cram a plate and manually rotate something just slightly to make it fit, I might not notice that it has a 35 degree monotonic surface finish until AFTER I print the part and see it looks different from the rest of the plate.
I've been paying no attention to how I organize parts on the plate until today because I didn't think it much mattered unless I was doing a 45 degree rotation for surface quality, like selectable in SuperSlicer or requested in https://github.com/SoftFever/OrcaSlicer/issues/1412

If I rotate a square part 45 degrees for wall surface finish quality then all my monotonic shell finishes are going to just be straight awkward lines and my infill pattern rotation won't match. If Infill rotation was pinned to part rotation, and shell monotonic finishes were pinned to part rotation, then parts are going to have a consistent print finish and strength no matter how they are oriented on the plate. The fact that they do not do this today is unexpected behavior.

**Comment by Sineos** [comment]
I stumbled across this as well, but this is not going to be easy or even possible:
* For rectangular object it should work
* But even there, how do you choose your reference edge?
* What are you doing if you have an irregular object?

In the end, the only possible solution would be to use a minimum bounding box and then choose the longest edge of this box as your reference for determining the 45° (then surely folks will come and demand that the short edge should be chosen)

**Comment by tastyratz** [comment]
Well, for monotonic to work, it goes left to right at a 45 degree angle, correct?
https://help.prusa3d.com/article/infill-patterns_177130
Wouldn't/shouldn't that already be aligned with the longest edge for it to make sense? I would think that's going to make the most consistent surface quality? 

As it is today, the choice for 45 degree rotation on corexy means either choosing best wall visual quality or best surface quality.

As far as solutions, there are a few possibilities:

Maybe it could be solved with a top surface pattern option - Pattern orientation: part Y (default)/part x/bed

Tooltip:
This override changes the 0 degree alignment for infill and monotonic surface patterns. It's useful when using non-0 degree part orientations on the bed or printing parts that are not square to the xy plane.

***

The other and more simple solution may just be to have a monotonic 45 degree top surface option and then people just need to change their default infill directions. The latter will be more important to set in profiles if Orca adopts a default part orientation option like Superslicer has.

If we think about the typical use case though, it's that parts are typically square to their STL file where you can assume most align a long or short edge with Y.

**Comment by iitsalex** [comment]
Automatic part orientation is in review now #1412
