### ISSUE TITLE
Modifier causes object to be effectively cut

### ISSUE THREAD

**Issue by tve** [SoftFever/OrcaSlicer#1758]
**Describe the bug**
When I add a modifier to change the printing speed the region inside the modifier is sliced as if it were its own object. Here's an example:

![image](https://github.com/SoftFever/OrcaSlicer/assets/39480/0de2b1ef-3876-47fb-a216-b97001b8ecbc)

results in 

![image](https://github.com/SoftFever/OrcaSlicer/assets/39480/0f6e396c-81f3-4d9c-b674-e0a3c79af007)

notice how the object is sliced as if it were two objects that abut.

**3mf File for This Bug**
[dovetails.3mf.tar.gz](https://github.com/SoftFever/OrcaSlicer/files/12307838/dovetails.3mf.tar.gz)

**To Reproduce**
- add any shape
- add a cube modifier
- edit the object settings for the modifier and change the speed of the outer wall or inner wall
- slice

**Expected behavior**
I expect the gcode to stop the lines, change speed, and continue at the change speed without changing how the object is otherwise sliced.

**Printer model**
Bambu X1C

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: Orca slicer 1.6.3

**Comment by foreachthing** [comment]
You're in for a treat!
That issue comes with, at least, PrusaSlicer. Maybe even Slic3r.
That was one issue I found - https://github.com/prusa3d/PrusaSlicer/issues/8121 - there are many, many more! And I don't think this is ever going to be fixed - ever! My personal opinion 😉
