### ISSUE TITLE
Different Pressure Advance values for each line type

### ISSUE THREAD

**Issue by steezyprintz** [SoftFever/OrcaSlicer#176]
Pressure Advance setting is great for the outer walls but when it comes to all the other line types the ability to fine tune each one differently is even better for more control over the inside.

I can see little gaps in the inner walls at corners of test cube due to the PA setting being globe to all line types.

Different speeds etc on different line types I have experienced with an ender 3 klipper build to need different PA values, tuning each one leads to a very well printed inside and out. Top and bottom surfaces edges can be made so much smoother at higher speeds by doing this I found with my build. Below is an image of what I mean from Cura.

![pa cura](https://user-images.githubusercontent.com/113864702/212477326-2d1789ee-9482-4f52-83d7-9b75834f41f6.JPG)

**Comment by SoftFever** [comment]
In my opinion, setting a separate PA for each line type is excessive as PA is directly related to the speed.
