### ISSUE TITLE
Tree Supports generating in mid air

### ISSUE THREAD

**Issue by igiannakas** [SoftFever/OrcaSlicer#1762]
**Describe the bug**
Tree supports generating in mid aid

**3mf File for This Bug**
3MF file can be found here: https://drive.google.com/file/d/1kAI4HKzYP2B18Y9GzfxTLOgutggixnc9/view?usp=share_link

**To Reproduce**
Slice model with Tree slim supports and the recommended settings

**Expected behavior**
No rogue extrusions happen

**Screenshots**
![Screenshot 2023-08-10 at 12 57 29](https://github.com/SoftFever/OrcaSlicer/assets/59056762/9e22927b-345b-46d3-9bc5-88b7b2c3c904)

**Printer model**
Bambu Lab X1 carbon

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: 1.6.4 Beta 2

**Comment by igiannakas** [comment]
Also issue happening upstream with Bambu slicer. Fix appears to have been identified upstream: https://github.com/bambulab/BambuStudio/issues/2115

**Comment by igiannakas** [comment]
Tested with latest code commits for 1.6.4-beta3. Issue appears a bit better (?) but still present.
![Screenshot 2023-08-11 at 15 16 37](https://github.com/SoftFever/OrcaSlicer/assets/59056762/65df01a9-0ca4-4d38-9fe5-e91eedfa096a)

**Comment by rfield19** [comment]
j
#
'/..22222222'#
;/this has been fixed in bs 1.7.4.52 - would be amazing if it arrives in orca12222"/;no#

**Comment by rfield19** [comment]
/
/
/
/

**Comment by igiannakas** [comment]
I’ve created a PR for this as I’ve ported over the code change from Bambu studio as I needed this to work for a model I’m printing :)
