### ISSUE TITLE
Arachne w/ Support breaks Slowdown on Overhang feature

### ISSUE THREAD

**Issue by pennystockss** [SoftFever/OrcaSlicer#1763]
**Describe the bug**
Arachne with Support, you do not get Slowdowns on Overhangs.

**3mf File for This Bug**
N/A

**To Reproduce**
Enable Supports with Arachne.

**Expected behavior**
To slowdown.

**Screenshots**
![classic suppport](https://github.com/SoftFever/OrcaSlicer/assets/60720749/09d2323f-f6da-4da6-8060-d07aab88cc61)
![Benchy Support](https://github.com/SoftFever/OrcaSlicer/assets/60720749/fe834f50-a865-49e6-88d6-201e9b37a0d3)
![Benchy](https://github.com/SoftFever/OrcaSlicer/assets/60720749/f1dece37-5873-488e-89e5-b1ca5f9c46c7)

**Printer model**
P1P

**Desktop (please complete the following information):**
 - OS: Windows 11
 - 1.6.4 Beta 2

**Comment by SoftFever** [comment]
Fixed in dev branch

**Comment by HahBikes** [comment]
Hey @pennystockss, totally unrelated to this, but would you mind sharing your support settings?
I can't get them to generate like this with my profile. (See this [issue](https://github.com/SoftFever/OrcaSlicer/issues/1750) that I created)
