### ISSUE TITLE
External hole step bug

### ISSUE THREAD

**Issue by LD3D** [SoftFever/OrcaSlicer#1764]
![capture-20230810-080740](https://github.com/SoftFever/OrcaSlicer/assets/53282402/a10bc74a-ca56-4da8-b712-1c89f6bb9dc3)
![capture-20230810-080832](https://github.com/SoftFever/OrcaSlicer/assets/53282402/6edac0e3-ba79-4f13-a0af-5a9d001baf89)
![capture-20230810-080658](https://github.com/SoftFever/OrcaSlicer/assets/53282402/6a59c75a-4423-4236-87db-4a0d353f53c0)

**Comment by SoftFever** [comment]
Hi,
Can you please provide move info of the issue and the project file ?

**Comment by LD3D** [comment]
I can not provide my file it is private. Im not sure what you need as your other request what move info?

**Comment by LD3D** [comment]
**Describe the bug**
When there is a hole in the side of a part, any shape, the top of that hole makes a step in the outer wall inner layer by one path smaller then the wall should be. This is compounded if ther are 2 holes in the outer wall one above the other causing a stare step in and out on the inner side of the wall. The outer side of the wall is remaining as smoothe it is only stepping the wall on the inside of the part with holes going all the way through a part.

**3mf File for This Bug**
I can not attach the models as their private.

**To Reproduce**
Any part with walls make a hole through the outer wall a through hole say 3mm in a 3mm wall. Slice the part and the step at the top of the hole on the inside of the part will be present

**Expected behavior**
the step in the top of the wall should not be there. the wall has a consistant thickness but after the slicing it is stepped.

**Screenshots**
I have attached several screenshots to help show this in detail.

**Printer model**
Custom, Printer is not the concern here this error happens on all my printers from bambu to my custom printers.

**Desktop (please complete the following information):**
 -Windows 10

**Comment by LD3D** [comment]
Make a part any shape put a hole through the side and slice the file it will step the inside at the top of the hole as my image shows above
