### ISSUE TITLE
Selectable default tick boxes when printing via the cloud

### ISSUE THREAD

**Issue by steezyprintz** [SoftFever/OrcaSlicer#177]
I am almost always deselecting 3 tick boxes each time I print via the cloud.
I would love to have a selectable default option. For example use AMS only that I configure myself.

![print tick boxes](https://user-images.githubusercontent.com/113864702/212482004-c67bca6f-3db3-4014-befa-6d1faa9c29f3.JPG)

**Comment by SoftFever** [comment]
I will add a feature so that it will remember your choice.

**Comment by SoftFever** [comment]
fixed in 6f5af33c2d6bd7cbcf1a637638ef3e89e334493b
