### ISSUE TITLE
Can't import config

### ISSUE THREAD

**Issue by fedonkin** [SoftFever/OrcaSlicer#1770]
**Describe the bug**
I exported the config before reinstalling windows...After that I decided to import the config file...And the alert popped up: 
"**There are 0 configs imported**"
What to do?

![Снимок](https://github.com/SoftFever/OrcaSlicer/assets/43302315/f7fe5bfd-59e3-4711-af77-ad247f49d27f)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by theophile** [comment]
It would help to know what the config importer is looking for. I've encountered many .json files that won't import but work fine when placed in the appropriate subdirectory.

**Comment by fedonkin** [comment]
> Было бы полезно узнать, что ищет импортер конфигурации. Я сталкивался со многими файлами .json, которые не импортируются, но нормально работают, если их поместить в соответствующий подкаталог.
Не подскажите  в какой каталог нужно кидать?
