### ISSUE TITLE
Sliced object has holes and missing walls

### ISSUE THREAD

**Issue by Matei-alt** [SoftFever/OrcaSlicer#1773]
**Describe the bug**
OrcaSlicer adds holes and removes walls when sliced and the issue was repaired completely when I opened a 3mf from PS and imported only the geometry ( as OrcaSlicer could not import the settings ).
After opening the 3mf all models slice well.

**3mf File for This Bug**
https://discord.com/channels/460117602945990666/461133450636951552/1139553526192803900
In the Voron discord, in #slicers_and_print_help .

**To Reproduce**
I haven't been able to reproduce the issue.

**Expected behavior**
The sliced object to be accurate to the provided 3d model.

**Screenshots**
![image](https://github.com/SoftFever/OrcaSlicer/assets/127838087/5abfbcda-aae6-41d1-989c-400db5b04a79)
![image](https://github.com/SoftFever/OrcaSlicer/assets/127838087/aef59665-c38b-4468-bf55-1ea4325f780b)
![image](https://github.com/SoftFever/OrcaSlicer/assets/127838087/8595d715-8750-4364-89f4-086f3c454da8)
![image](https://github.com/SoftFever/OrcaSlicer/assets/127838087/1ec5a2c1-1ee9-4ea0-a2a6-aaccab2fe0cd)

**Printer model**
Ender 3 pro to Voron Switchwire

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Version: 21H2

**Comment by Mr-Savag3** [comment]
I am having the same problem. I changed no settings from when I sliced this same model and printed it yesterday. ...ignore that it's a scary Roper for DnD. 
![Capture](https://github.com/SoftFever/OrcaSlicer/assets/110316104/889760a1-3717-45f2-af54-829bcc842685)

**Comment by yachal-upson** [comment]
Have just encountered this. Can't think what I've changed to generate the issue. Same Solidworks base model, same STEP format. Similar slicer profiles. 

Hit print without looking closely enough and got some very interesting spaghetti

**Comment by boyagogo** [comment]
I'm having the exact same problem files I sliced yesterday that were fine are now loosing walls.  Any of the previous posters find a solution?

**Comment by Mr-Savag3** [comment]
I fixed it. There's a setting (I don't remember which one) that asks for either a % or mm. If you don't type mm, it assumes % and it destroys walls.

**Comment by boyagogo** [comment]
> I fixed it. There's a setting (I don't remember which one) that asks for either a % or mm. If you don't type mm, it assumes % and it destroys walls.

THIS!  It was the Seam Gap modifier.  I had changed it from 10 to 8.  I suspected this but when I changed it back without the % I didn't notice the difference.  Thanks
