### ISSUE TITLE
Flow::spacing() produced negative spacing. Caused by Wall Loops

### ISSUE THREAD

**Issue by FaanPret** [SoftFever/OrcaSlicer#1775]
As soon as I change the wall loops to 4 from 3 I get the above error.  When I change it back to 3 it slices fine.

**3mf File for This Bug**
If it is related to slicing, please append the 3mf file. It could be extremely helpful to solve the issue.

error
![image](https://github.com/SoftFever/OrcaSlicer/assets/52246804/3d7608d8-3893-4d11-8596-ec03ee10c3cf)

with 3 walls
![image](https://github.com/SoftFever/OrcaSlicer/assets/52246804/6dfd53e3-5403-497b-9c13-98a321253561)

Version 1.6.4-Beta2

Printer: Creality CR10 v2

**Comment by TechRize** [comment]
Had the same problem. Not fixed.
