### ISSUE TITLE
bridging fan speed wrong with classic wall generator

### ISSUE THREAD

**Issue by Luke56784** [SoftFever/OrcaSlicer#1776]
**Describe the bug**
If I choose classic wall generator the fan speed is wrong in the bridging layer
With arachne it's correct.

**3mf File for This Bug**
[3MF_Duschknauf_CassicWallGenerator_bridging.zip](https://github.com/SoftFever/OrcaSlicer/files/12325305/3MF_Duschknauf_CassicWallGenerator_bridging.zip)

[STEP_Duschknauf v1.zip](https://github.com/SoftFever/OrcaSlicer/files/12325308/STEP_Duschknauf.v1.zip)

**To Reproduce**
Slice the modell. Go to the bridging layer almost on top.
Choose classic or arachne wall generator.

**Expected behavior**
both should run the fan on 100% for the complete layer

**Screenshots**
![image](https://github.com/SoftFever/OrcaSlicer/assets/126562710/893f4d39-943e-4c03-b0ca-931975bd6cdf)

**left: arachne , right: classic**

**Printer model**
Bambulab P1P

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Version 22H2
 - 1.6.3 + 1.6.4 Beta 2

**Comment by SoftFever** [comment]
@Luke56784 
I can't repro it.
Can you save it as project then share it?

[Duschknauf v1.zip](https://github.com/SoftFever/OrcaSlicer/files/12328701/Duschknauf.v1.zip)

**Comment by Luke56784** [comment]
Ah it was my fault.
Now it is a project file.

[Bridging_error_project_file.zip](https://github.com/SoftFever/OrcaSlicer/files/12329293/Bridging_error_project_file.zip)

I used 1.6.3

**Comment by lhndo** [comment]
similar to : https://github.com/SoftFever/OrcaSlicer/issues/1728

**Comment by Luke56784** [comment]
@SoftFever 
Could you reproduce it?
