### ISSUE TITLE
[Feature Request] - All Plates Stats - Total Cost

### ISSUE THREAD

**Issue by ondrovic** [SoftFever/OrcaSlicer#1781]
**Is your feature request related to a problem? Please describe.**
When slicing multiple plates, on the summary page it would be nice if there was a **Total Cost** that is a running total form each of the plate "Cost" fields, should also factor in https://github.com/SoftFever/OrcaSlicer/issues/571 (if implemented)

**Describe the solution you'd like**
A Total Cost on the all plate stats

**Describe alternatives you've considered**

**Additional context**
Current Total Stats
![image](https://github.com/SoftFever/OrcaSlicer/assets/3682042/068d24df-c10c-478b-92b8-75e55d0264a6)
Plate 1 Example
![image](https://github.com/SoftFever/OrcaSlicer/assets/3682042/9d9f4389-5393-47a2-b1ff-53e1c6e5f9ff)
Plater 2 Example
![image](https://github.com/SoftFever/OrcaSlicer/assets/3682042/a5eb2760-25bc-415c-b8fd-5af41969a7aa)
Plate 3 Example
![image](https://github.com/SoftFever/OrcaSlicer/assets/3682042/30504d7f-3502-477f-b1d4-ee6da85eb127)
Plate 4 Example
![image](https://github.com/SoftFever/OrcaSlicer/assets/3682042/f9ee702a-2730-4ae6-a59b-204beb0a027f)
Proposed Total Stats after this feature
![image](https://github.com/SoftFever/OrcaSlicer/assets/3682042/a9a8e104-86e1-45d6-ae3f-9ec34d5c0b6e)

**Comment by KD7LRJ** [comment]
We often group parts that need to be printed multiple times onto different plates. If this suggestion is implemented, a very close companion enhancement would be a way to specify how many copies of a plate are needed in a complete project.

It may work to be able to save a screenshot or export a summary of the totals and save them in the project directory for billing or future reference purposes.

**Comment by DVSVIDEO** [comment]
> We often group parts that need to be printed multiple times onto different plates. If this suggestion is implemented, a very close companion enhancement would be a way to specify how many copies of a plate are needed in a complete project.
> 
> It may work to be able to save a screenshot or export a summary of the totals and save them in the project directory for billing or future reference purposes.

Total =1 disk+2disk+3disk....+xdisk (computer at hand, windows has calculator)
There are screen saver applications for printing the list, which can also save regions (realdraw pro)

**Comment by discip** [comment]
@ondrovic
This Feature Request should be covered by #2238.
Please don't forget to close. 😊
