### ISSUE TITLE
I-Fast

### ISSUE THREAD

**Issue by KnowKontrol** [SoftFever/OrcaSlicer#1784]
Could you please please add the Qidi I-Fast to the list of printers! PLEASE PLEASE I LOVE YOU!

**Comment by DVSVIDEO** [comment]
Add your own. You have the possibility to adjust the size of the bed, the Z height. Then copy the settings from the other slicer and you're done.

**Comment by donnydavis** [comment]
Good luck. They use a firmware that makes you have to sneaker net files to the printer. 

In case you need the parameters for the machine, they can be found here. 

https://github.com/QIDITECH/Qidi-Print/blob/main/resources/definitions/i-fast.def.json

**Comment by FrancescoFR** [comment]
how do I add this printed in orcaslicer? Thank you

**Comment by mirspan** [comment]
I created a profile for QIDI i-Fast. Must test! To import into OrcaSlicer.

[Printer presets.zip](https://github.com/user-attachments/files/20744696/Printer.presets.zip)

**Comment by kiryutin-a** [comment]
> I created a profile for QIDI i-Fast. Must test! To import into OrcaSlicer.
> 
> [Printer presets.zip](https://github.com/user-attachments/files/20744696/Printer.presets.zip)

Hi. Thank you so much.
I tried, it works, but there are small issues.
In qidi ifast extruders are changing by moving the head to the right or to tve left position.
So, your profile dkes nkt include this option.
I need to press manualy the pin to change extruder.
Also, it seems that orca with this preset csn not operate  second extruder.
I think starting G ckde in the preset has to  be modified, but i dont know how to specify extruder there.

Please give me advise.

**Comment by stangs4** [comment]
I would also like to utilize Orca slicer with a Qidi i-Fast,. Can anyone please help resolve these issues? TIA

**Comment by Myuavbug66** [comment]
Hi 
I am another who would like to use Orca slicer with a Qidi I-Fast. Has anyone resolve these issues? TIA

**Comment by kiryutin-a** [comment]
> Hi I am another who would like to use Orca slicer with a Qidi I-Fast. Has anyone resolve these issues? TIA

Hi. I am now printing on i-fast using Orca slicer.
I am pretty sure that it is not fully funcional presets, but at least it is working.
PLease calibrate bed every time you switch on printer. I dont know why, but with orca sliced objects it can scratch the bed.
https://disk.yandex.ru/d/8q-RYKusl8hgfg
download, unpac,
import printer and import filament
Please try it and write here.

**Comment by Myuavbug66** [comment]
> > Hi I am another who would like to use Orca slicer with a Qidi I-Fast. Has anyone resolve these issues? TIA
> 
> Hi. I am now printing on i-fast using Orca slicer. I am pretty sure that it is not fully funcional presets, but at least it is working. PLease calibrate bed every time you switch on printer. I dont know why, but with orca sliced objects it can scratch the bed. https://disk.yandex.ru/d/8q-RYKusl8hgfg download, unpac, import printer and import filament Please try it and write here.

I have a profile that is working ( after mush searching ). I have not tried a dual head program yet. I had to modify the end code G28 Z to lower the bed to the bottom.

Your Problem with scratching the bed could be the offset mine was way too high.

![Image](https://github.com/user-attachments/assets/20fcf00d-8061-4aea-8a7d-e21ed392a1fa)

My Problem right now is connecting Orcas do the ifast. The only way I can transfer a file is by SD card or saving it to the hard drive and transferring it with Qidi print.

**Comment by Myuavbug66** [comment]
> > > Hi I am another who would like to use Orca slicer with a Qidi I-Fast. Has anyone resolve these issues? TIA
> > 
> > 
> > Hi. I am now printing on i-fast using Orca slicer. I am pretty sure that it is not fully funcional presets, but at least it is working. PLease calibrate bed every time you switch on printer. I dont know why, but with orca sliced objects it can scratch the bed. https://disk.yandex.ru/d/8q-RYKusl8hgfg download, unpac, import printer and import filament Please try it and write here.
> 
> I have a profile that is working ( after mush searching ). I have not tried a dual head program yet. I had to modify the end code G28 Z to lower the bed to the bottom.
> 
> Your Problem with scratching the bed could be the offset mine was way too high.
> 
> ![Image](https://github.com/user-attachments/assets/20fcf00d-8061-4aea-8a7d-e21ed392a1fa)
> 
> My Problem right now is connecting Orcas do the ifast. The only way I can transfer a file is by SD card or saving it to the hard drive and transferring it with Qidi print.

Just noticed your profile only has one nozzle the profile I'm using has two nozzles I'll send it to you if you'd like once I get done testing it. Wouldn't want to send you something that might crash your machine.

**Comment by kiryutin-a** [comment]
> > > > Hi I am another who would like to use Orca slicer with a Qidi I-Fast. Has anyone resolve these issues? TIA
> > > 
> > > 
> > > Hi. I am now printing on i-fast using Orca slicer. I am pretty sure that it is not fully funcional presets, but at least it is working. PLease calibrate bed every time you switch on printer. I dont know why, but with orca sliced objects it can scratch the bed. https://disk.yandex.ru/d/8q-RYKusl8hgfg download, unpac, import printer and import filament Please try it and write here.
> > 
> > 
> > I have a profile that is working ( after mush searching ). I have not tried a dual head program yet. I had to modify the end code G28 Z to lower the bed to the bottom.
> > Your Problem with scratching the bed could be the offset mine was way too high.
> > ![Image](https://github.com/user-attachments/assets/20fcf00d-8061-4aea-8a7d-e21ed392a1fa)
> > My Problem right now is connecting Orcas do the ifast. The only way I can transfer a file is by SD card or saving it to the hard drive and transferring it with Qidi print.
> 
> Just noticed your profile only has one nozzle the profile I'm using has two nozzles I'll send it to you if you'd like once I get done testing it. Wouldn't want to send you something that might crash your machine.

I always use USB stick to transfer files

**Comment by Willertrading** [comment]
Could you please post the profile for two nozzles/extruders for the I fast printer?

**Comment by Willertrading** [comment]
> > > > > I apologize, I am new to the GITHUB,  I would also like the orca slicer profile for the I fast for 2 extruders.  PLEASE
Thank you!

 Hi I am another who would like to use Orca slicer with a Qidi I-Fast. Has anyone resolve these issues? TIA
> > > > 
> > > > 
> > > > Hi. I am now printing on i-fast using Orca slicer. I am pretty sure that it is not fully funcional presets, but at least it is working. PLease calibrate bed every time you switch on printer. I dont know why, but with orca sliced objects it can scratch the bed. https://disk.yandex.ru/d/8q-RYKusl8hgfg download, unpac, import printer and import filament Please try it and write here.
> > > 
> > > 
> > > I have a profile that is working ( after mush searching ). I have not tried a dual head program yet. I had to modify the end code G28 Z to lower the bed to the bottom.
> > > Your Problem with scratching the bed could be the offset mine was way too high.
> > > ![Image](https://github.com/user-attachments/assets/20fcf00d-8061-4aea-8a7d-e21ed392a1fa)
> > > My Problem right now is connecting Orcas do the ifast. The only way I can transfer a file is by SD card or saving it to the hard drive and transferring it with Qidi print.
> > 
> > 
> > Just noticed your profile only has one nozzle the profile I'm using has two nozzles I'll send it to you if you'd like once I get done testing it. Wouldn't want to send you something that might crash your machine.
> 
> I always use USB stick to transfer files

**Comment by Myuavbug66** [comment]
Hi there.
I don't know where I got this from I searched so many sites to find it and tried so many different things Mostly this is untested but here it is so far the only thing I had to change was the And G code added "G28 Z"
Printer profile a test to material print profile and to screenshots

[Printer presets_TJM.zip](https://github.com/user-attachments/files/25921731/Printer.presets_TJM.zip)

[Test_Plate_ASM-A_Orca_Print.zip](https://github.com/user-attachments/files/25921769/Test_Plate_ASM-A_Orca_Print.zip)

![Image](https://github.com/user-attachments/assets/7e1c42ab-e9ef-4bbd-a604-9951a8af332d)

![Image](https://github.com/user-attachments/assets/4714c5bd-cbe5-4d2e-9f91-aaa456d72f08)

I found export the G code From Orcas I can use Qidi Print -> Control Panel to upload it to the printer. ( My printer is not in my den )
!!!!! Profile dose not work with Qidi Studios or I can't get it to work.

**Comment by Myuavbug66** [comment]
(Printer profile a test to material print profile and to screenshots) Wrong
1 - Printer Profile
1 - Print File ( 2 Material test ) ( My actual test was ASA and TPE. I don't think PLA and TPU like each other so set up test only )
2 - Screenshots

I'm new to posting but I don't see any reason why I shouldn't share my findings if I find something that works ( I-fast It is great hardware but the software sucks ) and Qidi Has left us behind!!!

**Comment by Myuavbug66** [comment]
I forgot to zero the Z offset mine will probably crash your bed ( Z-0.25 )

**Comment by ThothDroid** [comment]
> (Printer profile a test to material print profile and to screenshots) Wrong 1 - Printer Profile 1 - Print File ( 2 Material test ) ( My actual test was ASA and TPE. I don't think PLA and TPU like each other so set up test only ) 2 - Screenshots
> 
> I'm new to posting but I don't see any reason why I shouldn't share my findings if I find something that works ( I-fast It is great hardware but the software sucks ) and Qidi Has left us behind!!!

Just create a repository and pase everything in there
