### ISSUE TITLE
Tree supports ignore the adaptive layer height parameter

### ISSUE THREAD

**Issue by Faasteer** [SoftFever/OrcaSlicer#1787]
**Describe the bug**
I had a problem with tree supports not printing properly - significant underextrusion, collapses, breaks and failures. I found an old bug that mentioned flow issues with adaptive layer height for supports, which corresponds to the location that always fails for this print.

So I tried disabling this parameter and found that it doesn't work at all. No matter what style of tree supports I choose, if I turn off the adaptive layer height, the supports are still sliced with different layer heights. 

**3mf File for This Bug**
[OneWheelFender.zip](https://github.com/SoftFever/OrcaSlicer/files/12329612/OneWheelFender.zip)

**To Reproduce**
Just slice the attached file and look at the layer height view.

**Expected behavior**
A working support tree that won't ignore my settings. Or a fix so that they print correctly even with variable layer heights - I'm convinced this still doesn't work, even though this bug has been marked as resolved.

**Screenshots**
OrcaSlicer:
![OrcaSlicer2](https://github.com/SoftFever/OrcaSlicer/assets/5735288/7b0daffd-4c0d-459d-b0f9-db8843a1bea6)
![OrcaSlicer](https://github.com/SoftFever/OrcaSlicer/assets/5735288/1d4b8bba-e281-4257-903c-0d8968e8d9b4)

BambuStudio (where I used the same file):
![BambuStudio](https://github.com/SoftFever/OrcaSlicer/assets/5735288/95a42b13-3bd8-4ff1-9fee-f812d959a8a8)

**Printer model**
Bambu Lab P1S with AMS, but this was printed with a direct filament guide (too big spool for AMS).

**Desktop (please complete the following information):**
 - Windows 11 Pro, 22H2 (22621.2134)
 - Orca Slicer 1.6.4-beta2
 - Bambu Studio 1.7.3.50

**Comment by luisillo26** [comment]
I'm having a similar issue with the combination os using adaptive layer heigh and automatic tree supports.
The supports don't touch the model even with "Independent support layer height" turned off:

<img width="1203" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/1028540/d5f1c323-1157-401c-aaab-8200b5548d4c">


Once I change the supports type to Normal (auto) it adjusts the support height correctly:

<img width="1145" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/1028540/e830dba6-498d-49a4-b9c1-d028bb9d729c">


I'm running version 1.7.0 on MacOS 13.6.

**Comment by Ocelot08** [comment]
I believe I'm having a similar bug. Using either variable layer heights has what seems to be tree supports trying to support the "block" that applies the layer variation. That has my tree supports moving above my model.

![Screenshot 2023-11-10 102323](https://github.com/SoftFever/OrcaSlicer/assets/70420373/4350202f-1d14-4343-a647-68fddb557ec5)
![Screenshot 2023-11-10 102413](https://github.com/SoftFever/OrcaSlicer/assets/70420373/3e956cd7-cfd3-403a-9ea6-6004f9ab3d58)

**Comment by Garethgb** [comment]
Can confirm this is still happening with adaptive layers and tree support, whether its auto or manual, the support just doesn't reach the item.

![Screenshot 2024-01-05 201630](https://github.com/SoftFever/OrcaSlicer/assets/43449253/df48e00b-1e0e-4907-87a3-70bc7898c907)

**Comment by jbcpollak** [comment]
This appears to still be an issue

**Comment by Maxell2904** [comment]
This is still an issue
