### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by Iupoone** [SoftFever/OrcaSlicer#1789]
The file exe that Is in the V1.6.4-beta2-win64 seems to Avast to be affected by a virus IDP.Generic

*Describe the bug**

**3mf File for This Bug**
If it is related to slicing, please append the 3mf file. It could be extremely helpful to solve the issue.

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**

**Printer model**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Windows]

**Comment by shaneshort** [comment]
I don't know that this is an Orcaslicer bug, Have you tried reporting this to Avast? https://www.avast.com/false-positive-file-form.php

**Comment by josyb** [comment]
1.7 Beta got this report:
![image](https://github.com/SoftFever/OrcaSlicer/assets/4457022/c9982c10-4e1d-4e02-83af-feb6fc4be016)
