### ISSUE TITLE
V1.6.4 Beta 3 Does not start print when sent to X1C via Cloud

### ISSUE THREAD

**Issue by ChaosBlades** [SoftFever/OrcaSlicer#1791]
**Describe the bug**
Just switched to V1.6.4 Beta 3 and it is not starting the print. It will upload it to cloud and switch to device tab but the print does not start and it isn't in the X1 Carbons Print Cache. Switched back to V1.6.4 Beta 2 and it prints without issue. I tried to restart OrcaSlicer and reboot my X1 Carbon but the issue persists.

**To Reproduce**
Try to send a print to a Bambu Lab Printer via the cloud.

**Expected behavior**
Print to start.

**Printer model**
Bambu Lab X1 Carbon w/ AMS

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: OrcaSlicer V1.6.4 Beta 3

**Additional Information**
Depending on how long this is here before the issue is identified I will test on Linux and my Voron printers tomorrow and see if the same issue is present there.

**Comment by Nanolab53** [comment]
I can confirm, rolling back to beta 2 let me launch a print to my XC1

**Comment by Desterly** [comment]
Is your X1C / P1P on the latest firmware or a different version?

I've been printing to both my home and work printers today w/ B3 and it has started the job every time.   Both my printers are on the latest firmware.

It probably is an issue w/ the plugin and/or their cloud but maybe the firmware is a key

**Comment by Hammer57** [comment]
Latest firmware (1.04).

**Comment by buckeyestargazer** [comment]
I am having this issue as well with an X1C and also 3 P1Ps.  However I am on 1.6.3.  Also, I updated the firmware recently on all of these machines, in the last 2 days.  I'm going to try 1.6.4 beta 2 and see how it goes.

**Comment by ChaosBlades** [comment]
I have been on the latest firmware since the day it released.

Don't have issues using Upload and Print with my various Voron printers.

**Comment by dartrax** [comment]
Same here, latest fw on x1c

![image](https://github.com/SoftFever/OrcaSlicer/assets/15105943/84d69eba-f95b-4ea8-9ed0-9951671c80ba)

**Comment by buckeyestargazer** [comment]
This issue got a lot worse for me last night.  Using v1.6.3 I started a print on two P1Ps last night and after verifying that the prints started OK went to bed.  I woke up to find that somehow the printers printed TWICE, one right on top of the other!  Somehow the cache started printing the failed prints from before.  In retrospect this makes sense considering I never received any kind of "failed" message when the phantom prints never started.  

This morning I installed 1.6.4 beta 2 and I've started several prints successfully.  Again, this issue only started when I updated the firmware on these machines.  
![PXL_20230815_123831261](https://github.com/SoftFever/OrcaSlicer/assets/75807519/6cb88f71-cbf1-4543-8df3-9cb5d77a704f)

**Comment by SoftFever** [comment]
It's likely due to the recent debacle with their cloud service that began two days ago.
Given its unreliability in its current state, I would suggest using the LAN mode for peace of mind and to protect your privacy.

**Comment by dartrax** [comment]
First I doubted that because of the reports stating that with beta 2 it works... So to confirm I tried again with current V1.6.4 beta 3, but, to my surprise, it started printing!

I'll report if that happens again.

**Comment by dartrax** [comment]
I think this can be closed. The reason was [Bambus server outage](https://blog.bambulab.com/cloud-temporary-outage-investigation/), not an Orca issue.
