### ISSUE TITLE
First Layer Infill Speed not used

### ISSUE THREAD

**Issue by abstractFlo** [SoftFever/OrcaSlicer#1792]
**Describe the bug**
The latest Beta Version does not respects the first layer infill speed

**Screenshots**
![image](https://github.com/SoftFever/OrcaSlicer/assets/4614586/e3f7ddcf-ed78-4a5a-bd42-73bf5346627d)

**Printer model**
Voron 0.2

**Desktop (please complete the following information):**
 - Windows
 - Version 11

**Comment by asychev** [comment]
I can confirm, same issue for me

**Comment by Dustmuffins** [comment]
Same here on Windows 10

**Comment by asychev** [comment]
Still broken in 1.6.4 release
Similar to #1860 and #1800
@SoftFever FYI

**Comment by asychev** [comment]
Fixed in 1.6.5 via #1899
