### ISSUE TITLE
Request for a Creality Ender-3 V2 Neo profile

### ISSUE THREAD

**Issue by mattiasthalen** [SoftFever/OrcaSlicer#1799]
I can see that there is a Creality Ender-3 V2 profile and I've tried modifying it for the neo, but I'm out of luck. Hence my request :)

**Comment by TheBest6337** [comment]
If your neo has Klipper I could provide you my profile

**Comment by mattiasthalen** [comment]
I'm afraid not, it's my first printer and I've just had it for two months.
Not even sure where to start with getting Klipper on it.

**Comment by sherifsurf** [comment]
watch videos for (sonic pad) , this will help you get started with Klipper 
https://youtu.be/UtlUSF9VCOM

**Comment by TheBest6337** [comment]
Please don't go with the sonic pad. It has old AF Klipper Firmware and isn't rooted.

**Comment by leoaf79** [comment]
Me too, please.

**Comment by lambtho12** [comment]
Why not simply copy the ender 3v2 and just change a few settings like it is done in prusa slicer?
