### ISSUE TITLE
no fix model trought netfab ?

### ISSUE THREAD

**Issue by KennyBeaudoin** [SoftFever/OrcaSlicer#1802]
**Describe the bug**
there is no option to repair the model throught the netfab
error: 6 non-manifold edges

**3mf File for This Bug**
If it is related to slicing, please append the 3mf file. It could be extremely helpful to solve the issue.

**To Reproduce**
repair non manifold edges

**Expected behavior**
to repair the edges .,.. jesus

**Screenshots**

**Printer model**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Windows]

**Comment by foreachthing** [comment]
But, it has a "Fix Model" function. Doesn't that work for you?
![image](https://github.com/SoftFever/OrcaSlicer/assets/10420187/e6465b84-5beb-495a-8e51-22c7178b759a)

**Comment by KennyBeaudoin** [comment]
![Screenshot_1](https://github.com/SoftFever/OrcaSlicer/assets/115440478/7e973bb0-f161-435a-8a8d-e0ff93defae4)

**Comment by KennyBeaudoin** [comment]
there is no more the option to repair it ... no i dont seee the fix model option when i right click on it .... i only see it on bambu studio not in orca slicer anymore ... i dont know why

**Comment by foreachthing** [comment]
What version of OrcaSlicer are you using?
In 1.6.4b2 it's available.

**Comment by KennyBeaudoin** [comment]
i tried to go back to 1.6.4b2 doesnt work... tried b3 doesnt show also

**Comment by KennyBeaudoin** [comment]
if you want i can show you on discord on the voron live chat...

**Comment by KennyBeaudoin** [comment]
it came back by magic ... idk why sometime the option goes away and sometimes it there ... pretty anoying and i dont understand why

**Comment by weenis** [comment]
I use the "Fix Model" option quite frequently. I've been on v1.8.1 for a while, and I used the feature a few days ago. As of today, it mysteriously disappeared.

![image](https://github.com/SoftFever/OrcaSlicer/assets/29289000/6c5ab6aa-49eb-46ce-834c-d201c064b948)

I've tried restarting. The only thing I haven't tried is reinstalling. I am running the standalone instance.

**Comment by weenis** [comment]
I just launched v1.8.0 and "Fix Model" is there.

**Comment by KubaMiszcz** [comment]
in 2.2.0 this option is gone again
