### ISSUE TITLE
TPU95 filament profile for Ender 3

### ISSUE THREAD

**Issue by Archmule78** [SoftFever/OrcaSlicer#1805]
Hi all,

Can anybody assist me on how to add a TPU95 filament profile for my Ender 3, or as I call it "The Frankin Ender".

I have tried adding it in the setup wizard but it only gives me PLA, PETG and ABS.

I do have a profile for setup in Cura, but after using ORCA for a month now, I would like to switch to it permanently.

My setup is a Ender 3 V1, all metal hot end and a Titan DD extruder.  So my rig is setup to print almost every filament.

Any help and assistance would be greatly appreciated.

**Comment by DVSVIDEO** [comment]
![orca](https://github.com/SoftFever/OrcaSlicer/assets/96373457/c9eed6b0-dbda-4ceb-af84-e7ecd73812c4)
