### ISSUE TITLE
Moving cursor outside of layer & gcode slider when dragging will rotate build plate

### ISSUE THREAD

**Issue by ZyberSE** [SoftFever/OrcaSlicer#1807]
In macOS, when moving the layer and gcode sliders, if you do not keep the move over the slider you will start rotating the build plate instead. This is very annoying, especially on large monitors and high mouse sensitivity.

The preferred behaviour would be when dragging one of those sliders, only that should be affected, no matter of you move the cursor outside of it's area.

EDIT: This happens when the mouse cursor leaves the application window while still dragging, then it starts to rotate the build platform instead. As long as the mouse is still within the application window it works as expected.

- macOS v13.5
- OrcaSlicer v1.6.4-beta2 & OrcaSlicer v1.6.4-beta3

**Comment by whitegfx** [comment]
Same behaviour on OrcaSlicer v1.6.4-beta3.
