### ISSUE TITLE
Add support for multi-tool printers

### ISSUE THREAD

**Issue by jcleclaire** [SoftFever/OrcaSlicer#1816]
**Is your feature request related to a problem? Please describe.**
I run an E3D Toolchanger and cannot use any tool except for the first tool (T0).

**Describe the solution you'd like**
Support multi-tool printers, this involves:
1. Setting for number of extruders (likely under Printer > Basic Information)
2. Settings for each extruder (multiple Extruder tabs (Extruder 1, Extruder 2, etc))
3. Settings to specify specific tools for specific parts and also specific tools for different features (infill, perimeters, support, etc).
4. Gcode for toolchanges.
5. Filament settings for each tool
6. A boolean flag for each tool if it's used in the print or not (useful for start gcode to not heatup tools that aren't used, PrusaSlicer has it as _is_extruder_used[x]_).
7. Per extruder settings (temperature settings for heatup and idle, for example).

This has already been implemented well in PrusaSlicer so hopefully it can be drawn from them without too much additional work!

**Describe alternatives you've considered**
Using PrusaSlicer (current slicer I use for this).

**Comment by Otann** [comment]
Just curious, are there any plans for this?
