### ISSUE TITLE
Disabling prime tower when printing with multiple filaments sometimes causes pretty long prints

### ISSUE THREAD

**Issue by mplonski** [SoftFever/OrcaSlicer#1827]
**Describe the bug**
Sometimes, when printing multi-colour model without prime tower, calculated printing time is unrealistically long. So far I thought that it was purely random since it happened to me from time to time and restarting Orca (and opening my file again) usually solved the issue. When trying to reproduce it I found out that it may be related to having and not having prime tower.

When printing with this bug "enabled" and generated into gcode, print is actually taking a long time (it kinda hangs after switching colour and doesn't move at all, or does it very slowly).

**3mf File for This Bug**
Including three files: 3mf with simple project, gcode generated with prime tower enabled (Cube_PLA_25m42s.gcode) and gcode generated without prime tower enabled.

[test models.zip](https://github.com/SoftFever/OrcaSlicer/files/12364306/test.models.zip)

**To Reproduce**
 * Open CuraSlicer (tested also on 1.6.4-beta3)
 * add any model (or cube from Orca)
 * add another filament
 * add change to another filament on any layer
 * slice it, should be ok
 * disable prime tower
 * slice it, time may be unrealistically long

If it doesn't work as described above, restart Orca and try again :)

**Expected behavior**
Calculated gcode should not depend on how many times Orca was restarted, it should always be proper.

**Screenshots**
Attached: one with prime tower enabled, one without.

<img width="1728" alt="Screenshot 2023-08-17 at 02 06 06" src="https://github.com/SoftFever/OrcaSlicer/assets/3118602/fe480046-1014-4af8-afb0-e028f25142bb">

<img width="1728" alt="Screenshot 2023-08-17 at 02 06 26" src="https://github.com/SoftFever/OrcaSlicer/assets/3118602/41b10d82-41c1-4cfb-b5d8-932c6a3dcce9">

**Printer model**
Bambu Lab P1S (happened also on P1P)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: 13.5

**Comment by christophervankammen** [comment]
I know this was closed by the bot but did it actually get fixed?

**Comment by mplonski** [comment]
@christophervankammen last time I checked it wasn't, but haven't tried printing for a month.
