### ISSUE TITLE
Anomalie: bad numeric conversion: negative overflow (orca can't organise my plate)

### ISSUE THREAD

**Issue by felykiosa** [SoftFever/OrcaSlicer#1828]
when I want to organise my plate orca give me this message : 
 Anomalie: bad numeric conversion: negative overflow

**To Reproduce**
clone a small stl part many time on your plate . I have this problem when there is a lot iteration of the same stl

![image](https://github.com/SoftFever/OrcaSlicer/assets/36807853/4f418d89-c008-4f00-94d4-a40b62de7f39)

 - OS: [e.g. iOS, Windows]
 - Version 1.6.4 BETA 3 / 1.6.3

**Comment by ModernMakerStudios** [comment]
please reopen this.
