### ISSUE TITLE
Retraction Tower STL Non-manifold edges

### ISSUE THREAD

**Issue by DewiEJ** [SoftFever/OrcaSlicer#1842]
**Describe the bug**

**3mf File for This Bug**
If it is related to slicing, please append the 3mf file. It could be extremely helpful to solve the issue.

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**

**Printer model**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Windows]

**Comment by DewiEJ** [comment]
Slicer reports that the retraction_tower.stl from the calibration menu contains 53 non-manifold edges

Orca Slicer 1.6.4-beta2 Intel Mac
Prusa MK3S

<img width="396" alt="Screenshot 2023-08-19 at 00 59 03" src="https://github.com/SoftFever/OrcaSlicer/assets/30669664/32dd713e-3972-47b8-a366-477476d80bbc">

**Comment by A-A-Ron69420** [comment]
I'm getting the same error on 1.7 - beta of 40 non-manifold edges, does this actually affect anything???

**Comment by JosefWN** [comment]
The STL file bundled with the application does not contain manifold edges but as it's cut, the cut version gets non-manifold edges.

**Comment by apriendeau** [comment]
This is also occurring for me on 1.8.1.

**Comment by Ramttid** [comment]
Still occuring

**Comment by blindbatts** [comment]
Happening to me on 1.9.0 on macos

**Comment by TheMoye** [comment]
Hi everyone, this error is still present in Orca Slicer 2.1.1 on Windows 11.

**Comment by Ergonomicmike** [comment]
And on the 2.1.1 August 1 Nightly. It used to offer a Windows (10) repair tool to fix. But it's not offering that now.
