### ISSUE TITLE
Change first layer height per-object for z-offset calibration

### ISSUE THREAD

**Issue by knw257** [SoftFever/OrcaSlicer#1844]
**Is your feature request related to a problem? Please describe.**
Trying to run a z-offset test, but I cannot find any way to change the first layer height on a per-object basis

**Describe the solution you'd like**
When changing settings per object in the slicer, I'd like the "First Layer Height" option to be available to change

**Describe alternatives you've considered**
Only alternative currently is to create multiple different prints with the first layer height changed in each

**Additional context**
A Z-offset calibration test where a range of 10mm*10mm squares are printed with slightly different layer heights (e.g. -0.03 through +0.03mm) would also be helpful

**Comment by richard-scott** [comment]
Hey, I just noticed that a global Z offset feature was added in v1.8.0:

![image](https://github.com/SoftFever/OrcaSlicer/assets/5149834/581d3313-5c34-4d7a-9473-7ba023970b35)

**Comment by typetetris** [comment]
can we reopen this? Would be a great feature!
