### ISSUE TITLE
Overhang speed won't work on OrcaSlicer V1.6.4 beta3

### ISSUE THREAD

**Issue by rfnovo** [SoftFever/OrcaSlicer#1846]
Using stock Klipper 0.2 Standard profiler with all default settings.

Classic mode for overhang speed DISABLED. 

Beta3 seems to be using bridge speed for all overhangs. Comparison between 1.6.4 beta3 and 1.6.3:

![image](https://github.com/SoftFever/OrcaSlicer/assets/11941836/5fbc9054-7632-48b5-8787-2117807376bf)
![image](https://github.com/SoftFever/OrcaSlicer/assets/11941836/feeaed49-ef40-4e1f-995e-02caddf3e1ff)
[Overhang.zip](https://github.com/SoftFever/OrcaSlicer/files/12386316/Overhang.zip)

**Comment by SoftFever** [comment]
currently, perimeter will be considered as bridge is it's unsupported area is less than 13% percent
