### ISSUE TITLE
Slicer doesn't respect retraction settings when firmware retraction is enabled

### ISSUE THREAD

**Issue by Kozova1** [SoftFever/OrcaSlicer#1849]
If you enable firmware retraction in the slicer and set the retraction length to a different value than the one configured in the printer config, a `SET_RETRACTION` command isn't generated inside the result gcode, which means that the retraction value isn't honored.

**Printer model**
Heavily modded Voron 0.1 / Tri-Zero

**Desktop (please complete the following information):**
 - OS: Fedora Linux 38

**Comment by Bonaparte1446** [comment]
I’ve that retraction issue in just some seam, in the minor part of them, and also without change the retraction parameter but using the printer setting parameter
