### ISSUE TITLE
Appimage won't open - Fedora 37

### ISSUE THREAD

**Issue by emelbardis** [SoftFever/OrcaSlicer#185]
**Describe the bug**
Appimage will not load although I have marked properties with 'allow executing'

**To Reproduce**
1. Download Appimage on Fedora 37
2. Click on Appimage and select run once or integrate and run
3. Application does not open

**Expected behavior**
Expect the Appimage to open BambuStudio like any of the other Appimages on this system do (including PrusaSlicer)

**Desktop (please complete the following information):**
Fully updated Fedora 37 (wayland) on Dell laptop

This is odd since I don't see any other issues related to the actual appimage not opening. Sometimes an appimage fails to open due to a missing dependency. Is there another package I need to add to get this to work?

```
[user@fedora37 ~] $ '/home/user/Downloads/BambuStudio-SoftFever_V1.4 (1).2_Linux_AppImage/BambuStudio_ubu64.AppImage' 
/usr/bin/AppImageLauncher: /lib64/libcurl.so.4: no version information available (required by /usr/bin/../lib/x86_64-linux-gnu/appimagelauncher/libappimageupdate.so)
QSocketNotifier: Can only be used with threads started with QThread
/tmp/.mount_BambuSQXdon9/bin/bambu-studio: error while loading shared libraries: libwebkit2gtk-4.0.so.37: cannot open shared object file: No such file or directory

[user@fedora37 ~] $ sudo dnf install libwebkit2gtk-4.0.so.37
Last metadata expiration check: 1:14:26 ago on Mon 16 Jan 2023 08:36:03 AM PST.
Package webkit2gtk4.0-2.38.3-2.fc37.i686 is already installed.
Dependencies resolved.
Nothing to do.
Complete!


```

**Comment by zgrozemag** [comment]
For me it launched once i installed webkit2gtk4.0, system had 4.1

**Comment by emelbardis** [comment]
> For me it launched once i installed webkit2gtk4.0, system had 4.1

Thanks. My system has 4.0, 4.1 and 5.0 installed already

**Comment by andypiper** [comment]
I was able to run the AppImage on Fedora 37 by making it executable and running it from the command line, however, it crashes shortly afterwards (same as #204). It's fairly clear that it was built for Ubuntu / Debian, although AppImage itself is a portable format. I'm failing to build from source on Fedora myself.

**Comment by nelsongraca** [comment]
Should be portable yet it's not.
Not running on Gentoo either with the following error:

    $ ./OrcaSlicer_ubu64.AppImage 
    /tmp/.mount_OrcaSlX5H07L/bin/orca-slicer: symbol lookup error: /tmp/.mount_OrcaSlX5H07L/bin/orca-slicer: undefined symbol: gdk_wayland_window_get_wl_surface

I assume there's a hard dependency on wayland?

**Comment by TeaObvious** [comment]
> Not running on Gentoo either with the following error:

Same here and i feel stupid because i simply can't get it to compile my self... BambuLab/OrcaSlicer is the first where i have these Problems :( They won't wegen work with wine...

**Comment by emelbardis** [comment]
Just tried 1.8.0 beta and it opened and works fine on Fedora 38.

**Comment by mbribeiro** [comment]
Same here. Is this issue still valid ? I mean, as there is no comments I would consider a "wont fix issue".

**Comment by RebeccaStevens** [comment]
installing webkit2gtk4.0 fixed things for me on nobara 39

**Comment by vprasad1973** [comment]
FYI to any of the Fedora or other distro folks having difficulty with launching Orca app image, go ahead and try last night's Jan 22 v2.0.0 dev image from the nightly builds-- WORKS FANTASTIC!!!

**Comment by nelsongraca** [comment]
@vprasad1973 thanks for the tip will try it out

**Comment by BaxiDi** [comment]
I did install  libwebkit2gtk-4.0-37 ,  and add English language to the system .

**Comment by anxolerd** [comment]
I still have the same issue as in https://github.com/SoftFever/OrcaSlicer/issues/185#issuecomment-1494658033. Is it a hard dependency on wayland? Is it possible to run the software without wayland?

**Comment by j-aub** [comment]
@anxolerd @nelsongraca it's possible to run OrcaSlicer without wayland by stubbing out the wayland functions (https://forums.gentoo.org/viewtopic-p-8683928.html)
