### ISSUE TITLE
Temps in filament settings not being inserted into sliced file

### ISSUE THREAD

**Issue by poppinfresh69** [SoftFever/OrcaSlicer#1853]
**Describe the bug**
User values entered in Print Temperatures in Filament Settings are not being automatically inserted into code of the sliced file. 

**3mf File for This Bug**
N/A

**To Reproduce**
Go to Filament Settings > Nozzle or High Temp Plate settings and change values. 
Slice file and view generated code under filament start G-code.
Notice no code is generated for the nozzle or bed temps inputted by the user.
Should have set bed and set extruder temp G-code commands
Only way to get code to appear is to enter manual commands in Advanced > Filament Start G-code 

**Expected behavior**
Filament start G-code should have nozzle and bed temperature commands auto created from user entered values in the UI instead of requiring manual G-code entries.

**Screenshots**

**Printer model**
N/A

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 1.6.4 Beta 3

**Comment by Martorias** [comment]
I'm using klipper so via the Printer Machine G-code settings it starts with 
`print_start EXTRUDER=[first_layer_temperature] BED=[first_layer_bed_temperature] CHAMBER=[chamber_temperature]`
This works fine, but if I set first layer bed temp to 55 and then 60 it just starts at 55 and doesn't increase the next layer.

**Comment by warnesj** [comment]
I was having the same problem in v1.6.4, but it looks like it's fixed now in v1.6.6.

**Comment by warnesj** [comment]
I may have spoken too soon.  In v1.6.6 it appears the bed temperature gets set when I have Supports enabled, but when I disable them the bed temperature doesn't get set.  Looking at the generated G Code it looks like the M190 command is missing.

**Comment by oleksii-suprun** [comment]
I have the same issue as @Martorias. I set the bed temp for the first level to 85 and 90 for other layers (according to the Prusa Slicer's default profile for PETG), but after the first layer, the temperature still stays at 85. 
<img width="667" alt="Screenshot 2023-10-08 at 12 01 01" src="https://github.com/SoftFever/OrcaSlicer/assets/2777842/c1d01735-bbbc-4b86-8908-3ad33814ca78">

**Comment by oleksii-suprun** [comment]
Here is a small update on this issue. It looks like everything works well when both heater (nozzle and bed) temperatures are different for the first layer. For example, when I sed nozzle temperature to values 240/250 and bed 85/90 - everything works well. But when I set the nozzle to 240/240 and bed 85/90, I saw this issue happen and the bed temperature is not updated for subsequent layers and stays 85.

**Comment by Greg767** [comment]
> Here is a small update on this issue. It looks like everything works well when both heater (nozzle and bed) temperatures are different for the first layer. For example, when I sed nozzle temperature to values 240/250 and bed 85/90 - everything works well. But when I set the nozzle to 240/240 and bed 85/90, I saw this issue happen and the bed temperature is not updated for subsequent layers and stays 85.

I am seeing this issue as well although for first layers I want to set a higher temp value and when this is the case, it doesn't work. Temperatures are not changed from what is set in print start macro. So basically whatever temps I put in the macro that will be the temps no matter what is in the filament settings.

**Comment by ohyeah8000** [comment]
Hey I still have this problem and my sliced file do not contain the temperature information. 

I found out about it after switching to Orcaslicer and hitting wrong temperatures (well the temps defined as default in my start_print macro). 

Where are the places I should look for solving the issue?

When I delete the defaults an error messages comes up. 

![image](https://github.com/SoftFever/OrcaSlicer/assets/121863196/1de99ae0-dd60-4c3c-bba1-acabaf1a3338)

**Comment by skyguynca** [comment]
Orca is not generating the first layer temp in the gcode for the extruder. I put it in manually in the print start macro but then in the layer change the m104 s208 command is ignored and the extruder temp goes to 0. It does this in every stl I slice

**Comment by Grumbledore667** [comment]
![image](https://github.com/user-attachments/assets/c7216d3a-e13e-4294-af2a-90854bb7dad8)
![opera_rk8ZXrkGBt](https://github.com/user-attachments/assets/170a7598-0324-4e63-96b7-3eb0ccb3dec0)

1st layer temp is still not added. Same goes for speeds. Set everything to 60ms/s, even for the infill. The infill was definetly way above 60ms/s.

**Comment by micaheli** [comment]
I had this same issue. I used a built-in profile and it never generated.   I blew it away and started a profile from scratch and it now inserts the gcode.    This is definitely a bug, or that wouldn't happen.
