### ISSUE TITLE
Extend Maximum Size Limitation

### ISSUE THREAD

**Issue by madeintaiwan** [SoftFever/OrcaSlicer#186]
Currently, the bed limitation is 1200mm and our printer is 4000mm long. 
Is it possible to either remove the maximum value limit or set it at something like 6000mm?

**Comment by SoftFever** [comment]
That's huge!
Will ease the limitation in the next update.
Would love to see how does it work on such large printer :)

**Comment by madeintaiwan** [comment]
Pretty big, we're building a 6000mm3 one currently so we can print a small house, Superslicer has similarly removed the upper threshold to allow us to do some pretty big prints- 
![PXL_20220621_141228675](https://user-images.githubusercontent.com/2494432/213013173-924c5d06-1a22-45c1-8fdd-7200bee310c2.jpg)

**Comment by madeintaiwan** [comment]
Hi, any chance you had a look at removing / changing the bed size limit?

Thanks,

Nate

**Comment by madeintaiwan** [comment]
> That's huge! Will ease the limitation in the next update. Would love to see how does it work on such large printer :)

@Softfever any chance you can increase the bed size limit?

**Comment by SoftFever** [comment]
I'll take another look for 1.9.
It needs to change change to internal data type to support larger bed size

**Comment by madeintaiwan** [comment]
Thanks, that would be great. 

There seems to be a 2500mm limit in Y axis and a 2000mm limit in Z and I assume a similar limit in X but I haven't tried. 

Check out tldraw (make it real) and their Twitter feed. Possibly ready for Orca 2.0....

**Comment by madeintaiwan** [comment]
@SoftFever Any chance there's room for this in the next update? 🙏🙏 Having to go back to Cura to print big :( 

![image](https://github.com/SoftFever/OrcaSlicer/assets/2494432/6db1d93e-9aa2-4a24-955d-91e14a5cffd1)

**Comment by madeintaiwan** [comment]
@SoftFever Any chance you had a look at why there's a limit for length and if it possible to extend for larger format printers ?. 

Thanks , Nate

**Comment by SoftFever** [comment]
> [@SoftFever](https://github.com/SoftFever) Any chance you had a look at why there's a limit for length and if it possible to extend for larger format printers ?.
> 
> Thanks , Nate

working on it now
