### ISSUE TITLE
First layer infill speed not respected

### ISSUE THREAD

**Issue by lhndo** [SoftFever/OrcaSlicer#1860]
**Describe the bug**
First layer infill speed not respected

**Screenshots**

![2023_08_20_2930_orca-slicer](https://github.com/SoftFever/OrcaSlicer/assets/42773937/bc98a724-68c8-47ab-8e30-6cd1aad7f9f3)

**Desktop (please complete the following information):**
 - Windows 10
 - V1.6.4 beta3

**Comment by asychev** [comment]
Still broken in 1.6.4 release
