### ISSUE TITLE
P1S print options also have 'Flow Calibration' option... 

### ISSUE THREAD

**Issue by nirurin** [SoftFever/OrcaSlicer#1874]
**Describe the bug**
When you press the print button, the popup print menu includes the option to turn on 'flow calibration'... but the P1S doesn't have Lidar. This doesn't happen on bambu studio, it's just an orca bug. 

**To Reproduce**
Print any file on a P1S

**Expected behavior**
It should only have 'bed levelling', 'timelapse' and 'enable AMS' options. 

**Screenshots**
![Screenshot 2023-08-22 013536](https://github.com/SoftFever/OrcaSlicer/assets/3751273/902e0026-71e4-4490-9ee2-336f467d341a)

**Printer model**
P1S ... which does not have Lidar lol. 

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 11

**Comment by SurgeHawk** [comment]
You are using a custom profile for the P1S. On the default P1S profile the Flow Calibration is not present

 
![Flow_Cal](https://github.com/SoftFever/OrcaSlicer/assets/109320563/014c4178-a98c-48e8-9a00-393e58a801e3)

I would check your configuration.

**Comment by nirurin** [comment]
This is incorrect, I also tested it on the default profile and the same thing happened. 
I can workaround the issue by editing the config.json file, so the issue is with orcaslicer config. It lists the P1S as a strange amalgamation of p1p and x1c

**Comment by nirurin** [comment]
If you tested using todays updated version of Orca, than that may be why,
as the issue I was referring to was allegedly fixed as party of todays
update. However I have no updated yet, due to todays update having a bug
which completely breaks connection to bambu servers. I'll wait for the fix.
