### ISSUE TITLE
Not able to run Orca slicer on Windows

### ISSUE THREAD

**Issue by ttar1234** [SoftFever/OrcaSlicer#1876]
**Describe the bug**
I can't select printers in the welcome menu，so I can't do any thing else.

**To Reproduce**
just open exe file and it happens

**Expected behavior**
I expect I can use it.

**Screenshots**
https://lurl.cc/HsIhy

**Printer model**
bambu lab P1S

**Desktop (please complete the following information):**
 - OS: Windows11
 - Version: 22H2

**Comment by discip** [comment]
Same here on Windows 10!

**Comment by ttar1234** [comment]
The path to the exe should be English only.
Try to put it on desktop.
