### ISSUE TITLE
"Connecting to Server" Error when trying to send print - 1.6.4 release

### ISSUE THREAD

**Issue by TheSephiCloud** [SoftFever/OrcaSlicer#1878]
"Connecting to Server" Error when trying to send print

Slice anything and then try to "Print Plate" 
It won't let you send even though it sees the printer

Tried with the Windows Installer aswell as the portable Version
Stealth Mode is off and turning it off and on did not fix it either

Bug did not exist in 1.6.4.b2

P1P

Desktop Win10

**Comment by ThoughtfulDev** [comment]
Having the same issue. Didnt exist in b3

**Comment by Naninani** [comment]
Go to the Device tab and you will see it. I get the same as you on the Preview tab - Its the same issue.
<img width="478" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/1681582/5debe840-6cf2-471f-958f-775a05049790">

**Comment by ThoughtfulDev** [comment]
After logging out and then loggin back in it works...until you close orcaslicer.
I get both errors (on device tab AND on sent).

**Comment by NickUfer** [comment]
+1 same on windows

**Comment by FlyingLemming** [comment]
This is the same issue as [#1877](https://github.com/SoftFever/OrcaSlicer/issues/1877).

**Comment by Aron3DP** [comment]
I also cannot connect to any of my Bambu printers after updating. Reverted back to Beta 3 and now I can. BambuStudio also connects fine as well.

**Comment by SoftFever** [comment]
Thanks guys.
I'm aware of this issue, will investigate and release hotfix soon
