### ISSUE TITLE
Camera view in LAN mode

### ISSUE THREAD

**Issue by Prutsium** [SoftFever/OrcaSlicer#1879]
With the release of 1.6.4 there is still no camera view in LAN mode possible where BS can do this already.
![image](https://github.com/SoftFever/OrcaSlicer/assets/42968695/99a94eea-78d7-4493-a272-717de6997fa3)

Is this on the roadmap?

**Comment by SurgeHawk** [comment]
What printer are you using? I have a P1S in LAN mode and the cameras works fine in Orca.

**Comment by Prutsium** [comment]
X1C with AMS

**Comment by SoftFever** [comment]
can you try 1.6.6?

**Comment by Prutsium** [comment]
Will download now

**Comment by Prutsium** [comment]
Not sure what happened here but printer is online and connected (i see temp status and so on) 
When starting cam 2 errors ...
1: Not supported in LAN
2: Printer not conected :)
![image](https://github.com/SoftFever/OrcaSlicer/assets/42968695/603af315-cedd-4943-8bca-9724c4ae3c7b)

**Comment by fire1ce** [comment]
same here. lan-only mode. OrcaSlicer v1.6.6.
RTSP steam works fine in other places from the printer.

**Comment by SoftFever** [comment]
The access code will change everytime we change LAN or WAN mode.
What happens when you input the new acess code?

I tested on my P1P, it works fine.

**Comment by Qonstrukt** [comment]
I have the same issue. I have the RTSP stream working in Home Assistant, but OrcaSlicer can't seem to open it. Trying to open it in another video client at the same time, like VLC, works just fine, with the same access code.

**Comment by MotoFreak** [comment]
> The access code will change everytime we change LAN or WAN mode. What happens when you input the new acess code?
> 
> I tested on my P1P, it works fine.

In 1.6.6 I can get a video feed from my P1S  but not my X1C and both are in lan only mode.

**Comment by STC148** [comment]
Here the same, no video connection with my X1C in LAN mode with 1.6.6

**Comment by WZ9V** [comment]
Another one here, no camera feed from X1C LAN mode on Orca Slicer 1.6.6.  Running Linux Mint

**Comment by NairoDorian** [comment]
Camera Live feed does not work in 1.6.6 with X1 as well, I'm still in 1.5 firmware with the printer though, does this feature need the printer to be updated as well ?

**Comment by SoftFever** [comment]
It's tough to pinpoint the exact changes BL made in the slicer, closed-source plugin, or the black box printer firmware that might affect the camera feed.
Rather than chasing that down, I've updated the BL-related parts based on BS 1.7.4. 
This update also includes their lidar calibration changes.
Could you help verify if everything's working as expected?

You can download the nightly build here:
https://github.com/SoftFever/OrcaSlicer/actions/runs/5989893116

**Comment by NairoDorian** [comment]
@SoftFever Tried your latest build you linked, now I get a warning telling me to upgrade the printer
<img width="631" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/8990554/3b1e34d5-53cd-4a76-bf76-399e312185b0">
I'll finish my print and will update the firmware and try that again, will update here once I have results

**Comment by MotoFreak** [comment]
@SoftFever  just downloaded and tested the nightly build portable, P1S and X1C video feed works  now, thank you

**Comment by STC148** [comment]
confirm! works on X1C now. Thank you

**Comment by Prutsium** [comment]
Unfortunately cant check my printers are 12000km away as i am on business
trip in Sydney. If i find time will try to a vpn to home to test.

**Comment by NairoDorian** [comment]
I got an error now I updated and rebooted the printer and activated the Lan Live Video View in the X1 menu
<img width="437" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/8990554/823a9782-ed76-403f-9c5e-282dd4f860d4">

-10 | Certificate error | Check if you are using the official version of Bambu Studio

**Comment by Qonstrukt** [comment]
> It's tough to pinpoint the exact changes BL made in the slicer, closed-source plugin, or the black box printer firmware that might affect the camera feed. Rather than chasing that down, I've updated the BL-related parts based on BS 1.7.4. This update also includes their lidar calibration changes. Could you help verify if everything's working as expected?
> 
> You can download the nightly build here: [SoftFever/OrcaSlicer/actions/runs/5989893116](https://github.com/SoftFever/OrcaSlicer/actions/runs/5989893116)

This works perfectly for my on my X1C in LAN mode, thanks 😄

**Comment by bani6809** [comment]
> It's tough to pinpoint the exact changes BL made in the slicer, closed-source plugin, or the black box printer firmware that might affect the camera feed. Rather than chasing that down, I've updated the BL-related parts based on BS 1.7.4. This update also includes their lidar calibration changes. Could you help verify if everything's working as expected?
> 
> You can download the nightly build here: https://github.com/SoftFever/OrcaSlicer/actions/runs/5989893116

this seems to have fixed it for me on my x1c

**Comment by simonbuehler** [comment]
Video stream works for me now with the nightly on the p1p with new firmware, thanks!

**Comment by WZ9V** [comment]
Camera mode starts but locks up after a few seconds.
Orca Slicer 1.8.0 on Linux Mint 21.2 Cinnamon
