### ISSUE TITLE
P1S LAN mode not working

### ISSUE THREAD

**Issue by SurgeHawk** [SoftFever/OrcaSlicer#1882]
**Describe the bug**
After slicing model and attempting to print on a P1S it states that IP or access code is wrong.

In the device tab Ocra can connect to the P1S normally, camera works normally. This issue only occurs when attempting to print.

**To Reproduce**
1 - Load model
2 - Slice model with any settings
3 - print model
4 - ask to verify IP/Access code, confirm
5 - states wrong IP/Access code

**Expected behavior**
To allow printing of sliced models with the correct IP/Access code

**Screenshots**
![Wrong_P1S](https://github.com/SoftFever/OrcaSlicer/assets/109320563/18faeeb7-f5cd-4d92-a29e-26011230da36)

**Printer model**
Bambu Labs P1S

**Desktop (please complete the following information):**
 - Windows 10
 - Version 1.6.4 (Non-beta)

This issue was established with #1720 But has not had much traction.

**Comment by SurgeHawk** [comment]
This is still an issue with the latest commit ff92578.

@SoftFever

**Comment by gobau** [comment]
@SoftFever 
@SurgeHawk 

DeviceManager.cpp file
1392 lines
else if (printer_type == "C11")
=>
else if (printer_type == "C11" || printer_type == "C12")
When you change to , SSL is enabled and P1S LAN ONLY MODE operates normally.
If you give me the commit authority, I will modify it and request PR.

**Comment by SoftFever** [comment]
> @SoftFever @SurgeHawk
> 
> DeviceManager.cpp file 1392 lines else if (printer_type == "C11") => else if (printer_type == "C11" || printer_type == "C12") When you change to , SSL is enabled and P1S LAN ONLY MODE operates normally. If you give me the commit authority, I will modify it and request PR.

@gobau Great. Looking forward 
To create a PR, here is the workflow: fork -> create branch from main for the fix -> PR

**Comment by gobau** [comment]
@SoftFever 

PR Requested
https://github.com/SoftFever/OrcaSlicer/pull/1905

**Comment by SurgeHawk** [comment]
@gobau 
@SoftFever 

This has been resolved in f7184c8 1.6.6

Thank you! Closing issue

**Comment by SoftFever** [comment]
cheer.
Thanks @gobau  for the fix.
