### ISSUE TITLE
Orca slicer won't connect to the printer

### ISSUE THREAD

**Issue by Gil80** [SoftFever/OrcaSlicer#1886]
**Describe the bug**
Orca slicer won't connect to the printer, unlike Bambu studio. this is only happening since upgrade to 1.6.4.

**To Reproduce**
update to orca 1.6.4

**Expected behavior**
For Orca slicer to connect to my printer.

**Screenshots**
![image](https://github.com/SoftFever/OrcaSlicer/assets/8454919/35203971-e0ff-476b-bc1c-82a5fc80daf7)

**Printer model**
X1C

**Desktop (please complete the following information):**
 - OS: Window 11

**Comment by Gil80** [comment]
reinstalled and now it works.

**Comment by Mr-Savag3** [comment]
I have this problem, reinstalling didn't work. v1.8.1
