### ISSUE TITLE
Max flowrate calibration print causes TPU to jam (P1P)

### ISSUE THREAD

**Issue by PrincessLuna2253** [SoftFever/OrcaSlicer#1888]
**Describe the bug**
When performing the max flowrate calibration print, the slicer sets the max volumetric speed for the selected filament to 200mm3/s, which causes two problems for filaments with very low max volumetric flow values like TPU. 

The first is that the starting gcode for the P1P uses the volumetric flow limit to calculate how fast to print the priming line. This resulted in my P1P attempting to print the priming line at 15mm3/s which caused a jam. 

The second is that now the first layer prints at full speed, 50mm/s for me, which isn't as fast as the priming line but was still above 5mm3/s which was enough to cause the filament to jam.

**To Reproduce**
Select a filament with a low volumetric flow limit, generate a calibration print with appropriate values for said filament (1mm3/s start, 4mm3/s end, 0.2mm3/s step in my case), check the flow rates on the preview tab.

**Expected behavior**
The volumetric flow limit should be set to the end value instead of 200mm3/s, this would prevent the issue as long as a sensible end value is chosen.

**Screenshots**
![image](https://github.com/SoftFever/OrcaSlicer/assets/49230276/c1db7758-de95-4bb9-ae43-88adf1b0f0d2)

**Printer model**
Bambu Labs P1P

**Comment by SoftFever** [comment]
We'll need to set a reasonable max volumetric flow in the calibration dialog ourselves.
We can't rely on the max volumetric flow in the filament setting, as that would defeat the purpose of this test.

**Comment by PrincessLuna2253** [comment]
If the flow rate limit is automatically set to the max flow rate needed for the generated test it shouldn't interfere, and as long as a reasonable max value is chosen by the user it should make it so the filament will likely underextrude on the priming line and first layer but wouldn't strip. That said, adding max flow rate to the calibration dialog also sounds like a perfectly good solution.
