### ISSUE TITLE
"Fill bed with copies" does not perform well (enough)

### ISSUE THREAD

**Issue by foreachthing** [SoftFever/OrcaSlicer#1904]
## Describe the bug
Comparing to PrusaSlicer, OrcaSlicer does not perform very well in "filling bed" (I only wish those where instances over copies - but that's another (open) issue).

## 3mf File for This Bug
No need, STEP file is attached.
[USM-Headset.zip](https://github.com/SoftFever/OrcaSlicer/files/12426053/USM-Headset.zip)

## To Reproduce
1. load STEP
1. check "arrange" settings to be: 3.5 mm distance, rotation enabled (<- this matters!).
1. "Fill bed with copies"
1. observe results
1. repeat with PrusaSlicer (>= 2.6.0)

## Expected behavior
Very similar results, if not the same.

### OrcaSlicer
With rotation enabled:
![image](https://github.com/SoftFever/OrcaSlicer/assets/10420187/95d69dff-0fca-4de0-9106-9781bc4667af)

With rotation disabled 1:
![image](https://github.com/SoftFever/OrcaSlicer/assets/10420187/70e690f7-407d-4b3d-9915-440e2449826a)

With rotation disabled 2:
![image](https://github.com/SoftFever/OrcaSlicer/assets/10420187/eb39546c-0708-45f1-8cc6-7e83c81aa5d3)

### PrusaSlicer
![image](https://github.com/SoftFever/OrcaSlicer/assets/10420187/54a01271-2863-4837-b658-f2941b86c562)

## Desktop
- Windows 10/11
- OrcaSlicer 1.6.4
- PrusaSlicer 2.6.1rc1

**Comment by Noisyfox** [comment]
Not sure if it's caused by the "Arrange improvements" added in https://github.com/prusa3d/PrusaSlicer/releases/tag/version_2.6.1-rc1 have you tried PS 2.6.0?

**Comment by foreachthing** [comment]
Performance in 2.6 is the same.
Screenshot from 2.6.0 (arrange options: distance 3.5 mm, 1 mm spacing to plate and rotation enabled):
![image](https://github.com/SoftFever/OrcaSlicer/assets/10420187/c2a6b0ac-3b7b-4058-9e48-fd94138205e1)

So, I guess, it does not matter whether you port 2.6 or 2.6.1 ;-) If _I_ could make a wish, I'd like to be able to nest within objects => 2.6.1rc1 _(I yet have to try - but I want to keep using OrcaSlicer ...)_.

**Comment by Noisyfox** [comment]
![image](https://github.com/SoftFever/OrcaSlicer/assets/1537155/147e0eee-7f88-4491-b0ab-5f42df9dad55)
Much better now.

**Comment by foreachthing** [comment]
Not convinced, on my system 😆 
![image](https://github.com/SoftFever/OrcaSlicer/assets/10420187/4c6e76c7-46d0-4b6e-b80a-dbf0d7c87317)
To be fair, this was with a custom bed shape.

And now, with a rectangle:
_Naaa... same difference._
![image](https://github.com/SoftFever/OrcaSlicer/assets/10420187/67ac2915-aa27-48e2-ab81-40ab1f4eb4e4)

**Comment by Noisyfox** [comment]
Ah I didn't mean the production version. It's still under development and (mostly) working on my own dev branch.

**Comment by foreachthing** [comment]
This has yet to be fixed: "Fill bed with copies"
![image](https://github.com/SoftFever/OrcaSlicer/assets/10420187/368728c4-42be-4d64-95af-3104129774f9)

**Comment by kleinwareio** [comment]
Still an issue with round build plates

**Comment by foreachthing** [comment]
![image](https://github.com/SoftFever/OrcaSlicer/assets/10420187/8755bca6-2304-4ec9-8992-05cd8ce9af40)

With rectangular plates too.

**Comment by foreachthing** [comment]
This looks niiiiice, in 2.1rc1!!!
![image](https://github.com/SoftFever/OrcaSlicer/assets/10420187/708498b0-0b75-4a5d-aa81-194b7ce6994c)
