### ISSUE TITLE
Orca Slicer 1.6.4 doesn't connect to printer, but beta 3 does.

### ISSUE THREAD

**Issue by J9H2** [SoftFever/OrcaSlicer#1907]
**Describe the bug**
Printer won't connect to newest version of orcaslicer, the beta before it does work

**Screenshots**
<img width="167" alt="Screenshot 2023-08-24 134326" src="https://github.com/SoftFever/OrcaSlicer/assets/83965584/9a8bd41c-d639-4228-8f50-5661af97fbd7">

**Printer model**
Bambu Lab P1P
**Desktop (please complete the following information):**
 - OS: Windows

**Comment by SurgeHawk** [comment]
This has been resolved in the 1.6.5 release

**Comment by SoftFever** [comment]
Fixed in 1.6.6
