### ISSUE TITLE
Unable to edit Auxillary Fan Speed on filament profiles.

### ISSUE THREAD

**Issue by Soygen** [SoftFever/OrcaSlicer#1913]
When editing a custom filament profile, the aux fan speed setting is grayed out and I'm unable to edit it. I'm able to edit and save the setting in Bambu Studios, however. See picture:

![image](https://github.com/SoftFever/OrcaSlicer/assets/61511681/38f7144f-baeb-4642-ac1e-50794a627aae)

This is on Windows 10 and this started happening to me on a beta version of 1.6.4 but it's still  happening on 1.6.6 Any help is appreciated.

**Comment by SoftFever** [comment]
Hi
You will need to enable aux fan in machine profile

**Comment by Soygen** [comment]
> Hi You will need to enable aux fan in machine profile

Thanks so much. I must've missed that change when it went in. Thanks for all the work you do.
