### ISSUE TITLE
Crash if delete cube from pattern method PA, and slice. Doesnt show correct thumbnail either.

### ISSUE THREAD

**Issue by BakeJake** [SoftFever/OrcaSlicer#1925]
**Describe the bug**
Crash if delete cube from pattern method PA, and slice. Doesnt show correct thumbnail either.

**3mf File for This Bug**

**To Reproduce**
Steps to reproduce the behavior
Goto calibrations from prepare mode
select pressure advance, select pattern
delete unwanted cube
slice
crash

**Expected behavior**
delete cube, and slice, and still have pa pattern.

**Screenshots**
![image](https://github.com/SoftFever/OrcaSlicer/assets/52101762/8c567d54-f4ac-43c6-b832-ff9baf0c69ff)

**Printer model**
Ender 3 S1, Not Applicable though.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Windows]

**Comment by Arakon** [comment]
Same behavior with 1.7.0-beta.

**Comment by bani6809** [comment]
same behavior with 1.8.0-beta2

**Comment by BakeJake** [comment]
@bani6809 It also doesn't output the exclude object right for that test, It meshes my whole bed when I have adaptive.

**Comment by BakeJake** [comment]
> Dont delete that little cube - it's used as a handle to move the pattern around. Also best to disable exclude object when running this test.
> 
> Slim chance this will be corrected as its cosmetic issue.

Yeah thats bogus, it should be done internally we shouldnt see it placing that in the first place it should just work and do the pattern. should also display the pattern as an object after rendered so that it goes into the thumbnail. thats just lazy what you said lol.

**Comment by igiannakas** [comment]
> > Dont delete that little cube - it's used as a handle to move the pattern around. Also best to disable exclude object when running this test.
> > Slim chance this will be corrected as its cosmetic issue.
> 
> Yeah thats bogus, it should be done internally we shouldnt see it placing that in the first place it should just work and do the pattern. should also display the pattern as an object after rendered so that it goes into the thumbnail. thats just lazy what you said lol.

The pattern is implemented as a custom gcode. You can see that in the vertical slider. Hence why it needs an object to tie it to. The object can be removed but then you won't be able to move the pattern around. It's not an STL so you can't see it in the prepare tab.

**Comment by BakeJake** [comment]
> > > Dont delete that little cube - it's used as a handle to move the pattern around. Also best to disable exclude object when running this test.
> > > Slim chance this will be corrected as its cosmetic issue.
> > 
> > 
> > Yeah thats bogus, it should be done internally we shouldnt see it placing that in the first place it should just work and do the pattern. should also display the pattern as an object after rendered so that it goes into the thumbnail. thats just lazy what you said lol.
> 
> The pattern is implemented as a custom gcode. You can see that in the vertical slider. Hence why it needs an object to tie it to. The object can be removed but then you won't be able to move the pattern around. It's not an STL so you can't see it in the prepare tab.

You dont think it should be done internally? it should render an stl like OpenSCAD would. that would be ideal if youre worried about movement. No other slicer uses a placeholder for tuning that im aware of.

**Comment by igiannakas** [comment]
> > > > Dont delete that little cube - it's used as a handle to move the pattern around. Also best to disable exclude object when running this test.
> > > > Slim chance this will be corrected as its cosmetic issue.
> > > 
> > > 
> > > Yeah thats bogus, it should be done internally we shouldnt see it placing that in the first place it should just work and do the pattern. should also display the pattern as an object after rendered so that it goes into the thumbnail. thats just lazy what you said lol.
> > 
> > 
> > The pattern is implemented as a custom gcode. You can see that in the vertical slider. Hence why it needs an object to tie it to. The object can be removed but then you won't be able to move the pattern around. It's not an STL so you can't see it in the prepare tab.
> 
> You dont think it should be done internally? it should render an stl like OpenSCAD would. that would be ideal if youre worried about movement. No other slicer uses a placeholder for tuning that im aware of.

no other slicer implements this pattern. It's not an object, it's a custom gcode. Like the line pattern. The alternative is to display a text like the line pattern that is replaced when slicing.
