### ISSUE TITLE
Improved Infill Pattern Control

### ISSUE THREAD

**Issue by TheAtomicSoul** [SoftFever/OrcaSlicer#1942]
**Is your feature request related to a problem? Please describe.**
Currently you can only set a single option for the topmost, bottom, and single internal infill patterns.
It also only allows a single "Direction" for the infill.

**Describe the solution you'd like**
Cura allows the following: 

- Top Surface Skin Layers [# of skin layers] (I use [2])
- Top Surface Skin Pattern (I use [Line])
- Top Surface Skin Line Directions (I use  [0,90])

- Infill Pattern (Top/Bottom Patterns in Cura) (I use "Lines")
- Infill Line Direction (Top/Bottom Line Direction in Cura) (I use [45,-45,0,90])

Using the above infill line direction allows me to get all edges of a layer covered by a crossing direction, ensuring there' s no gaps (or "white" hot spot for light panels.)

**Describe alternatives you've considered**

Add an option to control "Infill Per Layer Direction and Pattern" 
- Set a number of infill layer settings that it will cycle the per layer settings through.
- Add options based on the above number for Layer Pattern and Line Direction

- Example:
- Infill Pattern [Infill Layer Control]
- Infill Layer Control [5]
-   ILC- Layer 1: Pattern [Line] , Direction [0]
-   ILC- Layer 2: Pattern [Line] , Direction [90]
-   ILC- Layer 3: Pattern [Line] ,  Direction [45]
-   ILC- Layer 4: Pattern [Line] ,  Direction [-45]
-   ILC- Layer 5: Pattern [Concentric] , Direction [NA]

With this example it would cycle through the five layer patterns and orientations for however many infill layers there are.

**Comment by TexZeTech** [comment]
I too would like to have the ability to set line direction on infill like shown in this video.

https://youtu.be/n5I2hBg0qHo?t=93
