### ISSUE TITLE
3DConnexion SpaceMouse control is wonky

### ISSUE THREAD

**Issue by ZyberSE** [SoftFever/OrcaSlicer#1950]
### Bambu Studio Version

1.6.6

### Where is the application from?

Bambu Lab github releases

### OS version

macOS 13.5

### Printer

RatRig VCore 3.1 400

### How to reproduce

Move the build plate with your normal mouse, then try todo the same with a 3DConnexion SpaceMouse, especially moving sideways (not rotating) and you'll see how it behaves.

Also add several build plates, slice and select one. Now rotate it with the SapaceMouse.

### Actual results

When moving sideways it's very slow.

Rotating with several build plates it feels like the center point is in the middle of all build plates and not the current one, this makes rotation wonky to use.

### Expected results

I expect it to move and be as snappy as in Fusion 360.

### Project file & Debug log uploads

Not needed, the behaviour is identical for all projects.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by jberry** [comment]
Not sure if related, but even my normal mouse goes wonky anytime the build plate disppears (such as support or seam painting modes). The rotation is totally screwed up somewhere, I have to go back to some mode with a build plate visible, rotate to where I want the object, then flip into whatever mode hides the build plate and paint then.
