### ISSUE TITLE
Top layer with terrible inconsistency

### ISSUE THREAD

**Issue by R4toLoko** [SoftFever/OrcaSlicer#1964]
### Bambu Studio Version

1.6.6

### Where is the application from?

Bambu Lab github releases

### OS version

Mint Cinnamon 21.1

### Printer

LDO Voron Trident 300mm

### How to reproduce

1. Slice a model

### Actual results

Top layer is creating this terrible inconsistency which not just increase the printing time but also terrible top layer finish.
No matter the wall generator you pick, you have this ugly finish.
I mean, look at this HDD.

![image](https://github.com/SoftFever/OrcaSlicer/assets/35049512/79646669-0f3a-476f-b042-c926ee44012f)

![image](https://github.com/SoftFever/OrcaSlicer/assets/35049512/f251bf36-fe00-417c-bc67-e9459de1c284)

### Expected results

PrusaSlicer on the right is the expected result with no weird top layer.
This is new and have been introduced recently!!

![image](https://github.com/SoftFever/OrcaSlicer/assets/35049512/5a5f5ac7-f77d-4935-9592-1fa2dcee87f6)

**IMPORTANT:** Please, fix this bug report, it looks a copy/paste from BambuStudio instead of OrcaSlicer.
Linux log for example is located under `$HOME/.config/OrcaSlicer/log`
Noobs will have a hard time following this.

Thank you

### Project file & Debug log uploads

[3MF.zip](https://github.com/SoftFever/OrcaSlicer/files/12483983/3MF.zip)

### Checklist of files to include

- [x] Log file
- [X] Project file

**Comment by R4toLoko** [comment]
This happens across different models so this is not a model, it happens with the project attached and any other project.

**Comment by R4toLoko** [comment]
[debug_Thu_Aug_31_18_15_35_36459.log](https://github.com/SoftFever/OrcaSlicer/files/12484070/debug_Thu_Aug_31_18_15_35_36459.log)

**Comment by R4toLoko** [comment]
Also, PrusaSlicer approach with the hook part makes more sense, it will also prints faster and better top layer quality.
On OrcaSlicer to do so, you need to disable the top surface scheme.

![image](https://github.com/SoftFever/OrcaSlicer/assets/35049512/cc6ee1e1-6633-4b02-a8f1-58553d7cc0cd)

The hook part only, it makes more sense than this.
I wonder if this isn't all related.

Thanks

![image](https://github.com/SoftFever/OrcaSlicer/assets/35049512/2e6ca8cd-e9ea-4e15-88dd-93b566afe9b0)

**Comment by Noisyfox** [comment]
Have you tried disabling the "single wall on top surface" option?

**Comment by R4toLoko** [comment]
> Have you tried disabling the "single wall on top surface" option?

Are you joking with me?? lol
I have single wall on top surface for awhile now but only now I notice the behavior above and following your recommendation solved the problem.

Thank you 
![image](https://github.com/SoftFever/OrcaSlicer/assets/35049512/ca5b2731-e290-4e37-a61a-d8bfbd1b06bc)
