### ISSUE TITLE
Only Prusa or MKS as Host Type possible after PR 27.8  PhysicalPrinterDialog.cpp

### ISSUE THREAD

**Issue by hliebscher** [SoftFever/OrcaSlicer#1967]
### Bambu Studio Version

1.7 dev

### Where is the application from?

Built from source by yourself or others

### OS version

Macos M1

### Printer

Prusa XL 2T ;-)

### How to reproduce

Select as Host Type  DUET  or other it is MKS 

### Actual results

MKS

### Expected results

DUET

### Project file & Debug log uploads

nothing

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by SoftFever** [comment]
Thanks for reporting.
Fixed
