### ISSUE TITLE
Extra perimeter on overhangs results in missing bridges / additional supports

### ISSUE THREAD

**Issue by jesterhead82** [SoftFever/OrcaSlicer#1968]
### Bambu Studio Version

1.7.0-dev

### Where is the application from?

Bambu Lab github releases

### OS version

Win11

### Printer

Selfmade

### How to reproduce

Without Extra Perimeters for Overhangs the slots are properly bridged:
![image](https://github.com/SoftFever/OrcaSlicer/assets/11690785/46a00b26-dcf5-467f-8f58-6b858b84eea6)

With Extra Perimeters for Overhang some bridges get replaced by Overhangs:
![image](https://github.com/SoftFever/OrcaSlicer/assets/11690785/7668a34f-96a0-4110-8932-4c193d2d5434)

Enabling "Dont support bridges" will print those long overhangs instead of short bridges.

### Actual results

Overhangs instead of bridges

### Expected results

Bridges instead of Overhangs

### Project file & Debug log uploads

[Gen 2 Lack Case - Double.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/12490161/Gen.2.Lack.Case.-.Double.3mf.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by tome9111991** [comment]
in my opinion no bug it is exactly what Extra perimeter on overhangs does.

**Comment by jesterhead82** [comment]
At least it should be either everywhere the same (because it generates only in some areas the extra perimeters).

Also SS does generate generate Bridge Infill type correctly for that Usecase properly with Extra Perimeters for Overhangs:

![image](https://github.com/SoftFever/OrcaSlicer/assets/11690785/560ed73d-7778-48fc-9c01-5c2b9e021c40)

**Comment by tome9111991** [comment]
the feature is ported from PS. maybe SS has a different behavior.
maybe @Noisyfox  can say something about it
