### ISSUE TITLE
Weird top layer

### ISSUE THREAD

**Issue by klmn-roland** [SoftFever/OrcaSlicer#1970]
### Bambu Studio Version

1.7.4.52

### Where is the application from?

Bambu Lab Official website

### OS version

Win 11 64bit

### Printer

X1C 

### How to reproduce

Slice a model with thin text on its top surface

### Actual results

Bad quality prints using orca slicer with the same model and profile as in bambu

### Expected results

Top surface like in bambu studio

### Project file & Debug log uploads

![IMG_4190](https://github.com/SoftFever/OrcaSlicer/assets/72163867/1a21222f-28c4-445e-9a1e-9d058147e20d)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Noisyfox** [comment]
Try disable the single wall on top surfaces option.

**Comment by klmn-roland** [comment]
Yeah this worked, thanks. But bambu studio works fine even if it's turned on.

**Comment by Noisyfox** [comment]
Yeah improving this is on the list.
