### ISSUE TITLE
Part cooling Fan speed control settings

### ISSUE THREAD

**Issue by kot0005** [SoftFever/OrcaSlicer#1972]
![image](https://github.com/SoftFever/OrcaSlicer/assets/68181325/7d4c4cf9-c115-4d0d-a8d8-759b628ffeaf)

could we please get the settings for fan speed control, like superslicer has ?

I was going to try orcaslicer on my klipper printer but noticed it doesnt have any fine tuning controls for part cooling fan.

i have included a screenshot of the settings that superslicer has.

**Comment by movinimage** [comment]
This!

It is sometimes critical to change the fan speed for Internal bridging AKA the first solid layer on top of infill...which Prusa derivatives see as a bridge...hard-to-print-warp-prone filaments like ASA need this for internal bridges that are large and close to the bed.

The first solid layer on top of infill is considered a bridge and therefore uses the bridging fan speed. This is fine for lot of filaments...but high-warp ones like ASA can't take an entire large layer of 80% fan...especially if it is only 1/4" off the build plate at that time....it consistently warps the part and all the corners come off the build plate, and the part is ruined.

The only way to fix it currently is to sit by the printer and when a large, low internal bridge starts to print, manually lower the fan.

**Comment by jeremytodd1** [comment]
Agreed. These settings would be really handy to have in some cases.

I recently had an issue where a 2 layer thick part of an object had a shiny finish. I then realized that my part cooling fan is only set to turn on after layer 3, which is a good thing as that will help prevent the first layer from warping.

To fix the shiny surface on the 2nd layer though, I had to set the filament's cooling to start the fan after layer 1.

If I had these settings I would have been able to just set the "top layers fan speed" and it would have been perfect.

I'm all for these settings to be added.

**Comment by kot0005** [comment]
Hi, any update on having these settings in Orca slicer ?

**Comment by nfons** [comment]
+1 to this....when using larger layer heights, part cooling sometimes warps the prints since it doesnt allow cooling fast enough at heigher heights.

**Comment by VladKolerts** [comment]
how to switch off fan?

**Comment by philbert440** [comment]
can we reopen this?

**Comment by Novichek-13** [comment]
who has figured out how to completely turn off the airflow when printing? It gets in the way when printing ABS

**Comment by fantastic-engineering** [comment]
For anyone still looking for fan controls, they are not in the printer settings, they are in the **filament** settings.
![image](https://github.com/SoftFever/OrcaSlicer/assets/171324466/44ea2a66-74ee-472c-a611-58af5c3b8d00)
![image](https://github.com/SoftFever/OrcaSlicer/assets/171324466/735c1c2d-defe-4efc-9ed5-42a3b7d7ce3a)
Hope this helps :)

**Comment by VladKolerts** [comment]
> For anyone still looking for fan controls, they are not in the printer settings, they are in the **filament** settings. 
We know where fan control settings)
Our question "**How to switch off the fan?**" 
You can just set  "No cooling for the first" to 99999 - not cool

**Comment by Maxell2904** [comment]
This is a big issue for me. Please improve fan controls.

**Comment by GrigoriyPeters** [comment]
It would be nice to have this issue reopened.
Inability to fully disable fan is frustrating.
And it would be cool, to disable fan cooling in project settings.
Like I know which parts is stronger without cooling and vice versa.

**Comment by SarraceniaWilds** [comment]
![screenshot](https://github.com/SoftFever/OrcaSlicer/assets/130192690/dfff78d2-b644-4d50-bef1-401539efeb8c)
Screenshot to illustrate request. Lack of feature specific control for fan, is there an open issue for this request? #5328? #4370?

**Comment by Asiak3** [comment]
Any fix for this?

**Comment by KubaMiszcz** [comment]
> For anyone still looking for fan controls, they are not in the printer settings, they are in the **filament** settings. ![image](https://github.com/SoftFever/OrcaSlicer/assets/171324466/44ea2a66-74ee-472c-a611-58af5c3b8d00) ![image](https://github.com/SoftFever/OrcaSlicer/assets/171324466/735c1c2d-defe-4efc-9ed5-42a3b7d7ce3a) Hope this helps :)

and how turn default fan to 80% for whole print? excepr exclusions,

**Comment by KubaMiszcz** [comment]
> It would be nice to have this issue reopened. Inability to fully disable fan is frustrating. And it would be cool, to disable fan cooling in project settings. Like I know which parts is stronger without cooling and vice versa.

also it is good if i can set to 80% eg

**Comment by Lensaic** [comment]
Would love a "fan blocker" modifier that could be added to certain portions of parts. Printing ABS-ASA multi-material part where the top layer of the material transition, while completely solid, is considered a bridge and gets the bridge fan speed. Because this is close to the bed it has been warping the part. Other internal bridges need the modified fan speed, and I haven't found a way to reduce the fan just for this part of the print.

**Comment by r0ddty** [comment]
Bump
