### ISSUE TITLE
FR: temp tower - go as low as 170°C

### ISSUE THREAD

**Issue by mhaas** [SoftFever/OrcaSlicer#1985]
**Is your feature request related to a problem? Please describe.**

When I was dialing in the Extrudr Wood filament, I could not run a temp tower across the recommended range of 170°C to 190°C.

**Which printers will be beneficial to this feature**

All printers that process Extrudr Wood filament :)

**Describe the solution you'd like**

Reduce the minimum temperature for the temp tower to 170°C.

**Describe alternatives you've considered**

* Use a third-party temp tower
* Just start calibration from 180°C

**Additional context**

![Screenshot at 2023-09-03 09-35-15](https://github.com/SoftFever/OrcaSlicer/assets/260872/726107fc-d998-45f4-a702-3c6af2eb1efb)

**Comment by SoftFever** [comment]
Fixed.
