### ISSUE TITLE
1.7-Dev: Original softfever calibrations not showing

### ISSUE THREAD

**Issue by igiannakas** [SoftFever/OrcaSlicer#1987]
### OrcaSlicer Version

1.7-Dev

### OS version

OSX

### Additional system information

MacBook Pro 14 - M1 Pro, retina screen

### Printer

X1 Carbon

### How to reproduce

A small set of UI defects I've found while playing around with 1.7-Dev. They may be on your radar, but if not, please see below:

**_Number 1 is now resolved, thank you!_**

**1. Layer and movement sliders not showing in OSX.**
Add one pre-built primitive (just to have an object to slice).
Slice object.
Sliders are not showing.
![Screenshot 2023-09-03 at 11 26 04](https://github.com/SoftFever/OrcaSlicer/assets/59056762/c47dbb70-b776-46f0-9551-48757552f6da)

This is caused by commit c54386d and specifically the multiplication with the m_layers_slider->m_scale. Reverting that change restores the bars

```
#if ENABLE_RETINA_GL
        IMSlider* m_layers_slider = get_gcode_viewer().get_layers_slider();
        IMSlider* m_moves_slider = get_gcode_viewer().get_moves_slider();
        const float sc = m_retina_helper->get_scale_factor();
        m_layers_slider->set_scale(sc);
        m_moves_slider->set_scale(sc);
        m_gcode_viewer.set_scale(sc);

        auto* m_notification = wxGetApp().plater()->get_notification_manager();
        m_notification->set_scale(sc);

#endif
```

**2. Non Bambu lab ported calibrations not showing**
The Softfever calibrations (PA, VFA test, tolerance test etc) are not visible any more on the UI. I suppose it's because the layout shifted due to the BBL Slicer port. Also the menu option is gone.

![Screenshot 2023-09-03 at 11 26 20](https://github.com/SoftFever/OrcaSlicer/assets/59056762/0cec00c9-6c90-4440-91f2-36577cbcd6e2)

### Actual results

As above

### Expected results

As above

### Project file & Debug log uploads

[OrcaCube.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/12505502/OrcaCube.3mf.zip)

### Checklist of files to include

- [x] Log file
- [X] Project file

**Comment by rovili** [comment]
MacBook Pro 14 - M1 Pro, retina screen, X1C.
Same here. On top of that, starting the manual calibration process closes OrcaSlicer instantly.
