### ISSUE TITLE
No calibration option

### ISSUE THREAD

**Issue by ppsirius** [SoftFever/OrcaSlicer#1991]
### OrcaSlicer Version

1.6.6

### OS version

Mac OS Ventura 13.5 

### Additional system information

CPU intel

### Printer

Sidewinder X2

### How to reproduce

1. Open Orca Slicer

### Actual results

Can't run calibration option, all are disabled.
https://www.dropbox.com/s/wcjlnixgylvbfvo/Screenshot%202023-09-03%20at%2011.11.58.png?dl=0

### Expected results

Can calibrate.

### Project file & Debug log uploads

.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by jattie-ire** [comment]
Please elaborate, I can see this on Linux, is this not planned for Windows and IOS?
