### ISSUE TITLE
Set speed as % of top speed

### ISSUE THREAD

**Issue by mattiasthalen** [SoftFever/OrcaSlicer#1992]
One field for entering top speed, then the ability to enter % (of top speed) for the other speed fields.

I often find myself having a spreadsheets with the % of top speed entered, calculated and then manually entered into Orca. Would be nice if this could be done directly in Orca.

**Comment by kylek29** [comment]
I think it's been suggested before. I wouldn't mind it myself, could simplify things .. especially if there's a corresponding Filament -> Settings Override field, so you don't have to maintain multiple profiles for different filaments (like PETG).
