### ISSUE TITLE
Finish retract before wipe ends.

### ISSUE THREAD

**Issue by npoulos** [SoftFever/OrcaSlicer#2012]
So currently you can have retract before wipe + retract with wipe but it would be great if you could retract during a wipe and finish retracting before the wipe ends.

If you look at the below screenshot, you'll see that it wipes while retracting (great!) but at the end of the "wipe" move it hasn't actually finished retracting and so has a tiny retract move without the nozzle moving right before it sets off for the next line.
<img width="514" alt="Screenshot 2023-09-05 at 5 10 22 pm" src="https://github.com/SoftFever/OrcaSlicer/assets/58903683/44658cbd-b70d-4b33-a381-462851454523">

I've found this allows for a tiny bit of stringing (especially on a .2 nozzle with printing very close miniature bits).

I'm trying to think of what it would call to retract over a shorter distance of the wipe move but cannot think so maybe a setting of "extra wipe length"  which allows you to add some more wiping after the nozzle has completely retracting during the first wipe move?

Either that or something like "Amount of wipe move to retract during".

**Comment by SoftFever** [comment]
Nice finding.
I think this might be a bug.
It should finish retraction during wiping.
It makes no sense to leave that 0.07 retraction there.

**Comment by b00gie-dev** [comment]
That's funny. I investigated yesterday the same thing. Here's the comparison with the current PrusaSlicer (2.6.1).
Prusa:
![prusa_wipe](https://github.com/SoftFever/OrcaSlicer/assets/61452016/5f375519-1119-445d-8227-1de83a596023)
Orca:
![orca_wipe](https://github.com/SoftFever/OrcaSlicer/assets/61452016/215e5cbf-5ede-447e-843c-8649e7145574)

Also @npoulos: Maybe this is a percentage value. Just by guess... Is your retraction set to 1.4mm? If so, then this unnecessary retraction after wipe is 5% of retraction length

**Comment by npoulos** [comment]
Interesting it's not present on purse slicer! It's there on BBS so must be a bug carried over from them.

I actually have no idea what I had retraction set to in that screenshot. I was doing retraction tests which lead me to the discovery so it could have been anything between .8 and 2.

**Comment by SoftFever** [comment]
Will be fixed in 1.7

**Comment by npoulos** [comment]
Amazing work thanks man! 😊

**Comment by gak45** [comment]
Any ETA on 1.7 as this issue is really, really annoying to deal with.

**Comment by SoftFever** [comment]
1.7 beta will be ready very soon.
Meanwhile, if you are interested, you can get the nightly build here: https://github.com/SoftFever/OrcaSlicer/actions/runs/6131933747

This build should be really close to the coming 1.7.0-beta if not identical.

**Comment by gak45** [comment]
Thanks! Appreciate it. :)

**Comment by SoftFever** [comment]
Fixed.
