### ISSUE TITLE
Feature Request: Import Organic Tree Supports from PrusaSlicer

### ISSUE THREAD

**Issue by itsKylvanas** [SoftFever/OrcaSlicer#2017]
**Is your feature request related to a problem? Please describe.**
I noticed OrcaSlicer has TreeSupports but after watching videos and going back into OrcaSlicer, it does not offer Organic Tree Supports, which I'm told "are a lifesaver" "In contrast to the previously common implementation of tree supports, the branching of Organic supports is smarter and we made them straighter (shorter), smoother, and more stable. The cross-section perpendicular to the branch axis is guaranteed to be circular, and the algorithm automatically uses double perimeter walls for the trees where needed (this is configurable)."

**Which printers will be beneficial to this feature**
All FDM Printers. Possibly Resin

**Describe the solution you'd like**
Implementation of Support for Organic Supports and "Snug" Support Profile Imported from PrusaSlicer 2.4

**Describe alternatives you've considered**
Using PrusaSlicer to Slice Models and Import to Orca

**Additional context**

**Comment by jeremytodd1** [comment]
Issue has already been worked. They are currently working on fixing some build issues, but after that they will be ready to use.

Follow here: https://github.com/SoftFever/OrcaSlicer/actions/runs/6057575634

Please close this issue.
