### ISSUE TITLE
Fan Speed only at 80%

### ISSUE THREAD

**Issue by mharmuth** [SoftFever/OrcaSlicer#2020]
### OrcaSlicer Version

1.6.6

### OS version

macOS

### Printer

Voron 2.4

### How to reproduce

I've got the following filament settings active:
![cooling](https://github.com/SoftFever/OrcaSlicer/assets/1242896/7236c9e5-e4b2-447b-9194-bf2deddca9e1)

### Actual results

Fan speed is maxed at 80%
![fan_speed](https://github.com/SoftFever/OrcaSlicer/assets/1242896/b986d0e0-27a9-482a-ad76-2f8cf744ae4e)

### Expected results

Fan speed should be at 100% most of the time. Why is it only at 80%

### Project file & Debug log uploads

[3DBenchy.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/12535201/3DBenchy.3mf.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by SoftFever** [comment]
Seems it's using first filament's fan cooling setting.

**Comment by mharmuth** [comment]
You are right. When I remove the first filament, it's working. But I explicitly set the Filament to the second one on the model. The preview correctly shows the color from the second filament, too.

**Comment by SoftFever** [comment]
Yes, it's a bug.

**Comment by SoftFever** [comment]
Duplicated with [#1829](https://github.com/SoftFever/OrcaSlicer/issues/1829)
