### ISSUE TITLE
Slicer generates unwanted G17 calls and G3 calls with arc fitting disabled

### ISSUE THREAD

**Issue by celtare21** [SoftFever/OrcaSlicer#2024]
### OrcaSlicer Version

1.7.0-dev

### OS version

Windows 11

### Printer

ZeroG Mercury One

### How to reproduce

Slice provided file with z-hop on auto or spiral, check the gcode and random G17 calls are added and also G3 calls even tho "Arc Fitting" is disabled:
![image](https://github.com/SoftFever/OrcaSlicer/assets/29823626/5644211a-b45d-4ce1-9d80-ca4c1a4c7311)

### Actual results

_spiral_travel_to_z should makes G3 or G17 calls
No  should be made

### Expected results

_spiral_travel_to_z should not make G3 or G17 calls

### Project file & Debug log uploads

[Mewtwo-Freestanding (2).zip](https://github.com/SoftFever/OrcaSlicer/files/12537096/Mewtwo-Freestanding.2.zip)
[debug_Wed_Sep_06_15_05_23_20396.log.zip](https://github.com/SoftFever/OrcaSlicer/files/12537101/debug_Wed_Sep_06_15_05_23_20396.log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by SoftFever** [comment]
@celtare21 
It's the spiral z hop that generate arc moves.
You need to disable that too.

**Comment by celtare21** [comment]
@SoftFever just to confirm, this is intended behavior to not have spiral z hop without arc moves?

**Comment by SoftFever** [comment]
I'm not sure if I get your question correctly.
The spiral z hop is not linked with arc fitting option. 
They all generate G3 commands but for different purpose.

-Jack

**Comment by celtare21** [comment]
Got it, I'll close this ticket then. Thanks for the support
