### ISSUE TITLE
OrcaSlicer 1.6.6 Crash When Slicing Multicolor Print on M1 MAC

### ISSUE THREAD

**Issue by PSS1205** [SoftFever/OrcaSlicer#2026]
I can't do a multicolor print with this version. Using MAC M1 laptop running OS 12.3.1.

Trying to do a color change at certain layer height.

I add a second filament and import my object. I then slice the model and use the slider to select at what layer height I want my second color to start at. The PREPARE tab shows object and purge block on the plate.

Right after slicing the file OrcaSlicer crashes.

![OS](https://github.com/SoftFever/OrcaSlicer/assets/144282375/195de7b7-8ca7-49c0-b693-55d6c04e4a00)

**Comment by SoftFever** [comment]
Is it possible to share the project file?
