### ISSUE TITLE
Exclude Object NAME causes malformed command in Klipper when special characters in name (soln = surround w quotes)

### ISSUE THREAD

**Issue by jcleclaire** [SoftFever/OrcaSlicer#2027]
### OrcaSlicer Version

1.6.6

### OS version

Windows 11

### Additional system information

N/A

### Printer

Voron 2.4r2 (Klipper)

### How to reproduce

1. Activate Label Objects and Exclude Objects under Process > Others
2. Slice a model that has special characters in it's name (like apostrophies)
3. Try and print

The solution is to surround the NAME in quotes ie NAME = name_of_object_'_ -> "name_of_object_'_" or remove all special characters.

### Actual results

Malformed command 'EXCLUDE_OBJECT_DEFINE NAME=2023-09-05_16-54-54___Max's_Shroud.stl_id_0_copy_0 CENTER=175,175 POLYGON=[[35,175],[35.0001,174.824],[35.0005,174.628],[35.0011,174.435],[35.002,174.244],[35.0032,174.057],[35.1332,168.893],[35.5327,162.798],[36.1977,156.726],[37.1269,150.689],[38.3186,144.698],[39.7704,138.765],[41.4796,132.901],[43.443,127.117],[45.6569,121.424],[48.1169,115.833],[50.8185,110.355],[53.7564,105],[56.9252,99.7781],[60.3187,94.6993],[63.9305,89.7734],[67.7538,85.0097],[71.7812,80.4174],[76.0051,76.0051],[78.1882,73.869],[80.4174,71.7812],[82.6916,69.7424],[85.0097,67.7538],[87.3707,65.8162],[89.7734,63.9305],[92.2167,62.0978],[94.6993,60.3187],[97.2202,58.5943],[99.7781,56.9252],[102.372,55.3123],[105,53.7564],[107.662,52.2583],[110.355,50.8185],[113.08,49.4378],[115.833,48.1169],[118.615,46.8564],[121.424,45.6569],[124.259,44.5189],[127.117,43.443],[129.998,42.4298],[132.901,41.4796],[135.824,40.593],[138.765,39.7704],[141.724,39.0121],[144.698,38.3186],[147.687,37.6901],[150.689,37.1269],[153.703,36.6294],[156.726,36.1977],[159.759,35.8321],[162.798,35.5327],[165.844,35.2997],[168.893,35.1332],[171.946,35.0333],[175,35],[178.054,35.0333],[181.107,35.1332],[184.156,35.2997],[187.202,35.5327],[190.241,35.8321],[193.274,36.1977],[196.297,36.6294],[199.311,37.1269],[202.313,37.6901],[205.302,38.3186],[208.276,39.0121],[211.235,39.7704],[214.176,40.593],[217.099,41.4796],[220.002,42.4298],[222.883,43.443],[225.741,44.5189],[228.576,45.6569],[231.385,46.8564],[234.167,48.1169],[236.92,49.4378],[239.645,50.8185],[242.338,52.2583],[245,53.7564],[247.628,55.3123],[250.222,56.9252],[252.78,58.5943],[255.301,60.3187],[257.783,62.0978],[260.227,63.9305],[262.629,65.8162],[264.99,67.7538],[267.308,69.7424],[269.583,71.7812],[271.812,73.869],[273.995,76.0051],[278.219,80.4174],[282.246,85.0097],[286.069,89.7734],[289.681,94.6993],[293.075,99.7781],[296.244,105],[299.182,110.355],[301.883,115.833],[304.343,121.424],[306.557,127.117],[308.52,132.901],[310.23,138.765],[311.681,144.698],[312.873,150.689],[313.802,156.726],[314.467,162.798],[314.867,168.893],[314.997,174.057],[314.998,174.244],[314.999,174.435],[315,174.628],[315,174.824],[315,175],[315,175.021],[315,175.22],[314.999,175.42],[314.999,175.622],[314.998,175.824],[314.996,176.026],[314.867,181.107],[314.467,187.202],[313.802,193.274],[312.873,199.311],[311.681,205.302],[310.23,211.235],[308.52,217.099],[306.557,222.883],[304.343,228.576],[301.883,234.167],[299.182,239.645],[296.244,245],[293.075,250.222],[289.681,255.301],[286.069,260.227],[282.246,264.99],[278.219,269.583],[273.995,273.995],[269.583,278.219],[264.99,282.246],[260.227,286.069],[255.301,289.681],[250.222,293.075],[245,296.244],[239.645,299.182],[234.167,301.883],[228.576,304.343],[222.883,306.557],[217.099,308.52],[211.235,310.23],[205.302,311.681],[199.311,312.873],[193.274,313.802],[187.202,314.467],[181.107,314.867],[175,315],[168.893,314.867],[162.798,314.467],[156.726,313.802],[150.689,312.873],[144.698,311.681],[138.765,310.23],[132.901,308.52],[127.117,306.557],[121.424,304.343],[115.833,301.883],[110.355,299.182],[105,296.244],[99.7781,293.075],[94.6993,289.681],[89.7734,286.069],[85.0097,282.246],[80.4174,278.219],[76.0051,273.995],[71.7812,269.583],[67.7538,264.99],[63.9305,260.227],[60.3187,255.301],[56.9252,250.222],[53.7564,245],[50.8185,239.645],[48.1169,234.167],[45.6569,228.576],[43.443,222.883],[41.4796,217.099],[39.7704,211.235],[38.3186,205.302],[37.1269,199.311],[36.1977,193.274],[35.5327,187.202],[35.1332,181.107],[35.0038,176.026],[35.0024,175.824],[35.0014,175.622],[35.0006,175.42],[35.0002,175.22],[35,175.021],[35,175]]'

### Expected results

The print should print

### Project file & Debug log uploads

[Exclude Object Name Issue.zip](https://github.com/SoftFever/OrcaSlicer/files/12544905/Exclude.Object.Name.Issue.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by SoftFever** [comment]
Fixed.
