### ISSUE TITLE
Slicer stays on white screen and doesnt open 

### ISSUE THREAD

**Issue by OrbitalSaint** [SoftFever/OrcaSlicer#2031]
### OrcaSlicer Version

1.6.6 

### OS version

windows 10

### Additional system information

CPU Intel 11th Gen i7 

### Printer

bambu x1c

### How to reproduce

1. Open slicer 
2. Blank screen

### Actual results

The slicer freezes on white screen. 

### Expected results

The slicer opens 

### Project file & Debug log uploads

theyre blank
![1 6 6 error](https://github.com/SoftFever/OrcaSlicer/assets/144385673/bbdeceb1-7a23-49f6-85ae-a198684cd7be)
![1 6 6 error 1](https://github.com/SoftFever/OrcaSlicer/assets/144385673/6b467905-90e8-4770-9ad7-dc9fd0a270fe)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by lin-ycv** [comment]
I'm also encountering this problem, to be more exact, for me, this only happens if orca launches on a non-primary display.

**Comment by ultimateshadsform** [comment]
I have the same issue. on latest version.

![image](https://github.com/SoftFever/OrcaSlicer/assets/151234273/73cce727-2056-4927-b394-726390fc7915)

It doesn't freeze but the device tab just doesn't load.

**Comment by yobaNGE** [comment]
As mentioned earlier this bug appears when slicer was closed on secondary display, so after you open it again you get a white screen.
For myself i figured a workaround to this, if i catch this bug, disable all secondary screens and start slicer, than turn screens back on.

**Comment by ultimateshadsform** [comment]
I only have 1 display.

**Comment by nicks911e** [comment]
I just had exactly the same problem in macos, latest os, latest revision of orca slicer, all I did to fix it was drag orca to my primary screen and back again, now all ok
