### ISSUE TITLE
option to hide Bambu Network login window pane

### ISSUE THREAD

**Issue by dlarue** [SoftFever/OrcaSlicer#2032]
**Is your feature request related to a problem? Please describe.**

No problem, just lots of wasted space when a user of the slicer is not on the Bambu network

**Which printers will be beneficial to this feature**
E.g. Voron/Klipper based printer/etc...

All but Bambu printers

**Describe the solution you'd like**

The left most window pain of the Home screen shows Bambu Network Login/Register and that should be hidden with a config file setting such as: 
        "show_login_window": false
or
        "show_bambu_login_window": false,

**Describe alternatives you've considered**

I've not seen any other way to hide or minimize that window pane.

**Additional context**

**Comment by johnsonm** [comment]
It might make sense to actually extend such a setting to also not reach out to e.bambulab.com at all. That might affect the best name to choose for such a feature.

**Comment by dlarue** [comment]
> It might make sense to actually extend such a setting to also not reach out to e.bambulab.com at all. That might affect the best name to choose for such a feature.

Does it go to e.bambulab.com regardless of installing the Bambu network driver and/or logging in?  That should not be happening in my book. Thanks for pointing this out

**Comment by johnsonm** [comment]
Yeah. I have not installed the Bambu network plugin, never logged into Bambu, don't have a Bambu, so I was surprised that OrcaSlicer was still reaching out to e.bambulab.com. I don't know what for.

**Comment by szafranski** [comment]
Hi, I agree. Downloading this Bambu-network-thing should be optional. No point of seeing this, every time after upgrade:
<img width="481" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/23621888/f55cd2f6-a4a7-4771-988f-4bd9cbf6d196">
Thanks!

**Comment by johnsonm** [comment]
Not actually stale as of 1.8.1

**Comment by johnsonm** [comment]
Well, I guess it's now clear that OrcaSlicer is only meant for Bambu. :sob:
