### ISSUE TITLE
Max Volumetric speed bug?

### ISSUE THREAD

**Issue by mysticprysm** [SoftFever/OrcaSlicer#2033]
### OrcaSlicer Version

1.6.6

### OS version

Windows 11

### Additional system information

Ryzen 7 5700x
RTX 3070
32GB RAM

### Printer

BambuLab P1P

### How to reproduce

Change max volumetric speed I think?

### Actual results

So, I'm not sure if it's model specific or what, but when I slice this model, be it with one on the plate, or multiple, it shows this high volumetric speed near the bottom, even though I have it capped. For visual sake, I capped it at 5, and it shows it getting up to 20 still. Unsure if it's a functional bug or visual glitch, but the print does seem to suffer in that area.

### Expected results

The volumetric speed should be capped at whatever you cap it at.

### Project file & Debug log uploads

[log.zip](https://github.com/SoftFever/OrcaSlicer/files/12555162/log.zip)
[Mushroom Containers.zip](https://github.com/SoftFever/OrcaSlicer/files/12555163/Mushroom.Containers.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by ercdvs** [comment]
Came here to look this up.  I have max volumetric speed set to 24mm^3, but i have, for a .6 nozzle, .3 layer height, and .62 line width have a wall @ 200mm/s

This results in a volumetric limit north of 37mm^3, and therefore fails to print.   The speed should be dropped to enforce this limit

**Comment by jaimewyant** [comment]
I'm having a similar issue also.  I've set the max volumetric flow rate to 5 but it hits 13.37 at certain parts of the model.  The image below illustrates this.

![slicer-speed](https://github.com/SoftFever/OrcaSlicer/assets/12301698/c3234bee-beb8-49f5-bfb7-d03246d74ca1)

**Comment by jaimewyant** [comment]
The bug is fixed in 1.7 for me.  @mysticprysm  may be worth checking out for you too.

**Comment by ercdvs** [comment]
1.7 is what i am using, and it is present for me still.  Even though i have max volumetric speed set, its allowing the speed to contribute leading to some areas to outrun my set flow.   I need to go an manually adjust speed for all areas which defeats the purpose

**Comment by Ninix-source** [comment]
I'm having the same issues as @ercdvs. Currently running 1.7 too.

**Comment by top4ek** [comment]
![Screenshot_20231023_180948](https://github.com/SoftFever/OrcaSlicer/assets/16016/7b28f499-e4f0-46a0-bce1-1fa05da9191f)
Got the same bug on 1.7 while material limit is 8.

**Comment by hatkyinc2** [comment]
1.8.0-beta2 same issue, the max volumetric flow doesn't seem to matter if you put speed up, can get to crazy numbers over

**Comment by hatkyinc2** [comment]
I found a similar bug in superslicer and it seems correct
https://github.com/supermerill/SuperSlicer/issues/3869
Basically flow multiplier/ratio is applied to max volumetric flow 🤦 
So one should divide the required max volumetric flow by flow ratio to get the desired result

**Comment by edooman** [comment]
<img width="730" alt="111111" src="https://github.com/SoftFever/OrcaSlicer/assets/159452124/002687b9-b2b9-4579-be80-2f581c88a030">

Same here on many models, Volumetric test is affected too with abnormal behavior. Orca ver. 2.0.0 dev

**Comment by DearTanker** [comment]
This error still exists in the latest version of OrcaSlicer V2.1.1 Official Release

**Comment by jeffalanmcclain** [comment]
Is it possible that you have "don't slow down outer walls" checked too?  I seem to see this significantly cause external walls to print with faster flow (I think there is not a way to limit it then because too many parameters to obey)?  If I uncheck this option, I can get it to significantly fall into the max volumetric flow rate (time flow ratio) on most areas.  Dramatically lines up.

**Comment by stefansjs** [comment]
I just came to check this bug. I'm seeing this as well. I do not have "don't slow down outer walls" checked for this filament. I also calculated the flow rate based on my multiplier of 1.078, which should give me a maximum of 20 mm3/s if I limit to 18.4, but it still shows a maximum of 22.4
<img width="911" alt="Screenshot 2024-08-16 at 1 46 52 AM" src="https://github.com/user-attachments/assets/f1b65b59-78c4-45e9-bad9-b0feea837cef">

FYI, if the dev team doesn't have resources to fix these types of bugs in a timely manner, then you should consider changing the github actions behavior to not close these issues right away. This is an open source project without (IIUC) any institutional support/money behind it, so the ticket management probably shouldn't be the same as if you had a full-time development team, project managers, etc.

**Comment by ShantanuNair** [comment]
@stefansjs @DearTanker @jeffalanmcclain You can see my finings and solutions [here.](https://github.com/SoftFever/OrcaSlicer/issues/7307#issuecomment-2766022845) Only later did I find out @hatkyinc2 already posted here what the issue is. For effective restricting of flow rate, divide your desired max vol speed by your flow ratio.
