### ISSUE TITLE
1.7 Dev: Organic Supports - Interface layer generating in mid air

### ISSUE THREAD

**Issue by igiannakas** [SoftFever/OrcaSlicer#2038]
### OrcaSlicer Version

1.7 Dev

### OS version

OSX

### Printer

X1 Carbon

### How to reproduce

Slice the attached model file. When an interface layer is present supporting a flat surface, the interface layer is generating as if it was a traditional support underneath it, not an organic support.

### Actual results

![Screenshot 2023-09-08 at 16 15 23](https://github.com/SoftFever/OrcaSlicer/assets/59056762/0817cdd9-beff-4289-9984-4be5e47eb8bb)

### Expected results

This should behave more like the tree support - strong as below:
![Screenshot 2023-09-08 at 16 15 38](https://github.com/SoftFever/OrcaSlicer/assets/59056762/970cff91-6ba2-4bf0-b73b-59d1adf270d9)

### Project file & Debug log uploads

[Issue Organic Support.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/12561302/Issue.Organic.Support.3mf.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by Noisyfox** [comment]
That's inevitable unless you disable top support surface. It may look strange but should print just fine (as long as you don't use a very low branch density (say, <10%)).

**Comment by igiannakas** [comment]
> That's inevitable unless you disable top support surface. It may look strange but should print just fine (as long as you don't use a very low branch density, say, <10%).

Understood. It would be great to be able to use an interface though to allow use of support material. Or do you feel it’s not necessary with these?

**Comment by Noisyfox** [comment]
> > That's inevitable unless you disable top support surface. It may look strange but should print just fine (as long as you don't use a very low branch density, say, <10%).
> 
> Understood. It would be great to be able to use an interface though to allow use of support material. Or do you feel it’s not necessary with these?

Your first image looks good to me, those interfaces can be printed just fine in most of the cases.

**Comment by igiannakas** [comment]
> > > That's inevitable unless you disable top support surface. It may look strange but should print just fine (as long as you don't use a very low branch density, say, <10%).
> > 
> > 
> > Understood. It would be great to be able to use an interface though to allow use of support material. Or do you feel it’s not necessary with these?
> 
> Your first image looks good to me, those interfaces can be printed just fine in most of the cases.

Maybe then we should consider defaulting the interface layer to 0 when selecting organic to prevent this from happening if a user selects organic supports? Kind of like when selecting the tree slim ones?

**Comment by Noisyfox** [comment]
> > > > That's inevitable unless you disable top support surface. It may look strange but should print just fine (as long as you don't use a very low branch density, say, <10%).
> > > 
> > > 
> > > Understood. It would be great to be able to use an interface though to allow use of support material. Or do you feel it’s not necessary with these?
> > 
> > 
> > Your first image looks good to me, those interfaces can be printed just fine in most of the cases.
> 
> Maybe then we should consider defaulting the interface layer to 0 when selecting organic to prevent this from happening if a user selects organic supports? Kind of like when selecting the tree slim ones? I’ll give the print a test and see how it goes with the interface layer in place.

It's recommended to have those interface layer for organic support I believe, based on the description of the branch density option.

**Comment by igiannakas** [comment]
Looks like this is a carry over issue from Prusa slicer - just checked and its the same there too.

https://github.com/prusa3d/PrusaSlicer/issues/11155
![Screenshot 2023-09-09 at 12 02 59](https://github.com/SoftFever/OrcaSlicer/assets/59056762/5e196d8d-0120-4357-9927-6b0bc08361f4)

In an ideal world, the support interface should have a check on whether the support interface edge and path changes are anchored over a support branch. If no branch is present, it may be worth generating one at the edge of the support interface and propagating it downwards to the next branch. Lack of that risks spaghetti when the interface is printed. 

For more "organic" objects that is not an issue as there are plenty of branches before the support interface is generated - see below. But for less complex geometries it fails as the branch generation algorithm probably assumes a lesser density is needed without taking into account the anchoring need of the interface.
![Screenshot 2023-09-09 at 12 15 13](https://github.com/SoftFever/OrcaSlicer/assets/59056762/00af6091-73a3-4237-8334-48aaf5e652e4)


But it looks like prusa slicer also has this bug. It is more evident in flat surfaces as the support interface attempts to mirror the top surface but ends up unsupported underneath it.
