### ISSUE TITLE
Show Export G-code button directly

### ISSUE THREAD

**Issue by Brugman** [SoftFever/OrcaSlicer#2041]
When using a non-networked printer, after every slice, we are confronted with a greyed out Print button.
Instead of 1 click to get the g-code, it now takes 3, of which the first is on the relatively tiny dropdown button.

I'd like to have Orca recognize that we do not have a networked printer, and that we just sliced something, so because the most likely next step is storing exporting the g-code manually, that it selects this option automatically.

![2023-09-08-22-42-08](https://github.com/SoftFever/OrcaSlicer/assets/2203813/79507e0e-6e4d-45c4-8430-4eda44064ce7)

**Comment by foreachthing** [comment]
I do like how Prusa does it: when a SD-Card is in, it will "automatically" save to it.

**Comment by niklasb22** [comment]
I just tried to recreate it. For me, if no network configuration is specified for a printer, the G-Code export is displayed by default.

See also "src\slic3r\GUI\MainFrame.cpp" (L. 1075)

**Comment by Brugman** [comment]
Yeah. I think 1-2 days after posting this issue it magically started working as I requested. Could have been implemented quietly.

**Comment by SoftFever** [comment]
Yeah, this had been implemented and I forgot to update it here...

Close this ticket as it is fixed.
