### ISSUE TITLE
Orca sliced files produces weird artifact at times.

### ISSUE THREAD

**Issue by actmoon** [SoftFever/OrcaSlicer#2044]
### OrcaSlicer Version

1.6.6

### OS version

Windows 11

### Printer

Bambu Labs P1S

### How to reproduce

Sliced with same settings on Bambu Slicer. 

No additional steps.

### Actual results

Orca SLicer's sliced files' preview shows artifacts. Which is also present when it is physically printed. Bambu Slicer's preview did not show artifacts for the same model, and settings, and results in a clean model when printed.

### Expected results

Both slicer should produce the same clean model preview & printed results.

### Project file & Debug log uploads

![BambuSlicer](https://github.com/SoftFever/OrcaSlicer/assets/127116723/8b98b5a5-ee72-4b9e-b59e-893bb898cbdc)
![Orca slicer](https://github.com/SoftFever/OrcaSlicer/assets/127116723/4b99a994-5f33-4b2b-a0bb-d2b061949bda)

[Project Files.zip](https://github.com/SoftFever/OrcaSlicer/files/12565260/Project.Files.zip)

### Checklist of files to include

- [ ] Log file
- [x] Project file

**Comment by igiannakas** [comment]
Could you attach the project file?

also please check the below:
1. Are you slicing the model using Arachne?
2. Are you using a single top layer mode?

if so, could you disable single top layer and see what the sliced file looks like?

**Comment by actmoon** [comment]
> Could you attach the project file?
> 
> also please check the below:
> 
> 1. Are you slicing the model using Arachne?
> 2. Are you using a single top layer mode?
> 
> if so, could you disable single top layer and see what the sliced file looks like? This may be related to #2034

Uploaded both project files from Orca & Bambu.

to answer your questions:

1. Yes already on Arachne
2. Nope 4 top layers

**Comment by igiannakas** [comment]
This is user error. you have your seam gap set to 10mm -> the seam will be open for 10mm!

![Screenshot 2023-09-09 at 10 03 31](https://github.com/SoftFever/OrcaSlicer/assets/59056762/368ee55c-60bf-4a67-b049-b986906e0dcf)


Change it to 10% - works great:

![Screenshot 2023-09-09 at 10 03 42](https://github.com/SoftFever/OrcaSlicer/assets/59056762/b863b3ed-93f3-4c6b-a7ce-ab016f92c1c9)

**Comment by actmoon** [comment]
> This is user error. you have your seam gap set to 10mm -> the seam will be open for 10mm!
> 
> ![Screenshot 2023-09-09 at 10 03 31](https://user-images.githubusercontent.com/59056762/266771266-368ee55c-60bf-4a67-b049-b986906e0dcf.jpg)
> 
> Change it to 10% - works great:
> 
> ![Screenshot 2023-09-09 at 10 03 42](https://user-images.githubusercontent.com/59056762/266771267-b863b3ed-93f3-4c6b-a7ce-ab016f92c1c9.jpg)

Ahhh!!

many thanks! Must have changed it accidentally when I was tweaking the seams.
