### ISSUE TITLE
LAN connection/sync device information issue

### ISSUE THREAD

**Issue by Organicactus** [SoftFever/OrcaSlicer#2048]
### OrcaSlicer Version

1.6.6

### OS version

Windows 10

### Printer

Bambu Lab X1C

### How to reproduce

1. Set X1C to LAN mode
2. Connect to printer with Orca Slicer, notice it often takes a long time to connect compared to Bambu Studio
3. Slice and send a print job

### Actual results

In ~90% of attempts, Orca Slicer comes up with Sync device information time out (see screenshot). If it sends print successfully, to reproduce the issue repeat step 3 without a restart. When it comes up with the time out error, it may fix itself in a few seconds and sync successfully without the user intervening, or it can get stuck.

![d01a2781c8ed795c75d72c70f9ab6063e61fa0dc_2_338x500](https://github.com/SoftFever/OrcaSlicer/assets/142729002/58dff48c-533a-405d-bfb8-c5c5957d5b70)

### Expected results

Robust and fast connection like Bambu Studio

### Project file & Debug log uploads

[Project file.zip](https://github.com/SoftFever/OrcaSlicer/files/12566201/Project.file.zip)
[log.zip](https://github.com/SoftFever/OrcaSlicer/files/12566203/log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by demosthenes384322** [comment]
Still broken in 2.0.0
