### ISSUE TITLE
LAN Liveview does not work

### ISSUE THREAD

**Issue by Organicactus** [SoftFever/OrcaSlicer#2049]
### OrcaSlicer Version

1.6.6

### OS version

Windows 10

### Printer

Bambu Lab X1C

### How to reproduce

1. Set X1C to LAN mode and enable Liveview
2. Connect to X1C via Orca Slicer
3. Go to device tab and press the Play button, attempting to turn on camera

### Actual results

LAN connection fails, camera inaccessible.

![LAN failed](https://github.com/SoftFever/OrcaSlicer/assets/142729002/0bff5b3a-5e0b-47a2-b931-d948745e5b26)

### Expected results

Liveview functionality like in Bambu Studio, camera should be accessible in LAN mode when Liveview is enabled

### Project file & Debug log uploads

[log.zip](https://github.com/SoftFever/OrcaSlicer/files/12566220/log.zip)
[Project file.zip](https://github.com/SoftFever/OrcaSlicer/files/12566221/Project.file.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by Alex-Schaefer** [comment]
Try beta 1.7.0, had the same problem with 1.6.6, it's now working.
