### ISSUE TITLE
Perimeter bridge detection inconsistent and wrong between Arachne and Classic slicing modes.

### ISSUE THREAD

**Issue by lhndo** [SoftFever/OrcaSlicer#2057]
### OrcaSlicer Version

1.6.6

### OS version

Windows

### Printer

Custom

### How to reproduce

Set bridge flow to 0.1 to be able to spot them
Slice with both Arachne and Classic and observe perimeter behaviour.

### Actual results

Arachne:
![2023_09_10_2987_orca-slicer](https://github.com/SoftFever/OrcaSlicer/assets/42773937/bce177a6-ac99-41a0-a94f-877106961c4d)

Classic:
![2023_09_10_2988_orca-slicer](https://github.com/SoftFever/OrcaSlicer/assets/42773937/76c708bc-84ab-47a0-b707-729d6c3b475d)

Arachne:
![2023_09_10_2990_orca-slicer](https://github.com/SoftFever/OrcaSlicer/assets/42773937/bafea1ba-adb6-46c5-a74f-1d3ceab8d4bd)

Classic:
![2023_09_10_2989_orca-slicer](https://github.com/SoftFever/OrcaSlicer/assets/42773937/ea7abb91-0629-4b44-8500-63b18487c042)

### Expected results

Two point suspended perimeters with 0 overlap should be drawn as bridges in all cases.
Overhangs that have a slight overlap should be drawn as overhang perimeters.

Currently both modes are wrong. Classic detects overhangs as bridges, while Arachne doesn't detect bridges in the benchy window frame. Also Classic ads gap fill to bridged sections.

### Project file & Debug log uploads

[3DBenchy bridges.zip](https://github.com/SoftFever/OrcaSlicer/files/12568177/3DBenchy.bridges.zip)

### Checklist of files to include

- [x] Log file
- [X] Project file

**Comment by blownupp** [comment]
I'm still seeing this issue in 1.8.0:

Arachne:

![image](https://github.com/SoftFever/OrcaSlicer/assets/13923459/89bc5445-2ac9-400d-bdbf-becb384ba1e6)

Classic:

![image](https://github.com/SoftFever/OrcaSlicer/assets/13923459/e9b81ad7-7a9d-41b4-a5a0-e9f40c871efb)
