### ISSUE TITLE
Organic support gets confused by adaptive layer height

### ISSUE THREAD

**Issue by szabczy** [SoftFever/OrcaSlicer#2062]
### OrcaSlicer Version

1.7 Beta

### OS version

Windows 10

### Additional system information

CPU: 11th Gen Intel(R) Core(TM) i5-11600 
RAM: 32GB
GPU: RTX 3060

### Printer

Creality Ender 5

### How to reproduce

1. Enable Adaptive layer height
2. Support type Tree(auto), style Organic
3. Slice plate

### Actual results

![image](https://github.com/SoftFever/OrcaSlicer/assets/13044346/b87610a8-3d2e-47ba-a3cb-199d1f1520c4)
![image](https://github.com/SoftFever/OrcaSlicer/assets/13044346/e215d9fa-5136-4075-b8a5-117808fc7759)
![image](https://github.com/SoftFever/OrcaSlicer/assets/13044346/6225db76-186a-4e4e-ab69-fb54725d6ed2)

### Expected results

The organic support should support the problematic areas of the model.

### Project file & Debug log uploads

No project file

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by jeremytodd1** [comment]
Just to get this out there, PrusaSlicer's Organic supports also do not work with adaptive layer height.

![organic](https://github.com/SoftFever/OrcaSlicer/assets/6227771/2d631dea-8174-4bd7-b850-d41c07df3f54)

**Comment by szabczy** [comment]
Then I guess it's not a bug.
It would be nice to have, though.
