### ISSUE TITLE
Windows Defender reports virus and blocks the EXE. (1.7.0 beta) (False alarm)

### ISSUE THREAD

**Issue by DokuKaefer** [SoftFever/OrcaSlicer#2071]
### OrcaSlicer Version

1.7.0 beta

### OS version

Windows 11 22H2 Build 22623.1928)

### Printer

Bambu Lab X1C

### How to reproduce

Download the OrcaSlicer_Windows_Installer_1.7.0-beta.exe

### Actual results

Windows defender reports the exe as a threat and blocks it.
I think this is a false alarm.

![image](https://github.com/SoftFever/OrcaSlicer/assets/11537653/2e57380f-34d5-468d-92d8-20315df491a7)

### Expected results

No blocking of the exe file.

### Project file & Debug log uploads

no project

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by SoftFever** [comment]
I scanned it with VirusTotal, it's all green
here is the result: https://www.virustotal.com/gui/file/186fed7bca658d96b8091d37cf6d043a1e8251f8daf746289309330a01d07776

No idea why Windows defender suddenly has issue with the NSIS installer, it's the same installer script as previous release and is built in GitHub runner 😵‍💫

**Comment by capsel22** [comment]
same here
![image](https://github.com/SoftFever/OrcaSlicer/assets/38831192/805e7c45-5578-4ba0-a019-167c5527bdb5)
![image](https://github.com/SoftFever/OrcaSlicer/assets/38831192/8147b834-0660-4451-bdfd-083e34d4b6a5)

**Comment by Misunderstood-Wookiee** [comment]
> To me, this iimplies a strong suggestion of a false positive The Wacatac!ml/Wacapew!ml is a machine learning based detection, which is an AI based heuristics and behavioural analysis method in this case. They sound scary, but they're generic names. The detection on MaxSecure is known as a detection that can be false positive due to heuristic behavioural analysis and conservative behaviour The detection from Bkav Pro is an AI based detection, which is also heuristic behavioural analysis.
> 
> This is likely the case because the NSIS installer is so widely used, and could as such be used in a popular malware package. The AI's and machine learning algorithms simply learnt that the NSIS installer and some malware package(s) came bundled together.

Historically the program has been safe, I am inclined to agree with you, but also historically the program has not flagged Windows Defender nor Virus Total, I would err on the side of caution on this one until the dev can do a more meaningful analysis on their end.

**Comment by SoftFever** [comment]
I will see if there is anything to upgrade for the NSIS.

Otherwise I clueless what else I can do.
The whole installer package is done by the same script as 1.6.6 on GitHub action runner, which is very unlikly contain virus...

**Comment by DokuKaefer** [comment]
In this thread there are some options you can do.
But the good options are very expensive. 😬

https://stackoverflow.com/questions/48946680/how-to-avoid-the-windows-defender-smartscreen-prevented-an-unrecognized-app-fro

**Comment by HumbleDeer** [comment]
I currently get no flags from Defender either; the definitions I have installed are from yesterday.

**Comment by Misunderstood-Wookiee** [comment]
Not sure about others but my platform is Windows 11 insider prev build. Honestly, it is probably nothing.  
That said, nothing changed and here we are, though I have heard it has given false pos in the past.

**Comment by l8nite** [comment]
Google chrome blocked this as well: 
![image](https://github.com/SoftFever/OrcaSlicer/assets/1711530/1779a642-1660-49ad-998e-6910f19bdf08)

**Comment by l8nite** [comment]
For what it's worth the latest 1.7.0 release seems to have resolved this issue - this issue can probably be closed out.

**Comment by scotty6435** [comment]
I've got the exact same issue with 1.8.0-beta on Windows 11:
![image](https://github.com/SoftFever/OrcaSlicer/assets/1446762/b4606c51-4099-4165-b745-3b4203eb5cce)

**Comment by jaegerschnitzel** [comment]
Same for me with all 1.8.x versions.

**Comment by SimonThompson1965** [comment]
Me too, same issue using either the exe or the portable zip file
![image](https://github.com/SoftFever/OrcaSlicer/assets/96429238/4066afc4-37c6-47b6-9264-2dd2b0dea110)

**Comment by Boergen** [comment]
Issue is also still present in the current stable and 2.0.0 nightly builds.
