### ISSUE TITLE
Question about deleted lines related to "Tip of the day"

### ISSUE THREAD

**Issue by AndylgTom** [SoftFever/OrcaSlicer#2072]
### OrcaSlicer Version

OrcaSlicer V1.7.0 Beta

### OS version

win10

In OrcaSlicer V1.7.0 Beta, the translation of lines related to "Tip of the day" has been removed (the lines are not in *.pot and translated *.po). Where did they go, why did they remove these lines?
Thx.

**Comment by SoftFever** [comment]
Phew, they deleted accidently.
Fixed!
