### ISSUE TITLE
Avoid printed parts

### ISSUE THREAD

**Issue by freiser77** [SoftFever/OrcaSlicer#2073]
When I print objects needing tree support, often times the tree support is knocked over by the nozzle, because it was already printed and the nozzle moves over it to another part to print.
Because of stringing I don't use z-hop.

It would be fine, if I could activate "Avoid printed parts" to tell the slicer, that the travel moves should move around already printed parts.

**Which printers will be beneficial to this feature**
All

**Comment by TexZeTech** [comment]
have you tried "Avoid Crossing Walls" ?
![image](https://github.com/SoftFever/OrcaSlicer/assets/7254540/a61be3fc-bfcc-4278-ae46-dc27da64693d)

**Comment by freiser77** [comment]
Yes, I did. But it was of no use. https://github.com/prusa3d/PrusaSlicer/issues/9640 recognizes this, too.

**Comment by Santars2022** [comment]
Same problem:

![image](https://github.com/SoftFever/OrcaSlicer/assets/110886710/f3614d24-5a5a-4ed8-9fdd-6bdab9a92048)


No one reacts, will go to cura. There is more optimized avoiding support when travelling

**Comment by TexZeTech** [comment]
Have you tried to Upload a model, log file, the system you are running and the version of Orcaslicer you are using?

Also, have you tried using settings that lift the print head slightly on move like was suggested in the post above yours?

![image](https://github.com/SoftFever/OrcaSlicer/assets/7254540/7a39ef22-b62e-4e30-b8b9-b2b6e1b09b40)
The devs over at Prusa are working on making the pathing so it is getting worked on.

If you think you can fix it better/faster do a pull request with your proposed fix you would be welcome to do so.

> No one reacts, will go to cura. There is more optimized avoiding support when travelling

Also, there are currently 636 issues for this project so let's say 50% of that is just bugs, that is still 318 posts to read and go through with varying degrees of severity & every time there is a change the dev team needs to make sure it doesn't regress any other features. Could you imagine clicking "I read this" 636 times?

Shame on you for your entitlement. 

![image](https://github.com/SoftFever/OrcaSlicer/assets/7254540/ff60e24c-c65a-4026-a8cc-745eb1e714af)

You walk into a bar you don't frequent, blink once and say "This bar sucks I will never come here again. I'm going to other bar!!!"

I doubt you have supported any open-source project in your life and you won't be missed. 

You are free to prove me wrong though, I'll wait.

**Comment by davids91** [comment]
Dear Dev team! Despite the original tone of the isue, this is indeed something that is a missed feature. 
What do you need to prioritize/plan this into a future release?
