### ISSUE TITLE
1.7.0-beta Multi-Material ( SEMM) slicer bug

### ISSUE THREAD

**Issue by Aleishus** [SoftFever/OrcaSlicer#2077]
### OrcaSlicer Version

1.7.0 beta

### OS version

macos

### Printer

Voron2.4

### How to reproduce

![image](https://github.com/SoftFever/OrcaSlicer/assets/3436724/2af2841a-a0c6-4ab4-8969-4d8fb9cbd9ea)
<img width="392" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/3436724/f4c6aba6-68a9-4063-aca6-715acb62eeb8">

### Actual results

show above

### Expected results

show above

### Project file & Debug log uploads
[3DBenchy.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/12575691/3DBenchy.3mf.zip)

show above

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by SoftFever** [comment]
Thanks @Aleishus 
This is not a bug actually.

It's the final ramming action after finishing the print.
While it looks strange, it's actually not printing, it's just pulling the filament out
