### ISSUE TITLE
"QoL thinner sliders" is not QoL for all

### ISSUE THREAD

**Issue by avxmw** [SoftFever/OrcaSlicer#2079]
### OrcaSlicer Version

1.7.0 beta

### OS version

Linux AppImage

### Printer

ALL

### How to reproduce

1. install beta
2. slice

### Actual results

What is called a Quality of Life improvement is actually detrimental in my case as it is harder to see and to click/drag.

### Expected results

Actually be QoL improving by giving people an option to set as needed.

### Project file & Debug log uploads

-

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by capsel22** [comment]
agreed. Let us set thin of fat slider in view menu

**Comment by foreachthing** [comment]
Same here! On 4k monitors, it's just 6-7 pixel in height/width. Not QoL at all 😦

**Comment by SoftFever** [comment]
Dman, I forgot the DPI scale is a thing.

Are you all running on 4K motinor?

**Comment by SoftFever** [comment]
Fixed.
