### ISSUE TITLE
Layer following a bridge is not oriented optimally

### ISSUE THREAD

**Issue by samwiseg0** [SoftFever/OrcaSlicer#2081]
### OrcaSlicer Version

1.7.0-beta

### OS version

MacOS 13.5.1 (22G90)

### Additional system information

N/A

### Printer

Voron 2.4

### How to reproduce

1. Add primitive (Voron Cube)
2. Slice with walls greater than 1
3. Observe that the preceding layer after a bridge follows the same orientation as the bridge itself. Layer 74-75 using .2mm layer heights. 

### Actual results

Bridge layer
![bridge_layer](https://github.com/SoftFever/OrcaSlicer/assets/2241731/1f5ff3bf-d185-47a4-9600-17ed17284dd0)

 The preceding layer after a bridge follows the same orientation as the bridge itself. 
![2_wall_undesired](https://github.com/SoftFever/OrcaSlicer/assets/2241731/9a611e21-f844-4e45-89df-a4eb1639b14e)

If you reduce walls to 1 then you get the desired result. 
![one_wall_desired](https://github.com/SoftFever/OrcaSlicer/assets/2241731/60104ce7-a2f2-4bb3-a3ff-9f50f348a274)

I have also tried to use classic vs Arcane and it has the same result.

What is produced on the print itself. Since the layer above the bridge is in the same orientation and it is not considered a bridge. The extrusion speed, cooling etc is not applied. Which can cause undesired results if your bridge density is not very high (>80%). 
![2023-09-11-17-18-54-337](https://github.com/SoftFever/OrcaSlicer/assets/2241731/924415fa-5b87-492b-a5d7-a962a2d2e1dc)

### Expected results

The layer above the bridge uses an offset angle from the bridge or uses the infill angle.

As stated above using only a single wall gives you the desired results.

This is an example from SuperSlicer.
![ss_desired](https://github.com/SoftFever/OrcaSlicer/assets/2241731/1e2d7a42-13c1-4ad6-a976-9389dbb8ecb8)

What is produced printed with SuperSlicer.
![2023-09-11-17-18-44-916](https://github.com/SoftFever/OrcaSlicer/assets/2241731/1999d8e7-b2e6-4ad1-a39d-19e94b90f8ac)

I apologize if I missed a setting somewhere that would produce the desired result. I have tried a few things and could not get bridges to print as well as in SuperSlicer. 

### Project file & Debug log uploads

[Voron_Design_Cube.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/12580552/Voron_Design_Cube.3mf.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by igiannakas** [comment]
Untick detect narrow internal solid infill option and it should print properly.

**Comment by igiannakas** [comment]
![Screenshot 2023-09-13 at 23 38 49](https://github.com/SoftFever/OrcaSlicer/assets/59056762/a68dc123-5b3f-4420-964f-438b055dfee6)

**Comment by samwiseg0** [comment]
@igiannakas Thank you for pointing that out. I have no idea how I missed that checkbox! 

Thanks again!

**Comment by samwiseg0** [comment]
p.s I believe unchecked should be the default? For the most part I cannot see a reason that it should be on by default?

**Comment by igiannakas** [comment]
> p.s I believe unchecked should be the default? For the most part I cannot see a reason that it should be on by default?

Speed… concentric infill is faster to print in small areas. But it will result in a slightly worse bridge. I’ve disabled it on my profiles btw

**Comment by igiannakas** [comment]
I've published a PR to Softfever to make the logic behind setting concentric infill less sensitive so more bridges are bridged properly vs. the concentric infill being used. Hopefully this gets published so we can use both a correct bridge behaviour and the faster concentric infill in areas where small infill is present.
