### ISSUE TITLE
Ankermake printers do not appear

### ISSUE THREAD

**Issue by Matrekus** [SoftFever/OrcaSlicer#2083]
### OrcaSlicer Version

1.7.0

### OS version

WIN 11

### Printer

Ankermake M5C&M5

### How to reproduce

Select one of the Ankermake printers when start the setup assistant or in Orca afterwards. 

### Actual results

The printer does not appear in the list and cant be selected.

### Expected results

Printer should be selectable in the printer dropdown.

### Project file & Debug log uploads

If you copy the profiles from bambu studio it works like it should.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by UncleJessy** [comment]
Confirming this is also an issue with Mac OS Orca 1.7.0

<img width="1630" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/73964437/cbf46f62-a1c0-4fa3-88c1-775d467e0e13">

![Screenshot 2023-10-09 at 9 33 41 PM](https://github.com/SoftFever/OrcaSlicer/assets/73964437/33eecbc5-cbb9-4f11-9003-df3e76a145bd)

**Comment by eliezedeck** [comment]
I've had this problem many times, even with the latest 1.8.0-beta1.

For other printers, it seems to appear immediately. For AnkerMake printers, you'll need to select the printer, then close Orca. Then open again, now it will appear.
