### ISSUE TITLE
Extruder Clearance is Too Large,  Causes Toolhead Crashing

### ISSUE THREAD

**Issue by qeggs** [SoftFever/OrcaSlicer#2084]
### OrcaSlicer Version

1.6.4 beta3

### OS version

Windows 11

### Additional system information

Not Applicable

### Printer

BBL X1C

### How to reproduce

The default value for Extruder Clearance "Radius" should be increased from 57mm to 68mm.
The default value for Extruder Clearance "Height to Rod" should be decreased from 36mm (default) to 35.2mm. 
These must be corrected to avoid toolhead crashes when sequential printing "by object".
Apply these new defaults to all four nozzle sizes for the BBL X1C.

![image](https://github.com/SoftFever/OrcaSlicer/assets/52592447/8720ad02-6ff7-4b60-913c-81eaa3944a47)

Steps to Reproduce:
1. Create two primitive objects. 
2. Scale them to be 36mm tall.
3. Place them side by side in the lateral direction, 60 mm apart.
4. Set print order to print right object first, then left object.
5. DO NOT DO THIS; IT WILL CAUSE A TOOLHEAD CRASH
6. Slice and print part (NOTE no warnings generated)
7. First part (the one on the right) will print without issue.
8. The first few layers of the second print will cause the lower lateral rod in the machine to crash into the top of the part on the right which has already been printed.
9. The lidar module will crash into the part on the right which has already been printed.

### Actual results

Toolhead crashes! If you're lucky, the part pops off the build plate and no damage is caused to the toolhead.

### Expected results

Toolhead should come close to contacting adjacent parts but not make contact.

### Project file & Debug log uploads

[Extruder Clearance Demo.zip](https://github.com/SoftFever/OrcaSlicer/files/12582058/Extruder.Clearance.Demo.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by DRWAK** [comment]
Unfortunately this issue is still there thus requiring manual adjustment to avoid tool head collision at by object pints. 
Any chance to get it sorted ? Thanks.
