### ISSUE TITLE
Linux -- Process - Objects - Text black.

### ISSUE THREAD

**Issue by TexZeTech** [SoftFever/OrcaSlicer#2086]
### OrcaSlicer Version

1.6.6 and 1.7.0 beta

### OS version

6.1.51-1-MANJARO (64-bit)

### Additional system information

Operating System: Manjaro Linux 
KDE Plasma Version: 5.27.7
KDE Frameworks Version: 5.109.0
Qt Version: 5.15.10
Kernel Version: 6.1.51-1-MANJARO (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-3770K CPU @ 3.50GHz
Memory: 15.6 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1080/PCIe/SSE2

### Printer

Custom profile. #Customized Robo3dR1+

### How to reproduce

1. Make sure the system is in dark mode
2. have `"dark_color_mode": "1",` in the OrcaSlicer.conf  (shouldn't matter)
3. Select printer profile
4. Select filaments
5. Have Advanced enabled (shouldn't matter)
6. Select Objects button

### Actual results

![image](https://github.com/SoftFever/OrcaSlicer/assets/7254540/0d7aa213-ec09-4886-bb9b-1d2f4c2b730d)

![image](https://github.com/SoftFever/OrcaSlicer/assets/7254540/3e43c0b9-3b68-4632-8e54-dc7b8cc49edb)

### Expected results

Readable text.

### Project file & Debug log uploads

[OrcaCube.zip](https://github.com/SoftFever/OrcaSlicer/files/12582858/OrcaCube.zip)

[debug_Mon_Sep_11_23_55_52_27964.log.0.log](https://github.com/SoftFever/OrcaSlicer/files/12582864/debug_Mon_Sep_11_23_55_52_27964.log.0.log)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by TexZeTech** [comment]
Also present in the Bed shape dialog

![image](https://github.com/SoftFever/OrcaSlicer/assets/7254540/8bb39f19-f48e-4c0a-ab28-8ec45c1b8fc9)

Extruder tab -> Extruder offset

![image](https://github.com/SoftFever/OrcaSlicer/assets/7254540/5e41cdd6-ed89-4483-8d7f-536425899439)

**Comment by Nosnahc** [comment]
+1

**Comment by TexZeTech** [comment]
Also in the network window
![image](https://github.com/SoftFever/OrcaSlicer/assets/7254540/c20cc8e4-4e56-40c6-9d33-449eb261697c)

**Comment by mdziekon** [comment]
I've experienced the same problem, and since so far there was no response from the maintainers, also decided to look myself into the issue.

So far I've been able to determine the following things:
- Changing back & forth between system's dark mode preference seems to "fix" some of the labels. When previously they would be black on dark background, after changing from dark, to light, to dark again, the label is now white-ish, as one would expect.
- Forcefully setting foreground color in some places (eg. here https://github.com/SoftFever/OrcaSlicer/blob/8e700818796c12b7c66fe7d4443956d70a68410e/src/slic3r/GUI/GUI_ObjectList.cpp#L93) seems to fix the problem
  - However, I'm not sure if this is the right approach. Looking at PrusaSlicer's code in corresponding places does not indicate any need for such things.

@SoftFever do you have any thoughts about the second point from my findings? If you think this is an acceptable approach, I can create a PR with such changes, for any place I can find where it fixes the dark mode.

**Comment by SoftFever** [comment]
> I've experienced the same problem, and since so far there was no response from the maintainers, also decided to look myself into the issue.
> 
> So far I've been able to determine the following things:
> 
> * Changing back & forth between system's dark mode preference seems to "fix" some of the labels. When previously they would be black on dark background, after changing from dark, to light, to dark again, the label is now white-ish, as one would expect.
> * Forcefully setting foreground color in some places (eg. here https://github.com/SoftFever/OrcaSlicer/blob/8e700818796c12b7c66fe7d4443956d70a68410e/src/slic3r/GUI/GUI_ObjectList.cpp#L93
>   ) seems to fix the problem
>   
>   * However, I'm not sure if this is the right approach. Looking at PrusaSlicer's code in corresponding places does not indicate any need for such things.
>   * Also, to be clear, the mentioned place is just a marker. It still needs something like `this->SetForegroundColor()` to actually set the color of the font.
> 
> @SoftFever do you have any thoughts about the second point from my findings? If you think this is an acceptable approach, I can create a PR with such changes, for any place I can find where it fixes the dark mode.

Hi @mdziekon 
Thanks for investigating the issue.
I don't have clues either unfortunately.
I'm open to using workaround solutions. 
Given that this is a Linux-specific issue, I'd suggest wrapping the codes with #ifdef __linux__  to minimise the risk

**Comment by mdziekon** [comment]
@TexZeTech @guestisp @GAZ082
Since all of you reported similar issues, and you all have different distros in use (I'm personally on ancient Ubuntu 20.04 with Gnome 3.36.8, X11, yaru-dark theme), would anyone of you care to compile my PR & test my partial fix? It does fix the issue for me, but it would probably be nice to confirm that it does so for other people as well.

**Comment by SoftFever** [comment]
I have kicked off the CICD build if that helps.

**Comment by guestisp** [comment]
Trying the automated build on Ubuntu. there is an issue with the initial checkbox but everything else looks fine to me, i'm able to see the texts. (not sure at 100% because i've never used this slicer before, due to missing texts and labels)


![image](https://github.com/SoftFever/OrcaSlicer/assets/3944655/7a804b34-9960-41c1-911e-22c130c3c75d)

**Comment by guestisp** [comment]
Uhm, some issues are still present here
![image](https://github.com/SoftFever/OrcaSlicer/assets/3944655/b2e4f8dd-5a3e-4871-ae35-11e1e8f5d0e8)

**Comment by mdziekon** [comment]
@guestisp as per pull request's title, my recent change fixes **only** the object's list, and nothing else. I couldn't find a quick solution for other places, so I'm fixing (or at least, trying) one place at a time.

**Comment by guestisp** [comment]
Sorry i didn't read the title carefully.

Object list is working properly, in 1.7 was black on dark grey, now is white on dark grey as expected

**Comment by GAZ082** [comment]
@mdziekon where is the build with this patch, couldnt find it.

Thanks!

**Comment by mdziekon** [comment]
@GAZ082  I think this should be it: https://github.com/SoftFever/OrcaSlicer/actions/runs/6438345400?pr=2346

**Comment by guestisp** [comment]
yes, that

**Comment by TexZeTech** [comment]
> @GAZ082 I think this should be it: https://github.com/SoftFever/OrcaSlicer/actions/runs/6438345400?pr=2346

![image](https://github.com/SoftFever/OrcaSlicer/assets/7254540/01cbcf68-b771-46be-aa0b-572f06db690f)

Just running that appimage as is seems to fix the one thing, it doesn't seem to fix the other dialogs.

**Comment by TexZeTech** [comment]
I should probably also rename this to "Linux -- darkmode ux issues" instead IDK.

**Comment by GAZ082** [comment]
Yes, this fixed the objects dialog, partially.

![image](https://github.com/SoftFever/OrcaSlicer/assets/100194/4ee47434-99f9-4a8b-9c19-d02a08e48ae1)

**Comment by kesor** [comment]
This issue makes OrcaSlicer pretty unusable in Linux. It is still possible to override the dark mode in GTK to be light-mode just for OrcaSlicer by setting the `GTK_THEME=:light` environment variable.

For example, using a script like this -

```shell
#!/bin/sh

export GTK_THEME=:light
exec OrcaSlicer
```

**Comment by guestisp** [comment]
As this is a semi-blocking bug on Linux, why not forcing the light theme directly in the app image ? Better a white working theme than dark but unusable

**Comment by TexZeTech** [comment]
As of [OrcaSlicer V1.8.0 Beta Release ](https://github.com/SoftFever/OrcaSlicer/releases/tag/v1.8.0-beta) the object text is no longer black, but it still has issues with the text on the tabs. 

![image](https://github.com/SoftFever/OrcaSlicer/assets/7254540/54667df9-363b-433e-8a3a-31d269a30964)

In FillamentSettings -> Multimaterial -> Ramming customization
we have text that is black on black (or gray on gray?)
![image](https://github.com/SoftFever/OrcaSlicer/assets/7254540/cf86dbfa-00a6-47ab-955a-1c59eb3b79f9)

In the Compare presets dialog 

There is a checkbox.... I have no idea what it says.

![image](https://github.com/SoftFever/OrcaSlicer/assets/7254540/b8867fc7-40ca-4e88-bc37-2bda86027c86)

Filament Color dropper is black on grey (this is not a big deal)

![image](https://github.com/SoftFever/OrcaSlicer/assets/7254540/d8aa2b25-4a46-463c-8929-8193fecc085a)

Flushing Volumes has grey on grey as well.

![image](https://github.com/SoftFever/OrcaSlicer/assets/7254540/91552e17-412d-4832-8a4a-404e6d7c7aa3)

--Printer Settings--

Basic information -> Best object position 

![image](https://github.com/SoftFever/OrcaSlicer/assets/7254540/be4fe271-fb80-4f01-b1a1-a34d4424979a)

Basic information -> Printable Area -> Set dialog

![image](https://github.com/SoftFever/OrcaSlicer/assets/7254540/e087f0c6-60f5-445b-939c-30f00588afc5)

Extruder -> Extruder Offset

![image](https://github.com/SoftFever/OrcaSlicer/assets/7254540/1d52e977-edfe-4d23-a813-bdec99cbc3a8)

--Network--

Text stating what the input fields are for is unreadable, input for most is usable with the exception of the profile at the top.
![image](https://github.com/SoftFever/OrcaSlicer/assets/7254540/d32b3ad9-64e9-4fec-acfe-173e24d69579)

Searching for the network is also in need of some TLC.

![image](https://github.com/SoftFever/OrcaSlicer/assets/7254540/add4920a-2754-4cfc-85a7-e477086bc4b8)

--Save/Discard changes--

![image](https://github.com/SoftFever/OrcaSlicer/assets/7254540/ac879e4a-005e-4e1c-b4ff-20c924904d90)



This technically fixes the "Object - Text black" so if a dev wants me to close this for that bug fix and open a new one for the other things that need to be fixed I will.

Thank you again for the work.

**Comment by TexZeTech** [comment]
> As this is a semi-blocking bug on Linux, why not forcing the light theme directly in the app image ? Better a white working theme than dark but unusable

You're correct but I really dislike light themes. If it was truly unusable I would go to the effort of swapping it to light mode for just this application.

**Comment by guestisp** [comment]
i hate light themes too but Orca is unusable on Ubuntu
so, why not forcing a light theme (until a fix) or why not adding a setting to change the theme from the app?

**Comment by TexZeTech** [comment]
Confirmed that it's broken the exact same way on Ubuntu 22.04.03 as my system with dark mode.

**Comment by TexZeTech** [comment]
This all seems to be fixed on the current release on my laptop so I think something is fubar with my tower install.
