### ISSUE TITLE
Linux -- Printer -- Invisable manual button?

### ISSUE THREAD

**Issue by TexZeTech** [SoftFever/OrcaSlicer#2087]
### OrcaSlicer Version

1.7.0 beta & probably 1.6.6?

### OS version

6.1.51-1-MANJARO (64-bit)

### Additional system information

Operating System: Manjaro Linux 
KDE Plasma Version: 5.27.7
KDE Frameworks Version: 5.109.0
Qt Version: 5.15.10
Kernel Version: 6.1.51-1-MANJARO (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-3770K CPU @ 3.50GHz
Memory: 15.6 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1080/PCIe/SSE2

### Printer

Custom profile. #Customized Robo3dR1+

### How to reproduce

1. Move mouse to the left of the plate selection.
2. Click.
3. ?????
4. profit!

### Actual results

![image](https://github.com/SoftFever/OrcaSlicer/assets/7254540/004ddea5-a01b-485f-8cca-bc419d1b93be)
+ click and then opens to https://wiki.bambulab.com/en/x1/manual/compatibility-and-parameter-settings-of-filaments

### Expected results

Something in that position to show its a link to an online manual about parameters and the like?

### Project file & Debug log uploads

[debug_Tue_Sep_12_00_04_46_30172.log.0.log](https://github.com/SoftFever/OrcaSlicer/files/12582951/debug_Tue_Sep_12_00_04_46_30172.log.0.log)

[OrcaCube.zip](https://github.com/SoftFever/OrcaSlicer/files/12582963/OrcaCube.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by Nosnahc** [comment]
+1

**Comment by TexZeTech** [comment]
I just checked on my laptop running Manjaro & it isn't an issue anymore.
