### ISSUE TITLE
No Thumbnail and no file stats

### ISSUE THREAD

**Issue by charles2690** [SoftFever/OrcaSlicer#2093]
### OrcaSlicer Version

1.7.0 - beta

### OS version

windows 10

### Printer

Voron 2.4 on Klipper with Mainsail 2.7.1

### How to reproduce

![Capture](https://github.com/SoftFever/OrcaSlicer/assets/36705820/699a31ae-ca43-401f-ae71-c1778dde2fe0)

There are no file stats appart from the object height and the thumbnails aren't showing up.

### Actual results

No data on the gcode file page

### Expected results

Both Superslicer and Prusaslicer are working as expected but I can't get this slicer to send the file data to mainsail.
happens also on  1.6.

### Project file & Debug log uploads

[Stand_Voron 2.4 300 0.4 nozzle-_6.20817g_ABS_22m7s (1).zip](https://github.com/SoftFever/OrcaSlicer/files/12588041/Stand_Voron.2.4.300.0.4.nozzle-_6.20817g_ABS_22m7s.1.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by samwiseg0** [comment]
This maybe an issue on your system as I uploaded your gcode file and it seems to work just fine. 
![2023-09-12_11-24](https://github.com/SoftFever/OrcaSlicer/assets/2241731/6ac6755a-02f5-4a49-a0e3-53900b82a584)
![2023-09-12_11-22](https://github.com/SoftFever/OrcaSlicer/assets/2241731/aef4aa55-779d-4a31-9c01-606a156bc165)

**Comment by TexZeTech** [comment]
I haven't had any changes to my thumbnail upload.

![image](https://github.com/SoftFever/OrcaSlicer/assets/7254540/d58be8b3-c247-4423-bbb0-59672126b536)


@charles2690 have you set the G-code thumbnail size?
![image](https://github.com/SoftFever/OrcaSlicer/assets/7254540/f78eff90-6f1c-4526-83c3-58816df32921)

I also found a Reddit post for a setup like this 

https://www.reddit.com/r/crealityk1/comments/15dlhve/need_help_regarding_the_thumbnail_situation_in/ju2va8j/

![image](https://github.com/SoftFever/OrcaSlicer/assets/7254540/bef58ae3-2718-42da-964b-96dd0b18e338)

**Comment by charles2690** [comment]
Even with everything up to date it’s not working. However, I have applied the fix I found on issue #840 and everything works fine now.
