### ISSUE TITLE
Extra Infill Wall Count from Cura

### ISSUE THREAD

**Issue by steezyprintz** [SoftFever/OrcaSlicer#21]
Would be most excellent if you could add Extra Infill Wall Count from Cura!

I find it very useful to be able to set prints to have two slow outer walls then have one or more infill walls that are printed in that order. I find it means the sharp corner details and tolerances are better when you need many walls for strength etc. 

![infill walls](https://user-images.githubusercontent.com/113864702/206937224-9d9f71c0-2b07-4b40-9918-ee62fb42d060.JPG)

**Comment by SoftFever** [comment]
It's interesting.

Will add a story to the backlog.

-SoftFever

**Comment by knw257** [comment]
I second this request
