### ISSUE TITLE
X1C Camera Error - BambuSource.dll

### ISSUE THREAD

**Issue by xenon2008** [SoftFever/OrcaSlicer#2104]
### OrcaSlicer Version

1.7.0 beta & 1.6.6

### OS version

Windows 10 Pro x64

### Printer

Bambulab X1C Combo

### How to reproduce

I downloaded OrcaSlicer and added my brandnew X1C Combo Printer.
I installed the Bambu Network Plugin und logged in into my BambuLab Account
Then i switch to Device Tab and want to try the Camera Feed.

I got an Messaged that the BambzSource has not correctly registered... => i Clicked yes and got an Error again.
(The folder path is correct and the files are there too)
also tried to Download Bambustudio & copied the files from them to my OrcaSlicer Plugins Folder - same Result
Also with the latest 1.6.6 stable version

Here some Screenshots:
![Error 1](https://github.com/SoftFever/OrcaSlicer/assets/12835450/39c344b3-d2a7-4b2d-b5ad-682dbaf2a3c3)
![Error2](https://github.com/SoftFever/OrcaSlicer/assets/12835450/cc24feed-db17-4098-9f46-16f3daeb249b)

Could somebody help me?
Its my first Bambulab Printer and did not one testprint with it  =) 

Kindly Regards
Xenon

### Actual results

See the two Error Screenshots above

### Expected results

I thought i could see the Camera Stream/Feed ;)

### Project file & Debug log uploads

Files in Plugin Folder
![image](https://github.com/SoftFever/OrcaSlicer/assets/12835450/514ece6e-5240-4912-816a-0da08e4658a6)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by igiannakas** [comment]
Download and install the official slicer - maybe there is a conflict somewhere. Then retry installing orca.

**Comment by xenon2008** [comment]
yes that looks good. 
I dont unterstand why., because i already tried to copy the original Files from BambuStudio to OrcaSlicer....
Only difference now is, that the registered DLL in Windows links to "C:\Users\USERNAME\Appdata\Local\BambuStudio" and not to the FilePath of OrcaSlicer, but it works. => So why not :D
