### ISSUE TITLE
Don't Support Bridges not available for tree supports

### ISSUE THREAD

**Issue by sdooweloc** [SoftFever/OrcaSlicer#2107]
### OrcaSlicer Version

1.6.6 and 1.7.0-beta

### OS version

Arch Linux

### Additional system information

Kernel: 6.4.12-zen1-1-zen 
CPU: AMD Ryzen 7 7700X (16) @ 4.500GHz 
GPU: AMD ATI Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT 

### Printer

Voron 2.4

### How to reproduce

Navigate to Support with Advanced enabled
change support type to tree 
and subtype to any non-organic option
observe lack of "don't support bridges" option. 

### Actual results

When you select tree supports with any "tree" style the option for "Don't support bridges" is no longer available for toggling and thus unnecessary supports get generated

### Expected results

I would expect the "don't support bridges option to be available for all support types and styles to prevent needless support. 

### Project file & Debug log uploads

I am not providing a zip because it happens on all profiles and it would be faster to just toggle the option for the tester than to download, extract, and import a zip. 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Noisyfox** [comment]
"Don't Support Bridges" doesn't work for slim trees from the very beginning. Use `max_bridge_length` instead.

**Comment by sdooweloc** [comment]
ah okay thank you for that information. I will close this issue accordingly.

**Comment by mrelwood** [comment]
"Don't support bridges" is found with the search anyways, so it's confusing that it doesn't point to an option in the app.

**Comment by Noisyfox** [comment]
> "Don't support bridges" is found with the search anyways, so it's confusing that it doesn't point to an option in the app.

That's true for all hidden options. I guess it can be improved by adding a label prefix like "Disabled" in search results for any options that are not appliable.

**Comment by lin-ycv** [comment]
> "Don't Support Bridges" isn't available for slim/strong/hybrid trees from the very beginning. Use `max_bridge_length` instead.

@Noisyfox 

This isn't working as expected in 2.3.1, when using tree default/organic, bridges are still being supported when `Don't Support Bridges` is enabled.

<img width="1232" height="1108" alt="Image" src="https://github.com/user-attachments/assets/8639c4d6-85c6-47b1-a24e-069bc7c9acda" />

when using slim/strong/hybrid, tress are still being generated even if i change `max_bridge_length` to a ridiculous length like 256 

<img width="1215" height="1107" alt="Image" src="https://github.com/user-attachments/assets/243c5ce0-d7de-4eb9-9c39-2b717d4950b2" />
