### ISSUE TITLE
Camera Stream

### ISSUE THREAD

**Issue by RadsWa** [SoftFever/OrcaSlicer#2108]
### OrcaSlicer Version

1.7.0-Beta

### OS version

Windows 11

### Additional system information

Nvidia Geforce RTX 3060 Ti

### Printer

Bambu Lab P1P

### How to reproduce

Print anything.

### Actual results

When printing the camera stops working after a minute or two, I noticed this in the latest bambu slicer also, it does not occur in the current stable release version, only in the Beta.

### Expected results

Camera works through whole print

### Project file & Debug log uploads

Nil

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by RadsWa** [comment]
Ahh ignore that it wasn't a slicer issue sorry.

**Comment by PrincessLuna2253** [comment]
I am having this same issue in the release version of 1.7.0, the video stream from my P1P stops updating every 2-10 minutes until it is restarted

**Comment by RadsWa** [comment]
Just to update the last working version I am currently having to use is 1.6.6, every after this including beta has this same issue, camera just stops working after a minute or two and displays a still image permanently, stopping and re-starting the camera allows it to work for another minute, but there is no way to get it to consistently work, this is every print.

**Comment by RadsWa** [comment]
The 1.8.0 beta fixes this issue for me.
