### ISSUE TITLE
Add non-disappearing "Total estimation"

### ISSUE THREAD

**Issue by dejero13** [SoftFever/OrcaSlicer#2118]
Please add to the presence of the interface the non-disappearing information "Total estimation" for sliced models.
Now this information is provided in the "Color scheme - Line Type", which will disappear when the "Line Type" is changed:

![2023-09-15 12-47-53 Untitled](https://github.com/SoftFever/OrcaSlicer/assets/57988069/15d7a232-6c64-46b5-b0e5-4e617af64a62)
![2023-09-15 12-48-53 Untitled](https://github.com/SoftFever/OrcaSlicer/assets/57988069/bca3ef1d-13a4-4395-be76-31cd8b374d08)

As an example:
![2023-09-15 12-14-32 Untitled](https://github.com/SoftFever/OrcaSlicer/assets/57988069/8af90763-df56-4c16-8d54-44375b76cc15)

**Comment by evgarthub** [comment]
I was going to request\suggest the same feature. I'm using non line type color scheme by default and it could be annoying to have to switch to Line Type in order to see estimated time or other non changing data.
