### ISSUE TITLE
Incorrect language after installation

### ISSUE THREAD

**Issue by jdschuitemaker** [SoftFever/OrcaSlicer#2119]
### OrcaSlicer Version

1.7.0

### OS version

Windows 11 - Microsoft Windows [Version 10.0.22621.2215]

### Printer

Artillery Sidewinder V2

### How to reproduce

1. Install the software
2. Start the software

### Actual results

Orca Slicer is opened with the Dutch language.

### Expected results

I live in The Netherlands, but my I use English for my Operating System and all my applications. I would expect the application to start in the language I am using on my PC, not based on my location.

### Project file & Debug log uploads

n/a

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by hliebscher** [comment]
you can change this in settings ... is not a bug ;-)
