### ISSUE TITLE
User Profile Filament --> All user Profile Printer 

### ISSUE THREAD

**Issue by RafBois** [SoftFever/OrcaSlicer#2122]
### OrcaSlicer Version

1.7.0

### OS version

OSX 13.5.2

### Additional system information

Apple M1 Max

### Printer

Raise3D N2 Klipper / Artllery X1 Klipper

### How to reproduce

I can't find my filament profile in all my printer profiles.

But I've made an import. It tells me that the filament profile already exists, and if I want to overwrite it.

### Actual results

<img width="426" alt="Capture d’écran 2023-09-15 à 11 49 14" src="https://github.com/SoftFever/OrcaSlicer/assets/50773923/2b964c1a-e01e-48f0-8b7c-015718df997c">
<img width="432" alt="Capture d’écran 2023-09-15 à 11 48 48" src="https://github.com/SoftFever/OrcaSlicer/assets/50773923/7ecf57e9-2d6a-43a7-abc0-2cbf134fb0d2">

### Expected results

But I've made an import. It tells me that the filament profile already exists, and if I want to overwrite it.

### Project file & Debug log uploads

[log.zip](https://github.com/SoftFever/OrcaSlicer/files/12618151/log.zip)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by Metallica22** [comment]
Same problem here. I received eSun ASA+ profiles from the seller. After importing these were in the slicer. After restarting the slicer, all imported profiles were gone.
My own custom profiles are still there.

But I think that the problem also exists in Bambu Studio, which behaves the same way.
