### ISSUE TITLE
Cant't control device tab macOs version

### ISSUE THREAD

**Issue by erathos77** [SoftFever/OrcaSlicer#2124]
### OrcaSlicer Version

1.7.0

### OS version

macOS 11.6.7

### Additional system information

The device tab displays an animated demo that cannot be stopped, and therefore I cannot take control of its use.

Macbook pro 12,1 , 2.7GHz intel core i5, mem 8GHz, Intel Iris Graphics 6100 retina

### Printer

any

### How to reproduce

Launch OrcaSlicer
Go to Device Tab of the window
See animated window showing how to set parameters

### Actual results

This process can't be stopped or canceled.
No crash
The other tabs are functional

### Expected results

cancel the demo to get control (if it is required)

### Project file & Debug log uploads

[debug_network_Fri_Sep_15_12_41_02.log](https://github.com/SoftFever/OrcaSlicer/files/12618536/debug_network_Fri_Sep_15_12_41_02.log)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by TexZeTech** [comment]
Forgive the question, do you have the IP in the printer network field?

![image](https://github.com/SoftFever/OrcaSlicer/assets/7254540/36d9627b-cf5d-4439-a049-885e7b45dcd3)
![image](https://github.com/SoftFever/OrcaSlicer/assets/7254540/8c9cd172-f0ee-4949-aed8-6e82a481d95a)
