### ISSUE TITLE
设置首层流量不会改变Skirt和Brim的流量

### ISSUE THREAD

**Issue by fineemb** [SoftFever/OrcaSlicer#2129]
**Is your feature request related to a problem? Please describe.**
在质量里面设置首层流量，加大和板的黏度。但是我发现这并不会改变Skirt和Brim的流量。这个比较困扰我

**Which printers will be beneficial to this feature**
打印机Voron/Klipper 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by R4toLoko** [comment]
If English isn't your main language, a translator will do.
It will make the guys' life working on these tickets easier and allow users to help you out.

Many tickets are solved by other users providing feedback. 
Keep that in mind next time.
