### ISSUE TITLE
UX glitches on Ubuntu dark mode

### ISSUE THREAD

**Issue by guestisp** [SoftFever/OrcaSlicer#2133]
### OrcaSlicer Version

1.7

### OS version

Ubuntu 23.04

### Printer

BLV mgn Cube

### How to reproduce

On ubuntu in dark mode (don't know if it's the same with light mode), there are some text not visible, like dark gray on black or black on black and so on.

![image](https://github.com/SoftFever/OrcaSlicer/assets/3944655/bc21c3e8-fb31-46a4-8fd7-18d5dac85779)

### Actual results

some texts are not visible

### Expected results

All texts should be visible

### Project file & Debug log uploads

No project as this is not related to a single probject

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by TexZeTech** [comment]
I believe this is the same as https://github.com/SoftFever/OrcaSlicer/issues/2086

**Comment by guestisp** [comment]
Guys please take a look at this issue, so that i can trash away prusaslicer :-D :-D
