### ISSUE TITLE
Random Layer Lines on Toplayers

### ISSUE THREAD

**Issue by ALEX-9-99** [SoftFever/OrcaSlicer#2140]
### OrcaSlicer Version

1.6.4 - 1.7.0

### OS version

Windows 10

### Printer

Bambu Lab P1P/S

### How to reproduce

1. Get the sample file from Printables - https://www.printables.com/de/model/228249-filament-samples-42-materials
2. import "PLA_Filament Sample.stl" from shared folder into orca slicer
3. Sliced with default P1P settings and Bambu PLA filament (reproducible with other filaments)

### Actual results

There are strange patterns appearing on the surface.
Possibly in combination with the letter placement.
![image](https://github.com/SoftFever/OrcaSlicer/assets/139878997/bd792a4a-35b2-4f27-b46a-878ff1178d3f)

### Expected results

The Print Surface should vbe even with no strange Pattern or higups
![image](https://github.com/SoftFever/OrcaSlicer/assets/139878997/7d0ff925-d14b-4538-b3cc-ca93abc86373)

### Project file & Debug log uploads

[PLA_filament_sample_Report.zip](https://github.com/SoftFever/OrcaSlicer/files/12641493/PLA_filament_sample_Report.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by samwiseg0** [comment]
Have you played with the one wall threshold? You should be able to lower it and get your desired results. Turning off one wall top layer will achieve the same thing. 
![2023-09-17_20-57](https://github.com/SoftFever/OrcaSlicer/assets/2241731/c178a2fe-59ec-4735-911f-19539624bd66)

**Comment by ALEX-9-99** [comment]
Thanks for the help and sorry for bothering you.
I've never heared about this setting bevor.
