### ISSUE TITLE
Supports issue with adaptive layer height

### ISSUE THREAD

**Issue by Fisheye3D** [SoftFever/OrcaSlicer#2143]
### OrcaSlicer Version

1.7.0

### OS version

Windows 11

### Printer

Flsun Superracer 

### How to reproduce

Turn adaptive layer height on, turned tree supports on.

### Actual results

Supports seams to go through the model ignoring geometry. 
![image](https://github.com/SoftFever/OrcaSlicer/assets/78997080/f85b8644-2ff3-44e0-b184-06f04527babd)

### Expected results

Supports not go through model

### Project file & Debug log uploads

[log1.zip](https://github.com/SoftFever/OrcaSlicer/files/12641838/log1.zip)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by igiannakas** [comment]
Duplicate of this: https://github.com/SoftFever/OrcaSlicer/issues/2062

Basically adaptive layers and organic support are not compatible. Same as prusa slicer.

please close as this is a duplicate.
