### ISSUE TITLE
Add PLA+ as a Filament Type option 

### ISSUE THREAD

**Issue by l8nite** [SoftFever/OrcaSlicer#2148]
I find it helpful to distinguish between PLA and PLA+ in the filament types

**Comment by samwiseg0** [comment]
It maybe nice to have a preset but you can always type in whatever you want in the filament type. 
![ezgif com-video-to-gif](https://github.com/SoftFever/OrcaSlicer/assets/2241731/cee35e79-d2df-41e0-8b8e-faec9a5bad26)

**Comment by l8nite** [comment]
Hey thanks! That wasn't immediately obvious - I should've tried that :D

**Comment by samwiseg0** [comment]
I don't blame you since a drop down does not normally let you do that!

**Comment by Ocraftyone** [comment]
This seems to be completed. Please close if so.
