### ISSUE TITLE
new bug report form does not allow preview before submit

### ISSUE THREAD

**Issue by julie777** [SoftFever/OrcaSlicer#2152]
### OrcaSlicer Version

1.7.0

### OS version

Windows 10

### Printer

P1P

### How to reproduce

create a bug report

### Actual results

no preview button

### Expected results

github should allow preview before submit

### Project file & Debug log uploads

none

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by samwiseg0** [comment]
This is not the place for this feedback as this is a GitHub issue and a limitation of the forms beta feature. More details can be found here. https://github.com/orgs/community/discussions/63402
