### ISSUE TITLE
Printer Cooling Modifier

### ISSUE THREAD

**Issue by Kaelum** [SoftFever/OrcaSlicer#2155]
Different printers have different cooling abilities, and the cooling settings are primarily set in the Filament Settings. It would be nice to have the ability to specify a cooling modifier in the Printer Settings that would be multiplied by the actual cooling value to allow for normalization across printers.

**Describe the solution you'd like**
Add a setting to the Printer Settings for "Cooling multiplier".

**Describe how it would work**
A value of 1.00 would mean no change. A value of 0.60 or 60% would mean a reduction of 40% in the calculated cooling setting, or 60% of the calculated value. A value of 1.25 or "125%" would mean an increase of 25% in the calculated value.

**Describe alternatives you've considered**
Creating duplicate Filament Settings for each printer would be impossible to manage, and is currently the only possible way to manage this. My Rat Rig cooling fan is at least 50% stronger than any of my other printers. My Snapmaker is capable of less than 60% of the cooling that my K1 Max is capable of, and my Ender 5 Plus is somewhere in the middle. As you can see, this is impossible to manage.

**Comment by Lt-Kammello** [comment]
Should be implemented in min and max CFM of the fan possibly tied to certains pwm values/regimes
