### ISSUE TITLE
saggy top surface when using combined infill

### ISSUE THREAD

**Issue by CooperGerman** [SoftFever/OrcaSlicer#2158]
### OrcaSlicer Version

1.6.6

### OS version

Windows 10

### Additional system information

CPU : AMD A8-7600 Radeon R7, 10 Compute Cores 4C+6G     3.10 GHz
RAM : 16,0 Go
GPU : Nvidia 770

### Printer

Voron trident 250

### How to reproduce

1. Select the top part of a sphere as test model
2. Use up to 40% (didn't test above), either `gyoïd` or `adaptative cubic` infill (haven't tested all infills)
3. Use number of outer walls between `3` and `7` 
4. Use `0.08` layer height (might work with higher but didn't test it)

Tested with a `Voron trident 250` and a `Prusa MK3S` with several `PLA` plastics.
### Actual results

![image](https://github.com/SoftFever/OrcaSlicer/assets/43497893/9de2a730-0ee0-42e8-96db-dcf91e277721)
![image](https://github.com/SoftFever/OrcaSlicer/assets/43497893/5c140ea6-4097-44c8-890e-2ef7f558a185)
![signal-2023-09-18-121222](https://github.com/SoftFever/OrcaSlicer/assets/43497893/7bb542dc-5217-4a45-8d00-3815f0ecdf36)

### Expected results

![signal-2023-09-18-134420](https://github.com/SoftFever/OrcaSlicer/assets/43497893/9b251860-f5f1-408e-95f4-4d3102368411)

### Project file & Debug log uploads

[projects.zip](https://github.com/SoftFever/OrcaSlicer/files/12647415/projects.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Thoughts 
Might be related to https://github.com/SoftFever/OrcaSlicer/issues/1125#issue-1721336655, as this could improve results. Same project was successfully printed with `PrusaSlicer` with `combined infill` set to `3`.

It seems like combining the infill does not provide enough structural support for layers printed above when combined as they might sagg.

**Comment by somebody-somewhere-over-the-rainbow** [comment]
this should be reopened - issue is there - #1125 could indeed help avoid this ...
