### ISSUE TITLE
Arrange All Objects ignores Spacing setting below 10

### ISSUE THREAD

**Issue by Domochevsky** [SoftFever/OrcaSlicer#2159]
### OrcaSlicer Version

1.7.0

### OS version

Windows 7

### Printer

Bambu Lab P1P

### How to reproduce

1. Open the slicer.
2. Import a few objects. (STL for example)
3. Click on "arange all objects" in the top bar. Set the Spacing slider to anything below 10. Click Arrange.

### Actual results

See that it spaces things out to be 10mm apart at minimum anyway. 
The Spacing slider is set on the value I defined, but ignores it if it's below 10.

### Expected results

I am expecting it to also accept values below 10mm, spacing them out accordingly.

### Project file & Debug log uploads

[xyzCalibration_cube_x10.zip](https://github.com/SoftFever/OrcaSlicer/files/12650044/xyzCalibration_cube_x10.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by foreachthing** [comment]
If I slice/arrange your file with my profile, all is fine.... so, there must be a setting messing with arrange.
In fact Disable support and you're set.

**Comment by Domochevsky** [comment]
Huh, you're right. If I disable supports entirely it suddenly adheres to the Spacing setting. Why is that?

**Comment by foreachthing** [comment]
I guess to "avoid" interference with other objects. If you don't _merge_ multiple objects, the supports can collide with other objects.

**Comment by mattswest** [comment]
So is this not considered a bug?

I'm not clear on why objects with supports have an enforced minimum spacing setting.

**Comment by buffcode** [comment]
This even affects objects with manual support setting and no added supports.
