### ISSUE TITLE
Exclude object ignores the prime tower

### ISSUE THREAD

**Issue by thisiscam** [SoftFever/OrcaSlicer#2167]
**Is your feature request related to a problem? Please describe.**

Currently the exclude object markers ignores the region for prime tower. My printer does a region based automatic bed leveling ([KAMP](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging)) so it's currently not able to print the prime tower without me manually adjusting the z-offset for the prime tower.   

**Which printers will be beneficial to this feature**
Any printer with an MMU?

**Describe the solution you'd like**
The prime tower should be treated as a printable object, having its own exclude_object region.

**Describe alternatives you've considered**
Not sure if there's any good alternatives? 

**Additional context**
I might be wrong but I think prior to 1.7 the old prime tower was indeed part of the exclude object region, since I had no problems printing back then? Or maybe just because 1.7 made the prime tower larger that is causing issue now..

**Comment by StdVectorBool** [comment]
I'm slicing this model with Tree Supports and it seems the polygon also doesn't include supports as the KAMP purge line runs right through the front support bases:
![image](https://github.com/SoftFever/OrcaSlicer/assets/4926951/371f4d28-84c0-42bf-8be3-cb39ed513b9c)
