### ISSUE TITLE
Allow Enter key for “OK”

### ISSUE THREAD

**Issue by mrelwood** [SoftFever/OrcaSlicer#2173]
Bambu Studio and hence Orca are rare applications in that you can’t approve and close pop-up windows by pressing the Enter key. For example when saving a preset, sending a job to the printer, or starting a calibration on the Bambu Lab P1P. After all, the Esc key does work for canceling and closing the window in each of those.

I can’t think of any other application that doesn’t allow to use the enter key this way. I’ve been using Orca pretty actively for a few months and I still keep hitting the enter key instead of clicking the “OK” button. I wish that Orca as well would allow the Enter key.

Using a MacBook Pro 16” 2019 running macOS Ventura 13.5.2.

**Comment by Ocraftyone** [comment]
Seems to be a Mac issue with my limited testing
