### ISSUE TITLE
Infill Combination ignores Layer Height limits

### ISSUE THREAD

**Issue by ZedOud** [SoftFever/OrcaSlicer#2175]
### OrcaSlicer Version

1.7.0

### OS version

macOS 13.5.2

### Printer

FLSun v400

### How to reproduce

Set:
`Quality -> Layer height` to 0.1mm
`Strength -> Advanced -> Infill combination` is enabled
`Printer Settings -> Extruder -> Layer Height limits -> Max` is less than the `Nozzle Diameter` (as I assume the latter is the calculated limit). For example, 0.3mm

### Actual results

When slicing an object, checking the `Layer Height` view shows us 0.1mm perimeter height and 0.4mm infill height, the latter of which is well beyond the `Layer Height limit`
<img width="945" alt="Screenshot 2023-09-19 at 4 51 13 PM" src="https://github.com/SoftFever/OrcaSlicer/assets/7321904/10b4c695-5762-45e1-8172-9de6ff67eb5d">

I believe this is related to issues #1125 and #2158 

### Expected results

The infill layer height as a result of `Infill combination` should be limited to the `Layer Height limit`, in this case 0.3mm, not 0.4mm

### Project file & Debug log uploads

[InfillCombinationIssue.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/12667333/InfillCombinationIssue.3mf.zip)

Uploading the log just because?
[debug_log.zip](https://github.com/SoftFever/OrcaSlicer/files/12667355/debug_log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by Vorta** [comment]
Too bad that this was not resolved. I cannot use infill combination in my prints because of this. I have max layer height set to 0.2mm on my 0.4mm nozzle and infill combination still wants to print 0.4mm high infills.

**Comment by Gamerou** [comment]
> Too bad that this was not resolved. I cannot use infill combination in my prints because of this. I have max layer height set to 0.2mm on my 0.4mm nozzle and infill combination still wants to print 0.4mm high infills.

same
