### ISSUE TITLE
Fan not turning on, Creality K1

### ISSUE THREAD

**Issue by dariotarantini** [SoftFever/OrcaSlicer#2183]
### OrcaSlicer Version

1.7.0

### OS version

archlinux:latest

### Printer

Creality K1

### How to reproduce

When priting something not all fan turns on after first layer. I usually turn on by hand. 
There could be a fix, if only there was a way to replace Gcode in orcaslicer.  Like following:
![image](https://github.com/SoftFever/OrcaSlicer/assets/34209633/65accc9b-5f73-4c8a-ab88-745afacd1ade)

### Actual results

No fan turn on

### Expected results

Fan should turn on

### Project file & Debug log uploads

no log

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by asmforce** [comment]
I have the same issue.
After the last K1 firmware upgrade the back fan never starts automatically. I have to start it manually every time.

**Comment by 21IsOnlyTheHalfTruth** [comment]
Same Issue here with the K1C. But i am kinda new to orca slicer so maybe there is a fix i dont know

**Comment by allexmail** [comment]
I have the same problem on k1c. The exhaust fan control does not work, because the names of the fans are mixed up in code M106. I can run it at the beginning of printing via gcode, but it's not convenient.
