### ISSUE TITLE
Automatic Slicing in Preview Tab

### ISSUE THREAD

**Issue by richard-scott** [SoftFever/OrcaSlicer#2193]
**Is your feature request related to a problem? Please describe.**
When testing out setting changes in the preview tab, I have to click Slice Plate every time

**Which printers will be beneficial to this feature**
All

**Describe the solution you'd like**
I would like to be able to enable auto-slicing, just like UltiMaker Cura has.

**Describe alternatives you've considered**
Clicking the button, but that gets repetitive.

**Additional context**
I've raised this issue here too https://github.com/bambulab/BambuStudio/issues/2542

**Comment by FinalFrag** [comment]
You can reslice with CTRL+R, but I agree that auto slicing a la cura would be nice.

**Comment by mdeeter** [comment]
Also at https://github.com/SoftFever/OrcaSlicer/discussions/970
