### ISSUE TITLE
Calibration menu shows ">No printer", can't seem to use Calibration menu

### ISSUE THREAD

**Issue by cjshaker** [SoftFever/OrcaSlicer#2197]
### OrcaSlicer Version

1.7.0

### OS version

Windows 11 Home 22H2 build 22621.2283

### Additional system information

Device name	cjshaker
Processor	11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz   3.60 GHz
Installed RAM	16.0 GB (15.8 GB usable)
Device ID	B5CDE8A9-447B-48FE-B136-D7E01C09CC4B
Product ID	00325-82189-88851-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

### Printer

Flsun V400, and Prusa MK3S

### How to reproduce

I'm a new Orca Slicer user. Apologize in advance if this is just operator error, but the wiki doesn't appear to show this?

Click 'New Project',  select Flsun V400 printer, select a filament (like FlSun Generic PLA), select 0.20mm Standard@FLSun V400 for print quality, select 'Preview' tab - all looks good. Now, select 'Calibration' tab to the right of 'Project', and nothing works:
![FlsunV400Selected](https://github.com/SoftFever/OrcaSlicer/assets/1294479/bc1c82cc-bde1-4fab-8300-02dbe10b98e0)
![FlowDynamicsGreyedOut](https://github.com/SoftFever/OrcaSlicer/assets/1294479/c6c23d40-f494-4d10-a797-7bded3ee9b6d)
![FlowRateGreyedOut](https://github.com/SoftFever/OrcaSlicer/assets/1294479/6aa82d50-9979-40c2-bfb4-f429cf9e2d87)

ALSO, the 'Project' tab says 'no model information'. Is this expected?
![ProjectNoModelInfo](https://github.com/SoftFever/OrcaSlicer/assets/1294479/01c0a4d8-8337-429c-b660-c495bf26c7d0)

I tried the same thing with the Prusa i3 MK3 printer, and that 'Calibration' tab is also greyed out for that printer too:
![MK3S Selected](https://github.com/SoftFever/OrcaSlicer/assets/1294479/7a1c737f-4b4c-4134-8779-ad70c5224030)
![CalibrationNotWorking2](https://github.com/SoftFever/OrcaSlicer/assets/1294479/49df0d93-6f14-4033-bee4-fda3eef71b33)

Either I'm missing something in the user interface, or this 'Calibration' tab is broken in 1.7.0?

Hmm. I just noticed the "Calibration" in the TOP menu bar, and that appears to work. 
Also, the "Calibration" in the TOP menu bar only works if you are in the 'Prepare' tab.
Why are there TWO ways of doing Calibration?

### Actual results

Can't select 'Manual Calibration' nor 'Auto Calibration'. Calibration says "> No printer". Screenshots above.

### Expected results

I thought I used to be able to launch calibration in a previous version of Orca slicer?

### Project file & Debug log uploads

[Project.zip](https://github.com/SoftFever/OrcaSlicer/files/12693874/Project.zip)
[debug_Thu_Sep_21_14_45_00_3296.log.zip](https://github.com/SoftFever/OrcaSlicer/files/12693875/debug_Thu_Sep_21_14_45_00_3296.log.zip)
[OrcaSlicer.conf.zip](https://github.com/SoftFever/OrcaSlicer/files/12693877/OrcaSlicer.conf.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by Noisyfox** [comment]
Because the calibration tab is added in BambuStudio and only works for their printers, while the one on menu bar is the Orca's.

**Comment by YELLOWFROG0623** [comment]
Hi!
Sorry for cutting in.
I went through the same process of trial and error for about 2 days, but I finally solved the mystery and felt refreshed.
thank you very much.

**Comment by DrDrache** [comment]
can we get an option to remove (hide) the tab for non-bamboo printers? or perhaps get it working for others?

**Comment by stopanko** [comment]
So confusing. 
![image](https://github.com/SoftFever/OrcaSlicer/assets/3759349/cabd6157-ec95-4f0d-9319-a900351870d2)
Bambu Calibrationts. Works only with Bambu printers.

![image](https://github.com/SoftFever/OrcaSlicer/assets/3759349/ad73017f-d553-4263-9bf8-a21c449a2c13)
Orca calibrations. Free to use))

**Comment by Noisyfox** [comment]
Should have been fixed a while ago by hiding the bambu calibration tab for non-bambu printers.
