### ISSUE TITLE
Option to place gcode preview text block at the end of file, rather than beginning.

### ISSUE THREAD

**Issue by PhilBaz** [SoftFever/OrcaSlicer#2200]
**Is your feature request related to a problem? Please describe.**

An option to place gcode preview text block at the end of file, rather than beginning. For those of us who look at the gcode it would be much nicer to not have to navigate past the huge preview block at the beginning.

**Which printers will be beneficial to this feature**
E.g. Voron/Klipper based printer/etc...

all gcode peepers.

**Describe the solution you'd like**

An option to place gcode preview text block at the end of file, rather than beginning

**Describe alternatives you've considered**

**Additional context**

**Comment by za-x-az** [comment]
Yes this please! 🙏

**Comment by PhilBaz** [comment]
Bump for git.....would be nice!

**Comment by za-x-az** [comment]
Any chance we will get this?

**Comment by PhilBaz** [comment]
@za-x-az  Would be nice wouldn't it?  it will be interesting to try the new gcode editor in 2.0. Maybe that will either make the need for this feature more relevant? Don't know, we will have to see.

**Comment by za-x-az** [comment]
> @za-x-az Would be nice wouldn't it? it will be interesting to try the new gcode editor in 2.0. Maybe that will either make the need for this feature more relevant? Don't know, we will have to see.

bump? :D

**Comment by PhilBaz** [comment]
Bump....would be nice.
