### ISSUE TITLE
Video feed from P1P stops updating after a few minutes

### ISSUE THREAD

**Issue by PrincessLuna2253** [SoftFever/OrcaSlicer#2204]
### OrcaSlicer Version

1.7.0

### OS version

Windows 11

### Additional system information

Ryzen 5800X3D, 32GB RAM, RTX 3080

### Printer

P1P

### How to reproduce

1. Go to device tab
2. Start video stream
3. Wait

### Actual results

Within 10 minutes the video feed freezes

### Expected results

Video feed continues until manually stopped

### Project file & Debug log uploads

N/A

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by RadsWa** [comment]
I too reported this, it is on Orca and Babbu's slicer
