### ISSUE TITLE
Junction deviation support

### ISSUE THREAD

**Issue by Duncro** [SoftFever/OrcaSlicer#2209]
**Is your feature request related to a problem? Please describe.**
No, a feature. Add support for Junction deviation

**Which printers will be beneficial to this feature**
Anything running on marling 2+

**Describe the solution you'd like**
Add an option for junction deviation instead of jerk

**Describe alternatives you've considered**
Removing the jerk settings (M205) from the gcode

**Additional context**
N/A

**Comment by 3Dmapsantos** [comment]
https://github.com/prusa3d/PrusaSlicer/issues/2115
