### ISSUE TITLE
Switch between AMS & Manual Spool in a running print with a Y-Splitter

### ISSUE THREAD

**Issue by xenon2008** [SoftFever/OrcaSlicer#2212]
**Is your feature request related to a problem? Please describe.**
Please add an Option for People who has an Y Splitter installed, so they could switch between a print from a Spool in the AMS to the manual outside Spool (for Glow in the Dark or some other abrassive FIlaments for example)

**Which printers will be beneficial to this feature**
Bambulab X1C with AMS

**Describe the solution you'd like**
I want to print some multicolor Files with some Glow in the Dark Filament for example.
In the AMS i have 4 different Colors and the Glow in the Dark Filament is outside of the AMS.
I didnt find any Option / Solution to switch between a Print from the AMS to the manual Spool outside the AMS and back.
I have an Y Splitter installed, like most other bambulab owners

**Describe alternatives you've considered**
-

**Additional context**
Switch between AMS & Manual Spool in a running print with a Y-Splitter

**Comment by bchevreau** [comment]
Reopening this, because it is such an obvious feature I can't believe it's been more than a year and a half and still no resolution...
