### ISSUE TITLE
Poor color choices

### ISSUE THREAD

**Issue by SwagDad99** [SoftFever/OrcaSlicer#2213]
### OrcaSlicer Version

1.7.0

### OS version

Windows 11

### Printer

Bambu X1C with 2 AMSs

### How to reproduce

Color a multi-color model.
Slice and send it to the printer

### Actual results

The color choices picked by the slicer when it ask, are very poor choices.  As the pic shows, there are both green, and yellow loaded in the AMS slots, but the slicer chose white for the green choice, and black for the yellow choice.

### Expected results

Pick a color close to the one selected in the model, from those loaded in the AMS

### Project file & Debug log uploads

![Screenshot_38](https://github.com/SoftFever/OrcaSlicer/assets/90676419/5979ba97-3861-4812-8f57-0612a4be2470)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by igiannakas** [comment]
I know it doesn’t help but Bambu slicer has the same issue in the last couple releases.
