### ISSUE TITLE
First Layer Print Time

### ISSUE THREAD

**Issue by TjardF** [SoftFever/OrcaSlicer#2216]
**Is your feature request related to a problem? Please describe.**
In Prusa there is a point called first layer duration, should be pretty easy to add to the preview I guess.
Maybe I'm not the only one interested in....

**Which printers will be beneficial to this feature**
All

**Describe the solution you'd like**
![image](https://github.com/SoftFever/OrcaSlicer/assets/37928929/e0ad6203-3599-471e-9a4b-fc80c32e0402)

**Describe alternatives you've considered**

**Additional context**

**Comment by Eldenroot** [comment]
+1

**Comment by Eldenroot** [comment]
This needs to backported from PS.
