### ISSUE TITLE
Overhang Slowdown logic somehow getting capped by Filament cooling ?

### ISSUE THREAD

**Issue by psiberfunk** [SoftFever/OrcaSlicer#2221]
### OrcaSlicer Version

1.7.0 release

### OS version

Windows 11 / Win64

### Additional system information

N/A - Slicer logic issue

### Printer

Bambu X1C

### How to reproduce

1. Slice attached project file with settings included, observe that for layer 57 (see screenshots below) the speed for the overhang in the screenshot is mysterious much slower (15 mm/sec) than it should be.
. 

### Actual results

1. Notice that the overhand speed in the screenshot here is 15, when at minimum it should be the lesser of 60 OR the VFR-limited speed (which is ~44 mm/sec at this line width).
2. Notice also that the filament min-slowdown for cooling speed is also 15 (appears to be hitting this limit somehow, but not near the min layer speed).
3.  Notice how when the slowdown-for-overhangs is turned OFF, this same segment is at speed 44 instead of 15.

**The only difference between these two screenshots is turning off slowdown-for-overhangs.. no other changes were made**

![Screenshot 2023-09-24 190921](https://github.com/SoftFever/OrcaSlicer/assets/19777571/10397ab4-6952-46f3-a457-c2963832f9ff)
![Screenshot 2023-09-24 190809](https://github.com/SoftFever/OrcaSlicer/assets/19777571/35ba1ad0-0a88-4fa6-8625-7d354c580512)
![Screenshot 2023-09-24 190742](https://github.com/SoftFever/OrcaSlicer/assets/19777571/81a513e2-6b52-43e5-a6ef-dd45cb36144d)

### Expected results

The speed for these overhangs should NOT be governed by the min-speed set in the filament cooling tab here, because 

1. the layer time is not anywhere near the min layer time (6 seconds, this layer is ~10 sec) 
2. The min speed for the appropriate overhang is set to 60 (way above 15).
3. Turning slow-down-for overhangs OFF fixes the problem by restoring the speed to 44 mm/sec - indicating that this slowdown is happening BECAUSE of slowdown-for-overhangs.. but the wrong logic is getting applied. 
5. The correct speed here, according to the settings ought to be the VFR limited speed (I think this is ~44 mm/sec) , since this is the lesser of Overhang slow down speed v.s. VFR-limited-speed.

### Project file & Debug log uploads

 [OverhangSlowdownLogicIncorrect.zip](https://github.com/SoftFever/OrcaSlicer/files/12709838/OverhangSlowdownLogicIncorrect.zip)

### Checklist of files to include

- [x] Log file
- [X] Project file

**Comment by psiberfunk** [comment]
Log file not included because this is a reproducible slicer logic bug and not a crash or UX issue or similar.

**Comment by kevinbrouwers** [comment]
Confirmed. I spent several hours trying to figure out what setting was slowing my speed down to 10mm/s when it should have been 100 mm/s. It was this bug. Thanks for posting this.
