### ISSUE TITLE
Bridged Holes Encroachment Setting

### ISSUE THREAD

**Issue by Lt-Kammello** [SoftFever/OrcaSlicer#2227]
Connection issues on bridged holes.

When you have an hole in a bridged surface, the perimeters are partially treated like bridges, if you choose thick bridge or not they are printed accordingly.

The issue is the amount of "encroaching" between bridged infill and hole's walls [See Pics Below].
While bridges attach to the main body walls with large amount of encroaching ensuring connection, the same does not apply for the walls of the inner hole, resulting in no connection.

I think this would be a fairly big step forward having the right amount of connection or at least an option to set it.

![Screenshot 2023-09-25 134101](https://github.com/SoftFever/OrcaSlicer/assets/116590108/f01f3770-7cc9-490c-b437-93c18acf7040)
![IMG_7082](https://github.com/SoftFever/OrcaSlicer/assets/116590108/0aec0ed6-8f5a-4e3a-8b15-dea4a8bc0313)

**Comment by mpsnp** [comment]
Guess these kind of issues can be easily solved with [this modelling trick](https://youtu.be/W8FbHTcB05w?si=nmwPoyhqK_hop9Ji&t=531)

**Comment by Lt-Kammello** [comment]
> Guess these kind of issues can be easily solved with [this modelling trick](https://youtu.be/W8FbHTcB05w?si=nmwPoyhqK_hop9Ji&t=531)

Sure thing but that’s not optimal.
Also bridged walls are not treated like bridges creating 2 main issues:
1) inconsistent adhesion to support due to the difference in applied flow rate;
2) lack of adhesion between bridge and wall like i showed in my pics

i will label this as a bug and i’m asking for @SoftFever attention since i think this bug is very relevant.

kindly

Lorenzo
