### ISSUE TITLE
Build fails with Xcode 15

### ISSUE THREAD

**Issue by superfloh247** [SoftFever/OrcaSlicer#2233]
### OrcaSlicer Version

ec90d7f

### OS version

MacOS 13.6

### Additional system information

Apple Silicon M1
Xcode 15

### Printer

Bambu P1P

### How to reproduce

run build_release_macos.sh

### Actual results

build fails:

CompileC /Users/lindner/VSCode/OrcaSlicer/build_arm64/build/hintsToPot.build/Release/Objects-normal/arm64/HintsToPot.o /Users/lindner/VSCode/OrcaSlicer/src/hints/HintsToPot.cpp normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'hintsToPot' from project 'OrcaSlicer')
    cd /Users/lindner/VSCode/OrcaSlicer
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c++ -ivfsstatcache /var/folders/ck/973lln0j18gc19rk0c2j_bxr0000gp/C/com.apple.DeveloperTools/15.0-15A240d/Xcode/SDKStatCaches.noindex/macosx14.0-23A334-4a76ee93ef69e462914ffe9883de22b8.sdkstatcache -target arm64-apple-macos11.3 -fmessage-length\=152 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -fcolor-diagnostics -Wno-trigraphs -fpascal-strings -O3 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-return-type -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wno-unused-variable -Wunused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wshorten-64-to-32 -Wno-newline-eof -Wno-c++11-extensions -Wno-implicit-fallthrough -DCMAKE_INTDIR\=\"Release\" -DSLIC3R_GUI -DSLIC3R_DESKTOP_INTEGRATION -DwxUSE_UNICODE -D_UNICODE -DUNICODE -DWXINTL_NO_GETTEXT_MACRO -DwxNO_UNSAFE_WXSTRING_CONV -DBOOST_ASIO_DISABLE_KQUEUE -DBOOST_ALL_NO_LIB -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk -fstrict-aliasing -Wdeprecated-declarations -Winvalid-offsetof -Wno-sign-conversion -Wno-infinite-recursion -Wno-move -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -Wno-range-loop-analysis -Wno-semicolon-before-method-body -I/Users/lindner/VSCode/OrcaSlicer/build_arm64/src/hints/Release/include -I/Users/lindner/VSCode/OrcaSlicer/src -I/Users/lindner/VSCode/OrcaSlicer/build_arm64/src/platform -I/Users/lindner/VSCode/OrcaSlicer/src/libigl -isystem /Users/lindner/VSCode/OrcaSlicer/src/eigen -isystem /Users/lindner/VSCode/OrcaSlicer/deps/build_arm64/OrcaSlicer_dep_arm64/usr/local/include/boost-1_75 -I/Users/lindner/VSCode/OrcaSlicer/build_arm64/build/hintsToPot.build/Release/DerivedSources-normal/arm64 -I/Users/lindner/VSCode/OrcaSlicer/build_arm64/build/hintsToPot.build/Release/DerivedSources/arm64 -I/Users/lindner/VSCode/OrcaSlicer/build_arm64/build/hintsToPot.build/Release/DerivedSources -F/Users/lindner/VSCode/OrcaSlicer/build_arm64/src/hints/Release -Wall -Wno-reorder -Werror\=partial-availability -Werror\=unguarded-availability -Werror\=unguarded-availability-new -DNDEBUG -std\=gnu++17 -fPIE -fsigned-char -Werror\=return-type -Wno-ignored-attributes -Wno-deprecated-declarations -MMD -MT dependencies -MF /Users/lindner/VSCode/OrcaSlicer/build_arm64/build/hintsToPot.build/Release/Objects-normal/arm64/HintsToPot.d --serialize-diagnostics /Users/lindner/VSCode/OrcaSlicer/build_arm64/build/hintsToPot.build/Release/Objects-normal/arm64/HintsToPot.dia -c /Users/lindner/VSCode/OrcaSlicer/src/hints/HintsToPot.cpp -o /Users/lindner/VSCode/OrcaSlicer/build_arm64/build/hintsToPot.build/Release/Objects-normal/arm64/HintsToPot.o
In file included from /Users/lindner/VSCode/OrcaSlicer/src/hints/HintsToPot.cpp:6:
In file included from /Users/lindner/VSCode/OrcaSlicer/deps/build_arm64/OrcaSlicer_dep_arm64/usr/local/include/boost-1_75/boost/property_tree/ini_parser.hpp:14:
In file included from /Users/lindner/VSCode/OrcaSlicer/deps/build_arm64/OrcaSlicer_dep_arm64/usr/local/include/boost-1_75/boost/property_tree/ptree.hpp:16:
In file included from /Users/lindner/VSCode/OrcaSlicer/deps/build_arm64/OrcaSlicer_dep_arm64/usr/local/include/boost-1_75/boost/property_tree/string_path.hpp:16:
In file included from /Users/lindner/VSCode/OrcaSlicer/deps/build_arm64/OrcaSlicer_dep_arm64/usr/local/include/boost-1_75/boost/property_tree/exceptions.hpp:17:
In file included from /Users/lindner/VSCode/OrcaSlicer/deps/build_arm64/OrcaSlicer_dep_arm64/usr/local/include/boost-1_75/boost/any.hpp:18:
In file included from /Users/lindner/VSCode/OrcaSlicer/deps/build_arm64/OrcaSlicer_dep_arm64/usr/local/include/boost-1_75/boost/type_index.hpp:29:
In file included from /Users/lindner/VSCode/OrcaSlicer/deps/build_arm64/OrcaSlicer_dep_arm64/usr/local/include/boost-1_75/boost/type_index/stl_type_index.hpp:47:
/Users/lindner/VSCode/OrcaSlicer/deps/build_arm64/OrcaSlicer_dep_arm64/usr/local/include/boost-1_75/boost/container_hash/hash.hpp:131:33: error: 
      no template named 'unary_function' in namespace 'std'; did you mean '__unary_function'?
        struct hash_base : std::unary_function<T, std::size_t> {};

### Expected results

expected: build does not fail :)

See also https://stackoverflow.com/questions/77133361/no-template-named-unary-function-in-namespace-std-did-you-mean-unary-fun

### Project file & Debug log uploads

no need pro project files

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by superfloh247** [comment]
looks like this is a problem in the included boost

See OrcaSlicer/deps/build_arm64/OrcaSlicer_dep_arm64/usr/local/include/boost-1_75/boost/functional.hpp

#if defined(_HAS_AUTO_PTR_ETC) && !_HAS_AUTO_PTR_ETC
            // std::unary_function and std::binary_function were both removed
            // in C++17.

**Comment by igiannakas** [comment]
The current version of boost is not compatible with Xcode 15 and specifically c++ 17. I downgraded my Xcode install to 14.x to get it to build locally again. Suggest the same for you till boost is upgraded

**Comment by superfloh247** [comment]
I just replaced all unary_function and binary_function with the __ versions and it works now.

**Comment by superfloh247** [comment]
fixed by 3b5f42c
