### ISSUE TITLE
Fan speed at 255 after Filament change

### ISSUE THREAD

**Issue by erdemdemir85** [SoftFever/OrcaSlicer#2234]
### OrcaSlicer Version

1.7.0

### OS version

Windows 10

### Printer

X1C

### How to reproduce

Slice a model with filament changes and overhangs

### Actual results

After Filament changes/support interface/(maybe even overhangs) the Fan Speed is set to Max value 255.

In the G Code every "CP TOOLCHANGE START - END" section looks like:

...
...
M621 S3A
M106 P2 S0
M106 S255

G1 E-1.4 F2700
G1 X176.502 Y216.597 F30000
G1 Z28.1
G1 Z24.9
M73 P58 R108
G1 E2.4 F2400

; filament start gcode
M106 S255

G4 S0
G1  X175.752 Y216.597 
G1  Y215.847 
G1  X179.292  E0.30272
M106 P3 S128
G1  X210.752  E2.69028
G1  Y236.597  E1.7744
G1  X175.752  E2.9930
G1  Y215.847  E1.7744
G1  X176.502 Y216.597  
; CP TOOLCHANGE WIPE
G1  X210.190  E2.8808 F1584
G1  Y219.454  E0.2443
G1  X176.314  E2.8968 F1800
G1  Y222.311  E0.2443
G1  X210.190  E2.8968 F2198
G1  Y225.168  E0.2443
G1  X176.314  E2.8968 F4200
G1  Y228.026  E0.2443
G1  X210.190  E2.8968 F4250
G1  Y230.883  E0.2443
G1  X176.314  E2.8968 F4300
G1  Y233.740  E0.2443
G1  X210.190  E2.8968 F4350
G1 F30000
G4 S0
G92 E0
; CP TOOLCHANGE END
;------------------

while my filament_start_gcode looks like that:
; filament start gcode
M106 P3 S128

so where does the "M106 S255" in my gcode come from?

Image Fan Speed:
[https://imgtr.ee/image/Dxrsr](url)

### Expected results

All fan speeds should be set according to the settings

### Project file & Debug log uploads

[TestBug.zip](https://github.com/SoftFever/OrcaSlicer/files/12728335/TestBug.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by dartrax** [comment]
It has something to do with the support. When you disable support generation, the problem will be gone.
(Note: In v1.8.0 there is a new problem when you enable Fan speed-up time and Fan kickstart time, see #2600 )
