### ISSUE TITLE
Role-based wipe speed does not follow current print speed, tries to wipe at set Outer wall speed

### ISSUE THREAD

**Issue by killerline10168** [SoftFever/OrcaSlicer#2244]
### OrcaSlicer Version

Release 1.7.0

### OS version

Windows 11 22H2

### Printer

Ender 3 Max 

### How to reproduce

Enable role-based wipe speed

### Actual results

Even though role-based wipe speed is enabled, it is still wiping at almost 3.5 times faster than the perimeter speed, which I suspect is why I have horrible seams that look under-extruded (off-topic).

![perimeter speed](https://github.com/SoftFever/OrcaSlicer/assets/1812366/96e2cd84-c6ff-4026-b2ab-132348be76f2)

This is showing the perimeter speed, which is correct.

![wipe speed](https://github.com/SoftFever/OrcaSlicer/assets/1812366/486af64f-bce8-4261-a1d6-b77755639e3a)

Here it shows the wipe and its speed (140 mm/s compared to 25 mm/s!)shows

### Expected results

If understood correctly, the meaning of role-based wipe speed is to continue the travel along the printed perimeter with the same speed as the perimeter was printed. This clearly shows otherwise.

### Project file & Debug log uploads

[Retraction test.zip](https://github.com/SoftFever/OrcaSlicer/files/12740461/Retraction.test.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by Naninani** [comment]
I wonder if this is related to all of a sudden, me started getting terrible stringing with PETG, which I never had before.

**Comment by killerline10168** [comment]
> I wonder if this is related to all of a sudden, me started getting terrible stringing with PETG, which I never had before.

I'm no expert, but I'm imagining that the nozzle is now moving too fast while wiping, which doesn't let the nozzle relieve its pressure, which is the whole point of a wipe (along with reducing the seam visibility). 

In my case I get horrible seams (see my [reddit post here](https://www.reddit.com/r/FixMyPrint/comments/15gmm5h/why_do_my_seams_look_like_this_at_occasionaly/)), which I believe could be caused by this bug (I still have this issue, although less since I lowered my PA value).

**Comment by killerline10168** [comment]
@Noisyfox I found out what the issue here is:

When role-based wipe speed is enabled, it basically copies what is typed in Outer wall speed. But if the printer needs to slow down because of minimum layer time, overhangs, etc. the wipe speed will still be what is set in the Outer wall speed and decouple from the actual print speed. 

The current printing speed is 30 mm/s because of low layer time.
![image](https://github.com/SoftFever/OrcaSlicer/assets/1812366/eeb47af7-491d-4ac0-8159-b2a94bf95ab1)


Wipe is performed, but at 98 mm/s because of the higher set Outer wall speed.
![image](https://github.com/SoftFever/OrcaSlicer/assets/1812366/a47bc009-8da0-4aa5-9834-0cd38e0afdcc)

Sounds like wipe speed doesn't calculate the actual speed to be used, but rather uses the same variable as is defined when setting Outer wall speed, or am I completely wrong?

**Comment by killerline10168** [comment]
Bumping so this doesn't close. Have any developers had the time to take a look at this?

**Comment by staal54a** [comment]
Has this issue been resolved or should it be re-opened?

**Comment by hotellonely** [comment]
It should be reopened. It's still a issue that is ruining some of the seam performance.
