### ISSUE TITLE
[CRITICAL] Corrupt gcode generating since 1.7.0

### ISSUE THREAD

**Issue by killerline10168** [SoftFever/OrcaSlicer#2245]
### OrcaSlicer Version

Release 1.7.0

### OS version

Windows 11 22H2

### Printer

Ender 3 Max 

### How to reproduce

1. Create new project
2. Import any model with overhangs (eg. Benchy)
3. Slice with custom default settings
4. Corrupt gcode generated, which if sent to printer to print, won't work.

### Actual results

![image](https://github.com/SoftFever/OrcaSlicer/assets/1812366/a1c22ce7-c450-431a-8189-89616d7bd034)

Results after slicing model. I have found that the underlying issue is due to "Slow down for overhangs", which if turned off becomes good again:

![image](https://github.com/SoftFever/OrcaSlicer/assets/1812366/9c483d22-d638-41a5-b354-186e5099a49d)

I am somewhat certain of this, as the changelog mentions an update to this function was done. I did not have these issues prior release 1.7.0 Beta and 1.7.0 Release.

### Expected results

Should slice like prior to the latest release (1.7.0)

### Project file & Debug log uploads

[3DBenchy.zip](https://github.com/SoftFever/OrcaSlicer/files/12740562/3DBenchy.zip)

Project file, but the bug is model-independent.

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by killerline10168** [comment]
Has any of the devs taken a look at this yet? I feel like this should be prioritized. A lot of people would probably like to use 1.7 or even 1.8_dev, but this bug forces us to revert back to 1.6.6.

**Comment by killerline10168** [comment]
Still nothing? I'm having the same issues on all 1.7.0 and all 1.8 releases (dev and latest beta). I've tried adjusting my settings but nothing resolves this bug (except for turning off Slowdown for Overhangs, which is a major downside).

**Comment by SoftFever** [comment]
Hey guys,

I can't reproduce the issue with the attached project file on latest nightly build.
Can you help verifying whether you can repro the issue with the attached project?

**Comment by Noisyfox** [comment]
Make sure outer wall speed (and many other speed/acc settings) is not 0. There is no guarantee that 0 is a valid value UNLESS the tooltips say so.

Will consider adding extra checks in the next release.

**Comment by SoftFever** [comment]
> Make sure outer wall speed (and many other speed/acc settings) is not 0. There is no guarantee that 0 is a valid value UNLESS the tooltips say so. It works in old releases doesn't mean it will continue to work forever.
> 
> Will consider improving this in the next release, by either making 0 a valid value or adding extra warnings/checks.

To add to that, for accelerations, 0 is allowed because it will fall back to the default acceleration. However, for speed settings, a non-zero value is required.

**Comment by killerline10168** [comment]
> Make sure outer wall speed (and many other speed/acc settings) is not 0. There is no guarantee that 0 is a valid value UNLESS the tooltips say so. It works in old releases doesn't mean it will continue to work forever.
> 
> Will consider improving this in the next release, by either making 0 a valid value or adding extra warnings/checks.

Last night I also noticed that setting the outer wall speed to a non-zero value solved the issue, which is great for now. 

Having everything at 0 / Auto is very practical and perhaps "decreases" time spent slicing files, but having a set outer wall speed often improves surface quality, so maybe a warning to not set this to 0 is fine to begin with. 

Maybe in future releases, you could allow 0 as a value, and then the slicer decides a fitting but constant speed depending on the volumetric flow (nozzle width, layer height), overhanging walls, size of 3D models (slow down if they're small?), etc. Just a thought, may be a bit difficult to code.

**Comment by lucascarvalho** [comment]
@SoftFever this change made is impossible to disable the Gap Fill, because you can't set the speed to 0 anymore.
