### ISSUE TITLE
Calculation of filament use for every type of printing part

### ISSUE THREAD

**Issue by Eldenroot** [SoftFever/OrcaSlicer#2252]
**Is your feature request related to a problem? Please describe.**
PS displays detailed info for used filament /weight, length, nicely visualized % of usage/

![image](https://github.com/SoftFever/OrcaSlicer/assets/778890/8b245c06-8008-4204-9f44-0e39efda062f)

**Which printers will be beneficial to this feature**
All

**Describe the solution you'd like**
Add these info (including first layer time) into Orca Slicer

![image](https://github.com/SoftFever/OrcaSlicer/assets/778890/63326df3-bf87-43aa-9676-da166fb247ba)

**Describe alternatives you've considered**
---

**Additional context**
----

**Comment by kylek29** [comment]
Agreed, that and the icon menu at the bottom of your PrusaSlicer screenshot are handy features of PS, would love to see those ported.

**Comment by Eldenroot** [comment]
Also I like the icons - it is easy to display/hide what you need... really handy!

**Comment by Noisyfox** [comment]
The used filament weight & length is on my todo list, though I personally find the icons very hard to use. I prefer the Orca's way so that I don't need to move my cursor to each of the icon to show the tooltip to find the one I need. I just can't remember which icon is which.

**Comment by Eldenroot** [comment]
Nice, I really like the visualization of the used filament for every "type".

Also I like the "first layer time" info... 

I am looking forward!

About icons - ok, makes sense :)
