### ISSUE TITLE
High RAM memory and battery consumption

### ISSUE THREAD

**Issue by deven-stinn** [SoftFever/OrcaSlicer#2257]
### OrcaSlicer Version

1.7.0

### OS version

macOS Sonoma 14.0

### Additional system information

M1 MacBook Pro - 16gb RAM - M1 Pro CPU

### Printer

All profiles and printers - FLSUN V400, KP3S, and Creality K1

### How to reproduce

1. Go to any printer and any profile
2. Load any model(more common with larger or more complicated models involving supports etc)
3. Slice

### Actual results

Computer produces a warning stating large amount of ram being used by single application(over 3gb being used), significant power consumption(10% battery in less than 5 minutes), and the slicer becomes incredibly slow and chunky. Other users seem to have similar issues with similar machines after asking on the Facebook group

### Expected results

Has been smoother and less power(battery and ram) hungry on other versions and other slicers aren't/can't producing the same issues.

### Project file & Debug log uploads

I don't have any logs or files. I will replicate the problem and upload something showing the message of error.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Noisyfox** [comment]
Do you have "Extra parameters on overhangs" turned on when this happened?

**Comment by deven-stinn** [comment]
No, the box is not checked for that setting

**Comment by Kyle0122** [comment]
I can confirm it can consume over 3200MB of memory on Windows, so the high RAM issue is not os related. It does not have performance or battery issues on Windows though.

**Comment by Noisyfox** [comment]
> I can confirm it can consume over 3200MB of memory on Windows, so the high RAM issue is not os related. It does not have performance or battery issues on Windows though.


Do you have "Extra parameters on overhangs" turned on when this happened?

**Comment by Kyle0122** [comment]
> > I can confirm it can consume over 3200MB of memory on Windows, so the high RAM issue is not os related. It does not have performance or battery issues on Windows though.
> 
> Do you have "Extra parameters on overhangs" turned on when this happened?
No, Extra parameters is off in all my profiles. The ram usage of orca slicer starts with 1790MB, and it gradually goes up, MB by MB. The rate is about 0.5 MB per second. So I had to restart the slicer during hour-long prints.

**Comment by Noisyfox** [comment]
> The rate is about 0.5 MB per second. So I had to restart the slicer during hour-long prints.

Wait... Are you saying the memory keeps increasing during the PRINTING not SLICING?

**Comment by Kyle0122** [comment]
Sorry, I tested it again, memory does not increase during printing, it only fluctuates about 200MB.
