### ISSUE TITLE
3mf settings lost when switching printer

### ISSUE THREAD

**Issue by dertester** [SoftFever/OrcaSlicer#2258]
Hey,

im new to orca / bambu studio.
I have installed both and set up my P1S.

Now when i load a 3mf with settings and printer profiles they often come with a X1C printer profile as default loaded.
I get extra lines (calibration) and a warnig sending this to my P1S like that.

Changing to my own printer profile:
=> Orca resets all provided setttings to default including colors.
=> Bambu keeps all settings just changes printer specific like calibration

Is this to be expected and can it be changed? Or an error on my side?

**Comment by Vahada3d** [comment]
this error costed me TONS of TIME reworking objects to the right color.
