### ISSUE TITLE
Mouse wheel invert direction option for zoom to be CAD like.

### ISSUE THREAD

**Issue by staffert** [SoftFever/OrcaSlicer#2271]
**Is your feature request related to a problem? Please describe.**

**Which printers will be beneficial to this feature**
E.g. Voron/Klipper based printer/etc...

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tlhintoq** [comment]
Sure would be nice if this were re-opened rather than have to make a new issue.

Mouse wheel `pull` should bring the object closer. (IE: Rolling towards user as if pulling the preview to you)

This is how all the modeling applications work, so consistency would be nice.

@SoftFever @Noisyfox
