### ISSUE TITLE
Nozzle temperature set in gcode without waiting option

### ISSUE THREAD

**Issue by jwg3** [SoftFever/OrcaSlicer#2277]
### OrcaSlicer Version

v1.7

### OS version

MacOS

### Additional system information

Mac Mini
3.2 GHz 6-Core Intel Core i7
Intel UHD Graphics 630 1536 MB
8 GB 2667 MHz DDR4

### Printer

Voron V0 Reprap on Duet

### How to reproduce

The generated gcode sets bed and nozzle temperatures with M190 and G10, respectively. M190 waits for temp to be achieved. G10 does not. 

### Actual results

This causes the print to start with the nozzle still heating up and not ready to extrude material.

### Expected results

Setting the nozzle temp should be done with M109 to wait for the temperature to be reached.

### Project file & Debug log uploads

[Archive.zip](https://github.com/SoftFever/OrcaSlicer/files/12775348/Archive.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by arsabe75** [comment]
Same issue in Windows with version 1.7.0
I added the following in Machine start G-code:

M140 S[bed_temperature_initial_layer] ; set final bed temp
M104 S[nozzle_temperature_initial_layer] ; set final nozzle temp
M190 S[bed_temperature_initial_layer] ; wait for bed temp to stabilize
M109 S[nozzle_temperature_initial_layer] ; wait for nozzle temp to stabilize

If I not add this instructions, orca slicer only adds to the gcode:

M190 S60 ; set bed temperature and wait for it to be reached
M104 S210 ; set nozzle temperature
