### ISSUE TITLE
Time Estimate Reaching Infinity When Added Filament Change on Layer

### ISSUE THREAD

**Issue by sabaatworld** [SoftFever/OrcaSlicer#2280]
### OrcaSlicer Version

1.7.0

### OS version

macOS 13.6

### Additional system information

Machine: MacBook Pro 16 inch 2023 (Apple M2 Pro)

### Printer

Bambu Lab P1S

### How to reproduce

1. Add primitive Orca Cube.
2. Slice file.
3. Drag to layer 3 and add filament change.
4. Slice again.

### Actual results

Note the almost infinite time. If this GCODE is sent to printer, it crashes the printer on filament change and causes extruder to clog.

### Expected results

Time estimate should be correct. Print should be successful.

### Project file & Debug log uploads

[OrcaCube.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/12775687/OrcaCube.3mf.zip)
[OrcaCube_PLA_35583992d72h49m.gcode.zip](https://github.com/SoftFever/OrcaSlicer/files/12775688/OrcaCube_PLA_35583992d72h49m.gcode.zip)
[debug_Sat_Sep_30_12_12_09_51645.log.0.zip](https://github.com/SoftFever/OrcaSlicer/files/12775690/debug_Sat_Sep_30_12_12_09_51645.log.0.zip)
<img width="1764" alt="Screenshot 2023-09-30 at 4 24 40 PM" src="https://github.com/SoftFever/OrcaSlicer/assets/2452471/d28b7a44-2c94-4922-a536-9680234f81f1">

### Checklist of files to include

- [x] Log file
- [X] Project file

**Comment by UsSuggester** [comment]
I have the same trouble.

In my case, when I use this option to filament change, my printer does the M600 (retraction) before starting the print, even before doing the skirt. I did check the starting G-Code again and its nothing like that on it.

At least "Add Custom G-code" works fine.

**Comment by shlagwuk** [comment]
same bug: https://github.com/SoftFever/OrcaSlicer/issues/689
