### ISSUE TITLE
Please add profile for Creality Ender 3 v3 SE

### ISSUE THREAD

**Issue by foobnix** [SoftFever/OrcaSlicer#2282]
https://www.creality.com/products/creality-ender-3-v3-se

**Comment by cime** [comment]
Maybe it helps - PR for Cura - https://github.com/Ultimaker/Cura/pull/16796/files

**Comment by joaogl** [comment]
I must admit I wish there was a few more profiles maybe 0.6mm nozzle as well, but never the less, I guess it can be closed:
https://github.com/SoftFever/OrcaSlicer/pull/3180/files
