### ISSUE TITLE
0.2mm~0.8mm Profiles for Prusa MK3s+ and Mini

### ISSUE THREAD

**Issue by ucirello** [SoftFever/OrcaSlicer#2286]
**Is your feature request related to a problem? Please describe.**
No a feature problem, but a project coordination problem. It seems that https://github.com/SoftFever/OrcaSlicer/issues/1333 slipped through the cracks, and the branch referred by @SoftFever is not accessible anymore (https://github.com/SoftFever/OrcaSlicer/tree/feature/consolidate_profile_naming)

**Which printers will be beneficial to this feature**
Prusa Printers

**Describe the solution you'd like**
I would like to see feature parity in terms of profile for Prusa Printers both in PrusaSlicer and OrcaSlicer

**Describe alternatives you've considered**
I have adapted a MK4 0.6mm profile to run on a MK3S+ Bear clone, and it worked OK. But in the past, I had better experiences when I copied from MK3S+.

**Comment by przygos** [comment]
It would be nice to have those profiles

**Comment by ucirello** [comment]
Ping?

**Comment by IkarusX1978** [comment]
I'm also interested to see the Prusa profiles back in Orca Slicer!

**Comment by SoftFever** [comment]
I will see if I can find some time to add them.
