### ISSUE TITLE
Feature Request: Local Project tab for tracking BOM, etc.

### ISSUE THREAD

**Issue by TexZeTech** [SoftFever/OrcaSlicer#2287]
**Is your feature request related to a problem? Please describe.**
Originally I raised a bug https://github.com/SoftFever/OrcaSlicer/issues/2136 and was under the impression that the project tab was broken. In that, it was mentioned that the Project tab is being modified to work with Bambus marketplace.

https://github.com/bambulab/BambuStudio/issues/2601#issuecomment-1733202269

> p2cardon MadMax389 The project can only open model files downloaded from the marketplace. Private model files are not supported. Please visit the following link. https://makerworld.com/

https://github.com/bambulab/BambuStudio/issues/2602#issuecomment-1733226500

> mast85-fm I apologize for the confusion. We have not removed these features. We have relocated the capability to add information and photos to our model marketplace. You can upload your files and add information and photos in the model marketplace.

**Describe the solution you'd like**
I would like to see the Project tab work as one would expect it to have worked in the older version so that if I have a job I can add the relevant information to it.

It could also have a slider in the window to swap between whatever is implemented in the future for Bambus marketplace and if Stealth mode is enabled that slider is removed so only local projects are loaded.

**Describe alternatives you've considered**
Using a custom DB (or spreadsheet) not related to the slicer.

**Comment by LupusTheCanine** [comment]
It would be great if the feature was brought back.
