### ISSUE TITLE
(Question, but maybe a bug) When filament color is black, Sonic Pad cannot show the thumbnail cause background is also black

### ISSUE THREAD

**Issue by UsSuggester** [SoftFever/OrcaSlicer#2290]
Since I do not own another klipper device than Sonic Pad and I don't know the behavior of other devices in this sense, I open this as a humble question/suggestion/bug.

Is it possible to create a contrast outline to the stl thumbnail when filament is black in Orcaslicer?

**Comment by Linnie73** [comment]
I think the rendering of black filament is bad anywhere in Orcaslicer (and Bambu Studio for that matter). Everything shows up as one black blob with no light. I always have to manually change the filament color to medium gray to even see what I am doing.
