### ISSUE TITLE
Add independent bridge infill pattern type

### ISSUE THREAD

**Issue by engelsheidt** [SoftFever/OrcaSlicer#2295]
In my opinion every printer´s output can be improved by allowing the user to select a different bridge infill pattern.

I would like to have an option in the slicer infill tab to specify a bridge infill pattern type.

**Comment by PhilBaz** [comment]
Hey, this is basicaly a duplicate of my existing issue, and I have more detail. can you close this please a comment on my issue.

https://github.com/SoftFever/OrcaSlicer/issues/1110
