### ISSUE TITLE
Feature Request: Spacing (from SuperSlicer)

### ISSUE THREAD

**Issue by evanphi** [SoftFever/OrcaSlicer#2297]
### Discussed in https://github.com/SoftFever/OrcaSlicer/discussions/2296

<div type='discussions-op-text'>

<sup>Originally posted by **evanphi** October  2, 2023</sup>
As I migrate over from Super, I find myself missing the more-precise way of setting extrusion width using the Spacing feature. 

When I model my parts with a certain wall width, I know I could go into SuperSlicer, input a value for my outer and inner walls to equal my modeled width, and the extrusion width would be automatically calculated. Thus a 2mm thick part wall would have 0.5mm spacing+overlap set for the outer and inner parameters, and I get 4 total extrusions of slightly more than 0.5mm to compensate for wall overlap. This cuts down on print time significantly as there is no "gap fill" or single arachne extrusion. 

Is this solved by using Arachne perimeter generators, where the arachne will automatically compensate for extrusion overlaps, and only working within the model's wall width? Or is it helped with the Precise Wall function enabled? I worry about the Precise Wall feature in my usage case (functional parts), as removing wall adhesion would negatively effect the overall strength of my parts. 

Or could the "Spacing" feature from SuperSlicer be ported over to Orca? With the UI as it is, it may be difficult to implement... but maybe even an auto-line-width feature where you can put in a single numerical value in mm for "wall thickness", near the "wall loops" value, again like in SuperSlicer. 

This is really one of the last features I am missing... That and a nice tool for migrating profiles. I know there is a script available, but I am not savvy to Perl. </div>

**Comment by inhabitworker** [comment]
I miss this feature too, though purely for aesthetic reasons in the first layer of a print, lessenening influence of bed surface on "look" or "finish". Unfortunately not a popular usage, though maybe less troublesome to implement given specificity
