### ISSUE TITLE
Allow global local variables in GCODE

### ISSUE THREAD

**Issue by dragosmiron** [SoftFever/OrcaSlicer#2299]
I would like to be able to set local and / or global variables in start / end gcode
<img width="618" alt="Screenshot 2023-10-02 at 23 24 14" src="https://github.com/SoftFever/OrcaSlicer/assets/353922/a297f4d2-9c5d-48d1-ad1b-0008c0e96815">

**Comment by Ocraftyone** [comment]
I could be wrong, but you may be able to use the jinja2 syntax to do this. Try the following syntax:
{% set variable_name = value %}

**Comment by Ocraftyone** [comment]
I am going to look in to this. Should be able to add this to the parser pretty easily.

**Comment by eoyilmaz** [comment]
I would love to be able to use Jinja2 templates in custom gcodes 👍  for this
