### ISSUE TITLE
Problems with printing internal threads

### ISSUE THREAD

**Issue by suizhenmin** [SoftFever/OrcaSlicer#230]
**Describe the bug**
For voron's test piece, an error occurs when printing internal threads, and macros have been added to printer.cfg.

**3mf File for This Bug**
[Thread_Test_2_x1_Rev1.zip](https://github.com/SoftFever/BambuStudio-SoftFever/files/10499486/Thread_Test_2_x1_Rev1.zip)

**Screenshots**
![1](https://user-images.githubusercontent.com/2957364/214569903-9e20d126-759e-4831-8110-f2bf48022b63.jpg)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 11

**Comment by SoftFever** [comment]
You might want to turn off the ` inner-outer-inner` or `outer first` mode for this model.
This is the kind of model that we shouldn't use that mode.

**Comment by Mario-vminion** [comment]
is see nothing in the option list for not using this mode

**Comment by SoftFever** [comment]
@Mario-vminion 
![image](https://user-images.githubusercontent.com/103989404/215243385-60970553-c5b4-4f91-a5cb-920cf934d3d2.png)
You should be able to see those options here.
