### ISSUE TITLE
Tag the slots to use

### ISSUE THREAD

**Issue by SwagDad99** [SoftFever/OrcaSlicer#2303]
**Is your feature request related to a problem? Please describe.**
It would be pretty cool to have little markers, like 'carrots', or asterisks above the AMS slots that have been assigned when the print was sent to the printer.  It would be a nice reference

**Which printers will be beneficial to this feature**
Bambu with AMS(s)

**Describe the solution you'd like**
Send the model to the printer from the slicer.  In the dialog where slots are assigned to the colors used in the model, note them, and then put a marker above the slots that will be used in the model printing process.

**Describe alternatives you've considered**
Write down, or just remember which colors will be used.  That works fine if the colors match what is displayed, but when I print the same model a bunch of different times, and instead of reslicing it with a new color in the prepare tab, I just send it to the printer again, and choose a different slot.  ie, if I want it to print in Red, but have it in Blue in the slicer, I just match the Blue to the Red filament in the AMS during the dialog selecting filaments.

**Additional context**
![AMS Colors](https://github.com/SoftFever/OrcaSlicer/assets/90676419/a8eeefda-5e37-4e94-9219-b4a900a521c2)

**Comment by Ocraftyone** [comment]
Since Bambu Labs uses proprietary printer firmware (the software that runs the printer, and thus the printer's display) there is no current way to implement that unless Bambu Labs themselves decides to implement that feature. I would suggest requesting that on the bambulabs/BambuStudio repo or by contacting Bambu Labs directly
