### ISSUE TITLE
An M141 S0 appear at the end of the gcode no matter what your printer is (1.8.0-dev)

### ISSUE THREAD

**Issue by cpasoft** [SoftFever/OrcaSlicer#2306]
### OrcaSlicer Version

1.8.0-dev

### OS version

Windows OS

### Printer

FLSUN V400

### How to reproduce

Just slice any model.

### Actual results

![imagen](https://github.com/SoftFever/OrcaSlicer/assets/29692062/a17fa762-10ba-412b-baef-d4deffd55c01)

### Expected results

The M141 must not be there

### Project file & Debug log uploads

Not necessary

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by igiannakas** [comment]
It is probably a residue from Bambu extending their code to cater for the x1E that will have a heated chamber.

**Comment by gbyleveldt** [comment]
Yeah, just noticed that as well this afternoon. Weird

**Comment by cpasoft** [comment]
> It is probably a residue from Bambu extending their code to cater for the x1E that will have a heated chamber.

This makes sense.

**Comment by discip** [comment]
Second that! 😊
