### ISSUE TITLE
Large Temperature Difference error on IDEX doesn't apply

### ISSUE THREAD

**Issue by KyGunsAndRadio** [SoftFever/OrcaSlicer#2311]
### OrcaSlicer Version

1.6.6

### OS version

Mint 21.2 and Windows 11

### Printer

Snapmaker J1

### How to reproduce

Select two different filament types (ex. ABS and TPU).
Error is displayed and plate cannot be sliced.

### Actual results

![image](https://github.com/SoftFever/OrcaSlicer/assets/89168030/2096bff3-7a0c-43ad-9d7b-92741ca4d7f2)

### Expected results

The printer is IDEX so different temperatures does not actually present any issue. Is it possible to suppress this error via profile setting, or a workaround to allow printing with IDEX?

### Project file & Debug log uploads

[ChainsawOilCapwOring-ABS-J1.zip](https://github.com/SoftFever/OrcaSlicer/files/12798507/ChainsawOilCapwOring-ABS-J1.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by awabom** [comment]
Encountered this too with my SV04.

(One workaround I can think of is fake temperature like 259 for PETG replaced by post-processing scripts.)
