### ISSUE TITLE
[FR] Import color data from 3mf and step files

### ISSUE THREAD

**Issue by enderextender** [SoftFever/OrcaSlicer#2323]
3MF and step files contain color data that could be used to display the parts with the associated color.  This would help with AMS users selecting colors for each object.  For 3MF files, windows Icon shows the color data so obviously it is there.  Step files reimported into Fusion also show correct colors, thus they contain color information as well.

**Comment by cgc007** [comment]
I realize this is stale, but I think this would be a very useful feature also. I'm working with very complex 3MF files that I import into Orca Slicer and thankfully through naming conventions of bodies in Fusion360 I'm able to color the bodies within the slicer relatively quickly, but if its possible to even group the bodies by color information stored in the 3MF file, that'd be a step forward.

**Comment by sumone-lol** [comment]
Why hasn't this picked up any traction? Onshape labels objects in composite objects as id1, id2, id3 etc so manually picking each one out in the slicer isn't feasible. This is particularly frustrating when one of my projects includes 50 different models with 100 parts each.
