### ISSUE TITLE
Prints in mid air - no "support needed" error shown

### ISSUE THREAD

**Issue by simonbuehler** [SoftFever/OrcaSlicer#2329]
### OrcaSlicer Version

1.7

### OS version

WIn 10

### Printer

Bambu Lab P1P

### How to reproduce

[clutch-roller.zip](https://github.com/SoftFever/OrcaSlicer/files/12818876/clutch-roller.zip)
slice the model, the overhang would need support but it just says "slice ok", path generated:

![grafik](https://github.com/SoftFever/OrcaSlicer/assets/78061/73992966-9d5e-4f30-b535-7cdf94cef04f)

### Actual results

print would fail obviously

### Expected results

warning: support needed

### Project file & Debug log uploads

[clutch-roller.zip](https://github.com/SoftFever/OrcaSlicer/files/12818923/clutch-roller.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by kylek29** [comment]
Is this with Arachne? I had a very similar model that did the same thing, I checked it in another slicer and it was the same (if I remember correctly).

**Comment by simonbuehler** [comment]
I just rechecked and it's both Arachne and classic
