### ISSUE TITLE
Invalid Invite - Discord server

### ISSUE THREAD

**Issue by bankh** [SoftFever/OrcaSlicer#2330]
### OrcaSlicer Version

1.7.0

### OS version

Ubuntu 20.04

### Printer

Ender3, Bambu P1P, ...

### How to reproduce

Click the Discord link on the repository.

### Actual results

Error received as follows:  
![image](https://github.com/SoftFever/OrcaSlicer/assets/9688867/07f65b56-8e69-4837-a8af-de6894a71b6e)

### Expected results

Access to discord server.

### Project file & Debug log uploads

![image](https://github.com/SoftFever/OrcaSlicer/assets/9688867/76ae31d7-e4f1-45ee-8f02-d0249b794fcc)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by SoftFever** [comment]
Thank you.
I have updated the link

**Comment by bankh** [comment]
It works. Thank you.

**Comment by itsmichaelk** [comment]
Need to re-open this - the link is expired again. Really would love to join the community.
