### ISSUE TITLE
New reference point setting

### ISSUE THREAD

**Issue by AWSb24** [SoftFever/OrcaSlicer#2335]
**Is your feature request related to a problem? Please describe.**
I moved from Cura to OrcaSlicer because I replaced my MK3S with X1C. Shame on me.
In Cura the reference point for users is in the middle of the bed. In OrcaSlicer the reference point is in the left front corner.
If I place the main object in the middle of bed and arrange multiple items by myself around the main object it is easier for me to calculate the offset in my head from the center instead of the left front corner.

**Which printers will be beneficial to this feature**
All?

**Describe the solution you'd like**
It would be great if you could implement an option to select the reference point.

**Additional context**

**Comment by Ocraftyone** [comment]
I don't see this happening soon. To help in the mean time, you can do relative moves using the move tool. Just add a plus or minus sign then the increment you want and it does the math for you.
