### ISSUE TITLE
Adaptive Meshing

### ISSUE THREAD

**Issue by discip** [SoftFever/OrcaSlicer#2340]
I searched but couldn't find if there was already a **Feature Request** on this topic.

So I'm proposing to add something like this to OrcaSlicer: **[KAMP](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging)**

**Comment by Ocraftyone** [comment]
It is possible that could be implemented, but what is the benefit of implementing it into the slicer if KAMP already exists. If you are using klipper, best practice is usually to use a start print macro in the slicer's custom gcode and to handle all of the start of the print (set temps, home printer, init bed mesh, purge nozzle).

**Comment by discip** [comment]
@Ocraftyone
Thank you for replying.
I managed to solve this.
