### ISSUE TITLE
Change type doesn't appear in right click menu

### ISSUE THREAD

**Issue by PhilBaz** [SoftFever/OrcaSlicer#2343]
### OrcaSlicer Version

current 

### OS version

win 10

### Additional system information

doesn't matter

### Printer

Voron 2.4

### How to reproduce

When adding a part as a 'negative' you get the 'change part type' menu item to change its type. This should be on the main right click menu. I can't seem to find it anywhere except the part created 'negative'

![Screenshot 2023-10-06 125622](https://github.com/SoftFever/OrcaSlicer/assets/21558241/4a9934dd-ae7a-4d93-8d35-43214ec8f11d)
![Screenshot 2023-10-06 125557](https://github.com/SoftFever/OrcaSlicer/assets/21558241/0ed84c64-3c5c-461e-97e8-0232800d8b55)

### Actual results

no otpion

### Expected results

Should be able to access this function multiple ways.

### Project file & Debug log uploads

![Screenshot 2023-10-06 125622](https://github.com/SoftFever/OrcaSlicer/assets/21558241/b09e13a5-81ce-43a1-9b72-29e10d01f8b5)
![Screenshot 2023-10-06 125557](https://github.com/SoftFever/OrcaSlicer/assets/21558241/4ca947a3-1a25-4e88-b64f-8dd5b4d65801)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by Ocraftyone** [comment]
It looks like that is the expected result. You are selecting the entire object in the first picture and an individual part in the second. There are no different types of objects, but there are different types of parts.

**Comment by PhilBaz** [comment]
@Ocraftyone 

Ahh, I see. It looks like the 'negative' object has to be created under an existing object like a parenting system. And it doesn't affect other objects. 

This is less flexible than a generalized system. But yeah this isn't a bug, it's just not nicely implemented, by bambu or prusa i imagine.

**Comment by Ocraftyone** [comment]
Yeah. I could see the benefit of having a sort global modifier, but many of the use cases could also be accomplished by converting multiple objects to multiple parts under a single object, then adding a modifier to that. And using the one object multi part system, you have to deliberately select which models you want to be modifiable, which could prevent mistakes.
