### ISSUE TITLE
Spiral vase mode produces extra bottom layers with 0.6mm nozzle

### ISSUE THREAD

**Issue by bitingsock** [SoftFever/OrcaSlicer#2344]
### OrcaSlicer Version

1.4.5(first introduced)/1.7.0/1.8.0

### OS version

Win11

### Printer

Custom Klipper

### How to reproduce

1: configure a printer with 0.6mm nozzle (and appropriate line widths), or use a preconfigured profile that uses 0.6mm (I tried several)
2: load a hollow model with no bottom and thin wall such as: 
[Part1.zip](https://github.com/SoftFever/OrcaSlicer/files/12836882/Part1.zip)
3: set `outer wall` width to >1
4: Enable spiral vase mode
5: Slice

### Actual results

The produced gcode contains a bottom infill layer and OrcaSlicer reports `Empty layers around bottom are replaced by nearest normal layers`
![Untitled](https://github.com/SoftFever/OrcaSlicer/assets/6302101/c096a620-bf9d-4470-aa2c-85b9a7849702)

If the bottom layers are then reduced to 0 and then resliced it almost fixes it but then it refuses to produce an internal brim.
![0](https://github.com/SoftFever/OrcaSlicer/assets/6302101/814ee55c-f033-45b7-b922-5fa0d9ca42c2)

### Expected results

A gcode similar to one sliced with a 0.4mm nozzle. A small external+internal brim and no `Empty layers around bottom are replaced by nearest normal layers` error.

### Project file & Debug log uploads

[debug_1layer.log](https://github.com/SoftFever/OrcaSlicer/files/12835153/debug_1layer.log)
[debug_0layer.log](https://github.com/SoftFever/OrcaSlicer/files/12835273/debug_0layer.log)

[Max volumetric speed test.zip](https://github.com/SoftFever/OrcaSlicer/files/12835154/Max.volumetric.speed.test.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by bitingsock** [comment]
With some testing it seems to fix itself by:
1: changing the `default` and `outer wall` line widths down any(?) amount
2: slice
3: change line widths back up

the bug seems to be triggered by turning on vase mode while `outer wall` is set >1

**Comment by Noisyfox** [comment]
It's not really caused by the vase mode, but rather by the fact that the model's shell thickness is less than the specified wall line width. You cannot print a wall that's are thinner than the extrusion width, hens the slicer thought the layers are invalid.

**Comment by bitingsock** [comment]
Ok, so the model has 1mm wall and It slices right with 1.6mm but not 1.7
If this is really the problem then the max flow calibration model might need to be fixed.

**Comment by Noisyfox** [comment]
> Ok, so the (part1) model has 1mm wall and It slices right with 1.6mm but not 1.7

Yeah it's slightly more complicated than just the thickness, but that's the major part. I'm still trying to figure out what exactly went wrong, as things like elephant foot could also contribute to the issue to some degree.

**Comment by bitingsock** [comment]
The issue realistically only presented itself with the max flow calibration. Perhaps the model should just be solid and sliced with 1 wall, 0 infill, 0 top, 0 bottom.
Still prevents inner brims but that is a preferable outcome over the extra layer.

**Comment by Noisyfox** [comment]
The proper solution is to use Arachne.

**Comment by bitingsock** [comment]
Yes but only to a reasonable extent. As per my 3mf, I am using Arachne. It is only tuned to compensate so much by default.

**Comment by Noisyfox** [comment]
> Yes but only to a reasonable extent. As per my 3mf, I am using Arachne. It is only tuned to compensate so much by default.

It should be good enough to perform the test I think.

**Comment by bitingsock** [comment]
The test "works" but is still producing improper slice.

**Comment by Noisyfox** [comment]
> The test "works" but is still producing improper slice.

It's "proper" as long as the test can be printed and achieve the goal of calibration. It doesn't need to be perfect.
Though for normal prints, we might need to improve the error message to clearly state the wall width is too thick for the print, and let the user to decide if proceed or change the parameter.

**Comment by Noisyfox** [comment]
Ah wait... I get what you mean. Arachne doesn't really solve the problem in this case. I thought it will because I'm running a modified version which I made some changes that (kinda) solve the problem. I'll do more tests.

**Comment by bitingsock** [comment]
> Though for normal prints, we might need to improve the error message to clearly state the wall width is too thick for the print, and let the user to decide if proceed or change the parameter.

I'd be fine with that, although the calibration script is still making such a scenario.

> It's "proper" as long as the test can be printed and achieve the goal of calibration (which I'm not sure if it does since I don't have a 0.6mm nozzle printer). It doesn't need to be perfect.

From my print and looking at the gcode (the script is seemingly only injecting G1 FXXXX at each layer) it achieves its goal.

**Comment by Noisyfox** [comment]
It was actually the `fix_slicing_errors` that mess the things up. I have it disabled on my local build and things looks much better.

**Comment by Noisyfox** [comment]
https://github.com/SoftFever/OrcaSlicer/blob/d54e5bd9d25ef117e2ca2f3288210181fe5865a2/src/libslic3r/PrintObjectSlice.cpp#L671-L673

This part will always offset the layer using the outer wall width, ignore things like variable line width and detect-thin-wall etc., which causes the problem.

**Comment by Noisyfox** [comment]
In my opinion, this `fix_slicing_errors` causes more errors than it claims to 'fix', we should just remove this part, just like what PrusaSlicer did a few months ago.

**Comment by bitingsock** [comment]
Separate issue but, could it also be a potential culprit of layers that are removed entirely?

**Comment by Noisyfox** [comment]
> Separate issue but, could it also be a potential culprit of layers that are removed entirely?

Exactly.
