### ISSUE TITLE
Creality K1 won't save Filaments

### ISSUE THREAD

**Issue by The760** [SoftFever/OrcaSlicer#2345]
### OrcaSlicer Version

1.7.0

### OS version

Windows 10

### Printer

Creality K1

### How to reproduce

1. Add Creality K1 as a printer
2. You'll see that only "Default Filament" is available
3. Edit this and save it as a new Filament
4. Close Orca and reopen. The Filament you saved will be gone, and you'll be left with "Default Filament"

### Actual results

![k1 default](https://github.com/SoftFever/OrcaSlicer/assets/20791883/4b4d66f6-689e-4b4d-83b1-12c29af1526c)

### Expected results

You should be able to save filament profiles as normal, and Orca should retain them. For whatever reason, this does not happen with the K1. It should also be noted that the K1 does not have any of the system preset filaments available either, even though I have it checked off in the Filament Selection menu.

### Project file & Debug log uploads

No project file or log for this.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Ocraftyone** [comment]
I have seen a similar issue like this in superslicer when the filament and printer are not properly marked as compatible with each other.

**Comment by timmeade** [comment]
I have hit this issue also if anyone has a workaround .   K1 MAX

**Comment by SoftFever** [comment]
@The760 @Ocraftyone 
Can I check if you created the custome filament based on "Default filament"?
If so, please try to select filament for Creality printer first.

**Comment by timmeade** [comment]
I was trying to Import the ones from the defaults.  They never show up.

**Comment by Ocraftyone** [comment]
Honestly, I'm not sure. What caused it for me was importing a prusaslicer config into superslicer. I just solved it by manually entering the config into SS.

**Comment by Ocraftyone** [comment]
Hmm. It should have asked you during the setup process if you wanted to add any filament types.
