### ISSUE TITLE
Supports wont turn off?

### ISSUE THREAD

**Issue by borris345** [SoftFever/OrcaSlicer#2353]
### OrcaSlicer Version

1.7.0

### OS version

windows 11

### Additional system information

2080ti
i9 13900k
64gb ddr5 ram

### Printer

bambu x1 carbon

### How to reproduce

turn supports off still there.
turn supports on there obviously
turn supports off still there

support painting removed them

### Actual results

supports stay on

### Expected results

supports to turn off

### Project file & Debug log uploads

https://pasteboard.co/fEwXP2Fa1FYP.png
https://pasteboard.co/B9WmJgtquF5E.png

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Noisyfox** [comment]
Check your per-obj settings

**Comment by borris345** [comment]
What am I looking for that I may have accidentally changed?

**Comment by Noisyfox** [comment]
![image](https://github.com/SoftFever/OrcaSlicer/assets/1537155/7ff099fc-b740-4dc2-808c-ab149e6ce9d5)
Check if you have per-obj support turned on.

**Comment by borris345** [comment]
cheers that was the prob. there was a lock on it. thanks
