### ISSUE TITLE
Update Filename Format to pass forward slashes

### ISSUE THREAD

**Issue by poppinfresh69** [SoftFever/OrcaSlicer#2354]
Want to send sliced files to specific directories in Klipper (printer 1, printer2, etc.). Manually adding the directory information ie. /E3V2/some_file_name works great in the Print window. The problem is that you have to manually change the directory every time you change printers as it does not tie to a print profile. Trying to add the directory information in the Filename format window is ignored as it does not appear to like the forward slashes.

**Which printers will be beneficial to this feature**
Klipper

**Describe the solution you'd like**
Being able to add the directory information in the Filename Format window and having it pass to the file name would fix this issue as it would be tied to what is saved in the filament profile. Changing filament profiles would also change the directory info.

**Describe alternatives you've considered**
If the directory info could update automatic from the printer profile it would be ideal, but my proposed seems like the quickest and easiest fix for now.

**Additional context**
![image](https://github.com/SoftFever/OrcaSlicer/assets/142692274/d2485fb5-d93f-4c54-8642-f040b5cb175f)

**Comment by Ocraftyone** [comment]
I'll look into this when I get a chance. Doesn't seem like it would be too hard to implement.

**Comment by Eldenroot** [comment]
Still relevant
