### ISSUE TITLE
Improve multicolour on a single extruder machine

### ISSUE THREAD

**Issue by cpasoft** [SoftFever/OrcaSlicer#2356]
Many of us use Orca with multiple filaments on single extruder printers. Typically, we would edit the G code for the filament change with a pause code and then perform the manual filament change.

However, we have a problem because Orca adds an M600 command after the initial heating phase, together with the T0, T1...Tx tool change codes, which we do not need as we only have one extruder.

![imagen](https://github.com/SoftFever/OrcaSlicer/assets/29692062/42e0d69e-4e74-4050-be7a-6a9a9ce10e4a)

![imagen](https://github.com/SoftFever/OrcaSlicer/assets/29692062/ab337c45-f85d-4811-81a4-160c77e52a0d)

![imagen](https://github.com/SoftFever/OrcaSlicer/assets/29692062/5553f946-230f-451c-b85b-ce9868f3c4f1)

Therefore, I suggest that when you check the single extruder option, OrcaSlicer automatically prevent the generation of the initial M600 command and the tool change codes (T0, T1...Tx). This is important because on some machines it causes errors that render them non-functional. For example, it causes problems with Bambu printers without AMS.

![imagen](https://github.com/SoftFever/OrcaSlicer/assets/29692062/8ef375d6-28c5-4efd-ab8c-1d3cf0219f78)

Sorry, the screenshot is in Spanish, but it says something like "Could not get the AMS mapping table; click retry to continue".

**Comment by cpasoft** [comment]
*Note: For the first M600 there is a workaround...
You must write on the "Change filament G-Code" section:
`{if layer_num > -1}M600{endif}`
instead of a single M600.

There is not workaround for the Tx codes right now.

**Comment by cpasoft** [comment]
For the second problem, I've written a little script in Windows to solve it.

Just create a Remove_T.cmd (or something similar) and then call it from the postprocessing script as:
"C:\wherever it is\Remove_T.cmd"

<@echo off
if "%~1"=="" (
  echo Uso: %0 archivo
  exit /b 1
)

findstr /V /R /C:"^T[0-9]" "%~1" > "%temp%\temp.txt"
move "%temp%\temp.txt" "%~1" > nul
>

Anyway, It should be solved by Orca itself.

**Comment by PegasusSeiya12** [comment]
It would be a notable improvement and an advantage for this laminator over the competition.

**Comment by waxall** [comment]
I am using my single toolhead klipper machine with a PAUSE command to swap filaments but when when I RESUME the print, I get an error like "Extrude only move too long ( 92233720368547.766mm vs 200.000mm)" I've also set my M83 and G92 E0 commands but that error keeps being thrown up. 

Was wondering if this is related to the T0 issue

**Comment by cpasoft** [comment]
Tested and working!!!...

Thank you all... :-)
