### ISSUE TITLE
Print order for the first layer

### ISSUE THREAD

**Issue by guestisp** [SoftFever/OrcaSlicer#2358]
I've asked the same months ago on superslicer (or prusaslicer, don't remember)
I don't see any single reason why, on first layer (the one attached to the bed, obviously) printing inner -> outer would be better than printing outer -> inner.

Usually, on first layer you want the max adhesion, and you can get this priting longer lines. printing from the inner lines are obviously shorter than printing from the outer (in examples, holes: an M3 hole is more stable if printed from the outside)

So, why not adding a flag to print external perimeters first on first layer ?

**Comment by Eldenroot** [comment]
+1

**Comment by trebory6** [comment]
Ok, am i taking crazy pills or is this common sense?

I'm having first layer adhesion issues, and the parts that print outer perimeter -> inner perimeter on the first layer have a 100% success rate over the parts that print inner perimeter -> outer perimeter. 

Unfortunately there is no way to control this manually. So I literally have to slice my plate with multiple objects, then print it then cancle the objects that print inner -> outer. 

If I delete the ones that print inner -> outer before I slice it, it'll just randomly select some other objects to print inner -> outer. It's completely random for some reason.

**Comment by malventano** [comment]
I recently ran into this when troubleshooting an elephant foot issue on first layer. The print order of the first layer was not honoring other layer settings (not even inner/outer/inner). As a compromise/workaround I had to enable 'only one wall on first layer', as it was the only way to get the outer wall to print first, but this has other negatives, as the user might not want only one wall there. That switch solved the elephant foot issue as the outer was printed first and was not pushed out by the preceding layers.

**Comment by TeaRex-coder** [comment]
+1 this should be a thing

**Comment by Mortereza** [comment]
@guestisp @Eldenroot @trebory6 @malventano @TeaRex-coder 
if you wanted a automated fix so you wont get forced to add the modifier on every item on the plate you can also use only one wall on first layer and the concentric infill pattern for the first layer
having the feature to be able to use a different wall printing order would be far superior but this is a band-aid fix i thought i should share
