### ISSUE TITLE
Creating profiles from scratch

### ISSUE THREAD

**Issue by ParadiseFallen** [SoftFever/OrcaSlicer#2365]
I want to have ability add profile from scratch. Right now im bounded to `system` profiles. And i need to build on top of them mine.
It would be nice to add ability to make custom root profile and inherit them later.

Same with filaments. Need ability to add pack of filaments when we can craete our own and use em across printers / projects.

Processes must be bounded to printer but also created and modified.
Right now we cant modify build it presets.

**Comment by Apotrox** [comment]
+1, i just want to create filament profiles. Not tie them to anything. maybe being able to create copies for different colors/variants. Don't make me tie them to a printer or system preset. very silly.

**Comment by ParadiseFallen** [comment]
reopen
