### ISSUE TITLE
Addition of custom printers

### ISSUE THREAD

**Issue by broncosis** [SoftFever/OrcaSlicer#237]
**Is your feature request related to a problem? Please describe.**
No latest version seems to do everything no errors so far 
I am still waiting on my X1cc so I thought I would jump in and see what I can do with the bambu studio 
with my current machines 

**Describe the solution you'd like**
I would like to add my Rail core printer  or possibly just have ability to import prusa configs
**Describe alternatives you've considered**

a decent base config for a railcore is Maintained by a great guy here 
https://github.com/JohnOCFII/RailCore/tree/master/slicers/PrusaSlicer
its not my config but its a solid base config

**Comment by hliebscher** [comment]
you can use for testing any custom printer and take your Prusa startcode and size
