### ISSUE TITLE
Hostname resolution fails when trying to send file to printer

### ISSUE THREAD

**Issue by XoBoR** [SoftFever/OrcaSlicer#2372]
### OrcaSlicer Version

1.7.0

### OS version

Windows 11

### Printer

Generic Klipper Printer

### How to reproduce

![Screenshot 2023-10-09 143532](https://github.com/SoftFever/OrcaSlicer/assets/38147819/ed6b2547-2a22-4c50-b5b8-8bcf295b546f)

This is my configuration, the "Test" works as seen in the screenshot

### Actual results

![Screenshot 2023-10-09 143607](https://github.com/SoftFever/OrcaSlicer/assets/38147819/fec67a04-e2b3-487e-b750-f5a0c821652c)
When I then try to upload a File I get this error. 

### Expected results

Im 100% sure the hostname resolution is working. Uploading from PrusaSlicer with the same host settings works. 

### Project file & Debug log uploads

This is not related to a project and no debug log file is generated. 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Michal-Szczepaniak** [comment]
It's FQDN even not just hostname (hostname would be aspire, then via search names it would have to resolve FQDN via local dns server), if FQDN doesn't work how can domains even work

**Comment by Michal-Szczepaniak** [comment]
Via further testing we've established that there are two domain names (hence i was pointing out FQDN). The router has domainname `fritz.box` while some devices, in this case host author is trying to reach has `local` domain name. Now, we assume that mDNS is in action, if you resolve through dns server, so router, it will use the `fritz.box` and the `local` will fail, then mdns should resolve the .local successfully. It would seem that when testing connection the mdns is used but when sending print the mdns is not used.

Also when omitting the domain name, via searchnames provided by dns server i assume from router, the searchname is `fritz.box` and resolution also doesn't fail

**Comment by ShaunDwyer** [comment]
I'm also seeing this issue after upgrading to 1.7.

I've always used the multicast dns entry 'mainsail01.local'.

the "Device" tab with the embedded browser has no problem, but the issue appears to be limited to curl.
If I set IPv4 address to connect to, it works, but hostname resolution for the gcode upload fails.

Perhaps there is a bug in the curl library?

mainsail01 and mainsail01.local both resolve to a local ipv6 address from command prompt.
