### ISSUE TITLE
USB device eject doesn't work in macOS Ventura

### ISSUE THREAD

**Issue by martin-badin** [SoftFever/OrcaSlicer#2375]
### OrcaSlicer Version

1.7.0

### OS version

macOS Ventura 13.6

### Printer

Elegoo Neptune 3 Plus

### How to reproduce

1. Import any STL file
2. Click Slice button
3. Click Export G-code file
4. Try to eject USB device

### Actual results

USB device eject doesn't work

### Expected results

USB device eject should work

### Project file & Debug log uploads

-

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by discip** [comment]
Doesn't work in Manjaro either.

Furthermore, if you try to eject the drive using the dedicated button after saving a g-code that was already on the disk **(Content is irrelevant, the name matters!)**, its content will be erased! 😲 🤷🏻‍♂️

**Comment by enotskellington** [comment]
I haven't found that it is erased (on Debian 12/Gnome) but I do find that eject seems to hang and nothing happens. For now I have switched to 'open in folder' > eject from there.

**Comment by discip** [comment]
@SoftFever @Noisyfox

Any solution for this yet?

**Comment by orgoj** [comment]
On Lubuntu eject doesn't work on. Prusa slicer eject is fine.

**Comment by SoftFever** [comment]
will take a look,
Haven't been using SD card for years, lol

**Comment by enotskellington** [comment]
I guess I should add this is an SD card using a USB adapter. But as others mentioned PS works.

Dec 24, 2023 1:58:35 AM SoftFever ***@***.***>:

**Comment by discip** [comment]
Any progress so far? 😊

**Comment by discip** [comment]
@SoftFever
Any progress so far? 😊

**Comment by discip** [comment]
@SoftFever
@Noisyfox
@igiannakas
Has anyone looked into this yet?
Would be great if this could finally be solved.

**Comment by myxxmikeyxx** [comment]
I am also having this problem on MacOS Sonoma 14.2.1 (23C71) (Intel).
It just keeps saying ejecting but never does.

**Comment by myxxmikeyxx** [comment]
@discip I had not tried it. I downloaded the nightly build and it did work for ejecting the usb! Thank you!

**Comment by discip** [comment]
You are welcome.
However, you should thank the guys who fixed this. 😊

**Comment by discip** [comment]
@martin-badin
As this seems to be fixed, please test and if it works for you as well, please don't forget to close. 😊

**Comment by martin-badin** [comment]
@discip Thank you. Currently, I am using wireless connection. So I believe it works. I am closing this issue.
