### ISSUE TITLE
Mouse Ears fill the inside of Text

### ISSUE THREAD

**Issue by Fragmon** [SoftFever/OrcaSlicer#2388]
### OrcaSlicer Version

1.7.0

### OS version

Windows 10

### Additional system information

non hardware related

### Printer

Voron 2.4 350mm

### How to reproduce

Slice an object with Text.
Activate Mouse ear

### Actual results

The text will be filled with brim. If you have only one layer text, you cant remove that.

### Expected results

No mouse ears in the Text

### Project file & Debug log uploads

![sliced with ear](https://github.com/SoftFever/OrcaSlicer/assets/50713890/3043c0bc-f1fb-42dd-902a-bef94b6ac7db)
![sliced without ears](https://github.com/SoftFever/OrcaSlicer/assets/50713890/50dab026-c4c5-4d5b-afb5-9cc80270f957)
[debug_Tue_Oct_10_18_32_23_11072.log](https://github.com/SoftFever/OrcaSlicer/files/12865673/debug_Tue_Oct_10_18_32_23_11072.log)
[gehause_oberteil-v39.zip](https://github.com/SoftFever/OrcaSlicer/files/12865676/gehause_oberteil-v39.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by Noisyfox** [comment]
Currently brim ears are applied to both inner and outer region. I was thinking if we should disable brims for any single-layer (or maybe more than 1 layer?) regions to avoid brim fusing with bridges.

**Comment by Fragmon** [comment]
> Currently brim ears are applied to both inner and outer region. I was thinking if we should disable brims for any single-layer (or maybe more than 1 layer?) regions to avoid brim fusing with bridges.

Would it be possible to introduce a tool, similar to the support feature, that allows users to designate areas where a brim shouldn't be generated?

**Comment by Noisyfox** [comment]
I think it's possible to add some sort of modifier that prevents creating brims.

**Comment by Fragmon** [comment]
It's puzzling that when 'auto brim type' is selected, Orca doesn't generate it internally.
![brim](https://github.com/SoftFever/OrcaSlicer/assets/50713890/7b3327e4-3b74-4405-a1a8-301d487da3a3)

**Comment by Noisyfox** [comment]
Yeah I know it's a bit puzzling.

**Comment by Noisyfox** [comment]
Oh and by the way, auto brim will NEVER generate inner brims.

**Comment by Fragmon** [comment]
> Oh and by the way, auto brim will NEVER generate inner brims.

Can i deactivate inner brims with mouse ears?

**Comment by Noisyfox** [comment]
Not at the moment. Will consider allowing so.

**Comment by doudar** [comment]
Id like this re-opened because I have the same issue with nylon prints, where I have recessed text and need mouse ears to keep the nylon from warping off the plate. Brim works, but it's very difficult to remove from nylon prints.

**Comment by crookz** [comment]
same, it makes ears useless for most of my current prints (with text)

**Comment by icariantk** [comment]
+1 i just need the ears only on a single part of the object, a blocking cube could be enought to do that at least.
