### ISSUE TITLE
Tree support generate filament change on supports

### ISSUE THREAD

**Issue by Fragmon** [SoftFever/OrcaSlicer#2389]
### OrcaSlicer Version

1.7.0

### OS version

Windows 11

### Additional system information

non pc related

### Printer

Voron 2.4 350..

### How to reproduce

Yuu change the colour on the first layer
You activate tree support
Orca generate filament swaps on supports on layer 3 and 5

### Actual results

It generates a few layer with the second colour only on the support

### Expected results

The filament should only change between layer 1 and 2

### Project file & Debug log uploads

![support](https://github.com/SoftFever/OrcaSlicer/assets/50713890/ebb5ea9d-e8a3-47e7-9217-38bda47a7d11)
[gehause_oberteil-v39.zip](https://github.com/SoftFever/OrcaSlicer/files/12866411/gehause_oberteil-v39.zip)
[debug_Tue_Oct_10_18_32_23_11072.log](https://github.com/SoftFever/OrcaSlicer/files/12866417/debug_Tue_Oct_10_18_32_23_11072.log)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by Noisyfox** [comment]
It's because layer 2-6 all have 2 colors:
![image](https://github.com/SoftFever/OrcaSlicer/assets/1537155/d96a8cbb-a3ed-4a9f-acd9-45013c1c2f3f)
