### ISSUE TITLE
filament_start_gcode Parsing error at line 6: Not a variable name (activate_air_filtration)

### ISSUE THREAD

**Issue by vidarw** [SoftFever/OrcaSlicer#2396]
### OrcaSlicer Version

1.7.0

### OS version

macOS 14.0

### Additional system information

df

### Printer

Bambu Lab X1C

### How to reproduce

1. Download add north profile for X1 (PETG or E-PLA)
https://addnorth.se/knowledge/articles/how%20to%20print%20on%20bambu%20lab%20printers
2. Import using File... -> Import -> Import Configs
3. Select and slice any model

### Actual results

Slicing fails with error

`Failed to generate G-code for invalid custom G-code.
filament_start_gcode Parsing error at line 6: Not a variable name
{if activate_air_filtration[current_extruder] && support_air_filtration}
    ^
Please check the custom G-code or use the default custom G-code.`

### Expected results

Slicing work properly

### Project file & Debug log uploads

Project file attached with printer profiles:

[Archive.zip](https://github.com/SoftFever/OrcaSlicer/files/12880791/Archive.zip)

[DebugLog.zip](https://github.com/SoftFever/OrcaSlicer/files/12880885/DebugLog.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by SoftFever** [comment]
Hi @vidarw 

1.7 doesn't support this variable.
You will need to use 1.7's filament_start_gcode 
Or you can also try the nightly build which support this.
