### ISSUE TITLE
bridges printed in mid air

### ISSUE THREAD

**Issue by dachu02** [SoftFever/OrcaSlicer#2398]
### OrcaSlicer Version

1.7.0

### OS version

win11

### Printer

Bambu p1p

### How to reproduce

[Wooden_bridge-top.zip](https://github.com/SoftFever/OrcaSlicer/files/12885875/Wooden_bridge-top.zip)
attached model sliced in PrisaSlicer and Orca gives 2 different results (correct one in Prusa, wrong in Orca)

Brisges are printed in mid air and not connected to the perimeters, see picture below (left prusa, right orca)

I was trying to play with different settings but cant achieve results as in prusa.

### Actual results

![prusa-orca](https://github.com/SoftFever/OrcaSlicer/assets/17782825/d8e82efd-1456-4c8e-be14-19cf1361d4aa)
on the right

### Expected results

![prusa-orca](https://github.com/SoftFever/OrcaSlicer/assets/17782825/d8e82efd-1456-4c8e-be14-19cf1361d4aa)
on the left

### Project file & Debug log uploads

[Wooden_bridge-top (2).zip](https://github.com/SoftFever/OrcaSlicer/files/12885900/Wooden_bridge-top.2.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by igiannakas** [comment]
Try the latest nightly. It has a number of improvements in bridging and internal infill handling.

**Comment by dachu02** [comment]
i'm using 17.0, is there a newer version?

**Comment by igiannakas** [comment]
Yes, the nightly builds, 1.8 beta 1. You can find it on the actions tab above.

**Comment by dachu02** [comment]
checking, thanks

**Comment by dachu02** [comment]
![image](https://github.com/SoftFever/OrcaSlicer/assets/17782825/cc512645-472d-492b-b22f-00fbd8e8e614)
works perfect, as expected :)
thanks guys
