### ISSUE TITLE
Tree support options seem to have duplicates, and incorrect tooltips?

### ISSUE THREAD

**Issue by nirurin** [SoftFever/OrcaSlicer#2400]
### OrcaSlicer Version

1.7.0

### OS version

Windows 11 22h2

### Printer

BambuP1S

### How to reproduce

Use orcaslicer tree settings

### Actual results

Trying to figure out which tree options are best to use, and it's... convoluted at best lol. 

The tooltips seem to say that slim and organic will both reduce material by culling branches (but doesn't seem to say why both options exist), and that hybrid will do a mix of trees and normal supports. Except it seems (in my testing) to only do trees. 

It doesn't say what strong does, though I assume it's obvious. The bambu wiki says strong is the old default, so I guess strong = normal, and organic and slim both do weaker trees than normal. 

It also says default is organic, with no explanation as to why both "default" and "organic" options exist if they're the same thing. Also the Bambu wiki says that Hybrid is the default... so has orca changed the default from hybrid to organic? And if so... why does default also exist still? 

So that's 3 variations (Default, Organic and Slim) that are all the same, with a 4th (hybrid) that is .... currently also the same, as it doesn't seem to be doing the hybrid part (this may be user error though, I'll continue testing this and report back). 

Can you at least let me know what the "default" option actually is, and delete all the extra options that are just duplicates? 

### Expected results

See above

### Project file & Debug log uploads

Doesn't need one

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Noisyfox** [comment]
The existence of the `default` option is to avoid unnecessary settings change when switching between tree support and normal support, especially when simple mode is used.

Slim tree and organic tree are very different, I'm not sure why you didn't notice the difference but check the screenshots here https://github.com/SoftFever/OrcaSlicer/pull/1938
