### ISSUE TITLE
Port add sacrificial bridge layer under holes from SS

### ISSUE THREAD

**Issue by meltiseugen** [SoftFever/OrcaSlicer#2402]
Reference to this SS feature in Ellie's tuning guide:

https://github.com/AndrewEllis93/Ellis-SuperSlicer-Profiles#superslicer-option

This would help a lot with not having to deal with supports under holes.

example of how it would work:
![image](https://github.com/SoftFever/OrcaSlicer/assets/18147746/6a3d562e-0728-46c2-867a-11c6c78c305d)
![image](https://github.com/SoftFever/OrcaSlicer/assets/18147746/b7fc3cfa-a709-4451-a534-2fb4b94d7eef)
![image](https://github.com/SoftFever/OrcaSlicer/assets/18147746/1c2b9e4f-9a07-49af-8b65-96731fc57c74)

**Comment by Eldenroot** [comment]
+1
