### ISSUE TITLE
Crashing at start

### ISSUE THREAD

**Issue by stiffconcepts** [SoftFever/OrcaSlicer#2406]
### OrcaSlicer Version

V 1,7,0

### OS version

windows 10 

### Printer

Ratrig Vcore 3.1

### How to reproduce

No issues at first. I was doing PA calibration for new filament and slicer crashed. Tried to reopen slicer and received following errors and slicer wont load.
![Screenshot (2)](https://github.com/SoftFever/OrcaSlicer/assets/121734294/e72f4187-54dd-49ae-8a76-79be7b598033)
![Screenshot (1)](https://github.com/SoftFever/OrcaSlicer/assets/121734294/797119d6-bd21-429b-a369-af9370cc454c)

### Actual results

slicer fails to open. i have deleted and redownloaded several times even tired v 1.6.6 and same issue. 

### Expected results

need help.

### Project file & Debug log uploads

none

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Ocraftyone** [comment]
Please provide the crash dump logs

**Comment by Ocraftyone** [comment]
And if you just want a semi quick fix. Just delete %appdata%/Orcaslicer. Be warned, **this will delete all custom settings!** It will be as if you just installed orca for the first time
