### ISSUE TITLE
No vertical seam

### ISSUE THREAD

**Issue by gogsi1** [SoftFever/OrcaSlicer#2407]
**Which printers will be beneficial to this feature**
For everyone

**Describe the solution you'd like**
So that the seam is vertical.

Seam on the edge: 
![2023-10-13 195217](https://github.com/SoftFever/OrcaSlicer/assets/36478778/70abc5b0-9fc4-4ed7-a42e-0b622655e3e7)

Seam at the back:
![2023-10-13 195654](https://github.com/SoftFever/OrcaSlicer/assets/36478778/60f3c66b-3f50-4153-ba69-451e9c0c9e66)

**Comment by gogsi1** [comment]
> Did you mean **_vertical_** (perpendicular to the build-plate) instead of _horizontal_?
Yes, you got it right. I made a little mistake

**Comment by discip** [comment]
Just to clarify:
So what you want is an absolutely vertical seam (90°) right?

**Comment by igiannakas** [comment]
Try the latest nightly. It has the option to set a straight seem that is vertical to the build plane.
