### ISSUE TITLE
意料之中的，耗材流量k值又tm全搞没了，每次更新都有这种卵事，真不知道在搞什么

### ISSUE THREAD

**Issue by six00** [SoftFever/OrcaSlicer#2409]
### OrcaSlicer Version

1.7.0

### OS version

win10

### Printer

p1p

### How to reproduce

1.6.6下载压缩包版1.7.0

### Actual results

耗材流量比例 k值丢失

### Expected results

原封不动

### Project file & Debug log uploads

..

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by SoftFever** [comment]
Hi
这是因为每次拓竹的插件更新都会删除就有配置然后从云中重新更新配置
你重启软件后配置应该会回来。
如果还没有，可以尝试登出账号然后登录回来

**Comment by six00** [comment]
我能理解拓竹有这个功能，但是如果几个版本下来发现这东西并不靠谱的话，我建议直接屏蔽了，改成如需同步在设置中手动点击同步才第一次从云中更新，拓竹那个哪是更新啊，直接给全复写了，好歹也给留个backup回滚吧
