### ISSUE TITLE
Softfever 1.4.3 - PA Lines are missing since new Version

### ISSUE THREAD

**Issue by tommy536** [SoftFever/OrcaSlicer#241]
I didnt know its a bug or a feature.

When i began to setup a PA Test. Slice it, there comes out a very short print within 3 Seconds and the micro line. There are no PA lines showing. I came from 1.4.2. I tested it backwards with 1.4.2 and there it works normaly.

**Comment by SoftFever** [comment]
Hi,
What printer did you use? Did you change any settings in the PA dialog? 

if possible, share the gcode file will be very helpful

**Comment by tommy536** [comment]
Hi,
attached the Gcode File. I am using a Voron 2.4.

![image](https://user-images.githubusercontent.com/45936061/215152924-0b5d3d37-2a85-4292-8be8-97c04c2c7038.png)

![image](https://user-images.githubusercontent.com/45936061/215152987-5b252259-3d0b-40f8-b6f8-35bcdc697d35.png)

[pressure_advance_test_PA-CF_3s.zip](https://github.com/SoftFever/BambuStudio-SoftFever/files/10521430/pressure_advance_test_PA-CF_3s.zip)

**Comment by hardtech87** [comment]
i have the same problem. X1c Combo.
version 1.4.2 works fine

**Comment by hliebscher** [comment]
the arm64 version at Mac 13.1 Ventura is working i think the x86_64 Mac version needs rebuild with clear build directory

**Comment by hliebscher** [comment]
@SoftFever PA Test works only in ENGLISH LANGUAGE ;-) in German no output !!!!!

**Comment by SoftFever** [comment]
Ouch.
Looks like only English and Chinese works.
I will note it in the release notes for now while I'm investigating the issue.

> @SoftFever PA Test works only in ENGLISH LANGUAGE ;-) in German no output !!!!!

**Comment by dimitrigerber** [comment]
![image](https://user-images.githubusercontent.com/56005690/215270361-1eeb8cb7-653b-4ea3-9fe0-498d14f8181b.png)


Hello, the window ist pretty small so I cant see all values.

**Comment by SoftFever** [comment]
> 

Which OS and resolution do you use?

**Comment by dimitrigerber** [comment]
![image](https://user-images.githubusercontent.com/56005690/215272608-7329ce5a-165f-4a71-9385-1cee03e4be0b.png)

**Comment by dimitrigerber** [comment]
Windows resolution 3000x2000 and 200% scaling

**Comment by SoftFever** [comment]
> 

Ah, okay, DPI stuff.
Will fix it in the coming hotfix release

**Comment by SoftFever** [comment]
Thanks for reporting the bug.
The problem has been resolved in the latest hotfix release.

**Comment by hliebscher** [comment]
@tommy536  if is fine for you can you close the bug ?
