### ISSUE TITLE
Integrate A1 Mini Support

### ISSUE THREAD

**Issue by abstractFlo** [SoftFever/OrcaSlicer#2411]
**Is your feature request related to a problem? Please describe.**
It would be cool, if you update orca with the latest bambu studio profiles for A1 Mini

**Which printers will be beneficial to this feature**
Bambu A1 Mini

**Comment by SoftFever** [comment]
Hi,
It's available in dev branch already.

**Comment by abstractFlo** [comment]
Ahhh, thank you :)

**Comment by PixelKaje** [comment]
> Hi, It's available in dev branch already.

How exactly does one find that to download?
