### ISSUE TITLE
Add ability to toggle gap filling

### ISSUE THREAD

**Issue by wight554** [SoftFever/OrcaSlicer#2414]
**Is your feature request related to a problem? Please describe.**
When printing TPU, the proccess of gap filling creates small bulges that are being covered by next layer of solid infill later on and makes the top wall not smooth. I believe  reducing extra movements will improve this experience a lot.

**Which printers will be beneficial to this feature**
Any

**Describe the solution you'd like**
Port from PrusaSlicer https://github.com/prusa3d/PrusaSlicer/pull/5999

**Describe alternatives you've considered**
Printing slower with higher retractions, but not really the best option for TPU. I also tried settingn gap infill speed to 0 as per https://forum.prusa3d.com/forum/original-prusa-i3-mk3s-mk3-hardware-firmware-and-software-help/can-i-turn-off-gap-filling-in-the-prusa-slicer/ but it didn't work

**Comment by SoftFever** [comment]
Hi @wight554 
Orca does has this feature.
It allows you to specify the gap fill threshold, offering more granular control.
![image](https://github.com/SoftFever/OrcaSlicer/assets/103989404/6b511bf6-242b-4a40-b51d-b2194f9c1072)

**Comment by wight554** [comment]
> Hi @wight554 Orca does has this feature. It allows you to specify the gap fill threshold, offering more granular control. ![image](https://user-images.githubusercontent.com/103989404/275246999-6b511bf6-242b-4a40-b51d-b2194f9c1072.png)

It's not applied to bottom and top layers as per description, I think prusa's one works for all. Not sure tho

**Comment by SoftFever** [comment]
The description need to be updated.
It applies to all layers.

**Comment by discip** [comment]
@wight554
So this issue is solved I assume, right?
Please don't forget to close. 😊

**Comment by wight554** [comment]
> @wight554 So this issue is solved I assume, right? Please don't forget to close. 😊

Well, the issue doesn't exist, but maybe we should keep it for tracking description fix?
If not needed, I'll close it for sure

**Comment by SoftFever** [comment]
Thanks, the description has been fixed.

**Comment by wight554** [comment]
Thanks, closing the issue
