### ISSUE TITLE
[Feature request] Quick export feature

### ISSUE THREAD

**Issue by Kokored7214** [SoftFever/OrcaSlicer#2417]
**Describe the solution you'd like**
Add an export button that export all sliced plate at once

**Describe alternatives you've considered**
Export one by one manualy for now

**Comment by Stevetm2** [comment]
We would also need a placehholder variable for the saved gcode filename,  such as {plate_num}, this would then contain the current plate number being saved for use in this filename.  Eg. MyModel_P{plate_num} To generate : MyModel_P1.gcode and MyModel_P2.gcode etc

**Comment by LupusTheCanine** [comment]
{plate_name} would be useful too.
