### ISSUE TITLE
Filament Shrinkage setting doesn't equally modify all parts on a 3MF model import

### ISSUE THREAD

**Issue by enly1** [SoftFever/OrcaSlicer#2418]
### OrcaSlicer Version

1.7.0

### OS version

Windows 10

### Printer

Bambu Labs - P1S

### How to reproduce

Import multi-part 3MF File.
Modify Shrinkage on selected filament to 99%
Notice component parts of model don't scale equally, resulting in gaps between perimeters of previously touching parts.

### Actual results

Gaps created between parts

![image](https://github.com/SoftFever/OrcaSlicer/assets/5808106/d2a3eaa9-0cc8-4f8a-ac2e-5240a8dd61d6)

### Expected results

No Gaps

![image](https://github.com/SoftFever/OrcaSlicer/assets/5808106/ffd96fe7-6942-466d-9baa-a51b6af05c4e)

### Project file & Debug log uploads

[Dessicant_Tray_Drafted_Filament_Dryer.zip](https://github.com/SoftFever/OrcaSlicer/files/12906683/Dessicant_Tray_Drafted_Filament_Dryer.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by enly1** [comment]
Gap present between lower arc in pictures and hex fill.

**Comment by psiberfunk** [comment]
@SoftFever , is xy shrinkage something other than XY scaling of objects ?

**Comment by SoftFever** [comment]
It scales each region(2d) after slcing the model.
It should equal to XY scale the model in 3d

**Comment by SoftFever** [comment]
With that said, filament shrinkage occurs on a per-project basis. 
Each object is scaled from its center point(it's acutually more like offseting). 
So, if you want to apply shrinkage to multiple objects collectively, please select these parts and then create an assembly for them.

**Comment by psiberfunk** [comment]
> With that said, filament shrinkage occurs on a per-project basis. Each object is scaled from its center point(it's acutually more like offseting). So, if you want to apply shrinkage to multiple objects collectively, please select these parts and then create an assembly for them.

Shouldn’t that be done for the user automatically though ? I guess my point is that the user expectation is that it behaves like scaling , which does keep everything together when applied ?
