### ISSUE TITLE
Artillery X2 "no sd-card"

### ISSUE THREAD

**Issue by GerhardPo** [SoftFever/OrcaSlicer#242]
**issue:**
When I slice an object in Softfever Studio for Artillery X2, store it on USB-stick and start the print I get the error message "no sd-card" and the print is not started.

**To Reproduce**
1. slice any object and store it to USB-stick
2. put USB-stick in Artillery X2 printer and start print
3. eroor message "no sd-card" appears

**Expected behavior**
print should start and no error should appear

**Desktop (please complete the following information):**
 - OS: Win11
 - 1.4.2 and 1.4.3

**Comment by SoftFever** [comment]
Such error is usually caused by incorrect g-code.
Please double check your Machine start g-code

**Comment by GerhardPo** [comment]
Hi,

thx for your reply. I´ve tried it with your code and also with my code I 
use in Cura and Ideamaker. Both versions didn´t work. when I´m back from 
my business trip I´ll try to clean the whole stard code and only add G28 
and give You feedback.

PS: Your work is awesome and i use your fork with my Bambu X1CC

Best regards

Gerhard Polic


------ Originalnachricht ------
Von "SoftFever" ***@***.***>
An "SoftFever/BambuStudio-SoftFever" 
***@***.***>
Cc "GerhardPo" ***@***.***>; "Author" 
***@***.***>
Datum 30.01.2023 15:30:32
Betreff Re: [SoftFever/BambuStudio-SoftFever] Artillery X2 "no sd-card" 
(Issue #242)

**Comment by GerhardPo** [comment]
Hi,

I´ve made some tests and the M20X commands create the problem. They are 
created internally in your code. I marked them out and then the "no 
sd-card" error was gone


Schöne Grüße

Gerhard Polic


------ Originalnachricht ------
Von "SoftFever" ***@***.***>
An "SoftFever/BambuStudio-SoftFever" 
***@***.***>
Cc "GerhardPo" ***@***.***>; "Author" 
***@***.***>
Datum 30.01.2023 15:30:32
Betreff Re: [SoftFever/BambuStudio-SoftFever] Artillery X2 "no sd-card" 
(Issue #242)
