### ISSUE TITLE
Bridge layer

### ISSUE THREAD

**Issue by AlexVikingos** [SoftFever/OrcaSlicer#2422]
![IMG_4808](https://github.com/SoftFever/OrcaSlicer/assets/136171896/e4766eec-3f3d-4223-9716-3d86865a3dee)
![IMG_4809](https://github.com/SoftFever/OrcaSlicer/assets/136171896/6c9f56e1-169c-4893-b6dc-69eecdda2ba7)
Bridge layers are not connected or making 100 small pieces not in one layer. No possible to expend it.
Basically if have object with hole or more holes than bridge make for all individual but not connected together. I try all possible settings and can find way how to do it. Compare to superslicer, prusa slicer and ideamaker all slice in one piece

**Comment by Noisyfox** [comment]
Could you share the project?

**Comment by AlexVikingos** [comment]
[https://drive.google.com/file/d/1iggmyspcU3t0ZwSpYqJVQr1jgaf-Sfu-/view?usp=sharing](url)

**Comment by Noisyfox** [comment]
![image](https://github.com/SoftFever/OrcaSlicer/assets/1537155/9d7f114f-95ad-45be-b5f6-6287565b808d)

I can also reproduce your issue using SuperSlicer. Did you change any specific settings? Or could you share your SuperSlicer's project?

**Comment by Noisyfox** [comment]
Also, with changes from this PR https://github.com/SoftFever/OrcaSlicer/pull/2382 it generates one single complete bridge layer:
![image](https://github.com/SoftFever/OrcaSlicer/assets/1537155/93c4fe21-0e82-40f7-9f38-60d8a3889835)

**Comment by AlexVikingos** [comment]
[https://drive.google.com/file/d/1rjHdeu4T0Nf5lGUSDaWTav04YP5KAF2X/view?usp=sharing, https://drive.google.com/file/d/1wlbtcQuVp5I1bGiOgccBJkCpNMWgwmMH/view?usp=sharing](url)
my super slicer settings, the same with prusa slicer and similar with ideamaker.

**Comment by Noisyfox** [comment]
Interesting.
BTW could you give the dev build of this PR https://github.com/SoftFever/OrcaSlicer/pull/2382 a try and see if it solves your problem?
