### ISSUE TITLE
Undo history (like PS)

### ISSUE THREAD

**Issue by Eldenroot** [SoftFever/OrcaSlicer#2425]
**Is your feature request related to a problem? Please describe.**
Add a undo/redo history like Prusa Slicer has

**Which printers will be beneficial to this feature**
Easier slicing

**Describe the solution you'd like**
Add a mew popup window? Check the screenshot.

**Describe alternatives you've considered**
---

**Additional context**
![image](https://github.com/SoftFever/OrcaSlicer/assets/778890/5f0d411e-eebe-4167-92e5-cd6e75e6cc2d)

**Comment by Noisyfox** [comment]
I do like this history window, but I'm not sure how to adapt that to current Orca's UI since 1) Orca has undo/redo buttons on the title bar; 2) We already have too many icons on the top toolbar and it's really hard to squeeze another two without making life harder for those with small screens.

**Comment by Eldenroot** [comment]
Hmm, what about to display a popup window if you click on the undo/redo on the title bar with the right mouse click?

**Comment by Noisyfox** [comment]
> Hmm, what about to display a popup window if you click on the undo/redo on the title bar with the right mouse click?

Yeah that's something I could try

**Comment by Eldenroot** [comment]
I think this is the only way :) I am looking forward!

**Comment by Eldenroot** [comment]
Still needed

**Comment by Eldenroot** [comment]
Bump
