### ISSUE TITLE
OrcaSlicer and bambu studio

### ISSUE THREAD

**Issue by WimVDK** [SoftFever/OrcaSlicer#2436]
So just ordered my X1C with AMS? Obviously it hasn't arrived yet lo, that be quick. In the mean time i'm looking around OS as i know it's more advanced than the native bambu studio (the same way i use Cura over Creality Slicer for my CR10 Max). I already signed in wiith my bambu account, set up the proper printer profiles but that leaves 1 question.

In order for the X1C to show up in OS, do i need bambu studio installed as well? Couldn't find that info in the OS documentation.

**Comment by Ocraftyone** [comment]
no. there is the option to install the bambu network plugin that provides feature parity with bambu studio.

**Comment by WimVDK** [comment]
I did install that one, Printer should arrive tomorrow. Then i'll be able to test in the upcoming days. But to clear just so there's no missunderstanding. OrcaSlicer is standalone and (although forked from BambuSlicer) does **NOT** require BambuSlicer to be installed?

**Comment by Ocraftyone** [comment]
Yup! 100 percent correct!

**Comment by Ocraftyone** [comment]
if that solves your issue, don't for get to close 😄

**Comment by WimVDK** [comment]
if you don't mind i'll leave it open until i've confirmed this affter setting up the printer.

**Comment by WimVDK** [comment]
We are up and running!
