### ISSUE TITLE
Program crash when trying to see livestream

### ISSUE THREAD

**Issue by PowerChaos** [SoftFever/OrcaSlicer#2439]
### OrcaSlicer Version

1.7.0

### OS version

Win11

### Additional system information

13500F
128GB Ram
Intel ARC 750

### Printer

bambu

### How to reproduce

see video

https://github.com/SoftFever/OrcaSlicer/assets/7650333/d37afa62-5174-4a91-8446-bc7f411a2038

### Actual results

program crash

### Expected results

not crashing and showing video feed

### Project file & Debug log uploads

got no project files
[orcadebuglog.zip](https://github.com/SoftFever/OrcaSlicer/files/12923954/orcadebuglog.zip)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by tdwilli1** [comment]
Any update on this? I submitted the same issue and it isn't fixed in 1.8.1.
