### ISSUE TITLE
1.4.3 Perimeter printing order still wrong is some case

### ISSUE THREAD

**Issue by ShryuKt** [SoftFever/OrcaSlicer#244]
I had hope when I saw

> Fixes:

> Wrong perimeter generation for overhangs in some cases https://github.com/bambulab

My problem is still present in 1.4.3
I have already referenced it on the bambu studio repo [BambuStudio#1055](https://github.com/bambulab/BambuStudio/issues/1055)
But maybe you can help

**3mf File for This Bug**
[Tap_Front_r2.3mf.txt](https://github.com/SoftFever/BambuStudio-SoftFever/files/10521301/Tap_Front_r2.3mf.txt)

**Description & Screenshots**
In some case the outer perimeters are still printed first (With Classic Wall Generator)
![image](https://user-images.githubusercontent.com/115975090/215144366-6e106baa-d68c-4025-9e94-94289db793a9.png)
On this part, these two holes are overhanging, which makes the printing fail because the outer perimeters are printed on a void without support.
All other holes are printed in the correct order.

When using arachne wall generator the order is correct
![image](https://user-images.githubusercontent.com/115975090/215148750-daab7ba2-b788-4fe2-a182-1df5436ea9bc.png)

**Comment by hliebscher** [comment]
its the same error on PrusaSlicer 2.5.0  and SuperSlicer
![prusa](https://user-images.githubusercontent.com/9274162/215224874-099ed69c-2582-441d-9c1e-223881f5aeee.jpg)

**Comment by ShryuKt** [comment]
I use superslicer 2.4.58.5 (so before arachne) for everydays prints and the order is correct
This is my 3mf with SS, same piece and almost same settings, as far as possible, as with BS
[Tap_Front_r2.SS.3mf.txt](https://github.com/SoftFever/BambuStudio-SoftFever/files/10526639/Tap_Front_r2.SS.3mf.txt)

![image](https://user-images.githubusercontent.com/115975090/215254125-060affac-6ca3-4cfe-881b-a29c3178e9fb.png)

Maybe this is something that appended with the implementation of arachne wall generator.

**Comment by SoftFever** [comment]
It's an edge case here.
The thing is: if you observe those wall loops carefully, the hole has only one wall.
Other walls/perimeters belong to the contour.

In the case of Arachne, the hole has 0 walls on its own; hence it solved the issue accidently.

We should be able to special handling such cases. 
Stay tuned.

**Comment by ShryuKt** [comment]
> We should be able to special handling such cases. Stay tuned.

That would be great,
Thank you for taking this into consideration

**Comment by julie777** [comment]
I just added quite a bit of information to #884 which also applies here.
