### ISSUE TITLE
OrcaSlicer for Mac camera stream playback issue

### ISSUE THREAD

**Issue by Magalex2x14** [SoftFever/OrcaSlicer#2444]
### OrcaSlicer Version

1.7.0

### OS version

macOS 14.0

### Printer

Bambu Lab X1CC

### How to reproduce

Just trying to watch a live stream from the printer's camera.

### Actual results

Initially, I created issue in the BambuStudio repository, and since OrcaSlicer 1.7.0 has exactly the same problem, I just copy the text from the [BambuStudio repo issue](https://github.com/bambulab/BambuStudio/issues/2735):

[This video clearly demonstrates the problem.](https://youtu.be/VD8vKUHor2M) Above is playback in BambuStudio for Mac 1.7.7.89 (Sonoma 14.0), below is a virtual machine window on the same computer with BambuStudio 1.7.7.89 for Windows (Windows 10 Parallels virtual machine). Just like on Windows, Bambu Handy for iOS also plays video stream normally. I also tried to open the stream via the link rtsps://bblp:<lanpass>@<lan ip>:322/streaming/live/1 using the Movist Pro player - the stream plays normally (however it stops after about 10 seconds, but it doesn’t matter ).

### Expected results

Smooth quality playback.

### Project file & Debug log uploads

[log.zip](https://github.com/SoftFever/OrcaSlicer/files/12937660/log.zip)
The problem is not project specific.

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by WZ9V** [comment]
This happens on Linux Mint also.
