### ISSUE TITLE
Orca Slicer commented tags not recognized by Klipper/Fluidd dashboard

### ISSUE THREAD

**Issue by StellarJay77** [SoftFever/OrcaSlicer#2446]
**Is your feature request related to a problem? Please describe.**
When Orca slicer creates the g-code file for a project is adds commented tags formatted as follows at the end of the code:
Example:

; filament used [mm] = 14395.62
; filament used [cm3] = 34.63
; filament used [g] = 42.94
; filament cost = 0.86; total filament used [g] = 42.94
; total filament cost = 0.86
; total layers count = 397
; estimated printing time (normal mode) = 1h 33m 15s

The tag that has the estimated printing time is not recognized by Klipper/Fluidd dashboard like the ones generated by Cura so that the estimated print and finish time show when printing. The tags that do work are formatted as follows:

;FLAVOR:Marlin
;TIME:402
;Filament used: 0.406692m
;Layer height: 0.2
;MINX:107.664
;MINY:107.664
;MINZ:0.2
;MAXX:127.336
;MAXY:127.336
;MAXZ:15
;Generated with Cura_SteamEngine 5.4.0

**Which printers will be beneficial to this feature**
All Klipper based printers I would assume.

**Describe the solution you'd like**
I've tested adding the properly formatted ;TIME:xxx tag to Orca generated G-code and it works, just need to have Orca generate the properly formatted tags automatically.

**Describe alternatives you've considered**
Creating a Macro that converts the existing estimated time tag to a properly formatted ;TIME tag. Problem with that is because the tag is commented out it is very hard to deal with and get Klipper to read the tag. Also considered having a macro that adds the tag through the start g-code of the machine but again is problematic as it is comment text.

**Comment by ruiaraujo012** [comment]
I'm trying to find the same, @StellarJay77 how do you have fixed the issue?
