### ISSUE TITLE
1.7.0  支撑设置全乱套了，支撑屏蔽不起作用

### ISSUE THREAD

**Issue by six00** [SoftFever/OrcaSlicer#2447]
### OrcaSlicer Version

1.7.0

### OS version

win10

### Printer

p1p

### How to reproduce

原先1.6。6的版本设置的支撑屏蔽一切正常，之前版本切片也正常，升级1.7.0后画了支撑屏蔽的地方依然出现了支撑，而且手动抹除所有自定义支撑后，再次画支撑屏蔽仍不起任何作用

### Actual results

画了支撑屏蔽仍有支撑生成

### Expected results

画了支撑屏蔽无支撑生成

### Project file & Debug log uploads

。。

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by xux1217** [comment]
确实, 支撑屏蔽不起作用了

**Comment by AisonSu** [comment]
还没有修好吗
