### ISSUE TITLE
Orca Slicer remove internal structure in vase mode

### ISSUE THREAD

**Issue by justloveengineering** [SoftFever/OrcaSlicer#2451]
### OrcaSlicer Version

1.7.0

### OS version

MacOS Ventura 13.4.1

### Printer

qidi x3 plus 

### How to reproduce

[Winglet.stl.zip](https://github.com/SoftFever/OrcaSlicer/files/13018705/Winglet.stl.zip)
Slice in vase mode

### Actual results

<img width="1027" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/148341786/d1efe5b8-fb33-44a5-9eec-7fa20a50460b">

### Expected results

<img width="1145" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/148341786/ea97c856-5268-419e-bfe7-dcd8d79a465c">
Sliced in cura

### Project file & Debug log uploads

none

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by InstantBenHur** [comment]
Does reducing slice gap closing radius help?

![image](https://github.com/SoftFever/OrcaSlicer/assets/125794048/f1fe9b6f-e98b-4179-98c2-f94a0de7e786)

**Comment by justloveengineering** [comment]
Yes, thank you!
