### ISSUE TITLE
Bridge: auto-direction-detection should not use the same direction as the infill above

### ISSUE THREAD

**Issue by Noisyfox** [SoftFever/OrcaSlicer#2458]
The issue is originated from https://github.com/SoftFever/OrcaSlicer/pull/2382#issuecomment-1761721677

In some cases the auto-detected bridge direction will be the same as the infill direction of the upper layer, which could cause quality issue if the bridge density is relative low.

We could consider improving this by adding some sort of constraint to the algorithm so it avoids using the same direction as the infill direction as much as possible.

**Comment by SoftFever** [comment]
Are you referring to these highlighted areas?
![Screenshot 2023-10-20 at 1 45 36 PM](https://github.com/SoftFever/OrcaSlicer/assets/103989404/a3e6380d-bed1-4606-9e4f-2d45cf5e6f42)

**Comment by Noisyfox** [comment]
> Are you referring to these highlighted areas? ![Screenshot 2023-10-20 at 1 45 36 PM](https://user-images.githubusercontent.com/103989404/276833234-a3e6380d-bed1-4606-9e4f-2d45cf5e6f42.png)

Nope, the other part.

**Comment by SoftFever** [comment]
Damn, not sure why I circled that parts. Need more coffee..
