### ISSUE TITLE
what is this? the little piece of extrusion beside warped wall

### ISSUE THREAD

**Issue by wonsuhna1** [SoftFever/OrcaSlicer#2466]
### OrcaSlicer Version

1.8.0.-dev (nightley)

### OS version

windows 10

### Printer

diy printer.

### How to reproduce

what is this? the little piece of extrusion beside warped wall
in my case, It happened almost every time. This also happened in version 1.7.0.

### Actual results

![ㅣ 2023-10-20 10 48 28](https://github.com/SoftFever/OrcaSlicer/assets/104687650/e390429b-a238-4181-bb25-f12a03c70153)

### Expected results

There should be no meaningless halucination extrusions.

### Project file & Debug log uploads

[turbo cooler mount v1.zip](https://github.com/SoftFever/OrcaSlicer/files/13049199/turbo.cooler.mount.v1.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by Noisyfox** [comment]
Have you tried the latest master build? I think this has been fixed by the new ensure vertical thickness algorithm.

**Comment by wonsuhna1** [comment]
> Have you tried the latest master build? I think this has been fixed by the new ensure vertical thickness algorithm.
> 
> ![image](https://user-images.githubusercontent.com/1537155/276799922-5412d3b8-43a1-437a-b7d1-259233400435.png)

I checked and it did indeed work.
Thanks

I'll close this post.
