### ISSUE TITLE
Add SVG emboss tool

### ISSUE THREAD

**Issue by rkarlsba** [SoftFever/OrcaSlicer#2487]
We have text emboss tool, but an even better one would be SVG emboss tool, so that you can project any SVG graphics on a model. This has now been added to https://github.com/prusa3d/PrusaSlicer/releases/tag/version_2.7.0-alpha1, so I guess it's just a matter of picking up the right patches?

**Comment by Eldenroot** [comment]
+1, also maybe check if all features are backported from ps

**Comment by discip** [comment]
@rkarlsba
I know, you issued this first, but since one of the highly productive contributors answered to a similar FR, I suggest to close this in favor of #2523. 😊

thanks in advance
