### ISSUE TITLE
Problem Network-Plug-in OrcaSlicer in VM Win 7 on OSX

### ISSUE THREAD

**Issue by NonBlackstation** [SoftFever/OrcaSlicer#2490]
I have Bambu Lab Studio on my laptop (virtual Machine with Win 7 64bit) and the network plug-in works there. The download also works and no other software accesses the files.
Now I have copied the folder under C:/........./AppData/Roaming/Bambu../plugins into the OrcaSlicer folder. However, this is not recognized and a download via OrcaS is not possible.
When I do the network test in Bambu Studio, it's OK. But with Orca the BBL page doesn't work and the http
![Test-OrcaSlicer](https://github.com/SoftFever/OrcaSlicer/assets/134835292/b577b2d7-d280-4dbe-8ec4-3bf882fae3da)
![Test-BambuLabStudio](https://github.com/SoftFever/OrcaSlicer/assets/134835292/d11d010b-4dce-4265-b5f2-6472e3cc3bfc)

**Comment by NonBlackstation** [comment]
Is the problem perhaps because I am using the OrcaSlicer in a virtual machine with Windows 7 (Parallels)?
However, all programs and internet access work. The test works with BambuStudio itself.
The virtual machine has its own IP (bridged network).
On my wife's laptop (Win7 Pro 64bit) it works with the OrcaSlicer network plug-in.

**Comment by SoftFever** [comment]
TBH, I never tested Win 7. It’s very likely not supported

**Comment by NonBlackstation** [comment]
jippie, OrcaSlicer 1.8.0 beta 1 work fine on Win 7 Pro 64bit. No problem to download the Network PlugIn...  :) :)

**Comment by discip** [comment]
@NonBlackstation
If this is fixed, than please don't forget to close. 😊
