### ISSUE TITLE
Unrecognized keys from Bambu Studio 1.7.7.89 3mf

### ISSUE THREAD

**Issue by bani6809** [SoftFever/OrcaSlicer#2493]
### OrcaSlicer Version

1.7.0

### OS version

Windows 10

### Printer

Bambu X1C+AMS

### How to reproduce

Save 3mf from Bambu Studio. Open it in OrcaSlicer 1.7.0.

### Actual results

![image](https://github.com/SoftFever/OrcaSlicer/assets/43738861/63b9c68a-5f9d-4558-8b67-7251ba618895)

### Expected results

OrcaSlicer should support these new keys 🙂

### Project file & Debug log uploads

N/A

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by igiannakas** [comment]
Latest nightly build (can be found in the actions section above) supports the latest Bambu slicer version. Give it a try.

**Comment by SoftFever** [comment]
Fixed in 1.8 beta
