### ISSUE TITLE
Makerworld doesn't accept print profiles from OrcaSlicer

### ISSUE THREAD

**Issue by bani6809** [SoftFever/OrcaSlicer#2494]
### OrcaSlicer Version

1.7.0

### OS version

Windows 10

### Printer

Bambu X1C+AMS

### How to reproduce

Go to makerworld. Select a model, then select add print profile. Select the 3mf generated from OrcaSlicer.

### Actual results

![image](https://github.com/SoftFever/OrcaSlicer/assets/43738861/5f916780-fa3b-4035-9ab7-5509291f412d)

### Expected results

It should accept the print profile.

### Project file & Debug log uploads

N/A

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by igiannakas** [comment]
It can’t - orca slicer has many more options that Bambu studio doesn’t support. And since the slicing is happening in the “cloud” using Bambu slicer using an orca profile would be incompatible and would not allow the model to slice.

**Comment by Vanilla009** [comment]
This is related to my issue #2223

**Comment by SoftFever** [comment]
It’s up to Bambu to accept OrcaSlicer’s profile.
I’d suggest asking for Orca support in their site

**Comment by psiberfunk** [comment]
This isn’t a valid bug for this repo.. it should be closed
