### ISSUE TITLE
Orca Slicer not launching on Arch Linux Due to SSL Cert error. 

### ISSUE THREAD

**Issue by KiwiHuman** [SoftFever/OrcaSlicer#2500]
### OrcaSlicer Version

1.7.0

### OS version

Arch Linux

### Additional system information

OS: Arch Linux x86_64 
Kernel: 6.5.8-arch1-1 
CPU: AMD Ryzen 5 2600 (12) @ 3.400GHz 
GPU: NVIDIA GeForce RTX 3060 
Memory: 3874MiB / 15938MiB 
                           
                                                                 

### Printer

Application Not launched

### How to reproduce

1. Download .appimmage
2. launch appimmage with appimmage launcher
3. intergrate and run 
4. ![orcaslicer](https://github.com/SoftFever/OrcaSlicer/assets/98422297/e81a2415-f82b-42ef-96cb-597478bc625d)
5. click yes or no with "remember my choice" either selected or deselected 

### Actual results

the dialog box asking about SSL certificates closes and the application dose not launch 

### Expected results

the application opens 

### Project file & Debug log uploads

There is no applicable project file or log. 
![orcaslicer](https://github.com/SoftFever/OrcaSlicer/assets/98422297/d20a182f-5544-4b25-93db-56b0b15e7c31)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by SoftFever** [comment]
It's system notification.
Please tick `Remember my choice` and click yes.
It will launch

**Comment by KiwiHuman** [comment]
> It's system notification. Please tick `Remember my choice` and click yes. It will launch

I selected "Remember My Choice" and yes. The dialog box closed. Relaunching OrcaSlicer just shows the dialog box again.

**Comment by zetabemol** [comment]
En mi caso pasaba lo mismo. También lo tengo instalado en Windows 10. Lo que hice fue copiar la carpeta de config de orca slicer (Windows10/Users/User/AppData/Roaming/orcaslicer) de windows 10, y reemplazar la misma carpeta en archlinux (/home/user/.config/orcaslicer). De esa manera funcionó

**Comment by KiwiHuman** [comment]
> En mi caso pasaba lo mismo. También lo tengo instalado en Windows 10. Lo que hice fue copiar la carpeta de config de orca slicer (Windows10/Users/User/AppData/Roaming/orcaslicer) de windows 10, y reemplazar la misma carpeta en archlinux (/home/user/.config/orcaslicer). De esa manera funcionó

Thank you so much. I had to sort out some issues with locales but this fixed it. (I used a config from Linux mint instead of windows)
