### ISSUE TITLE
X-Y hole compensation causes missing layers on pieces inside hollow parts

### ISSUE THREAD

**Issue by Starkiller4011** [SoftFever/OrcaSlicer#2521]
### OrcaSlicer Version

1.7.0

### OS version

Windows 10

### Additional system information

CPU: AMD Ryzen 9 5950X
Memory: 32GB
Display Card: AMD Radeon RX 6950 XT

### Printer

Sovol SV06+

### How to reproduce

1) Select ANY printer profile
2) Select ANY filament profile
3) Select ANY process profile
4) Load a model that has small parts inside of it (see attached screenshots for an example using STL file: [[a]_stealthburner_main_body.stl](https://github.com/VoronDesign/Voron-Stealthburner/blob/main/STLs/Stealthburner/%5Ba%5D_stealthburner_main_body.stl)
5) Change "X-Y hole compensation" to a positive non-zero value
6) Slice
![loaded_model_with_problem_area_identified](https://github.com/SoftFever/OrcaSlicer/assets/5083764/2023949f-d0a6-423b-b7e5-60dc86c9b6f9)
![sliced_model_with_problem_area_identified](https://github.com/SoftFever/OrcaSlicer/assets/5083764/9edf9746-e6af-4300-a856-5c0d884661ab)
![zoom_on_problem_area_with_problem_feature_highlighted](https://github.com/SoftFever/OrcaSlicer/assets/5083764/de55f7fd-7c51-4dcc-83a3-516c9b46dfa6)
![zoom_on_sliced_problem_area_with_problem_feature_highlighted](https://github.com/SoftFever/OrcaSlicer/assets/5083764/5e2a3dcd-e246-4f9e-bd5c-ef0d00491c96)

### Actual results

Small parts within the model will be misidentified as part of a hole and have the "X-Y hole compensation" applied to them resulting in missing layers.

### Expected results

Only holes should have the "X-Y hole compensation" applied to them.

### Project file & Debug log uploads

[project_file.zip](https://github.com/SoftFever/OrcaSlicer/files/13192853/project_file.zip)
[logs.zip](https://github.com/SoftFever/OrcaSlicer/files/13192855/logs.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by SoftFever** [comment]
It's not a bug. 0.2 compensation is way too big for such a model.
Voron parts has printing torrence in mind when they design them.
