### ISSUE TITLE
Aux_fan no longer works

### ISSUE THREAD

**Issue by SlackHacky** [SoftFever/OrcaSlicer#2538]
### OrcaSlicer Version

1.8.0. beta 

### OS version

OS windows 11

### Printer

VzBot 330

### How to reproduce

n/a 

### Actual results

Aux_fan no longer works - rolling back to orca 1.7.0 is works again, with no change of settings - so very 1.8.0 related rather than i've got a setting wrong.

### Expected results

aux_fan turning on with parts cooling fan at pre set level

### Project file & Debug log uploads

n/a

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by SoftFever** [comment]
@SlackHacky 
Can you share the project file?

**Comment by diezjl** [comment]
I have the same issue since version 1.8.0, in version 1.9.0 still persist.
I realised some test and see that the issue only occurs when select auxiliarity fan speed below 100%, in this cases the g-code generated miss "M106 P2 Sxx" command.

**Comment by SlackHacky** [comment]
can confirm no longer works as was using Rigid static cooling as Aux cooling on a vzbot and since 1.8.0 only woks at 100% not 99% as worked for 1.7.0

**Comment by diezjl** [comment]
The problem persist in 2.0.0 beta
