### ISSUE TITLE
Allow change of filament color printing order especially on first layer.

### ISSUE THREAD

**Issue by randyre** [SoftFever/OrcaSlicer#254]
**Is your feature request related to a problem? Please describe.**
Allow change of filament color printing order, especially on the first layer.

**Describe the solution you'd like**
Allow the user to define which color prints first. 

**Describe alternatives you've considered**
None.

I currently have a two-color print and the lighter color prints first, but as the second color prints, the nozzle barely touches the light color and it then streaks onto the darker color. Especially silk colors are very prone to this.

![2023-01-28](https://user-images.githubusercontent.com/60475095/215274825-12c532f9-f032-4869-a9bb-f8813b606707.png)

**Comment by parrothd** [comment]
Please add.. :)
