### ISSUE TITLE
Popup exact feature value.

### ISSUE THREAD

**Issue by GAZ082** [SoftFever/OrcaSlicer#2549]
Hi. Instead of looking at the color chart would be nice to have the actual value to pop up.

![image](https://github.com/SoftFever/OrcaSlicer/assets/100194/4af60b0f-e721-441c-9ecc-c0090a71c17d)

**Comment by Noisyfox** [comment]
Use the horizontal slider and the exact value will be shown.

**Comment by GAZ082** [comment]
> Use the horizontal slider and the exact value will be shown.

Oh, nice one :) Thanks
