### ISSUE TITLE
A1 mini - G92 E0 error message

### ISSUE THREAD

**Issue by Eldenroot** [SoftFever/OrcaSlicer#2565]
### OrcaSlicer Version

1.8.0b1

### OS version

Win11 64bit

### Printer

A1 mini

### How to reproduce

Add .stl file and you get the error 

![image](https://github.com/SoftFever/OrcaSlicer/assets/778890/07884232-e136-45f0-8bbe-f182949d06da)

### Actual results

![image](https://github.com/SoftFever/OrcaSlicer/assets/778890/b8dba532-a322-4a0c-b165-760762e9a1a1)

### Expected results

No error message. Code is missing?

### Project file & Debug log uploads

No necessary

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by SoftFever** [comment]
It has been fixed in nightly build

**Comment by VintarMfG** [comment]
![1000](https://github.com/SoftFever/OrcaSlicer/assets/32814265/b1fefed3-9587-4130-99df-7ffc50439ec8)
![2000](https://github.com/SoftFever/OrcaSlicer/assets/32814265/7dd470e1-68b5-482b-9d05-8c5f73790d56)

And check the Z error ( 0.10), so as not to run into the table

(G4 ; )
