### ISSUE TITLE
Vase mode for parts of the print

### ISSUE THREAD

**Issue by rkarlsba** [SoftFever/OrcaSlicer#2567]
AFAICS vase mode can only be selected globally. It'd be very nice to allow for a figure to, say, have a solid base or at least a thicker one and then the top, as in a lamp shade, to use vase mode, perhaps even switching back on the top for a rim or similar. Would this be hard to implement?

**Comment by HappyMark93** [comment]
It is possible, i have done it manually merging g-code solid on bottom, vase in mid and then again solid on top.
Transition layer is critical. Vase mode need to begin from zero level when z 0 offset is applied so that zero is on top surface of solid base.
Maybe it is possible to do right now with two solids stacked one on another, and vase mode selected for top model?

**Comment by hungrierwtf** [comment]
This would be a really good feature. Or at least have it setable by height/layer, so that you could print the base with whatever settings you wanted, then transition to vase mode for the rest.

**Comment by beatwinthewave** [comment]
+1 to have the vase mode for objects, good idea

**Comment by Knaudler** [comment]
+1
we need Vasemode for parts or heigh range modifier - aktivate the button in the parts menu
every slicer can do this

**Comment by ThinkBigPrintHuge** [comment]
+1
This is easily done in S3D. Not sure about other slicers as I have not tried. I am printing Rockets that are vase mode, but I need to add solid layers/infill to the tip to prevent sagging.

**Comment by TuTanK5** [comment]
+1 would love to have this

**Comment by Knaudler** [comment]
please add Vasemode at  heigh range modifier

**Comment by soundfx37** [comment]
+1  Really useful feature for printing thick bases of vases.

**Comment by soundfx37** [comment]
As an alternative, Can we allow the object modifier to turn off vase mode for a portion of the print?  Right now only the "other" category the modifier can change is fuzzy skin.

**Comment by SteWhite** [comment]
I'm really sad. I can do this with S3D 4.1.2, but not with this amazing slicer. Please add this feature!

<img width="1600" height="1067" alt="Image" src="https://github.com/user-attachments/assets/6ac43279-f4e8-417f-ac3a-737716d4df29" />
