### ISSUE TITLE
Inner Walls Combination (just as Infill Combination)

### ISSUE THREAD

**Issue by UsSuggester** [SoftFever/OrcaSlicer#2571]
There's an option to print a single but thicker line of infill per two layers of walls to save printing time.

It would be possible to apply the same option for inner walls by discriminating them from outer walls?

**Comment by survivalMan1** [comment]
I think being able to merge inner wall layers could be a great addition to the slicer because the walls can take even longer than the infill to print so this could save even more time while still being very unlikely to affect the outer wall quality any more than by merging just infill
