### ISSUE TITLE
Center of gravity toggle

### ISSUE THREAD

**Issue by liftbag** [SoftFever/OrcaSlicer#2574]
**Is your feature request related to a problem? Please describe.**
PrusaSlicer has a toggle that allows you to view the object's center of gravity in print preview. Provided that the cog calculation is accurate, the tool, together with the modifiers, could be useful in some specific cases. I am thinking for example of floating or flying models, illusions etc.
Certainly nothing of vital importance, but it can be useful  so as not to waste on trial and error where the center of gravity of the printed object is relevant.

**Which printers will be beneficial to this feature**
N.A.

**Describe the solution you'd like**
Porting from PrusaSlicer? As long as there are no problems of the type that porting of the ruler is causing.

**Additional context**

COG of the printed object
<img width="1438" alt="Screenshot 2023-11-01 alle 10 45 15" src="https://github.com/SoftFever/OrcaSlicer/assets/14921654/c00d2292-6383-4777-9008-d69a456714cf">

Moved forward via localized infill modifier
<img width="1438" alt="Screenshot 2023-11-01 alle 10 43 33" src="https://github.com/SoftFever/OrcaSlicer/assets/14921654/624b22e0-6053-4d03-b773-7929641b5fba">

Object that cannot remain erect with any uniform infill option

<img width="1438" alt="Screenshot 2023-11-01 alle 15 16 09" src="https://github.com/SoftFever/OrcaSlicer/assets/14921654/5acdbc0c-e0b5-461c-960b-8d00c0f69a9d">

By modifying the infill in a localized way I can safely print the result.
<img width="1438" alt="Screenshot 2023-11-01 alle 15 15 09" src="https://github.com/SoftFever/OrcaSlicer/assets/14921654/cd049fd4-4872-46f9-b036-3bd4530ccc80">
<img width="1438" alt="Screenshot 2023-11-01 alle 15 15 27" src="https://github.com/SoftFever/OrcaSlicer/assets/14921654/31f96fe7-3599-48e1-8b47-c93beaf46ece">

**Comment by liftbag** [comment]
The request is always present

**Comment by amdavidson** [comment]
Would love to have this feature in orca slicer. It was super useful in prusaslicer for using infill modifiers to make self righting bath/pool toys.
