### ISSUE TITLE
Minimum Z-hop between all travel moves?

### ISSUE THREAD

**Issue by scottmudge** [SoftFever/OrcaSlicer#2587]
Forgive me if this is already a feature, but I haven't been able to find it.

I've set the z-hop height in the filament settings, but this only gets applied to post-retraction travels. Frequently, however, retraction does not occur between travel moves when extruding infill, for example. This causes my hotend to "rattle"/scrape over the infill pattern, which sounds pretty horrible.

If there is no feature to add a minimum z-hop for *all* travel moves, can it be added?

Thanks!

**Comment by igiannakas** [comment]
Yes, disable this option (reduce infill retraction). Then it will retract and zhop across all moves greater than your travel distance threshold (printer settings -> extruder).

![Screenshot 2023-11-02 at 12 58 07](https://github.com/SoftFever/OrcaSlicer/assets/59056762/4a5cc1c2-811f-4871-9db8-18518c798a55)

**Comment by scottmudge** [comment]
Ah so that's where that setting was hiding. Thanks!

I may add a feature to just so a z-hop within infill and not retract, to save on time not needing to do a z move. But for now this will work.

**Comment by igiannakas** [comment]
> Ah so that's where that setting was hiding. Thanks!
> 
> I may add a feature to just do a z-hop within infill and not retract first, to save time.

If you zhop without retraction you'll get plenty of stringing, which even in infill I'd consider as undesirable personally.
