### ISSUE TITLE
Sync with latest Bambu Studio GitHub code

### ISSUE THREAD

**Issue by Eldenroot** [SoftFever/OrcaSlicer#2590]
**Is your feature request related to a problem? Please describe.**
2 days ago BL pushed new code on their github 

**Which printers will be beneficial to this 
All

**Describe the solution you'd like**
Sync what is useful

**Describe alternatives you've considered**

**Additional context**

**Comment by Ocraftyone** [comment]
Is there a specific feature you are looking to  have ported?

**Comment by Eldenroot** [comment]
Cut tool

**Comment by Eldenroot** [comment]
And you know, always less bugs and more handy features are welcomed

**Comment by Eldenroot** [comment]
Now Bambu studio version 1.8 (beta) is out :)

**Comment by Eldenroot** [comment]
Done in 1.9 (at least all what was released by BL studio on Github until this date).
