### ISSUE TITLE
Dynamic Flow Calibration -- Crashes when attempting Manual Calibration

### ISSUE THREAD

**Issue by arhdrums** [SoftFever/OrcaSlicer#2592]
### OrcaSlicer Version

1.8.0-beta 1

### OS version

Windows 11

### Printer

Bambu Lab X1 Carbon

### How to reproduce

1. Click on Calibration Panel (Bambu Lab)
2. Click on Manual Calibration
3. Attempt to start a calibration with either the Line or Pattern methods.

### Actual results

An error message appears, then OrcaSlicer closes.

"Unhandled unknown exception; terminating the application"

![Screenshot 2023-11-02 161704](https://github.com/SoftFever/OrcaSlicer/assets/149513632/56fbaa6c-aa50-4e44-a700-20d86a58240a)

### Expected results

A manual calibration should be successfully generated and sent to the printer.

### Project file & Debug log uploads

[debug_Thu_Nov_02_16_21_03_16500.log.zip](https://github.com/SoftFever/OrcaSlicer/files/13244233/debug_Thu_Nov_02_16_21_03_16500.log.zip)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by SoftFever** [comment]
Fixed in 1.8 beta 2

**Comment by arhdrums** [comment]
Thank you! I can confirm that it is now working for me.

Thanks for quickly fixing the issue, and take care!

**Comment by arhdrums** [comment]
> Fixed in 1.8 beta 2

Thank you! I can confirm that Beta 2 has fixed the issue for me.

Thanks again and take care!

**Comment by kurohouou** [comment]
Running 1.8.1 and getting this error now.

**Comment by Belliqueu** [comment]
Also getting this error in 1.8.1 Windows 10

**Comment by jintaogao** [comment]
happening in 1.8.1 Mac OS 14.1

**Comment by ronx** [comment]
This is happening with Pattern calibration in 2.1.0 and 2.1.1. Line works fine.

**Comment by Freekers** [comment]
> This is happening with Pattern calibration in 2.1.0 and 2.1.1. Line works fine.

Can confirm, same issue here.

**Comment by TomN7** [comment]
Also getting a crash on every attempt to use the pattern calibration in 2.1.0 and 2.1.1. 
Generating a pattern manually with the calibration option in the toolbar works, but not the step-by-step calibration tab.

**Comment by rmzalbar** [comment]
> Also getting a crash on every attempt to use the pattern calibration in 2.1.0 and 2.1.1. Generating a pattern manually with the calibration option in the toolbar works, but not the step-by-step calibration tab.

Me too, v. 2.1.1. Settings: Pattern, 0.022 to 0.032 step 0.001. Works in current Bambu Studio.
