### ISSUE TITLE
missing option "ensure vertical shell thickness" partly breaks single-wall slicing?!

### ISSUE THREAD

**Issue by AmaZz0r** [SoftFever/OrcaSlicer#2602]
When slicing models of parts for rc-planes that are designed to be printed without infill (single wall, printed ribs, close to vase mode), there is internal solid infill added despite setting infill to 0.

I also tried basically every other setting that might have something to do with it, but couldnt get rid of the internal solid infill.

This does not only add weight, but also causes print defects when printing with active foaming (lightweight) material. Why: Retractions are compensated with "extra length on restart", but the internal solid infill has a very close spacing; therefore, excess material accumulates.

This wasnt a problem when the option "ensure vertical shell thickness" was still present. I think it disabled internal solid infill generation.

Using vase mode is not an option, as these designs sometimes encorporate top+bottom layers and inevitable travel  moves.

## pay attention to the additional purple lines in the OrcaSlicer preview

How it looks in OrcaSlicer:
![Screenshot 2023-11-03 233744](https://github.com/SoftFever/OrcaSlicer/assets/149841724/f0cd30e5-6bff-4554-b6c1-678c5996a6ba)

How it should look:
![Screenshot 2023-11-03 235421](https://github.com/SoftFever/OrcaSlicer/assets/149841724/9e53a005-5356-4d9d-81c1-0424fddcb91b)

Real life defects with LW-filament:
![20231103_235025](https://github.com/SoftFever/OrcaSlicer/assets/149841724/33e10c6c-2dea-46a7-a882-9958eb4bbb49)

**Comment by Noisyfox** [comment]
Can you share the project file?

**Comment by AmaZz0r** [comment]
> Can you share the project file?

Sure, thanks for looking into this.

[WingPiece_sample.zip](https://github.com/SoftFever/OrcaSlicer/files/13256647/WingPiece_sample.zip)

**Comment by AmaZz0r** [comment]
The sliced file just reminded me of the floating bridges that are added too.

They're not necessary as well. Don't know if they'd cause any problems.

But normally, they don't belong there.

The shared project has one at layer 216.

It seems they are generated to support ribs that would otherwise start printing in the air.

Maybe theyre actually helpful, I dont know.

Otherwise, using bridge speed and bridge cooling, the ribs would probably print out fine without a whole bridged surface beneath.

**Comment by Noisyfox** [comment]
Can you also send me the original model/project as well? If that concerns you, you can email me.

**Comment by AmaZz0r** [comment]
what do you mean by original model/project?

**Comment by Noisyfox** [comment]
The project before slicing. The 3mf file you uploaded earlier contains only the resulting gcode which make it less useful because I could not re-slicing it with different parameter/version.

**Comment by AmaZz0r** [comment]
ah, sorry. thought that the settings etc. were included in the .3mf after slicing as well.

[WingPiece_sample_project.zip](https://github.com/SoftFever/OrcaSlicer/files/13256841/WingPiece_sample_project.zip)

**Comment by SoftFever** [comment]
looks like a setting issues.
Can you check if this is expected?
![image](https://github.com/SoftFever/OrcaSlicer/assets/103989404/702d5f80-54a7-40c7-8d81-bd6c2d563b7a)

[WingPiece_sample_project_corrected.zip](https://github.com/SoftFever/OrcaSlicer/files/13256992/WingPiece_sample_project_corrected.zip)

**Comment by AmaZz0r** [comment]
> looks like a setting issues. Can you check if this is expected? ![image](https://user-images.githubusercontent.com/103989404/280475994-702d5f80-54a7-40c7-8d81-bd6c2d563b7a.png)
> 
> [WingPiece_sample_project_corrected.zip](https://github.com/SoftFever/OrcaSlicer/files/13256992/WingPiece_sample_project_corrected.zip)

nope. that's not how it should look like. it's missing all of the internal ribs that way.

**Comment by SoftFever** [comment]
I see.
Seems we still need expose the option for user to turn off it.
@Noisyfox what do you think?

**Comment by AmaZz0r** [comment]
![Screenshot 2023-11-04 162505](https://github.com/SoftFever/OrcaSlicer/assets/149841724/7620d2b4-838f-4303-b8c8-895fa0600c1b)

that's the result you'd normally want.

**Comment by Noisyfox** [comment]
Haven't figured out better solution for this issue, so I think I will add the option back.

**Comment by Annuit20** [comment]
Can we add an option for a tolerance at which point vertical shell thickness kick in?
At minor overhangs most of the time there is not need we can compensate with more walls if we want.
But some geometries would benefit from these extra lines.
