### ISSUE TITLE
Can't save filament presets for Creality K1

### ISSUE THREAD

**Issue by PrincessLuna2253** [SoftFever/OrcaSlicer#2609]
### OrcaSlicer Version

1.8.0 Beta 2 (Also happened in 1.7.0)

### Printer

Creality K1

### How to reproduce

- Select Creality K1
- Open default filament profile
- Save as a new profile
- Close Orcaslicer
- Open Orcaslicer

### Actual results

The saved profile(s) are gone, replaced with only "Default Filament"

### Expected results

The saved profiles still being listed

I can create and save new profiles for my P1P, it's just the K1 that has this issue

**Comment by dragoonmc** [comment]
similar to this I cannot keep any user presets in 1.8.0
