### ISSUE TITLE
Display time cost (money/h) seperately from filament price (money/kg) in print preview summary

### ISSUE THREAD

**Issue by DefenderVex** [SoftFever/OrcaSlicer#2615]
**Is your feature request related to a problem? Please describe.**
Not exactly a problem but it's a small feature that would make estimating production costs slightly easier. It's definitely a QoL feature.

**Which printers will be beneficial to this feature**
All?

**Describe the solution you'd like**
Simply as described in the title, provide an additional breakdown for the total estimations in the print preview to display the time cost and filament cost separately in addition to the current combined value.

**Describe alternatives you've considered**
I don't think there really are alternatives for this kind of suggestion, I guess you could math it yourself instead of setting the cost per print hour?

**Additional context**
Useful for those who print on a commercial basis.

**Comment by Ocraftyone** [comment]
This is already implemented in 1.8 betas

**Comment by DefenderVex** [comment]
Where? Because I'm on 1.8.0 Beta 2, it only gives me the combined value.
![Screenshot 2023-11-09 124051](https://github.com/SoftFever/OrcaSlicer/assets/1343068/5963f3fa-ac29-480a-9762-7d534e837118)

**Comment by Ocraftyone** [comment]
Whoops! You are right. I will look into adding that metric.
