### ISSUE TITLE
Text debossing/cut function

### ISSUE THREAD

**Issue by DVSVIDEO** [SoftFever/OrcaSlicer#2616]
**Is your feature request related to a problem? Please describe.**
Please enable the option to add inward-bulging text to the 3D model.

**Which printers will be beneficial to this feature**
Not printer dependent

**Describe the solution you'd like**
A solution similar to the CUT or JOIN radio buttons in Prusaslicer

**Describe alternatives you've considered**
Complete port of the Prusaslicer complex text module

**Comment by Noisyfox** [comment]
It's on the road map.

**Comment by DVSVIDEO** [comment]
> It's on the road map.
Great...I'm glad. thanks for the reply!
