### ISSUE TITLE
Avoid crossing walls - rough walls

### ISSUE THREAD

**Issue by Z18Aplha** [SoftFever/OrcaSlicer#2621]
### OrcaSlicer Version

1.7.0

### OS version

Windows 11

### Additional system information

CPU: AMD Ryzen 7 3800X
Memory: 32GB
GPU: GTX1080

### Printer

Ender3 Pro - but completely upgraded

### How to reproduce

1. Use a Model with curves and separate details
2. Check "Avoid Crossing Walls"
3. Slice
4. Inspect the result and check "travel" to display

### Actual results

The travel moves which are caused by the "avoid crossing walls" function are generally quite good. But they are on the visible side of outer walls. So in fact the mid point of the nozzle is right above outline of the model which causes ugly and rough walls.
![Travel_move](https://github.com/SoftFever/OrcaSlicer/assets/44472284/d3ce6bed-20a3-4b81-aa1f-cd3eba840028)
![IMG_0521](https://github.com/SoftFever/OrcaSlicer/assets/44472284/6981919f-9eb5-43c0-949f-3e1a9c3594b5)

### Expected results

Travel moves to avoid crossing walls should have an offset to the outline of the model (at least half of the nozzle diameter) or should be located between outer walls.

### Project file & Debug log uploads

[avoid_crossing_walls_issue.zip](https://github.com/SoftFever/OrcaSlicer/files/13259682/avoid_crossing_walls_issue.zip)
[debug_Sat_Nov_04_22_18_40_28852.log.zip](https://github.com/SoftFever/OrcaSlicer/files/13259683/debug_Sat_Nov_04_22_18_40_28852.log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by CCS86** [comment]
Superslicer improved this by making sure the travel path was inset from the outer wall. Major improvement in quality. Orca devs should port that change in.
