### ISSUE TITLE
1.8.0: Settings Missing from STRENGTH > ADVANCED

### ISSUE THREAD

**Issue by CCS86** [SoftFever/OrcaSlicer#2623]
### OrcaSlicer Version

1.8.0-b2

### OS version

Win 10 x64

### Printer

X1C

### How to reproduce

Look at settings > strength > advanced

### Actual results

![image](https://github.com/SoftFever/OrcaSlicer/assets/12439543/92d6fa8a-8c59-4528-ba56-bb0e77a9ee22)

These settings are missing and "detect narrow internal solid infill" seems to be forced on.

### Expected results

These settings should be available to change.

### Project file & Debug log uploads

...

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by SoftFever** [comment]
The algorithm has been changed hence these option had been removed.
The ensure vertical shell thickness toggle will be added back in 1.8 official though

**Comment by Tarakesh83** [comment]
This forced on option is now actually destroying parts.
Even with Pressure Advance set to 0 in klipper the concentric infill produces gaps where as the old monotonic setting did not.
This behaviour should immediatelly be reverted.

**Comment by CCS86** [comment]
> The algorithm has been changed hence these option had been removed. The ensure vertical shell thickness toggle will be added back in 1.8 official though


This is my experience. Loading the same project in 1.8.0-b2, I get a very different and undesirable infill.


![image](https://github.com/SoftFever/OrcaSlicer/assets/12439543/69c41877-ddd9-40fc-ab7e-adc458da7d83)
