### ISSUE TITLE
Orca error, vector too long

### ISSUE THREAD

**Issue by pmarkiewicz** [SoftFever/OrcaSlicer#2634]
### OrcaSlicer Version

1.8.0 beta 2

### OS version

Window 10

### Printer

Kossel mini

### How to reproduce

Slices correctly on Voron 0.1 profile but fails on Kossel Mini (delta printer with round bed)
Just add project file and try to slice

### Actual results

Error message vector too long

### Expected results

sliced model

### Project file & Debug log uploads

[heater foot v1.zip](https://github.com/SoftFever/OrcaSlicer/files/13272504/heater.foot.v1.zip)
[log.zip](https://github.com/SoftFever/OrcaSlicer/files/13272506/log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by SoftFever** [comment]
Thanks for reporting the issue.
This issue duplicated with this one https://github.com/SoftFever/OrcaSlicer/issues/2537
It should have been fixed in nightly build
