### ISSUE TITLE
Filament change problem

### ISSUE THREAD

**Issue by olcayoren** [SoftFever/OrcaSlicer#2635]
### OrcaSlicer Version

1.7.0

### OS version

Macos Sonoma 14.0

### Additional system information

Macbook air M1

### Printer

Elegoo Neptune 4 Pro

### How to reproduce

When new filament is added to the filament replacement bar, the total time is disrupted.

### Actual results

Klipper crash and print interruption

### Expected results

Klipper crash and print interruption

### Project file & Debug log uploads

[gcodes.zip](https://github.com/SoftFever/OrcaSlicer/files/13273082/gcodes.zip)

https://github.com/SoftFever/OrcaSlicer/assets/33813227/bbf3188e-7e29-4556-9718-6c2b85d0919b

[problem_filament.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/13273087/problem_filament.3mf.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by Noisyfox** [comment]
Are you using an arm mac?

**Comment by olcayoren** [comment]
> Are you using an arm mac?

Yes arm mac m1

**Comment by Noisyfox** [comment]
Then this is a known issue that only presents on arm macs. I currently don't have my m1 mac around until maybe a few weeks later, then I'll be able to take a look.

**Comment by olcayoren** [comment]
> Then this is a known issue that only presents on arm macs. I currently don't have my m1 mac around until maybe a few weeks later, then I'll be able to take a look.

Thank you, this problem does not happen all the time, sometimes it happens all the time and sometimes it happens occasionally. I couldn't understand why either.

**Comment by IanAlbinson** [comment]
Same issue for me. Thanks for report this, @olcayoren.

**Comment by SoftFever** [comment]
Thank you all.
I've pushed a fix for the issue.

Could you help verify if the fix works by trying the latest dev build?

**Comment by olcayoren** [comment]
> Thank you all. I've pushed a fix for the issue.
> 
> Could you help verify if the fix works by trying the latest dev build?
Hello, which version do I need to install? is there an installation url?

**Comment by SoftFever** [comment]
> > Thank you all. I've pushed a fix for the issue.
> > Could you help verify if the fix works by trying the latest dev build?
> 
> Hello, which version do I need to install? is there an installation url?

You can download the latest dev build here: https://github.com/SoftFever/OrcaSlicer/actions/runs/6813204358

**Comment by IanAlbinson** [comment]
Awesome! Working for me here. Thank you.

**Comment by Noisyfox** [comment]
> Thank you all. I've pushed a fix for the issue.
> 
> Could you help verify if the fix works by trying the latest dev build?

Did this line solve this particular problem?

https://github.com/SoftFever/OrcaSlicer/commit/df0a49a73d1c61ba6cfbebb61ea7719d8e8ab532#diff-419b5af87b597b78d30c0cfa8db1f11894084e7b8ae4a0e0fad3af4ae3b4e995R740

**Comment by olcayoren** [comment]
> > > Thank you all. I've pushed a fix for the issue.
> > > Could you help verify if the fix works by trying the latest dev build?
> > 
> > 
> > Hello, which version do I need to install? is there an installation url?
> 
> You can download the latest dev build here: https://github.com/SoftFever/OrcaSlicer/actions/runs/6813204358

Hello, the problem has been resolved. Thanks.

**Comment by discip** [comment]
@olcayoren
> Hello, the problem has been resolved. Thanks.

If so, than please close this issue. 😊

thanks
