### ISSUE TITLE
Prime tower extend beyond the table

### ISSUE THREAD

**Issue by andronick83** [SoftFever/OrcaSlicer#2642]
### OrcaSlicer Version

1.7.0

### OS version

Windows 10

### Printer

ELEGOO Neptune 4

### How to reproduce

1. Add additional table
2. Add prime tower

### Actual results

On additional tables, the tower lines extend beyond the table
![image](https://github.com/SoftFever/OrcaSlicer/assets/439962/52862217-52b8-445e-84a4-886783b29c38)

### Expected results

-

### Project file & Debug log uploads

-

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by SoftFever** [comment]
This bug has been fixed in 1.8
