### ISSUE TITLE
Slicer creating geometry inside infill underneath the actual geometry

### ISSUE THREAD

**Issue by msteele999** [SoftFever/OrcaSlicer#2645]
### OrcaSlicer Version

1.8.0 beta 2

### OS version

Windows 11 Home

### Printer

Bambu Lab X1cc

### How to reproduce

- import model
- change filament to something easy to view (yellow)
- slice
- view layers and notice that they show infill, then some geometry, then infill (see screen shots)
- this was not happening in 1.7.0
- turning 'Only one wall on top surfaces' to off changes the behavior
- These are sliced with 100% infill to highlight what is happening

First two images are v1.7.0 - remaining images are 1.8.0 beta 2 (also happened in beta 2)

![Snag_10612fee](https://github.com/SoftFever/OrcaSlicer/assets/6474337/dfed9586-5235-4af4-824c-09701423ce89)

![Snag_10613d7b](https://github.com/SoftFever/OrcaSlicer/assets/6474337/dc63903b-b1ef-46e7-8e7c-54f82c3cb18a)

1.8.0 beta 2

![Snag_10619b99](https://github.com/SoftFever/OrcaSlicer/assets/6474337/6ab1c58f-464b-4eae-b991-9b2db7ad6eab)
![Snag_1061b0a7](https://github.com/SoftFever/OrcaSlicer/assets/6474337/c8120747-8a79-443e-a1fe-aa63a2b2bdfb)
![Snag_1061bf9c](https://github.com/SoftFever/OrcaSlicer/assets/6474337/1e248cfe-04f9-4f07-80fc-538905493333)
![Snag_1061cc6d](https://github.com/SoftFever/OrcaSlicer/assets/6474337/a5fc3f3f-562e-49a8-b9f5-a8668a4ca892)
![Snag_1061d854](https://github.com/SoftFever/OrcaSlicer/assets/6474337/62a2747b-d0b0-44a0-a2ce-b2223f243cb3)

### Actual results

this creates issues when printing - lots of retractions and slower printing due to printing geometry that will never be seen and is not needed for support.

### Expected results

just print smooth 100% infill layers until the actual geometry is reached.

I have inspected the model in Fusion using sectional analysis and the geometry is not overlapping - they sketches are created on top of the main surface and extruded upwards.

### Project file & Debug log uploads

[log.zip](https://github.com/SoftFever/OrcaSlicer/files/13281126/log.zip)
[geometry_inside_infill.zip](https://github.com/SoftFever/OrcaSlicer/files/13281127/geometry_inside_infill.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by msteele999** [comment]
Update - if I increase the number of bottom layers to be equal to the layer immediately before the color change / where the geometry SHOULD start, I can get the slice to only have ONE layer of geometry in the infill - which is workable.

![Snag_1294a00b](https://github.com/SoftFever/OrcaSlicer/assets/6474337/66563d22-3054-44a9-8614-9cbb7c297f8a)

**Comment by Noisyfox** [comment]
When I open the 3mf it says the file does not contain any geometry data. Could you reload the project file?

**Comment by msteele999** [comment]
I saved the project again - please let me know if this one works.

[RF Radiation - New v4.zip](https://github.com/SoftFever/OrcaSlicer/files/13328032/RF.Radiation.-.New.v4.zip)

**Comment by Noisyfox** [comment]
Yep that works.

For now you can disable the "Detect narrow internal solid infill" and "Ensure vertical shell thickness" which should greatly improve the quality (but the "Only one wall on top surfaces" still won't work well).

**Comment by msteele999** [comment]
Will do - standby

**Comment by msteele999** [comment]
Ouch - that actually made it worse.

Making the bottom layers >= the start of the new geometry works the best.

**Comment by Noisyfox** [comment]
Yeah I noticed. Your model is actually a great benchmark for testing slicing thing but complicated objects, and I've so far noticed a few more other types of defects, comparing to BBS and SS. Will try fixing each of them.

**Comment by msteele999** [comment]
Nice!

Glad to assist - let me know how I can contribute

**Comment by Noisyfox** [comment]
Are you able to give this build a try and see if that improves the quality? https://github.com/SoftFever/OrcaSlicer/actions/runs/6846552190

**Comment by msteele999** [comment]
This works properly!

**Comment by msteele999** [comment]
Note - I still have to set the infill to 100% - if I set it lower - I see
the geometry inside the lower layers still - but I can work around that

**Comment by msteele999** [comment]
Very good!

Please let me know how I can assist.

**Comment by Noisyfox** [comment]
Another tip:
Set "One wall threshold" to 0 while "Only one wall on top surfaces" turned on will remove the scars on the surface.

**Comment by msteele999** [comment]
testing!

**Comment by msteele999** [comment]
Which of these is one wall threshold? I assume by '0' you mean unchecked?

**Comment by msteele999** [comment]
[image: image.png]

**Comment by msteele999** [comment]
Nevermind - I see it - have to select it first to get the threshold

**Comment by msteele999** [comment]
That still leaves one layer with the next geometry being printed even
though it should be a solid top layer :-(

[image: image.png]

**Comment by Noisyfox** [comment]
Hmmmm unfortunately your images are all broken.

**Comment by scruplelesswizard** [comment]
> Another tip: Set "One wall threshold" to 0 while "Only one wall on top surfaces" turned on will remove the scars on the surface.

Setting _One wall threshold_ to `0` solved issues I was having in 2.1.1 with unexpected infill patterns under text. Does this behavior indicate a regression for #2716?

### `One wall threshold=300%`
![Screenshot 2024-07-10 091549](https://github.com/SoftFever/OrcaSlicer/assets/15822260/91eecd1b-f63a-46bc-aa6d-d4ae51f5f2e2)

### `One wall threshold=0`
![Screenshot 2024-07-10 091621](https://github.com/SoftFever/OrcaSlicer/assets/15822260/c16ed0d4-f2dc-417a-a60c-b49df8b52432)
