### ISSUE TITLE
Overhang Acceleration

### ISSUE THREAD

**Issue by pinwc4** [SoftFever/OrcaSlicer#2649]
**Is your feature request related to a problem? Please describe.**
When printing with high acceleration (20,000+ mm/s2) with PET-G I have a lot of curling in overhangs no matter what speed.  
  
**Which printers will be beneficial to this feature**
Annex K3 with Klipper

**Describe the solution you'd like**
Implement the ability to set the acceleration of overhangs.  

**Describe alternatives you've considered**
I currently use SuperSlicer which has this feature.  I experimented with various speeds to try to get OrcaSlicer to print the overhangs but that did not solve the problem.  

**Additional context**
Here is where you can set the setting in SuperSlicer
<img width="1025" alt="Screenshot 2023-11-07 at 11 36 16 AM" src="https://github.com/SoftFever/OrcaSlicer/assets/6935382/521a94b4-3a14-4d25-bb50-752b9f0363eb">

**Comment by Jaze20** [comment]
Not a solution to your problem.  Overhang control feels janky/buggy in Orcaslicer.  But putting that aside for now... 

To print my corner overhangs, I've had to go to 12mm/s (10%) and 16mm/s (25%).  Perimeters slowed down to 35mm/s for inner wall and 32mm/s for outer wall.  Without slowing it all down, the infill seems to pull the edge in causing it to curl up.  You can use modifier blocks if you want to speed up the print as much as possible so the problem areas are sufficiently slow.

**Comment by eafq78** [comment]
+1

**Comment by Firebirbionmahtavakoodaajees** [comment]
Bump
