### ISSUE TITLE
Not notifying anymore about new releases

### ISSUE THREAD

**Issue by martinrosolino** [SoftFever/OrcaSlicer#2656]
### OrcaSlicer Version

1.8.0 beta 1

### OS version

W11

### Printer

Hellbot Magna 2 300

### How to reproduce

Some versions before, i'll pop a message saying that a new version was abailable, what happened?

### Actual results

No notification about new releases

### Expected results

Notification about new releases

### Project file & Debug log uploads

idk

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Ocraftyone** [comment]
It is possible that it is because the new releases are betas.

**Comment by martinrosolino** [comment]
ok, I don't remember since when I've stopped receiving notifications, but it may be the cause, thanks man

**Comment by discip** [comment]
@martinrosolino
As this seems to be solved, please don't forget to close. 😊

thanks
