### ISSUE TITLE
Add Elegoo Neptune 4 Plus Printer Profile

### ISSUE THREAD

**Issue by sebastianbagya** [SoftFever/OrcaSlicer#2663]
Please add elegoo neptune 4 plus printer profile, I already try to print on elegoo neptune 4 plus with elegoo neptune 4 max printer profile (adjusted size), but I see some error / warning in fluidd console. So I will be glad if the printer profile is officially added, thank you.

**Comment by Axil94** [comment]
This would be amazing

**Comment by CINCOxBINCO** [comment]
Need this

**Comment by prisma7411** [comment]
würde mich auch interessieren :-), da es wirklich fehlt.

**Comment by MathiasKrill** [comment]
same problem here, need this.

**Comment by YvesSun23** [comment]
+1

**Comment by BlazS14** [comment]
This would help me as well :)

**Comment by BarleyBrewhammer** [comment]
Need this :)

**Comment by Badwolf7691** [comment]
Please, don't want top Patreon "Uncle Jessy" who Elegoo pays already.

**Comment by AE3D-A99** [comment]
Thanks Badwolf7691

i need also the profile for the new neptune 4 + but i don´t want to buy a membership to get this from "uncle Jessy".
Especially not when elegoo is paying him.

**Comment by GeneralDraga1701** [comment]
Please, By the gods of 3D Printing Add an Official Neptune 4 Plus profile! The Max profile with changed bed size doesnt seem to work right hinting at something else different with the Plus and Max.

**Comment by GeneralDraga1701** [comment]
> Thanks @Badwolf7691 for the hint with that Uncle Jessy, i paid the 2$ to get a good working profile. Without that i would not be able to use orca - thank you ! UPDATE: That Uncle Jessys profil is trash for the printer everything i try out is trash.

how do you import a profile like uncle jessy to orca? Im still very newish.

**Comment by BlazS14** [comment]
Just a psa for anyone using the n4 max profile on the n4+. I dont know why but i think that the fan structure on the backside of the y axis gantry isnt accounted for in the extruder size settings, so any prints that have the print by part setrring enabled (not by layer) may bump into previously printed parts on the bed. Otherwise the modified max profile with smaller bed dimensions works great for me.

**Comment by w34sel** [comment]
Here i made a profile for the EN4P, try it out.
no guarantees :)
https://github.com/w34sel/3D-Printing/tree/main

**Comment by vaxkun** [comment]
> Here i made a profile for the EN4P, try it out. no guarantees :) https://github.com/w34sel/3D-Printing/tree/main

Im waiting for the plus to arrive, is this working nice for u ppl?

**Comment by CreativeLens** [comment]
> Here i made a profile for the EN4P, try it out. no guarantees :) https://github.com/w34sel/3D-Printing/tree/main

Hi,
Thanks @w34sel  for the Profile, I directly installed it.

One Question, and please excuse if it sounds a little dumb I am new to the Game, why are the Speedsettings so low? I get it for the first layer, but why are the other layers at 80 or 100? 
Till now I printed with the Neptune 3 Plus Profile and the settings were also very slow. Thought 250mm/s is recommended by Elegoo.

Can you tell me, what is best?

**Comment by Kalooth** [comment]
@CreativeLens, the N4 Max profile that people usually say to copy and just change the bed size is running with those slower speeds. I've been running with my PR, https://github.com/SoftFever/OrcaSlicer/pull/2980  for over a week and haven't had any issues yet but... I'm a sample size of 1 so let me know if you give it a shot and if you run into issues.

**Comment by w34sel** [comment]
@CreativeLens I chose that speed because it was the same for the N4pro and N4Max standard profile, so I thought it would be nice to maintain consistency by using the same values across the profiles. However, you can certainly use a higher speed if desired.

You can tweak it for each print.

Here is a small image marked with different colors:
Blue: Outer wall
Orange: Inner Wall
Purple Top: Surface
Red: Sparse Infill
White: Internal solid ( imagine this is fully printed)

![fdm-sparse-fill-3](https://github.com/SoftFever/OrcaSlicer/assets/17765081/0775f110-46f3-4f5e-938d-c5edf679f999)

**Comment by francois-thi** [comment]
@CreativeLens Hello,

Brand new here in 3D printing ! Thanks for the profile, I downloaded it and installed it. I saw that the bed size is 330x330 in your profile, however the bed size for the Neptune 4 plus is 320x320. Is that normal or is that a mistake ? 

Thanks !

**Comment by CreativeLens** [comment]
Hi,

I think it is a mistake, but the Profile is from @w34sel  :)

**Comment by w34sel** [comment]
@francois-thi  I have copied the dimensions of the bed from the cura 4 elegoo profile for the n4plus

**Comment by helmanis** [comment]
@francois-thi If you measure the bed manually then it will be 330x330. Was suprised too, but had to replace the PEI Plate, so i know ;)

**Comment by francois-thi** [comment]
@helmanis Oh, thanks ! I didn't notice that :p

**Comment by Shotgun-Monk** [comment]
Does this Orca profile work well? I am tired of the Elegoo Cura I am having issues that seem slicer related because if I print anything that Elegoo sliced like the Buddha or Flower pot it comes out perfect so it tells me the printer is mechanically sound.

**Comment by Shotgun-Monk** [comment]
@w34sel, Thank You for making the Orca slicer profile. It is working great, better than the Uncle Jessy profile TBH.

**Comment by w34sel** [comment]
Thx man :D
https://github.com/w34sel/3D-Printing/

**Comment by francois-thi** [comment]
@Shotgun-Monk Hey, yes it's working great ;) I'm using it since a couple of weeks now, and I had no problems at all.

**Comment by Georgelou35** [comment]
Can i make one question @w34sel?So what are the differenc between your profile and th stock neptune4 plus orca profile?🤔🤔

**Comment by francois-thi** [comment]
@Georgelou35  Is there any Neptune 4 plus profile in Orca ?  I couldn't find one, only the Neptune 4 pro.

**Comment by Georgelou35** [comment]
The new 1.9 has neptune 4 plus Profile

**Comment by francois-thi** [comment]
@Georgelou35  Hurray ! Waiting for @w34sel answer then, but to be honest, it has been working perfectly fine for me since I downloaded it.

**Comment by Georgelou35** [comment]
Also i wonder what are the differences between stock and w34sel profile

**Comment by w34sel** [comment]
My bed size is 330x330 and the height is 387 (using dimensions from the Elegoo Cura profile) along with some speed settings. The current profile in version 1.9.0 was submitted by another guy who made his pull request earlier than mine.

**Comment by Georgelou35** [comment]
W34sel thank you very very much.Now i will put to print a deadpool helmet to see the results.

**Comment by w34sel** [comment]
@Georgelou35 please share your results with me :)

**Comment by Georgelou35** [comment]
Yeah yeah.So far so good.when i go home in about 4 hours i will send picture here.

**Comment by Georgelou35** [comment]
Also,do you know how i can when i transfer the gcode to transfer and the thumbnail???

**Comment by Georgelou35** [comment]
![IMG_20240117_143422](https://github.com/SoftFever/OrcaSlicer/assets/147695661/4973cd13-d3e8-4258-b7c3-de2ed5143716)
![IMG_20240117_143411](https://github.com/SoftFever/OrcaSlicer/assets/147695661/040ab959-cad6-46e8-9c88-1b7a0ce8ed42)
![IMG_20240117_143404](https://github.com/SoftFever/OrcaSlicer/assets/147695661/78846e0f-c113-44ad-816a-76effb92c425)
![IMG_20240117_143353](https://github.com/SoftFever/OrcaSlicer/assets/147695661/e211a09a-28f6-4ff7-afd2-0cc2e250c0bd)
![IMG_20240117_143331](https://github.com/SoftFever/OrcaSlicer/assets/147695661/c1ab7e4e-b66d-412c-a6fb-51d3a45e7e06)
![IMG_20240117_143323](https://github.com/SoftFever/OrcaSlicer/assets/147695661/fc13612a-1cdb-4a86-bcfd-2493d7404652)
![IMG_20240117_143319](https://github.com/SoftFever/OrcaSlicer/assets/147695661/66aec133-efc3-474c-8a11-895c46b3a7f1)
![IMG_20240117_143316](https://github.com/SoftFever/OrcaSlicer/assets/147695661/57e57f59-dfeb-4da0-bd0b-32b550b57896)
![IMG_20240117_143105](https://github.com/SoftFever/OrcaSlicer/assets/147695661/f010dd25-5717-4ccd-b15e-ff9c6d1a65fd)

**Comment by Georgelou35** [comment]
Its going well.

**Comment by w34sel** [comment]
@Georgelou35 nice :D 
Here is a repo for the thumbnails https://github.com/Molodos/ElegooNeptuneThumbnails-Prusa

**Comment by Georgelou35** [comment]
So one dayhas pass.So far so good.I dont have so much strings the print is so clean.Can wait to finish.
![IMG_20240118_084313](https://github.com/SoftFever/OrcaSlicer/assets/147695661/4b7d80b3-0c52-4e23-8519-d27e6f7e4dd2)
![IMG_20240118_084315](https://github.com/SoftFever/OrcaSlicer/assets/147695661/8b7f3ba5-8705-4aa4-8b23-8e5e4dc9beb2)
![IMG_20240118_084331](https://github.com/SoftFever/OrcaSlicer/assets/147695661/1c117485-b1bf-4ea4-a1c6-a80a8cd84836)
![IMG_20240118_084322](https://github.com/SoftFever/OrcaSlicer/assets/147695661/255a9114-4d8a-40b4-b894-e1edeede9e7d)
![IMG_20240118_084328](https://github.com/SoftFever/OrcaSlicer/assets/147695661/517ab2b1-136c-4ab7-b9c5-073df0097eaf)

**Comment by Georgelou35** [comment]
Also before deadpool helmet i print a gengar with stock profile.But the results was not good🤷🤷 i will print it again with your profile when i will finish the deadpool helmet
![IMG_20240118_084346](https://github.com/SoftFever/OrcaSlicer/assets/147695661/159175ce-9f37-4f75-9c6b-ce0b08526953)
![IMG_20240118_084352](https://github.com/SoftFever/OrcaSlicer/assets/147695661/a26aaebf-4e6e-42e2-b0b1-b211b3c3f8d3)

![IMG_20240118_084359](https://github.com/SoftFever/OrcaSlicer/assets/147695661/92436fc1-e3c4-48d2-9e14-5bf9227f5804)

**Comment by w34sel** [comment]
@Georgelou35 Here for the thumbs https://github.com/fifonik/ElegooNeptuneThumbnailPrusaMod  
It is working fine.

**Comment by Fleky** [comment]
> Gracias hombre: D https://github.com/w34sel/3D-Printing/

Muchas gracias amigo. Llevo una semana con orca y casi me di por vencido. Va muy bien.

**Comment by w34sel** [comment]
Hey @Coop94,

i will create simple copy installer in the next few days for you and upload it on my Github repo. I will inform you when it is rdy.

**Comment by Coop94** [comment]
Thanks w34sel.

**Comment by Coop94** [comment]
Thank you so much. I’m new to all this. Sent from my iPhoneOn Feb 23, 2024, at 11:30 PM, w34sel ***@***.***> wrote:﻿
Hey @Coop94,
i will create simple copy installer in the next few days for you and upload it on my Github repo. I will inform you when it is rdy.

**Comment by w34sel** [comment]
@Coop94  after rethinking it makes no sense for me to do this. 
Here a small instruction:
1) Download the repo as ZIP unpack and
2) go to §D-Printing/Elegoo Neptune 4 Plus/orca_19.0
3) copy the folders 2 folder to the following path in your home system (windows)
- copy "profiles" folder to "C:\Program Files\OrcaSlicer\resources" 
- copy "default" folder to "C:\Users\<USERNAME>\AppData\Roaming\OrcaSlicer\user"

**Comment by Coop94** [comment]
If I don't have the second folder, do i just need to create one?

**Comment by w34sel** [comment]
There should be one, if not drop the fault order to:
Type into your explorer %appdata% and go to "\OrcaSlicer\user" 
or
C:\Users\COOP94\AppData\RoamingOrcaSlicer\user

**Comment by Coop94** [comment]
i found it. There was a check box to show hidden folders that wasn't checked. Thanks again

**Comment by Kenepo17** [comment]
> There should be one, if not drop the default order to: Type into your explorer %appdata% and go to "\OrcaSlicer\user" or C:\Users\COOP94\AppData\RoamingOrcaSlicer\user

I did as instructed. I do use Elegoo Pla and Elegoo Rapid PETG. For the pla use your settings under sunlu pla?
