### ISSUE TITLE
Vector too long FLsun V400

### ISSUE THREAD

**Issue by spmfred** [SoftFever/OrcaSlicer#2664]
### OrcaSlicer Version

1.8.0 beta 2

### OS version

Windows 10 pro

### Printer

FlSun V400

### How to reproduce

Tried to slice a file and it goes through the slicing and at the end pops up and says "vector too long"

### Actual results

Won't output Gcode file

### Expected results

Should finish slicing and ask to save or send sliced gcode file
[christus.zip](https://github.com/SoftFever/OrcaSlicer/files/13297338/christus.zip)

### Project file & Debug log uploads

[christus.zip](https://github.com/SoftFever/OrcaSlicer/files/13297348/christus.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by lightmaster** [comment]
I have received this error too, on a FLSun Q5. Error specifically is `cannot create std::vector larger than max_size()`

**Comment by lightmaster** [comment]
Seems like this is probably the same as #2537, in which case it's reportedly fixed in a nightly build.

**Comment by SoftFever** [comment]
It has been fixed in 1.8.0 RC2, can you check?

**Comment by lightmaster** [comment]
I haven't seen it again on RC2, even on a project that was throwing that error every time before.

**Comment by discip** [comment]
@spmfred
Have you tested the latest build?
If that solves it for you, please consider closing this issue. 😊

thanks

**Comment by mydevpeeps** [comment]
I am now getting this on a Bambu X1C profile for a project I'm working on. The other plates printed fine and the object is no more complex than all the others. I am on 2.3.0. 

_NOTE: If I "Fix Model" (which wipes the painting by layers), and then repaint it again, it will slice._ 

![Image](https://github.com/user-attachments/assets/95fba8e4-9f0c-4b50-9954-9bd1084e0180)

![Image](https://github.com/user-attachments/assets/5abc3df7-fa64-490c-9341-f218b1da6901)
