### ISSUE TITLE
1.8beta2，桥接异常，平滑基础率导致异常速度

### ISSUE THREAD

**Issue by Dominguez-Z** [SoftFever/OrcaSlicer#2682]
### OrcaSlicer Version

1.8.0-beta2

### OS version

Windows11

### Printer

creality CR6MAX

### How to reproduce

一、桥接异常
使用1.7.0正式版切片正常的桥接模型，在1.8测试版会在连接处欠缺长度，导致桥接不上，塌了。
随机使用默认的参数也是一样没接上。
使用工程文件中的1号盘测试。

二、平滑基础率导致异常速度
![image](https://github.com/SoftFever/OrcaSlicer/assets/83202771/2298f9c4-5a67-48a7-a0f8-c2dbcc3a3fb5)
![image](https://github.com/SoftFever/OrcaSlicer/assets/83202771/5b3045b8-38d3-481d-aeea-93d8cbeb7360)

1、在开启熨烫和平滑挤出率的情况下，会出现速度只有1的极慢的层。
2、单独把熨烫关闭后，1速度的层就没有了，层速度的变化会不均匀，这个第三点应该是相关的。
3、换了单独把平滑挤出率关闭后，速度正常。

![image](https://github.com/SoftFever/OrcaSlicer/assets/83202771/f1484628-5d5b-4df7-9b1b-f3465cec5353)

![image](https://github.com/SoftFever/OrcaSlicer/assets/83202771/29d2ee1a-bbf1-4e42-8671-53257c60375d)

4、同样的模型在prusa中切出来较为均匀。
使用工程文件中的2号盘测试。

三、平滑挤出率对于同样的模型切片出来的结果不同
![image](https://github.com/SoftFever/OrcaSlicer/assets/83202771/de8dca25-9d1e-4b0b-a7cf-acf8600c68c3)
![image](https://github.com/SoftFever/OrcaSlicer/assets/83202771/97172a7f-b9c0-4244-8dc7-482fbd51be67)
![image](https://github.com/SoftFever/OrcaSlicer/assets/83202771/99ffe958-0e7b-4bb2-9ae8-fd64889e47df)
同样的方块模型9个，实心填充，开启平滑挤出率后，切片出来的速度变化并不是均一的。
1、接缝位置选择最近，每一个模型的实心填充起始点切片出来比较随机。变速也会在不同位置启动，但是是不均匀的启动，有些起始有变速，有些起始没有变速。
如果选择对齐，则会出现一层有变速一层没有。
2、实心填充开启或者关闭对结果基本不影响。
3、平滑挤出率仅在填充的起始有，收尾的时候没有，这个prusa的结果不一样。感觉prusa的比较合适。

### Actual results

一、桥接异常
1.8测试版切片结果
![1699586571730](https://github.com/SoftFever/OrcaSlicer/assets/83202771/2ef1f22e-95ba-4b11-add2-4a955ef44323)
实际打印效果图
![~G8_R9LI`Y2P@`6U1O09X_W_tmb](https://github.com/SoftFever/OrcaSlicer/assets/83202771/df922d42-2ff8-4f20-9565-aa9896f2639d)

二、平滑基础率导致异常速度
1、极慢层
![1699587671135](https://github.com/SoftFever/OrcaSlicer/assets/83202771/43b7704c-904f-4323-a144-b9ea8ac581a5)

2、关闭熨烫，开启平滑挤出率
![image](https://github.com/SoftFever/OrcaSlicer/assets/83202771/13921e4e-3344-4f61-8b99-b64f459b46ba)

3、开启熨烫，关闭平滑挤出率
![image](https://github.com/SoftFever/OrcaSlicer/assets/83202771/95235585-20bb-45fb-8464-32ad270fea24)

三、平滑挤出率对于同样的模型切片出来的结果不同
最近接缝的有些有有些没，中间的甚至是一直没有
![image](https://github.com/SoftFever/OrcaSlicer/assets/83202771/13b5e9d9-da71-4cb3-8b5b-5c1f399017cb)
![image](https://github.com/SoftFever/OrcaSlicer/assets/83202771/5bbec429-75aa-4ec5-a40d-91cbd01079dd)

对齐的
![image](https://github.com/SoftFever/OrcaSlicer/assets/83202771/56ffa766-6e19-4454-8ae1-9897d4acf955)
![image](https://github.com/SoftFever/OrcaSlicer/assets/83202771/e213b802-aad0-45de-aecf-9547ebdfb3aa)

### Expected results

一、桥接异常
1.7.0正式版切片结果，有较长的一段在实体填充上，连接稳定。
![image](https://github.com/SoftFever/OrcaSlicer/assets/83202771/98fef150-63a7-4c23-94c1-1275f881b633)

二、平滑基础率导致异常速度
prusa中开启了压力均衡器，速度也是较为均匀的。
![image](https://github.com/SoftFever/OrcaSlicer/assets/83202771/b7fbd3fc-b7ab-4ea1-a8b8-422da6b8185c)

三、平滑挤出率对于同样的模型切片出来的结果不同
prusa的结果，起始有，收尾也有，且均一。
![1699589676182](https://github.com/SoftFever/OrcaSlicer/assets/83202771/c58796f6-8e4b-44eb-aa14-4a941b6116a7)

### Project file & Debug log uploads

[拉桥+平滑挤出率.zip](https://github.com/SoftFever/OrcaSlicer/files/13315408/%2B.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by igiannakas** [comment]
You will not see any smoothing if thr nozzle moves more than 2-3 mm from its last extrusion. The behaviour is different to prusa as arguably prusas implementation is slightly flawed. It doesn’t smooth on external perimeters and it smooths even after long moves , despite nozzle pressure having fallen to zero after a retraction move.

**Comment by SoftFever** [comment]
@Dominguez-Z, thank you for reporting the issues. 
Regarding the Pressure Equalizer issue, please see @igiannakas's explanation. 

As for the bridge issue, it occurs in your test model because there's a thin layer that could be interpreted either as a top surface or a bridge surface. 
The differing behaviors between versions 1.7 and 1.8 are due to 1.8 incorporating some of the latest algorithms from PrusaSlicer. 
While ideally, this part should be considered a bridge rather than a top surface, such cases are very rare. It's very unlikely we will have single layer bridge in actual model.
