### ISSUE TITLE
Fuzzy skin as Color painting.

### ISSUE THREAD

**Issue by PLAmenPRINT** [SoftFever/OrcaSlicer#269]
Hello,
I am printing electronic enclosures and cone objects (varieties of speaker waveguides) and for more aesthetically finish I am using fuzzy skin.

Unfortunately if I apply fuzzy skin "outside only" it is not working all the time as expected.
Sometimes I am using Modifier shape in order to restrict the fuzzy skin on particular area but together with the outside wall there is also internal fuzzy skin wall created which is annoying.
Frequently I need to have Fuzzy skin inside only but there is no such an option
It will be great to have a way to chose which surface to be with this effect like the colors with the AMS.

![image](https://user-images.githubusercontent.com/100955264/227004727-f492f002-23bf-4c28-a347-2681ea5eaf97.png)
![image](https://user-images.githubusercontent.com/100955264/227004766-579f0823-0b33-41a3-96e6-7b9f61ad18d0.png)
![image](https://user-images.githubusercontent.com/100955264/227004814-3636099b-030b-4fe9-b320-4071d372ce4b.png)

Example with speaker waveguide
![Sample](https://user-images.githubusercontent.com/100955264/215875796-9c370e5a-04a9-493b-8361-1de505176345.png)

Is it difficult to be implemented?
"Fuzzy skin Only Inside" will be simple alternative?
Thank You for the attention
Best Regards

**Comment by DmncS** [comment]
I talally agree to your issue, it would be great to have it paintable, like colors.

**Comment by thelonecabbage** [comment]
bump

**Comment by netweaver1970** [comment]
another upvote here. For esthetic reasons I would like the fuzzy skin on specific (mostly outside) surfaces but the build-in function treats too many surfaces as outside. 
So either that function needs to be made a lot smarter (very hard probably as it might be object specific how inside/outside would be humanly determined) or a manual/assised fuzzy skin paint option (prefered) is needed.
Thanks for looking into it.

**Comment by jilleb** [comment]
https://github.com/TengerTechnologies/Fuzzyficator adds this feature, by using a 2nd filament, which can be painted on and then should print as fuzzy. So far I haven't got it to work as paint-on feature.
