### ISSUE TITLE
Anchor Solid Infill by X mm from SuperSlicer

### ISSUE THREAD

**Issue by djngnear** [SoftFever/OrcaSlicer#2698]
**Is your feature request related to a problem? Please describe.**

The top layer is often left with holes when printing text on top of a flat object. I'd like to have a nice clean monotonic top layer underneath the text.

![OrcaSlicer Solid Infill Issue 2](https://github.com/SoftFever/OrcaSlicer/assets/87901234/0e1f6fb6-b224-481c-8991-7434a6b0226d)
![OrcaSlicer Solid Infill Issue 1](https://github.com/SoftFever/OrcaSlicer/assets/87901234/9d5ecc62-0f78-46f2-a70a-186a8c82b838)

**Which printers will be beneficial to this feature**
All printers

**Describe the solution you'd like**

I love the SuperSliceroption to fill in small areas with solid infill on top surfaces like under text or smaller objects. I went to Superslicer for this very reason. By default it's set to 150% but I like to bump it up to 300 or 400%. That way the monotonic infill just looks better and it doesn't need to navigate around holes.
![SS Anchor Infill 3](https://github.com/SoftFever/OrcaSlicer/assets/87901234/140cc2e8-c66e-4733-ba77-7b32870263b8)
![SS Anchor Infill 4](https://github.com/SoftFever/OrcaSlicer/assets/87901234/5d6305a1-3635-4298-9052-bd45c69a7a69)

**Comment by rizwansarwar** [comment]
+1 

This although some cases slightly more filament, saves a lot of time in printing, gives better surface finish and reduces chances of bad surfaces due to poor bridging. I think this should really be implemented as an option.

**Comment by djngnear** [comment]
> +1
> 
> This although some cases slightly more filament, saves a lot of time in printing, gives better surface finish and reduces chances of bad surfaces due to poor bridging. I think this should really be implemented as an option.

I agree. I make a lot of signs and it really affects my top layers.

**Comment by rizwansarwar** [comment]
![Lego-Brick-1](https://github.com/SoftFever/OrcaSlicer/assets/3135402/cd069832-e3f9-4a2b-a473-39a1b3131acb)

@SoftFever Another example, when printing a Lego brick. There is unnecessary holes on top surface, the studs of the lego start above the top surface, so I am not sure if it really necessary to have these holes on top surface and have the algorithm fill around those holes. An option to fill to not do it would be really useful. This is present in Super Slicer where infill can be anchored by X amount on certain layer heights to eliminate this type of stuff.

It is an advanced user option but extremely useful to have.

**Comment by rizwansarwar** [comment]
Why is this marked as stale? this is a valid request albiet low priority.

@SoftFever Do you think this is worth adding to list of wants?

**Comment by TheBoojah** [comment]
This setting is really useful in a wide number of instances.
Note the "bridged" option on the same line of the first screenshot in SuSi, this option is very useful as a lot of internal bridges become much easier to print cleanly, and where disjoint solid infills creates weak spots in the printed geometry.
