### ISSUE TITLE
Icon size is wrong on MacOS

### ISSUE THREAD

**Issue by Guilouz** [SoftFever/OrcaSlicer#270]
Compared to original Bambu Studio, icon is oversized.

On dock when is not launched, icon is oversized :

<img width="293" alt="Capture d’écran 2023-02-01 à 03 40 57" src="https://user-images.githubusercontent.com/12702322/215932309-f6d8f63b-cf57-4e47-9c61-cbd64f4d362e.png">

On dock when is launched, icon is correct :

<img width="289" alt="Capture d’écran 2023-02-01 à 03 41 12" src="https://user-images.githubusercontent.com/12702322/215932357-8aa4f474-6b7e-4f7f-88c9-ab713ce112b0.png">

In list mode, icon is oversized too :

<img width="251" alt="Capture d’écran 2023-02-01 à 03 41 28" src="https://user-images.githubusercontent.com/12702322/215932405-24832254-e6df-479c-b8d5-6a7d6112af02.png">

**Comment by SoftFever** [comment]
Thanks for the feedback.
Will fix it in the next update.

**Comment by Guilouz** [comment]
@SoftFever Just see your last update and it's not fixed.
