### ISSUE TITLE
K1 Max Camera view streched 

### ISSUE THREAD

**Issue by niedzial1983** [SoftFever/OrcaSlicer#2709]
### OrcaSlicer Version

1.8.0-rc2

### OS version

Window 11

### Printer

Creality K1 Max

### How to reproduce

When using DEVICE tab the camera view is streched out. 
![Screenshot 2023-11-12 200316](https://github.com/SoftFever/OrcaSlicer/assets/150622127/56762d8b-1918-4779-9041-12c72f9c8091)

### Actual results

The camera picture is streched out and not in correct resolution

### Expected results

Camrea window should be in correct resolution and size ( 1920*1080 )
![Screenshot 2023-11-12 200449](https://github.com/SoftFever/OrcaSlicer/assets/150622127/3ff7c3a2-9a0a-4df0-9c1c-167bf5d12606)

### Project file & Debug log uploads

in comments attched is a picture from Orca ( streched ) and Creality Print  ( correct ) 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by niedzial1983** [comment]
Attched is a picture from Orca ( s
![Screenshot 2023-11-12 200906](https://github.com/SoftFever/OrcaSlicer/assets/150622127/386e850c-1b39-413d-b299-0db6feece344)
treched ) and Creality Print ( correct )

**Comment by X-Ryl669** [comment]
This is still not fixed. Please reopen.
