### ISSUE TITLE
Property invisible - Don't support bridges

### ISSUE THREAD

**Issue by Shama71** [SoftFever/OrcaSlicer#2723]
### OrcaSlicer Version

1.8.0.-rc2

### OS version

Windows 11

### Printer

Any

### How to reproduce

Click button "Search in preset"
Type "bridge".
Select "Advanced: Don't support bridges"
<img width="322" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/53084859/8e304ba7-f950-481a-8415-0ead58a9a3d5">

### Actual results

![image](https://github.com/SoftFever/OrcaSlicer/assets/53084859/799b7dba-2114-4882-8c78-18553d5615a3)

### Expected results

Expected property.

### Project file & Debug log uploads

[Untitled.zip](https://github.com/SoftFever/OrcaSlicer/files/13335138/Untitled.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Noisyfox** [comment]
This option is not available for certain types of support, so it's hidden. Currently it creates some confusion and #2170 means for solving this.

**Comment by Shama71** [comment]
Thanks for answer.

"Max bridge length" not working.
Remove Support blocker.
[Fan.zip](https://github.com/SoftFever/OrcaSlicer/files/13335551/Fan.zip)

**Comment by Noisyfox** [comment]
That only works well for large wide bridges, which will prevent support at the center of the bridge. In your case it's actually trying to support the loops around the bridge, which are categorized as overhang walls not bridges.

**Comment by Shama71** [comment]
Thanks for answer.
