### ISSUE TITLE
Flow Calibration does not work with a 0.2 Nozzle 

### ISSUE THREAD

**Issue by Gecko774** [SoftFever/OrcaSlicer#2727]
### OrcaSlicer Version

1.8.0 RC2

### OS version

Windows 11

### Printer

Bambu P1S

### How to reproduce

1. Go to Calibration
2. Select Flow Calibration
3. Pass 1 or 2

### Actual results

The test is successfully loaded and sliced.

Then the Bambu calibrates itself and successfully draws the first line as shown in the picture. As soon as it comes to the plates (even if you deselect some) the print fails immediately.

Nothing has been changed to the printer/filament or other settings themselves

Using the factory Generic and Bambu PETG profiles
Material: Petg // Nozzle: 0.2

![20231113_205220](https://github.com/SoftFever/OrcaSlicer/assets/59656463/42affcde-4b32-4c73-bb08-0df7fd3f842f)

### Expected results

He should be able to create the test as normal.
The test works perfectly with a 0.4 Nozzle

### Project file & Debug log uploads

No file available at the moment

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by kleinwareio** [comment]
Maybe silly question, especially since you said "Nothing has been changed to the printer/filament or other settings themselves" but did you update `Printer -> Extruder -> Nozzle diameter` to be `0.2`?
