### ISSUE TITLE
Flow calibration doesn't account for bed size

### ISSUE THREAD

**Issue by pmarkiewicz** [SoftFever/OrcaSlicer#2732]
### OrcaSlicer Version

1.8 RC 2

### OS version

Window 10

### Printer

Voron 0.1

### How to reproduce

Select Voron 0 and create flow test pattern

### Actual results

Pattern is bigger than bed size

### Expected results

Flow test pattern should fit into bed

### Project file & Debug log uploads

n/a it's basic functionality

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by SoftFever** [comment]
It's a bit difficult to automatically adapt to small bed.
As a workaround, you can manually delete some blocks that you think is likely off(e.g. the +- 20% blocks)
