### ISSUE TITLE
Ability to save bed type

### ISSUE THREAD

**Issue by insp1re1** [SoftFever/OrcaSlicer#2734]
each time loading the slicer, bed type for bambu defaults to a certain bed type. enable the ability to save whichever bed type we require between restarts of the program.

Also using a creality k1, its greyed out and defaults to a high temp bed, allow us to change to textured beds and others.

**Comment by Noisyfox** [comment]
This should already be fixed in 1.8 RC1

**Comment by Eldenroot** [comment]
Fixed in 1.8
