### ISSUE TITLE
"Infill combination" feature ignores layer height limitations from "printer settings" section

### ISSUE THREAD

**Issue by Luojja** [SoftFever/OrcaSlicer#2735]
### OrcaSlicer Version

1.8.0-rc2

### OS version

Windows 10, Windows 11

### Printer

Kingroon KP3S (custom preset)

### How to reproduce

1. Go to "Extruder" tab in 'Printer settings"
2. Set max layer height limit less than [layer_height * n]. For example, I tried it with 0.4 max layer height limit and 0.125 layer height
3. Enable "Infill combination" feature (process settings - strength - advanced)
![image](https://github.com/SoftFever/OrcaSlicer/assets/142262383/b7c29fca-97a1-445a-926b-f6a3895eb146)

### Actual results

Maximum layer height becomes greater than layer height limit and proportional to current layer height

### Expected results

Maximum layer height should be less than maximum layer height limit

### Project file & Debug log uploads

[Layer Height Test.zip](https://github.com/SoftFever/OrcaSlicer/files/13348960/Layer.Height.Test.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by ZedOud** [comment]
This seems to be the same as #2175

**Comment by igiannakas** [comment]
This is intentional - there is a PR from Noisyfox available that resolves this however it’s uncertain whether this is an issue.

**Comment by Gamerou** [comment]
I cannot use infill combination in my prints because of this. I have max layer height set to 0.32mm on my 0.4mm nozzle and infill combination still wants to print 0.4mm high infills.

**Comment by igiannakas** [comment]
Raised a PR that aims to address this above.
