### ISSUE TITLE
Program crashes when start printing after slicing

### ISSUE THREAD

**Issue by rainerschulte** [SoftFever/OrcaSlicer#2737]
### OrcaSlicer Version

above 1.6.6

### OS version

Windows 10

### Printer

Voron Legacy

### How to reproduce

Load a model, slice and then start " print this buildplate".

Programm crashes immediately. After restarting Orca, it found a model to recreate. When start printing again, it crashes. 
Storing on Harddisk works and uploading and printing from ORCA or Browser works. 

### Actual results

Use a different Slicer because ORCA seems to have also another issue on first layer and overextrusion. Need to figure out which setting is wrong. The Printer is connected via LAN and Raspberry Pi 3.

### Expected results

Printing out of ORCA should be possible. Version 1.6.6 is working fine! (Except for the Overextrusion on Holes...)

### Project file & Debug log uploads

[SB_x_carriage_frame_right_MGN12.zip](https://github.com/SoftFever/OrcaSlicer/files/13350356/SB_x_carriage_frame_right_MGN12.zip)
[debug_Tue_Nov_14_16_03_49_17044.log](https://github.com/SoftFever/OrcaSlicer/files/13350476/debug_Tue_Nov_14_16_03_49_17044.log)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by Noisyfox** [comment]
Are you able to give this build a try and upload the crash log here? We are trying to improve the crash logs and want to take the chance to have a real world test. Thanks.
https://github.com/SoftFever/OrcaSlicer/actions/runs/6872395629?pr=2736
