### ISSUE TITLE
Cosmetic toolbar appearance

### ISSUE THREAD

**Issue by 66mkiqdv** [SoftFever/OrcaSlicer#2739]
### OrcaSlicer Version

1.8.0-rc2

### OS version

openSUSE Tumbleweed

## Hardware Information:
- **Hardware Model:**                       ASUS All Series
- **Memory:**                                      8.0 GiB
- **Processor:**                                   Intel® Core™ i5-4670K × 4
- **Graphics:**                                    AMD Radeon™ RX 570 Series
- **Disk Capacity:**                            1.9 TB

## Software Information:
- **Firmware Version:**                     1402
- **OS Name:**                                    openSUSE Tumbleweed
- **OS Build:**                                     (null)
- **OS Type:**                                      64-bit
- **GNOME Version:**                        45.1
- **Windowing System:**                   Wayland
- **Kernel Version:**                           Linux 6.5.9-1-default

### Printer

Creality Ender 3v2

### How to reproduce

New project > View > Use orthogonal view = ugly toolbar icons.

### Actual results

Orthogonal view messes with the toolbar icons, perspective view does not. Same issue is present in Bambu Studio.

Perspective view: 
![image](https://github.com/SoftFever/OrcaSlicer/assets/150845468/a55a90e3-696a-4229-ac28-042fbc81945a)
Orthogonal view:
![image](https://github.com/SoftFever/OrcaSlicer/assets/150845468/1d512187-0395-4f3b-bbf6-32f245b73a67)

### Expected results

Toolbar icon appearance is expected to remain the same regardless of view setting.

### Project file & Debug log uploads

Files not necessary.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Noisyfox** [comment]
Could you give this build a try?
https://github.com/SoftFever/OrcaSlicer/pull/2603/checks

**Comment by 66mkiqdv** [comment]
Build tried and the cosmetic distortion now affects both orthogonal and perspective views.

![image](https://github.com/SoftFever/OrcaSlicer/assets/150845468/6c4884ec-c2d8-475c-a078-1d456b5ff737)

**Comment by Noisyfox** [comment]
I see. Will try fixing this.

**Comment by Noisyfox** [comment]
Could you try this build? https://github.com/SoftFever/OrcaSlicer/actions/runs/6912441593

**Comment by 66mkiqdv** [comment]
I have tried the latest build you suggested and can confirm that the cosmetic distortion is no longer present, both perspective and orthogonal view look good. Nice job.
