### ISSUE TITLE
DMGs are corrupted

### ISSUE THREAD

**Issue by StephanMa** [SoftFever/OrcaSlicer#274]
**Describe the bug**
On opening the DMGs (arm64) , MacOs says DMG is corrupted and couldn't be opened.
Tested with v1.4.3 and v1.4.4

**To Reproduce**
1. Download DMG (arm64) and unzip it
2. Click on BambuStudio-SoftFever
3. See error

Down
**Expected behavior**
Start Programm

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOs Ventura 13.1
 - Mac mini M1

**Comment by erebus04** [comment]
Have you read the note on the Main page about this issue and the articel that are linked? https://www.howtogeek.com/803598/app-is-damaged-and-cant-be-opened/
