### ISSUE TITLE
Blob on first move after purge tower

### ISSUE THREAD

**Issue by Durahl** [SoftFever/OrcaSlicer#2740]
### OrcaSlicer Version

1.7.0-beta

### OS version

Win11

### Printer

Voron 2.4 with ERCF running HappyHare Software

### How to reproduce

After finishing the Purge Tower, the very first Extrusion with the new Material in the actual Model seems to extrude _way_ too much material resulting in an unsightly blob about ⅓ to ½ the volume of grain of rice - Not enough to cause an issue but still kinda meh?

Screenshot of one example where it happens in the attached Project File:
![IMG](https://i.imgur.com/GotBau2.png)
⬆️ If I understand the above screenshot properly then at line `1734` the Extruder is being instructed to extrude 2.3mm of Filament after only having retracted -0.3mm in line `1727` while still on the Purge Tower?
![IMG](https://i.imgur.com/h8l7566.png)

What setting is responsible for that Over Extrusion after the Extruder moved from the Purge Tower to the Model? 🤔🤨😑

### Actual results

Blob

### Expected results

No Blob

### Project file & Debug log uploads

[WMF Vorratsbehaelter v2.zip](https://github.com/SoftFever/OrcaSlicer/files/13355036/WMF.Vorratsbehaelter.v2.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by devildog81** [comment]
I am also experiencing this issue after a filament change. The extruder purges into the purge tower after a filament changeand causes a blob, which in turn causes a collision with the nozzle and a failed print.
