### ISSUE TITLE
"Raft" is not in the correct menu

### ISSUE THREAD

**Issue by DVSVIDEO** [SoftFever/OrcaSlicer#2744]
"Raft" is not in the correct menu. "Raft" in other slicers is correctly in the "Bed adhesion" menu.
This is where it belongs, according to its role.

Currently located under the "Support" section.

![Raft_1](https://github.com/SoftFever/OrcaSlicer/assets/96373457/c2b40a13-4f62-4b50-9d1c-5d9bffa8d6f9)
**Describe the solution you'd like**
It should be moved to the "Bed adhesion" section under the "others" tab.
Instead of "Brim type", "Adhesion type" would be more appropriate and the "Raft" menu item should be placed in the drop down menu.
Raft invalidates Brim and vice versa.
When Brim is selected it should be possible to select the Brim type in another drop down menu, for Raft it should remain faded.

![Brim](https://github.com/SoftFever/OrcaSlicer/assets/96373457/ef10416c-78cb-4448-b16c-cb37faf928a8)
![Raft_2](https://github.com/SoftFever/OrcaSlicer/assets/96373457/1311df17-a368-4ab8-9fc9-01fd4532fce4)

**Comment by DVSVIDEO** [comment]
![Raft_cura](https://github.com/SoftFever/OrcaSlicer/assets/96373457/f7da97c9-c2be-422d-a01d-a405f6bd8dd3)

**Comment by Eldenroot** [comment]
@igiannakas maybe another pr

**Comment by Fmstrat** [comment]
@Eldenroot IMO, this should be reopened. Skirt and Brim are under `Others`, Raft should be there, too.
