### ISSUE TITLE
"Bottom interface spacing" option has no effect/"Top interface spacing" changes bottom spacing

### ISSUE THREAD

**Issue by trankillity** [SoftFever/OrcaSlicer#2745]
### OrcaSlicer Version

1.8.0-rc2

### OS version

Windows 11

### Printer

Generic Klipper (Ender 3 S1 Pro w/ Sonic Pad)

### How to reproduce

1. Load a [support interface test](https://www.printables.com/model/198420-support-test) model.
2. Enable supports/support interface
3. Set different values for `Top interface spacing` and `Bottom interface spacing`
4. Slice model

### Actual results

Both top and bottom interface spacing are the same (mirroring the `Top interface spacing` value). `Top interface spacing` affecting both top and bottom can be verified by changing only the `Top interface spacing` and re-slicing.

![Sliced Preview](https://github.com/SoftFever/OrcaSlicer/assets/53357041/970afe65-cf98-40fe-96ed-7036af6c09df)
![Settings](https://github.com/SoftFever/OrcaSlicer/assets/53357041/2f65c0d7-9a1f-4246-94a1-bdefd16bef63)

### Expected results

1. `Bottom interface spacing` should change the bottom interface spacing. It currently has no discernible effect on slicing.
2. `Top interface spacing` shouldn't change the bottom interface spacing.

### Project file & Debug log uploads

No project or log files.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Noisyfox** [comment]
Does this only happen to certain support types/styles?

**Comment by trankillity** [comment]
I just checked, it happens in Normal Auto/Manual. Tried all different patterns and bottom layer counts too. Still the same across all of them.

**Comment by Noisyfox** [comment]
Right so it doesn't affect tree supports?

**Comment by trankillity** [comment]
I've never used tree supports. It looks like tree supports completely ignore any "Bottom" settings anyway because there's no interface, and no spacing on the bottom when using Tree supports where the support starts on the model.
![image](https://github.com/SoftFever/OrcaSlicer/assets/53357041/e7b295ed-8433-40bc-8b9d-7352c353f802)

**Comment by SoftFever** [comment]
Hmm, the bottom interface spacing is not supported by normal/organic support currently.

**Comment by trankillity** [comment]
It may be stale, but it's still a bug :(

**Comment by AuT-PsycHo** [comment]
Hello I have the same problem (2.0.0) found this and now commenting so maybe it will come back

**Comment by gaminglaboratory** [comment]
I have the same problem with Orcaslicer (2.0.0)

**Comment by Stormwing01** [comment]
Tree supports completely ignore bottom interfaces and spacing. basically: Tree supports print directly on your model without any bottom spacing, fusing the supports to the model permanently.

**Comment by crookz** [comment]
same situation here, i need the tree supports to have interfaces with the model, currently its impossible
![Screenshot 2024-10-14 114933](https://github.com/user-attachments/assets/0806076d-cd32-4bd4-8b8e-14c25cec65cc)

**Comment by sssoaring** [comment]
Recommenting - 2.2.0-beta2 still has this error. Tried with Normal Snug supports.
