### ISSUE TITLE
Steam OS(Arch Linux) support

### ISSUE THREAD

**Issue by hogum** [SoftFever/OrcaSlicer#2747]
Hopefully support for steam os will be added so we can do slicing on the steam deck :)

**Comment by hogum** [comment]
> You can already install it from aur https://aur.archlinux.org/packages/orca-slicer

Thank you for your reply. However, Steam OS is not a complete Arch Linux, so its support for aur is not friendly. Hopefully there is a flatpak or AppImage that can support it.

**Comment by Rucadi** [comment]
There is an AppImage, but at least I get shared library errors, seems like not everything is packaged.

**Comment by m0d3rnX** [comment]
AppImage is a worthless format, please provide a Flatpak to make sure it runs on every distro.

**Comment by watzon** [comment]
Bambu Studio finally has an official Flatpak available, might be worth seeing how easy it would be to port their Flatpak to Orca.

**Comment by arpia49** [comment]
My understanding is flatpak could be available _soon_ as https://github.com/SoftFever/OrcaSlicer/issues/3949 In the meantime I use Bambu Studio.
