### ISSUE TITLE
Discord invite invalid

### ISSUE THREAD

**Issue by itsmichaelk** [SoftFever/OrcaSlicer#2749]
Hey there,

the link to the Discord community is invalid again.

![Bildschirmfoto 2023-11-15 um 15 12 30](https://github.com/SoftFever/OrcaSlicer/assets/51818807/140e623b-921a-48ae-bb10-c185c3c86c7e)

Would really love to join the community!

Thanks in advance!

**Comment by Noisyfox** [comment]
Use this for now https://discord.gg/SxyYkk5svz

**Comment by SoftFever** [comment]
Thank you.
Just check, are you referring the one in this Discussion thread? https://github.com/SoftFever/OrcaSlicer/discussions/1692

**Comment by discip** [comment]
@itsmichaelk
As this seems to be solved, please don't forget to close. 😊
