### ISSUE TITLE
Snapmaker J1 no longer shows up in the list of printers though I previously configured it with the 1.8 beta 2

### ISSUE THREAD

**Issue by rodneyflowers** [SoftFever/OrcaSlicer#2750]
### OrcaSlicer Version

1.8.0-rc2

### OS version

Windows 11

### Additional system information

![SnapmakerJ1MissingInList](https://github.com/SoftFever/OrcaSlicer/assets/7647653/850ba822-f3ed-4464-98bd-dcc6b6f10874)

### Printer

Unable to select the Snapmaker J1

### How to reproduce

Add the Snapmaker J1  0.4mm profile in the printers dialog and it is not available as a selection

### Actual results

Printer is not shown as a selection

### Expected results

In the 1.8 Beta 2 I was able to select the printer and generate working gcode for the printer.

### Project file & Debug log uploads

none

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by SoftFever** [comment]
Thanks for reporting. It should have been fixed.
