### ISSUE TITLE
PLEASE ADD THESE!!!!

### ISSUE THREAD

**Issue by MikeOxlong83** [SoftFever/OrcaSlicer#2763]
It would be FANTASTIC if you guys and gals could add to the Preferences menu the options to:

1) enable/disable "automatically drop model to plate"

and

2) enable/disable the stupid annoying "do you want to add these as multiple parts to one model" dialog when opening multiple files at once

Thanks In Advance!

**Comment by OXERY** [comment]
You are using a software that people create in their very much deserved spare time. Don't you think, a bit of respect for the developer(s) would be appropriate? So why don't you at least edit the title of your issue to something meaningful.
