### ISSUE TITLE
"Arc fitting" making error artefacts in gcode

### ISSUE THREAD

**Issue by surikatec** [SoftFever/OrcaSlicer#2773]
### OrcaSlicer Version

1.8.0

### OS version

Windows 11

### Additional system information

Ryzen 5 5700X
16GB RAM
1080Ti

### Printer

Custom / VzBot / Whatever

### How to reproduce

With enabled "Arc_fitting" + "Z-offset" (in printer config) makes randomly errors in G-code.
ONLY enabled "Arc_fitting" it's without problem.
ONLY enabled "Z-offset" it's without problem.

![Snímek obrazovky 2023-11-17 182051](https://github.com/SoftFever/OrcaSlicer/assets/64527075/940bb24e-bcf4-483d-a072-17da0d4b4425)
![Snímek obrazovky 2023-11-17 183331](https://github.com/SoftFever/OrcaSlicer/assets/64527075/ca6a7540-e551-40cf-b0bb-eff581feea9e)
![Snímek obrazovky 2023-11-17 183359](https://github.com/SoftFever/OrcaSlicer/assets/64527075/eb22b0b4-b6dc-46bb-8d16-7fb13554c004)
![Snímek obrazovky 2023-11-17 183520](https://github.com/SoftFever/OrcaSlicer/assets/64527075/2f518f20-c2f7-4075-a906-9dd1853d14f1)

### Actual results

Turn off "Arc_fitting" or "Z-offset".

### Expected results

Repair it.

### Project file & Debug log uploads

...

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by surikatec** [comment]
Tried reinstall Orca, tried portable version. Still same error.

**Comment by SoftFever** [comment]
can you attach the project?

**Comment by surikatec** [comment]
> can you attach the project?

You mean .3mf file?

**Comment by discip** [comment]
> You mean .3mf file?

Yes he does. 😊
