### ISSUE TITLE
[Feature Request] Multimaterial toolchange temperature and toolchange string reduction (Skinnydip) from SuperSlicer

### ISSUE THREAD

**Issue by soul1988** [SoftFever/OrcaSlicer#2775]
Hello, it would be fantastic to have these functions from Superslicer ported to Orcaslicer, as they are very useful for achieving good filament tips, especially with PLA.

**Comment by SoftFever** [comment]
Is that the same thing the ramming stuff in PrusaSlicer?
If so, it's already included. 
If not, can you explain a bit more about the feature?
![image](https://github.com/SoftFever/OrcaSlicer/assets/103989404/c96dee2a-6b14-4a0e-a12e-6fcf0f3683d7)

**Comment by foxmckraut** [comment]
he is talking about the temp.

f.e. print with 220°C and toolchange with 190°C cause makes less strings.
