### ISSUE TITLE
Black build plate

### ISSUE THREAD

**Issue by lin-ycv** [SoftFever/OrcaSlicer#2782]
### OrcaSlicer Version

1.8.0

### OS version

Windows 11

### Printer

Ender 3 s1 pro

### How to reproduce

On a HP omen laptop, the build plate doesn't display properly for ender 3 s1 pro.
It shows up as a black sheet instead of the build plate graphics.
Other printer options display the build plate just fine. 

### Actual results

![20231117_111918](https://github.com/SoftFever/OrcaSlicer/assets/60565737/c8e5c254-f49d-4178-8569-e6aa6240d319)

### Expected results

For the build plate to display properly. 

### Project file & Debug log uploads

Not a project or crash.
Tried both portable and installed version.
Only happens on this omen laptop. 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Noisyfox** [comment]
Is your laptop equipped with an AMD gpu?

**Comment by lin-ycv** [comment]
It's a Ryzen CPU with Nvidia GPU.

Is there incompatibilities with AMD GPU? On my desktop it's AMD iGPU, it displays fine.

**Comment by Noisyfox** [comment]
Do you mind giving this build a try and see if it helps? https://github.com/SoftFever/OrcaSlicer/actions/runs/6911265809

**Comment by lin-ycv** [comment]
yes, this build has solved the issue.

**Comment by Noisyfox** [comment]
Good to know that, thanks!

**Comment by adolfotregosa** [comment]
__EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/50_mesa.json ./OrcaSlicer_Linux_Ubuntu2404_V2.2.0-dev_c6d7155092af9b224253666b778b5e75.AppImage 

Does this help ???
