### ISSUE TITLE
PA Pattern Test: Retracts in Solid Infill Area

### ISSUE THREAD

**Issue by CCS86** [SoftFever/OrcaSlicer#2792]
### OrcaSlicer Version

1.8.0

### OS version

Win 10 x64

### Printer

X1C

### How to reproduce

Generate a PA pattern calibration.

### Actual results

Retract moves are generated for every tiny travel in the the solid infill area:

![image](https://github.com/SoftFever/OrcaSlicer/assets/12439543/c841f309-294e-471c-abc2-5756c98960d7)

### Expected results

I expect unretracted travel here because they are shorter than the Travel Distance Threshold

### Project file & Debug log uploads

...

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by CCS86** [comment]
Bump

**Comment by CCS86** [comment]
This seems like a really easy fix @SoftFever

**Comment by SoftFever** [comment]
Have you tried disable this option?

![image](https://github.com/SoftFever/OrcaSlicer/assets/103989404/8af31418-aeb6-461e-8fd1-f98faf27bf48)
