### ISSUE TITLE
First layer travel acceleration

### ISSUE THREAD

**Issue by shyblower** [SoftFever/OrcaSlicer#2797]
**Is your feature request related to a problem? Please describe.**
To print very soft TPU (60A, 70A) successfully (even on a Bambu Lab printer) you usually need very low acceleration values (around 150mm/s²) to keep the extruder from clogging but still be able maintain a decent maximum volumetric speed (around 3-4mm³/s). These low acceleration values should only apply to print moves and not for travel as it would lead to excessive stringing. This works on all layers but the bottom one where there is only one first layer acceleration setting which overrules travel acceleration.

**Which printers will be beneficial to this feature**
I suppose every printer

**Describe the solution you'd like**
I'd like to have a separate first layer travel acceleration setting to keep print acceleration for the first layer low but be able to configure first layer travel acceleration independently

**Describe alternatives you've considered**
None that could achieve the intended goal.

**Comment by DVSVIDEO** [comment]
Take a closer look:
![Brim](https://github.com/SoftFever/OrcaSlicer/assets/96373457/653f9eeb-badf-4bd4-936c-8f6ab2c9048d)

Then delete this error mark...

**Comment by shyblower** [comment]
I was not talking about travel speed but about travel acceleration!

**Comment by DVSVIDEO** [comment]
Yes! I am wrong, sorry...

**Comment by Z18Aplha** [comment]
I would be interested in this as well!

**Comment by vgdh** [comment]
Absolutely necessary!

**Comment by MxBrnr** [comment]
Implemented in #11674.
