### ISSUE TITLE
Where is Flow Ratio?

### ISSUE THREAD

**Issue by Dipo21** [SoftFever/OrcaSlicer#2798]
### OrcaSlicer Version

1.8.0

### OS version

Win 11

### Printer

Flsun V400

### How to reproduce

1. Go to Quality
2. Advanced
3. Flow Ratio disappear
4. if you search for "flow ratio" and click on the result it doesn't appear.
5. If you go to the individual object settings, it appears.

### Actual results

![image](https://github.com/SoftFever/OrcaSlicer/assets/151442979/9a723e72-5078-4466-ad4e-91a2537cad41)
![image](https://github.com/SoftFever/OrcaSlicer/assets/151442979/93b4b452-d808-4b63-a6a8-9c39d87d4259)

### Expected results

Previously I used 1.7.0 and with this latest version I cannot modify the imported flow ratio.
I have to go into each object and change the value

### Project file & Debug log uploads

[test_Flow-ratio.zip](https://github.com/SoftFever/OrcaSlicer/files/13403163/test_Flow-ratio.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by killerline10168** [comment]
Flow ratio is under Filament settings in 1.8.0. 

Kindly close this ticket once you find it :)

**Comment by Dipo21** [comment]
Also in 1.7.0 it is in the Filament setting.
The question is: how do I change that value by importing the old configuration files?
It's possible?

Thanks for your help

**Comment by Dipo21** [comment]
I changed the value to 1 on 1.7.0 and then exported it again for 1.8.0.
Thank you!

**Comment by DVSVIDEO** [comment]
This appeared sometime recently, then disappeared in 1.8.
When it appeared I didn't understand why I needed it, as I calibrated the flow for each material and adjusted it to the material property.
You could override separately for the bottom layer and the top layer to make it stick better and the top layer even smoother.
But what was this flow adjustment for?
I don't mind it disappearing, it was just a distraction.
