### ISSUE TITLE
Calibration: PA Lines Forced Low Accel

### ISSUE THREAD

**Issue by CCS86** [SoftFever/OrcaSlicer#2801]
### OrcaSlicer Version

1.8.0

### OS version

Win 10 x64

### Printer

X1C

### How to reproduce

When using the "lines" PA calibration, there is a forced acceleration value of 500 mm/s2 in the gcode. This makes the test pretty useless.

### Actual results

![image](https://github.com/SoftFever/OrcaSlicer/assets/12439543/51565b53-e9e3-49be-b3e9-e2d02392bddc)

### Expected results

The last given M204 should match the "first layer" acceleration value defined in the slicer.

### Project file & Debug log uploads

...

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by CCS86** [comment]
Bump

**Comment by capsel22** [comment]
I too would like to bump

**Comment by CCS86** [comment]
@SoftFever

**Comment by SoftFever** [comment]
It just respects your print setting.
500 is for first layer, from second layer it uses 5000 accel
![image](https://github.com/SoftFever/OrcaSlicer/assets/103989404/747b8583-d931-4c7c-a74d-affd106bb5f0)

**Comment by CCS86** [comment]
> It just respects your print setting. 500 is for first layer, from second layer it uses 5000 accel 


The "lines" PA test is only one layer high. 

Previously, with first layer and wall accels set to 5000, it was still asserting an M204 S500

I just tested in the new 2.1.0 beta and it appears to have been resolved at some point.
