### ISSUE TITLE
WORKAROUND IN COMMENTS | Retract not shown in Preview, possibly no Retract happening at all

### ISSUE THREAD

**Issue by Kraligor** [SoftFever/OrcaSlicer#2805]
### OrcaSlicer Version

1.8.0-beta2 and 1.8.0-release

### OS version

Windows 10

### Printer

Anycubic Vyper

### How to reproduce

1. Enable retraction
2. Slice object
3. In Preview, select 'Line Type' and hide all line types except 'Retract' and 'Unretract'

### Actual results

1. Only Unretractions are shown, there is only one single Retraction visible, and it is at the purge line (see screenshot).
2. The printed model has lots of stringing, making me think there might not be any retraction happening at all.

![actual_orca-slicer_P3TumXf9rL](https://github.com/SoftFever/OrcaSlicer/assets/1042116/83e6b35c-f622-4529-aaa4-dda5bd6ca32d)

### Expected results

For each Unretraction there should be a corresponding Retraction visible.

### Project file & Debug log uploads

[PowerMod_v3_testpiece.zip](https://github.com/SoftFever/OrcaSlicer/files/13404804/PowerMod_v3_testpiece.zip)
[gcode.zip](https://github.com/SoftFever/OrcaSlicer/files/13404810/gcode.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by SoftFever** [comment]
Hi,
Thanks for report the issue.

There is a bug when `Retract amount before wipe` is set to 0.
This will be fixed soon. 
As a workaround for now, we can avoid setting it to 0.
![Screenshot 2023-11-20 at 12 30 03 PM](https://github.com/SoftFever/OrcaSlicer/assets/103989404/a1b9c65c-48b8-43d6-9cee-a26e383d116a)

**Comment by killerline10168** [comment]
I reported the same issue a while back but with no response. I will refer to this ticket there.

**Comment by Kraligor** [comment]
Workaround: Set `Retract amount before wipe` to > 0
Will be fixed soon per @SoftFever
