### ISSUE TITLE
First Layer Infill Overlap Wrong

### ISSUE THREAD

**Issue by CCS86** [SoftFever/OrcaSlicer#2810]
### OrcaSlicer Version

1.8.0

### OS version

Win 10 x64

### Printer

X1C

### How to reproduce

Open attached project and look at the first layer. 

### Actual results

You will see that despite having a uniform line width between perimeters and infill, the stepover for each path type is different. 

The perimeter stepover is correct, but the infill stepover is too small, causing over-extrusion.

These two green lines are identical length. One of them covers 12 perimeters, the other covers 14 infill lines. This results in about 16% over-extrusion:

![image](https://github.com/SoftFever/OrcaSlicer/assets/12439543/4572be28-f7ae-4227-bdbd-d5791b7359ba)

### Expected results

I expect the stepovers to be equal for equal line widths.

### Project file & Debug log uploads

[Infill overlap.zip](https://github.com/SoftFever/OrcaSlicer/files/13406175/Infill.overlap.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by killerline10168** [comment]
Interesting. The file you are showing in your pictures looks like a great example. Could you perhaps print it out, to see if there is a noticeable difference?

**Comment by CCS86** [comment]
I noticed the issue through printing, where the first layer perimeters were
perfect and the the infill was badly over extruded. Subsequent layers
improved.

Then I swapped out my print model for a primitive cube to see if the
behavior stayed the same, and uploaded it as the example.

**Comment by CCS86** [comment]
More info: it only seems to be the case when "bottom shell layers" is set to zero.

**Comment by igiannakas** [comment]
This appears as resolved in the latest release:

![image](https://github.com/SoftFever/OrcaSlicer/assets/59056762/f0fb854a-8bed-4056-ab2c-4b08b80aed7a)

![image](https://github.com/SoftFever/OrcaSlicer/assets/59056762/7a6edcdd-7497-4602-a4f2-add626909d78)

![image](https://github.com/SoftFever/OrcaSlicer/assets/59056762/108f0640-1b0e-450a-9e9f-6baef02cbe97)

![image](https://github.com/SoftFever/OrcaSlicer/assets/59056762/aa6300f6-c689-4a60-bf83-3dd49cd189a1)
