### ISSUE TITLE
Default/Gap infill is not @ Jerk = 1 during PA tower

### ISSUE THREAD

**Issue by psiberfunk** [SoftFever/OrcaSlicer#282]
**Describe the bug**
Somewhere in the last few builds the PA tower changed which jerk values are assigned.  It used to be that everything but travel was = 1 , but now only inner/outer walls are =1.  However, because the slicer, with default profile settings @ 0.2 mm layer height, creates a "gap infill" inner line instead of inner walls, the jerk gets = 9 at for that line.  This could lead to misleading PA towers because the inner gap fill "wall" can influence the visual appearance of the outer walls as a secondary contributor.

The slicer should have this PA tower setup so that ALL lines drawn are the same jerk for consistency to best tune PA.

Suggest making sure this gap infill gets drawn with Jerk =1 instead of Jerk =9

**Screenshots**
![image](https://user-images.githubusercontent.com/19777571/216772171-4b109d64-2151-4d86-b43a-e5018b6f61d0.png)
![image](https://user-images.githubusercontent.com/19777571/216772179-c9ea9e88-a4f8-4f06-a178-7e6be279da8b.png)

**Desktop (please complete the following information):**
Windows 1.4.4

**Comment by SoftFever** [comment]
The gap fills are printed at last hence won't affect the benchmark. 
For the sake of consistency, I will change that back to 1 in the next update
