### ISSUE TITLE
Slicing only produces a single bottom and top layer

### ISSUE THREAD

**Issue by e-dreyer** [SoftFever/OrcaSlicer#2822]
### OrcaSlicer Version

1.8.0

### OS version

Pop!_OS 22.04 LTS

### Additional system information

CPU: Intel Core it-7300HQ 2.50GHz
Graphics: Nvidia MX150
Memory: 16GB DDR4
FreeSpace: 500GB+

### Printer

Creality K1

### How to reproduce

Slice the provided file. Using 1.8.0 the correct number of top and bottom layers are not produced, however using 1.8.0-rc does produce the correct output.

### Actual results

Slicing the provided file only produces a single top and bottom layer, although 5 top and bottom layers are specified as well as a minimum shell thickness.

### Expected results

5 Top and bottom layers or at least a thickness of 0.8mm

### Project file & Debug log uploads

[v1_8_0.zip](https://github.com/SoftFever/OrcaSlicer/files/13425908/v1_8_0.zip)
[v1_8_0_rc.zip](https://github.com/SoftFever/OrcaSlicer/files/13425919/v1_8_0_rc.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by e-dreyer** [comment]
Slicing with 1.8.0-rc yields the correct results:
[construction_1_8_0_rc.zip](https://github.com/SoftFever/OrcaSlicer/files/13425888/construction_1_8_0_rc.zip)

**Comment by pacmac** [comment]
I think I have the same issue, I can see the infill showing through on the top layer, it looks like there's only one layer on the top surface despite the fact that it's set to the default 3 layers.

![IMG_7257](https://github.com/SoftFever/OrcaSlicer/assets/2349856/a612f82e-7ea9-4426-8bfc-2d997c83dbf7)
[ReolinkCompoundAngles v1.stl.zip](https://github.com/SoftFever/OrcaSlicer/files/13463372/ReolinkCompoundAngles.v1.stl.zip)

**Comment by e-dreyer** [comment]
> I think I have the same issue, but only the top layer, I can see the infill showing through on the top layer, it looks like there's only one layer on the top surface despite the fact that it's set to the default 3 layers.
> 
> ![IMG_7257](https://github.com/SoftFever/OrcaSlicer/assets/2349856/a612f82e-7ea9-4426-8bfc-2d997c83dbf7)
> [ReolinkCompoundAngles v1.stl.zip](https://github.com/SoftFever/OrcaSlicer/files/13463372/ReolinkCompoundAngles.v1.stl.zip)
> 

You should only be able to see a single layer in the "Line type" view. Have you tried with 1.8.0-rc to ensure it isn't the model? Also try to set a minimum shell thickness. Otherwise, we might have found a bug.

**Comment by pacmac** [comment]
Thanks, strange thing is the line type shows no top layer (red).
<img width="954" alt="Screenshot 2023-11-25 at 4 43 09 PM" src="https://github.com/SoftFever/OrcaSlicer/assets/2349856/f6568420-e631-42c2-9532-76a80d01a817">

**Comment by pacmac** [comment]
I just tried on V1.7, same problem, it does not appear to recognise the compound angled upper surface as the top surface.

**Comment by e-dreyer** [comment]
Yeah, it is showing a print time as less than a second. I had similar results, but earlier versions worked for me. So your situation might be the model. Will open it on my side so see what I get.

**Comment by pacmac** [comment]
Also tried PruSlicer and same issue, then tried Cura and Cura does recognise the top layer correctly, so I guess this is inherited from the original Slic3R.

**Comment by pacmac** [comment]
It not inactive, it is just that nobody has responded to it :-)
