### ISSUE TITLE
Impossible move the Prime Tower closer to bed borders (inside your printable area)

### ISSUE THREAD

**Issue by cardom** [SoftFever/OrcaSlicer#2824]
### OrcaSlicer Version

1.8.0

### OS version

macOS 13.6

### Additional system information

Chip: Apple M2 Pro
RAM: 32 GB 

### Printer

Generic Klipper Printer / Prusa MK4 / Prusa MK3S

### How to reproduce

1. Go on Process (Advanced enabled) > Others
2. Enable Prime Tower
4. On Prepare tab, try to move Prime Tower closer to the border of your print area
5. This behaviour does not change if you set Brim width (under Prime tower) to 0 or to a bigger value than the defaul (3mm)

### Actual results

The Prime Tower have an hard limit to move and stop 15mm away to any border of the print area in the bed.

### Expected results

Every object on the bed plate should move freely inside the print area defined.
The Prepare tab does not take in to account the brim width of the Prime tower, but this doesn't should block the movement of the Prime tower on the bed. For example, if I would print the Prime tower with 0mm Brim width, I should be able to move the Prime tower closer to the printable area (let's say with the angle of it at the coordinate of 0,0, but actually it is impossible because you are forced to start from a 15mm of distance from any of the border.
This cause to have a smaller printable areas than Prusa Slicer with the same print file, because you're limited with the positioning of your Prime tower, that in some cases can make impossible the print, like as example this printable file:
https://www.printables.com/model/42616-spider-man-wall-art-single-and-mmu/files

### Project file & Debug log uploads

[spiderman-wall-art.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/13426372/spiderman-wall-art.3mf.zip)
![Screenshot 2023-11-21 at 13 46 11](https://github.com/SoftFever/OrcaSlicer/assets/10565355/7dc754e8-6e56-4267-8475-758637d8b1b8)
![Screenshot 2023-11-21 at 13 46 30](https://github.com/SoftFever/OrcaSlicer/assets/10565355/7ac7ce18-97b3-4d6c-88b3-bf0c2ab01cfb)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by CristianGTR97** [comment]
I find this frustrating as well

**Comment by vgdh** [comment]
Agree! I also want to place it at the edge of the bed.

**Comment by vgdh** [comment]
I can't stress enough how this is annoying !
Why i can't put the tower at the edge of the bed?
![Снимок](https://github.com/SoftFever/OrcaSlicer/assets/15322782/765d0148-f97b-472d-b41c-dad02d46b74e)
