### ISSUE TITLE
Raft problem when elephant foot compensation is activated

### ISSUE THREAD

**Issue by jiiimi** [SoftFever/OrcaSlicer#2826]
**Is your feature request related to a problem? Please describe.**
When elephant foot compensation is enabled and we set a distance of zero between the border and the object, the border does not stick to the object.
The border does not take into consideration the compensation of the elephant's foot.

**Which printers will be beneficial to this feature**
All

**Describe the solution you'd like**
That the distance between the object and the border takes into consideration the value indicated regarding the elephant foot compensation is activated

**Comment by jiiimi** [comment]
![Sans titre 2](https://github.com/SoftFever/OrcaSlicer/assets/92683359/7d594c31-aa98-4f1e-89b2-de84a47c63d3)

**Comment by Martorias** [comment]
That's not a raft but the brim, but yeah, it would be nice if the brim/mouse ears etc would follow the elephant foot compensation

**Comment by niguang1** [comment]
I am encountering the same problem.
For those who want to improve the first layer bonding problem through this method, this is a serious problem.

**Comment by center-777** [comment]
Up, please 🙂
