### ISSUE TITLE
Infill / Wall Overlap Not Applied to Bottom Layers w/ Monotonic Line Pattern

### ISSUE THREAD

**Issue by CCS86** [SoftFever/OrcaSlicer#2827]
### OrcaSlicer Version

1.8.0

### OS version

Win 10 x64

### Printer

X1C

### How to reproduce

Observe the bottom layer of a print with some number of bottom shell layers.

Set "infill / wall overlap" to a very large value, like 100%

Compare the path between "monotonic" and "monotonic line"

### Actual results

Infill / wall overlap snaps to a hardcoded value when using monotonic line:

![image](https://github.com/SoftFever/OrcaSlicer/assets/12439543/0b09745e-3272-469d-af4c-02ecd53b358d)

![image](https://github.com/SoftFever/OrcaSlicer/assets/12439543/2e46e141-e1aa-4d94-b093-621d23b2220c)

### Expected results

Infill / wall overlap should be applied regardless of pattern type.

### Project file & Debug log uploads

...

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by ShryuKt** [comment]
Hello @CCS86, it's not a bug it's a feature from BambuStudio
[BamuLab Wiki](https://wiki.bambulab.com/en/software/bambu-studio/fill-patterns#infill-of-the-top-surface-and-bottom-surface)

> compare to Monotonic, Monotonic linear infill has no overlap with the perimeter, some seam may appear on the surface, but will not has redundant material in connected areas. 

Some other slicers like Superslicer do it differently, but here this is by design.

**Comment by CCS86** [comment]
I see that, but don't think it is a good "feature".

The zero infill/wall overlap is only true on top on bottom surfaces. Monotonic Line uses the overlap setting for all other layers. 

So, why would you not want to tune your print for ideal extrusion on all layers? Top / Bottom shells aren't inherently different than any other layer, which would require them to have a different amount of overlap.

**Comment by FuryriderX** [comment]
I am noticing this on top layers as well - it would be nice if the overlap percentage was able to be applied.  Monotonic line can have one of the best surface qualities on top layers but can leave little pinholes if the overlap percentage is too low.
