### ISSUE TITLE
Filament library - not working

### ISSUE THREAD

**Issue by Eldenroot** [SoftFever/OrcaSlicer#2830]
### OrcaSlicer Version

1.8.0final

### OS version

Win11 64bit

### Additional system information

---

### Printer

Bambu Lab A1 mini

### How to reproduce

Go to filament settings (presents), uncheck (deselect) the filaments brands which you do not wanna.  

### Actual results

![image](https://github.com/SoftFever/OrcaSlicer/assets/778890/f7a5c782-3997-4a2b-9cf5-60cefd3395b3)

Polylite, eSun, Polyterra are still displayed, even when you dint want to...

### Expected results

Unchecked filaments should not be displayed.

### Project file & Debug log uploads

---

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Eldenroot** [comment]
@SoftFever - this one still happens

Even when you uncheck "Polyterra" and "eSun" - they are still displayed in the menu for filament selection:

![image](https://github.com/SoftFever/OrcaSlicer/assets/778890/bb917f12-3dba-4791-9a3e-238e165bc5a1)

![image](https://github.com/SoftFever/OrcaSlicer/assets/778890/8d211e97-f277-4f9b-8f1f-b932b790a2c8)

**Comment by SoftFever** [comment]
> @SoftFever - this one still happens
> 
> Even when you uncheck "Polyterra" and "eSun" - they are still displayed in the menu for filament selection:
> 
> ![image](https://private-user-images.githubusercontent.com/778890/291906585-bb917f12-3dba-4791-9a3e-238e165bc5a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwODQ5NTgsIm5iZiI6MTcwMzA4NDY1OCwicGF0aCI6Ii83Nzg4OTAvMjkxOTA2NTg1LWJiOTE3ZjEyLTNkYmEtNDc5MS05YTNlLTIzOGUxNjViYzVhMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMFQxNTA0MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZTUxYTIzZDVjZmRiMzU2YzU3OTc2ZjQ3NzJkYTg2ZDQ0ZDQxOGFjNDNkMzlmMzVmMjAwMzY3ODljOTkzYjU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fCs4M59lyhBLR10u0MjgIhOArqptVrJgxEEirYMGvMM)
> 
> ![image](https://private-user-images.githubusercontent.com/778890/291906730-8d211e97-f277-4f9b-8f1f-b932b790a2c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwODQ5NTgsIm5iZiI6MTcwMzA4NDY1OCwicGF0aCI6Ii83Nzg4OTAvMjkxOTA2NzMwLThkMjExZTk3LWYyNzctNGY5Yi04ZjFmLWI5MzJiNzkwYTJjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMFQxNTA0MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNDJmYWE0YjY2ZTQ3ZDc5MWUxNTJlYjViMjcyNWJiNzlhZTBhNGU0OGY2OWZiZTc1Y2EyMTQ0ZjQyNGI3YjcwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.O6De-1Fc-TJJ4-zZCkOco4_vBT0ruikJHj9E_dSIkP8)
Can you try the latest dev build?
I can't repro it with 1.9-dev
![Screenshot 2023-12-20 at 11 20 57 PM](https://github.com/SoftFever/OrcaSlicer/assets/103989404/62859fca-d001-4679-a0ab-9bad31aa468e)

**Comment by kylek29** [comment]
@Eldenroot Out of curiosity (for testing), do you have BambuLab cloud sync turned on or off?

**Comment by Eldenroot** [comment]
@kylek29 @SoftFever 

I can still reproduce on latest Github nightly build (21122023). 

These filaments are unchecked, but they are still in the list. It does NOT happens with Bambu Studio slicer. 

![image](https://github.com/SoftFever/OrcaSlicer/assets/778890/05550db2-76b2-4ec1-947a-ba617a29aac1)

I have disabled synchronize user settings in advance settings.

How to fix this, should I delete some folder with settings in my PC?
