### ISSUE TITLE
Add Internal edge to internal surface areas

### ISSUE THREAD

**Issue by TheAtomicSoul** [SoftFever/OrcaSlicer#2834]
**Is your feature request related to a problem? Please describe.**
I've noticed a lot of noise while printing and realized it's because the internal edge of surfaces is "floating" and has nothing to attach to. 
In comparison, there are edges for this in Cura. 

**Which printers will be beneficial to this feature**
all

**Describe the solution you'd like**
Add at least one internal edge for flat areas inside the model. 

![image](https://github.com/SoftFever/OrcaSlicer/assets/136633194/a5333f39-b6b3-4bf2-aaf2-03855aad57da)

![image](https://github.com/SoftFever/OrcaSlicer/assets/136633194/ef815708-aa01-4e79-8098-e5c7b8276266)

What I get in Cura: 
![image](https://github.com/SoftFever/OrcaSlicer/assets/136633194/eafb6754-d479-4f63-bfdd-df4718a248c0)

**Comment by TheAtomicSoul** [comment]
As visible in Cura, the bottom right area where the horizontal infill buts against an edge inside the model. 
Orca, meanwhile, leaves these edges floating in the air, with nothing to help them hold in place.

**Comment by SoftFever** [comment]
What version of Orca are you using?
This has been greatly improved in Orca 1.8

**Comment by discip** [comment]
@TheAtomicSoul
Have you already tested what was proposed to you?
Have you tried the latest version of OrcaSlicer?

Please remember closing your issue if it is solved. 😊

thanks

**Comment by TheAtomicSoul** [comment]
> What version of Orca are you using? This has been greatly improved in Orca 1.8
Unless there's an option I don't know of to add it, It still lacks any internal edge to butt against, which can increase edges curling.

1.8.0 also makes random sections into concentric surface patterns. 

![image](https://github.com/SoftFever/OrcaSlicer/assets/136633194/d942aedf-c9c0-4618-87d7-4e986056cb17)

![image](https://github.com/SoftFever/OrcaSlicer/assets/136633194/8c105979-1081-4222-be6b-5182d2e4dea1)

**Comment by TheAtomicSoul** [comment]
> @TheAtomicSoul Have you already tested what was proposed to you? Have you tried the latest version of OrcaSlicer?

Nothing has been proposed though? And this is in 1.8.0 RC.

**Comment by henrivdr** [comment]
@TheAtomicSoul was this fixed?

**Comment by TheAtomicSoul** [comment]
> @TheAtomicSoul was this fixed?

Nope. 
![image](https://github.com/user-attachments/assets/e56dda7b-0bdf-4b8e-a8a6-1942d50263fe)

**Comment by TheAtomicSoul** [comment]
To clarify: the weird loops that I was getting was fixed, but the original request for an internal edge loop to support the internal infill wasn't.
