### ISSUE TITLE
Snapmaker J1 - Multi extruder / filament issues with priming tower - show stopper on J1 multi filament

### ISSUE THREAD

**Issue by rodneyflowers** [SoftFever/OrcaSlicer#2837]
### OrcaSlicer Version

1.8.0

### OS version

Windows 11

### Additional system information

none

### Printer

Snapmaker J1

### How to reproduce

Add a 2nd filament to a project
Slice a model and paint the 2nd color on the model.
Enable the prime tower
Start the print on the J1

### Actual results

The print starts once the 2 hotends and the bed reach temperature as expected
Each print head draws a purge line
The first color releases a large stream of filament into the air near the dock location for the print head.
The 1st color starts to print and creates the purge tower first layer, then skirt outline, then the support bases and then the actual model begins to print.

Issue --> When color 2 starts it moves to a position in the prime tower and then releases a large glob of filament so large the print head gets stuck in place and cannot move. 

I tried modifications in the gcode and in the UI but nothing seems to stop the large glob from forming.  Perhaps the stream of filament released by print head one is also happening on print head 2 but its not into the air but into the prime tower.

### Expected results

Color 2 would start and do its work on the prime tower and then do its part on the model without creating the glob of filament in the prime tower.

If I do not use a prime tower the print will happen but the detail is lost in a lot of places due to the filament not being prepped on start of the colors.

### Project file & Debug log uploads

none

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by NexGen-3D-Printing** [comment]
I have a similar issue, with a completely different setup, this isues shows up when you enable "Purge in prime tower" in the Multimaterial tab for the machine settings and if you alter the Prime tower width from the defualt, it will slow down the tool head movement to a snail pace but still extrude the full amount od filament into the purge tower, this results in a tool head that bairly moves but dumps a crap ton of filament onto the bed jamming everything up, I found returning that setting to the default corrects everything again, it seems some calculations are not done correctly if mess about with the prime tower.

This one using the default Prime tower width

![Correct](https://github.com/SoftFever/OrcaSlicer/assets/20825418/4c6184c5-7c76-459f-80c5-1c0c317d87bb)

This one is use a smaller one

![Incorrect](https://github.com/SoftFever/OrcaSlicer/assets/20825418/84fed7b7-fb1a-4593-830d-c4184a995d30)

There is still an issue with this feature as it still tries to ram filament into the bed cause my extruders to sing a nasty sound at the beginning of this purge sequence, if I disable the "Purge into prime tower" feature, then it failes to execute the cooling move
