### ISSUE TITLE
flow ratio global process

### ISSUE THREAD

**Issue by StephInoP** [SoftFever/OrcaSlicer#2841]
i think you have missed the flow ratio in the global process, usually it's there

i dont know if its a bug or you just forget

and there is one more shown in the pics attached
![400798534_10161097920511165_4052554245792228823_n](https://github.com/SoftFever/OrcaSlicer/assets/94558162/e7ad3467-2e0f-4a2e-9a4e-e66f503202a1)
![401485387_10161097920521165_101807207015136557_n](https://github.com/SoftFever/OrcaSlicer/assets/94558162/5ac295c7-cc72-414d-b7f5-649b81145b64)

**Comment by igiannakas** [comment]
it has been removed as in the global process flow ratio is not necessary. You can achieve the same by setting the filament flow ratio.

**Comment by StephInoP** [comment]
how about the flow ratio under process objects? 

my opinion, i think it's better to have ONLY ONE flow ratio which is located at the filament setting, to avoid confusion,
(in previous versions there were 3, one under global, one under objects, one under filament setting) now there are 2,

and can keep bridge flow ratio, bottom/top surface flow ratio as they are now

**Comment by igiannakas** [comment]
The object one is useful for things like calibrations. You set your filament to 1 then create 4 cubes with 1, 0.99, 0.98, 0.97 and find the best looking one.

**Comment by StephInoP** [comment]
let's say I pick 0.96, then I put the same number in the flow ratio (filament setting and object)?

sorry to disturb you with my curiosity

**Comment by igiannakas** [comment]
> let's say I pick 0.96, then I put the same number in the flow ratio (filament setting and object)?
> 
> sorry to disturb you with my curiosity

Then it will use 0.96*0.96 = 0.9216 as the effective rate.

**Comment by StephInoP** [comment]
> > let's say I pick 0.96, then I put the same number in the flow ratio (filament setting and object)?
> > sorry to disturb you with my curiosity
> 
> Then it will use 0.96*0.96 = 0.9216 as the effective rate.

aha i get it now, thank you very very much

**Comment by discip** [comment]
@StephInoP
Judging by your last response this seems to be solved.
If this is the case, please don't forget to close. 😊

thanks

**Comment by discip** [comment]
@StephInoP
Judging by your last response, this seems to be solved.
If this is the case, please don't forget to close. 😊

thanks
