### ISSUE TITLE
SimplyPrint Integration

### ISSUE THREAD

**Issue by ETS5** [SoftFever/OrcaSlicer#2852]
**Which printers will be beneficial to this feature**
All printers supported by Simplyprint

**Describe the solution you'd like**
I was wondering if their could be some collaboration from simplyprint and yall to see if there was a way to be able to integrate Ocraslicer into Simplyprint.

**Describe alternatives you've considered**
I can yes just slice and export the gcode and then upload to Simplyprint it would be awesome to just upload it directly to there.

**Comment by Ocraftyone** [comment]
Documentation regarding integrations: https://simplyprint.io/integrations/

**Comment by AlbertMN** [comment]
@ETS5 this is now live :) https://github.com/SoftFever/OrcaSlicer/pull/4525
