### ISSUE TITLE
Kingroon profiles not avaliable

### ISSUE THREAD

**Issue by toniz4** [SoftFever/OrcaSlicer#2853]
### OrcaSlicer Version

1.8.0

### OS version

NixOS 23.05 (Stoat)

### Printer

None

### How to reproduce

1 - Add/Remove printer
2 - Search for Kingroon printers

### Actual results

Kingroon printers are not avaliable

### Expected results

It appears that the kingroon profiles are in orca slicer:

https://github.com/SoftFever/OrcaSlicer/blob/main/resources/profiles/Kingroon.json

But for some reason they are not listed.

### Project file & Debug log uploads

Not applicable 

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by kinghat** [comment]
still an issue on 1.8.1. can we get these included in the linux builds in 1.9?
