### ISSUE TITLE
Weird behavior with bottom/top surface pattern in vase spiral mode

### ISSUE THREAD

**Issue by WizardPC** [SoftFever/OrcaSlicer#2856]
### OrcaSlicer Version

1.8.0

### OS version

Windows 11

### Printer

Sidewinder X2 running Klipper

### How to reproduce

Using "Spiral vase" mode, there isn't Top or Infill.
![image](https://github.com/SoftFever/OrcaSlicer/assets/11718892/c0b60cc2-dccd-4a34-866e-4ea0e178288b)

Using this configuration to demonstrate the issue
![image](https://github.com/SoftFever/OrcaSlicer/assets/11718892/d012ab86-f07c-44b7-8ed9-3e6b27190934)

### Actual results

Each pattern are applied over the 3 bottom layers
![image](https://github.com/SoftFever/OrcaSlicer/assets/11718892/04713e48-b4a9-47a2-aaed-d6f14cf15125)
![image](https://github.com/SoftFever/OrcaSlicer/assets/11718892/86c9aa48-db2a-43e3-a340-ceda020acbf3)
![image](https://github.com/SoftFever/OrcaSlicer/assets/11718892/23427574-4545-4eb2-bca4-c5352d5a65c5)

### Expected results

I was expecting to have 1~3 layers, the same "bottom surface pattern".
Or at least the 1 & 3,  if the layer between is considered like an infill.
But not the layer 3 to have the "top surface pattern" since "Top shell layers" is 0.

### Project file & Debug log uploads

[vase_mode_issue.zip](https://github.com/SoftFever/OrcaSlicer/files/13450084/vase_mode_issue.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by rsmanning** [comment]
I'm having an issue with it introducing flaws in the sidewall that don't show in the slicer and no errors in the slicer ether.  They are consistent and repeatable in the same simple lower section of this model and its just a a section that's pretty much a tube.
