### ISSUE TITLE
orcaslicer starts with empty setup window

### ISSUE THREAD

**Issue by didli** [SoftFever/OrcaSlicer#2860]
### OrcaSlicer Version

1.8.0

### OS version

Fedora release 38 (Thirty Eight)

### Additional system information

Kernel: 6.5.10-200.fc38.x86_64 arch: x86_64 / Desktop: Xfce v: 4.18.1 / Distro: Fedora release 38 (Thirty Eight)
Graphics : NVIDIA TU106 [GeForce RTX 2060 Rev. A] driver: nvidia v: 545.29.02

### Printer

Ender 3 v2 Neo

#### running the appimage directly from terminal : 
- some critical / warnings from theme / gtk window
`[2023-11-23 15:37:02.601964] [0x00007f605e93be80] [trace]   Initializing StaticPrintConfigs
(orca-slicer:1637404): Gtk-CRITICAL **: 15:37:05.551: gtk_window_resize: assertion 'width > 0' failed
(orca-slicer:1637404): GLib-GObject-CRITICAL **: 15:37:05.575: invalid cast from 'wxPizza' to 'GtkCellLayout'
(...)`
- then these errors as the windows are loaded :
`KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 1198x713: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 1198x713: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 1198x713: Permission denied
Failed to create EGL images for DMABufs with file descriptors -1, -1 and -1`

### Actual results

orcaslicer starts with a certificate issue : 
- - - 
![certissue](https://github.com/SoftFever/OrcaSlicer/assets/3301204/4a1db9cc-de04-417c-800e-05fb9e008c00)
- - - 
then, global window and setup window shows up : 
- - -
![setupissue](https://github.com/SoftFever/OrcaSlicer/assets/3301204/54e2a771-6fbe-4f08-86d2-14da5543c6db)
- - -  

### Expected results

While I could understand its concerns, I expect orcaslicer to stop hating me and my machine.

### Project file & Debug log uploads

1st run log file :
[debug_Thu_Nov_23_15_21_38_1622907.log](https://github.com/SoftFever/OrcaSlicer/files/13451352/debug_Thu_Nov_23_15_21_38_1622907.log)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by etrigan63** [comment]
Same thing happening in Arch Linux.

**Comment by yomgui1** [comment]
Same after updated my NVidia drivers to 535.146.02

**Comment by yomgui1** [comment]
After a quick search, it looks to be an issue with WebKitGTK and DMA buffer.
Starting Orca with following environment variable set resolve the display issue: WEBKIT_DISABLE_DMABUF_RENDERER=1

**Comment by didli** [comment]
> Starting Orca with following environment variable set, resolves this display issue: WEBKIT_DISABLE_DMABUF_RENDERER=1
Works fine for me with this env set as mentioned. However as the issue is still in-going (at least with latest stable 2.0 version), this only serves as a workaround.

**Comment by letsruletheworld** [comment]
only helps with the startupwindow. the 3D view is still missing.
