### ISSUE TITLE
Side panel switch desn't work correctly

### ISSUE THREAD

**Issue by danik-ik** [SoftFever/OrcaSlicer#2861]
### OrcaSlicer Version

1.7.0

### OS version

Linux mint 21.1 Cinnamon

### Additional system information

System:
  Kernel: 6.2.0-37-generic x86_64 bits: 64 compiler: N/A Desktop: Cinnamon 5.8.4 tk: GTK 3.24.33
    wm: muffin dm: LightDM Distro: Linux Mint 21.2 Victoria base: Ubuntu 22.04 jammy
Machine:
  Type: Desktop Mobo: ASRock model: A520M-ITX/ac serial: <superuser required>
    UEFI: American Megatrends v: P1.10 date: 08/24/2020
CPU:
  Info: 8-core model: AMD Ryzen 7 PRO 4750G with Radeon Graphics bits: 64 type: MT MCP arch: Zen 2
    rev: 1 cache: L1: 512 KiB L2: 4 MiB L3: 8 MiB
  Speed (MHz): avg: 1568 high: 3600 min/max: 1400/4454 boost: enabled cores: 1: 1723 2: 1396
    3: 1579 4: 1400 5: 1397 6: 1397 7: 1397 8: 1400 9: 3600 10: 1400 11: 1400 12: 1400 13: 1400
    14: 1400 15: 1400 16: 1400 bogomips: 114986
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm
Graphics:
  Device-1: AMD Renoir driver: amdgpu v: kernel pcie: speed: 8 GT/s lanes: 16 ports:
    active: DP-1,HDMI-A-1 empty: DP-2 bus-ID: 07:00.0 chip-ID: 1002:1636
  Device-2: Logitech Webcam C270 type: USB driver: snd-usb-audio,uvcvideo bus-ID: 3-2:2
    chip-ID: 046d:0825
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: amdgpu,ati
    unloaded: fbdev,modesetting,vesa gpu: amdgpu display-ID: :0 screens: 1
  Screen-1: 0 s-res: 3840x1080 s-dpi: 96
  Monitor-1: DisplayPort-0 mapped: DP-1 pos: right model: Philips PHL 243V7 res: 1920x1080
    dpi: 93 diag: 604mm (23.8")
  Monitor-2: HDMI-A-0 mapped: HDMI-A-1 pos: primary,left model: Philips PHL 243V7 res: 1920x1080
    dpi: 93 diag: 604mm (23.8")
  OpenGL: renderer: AMD Radeon Graphics (radeonsi renoir LLVM 15.0.7 DRM 3.49 6.2.0-37-generic)
    v: 4.6 Mesa 24.0~git2311220600.73317b~oibaf~j (git-73317bb 2023-11-22 jammy-oibaf-ppa)
    compat-v: 4.6 direct render: Yes
Audio:
  Device-1: AMD Renoir Radeon High Definition Audio driver: snd_hda_intel v: kernel pcie:
    speed: 8 GT/s lanes: 16 bus-ID: 07:00.1 chip-ID: 1002:1637
  Device-2: AMD Family 17h HD Audio vendor: ASRock driver: snd_hda_intel v: kernel pcie:
    speed: 8 GT/s lanes: 16 bus-ID: 07:00.6 chip-ID: 1022:15e3
  Device-3: Logitech Webcam C270 type: USB driver: snd-usb-audio,uvcvideo bus-ID: 3-2:2
    chip-ID: 046d:0825
  Sound Server-1: ALSA v: k6.2.0-37-generic running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet vendor: ASRock driver: r8169
    v: kernel pcie: speed: 2.5 GT/s lanes: 1 port: f000 bus-ID: 03:00.0 chip-ID: 10ec:8168
  IF: enp3s0 state: up speed: 1000 Mbps duplex: full mac: <filter>
  Device-2: Intel Dual Band Wireless-AC 3168NGW [Stone Peak] driver: iwlwifi v: kernel pcie:
    speed: 2.5 GT/s lanes: 1 bus-ID: 04:00.0 chip-ID: 8086:24fb
  IF: wlp4s0 state: up mac: <filter>
  IF-ID-1: br-440a152ade08 state: down mac: <filter>
  IF-ID-2: br-68923040f141 state: down mac: <filter>
  IF-ID-3: br-b5b0f3c04d4b state: up speed: 10000 Mbps duplex: unknown mac: <filter>
  IF-ID-4: br-b6e2661fdbba state: down mac: <filter>
  IF-ID-5: br-df00fd46bd3d state: down mac: <filter>
  IF-ID-6: cscotun0 state: unknown speed: 10000 Mbps duplex: full mac: N/A
  IF-ID-7: docker0 state: down mac: <filter>
  IF-ID-8: veth3c5bd03 state: up speed: 10000 Mbps duplex: full mac: <filter>
  IF-ID-9: veth763fa56 state: up speed: 10000 Mbps duplex: full mac: <filter>
Bluetooth:
  Device-1: Intel Wireless-AC 3168 Bluetooth type: USB driver: btusb v: 0.8 bus-ID: 1-9:5
    chip-ID: 8087:0aa7
  Report: hciconfig ID: hci0 rfk-id: 0 state: down bt-service: enabled,running rfk-block:
    hardware: no software: yes address: <filter>
Drives:
  Local Storage: total: 447.13 GiB used: 333.84 GiB (74.7%)
  ID-1: /dev/sda vendor: Kingston model: SA400M8480G size: 447.13 GiB speed: 6.0 Gb/s
    serial: <filter>
Partition:
  ID-1: / size: 218.95 GiB used: 155.28 GiB (70.9%) fs: ext4 dev: /dev/sda2
  ID-2: /boot/efi size: 486 MiB used: 6.1 MiB (1.2%) fs: vfat dev: /dev/sda1
  ID-3: /home size: 218.57 GiB used: 178.55 GiB (81.7%) fs: ext4 dev: /dev/sda3
Swap:
  ID-1: swap-1 type: file size: 2 GiB used: 768 KiB (0.0%) priority: -2 file: /swapfile
Sensors:
  System Temperatures: cpu: N/A mobo: N/A gpu: amdgpu temp: 48.0 C
  Fan Speeds (RPM): N/A
Repos:
  Packages: 3303 note: see --pkg apt: 3283 flatpak: 20
  No active apt repos in: /etc/apt/sources.list
  No active apt repos in: /etc/apt/sources.list.d/additional-repositories.list
  Active apt repos in: /etc/apt/sources.list.d/appimagelauncher-team-stable-jammy.list
    1: deb [signed-by=/etc/apt/keyrings/appimagelauncher-team-stable-jammy.gpg] https: //ppa.launchpadcontent.net/appimagelauncher-team/stable/ubuntu jammy main
  Active apt repos in: /etc/apt/sources.list.d/git-core-ppa-focal.list
    1: deb http: //ppa.launchpad.net/git-core/ppa/ubuntu jammy main
  Active apt repos in: /etc/apt/sources.list.d/google-chrome.list
    1: deb [arch=amd64] http: //dl.google.com/linux/chrome/deb/ stable main
  Active apt repos in: /etc/apt/sources.list.d/nodesource.list
    1: deb [signed-by=/usr/share/keyrings/nodesource.gpg] https: //deb.nodesource.com/node_19.x focal main
    2: deb-src [signed-by=/usr/share/keyrings/nodesource.gpg] https: //deb.nodesource.com/node_19.x focal main
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list
    1: deb http: //packages.linuxmint.com victoria main upstream import backport
    2: deb http: //archive.ubuntu.com/ubuntu jammy main restricted universe multiverse
    3: deb http: //archive.ubuntu.com/ubuntu jammy-updates main restricted universe multiverse
    4: deb http: //archive.ubuntu.com/ubuntu jammy-backports main restricted universe multiverse
    5: deb http: //security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
  Active apt repos in: /etc/apt/sources.list.d/oibaf-graphics-drivers-jammy.list
    1: deb [signed-by=/etc/apt/keyrings/oibaf-graphics-drivers-jammy.gpg] https: //ppa.launchpadcontent.net/oibaf/graphics-drivers/ubuntu jammy main
  Active apt repos in: /etc/apt/sources.list.d/skype-stable.list
    1: deb [arch=amd64] https: //repo.skype.com/deb stable main
  Active apt repos in: /etc/apt/sources.list.d/sublime-text.list
    1: deb https: //download.sublimetext.com/ apt/stable/
  Active apt repos in: /etc/apt/sources.list.d/tensor.list
    1: deb https: //update.sbis.ru/Sbis3Plugin/23.6213.56/linux/deb_repo ./
  Active apt repos in: /etc/apt/sources.list.d/winehq.list
    1: deb [signed-by=/usr/share/keyrings/winehq.gpg] http: //dl.winehq.org/wine-builds/ubuntu/ jammy main
Info:
  Processes: 458 Uptime: 21h 58m Memory: 30.73 GiB used: 12.85 GiB (41.8%) Init: systemd v: 249
  runlevel: 5 Compilers: gcc: 11.4.0 alt: 11/12/8/9 Client: Cinnamon v: 5.8.4 inxi: 3.3.13

### Printer

Doesn't mean

### How to reproduce

AppImage distribution.
I want to switch (open or close) the side panel (Shift+Tab). 
The initial state: side panel is open.
Step 0: click in the model view/preview area

Scenario 1.
1. Press Shift
2. press tab (the panel is hidden)
3. release tab (ERROR: the panel is shown again)
4. release shift (the panel is still open)

Scenario 2
1. Press shift
2. press tab (the panel is hidden)
3. release SHIFT first. The panel is slill hidden, but the view mode switched: model → preview or preview → model.
4. release tab. The panel is still hidden, but ERROR: the viev mode is changed.

Se same issue occurs when I want to show hidden side panel

### Actual results

Panel is NOT become hidden or shown (scenario 1),
or it is, but the view mode changes which is undesirable (scenario 2)

### Expected results

The panel is hidden (if it was shown before), or shown (if it was hidden).
The view mode doesn't change.

### Project file & Debug log uploads

[debug_Thu_Nov_23_18_19_49_570721.log.0.zip](https://github.com/SoftFever/OrcaSlicer/files/13451569/debug_Thu_Nov_23_18_19_49_570721.log.0.zip)

### Checklist of files to include

- [x] Log file
- [ ] Project file

**Comment by Noisyfox** [comment]
Should have been fixed now.
