### ISSUE TITLE
PA Pattern does not always generate pattern when slicing

### ISSUE THREAD

**Issue by Bath93** [SoftFever/OrcaSlicer#2864]
### OrcaSlicer Version

1.8.0

### OS version

Windows 11

### Additional system information

13th Gen Intel(R) Core(TM) i7-13700KF
32GB DDR5 @ 5600MHz
NVIDIA GeForce RTX 4070

### Printer

Creality Ender 3 S1 (Running Sonic Pad)

### How to reproduce

Open New Project
Click calibration
Click pressure advance
Select DDE, PA Pattern, Start PA 0, End PA 0.08, PA step 0.005
click ok
click slice plate

### Actual results

No pattern is produced, only the square
![Screenshot 2023-11-23 115933](https://github.com/SoftFever/OrcaSlicer/assets/151865352/6bdb5233-e3e6-4d7a-8cac-b8bcbf4e5e3e)

### Expected results

The PA pattern should be produced. Sometimes it does work, but most often it does not.

### Project file & Debug log uploads

[log.zip](https://github.com/SoftFever/OrcaSlicer/files/13452400/log.zip)
[OrcaSlicer_PAProblem_BeforeSlicing.zip](https://github.com/SoftFever/OrcaSlicer/files/13452402/OrcaSlicer_PAProblem_BeforeSlicing.zip)
[OrcaSlicer_PAProblem_AfterSlicing.zip](https://github.com/SoftFever/OrcaSlicer/files/13452403/OrcaSlicer_PAProblem_AfterSlicing.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by TomFullen** [comment]
Same issue here in version 1.9.1 Just a cube generated.
