### ISSUE TITLE
Unable to turn off heated bed

### ISSUE THREAD

**Issue by tlhintoq** [SoftFever/OrcaSlicer#2867]
### OrcaSlicer Version

1.7

### OS version

Windows10x64

### Printer

CR10s-5 (but same with all)

### How to reproduce

1. Comment out the bed heating commands of the machine gCode, in the machine configuration.
2. Slice a file
3. Notice that there is a bed heating command in the `EXECUTABLE_BLOCK_START` just above the `CUSTOM` block.
![Snag_9a26111](https://github.com/SoftFever/OrcaSlicer/assets/11351506/46d0d10f-c6fc-42f8-a129-ef4666a837ff)

### Actual results

3. Notice that there is a bed heating command in the `EXECUTABLE_BLOCK_START` just above the `CUSTOM` block.

This makes it impossible to configure a machine that has an independently controlled bed heater such as an AC powered heater with its own controller like Keenovo bed heater.

The material should have a bed temperature.  That material might be used on several machines in the same shop.  Whether or not a specific machine has a heated bed should be configurable in the machine setup and not be reliant on the material definition.

### Expected results

Bed heating is already in the custom code block.  It should not be forced in an additional spot.

### Project file & Debug log uploads

![Snag_9a1e8d3](https://github.com/SoftFever/OrcaSlicer/assets/11351506/fcb5f71c-1c29-4bee-a337-2e703ab55a6d)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by tlhintoq** [comment]
Anti-bot auto-close nudge remark

**Comment by tlhintoq** [comment]
Anti-bot auto-close nudge remark

**Comment by tlhintoq** [comment]
Hey bot - Don't close me now

**Comment by tlhintoq** [comment]
Keep alive comment

**Comment by tlhintoq** [comment]
FYI: Still a problem in 1.8.1
![image](https://github.com/SoftFever/OrcaSlicer/assets/11351506/48d1d398-2677-4238-af6f-639b55c5bc5f)

**Comment by tlhintoq** [comment]
Keep alive

**Comment by tlhintoq** [comment]
Tag - you're it - Still an open issue.

**Comment by tlhintoq** [comment]
Still an issue on 1.9.0 beta

**Comment by tlhintoq** [comment]
Keep alive - Still an issue in 2.0 developer/nightly
![image](https://github.com/SoftFever/OrcaSlicer/assets/11351506/77366e3c-a0d7-4742-b59c-4d8727d4b13a)

**Comment by tlhintoq** [comment]
Interesting observation for nightly 20241221

If you select a temperature tower the generated gcode doesn't include setting the bed temp before the custom block.  It relies on the custom block to do its job.

But if you have another model instead... Even a built-in item like the Orca cube... Then it sets the bed temp.

@SoftFever @Noisyfox  Really would be nice to get this fixed for those of us with externally controlled AC heated beds.  Just seems like a fix that can't be more than 20 minutes to track down where the bed temp is being injected when it doesn't need to be and the user can't block it.

![image](https://github.com/SoftFever/OrcaSlicer/assets/11351506/e0ba4619-4d0f-4ad8-99d9-dd14d612894b)

**Comment by tlhintoq** [comment]
Hey bot, please don't close me - this is still an issue.

**Comment by tlhintoq** [comment]
@SoftFever @Noisyfox 
Just wondering...
Since fixing this seems to be a long-term issue...
Is there a gcode change ability that I can attach to jobs for the s5?
Like
` replace m190 with ;m190`
but have it happen just on jobs sliced for the printer with no heat bed.
This bit of having to open every s5 job in Notepad++, do a find, delete the line that should be there anyway,... Its getting old.

**Comment by tlhintoq** [comment]
> @tlhintoq Orca will automatically insert heating command if no heating command is detected in custom gcode. Not sure if it's a bug in your case. 

That is absolutely a/the bug in this case. That is the behavior I'm trying to stop.  The printer has no heated bed controlled by the printer controller. The heated bed is plugged directly to AC mains power and has its own controller.
![image](https://github.com/SoftFever/OrcaSlicer/assets/11351506/fef47085-3485-4dfa-8459-fcad495f1994)

There is no bed thermistor connected to the printer. If you try to send a command to heat the bed it squeals, throws up an error on the LCD. "Min temp error"

So anyone with an externally controlled heatbed can't use Orca.  That's at least half of the CR10s-4 and CR10s-5 users I know on those groups. Glass beds 400-500-600mm big take forever to heat off a 24vdc printer power supply: That's why owners of big bed machines get the AC mains powered silicone heat beds. 

They are forced to use Cura over a simple matter of a checkbox on the printer configuration page.
![image](https://github.com/SoftFever/OrcaSlicer/assets/11351506/35844ccf-00be-45c2-b677-8faceb443935)
And a simple line of code _to the effect of_ this logi:
`if {HasHeatedBed} then InsertBedHeatComman(BedTemp);`
however the actual code in Orca would follow that logic.

Does that help understand the problem better?

**Comment by tlhintoq** [comment]
Problem still exists in current 2.0 nightly as of 13mar2024

**Comment by tlhintoq** [comment]
Keep alive.  Problem still exists in current 2.0 nightly as of 15apr2024

**Comment by tlhintoq** [comment]
Bot nudge.

**Comment by jltx1** [comment]
this is absolutely wrong.  A slicer should NEVER control the machine without my consent.  I use macros to manage heaters and Orca decides to insert its own heating commands.  This must be allowed to be disabled.  If someone omits a heating command in their start g-code then that is on them.  Don't try to be a nanny.  Please fix.

**Comment by umartechboy** [comment]
Try 
M190 S0
In your start G code. Orca, just like cura, will skip its own heating command.

**Comment by ging3rb3ardman** [comment]
Only work around currently is exporting as G-Code and manually editing.  Orca is not detecting either M140 or M190 codes for heated bed in startup gcode editor for me.

In my usecase, I needed the bed completely off for a specific filament.

I got rid of M190 and substituted for M140.

Example of my "Executable Block Start" section:


_; EXECUTABLE_BLOCK_START
M73 P0 R148
M201 X20000 Y20000 Z500 E5000
M203 X500 Y500 Z20 E30
M204 P20000 R5000 T20000
M205 X9.00 Y9.00 Z3.00 E2.50 ; sets the jerk limits, mm/sec
M106 S0
M106 P2 S0_
_**M140 S0; sets temp but does not wait**_ 

Hope this helps those who need to edit this until hopefully something like this becomes a feature.

(Edits: grammar)
