### ISSUE TITLE
latest build #40 and #41 are no good for mac version, only 16.5kb

### ISSUE THREAD

**Issue by wnc2** [SoftFever/OrcaSlicer#2870]
### OrcaSlicer Version

1.8

### OS version

macos

### Printer

ratrig

### How to reproduce

simply read ot at best try to download

### Actual results

wrong file size

### Expected results

right file size

### Project file & Debug log uploads

what?

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Noisyfox** [comment]
That's been fixed now, thanks.
