### ISSUE TITLE
Arrange function broken

### ISSUE THREAD

**Issue by altmenorg** [SoftFever/OrcaSlicer#2872]
### OrcaSlicer Version

1.8.0

### OS version

Windows 11 / Ubuntu

### Printer

FLSun V400

### How to reproduce

Place multiple objects on the place, and try to arrange...
![1](https://github.com/SoftFever/OrcaSlicer/assets/18574781/792cbbda-d1e0-4b95-bf6e-e201720f5cc5)

### Actual results

Tried to both arrange "all plates" or arrange on plate (A and Shift + A) and got the following results
![3](https://github.com/SoftFever/OrcaSlicer/assets/18574781/5a320552-6f54-44b7-8e78-e4370af7a52d)
![2](https://github.com/SoftFever/OrcaSlicer/assets/18574781/7f4892b5-c537-4067-80a7-502712463dfc)

### Expected results

Should look something like this :
![4](https://github.com/SoftFever/OrcaSlicer/assets/18574781/ca3feb41-2d4b-4131-b038-4a1566ad08bb)

### Project file & Debug log uploads

[log.zip](https://github.com/SoftFever/OrcaSlicer/files/13457665/log.zip)
[test.zip](https://github.com/SoftFever/OrcaSlicer/files/13457672/test.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by julie777** [comment]
I have the same issue. My case is very simple. With 6 objects on the plate that will easily fit. 
![image](https://github.com/SoftFever/OrcaSlicer/assets/5090005/bcc71cce-5e55-4fa5-803a-e4638e03363b)
I click on the plate arrange icon and auto-arrange moves one of the items off the plate.
![image](https://github.com/SoftFever/OrcaSlicer/assets/5090005/fa1d181f-0b5f-46c1-9c40-e0af15e3cdde)

**Comment by altmenorg** [comment]
Another weird effect of the issue... I tried the "fill bed with copies" function. The issue is the same.
Here is the plate before
![before](https://github.com/SoftFever/OrcaSlicer/assets/18574781/0bc5fb45-4be8-40f7-bfb4-13b617d57d3f)

Here is the plate after
![after](https://github.com/SoftFever/OrcaSlicer/assets/18574781/a3a83dee-01ce-4ec2-85fd-1389f8088d7f)

Doesn't fill at all. It seems like the geometry of my plate isn't right from Orcaslicer perspective...

Everything works like a charm with Prusaslicer, by the way
![prusaslicer](https://github.com/SoftFever/OrcaSlicer/assets/18574781/35a5b6af-5507-4d66-93a2-ddab1d57738d)

I only own a delta printer. Can someone confirm if the "fill bed with instances" works with a more standard bed geometry ?

**Comment by kleinwareio** [comment]
I have this same issue. v1.9.1 and a 300mm diameter build plate (v400).

From the outside, it appears like the algorithm is able to correctly place the first column of parts, but then its idea of what the bounding box is screws up for the remaining columns.

The auto-arrange appears to break in the same way the "[Fill bed with copies](https://github.com/SoftFever/OrcaSlicer/issues/1904)" breaks. I suspect they're using the same algorithm under the hood.

The bed was populated by "Fill bed...". Then cloning one more item and moving it onto an empty area of the bed and then performing auto-arrange ends up moving that newly added item off the bed to the "outside."

![image](https://github.com/SoftFever/OrcaSlicer/assets/32728112/24f6e8c7-0467-4bae-bc64-8d72dd49a9c4)
