### ISSUE TITLE
Turkish Language file

### ISSUE THREAD

**Issue by olcayoren** [SoftFever/OrcaSlicer#2879]
### OrcaSlicer Version

1.8.0

### OS version

Macos Sonoma 14.0

### Additional system information

Macbook m1

### Printer

Elegoo Neptune 4 Pro

### How to reproduce

Hello, I could not find the lines in the Turkish language file (OrcaSlicer_tr.po) to edit the English fields in the picture? How can I edit it?

### Actual results

Although Turkish is selected as the language, some fields on the login screen are in English.
<img width="963" alt="Ekran Resmi 2023-11-25 14 35 42" src="https://github.com/SoftFever/OrcaSlicer/assets/33813227/3a4e9c0a-67c4-4c21-983a-6f99b25b0748">

### Expected results

Under normal circumstances, all terms are expected to be in Turkish.

### Project file & Debug log uploads

No need for log file

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by olcayoren** [comment]
Hello, I could not see the corresponding values ​​in the language file, how should they be added? @Noisyfox

**Comment by Noisyfox** [comment]
Those are placed in the resource/web folder
