### ISSUE TITLE
Bridging not working?

### ISSUE THREAD

**Issue by Arakon** [SoftFever/OrcaSlicer#2885]
### OrcaSlicer Version

1.8.0

### OS version

Windows 11

### Additional system information

Irrelevant

### Printer

VZBot custom

### How to reproduce

- Load the attached project and slice
- Check Layer 11 and notice that the sacrificial layer in that position is not using bridging, but rather overhangs that turn around a corner, making them unprintable (at least cleanly)
- I generally have a feeling that a lot of places where bridges should be used, Orca implements overhangs instead.

### Actual results

Sacrificial layer in mid-air is printed as overhang instead of bridge
![overhang](https://github.com/SoftFever/OrcaSlicer/assets/12016360/edb9e14e-d9d5-47f2-988d-0d577bc16ff9)
![beforeoverhang](https://github.com/SoftFever/OrcaSlicer/assets/12016360/9545ce80-36f2-4a3c-83ec-328aed061d08)

### Expected results

Bridging should be used. Example from Superslicer:
![superslicer](https://github.com/SoftFever/OrcaSlicer/assets/12016360/a9b763bc-d819-4044-bcf0-a2bc6c511a70)

### Project file & Debug log uploads

[Y_gantry_bottom_left.zip](https://github.com/SoftFever/OrcaSlicer/files/13464592/Y_gantry_bottom_left.zip)
[debug_Fri_Nov_24_20_08_51_3192.log.0.zip](https://github.com/SoftFever/OrcaSlicer/files/13464593/debug_Fri_Nov_24_20_08_51_3192.log.0.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by igiannakas** [comment]
Disable the extra perimeters on overhang setting. 

![image](https://github.com/SoftFever/OrcaSlicer/assets/59056762/295dddfd-a2a0-42c1-afa5-fddb34919972)

**Comment by Arakon** [comment]
Indeed, thanks.
