### ISSUE TITLE
Double digit Jerk settings dont emit SET_VELOCITY_LIMIT commands in Gcode when using Klipper

### ISSUE THREAD

**Issue by Nils-Hoffmann** [SoftFever/OrcaSlicer#2886]
### OrcaSlicer Version

1.8.0

### OS version

Windows 10

### Printer

Generic Klipper Printer

### How to reproduce

- Change Jerk settings of any/all feature to 10 or greater
- Slice any file
- GCODE export doesnt contain any commands SET_VELOCITY_LIMIT SQUARE_CORNER_VELOCITY=10 (or above)

### Actual results

Gcode with Jerk value below 10:
![image](https://github.com/SoftFever/OrcaSlicer/assets/7586835/96967f08-f242-44b3-ba05-96ffbfe68eb7)

Gcode with value above 10:
![image](https://github.com/SoftFever/OrcaSlicer/assets/7586835/413a74db-aeaf-445e-82c6-8898cae6a9bc)

### Expected results

SET_VELOCITY_LIMIT ACCEL=... ACCE_TO_DECEL=... SQUARE_CORNER_VELOCITY=... gcode commands are emitted for values above 10,

### Project file & Debug log uploads

log: [debug_Sat_Nov_25_18_19_44_43600.log](https://github.com/SoftFever/OrcaSlicer/files/13464862/debug_Sat_Nov_25_18_19_44_43600.log)
[3DBenchy.zip](https://github.com/SoftFever/OrcaSlicer/files/13464864/3DBenchy.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by igiannakas** [comment]
Not a bug. Set your Maximum Jerk X and Y in the motion ability of your printer settings to something higher. If the motion limit value is below the jerk setting in your process profile it will get ignored. 

![image](https://github.com/SoftFever/OrcaSlicer/assets/59056762/375987cd-f427-4e94-8302-f5f782899ad9)
