### ISSUE TITLE
Crashing when I click pressure advance test 

### ISSUE THREAD

**Issue by Brett19E7** [SoftFever/OrcaSlicer#2888]
### OrcaSlicer Version

V1.8.0-beta1

### OS version

Windows 10

### Printer

Anycubic kobra neo 

### How to reproduce

Calibration
Click on pressure advance settings DDE method PA Tower or PA Pattern error message picture taken then click ok and shuts down 
![inbound7006960158137283531](https://github.com/SoftFever/OrcaSlicer/assets/152027871/b9577b2d-9de8-42fb-8fec-c6cf96d6e9c5)
![inbound8029664653961313068](https://github.com/SoftFever/OrcaSlicer/assets/152027871/4ac764b6-55b9-4de2-9ab0-c15f265ab18c)

### Actual results

![inbound4119439725491119266](https://github.com/SoftFever/OrcaSlicer/assets/152027871/eb17c7a0-330e-4f47-92a4-623781dcb1e4)

### Expected results

Should slice the test so I can print it 

### Project file & Debug log uploads

N/A

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Downquark7** [comment]
Try updating to the latest version (1.8.0 official release)

**Comment by Brett19E7** [comment]
Yeah I found that confusing witch was the correct one 
![17009497803944447518265747225750](https://github.com/SoftFever/OrcaSlicer/assets/152027871/63ddac09-f6dc-4b47-a416-444e51ee711c)

**Comment by Downquark7** [comment]
Scroll down to assets of that box

**Comment by Brett19E7** [comment]
Thank you I can see the windows installer  1.8.0 and the portable zip

**Comment by Downquark7** [comment]
Installer is easier to use

**Comment by Brett19E7** [comment]
Thank you just want it to work so I can run these tests lol appreciate it

**Comment by Brett19E7** [comment]
![17009518859107514263105027723200](https://github.com/SoftFever/OrcaSlicer/assets/152027871/18af17dd-1b18-49f6-aab3-13d3dda3c947)


Same issue

**Comment by Noisyfox** [comment]
Could you post the crash log?

**Comment by Brett19E7** [comment]
How do I find the crash log?

**Comment by Noisyfox** [comment]
In the slicer's help menu there is an option called "open config folder" which you will find the logs there.

**Comment by Brett19E7** [comment]
Thank you I will do that asap

**Comment by Brett19E7** [comment]
There my only options I have

**Comment by Brett19E7** [comment]
I sent a picture when I click help there is not the option for the file log
you told me about

**Comment by Noisyfox** [comment]
Sorry but I don't understand what you are talking about. Stop replying via email if you want to post any pictures because that doesn't work.

**Comment by Brett19E7** [comment]
![17012497519671175267347902487433](https://github.com/SoftFever/OrcaSlicer/assets/152027871/7a398650-cfc8-4371-9d7d-1a5bcef8a022)

**Comment by Brett19E7** [comment]
Crant see the option for crash log

**Comment by Noisyfox** [comment]
"Show configuration folder"

**Comment by Brett19E7** [comment]
![17012522804283817363141446615589](https://github.com/SoftFever/OrcaSlicer/assets/152027871/0bc00e4e-2e2a-4bf1-a1bf-c73e4207785d)

I believe it's the one where it creates a closure

**Comment by Noisyfox** [comment]
Could you upload the log file?

**Comment by Noisyfox** [comment]
Will the app crash if you select a build-in printer/filament/process profile?

**Comment by silence48** [comment]
Another c0000005 ACCESS_VIOLATION
Related issues include #2921 #3375 #3340 #3292 #3157 #2896 #2766
