### ISSUE TITLE
UI refuses to enlarge beyond a single monitor

### ISSUE THREAD

**Issue by tlhintoq** [SoftFever/OrcaSlicer#2889]
### OrcaSlicer Version

1.7

### OS version

Win10x64

### Additional system information

i9 gen 11
See attached specs

### Printer

Any

### How to reproduce

On a dual monitor PC, try to resize to take advantage of all of your screen real estate.

### Actual results

Orca slicer refuses to resize taller than one monitor.

### Expected results

Orca slicer shouldn't be forcing the user to a smaller space during a drag.  There's already widgets in the title bar if someone want to snap to the window max.
![Snag_146b753f](https://github.com/SoftFever/OrcaSlicer/assets/11351506/7d15d456-575d-4c6a-a13f-afffca9d5eb3)

### Project file & Debug log uploads

![StealthDeck_DeviceManager](https://github.com/SoftFever/OrcaSlicer/assets/11351506/98ce70c2-8447-4cb8-928e-fa2fb0d5f5fa)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by tlhintoq** [comment]
Anti-bot auto-close nudge remark

**Comment by tlhintoq** [comment]
Hey bot - Don't close me now

**Comment by tlhintoq** [comment]
Keep alive comment

**Comment by foreachthing** [comment]
Looks like the OrcaSlicer windows' max. size is set to the startup monitor size.
Same issue on Windows 10/11.

**Comment by foreachthing** [comment]
@tlhintoq I'm, by all means, no programmer 😆 .
I just wanted to let you and others know that the same for Windows is happening.

**Comment by Noisyfox** [comment]
I'll take a look soon.

**Comment by Noisyfox** [comment]
I think that's a limitation of Windows, it simply does not allow you to resize a window larger than the size of your largest monitor size.

**Comment by foreachthing** [comment]
> Does any of the other software you are using that allows you to do so?

Almost every other software can do that (didn't try everything I have installed, but a whole bunch). So, it's not a Windows problem. It's the application not allowing to be larger than a single monitor.
Need more info, please let me know.

**Comment by tlhintoq** [comment]
> Does any of the other software you are using that allows you to do so?

Absolutely - nearly any program should do it so long as there hasn't been some specific action taken by a program to deliberately stop it.
Its a pretty common case - Aren't you running Visual Studio?  It does it.  Pretty common to run code on a vertical monitor or on two monitors acting as one.
![Snag_f4bd9a4](https://github.com/SoftFever/OrcaSlicer/assets/11351506/a384dc79-97f2-4d6f-80d6-07d3943b80f3)
![Snag_f4bfcdb](https://github.com/SoftFever/OrcaSlicer/assets/11351506/688605e2-84d9-4ef3-8cd3-0fe7bc76b692)
![Snag_f4c197c](https://github.com/SoftFever/OrcaSlicer/assets/11351506/9a59b3cb-3d53-4994-a328-b79e47539e05)
![Snag_f4c2ab2](https://github.com/SoftFever/OrcaSlicer/assets/11351506/ccbd15dc-c2f3-4b07-b73e-a39fcb427597)

**Comment by tlhintoq** [comment]
Keep alive

**Comment by Noisyfox** [comment]
I've found the cause of this issue. Will raise a PR soon.

**Comment by Noisyfox** [comment]
Could you give the pr build a try and see if it solves the problem? @tlhintoq

**Comment by Noisyfox** [comment]
There are a few bugs found. Repoening this.

**Comment by tlhintoq** [comment]
Watching for updates.
Sidenote: I haven't run Visual Studio in a couple years.  I don't even have it installed on my new laptop.  So pulling and compiling won't happen right away for me.  _{But I'm realizing I probably need to get back into this side of things}_

**Comment by Noisyfox** [comment]
> Sidenote: I haven't run Visual Studio in a couple years. I don't even have it installed on my new laptop. So pulling and compiling won't happen right away for me.

You don't have to do this. We got CI build for every PRs, so you could just download the binary from it.

**Comment by foreachthing** [comment]
@Noisyfox, which one should I try? https://github.com/SoftFever/OrcaSlicer/actions
Thanks!!

**Comment by Noisyfox** [comment]
https://github.com/SoftFever/OrcaSlicer/actions/runs/7235901104?pr=3149
this one

**Comment by foreachthing** [comment]
This PR works for me 😁 
This screenshot spans over 2x 4k monitors. It's an **AWESOME** sight! 👍🏼 

![image](https://github.com/SoftFever/OrcaSlicer/assets/10420187/a14b3476-a0f3-4f5e-8041-ec557b749fee)
