### ISSUE TITLE
M600 entry at the beginning of the print

### ISSUE THREAD

**Issue by bronsn** [SoftFever/OrcaSlicer#2893]
### OrcaSlicer Version

1.8.0

### OS version

Windows 11

### Printer

Ender 7 / K1

### How to reproduce

Setup a print File, add a second or third Filament, add at a specific layer height the Filament Change and slice the Objekt.
If i check the sliced gcode, there are 3 M600 Entry´s in the Code, 2 are correct but every time the Slicer add the M600 at the beginning of the Code so the printer stop with M600 after the Start Code

I have to manaally delete the M600 Entry in the Gcode.

### Actual results

M600 at the beginning of the print

### Expected results

M600 only th this point i added it in the slicer

### Project file & Debug log uploads

?

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by staal54a** [comment]
I also seeing this issue

**Comment by Eldenroot** [comment]
Confirmed

**Comment by Krustyr47** [comment]
I see this as well.  M600 at the beginning.  However, also on every layer change not just the layer I selected.

**Comment by samiresa** [comment]
Ender 3V2 can confirm it is happening for me as well, removing the fist m600 via notepad modification.

**Comment by dral3x** [comment]
Same issue.

**Comment by SwineFlew931** [comment]
I have been manually deleting the first M600. Sometimes i forget (it's that problem of being human). But this is so annoying that I am looking at learning Python just to hopefully write a post processing script to remove it. It seems a check box for an option to include/exclude that first change would solve the issue and give people with AMS/MMU units as well as manual change folks the power to configure it as they need.

**Comment by dral3x** [comment]
I think it's related to the "Manual Filament Change" option, introduced in #2379.

If your printer (like my Sovol SV06) support just one filament, you have to turn ON that option in your printer profile.
After that, the M600 is not added anymore at the beginning of each print with multiple colors, but only on the layers in which you set the color switch.

**Comment by borisb74** [comment]
> I think it's related to the "Manual Filament Change" option, introduced in #2379.
> 
> If your printer (like my Sovol SV06) support just one filament, you have to turn ON that option in your printer profile. After that, the M600 is not added anymore at the beginning of each print with multiple colors, but only on the layers in which you set the color switch.

Can confirm. After enabling the option for "Manual Filament Change" under Machine -> Multimaterial, the initial M600 is not in anymore. OrcaSlicer is version 1.8.1.

**Comment by SwineFlew931** [comment]
> > I think it's related to the "Manual Filament Change" option, introduced in #2379.
> > If your printer (like my Sovol SV06) support just one filament, you have to turn ON that option in your printer profile. After that, the M600 is not added anymore at the beginning of each print with multiple colors, but only on the layers in which you set the color switch.
> 
> Can confirm. After enabling the option for "Manual Filament Change" under Machine -> Multimaterial, the initial M600 is not in anymore. OrcaSlicer is version 1.8.1.

It was there the whole time *face->palm*.

Thank you @dral3x  for pointing that out.

**Comment by DBT85** [comment]
@dral3x thank you so much for that. I've only just started doing multi colours on my Ender 3 but having to strip the extra M600 after prime line out was a pain. Hopefully anyone else suffering the same issue will find this answer too!

**Comment by manferlo81** [comment]
Thank you @dral3x, @DBT85, @borisb74 , @SwineFlew931. I have the "Manual Filament Change" on but it still happening to me. I will attach a test project I put together really quick for a different issue but as it turns out it has an M600 at the beginning.

[M600 String Issue.zip](https://github.com/SoftFever/OrcaSlicer/files/14318079/M600.String.Issue.zip)

**Comment by Eldenroot** [comment]
Prusa slicer maybe fixed this in the 2.7.2 version?

I am not sure. Anyway this is not good for nonAMS users.

@SoftFever please could you reply if it is somehow fixable?

**Comment by samiresa** [comment]
![M500](https://github.com/SoftFever/OrcaSlicer/assets/129017544/bff141e1-746c-4afc-9397-70e90bc0a6c3)
This is how I fixed my issue, I think it is a bug, but this is a work around.

**Comment by vgdh** [comment]
It's not a bug. 
If you change filament automatically you do need M600 at start of your Gcode because if there is no such command you will print with the last used filament. 
So when you choose **manual filament change** slicer doesn't emit M600 at the start because it is your job to put right filament in the machine.
