### ISSUE TITLE
Apply bridge infill density for first layer above infill

### ISSUE THREAD

**Issue by rovili** [SoftFever/OrcaSlicer#290]
Please apply bridge infill density also for the first layer above infill - e.q. Super Slicer does.
Or create an additional bridge infill density for this purpose.

**Comment by hliebscher** [comment]
witch problem fix this?

**Comment by rovili** [comment]
Actually the same like bridge infill itself, prevents that the nozzle is dragging off the line next to it. 
Also prevents lifting up the bridge infill if not connected to a perimeter.
