### ISSUE TITLE
Generic PETG will change to ASA - Bambulabs X1 & AMS

### ISSUE THREAD

**Issue by TechDude23** [SoftFever/OrcaSlicer#2915]
### OrcaSlicer Version

1.8.0-beta 2

### OS version

Window 10

### Printer

Bambulabs X1

### How to reproduce

- Device tab
- Select Filament in the slot = generic PETG & confirm
- Next screen will change to ASA and it will not let you print with petg filament
- But if you switch it to Bambu labs basic petg it will work correctly and now you can print with petg
- This bug is also not in Bambu Studio Slicer 1.8.0.62 it's working correctly
- I don't know if the calibration tab and flow testing triggered this error ? 

![AMS_Photo_1](https://github.com/SoftFever/OrcaSlicer/assets/128856354/4e029047-d1bf-4b90-8e4c-0f46f414e1ab)

![AMS_Photo_2](https://github.com/SoftFever/OrcaSlicer/assets/128856354/d1fdac5b-c955-46ac-802a-36a644319f86)

### Actual results

Generic PETG will change to ASA filament on AMS icon

### Expected results

Generic PETG should show PETG on AMS filament icon

### Project file & Debug log uploads

None

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by svenzman** [comment]
Happens here too, but it only bugged in AMS Slot 4 and External Spool Holder (P1S with AMS)

I reinstalled ervything and deleted data manually, not fixed.

**Comment by TechDude23** [comment]
Version 1.9.0 DEV has been working correctly :)
