### ISSUE TITLE
Support Filament Interface Flushing Bugs Out When Disabling Prime Tower

### ISSUE THREAD

**Issue by Khangirey** [SoftFever/OrcaSlicer#2917]
### OrcaSlicer Version

1.8.0

### OS version

Win 11

### Printer

B1P

### How to reproduce

1. Load Model into slicer
2. Enable Supports
3. (Making sure to have 2 filaments enabled) Set "Support/Raft Interface" to second filament
4. Disable Prime Tower under Other tab
5. Slice, and record "Flushed" material amount under "Filament" dropdown in the top right

### Actual results

![bug report 1](https://github.com/SoftFever/OrcaSlicer/assets/65515074/84fd53ab-f879-444c-b83b-d25bb8d16fd0)

Flushed material always bugs out to be .02 or .01 grams, regardless of model - actual printing results in support material being printed in the base material, and certain sections of the base print contain support filament inclusions.

### Expected results

Actual changes should be similar to when Prime Tower is enabled. As shown in the below picture
![bug repot 2](https://github.com/SoftFever/OrcaSlicer/assets/65515074/9fb0093d-9542-493f-91cd-d3a6fa547025)

-----

Please see below comparison of bambu studio

![bug report 3](https://github.com/SoftFever/OrcaSlicer/assets/65515074/f3b60e8c-9e7b-40b7-97a2-584de88a2d9a)

### Project file & Debug log uploads

[petgplasupporttest.zip](https://github.com/SoftFever/OrcaSlicer/files/13494301/petgplasupporttest.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by Noisyfox** [comment]
Dup #2900

**Comment by igiannakas** [comment]
This is fixed in the latest nightly. Download from here: https://github.com/SoftFever/OrcaSlicer/actions/runs/7018932845
