### ISSUE TITLE
Doesn't run in a remote desktop on a VM - OpenGL error

### ISSUE THREAD

**Issue by jbuszkie** [SoftFever/OrcaSlicer#2928]
### OrcaSlicer Version

1.8.0

### OS version

win10

### Printer

none

### How to reproduce

Try to start

### Actual results

Program doesn't run.
I get the error "The application cannot run normally because your  OpenGL version is lower than 2.0"
Thent he program quits.
![Screenshot 2023-11-29 122941](https://github.com/SoftFever/OrcaSlicer/assets/11888706/282d3c35-7037-4f9b-8ebb-81a1bc66329e)

### Expected results

The program should run.
Bambu studio 1.7.7.89 runs fine.  Prusa slicer runs fine.

### Project file & Debug log uploads

Can't get configuration 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by jbuszkie** [comment]
Same issue with V1.7.0

**Comment by Noisyfox** [comment]
You can copy the "mesa" folder from BBS or PS into Orca and it should work. We will fix this in a future release.

**Comment by Mechanikerlegion511** [comment]
Hello guys, in version **1.9.0** **WIN10x64** there was also a problem: I had to copy the ***mesa*** folder from PrusaSlicer to ***C:\Program Files\OrcaSlicer*.**
_but under Linux everything works fine on the same laptop._
**The problem is only with Windows 10.**

**Comment by Antebios** [comment]
I copied the `mesa` from my SuperSlicer directory into OrcaSlicer and it worked!!!

**Comment by necrovamp** [comment]
> You can copy the "mesa" folder from BBS or PS into Orca and it should work. We will fix this in a future release.

Worked for me today for this error. Thank you
OrcaSlicer v2.30

**Comment by ddmgh** [comment]
This ticket should be reopened so it can be properly resolved; I shouldn't have to installed a different slicer to fix a problem with Orca.

**Comment by InsanityOnABun** [comment]
> This ticket should be reopened so it can be properly resolved; I shouldn't have to installed a different slicer to fix a problem with Orca.

Agreed, this issue isn't fixed, there is just a workaround that requires an install of another slicer.

**Comment by Noisyfox** [comment]
Please try #11281
