### ISSUE TITLE
Sign Windows Executables

### ISSUE THREAD

**Issue by Ocraftyone** [SoftFever/OrcaSlicer#2932]
Add signing to Windows executable (both the installer and the executable in the portable version)

Running an executable that is not signed on Windows shows a warning that it could contain malware etc and could turn away some users.

**Comment by SoftFever** [comment]
I thought about it.
But I feel it's not very necessary at the moment because of the hassles.
This blog summarizes it well: https://melatonin.dev/blog/how-to-code-sign-windows-installers-with-an-ev-cert-on-github-actions/

**Comment by kylek29** [comment]
^^ That explains why I see so many indie and small company programs that aren't even bothering with code-signing for Windows now, as a user I've gotten used to by-passing the malware disclaimer, their current system is contradictory to the whole purpose of the malware warning. They badly need to simplify that.

**Comment by Ocraftyone** [comment]
Yeah, that looks like a huge headache. Hopefully it becomes easier and more accessible soon.
