### ISSUE TITLE
UI issue on MacOS: print preview

### ISSUE THREAD

**Issue by superfloh247** [SoftFever/OrcaSlicer#2936]
### OrcaSlicer Version

e8a053e

### OS version

MacOS 14.1.1

### Additional system information

Apple Silicon M1pro

### Printer

Bambu P1P

### How to reproduce

Slice something

### Actual results

preview is shown with red background

### Expected results

preview should be shown with transparent background

### Project file & Debug log uploads

<img width="467" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/26180993/8a3c2ba5-1783-409a-acf2-913e5629108d">

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by Noisyfox** [comment]
Could you give a try to https://github.com/SoftFever/OrcaSlicer/pull/2926

**Comment by superfloh247** [comment]
I applied the patch

git fetch origin pull/2926/head:pr2926
git checkout pr2926

then removed the wx dips

rm -rf deps/build_arm64/dep_wxWidgets-prefix/src/dep_wxWidgets-build

then built the deps again

./build_release_macos.sh -d

then the slicer

./build_release_macos.sh

was that the correct way to apply the patch?

the background of the preview is stell red

**Comment by igiannakas** [comment]
It’s again because of the Xcode build on sonoma. Doesn’t happen if you build on ventura.

**Comment by Eldenroot** [comment]
@Noisyfox and @SoftFever - there are some new fixed from BL in latest GitHub commits from today, maybe it could help?

https://github.com/bambulab/BambuStudio/commits/master

**Comment by Noisyfox** [comment]
> @Noisyfox and @SoftFever - there are some new fixed from BL in latest GitHub commits from today, maybe it could help?
> 
> https://github.com/bambulab/BambuStudio/commits/master

Don't think that will help. I've looked at those new commits and doesn't find anything related. This appears to be another wxWidgets issue which BBS did not do anything to.

**Comment by superfloh247** [comment]
seems to be fixed in 3ca290d

<img width="456" alt="Bildschirmfoto 2023-12-15 um 08 06 57" src="https://github.com/SoftFever/OrcaSlicer/assets/26180993/8708d76c-21e4-4943-963b-8382ff61fe20">

**Comment by superfloh247** [comment]
this error is back in 90dd67e
