### ISSUE TITLE
UI issue on MacOS: scrolling panels

### ISSUE THREAD

**Issue by superfloh247** [SoftFever/OrcaSlicer#2937]
### OrcaSlicer Version

e8a053e

### OS version

MacOS 14.1.1

### Additional system information

Apple Silicon 14.1.1

### Printer

Bambu P1P

### How to reproduce

scroll any of the panels, eg Quality

### Actual results

panel slides over other UI elements

### Expected results

panel should slide behind other UI elements

### Project file & Debug log uploads

<img width="425" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/26180993/325196f6-c2ec-439c-be45-73c542e21c76">

now scroll down

<img width="429" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/26180993/b1e4ca8b-d839-455a-beab-20ae2e3ad059">

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by Noisyfox** [comment]
Yeah this only happens when you build locally. Seems to be a bug with newer Xcode. Tried to debug this a few months back but no luck.

**Comment by Eldenroot** [comment]
There are many macos fixem in bambu studio 1.8.1 version (released today). We should sync all useful changes and fixes into Orca. 1.8.0 is not synced too

**Comment by Noisyfox** [comment]
I've found the solution https://github.com/wxWidgets/wxWidgets/issues/23916
Will try backporting their fixes to Orca.

**Comment by Noisyfox** [comment]
Should have been fixed now.

**Comment by superfloh247** [comment]
aaaaaaaaaand back again in 374f78c

not fixed anymore

**Comment by Noisyfox** [comment]
> aaaaaaaaaand back again in [374f78c](https://github.com/SoftFever/OrcaSlicer/commit/374f78c7689b375c9fe842a2d4b8807eab70f176)
> 
> not fixed anymore

Yeah @SoftFever is working on it right now.
