### ISSUE TITLE
Temperature Calibration: Set temperature not working with Firmware RepRap

### ISSUE THREAD

**Issue by Omer-8** [SoftFever/OrcaSlicer#2953]
### OrcaSlicer Version

1.8.0

### OS version

Windows 10

### Printer

Custom

### How to reproduce

Doing the temperature calibration, the nozzle temperature is not changing.

### Actual results

Analysed the G-code-file: the temperature is only set at the begining.

### Expected results

The temperature clibration process should include the setting of the temperatures automatically into the G-code

### Project file & Debug log uploads

[temperature_tower_PLA_1h19m.zip](https://github.com/SoftFever/OrcaSlicer/files/13527762/temperature_tower_PLA_1h19m.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by Omer-8** [comment]
I figured out: Temperature calibration works with with custom printer Firmware Marlin (Legacy) and Marlin 2 and Klipper.
Does not work with Firmware RepRap. All following temperature changing  commands M104 are missing

**Comment by Nyhtfury** [comment]
I have a Fusion3 F410 running RepRap and Orca Slicer 1.8.1 also has this issue.
