### ISSUE TITLE
shifted icon

### ISSUE THREAD

**Issue by discip** [SoftFever/OrcaSlicer#2956]
I'm not sure, but I assume this happened after #2844.

### OrcaSlicer Version
[ae9a2d5](https://github.com/SoftFever/OrcaSlicer/actions/runs/7062190606)

### OS version
Linux (Manjaro)

### Actual results
![image](https://github.com/SoftFever/OrcaSlicer/assets/53649486/d24597af-44c5-4520-a82e-0b73a727d51c)

![image](https://github.com/SoftFever/OrcaSlicer/assets/53649486/675213d1-9092-4fa9-afa7-c8c48a99a6eb)

### Expected results
![image](https://github.com/SoftFever/OrcaSlicer/assets/53649486/29d7d33e-36a9-4f22-bb00-14e403107cce)

![image](https://github.com/SoftFever/OrcaSlicer/assets/53649486/d7727215-d720-4b3d-8c8d-9b29167ac66b)

**Comment by Eldenroot** [comment]
You are right :(

**Comment by Ocraftyone** [comment]
Noticed this too

**Comment by discip** [comment]
@Noisyfox @igiannakas @SoftFever
Does anyone have any idea about this?

**Comment by discip** [comment]
@Noisyfox @igiannakas @SoftFever
Does anyone have any idea about this?
This is still present in [0f2a223](https://github.com/SoftFever/OrcaSlicer/actions/runs/7300261688)

**Comment by discip** [comment]
@SoftFever @Noisyfox @igiannakas
Does anyone have any idea about this?
This is still present in [0f2a223](https://github.com/SoftFever/OrcaSlicer/actions/runs/7300261688)

**Comment by discip** [comment]
@SoftFever @Noisyfox @igiannakas
Does anyone have any idea about this?
This is still present in [0f2a223](https://github.com/SoftFever/OrcaSlicer/actions/runs/7300261688).

**Comment by igiannakas** [comment]
Unfortunately I can't replicate it as I dont see these icons on the Mac (and dont have another computer :() Will defer to Noisyfox / Ocraftyone for this one

**Comment by discip** [comment]
Still present even after [Revert to WxWidgets 3.1.5 (#3249)](https://github.com/SoftFever/OrcaSlicer/actions/runs/7307508790).

**Comment by discip** [comment]
@SoftFever
@Noisyfox

Any idea yet?

**Comment by discip** [comment]
Unfortunately this is still present using Manjaro Gnome.

**Comment by discip** [comment]
@yw4z
Could you please have a look at this?

![image](https://github.com/SoftFever/OrcaSlicer/assets/53649486/7355c1e8-2fd8-48ce-a478-bee27716b73f)


Additionally the icon is shifted very far to the left. Also in **`Printer settings`**:

![image](https://github.com/SoftFever/OrcaSlicer/assets/53649486/fe48ea69-3e81-450d-93ea-a2bf85b81a09)

I'm not sure if this also appears this way under Windows but using Linux (Manjaro Gnome) it certainly does.

Thanks in advance!

**Comment by yw4z** [comment]
i coulnt replicate issue on my system (windows 10) but this line responsible from that icon and DISABLE_UNDO_SYS also appears on  OG_CustomCtrl.cpp

https://github.com/SoftFever/OrcaSlicer/blob/e40d7780d596ed5e61973fbffb452f5391355a13/src/slic3r/GUI/Tab.cpp#L385-L388

here is how that area should looks like 
![Screenshot-20240507014437](https://github.com/SoftFever/OrcaSlicer/assets/28517890/7b50857e-5e36-4494-a379-a1debc27488e)

@jamincollins can you look at this im not using linux :)

**Comment by jamincollins** [comment]
I'll take a look

**Comment by discip** [comment]
@jamincollins
Any progress so far? 😊

**Comment by jamincollins** [comment]
No longer contributing to this project

**Comment by discip** [comment]
Oh, that's a shame.
Take care. 😊
