### ISSUE TITLE
Can't compile in DEBUG mode because of broken asserts

### ISSUE THREAD

**Issue by andrewboktor** [SoftFever/OrcaSlicer#2971]
### OrcaSlicer Version

Latest git

### OS version

Ubuntu

### Additional system information

Not relevant

### Printer

Not relevant

### How to reproduce

I can't build OrcaSlicer in DEBUG mode because of bad asserts
I'm using ./BuildLinux.sh on ubuntu. Works fine for release mode. But in debug mode it's failing on a bunch of asserts that reference code that seems to have been refactored.
Some of them are in the following files
TreeSupport.cpp
TreeSupportCommn.cpp
PressureEqualizer.cpp
GLGizmoMmuSegmentation.cpp

### Actual results

Fails to build

### Expected results

Succeed to build

### Project file & Debug log uploads

Not relevant

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Noisyfox** [comment]
Use `RelWithDebInfo` instead.

**Comment by andrewboktor** [comment]
> > Use `RelWithDebInfo` instead.
> 
> This! Also Debug is too slow to be "useful".

I don't like guessing at what's going wrong. I like to see it fail, then fix it. One step.
I agree that debug is dog slow. I got building with RelWithDebInfo, it's working great, but haven't tried debugging it yet. Will report back if/when I do.

**Comment by Ocraftyone** [comment]
When I build release (with VS2022 or jetbrains clion) I get breakpoints and exception inspection. Are there other benefits to using compiler debugging that I'm missing? Also, when compiling with relwithdebinfo, I get an error saying that orcaslicer.dll can't open its dependencies.
