### ISSUE TITLE
Mac Arm DMG for 1.8.1 release is broken. Won't run

### ISSUE THREAD

**Issue by rizwansarwar** [SoftFever/OrcaSlicer#2975]
### OrcaSlicer Version

1.8.1

### OS version

MacOS Arm

### Additional system information

Apple M1

### Printer

None

### How to reproduce

Install DMG on Apple M1

### Actual results

Won't run, running Orca slicer pops up error, "Application is damaged, and can't be opened. You should move it to Bin"

### Expected results

Should start application

### Project file & Debug log uploads

There is nothing to add here, application does not start.

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by alienboyxp** [comment]
Same here, Ventura 13.4.1

**Comment by Mario-vminion** [comment]
same here

**Comment by rizwansarwar** [comment]
> Run this command: xattr -dr com.apple.quarantine /Applications/OrcaSlicer.app
> 
> File was not signed, hence Mac wouldn't open it unless you told it its OK. New build from Softfever is coming in 1h.

we used to do that for SoftFever releases, but I thought it was dealt with in recent Orca releases as @SoftFever had already sorted the signing with valid certs. Did something get missed in the build? I rather just wait for a signed release whenever that comes.

**Comment by igiannakas** [comment]
> > Run this command: xattr -dr com.apple.quarantine /Applications/OrcaSlicer.app
> > File was not signed, hence Mac wouldn't open it unless you told it its OK. New build from Softfever is coming in 1h.
> 
> we used to do that for SoftFever releases, but I thought it was dealt with in recent Orca releases as @SoftFever had already sorted the signing with valid certs. Did something get missed in the build? I rather just wait for a signed release whenever that comes.

Yes it was an error - new build has been uploaded and is signed.
