### ISSUE TITLE
Merge Anycubic direct upload feature into Orcaslicer

### ISSUE THREAD

**Issue by kahl9** [SoftFever/OrcaSlicer#2988]
**Is your feature request related to a problem? Please describe.**
Not a problem necessarily.

**Which printers will be beneficial to this feature**
New Anycubic Kobra 2 series (Max, Pro, Neo, Plus) {I have the Kobra 2 Max personally}

**Describe the solution you'd like**
It would be great if Anycubic's direct upload over WiFi features could be merged into Orcaslicer. I prefer Orcaslicer over Anycubic's slicer because they have taken all advanced options out of the Anycubic slicer and Orcaslicer is head and shoulders better.

**Describe alternatives you've considered**
Anycubic's slicer will upload direct but it is so underwhelming in other features, they don't even have vase mode.

**Comment by Ocraftyone** [comment]
https://github.com/ANYCUBIC-3D/AnycubicSlicer source for any cubic slicer

**Comment by Deathfeast** [comment]
i have a kobra 2 plus and would love to see and monitor my printer via orca slicer as well.

**Comment by Ocraftyone** [comment]
I just looked into how the send functionality is implemented in AnyCubic's form and it looks proprietary AF. It is similar to what BBL does with their network plugin. I don't have an AnyCubic printer to do any kind of  testing or reverse engineering.

**Comment by MikeOxlong83** [comment]
And that's where this issue dies? Sad panda is sad...

**Comment by MikeOxlong83** [comment]
So in the mean time we're stuck slicing with Orca, then opening the sliced file in AnyCubic and sending it from there?

**Comment by jonathanalevi** [comment]
Following up here? They released their own orca-based slicer, with a network plugin... so we should be able to get it backwards ported into normal orca...?

**Comment by fazadaoc** [comment]
following.... it'd be nice to add anycubic compatibility to the connection.... perhaps with camera and webpage as well?

thanks

**Comment by icaras1966** [comment]
ACNext 1.3.7.3 download from Anycubic has wifi connect with email acct.
