### ISSUE TITLE
Zero/home button in the Prepare tab

### ISSUE THREAD

**Issue by szafranski** [SoftFever/OrcaSlicer#2995]
When using the slicer on the laptop with the touchpad it is not easy to "zero/home" the view of the model when you mess up the position. The orbit/rotate using touchpad is not easy.

I think that adding some simple button would be beneficial. Bottom left or right corner maybe?
Another solution: zero the view when clicking again on "Prepare" tab or something

Attaching screen shot of the issue:

<img width="1164" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/23621888/6dd951b3-97f2-4848-80a6-79c35838e9d9">

**Comment by Eldenroot** [comment]
Yes, this one! Zoom button, center, reset would be great!

**Comment by DVSVIDEO** [comment]
What's wrong with the default view menu item in the drop-down next to the file, under the view menu
Have you tried the ctrl-0 combination?

**Comment by szafranski** [comment]
> What's wrong with the default view menu item in the drop-down next to the file, under the view menu Have you tried the **ctrl-0** combination?
> 
Idk what you mean by this menu item. I can't see it.
Didn't know about ctrl-0 combination - works, thanks

> Another very simple solution is to connect a cheap USB mouse to your laptop. Is the programmer solving your problem when you can solve it? Sorry, but I'm pissed off by the attitude of today's society: always looking to the other guy for the solution, and less and less thinking...

Constructive feedback is another way of helping open source projects. I don't have the demanding attitude  in what I wrote and I reported few issues already. Devs were actually very ok with this so...
And "just connect the mouse" sounds like "if your nvidia GPU is working poorly on Linux, just use AMD one". It doesn't work that way.

With all respect - I don't agree with most points. Nevertheless - that you for the discussion and for the first paragraph. 

Regards

**Comment by DVSVIDEO** [comment]
So you don't need this feature, because it already exists:
![wiew](https://github.com/SoftFever/OrcaSlicer/assets/96373457/dac1e277-1f33-4923-8b70-f25ca98bd79d)

**Comment by szafranski** [comment]
Thank you very much! Didn't know about it. Have a good day!

pt., 8 gru 2023 o 23:04 DVSVIDEO ***@***.***> napisał(a):

**Comment by Eldenroot** [comment]
Actually would be better to add it into the view to make is more usable :)

**Comment by Ocraftyone** [comment]
>Constructive feedback is another way of helping open source projects. I don't have the demanding attitude in what I wrote and I reported few issues already. Devs were actually very ok with this so...

I very much agree. I can't speak too much for the other contributors, but I use these suggestions the help with development ideas. We can't test all edge cases. 

As for the actual request, I could see this being beneficial and it would follow the standard set by other 3D modeling programs.

**Comment by thebigMoose** [comment]
I would very much hope the good developers would reconsider this.  IMO there should be a little house icon next to the axis logo in the bottom left of the screen to "home" the view.  I spent hours looking how to home it.  Hopefully kind input from a user who enjoys this software.
