### ISSUE TITLE
move in Z

### ISSUE THREAD

**Issue by m4sis** [SoftFever/OrcaSlicer#2996]
Good morning,

I try to lift a part on the Z axis, but it automatically falls back to the table. it's annoying for a certain type of piece where I would like it to sit entirely on a support

**Comment by Schokobecher** [comment]
IIRC this is also the case in PrusaSlicer.
You can work around it by:

1. Add a sacrificial part (Primitive) first
![CleanShot 2023-12-05 at 02 34 04@2x](https://github.com/SoftFever/OrcaSlicer/assets/1642634/02259b90-981d-496c-8caf-d656c428045a)
2. Right-Click your sacrificial part, select _Add Part_ --> _Load_ and select the file you want to print
![CleanShot 2023-12-05 at 02 39 06@2x](https://github.com/SoftFever/OrcaSlicer/assets/1642634/8ccddc68-ce48-46fc-a580-f320f29bc572)

3. Adjust the scale of the primitive to be miniscule, something like 1x1x0.2mm
4. You can now float the original object as much as you like

![CleanShot 2023-12-05 at 02 37 04@2x](https://github.com/SoftFever/OrcaSlicer/assets/1642634/93dad03c-ef12-4a53-bb67-32fe0963fe50)

**Comment by m4sis** [comment]
Thank you so much
