### ISSUE TITLE
Doesn't Show Images(table/icons/printers)

### ISSUE THREAD

**Issue by XEGARE** [SoftFever/OrcaSlicer#2997]
### OrcaSlicer Version

1.8.1 and older

### OS version

Windows 11 Pro Build 22631.2715

### Additional system information

Unnecessary

### Printer

Not selected

### How to reproduce

First Launch

### Actual results

![1701725911](https://github.com/SoftFever/OrcaSlicer/assets/28856609/4ce79847-550b-45b6-8175-b6bee91cf238)
![1701725906](https://github.com/SoftFever/OrcaSlicer/assets/28856609/25e17279-541a-4d1b-a75b-e5871d4b82aa)

### Expected results

Images must be visible

### Project file & Debug log uploads

FIX: The program breaks if there is a Cyrillic alphabet in the path of the executable files. Most likely it will break in some other languages.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Noisyfox** [comment]
Make sure the install path does not contain non-ascii characters.

**Comment by XEGARE** [comment]
> Make sure the install path does not contain non-ascii characters.

Then the program works correctly.  I think the bug will be fixed in the future.  Thank you.
