### ISSUE TITLE
Extruder pulling out more filament then its extruding

### ISSUE THREAD

**Issue by AnbuKaru** [SoftFever/OrcaSlicer#3011]
### OrcaSlicer Version

1.80-rc2

### OS version

Windows 11 

### Printer

Ender 3 Pro w/ Sprite Extruder

### How to reproduce

All I have to do is start a print and the issue is there.

### Actual results

The print will start perfectly fine but I oticed during the extrusion process the filament will back out more than its being pulled through. 

### Expected results

It should print normally.

### Project file & Debug log uploads

[debug_Mon_Nov_13_11_41_26_24204.log.zip](https://github.com/SoftFever/OrcaSlicer/files/13564385/debug_Mon_Nov_13_11_41_26_24204.log.zip)

### Checklist of files to include

- [X] Log file
- [x] Project file

**Comment by repomanz** [comment]
@AnbuKaru can you share your profile?  I have the same setup with a cr touch.
