### ISSUE TITLE
[feature] - Backup/ Export ALL config files and presets

### ISSUE THREAD

**Issue by pixel-shock** [SoftFever/OrcaSlicer#3012]
**Is your feature request related to a problem? Please describe.**
- As I am regulary exporting my configs as a backup into dropbox or whatever it would be nice to export **all** profiles, configs etc. and not just the selected/ active one. 

**Which printers will be beneficial to this feature**
- all

**Describe the solution you'd like**
- As a user I want to click on the "export configs" and I want OrcaSlicer to export all config files and profiles - like a full backup of all my created profiles.

**Describe alternatives you've considered**
- IF you're totally into my feature request, then a full dropbox/ google drive/ icloud integration would be more than I could wish 😉 

**Additional context**
- none

Best & thank you for reading this :wink:

**Comment by yourbuddydinec** [comment]
Yes please. I just noticed today that it does this. I had been exporting for months only to today find out each was only the currently selected stuff. Backups are horrible like this if you have a ton of filaments or profiles

**Comment by Ocraftyone** [comment]
This would only solve the backup problem, but you may be able to use the snapshots feature

**Comment by KondratokGK** [comment]
YEEEEEEES PLEASE!

**Comment by Furthen64** [comment]
I would love to have that feature <3

**Comment by HazzzeHunter** [comment]
Any update here ?

**Comment by Antebios** [comment]
Top search result to find out how to back up settings brought me here.  So, I don't think there is a solution?

**Comment by yourbuddydinec** [comment]
> Top search result to find out how to back up settings brought me here. So, I don't think there is a solution?

I've been using this to backup for a while. Works great though I havent used it to restore in like 6 months. 

http://ilkos-home.blogspot.com/p/orca-slicer-pm.html

**Comment by HazzzeHunter** [comment]
@yourbuddydinec  thanks works greate
