### ISSUE TITLE
"Other layers" bed temperature not working after changing settings

### ISSUE THREAD

**Issue by leoshusar** [SoftFever/OrcaSlicer#3015]
### OrcaSlicer Version

1.8.0

### OS version

Windows 11

### Printer

Klipper Generic

### How to reproduce

1. Slice something (M140 is present)
2. Change e.g. brim settings
3. Slice (M140 is missing)
4. Revert the brim settings
5. Slice (M140 is still missing)
6. Change profile
7. Slice (M140 is present again)

### Actual results

See the video:

https://github.com/SoftFever/OrcaSlicer/assets/13891066/90334718-4f9c-4c2d-b5a2-e76e64c55218

### Expected results

M140 should be present every time

### Project file & Debug log uploads

[after-issue.zip](https://github.com/SoftFever/OrcaSlicer/files/13572825/after-issue.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by nishantsnair** [comment]
I notice the same on v1.8.0

**Comment by btCRO** [comment]
I noticed if you change any speed setting in profile M140 is missing from gcode for layer 2. Reseting profile does not help but switching to another profile helps. I've tested a little on V1.8.1 and on some print settings change M140 is still generated but on some like print speed in 100% it is missing from generated gcode. This really sohud not happen.

**Comment by btCRO** [comment]
And today I found that disabling automatic brim would forgot to set M140 at second layer in 100% of situation I'we tried.

**Comment by cbaugher** [comment]
Confirmed.  Setting brim to disabled removes M140 from second layer setup.  OS v1.8.1.
Very weird.

**Comment by mralien** [comment]
Same happens with 1.9.0.
My steps:
1) Set "Other layers" temp and sliced - M140 present in gcode
2) Changed filament cost (just to reproduce, it happens with other settings too) and sliced - M140 disappeared

To make it reappear I've changed temp to new value (different from old one), closed and re-sliced, then changed back to one I need. Changing temperature like X (required one) -> Y -> X without re-slicing at Y value doesn't bring back missing M140.

**Comment by lhndo** [comment]
Confirmed, and seems to be brim related as @cbaugher said.

**Comment by vgdh** [comment]
same https://github.com/SoftFever/OrcaSlicer/issues/4676

**Comment by antonyburden** [comment]
I too have this issue on latest v.21dev

**Comment by phreshxmetal** [comment]
I also have this issue, ver 2.0

**Comment by JPR75** [comment]
Same problem with Orca 2.0.0 / Windows 11 / gcode flavor: Klipper.
I don't use brim. Most of the time the temperature change is done correctly but not always.
