### ISSUE TITLE
Add Custom GCODE to layers

### ISSUE THREAD

**Issue by rfnovo** [SoftFever/OrcaSlicer#302]
**Describe the bug**
When adding custom GCODE to a layer, it will not show that there is a GCODE there, you must hover mouse over for it to highlight the area. It will also not allow to view the GCODE, now allow you to edit it. 

**3mf File for This Bug**
Any file

**To Reproduce**
1. Slice any STL
2. In Preview tab, on the side bar, go to any layer, right click and select "Add Custom G-code"
3. Move slide bar to other layer. 
4. The layer that you add the GCODE has no indication nor mark. It only shows a small green box if you hover your mouse over the side bar

**Expected behavior**
It should display the layer with the GCODE, and allow you to edit it. Bonus points if also shows in the sliced part.

**Screenshots**
![image](https://user-images.githubusercontent.com/11941836/218224932-7db3e216-2203-4ffc-8c5a-43aea4745ef6.png)

**Desktop (please complete the following information):**
 - Windows 10
 - 1.4.4

**Comment by hliebscher** [comment]
On Mac OS, you need to go to the "Prepare" tab and then back to "Preview" in order to see the change. It could also be a problem with the graphics card driver in Windows, which is often the case.

**Comment by rfnovo** [comment]
Tried that with no improvement. Might be an issue with card driver, but Prusa and SS can show that normally.

**Comment by SoftFever** [comment]
Looks like a rendering glitch caused by the graphic driver.
![image](https://user-images.githubusercontent.com/103989404/219867680-f3f87c31-24b7-4247-90ce-9d4faf711593.png)

**Comment by vicpon** [comment]
I have the same problem on Windows. I can see the little bars that show where the custom gcode is but I can't edit/view the existing gcode.

![image](https://github.com/SoftFever/OrcaSlicer/assets/2129528/833f7adb-6876-468a-a4bc-410b25c1c54e)

**Comment by SoftFever** [comment]
@vicpon can you share the project?

**Comment by vicpon** [comment]
> @vicpon can you share the project?

[ringing_tower.zip](https://github.com/SoftFever/OrcaSlicer/files/11452485/ringing_tower.zip)

**Comment by skl111** [comment]
Is there a nightly build where this has been addressed?
