### ISSUE TITLE
Login with Google crashes OrcaSlicer

### ISSUE THREAD

**Issue by dialtone** [SoftFever/OrcaSlicer#3021]
### OrcaSlicer Version

1.8.1

### OS version

MacOS 14.1.2 (latest)

### Printer

Bambulab X1C

### How to reproduce

1. Launch OrcaSlicer
2. Install Network Plugin
3. Click on Login/Register
4. Click on Google Logo under Login with other accounts
5. Orca slicer crashes

### Actual results

Orca slicer crashes

### Expected results

Orca Slicer should log you in

### Project file & Debug log uploads

[log.zip](https://github.com/SoftFever/OrcaSlicer/files/13587203/log.zip)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by blake-tisbury** [comment]
Having the same exact issue with the P1S

**Comment by whattheflukz** [comment]
also having this isse
