### ISSUE TITLE
OrcaSlicer will terminate because of running out of memory

### ISSUE THREAD

**Issue by vdd9474a** [SoftFever/OrcaSlicer#3023]
### OrcaSlicer Version

1.8.1

### OS version

Windows 11

### Additional system information

CPU : 12th Gen Intel(R) Core(TM) i7-1260P   2.10 GHz
Memory : 32,0 Go

### Printer

Ender 3 V2

### How to reproduce

Slice a benchy

### Actual results

error message and Orca closing

### Expected results

Get a Gcode

### Project file & Debug log uploads

[log.zip](https://github.com/SoftFever/OrcaSlicer/files/13590948/log.zip)
[3DBenchy.zip](https://github.com/SoftFever/OrcaSlicer/files/13590952/3DBenchy.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by dartrax** [comment]
Is this permanent or sporadic?
If sporadic it may be related to #1919.

**Comment by RoguishlyHandsome** [comment]
this does not happen sporadically. it happens every time Orca is left running idle for a few hours. I can reproduce this every time.
