### ISSUE TITLE
Pressure Advance Pattern Calibration causes extruder to retract nearly 1000mm after the first layer is printed.

### ISSUE THREAD

**Issue by Heratiki** [SoftFever/OrcaSlicer#3031]
### OrcaSlicer Version

1.8.0-beta 1

### OS version

Windows 11

### Additional system information

Processor AMD Ryzen 7 3800X 8-Core Processor                3.90 GHz
Installed RAM	32.0 GB
GPU AMD 5700XT

### Printer

Modified Ender 3 Pro

### How to reproduce

1. Open new project
2. Use Calibration option for PA Pattern with default settings of 0 to 0.08 with 0.005 stepping and print numbers turned on. 
3. Send to printer to print.

### Actual results

Printer prints the first layer but once it gets to the cube in the bottom left of the print the extruder retracts nearly 1000mm of filament as fast as possible and then attempts to deretract the same distance after a couple of seconds effectively grinding the filament into dust as it attempts to ram it through the hotend.  Added ZIP file including 3mf and generated gcode that causes the issue.  Unable to find where it's happening but only happens with OrcaSlicer and this calibration pattern.

### Expected results

PA Pattern printed for testing.

### Project file & Debug log uploads

[Cube_PLA_10m48s.zip](https://github.com/SoftFever/OrcaSlicer/files/13600432/Cube_PLA_10m48s.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by igiannakas** [comment]
I've attempted to make a first fix at it here:https://github.com/SoftFever/OrcaSlicer/pull/3314

can you please test and revert back?
