### ISSUE TITLE
Thumbnail on K1 Max Screen Missing

### ISSUE THREAD

**Issue by bhast2** [SoftFever/OrcaSlicer#3033]
### OrcaSlicer Version

1.8.1

### OS version

Windows 11

### Printer

Creality K1 Max

### How to reproduce

Load file into OrcaSlicer
Slice File
Send to printer
The Screen just has a white box with the thumbnail use to be

### Actual results

Just a white box on the HMI screen on the printer, instead of a thumbnail.
I tried to add 96x96 to the printer settings but that didn't work

### Expected results

Thumbnail on the HMI screen

### Project file & Debug log uploads

[trineo santa FINAL 2_PLA_4h32m.zip](https://github.com/SoftFever/OrcaSlicer/files/13601913/trineo.santa.FINAL.2_PLA_4h32m.zip)

Attached gcode file and it shows the thumbnail of both the 96x96 and 300x300 but not working on the hmi screen of the printer

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by serniko97** [comment]
Hi, I tested the G-code you provided on my K1 with firmware version 1.3.2.20 and both icon and preview are displayed correctly.
I also created the pull request [#3383](https://github.com/SoftFever/OrcaSlicer/pull/3383) to add the resolution of 96x96 to the default configuration.
