### ISSUE TITLE
Internal thick bridges overlap sparse infill

### ISSUE THREAD

**Issue by Downquark7** [SoftFever/OrcaSlicer#3036]
### OrcaSlicer Version

1.8.1

### OS version

Windows 11

### Printer

Bambu Lab P1S

### How to reproduce

Set Layer Height to 0.08mm
Turn on Thick internal bridges (on by default)
Slice object

### Actual results

![image](https://github.com/SoftFever/OrcaSlicer/assets/16943073/ddf951b8-d17d-45fa-8348-0649ec979eb1)

The infill overlaps with the thick bridge causing surface defects

### Expected results

The internal infill should stop below the internal bridge instead of inside of it. Maybe the overlap doesn't cause issues at 0.2mm layer height but it causes problems on 0.08mm layer height.

### Project file & Debug log uploads

[3DBenchy.zip](https://github.com/SoftFever/OrcaSlicer/files/13604624/3DBenchy.zip)
3mf file inside of zip

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by Downquark7** [comment]
Thick internal bridges enabled makes the bridges too thick (.4mm bridge height)
Thick internal bridges disabled makes the bridges fail (.08mm bridge height)
![20231207_185335](https://github.com/SoftFever/OrcaSlicer/assets/16943073/b9b91550-61b3-4123-921d-4fdf3f068a96)
[3DBenchy side by side comparison.zip](https://github.com/SoftFever/OrcaSlicer/files/13607746/3DBenchy.side.by.side.comparison.zip)

If this is just a "I need to tune the internal bridge flow ratio" and not just a sub optimal method of calculating internal bridges please close this issue.

**Comment by Noisyfox** [comment]
![image](https://github.com/SoftFever/OrcaSlicer/assets/1537155/d1a94fee-dbfc-46e9-87f0-a07a9610e780)
Have you tried changing this value?

**Comment by Downquark7** [comment]
![image](https://github.com/SoftFever/OrcaSlicer/assets/16943073/355abd6d-a385-46c9-ac21-6078a60600bd)
I guess the bridge layer isn't the problem. It's the layer right above the bridge that is the problem.
