### ISSUE TITLE
耗材剩余的预估展示与方式

### ISSUE THREAD

**Issue by zlkent** [SoftFever/OrcaSlicer#3041]
新手，刚开始玩，用的拓竹P1SC，官方的切片软件里，用官方的耗材，可以显示耗材的剩余量，但用第三方的就无法显示剩余量，虽然拓竹的剩余量也是估值，并不准，但体验还是不错的。不知道拓竹是依靠原装耗材里的rfid来实现耗材余量的计算，还是通过什么方法。
我想了个适用所有耗材的剩余量计算方式，不仅限于拓竹和AMS。

也很简单，就是在装入新的耗材，进行初始化的时候，填入初始耗材的重量，每次打印的时候消耗的耗材去扣除。就可以计算出大概的剩余量了。当然对于拓竹的及其，还得把冲刷体积计算在内，毕竟拉的屎还是不少的。不知道拓竹切片软件在打印时估算耗材的耗材使用量是否将这部分计算在内。

进一步的，如果是耗材没打完进行更换的，还可以增加耗材编号，在设备选项卡的耗材界面，给各个耗材一个编号和名称，对于已用过耗材，直接选择，这样可以将之前消耗的量记录在这个编号里。

**Comment by HakunMatat4** [comment]
如果用中文写作，你不会得到太多帮助，出于好奇，我使用了谷歌翻译。 英语。
