### ISSUE TITLE
[Arch Linux] Bundle webkit2gtk inside of AppImage

### ISSUE THREAD

**Issue by etrigan63** [SoftFever/OrcaSlicer#3046]
**Is your feature request related to a problem? Please describe.**
The OrcaSlicer AppImage needs `webkit2gtk` as a dependency. However, the version in the Arch Linux repositories causes problems running OrcaSlicer. Content is not rendered correctly and the onboarding process is crippled. I was able to work around it by compiling and installing a patched version of webkit2gtk from the Arch User Repositories. Compiling an older version of OrcaSlicer (1.70) also worked correctly

**Which printers will be beneficial to this feature**
All printers

**Describe the solution you'd like**
Bundle the version of `webkit2gtk` used to compile OrcaSlicer inside the AppImage.

**Describe alternatives you've considered**
Patched `webkit2gtk` (specifically `webkit2gtk-imgpaste`) works
Compiling OrcaSlicer (albeit 1.70) works.

**Comment by TexZeTech** [comment]
I don't suppose you would list the contents of your patch here for the rest of us?

**Comment by probonopd** [comment]
@github-actions please reopen.
