### ISSUE TITLE
windows 7 installation 

### ISSUE THREAD

**Issue by icedhot2** [SoftFever/OrcaSlicer#3048]
what file or folder on windows 7 do i need to delete so i can reinstall version 1.80rc2 with new configuration setup? i want to do a clean setup where i can select printer. so now when i try to reinstall version 180rc2 the previous configuration shows up.

**Comment by Ocraftyone** [comment]
You will want to delete %appdata%/OrcaSlicer

**Comment by icedhot2** [comment]
thanks - got it
