### ISSUE TITLE
Slicer adding filament change gcode at start of print

### ISSUE THREAD

**Issue by 53Aries** [SoftFever/OrcaSlicer#3050]
### OrcaSlicer Version

1.8.1

### OS version

Windows 11 

### Printer

Custom klipper

### How to reproduce

Single extruder multimaterial
No purging or ramming enabled
Line 125, 126, 127 should not be there
![Screenshot 2023-12-09 015904](https://github.com/SoftFever/OrcaSlicer/assets/110708581/6f57c9c3-0329-4384-ad72-5d7673f6f65d)

![Screenshot 2023-12-09 015851](https://github.com/SoftFever/OrcaSlicer/assets/110708581/4710340e-82ae-4d65-a0bd-d228dd741910)
![Screenshot 2023-12-09 015836](https://github.com/SoftFever/OrcaSlicer/assets/110708581/047fe66c-249e-40dc-b23d-2d6c4e9b95cb)

### Actual results

After initial load the filament change gcode is called

### Expected results

No toolchange or filament change gcode should be inserted. I don't know if I'm just doing something wrong or what. 

### Project file & Debug log uploads

[Cube.zip](https://github.com/SoftFever/OrcaSlicer/files/13623351/Cube.zip)
[Cube_PLA_18m0s.zip](https://github.com/SoftFever/OrcaSlicer/files/13623353/Cube_PLA_18m0s.zip)
[log.zip](https://github.com/SoftFever/OrcaSlicer/files/13623355/log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by RayTitone** [comment]
were you able to solve this? as im having the same issue on my k1. im very new to klipper and not to sure what im doing

**Comment by 53Aries** [comment]
> were you able to solve this? as im having the same issue on my k1. im very new to klipper and not to sure what im doing

So here's what I'm doing as kinda a work around. 
![Screenshot 2023-12-09 180438](https://github.com/SoftFever/OrcaSlicer/assets/110708581/e8192794-6c07-48a4-b4c7-92f26da19434)
![Screenshot 2023-12-09 180448](https://github.com/SoftFever/OrcaSlicer/assets/110708581/82cb8bab-9042-4b3b-b598-89a4b2c76f30)
So what happens is on the print start TR will load the initial lane and use my custom purge macro. After thats done it kinda jumps around and wipes following the go to purge and wipe macros but the duplicate T(x) is ignored since it's all ready on that tool. For the next tool change everything works as it should. 
If you are using Tradrack check in the discord for my thread in the build help for more specific info. I just assume you are since you have a K1.
