### ISSUE TITLE
Weird concentric pattern lines instead of just monotonic aka lines

### ISSUE THREAD

**Issue by HakunMatat4** [SoftFever/OrcaSlicer#3079]
### OrcaSlicer Version

1.8.0 official

### OS version

Linux

### Printer

Voron Trident

### How to reproduce

1. Slice anything
2. Check the layer by layer 

### Actual results

These concentric moves shouldn't be happening, it breaks the smooth run with these small runs and extra retraction.

![20231211_173244](https://github.com/SoftFever/OrcaSlicer/assets/35049512/12ff5eed-f4c8-410b-be0a-4fa006b7d80b)

These concentric prints will break the top layer, it isn't smooth lines affecting the top layers on top of it, I mean, that section top layer looks very bad.

![20231211_173232](https://github.com/SoftFever/OrcaSlicer/assets/35049512/ef1dd1ec-eab6-43f4-8abe-9a0ba8cf155d)
![20231211_173158](https://github.com/SoftFever/OrcaSlicer/assets/35049512/4f26ea2c-2724-45fc-a2a9-7b0fd0162b0b)

### Expected results

Keep the line pattern 

### Project file & Debug log uploads

[orca.log](https://github.com/SoftFever/OrcaSlicer/files/13631809/orca.log)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by Noisyfox** [comment]
Disable this 
![image](https://github.com/SoftFever/OrcaSlicer/assets/1537155/773b3139-5849-4525-b7f6-96fdf202b616)

**Comment by HakunMatat4** [comment]
oh wow, this has been driving me nuts and I swear I do not remember enabling this.
It started showing out of the blue and I had no idea how to disable it.

Thanks a lot.
