### ISSUE TITLE
OSX - Check for Updates

### ISSUE THREAD

**Issue by pacmac** [SoftFever/OrcaSlicer#308]
Latest version of BBS, lates version of OSX.

The check for updates feature under the help menu appears to do nothing or is not working.

After selecting this, nothing is reported, but it is on the original BBS version.

**Comment by hliebscher** [comment]
if is no new softfever version than nothing to download but the softfever version not replace the BBS version !
two different apps with different config directories

**Comment by pacmac** [comment]
I mean there is no popup message saying whether there is or is not an update available, nothing at all happens.

On the official version, a message pops up saying whether or not an update is available.

**Comment by hliebscher** [comment]
the update check is completly different like org BambuStudio is like Superslicer we can check if a new version 1.4.5 is ready
