### ISSUE TITLE
Power on Klipper devices

### ISSUE THREAD

**Issue by Tutankamon00** [SoftFever/OrcaSlicer#3082]
Hi, before OrcaSlicer i used cura, and in cura are a plugin named "Connect Moonraker", it allow to power up devices configured in Moonraker.conf, for example power up printer and other device wheen the slicer send GCode, please add this very usefull feature, thank you. 
![immagine](https://github.com/SoftFever/OrcaSlicer/assets/142754987/30025844-6a20-4d1b-bf54-28705d71d0ee)

**Comment by carveitup** [comment]
I'd like to second this request. The Moonraker Power options allows you to toggle a smart switch prior to uploading a job. The printer can be set to power down once the print is complete. This is an excellent safety measure in Moonraker but it is all too easy to forget to toggle power back on before starting a print. The Cura plugin automates this nicely.
