### ISSUE TITLE
MacOS: font list in OrcaSlicer is way smaller than the font list in MacOS

### ISSUE THREAD

**Issue by netweaver1970** [SoftFever/OrcaSlicer#3083]
### OrcaSlicer Version

1.9.0-Dev

### OS version

MacOS Sonoma, 14.1.2

### Additional system information

Arm M1 - MacBookPro

### Printer

Voron 2.4, single extruder, no AMS

### How to reproduce

install now ttf (or otf) fonts on MacOS level (in my case multiple free TTF Stencil fonts, downloaded from the internet).
They are nicely visible afterwards in FontBook program
But newly added fonts are NOT visible in the OrcaSlicer list of fonts to be used for the text tool.

### Actual results

All Stencil added fonts (Post-no-Bills, Ruler Stencil and Spotlight) are not visible in OrcaSlicer.

All added fonts are validated successfully and usable (eg. Ruler Stencil) in other apps.
![image](https://github.com/SoftFever/OrcaSlicer/assets/18028618/5d52d15b-c9e7-45ab-a7d4-6b73ed0685f6)

This might be a general MacOS issue, I'm just puzzled why it only is apparant on MacOS. Is there a ways to refresh a program specific cache or something?

### Expected results

All visible fonts in Fontbook should also be visible/usable in OrcaSlicer.

![image](https://github.com/SoftFever/OrcaSlicer/assets/18028618/4741e2ff-4ff2-426f-8c1d-b1c355a4d551)

![image](https://github.com/SoftFever/OrcaSlicer/assets/18028618/ecb11c02-4c8c-4c72-9a6c-6f21526fe518)

### Project file & Debug log uploads

the project file is not relevant, as I can't even select the font needed before saving
[log.zip](https://github.com/SoftFever/OrcaSlicer/files/13636090/log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by mkorczyk** [comment]
I am having the same issue. I was able to add custom fonts to v1.6.3 but not v1.9.0 beta.  I haven't tried any versions between them though.

**Comment by NeighNeighNeigh** [comment]
having the same issue, very annoying

**Comment by netweaver1970** [comment]
in the latest official release I can see all fonts, so for the issue is gone. I don't know waht solved it, MacOS updates, some -under water- font DB fix or a newer Orca release. Anyhow, for me it can be closed.
