### ISSUE TITLE
Klipper: max_accel_to_decel is being replaced with minimum_cruise_ratio

### ISSUE THREAD

**Issue by ericderace** [SoftFever/OrcaSlicer#3084]
**Is your feature request related to a problem? Please describe.**
A breaking change is coming to Klipper - max_accel_to_decel is being replaced with minimum_cruise_ratio

**Which printers will be beneficial to this feature**
Klipper based printers

**Describe the solution you'd like**
In print profiles, add an option to enable "minimum_cruise_ratio", much like "enable max accel_to_decel".

**Describe alternatives you've considered**
The alternative is to disable max_accel_to_decel in print profiles and set minimum_cruise_ratio in the firmware (printer.cfg) or in additional printer g_code settings (SET_VELOCITY MINIMUM_CRUISE_RATIO=value) 

**Additional context**
[Klipper pull request](https://github.com/Klipper3d/klipper/pull/6418)

**Comment by dstulken** [comment]
Not stale. 

The Klipper docs state that the max_accel_to_decel parameter "is deprecated and should no longer be used".

The changes for minimum_cruise_ratio have also now been merged:
https://github.com/Klipper3d/klipper/commit/0105aa330f2a4865b01cbbc548cba1322be5371e

**Comment by dstulken** [comment]
I had thought that the stale tag would have been removed after my comment, but it seems this is not the case. Does anyone know how to get this status changed?

**Comment by vgdh** [comment]
> I had thought that the stale tag would have been removed after my comment, but it seems this is not the case. Does anyone know how to get this status changed?

maybe @SoftFever knows

**Comment by SoftFever** [comment]
Oops, I overlooked this ticket.
Replied here:
https://github.com/SoftFever/OrcaSlicer/issues/4521#issuecomment-2002295479
