### ISSUE TITLE
Overhang percentage or angle in the GCode previewer and color scheme

### ISSUE THREAD

**Issue by e-dreyer** [SoftFever/OrcaSlicer#3086]
**Is your feature request related to a problem? Please describe.**
I would like to be able to preview what the slicer calculates as the angle for overhangs. With many designs, I often design with a max overhang angle of 60°. I am however not able to always achieve this and often it is required to decrease the layer height of the slicer to reduce the number of tool paths identified as overhangs (in the dark blue preview). 

Similar to how we can preview fan speed, flow, width etc. I would like to be able to view the overhang angle or percentage of overlap that the slicer calculates. This would help with improving designs as well as provide a better direction to move to when adjusting extrusion width and layer heights to reduce the number of overhangs and improve printing.

**Which printers will be beneficial to this feature**
All printers would benefit from this. It would allow users to see the overlap of the line relative to the previous layers and know whether they should change the angle or dimensions of their design or possibly tweak layer height and extrusion widths.

**Describe the solution you'd like**
The slicer currently allows use to preview Gcode with different color schemes for flow, fan speed, layer time etc. The slicer also allows use to set the dynamic speeds and fan speeds for percentages of overhangs. Thus, it is already available by looking at the print speed, fan speed and flow and comparing this with your settings for different percentages of overhangs.

**Illustrating the problem**

On the following print, I had an interior and exterior overhang, which can be seen as a positive and negative angle. The positive exterior angle printed quite well, with small artifacts due to an excessive angle of 59°.

![20231211_211406](https://github.com/SoftFever/OrcaSlicer/assets/87576808/314b6128-e1ba-4c4d-aba1-ebd499060b0e)

The interior negative angle however, did not print perfectly, using 0.2mm layer heights here. If I reduced the layer height to 0.1mm it would print better, but as will be shown in the following images from the slicer, with 0.2mm layer heights this was not identified as overhangs.

![20231211_211347](https://github.com/SoftFever/OrcaSlicer/assets/87576808/5e9bdcc5-f856-4501-88bf-917ec243cda8)

In the following image the exterior angle is shown

![Screenshot from 2023-12-11 21-14-46](https://github.com/SoftFever/OrcaSlicer/assets/87576808/cb6db618-2cb9-411e-aa01-09dda0a16915)

The interior angle can be seen in the following image as not being rendered in blue, identifying it as an overhang.

![Screenshot from 2023-12-11 21-14-41](https://github.com/SoftFever/OrcaSlicer/assets/87576808/e2b80b15-7835-4d16-b573-8f8797fc6fe8)

As this was printed with PLA, using the fan speed to see overhangs is useless as I used 100% fans and the dynamic fan speed for overhangs isn't used as 100% fan speed was used everywhere. I also had the part positioned close to and aligned with my auxiliary fan of my Creality K1, which is similar to the one available on the X1C and P1S.

![Screenshot from 2023-12-11 21-16-26](https://github.com/SoftFever/OrcaSlicer/assets/87576808/e830a788-6cc7-45bf-9331-d7a537ee385d)

Both the flow and speed previews do however allow for identification of overhangs by the slicer and can be seen in the following images.

![Screenshot from 2023-12-11 21-16-17](https://github.com/SoftFever/OrcaSlicer/assets/87576808/d472b492-9368-4ad3-a3ad-bef5ab0cd59b)

Allowing the user to preview a similar color scheme for the percentage of an overhang or overlap with the previous layer would greatly help here, because it is also possible for users to not use dynamic speeds or flow settings, which would then render similar to the fan speed preview shown previously.

![Screenshot from 2023-12-11 21-16-09](https://github.com/SoftFever/OrcaSlicer/assets/87576808/94cba878-bb32-4ad4-86a1-133d0ad5901d)

**Implementation**
I have already started to think about how to possibly implement this by using the calculation of overhang percentage used during slicing to determine the fan speed, print speed and flow and to add this as a possible color scheme which the user could use in the Gcode preview. I however am struggling to find the correct place to start working on it in the large code base of OrcaSlicer and Slic3r. From what I have found it seems that this would be done in the toolPaths module and GcodePreviewer, but I am struggling to find the starting point where the selected color scheme is applied. I was not able to find the relevant starting points in the OrcaSlicer or Slic3r source. If someone could possibly point me in the right direction, I could start to investigate this further and propose or implement a possible first solution.

**Comment by tome9111991** [comment]
I'm not sure if it's helpful for you.
But with Support Painting you can Highlight the Overhangs
![hoverhangs](https://github.com/SoftFever/OrcaSlicer/assets/57866234/40dbf150-77da-43e3-8042-817cec3dbca5)


But i like your idea +1 for this

**Comment by e-dreyer** [comment]
> I'm not sure if it's helpful for you. But with Support Painting you can Highlight the Overhangs ![hoverhangs](https://private-user-images.githubusercontent.com/57866234/291647911-40dbf150-77da-43e3-8042-817cec3dbca5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMDY2NjksIm5iZiI6MTcwMzEwNjM2OSwicGF0aCI6Ii81Nzg2NjIzNC8yOTE2NDc5MTEtNDBkYmYxNTAtNzdkYS00M2UzLTgwNDItODE3Y2VjM2RiY2E1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDIxMDYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5MDMwY2NlNTU0ZDA0NzQzNzdlODFkNDU4OTNlZTQ1MGIxMWQ1MzgzNzA3ZGE4ZTZiYTFiZjNlNzE1NjAzOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.quE6It5-a8XIUt12HwKTqj4JH1UyjsfwNekqJbgqqeI)
> 
> But i like your idea +1 for this i think is similar like my issue [prusa3d/PrusaSlicer#9783](https://github.com/prusa3d/PrusaSlicer/issues/9783)

Thanks for the tip, this is useful, but I would prefer a method of seeing the overhang percentage or angle in a color gradient manner similar to fan speeds, printing speed and flow.
