### ISSUE TITLE
Multi color model printed mid air

### ISSUE THREAD

**Issue by asychev** [SoftFever/OrcaSlicer#3088]
### OrcaSlicer Version

1.8.1

### OS version

MacOS

### Printer

P1S

### How to reproduce

Import STL, change color using fill tool, slice

![Screenshot 2023-12-11 at 21 46 47](https://github.com/SoftFever/OrcaSlicer/assets/19927701/34688d8e-7e9e-45fe-a412-f2625c9d2475)

![Screenshot 2023-12-11 at 21 38 07](https://github.com/SoftFever/OrcaSlicer/assets/19927701/6f13c106-e25f-47bd-a420-06711c68be4f)

### Actual results

Part of model printed mid air

### Expected results

Not parts of the model printed mid air

### Project file & Debug log uploads

[double-color-mid-air-issue.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/13640782/double-color-mid-air-issue.3mf.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by blownupp** [comment]
I think this may be related to #2845

**Comment by asychev** [comment]
I think this is still an issue
