### ISSUE TITLE
Feature Request for Solid Infill per specific layer

### ISSUE THREAD

**Issue by brycehoeper** [SoftFever/OrcaSlicer#31]
**Is your feature request related to a problem? Please describe.**
PrusaSlicer has an option in the Print Settings > Infill > Advanced section called "Solid infill every: ___" that allows a 100% solid infill per specific layer.  I need this to be able to print the prints that I make.

**Describe the solution you'd like**
Would you be able to add this "Solid Infill every:____" to SoftFever?

**Describe alternatives you've considered**
I don't think custom gcode would allow me to add this manually per feedback I've been given in the Bambu Lab discord

**Additional context**
Thank you

**Comment by Learoy1** [comment]
I'd love this feature too

**Comment by liftbag** [comment]
Is it possible to reopen this feature request? On some occasions it would have been useful to me.
