### ISSUE TITLE
Cannot import profile

### ISSUE THREAD

**Issue by szafranski** [SoftFever/OrcaSlicer#3101]
### OrcaSlicer Version

1.8.1

### OS version

Mac Sonoma and Windows 11

### Printer

Prusa i3

### How to reproduce

Export and import printer profile

### Actual results

Hi, I exported my profile and wanted to import this on another machine. Unfortunately it shows

![image](https://github.com/SoftFever/OrcaSlicer/assets/23621888/50c6d8ce-0e1b-49fe-81b7-1b4fc74b5111)

### Expected results

Import of settings

### Project file & Debug log uploads

[log.zip](https://github.com/SoftFever/OrcaSlicer/files/13653805/log.zip)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by skyeshadow94** [comment]
Following same issue
