### ISSUE TITLE
Internal Bridging ignores Internal Bridge Flow

### ISSUE THREAD

**Issue by ZedOud** [SoftFever/OrcaSlicer#3103]
### OrcaSlicer Version

1.8.1

### OS version

macOS 14.1.2

### Printer

FLSun v400

### How to reproduce

Set Bridge Flow to something low like 0.2
Set Internal Bridge Flow to something high like 1.0
Slice.
This also occurs when Thick Internal Bridges is enabled (though less noticeable, thus a very low Bridge Flow is needed).

### Actual results

Internal Bridges use the Bridge Flow and ignore the Internal Bridge Flow value.

In the screenshot you can see the Bridge Flow value is 0.2 and Bridges are disabled in the preview, so these skinny lines are Internal Bridges extruding with the Bridge Flow value.

### Expected results

Internal Bridges should always use the Internal Bridge Flow value.

### Project file & Debug log uploads

<img width="1904" alt="Screenshot 2023-12-12 at 8 22 03 PM" src="https://github.com/SoftFever/OrcaSlicer/assets/7321904/ed70c7be-7507-41f1-b33b-e36d72ec74ac">

[internal_bridge_flow_issue.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/13655974/internal_bridge_flow_issue.3mf.zip)

### Checklist of files to include

- [X] Project file

**Comment by igiannakas** [comment]
internal bridge flow is a multiplier over the bridge flow.
