### ISSUE TITLE
Adjust Bed Heater Temp @ Layers Heights

### ISSUE THREAD

**Issue by TechDude23** [SoftFever/OrcaSlicer#3104]
This is a sample from another slicer that works great for long prints when you can drop the bed temps at a layer height and not affect the part being printed.

![Bed Layer Temp Change](https://github.com/SoftFever/OrcaSlicer/assets/128856354/8a740b45-5ee5-4a79-be7d-75587805061a)

Thank you for all the fixes and new things Ocra Team :)

**Comment by Eldenroot** [comment]
I think it is possible already, not? At least Prusa Slicer has this, need to check Orca when I get home
