### ISSUE TITLE
OrcaSlicer crashes if PA Pattern changes are reverted 

### ISSUE THREAD

**Issue by HakunMatat4** [SoftFever/OrcaSlicer#3105]
### OrcaSlicer Version

1.8.0

### OS version

Linux Mint Cinnamon

### Printer

Voron Trident

### How to reproduce

1. Calibration
2. Pressure advance
3. PA Pattern
4. Reset all the changes applied by Orca
5. Slice

### Actual results

This is continuation of the ticket I opened ages ago, https://github.com/SoftFever/OrcaSlicer/issues/2702 , but had to close it because I seem to be the only one seeing the problem with this.

OrcaSlicer should not make unnecessary changes, it should use the user profile as it is to print this calibration.
Any attempt to reset the changes forced by it, crashes the slicer.

![Peek 2023-12-13 18-09](https://github.com/SoftFever/OrcaSlicer/assets/35049512/49b737d6-c590-44a5-b032-acc9c629027a)

### Expected results

1. First of all don't crash. 
2. Second, do not make unnecessary changes. It was a copy and paste from Ellis website and if It cannot use my profiles, there is no point in using OS PA Pattern. Access https://ellis3dp.com/Pressure_Linear_Advance_Tool/ manually set my profile and call it a day.

### Project file & Debug log uploads

[debug.log](https://github.com/SoftFever/OrcaSlicer/files/13657568/debug.log)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by silence48** [comment]
can you upload your crash log?
