### ISSUE TITLE
umlauts are not replaced

### ISSUE THREAD

**Issue by Avatarsia** [SoftFever/OrcaSlicer#3109]
### OrcaSlicer Version

1.8.1

### OS version

win 11, linux, nevermind

### Printer

never mind

### How to reproduce

use a stl called like körper.stl and slice it

### Actual results

the printer will instant pause  and the resume will show the error Unknown g-code state: PAUSE_state

### Expected results

if you edit the printfile you will see that the data for the exclude object part still have an ö in the name instead of an o like in the file name, after replacing these leters it just prints fine

### Project file & Debug log uploads

there is no log event visible

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by cottec** [comment]
I can confirm the same behaviour!
No prints startable with umlauts in the filename!

**Comment by Avatarsia** [comment]
Still up to date with 2.0

**Comment by DrPacemaker** [comment]
Still exists in v2.2.0

**Comment by Avatarsia** [comment]
> Still exists in v2.2.0

the only solution so far is to update python
