### ISSUE TITLE
Max Build Volume Height Not Calculated Correctly After Rotating

### ISSUE THREAD

**Issue by niveus** [SoftFever/OrcaSlicer#3110]
### OrcaSlicer Version

1.8.1

### OS version

Mac OS 14.2

### Additional system information

N/A

### Printer

Creality K1 Max

### How to reproduce

The max printable height check doesn't recalculate after rotating an object. I created a test box with a height of 300 mm (for my K1 Max). When the object is exported from Fusion with the flat face down, Orca will allow slicing. If I export the object rotated so that the max height exceeds 300mm, but then rotate in Orca so that the face is down, Orca doesn't recalculate the max volume height and won't allow it to be sliced.

1. Import box_300 and note that the Slice button is activated
2. Import box_300_skew, plant the box on a small side so the height is 300mm. Note the error around max volume height

<img width="1062" alt="Screenshot 2023-12-13 at 8 19 32 AM" src="https://github.com/SoftFever/OrcaSlicer/assets/753429/2f136f72-6d3f-4e96-9515-69fa30bf4650">

### Actual results

Will not allow slicing

### Expected results

Should allow slicing

### Project file & Debug log uploads

I didn't include the logs since it's so easy to reproduce. LMK if you need the logs. 

[box_300.zip](https://github.com/SoftFever/OrcaSlicer/files/13663229/box_300.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by ljohnso16** [comment]
Same problem on newest 1.9 windows 10. I was able to save project and open project in BBLS and slice just fine.

**Comment by lukehags007** [comment]
Same problem

**Comment by DrewJensen1** [comment]
Same problem also on the Windows 1.9 version. Potential fix by manually adjusting slicer max build height for printer but unclear of potential effects that could have printer side.

**Comment by Aurik23** [comment]
same isse here with BL P1S
- object height: 245mm
- same project possible to slice in BL Studio
![image](https://github.com/SoftFever/OrcaSlicer/assets/157401361/259ec745-aca8-4a3d-9e43-c40326e0115d)

**Comment by Blogshot** [comment]
Same problem here. 

It's noteworthy that the prime tower visualizes the issue pretty good, it seems that my ~200mm height gets calculated to around 350mm:
![image](https://github.com/SoftFever/OrcaSlicer/assets/15980143/1ca6acfc-8703-4b17-8b38-ddf9b0639dd5)
