### ISSUE TITLE
appImage not working on Kubuntu

### ISSUE THREAD

**Issue by flokosx** [SoftFever/OrcaSlicer#3113]
### OrcaSlicer Version

OrcaSlicer_Linux_V1.8.1

### OS version

Kubuntu 22.04

### Additional system information

Sistema operacional: Kubuntu 22.04
Versão do KDE Plasma: 5.24.7
Versão do KDE Frameworks: 5.92.0
Versão da Qt: 5.15.3
Versão do kernel: 6.2.0-39-generic (64-bit)
Plataforma de gráficos: X11
Processadores: 8 × Intel® Core™ i3-10105 CPU @ 3.70GHz
Memória: 7,4 GiB de RAM
Processador gráfico: Mesa Intel® UHD Graphics 630

### Printer

Creality Ender 3 S1 Pro

### How to reproduce

Click in appImage  OrcaSlicer_Linux_V1.8.1.AppImage doesnt occur nothing

### Actual results

Nothing occurs

### Expected results

run the appImage

### Project file & Debug log uploads

No log

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by mfraser** [comment]
Try running it from inside Konsole, I think you need to install a dependency.
`sudo apt install -y libwebkit2gtk-4.0-37 `

**Comment by flokosx** [comment]
Works! Thanks!
