### ISSUE TITLE
Ability to turn off mouse scrolling over layer control sidebar

### ISSUE THREAD

**Issue by npoulos** [SoftFever/OrcaSlicer#312]
**Is your feature request related to a problem? Please describe.**
Request - Currently, after you slice and preview, if you scroll your mouse over the right side bar where you can choose a layer, it scrolls through the layers. While this is useful, on a mac with a touchpad it's almost impossible to right click (2 finger click) to add gcode to certain layers as when you 2 finger over the area it scrolls a couple of layers.

Can you please give the ability to turn off this "change layer on mouse scroll"

this thing VV
<img width="87" alt="image" src="https://user-images.githubusercontent.com/58903683/218741159-b99f1fe1-354f-4675-b465-67b4bfad754d.png">

**Describe alternatives you've considered**
disable 2 finger right click on mac but that feels so unnatural!

**Comment by hliebscher** [comment]
is this in org BambuStudio the same?
