### ISSUE TITLE
"Create Filament" tab is missing 

### ISSUE THREAD

**Issue by Eldenroot** [SoftFever/OrcaSlicer#3135]
### OrcaSlicer Version

1.9.0nightly

### OS version

Win11 64bit

### Printer

A1 mini

### How to reproduce

Filaments settings page - tab "Create filament" is missing. It is present in Bambulab studio.

![image](https://github.com/SoftFever/OrcaSlicer/assets/778890/286da153-a61b-45ca-a632-8a536de5b8a2)

### Actual results

![image](https://github.com/SoftFever/OrcaSlicer/assets/778890/1a3249b6-507e-43db-ab67-e89ab44fb807)

### Expected results

![image](https://github.com/SoftFever/OrcaSlicer/assets/778890/f73d94d2-fa3d-442e-9f7f-ea01c3f5efc5)

### Project file & Debug log uploads

---

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Eldenroot** [comment]
When you create a new filament - it is displayed like this in Bambulab studio - I really like this 
![image](https://github.com/SoftFever/OrcaSlicer/assets/778890/c14d46ad-9fae-497a-8c60-79b0596bc993)

**Comment by SoftFever** [comment]
Thanks for reporting the issue.
Fixed.

**Comment by Eldenroot** [comment]
Thx
