### ISSUE TITLE
Hide G-Code viewer (hide/show button)

### ISSUE THREAD

**Issue by Eldenroot** [SoftFever/OrcaSlicer#3136]
**Is your feature request related to a problem? Please describe.**
Add collapsive or show/hide button for G-code viewer

![image](https://github.com/SoftFever/OrcaSlicer/assets/778890/305a432e-3848-4fb5-9643-9509d9e212e6)

**Which printers will be beneficial to this feature**
All

**Describe the solution you'd like**
Add an ability to hide/display G-code viewer

**Describe alternatives you've considered**
Now it is sometime annoying and it takes a lot of space.

**Additional context**
---

**Comment by TechDude23** [comment]
Hello, 

You can turn it off in the left corner, they have a drop down arrow select preferences and uncheck it.
 
It was removed in the new beta 1.9.0 dev. I don't know why it is not an option anymore, maybe causing problems ?

**Comment by Eldenroot** [comment]
Yes, I know. In 1.9dev there is no button anymore

@SoftFever @Noisyfox

**Comment by darco415** [comment]
Im on 1.9 dev 1212 and its there

**Comment by Eldenroot** [comment]
Where please, cannot see it :(

**Comment by Noisyfox** [comment]
Press C to toggle the viewer, or use the view menu.
