### ISSUE TITLE
Ellis PA calibration has dangerously bugged extrusion

### ISSUE THREAD

**Issue by Habag111** [SoftFever/OrcaSlicer#3154]
### OrcaSlicer Version

1.8.1

### OS version

Windows 10

### Printer

Ender 3 v2 with klipper

### How to reproduce

Use pressure advance calibration pattern (I used start 0, end 0,46, step 0,02) and "use relative E distances" disabled. with it enabled the issue still arises, but is less noticeable

### Actual results

at the end of the first layer when the pattern ends and the cube next to it is being printed, a "G92 0" command isn't issued (which results in the filament being retracted a long way, in my case 480 units). Then, after the cube is finished, a "G92 0" is issued, BUT the E distance that was used in the pattern before the cube is still used, which results (in my case) in a request for 480 units of E, which is impossible and makes the extruder skip. edit: tested it on a different pc with a different printer profile, and was able to reproduce the issue.

### Expected results

Generated Gcode has proper extrusion commands.

### Project file & Debug log uploads

[PA_bug.zip](https://github.com/SoftFever/OrcaSlicer/files/13694307/PA_bug.zip)

I included both the saved orca .3mf file, and the Gcode. the problem can be seen around the 2150 - 2250 lines of Gcode (screenshots attached)

![Orcaslicer_bug_1](https://github.com/SoftFever/OrcaSlicer/assets/80962238/cd704b10-7e59-4ab9-bd80-2e4d773c703a)
![Orcaslicer_bug2](https://github.com/SoftFever/OrcaSlicer/assets/80962238/3bd26ac6-235e-46df-9789-51f5456aefda)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by Habag111** [comment]
The issue is still present in 1.9.0 release. Screenshots with explanation attached.

![Orcaslicer_bug_update_1](https://github.com/SoftFever/OrcaSlicer/assets/80962238/272f2029-218a-4787-9c6a-90f2765b3235)

![Orcaslicer_bug_update_2](https://github.com/SoftFever/OrcaSlicer/assets/80962238/110e909e-7a4a-497c-830e-887dd128d6d7)

**Comment by igiannakas** [comment]
Hi, I have reproduced the issue. I'll try and fix it soon.

**Comment by igiannakas** [comment]
Can you try this build here: https://github.com/SoftFever/OrcaSlicer/pull/3314

**Comment by Habag111** [comment]
I haven't tried actually printing it, but looking at the generated gcode, it seems you fixed it! Thank you so much! 

Should I mark this issue as closed? I'm pretty new to github, so I'm not sure if that's whats appropriate.

**Comment by igiannakas** [comment]
yes please. However there is one more issue with it that is not related to this bug which I'm trying to fix. You're not encountering it as you have turned off the retract on layer change option

**Comment by Habag111** [comment]
Reopening because the bug is not completely fixed. 

The issue still arises, but now only on the last layer of the cube. This happens at line 3668 of the Gcode I attached as a zip. Screenshot and project file also attached. I'm using the official 1.9.1 version on win10. 

![obraz](https://github.com/SoftFever/OrcaSlicer/assets/80962238/4b517c78-a921-4707-8e8c-6dea5a8bcce7)

[PA_bug_orca_1_9_1.zip](https://github.com/SoftFever/OrcaSlicer/files/14341699/PA_bug_orca_1_9_1.zip)

**Comment by Habag111** [comment]
@igiannakas Sorry for tagging but don't want this to get lost, especially since my nozzle clogged because of the bug and I don't want anyone else to face the same problem
