### ISSUE TITLE
Custom color - HEX value

### ISSUE THREAD

**Issue by Eldenroot** [SoftFever/OrcaSlicer#3165]
**Is your feature request related to a problem? Please describe.**
Some filament prducers use HEX colors for their filaments (color), anyway I cannot add it into the database etc. I know, we can convert it but why to make it difficult?

**Which printers will be beneficial to this feature**
All, slicer based.

**Describe the solution you'd like**
Add a way to choose my own color with HEX values (
![image](https://github.com/SoftFever/OrcaSlicer/assets/778890/66296b49-76c7-4f92-a652-5ca98af55e3f)
)

**Describe alternatives you've considered**
Add a new row - add hex.

**Additional context**

**Comment by joesanford** [comment]
I'm pretty sure that color pickers are OS-specific and not part of this codebase.

**Comment by Eldenroot** [comment]
Hmm, OK, so use a 3rd library or close the issue. I am closing this :(

**Comment by joesanford** [comment]
<img width="232" alt="Screenshot 2023-12-17 at 16 25 36" src="https://github.com/SoftFever/OrcaSlicer/assets/2974073/1959caaf-666e-4433-be2f-e60430526a1a">
Or switch operating systems - it's possible on macOS.

**Comment by Eldenroot** [comment]
Nope, unfortunately SW for my work is not available for MacOS :)

Anyway thank you :)

**Comment by Eldenroot** [comment]
Well, actually I am reopening this one - because Windows 11 contains a new color picker UI; however Bambu Lab Studio/Orca slicer use the old picker in the codebase. It must be activated 

https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.colorpicker?view=winrt-20348

Then it looks like this one:
![image](https://github.com/SoftFever/OrcaSlicer/assets/778890/217300b0-85e9-4c6c-9982-98209b21c56d)

**Comment by dragoonmc** [comment]
@Eldenroot pinging you here since you marked as completed. 
I am still seeeing the old picker on windows 11. is there a way for me to change this? I did update from windows 10 to 11 so maybe that is the issue?

**Comment by ssmb212** [comment]
> Well, actually I am reopening this one - because Windows 11 contains a new color picker UI; however Bambu Lab Studio/Orca slicer use the old picker in the codebase. It must be activated
> 
> https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.colorpicker?view=winrt-20348
> 
> Then it looks like this one: ![image](https://github.com/SoftFever/OrcaSlicer/assets/778890/217300b0-85e9-4c6c-9982-98209b21c56d)

How do you activate the new color picker for orca slicer/other software etc?
