### ISSUE TITLE
Bambulab A1 (not Mini) Support/Printerprofile

### ISSUE THREAD

**Issue by CoReYeDe** [SoftFever/OrcaSlicer#3168]
Actually i cant find a possibility to import the BBL A1 Printer-Profile exported from BambuStudio (Filetype: bbscfg)
Also no predefined Profile for the new A1-Printer (not Mini)

The printer is in my bambulab-account and i find the device in the printer-list (but the Device-Information should be not correct for this modell)
![image](https://github.com/SoftFever/OrcaSlicer/assets/22613068/02a44512-cf27-4b21-8a5b-00952a150190)

But the control for material of the AMS-lite is also not functional (Filament cannot chosen)
![image](https://github.com/SoftFever/OrcaSlicer/assets/22613068/99fc112c-5fa7-48b1-a8dc-084eb9218b1d)

Is a Update planned with this Profile or how can i get Support for this Printer in OrcaSlicer <3

Thanks

**Comment by Eldenroot** [comment]
Orca needs to merge latest version 1.8.2 of Bambu lab studio... few commits, so I think it will happen soon :) I hope so, because A1 is on the way to my home :D

**Comment by ForsakenHarmony** [comment]
Just got mine and was hoping OrcaSlicer already supported it.
Well, soon :tm:

**Comment by Eldenroot** [comment]
Already supported, download nightly build

**Comment by ForsakenHarmony** [comment]
@Eldenroot ah yes just found it, thanks

**Comment by CallmeBigfat** [comment]
@Eldenroot hey where would one find the nightly builds? also would like to use my standard A1.
