### ISSUE TITLE
Split to parts misses one of the parts

### ISSUE THREAD

**Issue by ctadlock** [SoftFever/OrcaSlicer#3169]
### OrcaSlicer Version

1.8.1

### OS version

Windows 11

### Additional system information

AMD Ryzen, 16GB

### Printer

Bambu X1C and P1S

### How to reproduce

1. Create a multi body model; in my example I have a base model "spacer" with embossed text that has been filled in to with another body "text". 
2. In the slicer, "split to parts" or "split to objects"
3. Look at the parts the slicer detected

![image](https://github.com/SoftFever/OrcaSlicer/assets/1539397/3b63ae57-d90f-44ca-894c-2fb24eb2529f)

### Actual results

The slicer does not detect one of the bodies. This is not an issue with the actual model. Opening the exported stp file directly shows the appropiate solid bodies. The slicer seems to not detect either the first or last one. I have proven this by creating a test where I add another solid body "test" with the same embossed design; in this case it got the text bodies fine but not the new test body.

![image](https://github.com/SoftFever/OrcaSlicer/assets/1539397/17814b8f-d353-4884-940e-10e3fba00c45)

![image](https://github.com/SoftFever/OrcaSlicer/assets/1539397/caf7c219-d909-4e50-8868-66858a17dcc9)

### Expected results

The slicer should detect all solid bodies. 

This is a relatively new bug in the last couple releases. I have printed this same part many times before without issue until recently. 

### Project file & Debug log uploads

[roller_spacer_10_test.zip](https://github.com/SoftFever/OrcaSlicer/files/13697837/roller_spacer_10_test.zip)

### Checklist of files to include

- [x] Log file
- [x] Project file

**Comment by ctadlock** [comment]
Here is a clue to where the bug is. If I dont make the body fill in the emboss fully, but leave it recessed then the slicer properly detects it. 

![image](https://github.com/SoftFever/OrcaSlicer/assets/1539397/e9855250-fe46-48df-b0ca-c2a78f0e852e)

**Comment by ctadlock** [comment]
Same issue with BambuStudio 1.8.2

![image](https://github.com/SoftFever/OrcaSlicer/assets/1539397/54472843-333d-442a-9c15-9ef98927ed17)

**Comment by ctadlock** [comment]
If I repair the model in the slicer, it removes the "part".

![image](https://github.com/SoftFever/OrcaSlicer/assets/1539397/d586db2f-f6b4-4e92-901e-8a708d237840)

**Comment by EricCraigen** [comment]
I am having this issue with multi-body models too.

**Comment by mark-schuler** [comment]
Same here.

**Comment by avxmw** [comment]
Same problem here. I'm having tool holders which are supposed to be labeled on both sides, however on body is always missing.

When I label them 6/6 (left/right side) i only get 6 on one side, if I label them 23/23 I get 23/2 which leads me to assume there is an off-by-one error in processing bodies not actually an identification problem.
