### ISSUE TITLE
Feature Request: Calibration of purge amounts for color/material change

### ISSUE THREAD

**Issue by Robbvious** [SoftFever/OrcaSlicer#317]
Don't know if it's possible, but is there a way to add a calibration function to determine purge amounts for different colors / materials?  For example, I like to use one color PLA for Supports, PETG For Support interfaces, and a 2nd color PLA for the main part.  I feel like I'm wasting a metric tonne of filament using the slicer suggested amounts and even my guesses are too much.

**Comment by macminoz** [comment]
would be also great avoid any type of purge and so getting a melted color in between of layers especially when the precision is not an issue
