### ISSUE TITLE
Bambu lab X1C. When sending a print job, progress gets stuck at 10% on some models

### ISSUE THREAD

**Issue by FillPavS** [SoftFever/OrcaSlicer#3171]
### OrcaSlicer Version

1.9.0-dev (Fixed a regression that non spiral vase mode was broken. #3091)

### OS version

Windows 10

### Printer

Bambu lab X1C

### How to reproduce

Open the slicer, load the attached model or project, slice, send for printing

### Actual results

Progress gets stuck at 10%. You can wait forever, but nothing happens. If you do the same in the earlier version (dated 09 Dec 23 (~~Port Emboss & SVG gizmo from PrusaSlicer (https://github.com/SoftFever/OrcaSlicer/pull/2819)~~) (Fixed a bug that caused curled edge detection not to work as expected… (https://github.com/SoftFever/OrcaSlicer/actions/runs/7150314111)), then everything works as it should.
![Снимок экрана (150)](https://github.com/SoftFever/OrcaSlicer/assets/17209082/77e7e38d-854e-4de5-9d69-e1c0d61b3136)

### Expected results

This should work

### Project file & Debug log uploads

[log.zip](https://github.com/SoftFever/OrcaSlicer/files/13699679/log.zip)
[project.zip](https://github.com/SoftFever/OrcaSlicer/files/13699683/project.zip)
[model.zip](https://github.com/SoftFever/OrcaSlicer/files/13699687/model.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by FillPavS** [comment]
Initially, I made a mistake in determining the version where everything worked and was able to determine the version where it did not work.
Work in - Fixed a bug that caused curled edge detection not to work as expected… https://github.com/SoftFever/OrcaSlicer/actions/runs/7150314111
Doesn`t work in - Port Emboss & SVG gizmo from PrusaSlicer (#2819) and later
Both versions from December 9

**Comment by Noisyfox** [comment]
Will take a look.
