### ISSUE TITLE
Orca Slicer crashes on calibration

### ISSUE THREAD

**Issue by OoSTARTERoO** [SoftFever/OrcaSlicer#3174]
### OrcaSlicer Version

1.8.1

### OS version

Windows 11

### Additional system information

CPU: Ryzen 5 5600x
RAM: 32GB
GPU: 6900xt

### Printer

Klipper

### How to reproduce

1. in Calibration > Temperature > load the temperature tower
2. While temperature tower is loaded go to Calibration > Flow rate > then Save pop-up opens
3. click Cancel
4. error pops out

### Actual results

![image](https://github.com/SoftFever/OrcaSlicer/assets/20850618/a0518873-f0fe-4699-8196-384b68554a87)
Error pops out and orca slicer closes

### Expected results

it should not load the flow rate calibration at all.

### Project file & Debug log uploads

it is unrelated to project file
[crash_Mon_Dec_18_17_30_13_0.log](https://github.com/SoftFever/OrcaSlicer/files/13701340/crash_Mon_Dec_18_17_30_13_0.log)
[crash_Mon_Dec_18_17_28_34_0.log](https://github.com/SoftFever/OrcaSlicer/files/13701342/crash_Mon_Dec_18_17_28_34_0.log)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by silence48** [comment]
Likely relationship with issues #2921 #3375 #3157 #3340 #3292 #2896 #2766 #2888 #3174 Am trying to map all the issues, I left my comments in #2921 as it was the first one I found.  Have also been trying to discuss it on discord.
