### ISSUE TITLE
Move X/Y Compensation to Filament settings

### ISSUE THREAD

**Issue by Prutsium** [SoftFever/OrcaSlicer#320]
Would it be possible to have the X-Y Compensations settings under the Filament settings?
As Shrinkage is often Filament dependent and those settings would make more sense under filament settings.

![image](https://user-images.githubusercontent.com/42968695/219463429-ec9ab619-94b7-48e3-af75-4a301c37f378.png)

**Comment by hliebscher** [comment]
you can add a profile for PLA or ABS it works for me and some models need no hole compensation and the compensation depends some times at other parameter
