### ISSUE TITLE
Fuzzy skin inside problem

### ISSUE THREAD

**Issue by QoooQ** [SoftFever/OrcaSlicer#3200]
### OrcaSlicer Version

1.8.1

### OS version

windows 10 64bit

### Additional system information

i7 12700k
32gb
3060ti

### Printer

bambu lab p1s

### How to reproduce

0.4nozzle 0.2hight layer 3top 3 bottom 15%infill use fuzzy skin contour 0.8distance 0.3thickness

### Actual results

Why is there fuzzy skin  inside?  use fuzzy skin contour 0.8distance 0.3thickness

### Expected results

![o1](https://github.com/SoftFever/OrcaSlicer/assets/19821401/34814bda-66b4-463e-ba0b-1a5e512bbf32)
![o2](https://github.com/SoftFever/OrcaSlicer/assets/19821401/b4b5b3e0-da1b-419a-99c1-42cca770bede)

### Project file & Debug log uploads

[v2_profile200 orca.zip](https://github.com/SoftFever/OrcaSlicer/files/13721609/v2_profile200.orca.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by Noisyfox** [comment]
Because the parts you highlighted are contours, due to the opening on the side.
