### ISSUE TITLE
Minor Typo When Adding Text: "dowm" Should be "down"

### ISSUE THREAD

**Issue by PAughey** [SoftFever/OrcaSlicer#3204]
### OrcaSlicer Version

1.8.0 

### OS version

Macbook Sonoma 14.1.2

### Additional system information

N/A

### Printer

Bambu X1C

### How to reproduce

Click on Paint, Add Text, hover over the Keyboard on the bottom-left. Pop-up will say "Shift + Mouse move up or dowm: Rotate text" where the word "down" is misspelled with an "m".

### Actual results

Pop-up misspells the word "down" as "dowm".

### Expected results

"down" correctly spelled with an "n" rather than an "m".

### Project file & Debug log uploads

N/A

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by igiannakas** [comment]
This has been resolved in 1.9, mostly because the panel has been completely re-done. You can get the latest version here:
https://github.com/SoftFever/OrcaSlicer/actions
