### ISSUE TITLE
extrusion rate smoothing not taken into acount when print sequence is  in object mode

### ISSUE THREAD

**Issue by jlo1975** [SoftFever/OrcaSlicer#3208]
### OrcaSlicer Version

1.8.1

### OS version

win10

### Additional system information

i5-6500
32 GB
gtx-1070

### Printer

P1S

### How to reproduce

1-create a new project
2-add the orca cube
3-in speed tab set extrusion rate smoothing to 100
4-click slice switch to flow view and take a screenshot you will see the smooting if effectively here
5-go to prepare tab and set print mode to object
6-click slice and take a screenshot you will see the smoothing is not here
and it is exactly the same result like we didn't set the extrusion rate smoothing

### Actual results

print by layer+extrusion rate smoothing to 100
![image](https://github.com/SoftFever/OrcaSlicer/assets/154452786/8788bf3c-acfe-49bd-9527-bef25c2287fe)
print by object+extrusion rate smoothing to 100
![image](https://github.com/SoftFever/OrcaSlicer/assets/154452786/ac4d7bf4-f5d6-4a22-867b-9f6a74143d8a)
extrusion rate smoothing not activated
![image](https://github.com/SoftFever/OrcaSlicer/assets/154452786/407b2155-e886-45ce-8b84-3b9986dfd009)

### Expected results

rate smoothing should be activated when printing in object mode 

### Project file & Debug log uploads

[bug-OrcaCube.zip](https://github.com/SoftFever/OrcaSlicer/files/13729763/bug-OrcaCube.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by igiannakas** [comment]
I'll take a look at it tomorrow and see if I can fix this.
