### ISSUE TITLE
1.9 Dev - TUTK logs 

### ISSUE THREAD

**Issue by igiannakas** [SoftFever/OrcaSlicer#3209]
### OrcaSlicer Version

1.9

### OS version

Mac Sonoma

### Printer

X1 Carbon

### How to reproduce

Open the app, watch as TUTK logs are created.

![image](https://github.com/SoftFever/OrcaSlicer/assets/59056762/dcce12be-04d2-49ad-b2e2-28643a20c95d)

### Actual results

Logs created in the applications directory

### Expected results

No logs

### Project file & Debug log uploads

N/A

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by gitbreiti** [comment]
I have the same "error" with version 1.8.1 as soon as the camera in the slicer is activated. The log files end up on the desktop.
