### ISSUE TITLE
There is a way to completely eliminate the visible seam.

### ISSUE THREAD

**Issue by vgdh** [SoftFever/OrcaSlicer#3211]
**Is your feature request related to a problem? Please describe.**
# Hide the Seam Completely
## Explanation
Every closed loop will eventually have a visible seam. However, if there is no specific point where the line ends, there is no seam, right?
1. Begin the line with a height of 0 and gradually increase the height of the nozzle and the line over some length until it reaches the full height of the line.
2. Move through the loop until reaching the end of the line, but continue extruding the filament due to the initial zero line height. Systematically reduce the line's height while maintaining the same nozzle height until reaching the end of the starting slope.
3. Move on to the next perimeter or infill.

That's it. The algorithm is remarkably simple, though the result is astonishingly good. 
It is not an easy task to post-process already existing GCODE files, but if it works at the slicer level, it will work very well.

## The python code
The repository includes an [example](https://github.com/vgdh/seam-hiding-whitepaper/blob/main/main.py) demonstrating a basic implementation of the algorithm for printing a ring. This implementation allows specifying parameters such as the number of lines in the ring, layer height, line width, speed, etc.

Also there is an [example](https://github.com/vgdh/seam-hiding-whitepaper/blob/main/nozzle%200.4%20line%200.3x0.8.gcode) of gcode file for 0.4 nozzle line 0.3x0.6 layer height 0.3

## Photos of the Seam Details on the Printed Example.
The first layer (the top on the first photo) was printed without the algorithm to get better adhesion.
![botom 2](https://github.com/vgdh/seam-hiding-whitepaper/assets/15322782/a429c68b-1711-44fb-9c97-4f046763b9d3)
![botom 3](https://github.com/vgdh/seam-hiding-whitepaper/assets/15322782/f1ebe624-44af-4e7e-a7a7-aa55142d8ca1)
![photo_1_2023-12-20_16-13-32](https://github.com/vgdh/seam-hiding-whitepaper/assets/15322782/e4982fe6-1fb4-4d81-90e3-9ea5f6d95e3b)

In the photo below you can see there is no gap between the lines.
![top 1](https://github.com/vgdh/seam-hiding-whitepaper/assets/15322782/fbca6b12-d2ec-416c-ae08-4e37baf869fd)
![side 1](https://github.com/vgdh/seam-hiding-whitepaper/assets/15322782/dd3a2900-39af-4baa-b638-91ef0328c86e)
![botom 1](https://github.com/vgdh/seam-hiding-whitepaper/assets/15322782/a96b0b4b-1658-4c4a-a8d8-b70bbde8845e)
![center 1](https://github.com/vgdh/seam-hiding-whitepaper/assets/15322782/2989402c-cd03-430e-9bf3-4ee902ee383f)
![top 2](https://github.com/vgdh/seam-hiding-whitepaper/assets/15322782/bdfca30b-73c2-4045-b297-a6454080ec01)

**Which printers will be beneficial to this feature**
all the community

**Comment by vgdh** [comment]
printed on the cheapest kingroon kp3s

**Comment by Eldenroot** [comment]
Nice idea :)

**Comment by TheBest6337** [comment]
This could be game changing! Idk how well it could work on smaller things and not smooth shapes but it would be nice to have an implementation to test.

**Comment by Noisyfox** [comment]
One possible issue I could think of is the nozzle clearance, since you'll have to lower the z every time you start printing an outer wall.

**Comment by PrimeGoat** [comment]
How does this differ from the spiral vase?

**Comment by vgdh** [comment]
I have written some post-processing [script](https://github.com/vgdh/seam-slope-postprocessor/blob/main/postprocessor_seam_slope.py). Feel free to test, modify, or contribute.

**Comment by DVSVIDEO** [comment]
> Hogyan különbözik ez a spirális vázától?



> How does this differ from the spiral vase?

In that the spiral vase mode can only print a single object that returns to itself within the slice. So an object branching into two separate branches cannot be created with a single line.
This method works for any number of objects.

**Comment by SoftFever** [comment]
This is pure genius!

**Comment by Eldenroot** [comment]
This could be a game changer

**Comment by Noisyfox** [comment]
https://github.com/Noisyfox/seam-slope-postprocessor/tree/dev/better-orca-support

I've made a version that should be (mostly) usable with Orca as a post-processor script, with the following requirements:

- Arc fitting: off
- Wipe distance: 0
- Z hop when retracting: 0
- Disable set remaining time
- Seam gap: 0

This script is still very prototype, use at your own risk!

**Comment by Eldenroot** [comment]
Omg cool! Good job!

**Comment by vgdh** [comment]
Now the script processes only the outer perimeters, printing the inner ones as usual.

**Comment by vgdh** [comment]
bender likes it very much 😁
![1704131531564](https://github.com/SoftFever/OrcaSlicer/assets/15322782/9817c41a-3db7-47e6-822b-9e91e1510895)
![1704131531621](https://github.com/SoftFever/OrcaSlicer/assets/15322782/b32e5164-1831-4819-afbf-4aca952e0c18)

**Comment by Eldenroot** [comment]
Wau!

**Comment by Noisyfox** [comment]
Looks promising, will give it another shot tonight.

**Comment by Eldenroot** [comment]
Did you try and did you get better results?

**Comment by Noisyfox** [comment]
Yeah and I still got that over extrusion on overhangs... Maybe something wrong with my PA.

**Comment by Eldenroot** [comment]
Ouch, not good :( because this  would be a huge step forward in FDM printing world. 

@vgdh - do you have any idea?

**Comment by Noisyfox** [comment]
I've successfully integrated this into the slicer itself:

![91469be21465a5b9f2c8e272996dc391](https://github.com/SoftFever/OrcaSlicer/assets/1537155/4bffe435-f155-4dbb-9e41-1c5eb9d0dd31)

**Comment by Eldenroot** [comment]
Amazing!

**Comment by superfloh247** [comment]
please push a PR - I want to test this!

**Comment by Noisyfox** [comment]
Ok the PR is raised.

**Comment by superfloh247** [comment]
git fetch origin pull/3839/head:pr3839
git checkout pr3839
./build_release_macos.sh -t 14.2

correct?

is this new feature activated by default or how do I switch it on?

**Comment by Eldenroot** [comment]
Just download the build from PR

**Comment by vgdh** [comment]
> git fetch origin pull/3839/head:pr3839 git checkout pr3839 ./build_release_macos.sh -t 14.2
> 
> correct?
> 
> is this new feature activated by default or how do I switch it on?

[win pr artifact](https://github.com/SoftFever/OrcaSlicer/actions/runs/7675961229/artifacts/1199247257)

**Comment by vgdh** [comment]
This feature in now implementing by OrcaSlicer: https://github.com/SoftFever/OrcaSlicer/pull/3839
Feel free to participate.

**Comment by dstulken** [comment]
Thank you!

**Comment by vgdh** [comment]
> Thank you!

You are welcome! ❤️
