### ISSUE TITLE
inner-outer-inner/infill missing in UI dropdown

### ISSUE THREAD

**Issue by superfloh247** [SoftFever/OrcaSlicer#3217]
### OrcaSlicer Version

401ac1a

### OS version

MacOS 14.2.1

### Printer

Bambu P1P

### How to reproduce

click on dropdown

### Actual results

<img width="410" alt="Bildschirmfoto 2023-12-21 um 08 56 48" src="https://github.com/SoftFever/OrcaSlicer/assets/26180993/512c8f9f-68f1-45ec-a6bf-329e7f0d9afb">

### Expected results

<img width="414" alt="Bildschirmfoto 2023-12-21 um 08 56 15" src="https://github.com/SoftFever/OrcaSlicer/assets/26180993/a6a3f6c4-0f05-40e2-ae7e-eb7f980764c5">

### Project file & Debug log uploads

n/a 

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by Eldenroot** [comment]
This was changed in https://github.com/SoftFever/OrcaSlicer/pull/2962

Maybe some regression?

@igiannakas

**Comment by igiannakas** [comment]
No, this is deliberate. If you want infill first tick the box right under the wall order. Ported from BBL slicer a while ago.
