### ISSUE TITLE
Strange Diagonal Line at 50% of the print

### ISSUE THREAD

**Issue by MrBlonde1989** [SoftFever/OrcaSlicer#3219]
### OrcaSlicer Version

1.8.1

### OS version

Windows 11 23H2

### Additional system information

CPU : AMD Ryzen 7 5800X 8-Core
4x 8GB RAM DDR4 3600Mhz
Nvidia 3060 Ti

### Printer

Sovol SV06 Klipperized and enclosed

### How to reproduce

Hello everyone,

The issue occurred during the calibration of the PETG filament flow.

It seems to occur only on one layer, and I don't understand why this behavior only manifests itself halfway through the print, around 50%.

The object is still usable after printing, but at the end of the print, I noticed that there is a problem with the underlying layers. It's not catastrophic, but I wanted to understand if I'm doing something wrong in orcaslicer or if it could be a bug. I have set up the Z-hop, and it executes it in all the other steps, but for some reason, only for this particular movement, it moves flush on the piece, back and forth, creating this line. This line not only scratches the piece but also dirties the nozzle. I don't understand why it is executed. I have attached videos to help you understand better:

I tried the same model on Prusa Slicer and the issue does not occur.

Has anyone else encountered this problem?

What do you think is the best way to solve it?

### Actual results

Here is on slicer:
[https://youtu.be/fH2t155aouQ](https://youtu.be/fH2t155aouQ)

Here is the print movement:
[https://youtu.be/aUh30w97gwE](https://youtu.be/aUh30w97gwE)

there is a scretch on the fourth layer on surface of the print 
![image](https://github.com/SoftFever/OrcaSlicer/assets/62892620/1cb4bc90-066c-4e4f-855d-d5b63df94c34)

### Expected results

the fourth layer without scretch

### Project file & Debug log uploads

[Flowrate Test - Pass1.zip](https://github.com/SoftFever/OrcaSlicer/files/13740564/Flowrate.Test.-.Pass1.zip)
[log.zip](https://github.com/SoftFever/OrcaSlicer/files/13740565/log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by igiannakas** [comment]
It’s because z hop is not enabled.

**Comment by MrBlonde1989** [comment]
On my profile there are:
Printer Settings:
![image](https://github.com/SoftFever/OrcaSlicer/assets/62892620/625823e8-3afc-4c0a-9713-b12b28cb7d3b)
Filament Settings override:
![image](https://github.com/SoftFever/OrcaSlicer/assets/62892620/48900091-58c0-4de4-ba15-686dd0256d67)
at this point, where i can enabled It?

**Comment by igiannakas** [comment]
It’s disabled because your only lift z below is 0. Set it to your max print height minus your z hop height

**Comment by MrBlonde1989** [comment]
In the first place, I thank you for the support you are giving me.
I'm not sure if I understood correctly. The maximum Z position for my printer is 260 mm, with a 2mm Z-hop height when retracting. I have edited the Filament settings overrides as follows:
![image](https://github.com/SoftFever/OrcaSlicer/assets/62892620/504879ed-ae2f-49b3-a02e-a4b4b77eec95)
But it seems that nothing has changed:
![image](https://github.com/SoftFever/OrcaSlicer/assets/62892620/a2687715-4e49-4d78-b944-c7bc3908953b)
It seems that the other movements experience Z-hop, except for the diagonal line.

**Comment by igiannakas** [comment]
This is what I mean here::

set the only lift z below to 258

![IMG_2725](https://github.com/SoftFever/OrcaSlicer/assets/59056762/0ae48c76-0cbf-41fc-863a-7a5f754521e7)

edit: on second look it appears that z hop is working. You need to disable reduce infill retraction in the process - other tab.

**Comment by MrBlonde1989** [comment]
After unchecking this option, it seems to work fine.
![image](https://github.com/SoftFever/OrcaSlicer/assets/62892620/a2c6552b-eb18-458b-9087-bd8ad2ac6f16)

![image](https://github.com/SoftFever/OrcaSlicer/assets/62892620/392d23e4-8b36-4c52-b384-2c0bb4ddf1dd)

Thank you, for you support
