### ISSUE TITLE
Orca is taking extra 2h with unnecessary solid infill/shell thickness

### ISSUE THREAD

**Issue by HakunMatat4** [SoftFever/OrcaSlicer#3224]
### OrcaSlicer Version

1.9.0-dev, 1.8.1, 1.7.0

### OS version

Linux Mint Cinnamon

### Printer

Voron Trident

### How to reproduce

1. Slice the STL attached
2. Check layer by layer to see the problem

### Actual results

**NOTE**: This has been happening for some time now, it just got worse.

~2h wasted with solid infill but shell thickness is disabled.
No explanation is good enough to explain that, I usually print with 3 walls, you do not need any extra support, that is why I keep shell thickness disabled.

![image](https://github.com/SoftFever/OrcaSlicer/assets/35049512/d9aff7b9-1277-4c5d-bed3-ae3adeac8d6b)

If I enable shell thickness, it does the opposite, it partially disables those non necessary infill and takes less time to print.

![image](https://github.com/SoftFever/OrcaSlicer/assets/35049512/522ebe02-339b-40f6-b2ac-6434193eff96)

I tried to slice again and from 6h22 it changed to 6h10 so something weird is going on.
As I tried to replicate things to get the log, it went to 6h39

![image](https://github.com/SoftFever/OrcaSlicer/assets/35049512/0d3566ad-ae2f-443d-9be7-15183f2fbe7a)

The screenshots above were shared within Discord, now that I am replicating everything to open this bug report, shell thickness is finally showing what it should have done in the the first place and 30 minutes longer.
There is some logic bug going on

From 6h22 to 6h39 to 7h, this cannot be right.

![image](https://github.com/SoftFever/OrcaSlicer/assets/35049512/f083c3ec-ae88-4337-8d6a-99256dd715a5)

### Expected results

I expect no extra shell/infill to be added on its own.
It is taking an extra 2-3h to print, wasting filament and energy for no reason.

### Project file & Debug log uploads

[debug_log.txt](https://github.com/SoftFever/OrcaSlicer/files/13741866/debug_log.txt)
[Clockspring3D Torture Toaster v24.stl.zip](https://github.com/SoftFever/OrcaSlicer/files/13741870/Clockspring3D.Torture.Toaster.v24.stl.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by igiannakas** [comment]
I've replied to Discord for the above - but:
1. Two perimeters on sloped edges trigger the ensure horizontal thickness algorithm more frequently. This cannot be disabled from the GUI and it also has adverse effects on bridged surfaces so not recommended to create an option for it.
2. Enable detect narrow solid infill - it makes the print MUCH faster

**Comment by HakunMatat4** [comment]
@igiannakas I disabled detect narrow solid infill because on 1.8.1, it was generating these weird unnecessary moves/concentric.
I just noticed that 1.9.0-dev is doing the same with that feature disabled.

![image](https://github.com/SoftFever/OrcaSlicer/assets/35049512/36a1a201-f82f-4130-97da-5cdfb319ec4b)

I did a benchy test with detect narrow internal solid infill

2 Wall loops
![image](https://github.com/SoftFever/OrcaSlicer/assets/35049512/769e7839-5d76-4f3e-ab2b-a98b7a6e0e73)

2 Wall loops
![image](https://github.com/SoftFever/OrcaSlicer/assets/35049512/feb4b840-13fa-4449-b646-e6f2f51da1a4)

Conclusion: Detect narrow internal solid infill somewhat decrease the time. Not much of a difference.
Now, I have been printing 3 walls lately, everything changes.

-----

3 Wall loops

![image](https://github.com/SoftFever/OrcaSlicer/assets/35049512/f18d4257-5965-4224-9abb-546a24c8e30d)

3 Wall loops
![image](https://github.com/SoftFever/OrcaSlicer/assets/35049512/85356c57-3053-4067-a0c7-9e7b40d17d12)

Conclusion: With 3 walls, it prints 30s faster, still not a huge difference

-----

Back to the model I used to open this ticket.

3 Wall loops
![image](https://github.com/SoftFever/OrcaSlicer/assets/35049512/45b5f39e-f50a-4dbb-b281-2d6196c3fa6e)


3 Wall loops
![image](https://github.com/SoftFever/OrcaSlicer/assets/35049512/c6e9085c-c73d-4e01-9419-01a79ae436ac)

Conclusion: Not much of a difference, 20 minutes

----

Last but not least...
This big project on the backlog...

3 Wall loops: **ON/OFF looks exactly the same like if I had not changed anything**
![image](https://github.com/SoftFever/OrcaSlicer/assets/35049512/e0b2c0b4-dacb-4ff6-aee3-18d6042ab027)

2 Wall loops: **ON/OFF looks exactly the same like if I had not changed anything**
![image](https://github.com/SoftFever/OrcaSlicer/assets/35049512/7106966f-2680-4e92-bc7b-35afe3182658)

**Comment by igiannakas** [comment]
@HakunMatat4 what operating system are you running? I can send you a version with it completely disabled for testing as I’m hesitant to push a PR for this yet

**Comment by HakunMatat4** [comment]
> @HakunMatat4 what operating system are you running? I can send you a version with it completely disabled for testing as I’m hesitant to push a PR for this yet

Hey, I'm on Linux. Thank you for looking into this.
I believe "features" like this should be added as option.
My problem with "ensure shell thickness" was that I always kept it disabled. That feature was removed and added back as active.

So I always believed the time and filament used was correct only to find out ensure thickness wall was added back enabled by default. I believe I mentioned that to noisefox, no such features should be enabled by force.

Smoothing you released, users enable it by choice. 
If you ever merge the PR understanding that UI changes must be a pain, I wonder if there's a way to only trigger it under certain circumstances like +3 walls for example must be used which provides enough strength, below that follows the current logic.

idk if that makes sense, you cover both worlds that way.

**Comment by HakunMatat4** [comment]
I did a basic test and it looks awesome

I do have a question, this is your last test shared within the PR
![image](https://github.com/SoftFever/OrcaSlicer/assets/35049512/c8685d68-c72c-48ac-aefc-e67be6e4c688)

This is mine and yet, yours is like 45 minutes faster. How low are flying that printer??? haha
![image](https://github.com/SoftFever/OrcaSlicer/assets/35049512/0c228ed0-7d06-481c-8788-ec38d93e8e7c)

Back to test, Detect narrow internal solid infill seems to be working better, also, that weird direction was driving me nuts, this PR makes it to improve and got rid of that printing in the air problem.

![image](https://github.com/SoftFever/OrcaSlicer/assets/35049512/68bf5392-001c-4342-9392-80e76f9d563a)

I will do some printing soon but so far the slicer shows no problem from what I can tell. I can print 2 walls again for prototyping prints without extra stuff being added, that is the main reason I was using 3 walls, to reduce some weird stuff.

**Comment by igiannakas** [comment]
Just the standard BBL speeds with 0.2 layer height, adaptive cubic at 20% infill. The machine is indeed quick in the standard settings :)

Also suggest we move print tests to the PR itself
