### ISSUE TITLE
[FR] Add "Used filament" to Line type window

### ISSUE THREAD

**Issue by vovodroid** [SoftFever/OrcaSlicer#3239]
PrusaSlicer shows used filament amount for each line type:

![image](https://github.com/SoftFever/OrcaSlicer/assets/8691781/38b53715-c079-488d-ad17-db67c80f048e)

It's very useful for print setting optimization.

**Comment by Eldenroot** [comment]
Hi @vovodroid , I believe this one is on the todo list from @Noisyfox
