### ISSUE TITLE
Massive, random, instantaneous over extrusion when "Detect overhang walls" is checked

### ISSUE THREAD

**Issue by stromboli005** [SoftFever/OrcaSlicer#3247]
### OrcaSlicer Version

1.8.1

### OS version

Windows 11

### Additional system information

CPU: AMD Fyzen 9 7900 X
64 GB Ram

### Printer

Ender 3 V2 Neo running Klipper Mainsail

### How to reproduce

1. Load file that contains overhang perimeters
2. Click "Detect overhang walls"
3. Slice model
4. Check "Flow" under preview and see random sections of massive over-extrusion.  Look at "Line type" and see that slicer DOES detect overhang walls.
5. Look at G-code and see at point of over-extrusion that E axis instantaneously makes impossible jumps.
6. Uncheck "Detect overhang walls"
7. Slice model
8. Check "Flow" under preview and see normal extrusion rates.  Also look at "Line type" and see that no overhangs were detected.
![Screenshot 2023-12-21 194554](https://github.com/SoftFever/OrcaSlicer/assets/141848590/05a61db9-c7b2-4721-bb69-c08314a5ef59)
![Screenshot 2023-12-21 194623](https://github.com/SoftFever/OrcaSlicer/assets/141848590/7ef2a111-83d8-4129-b35a-b5e0fcf11804)
![Screenshot 2023-12-21 194649](https://github.com/SoftFever/OrcaSlicer/assets/141848590/026c3171-a1fd-4ff1-aff2-238ecc7e6007)
![Screenshot 2023-12-21 194659](https://github.com/SoftFever/OrcaSlicer/assets/141848590/603eb90b-7b5b-4acf-adcd-ca08f329f0c3)

### Actual results

G-code has segments where E axis makes massive leaps, on some models i have seen it 10,000 mm^3/s (ten thousand) or more.  I noticed it when printing a model and the printer started making terrible sounds.  I saw both extrusions and "retractions" of equally massive magnitude, the printer doing it's best to accommodate the G-code's demands. These over-extrusions do not occur at locations of overhang walls (that i've seen) it appears to be a bug that's somehow triggered by the setting but not directly affected by it, if that makes sense.  These occur sometimes once, sometimes several times in a model. Another example that i screenshot but didn't save model files of is below (note E value in G-code preview).
![Screenshot 2023-11-27 062155](https://github.com/SoftFever/OrcaSlicer/assets/141848590/dea3c962-ac35-437c-84c8-b099ce7d2a9a)

### Expected results

Slicer detects overhang walls and applies appropriate overhang adjustments, but does not affect extrusion rates of other areas of the model.

### Project file & Debug log uploads

[Little Joycon.zip](https://github.com/SoftFever/OrcaSlicer/files/13757846/Little.Joycon.zip)
[log.zip](https://github.com/SoftFever/OrcaSlicer/files/13757852/log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by najwaa-debug** [comment]
seconded. I'm getting massive retractions/deretractions with Flow going to 10K mm/s3. Issue was fixed when detect overhang walls was unchecked. On OS 1.9.

Appreciate you creating the post. Was tearing my hair out over this one.
