### ISSUE TITLE
-datadir doesn’t work

### ISSUE THREAD

**Issue by Ibot-11** [SoftFever/OrcaSlicer#325]
I use -datadir in the shortcut path to sync my profiles between multiple pcs by using my onedrive. With Prusaslicer and Superslicer this worked really well so far. But somehow I’m unable to use this with Bambustudio. It just won’t open it and nothing happens, I also tried using the Bambulab account synchronization. But this also doesn’t work.
Is there any way to get -datadir working?

**Comment by SoftFever** [comment]
Implemented in 1.5.0
