### ISSUE TITLE
[Feature Request] Add Brim Blocker

### ISSUE THREAD

**Issue by jordanlambrecht** [SoftFever/OrcaSlicer#3250]
It would be extremely useful to have a way to prevent a brim in certain areas, especially tight nooks and crannies where it's hard to get a deburring tool into.

**Comment by Eldenroot** [comment]
https://github.com/SoftFever/OrcaSlicer/issues/3131

**Comment by DVSVIDEO** [comment]
I recommend using Mouse Ear in such cases.

**Comment by Eldenroot** [comment]
B

**Comment by notsaeegavas** [comment]
> I recommend using Mouse Ear in such cases.

This didn't solve my issue as I used mouse ear brims and it sliced brims on an inner wall where I didn't want them. A brim blocker would be a great feature.

**Comment by Snuff1eupagus** [comment]
@jordanlambrecht 

Brim Blocking,

https://www.youtube.com/watch?v=6CRqNk_JUj4

Hopefully this will do the trick for you.

**Comment by MJ3Ds** [comment]
@Snuff1eupagus link is dead got a new one?

**Comment by DJDirtboy** [comment]
> [@jordanlambrecht](https://github.com/jordanlambrecht)
> 
> Brim Blocking,
> 
> https://www.youtube.com/watch?v=6CRqNk_JUj4
> 
> Hopefully this will do the trick for you.

@Snuff1eupagus vidéo is unavaillable :(
