### ISSUE TITLE
[Feature Request] Windows 11 ARM64 build

### ISSUE THREAD

**Issue by eblieb** [SoftFever/OrcaSlicer#3258]
Any chance we can get a native Windows 11 Arm64 build for Orca Slicer?

**Comment by giveen** [comment]
You could always try building it yourself?

in the build script:
https://github.com/SoftFever/OrcaSlicer/blob/main/build_release_vs2022.bat

```
echo cmake .. -G "Visual Studio 17 2022" -A x64 -DBBL_RELEASE_TO_PUBLIC=1 -DCMAKE_PREFIX_PATH="%DEPS%/usr/local" -DCMAKE_INSTALL_PREFIX="./OrcaSlicer" -DCMAKE_BUILD_TYPE=Release
cmake .. -G "Visual Studio 17 2022" -A x64 -DBBL_RELEASE_TO_PUBLIC=1 -DCMAKE_PREFIX_PATH="%DEPS%/usr/local" -DCMAKE_INSTALL_PREFIX="./OrcaSlicer" -DCMAKE_BUILD_TYPE=Release -DWIN10SDK_PATH="C:/Program Files (x86)/Windows Kits/10/Include/10.0.22000.0"
cmake --build . --config Release --target ALL_BUILD -- -m
```


change that to 

```
cmake .. -G "Visual Studio 17 2022" -A ARM64 -DBBL_RELEASE_TO_PUBLIC=1 -DCMAKE_PREFIX_PATH="%DEPS%/usr/local" -DCMAKE_INSTALL_PREFIX="./OrcaSlicer" -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="C:/Program Files (x86)/Microsoft Visual Studio/2022/Enterprise/Common7/IDE/VC/VCTargets/Platforms/ARM64/PlatformToolsets/v143/Toolchain.cmake
```

**Comment by eblieb** [comment]
Dont think I can since I dont own a copy of Visual Studios...

**Comment by giveen** [comment]
> Dont think I can since I dont own a copy of Visual Studios...

Its free, the community edition
https://visualstudio.microsoft.com/vs/

**Comment by eblieb** [comment]
I just noticed that.. Installing now and will have to update the build path since that is tied to enterprise, but will give it a try

**Comment by eblieb** [comment]
Was unable to build this. The platform tool sets isn't a thing that ever showed up. Not sure if the community version has that ability.
