### ISSUE TITLE
1.9.0 Alpha Release Bug on mac.

### ISSUE THREAD

**Issue by christianjou** [SoftFever/OrcaSlicer#3262]
### OrcaSlicer Version

1.9.0 Alpha release

### OS version

OS: MONTEREY 12.7.1

### Additional system information

at start it bug. 
<img width="641" alt="Capture d’écran 2023-12-24 à 12 56 55" src="https://github.com/SoftFever/OrcaSlicer/assets/72012052/b7e8e397-0c9b-4879-b597-33eec6915cc7">

### Printer

none

### How to reproduce

every launch

### Actual results

Bug

### Expected results

should open

### Project file & Debug log uploads

<img width="641" alt="Capture d’écran 2023-12-24 à 12 56 55" src="https://github.com/SoftFever/OrcaSlicer/assets/72012052/2ea75264-b300-4eaf-b207-5ebc7d1c0fcb">

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Noisyfox** [comment]
Will take a look soon.

**Comment by Noisyfox** [comment]
Currently you can install zstd as a workaround
`brew install zstd`

We are currently working on a proper fix.

**Comment by atl285** [comment]
Just to complete here: https://github.com/SoftFever/OrcaSlicer/issues/3099

**Comment by SoftFever** [comment]
> Just to complete here: #3099

Damn, how did I overlooked that
