### ISSUE TITLE
M486 / Label Objects not working

### ISSUE THREAD

**Issue by imh1kiko** [SoftFever/OrcaSlicer#3267]
### OrcaSlicer Version

1.9 alpha

### OS version

Windows 10

### Printer

Snapmaker A150

### How to reproduce

1. Open Orcaslicer
2. Import model, slice and print

### Actual results

Due to M486 (aka. label objects), the print won't start and will be endlessly stuck.

### Expected results

There should be an option to disable label objects.
This is a new bug/incompatibility. 1.8 worked fine.

### Project file & Debug log uploads

No file due to not needed, as confirmed by deleting
```gcode
M486 S0
M486 Avacuum_1_fix.step_id_0_copy_0
M486 S-1
```

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by imh1kiko** [comment]
So, after looking into it more, I found that the `Label Objects` doesn't seem to work?
I exported the G-code with Label Objects on, and off, then diffed the two files. M486 command does not get removed. There might be some changes, but I'll need to use a small object (because I used a file with 200k lines...).

I'll re-run the same experiment with a singular layer later to confirm it.

**Comment by SoftFever** [comment]
Looks like your firmware don't support object cancelling feature.
Let me check the second issue.

**Comment by SoftFever** [comment]
Please wait for this build: https://github.com/SoftFever/OrcaSlicer/actions/runs/7318919736
You should be able to turn off object exclusion now.
![Screenshot 2023-12-25 at 12 02 26 PM](https://github.com/SoftFever/OrcaSlicer/assets/103989404/ca29b7cf-09b9-445a-b8dd-84de731f51e3)

**Comment by imh1kiko** [comment]
The build got cancelled, but I used [latter one](https://github.com/SoftFever/OrcaSlicer/actions/runs/7318982046). This works great! Thanks for the fix!
