### ISSUE TITLE
Orcaslicer crashes when "Height Range Modifier" layer height is set to 0

### ISSUE THREAD

**Issue by Dustmuffins** [SoftFever/OrcaSlicer#3268]
### OrcaSlicer Version

1.9.0-Alpha

### OS version

Windows 11

### Additional system information

Ryzen 5600X
RTX 4070
16GB RAM

### Printer

Sovol SV06 CoreXY

### How to reproduce

1. Right click on model under "objects tab"
2. Select "Height Range Modifier"
3. Click on range
4. Set layer height to 0
5. When warning comes up, click "Ignore"
6. Orcaslicer crashes

### Actual results

Orcaslicer crashes

![image](https://github.com/SoftFever/OrcaSlicer/assets/17961638/0d3c07a8-5a4d-4196-a5a3-2b74388a580a)

### Expected results

Orcaslicer should automatically revert layer height.

### Project file & Debug log uploads

[log.zip](https://github.com/SoftFever/OrcaSlicer/files/13762832/log.zip)

This can be done on any project.

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by SoftFever** [comment]
Thank you.
We shouldn't allow user to set layer height to 0..
It has been fixed now.
