### ISSUE TITLE
MetaData still referencing BambuStudio in saved .3mf projects files and exported .gcode.3mf files

### ISSUE THREAD

**Issue by Trini8ed** [SoftFever/OrcaSlicer#3273]
### OrcaSlicer Version

1.8.0

### OS version

windows 11

### Printer

N/A

### How to reproduce

1. Create a new projects
2. Place a cube
3. Save the project
4. Open the 3mf in 7zip extra the contents
5. Inspect 3D/Objects/3dmodel.model see the following I would expect OrcaSlicer name and version
` <metadata name="Application">BambuStudio-01.07.07.89</metadata>`
` <metadata name="BambuStudio:3mfVersion">1</metadata>`

### Actual results

` <metadata name="Application">BambuStudio-01.07.07.89</metadata>`
` <metadata name="BambuStudio:3mfVersion">1</metadata>`

### Expected results

` <metadata name="Application">OrcaSlicer-1.8.0</metadata>`
` <metadata name="BambuStudio:3mfVersion">1</metadata>`

### Project file & Debug log uploads

[orcaslicer-multiplates-test.zip](https://github.com/SoftFever/OrcaSlicer/files/13764379/orcaslicer-multiplates-test.zip)

### Checklist of files to include

- [x] Log file
- [X] Project file

**Comment by DorvoG** [comment]
I also wonder why this is. 
Why doesn't OrcaSlicer say OrcaSlicer in metadata?


From a project generated in OrcaSlicer2.3.1 sliced for an Elegoo Centauri Carbon:
```
 <metadata name="Application">BambuStudio-2.3.1</metadata>
 <metadata name="BambuStudio:3mfVersion">1</metadata>
```
From a project generated in OrcaSlicer2.4.0-alpha sliced for an Elegoo Centauri Carbon:
```
 <metadata name="Application">BambuStudio-02.06.00.51</metadata>
 <metadata name="OrcaSlicer">2.4.0-alpha</metadata>
 <metadata name="BambuStudio:3mfVersion">1</metadata>
```

Apparently something has changed between versions. At least OrcaSlicer is referenced now.
Can't the BambuStudio references be removed completely when slicing for non-bambu printers?
