### ISSUE TITLE
V1.9.0 Alpha Linux crashes when sending file to SD card

### ISSUE THREAD

**Issue by emelbardis** [SoftFever/OrcaSlicer#3282]
### OrcaSlicer Version

V1.9.0 Alpha

### OS version

Fedora Linux / appimage

### Additional system information

11th gen i9, intel graphics

### Printer

Bambu Lab X1C

### How to reproduce

Slice all
Send all

### Actual results

Orcaslicer either crashes and closes or says that I need to be on the same LAN

### Expected results

File sent to X1C SD card

### Project file & Debug log uploads

no logs - will try again if needed

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by MonkaKokosowa** [comment]
Also crashes while testing lan connection to the printer before sending if the access code and IP are correct

**Comment by CCS86** [comment]
Also crashing on Windows x64 when sending to SD card.

**Comment by CCS86** [comment]
Still crashing in 1.9.0 beta

**Comment by CCS86** [comment]
@SoftFever can you reproduce?

**Comment by SoftFever** [comment]
Yes, and I have fixed this issue. Will release 1.9.0 official soon

**Comment by SoftFever** [comment]
Fixed.
