### ISSUE TITLE
Machine options empty

### ISSUE THREAD

**Issue by lin-ycv** [SoftFever/OrcaSlicer#3283]
### OrcaSlicer Version

1.7.0

### OS version

Windows 11

### Printer

None/Unable

### How to reproduce

I was teaching 3D printing, and was using orca slicer, but some students had issues with it.
On first launch of the program, at the page where machines need to be selected, the page is completely empty.
I am unable to reproduce this issue on any of my computers.
When I taught the class, 1.7 was the newest release. I don't know if the newer versions fixed this or not, as i'm unable to reproduce the issue.

I did check their installs, it had all the machine config files in the correct folders.

### Actual results

![image](https://github.com/SoftFever/OrcaSlicer/assets/60565737/49b62a2e-8cac-435d-bac2-532cbc4df931)

### Expected results

to be able to select the machines

### Project file & Debug log uploads

issue not on my computer, have no access to logs.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by SoftFever** [comment]
can you try with the latest 1.81 or 1.9.0-alpha and see if the problem persists?
Also it may worth to try install Orca in a non-Unicode path(in this case, avoid Chinese characters in the installation path)
