### ISSUE TITLE
Wrong flat surface slicing

### ISSUE THREAD

**Issue by giorgiomanieri** [SoftFever/OrcaSlicer#3286]
### OrcaSlicer Version

1.8.1

### OS version

Windows 11 Pro

### Printer

Creality K1

### How to reproduce

1. Start slicing of the model: https://www.printables.com/it/model/623172-creality-k1max-orbiter-20-adapter
![image](https://github.com/SoftFever/OrcaSlicer/assets/54476289/84adc31f-d6e5-4907-b510-b7597e0e1648)

2. The preview gcode of top surface layer is not flat like the 3d model
![image](https://github.com/SoftFever/OrcaSlicer/assets/54476289/119467d2-f2d7-4391-aed3-a50b57ed7c0f)

The model should be laid on top/bottom to reproduce the issue

### Actual results

![image](https://github.com/SoftFever/OrcaSlicer/assets/54476289/fbaf2c4e-278a-4e6a-9e25-7c78d9056de1)

### Expected results

![image](https://github.com/SoftFever/OrcaSlicer/assets/54476289/d9807383-785b-4240-b444-9606a037bd73)

### Project file & Debug log uploads

[K1_orbiter2_adapter.zip](https://github.com/SoftFever/OrcaSlicer/files/13767483/K1_orbiter2_adapter.zip)
[debug_Tue_Dec_26_00_24_34_17796.log.zip](https://github.com/SoftFever/OrcaSlicer/files/13767484/debug_Tue_Dec_26_00_24_34_17796.log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by sufe08** [comment]
It seems the flat surface for the model is not flat really, you can see the same result in Prusa as well. And preview show there is a very small step gap for that surface
