### ISSUE TITLE
[Feature] - Add Anycubic Kobra Line of Printers to Devices

### ISSUE THREAD

**Issue by ondrovic** [SoftFever/OrcaSlicer#329]
**Is your feature request related to a problem? Please describe.**
I would like to have the Anycubic Kobra line of printers added to devices, this would include device profiles for the following

Anycubic Kobra Go
Anycubic Kobra Neo
Anycubic Kobra
Anycubic Kobra Plus
Anycubic Kobra Max

**Describe the solution you'd like**
If the above devices were available as profiles in the slicer, so  I wouldn't have to switch to Cura / Prusa Slicer in order to use the printer

**Describe alternatives you've considered**
Currently using another slicer, haven't used Bambu Studio yet might be able to generate my own profiles

**Additional context**
Additional Information for each of the printers can be found [here[(https://www.anycubic.com/collections/kobra-series)

**Comment by hliebscher** [comment]
you can use your printer with other profile and modify the setup witch your config and your startcode
