### ISSUE TITLE
Multiple Extruders, Automatic build plate slicing, Add text directly to the object or Build plate just as Prusa Slicer

### ISSUE THREAD

**Issue by cdvankammen** [SoftFever/OrcaSlicer#3290]
Is there a reason that there is no is no automatic slicing in this slicing. This is a Prusa Slicer fork. 
Also, a need for multiple extruders is required for this slicer to complete strongly with Prusa Slicer. 

A need or desire to be able to add objects (shapes and text) directly to the build plate as Prusa Slicer has. I would be willing to try helping wit programing with any guidance.

**Comment by Noisyfox** [comment]
> Is there a reason that there is no is no automatic slicing in this slicing. This is a Prusa Slicer fork.

Because BBS disabled this for whatever reason, and we haven't brought it back yet.



> Also, a need for multiple extruders is required for this slicer to complete strongly with Prusa Slicer.

That's on the plan.



> A need or desire to be able to add objects (shapes and text) directly to the build plate as Prusa Slicer has. I would be willing to try helping wit programing with any guidance.

It's already supported in the 1.9 alpha version.

**Comment by cdvankammen** [comment]
Thank you for the response. With regards to things being disabled and the addition of multiple extruders.

I would like to offer my help with progressing these features. Are you an active developer on the project? Or who could I work with to provide help?

**Comment by cdvankammen** [comment]
So I see that the 1.9 was released. However, the options for automatic printing is still not available do you happen to know the pull request that added it?

**Comment by cdvankammen** [comment]
Any thoughts when this will become a thing?
