### ISSUE TITLE
1.9.0 alpha Crashes when color painting

### ISSUE THREAD

**Issue by Heiliger-Gral** [SoftFever/OrcaSlicer#3292]
### OrcaSlicer Version

1.9.0 Alpha

### OS version

Windows 10 X64

### Printer

Rook

### How to reproduce

As soon as I want to paint a multicoler print and I click on the "Color Painting" button at the top, OrcaSlicer crashes

### Actual results

![orca alpha](https://github.com/SoftFever/OrcaSlicer/assets/134379902/756d3b27-0531-46a9-b1e3-3370a0e8f073)

### Expected results

Orca Closes without notification

### Project file & Debug log uploads

[crash_Tue_Dec_26_11_15_11_0.log](https://github.com/SoftFever/OrcaSlicer/files/13770785/crash_Tue_Dec_26_11_15_11_0.log)
[lizard Orca1.zip](https://github.com/SoftFever/OrcaSlicer/files/13770792/lizard.Orca1.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by SoftFever** [comment]
Thanks for reporting back.
Does it crash consistently?

**Comment by Heiliger-Gral** [comment]
> Thanks for reporting back. Does it crash consistently?

After the 5th time it worked... but I still have a problem in that I get an MCU timer to close error when I print a lot of multicollers...

With Prusaslicer it works without any problems

But it's a different problem and I don't know how best to describe and show it to you... but I wrote about it in the Discord

**Comment by silence48** [comment]
Another 
Exception Code :c0000005 ACCESS_VIOLATION

Related issues include #2921 #3375 #3157 #3340
