### ISSUE TITLE
Orca 1.9 Alpha no --datadir option anymore

### ISSUE THREAD

**Issue by Prutsium** [SoftFever/OrcaSlicer#3297]
### OrcaSlicer Version

1.9 Alpha

### OS version

Win11

### Printer

Bambu X1C

### How to reproduce

In the past it was possible to point to a specific datadir to be able to have profiles on the network by opening orcaslider with orca-slicer.exe --datadir profiles and it would use the profiles directory within the Orcaslicer directory.

### Actual results

Profiles are not loaded and datadir is not been used

### Expected results

To open profiles from custom location

### Project file & Debug log uploads

..

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by SoftFever** [comment]
Fixed in dev.
Will be available in 1.9.0 beta

**Comment by Prutsium** [comment]
Great and thanks.
Btw paypal or something like that? You do a great job and has to be
appreciated 😁
