### ISSUE TITLE
Print Sequence By Objetct reports a height collision when collisions is virually impossible

### ISSUE THREAD

**Issue by bc30se** [SoftFever/OrcaSlicer#3299]
### OrcaSlicer Version

1.8,1

### OS version

win11

### Printer

creality k1

### How to reproduce

Try to place two objects of the same height distanced from each other. Then try to slice with PRINT SEQUENCE - BY OBJECT. The Sliver will show the height collision error message even for the arragments that are pysically not possible to collide with the hotend.

### Actual results

You cant slice the object and generate your gcode.

### Expected results

It should be possible to specify maximum radius and allowable height of the object. Or this option should be repaired.

### Project file & Debug log uploads

[crash_Tue_Dec_19_09_31_39_0.log](https://github.com/SoftFever/OrcaSlicer/files/13772947/crash_Tue_Dec_19_09_31_39_0.log)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by Noisyfox** [comment]
What's your clearance between the nozzle tip and the z axis rail?

**Comment by bc30se** [comment]
It is about 10cm - Creality K1, however I cannot make new entries as it is possible in Prusa slicer (radius/height)

**Comment by Noisyfox** [comment]
10cm? Are you sure? If you are certain then you could update these settings:
![image](https://github.com/SoftFever/OrcaSlicer/assets/1537155/57d3cc2e-2ebd-40dc-be80-7f0f3d135d14)

Use at your own risk!

**Comment by bc30se** [comment]
Where Can I find these settings, I was looking for them everywhere.

**Comment by bc30se** [comment]
Got it man thank you!!

**Comment by otede** [comment]
This doesn't make sense. The XY contour should be the only limiting factor for objects of height much less than the Z volume limits. The gantry height should then be used by the slicer to figure out how not to collide with any objects.

**Comment by otede** [comment]
The smaller the gantry height value the mor cautious Orca should be, setting higher Z travel up margins. I've just had a 50 mm model collision with mere 2 models on the plate, auto-arranged by Orca! Project attached:
[orca collision very small model pikachu 2 pieces.zip](https://github.com/user-attachments/files/15846387/orca.collision.very.small.model.pikachu.2.pieces.zip)
![irfan_20240615_114947](https://github.com/SoftFever/OrcaSlicer/assets/5107909/3e24bc09-e0cb-49a6-85e1-b7a475f9a2ca)

**Comment by otede** [comment]
This is still happening all the time. Sometimes it resets with the very same objects on the plate by merely re-initializing auto arrange, which proves this is a bug that produces bogus warnings. Reporting again
https://github.com/SoftFever/OrcaSlicer/issues/6876
