### ISSUE TITLE
Uniform filling

### ISSUE THREAD

**Issue by sssvolk** [SoftFever/OrcaSlicer#3303]
When filling the top layers, if the fill type is monotonous, and if there are objects above, prints the fill unevenly.

It is expected that when filling the top layers, if the monotone fill type is selected, and if there are objects above, it will print the entire fill evenly, monotonically.

p.s. now its best sliser!
![Screenshot_7](https://github.com/SoftFever/OrcaSlicer/assets/130272844/ed10abf5-63b3-4878-84c5-c694edc731a4)
![Screenshot_8](https://github.com/SoftFever/OrcaSlicer/assets/130272844/96a20065-23c2-4d5f-8cde-1a6e055c4180)

**Comment by Noisyfox** [comment]
Try set "only one wall on top threshold" to 0%.

**Comment by sssvolk** [comment]
> Попробуйте установить "только одну стену на верхнем пороге" до 0%.

It has become much better, although there are still artifacts. =)
![Screenshot_9](https://github.com/SoftFever/OrcaSlicer/assets/130272844/81bd76f2-bc5d-43e5-819d-8258114bea5e)
