### ISSUE TITLE
Add the calibration cube

### ISSUE THREAD

**Issue by mirspan** [SoftFever/OrcaSlicer#3310]
Add the calibration cube to the test in the slicer. I have prepared a calibration cube and attached it to the message in the archive *.zip.

[calibration-cube.zip](https://github.com/SoftFever/OrcaSlicer/files/13778287/calibration-cube.zip)

**Comment by giveen** [comment]
It actually already has several calibration prints

![image](https://github.com/SoftFever/OrcaSlicer/assets/1180939/969dc46b-0d29-451f-ac89-40be539ac1af)

**Comment by mirspan** [comment]
Why are the calibration cube and Autodesk FDM Test missing from the top calibration menu?

![Screenshot_20231227_194546](https://github.com/SoftFever/OrcaSlicer/assets/61486117/07748cd4-6db6-444e-ae01-efffe81f90a2)

**Comment by Eldenroot** [comment]
Because calibration cube could be set how you need (print settings). This is not a bug.
