### ISSUE TITLE
Filament Load / Unload time didn't change ETA

### ISSUE THREAD

**Issue by Gnierat** [SoftFever/OrcaSlicer#3311]
### OrcaSlicer Version

1.8.1 and 1.9.0

### OS version

Windows 11

### Printer

Voron 2.4

### How to reproduce

Slice
change load / unload time
Slice
Same time

### Actual results

Didn't change ETA

### Expected results

Recalculate ETA

### Project file & Debug log uploads

[log.zip](https://github.com/SoftFever/OrcaSlicer/files/13778594/log.zip)
[oddish.zip](https://github.com/SoftFever/OrcaSlicer/files/13778596/oddish.zip)

### Checklist of files to include

- [X] Log file
- [x] Project file

**Comment by eoyilmaz** [comment]
Yes, exactly what I was going to report, here are some screen shots:

Before
-------
Filament Load Time: 45 s
Filament Unload Time: 25 s
Total Time: 3h 48m

After
-------
Filament Load Time: 450 s
Filament Unload Time: 250 s
Total Time: 3h 48m

![Before](https://github.com/SoftFever/OrcaSlicer/assets/1786804/958ae2df-37a8-47af-8978-62f7d84afbfe)
![After](https://github.com/SoftFever/OrcaSlicer/assets/1786804/d77fc8cc-0114-46fb-9f73-de1e8d1668b2)

**Comment by eoyilmaz** [comment]
Started looking into this 👍

**Comment by eoyilmaz** [comment]
There is an issue the `machine_filament_load_time` / `machine_filament_unload_time` which stores the printer's filament load/unload time is never visible in the UI, and as far as I see the per filament `filament_load_time` is not read at all.
 
![Screenshot 2024-01-16 at 16 02 11](https://github.com/SoftFever/OrcaSlicer/assets/1786804/89ea41e2-9e76-42d4-9a5b-96b6d2af4050)

**Comment by eoyilmaz** [comment]
Updating the `machine_load_filament_time` and `machine_unload_filament_time` in the `.json` file of the printer now calculates the print time correctly:

![Screenshot 2024-01-16 at 16 14 43](https://github.com/SoftFever/OrcaSlicer/assets/1786804/c4fa99f1-f508-495c-836f-4d07518e255e)
<img width="727" alt="Screenshot 2024-01-16 at 16 16 34" src="https://github.com/SoftFever/OrcaSlicer/assets/1786804/e15012c0-40e6-4120-9245-fa9240ef2863">

**Comment by eoyilmaz** [comment]
So the `machine_load_filament_time` and `machine_unload_filament_time` are disabled on purpose here:
https://github.com/SoftFever/OrcaSlicer/blob/main/src/slic3r/GUI/Tab.cpp#L4059

and instead of `filament_load_time` and `filament_unload_time`, the hidden and 0 by default `machine_load_filament_time` and `machine_unload_filament_time` are used here:
https://github.com/SoftFever/OrcaSlicer/blob/main/src/libslic3r/GCode/GCodeProcessor.cpp#L1039

I think replacing those with the `filament_load_time`/`filament_unload_time` should fix this... Let me try it quickly.

**Comment by eoyilmaz** [comment]
It seems that Bambulab did change the working code of PrusaSlicer, I'm migrating this portion of the code from PrusaSlicer again.

**Comment by eoyilmaz** [comment]
Yep... it seems to be working now 👍 

creating PR in a minute.

**Comment by eoyilmaz** [comment]
PR created 👍
