### ISSUE TITLE
Perimeters offset too much for one wall on top surfaces

### ISSUE THREAD

**Issue by vovodroid** [SoftFever/OrcaSlicer#3313]
For lower top surfaces perimeters are shifted inward, especially when there are number of walls:

![image](https://github.com/SoftFever/OrcaSlicer/assets/8691781/55f8ef3b-ed1c-419e-8707-3df80c91ff2c)

I guess instead of complex calculations here
https://github.com/SoftFever/OrcaSlicer/blob/7ab2fabe6a8b314facb05a0cea372f5b304dc63a/src/libslic3r/PerimeterGenerator.cpp#L885

something like `coord_t offset_top_surface = ext_perimeter_width;` could produce better result:

![image](https://github.com/SoftFever/OrcaSlicer/assets/8691781/f8bd878f-774d-4e00-8d44-8b39eeade77d)

providing base for next layer external perimeter. Picture is from Prusa with ported code.

[Orca-Cube.zip](https://github.com/SoftFever/OrcaSlicer/files/13778968/Orca-Cube.zip)

**Comment by Eldenroot** [comment]
Are you working on a PR?

**Comment by vovodroid** [comment]
Not really. Merill took this code to his SS and used some other formula - https://github.com/supermerill/SuperSlicer/issues/4022#issuecomment-1871368000
