### ISSUE TITLE
Coast over seam gap (for all loops)

### ISSUE THREAD

**Issue by hannoHI** [SoftFever/OrcaSlicer#3325]
**Is your feature request related to a problem? Please describe.**
Not coasting over the seam gap allow extra material to end in the outer loop making the seam more visible as well as leaving gaps on the top visible layers.

**Which printers will be beneficial to this feature**
All

**Describe the solution you'd like**
Allow the printhead to coast for the seam gap distance for all loops (optionally also start the retraction process in this time)

**Describe alternatives you've considered**
Seam Gap with wiping. This does not happen if you have more than 2 walls.

**Additional context**
The additional material from not coasting on the inner layers end up in the outerlayer. This makes whiping less effective as there remain extra material with nowhere to go when doing whiping for the outer layer leaving very visible seam.
If one increase the seam gap to compensate the joint become weaker.

**Comment by igiannakas** [comment]
You can do this as I mentioned in issue https://github.com/SoftFever/OrcaSlicer/issues/3324 

Set travel distance threshold to 0. Set wipe to 1mm or so. Set retract before wipe to 0 if you want to use the "ooze" to close the gap.

**Comment by Javi3rV** [comment]
> You can do this as I mentioned in issue [#3324](https://github.com/OrcaSlicer/OrcaSlicer/issues/3324)
> 
> Set travel distance threshold to 0. Set wipe to 1mm or so. Set retract before wipe to 0 if you want to use the "ooze" to close the gap. Some print tests would be great, to evaluate the benefit vs, tradeoff in print quality.

you got answer in that issue, with photos and explanations it still got ignored. I guess the user who answered there is right, and orca devs think they know better than anyone and we will never have a good coasting system/setting like in Cura. Instead, we got 3 unintuitive wipe settings that could just be joined in a single coasting setting.
