### ISSUE TITLE
SVG files loading incorrectly

### ISSUE THREAD

**Issue by JesseHavok** [SoftFever/OrcaSlicer#3329]
### OrcaSlicer Version

1.8.1

### OS version

Windows 11

### Additional system information

Intel Core i7-10750
32gb ram
NVIDEA RTX 2070 Super

### Printer

Qiditech X-Max-3

### How to reproduce

Create vector in Illustrator
Load or drag svg file into OrcaSlicer

### Actual results

SVG files load into the program with manifold errors as if some anker points are missing. 
![Screenshot 2023-12-28 052540](https://github.com/SoftFever/OrcaSlicer/assets/153732631/8d3a1575-8ad4-4708-996b-e83b06c30701)

### Expected results

Design should be complete

### Project file & Debug log uploads

[bad SVG.zip](https://github.com/SoftFever/OrcaSlicer/files/13786026/bad.SVG.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by Noisyfox** [comment]
Have you tried the 1.9?

**Comment by JesseHavok** [comment]
> Have you tried the 1.9?

Yes

**Comment by Noisyfox** [comment]
Could you upload the svg file?

**Comment by JesseHavok** [comment]
![qr](https://github.com/SoftFever/OrcaSlicer/assets/153732631/1f46b314-ddac-49ca-99c7-3cbbaf3c088f)

**Comment by Noisyfox** [comment]
![image](https://github.com/SoftFever/OrcaSlicer/assets/1537155/01ac4ba8-554e-4ff2-baa0-33a9660ab74a)
It works alright on 1.9 beta.
