### ISSUE TITLE
Kobra 2 Series Update? Neo/Plus/Max

### ISSUE THREAD

**Issue by crazybanane** [SoftFever/OrcaSlicer#3332]
Hello will there comming soon a update on the Anycubic Kobra 2 Series? e.g Plus Max Neo?

**Comment by csstup** [comment]
Following.   I'm happy to provide a machine config for the Kobra 2 Pro and help test.    

Attached is the ini for the Kobra 2 Pro from the manufacturer supplied with the machine.  

[Kobra 2 Pro V1.0.ini.zip](https://github.com/SoftFever/OrcaSlicer/files/13789876/Kobra.2.Pro.V1.0.ini.zip)

**Comment by n4tur3502** [comment]
I would love to see the kobra 2 plus added.

**Comment by unbobby** [comment]
[Anycubic Kobra 2 Max 0.4 PETG自建.zip](https://github.com/SoftFever/OrcaSlicer/files/14141738/Anycubic.Kobra.2.Max.0.4.PETG.zip)
I have created a preset for PETG on the Kobra 2 Max. Any feedback is welcome.

**Comment by N0rdskog** [comment]
I started tinkering with porting some of AnyCubic's native settings to a Kobra 2 Pro profile. Does anyone know whether .ini files can be used in any way within OrcaSlicer?
