### ISSUE TITLE
do not log in

### ISSUE THREAD

**Issue by rafajluque** [SoftFever/OrcaSlicer#3333]
### OrcaSlicer Version

1.8.1

### OS version

Windows 10

### Printer

Ender3 S1

### How to reproduce

home, enter/registration

### Actual results

In Windows 10, it won't let me log in, the window remains blank:

![image](https://github.com/SoftFever/OrcaSlicer/assets/73631173/450bdebb-7e8a-4206-9567-d5226d1971b4)

### Expected results

A window should appear to log in to your bambulab account.

### Project file & Debug log uploads

not relevant

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by silence48** [comment]
You likely need to install the edge webview runtime.

 - [MicrosoftEdgeWebView2RuntimeInstallerX64](https://github.com/SoftFever/BambuStudio-SoftFever/releases/download/v1.0.10-sf2/MicrosoftEdgeWebView2RuntimeInstallerX64.exe)
          - [Details of this runtime](https://aka.ms/webview2)

**Comment by rafajluque** [comment]
Perfect, thank you very much, solved with #2004, deleting folders and restarting. Thank you so much
