### ISSUE TITLE
Preview problems with black filaments

### ISSUE THREAD

**Issue by TinyMito** [SoftFever/OrcaSlicer#3339]
### OrcaSlicer Version

1.9.0

### OS version

macOS 14

### Printer

Bambu Lab A1 Mini

### How to reproduce

See known bug from Bambu Studio here: https://github.com/bambulab/BambuStudio/issues/2761

1. Just load up any PETG / PLA black colour filaments. The models will be pitch black in the preview.

### Actual results

Result:

![20231229_001573](https://github.com/SoftFever/OrcaSlicer/assets/75095713/9a6bd9f5-8e44-42ad-93b5-2e4dfda9c386)

### Expected results

Expected:

![20231229_001574](https://github.com/SoftFever/OrcaSlicer/assets/75095713/0df4c0f9-29af-4a74-9bac-a3dcfe9ce7a4)

### Project file & Debug log uploads

3MF file included for sample.

[Toronto.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/13791265/Toronto.3mf.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by foreachthing** [comment]
Easy fix: don't use black. 😉 
Otherwise you'd have to use things like: raytracing, subsurface scattering, shine, roughness, etc.

**Comment by TinyMito** [comment]
Confirmed and closing this bug report. Looks like it is fixed.
![20240323_002006](https://github.com/SoftFever/OrcaSlicer/assets/75095713/462dc341-17fd-4b80-a976-a472c56a6a6f)
