### ISSUE TITLE
Crash while slicing with 1.9.0-alpha

### ISSUE THREAD

**Issue by kingstar42** [SoftFever/OrcaSlicer#3340]
### OrcaSlicer Version

1.9.0-alpha

### OS version

Windows 10 64 bit

### Additional system information

CPU: Intel Core i5-7400T 
Memory: 8 GB 
Graphics: Intel HD Graphics 630

### Printer

Voronized/Klipperized Ender 3V2

### How to reproduce

Load project file and slice plate. 

### Actual results

System will either crash and close window, or will show a fatal error and prompt to save and restart. File slices fine in 1.8.1.

### Expected results

Slicing completes successfully.

### Project file & Debug log uploads

[log.zip](https://github.com/SoftFever/OrcaSlicer/files/13791414/log.zip)
[Crash.zip](https://github.com/SoftFever/OrcaSlicer/files/13791416/Crash.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by silence48** [comment]
This issue also is also c0000005 ACCESS_VIOLATION
Many related issues have been reported, we really should find one issue where people can comment on this with their logs, instead of having tens of the same thing (IMO)
Related issues include #2921 #3375 #3157

**Comment by SoftFever** [comment]
It's a regression bug cause by PR #3014

**Comment by SoftFever** [comment]
Hi 
Can you try this build? https://github.com/SoftFever/OrcaSlicer/actions/runs/7377220740
It should be fixed now.
