### ISSUE TITLE
Detect Internal Overhangs

### ISSUE THREAD

**Issue by HongClarence** [SoftFever/OrcaSlicer#3341]
This is mostly beneficial for high speed printers. Currently, internal overhangs are not detected and are printed at normal infill speeds. Low(5 - 10%) infill parts will start to curl due to insufficient cooling from standard speed printing, leading to the print head colliding with the curled parts repeatedly and eventually the print toppling.

As low infill parts are usually used for props and display models, increasing infill percentage is not viable as it increases total weight and filament usage.

Bed adhession is not the problem as the plate has been thoroughly cleaned using warm soapy water on multiple occassions. Active cooling is not an issue as well as I have tried dual aux fans at 100% with part cooling fan at 100%.

Dropping internal solid infill speed to 50mm/s solves this problem as now the internal overhangs are printed at overhang speeds, however this is a band-aid fix as now all internal solid infills are printed slowly even if they are not an overhang(such as bottom internal infills).

![image](https://github.com/SoftFever/OrcaSlicer/assets/56550818/768e62ce-deb8-44c7-90e7-6def73d73849)
Internal overhangs are most common on parts with curved top and low infill percentage.

![image](https://github.com/SoftFever/OrcaSlicer/assets/56550818/1f8d0c2d-4313-43ab-85c9-4d4160204876)
Internal overhangs usually are under the ‘internal solid infill’ line type.

![image](https://github.com/SoftFever/OrcaSlicer/assets/56550818/b5536cb7-af35-46eb-9bd6-78dbef98bad2)
This is printed on 10% infill with standard speed profiles. As we can see, the internal solid infill is an overhang that is printed at standard speed. This causes curling and leads to print failure.

![image](https://github.com/SoftFever/OrcaSlicer/assets/56550818/4dce4e93-b523-4d40-94e3-f955b77e195a)
Printed again with the same profile but slowed internal solid infill speed to 50mm/s. Printed successfully without any issues but with a longer print time. Detecting internal overhangs will help reduce the print time as normal internal solid infills will be printed at normal speed while only internal overhangs are slowed down.

After printing multiple props and display models for the past year, curling internal overhangs has been my most encountered problem when a print failed.

**Comment by igiannakas** [comment]
Check this out: https://github.com/SoftFever/OrcaSlicer/pull/3319
