### ISSUE TITLE
BUG part cooling fan ramp up/down lag  GCODE not generated

### ISSUE THREAD

**Issue by jlo1975** [SoftFever/OrcaSlicer#3350]
********UPDATE*******
********UPDATE*******
the feature seem to be bugged see my tests in my reply
there is a blank line just after the M106 S255 command like something (a command ?) should be here but not generated (see my last screenshot at the end of this issue)
********UPDATE*******
********UPDATE*******

**Is your feature request related to a problem? Please describe.**
On some material like PETG where the part fan is very low. We need high fan speed for overhang or bridge.
But we miss the correct timing as the fan part is too late when the bridge/overhang is starting and still at high rpm when the bridge/overhang is finished

**Which printers will be beneficial to this feature**
all printers

**Describe the solution you'd like**
add a setting (in filament setup?) in part fan option to setup the lag in ms.
For ex a setting of -500 would move into the gcode 500 ms sooner the ramp up and ramp down of the part fan.
or add a wait command of 500 ms before the next gcode

**Describe alternatives you've considered**

**Additional context**

**Comment by amicloud** [comment]
This feature is in Orcaslicer, at least with the 1.9.0 beta I am currently using. 
![image](https://github.com/SoftFever/OrcaSlicer/assets/16375789/d39c21f5-5ee6-484e-9004-c08155da03b6)

**Comment by jlo1975** [comment]
thanks !
indeed I didn't check the printer setting

**Comment by jlo1975** [comment]
ok i've done some testing.
and it seem this feature does not work.
"the overhang does not wait" the correct fan speed

here a test with a 1 sec lag vs a 5 sec lag
you will see in the Gcode that the kickstart is at exactly the same location (as specified by the feature).
but there is not barrier/pause to let it ramp up and so the overhang is printed without the correct fan speed

see screenshot.

![z1](https://github.com/SoftFever/OrcaSlicer/assets/154452786/794e3377-cc1a-4a3e-9f70-7310a42f32ea)
![z2](https://github.com/SoftFever/OrcaSlicer/assets/154452786/aa4d33a5-0731-4c0e-87a9-d9a38ca85939)
![z3](https://github.com/SoftFever/OrcaSlicer/assets/154452786/ac4ad70a-c6dc-4207-9626-892b49f545a3)

**Comment by amicloud** [comment]
Not sure what could be going on there. It seems to be working for me, as shown in the bridging tests below. The first is with 1.25 second and the second with 5 second ramp up time, last is with 0.5 second

![image](https://github.com/SoftFever/OrcaSlicer/assets/16375789/ad502aca-2ef0-494a-a2ec-03ec6e197b5a)

![image](https://github.com/SoftFever/OrcaSlicer/assets/16375789/bde2eb67-7c5e-48ac-8f50-d83236905a9e)

![image](https://github.com/SoftFever/OrcaSlicer/assets/16375789/26d2a916-f184-4adf-b95b-16bebffc6d29)


Maybe the kick-start time has something to do with it but tbh at this moment I don't have time to look into it myself

**Comment by jlo1975** [comment]
in your screenshot what we see is the the theorical fan speed.
but in real life the fan is not a the shown speed when starting the overhang section
we don't see in the code something after a M106 s*** code like an extruder speed down/flow down or a barrier/waiting commang like  a G4 ***  to let the time to the fan to speed up.

you can make a real life test with a simple overhang test and put  a 2 - 3 sec in the fan setting a you will see that the printer start the overhand section without waiting the 2 sec.

I will put some screenshot of what i'm saying in few minutes (I will edit this reply)

**Comment by jlo1975** [comment]
ok here the scrreenshot and we see something is really wrong

here a test with 0 speed up time
![z1](https://github.com/SoftFever/OrcaSlicer/assets/154452786/4721342c-3602-4658-87ad-cb185113701a)

and with  2 sec speed up time and we see no diff !!!!
![z2](https://github.com/SoftFever/OrcaSlicer/assets/154452786/32a61f05-802e-4112-9896-3a2a360ddb17)

but something more weird if following
here you will see a kdiff3 of the generated GCODE (0sec  speed up vs 2 sec speed up)
and we can see something is missing on the 2 sec GCODE !!!! the M106 command !
![z3](https://github.com/SoftFever/OrcaSlicer/assets/154452786/4e137987-3a9a-4593-9fd9-687ded3c0313)

**Comment by jlo1975** [comment]
here the weird thing

test with 0 speed up time look at the inner  line with speed at 90%
![w1](https://github.com/SoftFever/OrcaSlicer/assets/154452786/43d6d1a7-cfdd-4a0f-b552-1bc5e517cc83)

and now with a speed time of 2 sec the inner line is no more at 90% but at 30% ...... weird no?
![w2](https://github.com/SoftFever/OrcaSlicer/assets/154452786/5c68857e-ebf7-417d-bd42-f973c006f008)

confirmed by the kdiff3 between the 2 gcode a M106 command is missing when we specifiy the 2 sec speed up time.
Bit still no barrier/wainting time or slow down of the hotend speed or flow to let the fan ramp up.
![z3](https://github.com/SoftFever/OrcaSlicer/assets/154452786/b2ab011b-542a-4a35-b7a5-e1e45d1bf402)

**Comment by jlo1975** [comment]
here another test where i'm showing visually where the barrier/waiting block should be by playing with the fan kick start time (aka 100% fan). and we can see no change between the  2 gcode except where the end of kick start is


![u1](https://github.com/SoftFever/OrcaSlicer/assets/154452786/faa4f570-fa71-4c54-a795-9028ce0f1e60)


![u2](https://github.com/SoftFever/OrcaSlicer/assets/154452786/3e51ece3-fe36-4b04-a985-a590c8b0191b)

**Comment by jlo1975** [comment]
finally on my last screenshot above I've just noticed -> there is a blank line just after the M106 S255 command like something (a command ?) should be here but not generated

**Comment by jlo1975** [comment]
ok found out the problem is comming from the check box -> only overhangs...
more info here -> https://github.com/SoftFever/OrcaSlicer/issues/3498

**Comment by jlo1975** [comment]
closing this issue but let the BUG report opened as  found out the problem is coming from the check box -> only overhangs...
for cooling fan ramp up/lag to be correctly handled for overhang you have to untick the check box -> only overhangs...
see my last comments on the bug report  https://github.com/SoftFever/OrcaSlicer/issues/3498
