### ISSUE TITLE
Add job cost {variable_name} to exported gCode filename format options

### ISSUE THREAD

**Issue by tlhintoq** [SoftFever/OrcaSlicer#3364]
It would be really nice if exported gCode names could include the job cost as well as the job print time.
After much experimentation with possible variable names the only working one I could find was `filament_cost[0]` but that returns the total spool cost as set on the material  ($20/kg) instead of the cost of running this job.
![image](https://github.com/SoftFever/OrcaSlicer/assets/11351506/eb572c06-0efc-4fc7-a68f-6b4794f3188d)

**Comment by tlhintoq** [comment]
Keep alive - Still an issue in 2.0 developer/nightly

**Comment by tlhintoq** [comment]
Hey bot, please don't close me - this is still an issue.

**Comment by tlhintoq** [comment]
Problem still exists in current 2.0 nightly as of 13mar2024

**Comment by tlhintoq** [comment]
Keep alive.  Problem still exists in current 2.0 nightly as of 15apr2024

**Comment by tlhintoq** [comment]
@Noisyfox @SoftFever 
Just wondering... Any sense of whether this will get on the roadmap?  or is this maybe subsumed into another ticket?  I seem to recall someone was working an entire framework of costing.  Any chance that those variables are available for file naming?
![image](https://github.com/SoftFever/OrcaSlicer/assets/11351506/6a71b15e-5b49-44e7-9a9c-24418cd92212)

**Comment by SoftFever** [comment]
@tlhintoq 
Hmmm it should be supported already.
Can you try this variable name instead? 'total_cost'
Let me know if it works

**Comment by tlhintoq** [comment]
>  Can you try this variable name instead? 'total_cost' Let me know if it works

Yes.  Thank you.  `{total_cost}` does the job.  Formatted a little long, but I can live.  Just wondering... I where can I find a proper list of usuable variables?  I've asked on Discord before getting banned, I've asked on facebook.  The only answer was "same as bambu slicer" which still isn't a location.  If I could have found a complete list I wouldn't have had to raise this as a bug and  then pester people for 9 months which nobody wants.
![image](https://github.com/SoftFever/OrcaSlicer/assets/11351506/99445f82-2aef-4038-9742-8ca815bc5ed1)
