### ISSUE TITLE
Easy plate naming

### ISSUE THREAD

**Issue by Nevio024** [SoftFever/OrcaSlicer#3367]
**Is your feature request related to a problem? Please describe.**
Naming all the different plates of a big project is a pain. It's just unnecessarily complicated.

**Which printers will be beneficial to this feature**
This would make using and naming multiple build plates for projects in Orca Slicer easier.

**Describe the solution you'd like**
Just a simple click on the "Untitled" (or on a symbol next to it) would allow the title to being edited. It could be confirmed with Enter or just by clicking somewhere else. There would be no extra window opening. The title should be edited in the standart "Prepare" view.

**Comment by Eldenroot** [comment]
Bambulab studio 1.8.2 contains this feature. There is an icon of pencil next to the plate name, you can easily rename it.

**Comment by Nevio024** [comment]
Yes, exactly! Having that in OrcaSlicer would be awesome!

**Comment by Eldenroot** [comment]
Yes, I agree!

This is the screenshot from Bambulab studio 1.8.2

![image](https://github.com/SoftFever/OrcaSlicer/assets/778890/7d71eb1e-3e88-4850-b7ff-d1669f6b4e18)

@SoftFever - please, could you port this?

**Comment by Noisyfox** [comment]
> Bambulab studio 1.8.2 contains this feature. There is an icon of pencil next to the plate name, you can easily rename it.

But that still shows a popup instead of editing the name in place.

**Comment by SoftFever** [comment]
They added an icon when they ported this feature from Orca. I think I can add a behaviour that invokes the plate name dialog when double clicking the plate name

**Comment by Eldenroot** [comment]
@SoftFever - this would be awesome, together with sync up to Bambu studio v 1.8.3
