### ISSUE TITLE
XY movement before Z on travel to first print movement

### ISSUE THREAD

**Issue by Patn1** [SoftFever/OrcaSlicer#3377]
### OrcaSlicer Version

1.9.0 Beta

### OS version

Windows 11

### Printer

AnkerMake M5

### How to reproduce

Slice a model

### Actual results

After homing, the slicer tells the printer to go to a certain point. In Orca it does the XY movement before the Z movement, which wipes some filament on the built plate (or even scratches the plate, if Z-offset is too close). AnkerMake Studio does it the other way round what leaves no unwanted filament on the plate.
![OrcaSlicer](https://github.com/SoftFever/OrcaSlicer/assets/139695400/9063833b-2242-4bef-a037-8d9f18e37395)

### Expected results

Z before XY on first print move
![AnkerStudio](https://github.com/SoftFever/OrcaSlicer/assets/139695400/b5a47393-81ca-436a-8e0c-c8db3fb22ff8)

### Project file & Debug log uploads

[Container 100-50.zip](https://github.com/SoftFever/OrcaSlicer/files/13799030/Container.100-50.zip)
[debug_Sat_Dec_30_20_48_33_2668.log](https://github.com/SoftFever/OrcaSlicer/files/13799056/debug_Sat_Dec_30_20_48_33_2668.log)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by foreachthing** [comment]
Yeah, same here.
That's why I wrote this some time ago https://github.com/foreachthing/Slic3rPostProcessing
