### ISSUE TITLE
Embossed text and Wiggle error

### ISSUE THREAD

**Issue by olcayoren** [SoftFever/OrcaSlicer#3378]
### OrcaSlicer Version

1.9.0 beta

### OS version

Macos Sonoma 14.0

### Additional system information

Macbook M1 2020 Arm

### Printer

Elegoo Neptune 4 Pro

### How to reproduce

Hello, as seen in the video, there is a jitter problem when switching between fonts and a problem of blank text when switching to one font.

https://github.com/SoftFever/OrcaSlicer/assets/33813227/713c99ac-ba7e-49ab-b5f7-3046e45bf6cb

### Actual results

None

### Expected results

None

### Project file & Debug log uploads

None

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Noisyfox** [comment]
The font you selected simply does not contain the characters you entered.
