### ISSUE TITLE
Hole wall problem

### ISSUE THREAD

**Issue by olcayoren** [SoftFever/OrcaSlicer#3392]
### OrcaSlicer Version

1.8.1

### OS version

Macos Sonoma 14.0

### Additional system information

Macbook air m1 2020 arm

### Printer

Elegoo Neptune 4 Pro

### How to reproduce

- Drawing a hole in the wall

https://github.com/SoftFever/OrcaSlicer/assets/33813227/3e794160-d594-4f3f-be0f-21da19c782da

![IMG_20231231_214443](https://github.com/SoftFever/OrcaSlicer/assets/33813227/ad349153-fe81-450a-84fb-d447c0b58b89)
![IMG_20231231_214446](https://github.com/SoftFever/OrcaSlicer/assets/33813227/6063c8a8-efda-43be-ad64-b3820404e731)

### Actual results

- Internal overflow problem in a drawing with a hole in the wall
- There is no problem reflected on the outer surface

### Expected results

None

### Project file & Debug log uploads

[CaseV2.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/13802029/CaseV2.3mf.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by wrenchonline** [comment]
the same problem

**Comment by wrenchonline** [comment]
Arachne mod is enabled by default and seems to have nothing left to do with it.It doesn't seem like a universal solution

**Comment by wrenchonline** [comment]
> > the same problem.I have looked for many situations, but only this [website](https://forum.prusa3d.com/forum/prusaslicer/mitigate-wall-bulge/paged/1/) has some help, it seems to be an error in the Prusa kernel.
> 
> From what I've read, they recommend using the arachne mod.


Arachne mod is enabled by default and seems to have nothing left to do with it.It doesn't seem like a universal solution

**Comment by olcayoren** [comment]
> I changed the line width and speed of the inner and outer walls, and there has indeed been an improvement
> 

Which values did you write? Can you post a picture?

**Comment by wrenchonline** [comment]
yes，But I found that it's not the main reason, I probably know the main reason now.

**Comment by wrenchonline** [comment]
> > I changed the line width and speed of the inner and outer walls, and there has indeed been an improvement
> 
> Which values did you write? Can you post a picture?


yes，But I found that it's not the main reason, I probably know the main reason now.

![Uploading 862DCCDD787570AA29C512F3119B36C4.png…]()

**Comment by wrenchonline** [comment]
> > I changed the line width and speed of the inner and outer walls, and there has indeed been an improvement
> 
> Which values did you write? Can you post a picture?

This can greatly reduce the layering, which seems to be faintly visible.

**Comment by wrenchonline** [comment]
> > > I changed the line width and speed of the inner and outer walls, and there has indeed been an improvement
> > 
> > 
> > Which values did you write? Can you post a picture?
> 
> This can greatly reduce the layering, which seems to be faintly visible.It seems that there are more available variables to handle, and the feel will also be much worse after reducing precision. good luck for your.

**Comment by olcayoren** [comment]
> > > > I changed the line width and speed of the inner and outer walls, and there has indeed been an improvement
> > > 
> > > 
> > > Which values did you write? Can you post a picture?
> > 
> > 
> > This can greatly reduce the layering, which seems to be faintly visible.It seems that there are more available variables to handle, and the feel will also be much worse after reducing precision. good luck for your.

Thanks, I hope I can find a permanent solution.

**Comment by wrenchonline** [comment]
> > > > > I changed the line width and speed of the inner and outer walls, and there has indeed been an improvement
> > > > 
> > > > 
> > > > Which values did you write? Can you post a picture?
> > > 
> > > 
> > > This can greatly reduce the layering, which seems to be faintly visible.It seems that there are more available variables to handle, and the feel will also be much worse after reducing precision. good luck for your.
> 
> Thanks, I hope I can find a permanent solution.

I have discovered a new solution that can reduce the layering without losing the outer wall.
![QQ截图20240120094724](https://github.com/SoftFever/OrcaSlicer/assets/35405471/f2ff6023-f065-4542-b593-20370f322d24)

**Comment by wrenchonline** [comment]
I have found that there is another issue that leads to hole wall problems, which is the shrinkage rate of consumables, which is the difference in heat dissipation and time between different layers during bridging.Use OrcaSlicer Layter time to view the printing time of different layers. Some layers print too slowly and dissipate heat too quickly, causing consumables to shrink due to stress.

**Comment by olcayoren** [comment]
Thanks for your help, yes, in most filaments, reducing the wall speed and temperature causes healing to the holes in the wall. Then, in such perforated models, it is necessary to follow the layer time chart as much as possible. It seems that playing with the minimum layer time value may also be beneficial in terms of cooling.
