### ISSUE TITLE
Model Not Visible When Painting Seams or Supports

### ISSUE THREAD

**Issue by XSvFury** [SoftFever/OrcaSlicer#3395]
### OrcaSlicer Version

Issue first presented in 1.9.0 Beta but is still present in 1.9.0 Official Release. 

### OS version

Windows 10

### Additional system information

AMD Ryzen 4800HS, 16 GB memory, NVidia GTX 1660 Ti Max-Q

### Printer

Voron Trident, Ratrig V-Core 3, Bambu P1S, Creality K1

### How to reproduce

1. Place an stl model onto the bed.
2. Select either support painting or seam painting.

### Actual results

Model disappears. The mouse will still change to the painting tool when it is over where the model is supposed to be.

Note: I have used more than few versions of OrcaSlicer on this computer and this has never been an issue. Also, I reinstalled version 1.8.1 Release and it works fine.

### Expected results

The model should stay so it can be painted.

### Project file & Debug log uploads

[desk_tool_holder-prject-file.zip](https://github.com/SoftFever/OrcaSlicer/files/13802213/desk_tool_holder-prject-file.zip)
[log.zip](https://github.com/SoftFever/OrcaSlicer/files/13802215/log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by Noisyfox** [comment]
Have you try running the app using iGPU/eGPU?

**Comment by XSvFury** [comment]
> Have you try forcing running the app with iGPU/discrete GPU?

I tried both and both had the same result.

**Comment by michaltulach** [comment]
I have the same problem and filament painting doesn´t work too.

**Comment by XSvFury** [comment]
> I have the same problem and filament painting doesn´t work too.

Thank you for posting. Hopefully it gets fixed soon.

**Comment by JohnGames** [comment]
Reference this issue for temporary work around: https://github.com/SoftFever/OrcaSlicer/issues/3487
