### ISSUE TITLE
Text is garbled when display scaling greater than 300%

### ISSUE THREAD

**Issue by lllucius** [SoftFever/OrcaSlicer#3401]
### OrcaSlicer Version

1.9.0

### OS version

Windows 11

### Printer

Bambu Lab X1C

### How to reproduce

Set windows display scaling to 350%:

1)  Settings -> System -> Display  -> Scale
2)  Start OrcaSlicer
3)  Load attached (or any) project
4)  Click on an object to display info
5)  Click on "Emboss" toolbar button

In the release version, you will see the info with garbled text.  I the beta version, it will be all black.

### Actual results

This is what it looks like:

![garbled text](https://github.com/SoftFever/OrcaSlicer/assets/7347848/d3918d2f-fc98-445e-8d55-965d85928e46)

### Expected results

And this is what it should look like:

![fixed text](https://github.com/SoftFever/OrcaSlicer/assets/7347848/19564e35-75e4-4ce4-9239-434fc494b4a6)

### Project file & Debug log uploads

Project: 

[V1.3_POOPY_SHOE_Shortened_Narrower_STEP.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/13802628/V1.3_POOPY_SHOE_Shortened_Narrower_STEP.3mf.zip)

Debug log:

[debug_Sun_Dec_31_20_51_53_24548.log.0.zip](https://github.com/SoftFever/OrcaSlicer/files/13802627/debug_Sun_Dec_31_20_51_53_24548.log.0.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by yshui** [comment]
This still happens on Linux with 2.3.0-dev commit 99a0facfb3a5c9b4e661e536825c08393053cb53

Behavior is the same, with GTK scaling >= 300%, imgui texts are all black blocks, reduce the scaling and they render normally.
