### ISSUE TITLE
Add Pause at  "X" Layer as well as later progress indicator.

### ISSUE THREAD

**Issue by yexele** [SoftFever/OrcaSlicer#3418]
No this is not related to a problem

All Printer

Being able to add a hard pause in the G Code at a given layer would be great.  This would aid when people want to switch colors at a given point and or when doing chain mail add fabric.  or if you wanted to fill a void with weight before closing of the print.

Beside sitting and watching and pausing yourself manually and hoping you catch it

**Comment by yexele** [comment]
Ps I run a Comgrow T500

**Comment by AndreaErario** [comment]
You can already do that using the right click on the layer bar on the right of the preview section

**Comment by yexele** [comment]
Oh hell ....  Don't I feel stupid...  Thank you so much for pointing that out :)
