### ISSUE TITLE
Part modifier modifications not being applied in correct order

### ISSUE THREAD

**Issue by Shaolo** [SoftFever/OrcaSlicer#3421]
### OrcaSlicer Version

1.8.1

### OS version

Windows 10

### Additional system information

AMD Ryzen 9 5950X 16-Core Processor               
3.40 GHz

128GB RAM

### Printer

Bambu Lab X1C

### How to reproduce

This started with me trying to reproduce super fine mesh after seeing one produced by a support.

I created a design, imported it, and began trying to much around with shells and infills using a part modifier. Turns out the order of operations for a part modifier is not always consistent.

I've attached a simple design with a STEP model and a modifier. The intention is for the modifier to adjust the number of top and bottom shells to 0 and adjust the infill accordingly. However. Depending on how you adjust the number of shells between the part and the modifier chronologically will give you different results. An entirely unexpected result.

Download the zip. Open the file and try the following:

1. Adjust the number of bottom shells on the part via the object screen. Just the part. Set it to 1 and slice. The bottom of the part now has a complete shell on it despite the modifier having zero bottom shells.
2. Now adjust number of bottom shells on the part and the modifier. Sometimes the shells are applied correctly. Sometimes they aren't. It's inconsistently inconsistent. No joke.

The point was to have the design look like this: 
![image](https://github.com/SoftFever/OrcaSlicer/assets/949654/0e0ad2c4-4d9e-4959-8058-5c257c449348)

But it often ends up looking like this:
![image](https://github.com/SoftFever/OrcaSlicer/assets/949654/ad1fd902-4d26-420d-b176-0cd4f08baa4c)

Even with bottom shells on the part set to 1 and bottom shells on the modifier set to 0.

### Actual results

See steps to reproduce

### Expected results

Modifier should always take precedence over base part and sometimes it doesn't.

### Project file & Debug log uploads

[Wide Mouth - Lid slice.zip](https://github.com/SoftFever/OrcaSlicer/files/13806074/Wide.Mouth.-.Lid.slice.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by ColColonCleaner** [comment]
I'm running into a similar issue with a cut modifier and an 'add' modifier. I want the cut modifier to be applied BEFORE the add modifier, but right now it's always cutting the bits that the 'add' modifier is creating. Can't seem to change the order of how these are performed.

**Comment by mattswest** [comment]
Any update on this or has it been addressed somewhere else?

I'm not sure why this was ignored.

This is undocumented, unpredictable behavior that gives arbitrary results.

For example, I have a base config with 3 top and bottom layers, with two overlapping modifiers: one set to 0 top and bottom layers and the other set to 3 top and bottom layers (or any other number > 0). The slicer decides based on nothing the user can control to use the modifier with 0 layers, and reordering the modifiers in the Objects list does nothing to change this.

I'm not sure why the user can't have control over this. Without this functionality, users would have to create generally more complicated modifier arrangements to achieve the same effect. This software is obviously picking one to use, and each modifier is being applied to some degree despite overlapping, so It's unclear what technical limitation would preclude this.
