### ISSUE TITLE
Can’t Add Negative Part

### ISSUE THREAD

**Issue by JeffreyOI** [SoftFever/OrcaSlicer#3423]
### OrcaSlicer Version

1.9.0-beta

### OS version

macOS Sonoma 14.1.2

### Printer

Bambu X1C but it’s a gui issue

### How to reproduce

1. Add a cube
2. Scale the cube a bit alone only a single axis (i.e., non-uniform scale)
3. Right-click primitive-> Add Negative Part

### Actual results

No object is created, size xyz values are nan.
![Screenshot 2024-01-01 at 11 13 37 PM](https://github.com/SoftFever/OrcaSlicer/assets/58099798/29ce13f5-60f7-4c68-a4b0-221316f36144)

### Expected results

A negative object should be created.

### Project file & Debug log uploads

[Cube.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/13807112/Cube.3mf.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by Noisyfox** [comment]
I can reproduce this issue. Will take a look soon.

**Comment by qwewer0** [comment]
Can confirm.
But as a quick "fix", you can add a second negative part that will appear correctly - at least it did for me.

**Comment by CROKOBACON** [comment]
+1 i have this same issue

**Comment by Noisyfox** [comment]
> +1 i have this same issue

Any step/file to reproduce?

**Comment by CROKOBACON** [comment]
> > +1 i have this same issue
> 
> Any step/file to reproduce?

[bugfile_orca.zip](https://github.com/user-attachments/files/16860281/bugfile_orca.zip)

here you go, latest orca version (OrcaSlicer V2.1.1 Official Release), windows 10, Bambu Lab x1c

**Comment by Noisyfox** [comment]
> > > +1 i have this same issue
> > 
> > 
> > Any step/file to reproduce?
> 
> [bugfile_orca.zip](https://github.com/user-attachments/files/16860281/bugfile_orca.zip)
> 
> here you go, latest orca version (OrcaSlicer V2.1.1 Official Release), windows 10, Bambu Lab x1c

Your file seems to be a different problem though. The negative part does not work properly, but the negative part is added successfully to the object.
