### ISSUE TITLE
With 0.4 nozzle, changing inner wall from 0.4 to 0.6 radically changes infill

### ISSUE THREAD

**Issue by yonkiman** [SoftFever/OrcaSlicer#3424]
### OrcaSlicer Version

1.9.0-beta

### OS version

Windows 10

### Additional system information

CPU: AMD Ryzen 7 5800X

### Printer

Voron 2.4

### How to reproduce

Open enclosed Inner Wall Issue.3mf file.  Compare infill at various layers with Inner wall = 0.4 and Inner wall = 0.6.  I've attached 2 png images to quickly show the issue.

### Actual results

Infill changes 15% sparse (0.4mm) to 100% internal solid infill (0.6mm).

### Expected results

I would expect the amount of infill to _reduce_ when the inner wall width is increased.

### Project file & Debug log uploads

[Inner_Wall_Issue.zip](https://github.com/SoftFever/OrcaSlicer/files/13807463/Inner_Wall_Issue.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by qwewer0** [comment]
That is an expected result, as the 0.6 inner wall setting will reduce the infill area bellow the set `minimum_sparse_infill_area`.
