### ISSUE TITLE
Auxiliary part cooling fan set to 100% before chamber heating

### ISSUE THREAD

**Issue by freiser77** [SoftFever/OrcaSlicer#3426]
### OrcaSlicer Version

1.8.1

### OS version

MacOS 14.2.1

### Printer

QIDI X-Max 3

### How to reproduce

# How to reproduce

1. Open Cube.3mf
2. Slice
3. View Gcode-File.

### Actual results

```
;TYPE:Custom
M106 P2 S255 
M191 S55 ;set chamber_temperature and wait for it to be reached
M106 P2 S0 

```

### Expected results

```
;TYPE:Custom
M191 S55 ;set chamber_temperature and wait for it to be reached

```

### Project file & Debug log uploads

[Cube.zip](https://github.com/SoftFever/OrcaSlicer/files/13808796/Cube.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by KD7LRJ** [comment]
Seems like that would help distribute the heat around the chamber.

**Comment by freiser77** [comment]
I see, will close the issue.
