### ISSUE TITLE
Support SD card remote browsing for time-lapses and models

### ISSUE THREAD

**Issue by elax46** [SoftFever/OrcaSlicer#3430]
### OrcaSlicer Version

1.8.1

### OS version

Windows 11

### Printer

Bambulab P1S

### How to reproduce

[Bambulab has released a firmware update for the p1 versions which includes support for SD card remote browsing for time-lapses and models](https://wiki.bambulab.com/en/p1/manual/p1p-firmware-release-history) but at the moment the MicroSD section returns the error initialization failed

### Actual results

Unable to view files on SD

### Expected results

view files and other additional information

### Project file & Debug log uploads

no files are required

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by elax46** [comment]
> Have you checked with Orca 1.9 Beta?

No I didn't check

**Comment by electricar** [comment]
Same issue for me in Orca 1.9 Beta.
