### ISSUE TITLE
Filament notes in tooltip

### ISSUE THREAD

**Issue by ReinhardC** [SoftFever/OrcaSlicer#3443]
My idea is to have the Notes (Notes tab content) in the tooltip for cross referencing at a quick glance. 
If the notes are too long like 4+ lines they could be cut short with a ("...") line inserted. 

Could make sense for other tooltips (printer, process) as well

Example: This
![orca_featurewish_fila_tooltip2](https://github.com/SoftFever/OrcaSlicer/assets/28957452/bae78487-5e3e-4155-a227-e5eed80d501e)

would appear here:
![orca_featurewish_fila_tooltip](https://github.com/SoftFever/OrcaSlicer/assets/28957452/2c924a97-14a7-4989-822b-2a37775f8452)

**Comment by pgifford** [comment]
Very good idea! I think the tooltip could be far longer than 4 lines, look at the length of the "Walls printing order" tooltip.

In fact I like your idea better than my Notes-related idea: add something to the Notes tab (the tab part, not the body) to indicate the presence of notes.  I find it annoying to click on Notes just to see if there are notes after first clicking the edit button for each filament I'm interested in.  If your suggestion is implemented then I would only have to click on Notes to write them and a simple mouseover would display existing notes.
