### ISSUE TITLE
Issuse acceleration

### ISSUE THREAD

**Issue by DrumClock** [SoftFever/OrcaSlicer#3444]
### OrcaSlicer Version

1.8.1

### OS version

Windows 10

### Printer

 Home-made FW Klipper

### How to reproduce

 Hi,
if parameter (1) is set to lower values than those in parameters (2), parameter (1) is always set to G-code (3).

![Aufnahme2](https://github.com/SoftFever/OrcaSlicer/assets/64655979/3682b4bb-68c3-42d0-99e8-bc376fe6d53d)

### Actual results

 Hi,
if parameter (1) is set to lower values than those in parameters (2), parameter (1) is always set to G-code (3).

![Aufnahme2](https://github.com/SoftFever/OrcaSlicer/assets/64655979/3682b4bb-68c3-42d0-99e8-bc376fe6d53d)

### Expected results

Hi,
if parameter (1) is set to lower values than those in parameters (2), parameter (1) is always set to G-code (3).

![Aufnahme2](https://github.com/SoftFever/OrcaSlicer/assets/64655979/3682b4bb-68c3-42d0-99e8-bc376fe6d53d)

### Project file & Debug log uploads

 Hi,
if parameter (1) is set to lower values than those in parameters (2), parameter (1) is always set to G-code (3).

![Aufnahme2](https://github.com/SoftFever/OrcaSlicer/assets/64655979/3682b4bb-68c3-42d0-99e8-bc376fe6d53d)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by zarigata** [comment]
same thing here, it broke my k1 config... now it is slower than my Ender 3
