### ISSUE TITLE
Top surface pattern not updated on 1.4.5

### ISSUE THREAD

**Issue by suchabadperson** [SoftFever/OrcaSlicer#345]
According to the changelog from the latest version, the top surface pattern was changed to monotonic by default, but it is still as monotonic line. I have tested on both macOS and Windows to be sure.

**Comment by hliebscher** [comment]
for me it works MAC M1 OS 13.1...

**Comment by SoftFever** [comment]
> According to the changelog from the latest version, the top surface pattern was changed to monotonic by default, but it is still as monotonic line. I have tested on both macOS and Windows to be sure.

Oops, I forgot to mention I only made this change for third party printers.
The monotonic line pattern generates aggressive gap fills which may cause trouble for slightly slow printers
