### ISSUE TITLE
Add an option to collapse the GCode Box

### ISSUE THREAD

**Issue by cpasoft** [SoftFever/OrcaSlicer#3462]
Add an option to collapse the Gcode window, as you can do with the current Color Scheme window.
![imagen](https://github.com/SoftFever/OrcaSlicer/assets/29692062/28787f16-dfed-49bb-af39-124ce38ee212)

Sometimes it is annoying to have the Gcode window visible.

**Comment by missionfloyd** [comment]
Press C on the keyboard (to see all shortcuts, press ?)

**Comment by igiannakas** [comment]
Also available in the menu options - show gcode window
