### ISSUE TITLE
Implement "allow 3d arcs" for arc fitting

### ISSUE THREAD

**Issue by evilDave** [SoftFever/OrcaSlicer#3465]
**Is your feature request related to a problem? Please describe.**
Arc fitting does not operate when in spiral vase mode

**Describe the solution you'd like**
Add something similar to the code ArcWelderLib added (v1.0.1, see also https://github.com/FormerLurker/ArcWelderPlugin/issues/56#issuecomment-731406144) for allow-3d-arcs to the arc fitting code that is re-used here

I would be interested in looking into this, was just wondering if anyone else had started on anything.

**Comment by malventano** [comment]
This should certainly be reopened and planned, as the arc fitting in Orca/BS breaks in way too many cases, where the 4-year-old arcwelder script handles things seamlessly, and even supports fitting in z, which includes vase mode, etc.
