### ISSUE TITLE
1.9.0 Beta crashes accessing Device tab (Bambu Lab P1S)

### ISSUE THREAD

**Issue by Kolpitsa** [SoftFever/OrcaSlicer#3469]
### OrcaSlicer Version

1.9.0 Beta

### OS version

Windows 11 Home 22H2 22621.2861 x64

### Additional system information

CPU: 11th Gen Intel(R) Core(TM) i5-1155G7 @ 2.50GHz
Memory: 8 Gb
Video: Intel Iris Xe

### Printer

Bambu Lab P1S

### How to reproduce

Issue happens on both, portable and installed packages.
1. Run Orca Slicer setup (for package with installer)
2. Add Bambu Lab P1S printer
3. Install Bambu Lab network plug-in
4. Agree to the prompt to synchronize with Bamboo cloud
5. Log in to Bambu account
6. Go to Orca Slicer and click Device tab at the top of the app window

### Actual results

Orca Slicer crashes without displaying the content of Device tab window

### Expected results

Content of the window under Device tab in displayed

### Project file & Debug log uploads

[OrcaSlicerCrash.zip](https://github.com/SoftFever/OrcaSlicer/files/13837870/OrcaSlicerCrash.zip)
[log.zip](https://github.com/SoftFever/OrcaSlicer/files/13837908/log.zip)

![Screenshot 2024-01-04 210246](https://github.com/SoftFever/OrcaSlicer/assets/155701927/765f9703-9012-47ae-b224-c63fc62b9522)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by stuomas** [comment]
[Known issue](https://github.com/SoftFever/OrcaSlicer/releases/tag/v1.9.0-beta)
