### ISSUE TITLE
Crashing when attemptinmg to save new process

### ISSUE THREAD

**Issue by krankydonkey** [SoftFever/OrcaSlicer#3472]
### OrcaSlicer Version

1.9.0 beta

### OS version

Windows 11

### Printer

Voron Trident

### How to reproduce

Click save on an existing user process, and attempt to rename it to a new preset and save.

### Actual results

The save window will close, but the application will hang indefinitely.

### Expected results

A new user process should be added with the given title.

### Project file & Debug log uploads

[SpeedTestStructure.zip](https://github.com/SoftFever/OrcaSlicer/files/13842642/SpeedTestStructure.zip)
[log.zip](https://github.com/SoftFever/OrcaSlicer/files/13842651/log.zip)

### Checklist of files to include

- [x] Log file
- [x] Project file

**Comment by jimmyapage** [comment]
I Have the same issue

**Comment by flyfr8rs** [comment]
I also have the same issue.
