### ISSUE TITLE
Printbed display incorrect

### ISSUE THREAD

**Issue by bbinnard** [SoftFever/OrcaSlicer#3477]
### OrcaSlicer Version

1.9.0

### OS version

WIndows 11

### Additional system information

Display: LG 4K 
Video Driver: AMD Radeon RX550

### Printer

FLSun SuperRacer running Klipper

### How to reproduce

Open OrcaSLicer

### Actual results

![1](https://github.com/SoftFever/OrcaSlicer/assets/88475689/be4886e8-0b06-43fc-ba41-1f9030f70f89)

Printbed diagram is offset from printbed background. Previous Beta version did not do this.

### Expected results

Printbed diagram should coincide with printbed background

### Project file & Debug log uploads

This happens with no STL file loaded and does not change after one is loaded and sliced. I didn't think a log file etc. was necessary.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by NickSchaf** [comment]
Seeing the same issue upon opening OrcaSlicer 1.9.0.  Additional information, in case it's of use: Adding a second plate results in the folowing:
![image](https://github.com/SoftFever/OrcaSlicer/assets/10584397/53bab24d-2b4a-4f04-aec9-84b9e95e58e5)

**Comment by bbinnard** [comment]
Very interesting. Clearly there is something whacked someplace.

**Comment by bbinnard** [comment]
This problem still exists in the nightly build 08 Mar 2024. Is it always going to be like this? Does it happen only for delta printers?

**Comment by bbinnard** [comment]
I solved this by making an STL file in the shape of my print bed and using that in the printer definition.
