### ISSUE TITLE
Individual skirts when printing by object.

### ISSUE THREAD

**Issue by LazaroFilm** [SoftFever/OrcaSlicer#3486]
I can't seem to find the individual skirts option when printing by object, only a single skirt around all objects. 
I use the skirt as a way to prime my nozzle before a new object and the individual skirt does a better job at that.

**Comment by vovodroid** [comment]
You can set small two loop brim with 2mm gap. It's essentially the same as object skirt.

**Comment by LazaroFilm** [comment]
That's a good bandaid solution for now, but this option should still be available in the settings in my opinion.
