### ISSUE TITLE
Support painting and seam painting

### ISSUE THREAD

**Issue by Rhoenbussard** [SoftFever/OrcaSlicer#3487]
### OrcaSlicer Version

1.9.0

### OS version

Windows 10

### Printer

Sovol SV01

### How to reproduce

Import file
choose an object
click Support painting or Seam painting

the object disappears

### Actual results

no possibility to manipulate both paintings

### Expected results

see the object

### Project file & Debug log uploads

[clearance-test.zip](https://github.com/SoftFever/OrcaSlicer/files/13845971/clearance-test.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Sopbeen12** [comment]
Same Issue here.

**Comment by kencor1** [comment]
I had the same problem.  Rolled back to the previous version. Works on it.

**Comment by davidlaym** [comment]
I was having the same issue, with a notebook that has Nvidia card and AMD integrated graphics. Setting the OrcaSlicer to use the Nvidia card instead of the AMD IG made it work.

On windows 10/11, this is done in the Graphics settings (Settings>Display>Graphic settings link at the end), choosing the orca slicer executable (at Program Files/OrcaSlicer) and changing the options to use High Performance with the Nvidia Graphics.

**Comment by nva48** [comment]
Same problem here on my laptop with an AMD Ryzen 5 4500U with Radeon Graphics. Previous Orca version had no issues. Windows 11.

**Comment by linyongzheng** [comment]
I have Nvidia dGPU and AMD integrated graphics. Forcing Orca-slicer to use either integrated or dGPU does not fix the issue of the model not appearing when support painting for me.

**Comment by Noisyfox** [comment]
> I have Nvidia dGPU and AMD integrated graphics. Forcing Orca-slicer to use either integrated or dGPU does not fix the issue of the model not appearing when support painting for me.

Make sure you force the dGPU from windows' own display settings, not from Nvidia control panel.

**Comment by Rhoenbussard** [comment]
I just test ist on my notebook with Nvidia graphics - all is  ok
The desktop computer has AMD Radeon R7 graphics

**Comment by cherub-i** [comment]
I am experiencing the same problem. 
Win11, AMD Vega graphics card.

Forcing Orca to use the on-chip graphics card (Intel "something") did not change the behaviour. 
(But maybe changing that setting did not work as expected - I don't know.)

I had no problems with AMD Vega and previous versions.
