### ISSUE TITLE
tip of the day ignoring preference

### ISSUE THREAD

**Issue by unrushed-boots** [SoftFever/OrcaSlicer#3492]
### OrcaSlicer Version

1.9.0

### OS version

win 11

### Printer

bambu x1c

### How to reproduce

1. open any model in orca 1.9.0
2. click slice
3. see tip of the day appear

### Actual results

tip of the day along with a "slicing complete" notice show in the bottom right corner. this happens with or without the tip of the day preference being selected. seeming like it is ignored.

### Expected results

no tips shown when the user deselects the option, and no notice when slicing is complete similar to past versions.

### Project file & Debug log uploads

n/a

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by mroek** [comment]
Seeing the same. Mildly annoying.
