### ISSUE TITLE
How to hide G-code preview?

### ISSUE THREAD

**Issue by kozross** [SoftFever/OrcaSlicer#3496]
I just updated to 1.9, and I now get a G-code preview in addition to the usual slicer preview:
 
![Screenshot from 2024-01-06 10-40-57](https://github.com/SoftFever/OrcaSlicer/assets/8463904/93c130fb-a23b-47a2-8f2a-37283166a0ff)

How do I turn this off?

**Comment by amdavidson** [comment]
I have seen this before from time to time in previous versions as well and also do not know how to hide it. 

Am I missing something?

**Comment by WluhWluh** [comment]
Press the C key to disable or enable G-code preview.

**Comment by amdavidson** [comment]
Ah, should have checked help->keyboard shortcuts hadn't looked there. Thanks @WluhWluh

**Comment by unrushed-boots** [comment]
https://github.com/SoftFever/OrcaSlicer/issues/3489 same issue. seems this was turned on by default in 1.9

**Comment by tlhintoq** [comment]
Just look in the menus for Pete's sake.

![image](https://github.com/SoftFever/OrcaSlicer/assets/11351506/5c1041da-c6c9-4b51-82e5-1db864169983)

**Comment by bistory** [comment]
> Just look in the menus for Pete's sake.
> 
> ![image](https://private-user-images.githubusercontent.com/11351506/294636244-5c1041da-c6c9-4b51-82e5-1db864169983.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1MjU2MDYsIm5iZiI6MTcwNDUyNTMwNiwicGF0aCI6Ii8xMTM1MTUwNi8yOTQ2MzYyNDQtNWMxMDQxZGEtYzZjOS00YjUxLTgyZTUtMWRiODY0MTY5OTgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDA3MTUwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwYmQ5OWY0NWY0MGYxZWRjMDJkZTE0NmI1MTFkZGIzMDJjNmJkNWM4OTEzZGMxYTNmMjEzNGRmYmVmY2NmYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-QBt_K345HFf4dRVkogfJApRvcLCwYDHG9qNAbAlt_k)

This is the right answer, @kozross please don't forget to close this issue.
