### ISSUE TITLE
fan speed up time in printer seeting is not working

### ISSUE THREAD

**Issue by jlo1975** [SoftFever/OrcaSlicer#3498]
******************UPDATE***************
untick the check box -> only overhangs... and it will work as intended 
side effect it will also perform on other parts that are not overhangs 
but it is a minor loss as we gain a major benefits for overhangs
******************UPDATE***************

### OrcaSlicer Version

1.8.1 & 1.9.0

### OS version

win10

### Printer

bambu lab P1S

### How to reproduce

1 use the bambu lab P1S default printer setting, 
2 create a new project and add the autodesk  FDM test (in primitive popup menu)
3 save the gcode generated (we are focusing on the overhang part)

4 modify the printer setting and put 1 second to fan speed up time
5 regenerate the gcode

perform a diff on both gcode and you will notice even if the option is active, no special gcode is generated to handle the fan speed up time (no barrier, no wait G4 code, no slow down of the extruder)..... for overhang part 
do a search on keyword -> ; FEATURE: Overhang wall

**please note the kick start time is working perfectly (so it is not included in this issue)**

see screenshot below and generated gcode (you will notice some noise with the M73 not generated at the same line)
You will also notice some M106 fan speed command now missing when setting the fan speed up time is 1 second.

for the long story about this bug with more test see -> https://github.com/SoftFever/OrcaSlicer/issues/3350
where I asked to get this feature (I didn't known it was implemented but seem now to be bugged)

default setup
![z0s](https://github.com/SoftFever/OrcaSlicer/assets/154452786/f517fb7a-8f34-4cb6-afbb-ddcaf3d8c0d4)

with  1 seconde on fann speed
![z1s](https://github.com/SoftFever/OrcaSlicer/assets/154452786/e53980f4-7baa-4b1b-bdf4-7b16fc0cac49)

kdiff3 result on the 2 generated GCODE (with a lot of noise on M73 command not at the same location)
![zgcode](https://github.com/SoftFever/OrcaSlicer/assets/154452786/49026a6e-cd66-450f-9af5-71a20b183efb)
![zgcodeb](https://github.com/SoftFever/OrcaSlicer/assets/154452786/cae85512-7e4c-41ad-bfbf-45e9a715a028)

### Actual results

the fan speed up time is not handled in the GCODE

### Expected results

see some barrier / wait command or slow extruder speed alt/slow down

### Project file & Debug log uploads

here the gcode for both test 
[gcode.zip](https://github.com/SoftFever/OrcaSlicer/files/13847072/gcode.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by maziggy** [comment]
Same here with the latest version on MacOS.

**Comment by jlo1975** [comment]
ok I found out the problem is coming from the check box -> only overhangs...

here the test result:

a test to replicate the problem
![image](https://github.com/SoftFever/OrcaSlicer/assets/154452786/ba7dcc3b-1619-4f09-8de4-6b070dfff98b)

THE BUG !
![image](https://github.com/SoftFever/OrcaSlicer/assets/154452786/a481a08d-c495-4b7d-93e8-358d494bfeb4)

AND FINALLY !!!!!
![image](https://github.com/SoftFever/OrcaSlicer/assets/154452786/f980638d-090b-4bea-a8ef-4090134ef4ad)

**Comment by jlo1975** [comment]
on the last screen shot you can see that the fan part ramp up way before the critical parts.
this is what we wanted!

the checkbox only overhang is missleading as it implies to limits the ramp up time frame ONLY inside the overhangs time frame.
So you can't have any fan ramp up just before entering the overhang part....

the side effect of untick this check box is the rampup will also applied on part that are not overhangs.
But it is a minor problem vs overhangs to be cooled correctly (Yes I know i'm unclear sorry......)
