### ISSUE TITLE
One wall on first layer does not work in Arachne mode

### ISSUE THREAD

**Issue by poloniumn** [SoftFever/OrcaSlicer#350]
I have been using one wall on first/top layer to get a better looking model, using the traditional mode I can generate the top and bottom One wall effect normally, but in Arachne mode the top is disabled and I use ironing instead, the bottom is allowed to be selected but it does not work when selected.

Is this an Arachne feature? Or is it a small bug that forgot to disable the option?

Finally, this is a very good project, thank you very much for your work, I just changed over from SuperSlicer and hope this project will continue, thanks again.

![Snipaste_2023-02-23_12-11-05](https://user-images.githubusercontent.com/31156382/220819668-eeb5468d-5701-4392-9f2a-708e005ff8d3.png)

**Comment by SoftFever** [comment]
yeah, this option is overlooked.
Will add support in the next release
