### ISSUE TITLE
Slicer crashing when switch printer since adding the A1

### ISSUE THREAD

**Issue by win10ha** [SoftFever/OrcaSlicer#3500]
### OrcaSlicer Version

V1.9.0 Official Release

### OS version

Windows 10

### Additional system information

I7 4770K
16 GB DDR 3
GTX 1070 TI

### Printer

Bambu A1/ Ender 3/ CR10's

### How to reproduce

Switch printer profiles from Bambu A1

### Actual results

Hard crash no errors reported, seems to work ok if I remove the Bambu A1 profile (crashes when removing)

### Expected results

The ability to switch between profiles 

### Project file & Debug log uploads

[Orca Crash.zip](https://github.com/SoftFever/OrcaSlicer/files/13847095/Orca.Crash.zip)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by win10ha** [comment]
Also happens with Bambu Slicer

![image](https://github.com/SoftFever/OrcaSlicer/assets/78395489/b7556dfd-7428-48eb-932a-3366136a5f5b)

![image](https://github.com/SoftFever/OrcaSlicer/assets/78395489/2484eb06-cdad-47fc-aaaa-d1ea41ab5685)

**Comment by Egosumumbravir** [comment]
I've been getting crashes just like that switching from Ender3 to Bambu X1C profile on the 1.9beta.
