### ISSUE TITLE
Getting error on my sonic pad

### ISSUE THREAD

**Issue by Fannar1984** [SoftFever/OrcaSlicer#3501]
### Discussed in https://github.com/SoftFever/OrcaSlicer/discussions/3495

<div type='discussions-op-text'>

<sup>Originally posted by **Fannar1984** January  5, 2024</sup>
Hello i am getting error on my sonic pad after slice from Orca slicer about extrude below minimum temp but i dont get it when i slice in bambulab or cura or simplify3D can some explein for me what im doing wrong 
regards Fannar
![20240105_212114](https://github.com/SoftFever/OrcaSlicer/assets/15815988/80e2743e-8fca-4546-8381-a7669f4ac190)
</div>

**Comment by bistory** [comment]
You probably miss some g-code that turns the heater on.
What printer do you use ? Did you change your start gcode ?
BTW, this is a user error, not Orca Slicer bug
