### ISSUE TITLE
What kind of problem can cause this?

### ISSUE THREAD

**Issue by StillMT** [SoftFever/OrcaSlicer#3506]
![photo_2024-01-06_01-59-27](https://github.com/SoftFever/OrcaSlicer/assets/38948783/48823667-4cac-48b0-a2a4-e9db851eead8)
Hi everyone, I'm trying to figure out what can cause this, please help me.

**Comment by tlhintoq** [comment]
That's a user issue, not a software issue.
Settings, hardware issue like clogging, etc.

Best to ask for help on the Orca discord server or orca facebook pages rather than clog up the git issue reporting mechanism use to track actual bugs with the software
