### ISSUE TITLE
Ability to re-organize plate order

### ISSUE THREAD

**Issue by tlhintoq** [SoftFever/OrcaSlicer#3508]
It would be of tremendous help to be able to re-order the plates of a job.

- Sometimes its nice to move similar objects in sequence
- Move completed plates to the end so you know what's next or where you left off printing
- - Or maybe just a clickable check box on the right-side tools to show `[x] Done`.  I feel silly using the `Lock` tool right now for this indicator.
- Re-organize once you slice and know the print time.  For example: Two 4hrs jobs making up one 8hr shift of work, followed by a 12-16hr job to run overnight.  Putting the jobs in workflow order would do a lot for job sequence planning.

![image](https://github.com/SoftFever/OrcaSlicer/assets/11351506/179ed90b-8e96-4d6c-83d8-e67e4a123062)

**Comment by Glenno-H** [comment]
being able to reorganise plate order would be soooo nice.

**Comment by tlhintoq** [comment]
Keep alive - Still an issue in 2.0 developer/nightly

**Comment by tlhintoq** [comment]
Hey bot, please don't close me - this is still an issue.

**Comment by mascenzi80** [comment]
+1

**Comment by tlhintoq** [comment]
Problem still exists in current 2.0 nightly as of 13mar2024

**Comment by tlhintoq** [comment]
Keep alive.  Problem still exists in current 2.0 nightly as of 15apr2024

**Comment by Moeser** [comment]
I'm currently working on a project with over 20 build plates, and being able to re-order the build plates would help me keep the project more organized and print in the correct order.  For doing just-in-time printing tasks for larger projects, this would help make sure the correct parts are printed when needed.

**Comment by tlhintoq** [comment]
Bot nudge.

**Comment by stevenhu70** [comment]
ohhhh yes please!!!   I have a large project with 10+ plates and it would help sooo much if I could re-order them

**Comment by Shadowpheonix** [comment]
This would be a very nice enhancement.

**Comment by geekypilot** [comment]
This feature is definitely needed for larger projects.

**Comment by emeyedeejay** [comment]
June '24 bot bump

+1 from me 🙏

**Comment by mgjv** [comment]
I would also like this. I have several large projects that have become messy over time, and plate reordering would help me work with them a bit more easily.

**Comment by malteschulz** [comment]
This would be very helpful for keeping track of a large project

**Comment by tlhintoq** [comment]
@Azio-Pantheon 
I very much appreciate the work you did to give us the ability to `move plate to the front`.  While not a total ability to re-org the entire project it should do a lot for workflow tracking and ordering.

- Select - move to front
- Select - move to front
- {repeat}

Eventually you have the order you'd like to do the project in.
Or just select - move to front, tells you the most recently printed part.

Thanks!

**Comment by tlhintoq** [comment]
> [Azio-Pantheon](https://github.com/Azio-Pantheon) linked a pull request [3 weeks ago ](https://github.com/SoftFever/OrcaSlicer/issues/3508#ref-pullrequest-2432989746) that will close this issue


3 weeks ago.  Not yet merged.  Just thought I'd throw a nudge in there for this.
cc: @SoftFever

**Comment by MattiaConfalonieri** [comment]
+1 for this feature

**Comment by MKloberg** [comment]
Me too! This would be awesome.
My use case is 37 different ear ring models that each need a specific color/filament, I need to keep in alphabetical order to stay on top of all the stl's.
Then I would like to insert production plates at the top/start/beginning to sort these into material based plates, to group them by filament/color.
This would be a major enhancement for us commercial printers and super cool, even in a crude way so we can move the plates around (doesn't have to be drag and drop), some kind of index field in the plate properties to rearrange them would be fine.

![image](https://github.com/user-attachments/assets/fd3adaa8-24bf-45d6-809d-1af0e18fbe99)

**Comment by MKloberg** [comment]
I just ran into another thing that makes no sense. There's a hard limit of how many plates can be created at 36 plates.
Can we remove that limitation?
Why not? Is there a reason for that?
Sure, the users machine will blow at some point, but what if there is ample CPU/GPU available to lean that far out?
To organize my jewelry project properly, I will need at least 10 more plates to make it work...
Thank you for looking into this also.

![image](https://github.com/user-attachments/assets/4d683129-13a2-4c32-86c8-651618875f1a)

**Comment by tlhintoq** [comment]
> I need to keep in alphabetical order to stay on top of all the stl's.
What a fraking nightmare.  Just a thought-Use the plate names?  Or put the color on the plate?
![2024-09-16_15-07-01](https://github.com/user-attachments/assets/85350e72-fcc7-43b5-87b3-94183fcd2c34)

**Comment by MKloberg** [comment]
I found where the plate limit is defined (hard-coded) if that helps.
Would it be possible to make that a preference item - defaulting to 36, so we can crank it up if needed?

![image](https://github.com/user-attachments/assets/7a6ff04a-703b-4996-addd-326d4045f295)

**Comment by hermitdafunk** [comment]
+1, please.

**Comment by dsluo** [comment]
I don't really feel like #6262 is a complete solution for this issue. Moving to front is nice, I guess, but it still doesn't let you reorder plates arbitrarily without manually shuffling them around.

**Comment by tlhintoq** [comment]
@Noisyfox  Should folks like @dsluo and I keep making suggestions here even though this ticket is closed?  Does that get any attention or would a new ticket be better?

I agree that more ability to re-organize would be nice.  I kinda thought the `move to first` was a fast stop-gap measure until a more complete solution could be completed.

Here's a thought that shouldn't take any new UI, no new widget tools or mouse behaviours.  Let us grab the plate itself from the object list and move the entire plate up and down between other plates, exactly the same way we grab an object *on* the plate and move it to change sequence.
(also, a `collapse all` button at the top of the plate list would make this a ton easier)

![Image](https://github.com/user-attachments/assets/f6934434-882f-4beb-b03a-a4399ae8fd66)

**Comment by Lexxus17** [comment]
+1

**Comment by scrith** [comment]
+1 to this feature.

I sometimes create new revisions of models, but need to retain the current revision. It would be really awesome if I could make a new plate with the updated print and then move it to the workflow space it belongs at.
