### ISSUE TITLE
Auto Rotate Doesnt function correctly.

### ISSUE THREAD

**Issue by insp1re1** [SoftFever/OrcaSlicer#3510]
### OrcaSlicer Version

9 Beta onwards

### OS version

11

### Additional system information

5950x 32gb 3800

### Printer

bambu p1s

### How to reproduce

auto rotate random files.

### Actual results

doesnt rotate into a printable manner, often the degrees are out on the readout too. Bizarre behaviour.

### Expected results

auto rotate to a printable orientation. 

### Project file & Debug log uploads

.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by otwieracz** [comment]
Also reproduced on 1.9.0.
