### ISSUE TITLE
Output 3MF file name to the printer not name of model top of object list!

### ISSUE THREAD

**Issue by 3DPrintDemon** [SoftFever/OrcaSlicer#3511]
**Is your feature request related to a problem? Please describe.**
Problem, Orca outputs the name of the model at the top of the objects list when using {input_filename_base} which is very annoying! 

**Which printers will be beneficial to this feature**
ALL printers!

**Describe the solution you'd like**
I'd like to see the slicer use the {input_filename_base} as any other slicer does & output the correct saved 3MF filename instead of whatever random model is at the top of the Objects list

**Comment by skl111** [comment]
To add to this, if createa new project, import and stl file, save the project and then reopen it and add a new stl file and remove the original stl and save the 3mf with a new file name, it keeps the original stl name in the 3mf file and sends that as the 3md file name to BBL printers.
