### ISSUE TITLE
Paint on Z Hop

### ISSUE THREAD

**Issue by Misunderstood-Wookiee** [SoftFever/OrcaSlicer#3512]
**Is your feature request related to a problem? Please describe.**
Not specifically. I just ran into a problem in a model I attempted to print 3x that failed the exact same way where the nozzle or probe would crash into a pillar during a Travel move and render being able use the pillar for supporting a long bridge, I was told to consider Z Hop but this is a global setting and I did not want to Z Hop for every travel move.

**Which printers will be beneficial to this feature**
All

**Describe the solution you'd like**
Feature added to tools to allow manually painting Z Hop _(areas of a model you would like to Z Hop over)_  that have a variable setting that defines how much Z will added to the travel move when passing over the locations painted.

**Describe alternatives you've considered**
Can't really think of anything, except clearer instructions on how to setup/calibrate to avoid collisions, or detect potential collisions in layers and recommend something in the slicer that that makes it possible to do safer. 

**Additional context**
Z Hop Painting will act similar to Manual Support where by the print head will Z Hop whenever a travel move would pass over the painted on coordinate. This feature work independently of Global Z-Hop choices in slicer.

**Comment by kadisonm** [comment]
Oh I see. Hope this gets resolved for you then.

:)
