### ISSUE TITLE
Flickering window when sending a job to printer

### ISSUE THREAD

**Issue by NordicRavn** [SoftFever/OrcaSlicer#3514]
### OrcaSlicer Version

1.9.0

### OS version

Windows 10 Pro

### Additional system information

CPU: Inter i5-8400, RAM: 16GB DDR4, GPU: Nvidia RTX 2060 

### Printer

Bambu Labs X1C

### How to reproduce

1. After slice go to Print plate and send it to printer
2. The window which you see the options like bed leveling, timelapse
3. Pressing send to printer it flicks fast till it starts the countdown to forward you to Device tab and see the camera

### Actual results

The printing started normal

### Expected results

It should not flick

### Project file & Debug log uploads

log

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by NordicRavn** [comment]
![image](https://github.com/SoftFever/OrcaSlicer/assets/129986413/55967de5-bd0e-47b4-bef0-a7a4754595ba)

**Comment by Padawg** [comment]
I also have this happening.

**Comment by erebus04** [comment]
I have the same problem

**Comment by liciana24** [comment]
@NordicRavn @SoftFever i dont see a linked pr but still have this happen on 2.1.1
