### ISSUE TITLE
Auto-arange moves part off plate to bottom left of screen.

### ISSUE THREAD

**Issue by TexZeTech** [SoftFever/OrcaSlicer#3515]
### OrcaSlicer Version

1.8.1, 1.9.0

### OS version

Manjaro

### Additional system information

Operating System: Manjaro Linux 
KDE Plasma Version: 5.27.10
KDE Frameworks Version: 5.113.0
Qt Version: 5.15.11
Kernel Version: 6.1.69-1-MANJARO (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-3770K CPU @ 3.50GHz
Memory: 15.6 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1080/PCIe/SSE2

### Printer

Custom profile. #Customized Robo3dR1+

### How to reproduce

1. have multi-build plates.
2. place two objects on build plates. one on a separate build plate and the other on the last.
3. Click the arrange object on the build plate icon on the individual plates.
4. move the 2nd object onto the last built plate.
5. click the arrange object button.
6. ?????
7. the 2nd part moves off the build plate into the bottom left.separate

### Actual results

![image](https://github.com/SoftFever/OrcaSlicer/assets/7254540/28ababaa-81c1-443b-b85d-7e24b235a66d)
![image](https://github.com/SoftFever/OrcaSlicer/assets/7254540/5f4215fc-1b60-4d67-9f7e-5e9f861acca4)

### Expected results

To have the parts auto-arranged on the same plate.

### Project file & Debug log uploads

[log.zip](https://github.com/SoftFever/OrcaSlicer/files/13850855/log.zip)
[140mm_extrusion_drill_guide.zip](https://github.com/SoftFever/OrcaSlicer/files/13850858/140mm_extrusion_drill_guide.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by TexZeTech** [comment]
I also have multiple materials (mainly for color coding) but I don't think this will be an actual issue in reproduction.
I also have not tested this on windows.

**Comment by TexZeTech** [comment]
I will verify this in v2.0.0/dev build and post results.

**Comment by alexfornuto** [comment]
Please re-open this issue, as it is still a problem in 2.3.1.

**Comment by cmdada** [comment]
I also am able to reproduce this across multiple laptops and windows/arch linux by selecting the anycubic kobra 3, it occurs every time even with a single benchy in 2.3.2.
