### ISSUE TITLE
Auto-orient not working correctly

### ISSUE THREAD

**Issue by wardzin** [SoftFever/OrcaSlicer#3517]
### OrcaSlicer Version

1.9.0

### OS version

Windows 11

### Additional system information

CPU: 11600K
Memory: 32 GB
GPU: 3080 Ti

### Printer

Bambu Lab X1C

### How to reproduce

1. Import [bullet.zip](https://github.com/SoftFever/OrcaSlicer/files/13851310/bullet.zip) into OrcaSlicer, it should start on its side.
2. Click Auto-Orient

### Actual results

Nothing happens, the bullet remains on its side.
![image](https://github.com/SoftFever/OrcaSlicer/assets/1664699/dca156e7-31b0-4c19-94a6-073ac62e5a54)

It's also worth noting that even if you "help" it by almost orienting it correctly, it will still fail and start orienting it in strange angles.

### Expected results

The bullet should be turned upright, as this is obviously the correct orientation.
![image](https://github.com/SoftFever/OrcaSlicer/assets/1664699/0f003b54-2df6-406b-b30b-ba52e4aadd4f)

Note that Bambu Studio does actually orient the bullet correctly, so this may be a regression.

### Project file & Debug log uploads

[bullet_project.zip](https://github.com/SoftFever/OrcaSlicer/files/13851327/bullet_project.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by ControllerArts** [comment]
Just adding the information that in version 1.8.1, the feature was working as expected.

**V1.8.1** - Working as expected

https://github.com/SoftFever/OrcaSlicer/assets/20363585/120ba401-d9ad-4d5b-b2b9-571dcce2c44d


**V1.9.0** - Weird and unexpected behavior
the same object from the first video

https://github.com/SoftFever/OrcaSlicer/assets/20363585/9efa38b8-c387-4806-ac62-f3ac06d1165b

default / primitive cube from Orca

https://github.com/SoftFever/OrcaSlicer/assets/20363585/a7a0b798-8b57-4fd8-9295-cbbea367c487

**Comment by MyStoopidStuff** [comment]
I have observed this issue as well, along with auto-rotate.  The models in the pic are some latches for a case I'm [working on](https://www.mystoopidstuff.com/blog/finally-getting-back-to-the-gridfinity-box-for-stuff) (not yet published - but I can post the models in the next few days if it would help). I first dropped them on the plate (dropped them together, but not as a "single object with multiple parts"), and then selected "arrange" (via right the click menu) followed by "auto-rotate". The result would have been an interesting printing experience I think.
![Orca_BFS-GRIDFINITY_1D](https://github.com/SoftFever/OrcaSlicer/assets/38815108/4dcda8c6-edf2-438e-af58-a04c3d8cf41d)

**Comment by CameraRick** [comment]
It isn't working here either, but worked for me in 1.8.1.
To add, when I hit the button I get a little "Orienting..." window in the lower right corner of the screen, for exactly one frame; please mind the quality of the image, I had to make a screen recording to snatch it

![1 2 1_1 2 1](https://github.com/SoftFever/OrcaSlicer/assets/22145913/ff732cc3-f1c0-409d-b169-f2c6665d0a14)

**Comment by brjohnso1** [comment]
I have the same issue on the Mac version (1.8). Auto rotate does nothing. It may be related to the fact that auto-arrange also does nothing on the Mac 1.8 version. Both features work on Bambu Studio.

**Comment by CameraRick** [comment]
Okay, this issue becomes more weird to me. I just wanted to print some part, and suddenly the Auto-Orient works - kinda. I had to do it twice. But on my original test object, it still doesn't work. I recorded a video to show what I mean:

[](https://youtu.be/-UDOjUjDVPg)

**Comment by bbbrown70** [comment]
also broken here on 1.9 with model https://www.printables.com/model/644333-spool-shelf-storage
doesnt work no matter how many times the button is clicked

**Comment by timnolte** [comment]
This still seems to be an issue with more complex models with many overhangs.
