### ISSUE TITLE
Feature request: implementation of "curve smoothing" from SuperSlicer

### ISSUE THREAD

**Issue by Argolein** [SoftFever/OrcaSlicer#3518]
Problem: Models exported from CAD with low/medium resolution are not round.

Example of low poly model:
![Without](https://github.com/SoftFever/OrcaSlicer/assets/52103738/39363930-b892-4cc0-a7b0-182b5257c977)

Super Slicer has this neat little feature:
![image](https://github.com/SoftFever/OrcaSlicer/assets/52103738/32b3d96e-369e-486c-8752-928086ff6b0f)

The result:
![Screenshot 2024-01-06 at 21 44 32](https://github.com/SoftFever/OrcaSlicer/assets/52103738/d074eece-6f7a-4c20-ae39-d43c28d9d158)

Since it's open source, maybe this can be ported over to OrcaSlicer?

**Comment by Eldenroot** [comment]
I didnt know about this
