### ISSUE TITLE
Custom User Interface Accent Color

### ISSUE THREAD

**Issue by Hyperspeed1313** [SoftFever/OrcaSlicer#3520]
**Is your feature request related to a problem? Please describe.**
It would be nice if OrcaSlicer allowed the user to set a customizable accent color for the user interface in Preferences. I'm not a fan of the teal it's currently locked to.

**Comment by Ocraftyone** [comment]
Hmm. Interesting idea..  could be done via a replacement during svg import in BitmapCache. That would possibly require a restart of orca but I don't think that would be unreasonable.

**Comment by TheCorruptedEngineer** [comment]
> just a ps, i did change the color by editing the source code came out looking like this
> 
> ![Image](https://github.com/user-attachments/assets/efa7dae5-f0ed-41d7-84b4-29059c7e8a81)
> 
> it was a pain but worth it in my opinion

Mind sharing how you did it?

**Comment by thayeeboi890** [comment]
> > just a ps, i did change the color by editing the source code came out looking like this
> > ![Image](https://github.com/user-attachments/assets/efa7dae5-f0ed-41d7-84b4-29059c7e8a81)
> > it was a pain but worth it in my opinion
> 
> Mind sharing how you did it?

i did a find and replace on the entire codebase
grabbed colors with an eyedropper like xcolor, and converted the color into multiple formats like hex, rgb, rgba, and a weird rgba in float format which i think is weird.
in the future though i want to make a theming engine for orcaslicer where colors are defined on a json file and would love to contact softfever for help on where all colors are defined.

**Comment by Prazgreen1** [comment]
A theming engine in the future would definitely be a great PR as it would solve theming issues such as the slicer not respecting system theme.

**Comment by thayeeboi890** [comment]
@Prazgreen1 i have begun works on the theming engine
it will be similar to cura, you will be able to change the theme to whatever you want.
i will create a pr once its finished

**Comment by Prazgreen1** [comment]
> [@Prazgreen1](https://github.com/Prazgreen1) i have begun works on the theming engine it will be similar to cura, you will be able to change the theme to whatever you want. i will create a pr once its finished

ty
