### ISSUE TITLE
Pressure Advande strange travel movements 1.4.5

### ISSUE THREAD

**Issue by Stiffler0210** [SoftFever/OrcaSlicer#353]
With version 1.4.5 I can't manage to print a proper PA test, I noticed these strange travel moves to the front.

1st pic is stock 1.4.5
2nd pic is stock 1.4.4
![800](https://user-images.githubusercontent.com/26834671/220946913-1ded9d32-7227-451d-9a92-ec40b6144986.JPG)
![80](https://user-images.githubusercontent.com/26834671/220946920-b2f67e90-fbc4-423d-ac87-ec3d843ed264.JPG)

**Comment by SoftFever** [comment]
Looks like Arachne is doing some "gap fill" thing at the sharp corner. Hence those travel moves.
Though technically it should affect PA testing results.
Can you provide more details on how this failed your test? Preferable with some photos.
