### ISSUE TITLE
WIFI to Flashforge M5 Pro

### ISSUE THREAD

**Issue by Millemus** [SoftFever/OrcaSlicer#3536]
I have a Flashforge M5 Pro With Wifi
is it possible to make it so that I can use wifi without having to create filerbe for a usb key

**Comment by Discorez** [comment]
In version 2.0 of the program there is a profile for this printer and downloading via WiFI works.
I found it on YouTube using this link - https://www.youtube.com/watch?v=2QhjS5pAz_8

**Comment by Millemus** [comment]
it works 100%, on our m5 pro 1000 thanks for the help.

**Comment by YahWhoMtnDew** [comment]
Yeah, I got my hopes WAY up when I came across that YT video, too.  Unfortunately, when I tried 2.0 dev AppImage the only new printer type in the pull-down list was something like "obico," not REMOTELY like "Flashforge" as the video demonstrates!  HUGELY disappointing, to say the least!  I have to wonder at this point if it would even be worth my trying to finger out how to build my own (maybe sketchy on this wimpy Chromebook) - if it's not there either!?!?!?!?

**Comment by jtenniswood** [comment]
There is a test build that I'm using and works perfectly, I don't understand why this isn't in the nightly builds?

**Comment by Millemus** [comment]
I totally agree with you

**Comment by YahWhoMtnDew** [comment]
![IMG_20240308_094953055~2](https://github.com/SoftFever/OrcaSlicer/assets/161763193/ed63dd1e-2525-450b-aee8-c1ded464fc0e)

Here's a shot of what I see - clearly no Flashforge offered there!  Given that I'm working with 2.0 as you were, it's a total mystery to me why I don't have any joy.  It's so UNFAIR!!!  Waaaaaaaaaaaaaaaaaaaaaaaaaaa

**Comment by jtenniswood** [comment]
Yes it doesn't show up for me. Only works on that earlier build. Still
better than copying to a usb key tho!

**Comment by YahWhoMtnDew** [comment]
Well, that's precisely what I'm after: TIRED of the "sneaker-net" thing! So
I'm STILL wondering how I can lay my hands on a version LIKE YOURS!... What
OS are you running, BTW?

**Comment by Millemus** [comment]
https://www.youtube.com/watch?v=2QhjS5pAz_8&ab_channel=RCSchim

watch this youtuber. and it works

![Skærmbillede 2024-03-10 195219](https://github.com/SoftFever/OrcaSlicer/assets/155895652/a8c4c851-ebfe-4d08-9c8e-ed25dd31eb5a)

**Comment by YahWhoMtnDew** [comment]
Well, that's precisely the video that had me running to snag v.2.0 beta for
myself, with HIGH HOPES!  But when I did so, there was NO SUCH OFFERING!  I
posted a pic of the choices I saw, so your similar pic showing something
different begs the question: WHY are we seeing DIFFERENT THINGS in what is
supposed to be the same numbered version????????  I don't see Obico in
yours and I don't see Flashforge in mine!

**Comment by jtenniswood** [comment]
I just don't think it's in the Mac version yet.

**Comment by YahWhoMtnDew** [comment]
Well, now, that DOES bring up a non-trivial detail: are you running Windoze or linux?  I'm certainly NOT on a Muk, as I am seriously allergic to Apples, but I'm going to have to revisit that video to see what OS it seems to be working on!  I didn't even THINK there would be different features based on which OS!?!?!?  Silly me?

**Comment by YahWhoMtnDew** [comment]
Yup - it's Windoze that it's working on.  Not on Mac - couldn't care LESS - but SADLY, NOT on Linux, either!  Dunno if my wimpy little Chromebook has the capacity to try to build my own, but if it doesn't show up pretty soon in the prebuilt offerings, I may have to try to finger out how to do it!  Just waiting at someone else's mercy is PAINFUL!

**Comment by YahWhoMtnDew** [comment]
Just D/Led the latest to check again: STILL NO JOY.  Same as before: Obico but no Flashforge.

How does one push a request like this forward - is this thread at all likely to come to the attention of any of the coders?

**Comment by Millemus** [comment]
I run windows 11
version 23H2 build 22631.3235
![Skærmbillede 2024-03-11 001148](https://github.com/SoftFever/OrcaSlicer/assets/155895652/983c8744-4744-453a-a3a7-4dedf2bdc6e8)


- as of today (6.Feb.2024) this is the newest beta version to contain the "Flashforge" Printertype - it will for sure be in the main Orca release soon.
[https://github.com/iherbak/OrcaSlicer...](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbXlkNnU0RzliX3R3d3llUUVPbGJjakVQOTVHUXxBQ3Jtc0ttSFI1RVI4NDlMREVfOF9fb2NFSkkzd1RyZF9BU2h2dzE1Z2h6SWV6N2k1eTFpTXNqRVZCVVg0Nl9VLXNyZFhsZW96UTlKMlJWLUhKWVlEY09mZG94dGZBZ3ZkNFlQMEtWby10TWJsWEhNUEJybTYxdw&q=https%3A%2F%2Fgithub.com%2Fiherbak%2FOrcaSlicer%2Freleases%2Fdownload%2FV2%2FOrcaSlicer_A0vy.zip&v=2QhjS5pAz_8)     (download the above ZIP and extract for Windows PC)

There's also a mac version:
[https://github.com/iherbak/OrcaSlicer...](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqa056VTlhbDlKNXYzRmtJM0Z4ZDYyWjRCdFRjZ3xBQ3Jtc0tuOUxqakRZWXBCZG8xZDdqd212dzRVbGFXZnRnSjZNek1DNTVLczZBRFpyVURtcE1kNUVYNlRCalVwSHprZC1EVTN4UG9FeDdWRlhKQzBCTXNHMnVSVFAyUUV4N0FfYkp2THVCbkRKRl9mbVhfVXhGdw&q=https%3A%2F%2Fgithub.com%2Fiherbak%2FOrcaSlicer%2Freleases%3Ffbclid%3DIwAR1KyE1_eQlgBOxUEfNy9J7aCZ3DTqRWx4vlb2DPfM6ms4W4aEJfTKZEagA&v=2QhjS5pAz_8)

**Comment by Millemus** [comment]
![Skærmbillede 2024-03-11 002337](https://github.com/SoftFever/OrcaSlicer/assets/155895652/04184667-0a38-4ffa-ad98-e3df1e90acad)

from inside my Flashforge M5 Pro

**Comment by Millemus** [comment]
192.168.0.225
http://192.168.0.225:8080/stream_simple.html

**Comment by Millemus** [comment]
![Skærmbillede 2024-03-11 001148](https://github.com/SoftFever/OrcaSlicer/assets/155895652/e4708b61-fd61-470a-b5c1-d88bd82b8cf5)
![Skærmbillede 2024-03-11 002337](https://github.com/SoftFever/OrcaSlicer/assets/155895652/ac98fefc-e86a-4114-b8bd-f23907b181a8)

**Comment by YahWhoMtnDew** [comment]
Or - it's been resolved - in the latest release?
