### ISSUE TITLE
Color Paint Fill tool broken after 1.9.0

### ISSUE THREAD

**Issue by erlis** [SoftFever/OrcaSlicer#3539]
### OrcaSlicer Version

1.9.0

### OS version

Windows 10

### Additional system information

Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz   4.01 GHz
32.0 GB

### Printer

Voron 2.4

### How to reproduce

The paint fill option is not detecting all edges, so I can't use it now. 

The provided stl is an example. Just select the object and go to the Color Paint Tool, then select the fill option and try to just fill the text... with 1.9.0 it's impossible, you can select the part that IS NOT the text but that's not what I want...  With the previous version this was working

[test.zip](https://github.com/SoftFever/OrcaSlicer/files/13853810/test.zip)

### Actual results

You can't fill just the text, but you can fill the exterior

### Expected results

The text or the exterior both should be able to be filled

### Project file & Debug log uploads

[test_project.zip](https://github.com/SoftFever/OrcaSlicer/files/13853816/test_project.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by cobyn** [comment]
paint is pretty much broken in 1.9 on my machine. my cursor is missing on the sphere tool. and the circle tool will color smaller then my selection.
