### ISSUE TITLE
Arc fitting does not seem to work ( +layer count is not right)

### ISSUE THREAD

**Issue by Theos88** [SoftFever/OrcaSlicer#354]
**Describe the bug**
Hi, arc fitting does not seem to work in your latest version 1.4.5, Bambu studio seems to recognise the circular shape ok and does G2/3 movements . Additionally I noticed that the layer count is not right (1, 2, 4, 6, 7, 9 etc...which does not bother me... :D) 

Thank you for your work!

**3mf File for This Bug**
I tried to upload files for you, but for some reason it didn´t accept the file format. :-(

**To Reproduce**
1. Add cylinder
2. slice with Standard 0.2.. BBLX1C profile and watch the segmented movement of the circular lines
3. compare to Bambu Studio

**Desktop (please complete the following information):**
 - OS: Windows
 - Version SoftFever 1.4.5  Bambu Studio 1.4.2.13

**Comment by SoftFever** [comment]
Looks like this only happens with Arachne engine.
It tends to generate more fragmented arc moves with Arachne.

**Comment by Theos88** [comment]
Okay, you are right. It seems conical circles tend to be fragmented in classic mode, too. The cylinder was no good example (for my particular case.)
