### ISSUE TITLE
Splash Screen Black on MacOS Sonoma (Arm64) on M2Pro

### ISSUE THREAD

**Issue by ajaytanna** [SoftFever/OrcaSlicer#3551]
### OrcaSlicer Version

1.9.0

### OS version

MacOS Sonoma 14.2.1

### Additional system information

Model Name:	Mac mini
  Model Identifier:	Mac14,12
  Model Number:	MNH73HN/A
  Chip:	Apple M2 Pro
  Total Number of Cores:	10 (6 performance and 4 efficiency)
  Memory:	16 GB
  System Firmware Version:	10151.61.4
  OS Loader Version:	10151.61.4

### Printer

Ender3 S1 Pro

### How to reproduce

Launching the program with splash screen enable in preferences, display a blank black box instead of the graphics.

### Actual results

Program launches normally

### Expected results

Diaplay of Splash screen graphics.

### Project file & Debug log uploads

[](url)
[Untitled.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/13855589/Untitled.3mf.zip)
[log.zip](https://github.com/SoftFever/OrcaSlicer/files/13855590/log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by anarsoul** [comment]
Same here on Linux. Sounds like platform-independent bug :)
