### ISSUE TITLE
Unable to Complete Manual Calibration in 1.9.0 for Bambu Lab P1S

### ISSUE THREAD

**Issue by imobe001** [SoftFever/OrcaSlicer#3553]
### OrcaSlicer Version

1.9.0

### OS version

Windows 10

### Additional system information

Ryzen 7 5800X

### Printer

Bambu Lab P1S

### How to reproduce

1. Go to Calibrate
2. Click either Flow Dynamics or Flow Rate
3. Click "Manual Calibration" and let the calibration print finish
4. Unable to ever click the "Next" button.

### Actual results

Cannot complete manual calibration for Flow Dynamics of Flow Rate for the Bambu Lab P1S.  The 1st calibration print does print, but then I can never click "Next"

### Expected results

Should be able to complete manual calibration.

### Project file & Debug log uploads

N.A

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by bsrotten** [comment]
I have the same issue when doing a automatic calibration, it completes to 100% and then no NEXT button to continue with.
