### ISSUE TITLE
Unable to export filament preset

### ISSUE THREAD

**Issue by lin-ycv** [SoftFever/OrcaSlicer#3554]
### OrcaSlicer Version

1.9

### OS version

Windows 11

### Printer

V400

### How to reproduce

1.Export Config
2.Filament Presets

### Actual results

Missing options to export
![image](https://github.com/SoftFever/OrcaSlicer/assets/60565737/fbf7cf94-697d-4f87-b7a4-febad3bc82af)
![image](https://github.com/SoftFever/OrcaSlicer/assets/60565737/0bcb2931-dd00-4cd7-ae0f-c805f3072bf2)

### Expected results

Have options like when exporting other presets
![image](https://github.com/SoftFever/OrcaSlicer/assets/60565737/c67f2012-8993-419a-9c1a-209ea60c3873)

### Project file & Debug log uploads

UI design issue, not a project or a crash

### Checklist of files to include

- [X] Log file
- [x] Project file

**Comment by tlhintoq** [comment]
Confirmed on Win10x64 as well.

**Also note:**
If you have Orca on a secondary monitor, the dialog jumps to the primary after you tick a radio button.  IE: at the point it would repaint with the options appropriate for the button you ticked.
![Snag_4c588d4](https://github.com/SoftFever/OrcaSlicer/assets/11351506/a9f5e869-6134-4920-a4f4-194993e63e5a)

**Comment by Altblechkutscher** [comment]
I've also experienced that issue.

**Comment by kiesan88** [comment]
Confirming same issue (Filament presets and Filament bundle)

**Comment by hannut** [comment]
Same here. Version 2.0.0 Linux AppImage

**Comment by talentedmrripley** [comment]
This issue is ongoing in 2.1

**Comment by timboll** [comment]
still an issue for me.
