### ISSUE TITLE
V1.9 Support being printed as a solid (100% infill)

### ISSUE THREAD

**Issue by lin-ycv** [SoftFever/OrcaSlicer#3556]
![image](https://github.com/SoftFever/OrcaSlicer/assets/60565737/b83831d0-30ce-41be-8104-ff4afba5542e)

**Comment by lin-ycv** [comment]
Same issue as #1303

**Comment by lin-ycv** [comment]
works fine if the tree type is default, but default doesn't work with adaptive layer height

**Comment by Noisyfox** [comment]
Could you upload the project?

**Comment by lin-ycv** [comment]
Here's the project file
[SolidSupport.zip](https://github.com/SoftFever/OrcaSlicer/files/13926400/SolidSupport.zip)

**Comment by Noisyfox** [comment]
Change base pattern to Default, or increase the Base pattern spacing to some value like 1mm.
![image](https://github.com/SoftFever/OrcaSlicer/assets/1537155/c846ab86-8c80-4f51-8050-733d92e90f16)

**Comment by lin-ycv** [comment]
Cant use default, because it doesn't support adaptive layer height, changing the base pattern spacing did the trick.

I think `Tree Strong` and `Hybrid` should also have a suggestion message like `Slim`, for changing the spacing
![image](https://github.com/SoftFever/OrcaSlicer/assets/60565737/d08c01d6-4165-4088-a3a4-0f7b36865839)
