### ISSUE TITLE
Acceleration values not calculated in speed visualization 

### ISSUE THREAD

**Issue by hutje** [SoftFever/OrcaSlicer#356]
**Describe the bug**
When changing the acceleration values, the visualization for the color scheme are not being used in the calculation for the speed.
The slicing is correct and the time is right, but not in the speed visualization.

**3mf File for This Bug**
[Final Top twist container simulation speed not correct.zip](https://github.com/SoftFever/BambuStudio-SoftFever/files/10818985/Final.Top.twist.container.simulation.speed.not.correct.zip)

![image](https://user-images.githubusercontent.com/15308350/221043171-07f14914-9592-4c3a-b9b4-0efd8ca40545.png)
![image](https://user-images.githubusercontent.com/15308350/221043258-92849fbd-79f3-4819-878b-3116c82ea126.png)
![image](https://user-images.githubusercontent.com/15308350/221043316-7a4eb182-158d-45ca-b8a3-239dd0c512b4.png)

**Desktop (please complete the following information):**
Windows 10 - BambuStudio SoftFever (v1.4.5)

**Comment by psiberfunk** [comment]
I’m not sure this is a bug per se , it’s just a feature (modeling acceleration behavior of the printer ) that doesn’t exist in the preview ?

**Comment by SoftFever** [comment]
The visualization is for speed only per design.

**Comment by hutje** [comment]
When changing the max volumetric speed, the visualization changes accordingly... Seems to me acceleration would also be important to give a good visualization of the speed you are actually get during printing...

**Comment by psiberfunk** [comment]
I think what he’s asking for @SoftFever is that the speed display model the expected effects of acceleration on speed such that you’d see the expected speed gradient on a given layer, as it would appear in reality.

presently there is an assumption that the acceleration is instantaneous in the speed display .

**Comment by psiberfunk** [comment]
To clarify , this is clearly a new feature and the display would have different troubleshooting purposes .  If you implemented this , You would probably want to add a totally new visualization type like : “Speed, with accelerations”

**Comment by psiberfunk** [comment]
> When changing the max volumetric speed, the visualization changes accordingly... Seems to me acceleration would also be important to give a good visualization of the speed you actually get during printing...

This is because the GCODE for feed-rate actually changes in this case.  What you’re asking for is to visualize not just the GCODE setting in this case but ALSO to model the impact the currently set acceleration and jerk would have on the line drawn.  It’s a much more complex thing because you have to make additional look backs to find the present acceleration and additional modeling of speed over visualization segments , and then decide at what resolution you should model those things .

**Comment by hutje** [comment]
Thanks for the explanation. Didn't think about that.
