### ISSUE TITLE
support_critical_regions_only option not visible in slicer UI

### ISSUE THREAD

**Issue by OmegaModr** [SoftFever/OrcaSlicer#3566]
### OrcaSlicer Version

1.9.0

### OS version

Windows 11

### Printer

Artilery sidewinder X2

### How to reproduce

1. Go to support
2. Enable supports
3. Option not available between "On build plate only" and "Remove small overhangs"

### Actual results

The option is missing, adding the option to the json profile appears to be working.
![Screenshot 2024-01-08 195650](https://github.com/SoftFever/OrcaSlicer/assets/9103074/51e957b0-ec5f-4429-9020-7c8eab9a6899)

### Expected results

The option should be there

### Project file & Debug log uploads

[log.zip](https://github.com/SoftFever/OrcaSlicer/files/13865287/log.zip)
[Midde_Finger_Pot_V2.zip](https://github.com/SoftFever/OrcaSlicer/files/13865288/Midde_Finger_Pot_V2.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by Noisyfox** [comment]
This option is not available for default/organic tree style.

**Comment by OmegaModr** [comment]
Mea culpa, was not aware of that fact - can disregard this ticket then.
