### ISSUE TITLE
Lightning infill with sparse infill width set to 0 causes "divide by zero" fatal error

### ISSUE THREAD

**Issue by Snelso91** [SoftFever/OrcaSlicer#3567]
### OrcaSlicer Version

1.9.0

### OS version

Windows 10

### Additional system information

CPU: AMD Ryzen 7 3700X
RAM: 32GB
GPU: Nvidia RTX 3060

### Printer

Bambu Lab A1

### How to reproduce

1. Go to the Strength tab, then infill, and change the sparse infill pattern to Lightning
2. Go to the Quality tab, then line width, and change the sparse infill width to 0 (which should mean it uses the default line width)
3. Try to slice a print, it will give an error and will fail to slice.

### Actual results

The error given is:
```
A fatal error occurred: "Divide by zero"
Please save your project and restart the application.
```
![image](https://github.com/SoftFever/OrcaSlicer/assets/78712321/466beaac-9f3a-4a2f-9cad-7810afde1faf)

This same exact error also happens with Bambu Studio 1.8.2.56 if you follow the same steps.

The error does not occur if you do not use lightning infill, or if you use a line width other than 0.
For example using a line width of 0 with the "line" infill type works fine, and using a line width in either absolute (0.42mm) or percent (105%) terms with lightning infill also works fine.

### Expected results

The object should slice using the default line width field, as it does when using infills other than lightning.

### Project file & Debug log uploads

[cube lightning infill bug.zip](https://github.com/SoftFever/OrcaSlicer/files/13865663/cube.lightning.infill.bug.zip)
[debug_Mon_Jan_08_19_45_22_21204.log.zip](https://github.com/SoftFever/OrcaSlicer/files/13865664/debug_Mon_Jan_08_19_45_22_21204.log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by igiannakas** [comment]
Fixed in the PR above. Please test and report back :)

**Comment by Snelso91** [comment]
@igiannakas thanks for the fix - could you provide some details on how I should test this fix from a user perspective (as I am not a developer so I'm not familiar with testing github commits)?

My guess is that the simplest way would be to download a portable version of orcaslicer 1.9.0 (so I don't have to overwrite my installed version), download your patched Generator.cpp file from the commit and overwrite the portable install's Generator.cpp file with the patched file, then see if the issue is gone?

**Comment by igiannakas** [comment]
Sure thing, download the portable version from here, at the bottom of the page, and just use it as normal. Nothing more, the patch is applied in the portable file. https://github.com/SoftFever/OrcaSlicer/actions/runs/7466667672

**Comment by Snelso91** [comment]
@igiannakas thanks, I can confirm that build works - it doesn't throw an error when slicing with lightning infill and the infill width set to 0, and uses the infill width is the same as the default width value, as expected.

Should I close this issue now that the fix is confirmed, or will that be done automatically once it is approved for merging into [SoftFever:main](https://github.com/SoftFever/OrcaSlicer/tree/main)?

**Comment by igiannakas** [comment]
Yeap you can close it to save the admin later, at some point the bug fix will be rolled into the next release.
