### ISSUE TITLE
Painting and manual suport drawing makes object invisible

### ISSUE THREAD

**Issue by SeriuxExe** [SoftFever/OrcaSlicer#3579]
### OrcaSlicer Version

1.9.0

### OS version

windows 11

### Printer

Ender 3

### How to reproduce

press "L"

### Actual results

object and build plate becomes invisible

### Expected results

not become invisible

### Project file & Debug log uploads

///

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by Thismadara** [comment]
Hello, same problem with flsun v400

**Comment by mobiobione** [comment]
Same here, X1C.

**Comment by bikerman51** [comment]
Same problem with my win7 desktop, even with the portable edition, but I don't have this issue on my laptop (win 10pro).

**Comment by ryanaukes** [comment]
I am having the same problem. 
Orca Slicer version 1.9.0 running on my laptop (Windows 10 Pro 22H2, AMD Ryzen 7 4800U processor with built in Radeon Graphics)
