### ISSUE TITLE
SoftFever icon is too large on Mac OS

### ISSUE THREAD

**Issue by moebis** [SoftFever/OrcaSlicer#358]
Screenshot shows it all, but basically the SoftFever version of the logo/icon doesn't conform to the standard Mac OS size for these icons, it's too large: [https://imgur.com/a/lw1BLOl](https://imgur.com/a/lw1BLOl)

Installed latest 1.4.5 version too.

**Comment by moebis** [comment]
It also shows large in the launcher once you close the app too: [https://imgur.com/a/wrqUJmg](https://imgur.com/a/wrqUJmg)

**Comment by hliebscher** [comment]
in the launcher only during application start

**Comment by Snicket8247** [comment]
I made a version with the right dimensions if you want to use that.
I also gave it a gradient instead of a solid color since I find it more aesthetically pleasing.

![softfever](https://user-images.githubusercontent.com/89993948/221299995-9b0ec8f3-0efb-4671-bcf9-68a4ac9cf7c2.png)

**Comment by moebis** [comment]
> I made a version with the right dimensions if you want to use that until it is fixed. I also gave it a gradient instead of a solid color since I find it more aesthetically pleasing.
> 
> You can right click the application and press "get info", then simply select the icon in the top right and paste it in.
> 
> ![softfever](https://user-images.githubusercontent.com/89993948/221299995-9b0ec8f3-0efb-4671-bcf9-68a4ac9cf7c2.png)

Thank you. Looks great. FYI, once you launch it the icon goes back to the non-gradient, but at least it stays proportional to the other icons. In a way it's kinda cool, when it's not running it's darker (gradient) and launched it's the lighter solid color. Neat unintentional effect.

**Comment by hliebscher** [comment]
thanks for the png file ;-)
