### ISSUE TITLE
Bug with round (Circular) table

### ISSUE THREAD

**Issue by Maksimius** [SoftFever/OrcaSlicer#3581]
### OrcaSlicer Version

V1.9.0

### OS version

Windows 11

### Additional system information

CPU: Intel core i7
GPU: Nvidia FeeForce 2Gb
Mem: 32Gb

### Printer

Custom delta

### How to reproduce

1. Go to printer settings
2. Select table shape: Circular
3. Click Ok
![photo_2024-01-09_16-46-16](https://github.com/SoftFever/OrcaSlicer/assets/12676332/11b9fecf-858a-4c67-b946-cbf012acf905)

### Actual results
![2](https://github.com/SoftFever/OrcaSlicer/assets/12676332/a567bc31-699b-421b-91c9-7121726f03a3)

### Expected results

Normal table view

### Project file & Debug log uploads

[log.zip](https://github.com/SoftFever/OrcaSlicer/files/13875205/log.zip)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by tastechnician** [comment]
OrcaSlicer Version
V1.9.0

OS version
Windows 10

CPU: AMD Ryzen 7 1700
GPU: AMD RX580
Mem: 16GB

Issue does not occur in previous versions, but occurs with 1.9.0.

**Comment by PeterBeklemishev** [comment]
Same on nightly build.

**Comment by metatron-0** [comment]
This problem is eliminated by choosing a model for the table. You can simply create a plane of the desired diameter.
![Screenshot_1](https://github.com/SoftFever/OrcaSlicer/assets/159989982/b3667a38-f257-42df-ae82-c059b3d4c4f2)
![Screenshot_2](https://github.com/SoftFever/OrcaSlicer/assets/159989982/bf6fe300-a038-427d-bacb-0d1cbd0fa6a3)

**Comment by jmezzacappa** [comment]
This bug still exists in OrcaSlicer 2.1.0. Should this issue be reopened, or should I open a new one?

I tried loading a custom model for the bed, but that only solves the "cosmetic" problem (the appearance of side-by-side beds). The "arrange all objects" feature is still broken.

This is where the "arrange all objects" feature places the models:
<img width="776" alt="image" src="https://github.com/user-attachments/assets/4cad5c40-b847-4877-85cf-e1dcfc272459">
(OrcaSlicer 2.1.0, macOS Sonoma 14.6.1, Apple M1 Pro CPU)

**Comment by TexZeTech** [comment]
> This bug still exists in OrcaSlicer 2.1.0. Should this issue be reopened, or should I open a new one?
> 
> I tried loading a custom model for the bed, but that only solves the "cosmetic" problem (the appearance of side-by-side beds). The "arrange all objects" feature is still broken.
> 
> This is where the "arrange all objects"  (OrcaSlicer 2.1.0, macOS Sonoma 14.6.1, Apple M1 Pro CPU)


I just tried to replicate the bug that was in this bug report and could not replicate in v2.2.0-rc on Linux.

The issue you are talking about "arrange all objects" should have its own separate bug report.

I would also upload the part file you are using, log files & even a project file for others to try and replicate.

**Comment by RandomGgames** [comment]
Still an issue in v2.2.0

**Comment by charlesmeyer** [comment]
Can also confirm this bug still exists.

**Comment by bruce98101** [comment]
Been following this for a while and updating that it's still a bug with OrcaSlicer_Linux_AppImage_V2.3.0.AppImage.
