### ISSUE TITLE
Timelapse prompt disappeared on print confirmation modal in a printer

### ISSUE THREAD

**Issue by Voltmod** [SoftFever/OrcaSlicer#3582]
### OrcaSlicer Version

1.9.0

### OS version

macOS 13.6.1

### Printer

Bambu Lab X1C

### How to reproduce

1. Bambu X1C with microSD card
2. Slice any model using OrcaSlicer 1.8.1 
3. Slice the same model using OrcaSlicer 1.9.0 
4. Send both to the printer using the "Send" button
5. Manually on the printer screen - select the model sliced in 1.9.0 for print and observe the **absence** of the option to enable/disable timelapse
6. Open the model sliced in 1.8.1 and observe the option to disable timelapse

### Actual results

Timelapse is enabled by default without the possibility of disabling it.

### Expected results

A timelaps prompt (check mark) appeared in the modal window of printing details confirmation. 

### Project file & Debug log uploads

[timelapse-issue.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/13875256/timelapse-issue.3mf.zip)
[timelaps-issue-log.zip](https://github.com/SoftFever/OrcaSlicer/files/13875257/timelaps-issue-log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by bbbrown70** [comment]
can confirm and replicate this. without the checkbox on the printer timelapse is **always** enabled and recorded for the model regardless of what was set in orca when sent

**Comment by ccatlett1984** [comment]
Still in issue in latest build ( 2.1.0)

**Comment by theonlytruth** [comment]
duplicate of https://github.com/SoftFever/OrcaSlicer/issues/3640 https://github.com/SoftFever/OrcaSlicer/issues/6297 https://github.com/SoftFever/OrcaSlicer/issues/7913
