### ISSUE TITLE
Retractions in vase mode when Travel distance threshold set to 0

### ISSUE THREAD

**Issue by Richard-Wals** [SoftFever/OrcaSlicer#3603]
### OrcaSlicer Version

1.9.0

### OS version

OS: Windows 10

### Printer

Snapmaker J1S

### How to reproduce

1. Add a primitive cylinder
2. Enable spiralize vase
3. Set Travel distance threshold to 0 in either machine settings or filament settings
4. Slice

### Actual results

![image](https://github.com/SoftFever/OrcaSlicer/assets/130517850/e2f13413-e2e2-4a70-acf9-22973074cb61)

### Expected results

![image](https://github.com/SoftFever/OrcaSlicer/assets/130517850/b2bee65e-4920-4464-a895-cbcf026842bc)
There are no travel moves in vase mode (at least after the initial layers) so there shouldn't be any retractions. 

### Project file & Debug log uploads

[Cylinder.zip](https://github.com/SoftFever/OrcaSlicer/files/13895937/Cylinder.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by igiannakas** [comment]
I've attempted to resolve this here: https://github.com/SoftFever/OrcaSlicer/actions/runs/7489048846

Please download the latest build from the link above and report back if this is resolved.

**Comment by Richard-Wals** [comment]
Yeah this fixes the problem, thank you. I just had a little poke around and this also occurs in Prusaslicer, but not Superslicer.
