### ISSUE TITLE
(optionally) add the bed with calibration marks

### ISSUE THREAD

**Issue by ImagineerNL** [SoftFever/OrcaSlicer#361]
**Is your feature request related to a problem? Please describe.**
Can do it manually each new version, or submit it as a feature request ;)

https://www.printables.com/model/321899-bambulab-slicer-bed-texture-with-calibration-marke/files

![image](https://user-images.githubusercontent.com/62603552/221265864-14a2f233-95a4-4ee0-a393-2a3c498de510.png)

**Comment by keenzkustoms** [comment]
hey mate thanks for using my model :) i have already raised this request so hopefully will see it implemented soon :) https://github.com/SoftFever/BambuStudio-SoftFever/issues/88
