### ISSUE TITLE
Zoom to mouse position breaks the viewport under certain conditions

### ISSUE THREAD

**Issue by liftbag** [SoftFever/OrcaSlicer#3615]
### OrcaSlicer Version

1.9.0 official

### OS version

macOS Sonoma 14.3 Beta 3 (23D5043d)
### Additional system information

CPU: Apple M2 Pro
Memory: 32 GB
Display card: Apple M2 Pro GPU 19 core (Metal 3 supported)

### Printer

Not relevant, slicer issue.

### How to reproduce

The problem occurs both in the prepare and in the preview tabs.

1. Open the slicer
2. Enable Zoom to mouse point in settings.
3. Click on New project
4. Go to any side view, either via the View menu or via the keyboard keys (shortcut 3, 4, 5, 6)
5. zoom with the mouse wheel

### Actual results

The bed disappears from sight and never reappears.
This also happens with a bed populated with objects.
This does not happen zooming from the top and bottom views.
The problem happens in both perspective and orthogonal views.
The problem disappears if Zoom to mouse point is disabled.

### Expected results

Being able to freely zoom without losing the view of the printing surface.
In my case the behavior is systematic, and forces me to close and reopen the slicer.
I had previously notified to a developer on Discord, as I believed it was a specific issue with his builds. But I found out that the latest release also has this bug.

### Project file & Debug log uploads

I am attaching an empty project file, so you can evaluate if there was any setting that triggers the problem.

[Empty.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/13904095/Empty.3mf.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by discip** [comment]
Yes finally!
Thank you for reporting this.
This is a real show-stopper since there is no way to recover from this state. You basically loose all the changes as you have to restart the program.

@SoftFever @Noisyfox @igiannakas @Ocraftyone

thanks in advance

**Comment by discip** [comment]
Yes finally!
Thank you for reporting this.

This is a real showstopper as there is no way to recover from this state. Basically, all changes are lost as you have to restart the program.

@SoftFever @Noisyfox @igiannakas @Ocraftyone

thanks in advance

**Comment by igiannakas** [comment]
Can't replicate it on 14.2.1 M1 Pro. Any tips?


https://github.com/SoftFever/OrcaSlicer/assets/59056762/8d48823c-7c0e-4d02-a143-6803437465bc

**Comment by liftbag** [comment]
> Can't replicate it on 14.2.1 M1 Pro. Any tips? Same with the above project file.
> 

Where do I find the setting to switch from dark to light mode? Although very unlikely, I want to replicate your usage settings, although I don't want to downgrade to 14.2. However, I know that @Noisyfox has the same anomalous behavior.

**Comment by liftbag** [comment]
In this video, you see that something happens at a certain point. The bed slides very far and it is no longer possible to take a close up at the maximum zoom level. When the view disappears it is because I activated the command+5 keyboard shortcut.


https://github.com/SoftFever/OrcaSlicer/assets/14921654/0d4def2c-4f92-4f6d-8333-a7d8059ecb94

**Comment by liftbag** [comment]
To further integrate, OrcaSlicer 1.8.1 works fine.

**Comment by glebsexy** [comment]
I can confirm, also have this issue. macOS 12.6.7, Intel MBP.

**Comment by liftbag** [comment]
> I can confirm, also have this issue. macOS 12.6.7, Intel MBP.

I would say that the macOS version can be excluded.

**Comment by glebsexy** [comment]
I just tested: if you zoom in by pinching the trackpad it  works but if you zoom by scrolling it breaks.

**Comment by liftbag** [comment]
It's starting to be a limiting issue from my point of view. On the bright side, it's teaching me to save my work often :)

**Comment by discip** [comment]
@igiannakas
> Can't replicate it on 14.2.1 M1 Pro. Any tips? Same with the above project file.

1. Press **`Ctrl + (one of 3 - 6)`**.
2. Use your mouse wheel to zoom.

It is still present in the latest builds both for Win & Linux (Manjaro).

**Comment by liftbag** [comment]
I set the mouse wheel to scroll freely (not in steps) to better evaluate when the glitch occurs. It seems that the viewport collapses when the bed is moved away to almost the maximum distance.


https://github.com/SoftFever/OrcaSlicer/assets/14921654/7659d0d2-ac9a-4cda-a18c-e3cf3bb456c3

**Comment by libfitz** [comment]
I have the same issue happening on macOS 14.2.1, Orca 1.9.0, although for me it happens regardless of whether I zoom using a mouse or trackpad.

**Comment by Noisyfox** [comment]
I think this can be reproduced (much more easier) if "zoom to mouse position" is enabled.

**Comment by discip** [comment]
I took it for granted, that everyone uses this as default.
That's why I didn't even think about mentioning it. 😅

**Comment by liftbag** [comment]
> I think this can be reproduced (much more easier) if "zoom to mouse position" is enabled.

Thank you for the tip. I will adopt this mode while the problem is solved, even if zooming on the cursor is definitely more convenient and faster.

**Comment by liftbag** [comment]
> Just tested the 2.0 beta, and the bug still persists. The Zoom to mouse position setting cannot yet be used.

2.0.0 stable too.

**Comment by liftbag** [comment]
The pull request #4844 seems seems to work well.
