### ISSUE TITLE
Crashes when trying to login into Bambu account using AppleID

### ISSUE THREAD

**Issue by Xminus6** [SoftFever/OrcaSlicer#3626]
### OrcaSlicer Version

1.9.0

### OS version

MacOS 14.1.1

### Printer

BambuLab X1C

### How to reproduce

1. Home
2. Login/Register
3. Agree to TOU
4. Press AppleID Button

### Actual results

Crashes immediately

### Expected results

Log into my Bambu account in OrcaSlicer.

### Project file & Debug log uploads

[debug_network_Thu_Jan_11_16_33_30.log.enc.zip](https://github.com/SoftFever/OrcaSlicer/files/13910194/debug_network_Thu_Jan_11_16_33_30.log.enc.zip)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by DrewFitz** [comment]
Having this issue too, commented here: https://github.com/SoftFever/OrcaSlicer/issues/4176#issuecomment-2021634358

**Comment by wkethman** [comment]
I was having the same issue and found a work around that works in MacOS - arm64:

- Uninstall OrcaSlicer by removing it from Applications and removing ~/Library/Application\ Support/OrcaSlicer
- Install OrcaSlicer
- Click Login/Register after installing Bambu Network Plugin
- Click System Browser Login and login
- Click Yes to Syncronization

Not sure why this workflow works and direct Google login doesn't
