### ISSUE TITLE
Automatic rotation of parts no longer works intelligently.

### ISSUE THREAD

**Issue by TheRealDrCarbon** [SoftFever/OrcaSlicer#3632]
### OrcaSlicer Version

1.9.0

### OS version

WIn 11

### Printer

X1 Carbon

### How to reproduce

Place a part with a transition that could normally be turned over and printed without any problems during automatic rotation. This no longer works.

### Actual results

The object remains in its original position after the import.

### Expected results

Automatic rotation should happen. This still works in the previous version 1.8.1.

### Project file & Debug log uploads

not required

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by bbbrown70** [comment]
can replicate with https://www.printables.com/model/644333-spool-shelf-storage . the model is vertical when opened and auto orient doesnt lay it down or rotate it

**Comment by kylek29** [comment]
I thought I was going crazy, I noticed this as well.

It also seems to affect the "rotate part to selected face" .. I got some weird rotations with that, ended up having to manually rotate a part.

**Comment by claymore666** [comment]
I did replicate this on OrcaSlicer 1.9.0 with multiple models, the latest being [Bambu Labs Gear Removal Tool](https://wiki.bambulab.com/x1/troubleshooting/extruder-clog/gear_removal_tool.stl) as mentioned on their Extruder Clog HowTo, basically a open box which can be layed flat.

**Comment by jlo1975** [comment]
I confirm the bug with 1.9.0
auto rotate is erratic

**Comment by GhostTE6** [comment]
I also found this bug with 1.9.0. It didn't happen in previous versions.
