### ISSUE TITLE
Issues with flow rate calibration

### ISSUE THREAD

**Issue by TheChimaira** [SoftFever/OrcaSlicer#3635]
### OrcaSlicer Version

1.9.0.

### OS version

Windows 11

### Printer

Elegoo Neptune 4 Plus

### How to reproduce

I am currently using Orcaslicer for my Elegoo Neptune 4 Plus printer, with PLA. Default flow rate in filament type was 0.98%.

I am following the instructions but am struggling with the outcomes. After the Pass 1, I feel like -5 is the best one, so I apply the formula FlowRatio_old*(100 + modifier)/100: which gives

0,98*(100+(-5))/100 which gave me 0.931. When I enter that value and do pass 2, I get very poor results. Am I overlooking something?

First pass:
![image](https://github.com/SoftFever/OrcaSlicer/assets/60472336/7ab3af6e-d13d-4a61-8513-40251629fa54)

Second pass:
![image](https://github.com/SoftFever/OrcaSlicer/assets/60472336/7b7ecc88-c7e8-4abd-9b2f-a6ff74a88092)

### Actual results

Worse results

### Expected results

Better results

### Project file & Debug log uploads

[Flow.zip](https://github.com/SoftFever/OrcaSlicer/files/13920253/Flow.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by jetmansion** [comment]
I agree there seems to be a bug in the second pass. I checked the flow rate for setting '0' from the first pass which came out to 15.09. If I then leave the flow setting in the filament as is and start the second pass, now the flow rate for '0' is 17.65, much higher than the one from the first pass.
