### ISSUE TITLE
text positioning no longer works

### ISSUE THREAD

**Issue by bbbrown70** [SoftFever/OrcaSlicer#3636]
### OrcaSlicer Version

1.9.0

### OS version

any

### Printer

x1c

### How to reproduce

add text to model, attempt to reposition manually

### Actual results

random numbers are used instead of the input value to the coordinates

![orca-slicer_Dxe2oXqkNX](https://github.com/SoftFever/OrcaSlicer/assets/156445968/18245862-e7bd-4c11-aeeb-6f941ffadfef)

### Expected results

text positioning works like previous versions and bambu studio. text position is relative to object it is placed on.

### Project file & Debug log uploads

can recreate with any primitive and text, not model specific

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by TexZeTech** [comment]
I wasn't able to recreate this in 1.9.0 or 2.0.0 appimages on linux.

I recommend uploading the logs & project file.
