### ISSUE TITLE
Save Filment Preset won't allow options to select

### ISSUE THREAD

**Issue by jxer** [SoftFever/OrcaSlicer#3637]
### OrcaSlicer Version

1.9

### OS version

11

### Printer

a1

### How to reproduce

save preset for filament user preset or preset inside project not selectable

### Actual results

not selectable appears to be defaulting to user preset

### Expected results

button should be selectable

### Project file & Debug log uploads

.

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by AJolly** [comment]
im having this issue on 2.1.1
