### ISSUE TITLE
Have Archimedean Chords use Arachne variable line widths.

### ISSUE THREAD

**Issue by PMilstone** [SoftFever/OrcaSlicer#3639]
**Is your feature request related to a problem? Please describe.**
Archimedean Chords surface patterns use fixed line widths which result in gaps on circles and other shapes.

**Which printers will be beneficial to this feature**
All

**Describe the solution you'd like**
Archimedean Chords surface pattern should start with thin lines, progressively grow until the center is filled, and then remain consistent until the end of the line where it tapers off again at the walls.

**Describe alternatives you've considered**
Different spiral pattern that does not result in surface gaps

**Additional context**
Bottom surface shows the line stops before filling out the full shape because the line width is too big to fit between the walls and itself.
![Archimedean Chords Issue](https://github.com/SoftFever/OrcaSlicer/assets/49994250/a1fbb1a8-81c8-467a-af82-39d375b45c1e)

Here you can see the ramifications of the issue. It messes with the surface finish by leaving gaps where it should be smooth.
![Archimedean Chords Issue2](https://github.com/SoftFever/OrcaSlicer/assets/49994250/1f0ded79-5085-41d6-ae4d-569cbbdd99f9)

**Comment by Soloithz** [comment]
This is important, please address this. First layers do not bond in certain areas because of this. 
![arch infill](https://github.com/SoftFever/OrcaSlicer/assets/132028499/a8b60005-a370-4c26-8a7d-dc233c8ff13c)
