### ISSUE TITLE
Lost Timelapse function

### ISSUE THREAD

**Issue by WimVDK** [SoftFever/OrcaSlicer#3640]
### OrcaSlicer Version

1.9.0

### OS version

Win 11 Pro 23H2

### Additional system information

13900k, 64gb corsair dominator titanium

### Printer

Bambulab X1C

### How to reproduce

1. Slice file
2. Send to printer
3. Select file on printer

### Actual results

No timelapse option present. 

Video: https://drive.google.com/file/d/1s5VzhPTuIctgMZl1lX1S-NR-nNrenmOh/view?usp=sharing

From what i can find this is because the printer thinks the gcode file is not sent from bambu slicer. Which seems accurate with my project file. Loaded the same 3mf file generated entirely from orcaslicer and load it into Bambu Studio, Slice it and send it to the printer (i never use the print option) the timelapse option IS available.

### Expected results

Timelapse option being available on the LCD after sending

### Project file & Debug log uploads

[dragon.zip](https://github.com/SoftFever/OrcaSlicer/files/13923605/dragon.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by WimVDK** [comment]
any idea @lostfever

**Comment by WimVDK** [comment]
> any idea @SoftFever ?

**Comment by WimVDK** [comment]
Additionally i just noticed that thumbnails don't seem to work on the bambu handy app either. But they do work on the printer itself

**Comment by SoftFever** [comment]
For my testing, it works well.
Have you tried the 2.0.0 beta?

![image](https://github.com/SoftFever/OrcaSlicer/assets/103989404/b75480fc-c7df-42bc-bd5b-45913d6013d3)

**Comment by WimVDK** [comment]
What's your settings for the gcode flavor/thumbnail. I'll check.

**Comment by SoftFever** [comment]
use the built-in setting

**Comment by WimVDK** [comment]
I am using the default 1.9.1 settings (Marlin legacy, default thumbnails settings) haven't touched anything. Just wanna verify my settings match yours.

**Comment by WimVDK** [comment]
Here's my settings in OrcaSlicer for the X1C (in regards to thumbnails). With

![image](https://github.com/SoftFever/OrcaSlicer/assets/14872315/560e01d8-7fba-452a-8c56-f039290c7ca4)

The original subject of this post though is the "lost timelapse function", which boils down to any file sent to the printer sd card (via send/send all) does not show the ability to toggle on the X1C LCD to turn timelapse on or off. Seems i deleted that video on my google drive but i can make a new one.

Can't use 2.0.0 beta as that seems to break auto calibration but that's a different issue
![image](https://github.com/SoftFever/OrcaSlicer/assets/14872315/fce64698-8dd6-4fab-8259-6f2c42dfc49a)

**Comment by WimVDK** [comment]
@SoftFever 

Issue persists in 2.0.0 stable. No timelapse (enable/disable) option on X1C LED after sending file to printer

**Comment by Thirtybird** [comment]
This issue is still present in Orca Slicer 2.1.1

**Comment by theonlytruth** [comment]
duplicate of https://github.com/SoftFever/OrcaSlicer/issues/3582 https://github.com/SoftFever/OrcaSlicer/issues/6297 https://github.com/SoftFever/OrcaSlicer/issues/7913
