### ISSUE TITLE
add object labeling to enable skip object feature for failing support material

### ISSUE THREAD

**Issue by timboll** [SoftFever/OrcaSlicer#3642]
**Is your feature request related to a problem? Please describe.**
Sometimes I print objects that include 'elective' support material- i.e. it improves quality of overhangs, but may not be strictly necessary. Sometimes this support material fails, and the spaghetti extrusion gathers and drags through the printing of the part. Given that support material in some cases may not be crucial, and that it runs a risk of destroying a salvageable print many hours in, it would be helpful to expose access to the skip objects feature in BambuLab printers for support material. 

**Which printers will be beneficial to this feature**
E.g. Voron/Klipper based printer/etc...
any printer that supports "Label objects" for object skipping

**Describe the solution you'd like**
I'd like to be able to cancel printing of support material, using the same methods as skipping any other failing object. sometimes i print with support material that is elective, and improves quality of the print, but could survive without as an alternative to losing 10s of hours of print progress on ~50h+ prints. The use case arises when thin organic tree supports go spaghetti, and risk dragging to other parts of the print.

**Describe alternatives you've considered**
I've considered adding a proxy object (i.e. `cube.stl`) a find-and-replace edit to gcode to place the object label before `; FEATURE: Support`, but the Bambu Lab P1S and X1C printers that I'm working with don't support skip object without going through the cloud at present. I've considered a python post-processing script and may find time to attempt that, but I'm also uncertain whether the Bambu machines would accept that and behave accordingly.

**Additional context**

**Comment by ToXIc69** [comment]
cant find the option in my 1.9 install 
+1 for feature

**Comment by jurassicplayer** [comment]
I personally haven't tried it yet, but isn't the feature already in OrcaSlicer?
`Prepare` => `Process` => `Others` => `G-code Output`
https://i.imgur.com/pYBfbRh.png

**Comment by dapetcu21** [comment]
+1 on this? new versions of klipper support object exclusion, which is useful for partially failed prints:
https://docs.mainsail.xyz/overview/features/exclude-objects

**Comment by ThatStella7922** [comment]
> The label objects feature needs a "firmware specific" option as per Prusa Slicer 2.7.0+

Chiming in to say that Orca does not need this with my setup. It works pefectly.

- OrcaSlicer 2.3.0
- Klipper v0.13.0-301
- Mainsail v2.14.0
- Moonraker v0.9.3-116

Basically just make sure your stuff is updated.

# Impromptu guide

## 1. Slicer prep
### Inside OrcaSlicer
Process > Others
<img width="300" alt="Image" src="https://github.com/user-attachments/assets/deb61a7b-159c-4c4c-b2c1-30822604b07f" />

"Label objects" enabled. Don't forget to enable this across all your process profiles in case you change between them frequently.

### 2. Moonraker moonraker.conf
Add this bit:
```ini
[file_manager]
enable_object_processing: True
```
Then restart Moonraker. This enables Moonraker to process any uploaded gcode files for Klipper's usage.

### 3. Klipper printer.cfg
Add `[exclude_object]` to the printer.cfg config file and restart Klipper.

# End results
Once you made all these changes, re-slice your objects and re-upload them. I use OrcaSlicer's upload feature, so I don't have to deal with dragging and dropping files.
> [!NOTE]
> Existing gcode files will *not* be capable of excluding objects. This is because in step 2 we told Moonraker to process objects in gcode files, which only applies to new uploads.

Start a print and you should now see this new icon next to the pause button:
<img width="130" alt="Image" src="https://github.com/user-attachments/assets/fc073a08-4e78-4ebe-be15-676531ecb167"/>

For more details about how to exclude objects now that it's set up, see https://docs.mainsail.xyz/overview/features/exclude-objects#enable-exclude_object-module-in-klipper

**Comment by namalahideaway** [comment]
> 
> For more details about how to exclude objects now that it's set up, see https://docs.mainsail.xyz/overview/features/exclude-objects#enable-exclude_object-module-in-klipper

NO!!

That is object exclusion that stop a part... it is not support specific. did you read his feature request???
