### ISSUE TITLE
Scaling a mirrored object removes the mirroring

### ISSUE THREAD

**Issue by ThorsReign** [SoftFever/OrcaSlicer#3643]
### OrcaSlicer Version

1.9

### OS version

Windows 10

### Additional system information

CPU: 7th gen Intel 7700HQ
GPU: GTX 1060
RAM: 32GB

### Printer

Bambu P1S w/AMS

### How to reproduce

1: Import model
2: Paint model
3: Copy model
4: Mirror the copy
5: Scale the original using the scaling button
6: Scale the copy using the scaling button

### Actual results

The copy will lose the mirroring after being scaled, and will return to original orientation.
![1 Original Model](https://github.com/SoftFever/OrcaSlicer/assets/145937964/7cf08e98-3b8a-4ed8-992c-37123a5881b3)
![2 Copy highlighted](https://github.com/SoftFever/OrcaSlicer/assets/145937964/3028e64b-5c5c-414b-ab4f-1e033c39ab21)
![3 Copy mirrored on X axis](https://github.com/SoftFever/OrcaSlicer/assets/145937964/c3b4e5d5-c8e5-40c4-8bb1-f6a08b5135d8)
![4 Original Scaled](https://github.com/SoftFever/OrcaSlicer/assets/145937964/c2005f19-82fa-4469-b126-a9ec64462718)
![5 Copy scaled](https://github.com/SoftFever/OrcaSlicer/assets/145937964/a87335f2-734c-4d5b-867e-8642bb739ae9)

### Expected results

The mirrored orientation should be preserved, resizing the model should not affect the orientation or mirroring of the model.
[Bug.zip](https://github.com/SoftFever/OrcaSlicer/files/13924682/Bug.zip)

### Project file & Debug log uploads

[Bug.zip](https://github.com/SoftFever/OrcaSlicer/files/13924685/Bug.zip)
[tutk_log_iotc_30196.txt](https://github.com/SoftFever/OrcaSlicer/files/13924688/tutk_log_iotc_30196.txt)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by Noisyfox** [comment]
Yeah that's weird... I could reproduce, will take a look.

**Comment by ThorsReign** [comment]
@Noisyfox @SoftFever This issue was not resolved by this update - I was able to reproduce using the above steps on Orca 1.9,1.

**Comment by Noisyfox** [comment]
> @Noisyfox @SoftFever This issue was not resolved by this update - I was able to reproduce using the above steps on Orca 1.9,1.

It'll be included in 2.0.
