### ISSUE TITLE
Can't add Elegoo Neptune 4 Max

### ISSUE THREAD

**Issue by tlhintoq** [SoftFever/OrcaSlicer#3652]
### OrcaSlicer Version

2.0.0 Dev

### OS version

windows 10

### Printer

Elegoo Neptune 4 max

### How to reproduce

Add printer.
Select Neptune4max as shown
Look in your printer list - Its not there.

![image](https://github.com/SoftFever/OrcaSlicer/assets/11351506/def2d568-172f-41ca-8c1b-8cd826dcf219)

### Actual results

I can add a default Neptune 3 max (as shown in pic)
I can add and customize a Neptune 3 max (N3Max in `---User Presets---`)
But adding an 4 max just doesn't show up in the printer list.

### Expected results

Should be able to add and select a 4 max.

### Project file & Debug log uploads

No project required

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by tlhintoq** [comment]
Hmmm... I wonder if this is similar to the STILL UNRESOLVED
https://github.com/SoftFever/OrcaSlicer/issues/2467#issuecomment-1890548903

Where there's a problem in the JSON higher up the inheritance chain

**Comment by bistory** [comment]
Hi, I tried to reproduce your issue but I wasn't able to...

<img width="557" alt="Capture d’écran 2024-01-14 à 08 03 21" src="https://github.com/SoftFever/OrcaSlicer/assets/108102/7fbc2381-cbcf-4fb2-bc83-78d60195ce8e">

**Comment by tlhintoq** [comment]
Well.... Maybe I'm doing something differently?

Printers before adding:
![Snag_b2a02c1](https://github.com/SoftFever/OrcaSlicer/assets/11351506/ae5cc58c-13f9-43af-b0d0-5f27cab557ce)

Click the sprocket icon next to printer list to get to this dialog
![Snag_b2a84b3](https://github.com/SoftFever/OrcaSlicer/assets/11351506/dd2bc3bb-fa2f-481a-b73d-f0a984512b4f)
Tick the Max4 box then `Confirm`.  Dialog closes.

Then here's the new printer list. {second verse same as the first}
![Snag_b2b491c](https://github.com/SoftFever/OrcaSlicer/assets/11351506/e944db0a-0943-49c8-8a49-32745cbdb749)

Is there a config / file / folder I can zip up and include that might shed some light?

**Comment by tlhintoq** [comment]
There had a been an ongoing problem with the FSON definition for a parent printer this inherited from.
That was fixed in another bug, so this was fixed for free by the upstream bug fix.

**Comment by JPinage** [comment]
For weeks now I can’t get Orca to even work with my N4 Max. Multiple uninstalls and complete work overs. Files won’t transfer over wifi, files off a USB stick reboot my printer. Orca works fine with my N4Pro but won’t with my Max. I can even do work in fluids on my max in the Device tab or Orca and it says all my connections work but I get 502 bad gateway and print host errors, usb uploads reboot my printer, not these options are flawless on my pro.
