### ISSUE TITLE
Set support type per modifier object (allow modifier objects to specify different support)

### ISSUE THREAD

**Issue by motley74** [SoftFever/OrcaSlicer#3658]
**Is your feature request related to a problem? Please describe.**
I would like to be able to add a part modifier and set the support type for that object that is different from main object.

**Which printers will be beneficial to this feature**
Bambu X1C/P1S/P1P, any?

**Describe the solution you'd like**
Would like to be able to set support parameters per object instead of being limited to only global setting. For example, I would like to be able to set support type to Normal by default but then add a part modifier and specify that tree supports be used in that area.

This would allow normal supports be used for areas that can be supported better using normal supports, like large flat areas not far from the build plate; but then specify tree supports be used for areas that would normally require supports to start on the main object instead of the build plate, like tops of openings or overhangs inside an object.

This would allow for cleaner parts, less post processing, and likely less filament usage for areas where supports normally start on a part instead of build plate which are harder to remove cleanly.

A good example is the AMS Riser created by Ben Levi on Makerworld (https://makerworld.com/en/models/19535#profileId-19420). Parts 3 & 4 have openings that would be best supported by tree supports so the supports are not started on the part being printed but also have a large flat area that is only a few mm above the build plate and, imo, are better supported by normal supports as tree supports are problematic when they are that short and require such a large surface area to be supported.

**Comment by jlacroix42** [comment]
That feature is already present in PrusaSlicer IIRC, I was a somehow surprised you can't do this in OrcaSlicer

**Comment by WimVDK** [comment]
Bump

**Comment by lockheed** [comment]
Bump again. That's a pretty critical feature.

**Comment by LancerGM** [comment]
Bump. I am relatively new to Orca slicer, and was pretty satisfied with all the features I discovered. This made me all the more surprised this feature is missing. Given that it would be a very intuitive feature.
For some models, painting all supports manually would be too much work, but auto-generating supports will generate an entire tower just for a tiny feature that did not even need supporting anyway. Being able to exclude just that area would be incredibly convenient.

**Comment by alexfornuto** [comment]
I wouldn't normally add a "me too" comment, except that this issue was closed by robots before being looked at by human maintainers, so being as loud as possible about it seems like the thing to do.

**Comment by handmade0octopus** [comment]
Worth revisiting. Important feature.

**Comment by TexturedGuppy** [comment]
Ended up here looking for this feature, so leaving a comment saying it would be a great feature to have.

**Comment by kk0425** [comment]
Also would like this feature added. It really would simplify a lot of prints.

**Comment by yoru-si** [comment]
Same here, would love this feature in OrcaSlicer, can save some filament and time in the long run.

**Comment by VanUsual** [comment]
I second that!

**Comment by Voxar** [comment]
I needed this feature today. Need to stack the plate with variations of hilts and one of the models need the snug grid to not risk falling off the plate but the other would do a lot better with trees.

![Image](https://github.com/user-attachments/assets/c1f8af08-001f-4e75-85e5-21b1e14bbb66)
![Image](https://github.com/user-attachments/assets/9dcdcc81-e671-40e2-b364-a96d77e15014)

**Comment by Lexxus17** [comment]
Currently struggling with this at the moment. Being able to use different support types in a model would be game changer level amazing!!!

**Comment by confuzled-dev** [comment]
interested in this feature. would solve some workflow problems for me

**Comment by shearographic-beep** [comment]
Further bump, need a 'support' tab in the modifier settings

**Comment by JustinAndersonPM** [comment]
Bump. I'm printing tall models where I'm doing double-wall "support wall loops" on the tree supports for the +9cm vertical reach. But double walls is absolutely NOT needed on the rest of the print.
A simple cube modifier that allowed me to set "support wall loops" for just a portion of the Supports would shave 1-2hrs off these print times.

**Comment by ivorykeys31** [comment]
Bump. With the fact every printer is going multi-material, this is a big feature that's needed.

**Comment by alexfornuto** [comment]
Feel free to add your bumps to #9701 since this PR was auto-closed, to prevent the open one bringing attention to this discussion from also being auto-closed.

**Comment by Atiroocky** [comment]
Bump, would be awesome (time and filament savings) !
