### ISSUE TITLE
Extrusion in the air above the prime tower (V1.9.0, win 10, portable)

### ISSUE THREAD

**Issue by andronick83** [SoftFever/OrcaSlicer#3665]
### OrcaSlicer Version

V1.9.0 Official Release

### OS version

Windows 10

### Printer

ELEGOO Neptune 4

### How to reproduce

1. Add filament change
2. Add prime tower
3. Slice

### Actual results

On the last layer, extrusions occur above the prime tower.

![image_2024-01-14_15-48-23](https://github.com/SoftFever/OrcaSlicer/assets/439962/aca5c889-003e-4112-b666-fd5d22f1b71d)
![image_2024-01-14_15-48-24](https://github.com/SoftFever/OrcaSlicer/assets/439962/1da5d813-2e59-4343-8d3f-637c6bd8e0fc)

### Expected results

-

### Project file & Debug log uploads

-

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by bistory** [comment]
Hi,
I saw the same problem on latest build, manual filament swap, enabled prime tower.

<img width="913" alt="Capture d’écran 2024-01-14 à 18 38 40" src="https://github.com/SoftFever/OrcaSlicer/assets/108102/f7dd22cc-b11b-49bd-90d6-133b3eb40dd5">

Here is a project to test...

[Parties Noires boitier avant.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/13932507/Parties.Noires.boitier.avant.3mf.zip)

**Comment by igiannakas** [comment]
This is the ramming action

**Comment by danno131313** [comment]
I am experiencing this issue as well.

> This is the ramming action

This happens regardless if filament ramming is enabled or disabled in printer settings. When enabled it shows a rather large amount, when disabled it shows a single line, but in both cases the amount it extrudes for the last layer is shown in mid-air.

![Screenshot 2024-01-15 120529](https://github.com/SoftFever/OrcaSlicer/assets/4003125/c7978c86-79e6-404c-a8ec-bd39417b1192)
![Screenshot 2024-01-15 120605](https://github.com/SoftFever/OrcaSlicer/assets/4003125/3c0e3279-f570-4b87-915a-df156e8e0a25)

**Comment by Kosmoook** [comment]
I am experiencing the same issues both with my custom config and with any config that isnt using a sort of AMS from Bambulab. This is a showcase of the issue on my custom Vcore profile. 
I am attaching both gcode and 3mf file in a zip. 
[issue.zip](https://github.com/SoftFever/OrcaSlicer/files/14042279/issue.zip)
![image](https://github.com/SoftFever/OrcaSlicer/assets/63173427/f8f1b9df-6f58-4ecc-8145-3c1d8963fdf9)
