### ISSUE TITLE
Invisible text

### ISSUE THREAD

**Issue by real-artswan** [SoftFever/OrcaSlicer#3667]
### OrcaSlicer Version

1.9.0

### OS version

Ubuntu 22.04.3 LTS

### Additional system information

AMD Ryzen 5 PRO 4650G (integrated GPU)

### Printer

Bambu Lab X1

### How to reproduce

1. Change any setting in a profile
2. Create new file

### Actual results

Dialog to transfer changes appears, but changed settings names are not recognizable
![зображення](https://github.com/SoftFever/OrcaSlicer/assets/3417195/c11c4f8b-611d-40b4-aa9d-4906d644c084)

### Expected results

The font must be black (or somehow much darker then background)

### Project file & Debug log uploads

nothing to upload

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by henrivdr01** [comment]
Same here. On Ubuntu.

**Comment by jamincollins** [comment]
Same on Arch Linux with v1.9.0.

**Comment by real-artswan** [comment]
The same on the curent nightly 2.0.0-dev

**Comment by JannikWilhelm** [comment]
Same on Fedora 39, might be related to #3936 and #3675

**Comment by real-artswan** [comment]
very bad after all, half of the cool (overall) UX is broken by this

**Comment by Highcooley** [comment]
Does anybody know if this has been fixed in the meantime? I only see closed issues regarding this topic. Or did the UI improvements also fix the issue?

**Comment by real-artswan** [comment]
fixed to me in 2.1.1
