### ISSUE TITLE
Klipper reports unknown command at start/end of print

### ISSUE THREAD

**Issue by bbinnard** [SoftFever/OrcaSlicer#3672]
### OrcaSlicer Version

1.9.0

### OS version

Windows 11

### Printer

FLSun SuperRacer

### How to reproduce

Klipper displays "Unknown command Start print" at beginning of print, and "Unknown command End print" at end of print. These GCode commands should not be included when Klipper is specified.

### Actual results

Klipper displays "Unknown command Start print" at beginning of print, and "Unknown command End print" at end of print.

### Expected results

Above messages should not occur.

### Project file & Debug log uploads

Problem happens with all files

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by quantumfrost** [comment]
start_print and end_print are customary Klipper start and end macros. You can change it in the slicer: printer settings -> machine g-code

**Comment by bbinnard** [comment]
I specified Klipper as the GCode type months ago. Prior versions of Orca did not display the 2 messages. 

![1](https://github.com/SoftFever/OrcaSlicer/assets/88475689/470c9562-1ee6-449f-9cce-e6c70b0ebf1b)

**Comment by quantumfrost** [comment]
You need to check the machine g-code tab in that dialog.

**Comment by bbinnard** [comment]
You are correct - in that tab I had Start and End statements that were left over from prior use of PrusaSlicer. I removed them.

THanks.
