### ISSUE TITLE
TAB key not working. 

### ISSUE THREAD

**Issue by GAZ082** [SoftFever/OrcaSlicer#3674]
### OrcaSlicer Version

1.9

### OS version

Linux - Gnome 45 Wayland

### Printer

Ender 6

### How to reproduce

Try to tab in the fields and you will find it does not work.
![image](https://github.com/SoftFever/OrcaSlicer/assets/100194/56fa9d53-84a8-4880-911c-c25bec23ddb9)

### Actual results

Nothing.

### Expected results

Cycle through the fields.

### Project file & Debug log uploads

x

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by GAZ082** [comment]
This still happens in 2.0 Beta.

**Comment by EvilGremlin** [comment]
2.1.0 beta, no proper navigation, immense annoyance and waste of time. Personally. i consider lack of proper tab/shift+tab/ctrl+tab/ctrl+shift+tab navigation and broken field order as critical bug. 
Is this Linux-only issue?
