### ISSUE TITLE
Tab titles hidden/same color as background in dark mode, with exceptions.

### ISSUE THREAD

**Issue by GAZ082** [SoftFever/OrcaSlicer#3675]
### OrcaSlicer Version

1.9

### OS version

Linux - Gnome 45 Wayland

### Printer

X

### How to reproduce

Go to any area with section tabs and you will find that one active, the title gets hid.

This does not happen with all.

### Actual results

![image](https://github.com/SoftFever/OrcaSlicer/assets/100194/879a3ab1-3526-455c-a7e0-05ff437af23a)
This is ok!
![image](https://github.com/SoftFever/OrcaSlicer/assets/100194/25f199e9-fc68-410a-b365-da4ce921921b)
Bad again...
![image](https://github.com/SoftFever/OrcaSlicer/assets/100194/925c65af-ce9d-4b69-89ed-5115db854d16)
Notes is ok!
![image](https://github.com/SoftFever/OrcaSlicer/assets/100194/35d142ce-3aa0-4335-a2fb-588aa21a91ab)

On the sidebar, all bad except notes:
![image](https://github.com/SoftFever/OrcaSlicer/assets/100194/15dd58c4-50b7-451b-b53c-149dbf9b9346)
![image](https://github.com/SoftFever/OrcaSlicer/assets/100194/e1ca1247-dd03-471f-96b9-968b209c7f40)

### Expected results

See the tab titles.

### Project file & Debug log uploads

X

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by tlhintoq** [comment]
Seems to work in 2.0 dev

https://github.com/SoftFever/OrcaSlicer/assets/11351506/6d636ae5-dfcd-4f34-819e-5d5ec00f6995

**Comment by GAZ082** [comment]
Thanks @tlhintoq . Is this in Linux, Gnome 45 Wayland?

**Comment by tlhintoq** [comment]
I'm confused... Either this bug was renamed or I replied to the wrong bug.
That video was for a bug about tabbing from field to field not working - the video shows that focus does correctly shift from field to field.

So did I post to the wrong bug, or is this the same bug with an updated description+title?

**Comment by GAZ082** [comment]
> I'm confused... Either this bug was renamed or I replied to the wrong bug. That video was for a bug about tabbing from field to field not working - the video shows that focus does correctly shift from field to field.
> 
> So did I post to the wrong bug, or is this the same bug with an updated description+title?

You replied in the wrong issue :D

**Comment by tlhintoq** [comment]
Ok.  I'm a dork

**Comment by henrivdr01** [comment]
I experience the same issue.  Ubuntu 22.04, Gnome.
I will get the detail on version etc.

**Comment by GAZ082** [comment]
Bad bot!
