### ISSUE TITLE
Add plate-based plateholders for filenames, etc

### ISSUE THREAD

**Issue by arrisar** [SoftFever/OrcaSlicer#3678]
**Is your feature request related to a problem? Please describe.**
When naming an output file for upload, there are several useful placeholders, such as `{input_filename_base}`. However, this does not allow us to set up more complex multi-plate files with easy naming conventions.

**Which printers will be beneficial to this feature**
All printers that are connected for direct uploads.

**Describe the solution you'd like**
Introduce some new placeholder parameters, such as `{plate_name}` and potentially others for better naming convention support. Ability to slice and upload multiple plates at a time wouldn't hurt either 😅 

**Describe alternatives you've considered**
I've done my best to investigate the Orca and Prusa docs, but I'm also human, so I may have missed an existing solution or workaround.

**Additional context**
Here is an example of multiple plates I've set up for a given project (in this case the DUMMY 13 by Soozafone).

<img width="855" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/846173/979c34b5-6d2f-4fbe-bd20-cfab9d2b2459">

**Comment by arrisar** [comment]
OK further, deeper diving into the other issues in the Github revealed that there is _already_ a variable for this, it simply isn't documented (as far as I can tell). In which case, the premise of this issue would be to document this and any other available placeholder _somewhere_.

The only two locations I'm aware of for this reference are the following:

- https://wiki.bambulab.com/en/software/bambu-studio/placeholder-list
- https://help.prusa3d.com/article/list-of-placeholders_205643

**Comment by tlhintoq** [comment]
I just guessed at the variable name based on other names.  
I guess I got lucky-been doing this for a while now.
![image](https://github.com/SoftFever/OrcaSlicer/assets/11351506/829a74df-f89b-477b-99a5-6fd22594849d)
