### ISSUE TITLE
Too many solid infill layers with no way to adjust

### ISSUE THREAD

**Issue by Joseph-Goergen** [SoftFever/OrcaSlicer#3683]
### OrcaSlicer Version

1.9.0

### OS version

Mac os M1 pro(arm)

### Printer

Bambu p1p

### How to reproduce

1. Insert primitive box as a slicing model
2. modify top layer and bottom layer settings to 1
3. Slice and observe the solid infill layers

### Actual results

There are too many solid infill layers when slicing and want control of top/bottem layer thickness

### Expected results

For there to be only 1 layer on top/bottom when I tell it to after infill. Theres a specific model that I was using that only used 96 grams of filament in 1.8.1. After updating to 1.9.0 it jumped to 111 grams. When observing and testing, modifying the top/bottom layer did not change the amount of filament being used and noticed the high amount internal solid infill being used.

### Project file & Debug log uploads

[Cube.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/13938415/Cube.3mf.zip)

### Checklist of files to include

- [ ] Log file
- [x] Project file

**Comment by kisslorand** [comment]
Set "Top shell thickness" and "Bottom shell thickness" to 0.

**Comment by Joseph-Goergen** [comment]
@kisslorand Thanks!
