### ISSUE TITLE
Latest 1.9 .0-dev With K1 Max, camera monitor flickers.  

### ISSUE THREAD

**Issue by burtbick** [SoftFever/OrcaSlicer#3689]
### OrcaSlicer Version

1.9.0-dev

### OS version

Pop! OS 20.04

### Additional system information

CPU: AMD Ryzen 5 2400G with Radeon Vega Graphics × 4
Memory: 30.3 GiB
Graphics Card: dvanced Micro Devices, Inc. [AMD/ATI] Raven Ridge [Radeon Vega Series / Radeon Vega Mobile Series]

### Printer

Creality K1 Max

### How to reproduce

Connected to printer via IP.  
Select Device tab.
Note that while the camera works there is an annoying image flicker that is not present when using Creality Print.
Also note that the printer is not yet rooted, so this is the latest stock Creality FW as of 01/15/24

### Actual results

Hard to show a screen shot,   The image has a bunch of flickering that is pretty consistent but changes frequency and sometimes will clear up for a second or two.   This is without printing anything.

### Expected results

Camera image should not be flickering.

### Project file & Debug log uploads

[camflickerbug.zip](https://github.com/SoftFever/OrcaSlicer/files/13942202/camflickerbug.zip)
[logs.zip](https://github.com/SoftFever/OrcaSlicer/files/13942227/logs.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by mttr402** [comment]
I'm using linux mint 20.3 Una. In firefox there is no flicker but using Orca or Chrome Version 120.0.6099.129 (Official Build) (64-bit) it is there. The frame rate is constantly changing.
