### ISSUE TITLE
Add Printer Model Creality Ender 3 S1 Plus

### ISSUE THREAD

**Issue by mandaponk** [SoftFever/OrcaSlicer#3707]
Is your feature request related to a problem? Please describe.
when looking through printers on the selection there is no ender 3 s1 plus

Describe the solution you'd like
addition of printer to the list
ender 3 s1 plus

Describe alternatives you've considered
a choice to do 300mm x 300mm bed option

**Comment by r3dka** [comment]
I second that - PLUS 0.6 nozzle, as we can use it with Ender 3 S1 Plus
