### ISSUE TITLE
Enable / disable dark mode

### ISSUE THREAD

**Issue by suchabadperson** [SoftFever/OrcaSlicer#371]
I would like to propose the possibility of including a box in the preferences menu to be able **to enable or disable dark mode** without depending on the OS.

**Comment by Ibot-11** [comment]
There is already a box. As far as i know this is already independent from the os.
![image](https://user-images.githubusercontent.com/84148069/221368170-533e260f-6aa6-41af-a14f-7aa1fcbbd1df.png)

**Comment by suchabadperson** [comment]
That's true! It seems that macOS version lacks that feature. I wonder if it would be possible to include it.

**Comment by jimdoescode** [comment]
Sorry to resurrect this but there's still no dark mode option in OSX. Are there any plans to add this?

**Comment by reevo1985** [comment]
Would like to also add there is no dark mode on Linux so this is a Windows only feature unfortunately.
