### ISSUE TITLE
Wifi printing not working with sonicpad any more 

### ISSUE THREAD

**Issue by JaredThatcher8** [SoftFever/OrcaSlicer#3710]
### OrcaSlicer Version

1.9

### OS version

windows 10

### Printer

Ender 5 s1 

### How to reproduce

goto the wifi connection button, type in hostname or IP address, hit test 

### Actual results

Could not connect to OctoPrint: curl:Timeout was reached:
Connection timed out after 10001 milliseconds
[Error 28]
Note: OctoPrint version at least 1.1.0 is required.

### Expected results

connect to the sonic pad for wifi printing

### Project file & Debug log uploads

[bracket.zip](https://github.com/SoftFever/OrcaSlicer/files/13957866/bracket.zip)

[crash_Tue_Jan_16_17_23_00_0.zip](https://github.com/SoftFever/OrcaSlicer/files/13957888/crash_Tue_Jan_16_17_23_00_0.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by EB2k05** [comment]
Same issue on my P1S
