### ISSUE TITLE
1.9.0 Selected Model not visible - Paint On Seams/Supports 

### ISSUE THREAD

**Issue by jbeardon** [SoftFever/OrcaSlicer#3714]
### OrcaSlicer Version

1.9.0

### OS version

Windows 11

### Printer

P1P

### How to reproduce

Select model.
Select any of the 'paint on' modes - seams, supports etc

### Actual results

Selected model disappears.

### Expected results

Selected model should be the only one visible.

### Project file & Debug log uploads

[log.zip](https://github.com/SoftFever/OrcaSlicer/files/13961154/log.zip)
[Cube.zip](https://github.com/SoftFever/OrcaSlicer/files/13961190/Cube.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by Noisyfox** [comment]
This has been fixed in latest nightly build.

**Comment by CaptainRoot** [comment]
#3758 Still present in 1.9.0 Release

**Comment by KuroObi72** [comment]
Problem immer noch da!!! Bei Nähte, Stützen und Farben nur grauer Bildschirm
