### ISSUE TITLE
Backport Draft Shield support from Prusa Slicer

### ISSUE THREAD

**Issue by ucirello** [SoftFever/OrcaSlicer#3718]
**Is your feature request related to a problem? Please describe.**
Up to BL X1/P1 series, there was no need for draft shields. However, OrcaSlicer support more printers than BambuStudio, and among them are open-frame printers.

**Which printers will be beneficial to this feature**
All ABS/ASA capable Artillerys, BIQUs, Comgrows, Voxelabs, and Flashforge Adventurer 5M, at least some of the RatRigs, all ABS/ASA capable Elegoo Neptunes, AnkerMake M5/C, All ABS/ASA capable Anycubics, etc.

**Describe the solution you'd like**
Back port the "Draft Shield" option from Prusaslicer - or at least, add a modifier to the skirt height definition that allows me to set the whole height automatically.

**Describe alternatives you've considered**
I can achieve the same behavior manually, but if I change layer height for instance, I have to re-slice, get that number, and manually feed into the form. 

**Additional context**
No additional context necessary.

**Comment by Eldenroot** [comment]
+1

**Comment by ucirello** [comment]
ping - for freshness.

**Comment by debemdeboas** [comment]
ping - for freshness.

**Comment by epicylon** [comment]
#1630

**Comment by igiannakas** [comment]
Done, implemented in PR https://github.com/SoftFever/OrcaSlicer/pull/5356
