### ISSUE TITLE
Set different presets on plates (plate 01 0.2mm LH, plate 02 0.08mm LH)  

### ISSUE THREAD

**Issue by maizyy** [SoftFever/OrcaSlicer#3723]
**Is your feature request related to a problem? Please describe.**
I have a workflow that I organize all printing files in one 3mf using multiple build plates (this feature is the reason I switched from PS) and I am not only one I think.
Possibilty to use many preset on every one of plates (for example: 0.2 layer height on plate 01, 0.08 layer height on plate 02 etc.)

**Which printers will be beneficial to this feature**
Any printer, but workflow of making and organize projects will be beneficial

**Describe the solution you'd like**
I thought that solution will be someting like editing preset on single plate in Objects tab
Default behaviour will be like is now, but if you want to change preset to whole plate, option will be available in Objects tab and on right clicking Plate Name (Plate 1 etc.)
Another thought is when selecting/changing preset for plate, place a checkbox with 'Change to all plates'

**Describe alternatives you've considered**
I didn't think about alternatives, because there's any i think

**Additional context**
I would help with 3mf's with big projects, that have one big parts that can be slicec with 0,3 layer height but also smaller parts that have to be for example 0,08mm. Every iterations (changing preset) over parts needs to be sliced again and with large parts and not much resources on machine, slicing is kinda long time

**Comment by Panacaguy** [comment]
+1 I've been thinking for a while that this would be a good enhancement. It's easy enough to change one or two parameters between the different plates, but quite often there are many parameters that you might want to set differently for different plates and those happen to be all set correctly in a different profile. It would be nice to be able to select a whole different slicing profile for different plates and still retain the ability to tweak parameters as needed.
