### ISSUE TITLE
Cooling Fan - Fan speed-up time changes fan gcode in custom 'change filament G-code'

### ISSUE THREAD

**Issue by AndiS977** [SoftFever/OrcaSlicer#3724]
### OrcaSlicer Version

1.9.0

### OS version

OS: Win10 Pro

### Printer

Mambu Lab P1P

### How to reproduce

1. Slice a project with a filament change.
2. Export g-code
3. Change Cooling fan - Fan speed-up time to e.g. 0.2
4. Slice again
5. Export again
6. Compare the fan commands in the filament change section

### Actual results

Fan gcode commands in custom Change filament gcode are altered.
Left: Fan speed-up set to 0, right: fan speed-up set to 0.2
![Fan speed-up time fail](https://github.com/SoftFever/OrcaSlicer/assets/83065178/2f5dc1ae-6183-47ed-8f91-fa2e4fd58063)

### Expected results

All fan g-code commands in custom gcodes should remain unaltered as described in the tooltip of the Fan speed-up time input field.

### Project file & Debug log uploads

[Fan speed-up test.zip](https://github.com/SoftFever/OrcaSlicer/files/13969875/Fan.speed-up.test.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by 53Aries** [comment]
Can confirm this. I discovered this same issue yesterday.

**Comment by AndiS977** [comment]
Bug still present in 2.0.0 beta.

**Comment by AndiS977** [comment]
Bug still present in 2.1.0 beta.

**Comment by MrMonkey1302** [comment]
same issue in v2.4.0 dev
