### ISSUE TITLE
Printer based post-processing scripts

### ISSUE THREAD

**Issue by foosinn** [SoftFever/OrcaSlicer#3725]
**Is your feature request related to a problem? Please describe.**

Currently Orca Slicers time estimations are less than ideal. There is an awesome Github project called [klipper_estimator](https://github.com/Annex-Engineering/klipper_estimator) that provides near perfect estimations.

It can be included as post-processor, but only on a per process base. It would be much nicer to have a per printer base.

**Which printers will be beneficial to this feature**

All Klipper based printers.

**Describe the solution you'd like**

Add a post-processing scripts to the machines "Machine G-Code" tab in the printer configuration.

To me it would feel natural that they happen before the process post-processors

**Describe alternatives you've considered**

The only real alternative is to add them to every process. But this means also that a process cannot be shared across multiple printers.

Another theoretical option is that Orca Slicer implements 
klipper_estimator as libary or as a rewrite.

**Additional context**

Thank you for your awesome work!

**Comment by giveen** [comment]
Downside I see that is the tool is written in Rust and Orcaslicer is in C++, so it would require another entire toolchain to compile.

**Comment by hyperlogos** [comment]
I could use this feature for adding a MD5, which I am now having to put into the post-processing scripts for each material...
