### ISSUE TITLE
Flow dynamics calibration method "Pattern" crash

### ISSUE THREAD

**Issue by BlackTeaLeaf** [SoftFever/OrcaSlicer#3726]
### OrcaSlicer Version

1.9.0

### OS version

Windows 11 X64

### Printer

Bambu lab X1C & P1S

### How to reproduce

1.click "Calibration"
2.click "Flow dynamics"
3.select printer
4.click "Manual Calibration"
5.select plate type "Textured PEI Plate"
6.select random "Filament For Calibation"
** 7.select method "Pattern"
8.click "Calibrate"

### Actual results

<img width="904" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/23370842/419ff2cf-faec-48a4-908d-3b1e4c8a7945">

### Expected results

Start calibration

### Project file & Debug log uploads

[debug_Thu_Jan_18_15_24_30_43844.log.zip](https://github.com/SoftFever/OrcaSlicer/files/13973527/debug_Thu_Jan_18_15_24_30_43844.log.zip)

### Checklist of files to include

- [x] Log file
- [x] Project file

**Comment by jintaogao** [comment]
Also happening on 1.9.1

**Comment by tobilab** [comment]
Also happening on 2.0.0-beta

**Comment by Dedoque** [comment]
Same, -- 2.0.0-dev

**Comment by PippyT** [comment]
It's still happening on 2.0.0 stable release. Orca seems to work flawlessly otherwise.

**Comment by Voyex** [comment]
This is occurring in v2.0.0 official release for me as well.

**Comment by truffaut** [comment]
I can confirm I'm also seeing this in the 2.1.0 beta release on MacOS.

**Comment by LouisH98** [comment]
2.1.0 release windows also crashing

**Comment by dvomang** [comment]
This has been non-functional for months now...
