### ISSUE TITLE
More than one 100% density layer on raft

### ISSUE THREAD

**Issue by go1den3ye** [SoftFever/OrcaSlicer#3727]
I'd like to be able to use a raft with more than one layer of 100% like in cura
![image](https://github.com/SoftFever/OrcaSlicer/assets/157007159/e00131a8-ae18-47a2-b30f-43c0cb776c2b)
![image](https://github.com/SoftFever/OrcaSlicer/assets/157007159/9f30fa61-b71a-46eb-9a67-ac11e5d72b5b)

**Which printers will be beneficial to this feature**
FLSUN V400, Creality CR-10s pro

**Describe the solution you'd like**
1 layer of raft does not work with certain larger projects with my printer and PLA+ filament, but when using other slicers like Cura, and having a 100% density, with several layers of raft, everything works fine

**Describe alternatives you've considered**
1 layer raft with first layer density set to 100% doesn't work. alternative has been to use another slicer on certain print projects. However I would prefer to use Orca for all my prints

**Additional context**
I found someone that has previously put in the same request, but it had been closed (case #475 by user Romrider). I have also seen several other people ask about this on reddit and with a few google searches, so I believe this is a feature several users would like implemented

**Comment by RoguishlyHandsome** [comment]
when setting up your Raft... in the Advanced portion, set the base pattern spacing to 0. that should give you the same smooth surface that Cura has. I found this setting by trial and error. If you set the same Top surface Interface layers to 0. You will get the same smooth surface. 
![image](https://github.com/SoftFever/OrcaSlicer/assets/152580872/9a14feea-3415-4dbf-ac99-36b145a789c5)
![image](https://github.com/SoftFever/OrcaSlicer/assets/152580872/72be5aff-ccff-40e7-9af0-4caa0252f8e8)

You must set the Pattern to Rectilinear pattern to get the best results. Give it a go.

**Comment by RoguishlyHandsome** [comment]
I think you may be trying to do a 1:1 setup in Orca from Cura. that may not work the way you want it. If you setup 3 layers in Orca then you will have what orca sees as layer 1 b(bottom) layer 2(Middle) and layer 3(top). 
image1: first layer
![image](https://github.com/SoftFever/OrcaSlicer/assets/152580872/20c13094-427d-4d20-89b1-0b9ea7ce7326)
Image2: second layer
![image](https://github.com/SoftFever/OrcaSlicer/assets/152580872/296c8fe8-e3c3-4574-bc7f-86fb4e570fb2)
Image3: third layer
![image](https://github.com/SoftFever/OrcaSlicer/assets/152580872/1016582d-e92b-4cdb-b5ac-be678df5e64c)

**Comment by RoguishlyHandsome** [comment]
Orca will create the first layer based on the expansion size your stipulated, then the subsequent layers based on the size of the base that it is supporting. Take a look at this.

 

This picture below is at 5mm expansion, so that only applies to the first layers. Take a look at the two other layers and how close they get to the object. I think it does it to save material. I think.
