### ISSUE TITLE
Frame for PA Line Calibration

### ISSUE THREAD

**Issue by Ibot-11** [SoftFever/OrcaSlicer#373]
**Is your feature request related to a problem? Please describe.**
It’s really frustrating to remove the current PA line calibration pattern. The little numbers and lines flying everywhere when you remove them. It's also pretty annoying to clean the plate from all these tiny junks.

**Describe the solution you'd like**
A simple frame around the calibration pattern. Also a single layer base under the numbers, which connect them together.
The same way Ellis new PA calibration pattern does it.
![image](https://user-images.githubusercontent.com/84148069/221368857-91a9a41f-5d1c-418a-896d-3b205ddccb6d.png)

**Additional context**
It would also be nice to have the new pattern from the Ellis Tuning guide. ATM Im testing both and try to compare them. I can’t tell which is better for now.

**Comment by kylek29** [comment]
Yes, please. I just came here for that exact same reason and had the exact same solution. Having the option to choose the Ellis pattern would be a welcome addition.

https://ellis3dp.com/Print-Tuning-Guide/articles/pressure_linear_advance/pattern_method.html
