### ISSUE TITLE
Filament edit page - ramming button not visible (dark theme)

### ISSUE THREAD

**Issue by Eldenroot** [SoftFever/OrcaSlicer#3730]
### OrcaSlicer Version

1.9.0

### OS version

Win 11 64bit

### Printer

A1

### How to reproduce

Go to edit filament page and then to multimaterial tab

### Actual results

![image](https://github.com/SoftFever/OrcaSlicer/assets/778890/ebd93945-4dd8-409f-ae99-9a638a427251)

### Expected results

Ramming should have different color (text, button).

### Project file & Debug log uploads

---

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Eldenroot** [comment]
Still valid

**Comment by yw4z** [comment]
this one is on my list, i will update with Printer settings > Printable area > Set button

also this one was fully fixed on my design branch but we decided to not fully merge it
