### ISSUE TITLE
Bug in default Max Volumetric Speed settings.

### ISSUE THREAD

**Issue by lamarks13** [SoftFever/OrcaSlicer#3736]
### OrcaSlicer Version

1.9.0

### OS version

Windows 10

### Additional system information

Not necessary

### Printer

Creality K1 Max

### How to reproduce

1. Set printer Creality K1 Max (0.6 nozzle)
2. Set Filament to Creality Generic PLA
3. Set Process to 0.24mm Optimal @Creality K1Max (0.6 nozzle)
4. Go to Speed > Advanced > Extrusion rate smoothing and set to a very small number like 0.07.
5. Run Calibration > Max Volumetric Speed > Set parameters 15, 25, 0.5
6. Watch the Total print time SOAR

### Actual results

Without changing step 4, it has a print time of 24 minutes and 4 seconds.  After doing step 4, the print time climbs to 1 day, 10 hours, and 30 minutes.

### Expected results

When running the test outlined in step 5, many values in the slicer are changed to conform to the test.  Extrusion rate smoothing should be included to be set to zero.  It took me 3 hours to find the wrong value I had in my settings.  Turns out it was something completely different from what I understood it to be anyway.  Nothing to protect idiot end users from themselves. ;)

### Project file & Debug log uploads

[Max volumetric speed test (2).zip](https://github.com/SoftFever/OrcaSlicer/files/13985801/Max.volumetric.speed.test.2.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by dstulken** [comment]
This sounds like it's in the same case as the bug I posted earlier - that the fuzzy skin settings aren't disabled for the calibration tests.

https://github.com/SoftFever/OrcaSlicer/issues/4227
