### ISSUE TITLE
[Feature Request] Allow customizations of (or reduce aggressiveness of) viewport camera near / far clipping panes

### ISSUE THREAD

**Issue by tehbiga** [SoftFever/OrcaSlicer#3759]
**Is your feature request related to a problem? Please describe.**
Latest version of OrcaSlicer _(1.9.0)_ has dynamic viewport camera near and far clipping panes.
This is hiding objects I've dragged off the build plate and want to keep in my project, but not slice.

**Which printers will be beneficial to this feature**
Any, but actually only beneficial to the user as they are preparing a print.

**Describe the solution you'd like**
Revert viewport camera clipping pane changes or add a viewport option to make static or customize distances.

**Describe alternatives you've considered**
Only valid alternative to me is reverting to an older version before viewport camera changes.

**Example of a storage bin project**
[Comparison Image](https://i.imgur.com/v3IlBZl.png)

**Comment by jakk2809** [comment]
I agree. I tend to lose off-plate parts depending on the camera angle.

![2024-03-08 06 22 27](https://github.com/SoftFever/OrcaSlicer/assets/7157378/032ed99b-2a5f-495e-af92-699a13ca77dc)
