### ISSUE TITLE
FEATURE REQUEST: Allow editing text once placed so you don't have to make a new text and re-enter size and position

### ISSUE THREAD

**Issue by Photogad** [SoftFever/OrcaSlicer#376]
**Is your feature request related to a problem? Please describe.**
FEATURE REQUEST: Allow editing text once placed so you don't have to make a new text and re-enter size and position

**Describe the solution you'd like**
I'd like to be able to edit text once it is placed so that if I want to add multiple texts, I don't have to create a new one and re-do size, rotation, position, etc

**Describe alternatives you've considered**
There is none!

**Additional context**
![edittext](https://user-images.githubusercontent.com/18505956/221383245-6885fa7c-be09-41d9-a215-ebd56e033882.jpg)

**Comment by chuckkay** [comment]
I posted a similar request on Bambu Studio Github, but probabbly more likely to happen here first
Dynamic Text #1518
https://github.com/bambulab/BambuStudio/issues/1518

After adding text to an object, you are able to edit the text (the actual text) at any time later as long as you don't exit and save. after saving the 3mf file and reopening it, you cannot edit the text (only things like scale rotation etc) but not the actual text. you can break it up into parts which isn't helpful and only gives you a bunch of letters as individual parts..

think of a gift box for example it has.
To: Johnny
Happy Birthday

a month later you open the gift box 3mf file to make a gift box for jane, you have to delete the text that says to: johnny and recreate a new text object that says to: jane additionally you have to try trying remembering the original text size font thickness and depth you used a month ago.

The text should be dynamic and changeable later.

additionally it would be nice if the parts label name which currently defaults to naming as "Text_shape" would incorporate the actual text in the name.
