### ISSUE TITLE
AUTO PAINT SUPPORTS missing.

### ISSUE THREAD

**Issue by Phardbean** [SoftFever/OrcaSlicer#3763]
### Discussed in https://github.com/SoftFever/OrcaSlicer/discussions/3399

<div type='discussions-op-text'>

<sup>Originally posted by **Phardbean** December 31, 2023</sup>
For the love of me, this is the thing that would make me download Orca and donate.  This gives you a base, then you refine it, saves so much time and filament .... jesus.
https://www.youtube.com/watch?v=bHl1UaWyooE</div>

**Comment by Eldenroot** [comment]
It is duplication of this one #1983 https://github.com/SoftFever/OrcaSlicer/issues/2428

**Comment by Eldenroot** [comment]
Bump

**Comment by Phardbean** [comment]
It's not really stale Mr. Bot it's just not understood.

**Comment by Eldenroot** [comment]
Reopen
