### ISSUE TITLE
Bed incorrectly displayed for delta printer

### ISSUE THREAD

**Issue by pmarkiewicz** [SoftFever/OrcaSlicer#3766]
### OrcaSlicer Version

1.9.0

### OS version

Window 10

### Printer

Kossel mini

### How to reproduce

open slicer and select delta printer
This is regression and this happened after upgrade to 1.9.0

### Actual results

see picture

![image](https://github.com/SoftFever/OrcaSlicer/assets/483107/d18c22b6-f2b6-482a-8b46-892d101ad1ac)

### Expected results

bed grid and shadow should be in same place

### Project file & Debug log uploads

[Body12.zip](https://github.com/SoftFever/OrcaSlicer/files/13999463/Body12.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by tastechnician** [comment]
Hi Piotr.
Issue raised in case #3581. Perhaps you wish to transfer your details there.

kind regards,

**Comment by pmarkiewicz** [comment]
Close as there is #3581
https://github.com/SoftFever/OrcaSlicer/issues/3581
