### ISSUE TITLE
"Alternate extra wall" with zero infill causes artifacts

### ISSUE THREAD

**Issue by oleksii-suprun** [SoftFever/OrcaSlicer#3774]
### OrcaSlicer Version

1.9.0

### OS version

macOS 14.2.1 (23C71)

### Printer

Voron 2.4

### How to reproduce

1. Create a new project
2. Right-click on plate -> Add primitive -> Cylinder
3. Enable "Alternate extra wall" at "Strength/Walls"
4. Set infill to 0% at "Strength/Infill"
5. Set top shell layers to 0 at "Strength/Top/bottom shells"
6. Start print

### Actual results

The cylinder printed with extra wall every other layer floating in the air.
![IMG_1551](https://github.com/SoftFever/OrcaSlicer/assets/2777842/7b5b2827-937b-4820-b575-85de888afe41)
![IMG_1550](https://github.com/SoftFever/OrcaSlicer/assets/2777842/4d86e5a0-e31b-46fc-abb8-e140e494b712)
![IMG_1549](https://github.com/SoftFever/OrcaSlicer/assets/2777842/72f410a2-3a28-4039-9d53-cf8500cc2f55)
![IMG_1548](https://github.com/SoftFever/OrcaSlicer/assets/2777842/ccffed7e-58cc-44e0-8211-c7ae8aed410e)

### Expected results

The model printed without artifacts

### Project file & Debug log uploads

[Cylinder.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/14001492/Cylinder.3mf.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by igiannakas** [comment]
Nice one!
