### ISSUE TITLE
Cannot select a different filament in AMS to run the max flowrate calibration

### ISSUE THREAD

**Issue by AdrianGarside** [SoftFever/OrcaSlicer#378]
If you try and change the filament for the flowrate model and then try to calibrate it won't let you - you have to save or abandon what's there. I worked around it by lying about what filament was in slot 1 (so slicing had the right data) and then choosing the correct filament as I went to print.

**Comment by spali** [comment]
Does this still apply to 1.50?
Just did a flow calibration and could select the filament in the "print screen" (there wehere you can disable AMS or the bambu flow calibration just before sending the job).

**Comment by AdrianGarside** [comment]
No I cannot repro this with 1.50.

**Comment by AdrianGarside** [comment]
Closing as resolved.
