### ISSUE TITLE
Seam gap increased in new version 1.9.0

### ISSUE THREAD

**Issue by ruiaraujo012** [SoftFever/OrcaSlicer#3783]
### OrcaSlicer Version

1.9.0

### OS version

macOS

### Additional system information

Macbook Pro M1

### Printer

Elegoo Neptune 4 Pro

### How to reproduce

After updating from 1.8.0 to 1.9.0 the seam gap has been increased in prints, at least, it is much visible now, I've checked prints from 1.8.0 (same print).

### Actual results

Seam gap visible.
![image](https://github.com/SoftFever/OrcaSlicer/assets/16304685/da5c77d6-979c-4ba9-89e3-e5293d47c731)

### Expected results

Seam gap not visible

### Project file & Debug log uploads

[Double Heart Stamp.zip](https://github.com/SoftFever/OrcaSlicer/files/14003085/Double.Heart.Stamp.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by magickarle** [comment]
Same thing on my end . My seams increased enough that I've notice a good difference.
