### ISSUE TITLE
Intelligent "Insert Text" using system variables

### ISSUE THREAD

**Issue by Templar01** [SoftFever/OrcaSlicer#3785]
**This is an enhancement of the recent Embossed Text feature introduced in 1.9 release.**  Not Printer specific.

I was deeply impressed and encouraged by the new Embossed Text feature appearing in 1.9. Here are some thoughts.

When modifying parameters during experiments with various filaments, printers, and model profiles, it would be extremely useful to have the capability to pass both the name and value of each variable into the "Input Text" function. Additionally, having a distinct default font to serve as a visual cue, indicating that the displayed text is derived from a system variable, would be beneficial.

### **Here's how this might work.** 
1) In the "Input Text" function, when a user presses a special character, such as the hash '#' sign, it triggers the display of a variable menu. To distinguish between using the '#' as a literal character and as a symbol for variable access, the software interprets two consecutive '#' characters as the actual character. However, a single '#' is recognized by the slicer as a command to present a menu showing available variables and their current states. Users can then insert a variable into the text by either selecting the desired option from this menu or, if they are familiar with the variable name, by typing the '#' symbol followed by the variable name manually. 

2) During each print operation, if there is a modification in the parameter value, this change will only be updated during the re-slicing process. Introducing a feature named "re-slice," might enhance usability, it is more of a "nice to have" rather than a necessity. Alternatively, providing real-time values, such as timestamps, could be more suitable if updated at the time of printing.

![image](https://github.com/SoftFever/OrcaSlicer/assets/49827456/58854585-0a11-4b1a-871f-d4852560bb2e)
In this example above, it was desirable to note the flow rate when testing different flow rate parameters on the test piece. This was entered manually for the purposes of documenting the sample. This manual operation is not just tedious but prone to human error. 

![image](https://github.com/SoftFever/OrcaSlicer/assets/49827456/a230923d-1029-45f8-94bc-e1505f83679b)
In the example above, the concept of inserting variable names parallels the functionality seen in OnShape's CAD system, which uses a variable table that also supports text overlays. In OnShape, when a user types the hash (#) symbol while entering a numeric value, a menu appears displaying all predefined variables. This approach could be adapted for our purposes.

Link to OnShape's Text Variable Support
[https://cad.onshape.com/help/Content/text-sketch.htm#text-variable](url)

### Other possible useful Global or Systems variables. 
Note Abbreviations Might be needed on most of these. Example abbreviations in parenthesis.
* (DAT) Current System Date and Time(this would be great if it was real time but still useful if it showed the time at slice)
* (LC) Layer count
* (FIL.Prof) Filament Profile Name 
* (PRT) Printer Name
* (PROC) Process Name
* (OBJ) Object or model name
* (MODXY) Model X,Y and Z dimensions
* (MOD.CORD) Model X,Y and Z coordinates on the build plate

### Other considerations
It would also be really helpful is that if it's a value stored in the JSON file, Perhaps a save function could be on the Emboss menu to include in the embossed text function.

### Here's a really big ask... External Variable Table support. 

If we go this far, then it would be nice to be able to create an importable/exportable variable table that we can use from model to model. This would make the Bambu Studio a useful tool let's say for identification of print jobs done in printer farms. Use cases like customer/client name or Job Number would be two that come to mind but anything that lends itself to automated labeling could use this feature too, simply by updating the external file. At print, the file would be pulled into the slicer.

In fact, if it could be linked to a CSV table with Titles to name the field, then import/export wouldn't be needed. This could be done outside Studio thus increasing its extensibility and perhaps even allowing 3rd party apps to interface to billing and production systems.

**Comment by ABalinko** [comment]
Im having the same problem, I like to have a date of print on the bottom of my prints, and its painful to manually type every time
