### ISSUE TITLE
 [Latest dev build issue] One wall only on topmost layer with arachne enabled

### ISSUE THREAD

**Issue by liftbag** [SoftFever/OrcaSlicer#379]
**Describe the bug**
In the latests dev builds, when Arachne wall generator is enabled, the option "Only one wall on top surfaces" produces results only on the topmost layer.

**Expected behavior**
As with the Classic wall generator, each exposed top layer should have a single perimeter.

**Screenshots**

Classic wall generator

<img width="1671" alt="Screenshot 2023-02-26 alle 10 13 04" src="https://user-images.githubusercontent.com/14921654/221402534-44a520f6-33f9-43be-a64f-37b17b2ce2f4.png">

Arachne wall generator

<img width="1671" alt="Screenshot 2023-02-26 alle 10 14 54" src="https://user-images.githubusercontent.com/14921654/221402559-e38fd70f-69fa-415a-a612-68b9d2337121.png">

**Desktop (please complete the following information):**
 - OS: Apple macOS 
 - Version Ventura 13.2.1
 - Bambu Studio SoftFever nightly build 374 build mac x64 93

**Comment by liftbag** [comment]
I just realized the same issue is present in SuperSlicer. To enable the single perimeter on the top surfaces with arachne in SuperSlicer it must be enabled from the classic mode, as with arachne enabled the option is currently greyed out. When you re-enable arachne the option works, but only on the topmost layer.

**Comment by hliebscher** [comment]
@liftbag pls look at #350

**Comment by liftbag** [comment]
> @liftbag pls look at #350

Yes, in the letest dev releases the issue #350 is solved while the single perimeter on top layers is only partially solved.

**Comment by Ibot-11** [comment]
Single wall top surface will be included in the next release
#340

**Comment by SoftFever** [comment]
can you attach a 3mf project file to repro the issue?

**Comment by kvnper** [comment]
This issue also occurs with the setting "Only one wall on **first** layer"

**Comment by kvnper** [comment]
I am additionally having an issue where no top layers at all were getting a single wall.

**Comment by liftbag** [comment]
> I am additionally having an issue where no top layers at all are getting a single wall.

I've changed the title, according to the fact that the issue refers to the latest dev builds. The single perimeter on the bottom and topmost layer with arachne enabled currently works fine on the latest dev build. But the rest of the top layers under the maximum Z height, set the perimeters established in the settings.

**Comment by kvnper** [comment]
> 

ok no problem, although in my opinion i suggest putting it at the start of the title instead of the end

**Comment by liftbag** [comment]
Solved in the build Mac x64 no. 102

<img width="881" alt="Screenshot 2023-03-07 alle 17 48 04" src="https://user-images.githubusercontent.com/14921654/223491861-75f6fab0-cf0c-4b6c-add4-29a3a40c4f03.png">

Thanks a lot! Can be closed.

**Comment by the0bone** [comment]
> I've changed the title, according to the fact that the issue refers to the latest dev builds. 

But it is not just the latest dev Build.
v 1.6.2 have the issue as well.

**Comment by liftbag** [comment]
> But it is not just the latest dev Build. v 1.6.2 have the issue as well.

The post is dated February 26th. I believe it was a development version of 1.6.2.
The issue refers to the fact that Arachne Wall generator broke the single wall on both the top and bottom layers. A fix was later made which is the current way it works.

**Comment by liftbag** [comment]
It seems that PrusaSlicer is finally going to implement this feature in the next release. It would be nice if OrcaSlicer fixes it before then.

https://github.com/prusa3d/PrusaSlicer/issues/10913#issuecomment-1609484522

**Comment by SoftFever** [comment]
> It seems that PrusaSlicer is finally going to implement this feature in the next release. It would be nice if OrcaSlicer fixes it before then.
> 
> [prusa3d/PrusaSlicer#10913 (comment)](https://github.com/prusa3d/PrusaSlicer/issues/10913#issuecomment-1609484522)

I assume you meant "port it after then" ;)
Thanks for the heads up. I'm glad to hear that.
I've been a bit busy with family and work recently, so I have to deprioritize some feature requests.

**Comment by liftbag** [comment]
Seems fixed with the latest 1.7 dev release :)

<img width="1748" alt="Screenshot 2023-08-30 alle 15 45 19" src="https://github.com/SoftFever/OrcaSlicer/assets/14921654/13b1401f-16b8-47e2-86a9-452b7147de98">

**Comment by Jo-Con-El** [comment]
> Seems fixed with the latest 1.7 dev release :)
> 
@liftbag: Could you please close this issue then?  Thanks!
