### ISSUE TITLE
Layer shift when using concentric top surface pattern

### ISSUE THREAD

**Issue by luisillo26** [SoftFever/OrcaSlicer#3796]
### OrcaSlicer Version

1.9.0

### OS version

macOS Sonoma 14.2.1

### Additional system information

MacBook Pro with Apple M1 Pro CPU, 16 GB RAM.

### Printer

Ender 3 Pro

### How to reproduce

1. Set Top Surface Patter to concentric.
2. Slice model
3. Upload model to printer's moonraker.
4. Print model.
5. Layer shift on Y axis happens on layer 20 or 21 when a big portion of top surface with concentric pattern is printed.
6. Issue was confirmed by rotating the model 90 degrees on the xy plane. Layer shift occurred on the X axis after such change.
7. Issue was solved after changing the top pattern to Aligned Rectilinear, slicing and printing the new gcode file.

### Actual results

![IMG_4435](https://github.com/SoftFever/OrcaSlicer/assets/1028540/5a8a789e-f7f2-4e9d-a5d3-7b3423cb4d55)

### Expected results

<img width="756" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/1028540/d44aa9d0-ffea-4d36-8071-e25407e16239">

![IMG_4437](https://github.com/SoftFever/OrcaSlicer/assets/1028540/f9e27b05-c6e4-4094-8282-fc941b5c7e9d)

### Project file & Debug log uploads

[spoon_rest_failed.zip](https://github.com/SoftFever/OrcaSlicer/files/14015080/spoon_rest_failed.zip)

### Checklist of files to include

- [ ] Log file
- [x] Project file

**Comment by t-ihmels** [comment]
I loaded the resulting gcode from OrcaSlicer 1.9.0 into a viewer (https://zupfe.velor.ca/) and didn't see the layer shift.

If you load the gcode your slicer instance generates into a viewer like that do you see the shift?
