### ISSUE TITLE
When selecting Calibration>>Pressure Advance>>PA Line, Model Results with No Lines, Rather Text "PA Test"

### ISSUE THREAD

**Issue by krmtech** [SoftFever/OrcaSlicer#3799]
### OrcaSlicer Version

1.9.0

### OS version

MacOS 14.2

### Additional system information

2023 MacBook Pro M3 18GB RAM

### Printer

BambuLab P1P

### How to reproduce

1. Go to Calibration>>Pressure Advance>>
2. Select PA Line, Model Results with Text "PA Test"
3. No Lines are generated
4. Cannot run PA Line Test

### Actual results

<img width="1009" alt="Screenshot 2024-01-22 at 6 26 18 PM" src="https://github.com/SoftFever/OrcaSlicer/assets/20956210/c0a17cc9-1617-41b6-a6e2-a0c70af4f16d">

### Expected results

Should see model of PA Test Lines

### Project file & Debug log uploads

[debug_Mon_Jan_22_05_26_39_24152.log.0.zip](https://github.com/SoftFever/OrcaSlicer/files/14016521/debug_Mon_Jan_22_05_26_39_24152.log.0.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by derDoc81** [comment]
Just slice ;)

**Comment by krmtech** [comment]
Thanks, just document

**Comment by krmtech** [comment]
Thanks, this was already answered by @derDoc81 .

This step should be added to the documentation as it differs from all of the other calibration models.
