### ISSUE TITLE
Export Configs missing printer/process/filament selector

### ISSUE THREAD

**Issue by mjonuschat** [SoftFever/OrcaSlicer#3803]
### OrcaSlicer Version

2.0.0-dev (2024-01-22)

### OS version

MacOS 14.3

### Printer

Voron 2.4

### How to reproduce

1. Go To "File > Export Configs...
2. Select "Printer config bundle (.orca_printer)
3. Click on "Ok"
![Screenshot 2024-01-22 at 21 57 18](https://github.com/SoftFever/OrcaSlicer/assets/203423/1f04a9e1-725b-426b-8c81-3556080dfa38)

### Actual results

See error "Please select at least one printer or filament."
![Screenshot 2024-01-22 at 21 57 24](https://github.com/SoftFever/OrcaSlicer/assets/203423/221e4c82-eb4f-416d-8ed4-734ef45fd03a)

### Expected results

Option to choose a printer/process/filament, either as a step in the dialog or after pressing "Ok" on a following page/dialog.

### Project file & Debug log uploads

[debug_Mon_Jan_22_21_48_31_11623.log.0.zip](https://github.com/SoftFever/OrcaSlicer/files/14019015/debug_Mon_Jan_22_21_48_31_11623.log.0.zip)

### Checklist of files to include

- [X] Log file
- [x] Project file

**Comment by mjonuschat** [comment]
This seems to happen for all User Presets that I have, independent of Printer/Process/Filament Type.
If I take a system preset and save it as a new preset it seems to work...

**Comment by SethPDA** [comment]
This issue still persists. Re-creating everything based on a system presets is too much hassle. Please fix.

**Comment by Alattice** [comment]
I'm facing the same issue on the Windows 10 1.9.0 version. The checkboxes show up sometimes for nozzle presets but not filament.

**Comment by aicherm** [comment]
This issue is also present in the AppImage (OrcaSlicer_Linux_V1.9.1) on Ubuntu 23.10

**Comment by montyx00** [comment]
Checked in v2.0 stable and the bug still exists

**Comment by Mierscheid** [comment]
Same here.

**Comment by gijsprins93** [comment]
Still all processes are missing. However they are in the correct folder. When i try to import them, it says they already exist.

**Comment by maxim-kukushkin** [comment]
Could someone please re-open this issue? It's still happening on 2.2.0 - any custom printer configuration doesn't appear in the dialog window

**Comment by Mierscheid** [comment]
The developers are not interested in you using printers other than those intended by them. But there is a very simple solution to the problem that works perfectly for me: use Cura!

**Comment by shadowofsoul** [comment]
For those looking for a workaround, in windows at least, the user settings are at users folder: `C:\Users\[user]\AppData\Roaming\OrcaSlicer\user\default`

**Comment by maker-nathan** [comment]
Thanks @shadowofsoul! The config files I found in \user\default were old, but I managed to find my newest one in \user\[9-digit-number]. Hope that helps someone.

Copyable AppData path to save someone a few keystrokes:
%AppData%\OrcaSlicer\user

You can also get there from OrcaSlicer via the top menu (the one just to the right of the File menu) >Help>Show Configuration Folder and then navigate to the user folder from there.
