### ISSUE TITLE
Ironing Inset

### ISSUE THREAD

**Issue by Vantage-DS** [SoftFever/OrcaSlicer#3808]
When using 0.6 Nozzle (untested with 0.4) - Ironing results in jagged edges on narrow surfaces that need de-burring. 

**Which printers will be beneficial to this feature**
P1S/X1C/P1P

**Describe the solution you'd like**
Similar to Cura, an option to inset the ironing distance from the edge.

**Describe alternatives you've considered**
Tested different ironing flow rates, speeds and line spacing, the result is the same - still jagged.

**Additional context**
Example from Cura -
<img width="847" alt="Screenshot 2024-01-23 at 11 38 43" src="https://github.com/SoftFever/OrcaSlicer/assets/42471125/6b914de0-a0a8-4c23-ba2e-bbe5b088841b">

**Comment by Eldenroot** [comment]
+1 good idea"

**Comment by giveen** [comment]
https://github.com/Ultimaker/Cura/blob/36f1932dbb1353f581b55f09624eec8b792243bf/plugins/VersionUpgrade/VersionUpgrade462to47/VersionUpgrade462to47.py#L99

**Comment by Eldenroot** [comment]
It is a good start, it could help with the implementation.

**Comment by arobdog** [comment]
Agree with this idea, see my feature request post here: https://github.com/SoftFever/OrcaSlicer/discussions/2778#discussioncomment-7877100

**Comment by PeteCondliffe** [comment]
I would love to see this too

**Comment by dfosantos** [comment]
https://github.com/SoftFever/OrcaSlicer/pull/7969
