### ISSUE TITLE
BUG: Some windows buttons are missing text (white text on white button)

### ISSUE THREAD

**Issue by Photogad** [SoftFever/OrcaSlicer#381]
**Describe the bug**
Some windows buttons are missing text (white text on white button)

**To Reproduce**
Check the "object type" (modifier) menu when using dark mode

**Expected behavior**
The button text is visible and dark mode not white text on white button

**Screenshots**
![darkmode](https://user-images.githubusercontent.com/18505956/221439216-c70f079f-c287-459b-a309-69d8d5942b90.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 13
 - Bambu Slicer SoftFever 1.4.5

**Comment by rufinus** [comment]
OS: Ubuntu (Dark mode)
Slicer: OrcaSlicer 1.5.0

- Highlighted/Active Tab - Text color equals background color
- Textareas - Text color almost background color

see screenshot
![image](https://user-images.githubusercontent.com/343160/226947762-b36a8217-7038-4b09-8729-b4c0aa1d3133.png)

**Comment by guestisp** [comment]
Same in 1.6.1 for linux

**Comment by Photogad** [comment]
@SoftFever I am not sure if this is fixed in newest 1.6.3 nightly release (I am still on 1.6.2) but as below you can see the buttons still have no text in 1.6.2
![Screenshot 2023-05-21 160633](https://github.com/SoftFever/OrcaSlicer/assets/18505956/bf5f5b20-b866-40a4-a4f8-99506c77d2b2)
