### ISSUE TITLE
Fail to load camera live stram from Babmulab X1 Carbon "Laden Fehlgeschlagen [2] !"

### ISSUE THREAD

**Issue by Sykr0** [SoftFever/OrcaSlicer#3811]
### OrcaSlicer Version

1.9.0

### OS version

Windows 11 Pro, Version: 22H2, Build: 22621.3007

### Additional system information

AMD Ryzen 9 7900X 12-Core Processor               4.70 GHz

### Printer

Bambu Lab X1 Carbon

### How to reproduce

It´s not possible to load the Camera Live Stream.

I´ve early reinstalled the Windows Media Player, reinstall Orca and Bambu Studio.

At Bambu Studio, it works without problems.

At Orca Sliver I get this Fail:

![image](https://github.com/SoftFever/OrcaSlicer/assets/157534624/70c58350-3f16-4062-b878-d74ae7e2f118)

### Actual results

Fail

### Expected results

solve...

### Project file & Debug log uploads

[tutk_log_avapi_13696.txt](https://github.com/SoftFever/OrcaSlicer/files/14029578/tutk_log_avapi_13696.txt)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by RPINerd** [comment]
Having the same issue here on linux, exact same error (but in english lol) and still working fine on Bambu Studio. If this isn't the right log file let me know!
[tutk_log_avapi_312976.txt](https://github.com/SoftFever/OrcaSlicer/files/14045752/tutk_log_avapi_312976.txt)

**Comment by giveen** [comment]
It may end up being more than just the camera.  I cant view timelapse, even going to the nightly which has the latest pulls from Bambu Studio

![image](https://github.com/SoftFever/OrcaSlicer/assets/1180939/32eb8a97-25f5-4c1f-87c9-0e9c0d8c9ab5)
