### ISSUE TITLE
Adding more than one printer on the same host

### ISSUE THREAD

**Issue by garik345** [SoftFever/OrcaSlicer#3812]
**Is your feature request related to a problem? Please describe.**
I can't add two printers that connected to one host, host has one ip, but have two klipper ports for two printers.

**Which printers will be beneficial to this feature**
Klipper based printer

**Describe the solution you'd like**
Please add future to connect two or more printers on the same ip.

**Comment by faith-healer** [comment]
+1 to this, same issue.
adding printer by ip:port will be a solution, as it done in PrusaSlicer.

**Comment by tkunchick** [comment]
<img width="623" alt="Screenshot 2024-03-01 at 8 29 20 AM" src="https://github.com/SoftFever/OrcaSlicer/assets/45150915/d6bc5f7a-5cd8-44d9-a607-b93490308bf6">


This doesn't work for you? That's how I add my rooted K1
