### ISSUE TITLE
Add file name placeholders for `project_file_name_base`, `plate_name`, `plate_num`, `plate_num_2digits`

### ISSUE THREAD

**Issue by filimonic** [SoftFever/OrcaSlicer#3816]
**Is your feature request related to a problem? Please describe.**
Want to automatically organize all plates from single project into klipper subfolder

**Which printers will be beneficial to this feature**
Klipper

**Describe the solution you'd like**
Prepare->Process->Others->Filename format should allow per-project and per-plate placeholders:

- `project_filename_base` - name of project file without extension.
- `plate_name` - name of plate. 
- `plate_num` - ordinal number of plate in project, without leading zeros. Ex: `1`, `2`, `12`
- `plate_num_2digits` - ordinal number of plate in project, 2 digits (leading zero for 1-9). Ex: `01`, `02`, `12`

**Describe alternatives you've considered**
Manual setting file name for each plate is not available too, so manually typing each time

**Comment by LupusTheCanine** [comment]
Is this being worked on?

**Comment by tefracky** [comment]
Is there anything new on this? It would be a very nice feature.
