### ISSUE TITLE
Laggy UI when choosing printers

### ISSUE THREAD

**Issue by MadKiefer** [SoftFever/OrcaSlicer#3818]
### OrcaSlicer Version

1.9

### OS version

Win 11

### Printer

Bambulabs P1S + A1 + A1 Mini

### How to reproduce

1. Add multiple printers (necessary, I guess)
2. Slice something
3. Try to edit text or choosing other printers causes lag / delay, making it incredibly hard to type or hit the print button in the end

### Actual results

Causes lag in the UI, making it very inconvinient to edit text or choose a printer and even press the print button

### Expected results

Nothing, it should not lag.

### Project file & Debug log uploads

None

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Eldenroot** [comment]
Yes, it seems to be a little big longer loading
