### ISSUE TITLE
Orca is sending M106 commands to printer despitecode type is Klipper

### ISSUE THREAD

**Issue by Experiment4** [SoftFever/OrcaSlicer#3828]
### OrcaSlicer Version

1.9.0

### OS version

Linux/Win

### Additional system information

doesnt matter

### Printer

Voron 2.4 and Ender3

### How to reproduce

check gcode - look for m106
check printer setting  - look for code type = klipper

### Actual results

Spamming my command line with M106 unknown

### Expected results

If i choose Klipper as code type, no command are send by the slicer that klipper does not know.

### Project file & Debug log uploads

G1 X171.009 Y156 E.02328
G1 F2999.995
G1 X170.854 Y155.911 E.0052
G1 X170.454 Y155.218 E.02328
M106 S255
G1 X169.221 Y153.082 E.07176
G1 F3000.035
G1 X168.821 Y152.389 E.02328
G1 X168.821 Y152.389
G1 F2799.284
G1 X168.798 Y152.284 E.00313
G1 X168.821 Y152.211 E.00223
G1 F3000
G1 X168.821 Y152.211

--X 90 M106 in the tolerance test file

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by mjoconr** [comment]
M106 is a supported gcode in klipper as per https://www.klipper3d.org/G-Codes.html
I suggest you do not have a part cooling fan configured, meaning klippper does not have M106 command support.

**Comment by Sonnenwerk** [comment]
Oh thanks ! That helped me !
It is solved - so we can now close this for Orca.
but maybe we should improve klipper somewhat - for interpreting that "error" better --> like "fan not configured" or so...

**Comment by Sonnenwerk** [comment]
btw..Sonnenwerk is my second account..dont be irritated ;)
