### ISSUE TITLE
MakerWorld - "Open in BambuStudio" -> Point to OrcaSlicer

### ISSUE THREAD

**Issue by DokuKaefer** [SoftFever/OrcaSlicer#3829]
Hello,

if I adjust the path to OrcaSlicer in the registry under Windows and then click on "Open in BambuStudio" on MakerWorld, OrcaSlicer opens but it does not find any geometry in the loaded file.

Is it possible to adjust this? 😊

![2024-01-25_19h21_50](https://github.com/SoftFever/OrcaSlicer/assets/11537653/a71bcf0e-8577-4017-bb06-6d3179af3fe2)

![2024-01-25_19h43_44](https://github.com/SoftFever/OrcaSlicer/assets/11537653/083d9b49-62d6-4656-af4b-8cd165df3f1a)

**Comment by vordenken** [comment]
Yes please, it would be awesome to use this feature (on Windows as well as macOS).

**Comment by wiyoon** [comment]
You need to modify the source code.

src/slic3r/GUI/GUI_App.cpp

```c++
    if (!url.empty() && (boost::starts_with(url, "orcasliceropen://") || boost::starts_with(url, "bambustudioopen://"))) {
        auto input_str_arr = split_str(url.ToStdString(), "orcasliceropen://");
        if (input_str_arr.size() <=1 ) {
            input_str_arr = split_str(url.ToStdString(), "bambustudioopen://");
        }
``` 



https://blog.naver.com/wiyoon/223386467252
