### ISSUE TITLE
Add PrusaSlicer shortcuts

### ISSUE THREAD

**Issue by rkarlsba** [SoftFever/OrcaSlicer#383]
PrusaSlicer has a lot of [shortcuts](https://help.prusa3d.com/article/keyboard-shortcuts_1764), although my favourite one doesn't seem to be listed there - press &lt;tab&gt; to switch between Prepare and Preview. Could you add  this, please?

**Comment by SoftFever** [comment]
I don't plan to replicate whole shortcuts from PS as that may conflict with existing shortcuts.
I like the idea of using the `tab` key to switch between Prepare and Preview.
Will add that

**Comment by SoftFever** [comment]
Implemented in 1.5.0
