### ISSUE TITLE
Attempting to create a new filament fails due to missing printer or preset

### ISSUE THREAD

**Issue by ChristianMP** [SoftFever/OrcaSlicer#3830]
### OrcaSlicer Version

1.9.0

### OS version

OS: Windows 10

### Printer

Ender 3 S1 Pro

### How to reproduce

1. Click filament gear
2. Add new custom filament
3. Select Anycubic TPU
4. Createbased on current filament dropdown is empty
4.1 Copy current filament preset yields same error.

### Actual results

![image](https://github.com/SoftFever/OrcaSlicer/assets/80536265/61c18562-8d3b-4de8-b188-9b0b772b06a9)

### Expected results

Filament is created

### Project file & Debug log uploads

No logs created.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by acidg** [comment]
I am having the same problem: I want to add a custom filament for my custom printer, but can't do so, because the printer cannot be selected. It works for the Bambu Lab X1 Carbon, which I have in my list of printers. Maybe the problem is caused by the custom printer?

**Comment by acidg** [comment]
Workaround: Save a profile with another name and adjust all parameters manually.

**Comment by JediMasterBob** [comment]
having the same issue in V1.9.1. I've added a custom printer profile and now I do not get any printers in the dropdown box. eventually the program crashes with this error:

![image](https://github.com/SoftFever/OrcaSlicer/assets/84201785/7e1432cf-fce1-4891-abfa-8e4c18569252)

**Comment by RadioAndrea** [comment]
Present in 2.3.0-Beta as well

**Comment by steadmanc** [comment]
I have the same problem.  Cannot add a custom filament because it keeps saying no printer selected.  It does not show any printers to select when you create the custom filament as seen in the instructional video https://www.youtube.com/watch?v=a4PX-2u6BMM.  Fast forward to 1:31 to see where the printer selection is made.  That does not appear for me.
