### ISSUE TITLE
Miss spelling

### ISSUE THREAD

**Issue by Kprint5454** [SoftFever/OrcaSlicer#3833]
This is not a major issue but just something to give yah guys a heads up. I noticed a potential miss spelling under the 'One wall threshold' drop down. The last sentence has "is" in the place of "if". I'm not sure if this is what it is supposed to be, but just saw this now. I'm currently using the latest OrcaSlicer version.
![Screenshot 2024-01-25 175045](https://github.com/SoftFever/OrcaSlicer/assets/157761879/cd4c7de4-6673-4e6b-b2be-46a654d37972)

**Comment by darco415** [comment]
ironic

**Comment by Ergonomicmike** [comment]
I didn't want to be the first to say it. (At first I thought the title was a joke.)
