### ISSUE TITLE
macOS full screen mode error on 'Device' tab

### ISSUE THREAD

**Issue by amirnickolla** [SoftFever/OrcaSlicer#384]
**Describe the bug**
When going into full screen mode on macOS, the 'Device' tab is zoomed in more than it needs to be and there is a horizontal scroll bar that appears which is then needed to view the whole page. When returning to windowed mode, the scroll bar remains and the 'Device' tab remains zoomed in rather than returning to its original size.
Note that if you enter full screen mode before navigating to the 'Device' tab, the issue does not occur.

**To Reproduce**
1. Open Bambu Studio SoftFever fork in windowed mode
2. Navigate to the 'Device' tab
3. Go into Full Screen mode on the window
4. Go into windowed mode, and the error still persists

**Expected behavior**
The application goes into full screen mode and the current page resizes automatically to fit into the screen real estate without needing a scroll bar.

**Screenshots**
<img width="1440" alt="Screenshot 2023-02-28 at 1 06 08 am" src="https://user-images.githubusercontent.com/126486633/221584739-884af31e-a2ff-42c5-8a09-ae273397fd5d.png">
<img width="1440" alt="Screenshot 2023-02-28 at 1 10 31 am" src="https://user-images.githubusercontent.com/126486633/221585809-30958f65-3162-4be7-98fa-71719568d34a.png">

**Desktop**
 - OS: macOS Ventura 13.0 running on M1 MacBook Air

**Comment by hliebscher** [comment]
for not bambu printers works fine ;-)

MAC M1 13.1
