### ISSUE TITLE
Sphere tool preview circle is offset from the cursor by a lot

### ISSUE THREAD

**Issue by dojohnso** [SoftFever/OrcaSlicer#3846]
### OrcaSlicer Version

1.9

### OS version

macOS Sanoma 14.2.1 (23C71)

### Additional system information

CPU: 2.3 GHz 8-Core Intel Core i9
Graphics: AMD Radeon Pro 5500M 4 GB, Intel UHD Graphics 630 1536 MB
Mem: 32 GB 2667 MHz DDR4

### Printer

Bambu Lab A1

### How to reproduce

1. Select an object
2. Enter Paint mode
3. Select the Sphere tool type
4. move the mouse around

### Actual results

note the dot indicator is either not visible or offset by the equivalent of inches depending on the rotation/position of the view camera. The circle tool has the circle indicator accurately at the point of the mouse. The painting with the sphere works as expected, it's juts the preview dot that is off. It i accurate with size and color preview.

![image](https://github.com/SoftFever/OrcaSlicer/assets/294549/07378e9d-7e64-4d2f-8f51-a97aa57ec42e)
In this image, my cursor was on the object. 

![image](https://github.com/SoftFever/OrcaSlicer/assets/294549/5769ae55-5e1f-486a-8b3d-a8792c285eb0)
similar area with the circle tool selected and the cursor in the same position

![image](https://github.com/SoftFever/OrcaSlicer/assets/294549/64b0060b-0fd8-4b07-8cd7-a100a9f639f9)
similar outside of paint mode

If i rotate the view, the dot moves with it, so the position you see it in is static relative to the plate/object
![image](https://github.com/SoftFever/OrcaSlicer/assets/294549/76cfed1e-1b41-4a58-a3db-b46db3c11d8d)
![image](https://github.com/SoftFever/OrcaSlicer/assets/294549/70fad496-2c2e-4010-b8ff-6895ebe3b7d6)

### Expected results

The solid dot for the sphere tool should be at the position of the cursor where the painting actually occurs

### Project file & Debug log uploads

[Cube.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/14069842/Cube.3mf.zip)
[debug_Fri_Jan_26_15_17_10_55001.log](https://github.com/SoftFever/OrcaSlicer/files/14069845/debug_Fri_Jan_26_15_17_10_55001.log)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by cobyn** [comment]
I have the same issue on windows 11
