### ISSUE TITLE
Cannot restore/unmaximize the window using the client-side decorations

### ISSUE THREAD

**Issue by RebeccaStevens** [SoftFever/OrcaSlicer#3848]
### OrcaSlicer Version

2.0.0-dev

### OS version

Nobara 39 (KDE)

### Printer

Bambu Lab X1c

### How to reproduce

1. Disable server-side decorations
2. Maximize the window
3. Click the Restore/Unmaximize button (Observer no restore/unmaximize)
4. Double click the title-bar (Observer no restore/unmaximize)
5. Click and drag the title-bar (Observer no restore/unmaximize nor window move)

### Actual results

Windows remains maximized

### Expected results

Window should be able to be restored/unmaximized.

There should also be an option in settings to make the window use server-side decorations. 

### Project file & Debug log uploads

[debug_Sat_Jan_27_20_00_18_12724.log.0.zip](https://github.com/SoftFever/OrcaSlicer/files/14071435/debug_Sat_Jan_27_20_00_18_12724.log.0.zip)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by gregersn** [comment]
I have this same issue.
