### ISSUE TITLE
Enhance Overhang features: apply speed restrictions on inner wallls as well. 

### ISSUE THREAD

**Issue by itchy2** [SoftFever/OrcaSlicer#3858]
The Overhang quality is very bad. Based on many test prints the overhang quality can be improved if the outer and inner walls will be printed slower.

Printer: Bambulab X1C - I would guess also other fast printers would benefit from this feature. 

In the settings you can define the speed for ranges of overhangs (e.g. 0-25% etc.). I would like to have these settings also applied (or set in a different box) for the internal walls not only the external walls. It would be also beneficial if you can define an amount of layer where it is applied when below there is also an overhang. and to make the ranges (e.g 0-25%) more flexible (you can enter the values by hand).

As an alternative you can always apply modifier boxes on the required overhangs but that requires a lot of manual effort.

Thanks and kind regards
itchy2

**Comment by mbrady4597** [comment]
I have seen this issue pop up for models with steep overhangs as well. The slow down external walls for overhangs works great and allows for more cooling time without having a large effect on total printing time. Inner walls have no slow down though, and when they also have large overhangs, this leads to curling and delamination which can build up and lead to surface defects on the outside. The current fix is to drastically reduce inner wall speed for the entire model which adds significant print time. Ideally the slow down for overhangs setting would have an option to apply to both external and internal perimeters.

![inner_overhangs](https://github.com/SoftFever/OrcaSlicer/assets/128195716/b781227b-0152-49a2-890f-e962aa18386f)
Picture shows the slow down for the overhanging outer perimeter but no slow down for the inner perimeter.

**Comment by ver151set** [comment]
bump
