### ISSUE TITLE
Calibration-Advanced Volumetric Flow

### ISSUE THREAD

**Issue by grandoth** [SoftFever/OrcaSlicer#3860]
### OrcaSlicer Version

1.9.0

### OS version

Windows 10

### Printer

Creality K1 Max

### How to reproduce

1. Create a New Project.
2. menu Calibration -> Max Flowrate -> Accept Defaults (5, 20, 0.5) (OK)
3. View the Layer height settings under the Quality tab.

### Actual results

The "Layer height" and "First layer height" settings are changed from my default (0.2 mm) for the system presets to 0.32 mm. Following the Calibration guide, it suggests using the expression which implies a 0.2 mm step height:
start + (height-measured * step)

with example 5 + (19 * 0.5) , or 13mm³/s

When I print this test model, the height is in fact 32 mm.

![image](https://github.com/SoftFever/OrcaSlicer/assets/32348693/36ca6306-6815-4d29-bf0d-3cb4b8d2f0d7)

Guide reference:
https://github.com/SoftFever/OrcaSlicer/wiki/Calibration#max-volumetric-speed

### Expected results

The "Layer height" and "First layer height" settings should both be set to 0.2 mm step height OR the wiki Calibration page described above should be updated to account for the measurement of 32 mm.

### Project file & Debug log uploads

[Max volumetric speed test.zip](https://github.com/SoftFever/OrcaSlicer/files/14074902/Max.volumetric.speed.test.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by SoftFever** [comment]
The model is printed in vase mode, hence it's not an issue. The layer height is purposely set to 0.32 to avoid increasing the printing speed too quickly.

**Comment by grandoth** [comment]
OK. I see now that the model automatically calculates its height depending on the step size and end max volumetric speed. I think what might have been confusing me is the following from the wiki: "5 + (19 * 0.5) , or 13mm³/s" when the result of that expression evaluates to 14.5. Or am I misunderstanding the calculation?
