### ISSUE TITLE
Not printning colors

### ISSUE THREAD

**Issue by timpaforfan** [SoftFever/OrcaSlicer#3869]
### OrcaSlicer Version

1.9.0

### OS version

Windows 11

### Printer

Bambu Lab A1 + AMS Lite

### How to reproduce

1. Download https://makerworld.com/en/models/154577
2. Import to Orca Slicer, Slice.
3. The white bands on the side of the box gets the red color no matter what. Works perfectly in Bambu Studio
![IMG_9552](https://github.com/SoftFever/OrcaSlicer/assets/155464216/84e6ab52-0d2a-4cab-beaa-1a76a07c56be)
![IMG_9553](https://github.com/SoftFever/OrcaSlicer/assets/155464216/663a15d4-490b-4f46-8ce7-9f80fdf2b8c5)
![IMG_9555](https://github.com/SoftFever/OrcaSlicer/assets/155464216/a79f3ad9-a3bc-49ac-ac18-c20ba47c99d3)

### Actual results

The white bands on the side of the box gets the red color no matter what. Works perfectly in Bambu Studio
2 pictures is from Orca Slicer, one picture is from Bambu Studio, but thats marked with "Bambu Studio"
![IMG_9555](https://github.com/SoftFever/OrcaSlicer/assets/155464216/a00540b7-454f-4a80-8734-366b2a286c03)
![IMG_9552](https://github.com/SoftFever/OrcaSlicer/assets/155464216/84964c3b-00ce-4a84-8080-4df174be9ff3)
![IMG_9553](https://github.com/SoftFever/OrcaSlicer/assets/155464216/2fb70e6a-1048-4c27-9f79-325b902e36c3)

### Expected results

The bands should slice in to the color i choose

### Project file & Debug log uploads

[mmu_heart_box(1).zip](https://github.com/SoftFever/OrcaSlicer/files/14076433/mmu_heart_box.1.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by itchy2** [comment]
I can confirm a similar behaviour on a different model. In my case the are was not vertical (as in this case) it was turned by 45 degrees.
