### ISSUE TITLE
Filamenttype for all Printers

### ISSUE THREAD

**Issue by Slevin7** [SoftFever/OrcaSlicer#3872]
Orca Slicer has an extremely large number of filaments as presets in the slicer itself.
Unfortunately, only if you have selected all printers.
Since I only have one printer, and I don't think I'm alone in this, only the Creality Filmante are displayed.
It would be great if I could see them all. 
![Bildschirmfoto 2024-01-28 um 19 00 48](https://github.com/SoftFever/OrcaSlicer/assets/22618979/9b1db3e1-9b58-4015-aabd-5ad259643b64)
![Bildschirmfoto 2024-01-28 um 19 01 43](https://github.com/SoftFever/OrcaSlicer/assets/22618979/32c63005-fa82-4447-8b16-eb61d9f0af73)

**Comment by atl285** [comment]
If you don't have a Bambu Lab printer configured, it makes no sense to show you the other filament profiles, because they are calibrated especially for the Bambu Lab printers.

So for all printers, which has no pre-configured (calibrated) filament profiles, the Generic profiles are created.

**Comment by Slevin7** [comment]
I see, I thought these were the starting points for each filament, like preferred temperature.
I can then use them to adjust my stuff, like pressure and temp and so on.
