### ISSUE TITLE
Add more nozzle profiles for Prusa MK3S Profile.

### ISSUE THREAD

**Issue by BladerunnerxRC** [SoftFever/OrcaSlicer#3875]
**Is your feature request related to a problem? Please describe.**
Only one nozzle size. A 0.4 mm profile is available for Prusa MK3S.

**Which printers will be beneficial to this feature**
Prusa MK3S

**Describe the solution you'd like**
Please add the following nozzle sizes: 0.2, 0.6, 0.8

**Describe alternatives you've considered**
The alternative is to use Prusa Slicer

**Additional context**
![image](https://github.com/SoftFever/OrcaSlicer/assets/40814001/8d556352-b85d-4332-97a6-826415725c35)

**Comment by lovelace** [comment]
I'll add a vote for this one. My MK3S+ has the E3D Revo hot end installed and I regularly use all 4 nozzle sizes. Someone suggested I look into switching from PrusaSlicer but without the ability to use other nozzle sizes this is a complete non-starter for me. So, please add this feature. Thanks.

**Comment by BladerunnerxRC** [comment]
Figured I was not the only one wanting this. It would be nice to stay in
the same slicer since I have an X1Carbon as well.
