### ISSUE TITLE
Selective Ironining

### ISSUE THREAD

**Issue by escfoe2** [SoftFever/OrcaSlicer#3879]
Like the subject suggests, I’d like to be able to select the surfaces I want ironed. This should be accomplished using the paint tool just like supports, but if it makes it simple/easier, only allowing the Bucket painting option is fine.

All Top Surfaces option doesn’t suffice because I don’t need all top surfaces ironed. I only need SOME top surfaces. This would greatly increase print time for me on many models while also greatly improving surface finish in places where it needs it.

This is also helpful for supports when you’re printing supports on top of your object instead of the build plate, it helps to iron the objects surface first. Makes support removal easier.

I understand this can be done manually with modifier objects; however, this is tedious, time consuming, error prone, and not user friendly.  There is a better approach that should be taken and I believe what I mentioned above is the way to go.

**Comment by Hammerfest** [comment]
Upvote for this feature request.

Sometimes I print items with a flat internal bottom but sidewalls like a case, it would be nice to have the bottom ironed but not the top of the walls.
