### ISSUE TITLE
Can't switch off of dark mode on linux

### ISSUE THREAD

**Issue by sam0622** [SoftFever/OrcaSlicer#3882]
### OrcaSlicer Version

1.9.0

### OS version

Linux Mint 21.2 Cinnamon

### Printer

Custom Klipper profile (for Ender 3 V2)

### How to reproduce

Go to settings, look for theme button.

### Actual results

The dark mode/ theme button is missing which is really annoying because all the grey makes some of the icons near invisible
I also went in the config file and changed it but it just set itself back to dark mode.
![Screenshot from 2024-01-28 17-07-05](https://github.com/SoftFever/OrcaSlicer/assets/140025368/443fc353-7bce-4709-b0e6-47e3e887643c)

### Expected results

There should be a checkbox/ selector to change the theme.

### Project file & Debug log uploads

[orcaproject.zip](https://github.com/SoftFever/OrcaSlicer/files/14077937/orcaproject.zip)
[log.zip](https://github.com/SoftFever/OrcaSlicer/files/14077949/log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by vontrapp** [comment]
still a problem in 2.0.0 appimage

**Comment by whytf** [comment]
Still a problem with 2.2.0

**Comment by sperdev54** [comment]
> Still a problem with 2.2.0

still a problem with 2.3.0

**Comment by Prazgreen1** [comment]
Still an issue with 2.3.1 flatpak and appimage as well as compiled either from docker or AUR.
In theory, this should be an easy fix. This issue should definitely be reopened and marked as enhancement.

**Comment by barbaracleaver1915-star** [comment]
Still persists on Linux Mint Cinnamon 22.3 with OrcaSlicer 2.3.2.
