### ISSUE TITLE
Crash when attempting to edit filament under Device

### ISSUE THREAD

**Issue by pgifford** [SoftFever/OrcaSlicer#3896]
### OrcaSlicer Version

2.0.0-dev

### OS version

Windows 10

### Printer

Bambu X1C

### How to reproduce

1. Click on "Device"
2. Click on pencil icon over filament

<img width="325" alt="device" src="https://github.com/SoftFever/OrcaSlicer/assets/6106848/5567fb2d-1763-488c-b2ad-7070ac396899">

### Actual results

Error dialog, program closes

<img width="403" alt="error" src="https://github.com/SoftFever/OrcaSlicer/assets/6106848/4fce86e3-280c-4eb9-80d8-bd3231d2c525">

### Expected results

I can edit filament setting on device tab.

### Project file & Debug log uploads

[project_and_log.zip](https://github.com/SoftFever/OrcaSlicer/files/14090676/project_and_log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by KrisMorr** [comment]
I confirm, I also have the same error
![error](https://github.com/SoftFever/OrcaSlicer/assets/154343071/6afcbacf-f045-4db6-bfd6-e6b1666991ed)

**Comment by pennystockss** [comment]
Same on Mac, tried various builds. Orca just closes no errors.

**Comment by pgifford** [comment]
Issue no longer occurs with latest dev, fixed by https://github.com/SoftFever/OrcaSlicer/pull/3981 (probably)
