### ISSUE TITLE
Question: Bug merges from BS valuable?

### ISSUE THREAD

**Issue by bjmckenz** [SoftFever/OrcaSlicer#391]
I'm curious if you would like PRs for merge commits from BS's GH?

I can build/test under Linux, and probably Win.

But the main question is about your plans/intent with respect to refreshing?

(I really want the newest stuff from PS, but who knows how long that's gonna take to get into BS)

But in the meantime there are fixes in BS that might be nice to have. There are ~400 commits since your fork.

Thanks!

**Comment by SoftFever** [comment]
Hi @bjmckenz 

Sure,
They are welcomed :)
