### ISSUE TITLE
Orcaslicer hangs while slicing a "swiss cheese" object

### ISSUE THREAD

**Issue by austinchambers** [SoftFever/OrcaSlicer#3910]
### OrcaSlicer Version

1.9.0

### OS version

Win10 Pro, 64bit

### Additional system information

CPUs: 2x Xeon E5-2695 v3, Z10PE-D8WS MB

### Printer

Bambu P1S

### How to reproduce

1. Start a new project with "Generic ASA" filament and 0.4 or 0.6 nozzle (I repro'd this with both, but I don't think nozzle/filament affects this). 
2. Extract the zip and add the attached STL file that it contains. I also had about 8 variants of this file that all failed similarly. In short, when there were 30+ "holes" going through the object, slicing never finished.  
3. Click "Slice" button to begin slicing
[StencilFix_PCBHolder7.zip](https://github.com/SoftFever/OrcaSlicer/files/14105742/StencilFix_PCBHolder7.zip)

![image](https://github.com/SoftFever/OrcaSlicer/assets/8466736/9dcf0ea0-c6f6-47d7-8691-cd5575234836)

### Actual results

Slicer remains at 35% stuck on "Generating Infill Path"
I left this running overnight and it was still doing this 8 hours or so later. CPU usage was minimal. I couldn't stop the process, so I had to force-terminate the program. 

### Expected results

In Bambu Studio, the above STL prints and slices fine. It looks like Orcaslicer has issues specific to this STL. I should note that both Orcaslicer and Bambu Studio are working fine with other prints, and that both were set to default settings (other than changing nozzle size or filament to ASA). 

### Project file & Debug log uploads

[debug_Mon_Jan_29_01_20_05_20688.log.zip](https://github.com/SoftFever/OrcaSlicer/files/14105786/debug_Mon_Jan_29_01_20_05_20688.log.zip)
[StencilFix_PCBHolder7_ProjFile.zip](https://github.com/SoftFever/OrcaSlicer/files/14105788/StencilFix_PCBHolder7_ProjFile.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by 3dPrintsOnFire** [comment]
I am having a similar issue with a model. I will provide more details when I get back to my computer tomorrow.

**Comment by Cikmo** [comment]
Getting the exact same issue

**Comment by marktuk** [comment]
I just recently had this issue on version 2.2.0 when slicing a "swiss cheese" type model i.e. lots of holes spaced closely together in a grid pattern. I found turning off this setting solved the issue, I assume there was some problem generating infill around the holes.

<img width="343" height="55" alt="Image" src="https://github.com/user-attachments/assets/fec9b522-1026-43ee-9efc-742067f61c87" />
