### ISSUE TITLE
Feature request: Ironing outer wall offset setting and fixed seam position option

### ISSUE THREAD

**Issue by TechDude23** [SoftFever/OrcaSlicer#3912]
1. Ironing top layer but we need a outer wall offset setting distance box option added 0.00 mm

2. Fixed Seam option added to the ( Seam Position selector box )

Layer start point X at: 0.00 mm
Layer start point Y at: 0.00 mm

**Comment by Eldenroot** [comment]
+1 this is same request for ironing
