### ISSUE TITLE
Support/Color Painting issue: Doesn't show the model 

### ISSUE THREAD

**Issue by Kynan29** [SoftFever/OrcaSlicer#3916]
### OrcaSlicer Version

1.9

### OS version

Windows

### Printer

Bambu X1-C

### How to reproduce

Go to Orca slicer and select model and select support painting or color painting

### Actual results

It doesn't show the model for me to paint.

### Expected results

Should be able to view the selected model to paint supports/color change

### Project file & Debug log uploads

https://github.com/SoftFever/OrcaSlicer/assets/158364612/656d33de-dee7-46f3-8cb0-16ba30e5c6d1

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Dez125** [comment]
I am having the same problem
