### ISSUE TITLE
Request: Add Ender 5 Pro Support

### ISSUE THREAD

**Issue by mssmison** [SoftFever/OrcaSlicer#392]
Would you be able to add the Ender 5 pro profile?

**Comment by bojangles86** [comment]
> 

or all the creality ones.. if not then just the most used.. E3, E5(all of them,E7.

**Comment by jeanres** [comment]
CR 10 Smart would be great as well

**Comment by mm108** [comment]
> > 
> 
> or all the creality ones.. if not then just the most used.. E3, E5(all of them,E7.

CR-10 Smart Pro too :)

**Comment by neclimdul** [comment]
I think there's technically a Ender 5 Pro profile now so probably can close this.

**Comment by garocdev** [comment]
> I think there's technically a Ender 5 Pro profile now so probably can close this.

Tried the one listed as Ender 5 pro 2019 - can't get it to work.  First layer goes down fine, but then something happens and remaining layers are spaghetti or filament. Working with Merlin firmware 2.1.  Using Cura without issue.
