### ISSUE TITLE
More calibration and quality tests predefined

### ISSUE THREAD

**Issue by Sonnenwerk** [SoftFever/OrcaSlicer#3922]
I would be exited, if we could have more calibration and quality test already prepared in the slicer.

I REALLY MISS THE BENCHY !

**Comment by mrmultifunk** [comment]
The benchy is already there, right-click on the buildplate --> Add Handy models

**Comment by Sonnenwerk** [comment]
Whooo great ! A hidden feature - nice !

Then i would just have the request to add them to the "calibration" menu too.

**Comment by DVSVIDEO** [comment]
> Whooo great ! A hidden feature - nice !
> 
> Then i would just have the request to add them to the "calibration" menu too.

Printing Benchy is not really calibration...I don't think it belongs there.
Calibration is an interactive process: Print...setting....print...setting
