### ISSUE TITLE
Modelname not Filename not Jobname when sending to Bambu X1

### ISSUE THREAD

**Issue by CoReYeDe** [SoftFever/OrcaSlicer#3923]
Would like to reopen (https://github.com/SoftFever/OrcaSlicer/issues/1268#issuecomment-1920994179), because i have the same behavior..
OrcaSlicer 1.9.0
STL exported from Fusion360, imported to orcaslicer..
Dont know, where this Information is get from and how to change it.
Also "Bambu Weihnachtshütte" - What is this?

![image](https://github.com/SoftFever/OrcaSlicer/assets/22613068/b9b128d9-2d94-44ee-a382-e05f5778fd2b)
![image](https://github.com/SoftFever/OrcaSlicer/assets/22613068/7b13bbe5-7fd6-4671-b51a-32239db898f7)
![image](https://github.com/SoftFever/OrcaSlicer/assets/22613068/ea9842a7-6117-409a-95b7-055ea53635ea)

_Originally posted by @CoReYeDe in https://github.com/SoftFever/OrcaSlicer/issues/1268#issuecomment-1920994179_

**Comment by kylek29** [comment]
Was this a model that you imported to F360 to modify?

I've had that metadata stay intact when importing an existing model (from MakerWorld) to F360, modifying it, exporting, and bringing it back onto Orca.

I think one solution (and one I'm surprised Bambu hasn't implemented) would be to add an "edit" view (and abilities) to the model Project view.

**Comment by CoReYeDe** [comment]
Any Updates?

**Comment by CoReYeDe** [comment]
Bump
