### ISSUE TITLE
Solving the problem with large overhangs during Inner/Outer/Inner

### ISSUE THREAD

**Issue by NNMale** [SoftFever/OrcaSlicer#3924]
**Is your feature request related to a problem? Please describe.**
Inner/Outer/Inner walls printing order creates a problem with overhanging perimeters. The outer perimeter is printed in the air.

![2024-02-01_162842](https://github.com/SoftFever/OrcaSlicer/assets/96396187/0f3f9aae-a342-477b-9c78-a4064ff04ca5)

**Which printers will be beneficial to this feature**
For all printers

**Describe the solution you'd like**
I would like to see a different sequence for printing the walls:
Middle/Outer/Inner.
Start with the second outer wall, then print the outer wall, then the inner wall. See the picture in the attachment.

![2024-02-01_163739](https://github.com/SoftFever/OrcaSlicer/assets/96396187/4142ad46-15d0-45a3-8a6e-31702123816c)

Using this method will improve the overhangs and make the outer wall printing more accurate compared to the Inner/Outer walls printing order.

**Comment by kylek29** [comment]
There is a current PR for doing a hybrid:
https://github.com/SoftFever/OrcaSlicer/pull/3809
