### ISSUE TITLE
Overhang detection deactivated with active supports.

### ISSUE THREAD

**Issue by foxmckraut** [SoftFever/OrcaSlicer#393]
**Describe the bug**
The overhang detection isnt working when supports are activated > results in bad overhangs in unsupportet regions

**Printer model**
x1c

**Desktop (please complete the following information):**
 - Macosx arm BS-SF 1.4.5

<img width="785" alt="Bildschirm­foto 2023-02-28 um 09 20 19" src="https://user-images.githubusercontent.com/101701200/221794592-8ac08051-2c77-41b2-9a74-693375b01879.png">
<img width="856" alt="Bildschirm­foto 2023-02-28 um 09 20 34" src="https://user-images.githubusercontent.com/101701200/221794668-09dfcf89-5413-499f-bbfa-6c1ba9975da6.png">

edit: on BS 1.4.2.13 it is working as intended

**Comment by foxmckraut** [comment]
Problem solved. if topz distance is set to 0 it disables overhangs

<img width="1024" alt="Bildschirm­foto 2023-02-28 um 10 57 24" src="https://user-images.githubusercontent.com/101701200/221818489-338b26f6-744d-461e-92fe-e3ae5992a612.png">
<img width="981" alt="Bildschirm­foto 2023-02-28 um 10 57 56" src="https://user-images.githubusercontent.com/101701200/221818717-ee8f1450-8da6-434a-880f-e17b41de6aae.png">

**Comment by SoftFever** [comment]
Thanks for the report and updates.
