### ISSUE TITLE
No top support interface while using tree supports

### ISSUE THREAD

**Issue by midnight1979** [SoftFever/OrcaSlicer#3930]
### OrcaSlicer Version

1.9.0

### OS version

Windows 10

### Printer

Anycubic i3 Mega

### How to reproduce

Slice model with tree auto supports
![image](https://github.com/SoftFever/OrcaSlicer/assets/18383176/e1659adb-010a-4ce1-a8b6-e136ed189291)

And the tip on Branch Density saying that I must enable top support interface...
where is this settings for Tree Supports
![image](https://github.com/SoftFever/OrcaSlicer/assets/18383176/82faf58c-09c0-4178-98ff-07c694dd092f)

### Actual results

Support interface for tree supports working randomly

### Expected results

Working top support interface in tree supports. 

### Project file & Debug log uploads

not needed

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by midnight1979** [comment]
tree style was selected incorrectly on my side

**Comment by lightmaster** [comment]
@midnight1979 I hate to necro this, but I'm experiencing the same issue. What exactly do you mean by "selected incorrectly on my side"?
