### ISSUE TITLE
Linux: Color theme makes settings unreadable (almost) white on light gray in the unsaved changes popup

### ISSUE THREAD

**Issue by potens1** [SoftFever/OrcaSlicer#3936]
### OrcaSlicer Version

1.9.0

### OS version

Arch Linux (Gnome 45.3)

### Additional system information

CPU: Ryzen 9 3900X
GPU: AMD 6900XT
32GB RAM

### Printer

Qidi X-Max3

### How to reproduce

Change any printing parameter
Close the app
Wait the popup to ask to save changes

### Actual results

Gnome dark theme
![image](https://github.com/SoftFever/OrcaSlicer/assets/3988571/7a9e569d-0c57-4b65-91c7-80b6d8d2fae1)

Gnome Light theme
![image](https://github.com/SoftFever/OrcaSlicer/assets/3988571/8b0076bb-a702-4565-aa78-6c6a908ba7b6)

The settings names are barely readable since it written in white on light gray, and since we can't select anything in the windows, we can't even highlight to workaround

### Expected results

Readable interface ?
Putting the settings names in the same color as the values ?

### Project file & Debug log uploads

[porte-casque(solide).zip](https://github.com/SoftFever/OrcaSlicer/files/14138568/porte-casque.solide.zip)
[debug_Fri_Feb_02_11_12_02_23676.log.zip](https://github.com/SoftFever/OrcaSlicer/files/14138609/debug_Fri_Feb_02_11_12_02_23676.log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by brandonbeaumia** [comment]
![image](https://github.com/SoftFever/OrcaSlicer/assets/650565/88c6028b-8e94-4e45-94ca-17aad3c1ead2)

Similarly bad for the dark theme. Pop_OS! 22.04
