### ISSUE TITLE
Being able to increase fan speed ahead of time before overhangs

### ISSUE THREAD

**Issue by felipejfc** [SoftFever/OrcaSlicer#3938]
**Is your feature request related to a problem? Please describe.**
When running fans with the following config:
![image](https://github.com/SoftFever/OrcaSlicer/assets/285782/4f79fb70-cdc3-4436-a1ba-fcfced97f82f)

The fan will mostly work at 70%, apart from overhangs (100%) and when it hits minimum layer time. Fine. The problem is there's a delay between the printer increases the speed and it being actually reflected in the fans, so when printing small models (such as a benchy), overhangs can be print with lower than 100% fan speed. What would help would be to be able to configure how much time or layers before the overhang the speed should increase.

**Which printers will be beneficial to this feature**
Klipper based printer. I'm running a V3 SE with it.

**Describe the solution you'd like**
What would help would be to be able to configure how much time or layers before the overhang the speed should increase.

**Describe alternatives you've considered**
Didn't think of any, but I'm newbie so happy to hear from others :)

**Comment by DVSVIDEO** [comment]
Such a feature already exists:

Printer settings---->Basic information---->Cooling fan


![Fan](https://github.com/SoftFever/OrcaSlicer/assets/96373457/d3e9c339-ece1-41a2-ae36-015b63f48731)

**Comment by felipejfc** [comment]
aha! thanks for that! exactly what I needed :D
