### ISSUE TITLE
Find an replace option

### ISSUE THREAD

**Issue by Galloant** [SoftFever/OrcaSlicer#3939]
**Problem**
I have changed from Prusa slicer to Orca just recently. 2 of my 3 printers work fine with it, but when importing the gcode output from Orca into the Anker slicer, it doesn't recognize the print movements type (perimeter, infill, etc.).
I found this to be caused by the different type of naming scheme such as  "Outer wall" vs. "External perimeter" for example.
This results in Anker slicer not being able to generate a AI file and thus the AI recognition doesn't work.
![image](https://github.com/SoftFever/OrcaSlicer/assets/69965491/8f503afd-663a-4e38-8c76-935df3aa7758)

(This is my best guess until now, so please feel free to correct me on that.)

**Solution**
Replace the type names when creating the gcode. This would be easiest if there would be a option to search and replace text, like in Prusa Slicer:
![image](https://github.com/SoftFever/OrcaSlicer/assets/69965491/86349de1-10fa-4631-a199-3dce846d8d44)

**Comment by Galloant** [comment]
Circumvented the issue by using AnkerMake Studio instead. AnkerMake Slicer is obsolete as it seems.
Nevertheless, option to find and replace text would still be appreciated.

**Comment by atmacali** [comment]
same problem i need find and replace to set fan number as P2. I need to control cooling fan as M106 P2 S255
