### ISSUE TITLE
Being able to set fan speed threshold without needing to change minimum layer time

### ISSUE THREAD

**Issue by felipejfc** [SoftFever/OrcaSlicer#3940]
**Is your feature request related to a problem? Please describe.**
I wanted to be able to do the following:
-> If layer time is less than 8 seconds, use fans at 100%
-> Set minimum layer time to 3 seconds

Today I can only change both things at once, if minimum layer time is 3 seconds, this will be the threshold to fans at 100%.

**Which printers will be beneficial to this feature**
All printers. I'm using a Ender 3 V3 SE with Klipper

**Describe the solution you'd like**
In creality print they have both options unlinked, minimum layer time is a separate option than max fan layer time threshold. We could do the same.

**Describe alternatives you've considered**
I don't think there's an alternative today in orca, but happy to hear from others if I'm wrong.

**Comment by DVSVIDEO** [comment]
At any time you can specify the fan speed for the layer time.
You can slow down printing for better cooling.
If these settings are not sufficient, you should think about hardware modification of the cooling...

![Fan2](https://github.com/SoftFever/OrcaSlicer/assets/96373457/ebb63559-ffc0-480b-ad88-c51e7274ac52)

**Comment by felipejfc** [comment]
Makes sense but I wanted to be able to change minimum layer time without changing max fan speed threshold. Isn't this reasonable?

**Comment by patrezp** [comment]
I just saw induction hotend came to reality, and having temperature modifier would be great addition to printing 0 gap supports for example. See https://www.youtube.com/watch?v=XphpaHd8Q9s for more ideas

**Comment by bra1nDeaD** [comment]
Closed thread, but I found this because I've got the same issue, but in Bambu Studio. I've opened an issue here: https://github.com/bambulab/BambuStudio/issues/10202

I hope I've described it well as it's clear there is a situation where there is no control over the cooling. So if anyone else comes across this thread with the same issue, have a look at mine as that's new and still open (for now).
