### ISSUE TITLE
Сreality-SR10-SE printer profile

### ISSUE THREAD

**Issue by teleskop-tv** [SoftFever/OrcaSlicer#3945]
Please add a Сreality-SR10-SE printer profile into your wonderful slicer program! Please! A lot of people already have this printer. We have been waiting for a profile for this printer for a very long time. Please add a Creality-SR10-SE printer profile. Please, please, please!!!

**Comment by V1os** [comment]
Yes, or sey how preset CR-10 SE? From witch printer base?

**Comment by gamali15** [comment]
Yes, we have been waiting for a long time for the profile to be loaded. we cannot use the printer with full efficiency.

**Comment by henrivdr** [comment]
In the meantime you can look inside the Benchy gcode, which shipped with the memory stick, for the printer settings that was used.

**Comment by cochcoder** [comment]
Is Сreality-SR10-SE a mistype, do you mean Сreality-CR10-SE?

**Comment by teleskop-tv** [comment]
Yes, of course! I mean Reality-CR10-SE. I apologize for the mistake I made in the 3d printer model. Please add a Сreality-СR10-SE printer profile into your wonderful slicer program!

**Comment by cochcoder** [comment]
> Yes, of course! I mean Сreality-CR10-SE. I apologize for the mistake I made in the 3d printer model. 

Don't worry about it, just wanted to make sure that I wasn't confusing two completely different 3D printers!

> Please add a Сreality-СR10-SE printer profile into your wonderful slicer program!

I have a PR request for a standard profile, if you want to give settings for a draft or detailed one, please do!

**Comment by teleskop-tv** [comment]
Thank you! I'm not sure I can figure out what I need to do. If it is not difficult for you, please add the profile of this printer to the distribution package of the program. Night assembly or something like that
