### ISSUE TITLE
Allow only single instance of program

### ISSUE THREAD

**Issue by Pveska** [SoftFever/OrcaSlicer#3950]
Would be nice to add availability to enable/disable one instance of program per time, like on PrusaSlicer for ex:
![image](https://github.com/SoftFever/OrcaSlicer/assets/25360098/8bdd46c3-027a-45bb-a19f-2898ab47b50f)
It usefull when you sending print from Fusion360, and instead creating new instance of OrcaSlicer it will use the one that already runned

**Comment by noobydp** [comment]
This will be resolved by #4810
