### ISSUE TITLE
Brim/skirt startpoint the same placement as rest of model

### ISSUE THREAD

**Issue by FlowForm** [SoftFever/OrcaSlicer#3952]
The starting point of the brim and skirt is always in the left front corner and not near the rest of the chosen or painted seam position. 

This creates unnecessary and unwanted travel moves in the first layer. With filament that sticks really badly, the least amount of travel is preferred. Also with woodfil and other filaments this travel leaves ooze on the buildplate. 

![Skærmbillede 2024-02-03 133235](https://github.com/SoftFever/OrcaSlicer/assets/84511476/b743f756-6a67-4aab-a809-e7baa465ec68)

- Wanted: Same startpoint of brim & skirt as rest of model!

**Comment by FlowForm** [comment]
Would be so nice to see this implemented :-)

**Comment by DorjeDorf** [comment]
bumping this in hopes of getting this sorted out / explained / implemented :D

**Comment by Dumplap** [comment]
bumping
