### ISSUE TITLE
"Collapse Sidebar"

### ISSUE THREAD

**Issue by ThinkBigPrintHuge** [SoftFever/OrcaSlicer#3955]
**Is your feature request related to a problem? Please describe.**

Orca v1.9.0, I hate the new collapsing sidebar. I would love to see the default placement of the sidebar in the same location as previous versions of Oca. As of now when I open Orca, the side bar is halfway collapsed and it's not a smooth experience sliding it. Also, after clicking <<>> to collapse and then again to expand, it doesn't revert back to the position it was collapsed from. All very minor QOL things, I know. Thank you!

**Comment by discip** [comment]
Have you tried the latest build: https://github.com/SoftFever/OrcaSlicer/actions/runs/7725298637

**Comment by ThinkBigPrintHuge** [comment]
I finally installed 1.9.1. Moved the sidebar to see how docking (insert joke here) works. Now I have a free floating sidebar again and cannot figure out how to re-dock it.
