### ISSUE TITLE
Auto Backup Failed

### ISSUE THREAD

**Issue by kayboy-bebop** [SoftFever/OrcaSlicer#3963]
### OrcaSlicer Version

1.9.0

### OS version

Linux Mint 21.3

### Additional system information

AMD 5800X3D, AMD 6700XT

### Printer

Voron

### How to reproduce

Open existing .3mf file and work on it for 0.5 hour or so. "Auto-Backup" is at default setting of every 10 seconds. Power failure leads to unexpected shutdown. Open Orca Slicer and open same .3mf file.

### Actual results

No prompt for backup restoration shown.

### Expected results

Expect prompt for auto-backup restoration.

### Project file & Debug log uploads

[debug_Sat_Feb_03_09_10_37_54260.log](https://github.com/SoftFever/OrcaSlicer/files/14156423/debug_Sat_Feb_03_09_10_37_54260.log)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by jb510** [comment]
IDK if this behavior is new (your report was v1.9, this is v2.1.1), but if you DRAG a .3mf into an open project it'll prompt you if you'd like to import just the geometry.  This doesn't happen when opening the .3mf directly since there wouldn't be settings to override there.  

In short, open a new project with your defaults, then drag in the .3mf and you'll have the options you're looking for.

![CleanShot 2024-10-23 at 11 54 20](https://github.com/user-attachments/assets/e795a6ca-d2e1-4f9a-a720-befca2c59c37)

**Comment by gquinche** [comment]
I investigated this issue with Antigravity and managed to manually solve the problem, here is a summary.


***

### 🛠️ Manual Recovery Workaround
If OrcaSlicer crashes and fails to show the recovery prompt, you can force it to trigger manually:

1.  **Locate the backup:** Go to your system temp folder and find the most recent folder inside `orcaslicer_model` (e.g., `/tmp/orcaslicer_model/...` or `%TEMP%\orcaslicer_model\...`).
2.  **Delete the lock:** Inside that folder, delete the file named **`lock.txt`**.
3.  **Update the config:**
    *   **Close OrcaSlicer completely.**
    *   Open your `OrcaSlicer.conf` (in `%AppData%\OrcaSlicer` or `~/.config/OrcaSlicer`).
    *   Find the line `"last_backup_path": "..."` and change the value to the path of the backup folder you found in Step 1.
4.  **Restart OrcaSlicer:** The app should now correctly detect the orphaned session and show the "Restore Project" prompt.

**Technical Note:** There is likely a race condition in `Plater.cpp` where initializing a new session on startup overwrites the `last_backup_path` breadcrumb before the recovery check can process the older crashed session.

**Comment by capntrips** [comment]
Be sure to backup the session, if you already have the app open. I found the session in `/tmp/orcaslicer_model/`, but it was deleted when I closed the app after deleting the lock. Hopefully this saves someone else from the same fate.
