### ISSUE TITLE
Variable extrusion width in Vase mode

### ISSUE THREAD

**Issue by Jigit3D** [SoftFever/OrcaSlicer#3964]
When printing a cone shape in a vase mode it is often needed to increase extrusion width in order to keep wall thickness the same through the entire part. Orca slicer, unlike Idea maker, uses modifiers to apply different settings to a different parts of the printed model. However, this feature does not work when printing in vase mode. With an error message that Vase mode works only with one material.
I would like to ask to add the feature, where it is possible to change extruder width at certain hight during printing in vase mode.

**Comment by faith-healer** [comment]
up.
