### ISSUE TITLE
Wrong STEP slicing when the same part STL is OK

### ISSUE THREAD

**Issue by sebox1** [SoftFever/OrcaSlicer#3966]
### OrcaSlicer Version

1.6-1.8.1

### OS version

Windows 10

### Printer

Creality K1

### How to reproduce

Save the same solidworks model to STEP and STL

### Actual results

![1](https://github.com/SoftFever/OrcaSlicer/assets/158845033/eea964ab-a947-4721-8cd2-08992cfa0fd5)
![2](https://github.com/SoftFever/OrcaSlicer/assets/158845033/0814c08e-5dbb-4ca0-ad68-98311624e0b1)
![3](https://github.com/SoftFever/OrcaSlicer/assets/158845033/7511609f-e2b1-4ea4-a7d9-e7cdd4a5446b)
![4](https://github.com/SoftFever/OrcaSlicer/assets/158845033/8d5b6591-127c-4b1c-bc0d-d80953b6fc0b)
![5](https://github.com/SoftFever/OrcaSlicer/assets/158845033/edafaa89-be49-4558-a3ad-b2750a16194b)
![6](https://github.com/SoftFever/OrcaSlicer/assets/158845033/5f33daba-4284-46f0-8a3f-13fbb8cb800e)

### Expected results

it need to be fixed

### Project file & Debug log uploads

[STEP issue.zip](https://github.com/SoftFever/OrcaSlicer/files/14157893/STEP.issue.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by sebox1** [comment]
![7](https://github.com/SoftFever/OrcaSlicer/assets/158845033/c90195c3-77f4-41da-a6aa-24b931a36070)

**Comment by foreachthing** [comment]
There is no STEP (nor STL, nor SolidWorks) file in your ZIP. Could you please add those?

**Comment by sebox1** [comment]
[ ! Orca STEP issue.zip](https://github.com/SoftFever/OrcaSlicer/files/14167635/Orca.STEP.issue.zip)

**Comment by sebox1** [comment]
Thanks for your interest. This trick didn't work for me when I saved STEP from my SW 2021sp5.1 again. Then, out of curiosity, I saved this STEP from SW 2019sp5.1 and now everything was OK.
Surprisingly, it means the SW 2021sp5.1 is to blame!

However, this discovery does not solve my problem in any way. It’s much easier for me to save this part as STL, while all the other 15 parts of the project are transferred to Orca as STEP and work without any problems.

Perhaps a little later I will install SW2023 or 24 and see how the STEP of this part, saved from a newer version, behaves.

But your observation became important and interesting. Thank you again!

**Comment by sebox1** [comment]
I found the real cause of the bug!

In STEP Options of my SW 2021, two checkboxes are disabled, which should be enabled by default.

When I turned them back ON and saved the new STEP, Orca slice it without problems.

![STEP Options](https://github.com/SoftFever/OrcaSlicer/assets/158845033/9ddbb8a3-2d9f-4073-933e-1ce167948d5e)

**Comment by foreachthing** [comment]
You could write a small macro (vba, vb.net, c#) to make sure your settings are always the way you want/need them (lots of help and examples in the "API help" from SolidWorks).
I did not have the option "Split periodic faces" selected. Maybe that one is not needed? I don't even know what it does 😆 
Oh, and if you think this issue has been resolved, please close it 😉 .
