### ISSUE TITLE
Automatic Speed Options...choose to use exact value or percentages

### ISSUE THREAD

**Issue by soundtechscott** [SoftFever/OrcaSlicer#3969]
**Is your feature request related to a problem? Please describe.**

If I want to change a speed for my material, I have to change every single line speed manually
but I already know there are simple math values that work for the other parts of my print
lets say as an example...
if I want to hit a max speed of 100mm/sec
I know I can proably go 50-60mm/sec on my first layer with no issues
my outer walls might only be 80mm...my inner walls might be the full 100mm
my infill will probably be 70-75mm

if my max speed is only 80mm/sec
then my first layer is going to be 40-48mm (50%-60%)
my outer walls are only going to be 64mm (80%)
my inner walls are going to be the full 80mm
my infill will be 56-60mm (70-75%)

**Which printers will be beneficial to this feature**
E.g. Voron/Klipper based printer/etc...

all 3d printers

**Describe the solution you'd like**

Just make speed cells value or % like you have already done for line width

**Describe alternatives you've considered**

I currently use an excel sheet to do my calc based on a percentage

**Additional context**

**Comment by Tsoukan** [comment]
I was looking for this exact feature.  Being able to have the speed and acceleration values be calculated as a % of a base value would be fantastic  - also a document could be made to help new makers fill in starting % values.

**Comment by soundtechscott** [comment]
lets keep this going as it hasnt been added yet and its a big quality of life feature for people that understand how it works

**Comment by antonyburden** [comment]
100% is the setting I miss most from other slicers. Please consider adding this. Just 1 number to adjust will keep my profiles down to just 1 or 2.

**Comment by Lbredeson** [comment]
Just seeing if this perma closed. Or if anyone has thought to bring this back as an issue. Would help with generating a constant flow rate.

**Comment by iceman2511** [comment]
This feature still hasn't been added; it's the one big thing making this slicer feel outdated, as pretty much every other slicer I've used has percentage-based speed settings for most of their speeds.
