### ISSUE TITLE
Disable Gap Infill

### ISSUE THREAD

**Issue by Stargo44** [SoftFever/OrcaSlicer#3985]
Since the release 1.8, we are not able to set the speed of "Gap Infill" to 0.
It was used to get rid of the "Gap Infill". The only method that I know of.
Archane is not a solution in some case, it cause other issues.

Every printer will benefit of this feature.

The solution would be to set a paramter (On/Off) to disable or not the Gap Infill (as prusa slicer have).

On this picture you can see a scenario where I don't want to have the Gap Infill. 
![image](https://github.com/SoftFever/OrcaSlicer/assets/83824326/8da5456f-7abc-4436-81b8-e2233cf00f74)

**Comment by dartrax** [comment]
Duplicate of https://github.com/SoftFever/OrcaSlicer/issues/2414

**Comment by Stargo44** [comment]
> Duplicate of #2414

It's working for tiny gap but not for all gap as the image below. Watever threashold I set for the "Filter ou tiny gaps" setting.

![image](https://github.com/SoftFever/OrcaSlicer/assets/83824326/929e583f-ba0d-417f-98c7-a67489645123)

A check box to remove everithing would be great as Prusa Slicer.

**Comment by Stargo44** [comment]
It's working with the setting "Filter ou tiny gaps", I didn't know.
Sorry for the post.

**Comment by cubitik** [comment]
If anyone wonders how to turn it off, here is the cure: Go to the Strength tab, find the setting "Apply gap fill". Choose an option other than nowhere. Now there should be another setting visible "Filter out tiny gaps", now set it to 9999999 (whatever highest value you can) and ta da! It won't fill again.

**Comment by Salvinor** [comment]
@cubitik 
> If anyone wonders how to turn it off, here is the cure: Go to the Strength tab, find the setting "Apply gap fill". Choose an option other than nowhere. Now there should be another setting visible "Filter out tiny gaps", now set it to 9999999 (whatever highest value you can) and ta da! It won't fill again.

I made an account here only to be able to comment and to say "thank you"!

It worked perfectly!  :)

I set "Apply Gap Fill" to "Nowhere" but Orca did apply gap fill to many areas.
That drove me nuts!

Never could have figured this out myself.
