### ISSUE TITLE
Displacement maps

### ISSUE THREAD

**Issue by adenta** [SoftFever/OrcaSlicer#3992]
**Is your feature request related to a problem? Please describe.**
I want to add texture to my 3d prints without blender

**Which printers will be beneficial to this feature**
All printers

**Describe the solution you'd like**
This guy did a good amount of the work: https://github.com/prusa3d/PrusaSlicer/issues/8649

**Comment by kylek29** [comment]
I will say this did cross my mind awhile back. I know in the model creation process it can become very tedious to create a lot of patterns because the software will often slow to a crawl (*glares* at Fusion 360), rather just do it at slice time.

**Comment by Keavon** [comment]
Having this would be really nice.
