### ISSUE TITLE
z height in world coordinates does not allow you to move a item up.

### ISSUE THREAD

**Issue by NBF1998** [SoftFever/OrcaSlicer#3997]
### OrcaSlicer Version

1.9.0

### OS version

windows 11

### Printer

bambu lab a1

### How to reproduce

import a new object on build plate, then try to move z coordinates of part.

### Actual results

you type in a new number then it resets to previous number . if you drag the part up it just goes back to build plate.

### Expected results

the z height above the build plate should stay where i set it.

### Project file & Debug log uploads

[polysoup.zip](https://github.com/SoftFever/OrcaSlicer/files/14184987/polysoup.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by NBF1998** [comment]
I have to use creailty slicer anytime i want to put a logo on a print because of these issues.

**Comment by gasprints** [comment]
you need to "add part" to combine them and be able to move one part in relation to the other and have the height stay
<img width="348" alt="Screenshot 2024-03-12 at 2 41 18 PM" src="https://github.com/SoftFever/OrcaSlicer/assets/128255447/a82f46f7-4f74-424f-8166-d95e45e577f4">

**Comment by IcarianOM** [comment]
I think i have a similar issue:

![image](https://github.com/SoftFever/OrcaSlicer/assets/57366931/f11ef88b-6a1d-4d3a-b7cf-083de5367f3f)

if i move the OTHER part to the Mirrored Coordinates, after i set the 3 values, but y=45, the piece moved as the following image:

![image](https://github.com/SoftFever/OrcaSlicer/assets/57366931/7523f53f-6d35-4e9d-af11-8ee250364e6a)

**Comment by NBF1998** [comment]
Why is that a problem though? I imagine itd be a very easy bug for them to
fix

**Comment by scottkwarren** [comment]
How does it make sense to close a bug just because nobody's worked on it yet? It's still a bug, and it's still keeping me from doing my work. In grown-up software development we keep a list of ALL known bugs until we get to 'em or the project shuts down.
