### ISSUE TITLE
Hot end error 

### ISSUE THREAD

**Issue by Morschri1991** [SoftFever/OrcaSlicer#3999]
### OrcaSlicer Version

1.9.0

### OS version

MacOS 14.3

### Additional system information

CPU: M1 Ram 16GB

### Printer

Ender 3 pro 

### How to reproduce

set up your print
set print temp to 210 
Slice print
Send print to Octo print

### Actual results

The hot end will heat up to about 205 and then the printer will throw an E1 error and start beeping saying there is a heat error

### Expected results

The hotted should reach the designated temp

### Project file & Debug log uploads

[riser_lower.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/14188767/riser_lower.3mf.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by samwiseg0** [comment]
I suspect you may have a problem with your printer. Checking the outputted gcode. It is sending the correct commands to heat your nozzle. 

There maybe an issue with your wiring or some other physical issue that is causing your printer to error out. I would suggest trything to set the temp of your hotend manually via octoprint and see if it even reaches 210 without error. 

![2024-02-06_23-31](https://github.com/SoftFever/OrcaSlicer/assets/2241731/e0b8e4de-b457-48fa-9981-7f3b38d2e343)
