### ISSUE TITLE
Critical conflict between drawn supports and shrinkage compensation

### ISSUE THREAD

**Issue by flugegegeheimen** [SoftFever/OrcaSlicer#4000]
### OrcaSlicer Version

1.9.0

### OS version

Windows 10

### Additional system information

i7 9900k
titan rtx
ram 32

### Printer

any printer

### How to reproduce

1) enable support, any manual mode, snug style for example
2) draw support on any inclined surface
3) shrinkage 100 in plastic profile
4) slice and see
5) change shrinkage to any instead 100 (99,4 for example)
6) slice and see

### Actual results

(sorry, I'm writing via Google Translate)
For a long time I tried to understand the reason for the defects on my printouts made from materials with high shrinkage...

An illustration of how the supports were drawn by hand and what I expected to see:

![image_2024-02-07_12-56-08](https://github.com/SoftFever/OrcaSlicer/assets/124463484/3d3e693a-4541-447d-a7d0-07622ab9abe9)

If you change the compensation value instead of 100% (for example, to 99.4 as in my screenshot), then the supports are built incorrectly:

![image_2024-02-07_12-56-09](https://github.com/SoftFever/OrcaSlicer/assets/124463484/75883d87-8058-44c6-bc13-31db8bf33e7a)

I received a lot of defects because of this bug.

### Expected results

If you slice the g-code without using shrinkage compensation in the plastic profile, then everything works as normal:

![image_2024-02-07_12-56-08 (2)](https://github.com/SoftFever/OrcaSlicer/assets/124463484/b6e63de4-050d-435c-b770-c7599d05c14c)

### Project file & Debug log uploads

[test_shrinkage.zip](https://github.com/SoftFever/OrcaSlicer/files/14190862/test_shrinkage.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by atl285** [comment]
@flugegegeheimen, nice find. I often had problems with manual support and use mainly filament with shrinkage compensation. But I never thought, that this can be a reason for this. 😮

**Comment by atl285** [comment]
Is it solved?
