### ISSUE TITLE
OrcaSlicer 1.9.0 error displaying round build plate (config for FLSUN SR)

### ISSUE THREAD

**Issue by ekatus** [SoftFever/OrcaSlicer#4002]
### OrcaSlicer Version

1.9.0

### OS version

Ubuntu 22.04

### Additional system information

Intel NUC8i5BEH 16GB

### Printer

FLSUN SR

### How to reproduce

Configure a Delta Printer

### Actual results

The Build plate display is duplicated with overlay
![image](https://github.com/SoftFever/OrcaSlicer/assets/32845922/fa1587f8-7768-4fb4-b613-86782cb17f90)

### Expected results

Same view as 1.8.1 which is correct. 
![image](https://github.com/SoftFever/OrcaSlicer/assets/32845922/576c80e7-132b-45ea-a406-1974a23155b4)

### Project file & Debug log uploads

No configuration to show. It's obvious
[ObjectiveTube-short.zip](https://github.com/SoftFever/OrcaSlicer/files/14194264/ObjectiveTube-short.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Cascadier1** [comment]
Same here if i try to add a Delta Printer

Funny thing: Not visible in Dark Mode.
![grafik](https://github.com/SoftFever/OrcaSlicer/assets/138386572/ad641f2f-4bfc-4576-a7d9-45e251413b02)

**Comment by faith-healer** [comment]
same here
1.9,.x
latest 2.0.0. alpha too

![photo_2024-02-27_07-25-50](https://github.com/SoftFever/OrcaSlicer/assets/89359028/9c202020-3b4d-497d-a292-aa1346270e82)
