### ISSUE TITLE
Folders to organize Filament and Process Profiles

### ISSUE THREAD

**Issue by NeverHere** [SoftFever/OrcaSlicer#4006]
**Is your feature request related to a problem? Please describe.**
Not really a problem, but I have a lot of filament and process profiles.

**Which printers will be beneficial to this feature**
Any

**Describe the solution you'd like**
I would like to be able to organize my filament profiles and process profiles into folders. For example:

-ABS
->.4 MM Nozzle
---> eSun ABS Black
---> MatterHackers ABS
---> etc
->.4MM CHT Nozzle
---> eSun ABS Black CHT
---> etc

I would like to do the same for processes.

**Describe alternatives you've considered**
A good naming convention has gotten me so far, but diversifying nozzles with the same filaments is getting tricky to not accidently pick the wrong profile.

**Comment by tkunchick** [comment]
these should be combined.

https://github.com/SoftFever/OrcaSlicer/issues/3821
