### ISSUE TITLE
Support interface is significantly improved when interface pattern is rotated 20-30 degrees

### ISSUE THREAD

**Issue by ImagineerNL** [SoftFever/OrcaSlicer#401]
**Describe the Request**
Also an [open FR in bambu studio](https://github.com/bambulab/BambuStudio/issues/1102), but so far hasnt been implemented.

When slicing for an object that needs support, the support interface can be selected as circular or rectilinear.
Rectilinear is used most of the times due to shape of the objects.
However, the support interface lines will then always be colinear with either some of the wall lines or the top/bottom infill pattern lines.
Even with a solid support interface, this causes bad quality or hard to remove supports (breakaway)

When rotating the object between 20 - 30 degrees (as the top/bottom infill pattern is usually 45 degrees), this will guarantee a better support of the layer above and will guarantee no colinear wall or infill pattern.

Current workaround: Rotate the object
Expected workflow: Be able to define the angle of the support interface.

**Screenshots**
Normal object, rectilinear grid; interface lines (green) colinear with some wall (yellow)
![image](https://user-images.githubusercontent.com/62603552/212980328-6ca0f5fd-5607-48b8-82b1-9377126e7efd.png)

Normal object, concentric support interface; interface lines colinear with all walls
![image](https://user-images.githubusercontent.com/62603552/212980669-9a7fd5e3-3cff-4974-889e-7eab1c6aecee.png)

Rotated object; green lines are support interface; no colinear lines and thus better support quality
![image](https://user-images.githubusercontent.com/62603552/212979939-efa2ba4b-1608-487a-a8a8-3aa048370c23.png)

Other remark by MadMax389:
> That does appear to be a feature in Prusa Slicer. Set at 20 deg. Rotates both the support structure and the interface... ![image](https://user-images.githubusercontent.com/96731892/213196764-68bdfa6e-ba66-4b9f-a3f0-1c8c965fe30e.png) ![image](https://user-images.githubusercontent.com/96731892/213197121-8e059237-dda8-4061-86d1-9e61f2bd6841.png)

**Comment by SoftFever** [comment]
Implemented in 1.5.0
