### ISSUE TITLE
Can we get overhangs highlighted in the prepare menue? Some models it is hard to know is supports are needed or not and to what degree. Having the areas that should be are helpful, especially for painting on supports.

### ISSUE THREAD

**Issue by poolboy97** [SoftFever/OrcaSlicer#4014]
**Is your feature request related to a problem? Please describe.**

**Which printers will be beneficial to this feature**
E.g. Voron/Klipper based printer/etc...

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by atl285** [comment]
In the **view** menu activate **show overhangs**.  Or isn't this what you mean? 😄

**Comment by kylek29** [comment]
It's there under support painting, you can then adjust the angle at which they highlight via the slider and use the paint bucket (fill) or other tools to add.

Or do you mean an option to see those highlighted while not in the Support Painting view?

**Comment by poolboy97** [comment]
> In the **view** menu activate **show overhangs**.  Or isn't this what you mean? 😄 

Yep. Thats what i was looking for. Sorry guess had a senior moment.
