### ISSUE TITLE
Objects on slicer plate move after save and reopen

### ISSUE THREAD

**Issue by shortbus** [SoftFever/OrcaSlicer#4016]
### OrcaSlicer Version

1.9.0

### OS version

OS: Mac Orca: 1.9.0

### Additional system information

CPU: Intel

### Printer

Bambu X1C

### How to reproduce

Save, open another Project. Save, open original Project.

### Actual results

all objects on all plate move on the Y axis
![Screen Shot 2024-02-08 at 10 17 05 AM](https://github.com/SoftFever/OrcaSlicer/assets/1488794/c5464238-a48c-4219-b30c-ed00b6a392a7)

### Expected results

The objects should stay in place between openings. 

### Project file & Debug log uploads

no logs

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by m2torres97** [comment]
Still happens even on 2.0.0

**Comment by joedarrah88** [comment]
still happens on 2.1.1 and is extremely frustrating

**Comment by digitalsr2** [comment]
I have the same issue on my MacBook Pro 16-inch. M1 Max running Sonoma 14.5.

**Comment by mtbikemarc** [comment]
Still happening

**Comment by martincollar** [comment]
Hi, why this is closed? Im having this issue on both computers (Mac, Win) since i started using OrcaSlicer two months ago. currently happening every day on version 2.2.0-beta, macos 14.6.1 (23G93).. its so annoying, i have projects with maximum plates, and everything needs to be moved again and again. plese fix it...

**Comment by mtbikemarc** [comment]
How do we reopen this?

**Comment by klydex** [comment]
Still happens on 2.2.0

**Comment by yomarcyo** [comment]
@shortbus I re-opend the issue [here](https://github.com/SoftFever/OrcaSlicer/issues/7917) using your screenshot. Hope that's ok for you, as the problem is still unsolved.

**Comment by FelixBuehler** [comment]
Still not fixed to this day.

**Comment by mtbikemarc** [comment]
Can someone please help with this? 

Negative space will also move on it's own after saving/reopening. Not always related to the object moving.

**Comment by martincollar** [comment]
its so annoying that devs ignoring such a big bug, im about to leave the slicer due this, i have lot of plates in my projects and everything keeps moving :(

**Comment by FelixBuehler** [comment]
It's fixed in the 2.3.0 beta:
https://github.com/SoftFever/OrcaSlicer/pull/7923
