### ISSUE TITLE
Bambu Lab AMS show no color in device tab

### ISSUE THREAD

**Issue by Schmudus** [SoftFever/OrcaSlicer#4017]
### OrcaSlicer Version

2.0.0 (nightly build)

### OS version

Windows 10

### Additional system information

Not necessary

### Printer

Bambu Lab P1S

### How to reproduce

Go to device and load/change filament in AMS.
![Screenshot 2024-02-08 1](https://github.com/SoftFever/OrcaSlicer/assets/143350729/9a6013f5-935a-4754-aa4b-860f7ef06f33)
![Screenshot 2024-02-08 2](https://github.com/SoftFever/OrcaSlicer/assets/143350729/f157c09d-2e54-4457-bb2a-b493f635542f)
![Screenshot 2024-02-08 3](https://github.com/SoftFever/OrcaSlicer/assets/143350729/d45d2123-ef99-498a-a302-175bb070a0e7)

### Actual results

After loading a filament in device tab the corrsponding slot shows sometimes no color and sometimes no edit button (editing is still working). Looks like a layer shift in the faceplate. PETG seems to be working, PLA matte and PLA HS not. See enclosed Screenshots.

### Expected results

Colored AMS slot

### Project file & Debug log uploads

---

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by AngelDLM08** [comment]
Same issue with colors, but it appears only when selecting custom color.
If selecting standard colors from drop-down menu color renders correctly.

**Comment by Ruxery** [comment]
same problem. 
In V1.9.1 it was working. Now in V2.0.0 (beta and release) it is showing no color in the device tab.
![grafik](https://github.com/SoftFever/OrcaSlicer/assets/102697188/afed1cc7-2bf2-4add-90ff-f3678b710e08)

The colors are displayed and can be selected as normal when selecting a print.
![grafik](https://github.com/SoftFever/OrcaSlicer/assets/102697188/3ad320b8-e4d6-45ac-bdec-63ca5c30635d)
