### ISSUE TITLE
[Feature request] Brim ears

### ISSUE THREAD

**Issue by liftbag** [SoftFever/OrcaSlicer#402]
**Is your feature request related to a problem? Please describe.**
There are cases where brim ears are extremely useful, or save time and material.

**Describe the solution you'd like**
If there were no particular compatibility issues, porting from SuperSlicer could be considered, as it seems to me to be very well implemented, with useful configuration parameters.

**Additional context**
Here is an example of use. The material used has warping problems, but strong adhesion between perimeters and layers. Due to warping, I have to keep a distance between brim and object of 0mm. This causes a problematic separation between the brim and the piece. Using SuperSlicer's brim ears allowed me to easily remove the ears from the piece with a cutter.

<img width="640" alt="Screenshot 2023-03-01 alle 11 17 26" src="https://user-images.githubusercontent.com/14921654/222114429-815d8574-c6c5-4669-919a-f21d8ed7cfbc.png">

<img width="673" alt="Screenshot 2023-03-01 alle 11 17 51" src="https://user-images.githubusercontent.com/14921654/222114457-28ba5f86-08a5-472f-a0d8-ba14d2968a24.png">

**Comment by Fredyy90** [comment]
I only knew about manually placed anti-warping tabs using a cura plugin, but this looks like a really neat solution, if the automatic placement is clever enough

**Comment by liftbag** [comment]
> I only knew about manually placed anti-warping tabs using a cura plugin, but this looks like a really neat solution, if the automatic placement is clever enough

The ears in the screeshots are automatically generated by SuperSlicer. I changed the max angle (170°) to increase the number of ears. And I chose the rectilinear pattern, because the concentric produced strange results.

**Comment by StefanX13** [comment]
Would be much appreciated, since i use them a lot for thin ABS Parts which tends to warp pretty easy.

**Comment by guillaumemolter** [comment]
+1 actually requested samilar feature on [Vanilla Bambu Studio](https://github.com/bambulab/BambuStudio/issues/1393). I would personally prefer a manual paint feature like [TabAntiWarping](https://github.com/5axes/TabAntiWarping) but I would gladly take an automated feature if the implementation is faster/easier.

**Comment by thepowersource** [comment]
I would really like to see this feature also as the traditional brim is not really necessary because the prints always warp in certain places not around the whole object.

**Comment by operinko** [comment]
I would also love to see this implemented.

**Comment by H4kunaM4tata** [comment]
That is a nice feature, I manually add cylinder with the same layer height like 0.2
It is manual and all but works somewhat haha
+1 for this feature

**Comment by Fragmon** [comment]
+1

**Comment by cryoglobe** [comment]
> +1 actually requested a similar feature on [Vanilla Bambu Studio](https://github.com/bambulab/BambuStudio/issues/1393). I would personally prefer a manual paint feature like [TabAntiWarping](https://github.com/5axes/TabAntiWarping) but I would gladly take an automated feature if the implementation is faster/easier.

Yes .. SuperSlicer has this "Brim ears" and automatically generated for a while , that would be a real added value in Orca 
What could be nice to implement since the beginning , is the possibility to select any "ear" and be able to delete , or reduce or enlarge it individually to customize each if needed ( I'm thinking about some "print in place" prints )

**Comment by Linnie73** [comment]
> >  ( I'm thinking about some "print in place" prints )

Any articulated print is dramatic for brim removal, even if you don't have elephant's foot and a proper brim distance. IF the designer knows their stuff, you shouldn't even need brims to get the print to stick to the bed, but I've had varying experiences. 

So +1. specifically for mouse ears to be placed either automatically OR manually painted, and for both to behave according to the normal brim rules, i.e. adjustable width and brim distance, and placement around the object instead of across the bottom (like a flattened cylinder does).

**Comment by guestisp** [comment]
+1 for this.
very useful when printing single walls RC planes

**Comment by Fredyy90** [comment]
+1 any updates on this request? this would be the killer feature to make orcaslicer the clearly superior fork.

**Comment by cybrsage** [comment]
I would love this, as some prints tend to lift on a single corner and brim can be a real hassle to remove.

**Comment by Robnex** [comment]
+1

**Comment by mlewis-everley** [comment]
+1, I use this feature in SuperSlicer a lot and it is probably the main reason I can no longer get on with any other slicer :-o

**Comment by FireflyJar** [comment]
+1  I could use this too.

**Comment by codeframe78** [comment]
+1 I legit just came here to post about this very request LOL.

**Comment by FireflyJar** [comment]
> +1 I legit just came here to post about this very request LOL.

it is in the latest release now.   Thank you Noisyfox!

**Comment by operinko** [comment]
I believe this FR can be closed, as brim ears have been implemented as an option now.

**Comment by liftbag** [comment]
Thanks a lot.

**Comment by Knaudler** [comment]
+1 
need Brim ears

**Comment by cryoglobe** [comment]
> +1 need Brim ears

it's already in Orca , this topic is closed

**Comment by HakunMatat4** [comment]
> > +1 need Brim ears
> 
> it's already in Orca , this topic is closed

Since when???
AFAIK OrcaSlicer only support it everywhere rather than only where I need.

**Comment by cryoglobe** [comment]
> > > +1 need Brim ears
> > 
> > 
> > it's already in Orca , this topic is closed
> 
> Since when??? AFAIK OrcaSlicer only support it everywhere rather than only where I need.

Hello, then you need to open another feature request ...  "paint brim ear"   that would be indeed cool to paint only where you wants brim ears 
or maybe have the choice :  paint where you wants brim ears , or paint where you do not wants them
