### ISSUE TITLE
Division by zero exception on any model

### ISSUE THREAD

**Issue by nikjust** [SoftFever/OrcaSlicer#4026]
### OrcaSlicer Version

1.9.0

### OS version

Windows 11

### Additional system information

CPU: intel core i5 8400
RAM: 16gb
GPU: palit gtx 1060 6gb

### Printer

Anycubic Kobra Plus 

### How to reproduce

1. select Anycubic Kobra Plus printing profile, Mako PETG filament profile and Anycubic Kobra Plus-petg print profile
2. Slice Orca Cube

### Actual results

got Division By Zero exception, orca crashed

### Expected results

Model would slice normally

### Project file & Debug log uploads

[OrcaSlicer Issue.zip](https://github.com/SoftFever/OrcaSlicer/files/14224390/OrcaSlicer.Issue.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by foreachthing** [comment]
It has something to do with the tree-support.
Change it to "Normal" and it will slice...
