### ISSUE TITLE
"Reverse on odd" seems to disable "Slow down for curled perimeters" without a warning that it does so

### ISSUE THREAD

**Issue by torndar** [SoftFever/OrcaSlicer#4040]
### OrcaSlicer Version

1.9.0

### OS version

22.04.1-Ubuntu

### Printer

Voron Trident

### How to reproduce

Prepare a temperature tower test and look at the left overhang section outermost lines

### Actual results

With "...curled..." enabled and NOT "reverse..."
![image](https://github.com/SoftFever/OrcaSlicer/assets/1268782/de61971e-f462-48a3-9480-7cf31fd18640)
With both enabled
![image](https://github.com/SoftFever/OrcaSlicer/assets/1268782/376eebec-45f1-4cd7-9ad7-a04c9016f7dd)

### Expected results

I would expect the slower of the speeds would be used *and* direction reversed every other layer. I have not tried printing with either settings yet, just noticed curling when doing the temperature test print and investigating mitigation options so far.

### Project file & Debug log uploads

No project file, just use the temperature tower calibration option.

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by gogsi1** [comment]
I will add on my own, if there is a text or pattern on the surface of the part, when the "Reverse on odd" is turned on, the layers bulge on the walls.
When enabled:
![1](https://github.com/SoftFever/OrcaSlicer/assets/36478778/3b696040-f92f-49ee-9907-a44cc0ca64f8)
![2](https://github.com/SoftFever/OrcaSlicer/assets/36478778/b1b635a5-86aa-45cd-8532-95872d18c24c)
When turned off:
![3](https://github.com/SoftFever/OrcaSlicer/assets/36478778/e38f32a7-07a5-4700-ac14-ace59b82cfd1)
![4](https://github.com/SoftFever/OrcaSlicer/assets/36478778/ad586fe9-5b2d-4e42-85b4-affcecfb6e20)
