### ISSUE TITLE
[Bug] Default Creality Printers won't show up

### ISSUE THREAD

**Issue by MatthaeusLeiner** [SoftFever/OrcaSlicer#4047]
### OrcaSlicer Version

2.0.0-dev

### OS version

Windows 11

### Printer

Creality K1 Max

### How to reproduce

Install new Version -> Add Printer -> K1 Max, K1 all Nozzles -> Displays after pressing OK only default printer.
After adding K1C it displayed K1 and K1 Max and my Custom K1 Max but no K1C.

### Actual results

![image](https://github.com/SoftFever/OrcaSlicer/assets/133122607/b1dfea44-7009-4160-97c9-9869dd2700fd)
![image](https://github.com/SoftFever/OrcaSlicer/assets/133122607/3335d141-c98d-4cf7-b1af-b3edbd46228b)

### Expected results

All printer should show up.

### Project file & Debug log uploads

[Printer Issue.zip](https://github.com/SoftFever/OrcaSlicer/files/14233172/Printer.Issue.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by bistory** [comment]
You have a conflict with a config named "0.20mm Standard @Creality K1Max (0.4 nozzle)", which is the same name as the K1 Max config of Orca. Remove that configuration and it should fix your issue

**Comment by MatthaeusLeiner** [comment]
I removed now all my data from AppData\Roaming\OrcaSlicer\user but I can't add anything. It just shows default.
Or should I search elsewhere?

![image](https://github.com/SoftFever/OrcaSlicer/assets/133122607/55482128-4421-478b-ad97-9e6b9129d457)

**Comment by bistory** [comment]
> AppData

The data folder is /Users/YOUR_USER/Library/Application Support/OrcaSlicer

**Comment by bistory** [comment]
> I removed now all my data from AppData\Roaming\OrcaSlicer\user but I can't add anything. It just shows default. Or should I search elsewhere?
> 
> ![image](https://private-user-images.githubusercontent.com/133122607/303940531-55482128-4421-478b-ad97-9e6b9129d457.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2Nzc3NjEsIm5iZiI6MTcwNzY3NzQ2MSwicGF0aCI6Ii8xMzMxMjI2MDcvMzAzOTQwNTMxLTU1NDgyMTI4LTQ0MjEtNDc4Yi1hZDk3LTllNmI5MTI5ZDQ1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMVQxODUxMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MzJiYTIxNzc3MjZhMWIyN2NkNWY2MWU4YWI4ZThkYjk5NDU2YzNmZTZiZjdkNDY5NTJjM2FhODc3MDUxOTg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.78rbVeu8pGdeuME0AD42dp_6B-HzvoIbnkuyH_V4TMo)

I don't have Windows to test but you should wipe data folder and re-install Orca

**Comment by MatthaeusLeiner** [comment]
The mentioned data folder is mac yes.

I wiped now my data folder and everything called Orca, reinstalled Orca V2.0.0 and it still won't work.
With Orca V1.9.0 it works.

**Comment by HAndreasH** [comment]
Same here on latest nightly. Can not create Creality Ender 3.
Seems as if only creality printers are affected.

**Comment by MatthaeusLeiner** [comment]
Tried it with the Ender V3 and it won't show up too. I tried it on 2 different laptops.
