### ISSUE TITLE
Feature Request: Height Range Modifiers

### ISSUE THREAD

**Issue by djngnear** [SoftFever/OrcaSlicer#405]
**Is your feature request related to a problem? Please describe.**

It's super helpful to use height range modifiers to have more control over the slice. I'm frustrated when I want to change certain settings (layer height, infill, wall count) for select layers but have to try to line up primitive shapes to modify the objects.

**Describe the solution you'd like**

Implementing height range modifier settings where settings for certain ranges or layers can be changed would be amazing. This feature is one of the only reasons I'll slice in prusaslicer/superslicer from time to time.

**Describe alternatives you've considered**

An alternative would be lining up modifier shapes and that can be time consuming. 

**Additional context**

**Comment by pemerick07** [comment]
This would be a great addition. I really like how Superslicer allows you to change settings in for specific height ranges, particularly layer height. It frustrates me that in Bambu/Orca I can't set a height range with a specific layer height, instead it forces me to fade from one layer height to another in a relatively imprecise way.

**Comment by djngnear** [comment]
> This would be a great addition. I really like how Superslicer allows you to change settings in for specific height ranges, particularly layer height. It frustrates me that in Bambu/Orca I can't set a height range with a specific layer height, instead it forces me to fade from one layer height to another in a relatively imprecise way.

They both have it now.
