### ISSUE TITLE
"Wipe before external loop" casing double seam

### ISSUE THREAD

**Issue by Naninani** [SoftFever/OrcaSlicer#4055]
### OrcaSlicer Version

2.0.0-dev nightly based on latest 3840935 commit

### OS version

macOS Sonoma 14.3

### Additional system information

"Wipe before external loop" is casing double seam

Related: https://github.com/SoftFever/OrcaSlicer/pull/3616

### Printer

Bambu Lab P1P/A1 mini

### How to reproduce

Slice a model with 2 walls with "Wipe before external loop" on and put seam on different locations for the outside and inside walls.

### Actual results

The seam on the outside wall is visible and blobby on the instead wall
<img width="836" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/1681582/7e44972e-3c3e-49d2-803b-3c23c2359198">
<img width="751" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/1681582/520b019d-9ce7-48e3-b5fd-23e2bdd28d8d">

### Expected results

<img width="836" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/1681582/23d69095-4a5a-43ce-9d76-6f901a78d74b">
<img width="828" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/1681582/7c4a067f-02cf-4ded-bdb5-52b5df85a197">

### Project file & Debug log uploads

n/a

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Naninani** [comment]
@igiannakas fyi.

**Comment by igiannakas** [comment]
I dont think much can be done about this. 

As there’s no project file the below are my working assumptions as to what is going on:

If the model is 3 perimeters wide the wipe before external seam will de retract over the middle perimeter then extrude the external.

however if your hot end is struggling a bit to control the amount of oozing during deretraction these blobs may cause scarring on the external perimeter.

but it would be better please to attach the project file so I can check the produced slicing.
