### ISSUE TITLE
Quick first layer "Calibration"

### ISSUE THREAD

**Issue by Glenno-H** [SoftFever/OrcaSlicer#4059]
I would be great to have a quick first layer "Calibration", where it just generates simple first layer patches / pattern based on the "First Layer Height" calibration etc, it would make checking that all important first layer a little quicker and easier.

**Which printers will be beneficial to this feature**
I think it would be beneficial to any printer that doesnt have automatic offset / first layer calibration like the X1C.

**Describe the solution you'd like**
Within the calibration menu, a option to generate first layer patches / pattern. 

**Describe alternatives you've considered**
A simple drop in STL is used for the moment, but would be better if it was automatically generated.

**Additional context**
Perhaps something like this, or a pattern might be better.
![image](https://github.com/SoftFever/OrcaSlicer/assets/112679157/a307d824-645d-4097-b79e-626eb055a118)

**Comment by jnslmk** [comment]
I'd also be interested in this feature and think it would be a useful addition to the calibration tools. An automated vertical position shift could be generated with the gcode. Is there a reason why this is marked as not planned?

Edit: Found the explanation here for anyone stumbling across this issue: https://github.com/SoftFever/OrcaSlicer/issues/7874#issuecomment-2743766822
