### ISSUE TITLE
3fm format is not supported by other slicers/ orcaslicer have proprietary 3fm format?

### ISSUE THREAD

**Issue by Goodfeat** [SoftFever/OrcaSlicer#4064]
### OrcaSlicer Version

1.9.0

### OS version

Windows 10

### Printer

Delta

### How to reproduce

1) upload any stl file to the orcaslicer
2) save this file in 3fm format
3) try opening a 3fm file in prushaslicer or cura

### Actual results

Сura gives the error "no models in file"
Prusha gives the error "invalid format while parsing at line 20"
![error cura](https://github.com/SoftFever/OrcaSlicer/assets/44455128/a7c6abed-076e-4304-8a5f-f7f4072425d0)
![error prusa](https://github.com/SoftFever/OrcaSlicer/assets/44455128/2a989ab3-7460-46d5-b9fe-f5dfb5adc101)

### Expected results

The file had to be loaded because other cura in Prushaslicer support the 3fm format

### Project file & Debug log uploads

[1.zip](https://github.com/SoftFever/OrcaSlicer/files/14255268/1.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by faith-healer** [comment]
up
