### ISSUE TITLE
Currently it is possible to enable infill combination but not to specify how many layers we want the infill combined by which is the case on superslicer

### ISSUE THREAD

**Issue by lewiss66** [SoftFever/OrcaSlicer#4066]
### OrcaSlicer Version

1.9.0

### OS version

windows 11

### Additional system information

Currently it is possible to enable infill combination but not to specify how many layers we want the infill combined by.

When printing at small layer heights like 0.1mm I have found that combining infill can drastically speed up print times. But by default the combined infill prints a thick infill only every 4 layers at 0.4mm thick. This has made for some poor top surface finish on some of my parts.

The above example sliced in superslicer it is possible to specify to print infill every 2nd layer for instance resulting in a 0.2mm thick infill or even every 3rd layer.

I feel that this would be benifical to specify printing every x number of layers. 1 being the default setting where combined infill is disabled

### Printer

ender 3

### How to reproduce

Currently it is possible to enable infill combination but not to specify how many layers we want the infill combined by.

### Actual results

When printing at small layer heights like 0.1mm I have found that combining infill can drastically speed up print times. But by default the combined infill prints a thick infill only every 4 layers at 0.4mm thick. This has made for some poor top surface finish on some of my parts.

### Expected results

Like in superslicer it is possible to specify to print infill every 2nd layer for instance resulting in a 0.2mm thick infill or even every 3rd layer.

### Project file & Debug log uploads

![image](https://github.com/SoftFever/OrcaSlicer/assets/37708145/14aa3d3a-2163-4d54-92f5-693bb1cfc072)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by weekendkoder** [comment]
Quite usefull. Would be great to have it soon

**Comment by Nuc1eoN** [comment]
I support this case

**Comment by ZedOud** [comment]
These may be relevant: #2757 #2735 #2175

**Comment by igiannakas** [comment]
Raised a PR that aims to address this above.
