### ISSUE TITLE
Change wall order only on overhangs

### ISSUE THREAD

**Issue by cosminr86** [SoftFever/OrcaSlicer#4068]
**Is your feature request related to a problem? Please describe.**

improve overhangs quality and overall print quality

**Which printers will be beneficial to this feature**
E.g. Voron/Klipper based printer/etc...

all printers

**Describe the solution you'd like**

As orca can detect overhangs, I think it will be beneficial to use wall orderin inside to outside where the overhangs are, and use outside to inside where is not needed

**Describe alternatives you've considered**

A wall ordering option on overhangs will be wonderfull

Thank you!

**Comment by killerline10168** [comment]
+1

I also had the same idea a couple of weeks ago, but it felt like the devs had their hands full. This feels like a somewhat simple yet great solution to bad overhangs. We have to choose between layer consistency or nice overhangs, but why not both? :)

**Comment by jet689** [comment]
I 3rd this idea

**Comment by eternal-sorrow** [comment]
Please reopen this. Automatic issue closing shouldn't be a thing.

**Comment by imagesurgery** [comment]
- I can only get rid of seams completely when using I/O/I or O/I
- I can only get good overhangs with I/O

This is a feature I would love!

**Comment by tjeerdvandijk** [comment]
This would be a fantastic feature to ensure quality walls when printing a model with overhangs.
