### ISSUE TITLE
FEATURE REQUEST: Add Snapmaker Artisan as 3th party printer

### ISSUE THREAD

**Issue by Obicom** [SoftFever/OrcaSlicer#407]
**Is your feature request related to a problem? Please describe.**
Please add the Snapmaker Artisan as a 3th party printer

**Describe the solution you'd like**
Snapmaker Artisan should be an printer option in Bambu Studio SF

**Describe alternatives you've considered**
No alternative

**Additional context**
![image](https://user-images.githubusercontent.com/25134482/222299194-f71e65f7-2aa8-47f5-85c5-f407f066f45f.png)

**Comment by hliebscher** [comment]
you can use the snapmaker 350 profile an rename it and set the right dimensions ... for dualprint head you need only add a second color.
works with Artisan and the J1 very easy

**Comment by troian** [comment]
I think there is a bit more than just renaming and dimensions (tho certainly it will work).
- the print area is different depending on which nozzle is used
- L & R nozzles can have different diameter

**Comment by ZeroMuhi** [comment]
will a Snapmaker Artisan printer be added for Orca Slicer?

**Comment by ZeroMuhi** [comment]
will a Snapmaker Artisan printer be added for Orca Slicer?
