### ISSUE TITLE
Softfever Bambu Profile Saving Failure

### ISSUE THREAD

**Issue by ArcNzym3** [SoftFever/OrcaSlicer#408]
I set up my 5 printers, 3 filament types, and 3 printing profiles, but upon exiting the program, only 4 of my 5 printers are recalled and my filament types and printing profiles have all been wiped or werent saved in the first place.

this is from general use, so i do not have a way to submit a file for investifation

**To Reproduce**
i have a creality ender 3 profile set up and 4 voron printers.  the ender 3 only has a PLA filament profile and a single printing profile.  all my vorons share the same filaments and printing profiles for consistency.  upon opening a bambu P1P TPU print 3mf, the program fails to save one of my voron printers, as well as all my previously saved user profiles for filaments and printing profiles.  exiting the program seems to wipe out the most recently used printer.

**Expected behavior**
my user presets and printer configs should not disappear upon exiting the program

**Printer model**
voron trident 250mm

**Desktop (please complete the following information):**
 - OS: Windows 10
 - latest stable version as of 3/1/2023

**Comment by hliebscher** [comment]
for me it works ... you can only open a 3mf file with the the same printer profile from your BS-SF. it works not with the org Bambustudio 3mf !  Pls name all printers ... voron1 voron2 voron3 and select the right printer for the 3mf 

![no bug](https://user-images.githubusercontent.com/9274162/222346837-0cb53dce-f187-4e6b-a504-64efb624b5a9.jpg)
