### ISSUE TITLE
My custom profiles are gone (inaccessible) after updating to Feb 13 Development build (Creality Ender 3 v2)

### ISSUE THREAD

**Issue by Ergonomicmike** [SoftFever/OrcaSlicer#4087]
### OrcaSlicer Version

2.0 alpha

### OS version

Win10 64-bit

### Printer

Ender 3 v2

### How to reproduce

Update to the Feb 13 (2024) alpha build. (Where some new Ender 3 profiles had been added?)
Run Orca.
Now the "Select a Printer" Wizard appears. (It didn't appear before this latest alpha.)
Select your Printer. > Finish
Start a new project.

### Actual results

All my (custom) User Presets (printer, filament, process) were gone in Orca. (But they are in my Windows' user folder.)

(This seems similar to the issue here: https://github.com/SoftFever/OrcaSlicer/issues/980 )

Upon restart of Orca, the "Select a Printer" Wizard kept popping up on start.

(I thought that the problem "fixed itself" after I opened v1.9 of Orca and saved a previous Project in v1.9 that had been made in the alpha. When I opened the alpha and imported the Project file in the alpha, the Presets that I had used for this Project suddenly came back. 

But I cannot see any of my other User Presets. (E.g., I cannot change filament from my custom PLA to my custom PETG when I open an existing Project in the alpha,) I am limited to only 'Project inside presets." Is this desired behavior?)

### Expected results

I expected all my User Presets to be available, as before with the previous alpha releases of 2.0 alpha.

I suspect that something has been overlooked with the addition of the added Ender 3 profiles to Orca.

### Project file & Debug log uploads

A 0 byle (required) log file

[debug_Tue_Feb_13_20_12_03_175008.log.zip](https://github.com/SoftFever/OrcaSlicer/files/14274867/debug_Tue_Feb_13_20_12_03_175008.log.zip)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by bistory** [comment]
I could help you with a real logfile, 0 byte is useless.
It seems new Ender 3 profiles introduces several bugs, one was fixed yesterday, did you try that build?
