### ISSUE TITLE
X-Y Hole compenation affecting square holes too?

### ISSUE THREAD

**Issue by SaturnsVoid** [SoftFever/OrcaSlicer#4088]
### OrcaSlicer Version

1.9

### OS version

Windows 11 Pro

### Additional system information

i9-9900k
32GB ram
2080Ti, Latest drivers.

### Printer

Creality K1 Max

### How to reproduce

Make cad with circle holes and square holes, enable X-Y hole compensation for (0.2), print

### Actual results

In my testing the circle holes were corrected for the 0.2mm but the squares also gained 0.2mm size

### Expected results

I would imagine that only the circle holes with more them x sides would be corrected...

### Project file & Debug log uploads

....

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by SoftFever** [comment]
Yes, that's per-design.
square holes are holes too ;)
