### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by DiegoHerrera1890** [SoftFever/OrcaSlicer#4090]
### OrcaSlicer Version

1.9.0

### OS version

Ubuntu 22

### Additional system information

Display Card: Nvidia RTX 4060

### Printer

Voxelab Aquila X2

### How to reproduce

1. Clone the latest repo
2. cd OrcaSlicer/
3. sudo ./BuildLinux.sh -u
4. ./BuildLinux.sh -dsir

### Actual results

`(orca) diego@diego-instalimb:~/OrcaSlicer$ ./BuildLinux.sh -dsir
FOUND_GTK2=un  libgtk2-perl               <none>                    <none>       (no description available)
ii  libgtk2.0-0:amd64          2.24.33-2ubuntu2          amd64        GTK graphical user interface library - old version
ii  libgtk2.0-bin              2.24.33-2ubuntu2          amd64        programs for the GTK graphical user interface library
ii  libgtk2.0-common           2.24.33-2ubuntu2          all          common files for the GTK graphical user interface library
ii  libgtk2.0-dev:amd64        2.24.33-2ubuntu2          amd64        development files for the GTK library
un  libgtk2.0-doc              <none>                    <none>       (no description available))
[1/9] Updating submodules...
~/OrcaSlicer/resources/profiles ~/OrcaSlicer
~/OrcaSlicer
[2/9] Changing date in version...
done
[3/9] Configuring dependencies...
~/OrcaSlicer/deps/build ~/OrcaSlicer
cmake .. -DDEP_WX_GTK3=ON
-- OrcaSlicer deps DESTDIR: /home/diego/OrcaSlicer/deps/build/destdir
-- OrcaSlicer dowload dir for source packages: /home/diego/OrcaSlicer/deps/build/../DL_CACHE
-- OrcaSlicer deps debug build: 
-- Forcing CMAKE_BUILD_TYPE to Release as it was not specified.
Using Jpeg Lib 80
-- Configuring done
-- Generating done
-- Build files have been written to: /home/diego/OrcaSlicer/deps/build
done
[4/9] Building dependencies...
[ 43%] Built target dep_TBB
[ 43%] Built target dep_Cereal
[ 43%] Built target dep_GLFW
[ 43%] Built target dep_PNG
[ 43%] Built target dep_GLEW
[ 43%] Built target dep_EXPAT
[ 43%] Built target dep_Boost
[ 43%] Built target dep_Qhull
[ 58%] Built target dep_Blosc
[ 58%] Built target dep_GMP
[ 58%] Built target dep_NLopt
[ 58%] Built target dep_OpenEXR
[ 61%] Built target dep_OpenSSL
[ 64%] Built target dep_JPEG
[ 66%] Built target dep_FREETYPE
[ 77%] Built target dep_MPFR
[ 78%] Built target dep_CURL
[ 79%] Built target dep_OpenCSG
[ 86%] Built target dep_OCCT
[ 87%] Built target dep_TIFF
[ 93%] Performing update step for 'dep_wxWidgets'
[ 96%] Built target dep_OpenVDB
[ 96%] Built target dep_CGAL
[ 97%] Performing patch step for 'dep_wxWidgets'
Checking patch build/cmake/init.cmake...
error: while searching for:
        else()
            find_package(OpenGL)
            if(WXGTK3 AND OpenGL_EGL_FOUND AND wxUSE_GLCANVAS_EGL)
                set(OPENGL_LIBRARIES OpenGL::OpenGL OpenGL::EGL)
                find_package(WAYLANDEGL)
                if(WAYLANDEGL_FOUND AND wxHAVE_GDK_WAYLAND)
                    list(APPEND OPENGL_LIBRARIES ${WAYLANDEGL_LIBRARIES})

error: patch failed: build/cmake/init.cmake:413
error: build/cmake/init.cmake: patch does not apply
Checking patch build/cmake/lib/webview/CMakeLists.txt...
error: while searching for:
elseif(WXMSW)
    if(wxUSE_WEBVIEW_EDGE)
        # Update the following variables if updating WebView2 SDK
        set(WEBVIEW2_VERSION "1.0.705.50")
        set(WEBVIEW2_URL "https://www.nuget.org/api/v2/package/Microsoft.Web.WebView2/${WEBVIEW2_VERSION}")
        set(WEBVIEW2_SHA256 "6a34bb553e18cfac7297b4031f3eac2558e439f8d16a45945c22945ac404105d")

        set(WEBVIEW2_DEFAULT_PACKAGE_DIR "${CMAKE_BINARY_DIR}/packages/Microsoft.Web.WebView2.${WEBVIEW2_VERSION}")

error: patch failed: build/cmake/lib/webview/CMakeLists.txt:56
error: build/cmake/lib/webview/CMakeLists.txt: patch does not apply
Checking patch include/wx/fontutil.h...
error: while searching for:
    wxFontEncoding GetEncoding() const;

    void SetPointSize(int pointsize);
    void SetFractionalPointSize(double pointsize);
    void SetPixelSize(const wxSize& pixelSize);
    void SetStyle(wxFontStyle style);
    void SetNumericWeight(int weight);

error: patch failed: include/wx/fontutil.h:294
error: include/wx/fontutil.h: patch does not apply
Checking patch include/wx/gdicmn.h...
error: while searching for:
class WXDLLIMPEXP_FWD_BASE wxString;
class WXDLLIMPEXP_FWD_CORE wxIconBundle;
class WXDLLIMPEXP_FWD_CORE wxPoint;

// ---------------------------------------------------------------------------
// constants

error: patch failed: include/wx/gdicmn.h:38
error: include/wx/gdicmn.h: patch does not apply
Checking patch include/wx/generic/grid.h...
error: while searching for:
                         wxGridWindow* gridWindow);

    // Update the width/height of the column/row being drag-resized.
    void DoGridDragResize(const wxPoint& position,
                          const wxGridOperations& oper,
                          wxGridWindow* gridWindow);

    // process different clicks on grid cells
    void DoGridCellLeftDown(wxMouseEvent& event,

error: patch failed: include/wx/generic/grid.h:2951
error: include/wx/generic/grid.h: patch does not apply
Checking patch include/wx/msw/font.h...
error: while searching for:
    // ctors and such
    wxFont() { }

    wxFont(const wxFontInfo& info);

    wxFont(int size,
           wxFontFamily family,

error: patch failed: include/wx/msw/font.h:23
error: include/wx/msw/font.h: patch does not apply
Checking patch include/wx/msw/tooltip.h...
error: while searching for:
    // the one and only one tooltip control we use - never access it directly
    // but use GetToolTipCtrl() which will create it when needed
    static WXHWND ms_hwndTT;

    // create the tooltip ctrl if it doesn't exist yet and return its HWND
    static WXHWND GetToolTipCtrl();

    // to be used in wxModule for deleting tooltip ctrl window when exiting mainloop
    static void DeleteToolTipCtrl();

error: patch failed: include/wx/msw/tooltip.h:91
error: include/wx/msw/tooltip.h: patch does not apply
Checking patch include/wx/osx/app.h...
error: while searching for:

public:
    bool                OSXInitWasCalled() { return m_inited; }
    void                OSXStoreOpenFiles(const wxArrayString &files ) { m_openFiles = files ; }
    void                OSXStorePrintFiles(const wxArrayString &files ) { m_printFiles = files ; }
    void                OSXStoreOpenURL(const wxString &url ) { m_getURL = url ; }
#endif

error: patch failed: include/wx/osx/app.h:161
error: include/wx/osx/app.h: patch does not apply
Checking patch src/common/combocmn.cpp...
error: while searching for:
        #if !USES_GENERICTLW
            m_winPopup = new wxComboPopupWindowBase2( this, wxNO_BORDER );
        #else
            int tlwFlags = wxNO_BORDER;
          #ifdef wxCC_GENERIC_TLW_IS_FRAME
            tlwFlags |= wxFRAME_NO_TASKBAR;
          #endif

error: patch failed: src/common/combocmn.cpp:2141
error: src/common/combocmn.cpp: patch does not apply
Checking patch src/common/datavcmn.cpp...
error: while searching for:

    wxDataViewItemArray selections;
    GetSelections(selections);
    return selections[0];
}

namespace

error: patch failed: src/common/datavcmn.cpp:1322
error: src/common/datavcmn.cpp: patch does not apply
Checking patch src/common/dcbufcmn.cpp...
error: while searching for:
        const double scale = dc ? dc->GetContentScaleFactor() : 1.0;
        wxBitmap* const buffer = new wxBitmap;

        // we must always return a valid bitmap but creating a bitmap of
        // size 0 would fail, so create a 1*1 bitmap in this case
        buffer->CreateScaled(wxMax(w, 1), wxMax(h, 1), -1, scale);

        return buffer;
    }

error: patch failed: src/common/dcbufcmn.cpp:82
error: src/common/dcbufcmn.cpp: patch does not apply
Checking patch src/common/gdicmn.cpp...
error: while searching for:
        *height = size.y;
}

wxSize wxGetDisplaySize()
{
    return wxDisplay().GetGeometry().GetSize();
}

void wxClientDisplayRect(int *x, int *y, int *width, int *height)
{
    const wxRect rect = wxGetClientDisplayRect();

error: patch failed: src/common/gdicmn.cpp:863
error: src/common/gdicmn.cpp: patch does not apply
Checking patch src/common/image.cpp...
error: while searching for:
                    unsigned char red = pixel[0] ;
                    unsigned char green = pixel[1] ;
                    unsigned char blue = pixel[2] ;
                    unsigned char alpha = 255  ;
                    if ( source_alpha )
                        alpha = *(source_alpha + y_offset + x * xFactor + x1) ;
                    if ( !hasMask || red != maskRed || green != maskGreen || blue != maskBlue )
                    {
                        if ( alpha > 0 )
                        {
                            avgRed += red ;

error: patch failed: src/common/image.cpp:383
error: src/common/image.cpp: patch does not apply
Checking patch src/common/intl.cpp...
error: while searching for:
            {
                str = buf;

                // As we get our decimal point separator from Win32 and not the
                // CRT there is a possibility of mismatch between them and this
                // can easily happen if the user code called setlocale()

error: patch failed: src/common/intl.cpp:1628
error: src/common/intl.cpp: patch does not apply
Checking patch src/generic/grid.cpp...
error: while searching for:
            {
                case WXGRID_CURSOR_RESIZE_ROW:
                {
                    DoGridDragResize(event.GetPosition(), wxGridRowOperations(), gridWindow);
                }
                break;

error: patch failed: src/generic/grid.cpp:3824
error: src/generic/grid.cpp: patch does not apply
Checking patch src/msw/bmpcbox.cpp...
error: while searching for:

    wxComboBox::DoClear();

    HWND hwnd = GetHwnd();
    DissociateHandle();
    ::DestroyWindow(hwnd);

    if ( !MSWCreateControl(wxT("COMBOBOX"), wxEmptyString, pos, size) )
        return;

    // initialize the controls contents
    for ( i = 0; i < numItems; i++ )
    {

error: patch failed: src/msw/bmpcbox.cpp:156
error: src/msw/bmpcbox.cpp: patch does not apply
Checking patch src/msw/font.cpp...
error: while searching for:
class WXDLLEXPORT wxFontRefData: public wxGDIRefData
{
public:
    wxFontRefData(const wxFontInfo& info = wxFontInfo());

    wxFontRefData(const wxNativeFontInfo& info, WXHFONT hFont = 0)
    {

error: patch failed: src/msw/font.cpp:54
error: src/msw/font.cpp: patch does not apply
Checking patch src/msw/menuitem.cpp...
error: while searching for:
        // native menu uses small top margin for separator
        if ( SeparatorMargin.cyTopHeight >= 2 )
            SeparatorMargin.cyTopHeight -= 2;
    }
    else
#endif // wxUSE_UXTHEME

error: patch failed: src/msw/menuitem.cpp:368
error: src/msw/menuitem.cpp: patch does not apply
Checking patch src/msw/window.cpp...
error: while searching for:
}

/*extern*/
int wxGetSystemMetrics(int nIndex, const wxWindow* window)
{
#if wxUSE_DYNLIB_CLASS
    if ( !window )
        window = wxApp::GetMainTopWindow();

    if ( window )
    {
        typedef int (WINAPI * GetSystemMetricsForDpi_t)(int nIndex, UINT dpi);
        static GetSystemMetricsForDpi_t s_pfnGetSystemMetricsForDpi = NULL;
        static bool s_initDone = false;

        if ( !s_initDone )
        {
            wxLoadedDLL dllUser32("user32.dll");
            wxDL_INIT_FUNC(s_pfn, GetSystemMetricsForDpi, dllUser32);
            s_initDone = true;
        }

        if ( s_pfnGetSystemMetricsForDpi )
        {
            const int dpi = window->GetDPI().y;
            return s_pfnGetSystemMetricsForDpi(nIndex, (UINT)dpi);
        }
    }
#else
    wxUnusedVar(window);
#endif // wxUSE_DYNLIB_CLASS

    return ::GetSystemMetrics(nIndex);

error: patch failed: src/msw/window.cpp:4773
error: src/msw/window.cpp: patch does not apply
Checking patch src/osx/cocoa/dataview.mm...
error: while searching for:
        if ( !dvc->GetEventHandler()->ProcessEvent(eventDV) )
            [super keyDown:event];
    }
    else
    {
        [super keyDown:event];  // all other keys
    }
}

//
// contextual menus
//

error: patch failed: src/osx/cocoa/dataview.mm:1734
error: src/osx/cocoa/dataview.mm: patch does not apply
Checking patch src/osx/cocoa/settings.mm...
error: while searching for:
// ----------------------------------------------------------------------------

// Get a system metric, e.g. scrollbar size
int wxSystemSettingsNative::GetMetric(wxSystemMetric index, const wxWindow* WXUNUSED(win))
{
    int value;

error: patch failed: src/osx/cocoa/settings.mm:224
error: src/osx/cocoa/settings.mm: patch does not apply
Checking patch src/osx/cocoa/window.mm...
error: while searching for:
- (BOOL)isEnabled;
- (void)setEnabled:(BOOL)flag;

- (void)setImage:(NSImage *)image;
- (void)setControlSize:(NSControlSize)size;

error: patch failed: src/osx/cocoa/window.mm:190
error: src/osx/cocoa/window.mm: patch does not apply
make[3]: *** [CMakeFiles/dep_wxWidgets.dir/build.make:123: dep_wxWidgets-prefix/src/dep_wxWidgets-stamp/dep_wxWidgets-patch] Error 1
make[2]: *** [CMakeFiles/Makefile2:638: CMakeFiles/dep_wxWidgets.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:738: CMakeFiles/deps.dir/rule] Error 2
make: *** [Makefile:423: deps] Error 2`

### Expected results

It should compile, I guess. This is my first-time using Orca.

### Project file & Debug log uploads

There is no log files generated.

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by Ender436** [comment]
I'm having an issue that seems similar to yours, have you found anything yet?

**Comment by DiegoHerrera1890** [comment]
@Ender436 Not yet, have you tried using windows?

**Comment by Ender436** [comment]
@DiegoHerrera1890 No, I'm trying to build it for my raspberry pi as I don't have access to my pc right now..

**Comment by DiegoHerrera1890** [comment]
I could built it in Ubuntu 20, but now I am not sure how to run `oscar-slicer --help`, do you have any ideas?

**Comment by dekay** [comment]
I have the same issue trying to compile this on an up-to-date Arch Linux install with a tweaked BuildLinux.sh that skirts around all the Ubuntu specific stuff.

**Comment by digitamo** [comment]
I had the same issue with ubuntu:23.04. I managed to build it using a docker container running ubuntu 20.04

**Comment by DiegoHerrera1890** [comment]
Is there any updates?

**Comment by ZealACMer** [comment]
> I had the same issue with ubuntu:23.10. I managed to build it using a docker container running ubuntu 20.04

How did you do that? I used the ./DockerBuild.sh, but encountered the error, ninja stopped. Thank you so much for your help!
