### ISSUE TITLE
Filament shrinkage is mixing an objects' coloring

### ISSUE THREAD

**Issue by Gil80** [SoftFever/OrcaSlicer#4091]
### OrcaSlicer Version

1.9.0

### OS version

Windows 11

### Printer

Bambu Lab X1C

### How to reproduce

1. Open an object that is suitable for multi color
2. Color with two colors (black and red for example)
3. Slice the object and verify all looks well
4. Enter to one of the selected colors filament settings
5. Set the shrinkage value, in my case 99.97% for PLA
6. Slice the object again

### Actual results

The slicer mixes the coloring.

![image](https://github.com/SoftFever/OrcaSlicer/assets/8454919/3ae81787-f77f-43b3-be31-017cf45e1679)

### Expected results

Filament shrinkage should not affect the object multi-coloring

![image](https://github.com/SoftFever/OrcaSlicer/assets/8454919/dca89724-3da1-40f0-9cf8-66f3cf6b7949)

### Project file & Debug log uploads

[two-faced-sturdy-infinity-cube-20.zip](https://github.com/SoftFever/OrcaSlicer/files/14279627/two-faced-sturdy-infinity-cube-20.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by Fliens** [comment]
I have the same issue

Without shrinkage:
<img width="363" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/35639879/7767451e-dd7d-4b30-9b7c-3724800831b5">

With shrinkage:
<img width="396" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/35639879/27c5f984-7561-4ec6-9cbc-723132f92efd">

**Comment by niteowl660** [comment]
Same here

Without Shrinkage
![image](https://github.com/SoftFever/OrcaSlicer/assets/33509463/813a9e04-c6a0-4516-8e07-1df58ffe26cd)


With Shrinkage
![image](https://github.com/SoftFever/OrcaSlicer/assets/33509463/8098c8d1-8096-4c4b-b839-14a61541377c)

**Comment by SCISOK** [comment]
I also have this same issue.

**Comment by igiannakas** [comment]
Please test this here: https://github.com/SoftFever/OrcaSlicer/pull/5774
