### ISSUE TITLE
Issue slicing model with Spiral Vase mode. Partial missing layer.

### ISSUE THREAD

**Issue by 0ldHand** [SoftFever/OrcaSlicer#4093]
### OrcaSlicer Version

2.0.0-dev

### OS version

Windows 11

### Printer

Bambu P1S

### How to reproduce

Slicing full model in Cura 4.6.1 is successful in spiral mode with no missing layers or seams. (Eclipson Helix plane model)
Slicing same model in Orca produces both a seam and missing lines.
Including relevant portion of stl.
[Fuselage_F1-Spriral-Testing.zip](https://github.com/SoftFever/OrcaSlicer/files/14282210/Fuselage_F1-Spriral-Testing.zip)

### Actual results

Orca does not appear to be able to generate an uninterrupted tool path in spiral mode with this model. 
![Orca](https://github.com/SoftFever/OrcaSlicer/assets/6632242/1723bb43-f97d-4a61-ac31-dfa8b44503fb)

### Expected results

Orca produces a missing section 1 layer thick on part of the model and creates a seam. I can probably get permission to share the entire stl from Eclipson if needed.
![Cura](https://github.com/SoftFever/OrcaSlicer/assets/6632242/977c89d1-be8b-4c15-8550-3d658db77fdb)

### Project file & Debug log uploads

[Fuselage_F1-Spriral-Testing.zip](https://github.com/SoftFever/OrcaSlicer/files/14283251/Fuselage_F1-Spriral-Testing.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by pollosud** [comment]
I have the same problem. When I pront in Vase Mode, after about 10-12 layers, it does not print 2 layers .

**Comment by Noisyfox** [comment]
Does this issue occur on 1.9?

**Comment by mduclehcm** [comment]
I got the same issue on version 2.1.1 when printing rc air place in vase mode. The model is sliced perfect in cura slicer.

**Comment by DBShrill** [comment]
Same issue. Printing a spiral vase wing from **https://www.youtube.com/watch?v=QJjhMan6T_E** and have random empty layers. Only remedy is to increase "Slice Gap Closing Radius" until the empty layers disappear but everything else prints normally.
<img width="1173" alt="Screenshot 2024-11-27 at 5 09 39 PM" src="https://github.com/user-attachments/assets/13773e52-1837-4f64-a7a2-
<img width="1094" alt="Screenshot 2024-11-27 at 5 09 49 PM" src="https://github.com/user-attachments/assets/a670d8e4-b34f-4522-9454-7d987a5ba939">
3295c05d05d1">
