### ISSUE TITLE
printable area

### ISSUE THREAD

**Issue by Anothermbdusted** [SoftFever/OrcaSlicer#411]
**Describe the bug**
when going to your printers bed size in dark mode the pop up for the bed size is not in dark mode but a mix of dark and light modes

**To Reproduce**
i setup my own printer none bambu and  when you select the bed size in dark mode its always there

**Expected behavior**
should be in dark mode not a mix of normal and dark

**Screenshots**

**Printer model**
home built

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Windows] 10 home 64 bit
 - Version [e.g. 22] 22h2
    19045.2673    build

**Comment by hliebscher** [comment]
Which softfever software version are you referring to, and which printer specifically is this issue occurring on? Also, it would be helpful if you could provide a screenshot.

**Comment by DVSVIDEO** [comment]
This is what he meant [Anothermbdusted]
![BS_SF_issue](https://user-images.githubusercontent.com/96373457/224105801-a506264b-137d-4c7a-b235-e9a7f788038f.jpg)
