### ISSUE TITLE
max flow rate calibration model has non-manifold errors

### ISSUE THREAD

**Issue by julie777** [SoftFever/OrcaSlicer#4126]
### OrcaSlicer Version

1.9.0

### OS version

Windows 10

### Printer

P1P

### How to reproduce

1. select max flow rate from the calibration menu

### Actual results

![image](https://github.com/SoftFever/OrcaSlicer/assets/5090005/a2f9cd82-5cee-4533-91f4-d217bb6e9488)

### Expected results

The object to be sliced should not have errors.
It should also look like what is going to be printed

Note: this has been reported before, probably a year ago. It still has not been fixed so I am reporting it again.

### Project file & Debug log uploads

none

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by todd200** [comment]
I found this yesterday and tried the print before and after "repair." Does the print complete for you? For me it stops after the skirt is printed. Bed and nozzle stay at temp but longer move, just stops. Wonder if I should make a new issue?
