### ISSUE TITLE
temp tower does not slice correctly

### ISSUE THREAD

**Issue by julie777** [SoftFever/OrcaSlicer#4127]
### OrcaSlicer Version

1.9.1

### OS version

Windows 10

### Printer

P1P

### How to reproduce

1. select calibration/temp tower
2. set temp range 225-210
3. slice

### Actual results

![image](https://github.com/SoftFever/OrcaSlicer/assets/5090005/2c68ccb7-0b34-4a56-9215-74f9065af10f)

Temp tower is missing the Orca text on second layer
![image](https://github.com/SoftFever/OrcaSlicer/assets/5090005/c743aee2-1b7c-43c1-94b1-59745f3440ce)

If I repair non-manifold edges before slicing then the ORCA text for the first temp is missing
![image](https://github.com/SoftFever/OrcaSlicer/assets/5090005/f353761d-7599-4970-8dd3-b95a3d5d1c65)

### Expected results

I expect the object shown in the preview to be sliced and have all the original features
preview:
![image](https://github.com/SoftFever/OrcaSlicer/assets/5090005/10cbb660-4a86-4374-af6b-2b249515dd18)

### Project file & Debug log uploads

none

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by queueeeee** [comment]
This happens on my temp towers as well. unsure of what the cause is

**Comment by kenour** [comment]
It's a layer height issue, set layer height to 0.19 and it'll comes back. Seems to an issue of the feature falling between layers and being ignored.

Edit: Just confirmed, the top layers fall on an odd layer height of ##.7, and it's compounded by the text not being a full 0.2mm tall.
If you scale the model and set the height to 61mm, it'll sort it all out. Not sure if this will impact where the temp changes takes place (if it's layer or height based, can't be bothered looking). Either way, this is a pretty sloppy model and could do with an update.

**Comment by queueeeee** [comment]
Alright, I'll try that. Thank you for your help.

Kind regards,
Quinton
