### ISSUE TITLE
Staggered layer perimeters

### ISSUE THREAD

**Issue by shortbus** [SoftFever/OrcaSlicer#4133]
https://www.youtube.com/watch?v=5hGm6cubFVs

CNC Kitchen
Brick Layers: Could printing STRONG parts be so simple?

**Comment by Hammerfest** [comment]
Thats pretty insane, 10% while seemingly like nothing is huge at scale.

Hopefully someone reaches out to work through some of the issues he was unable to tackle to make it a usable method.

**Comment by Noisyfox** [comment]
That's interesting. I'll try implementing this when I got some time.

**Comment by paulnaude** [comment]
Very smart idea indeed. It falls in my "Why didn't I think of that?" category!
His visuals also show (without him saying it) why a little bit of increased flow will be a great idea to fill those gaps between the layer lines for maximum layer surface adhesion.

**Comment by AbitNutzT00** [comment]
I would really appreciate it if this could be implemented. Is this actively being worked on?

**Comment by balloch** [comment]
@Noisyfox I'm happy to contribute as well, where are you so far on this?

**Comment by cochcoder** [comment]
There is a issue request on [PrusaSlicer](https://github.com/prusa3d/PrusaSlicer/issues/1823) and they have come up with some cool ideas like [this one](https://github.com/prusa3d/PrusaSlicer/issues/1823#issuecomment-1961309760).

**Comment by doudar** [comment]
This is a really great idea. Hopefully someone can find time to implement it.

**Comment by theboee** [comment]
@Noisyfox Bumping this. Really want to see this added to a slicer.

**Comment by AbitNutzT00** [comment]
Me, too. It doesn't sound like they're interested, overwhelmed, have other priorities, or all of the above.

**Comment by xboxhacker** [comment]
BUMP. I need this!!

**Comment by jside86** [comment]
New video from Geek Detour on this:

https://www.youtube.com/watch?v=9IdNA_hWiyE

Apparently, someone was able to get a patent in 2020 that suggest the same thing as a previous Stratesys Patent from 1995. The patent should not have been approve and would most likely not hold up in court. 

Someone should create a update for Orca for this feature alone. 

Imagine having stronger layer adhesion!

**Comment by Nebur99** [comment]
> New video from Geek Detour on this:
The guy also summarized all the relevant facts in text: https://www.patreon.com/posts/115566868

**Comment by Shall0e** [comment]
Bumping this as well! We need this.

And yes, I did come from Geek Detour.

**Comment by sudokit** [comment]
This would be such a cool feature if implemented

**Comment by roger181078** [comment]
Testing is now possible:

[https://www.youtube.com/watch?v=EqRdQOoK5hc&list=LL&index=2](url)

[https://github.com/TengerTechnologies/Bricklayers](url)

Again, many thanks to the person who made this possible, and shared it with the community.
