### ISSUE TITLE
Feature Request "Paint Text"

### ISSUE THREAD

**Issue by KevinFairgrieve** [SoftFever/OrcaSlicer#4136]
**Is your feature request related to a problem? Please describe.**

**Which printers will be beneficial to this feature**
E.g. Voron/Klipper based printer/etc...

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

I am using a Bambu Lab P1S and would like to be able to paint text. When painting on a flat surface I would like to be able to select paint and then as an option in tool type. "TEXT".

**Comment by Noisyfox** [comment]
Use text tool as a modifier and set the filament.

**Comment by KevinFairgrieve** [comment]
> Use text tool as a modifier and set the filament.

Apologies, really new to Orca slicer. Could you explain in simple steps.

Many thanks.

**Comment by Noisyfox** [comment]
Right click the main object that you want to paint text on, select "Add modifier"->"Text", then put what ever text you want. Then go to object list, change the filemant you want to use for the text
![image](https://github.com/SoftFever/OrcaSlicer/assets/1537155/17b8c8fc-af1d-4b27-b0e6-f1b59bc4ae7b)

**Comment by KevinFairgrieve** [comment]
Got it, Thank you. 

Closing the issue.
