### ISSUE TITLE
TempTower non-manifold in 1.9.x

### ISSUE THREAD

**Issue by WimVDK** [SoftFever/OrcaSlicer#4139]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

1.9.1

### Operating System (OS)

Windows

### OS Version

11 23H2

### Printer

Bambulab X1C

### How to reproduce

1. Click Calibration
2. Click Temperature
3. Pick any tower type
4. Tower gets added

### Actual results

Loaded temp tower is non-manifold
![image](https://github.com/SoftFever/OrcaSlicer/assets/14872315/c259e764-237b-4c3c-8ff6-05119cbbb77a)

### Expected results

Manifold tower should be loaded. Towers in 1.8.x were fine.

### Project file & Debug log uploads

[Nozzle temperature test.zip](https://github.com/SoftFever/OrcaSlicer/files/14323043/Nozzle.temperature.test.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by Sp4rkR4t** [comment]
Just found this issue when testing 2.0
![image](https://github.com/SoftFever/OrcaSlicer/assets/3926906/7bbefec9-44e0-455b-af40-8995d0abe68c)

**Comment by WimVDK** [comment]
Issue persists in 2.0.0

Towers still not manifold

**Comment by hho** [comment]
Still an issue in 2.2.0
