### ISSUE TITLE
Inconsistent reporting of floating cantilever

### ISSUE THREAD

**Issue by Poporacer** [SoftFever/OrcaSlicer#4140]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

1.9.1

### Operating System (OS)

Windows

### OS Version

Widows 10

### Printer

Creality Ender 3 or Ender 5 Plus

### How to reproduce

1. Load file
2. Arrange file
3. Slice file
4. I get an error message as shown
5. Move object a few mm in the x or y direction
6. Slice the file
7. Error message is no longer generated

### Actual results

Slicing with the object "arranged" produces an error

![cantilever error](https://github.com/SoftFever/OrcaSlicer/assets/46263877/8998dc1b-f556-4568-b9ef-6b3c272248da)

If you move the object slightly in either x/y direction, the error no longer exists.

![cantilever no error](https://github.com/SoftFever/OrcaSlicer/assets/46263877/722d1075-799c-484f-8523-92de13d30735)

### Expected results

The floating cantilever error should be consistent.

### Project file & Debug log uploads

Both files are included in the zip file. 
 [Large BulbFinal.zip](https://github.com/SoftFever/OrcaSlicer/files/14323677/Large.BulbFinal.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by liftbag** [comment]
I can also confirm that, occasionally, this message appears in some stl and that, as reported, it is sufficient to move it to xy to eliminate the error.
