### ISSUE TITLE
Softfever not slicing correctly - adding extra lines to prints

### ISSUE THREAD

**Issue by parrothd** [SoftFever/OrcaSlicer#415]
**Describe the bug**
When using softfever to slice a 3d print with embossed texted the embossing or texted is filled incorrectly when prints. 

When I slice with Bambu the text is sliced and prints correctly. 

Both slicers are using the same default settings.

**3mf File for This Bug**
Can't attach 3mfs

**To Reproduce**
open and slice file, see the attached images, text is filled where it should not be.

**Expected behavior**
The print should look like the model, embossed text.

**Screenshots**
see screen shot

**Printer model**
p1p
**Desktop (please complete the following information):**
windows 10, latest patches, newest softfever 1.4.5
![2023-03-03_11-27-46](https://user-images.githubusercontent.com/47510399/222790180-cb90e1f1-72c0-4bce-b849-1e6fba24b2e2.jpg)

**Comment by SoftFever** [comment]
Hi @parrothd ,

Default settings are slightly different between SF and BambuStudio, you can try switching to the classic wall generator instead of Arachne. That might solve your problem.

**Comment by parrothd** [comment]
![2023-03-04_10-15-30](https://user-images.githubusercontent.com/47510399/222916912-a3f1f796-5f6b-4c5c-9e45-5a9d1c9265ef.jpg)

I changed softfever to classis and still has the same issue, see screen shot.

In Bambu I switched to Arachne and it still sliced correctly.

**Comment by hliebscher** [comment]
can you attach the 3mf project file from bs-sf as zip?

**Comment by parrothd** [comment]
It's the auto brim feature in softfever, if I change it to none it works all other options have the same issue. 

Strange that it's only on some text, and see the attached image, I see these tiny brims affects when using softfever with auto. brim. Could be something from fusion?

![2023-03-06_15-47-42](https://user-images.githubusercontent.com/47510399/223242665-609cab63-9992-4a41-82ba-b4002134d947.jpg)
 

[Softfever-Text-Issue.zip](https://github.com/SoftFever/BambuStudio-SoftFever/files/10903017/Softfever-Text-Issue.zip)

**Comment by SoftFever** [comment]
> It's the auto brim feature in softfever, if I change it to none it works all other options have the same issue.
> 
> Strange that it's only on some text, and see the attached image, I see these tiny brims affects when using softfever with auto. brim. Could be something from fusion?
> 
> ![2023-03-06_15-47-42](https://user-images.githubusercontent.com/47510399/223242665-609cab63-9992-4a41-82ba-b4002134d947.jpg)
> 
> [Softfever-Text-Issue.zip](https://github.com/SoftFever/BambuStudio-SoftFever/files/10903017/Softfever-Text-Issue.zip)

Thanks for the update.
Auto brim doesn't work well in many cases.
