### ISSUE TITLE
Can't start on hyprland

### ISSUE THREAD

**Issue by RandomLegend** [SoftFever/OrcaSlicer#4155]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

1.9.1-1

### Operating System (OS)

Linux

### OS Version

Garuda-Linux

### Additional system information

┌──────────────────────────────────────────┐
 ​ ​​  OS : Garuda Linux x86_64
 ​​ ​  Kernel : 6.7.5-zen1-1-zen
 ​​ ​  Packages : 2037 (pacman), 22 (flatpak)
 ​​ ​  Resolution : 3440x1440
 ​​ ​  DE : Hyprland
 ​​ ​  Terminal : alacritty
└──────────────────────────────────────────┘
┌──────────────────────────────────────────┐
 ​​ ​  CPU : AMD Ryzen 7 5800X3D (16) @ 3.400GHz
 ​​ ​  GPU : NVIDIA GeForce RTX 3070
 ​​ ​  GPU Driver : NVIDIA 545.29.06
 ​​ ​ ﬙ Memory : 7507MiB / 64206MiB
└──────────────────────────────────────────┘

### Printer

Bambulab X1C

### How to reproduce

Use any of the available packages for orcaslicer. Be it appimage, AUR build or AUR binary.

### Actual results

You will see the splash screen for a second and then it disappears. The console output crashes with:

```
libEGL warning: egl: failed to create dri2 screen
ERROR:             ICD associated with VkPhysicalDevice does not support GetPhysicalDeviceCalibrateableTimeDomainsKHR
fish: Job 1, 'orca-slicer' terminated by signal SIGABRT (Abort
```

This is the same with all of the packages.

### Expected results

The application starting.

It worked until recently.

### Project file & Debug log uploads

[debug_Mon_Feb_19_15_10_12_110890.log.0.txt](https://github.com/SoftFever/OrcaSlicer/files/14332149/debug_Mon_Feb_19_15_10_12_110890.log.0.txt)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by imJohly** [comment]
This seems like a problem with orca-slicer not liking the NVIDIA GPU. I've tried it on my main machine with an RTX 3060 and it produces the same error. On another machine with no discrete graphics card it was able to load. (Both running Arch Linux and Hyprland)

My **bandaid** solution is to run Orcaslicer as follows in a terminal (or you can change the .desktop file's exec command):

```bash
LIBGL_ALWAYS_SOFTWARE=1 orca-slicer
```

This forces the app to disable hardware acceleration and Orca slicer should load.
