### ISSUE TITLE
adding STL as modifier does not honor z-alignment

### ISSUE THREAD

**Issue by avxmw** [SoftFever/OrcaSlicer#4157]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

1.9.1

### Operating System (OS)

Linux

### OS Version

openSUSE Tumbleweed

### Printer

Creality K1

### How to reproduce

1. open some file
2. right click, add modifier, load, select file
3. observe position of newly added structures

### Actual results

Modifier file is aligned in X- and Y-direction, but not in Z, leading to manual positioning which is both fiddly as well as prone to errors.

### Expected results

Position perfectly as intended.

### Project file & Debug log uploads

-

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Anything else?

Works perfectly fine in PrusaSlicer, does not in OrcaSlicer. As such I call it a bug, if it's the result of a deliberate choice, I'd like to feature request this being optionally able to work as in PS.

![orcaprusabug](https://github.com/SoftFever/OrcaSlicer/assets/97355652/9044ad65-2243-4d5f-96ff-3a51efc34e23)

Edit, likely related to https://github.com/SoftFever/OrcaSlicer/pull/3802 however if that is what I understand it to be then it does not work for me.

**Comment by foghatredbird** [comment]
I'm unable to repro this (works for me).  If you'd like to provide a simple openscad repro I'd be happy to fix it.
