### ISSUE TITLE
Filament / Process Filter per Printer.

### ISSUE THREAD

**Issue by Glenno-H** [SoftFever/OrcaSlicer#4160]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

It would be nice to have the filaments / features filtered out by printer.  Ie, only the filaments tuned for that printer are shown (Or even just put at the top of the list)  This would help decluter the filament / process section a lot for those running multiple printers.

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

A "Filament / Process" filtering option per printer.

### Describe alternatives you've considered

I guess instead of a filter, the filament / process list could be resorted with the relevant ones at the top, but this sounds like it could cause other issues.

**Comment by tkunchick** [comment]
these should be combined,.

https://github.com/SoftFever/OrcaSlicer/issues/3821
