### ISSUE TITLE
Process Profile Loss on restart of Application

### ISSUE THREAD

**Issue by M1keGyver** [SoftFever/OrcaSlicer#4170]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

1.9.0 and 1.9.1

### Operating System (OS)

Windows

### OS Version

Windows 10 64-bit

### Additional system information

CPU: Intel(R) Core(TM) i7-4960X CPU @ 3.60GHz   3.60 GHz
RAM: 32GB

### Printer

Creality CR-10 Smart Pro with latest version of Octoprint

### How to reproduce

1. Create any process profile
2. Save the profile with any changes
3. Close Orca Slicer
4. Launch Orca Slicer
5. All Process Profiles are lost, only thing showing is "Default Setting"

![Orcaissue3](https://github.com/SoftFever/OrcaSlicer/assets/160449397/980da8ba-a92d-4e15-95d1-89323071cada)

### Actual results

All Process Profiles are lost, only thing showing is "Default Setting" and everything is set to back to nothing (line width etc)

### Expected results

I should be able to close Orca Slicer and reopen it again with all my process profiles intact.

### Project file & Debug log uploads

It is with any project file. Even just using the built in shapes.
[Orcaprofileissue.zip](https://github.com/SoftFever/OrcaSlicer/files/14345343/Orcaprofileissue.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Anything else?

- Something to note, printer profile and Filament Profiles seem to be intact. 

- Configuration Folder shows the profiles are there, Orcaslicer is just not registering or picking them up. Hopefully that should help with resolution.

- I made sure Auto syncing of user presets and Update Built-in presets automatically are turned off.
- 
![Orcaissue2](https://github.com/SoftFever/OrcaSlicer/assets/160449397/db155ad2-c85b-436f-a9b6-5e4da17f4d52)

**Comment by eduncan911** [comment]
Same issue with a 1.9.1 build I'm running.  

I'll try the 2.0 branch as it looks like 1.9 ain't getting any love.
