### ISSUE TITLE
Menus are blank 1.9.0 and 1.9.1 in Dark Mode

### ISSUE THREAD

**Issue by imk2021** [SoftFever/OrcaSlicer#4174]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

1.9.0 and 1.9.1

### Operating System (OS)

Windows

### OS Version

Windows 10 latest updates 

### Additional system information

CPU Intel 13th Gen with integrated GPU
16gb RAM, 512GB SSD

### Printer

K1C

### How to reproduce

I had 1.9.0 installed and all was working as expected (nice application many thanks) so i tried the Dark Mode which worked fine.
I manipulated the printer selections and accidentally  deleted all the stock printers, when trying to add them back the menus blank. I de-installed 1.9.0 from windows and reinstalled it again, but problem was the same. It seems maybe some Register/INI updates are still present after it was de-installed.   De-installed 1.9.0 again and installed 1.9.1 but problem same.
All the Preview functions panels/icons like lay flat, rotate, speed, supports all seems to work fine and the slicers function seem to work fine.
Maybe of interest; I C/C++ hobby develop using VS 2022 for PC/Windows and Arduino STM32
Just thought I'd mention above as maybe some conflict with your install.

### Actual results

None

### Expected results

None

### Project file & Debug log uploads

None

### Checklist of files to include

- [X] Log file
- [X] Project file

### Anything else?

None

**Comment by Ocraftyone** [comment]
Orca doesn't use the windows registry to store settings AFAIK. Have you tried deleting the OrcaSlicer folder under the app data folder? %appdata%/OrcaSlicer. That will reset the app completely.
