### ISSUE TITLE
Vase Mode Warning Causes Crash

### ISSUE THREAD

**Issue by Dragunbo3** [SoftFever/OrcaSlicer#4177]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

1.9.1

### Operating System (OS)

Windows

### OS Version

11

### Printer

Creality Ender 3 V3 SE

### How to reproduce

Loaded up the slicer new on my laptop to do some quick slicing.
Loaded the profile for the V3 SE
Did my settings and sliced my 4 prints. 
Also, I added and sliced 4 of the calibration tools, and each time it asked me to transfer my settings to the calibration tool. 
After loading the Others Tab and the Extruder Max test it popped up the Vase mode error and crashed. 

### Actual results

Now on launch, it gives the error and crashes and will not run no matter what I select. 
I uninstalled and reinstalled twice, and tried the portable version, but all give the same error and will not run the program.
I had to download Bambu Studio to check my Gcode files lol. 

### Expected results

The program should continue working normally.

### Project file & Debug log uploads

Cannot load the debug log as the program does not run on my laptop anymore. I assume I have to go digging for the userdata folder where the program stores user info and delete it. 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Anything else?

![Orca Error](https://github.com/SoftFever/OrcaSlicer/assets/160726552/36397be5-95c9-4096-8a0b-b125cd849bdf)

This error comes up and the Orca splash screen. But crashes and nothing you choose matters. Does this even on the portable version.

**Comment by xoma262** [comment]
It is still an issue in 2.2.0
