### ISSUE TITLE
Orca freeze and crash after network plugin update

### ISSUE THREAD

**Issue by gddrx** [SoftFever/OrcaSlicer#4178]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

1.9.1

### Operating System (OS)

Linux

### OS Version

openSuSE Tumbleweed

### Printer

Bambulab P1S

### How to reproduce

1. Run appimage Orcaslicer
2. Click new project
3. In right down corner i see message "New plugin available"
4. 
![2024-02-21_12-16](https://github.com/SoftFever/OrcaSlicer/assets/97629/13c99215-eeb4-4022-8b7b-aa41de6f3b1c)
5. Click Update plugin
6. Close orca
7. Run orca 

### Actual results

After this update and run appimage - orce runs and freez after i see window orca.
If i just wait, 1-3 mins = app crash.

### Expected results

Just normally working after update xD

### Project file & Debug log uploads

[Archive.tar.gz](https://github.com/SoftFever/OrcaSlicer/files/14357928/Archive.tar.gz)

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Anything else?

If i delete all configs or orca for "clear new first run" - all working before i sign in acc bambulab.
If i replace backup of old plugin version from /plugins/backup - orca runs and working again except i can't send project to print over cloud bambulab - freez at window where need select printer and click "Send". Before update plugin i can't send job to print too - freeze at window with printer select.

**Comment by ddt3** [comment]
I am faced with the exact same issue: restarting orca to install the new plugin: orca freezes and crashes. Replacing the new plug-in with the backup, all works fine.

### OrcaSlicer Version
1.9.1

### Operating System (OS)
Linux

### OS Version
Manjaro

### Additional system information
No response

### Printer
Bambulab X1C

### How to reproduce 
Run orca-slicer (from:[ AUR](https://aur.archlinux.org/packages/orca-slicer-bin))
(And then it continues as reported above...)

**Comment by ciphercore** [comment]
Seeing the same with the AppImage or AUR.  Starts crashing after network plugin update + logging in.


OrcaSlicer Version
1.9.1

Operating System (OS)
Linux

OS Version
Manjaro 

Additional system information
AUR and AppImage

**Comment by mike1808** [comment]
Same here on Manjaro. After bisecting I found that regression was introduced in 1.9.0. Downgrading to 1.8.1 fixes it.

**Comment by mike1808** [comment]
I have the same problem. The regression was added in 1.9.0. 1.8.1 runs normally.

**Comment by DarkMetatron** [comment]
Same issue with 1.9.0 and 1.9.1 but it works fine for me with the latest Nightly Appimage

Operating System (OS)
Linux

OS Version
Arch Linux

**Comment by acidg** [comment]
Crashing for me as well on Arch Linux

**Comment by jaype87** [comment]
Same here, thanks for identifying that the plugin was the culprit and mentioning the backup.

**Comment by mike1808** [comment]
Can someone share the backup? How do you make Orca not to automatically download it

**Comment by WayneManion** [comment]
I am having the same problem. The orca-slicer-bin and the orca-slicer AUR packages both work OK before I install the Bambu network plugin. After I install the latest version of the Bambu network plugin Orca Slicer always segfaults. 

https://aur.archlinux.org/packages/orca-slicer-bin#comment-957853

**Comment by WayneManion** [comment]
I have another computer I have not updated yet. What files do I need to grab from it to be able to use the Bambu net plugin? I would like to be able to sync my files.

**Comment by flying-x** [comment]
Same issue here on manjaro. I think all arch based system will be the same. The same version of orca was working fine until system update this week. Even bambustudio-git freeze and crash. It feel like the same OS issue.

**Comment by jaype87** [comment]
For me the backups where located under .config/OrcaSlicer/plugins/backup.
I just copied the libbambu_networking.so from backup to plugins and now hit cancel when it tells me about the new version.

**Comment by WayneManion** [comment]
[libbambu_networking.zip](https://github.com/SoftFever/OrcaSlicer/files/14420804/libbambu_networking.zip)

I dug backup Bambu Network Plugin file out of another machine that wasn't updated yet.

**Comment by Modusmundi** [comment]
I had this same issue in #4309, fix supplied here works but it obviously isn't a "fix" so much as it is rolling back to an old network driver.

**Comment by bullsbarry** [comment]
I have also experienced this issue which I "resolved" by rolling back the network plugin.

**Comment by rcragun1738** [comment]
Same issue for me on Kubuntu Linux. Crashes every time I try to Print my plate. Everything works fine until then. Rolling back the network driver provided here isn't working either. Orca basically can't send anything to my A1 mini anymore. :(

**Comment by SirSurfsAlot** [comment]
Does anyone have a version of this file for windows? When I found the network file to replace, it was a .dll file. Either I'm looking at the wrong file or I need a different file to swap out. 

I have the same issues as you've explained, if I start up Orca without being signed in it works fine but once I try to sign in, it gives an "unknown error; terminating the application" message and crashes.
