### ISSUE TITLE
The software crashes when I print on my P1S 

### ISSUE THREAD

**Issue by RafBois** [SoftFever/OrcaSlicer#4202]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

1.9.1

### Operating System (OS)

macOS

### OS Version

14.2.1 (23C71)

### Additional system information

Apple M1 Max

### Printer

P1S

### How to reproduce

The software crashes when I print on my P1S 

<img width="658" alt="Capture d’écran 2024-02-23 à 10 13 11" src="https://github.com/SoftFever/OrcaSlicer/assets/50773923/f52ea25d-fd97-44a8-8368-0ac4209a5bb5">
<img width="303" alt="Capture d’écran 2024-02-23 à 10 13 55" src="https://github.com/SoftFever/OrcaSlicer/assets/50773923/6d75d79b-5bf6-44a6-b607-d4ee696c3b05">

### Actual results

<img width="303" alt="Capture d’écran 2024-02-23 à 10 13 55" src="https://github.com/SoftFever/OrcaSlicer/assets/50773923/6d75d79b-5bf6-44a6-b607-d4ee696c3b05">

### Expected results

Unable to print with Orcaslicer 1.9.1. This worked perfectly before installing version 1.9.1.
I used it every day

### Project file & Debug log uploads

[Archive.zip](https://github.com/SoftFever/OrcaSlicer/files/14383579/Archive.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Anything else?

<img width="303" alt="Capture d’écran 2024-02-23 à 10 13 55" src="https://github.com/SoftFever/OrcaSlicer/assets/50773923/ebdc3812-70ba-45a2-a3c8-b7145e17691d">
<img width="658" alt="Capture d’écran 2024-02-23 à 10 13 11" src="https://github.com/SoftFever/OrcaSlicer/assets/50773923/847ed44a-1594-4971-a958-33ce5e762e89">

**Comment by Jer406** [comment]
im having them same issue on windows

**Comment by git-rz** [comment]
Same issue on windows, but the printer is Voron Trident running latest Mainsail / Klipper.
