### ISSUE TITLE
FlashForge Adventurer 4 profile request

### ISSUE THREAD

**Issue by mjexcelle** [SoftFever/OrcaSlicer#4206]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

The only problem is not having the FF Adventurer 4 profile supported.

### Which printers will be beneficial to this feature?

Marlin

### Describe the solution you'd like

I would like to see FlashForge Adventurer 4 profile with 0.3, 0.4, and 0.6 nozzle size and High Speed print support for the OrcaSlicer. I think it's great you have the Adventurer 5 but alot of people have the 4 series also.

**Comment by Shad0wyDr3amz** [comment]
this would be a great thing to have still. still using my ADV4 and been wanting to use orcaslicer with it
