### ISSUE TITLE
Allow non uniform scaling on multiple objects 

### ISSUE THREAD

**Issue by eriroh** [SoftFever/OrcaSlicer#421]
It would be nice if it was possible to scale multiple objects nonuniformly. At the moment it is only possible to scale multiple objects uniformly and the option can't be unchecked. 

![image](https://user-images.githubusercontent.com/62106991/222853709-085d807f-59c2-4159-abf0-de1d86b85e79.png)

**Comment by hliebscher** [comment]
it is a Feature request ;-)
