### ISSUE TITLE
Add Device: Anycubic Kobra 2 Plus (Easy to do)

### ISSUE THREAD

**Issue by aldaw** [SoftFever/OrcaSlicer#4210]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I have downloaded the nightly 2.0 and the Anycubic Kobra 2 Plus is missing in the list.

### Which printers will be beneficial to this feature?

Klipper

### Describe the solution you'd like

The Anycubc Kobra 2 Plus is listed.

**You can download and the settings from their official homepage for prusiaslicer.**
https://store.anycubic.com/pages/firmware-software
https://drive.google.com/file/d/1D-iqxPlP9TRq5NXVWtQRBSRd3YL2Ip79/view?usp=drive_link

**Here is a script to convert it in .json for orcaslicer.**
https://github.com/theophile/SuperSlicer_to_Orca_scripts

**Comment by aldaw** [comment]
Here is a script to convert it in .json for orcaslicer.
https://github.com/theophile/SuperSlicer_to_Orca_scripts

**Comment by cropse** [comment]
I've same feature request, thanks.

**Comment by cropse** [comment]
OK, I tried and it ends out not good https://github.com/theophile/SuperSlicer_to_Orca_scripts/issues/31

**Comment by White3rabbit** [comment]
I have the same problem.

**Comment by NnamOnye** [comment]
Please integrate Anycubic Kobra 2 Plus into the orca slicer

**Comment by cropse** [comment]
@NnamOnye Try this and read the comment: https://www.printables.com/model/788326-kobra-2-pro-profiles-for-orcaslicer
