### ISSUE TITLE
Arc fitting wall overflow problem

### ISSUE THREAD

**Issue by olcayoren** [SoftFever/OrcaSlicer#4215]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

1.9.1

### Operating System (OS)

macOS

### OS Version

14.2.1 Sonoma

### Additional system information

Air M1 Arm

### Printer

Elegoo Neptune 4 Pro

### How to reproduce

1- Add Cylinder
2- On arc fitting

### Actual results

**Arc fitting on:**

<img width="398" alt="Ekran Resmi 2024-02-24 14 44 26" src="https://github.com/SoftFever/OrcaSlicer/assets/33813227/d5083f28-494e-49ab-aa40-f1469dd1ed14">
<img width="664" alt="Ekran Resmi 2024-02-24 14 44 32" src="https://github.com/SoftFever/OrcaSlicer/assets/33813227/0ca081fd-49ec-420a-bb45-34d7be705f4c">

**Arc fitting off:**

<img width="399" alt="Ekran Resmi 2024-02-24 14 44 51" src="https://github.com/SoftFever/OrcaSlicer/assets/33813227/eb07fc56-495b-4270-8e91-e6c121166bed">
<img width="610" alt="Ekran Resmi 2024-02-24 14 44 56" src="https://github.com/SoftFever/OrcaSlicer/assets/33813227/410c4804-827e-4fb2-b518-814007f5b620">

### Expected results

None

### Project file & Debug log uploads

[Cylinder.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/14392657/Cylinder.3mf.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by igiannakas** [comment]
Your resolution is set to 0... Set it back to default and try again

**Comment by olcayoren** [comment]
> Your resolution is set to 0... Set it back to default and try again

With default values, there are still deformities on the walls

**Arc fitting on:**

<img width="394" alt="Ekran Resmi 2024-02-26 10 40 09" src="https://github.com/SoftFever/OrcaSlicer/assets/33813227/03150e1c-751f-4959-819e-76469318837a">
<img width="675" alt="Ekran Resmi 2024-02-26 10 39 53" src="https://github.com/SoftFever/OrcaSlicer/assets/33813227/2a8c6405-a830-41d5-a32a-0b081951c4e9">


**Arc fitting off:**

<img width="390" alt="Ekran Resmi 2024-02-26 10 40 47" src="https://github.com/SoftFever/OrcaSlicer/assets/33813227/4f3b59db-fa66-4585-9951-771fbaca59e2">
<img width="634" alt="Ekran Resmi 2024-02-26 10 40 26" src="https://github.com/SoftFever/OrcaSlicer/assets/33813227/c6169611-0f13-4481-a6cb-e0f8fadcd9de">

**Comment by igiannakas** [comment]
With klipper arc fitting should be turned off as klipper does not create arc movements - it breaks them down to segments (lines) defined by the resolution in the printer.cfg.

if you print the cylinder on a Bambu or marlin printer you they will come out artefacts free.

**Comment by olcayoren** [comment]
> With klipper arc fitting should be turned off as klipper does not create arc movements - it breaks them down to segments (lines) defined by the resolution in the printer.cfg.
> 
> if you print the cylinder on a Bambu or marlin printer you they will come out artefacts free.

I didn't know thatklipper doesn't support g2 and g3 commands. When I examined it in detail, I confirmed that it was not supported. Thank you for your information. 👏
