### ISSUE TITLE
Arc fitting not working using ender profile but works if I modify the bambu profile for the ender.

### ISSUE THREAD

**Issue by CodeMasterCody3D** [SoftFever/OrcaSlicer#4216]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

1.9

### Operating System (OS)

Windows

### OS Version

10

### Additional system information

Ryzen 3600 16fb ram rx 5700xt

### Printer

Ender 3 Pro 

### How to reproduce

If I have 2 instances opened up of Orca, one with bambu profile and the other ender profile I copied all settings over to the bambu for the ender and vice versa trying to get the arc fitting to work like the modified bambu profile that works on the ender 3 with arc fitting. Arc fitting does not work like it does on bambu profile while on ender profile despite any settings changes like slowing down for overhangs.

### Actual results

The ender profile does not incorporate the arc fitting properly on the chimney area of the 3d benchy (circular object) 

### Expected results

I should see G2 commands for arc circular motion on gcode for the chimney area on the 3d benchy but I do not.

### Project file & Debug log uploads

[](url)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Anything else?

Simple fix possibly for now is to add function of octoprint server add on for the bambu profile So i can quickly upload.

**Comment by hidara2000** [comment]
My following comment may be related. 

On some profiles I can check the arc fitting option but for some profiles, it is greyed out

https://github.com/SoftFever/OrcaSlicer/assets/15170494/65077982-f477-44cc-9189-6392e0baf0cc

**Comment by dJOS1475** [comment]
I can confirm this Arc fitting bug is real - if I select a Voron default profile it’s not greyed out:

![Screenshot 2024-04-17 at 8 58 22 AM](https://github.com/SoftFever/OrcaSlicer/assets/39177227/f1440590-3fdb-4edb-bc4c-c540470d0ca5)

However, on profiles I created from the Voron Standard profile on earlier versions of OS, it's greyed out:

![Screenshot 2024-04-17 at 8 59 31 AM](https://github.com/SoftFever/OrcaSlicer/assets/39177227/596652f8-53a4-4f03-ae04-bc8995209dfb)

**Comment by CanaryTours** [comment]
Same here, I can't find what is not letting me activate the Arc fitting, did you find any solution?
