### ISSUE TITLE
SV07+ process profiles are ridicolously slow

### ISSUE THREAD

**Issue by ForenSeil** [SoftFever/OrcaSlicer#4223]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0-dev

### Operating System (OS)

Windows

### OS Version

Win 10 and Win 11

### Additional system information

Tested on different PCs

### Printer

SV07+

### How to reproduce

Printspeed/overhang/acceleration in process settings are extremly slow
![spped](https://github.com/SoftFever/OrcaSlicer/assets/161213536/45aebe31-b45c-4ca3-9839-803dded20fb8)
![Unbenannt](https://github.com/SoftFever/OrcaSlicer/assets/161213536/10c21fd4-2380-416f-8484-de24fa2b4e52)

### Actual results

Prints are extremly slow

### Expected results

SV07+ is a very fast printer

### Project file & Debug log uploads

Not necessary

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by cochcoder** [comment]
What speeds do you suggest should be used and in what profiles? Do these speeds match the desired quality from these profiles?
