### ISSUE TITLE
No Wipe Is Present With Outer/Inner Wall Order

### ISSUE THREAD

**Issue by cubitik** [SoftFever/OrcaSlicer#4226]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

1.9.1

### Operating System (OS)

Windows

### OS Version

Windows 10

### Printer

ELEGOO Neptune 4 Pro

### How to reproduce

Slice any model with inner/outer wall order, examine seams to see the wipe operation. And slice the same model with outer/inner wall order and boom, see, wipe is gone on seams (no wipe). Issue with outer/inner wall order gets fixed by defining turning on "Travel distance threshold" and setting value to 0. Inner/Outer wall order works perfectly without turning on or off Travel distance threshold.
![inner-outer-orca](https://github.com/SoftFever/OrcaSlicer/assets/111056006/b1dc7421-3f62-4316-83f0-61d07e2bfff0)
![outer-inner-orca](https://github.com/SoftFever/OrcaSlicer/assets/111056006/80e6a3e5-f155-4e10-8fd6-e6541b14a9e0)
![outer-inner-with-threshold-0-orca](https://github.com/SoftFever/OrcaSlicer/assets/111056006/2777a271-ff26-4e6d-9052-3c4c19ca0b96)

### Actual results

![prints2](https://github.com/SoftFever/OrcaSlicer/assets/111056006/26c92e3d-36bb-4a9a-a5f6-e98c244c5661)
![20240225_164322 1](https://github.com/SoftFever/OrcaSlicer/assets/111056006/d47f25f8-654f-48ab-abeb-96242dc8c770)

### Expected results

Wipe at seams without playing travel distance threshold when outer/inner wall order selected.

### Project file & Debug log uploads

[project-files.zip](https://github.com/SoftFever/OrcaSlicer/files/14396731/project-files.zip)
[logs.zip](https://github.com/SoftFever/OrcaSlicer/files/14396734/logs.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by will-flaugher** [comment]
I'm having a similar issue with 2.0.0. It also looks to me like under-extrusion to start the layers, but the first few layers look very similar to yours. This wasn't an issue with older versions and I'll have to roll back to the previous version of OrcaSlicer until it's resolved.

![bad seam](https://github.com/SoftFever/OrcaSlicer/assets/35500351/89d5e2a7-5268-492a-8a66-3a7f5e153c9a)
