### ISSUE TITLE
Version information is not correctly added to exe and dll files during build

### ISSUE THREAD

**Issue by julie777** [SoftFever/OrcaSlicer#4228]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

1.9.1

### Operating System (OS)

Windows

### OS Version

10

### Printer

p1p

### How to reproduce

1. Look at Windows event log (event viewer) application log after an Orca Slicer crash

### Actual results

The following is the event log information showing version for the exe and dll with bad values for the version which is not helpful for debugging.

Faulting application name: orca-slicer.exe, version: 1.0.0.0, time stamp: 0x65ce0863
Faulting module name: BambuSource.dll_unloaded, version: 0.0.0.0, time stamp: 0x65c1c501
Exception code: 0xc0000005
Fault offset: 0x00000000000a6156
Faulting process id: 0x6764
Faulting application start time: 0x01da64ef43d848fd
Faulting application path: C:\Program Files\OrcaSlicer\orca-slicer.exe
Faulting module path: BambuSource.dll
Report Id: 5777cf15-316d-4996-8b67-c924842aa2b3
Faulting package full name: 
Faulting package-relative application ID: 

### Expected results

During the build, the version should be added in the code to enable debugging. This makes it easy to correlate a problem to the actual source code of the application.

In addition, when the application is started, the initial entry in the debug log file should be detailed version information for all parts of the application (exe, dlls) and the OS. This allows a log file to provide complete and correct information when diagnosing a problem regardless of what is provided by other means.

Note: I do not understand the debug log process. It seems to start logs at random times and does not appear to start a new log file when Orca Slicer is started, which is something that I think would be extremely helpful. 

Log file naming could also be improved. Adding a sequence number after the filename extension prevents file association from working correctly, and double clicking on the file does not open the with the default text editor. Given that the time when the log file is created is part of the name it should not need a sequence suffix. 
    Ex: 
```
    debug_Fri_Feb_23_11_05_15_13588.log.1
```

I would suggest an improved name format that is more human readable and sorts correctly by using ISO 8601 with a space instead of the 'T' date/time separator which is allowed (https://en.wikipedia.org/wiki/ISO_8601).
```
    <logtype>_<ISO timestamp>.log
```
This format would give a log file a name such as 
```
    debug_2024-02-24 05:15:13.log
``` 
for the above mentioned file. The ISO timestamp allows sorting files by name to also be sorted chronologically and is very human readable. 

### Project file & Debug log uploads

N/A

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by kylek29** [comment]
Yeah, you can further confirm this by right-clicking the .exe and viewing the properties, the version info is not set, and seems to receive (or have) generic placeholders.
