### ISSUE TITLE
Different Extrusion Multiplier (flow ratio) on multiple objects for testing

### ISSUE THREAD

**Issue by TheJoyofPrinting** [SoftFever/OrcaSlicer#4230]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Im dialing in my voron using the Ellis tuning guide and it says that some slicers allow you to set the extrusion multiplier (flow ratio) for each object. while Orca slicer/ prusa slicer/ bambu studio do not. 

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

I would like to be able to right click or go into objects and change the extrusion multiplier for each model. It looks like atm the only way to change the extrusion multiplier (flow ratio) is inside the filament section.

### Describe alternatives you've considered

1. Add an option when you right click a model to change the Extrusion multiplier (flow ratio)
2. When you go into individual objects mode have a setting for extrusion multiplier (flow ratio)
![Screenshot 2024-02-25 150900](https://github.com/SoftFever/OrcaSlicer/assets/88120921/512ece8b-c11c-401d-af83-17739449cb65)
![Screenshot 2024-02-25 150840](https://github.com/SoftFever/OrcaSlicer/assets/88120921/2b03de4e-7037-4233-ba0f-cb1ee0a9f794)

**Comment by igiannakas** [comment]
you can change the flow ratio (EM) per object in the quality - flow ratio setting:

![image](https://github.com/SoftFever/OrcaSlicer/assets/59056762/ccd0eb6f-a5d5-443f-8662-edadc30e0937)

**Comment by TheJoyofPrinting** [comment]
Thank you for showing me this. Could not find anything when I looked. Problem solved well done orca slicer!

**Comment by drake90001** [comment]
please reopen this issue, this setting does not show up when searching any of the searchable settings.
