### ISSUE TITLE
Can't create new filament presets with imported printer presets

### ISSUE THREAD

**Issue by Apotrox** [SoftFever/OrcaSlicer#4252]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

1.9.1

### Operating System (OS)

Windows

### OS Version

Windows 11

### Additional system information

Ryzen 9 5900x, RTX 3080, 32GB 3200mhz RAM

### Printer

Anycubic Kobra Neo

### How to reproduce

1. Import custom printer profile 
2. Try to create a filament preset for that printer

### Actual results

Filament Presets created under the system printer preset will not show up for the custom printer presets. 

### Expected results

Being able to create filament presets under the custom printer preset (or preferably without being tied to any printer at all!)

### Project file & Debug log uploads

[debug_Wed_Feb_28_17_25_57_16764.log.zip](https://github.com/SoftFever/OrcaSlicer/files/14437526/debug_Wed_Feb_28_17_25_57_16764.log.zip)
[new.zip](https://github.com/SoftFever/OrcaSlicer/files/14437543/new.zip)
Note that the project file doesnt contain a model (but hopefully the presets)
[Printer presets.zip](https://github.com/SoftFever/OrcaSlicer/files/14437602/Printer.presets.zip)
Here are the printer presets

### Checklist of files to include

- [X] Log file
- [X] Project file

### Anything else?

![grafik](https://github.com/SoftFever/OrcaSlicer/assets/26527256/806f4906-e1e0-45ec-afd7-0efa3ac93aa8)
When trying to create the filament with a existing preset (which doesnt exist)
![grafik](https://github.com/SoftFever/OrcaSlicer/assets/26527256/9c545ec9-1233-4eb4-971b-4a0e64726d46)

![grafik](https://github.com/SoftFever/OrcaSlicer/assets/26527256/5082985d-351e-4328-a31a-4edbab4bfb9c)
Doesnt appear under my custom printer presets
![grafik](https://github.com/SoftFever/OrcaSlicer/assets/26527256/0fead1a7-3a6c-484c-8363-14f33bb6143e)
Only for the generic klipper preset

**Comment by Apotrox** [comment]
Maybe i just can't use OrcaSlicer correctly but i'd also like to point out that adding my 3 existing filament presets was already incredibly cumbersome to do due to the exact same issue.

**Comment by GitHag42** [comment]
I wanted to open the very same topic:
Can't create Custom Filaments for my custom (imported) printer preset.

I see a usecase for printer related filament profiles: e.g. different retract overwrites for different printers (bowden or direct extruder) OR when real temperatures significantly differ on different printers for the same set value OR different fan speeds are needed due to different setups.
But it would also be nice to assign a filament profile to several printers at once if such a differentiation is not needed.

By the way, where do you get all the filament information from (density, shrinkage, softening temp, ...)?

**Comment by Apotrox** [comment]
@GitHag42 from the manufacturers website usually (see [here](https://www.elegoo.com/en-de/products/elegoo-pla-3d-printer-filament-1-75mm-colored-1kg) for example). Everything i don't know i just leave as is.

**Comment by karaktaka** [comment]
It seems like this problem still exists in the current Beta. In Version 2.0.0 it worked sometimes but I had multiple "Printers" as choice (I suspect it was always the same as it showed the exact same name multiple times), but now in Beta 2.1.0 I don't see any printers anymore when trying to add a custom filament.
![grafik](https://github.com/SoftFever/OrcaSlicer/assets/1451140/2a13cd29-7f37-4b4f-9bc8-ca7cda86f655)
