### ISSUE TITLE
Can't Slice file to send to A1 Mini

### ISSUE THREAD

**Issue by skl111** [SoftFever/OrcaSlicer#4262]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0-DEV

### Operating System (OS)

Windows

### OS Version

11

### Printer

Bambu Labs A1 Mini

### How to reproduce

Attempt to slice a file using the A1 Mini Profile

### Actual results

It produces this error
![Screenshot 2024-02-28 225831](https://github.com/SoftFever/OrcaSlicer/assets/25110469/397bbea3-0fce-4a41-908a-11f25c17a024)

### Expected results

Slice should complete without errors

### Project file & Debug log uploads

[debug_Wed_Feb_28_23_12_03_254688.log.zip](https://github.com/SoftFever/OrcaSlicer/files/14442716/debug_Wed_Feb_28_23_12_03_254688.log.zip)
[Cube.zip](https://github.com/SoftFever/OrcaSlicer/files/14442718/Cube.zip)

### Checklist of files to include

- [x] Log file
- [x] Project file

**Comment by SoftFever** [comment]
Thank you for reporting this.
Fixed now.
The fix will be included in the nightly release once the auto build complete

**Comment by skl111** [comment]
Welcome, and thank you!

**Comment by skl111** [comment]
I can confirm the build fixed it, just sliced and diced it into an A1 Mini
