### ISSUE TITLE
gcode to anycubic --- Damaged file, cannot view details

### ISSUE THREAD

**Issue by sysnxw** [SoftFever/OrcaSlicer#4265]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

1.9.1

### Operating System (OS)

Windows

### OS Version

win10

### Printer

kobra2pro

### How to reproduce

Must appear.

### Actual results

G files uploaded to cloud-universe.anycubic.com, When viewing or printing, the web page prompts "Damaged file, cannot view details"

### Expected results

You can view it through the web, and the app prints Gcode.

### Project file & Debug log uploads

“”Damaged file, cannot view details“”

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by nyonor2** [comment]
so?

**Comment by A-lexLuthor** [comment]
Hello, same issue here. I search every where but can't find a solution

**Comment by Frengo92** [comment]
Any news about the problem?
