### ISSUE TITLE
Fan Control Fail - Starts fans at 100% instead of filament setting.

### ISSUE THREAD

**Issue by tkunchick** [SoftFever/OrcaSlicer#4270]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

1.9.1

### Operating System (OS)

macOS

### OS Version

Sonoma 14.3.1 (23D60)

### Printer

K1 Max

### How to reproduce

**Set fan speeds in filament profile**

![Fan Control Fail 1](https://github.com/SoftFever/OrcaSlicer/assets/45150915/f4f66fc2-75dc-490a-8836-88ca00fca3de)

**slice multi layer file**
![Fan Control Fail 2](https://github.com/SoftFever/OrcaSlicer/assets/45150915/5b8d9c8e-49ae-42a6-af5a-349473c8e431)

**check fan speed at different levels in preview and gcode**
![Fan Control Fail 3](https://github.com/SoftFever/OrcaSlicer/assets/45150915/addafe03-88b2-43b3-b0b0-3b97da3f1e26)
<img width="778" alt="Fan Control Fail 4" src="https://github.com/SoftFever/OrcaSlicer/assets/45150915/abf437f6-f3f7-46ef-bd91-2cd8d9c99cae">

### Actual results

Fans start at 100% regardless of filament profile settings.

**Corrects it self once it hits something that changes fan speed such as over hang or support and then runs at correct filament setting.**
![After hitting support](https://github.com/SoftFever/OrcaSlicer/assets/45150915/95fb3a51-c5c8-4ae4-b3f2-38758b0f8fa2)

### Expected results

Starting at indicated level, fans speed set to setting as indicated in filament profile.

### Project file & Debug log uploads

No log

### Checklist of files to include

- [x] Log file
- [x] Project file

**Comment by Asiak3** [comment]
Same issue V2.2.0

**Comment by Chevan94** [comment]
It's the same issue in all the recent versions of Orca.
The M106 S255 seems to get inserted right after the filament change gcode, resulting in turning the fan on full blast, instead of the setting dictated by the filament. 

I tried a lot of things, Bambu Studio doesn't do that. 

Has anyone managed to work around this somehow?

I'm on BambuLab A1.
