### ISSUE TITLE
Ender 3 Max Neo profile!

### ISSUE THREAD

**Issue by Wunder111** [SoftFever/OrcaSlicer#4275]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Could we get a ender 3 max neo profile for the Orca Slicer? I looked it up and their was no issues.

### Which printers will be beneficial to this feature?

Others, All

### Describe the solution you'd like

New profile for Ender 3 Max Neo

**Comment by Duck-Lady** [comment]
Is anything being done for this?

**Comment by fjfuen** [comment]
Following up, any updates?

**Comment by Wunder111** [comment]
Not that I know of

**Comment by lucas-fs** [comment]
Any updates on this?
