### ISSUE TITLE
undefined symbol: eglCreatePlatformWindowSurface

### ISSUE THREAD

**Issue by drtedastro** [SoftFever/OrcaSlicer#4284]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

1.9.0 1.9.1

### Operating System (OS)

Linux

### OS Version

Ubuntu Mint 20.4

### Additional system information

CPU:       Topology: 8-Core model: AMD FX-8350 bits: 64 type: MCP arch: Bulldozer
Graphics:  Device-1: NVIDIA GK104 [GeForce GTX 690] vendor: ASUSTeK driver: nvidia v: 340.108 
Memory: 32 GB

### Printer

Never got to choose

### How to reproduce

1. download appimage
2. change permissions to executable
3. try to run normal, double click.  nothing
4. try to run from terminal ./appimage
5. get ./OrcaSlicer_Linux_V1.9.1.AppImage 
/tmp/.mount_OrcaSlvST36B/bin/orca-slicer: symbol lookup error: /tmp/.mount_OrcaSlvST36B/bin/orca-slicer: undefined symbol: eglCreatePlatformWindowSurface

### Actual results

?

### Expected results

turn actually work

### Project file & Debug log uploads

none created

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Anything else?

Just a simple crash, well not even crash...  A non start,

**Comment by hyegeek** [comment]
This is likely due to a lack of wayland support in your base OS. I'm running into the same issue with Gentoo as you are with Mint. It would be nice if the AppImage could be created with the known workarounds for this issue.
