### ISSUE TITLE
New Sidebar

### ISSUE THREAD

**Issue by ThinkBigPrintHuge** [SoftFever/OrcaSlicer#4300]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

1.9.1 sidebar is as bad/worse/more confusing than 1.9.0.

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

Please add a checkbox option to enable/disable floating sidebar in Preferences. I am still stuck on 1.8.1 because the new sidebar is unusable for a heavy user. The default collapse hides half of the settings and expanding it is not a great experience. It's jittery and you can't see where it's going to be set until it's actually set. I finally downloaded 1.9.1 because it was supposed to have an updated collapsible sidebar which also docks (compared to 1.9.0 beta). Ok great, so I undock it to see how to re-dock feature works. Now I haven't been able to find how to re-dock it. I even uninstalled and reinstalled and it's stuck undocked. I found a settings in Preferences to reset default layout, but it doesn't reset it to default. It sets it to a collapsed sidebar. So unfortunately I won't get to use any of the new features until this issue is fixed as I will be reverting back to 1.8.1 again. 

PS. 
The new features are amazing and I cannot wait to get to use them! Orca has absolutely changed my overall 3D printing experience as a whole and I appreciate all the work you guys do!

### Describe alternatives you've considered

I will be reverting back to v1.8.1

**Comment by Noisyfox** [comment]
Try the latest nightly build, which should have fixed some issue with the sidebar size.
Regarding re-docking the sidebar, simply click on the up most space of the sidebar and drag it to the left/right most of the main window and it should re-dock:

![orca_dock](https://github.com/SoftFever/OrcaSlicer/assets/1537155/d71ba96c-6069-4324-8d32-ea4471d9124d)
