### ISSUE TITLE
Implement BugFix for unexpected seam in vase mode

### ISSUE THREAD

**Issue by djonasdev** [SoftFever/OrcaSlicer#431]
I currently have the problem that a seam can be seen in vase mode. This is probably a problem that is in the original source code.

`degroof` has probably managed to write a small hotfix for it in java. Would it be possible to implement this as an experimental fix (optionally with a checkbox)?
Should this feature be implemented in BambuStudio, especially in the SoftFever Fork, this will again be an enormous boost for our community.

https://github.com/prusa3d/PrusaSlicer/issues/2841#issuecomment-1267667080

### screenshots:

![grafik](https://user-images.githubusercontent.com/17551597/223078049-def2f5c8-87aa-4141-8faf-c3f4c8facf2d.png)

### sample stl file

https://anonfiles.com/L1y8xfc1z8/peel_stl

**Comment by Pmant** [comment]
This is a post processing script and would not work during slicing. You probably can add it as a post processing script, which is supported by the SoftFever fork. 
There is always a risk when using such scripts to allter your gcode as they can easily do so in unintended ways. The author of the script describes it as alpha and that it does things like removing color changes.

**Comment by npoulos** [comment]
Where can you find the option to add post processing scripts in softfever? Didn’t know this was available!

**Comment by Pmant** [comment]
Under process settings -> others. Personally I have not used it so far.
