### ISSUE TITLE
Custom transition filaments through the use of an AMS

### ISSUE THREAD

**Issue by Keitio** [SoftFever/OrcaSlicer#4318]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

With the use of an AMS, MMU or equivalent, we could create our own transition filaments by swapping colors every meter for exemple and not purging anything to allow for the transition to show

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

Enable the creation of transition "meta-filaments" with settings, e.g. swap between filaments 1 and 2 every 1.5m
This may need a smaller prime tower than usual to keep the transitions showing
It also may be interesting to have less purge in the filament swap portion

### Describe alternatives you've considered

Swapping filament every few layers with 0 purge but a prime tower kind of works but is very tedious and doesn't have the same effect due to layers not necessarily having the same amount of filament used, altough this could be somewhat automated

Layer swapping also has the downside of being very repetitive and thus showing a pattern on your print which woiuld not happen when swapping on a length basis.

### Additional context

Here is a benchy with a color swap every 4 layers and a 45mm³ prime tower.
As you can see, while the output is nice, it would be quite different with a "normal" transition filament that is length-based
![IMG_20240303_165359981](https://github.com/SoftFever/OrcaSlicer/assets/23667092/1ab5e836-0ea9-4ac5-abee-77d866ea00a2)

For reference, this was ~8m of filament total, with ~2m for each color for both the prime tower and the model, and ~60 filament swaps

I could contribute to the code but am not well-versed in neither gcode nor C++, but am willing to try if someone points in the general direction of where this kind of code is located

**Comment by djcosmic22** [comment]
In addition, what if you could have a script to change AMS slots (between 2-4 slots) randomly every X meters of material used where X is a random number between Y and Z?
