### ISSUE TITLE
Add “complete print” fan speed for aux fan. 

### ISSUE THREAD

**Issue by Qjeezy** [SoftFever/OrcaSlicer#4321]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

No problem, just feature enhancement. 

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

Add an option in the filament profile to have the auxiliary fan turn on when the print is completed. For those of us with a bento box, this will be beneficial to help circulate the air when a print is complete so the bento box can scrub the air more efficiently before we open the chamber and collect our prints. This can reduce exposure to any VOC’s that are released during printing of engineering materials by helping the bento box scrub the air quicker. This is also useful for those of us that have hepa filters located on the inlet of the aux fan. It would act exactly like the existing “complete print” option that is there for the exhaust fan.  

### Describe alternatives you've considered

The only alternative at the moment to complete the task is to turn on the aux fan manually when the print is complete.

**Comment by alexn-s** [comment]
awesome idea. i would love to see that

**Comment by vgdh** [comment]
it easily doable with end print gcode

**Comment by Qjeezy** [comment]
> it easily doable with end print gcode

It is, but an official option next to the other similar ones would be better.
