### ISSUE TITLE
Flow Dynamics Calibration Silliness 

### ISSUE THREAD

**Issue by DARKFiB3R** [SoftFever/OrcaSlicer#4326]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

1.9.0

### Operating System (OS)

Windows

### OS Version

OS: Windows 10

### Additional system information

CPU: i7-4790K 4.4GHz
RAM: 16GB
GFX: GTX 970

### Printer

Bambu Lab P1S

### How to reproduce

Attempt to start Flow Dynamics Calibration

### Actual results

Can't continue due to invalid default values

Suggested values also do not work.

Wording is inconsistent, i.e. "From K Value" = "Start Value", etc.

![orca-slicer_2024-03-03_22-13-09](https://github.com/SoftFever/OrcaSlicer/assets/654659/6c395c22-a381-4a27-849b-8377b6e420c6)

![orca-slicer_2024-03-03_22-17-08](https://github.com/SoftFever/OrcaSlicer/assets/654659/eb949039-043c-48fb-b87d-4b7254bbaf7b)

![orca-slicer_2024-03-03_22-19-08](https://github.com/SoftFever/OrcaSlicer/assets/654659/9b4be165-7bde-4e9c-a0cd-e7be75ee140b)

### Expected results

Default values should be usable.

Sugested values should be usable.

Wording should be consistent (elsewhere in the application also)

### Project file & Debug log uploads

N/A

### Checklist of files to include

N/A

### Anything else?

Thanks

**Comment by Yorshka-Vermilion** [comment]
i've encountered this one in BS too. In BS you would need to replace "." with "," on numbers. Don't know if this will work in Orca too, but its basiclly the same system so if you are in hurry it is worth give it a try.

**Comment by frankieorabona** [comment]
Even inserting the comma always gives the same problem:

![image](https://github.com/SoftFever/OrcaSlicer/assets/32438819/7523b081-0a98-4f03-a9b3-26df87654a41)

**Comment by frankieorabona** [comment]
I have the same problem. 
Even inserting the comma always gives the same problem:

![image](https://github.com/SoftFever/OrcaSlicer/assets/32438819/93295bfd-baf6-4766-89d4-1945888f9669)


By the way, in Bambu Studio with the same values it works regularly

**Comment by patridge** [comment]
Have this issue on OrcaSlicer 2.0.0. Didn't have any luck swapping the decimal separator to commas, though. I don't know enough about the test to risk trying other values, but everything from the error-suggested to the default values presents an error.

**Comment by nmcandrews** [comment]
I am seeing this issue for the first time today as well. 
Same exact parameters for both instances.
Starts fine in Bambu Studio, but gives an error in Orca Slicer. 
Orca Slicer will actually CRASH to desktop, when trying to run a pattern as the calibration shape, rather than a line, while citing an error of invalid operation. But Bambu Studio is more than happy to do it.

**Comment by Jinro87** [comment]
Exactly the same happens on my Orca Slicer too. Default values show this invalid values error. 
It seems like it accepts "corrected" values but the whole Slicer crashes right after.
This happened across few older versions of the Slicer already.
I think the last version where flow dynamics calibration worked for me was 1.8.x.x.
