### ISSUE TITLE
Error when trying to compile BambuStudio-SoftFever on M1 Mac

### ISSUE THREAD

**Issue by esc247** [SoftFever/OrcaSlicer#434]
**Describe the bug**
I have been trying to follow the build guide here: https://github.com/bambulab/BambuStudio/wiki/Mac-Compile-Guide

When I get to the last stage: `building it use cmake` I get the following error.

```
CMake Error at CMakeLists.txt:419 (find_package):
  Could not find a package configuration file provided by "CURL" with any of
  the following names:

    CURLConfig.cmake
    curl-config.cmake

  Add the installation prefix of "CURL" to CMAKE_PREFIX_PATH or set
  "CURL_DIR" to a directory containing one of the above files.  If "CURL"
  provides a separate development package or SDK, be sure it has been
  installed.
```

**To Reproduce**
Follow the guide (https://github.com/bambulab/BambuStudio/wiki/Mac-Compile-Guide) on an M1 Mac, OS version 13.2.1. When you get to the final step of 'building it use cmake' you will face this error.

**Expected behavior**
App should compile, and I should be able to use it.

**Screenshots**
![image](https://user-images.githubusercontent.com/2703225/223104886-51f8bc63-c46d-485f-bce2-87d8c1b2ee97.png)

**Printer model**
Bambulab X1C

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Version 13.2.1

**Comment by GP3D84** [comment]
Missing curl?
install it with homebrew and try again

**Comment by AidanWenzel** [comment]
@esc247 I had these issues yesterday - I'd actually just ignore that guide completely. I finally had success just using the `build_release_macos.sh` script running with `-d` first and `-s` second. Had endless issues with the guide's commands - both with CURL and TBB and others. 

Seems like Homebrew doesn't configure the `<package>-config.cmake` files on Ventura, and something in the guide's commands isn't setting things up correctly.

**Comment by SoftFever** [comment]
Let's discuss compiling issues in `[Discussions](https://github.com/SoftFever/OrcaSlicer/discussions)` 
#251
