### ISSUE TITLE
Add an option to disable the "Device" tab.

### ISSUE THREAD

**Issue by Ataraxia-Mechanica** [SoftFever/OrcaSlicer#4342]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

The device tab in windows runs webview2 which is laggy and consumes a significant amount of CPU cycles even when in background. This results in basically the entire computer being unusable with 4+ Orca slicers open.

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

An option to disable the tab would be good. Or pause the tab while the page is in background.

**Comment by Maximus-CZ** [comment]
Can not replicate, here the OrcaSlcier process consumes less than 1.5% CPU when on device tab. regardless if camera feed is running or not. When on other tabs the CPU usage falls to below 0.8%.
Windows 10, 7800x3d.

**Comment by Ataraxia-Mechanica** [comment]
Could it have something to do with high resolution? I have a 4k monitor and each instance takes 20% processing power or so.

**Comment by Maximus-CZ** [comment]
I too am running at 4k, altho at 1.25x scaling

**Comment by Ataraxia-Mechanica** [comment]
Guess this has something to do with my computer. Guess sending webview2 to the shadow realm via windows firewall it is then.

**Comment by Ataraxia-Mechanica** [comment]
After blocking internet access Orca slicer only consumes ~0.2% CPU in background, despite all the webview2.exe running, so it's caused by the combination of fluidd + webview. Weird.
