### ISSUE TITLE
First Layer Travel Acceleration

### ISSUE THREAD

**Issue by Z18Aplha** [SoftFever/OrcaSlicer#4346]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Normally, a low acceleration value for the first layer is necessary for good bed adhesion. But unfortunately the acceleration value also applies for the travel movements, which is not optimal. This supports stringing and oozing.

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

It would be nice to add a "first layer travel acceleration" parameter like the "first layer travel speed" which already exists.
I opened this issue again, because #2797 was closed some weeks ago but i think there is really a need of this setting.

**Comment by vgdh** [comment]
It will be very useful feature! 
This is so annoying I am almost at the point of writing my own post script for changing acceleration at first layer.

**Comment by vgdh** [comment]
I've wrote a postscript for fixing this issue.
It fixes this annoying behavior for the first layer.
https://github.com/vgdh/OrcaSlicer-first-layer-travel-acceleration-fix

**Comment by vgdh** [comment]
I've updated the acceleration fix script, now it works very fast.

**Comment by slackista** [comment]
+1

**Comment by MxBrnr** [comment]
Implemented in #11674.
