### ISSUE TITLE
"Sphere" isn't visible in paint or paint supports 

### ISSUE THREAD

**Issue by ThinkBigPrintHuge** [SoftFever/OrcaSlicer#4347]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

v2.0.0

### Operating System (OS)

Windows

### OS Version

Windows 11 Home

### Additional system information

CPU: i9-12900h
GPU: Nvidia 3070Ti (Laptop)
Ram: 32g LPDDR5

### Printer

n/a

### How to reproduce

1. Go to Paint/Support paint
2. Select "Sphere" tool
3. Hover over part

### Actual results

![Screenshot 2024-03-05 081114](https://github.com/SoftFever/OrcaSlicer/assets/148880524/8de72f6b-3417-4636-b582-bff1558b0d52)
<img width="613" alt="Screenshot 2024-03-05 081120" src="https://github.com/SoftFever/OrcaSlicer/assets/148880524/cefc2e2f-54bd-4372-ba5e-a397bd489d76">
![Screenshot 2024-03-05 081132](https://github.com/SoftFever/OrcaSlicer/assets/148880524/94a2f595-9bed-4c10-8080-8fa5562d1a29)
![Screenshot 2024-03-05 081137](https://github.com/SoftFever/OrcaSlicer/assets/148880524/8b4c6311-ab7d-49ea-8c6c-eb808d2457d0)

### Expected results

Sphere tool should be visible (as in previous versions).

### Project file & Debug log uploads

No need, this happens on all models since transitioning to V2.0.0 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Anything else?

I searched for related issues and found a report about Sphere not showing up during Seam Painting, but no reference to painting and support painting. It's important to note I switched from 1.8.1 to 2.0.0, so I am unsure if this also happening in V1.9.x.

**Comment by cobyn** [comment]
Can confirm this started happening on V1.9

**Comment by foreachthing** [comment]
Still an issue in 2.0b.
