### ISSUE TITLE
Assuming all klipper configurations use 'PRINT_START' and other macros causes many to run into issues!

### ISSUE THREAD

**Issue by phuzzyday** [SoftFever/OrcaSlicer#4360]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

1.9.1

### Operating System (OS)

Windows

### OS Version

Win11

### Additional system information

This stuff isn't relevant here.

### Printer

Klipper Generic

### How to reproduce

Set up a klipper printer following the standard klipper instructions.
Install Orca, set up as Generic Klipper printer, and slice something.
Send it to printer.

### Actual results

Errors fly! Like;
6:35 PM
Must home axis first: 0.000 0.000 0.400 [-0.800]
6:35 PM
Unknown command:"PRINT_START"

Of course, these macros are not in the printer.cfg, as they are not part of the standard setup instructions set. Unless I am mistaken! There IS a file at https://github.com/Klipper3d/klipper/blob/master/config/sample-macros.cfg whick seems to be a good cluse as to what Orca is assuming, but I don't think klippers directions aim users that way unless they are looking at specific additional desired features.

### Expected results

The slicer should either provide standard start G-Code / end G-Code to modify, or, given there are so many klipper possibilities, perhaps some other support or warnings should be given?
But yes, I would expect some attempt at a decent print!

### Project file & Debug log uploads

ats 3938.7: gcodein=0  mcu: mcu_awake=0.003 mcu_task_avg=0.000014 mcu_task_stddev=0.000027 bytes_write=53737 bytes_read=478242 bytes_retransmit=9 bytes_invalid=0 send_seq=6121 receive_seq=6121 retransmit_seq=2 srtt=0.000 rttvar=0.000 rto=0.025 ready_bytes=0 upcoming_bytes=0 freq=71997436 sd_pos=19758 heater_bed: target=80 temp=80.4 pwm=0.461 sysload=0.51 cputime=99.190 memavail=6499184 print_time=54802.923 buffer_time=0.182 print_stall=0 extruder: target=255 temp=256.2 pwm=0.234
Stats 3939.7: gcodein=0  mcu: mcu_awake=0.003 mcu_task_avg=0.000014 mcu_task_stddev=0.000027 bytes_write=53832 bytes_read=478385 bytes_retransmit=9 bytes_invalid=0 send_seq=6127 receive_seq=6127 retransmit_seq=2 srtt=0.000 rttvar=0.000 rto=0.025 ready_bytes=0 upcoming_bytes=0 freq=71997435 sd_pos=19758 heater_bed: target=80 temp=80.4 pwm=0.270 sysload=0.51 cputime=99.229 memavail=6502952 print_time=54803.925 buffer_time=0.183 print_stall=0 extruder: target=255 temp=255.8 pwm=0.381
Unknown command:"PRINT_START"
toolhead: max_velocity: 200.000000
max_accel: 500.000000
max_accel_to_decel: 250.000000
square_corner_velocity: 5.000000
Must home axis first: 0.000 0.000 0.400 [-0.800]
Exiting SD card print (position 0)
Stats 3940.7: gcodein=0  mcu: mcu_awake=0.003 mcu_task_avg=0.000013 mcu_task_stddev=0.000021 bytes_write=53900 bytes_read=478537 bytes_retransmit=9 bytes_invalid=0 send_seq=6132 receive_seq=6132 retransmit_seq=2 srtt=0.000 rttvar=0.000 rto=0.025 ready_bytes=0 upcoming_bytes=0 freq=71997445  heater_bed: target=0 temp=80.4 pwm=0.432 sysload=0.51 cputime=99.288 memavail=6500652 print_time=54804.929 buffer_time=0.186 print_stall=0 extruder: target=0 temp=255.7 pwm=0.373
Stats 3941.7: gcodein=0  mcu: mcu_

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by igiannakas** [comment]
In general for Klipper it is good practice to de-couple the print start/print end functions from the slicer to the printer. Hence why most Klipper setups use a print start macro. You have more control over the print start procedure (such as waiting for the chamber to heat up, attach/detach your Klicky probe if you have it, pre-heat nozzle to a specific temp if using Voron tap or similar etc).

Also due to the variety of different hardware and set up it's difficult to set up a "safe" print start Gcode in the slicer without knowing exactly what the user has done to the machine. Hence the current approach.
