### ISSUE TITLE
fails to detect bridge when using "detect overhangs walls" setting.

### ISSUE THREAD

**Issue by KoenVanduffel** [SoftFever/OrcaSlicer#4365]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

1.9.1

### Operating System (OS)

Windows

### OS Version

11

### Additional system information

CPU: AMD Ryzen 5900, 32 GB ram, Nvidia 1300 2GB

### Printer

RatRig 500 IDEX

### How to reproduce

When using the "detect overhang walls" setting bridges that have a support on one side smaller than the wall thickness are not sliced as bridges. Switching "detect overhang walls" off generates bridges almost perfectly. The remining issue is that when one of the legs under the bridge is slimmer than the wall thickness the wall will be printed overhanging instead of making the wall slimmer and anchoring the bridge properly (this is an edge case though).

### Actual results

![image](https://github.com/SoftFever/OrcaSlicer/assets/13643644/d5778381-7efa-4f0c-a47e-6d9c0e243be0)
The 2 left and the right one have legs slimmer than the wall thickness and get a rectangular pattern.

### Expected results

![image](https://github.com/SoftFever/OrcaSlicer/assets/13643644/6addc66f-f10f-4e35-9a11-f2886943732e)
Switching "detect overhang walls" off corrects the problem.
![image](https://github.com/SoftFever/OrcaSlicer/assets/13643644/93794e77-590c-4f8a-bf02-35c160ea10c8)
There is a residual problem though: at the one with the slimmest legs (1mm) the innermost wall overlaps with the bridge so the bridge will not be properly anchored (this is an edge case though).

### Project file & Debug log uploads

[log.zip](https://github.com/SoftFever/OrcaSlicer/files/14529472/log.zip)
[bridges with varying leg thickness orca.zip](https://github.com/SoftFever/OrcaSlicer/files/14529473/bridges.with.varying.leg.thickness.orca.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Anything else?

This same bug also happens in PrusaSlicer

**Comment by igiannakas** [comment]
Turn off extra perimeters on overhangs.
