### ISSUE TITLE
Signing into OrcaSlicer causes OrcaSlicer to crash upon startup

### ISSUE THREAD

**Issue by willjsaint** [SoftFever/OrcaSlicer#4374]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

1.9.1

### Operating System (OS)

Linux

### OS Version

Fedora 39 KDE

### Additional system information

R7 4700U, 8GB LPDDR4, iGPU

### Printer

Neptune 4 Plus

### How to reproduce

Download OrcaSlicer on fedora 39 KDE
Login to OrcaSlicer using Bamboo Labs account

### Actual results

OrcaSlicer will start and then instantly lock up then crash a few seconds later

### Expected results

OrcaSlicer should launch normally

### Project file & Debug log uploads

[debug_Fri_Mar_08_00_23_05_22750.log.0.zip](https://github.com/SoftFever/OrcaSlicer/files/14533602/debug_Fri_Mar_08_00_23_05_22750.log.0.zip)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by vprasad1973** [comment]
FYI to any of the Fedora or other distro folks having difficulty with launching Orca app image, go ahead and try last night's Jan 22 v2.0.0 dev image from the nightly builds-- WORKS FANTASTIC!!!
