### ISSUE TITLE
Libwebkit2 is missing from the Linux AppImage

### ISSUE THREAD

**Issue by tigert** [SoftFever/OrcaSlicer#4377]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

1.9.1

### Operating System (OS)

Linux

### OS Version

Fedora 39 silverblue

### Printer

None yet

### How to reproduce

1. Run appimage
2. Get error

### Actual results

./OrcaSlicer_Linux_V1.9.1.AppImage 
/tmp/.mount_OrcaSlKbla0c/bin/orca-slicer: error while loading shared libraries: libwebkit2gtk-4.0.so.37: cannot open shared object file: No such file or directory

### Expected results

I would guess the appimage packages all required libraries along with the application binary.

I guess the lib version numbering is different, I do have libwebkit2gtk-4.1.so.0.12.8 on my system, but it expects libwebkit2gtk-4.0.so.37. And the point of the AppImage is to not rely on system libraries even if they would exist, but package the correct versions of dependencies with the binary, I guess.

### Project file & Debug log uploads

not relevant as the app does not even run.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by vprasad1973** [comment]
FYI to any of the Fedora or other distro folks having difficulty with launching Orca app image, go ahead and try last night's Jan 22 v2.0.0 dev image from the nightly builds-- WORKS FANTASTIC!!!

**Comment by xPakrikx** [comment]
Same problem on my Fedora 39 even on v2.0.0 beta. I tried cleanup .local and .config but its still same problem. Just blank setup wizard.  No problem with Prusa slicer app image.

**Comment by VorpalBlade** [comment]
Tried the OrcaSlicer_Linux_V2.0.0-beta.AppImage on Arch Linux, fails to start with: 

```
/tmp/.mount_OrcaSlTwTZnd/bin/orca-slicer: error while loading shared libraries: libwebkit2gtk-4.0.so.37: cannot open shared object file: No such file or directory
```

However you can install webkit2gtk (`pacman -S webkit2gtk`) and it then works. Still that should be bundled in the AppImage as there can be many different incompatible versions of that library I believe.

**Comment by karolbe** [comment]
I am using Fedora 39, and Orca did not work for me, however with this settting:

**Comment by ffries** [comment]
All these issue are related :
https://github.com/SoftFever/OrcaSlicer/issues?q=libwebkit2gtk-4.0.so.37

**Comment by kwagnitz** [comment]
error while loading shared libraries: libwebkit2gtk-4.0.so.37
OrcaSlicer_Linux_V2.1.1.AppImage OR OrcaSlicer_Linux_V2.1.0.AppImage
Ubuntu 24.04.

Worked with Ubuntu 23.10.
