### ISSUE TITLE
PA Pattern does get removed after deleting from plate

### ISSUE THREAD

**Issue by poppinfresh69** [SoftFever/OrcaSlicer#4385]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

1.9.1 and 2.0.0

### Operating System (OS)

Windows

### OS Version

10

### Printer

probably all

### How to reproduce

1. Start Orca
2. Click on Calibration and select Pressure Advance
3. Select PA pattern and customize if needed
4. Slice PA pattern test (print if desired doesn't affect issue)
5. Delete PA pattern test from plate
6. Import any SLT model and slice

### Actual results

Notice PA pattern test still on plate to print with the model in some cases merged with the model. Using select all does not show that the PA pattern test even exists on the plate. Only visible after slice. Does not appear in the object list either. Only way to remove is close project and start a new one.
![image](https://github.com/SoftFever/OrcaSlicer/assets/142692274/727f69fb-1d18-47e2-9b36-a8873d9643d6)
![image](https://github.com/SoftFever/OrcaSlicer/assets/142692274/709f52af-7593-4fc5-a047-ab81868c797c)

### Expected results

After deleting PA pattern test from plate it should no longer be printing.

### Project file & Debug log uploads

[vent.zip](https://github.com/SoftFever/OrcaSlicer/files/14541990/vent.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by bkaczmarczyk** [comment]
It is worth noting that adding calibration to a project changes print settings like line width. If you delete the model these settings remain.
