### ISSUE TITLE
switching printers resets global process settings

### ISSUE THREAD

**Issue by scotta316** [SoftFever/OrcaSlicer#4388]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

1.9.1

### Operating System (OS)

Windows

### OS Version

11

### Printer

Bambu Lab P1S

### How to reproduce

- Download a .3mf file, e.g. from Thangs.com, that has print process settings embedded.
- The printer saved in the .3mf file is not the same model as my printer.
- Switch the active printer to my printer.
- All embedded print process settings revert to the defaults. (Per object settings appear to be retained.)
- In Bambu Studio, switching printers does not affect the global process settings, so I believe this is a bug.

### Actual results

All print process settings revert to the defaults for the selected process

### Expected results

The selected printer should change to my choice, and the process settings should not change

### Project file & Debug log uploads

[Lamp Shade before and after.zip](https://github.com/SoftFever/OrcaSlicer/files/14542887/Lamp.Shade.before.and.after.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by jb510** [comment]
Seems like this is still a bug.  When loading a .3mf in Orca 2.1.1 in which objects have individual overrides (for example tree supports on 2 out of 6 objects) and then switching printers, all those individual object settings are lost.  

Video demostrating 
https://share.cleanshot.com/bxdJ5NtK
This uses the 3mf file from
https://www.printables.com/model/835725-63mm-2-12-truncated-ball-valve-type-non-clog-blast/files
