### ISSUE TITLE
Add ASA and TPU profiles

### ISSUE THREAD

**Issue by whyb33** [SoftFever/OrcaSlicer#4397]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Can't use Orca Slicer because it will not allow me to add TPU and ASA filament profiles for my Elegoo Neptune 4. They are present and work great in the default Cura profile

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

Add default/preset ASA and TPU filaments as an option on all printers.

### Describe alternatives you've considered

Use Cura instead?

**Comment by rojoricardo** [comment]
I guess there is no solution to this?

**Comment by peperonikiller** [comment]
[https://i.imgur.com/Nk47UMW.png](url) Can confirm, there is no ASA option under material type. :(
