### ISSUE TITLE
Custom filaments vanish when decreasing nozzle size from .4 to .2

### ISSUE THREAD

**Issue by WimVDK** [SoftFever/OrcaSlicer#4406]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

1.9.1

### Operating System (OS)

Windows

### OS Version

11

### Printer

Bambulab X1C

### How to reproduce

1. Create custom filament with nozzle type set to .4
2. Switch to .2 nozzle

### Actual results

Custom filament disappears

### Expected results

Custom filament should remain selectable. Just because a nozzle size changes, doesn't mean the filament suddenly is incompatible with the nozzle

### Project file & Debug log uploads

no logs for this one

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Anything else?

At .4 nozzle some of my custom filaments
![image](https://github.com/SoftFever/OrcaSlicer/assets/14872315/f46dc310-4001-4ad3-8b22-321109adbc78)

at .2 nozzle, all of my custom ones disappear

![image](https://github.com/SoftFever/OrcaSlicer/assets/14872315/30193af4-d739-4c7e-93d0-5ba4d46be2f2)

**Comment by jsladerman** [comment]
Filament profiles are made specific to the Printer/Nozzle combo. Did you include 0.2 as an option (example below) when making the filament's profile? If not, you can also add a new nozzle option to the existing one you made (second pic)

![Screenshot 2024-03-10 at 5 50 54 PM](https://github.com/SoftFever/OrcaSlicer/assets/28611154/7b0b75ab-9101-4569-a3c1-8f66f3f23b3f)

![Screenshot 2024-03-10 at 5 53 50 PM](https://github.com/SoftFever/OrcaSlicer/assets/28611154/2cce19e3-7b86-4cd3-a828-db9c929e1401)

Hope this helps!

**Comment by WimVDK** [comment]
I made the first custom based off of a modified generic. Then modifed names and colors when needed. I never saw either of those screenshots.

**Comment by jsladerman** [comment]
Ah makes sense. Yeah the system's a little fragmented. Best way to do it is to make a custom filament (you can still base it off an existing preset to preserve your settings) for the filaments/profiles you like to use and then it'll be easy to transfer between nozzles and printers

**Comment by WimVDK** [comment]
Tried that, won't allow me to set my .4 profile for .2. I can select it for .4, .6 and .8, but i can only pick "bambu ...." for some. I just wanna easily swap them to .2 compatible. There has to be an easier way than to redo 2 dozen profiles

**Comment by HAndreasH** [comment]
I strggled with the same thing as I started using Orca.
Coming from Cura it is very strange how the combination of settings for machine-filament-process works. But it seems to make sense.
For me it was not relevant to have different filament settings for 0.4 and 0.6 nozzles, so I ended up with editing the .json files for my filaments and setting "compatible_printers": []

**Comment by WimVDK** [comment]
Can you post a screenshot of what and where you edited that

**Comment by HAndreasH** [comment]
The way [jsladerman](https://github.com/jsladerman) described should actually work fine 
Please note that changing the files manually is actually not the best way to go!

for example a new created custom filament for a specific printer with 0.6 nozzle looks like this:

![1](https://github.com/SoftFever/OrcaSlicer/assets/98119968/685fe7a8-5778-415e-a2af-0515f57e6692)

if you have more printers selected ( 0.4 and 0.6 nozzle)

![2](https://github.com/SoftFever/OrcaSlicer/assets/98119968/37ed9d75-4954-4a76-ad2c-0bd3e51dd076)

this is how I did it, so the filament is visible to all printers:

![3](https://github.com/SoftFever/OrcaSlicer/assets/98119968/82541858-c5dd-4503-a957-808abab96c3a)

**Comment by WimVDK** [comment]
Reactivating this
