### ISSUE TITLE
Orca slicer doesn't set acc in gcode 

### ISSUE THREAD

**Issue by B7zvrvysaj** [SoftFever/OrcaSlicer#4419]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

1.9.1

### Operating System (OS)

Windows

### OS Version

Windows 10

### Additional system information

CPU: Ryzen 5 2600X , Memory: 16gb ddr4 2600hz , GPU: Nvidea rtx 3050

### Printer

Ender 3 S1 

### How to reproduce

set accel

???

profit!
![изображение](https://github.com/SoftFever/OrcaSlicer/assets/29804376/01a90bdf-054e-4b2e-8856-222a486c159b)
![изображение](https://github.com/SoftFever/OrcaSlicer/assets/29804376/b0acf22a-3519-4a1e-ae06-35724fbee560)

### Actual results

nothing 

### Expected results

see the acc changes 

### Project file & Debug log uploads

[gre.zip](https://github.com/SoftFever/OrcaSlicer/files/14562452/gre.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by igiannakas** [comment]
Check your printer settings under motion ability. Is it set to over 500mm/sec acceleration?

**Comment by Normal1no** [comment]
> Check your printer settings under motion ability. Is it set to over 500mm/sec acceleration?
![shaper_calibrate_y](https://github.com/SoftFever/OrcaSlicer/assets/29804376/3009561d-35d6-412e-9e5e-fbb15d3d1177)
![shaper_calibrate_x](https://github.com/SoftFever/OrcaSlicer/assets/29804376/2e8a9a88-08a9-4d4f-aacc-bfe31012fd9a)

velocity is normal, accel to. but this isn't applicable to my issue

**Comment by igiannakas** [comment]
No I mean in orca - in the edit printer settings…

**Comment by Normal1no** [comment]
> No I mean in orca - in the edit printer settings…

![изображение](https://github.com/SoftFever/OrcaSlicer/assets/29804376/a9655138-b414-4545-a47e-b6d4de19635f)
yea

**Comment by Normal1no** [comment]
![изображение](https://github.com/SoftFever/OrcaSlicer/assets/29804376/5ae8686b-e6d1-4239-8b35-a2c7c2823dfa)
I found a problem, but idk how to solve it

**Comment by igiannakas** [comment]
Set your max accel for extruding and retracting to 7k and it should work

![image](https://github.com/SoftFever/OrcaSlicer/assets/59056762/79a51fad-1c77-4556-949f-fbe022c777b0)

In the latest version (2.0 beta) you'll get appropriate warnings like the below:
![image](https://github.com/SoftFever/OrcaSlicer/assets/59056762/c54233be-b4ce-4b96-9250-f6f9f013b923)

**Comment by henrivdr** [comment]
@igiannakas 
The new warning does not make sense. Why does it compare the Extrusion Acceleration with the other acceleration(s)?

Bumping it to 7000 is just a workaround, right?  Defeating the purpose of that limit.
Won't it cause issues with the extrusion?

**Comment by igiannakas** [comment]
The label should say maximum acceleration while extruding

**Comment by henrivdr** [comment]
Ahh, that makes sense.

**Comment by henrivdr** [comment]
Ahh, 
I also looked at the source and it emits M204 for machine_max_acceleration_extruding.
When I looked at the two values _extruding and _retracting, I wrongly assumed they were for the extruder **_motor_** itself.

The gcode docs explains it properly.
https://marlinfw.org/docs/gcode/M204.html
P<accel>]	
Printing acceleration. Used for moves that **_include_** extrusion (i.e., which employ the current tool).
[R<accel>]	
Retract acceleration. Used for extruder retract / recover moves.
