### ISSUE TITLE
Creality Ender 3 V3 SE/KE Incorrect start of G-Code

### ISSUE THREAD

**Issue by aschmitt1909** [SoftFever/OrcaSlicer#4420]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Creality Ender 3 V3 SE and V3 KE are using a CR-Touch sensor by default and create a mesh of the bed by themself.
By default, Marlin turns off using the bed mesh in the G28 command, so an additional M420 S1 command is needed at the start of the g-code, to re-enable it.
In the default profile for these printers, the M420 S1 command is missing.

### Which printers will be beneficial to this feature?

Marlin

### Describe the solution you'd like

After "_G28; Home_", a "_M420 S1; Enable mesh leveling_" command is needed in the default profile for these printers.

**Comment by cochcoder** [comment]
Does [this](https://github.com/cochcoder/OrcaSlicer/actions/runs/8455259221) fix your issue with the Ender-3 V3 KE?
