### ISSUE TITLE
Disabling "Ensure Vertical Shell Thickness" breaks "Don't Filter Out Small Internal Bridges"

### ISSUE THREAD

**Issue by mf7120** [SoftFever/OrcaSlicer#4435]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

Windows

### OS Version

Windows 11

### Printer

Ender 3 S1

### How to reproduce

Disable "Ensure Vertical Shell Thickness" and use "Don't Filter Out Small Internal Bridges -> Limited filtering"

### Actual results

Just by disabling "Ensure Vertical Shell Thickness" no internal bridges will be created to support small top surfaces and they drop down giving bad results. First 2 pictures with EVT OFF. The other 2 with EVT ON -> ALL
![EVTOFF](https://github.com/SoftFever/OrcaSlicer/assets/153242792/226688ce-91e0-429d-bec5-77125d349118)
![EVTOFF2](https://github.com/SoftFever/OrcaSlicer/assets/153242792/35bab7da-a7bf-4eef-a6d7-e7595d22f576)
![EVTONALL2](https://github.com/SoftFever/OrcaSlicer/assets/153242792/7ef1375b-f517-4b60-881f-a969ecb88878)
![EVTONALL](https://github.com/SoftFever/OrcaSlicer/assets/153242792/829a7c58-0877-430b-9670-92af77e5e714)

### Expected results

Be able to create internal bridges regardless of ensure vertical thickness turned off or on..

### Project file & Debug log uploads

See layers from 3.36mm to 5.00mm
[EVTON-OFFISSUE.zip](https://github.com/SoftFever/OrcaSlicer/files/14576170/EVTON-OFFISSUE.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by igiannakas** [comment]
I still see the internal bridges generated correctly when critical only is selected on ensure vertical shell thickness.

![image](https://github.com/SoftFever/OrcaSlicer/assets/59056762/67464ba4-33c7-4cd4-82ee-50f0f7e43d8c)

What you're seeing is less solid infill needing support, hence less internal bridging happening.

Dont use "None" on ensure vertical shell thickness, this disables it completely and for your model it won't work.

**Comment by mf7120** [comment]
@igiannakas that's the thing, as mentioned internal bridges should be still created even if EVT is set to "None". Prusa Slicer is able to do it. Also for me personally EVT just adds unnecessary material and increases printing time it even handles better with "All" instead of "Critical Only".

Also it is kind of weird now that I see it that the amount of top layers are not being generated with EVT set to "None"

**Comment by igiannakas** [comment]
Prusa slicer doesn’t have the evt option. None should not be used for regular printing…

**Comment by mf7120** [comment]
@igiannakas exactly. They got rid of that function many versions ago since it didn't serve any purpose and as mentioned it just added unnecessary material and time to any print.
