### ISSUE TITLE
Mispell 

### ISSUE THREAD

**Issue by thefluxplux** [SoftFever/OrcaSlicer#4441]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

 Under Quality tab --> Wall and surfaces --> Wall loop direction --> Description has a misspell :D

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

 Under Quality tab --> Wall and surfaces --> Wall loop direction --> Description has a misspell

**Comment by cochcoder** [comment]
What is the missed spelt word? Do you mean Walls printing order?

**Comment by cochcoder** [comment]
Found it
