### ISSUE TITLE
Change Elegoo Neptune 4 thumbnail settings

### ISSUE THREAD

**Issue by mtc1122** [SoftFever/OrcaSlicer#4446]
### Is there an existing issue for this feature request?

- [x] I have searched the existing issues

### Is your feature request related to a problem?

I believe most Elegoo Neptune 4 users who want thumbnails (as Orca doesn't handle these) are using the thumbnail script at https://github.com/Molodos/ElegooNeptuneThumbnails-Prusa. The default setting for Colpic does not work correctly, and the resolutions are incorrect.

### Which printers will be beneficial to this feature?

Klipper

### Describe the solution you'd like

If thumbnails settings changed to PNG with resolutions 300x300, 600x600, it will at least work with the script. (Of course, it would be even better if this functionality was added to Orca Slicer.) It doesn't work with the default settings otherwise so I wouldn't expect it to break anything for other users.

**Comment by CLNilix** [comment]
it seems the current version of orca slicer did not include the additional information (e.g. print duration, used filament weight, used filament length and model height) in the gcode file.
At least in my case, all these additional information are missing:
![ThumbnailMod_missing-infos](https://github.com/SoftFever/OrcaSlicer/assets/83114330/e4adf09a-e8f1-4da3-8f94-e6b61e75a331)
