### ISSUE TITLE
Counterbore misspelled

### ISSUE THREAD

**Issue by mtc1122** [SoftFever/OrcaSlicer#4447]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

Windows

### OS Version

Windows 11

### Printer

Elegoo Neptune 4 Plus

### How to reproduce

1.  Go to "Quality"
2. Scroll down to "Bridge counterbole holes"
3. Notice that "counterbore" is misspelled as "counterbole" (including in one spot in the tooltip).

### Actual results

Notice that "counterbore" is misspelled as "counterbole" (including in one spot in the tooltip).

### Expected results

counterbore

### Project file & Debug log uploads

N/A

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Anything else?

![Screenshot 2024-03-12 205216](https://github.com/SoftFever/OrcaSlicer/assets/17415693/83ee2aac-116b-42a8-a604-efc8637e1738)

**Comment by cochcoder** [comment]
This issue should now be fixed

**Comment by cochcoder** [comment]
Please close this issue if Counterbore isn't misspelled anywhere else
