### ISSUE TITLE
adaptive bed meshing not working on K1max

### ISSUE THREAD

**Issue by tkunchick** [SoftFever/OrcaSlicer#4449]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

OrcaSlicer V2.0.0 Beta Release

### Operating System (OS)

macOS

### OS Version

14.3.1

### Additional system information

M1 Pro

### Printer

k1max

### How to reproduce

add gocode before or after START_PRINT EXTRUDER_TEMP=[nozzle_temperature_initial_layer] BED_TEMP=[bed_temperature_initial_layer_single]

 

### Actual results

Put

; Always pass `ADAPTIVE_MARGIN=0` because Orca has already handled `adaptive_bed_mesh_margin` internally
BED_MESH_CALIBRATE mesh_min={adaptive_bed_mesh_min[0]},{adaptive_bed_mesh_min[1]} mesh_max={adaptive_bed_mesh_max[0]},{adaptive_bed_mesh_max[1]} ALGORITHM=[bed_mesh_algo] PROBE_COUNT={bed_mesh_probe_count[0]},{bed_mesh_probe_count[1]} ADAPTIVE=1 ADAPTIVE_MARGIN=0

before or after 
START_PRINT EXTRUDER_TEMP=[nozzle_temperature_initial_layer] BED_TEMP=[bed_temperature_initial_layer_single]

does not heat bed or hotend before probing. 

errors out when trying to extrude prime line with low nozzle temp

### Expected results

heat bed, do adaptive bed mesh, print

### Project file & Debug log uploads

none at this time

### Checklist of files to include

- [X] Log file
- [X] Project file

### Anything else?

none

**Comment by Cblaze401** [comment]
Its on a KE but this is what I did to get bed to temp before probe

M140 S[bed_temperature_initial_layer_single] ;Set final bed temp
G28 ;Home
M190 S[bed_temperature_initial_layer_single] ;Wait for bed temp to stabilize

; Always pass `ADAPTIVE_MARGIN=0` because Orca has already handled `adaptive_bed_mesh_margin` internally
BED_MESH_CALIBRATE mesh_min={adaptive_bed_mesh_min[0]},{adaptive_bed_mesh_min[1]} mesh_max={adaptive_bed_mesh_max[0]},{adaptive_bed_mesh_max[1]} ALGORITHM=[bed_mesh_algo] PROBE_COUNT={bed_mesh_probe_count[0]},{bed_mesh_probe_count[1]} ADAPTIVE=1 ADAPTIVE_MARGIN=0 

Then 

M104 S[nozzle_temperature_initial_layer] ;Set final nozzle temp  
G1 X-2.0 Y20 Z0.28 F5000.0 ;Move to start position 
M109 S[nozzle_temperature_initial_layer] ;Wait for nozzle temp to stabilize  
G1 X-2.0 Y145.0 Z0.28 F1500.0 E15 ;Draw the first line

**Comment by cochcoder** [comment]
Is this issue on the K1 Max or the K1 KE? Which machine do you personally own so you can test this?

**Comment by cochcoder** [comment]
> Its on a KE but this is what I did to get bed to temp before probe
> 
> M140 S[bed_temperature_initial_layer_single] ;Set final bed temp G28 ;Home M190 S[bed_temperature_initial_layer_single] ;Wait for bed temp to stabilize
> 
> ; Always pass `ADAPTIVE_MARGIN=0` because Orca has already handled `adaptive_bed_mesh_margin` internally BED_MESH_CALIBRATE mesh_min={adaptive_bed_mesh_min[0]},{adaptive_bed_mesh_min[1]} mesh_max={adaptive_bed_mesh_max[0]},{adaptive_bed_mesh_max[1]} ALGORITHM=[bed_mesh_algo] PROBE_COUNT={bed_mesh_probe_count[0]},{bed_mesh_probe_count[1]} ADAPTIVE=1 ADAPTIVE_MARGIN=0
> 
> Then
> 
> M104 S[nozzle_temperature_initial_layer] ;Set final nozzle temp G1 X-2.0 Y20 Z0.28 F5000.0 ;Move to start position M109 S[nozzle_temperature_initial_layer] ;Wait for nozzle temp to stabilize G1 X-2.0 Y145.0 Z0.28 F1500.0 E15 ;Draw the first line

Are you using the Ender-3 V3 KE? If so, does [this](https://github.com/cochcoder/OrcaSlicer/actions/runs/8455259221) fix your issue?

**Comment by cochcoder** [comment]
@tkunchick Does [this](https://github.com/cochcoder/OrcaSlicer/actions/runs/8455846636) fix your issue?

**Comment by tkunchick** [comment]
> @tkunchick Does [this](https://github.com/cochcoder/OrcaSlicer/actions/runs/8455846636) fix your issue?
@cochcoder
I just seen this, will try it out today or tomorrow.

**Comment by cochcoder** [comment]
Just want to mention that the file I sent to Cblaze401 is different than the one I sent you

**Comment by tkunchick** [comment]
> Just want to mention that the file I sent to Cblaze401 is different than the one I sent you
@cochcoder 
I Have a K1Max

wow, I totally missed that file link.. I was just looking at the start machine code trying to figure out what was different.


I am assuming I just need to add the adaptive string before the START_PRINT. This is my machine start gcode.

```
{if curr_bed_type=="Textured PEI Plate"}
  SET_GCODE_OFFSET Z=0.270
{else}
  SET_GCODE_OFFSET Z=0.0
{endif}

; Always pass ADAPTIVE_MARGIN=0 because Orca has already handled adaptive_bed_mesh_margin internally
BED_MESH_CALIBRATE mesh_min={adaptive_bed_mesh_min[0]},{adaptive_bed_mesh_min[1]} mesh_max={adaptive_bed_mesh_max[0]},{adaptive_bed_mesh_max[1]} ALGORITHM=[bed_mesh_algo] PROBE_COUNT={bed_mesh_probe_count[0]},{bed_mesh_probe_count[1]} ADAPTIVE=1 ADAPTIVE_MARGIN=0

M140 S0
M104 S0 
START_PRINT EXTRUDER_TEMP=[nozzle_temperature_initial_layer] 
BED_TEMP=[bed_temperature_initial_layer_single]

```

**Comment by cochcoder** [comment]
> > Just want to mention that the file I sent to Cblaze401 is different than the one I sent you
> 
> @cochcoder 
> 
> I Have a K1Max
> 
> 
> 
> wow, I totally missed that file link.. I was just looking at the start machine code trying to figure out what was different.
> 
> 
> 
> 
> 
> I am assuming I just need to add the adaptive string before the START_PRINT. This is my machine start gcode.
> 
> 
> 
> ```
> 
> {if curr_bed_type=="Textured PEI Plate"}
> 
>   SET_GCODE_OFFSET Z=0.270
> 
> {else}
> 
>   SET_GCODE_OFFSET Z=0.0
> 
> {endif}
> 
> 
> 
> ; Always pass ADAPTIVE_MARGIN=0 because Orca has already handled adaptive_bed_mesh_margin internally
> 
> BED_MESH_CALIBRATE mesh_min={adaptive_bed_mesh_min[0]},{adaptive_bed_mesh_min[1]} mesh_max={adaptive_bed_mesh_max[0]},{adaptive_bed_mesh_max[1]} ALGORITHM=[bed_mesh_algo] PROBE_COUNT={bed_mesh_probe_count[0]},{bed_mesh_probe_count[1]} ADAPTIVE=1 ADAPTIVE_MARGIN=0
> 
> 
> 
> M140 S0
> 
> M104 S0 
> 
> START_PRINT EXTRUDER_TEMP=[nozzle_temperature_initial_layer] 
> 
> BED_TEMP=[bed_temperature_initial_layer_single]
> 
> 
> 
> ```

Is it different than what you initially put? I added the start G-code that you said needed to be in place in the default profile for the K1 Max.

**Comment by tkunchick** [comment]
> > > Just want to mention that the file I sent to Cblaze401 is different than the one I sent you
> > 
> > 
> > @cochcoder
> > I Have a K1Max
> > wow, I totally missed that file link.. I was just looking at the start machine code trying to figure out what was different.
> > I am assuming I just need to add the adaptive string before the START_PRINT. This is my machine start gcode.
> > ```
> > 
> > {if curr_bed_type=="Textured PEI Plate"}
> > 
> >   SET_GCODE_OFFSET Z=0.270
> > 
> > {else}
> > 
> >   SET_GCODE_OFFSET Z=0.0
> > 
> > {endif}
> > 
> > 
> > 
> > ; Always pass ADAPTIVE_MARGIN=0 because Orca has already handled adaptive_bed_mesh_margin internally
> > 
> > BED_MESH_CALIBRATE mesh_min={adaptive_bed_mesh_min[0]},{adaptive_bed_mesh_min[1]} mesh_max={adaptive_bed_mesh_max[0]},{adaptive_bed_mesh_max[1]} ALGORITHM=[bed_mesh_algo] PROBE_COUNT={bed_mesh_probe_count[0]},{bed_mesh_probe_count[1]} ADAPTIVE=1 ADAPTIVE_MARGIN=0
> > 
> > 
> > 
> > M140 S0
> > 
> > M104 S0 
> > 
> > START_PRINT EXTRUDER_TEMP=[nozzle_temperature_initial_layer] 
> > 
> > BED_TEMP=[bed_temperature_initial_layer_single]
> > ```
> 
> Is it different than what you initially put? I added the start G-code that you said needed to be in place in the default profile for the K1 Max.

the only thing different is the offset code.

<img width="264" alt="Screenshot 2024-03-27 at 3 00 15 PM" src="https://github.com/SoftFever/OrcaSlicer/assets/45150915/3b543c78-f17e-4a20-aade-2f68554daeb3">


he new rc will not open on my Mac.

**Comment by cochcoder** [comment]
> the only thing different is the offset code.

I'll change that real quick 

> he new rc will not open on my Mac.

I'll try and fix this

**Comment by cochcoder** [comment]
> > the only thing different is the offset code.
> 
> I'll change that real quick

I just realized that the offset is for bed types, which I can't change

**Comment by tkunchick** [comment]
> > > the only thing different is the offset code.
> > 
> > 
> > I'll change that real quick
> 
> I just realized that the offset is for bed types, which I can't change

Aye, I just wanted to give you all the info.

I am still unable to open the release version with my Mac. Gives an error each time saying its damaged

**Comment by cochcoder** [comment]
> I am still unable to open the release version with my Mac. Gives an error each time saying its damaged

It should be working now, just re-complied it [here](https://github.com/cochcoder/OrcaSlicer/actions/runs/8457312895)

**Comment by tkunchick** [comment]
<img width="270" alt="Screenshot 2024-03-27 at 4 15 25 PM" src="https://github.com/SoftFever/OrcaSlicer/assets/45150915/140fe83e-3efd-4cbf-81d6-d87d1ac6a86e">
 :(

**Comment by cochcoder** [comment]
> <img alt="Screenshot 2024-03-27 at 4 15 25 PM" width="270" src="https://private-user-images.githubusercontent.com/45150915/317503606-140fe83e-3efd-4cbf-81d6-d87d1ac6a86e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NzA5ODEsIm5iZiI6MTcxMTU3MDY4MSwicGF0aCI6Ii80NTE1MDkxNS8zMTc1MDM2MDYtMTQwZmU4M2UtM2VmZC00Y2JmLTgxZDYtZDg3ZDFhYzZhODZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDIwMTgwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxZDI0ZGRhYzRhNTNhNDFhMDU2YmJhYTY2ZmNjNGM2MWU5ZDNkOGQwNzA4ZTgyZTkyYzRhYTY3OWRkNjJiYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LGMOboNMiQ_siIbOhuBfwI2kvaJsmhQ9um28-N_Q5_A"> :(

Ugh, are you using the correct version for the Mac? I.e. arm or x64. Do you happen to have a different device that this would work on? I have no clue why it isn't working on Mac, as I didn't change anything to do with that.

**Comment by tkunchick** [comment]
> > <img alt="Screenshot 2024-03-27 at 4 15 25 PM" width="270" src="https://private-user-images.githubusercontent.com/45150915/317503606-140fe83e-3efd-4cbf-81d6-d87d1ac6a86e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NzA5ODEsIm5iZiI6MTcxMTU3MDY4MSwicGF0aCI6Ii80NTE1MDkxNS8zMTc1MDM2MDYtMTQwZmU4M2UtM2VmZC00Y2JmLTgxZDYtZDg3ZDFhYzZhODZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDIwMTgwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxZDI0ZGRhYzRhNTNhNDFhMDU2YmJhYTY2ZmNjNGM2MWU5ZDNkOGQwNzA4ZTgyZTkyYzRhYTY3OWRkNjJiYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LGMOboNMiQ_siIbOhuBfwI2kvaJsmhQ9um28-N_Q5_A"> :(
> 
> Ugh, are you using the correct version for the Mac? I.e. arm or x64. Do you happen to have a different device that this would work on? I have no clue why it isn't working on Mac, as I didn't change anything to do with that.

<img width="319" alt="Screenshot 2024-03-27 at 4 22 23 PM" src="https://github.com/SoftFever/OrcaSlicer/assets/45150915/54d4b6e6-8cb2-4cc7-b771-8aa70f07f1fd">

**Comment by cochcoder** [comment]
In the version that works for you can you add this to the start G-Code field? 

M140 S0
M104 S0
; Always pass ADAPTIVE_MARGIN=0 because Orca has already handled adaptive_bed_mesh_margin internally BED_MESH_CALIBRATE mesh_min={adaptive_bed_mesh_min[0]},{adaptive_bed_mesh_min[1]} mesh_max={adaptive_bed_mesh_max[0]},{adaptive_bed_mesh_max[1]} ALGORITHM=[bed_mesh_algo] PROBE_COUNT={bed_mesh_probe_count[0]},{bed_mesh_probe_count[1]} ADAPTIVE=1 ADAPTIVE_MARGIN=0 
START_PRINT EXTRUDER_TEMP=[nozzle_temperature_initial_layer] BED_TEMP=[bed_temperature_initial_layer_single]

**Comment by cochcoder** [comment]
Bistory informed me that ADAPTIVE=1 is not supported by the version of Klipper that comes on the K1 series. Does bed leveling work with the unchanged start G-Code in Orca Slicer?

**Comment by tkunchick** [comment]
@cochcoder 

this is my standard orca start gcode. it will run Creality full mesh, or run KAMP if I have it on.

`{if curr_bed_type=="Textured PEI Plate"}
  SET_GCODE_OFFSET Z=0.245
{else}
  SET_GCODE_OFFSET Z=0.0
{endif}

M140 S0
M104 S0 
START_PRINT EXTRUDER_TEMP=[nozzle_temperature_initial_layer] BED_TEMP=[bed_temperature_initial_layer_single]`

**Comment by cochcoder** [comment]
Does the G-Code that is already in Orca Slicer do bed leveling?

**Comment by tkunchick** [comment]
From what I can tell, no, at least not directly. the START_PRINT seems to run a rough mesh checking the corners.

I assume, if the corners are far enough out of range, the printer runs a full mesh at that point.

I have seen the printer run a full mesh after changing build plates automatically, I assume the range was different enough to cause it to do so.

I am only guessing, since I do not fully understand all the code, why I posted all the codes that seemed relevant. 

KAMP runs a mesh before every print.

Before KAMP was installed, it always checked all 4 corners, but not a full mesh all the time. hard to tell what triggered it to run a full mesh, aka print count or range on the 4 corner probes or even some combo or something else I haven't noticed.

**Comment by cochcoder** [comment]
The only issue with KAMP is that, to my understanding, it doesn't come installed by default on the K1 Max. If we want it to do a full bed mesh leveling, we'll need to have it compatible with what comes preinstalled on the printer.

**Comment by catapultcase** [comment]
just found this thread after experiencing defects that looked like bed compensation wasn't working in Orca 2.1 with my K1 Max. I'm currently printing the same model now using Crealty Print and it looks fine.... what's the outcome here? it will never work on K1 series?
