### ISSUE TITLE
FEATURE REQUEST - Buttons PGUP and PGDOWN like PrusaSlicer

### ISSUE THREAD

**Issue by insane78** [SoftFever/OrcaSlicer#445]
**Is your feature request related to a problem? Please describe.**
Rotate model about 45° is only possible writing down the rotation degree

**Describe the solution you'd like**
Like PrusaSlicer, using PGUP and PGDOWN buttons, we can rotate models about +45° or -45° on z axis

**Comment by SoftFever** [comment]
Make sense
