### ISSUE TITLE
Can move items on a locked plate

### ISSUE THREAD

**Issue by tlhintoq** [SoftFever/OrcaSlicer#4457]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0-dev

### Operating System (OS)

Windows

### OS Version

Win10x64

### Additional system information

Unrelated to bug

### Printer

Unrelated to bug

### How to reproduce

1. Multiple items across 2 or more plates
2. Lock plate 1
3. Select plate 2 as the current working plate
4. Select-All {Control + A}
5. Move the objects

### Actual results

**ALL** of the object on all of the plates move - including the locked plate

![image](https://github.com/SoftFever/OrcaSlicer/assets/11351506/3f405794-7c06-441f-9d09-ccea2a45be3d)

### Expected results

Only the unlocked plate(s) should be affected.

Just a thought... Maybe `Control+A` should only select on the selected plate.  `Control+Shift+A` could be a less common `Select across all plates`.

### Project file & Debug log uploads

Unrelated/unrequired for this bug

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Anything else?

![image](https://github.com/SoftFever/OrcaSlicer/assets/11351506/f96de2ba-d0a8-4bfa-ae9c-abec885f7b0a)

**Comment by tlhintoq** [comment]
Keep alive.  Problem still exists in current 2.0 nightly as of 15apr2024

New job
Add primative: Torus
Lock plate
Grab and move

So what does the lock even do?

**Comment by tlhintoq** [comment]
Bot nudge.

**Comment by tlhintoq** [comment]
"Bot don't close me now" - This is still very much needed.

**Comment by disconn3ct** [comment]
Stalebot is here to say that the maintainers aren't going to triage this and we should go away.

**Comment by tlhintoq** [comment]
A bit pessimistic - but I know it can feel like that at times.
If something *can't* be addressed for a reason like... its too deeply ingrained from the master version that Orca inherits from (I think that's Prusa slicer or Bambu Slicer) then someone should just say that.  We'd all respect it.
But otherwise - since so much work is from volunteers I think it mostly means that nobody feels comfortable tackling the matter after looking at the code for that feature.  I've seen some horrendous gerry-rigged code that someone looks at and says
> Oh helllllll no.  I'm not touching that beast.

**Comment by aaravrav** [comment]
So if there's no progress on an issue it suddenly doesn't exist anymore? What kind of backward logic is this?

**Comment by disconn3ct** [comment]
Didn't you hear? The clanker came out to tell us we aren't wanted here.

**Comment by sweenbeen** [comment]
Lol came here to comment that this problem is still alive and well.... please patch it.

**Comment by travisterrell** [comment]
If this is "Not Planned", the lock button should simply be removed! It doesn't do anything—including a disconnected button on every plate that purports to do something is just confusing.

CORRECTION: Okay, it does have a purpose...but it's solely in support of another pretty rarely used function. It's a flag for "Arrange All" [plates] to ignore that plate when auto-arranging. (Which, if you ask me, the mere _existence_ of an Arrange All plates button is a bug in and of itself, haha.)
