### ISSUE TITLE
"Avoid seam on overhangs" feature request 

### ISSUE THREAD

**Issue by michael7370** [SoftFever/OrcaSlicer#4460]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

the problem occurs when seam  position is set to nearest  and may be generated at too steep overhangs.  seams on steep overhangs can greatly reduce overhang print quality especially  at curled overhangs . ive asked at the facebook group if such a feature will be helpful and the comments were really positive.  

                                                                                                                                                                                 Michael Ben Ezri 

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

just a feature that  prevents seams to be generated at over hangs 

### Additional context

my post at facebook: 
https://www.facebook.com/groups/536505358690130/?multi_permalinks=679112627762735

**Comment by SoftFever** [comment]
This has been implemented in 2.1.0 via #5436
