### ISSUE TITLE
[Feature Request]: Add / Remove instances of item like prusa slicer

### ISSUE THREAD

**Issue by ondrovic** [SoftFever/OrcaSlicer#448]
**Is your feature request related to a problem? Please describe.**
Not really a problem just ease of use.

Adding the + / - buttons to the UI similar to what's available in prusa slicer to allow for add / remove instances of parts

**Describe the solution you'd like**
Add the + / - minus buttons to the UI and have them add or remove an instance of the item that is selected

![image](https://user-images.githubusercontent.com/3682042/223730731-a423b472-c9e0-4881-8ade-d5fb2fb87d7e.png)
![image](https://user-images.githubusercontent.com/3682042/223730811-ad3cb056-0459-42f5-8662-1d8365ec7162.png)
![image](https://user-images.githubusercontent.com/3682042/223730874-fdae2448-18e9-4129-be3b-79575bbc0e67.png)

**Describe alternatives you've considered**
Currently you can copy / paste an item to add, or select and item and delete it

**Comment by munkford** [comment]
Definitely want this!  Further to this, would love to see the "Fill Bed with Instances" function like PrusaSlicer has.

**Comment by Turge08** [comment]
This and "Set number of instances"

**Comment by locki-cz** [comment]
I need this, clone just killing me ... I draw seam on one but no instance and it not copy to rest... then delete and clone again... tehn another tune in second round of printing and again and again :(
