### ISSUE TITLE
After changing the language from English to other language, any stl file cannot be sliced

### ISSUE THREAD

**Issue by dlouvard** [SoftFever/OrcaSlicer#4480]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

macOS

### OS Version

Ventura 13.6.1

### Additional system information

MacbookPro M2 MAX

### Printer

Flashforge M5 pro

### How to reproduce

1. I'm trying to slice a file please with the default language, everything's fine
2. I change the language of Orcaslicer to French, and i restart the soft
3. I retry to slice the same file and now i have an alert message
<img width="679" alt="Capture d’écran 2024-03-13 à 22 53 16" src="https://github.com/SoftFever/OrcaSlicer/assets/3457726/38e8693d-1a07-464e-a202-9a48764184aa">

### Actual results

If the language of the software is not English, the slice causes an error

### Expected results

Any language can be used for slicing

### Project file & Debug log uploads

[debug_Thu_Mar_14_12_49_10_18806.log](https://github.com/SoftFever/OrcaSlicer/files/14601659/debug_Thu_Mar_14_12_49_10_18806.log)
[bug-slicer-other-language.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/14601661/bug-slicer-other-language.3mf.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by iStarComLab** [comment]
Ventura 13.6.1 - The Russian localization has exactly the same error!!!
There is no such error on version macOS 10.15.7!
![photo_2024-03-16_09-32-03](https://github.com/SoftFever/OrcaSlicer/assets/129138485/580c8ab8-cf31-43ea-a74c-4b650b3c7544)
![photo_2024-03-16_09-32-11](https://github.com/SoftFever/OrcaSlicer/assets/129138485/e75e038c-29e3-4658-b9c3-5d8658bff336)

**Comment by Doms3n** [comment]
Same here on Mac Studio and german language. Error on slicing if the language is not english.

**Comment by mrgfonkyfresh** [comment]
toujours le meme probleme avec la version 2.0.0 RC (français)

**Comment by iStarComLab** [comment]
Up

**Comment by dlouvard** [comment]
Always the same problem with 2.0.0 stable :-(

**Comment by iStarComLab** [comment]
What is being done to solve the problem, has it taken a while to resolve this bug?

**Comment by iStarComLab** [comment]
![Снимок экрана 2024-04-04 в 20 31 12](https://github.com/SoftFever/OrcaSlicer/assets/129138485/e2457d6f-b6e9-4789-8d79-8fc327df8d51)

**Comment by mrgfonkyfresh** [comment]
personne n a encore trouvé de solution???
apparemment sur version ultérieurs macos (catalina) cela fonctionne...

**Comment by DerksenA** [comment]
<img width="402" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/94867202/0d0955b0-2a75-4c49-8aa8-a25b8f0c0501">
Find the option Small Area Compensation, set checkbox to true and then delete all in the field Compensation Modell. After this you can disable the checkbox again and you are able to slice.

**Comment by mrgfonkyfresh** [comment]
Ça ne fonctionne pas j’ai un message d erreur. 

![image](https://github.com/SoftFever/OrcaSlicer/assets/163590068/86dd489a-cf4f-4712-8abd-d43539f4d1b6)

**Comment by iStarComLab** [comment]
> <img alt="image" width="402" src="https://private-user-images.githubusercontent.com/94867202/325766448-0d0955b0-2a75-4c49-8aa8-a25b8f0c0501.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyMzAyMjMsIm5iZiI6MTcxNDIyOTkyMywicGF0aCI6Ii85NDg2NzIwMi8zMjU3NjY0NDgtMGQwOTU1YjAtMmE3NS00YzQ5LThhYTgtYTI1YjhmMGMwNTAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI3VDE0NTg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1MTQwOTM2MDZmZTQ3MTc4YTU5YjcxYjM4NjIwOWJlODBlOGU3YmFlYzFjMGRhNjdiM2YzM2QxMjk1YThmODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JPJwZhSwKjmSRMUEQYxs5HDVR9Wqj-go9NVQ8uuGUoU"> Find the option Small Area Compensation, set checkbox to true and then delete all in the field Compensation Modell. After this you can disable the checkbox again and you are able to slice.

Everything worked out! Thank you!

**Comment by iStarComLab** [comment]
![Uploading Снимок экрана 2024-04-27 в 20.01.03.png…]()

**Comment by iStarComLab** [comment]
![Снимок экрана 2024-04-27 в 20 01 03](https://github.com/SoftFever/OrcaSlicer/assets/129138485/6bc7ec55-ce01-4e48-88af-cdb9fc31707c)
