### ISSUE TITLE
AMS Custom filaments cannot be selected with V.2.0.0 Version!

### ISSUE THREAD

**Issue by dChamp94** [SoftFever/OrcaSlicer#4481]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

Windows

### OS Version

Windows 11

### Printer

Bambulab P1s

### How to reproduce

Go to "Device" > Reset slot > Click the pencil > Drop down > Custom filaments is not in the list anymore. > Degrade to previous Orcaslicer version > Custom filaments is back in the AMS drop down list!

### Actual results

Custom filament in the AMS is not available

### Expected results

Custom filaments should show up in the AMS drop down.

### Project file & Debug log uploads

Dont have.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by SoftFever** [comment]
Custom filament profiles is never supported?

**Comment by dChamp94** [comment]
> Custom filament profiles is never supported?

![1](https://github.com/SoftFever/OrcaSlicer/assets/38186101/48c1330e-ae4a-45b4-a7f8-f7fa4a967e6d)
![2](https://github.com/SoftFever/OrcaSlicer/assets/38186101/ad3c510a-b0e1-454b-a05c-ea6de9be3dcd)
![3](https://github.com/SoftFever/OrcaSlicer/assets/38186101/75a7aa27-74ba-4716-ab6c-a8fe3e807bdf)
![4](https://github.com/SoftFever/OrcaSlicer/assets/38186101/0c9e534a-3b09-4aac-8f94-2a64ba538123)

This is custom filament profiles, or am I missing out on smth? I've created custom filaments and successfully loaded them into AMS as pictures shows. 😨

**Comment by qidldle** [comment]
I had the same problem and had to downgrade the version

**Comment by anselor** [comment]
I had the same problem. It was happening with the nightly builds too. 

This may or may not be related but I noticed that when I export profiles with the nightly/beta it reports version 1.8.3 rather than 1.9 or 2.0.

**Comment by brjohnso1** [comment]
Me too. Same issue. All my custom filament settings are unusable.

**Comment by romanAst** [comment]
У меня такая же проблема, кто нибудь смог ее решить?

**Comment by p0lfilt3r** [comment]
Same issue running appimage on Linux

**Comment by gshpychka** [comment]
> Custom filament profiles is never supported?
@SoftFever are you sure? I've been using them with my P1S since 1.8.0 I believe. Wasn't it one of the features of the release?

**Comment by anselor** [comment]
As a Bambu user, the 2.0.0 release is very broken without the ability to configure the filament in the AMS.

**Comment by Unit210** [comment]
Version 2.0.0 official release, not beta. Still happening. Can't configure AMS even though custom filament exist just like in the picture above. Feels like the drop down menu in Device tab has lost it's link to the Custom Filament list. If it's that it should an easy fix

**Comment by anselor** [comment]
It looks like I'm being forced to become a Bambu Studio user now.

**Comment by anselor** [comment]
I use the Bambu P1S with AMS. The PRs I submitted a while back were all related to managing custom filament profiles - adding new material types and popular vendor types.

You can configure custom filaments like this:
<img width="335" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/17968842/24093c7b-57ba-4692-ac12-1d40385a29e0">
<img width="630" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/17968842/fdafa106-a4d8-479b-a4ee-9c85d01389bf">
<img width="614" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/17968842/50045c10-58d1-4d98-8a76-3eb58eae8df9">
![image](https://github.com/SoftFever/OrcaSlicer/assets/17968842/d51a9a5c-9b5c-4ead-9d9d-096aea1a69e8)

Once a custom filament is created, you can select them here:
<img width="482" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/17968842/43f0cd79-8c5c-4587-b57b-4a0ffd9a4b2d">
<img width="485" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/17968842/08c77c56-a7a1-430b-b14c-518b411fce3a">
<img width="299" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/17968842/f46c45e7-cdc1-401f-95c9-669fb7a51fc0">
![image](https://github.com/SoftFever/OrcaSlicer/assets/17968842/945dbfe0-35fa-45fa-b14a-f10e75c9d0d0)


@SoftFever

**Comment by gshpychka** [comment]
> I only have a P1P printer, neither orca nor bambu studio can see custom filament in my machine.

Custom filament was selectable with a P1S pre-2.0 (might have been broken in 1.9.1 too). Check the screenshots higher up in the thread.

**Comment by anselor** [comment]
> > I only have a P1P printer, neither orca nor bambu studio can see custom filament in my machine.
> 
> Custom filament was selectable with a P1S pre-2.0 (might have been broken in 1.9.1 too). Check the screenshots higher up in the thread.

I'm still using 1.9.1 because it custom filaments work correctly.

**Comment by SoftFever** [comment]
Hey guys,

Here are some updates on this:
I have investigated the issue. Bambu explicitly disabled the ability to set custom filament to AMS for A1 and P1 serials starting with BS1.8.4. The likely reason is that while you can set it in Orca/BS, it doesn't appear in their mobile app. I have re-enabled this feature in the latest [OrcaSlicer nightly](https://github.com/SoftFever/OrcaSlicer/releases/tag/nightly-builds) build. Please give it a try.

**Comment by anselor** [comment]
The missing custom filaments appear to show up in the nightly. What a strange thing for them to do.

**Comment by p0lfilt3r** [comment]
Custom filaments are shown in the nightly now, thank you! And they appear in the mobile app from Bambulab. Don't know what  app they are using.

**Comment by supagold** [comment]
I'm not sure if I'm doing something wrong here, but I appear to be having this issue with custom filaments and my AMS, which is connected to a P1P with a P1S upgrade kit. My custom filament doesn't appear in OrcaSlicer nightly build linked by @SoftFever (which took me to the 2.1.0-beta), the v2.0 release, or v1.9.1. The post above mine appears to imply they might also show in Bambu Handy, but I'm not seeing it there either.

**Comment by RemindZ** [comment]
@SoftFever 
this is broken for me again in 2.1.1 - had the filaments successfully setup in 2.0 (I reckon, at least) after installing 2.1.1 they don't show in the AMS anymore (still see them in the custom filament tab).

**Comment by anselor** [comment]
@RemindZ Depending on how your custom filaments are defined, it could be related to this issue I found
https://github.com/SoftFever/OrcaSlicer/issues/5707

**Comment by RemindZ** [comment]
@anselor sorry for being a bit late with my reply. 
Unfortunately, regardless of what name I give the profile it doesn't show up (I have multiple compatible nozzles within the .json like you do). Even if I create a new profile via the custom filaments menu within the filament settings and then switch to the device tab immediately after I won't be able to find it within the AMS settings there.

**Comment by anselor** [comment]
@RemindZ Best I can tell, Bambu is actively making changes to break the ability to do this kind of customization. Over the past few months I've had to re-adjust the way I do custom filaments multiple as each time I've gotten something working they've introduced a new change to disable it.

**Comment by RemindZ** [comment]
@anselor that sounds great...
well, I do believe we are able to update their Bambu presets that the AMS can read out from the RFID tags on their own spools right - wonder if anything prevents me from reusing those tags.
