### ISSUE TITLE
Model does have free floating regions despite using tree supports (auto)

### ISSUE THREAD

**Issue by jannisbecker** [SoftFever/OrcaSlicer#4483]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

1.9.1 - 2.0.0

### Operating System (OS)

Windows

### OS Version

Windows 11

### Additional system information

Ryzen 5800x
32gb DDR4

### Printer

Bambu Lab P1P

### How to reproduce

1. Load the attached project
2. Switch to a Bambu Lab P1P Profile if not already selected and Bambu PLA Basic (it seems to occur on both 0.4 and 0.8 nozzle profiles in different ways) 
2. Slice the project (settings should be set to Tree Supports Auto, otherwise default)
3. Observe the first 3 layers.

### Actual results

There is a giant overhang wall that overhangs well over a centimeter in mid air, it does not have Tree supports beneath it. I assume its because its only on the second/third layer and there's no space beneath it, but Bambu Studio in contrast still puts support below it

See here: The blue overhang is built on the second layer above the purple first layer, and there's no supports under it.
The structure only gets supported starting on the 4th layer.
![image](https://github.com/SoftFever/OrcaSlicer/assets/31903525/a4a34008-a699-4e8c-ab54-539d1a3e94e5)

### Expected results

Even the second and third layer should have support in some way, if they dont it leads to extrusion problems (similar to printing the first layer too high)

### Project file & Debug log uploads

[staff_head_full.zip](https://github.com/SoftFever/OrcaSlicer/files/14602565/staff_head_full.zip)
[log.zip](https://github.com/SoftFever/OrcaSlicer/files/14602601/log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by SoftFever** [comment]
Thanks for reporting, it's indeed a bug here.
As a workaround for now, you can use normal support for such model.
