### ISSUE TITLE
Increase size of color scheme dropdown to eliminate need to scroll

### ISSUE THREAD

**Issue by Lincoln-Jones** [SoftFever/OrcaSlicer#4486]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

The dropdown for the color scheme options is unnecessarily small and requires scrolling down to access options like Fan Speed or Temperature:

![image](https://github.com/SoftFever/OrcaSlicer/assets/94238653/175723ef-1545-424b-98a5-1d93b2e5718c)

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

There is plenty of space in that area, so hopefully that dropdown element can be extended vertically so all the options are visible without the need to scroll.

**Comment by kylek29** [comment]
I agree on this, the list has outgrown the initial implementation with all of the options now. 

Alternatively, I'd love to see an option to toggle on the PrusaSlicer way of using UI buttons along the bottom of the model that toggle these, it's way quicker to switch between the different views that way.

**Comment by yw4z** [comment]
added to my list
