### ISSUE TITLE
"False" travel acceleration warning

### ISSUE THREAD

**Issue by Exerqtor** [SoftFever/OrcaSlicer#4487]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0 beta

### Operating System (OS)

Windows

### OS Version

Win10x64

### Printer

Voron Trident running RRF

### How to reproduce

Copy the settings in the attached image and "Add primitive cylinder" or whatever to the buildplate and it throws the warning.
![orca2bug](https://github.com/SoftFever/OrcaSlicer/assets/41635644/79c170d5-3e0f-4a54-ad16-a39cc7b8f50e)

### Actual results

Warns about the set travel acceleration is exceeding the machine limits.

### Expected results

Shouldn't warn since the travel acceleration set in the profile is the same as the machine limit.

### Project file & Debug log uploads

[log.zip](https://github.com/SoftFever/OrcaSlicer/files/14605452/log.zip)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by DVSVIDEO** [comment]
The framed error message does not mention the trip but the extruder....

**Comment by Exerqtor** [comment]
I don't know what you're trying to achieve with your comment @DVSVIDEO.. In what way am i being inattentive? The `travel acceleration` should as far as i know not be connected with the `extruder max acceleration` in this case. How fast i want to move the print head during travel NOT EXTRUDING shouldn't be capped off by the max acceleration of the extruder in any way since the extruder aren't doing anything during that move.

**Comment by ReinhardC** [comment]
(Not directly related but allow me to piggyback if this gets looked at :) -- There's also a travel speed warning and cap when the machine limit speed per axis is set to 500 for example, it could in theory go bit above 700 when both axes are used at the same time - still there's a warning when max travel speed is 700)

**Comment by SoftFever** [comment]
@Exerqtor 
what gcode flavor are you using?

**Comment by Exerqtor** [comment]
> @Exerqtor what gcode flavor are you using?

RepRapFirmware

**Comment by SoftFever** [comment]
RRF use separate travel accel.
This is fixed in nightly build: https://github.com/SoftFever/OrcaSlicer/releases/tag/nightly-builds
