### ISSUE TITLE
Flow calibration using a 1mm nozzle creates overlapping objects on the bed

### ISSUE THREAD

**Issue by netweaver1970** [SoftFever/OrcaSlicer#449]
**Describe the bug**
When using the BS-SoftFever build-in Flow calibration using a 1mm nozzle, it creates overlapping objects on the bed

**To Reproduce**
create a printer with a 1mm nozzle, do a flow calibration test.

**Expected behavior**
'normal' test squares created

**Screenshots**
![image](https://user-images.githubusercontent.com/18028618/223782387-ddd41c11-b876-4981-a3c7-b617c06485db.png)

**Printer model**
Voron 2.4

**Desktop (please complete the following information):**
Build Win64 #117: Commit [a6cd32f](https://github.com/SoftFever/BambuStudio-SoftFever/commit/a6cd32fe7276a4de549a24d7e29a61f508c8d10f) pushed by [SoftFever](https://github.com/SoftFever)

**Comment by bojangles86** [comment]
overlaps with .8mm as well, just not as bad as this.

**Comment by netweaver1970** [comment]
bump. In fact lots of calibrations are going haywire with NON 0.4 nozzles. It's clear there's hardcoding of 0.4mm in lots of them, instead of taking the configured nozzle width and being more intelligent about it

**Comment by sleewok** [comment]
Same issue here on 1.8. When I first load up the flow rate test on my 0.8+ nozzles it will layout correctly. However, I don't always print them all. If I disable printing, or delete an object the layout gets fudged.

**Comment by night-crawler** [comment]
Same here
![image](https://github.com/SoftFever/OrcaSlicer/assets/1235203/582459c8-6ca2-4e9b-bbcf-54b14cd89e2e)
