### ISSUE TITLE
Crash when using Send instead of Print

### ISSUE THREAD

**Issue by 407pilot** [SoftFever/OrcaSlicer#4496]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0 Beta

### Operating System (OS)

macOS

### OS Version

Sonoma 14.3.1 (23D60)

### Printer

Bambu X1C

### How to reproduce

Slice an object.
Change Print to Send with the pulldown carrot.
Click Send

### Actual results

The send status bar begins to move, then the app crashes. The window closes and MacOS displays the system crash report dialog. 

This happens with every project I've tried.

### Expected results

It should send the gcode to the printer without crashing. 

### Project file & Debug log uploads

[logs.zip](https://github.com/SoftFever/OrcaSlicer/files/14609754/logs.zip)
[Cyclic Grip.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/14609756/Cyclic.Grip.3mf.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by no3l0815** [comment]
i got the same bug on linux since V1.9.1
