### ISSUE TITLE
Mirroring STL causes crash

### ISSUE THREAD

**Issue by DBShrill** [SoftFever/OrcaSlicer#4498]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

1.9.1 and 2.0.0 beta

### Operating System (OS)

macOS

### OS Version

MacOS 136.2

### Additional system information

M2 Pro 16gb

### Printer

Voron 0.2

### How to reproduce

1. Import stand_2_b_LHS.stl
2. Lay flat using Auto orient
3. Mirror across x-axis
4. Try to slice

### Actual results

App crashes
<img width="254" alt="Screenshot 2024-03-15 at 12 31 11 PM" src="https://github.com/SoftFever/OrcaSlicer/assets/87656771/5e17d447-55e3-4286-80a2-6d87e32ec284">

### Expected results

Should be able to slice normally and upload it to my designated printer

### Project file & Debug log uploads

[stand_2_b_LHS.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/14610752/stand_2_b_LHS.3mf.zip)
[debug_Fri_Mar_15_11_30_25_61421.log.0.zip](https://github.com/SoftFever/OrcaSlicer/files/14610755/debug_Fri_Mar_15_11_30_25_61421.log.0.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by SoftFever** [comment]
I'm not able to repro the bug with the attached project.
Are you able to repro this crash consistently? Any extra info would be helpful

**Comment by Sushiman42** [comment]
I am having trouble with this as well. Seems to be related to #3346. Interestingly, I was able to solve this by mirroring my parts, exporting as STL, and then re-importing them alongside the non-mirrored originals.

**Comment by DBShrill** [comment]
> I'm not able to repro the bug with the attached project. Are you able to repro this crash consistently? Any extra info would be helpful

Only for that specific file. I provided all the information about that specific error but a problem that arose was that if my layer height was above 0.32 (for a 0.4mm nozzle), the app would never open. I could only fix this issue by manually editing the slicer profile using some text editor. 

As of now I have not had any error with any other file the 2.0.0 beta seems to be working well.

**Comment by DBShrill** [comment]
I have tried reproducing the error again and have not been able to. If someone else were to have this issue I would suggest trying to manually lay the object flat or mirroring the object directly from a different modeling software. As far as I know, this seems to be an isolated issue that may have only affected me.

**Comment by BlackEagle94** [comment]
The issue still Exists on v2.0.0 nightly build.
The Object was Mirrored correctly. When Start to Slice Orca will Crash.
[Orca v2.0.0 Mirroring Crash.txt](https://github.com/SoftFever/OrcaSlicer/files/14897946/Orca.v2.0.0.Mirroring.Crash.txt)

**Comment by ckonkel** [comment]
I have the same issue with this model, when I try mirroring (x or y or z)it I get this error:
Orca 2.0.0 windows 11

A fatal error occurred: "Access violation"
Please save your project and restart the application

using this model

[tb2-side-front-v2 (1).zip](https://github.com/SoftFever/OrcaSlicer/files/15358984/tb2-side-front-v2.1.zip)

have seen other errors that force me to restart orca as well, but have not replicated , but happens when mirroring
