### ISSUE TITLE
BIQU B1 SE PLUS with ABL profile

### ISSUE THREAD

**Issue by Frank41682** [SoftFever/OrcaSlicer#4509]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I cannot get the BIQU B1 profile to work for the larger BIQU B1 SE PLUS. In other slicers you can just edit the bed size and add ABL to the start code. That is not working with the B1 preset profile in Orca 

### Which printers will be beneficial to this feature?

Marlin

### Describe the solution you'd like

I would like a machine/printer profile for the BIQU B1 SE PLUS with auto bed leveling in the Start G-code.

**Comment by nilcemar** [comment]
Same issue here... BIQU B1 SE PLUS not working with Orca Slicer... Any suggestions?
