### ISSUE TITLE
SEMM-Output variable volume purge info with "purge into prime tower" disabled

### ISSUE THREAD

**Issue by 53Aries** [SoftFever/OrcaSlicer#4510]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I am attempting to purge into a bucket using variable volume purge. Orca will not output variable purge volumes to gcode unless "purge into prime tower" is enabled. With "purge into prime tower" enabled I am unable to purge into bucket AND have a prime tower. All purging is done into prime tower. 

### Which printers will be beneficial to this feature?

Klipper

### Describe the solution you'd like

I would like to do like a Bambu printer and purge into bucket using variable volume purge and also use a prime tower after purging. I see in the Bambu X1 preset Orca is outputting variable volume purge info while "purge into prime tower" is disabled. 

### Describe alternatives you've considered

I have found no way to use variable volume purge into bucket while also using a prime tower. Currently I do not use a prime tower so that my purge can be done in a bucket.

**Comment by 53Aries** [comment]
This is the same issue as https://github.com/SoftFever/OrcaSlicer/issues/2900. It seems it was fixed for Bambu printers but not other printer profiles.

**Comment by Batalhoti** [comment]
I had the same problem as you, the alternative was to go back to version 1.8beta, where you can use the same filament change gcode as bambulab to purge in the bucket.
