### ISSUE TITLE
crashing on macos upon loading stl with (0.6/0.8) nozzle printer

### ISSUE THREAD

**Issue by MuaiyadTSB** [SoftFever/OrcaSlicer#4512]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0-beta Nightly (1943259)

### Operating System (OS)

macOS

### OS Version

macos 14.4 (arm-64) 

### Printer

multiple printers with large nozzle

### How to reproduce

1- Select Printer with 0.6/0.8 Nozzle
(Tested on the following: K1 0.6, X1C 0.6, Ender 5 pro 0.8, MK4 0.8, Voron 2.4 250 0.6)
2- Import stl file 

### Actual results

Orcaslicer crash

### Expected results

Load STL

### Project file & Debug log uploads

[Archive.zip](https://github.com/SoftFever/OrcaSlicer/files/14623159/Archive.zip)

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Anything else?

oddly enough i have a modified profile of K1 0.8, with lower motion speeds and it loads stl's just fine.

**Comment by patofoto** [comment]
Same problem here.

**Comment by Mario-vminion** [comment]
same here
