### ISSUE TITLE
Increase permissable Z build height

### ISSUE THREAD

**Issue by enderextender** [SoftFever/OrcaSlicer#452]
**Is your feature request related to a problem? Please describe.**
The current maximum build height is capped at 1000mm.  Can this be increased to accommodate large format printers?

**Describe the solution you'd like**
I have a printer that has 1600mm z height.  I cannot set the value to this in either PrusaSlicer or SoftFever.  So I'm stuck with Cura.

**Alternatively** 
I can compile the code but I can't find the code that's enforcing this rule or the problems that may be caused by increasing it?

**Comment by SoftFever** [comment]
@enderextender 
 Increase to 2 meters.
You can ref commit https://github.com/SoftFever/OrcaSlicer/commit/dfa5d42d84c6de62ea48ec36447c51e617011f64 regards where to change
