### ISSUE TITLE
"Detect narrow internal solid infill" corner triangle has wrong print order

### ISSUE THREAD

**Issue by adripo** [SoftFever/OrcaSlicer#4534]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0-beta

### Operating System (OS)

Windows

### OS Version

W11

### Printer

BambuLab P1P

### How to reproduce

I was trying to print https://www.thingiverse.com/thing:4320201 and came across a strange issue.
The wallet is positioned upside down, with the opening on the bottom.
If the option "Detect narrow internal solid infill" is enabled (enabled by default for me) the slicer will produce strange behaviour on layers 2, 4.
In the corner of the internal "flap" it will create a separate triangle with concentric pattern and will do the rest of the layer with the correct pattern.
This is an issue in my case because the extruder will travel from that triangle to the other side of the layer to continue the infill without retracting and oozing filament that will ruin the print.

![2024-03-17_19-28-00-332_orca-slicer](https://github.com/SoftFever/OrcaSlicer/assets/26493496/748b7413-8077-4a7a-b5dd-6335a3049bfa)
![2024-03-17_19-28-27-362_orca-slicer](https://github.com/SoftFever/OrcaSlicer/assets/26493496/0feb9b90-67b4-4e8d-9a31-1f8a867d7f78)
![2024-03-17_19-28-57-075_bambu-studio](https://github.com/SoftFever/OrcaSlicer/assets/26493496/e437f6ab-9483-47bb-b240-939cdcf390d2)

### Actual results

![2024-03-17_19-28-00-332_orca-slicer](https://github.com/SoftFever/OrcaSlicer/assets/26493496/748b7413-8077-4a7a-b5dd-6335a3049bfa)

### Expected results

![2024-03-17_19-28-27-362_orca-slicer](https://github.com/SoftFever/OrcaSlicer/assets/26493496/0feb9b90-67b4-4e8d-9a31-1f8a867d7f78)

### Project file & Debug log uploads

Attached projects:

[Wallet_issue.zip](https://github.com/SoftFever/OrcaSlicer/files/14628458/Wallet_issue.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by vgdh** [comment]
You can disable this feature. Just uncheck **detect narrow internal solid** infill in **strength**

**Comment by adripo** [comment]
Why does the behavior differ between Orca and BS despite identical settings? If this is indeed the case, then there appears to be an issue with the print order: after printing the triangle, the extruder travels to the opposite side of the layer to begin the standard monotonic infill. A more logical approach would be to initiate the infill at the triangle and continue towards the other side, or conversely, start on the opposite side and conclude with the triangle.

**Comment by adripo** [comment]
@igiannakas did you have time to check?

@SoftFever I just rechecked with version 2.1.0-beta and the results are the same. Please check the attached video. As you see the triangle is done at the end of the layer by moving the head back and forth and ruining the print.
![2024-06-19_12-41-39-547_orca-slicer](https://github.com/SoftFever/OrcaSlicer/assets/26493496/1a42d822-0e1a-40cb-aa2c-22925e18507f)

**Comment by igiannakas** [comment]
This is intentional. It’s because that triangle is faster to print than a small zig zag line and also causes less over extrusion compared to a small line.

Bambu studio doesn’t have this feature (along others which have been ported from prusa to orca) so doesn’t do this. But that doesn’t mean that is the better approach ;)

in any case if you don’t want those small triangles you can disable this feature as said above but it’s not generally recommended to do so.

**Comment by igiannakas** [comment]
So I’ve found the reason for this - the code basically always adds the narrow concentric infill to the last position in the layer infill - it may make some sense to check the distance from the next solid infill and order them based on proximity. 

I may work on this in the near future but no promises :)

**Comment by adripo** [comment]
Thank you for the update. Yes, this would definitely be helpful.

**Comment by igiannakas** [comment]
I tried implementing the above and it didn’t fix it - the distance is not mother problem but rather proximity to the last/first position. I’ll try again with a different fix later :)

**Comment by adripo** [comment]
This issue is not solved yet

**Comment by Futtawuh** [comment]
Still an issue, this issue is causing the "tringle" part to be printed last and can cause travel scratches if no z hop.
