### ISSUE TITLE
Cut tool button missing from UI in v 2.0.0, keyboard shortcut (Shift +C) still works

### ISSUE THREAD

**Issue by Ash2033** [SoftFever/OrcaSlicer#4543]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

Windows

### OS Version

Windows 10

### Printer

BambuLab P1S

### How to reproduce

In the toolbar buttons above the render window, it seems the cut button was replaced by a Boolean mesh button(which also has not activated/ darkened from grey when selecting two objects), and the cut tool button is no longer present. The keyboard shortcut of Shift + C still activates the cut tool on the selected part/object.

### Actual results

![image](https://github.com/SoftFever/OrcaSlicer/assets/69884754/8c0799f3-d726-4be7-98d4-2fd35587714f)

![image](https://github.com/SoftFever/OrcaSlicer/assets/69884754/5eb9c46a-4a14-4853-890e-e65767e8d107)

![image](https://github.com/SoftFever/OrcaSlicer/assets/69884754/0ee45ed1-6608-40b6-8773-12faaa036a42)

### Expected results

I assume although not perfect the cut tool was intended to stay in, and have it's own button next to the boolean mesh tool.

### Project file & Debug log uploads

[debug_Sun_Mar_17_20_52_31_3504.log.zip](https://github.com/SoftFever/OrcaSlicer/files/14629625/debug_Sun_Mar_17_20_52_31_3504.log.zip)

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Anything else?

It would be cool to have a button again. I will definitely forget the keyboard shortcut in a week and be frustrated without a visual button.

**Comment by Ash2033** [comment]
I've found the tool button appears when advanced mode is toggled - That may be intended and I'll mark this closed. Otherwise I'm willing to try to add the button in basic mode if someone can direct me to where those buttons appear in the codebase; I'm not a programmer and not versed in it but I'm willing to try/learn.

**Comment by valeyard** [comment]
> I've found the tool button appears when advanced mode is toggled - That may be intended and I'll mark this closed. Otherwise I'm willing to try to add the button in basic mode if someone can direct me to where those buttons appear in the codebase; I'm not a programmer and not versed in it but I'm willing to try/learn.

Thanks, I had no idea that toggling advanced mode on/off changed the buttons visible here!

**Comment by tluv2006** [comment]
> I've found the tool button appears when advanced mode is toggled - That may be intended and I'll mark this closed. Otherwise I'm willing to try to add the button in basic mode if someone can direct me to where those buttons appear in the codebase; I'm not a programmer and not versed in it but I'm willing to try/learn.

Can we have Advanced  defaulted on please? Thanks for finding this.

**Comment by emeyedeejay** [comment]
OMG - thanks for this post ... this was driving me nuts - a friend had not cut icon and we had no clue why. Is cutting an advanced operation? It's not imo - it's a basic thing that many people use to slice things up to fit on build plates.

**Comment by maplemedley** [comment]
I see no reason to hide this button from users that don't need all the parameters in the advanced mode. Slicing is a standard operation that people use to print things bigger than their print-bed and test-print parts of their model. For reference, BambuLab decided to not hide this button from basic mode. 

People who don't tweak advanced print settings either have to keep advanced mode on - making every settings page five times as long and filled with options they're not going to use and have to scroll past - or they'll have to constantly switch advanced mode on and off, just to access this basic functionality. 

This is a needless frustration point honestly, its not like there's not enough space on screen for this one button (and if that is the case, plenty other buttons are more advanced than slicing, like brim ears)

Point in case, I started using OrcaSlicer specifically for the solid splitting functionality, and only found out how to access it through this issue.
