### ISSUE TITLE
Gray box for the max acceleration for travel of printer motion ability setting. The box is gray and not editable.

### ISSUE THREAD

**Issue by FlashforgeOfficial** [SoftFever/OrcaSlicer#4545]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0 beta

### Operating System (OS)

Windows

### OS Version

Edition	Windows 10 Pro Version	22H2 Installed on	‎9/‎5/‎2023 OS build	19045.4046 Experience	Windows Feature Experience Pack 1000.19053.1000.0

### Additional system information

Device name	DESKTOP-S17PHJ6
Processor	13th Gen Intel(R) Core(TM) i7-13700F   2.10 GHz
Installed RAM	32.0 GB (31.8 GB usable)
Device ID	C3C59957-656A-4CD7-89AB-337205BA64C3
Product ID	00331-10000-00001-AA589
System type	64-bit operating system, x64-based processor
Pen and touch	Pen support

### Printer

Flashforge AD5M Pro

### How to reproduce

Just run the OrcaSlicer, and click the edit button for printer preset. I can't find a way to make the [max acceleration for travel] box editable. As shown below:
![motion_ability_acceleration](https://github.com/SoftFever/OrcaSlicer/assets/144670305/275b0f03-56da-49c2-b06c-6f7e168e7706)

### Actual results

I am not able to edit and have a bit higher max acceleration for travel for the printer.

### Expected results

The box should be black and editable as the other motion ability settings, such as max acceleration for retracting and extruding etc.

### Project file & Debug log uploads

[Report issue_ max acceleration for travel not editable.zip](https://github.com/SoftFever/OrcaSlicer/files/14632807/Report.issue_.max.acceleration.for.travel.not.editable.zip)
[log.zip](https://github.com/SoftFever/OrcaSlicer/files/14632811/log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Anything else?

![motion_ability_acceleration](https://github.com/SoftFever/OrcaSlicer/assets/144670305/5908e534-636c-48ac-b628-d02048ffa0f8)
This is a screenshot for your reference. Thank you!

**Comment by Luke56784** [comment]
Same problem here with a Ratrig V-Minion.
I'm limited to 9000 maximum travel speed. Gray, not editable box.

I'm using the Orcaslicer 2.0.0

**Comment by iz3man** [comment]
Same here. Greyed out with 20.000mm/s2 which is way too much for my little Ender2 ;)

**Comment by Luke56784** [comment]
You can set the value manually in your printers .json file.

add this:

```
    "machine_max_acceleration_travel": [
        "15000",
        "9000"
    ],
```

first value is active, second looks like it's the default one.

**Comment by matiasgql** [comment]
It is intentional, [here](https://github.com/SoftFever/OrcaSlicer/issues/5188#issuecomment-2081584890) it explains why it is disabled
