### ISSUE TITLE
Issue with importing filament & printer profiles after laptop change

### ISSUE THREAD

**Issue by fryc88** [SoftFever/OrcaSlicer#4547]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0

### Operating System (OS)

Windows

### OS Version

Win 11

### Additional system information

Not relevant.

### Printer

Voron 2.4, Creality K1 Max, Sovol SV01 pro

### How to reproduce

1. File > Export configs.
2. Reinstall windows/change PC
3. File > Import configs

### Actual results

Nothing gets imported.
![image](https://github.com/SoftFever/OrcaSlicer/assets/50572708/a9157a61-384b-4eff-aa6b-a3778f2dcc60)

### Expected results

All Orca, printer and filaments configs to be imported.

### Project file & Debug log uploads

[log.zip](https://github.com/SoftFever/OrcaSlicer/files/14633652/log.zip)
[Klicky-dock-A-no_logo.zip](https://github.com/SoftFever/OrcaSlicer/files/14633653/Klicky-dock-A-no_logo.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Anything else?

Export/import config seems to be completely broken.

**Comment by cdreier** [comment]
did you manage to import your configs somehow? just hitting the same problem on linux :(

**Comment by jrbenito** [comment]
Same here is happening with Creality K1, Linux Appimage Orca

**Comment by pm0u** [comment]
Yep. Export a printer, import it on another machine... nothing? Is there some trick here? I was hoping that the printer preset would be the printer and everything that goes along with it

**Comment by pm0u** [comment]
I managed to import mine by adding the generic system preset that relates to my printer and then import the saved presets. This did include all filaments and print profiles thankfully. I'm not sure what you would do for a generic - i guess start with the generic klipper or marlin profile?

**Comment by dylan-hilger** [comment]
I know this thread is pretty old, but I ran into the same issue just moments ago when moving files & configs over from my old desktop. I found that you need to import your .orca_printer config files to the SAME version of OrcaSlicer that they were taken from.

For example, my old desktop had OrcaSlicer v2.0.0; when setting up my new desktop I just installed the latest version from OrcaSlicer's website (v2.3.0), this resulted in the .orca_printer config files not being properly import/register within the application. I tried importing to an older version (v1.9.0), but this also didn't work.

It was only when I completely uninstalled the previous versions of OrcaSlicer, restarted my PC, and then installed the same OrcaSlicer version from my old desktop (v2.0.0) that the .orca_printer config files were completely and properly imported and available within the app. 

There was no warning or indication that a version mismatch was the exact cause, but through trial and error I'm fairly confident that was the cause. 

I haven't yet tried updating, but I'm sure now that they exist, I'll have a better chance of going to a newer version.
Hopefully this helps. Best of luck!

**Comment by Silezmogul** [comment]
Still present.

Printer preset should export without password (+notification password will not be in the export) .

Log-in / printer password should be provided after profile import.

**Comment by KlausHans** [comment]
Same problem in latest 2.3.2
