### ISSUE TITLE
Sliced multi-color model inncorrect color on top layer

### ISSUE THREAD

**Issue by longrackslabs** [SoftFever/OrcaSlicer#4551]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

Linux

### OS Version

Mint 21.3

### Additional system information

![image](https://github.com/SoftFever/OrcaSlicer/assets/1175466/0692a38b-103b-4d59-b78e-3e6317d2302f)

### Printer

Bambu X1C

### How to reproduce

Open attached model of lid riser, model is blue with silver bambu logo.  Slice model, expect blue model with silver logog.

### Actual results

Logo sliced with blue filament

### Expected results

Logo should print with silver filament

### Project file & Debug log uploads

[Bambu Top Lid Glass Riser_Orca_Slice_Bug.zip](https://github.com/SoftFever/OrcaSlicer/files/14637899/Bambu.Top.Lid.Glass.Riser_Orca_Slice_Bug.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Anything else?

Left: Preview of blue model with silver logo
Middle: Sliced with Bambu studio, blue model with silver logo (expected result)
Right: Sliced with Orca, blue model with blue logo (wrong, logo should have top layer of silver).

![Screenshot from 2024-03-18 07-34-15](https://github.com/SoftFever/OrcaSlicer/assets/1175466/db9113b7-75ca-4d3b-b8da-22904b0e8575)

**Comment by igiannakas** [comment]
Please test this fix here: https://github.com/SoftFever/OrcaSlicer/pull/5774
