### ISSUE TITLE
Slow Down For Overhangs - Artifacts induced by unwanted slowdowns.

### ISSUE THREAD

**Issue by lhndo** [SoftFever/OrcaSlicer#4553]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0-beta

### Operating System (OS)

Windows

### OS Version

Windows 10

### Printer

LH Stinger

### How to reproduce

Load the file
Switch preview to Flow and observe unwanted slowdowns continuing out of the overhang areas.
Switch to Classic and observe they are gone.

### Actual results

![image](https://github.com/SoftFever/OrcaSlicer/assets/42773937/37e942a5-850a-440c-90e0-2885c433a8a3)

### Expected results

No slowdowns on perimeters with no overhang
More like Classic mode
![2024_03_18_4820_orca-slicer](https://github.com/SoftFever/OrcaSlicer/assets/42773937/3cc74e47-882e-4ed1-a352-1e9eba44d437)

### Project file & Debug log uploads

[cube overhang.zip](https://github.com/SoftFever/OrcaSlicer/files/14638331/cube.overhang.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by lhndo** [comment]
Hey @SoftFever, just curious, what does make this an enhancement as opposed to a bug?

**Comment by SoftFever** [comment]
These are single ‘long’ extrusions (G1 command) which have only a small part overhanging. Therefore, the whole extrusion is considered as overhanging. To properly apply overhang settings to the exact part of the extrusion, we will need to do some extra work first to break this one ‘G1’ command into multiple smaller G1 extensions.And this might have other consequences like generating larger gcode Sent from my iPhoneOn 28 Mar 2024, at 8:16 PM, LH ***@***.***> wrote:﻿
Hey @SoftFever, just curious, what does make this an enhancement as opposed to a bug?

**Comment by lhndo** [comment]
Understood and thanks for taking the time to answer! I will be trying to stay with the classic algorithm, or find a workaround in the mean time. 

> These are single ‘long’ extrusions (G1 command) which have only a small part overhanging. Therefore, the whole extrusion is considered as overhanging. To properly apply overhang settings to the exact part of the extrusion, we will need to do some extra work first to break this one ‘G1’ command into multiple smaller G1 extensions.And this might have other consequences like generating larger gcode Sent from my iPhoneOn 28 Mar 2024, at 8:16 PM, LH ***@***.***> wrote:﻿ Hey @SoftFever, just curious, what does make this an enhancement as opposed to a bug? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
