### ISSUE TITLE
Port mac ARM application to iPad OS for ipad pro on M processors. 

### ISSUE THREAD

**Issue by artemsvit** [SoftFever/OrcaSlicer#4558]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Hey Folks. I want to ask about the possibility to port application to my iPad pro m2. This is so much powerful device, I guess Orca can easily run on this hardware. 

I’m designer and can help adapt some controls for touch interface, but it can be stay as it is. 

Let’s collaborate and create Orca for iPad Pro first and after maybe it can be run on phones. 

![IMG_7079](https://github.com/SoftFever/OrcaSlicer/assets/156072729/73e20d33-689f-4ea1-b23f-d375fbdefd34)

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

No have solutions right now, it’s proposal.

**Comment by 10a5er** [comment]
Oh no, why did you close it?!

**Comment by michael-rogers289** [comment]
I'm an iOS / Android Dev and I would work on this! I'd love to have a slicer on my iPad.
