### ISSUE TITLE
Feature request? Nightly build has no option to only use custom start gcode.

### ISSUE THREAD

**Issue by DanniDesign** [SoftFever/OrcaSlicer#456]
**Is your feature request related to a problem? Please describe.**
Today i started a print with my own custom start gcode on the nightly build. But in the gcode it still adds the heating commands while im already doing that in the start gcode. So that's very annoying.
Here's an example:
;TYPE:Custom

START_PRINT BED_TEMP=65 HOTEND_TEMP=215

M190 S65 ; set bed temperature and wait for it to be reached

M104 S215 ; set nozzle temperature

M109 S215 ; set nozzle temperature and wait for it to be reached

**Comment by abstractFlo** [comment]
You can remove this by setting 

```
;M190 S[bed_temperature_initial_layer_single] 
;M109 S[nozzle_temperature_initial_layer] ;
```
before your START_PRINT Macro. It's a fix for any Slic3r Related Slicer.

**Comment by Ibot-11** [comment]
For me this removes the bed temp related gcode, but the Hotend ones are still there.

Slicer Startgcode:
```
;M190 S[bed_temperature_initial_layer_single] 
;M109 S[nozzle_temperature_initial_layer]

PRINT_START EXTRUDER_TEMP=[nozzle_temperature_initial_layer] BED_TEMP=[bed_temperature_initial_layer_single] AREA_START={first_layer_print_min[0]},{first_layer_print_min[1]} AREA_END={first_layer_print_max[0]},{first_layer_print_max[1]}
```

Generated Startgcode
```
;TYPE:Custom
;M190 S75 
;M109 S235

PRINT_START EXTRUDER_TEMP=235 BED_TEMP=75 AREA_START=110.375,120.375 AREA_END=209.625,219.625
M104 S235 ; set nozzle temperature
M109 S235 ; set nozzle temperature and wait for it to be reached
G90
G21
M83 ; use relative distances for extrusion
```

**Comment by strayr** [comment]
I get this using Klipper output on 1.5.0, kind of annoying when tying to try this out

```
START_PRINT BED_TEMP=105 EXTRUDER_TEMP=260
;M190 S105 
;M109 S260
M104 S260 ; set nozzle temperature
M109 S260 ; set nozzle temperature and wait for it to be reached
```

**Comment by tlhintoq** [comment]
Bot closed it.  Its not *completed*; its the very opposite of completed or there would have been updates keeping this alive.

On the other hand, there's another bug for basically the same thing.  Forced bed heating even though its in the custom code.
https://github.com/SoftFever/OrcaSlicer/issues/2867
