### ISSUE TITLE
Cannot print to K1C printer

### ISSUE THREAD

**Issue by phuongnd08** [SoftFever/OrcaSlicer#4571]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0-beta

### Operating System (OS)

macOS

### OS Version

14.3.1 (23D60)

### Printer

Creality K1C

### How to reproduce

0. Add K1C Printer, update IP Address
1. Check that the printer successfully connected in the Device tab
<img width="1798" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/184037/ab34821f-32a9-48e2-9292-bc77b4bf57c4">
3. Prepare a model
4. Slice 
5. Print > Upload

### Actual results

<img width="436" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/184037/14eda342-7b17-4e19-8abf-fb4df1c1784b">

```
Error uploading to print host:
HTTP 404: <!DOCTYPE html>
<html>
<head>
<title>404 Not Found</title>
</head>
<body>
<center><h1>404 Not Found</h1></center>
<hr>
</body>
</html>
```

### Expected results

G-Code file uploaded successfully

### Project file & Debug log uploads

Project File:
[NutTapLuoiError.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/14643900/NutTapLuoiError.3mf.zip)

Log File:
[log.zip](https://github.com/SoftFever/OrcaSlicer/files/14643919/log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by bistory** [comment]
You need to root your printer first

**Comment by phuongnd08** [comment]
K1C printer is rooted by default. I just checked, the printer is already rooted, at least on the interface. I can get the root password going to System > Root account information.

**Comment by bistory** [comment]
> K1C printer is rooted by default. I just checked, the printer is already rooted, at least on the interface. I can get the root password going to System > Root account information.

Update moonraker, that's what you need to be able to use push gcode from orca.

**Comment by phuongnd08** [comment]
I installed moonraker:

<img width="403" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/184037/92f9b8e9-f11c-4f27-8fb7-54a94c494084">

But uploading g-code still fails:

<img width="439" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/184037/ae6fe43e-f615-41fa-862c-e818d61f4ce8">

**Comment by phuongnd08** [comment]
I still see Creality default web interface so I'm not sure if there is something else to be done:

<img width="1778" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/184037/95e7c92b-7175-42ad-9af7-9795d9f0dd9c">

**Comment by phuongnd08** [comment]
Okay, I updated the host to http://xxx.xxx.xxx.xxx:4408/ and it's uploading just now. Many thanks @bistory for your support

**Comment by paulochavesBrasil** [comment]
> Okay, I updated the host to http://xxx.xxx.xxx.xxx:4408/ and it's uploading just now. Many thanks @bistory for your support

how do you do it? same problem here, can t send g code direct from my k1

**Comment by phuongnd08** [comment]
<img width="1058" alt="image" src="https://github.com/user-attachments/assets/4c8e7221-150b-4c8a-a84d-7c8f016d617f">
See these red dude.
