### ISSUE TITLE
1 layer thickness on top / bottom

### ISSUE THREAD

**Issue by ValikDov** [SoftFever/OrcaSlicer#4575]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

e.g. 2.0.0

### Operating System (OS)

Windows

### OS Version

Windows 10

### Printer

Anycubic Kobra 2 

### How to reproduce

No Idea how to reproduce

### Actual results

On the screen you can see layer settings that should be used 
![image](https://github.com/SoftFever/OrcaSlicer/assets/80005735/b3e05ebc-ad90-441e-9ca2-235e328e6db8)
1 top layer height
![image](https://github.com/SoftFever/OrcaSlicer/assets/80005735/2cc97bc9-bb29-44d4-811e-e4ef39bbda22)
Still 1 layer height 
![image](https://github.com/SoftFever/OrcaSlicer/assets/80005735/0a39824a-2fe4-4c87-a42d-306ab7b4eca9)
![image](https://github.com/SoftFever/OrcaSlicer/assets/80005735/28cafb12-63a5-472c-bff8-0c48f78828eb)

bottom

### Expected results

Heigth level of 5 layers on top and bottom surfaces

### Project file & Debug log uploads

[Layer_bug_2.0.0.zip](https://github.com/SoftFever/OrcaSlicer/files/14648901/Layer_bug_2.0.0.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by ValikDov** [comment]
There will be a question about "Only one wall of top surfaces". This tab is disabled

**Comment by Sophist-UK** [comment]
I too am seeing this issue - I ask for multiple top and / or bottom layers, but the slicer only slices a single top or bottom layer.

**Comment by kayboy-bebop** [comment]
I can reproduce this error when "Ensure vertical shell thickness" is set to "None".

**Comment by lhndo** [comment]
same here as @kayboy-bebop . "None" setting and 0 shell thickness creates a single top/bottom layer.

**Comment by ilko-k** [comment]
I was about to report this and a quick search took me here so I can confirm. When I want 0 infill, all the shell's solid fill is not generated if "Ensure vertical shell thickness" is disabled ( Strenght → Advanced ).

**Comment by vgdh** [comment]
I can't reproduce the issue in release candidate version

**Comment by kayboy-bebop** [comment]
> I can't reproduce the issue in release candidate version https://github.com/SoftFever/OrcaSlicer/releases/tag/nightly-builds try latest RC version

Yup, RC release fixed this for me.

**Comment by vgdh** [comment]
[ValikDov](https://github.com/ValikDov) please check and close the issue if it resolved.

**Comment by ilko-k** [comment]
latest nightly seems ok in my case (build from 2024.03.23)
