### ISSUE TITLE
Could we get a Ender 3 Max neo Slicer profile (with klipper or without) 

### ISSUE THREAD

**Issue by Ismael-Yakoubi** [SoftFever/OrcaSlicer#4576]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I unfortunately can't find a profile for the Ender 3 max neo

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

A new printer profile for the Ender  3 max neo

**Comment by Duck-Lady** [comment]
So no one is going to even answer this? It is from March.
