### ISSUE TITLE
Blowing the non-hanging overhang

### ISSUE THREAD

**Issue by Artemonim** [SoftFever/OrcaSlicer#4583]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0-beta

### Operating System (OS)

Windows

### OS Version

Windows 11 23H2

### Printer

Ender 3

### How to reproduce

Slice a cylindrical model, with elements on the support

### Actual results

The fan blows the entire support layer equally, resulting in poor baking of the layer.
Pics with fan heatmap:
<img src="https://github.com/SoftFever/OrcaSlicer/assets/36363466/d1cc8f49-d59f-4cf0-a7ba-f091ce96775f" width="800">
<img src="https://github.com/SoftFever/OrcaSlicer/assets/36363466/a152b2fc-fde1-4cef-b43c-d73c73c8ce23" width="800">

### Expected results

Ensure airflow is directed at the sections printed on support structures, but avoid airflow on sections being printed directly on top of the previous layer of the object itself. This is especially important for filaments that are harmed by blowing.
<img src="https://github.com/SoftFever/OrcaSlicer/assets/36363466/3fab8be7-962c-465f-b6bf-b90ff9bd178e" width="800">

### Project file & Debug log uploads

[gear.zip](https://github.com/SoftFever/OrcaSlicer/files/14652324/gear.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by Panzerhalzen** [comment]
A similar problem. The fan blows the entire layer at full power, although it should only work on the supports. In addition, after printing the internal bridges, the fan does not turn off and continues to work until the first layer of the cover is printed.
![JnvIouf6ov](https://github.com/SoftFever/OrcaSlicer/assets/95699436/4b22d89b-bd49-437a-93f8-159a73cbf4ac)
![hnvSyGgIek](https://github.com/SoftFever/OrcaSlicer/assets/95699436/4106bf24-55d6-4967-be0b-6e126aff24ff)

**Comment by Artemonim** [comment]
Haven't re-tested the case from the report, but a similar problem is caused by shifting the timing of the blower fan on.
