### ISSUE TITLE
Switching Bambu printers doesn't transition filament presets

### ISSUE THREAD

**Issue by redstarcg** [SoftFever/OrcaSlicer#4585]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0 - Beta

### Operating System (OS)

Windows

### OS Version

Windows 10

### Printer

P1P ,  P1S, X1C

### How to reproduce

Select printer P1S
Change the filament layer height preset to lets say 0.08
Switch printer to X1C,

### Actual results

The preset will switch from 0.08 to whatever the last preset was on the next printer.

### Expected results

Based on the BambuSlicer they make it so the presets transition from printer to printer. This allows for somebody who has various bambu pritners to print a big part without having to reconfigure all the settings and reclice which takes time especially if a lot of custom settings have been changed. 

### Project file & Debug log uploads

No need for a project file as it works with a blank scene.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by SoftFever** [comment]
Should be fixed in 2.0.0
