### ISSUE TITLE
manual layer change -change color

### ISSUE THREAD

**Issue by PadreDiCudla** [SoftFever/OrcaSlicer#4588]
### Is there an existing issue for this problem?

- [ ] I have searched the existing issues

### OrcaSlicer Version

1.9.1

### Operating System (OS)

Windows

### OS Version

W10

### Printer

FLSUN V400

### How to reproduce

adding pause at layer by right click on layer 
![image](https://github.com/SoftFever/OrcaSlicer/assets/103249694/117f637e-5738-4bb4-acfc-2f19e6cc5962)

### Actual results

did nothing in klipper and didnt stop printer

### Expected results

pause printer and wait for resume

### Project file & Debug log uploads

[log.zip](https://github.com/SoftFever/OrcaSlicer/files/14654503/log.zip)
[cat_bookmark_v2.zip](https://github.com/SoftFever/OrcaSlicer/files/14654507/cat_bookmark_v2.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by vgdh** [comment]
Did you add custom Gcode for pause command in the printer settings section?
