### ISSUE TITLE
Top surface with 1 wall with Arachne

### ISSUE THREAD

**Issue by RickDnamps** [SoftFever/OrcaSlicer#459]
Hello,

Like I said in the title, it would be nice to use arachne and be able to have the top surface with 1 wall only like the classic option. :)

Thanks

**Comment by Ibot-11** [comment]
There are already multiple requests for this. I also requested this a while ago… as a duplicate 😀
#340 #379 #350

**Comment by hliebscher** [comment]
it is working !!!
![a](https://user-images.githubusercontent.com/9274162/224480942-fc9bd5d1-712a-4775-8a48-6b56edfbe8aa.jpg)
