### ISSUE TITLE
Speed value not accepting "0"

### ISSUE THREAD

**Issue by dsplendido** [SoftFever/OrcaSlicer#4599]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0

### Operating System (OS)

Windows

### OS Version

11

### Printer

Ratrig v1 with Fly CDY V3

### How to reproduce

1. Enter value "0" in any layer speed parameter
2. Press enter

### Actual results

![image](https://github.com/SoftFever/OrcaSlicer/assets/97243766/b633ac53-179a-4060-96be-fab3ea1ed0fa)

### Expected results

This screenshot shows that values of "0" were acceptable as parameters in a prior version (1.7). This allows Max Volumetric Flow feature to control speed parameters. Values of 1 or greater in Layer Speed parameters overrides the "Autospeed" values. Result is that Autospeed related to Max Volumetric Flow is effectively disabled.
![image](https://github.com/SoftFever/OrcaSlicer/assets/97243766/995475e3-1ab0-46a5-9870-6b454ff63e63)

### Project file & Debug log uploads

[Max volumetric speed test 105-125.zip](https://github.com/SoftFever/OrcaSlicer/files/14668032/Max.volumetric.speed.test.105-125.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by bitingsock** [comment]
For me, setting it to something like 9999 is the same as 0. Max flow still works.

**Comment by dsplendido** [comment]
That did the trick, thanks for the insight. Max flow or "autospeed" is a critical setting for me, coming from SuperSlicer.
