### ISSUE TITLE
Add "Random" to Seam Painting

### ISSUE THREAD

**Issue by cubitik** [SoftFever/OrcaSlicer#4601]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

It would be good if we had a tick in seam painting menu named "Random"

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

It should randomize the seams in painted area just a little bit, just like in GalaxySlicer (added image). But with a tick named "Random" to enable.
![image](https://github.com/SoftFever/OrcaSlicer/assets/111056006/be220357-eaf7-4fe7-8986-c1bd11cf4d33)

**Comment by buzzhuzz** [comment]
It is already there.

Just paint seams with a bigger *and* select Random seams.

![Screenshot from 2024-03-22 06-41-19](https://github.com/SoftFever/OrcaSlicer/assets/46728448/c4a476ef-a1d1-44c3-bc5f-0bd932d9f7ab)
![Uploading Screenshot from 2024-03-22 06-41-37.png…]()

**Comment by vgdh** [comment]
should be closed, the feature is already there (v 2.0)

**Comment by cubitik** [comment]
> should be closed, the feature is already there (v 2.0)

There is no any feature as explained in the suggestion. Also, if you mean the "brush size", seams are just going at the edge of painted area.
![image](https://github.com/SoftFever/OrcaSlicer/assets/111056006/ea66d9cf-85b3-4f24-9010-5ce14b9b6d3b)
![image](https://github.com/SoftFever/OrcaSlicer/assets/111056006/910939a4-41d2-409c-b460-285af8493d54)

**Comment by vgdh** [comment]
> > should be closed, the feature is already there (v 2.0)
> 
> There is no any feature as explained in the suggestion. Also, if you mean the "brush size", seams are just going at the edge of painted area.

what version of slicer do you use?

**Comment by cubitik** [comment]
> > > should be closed, the feature is already there (v 2.0)
> > 
> > There is no any feature as explained in the suggestion. Also, if you mean the "brush size", seams are just going at the edge of painted area.
> 
> what version of slicer do you use? 

Using latest 2.0.0 RC. ![20240325_013816.jpg](https://github.com/SoftFever/OrcaSlicer/assets/111056006/e9edee19-bd2a-492d-b20b-5c15e07b1748)

![20240325_013831.jpg](https://github.com/SoftFever/OrcaSlicer/assets/111056006/5e46bd41-715d-456f-8a99-b77261d787c6)

**Comment by cubitik** [comment]
> It is already there.
> 
> Just paint seams with a bigger *and* select Random seams.
> 
> ![Screenshot from 2024-03-22 06-41-19](https://github.com/SoftFever/OrcaSlicer/assets/46728448/c4a476ef-a1d1-44c3-bc5f-0bd932d9f7ab)
> ![Screenshot from 2024-03-22 06-41-37](https://github.com/SoftFever/OrcaSlicer/assets/46728448/70a5bc45-80ea-4cdd-9202-1bb02ac42e30)
> 
> 

This causes all the seams to fall apart randomly. The purpose of the feature I propose is to select the "random" option in the seam dyeing menu and only the painted areas will be random.
