### ISSUE TITLE
Large models force support to be built outside of the print bed.

### ISSUE THREAD

**Issue by CreamOfPantsSoup** [SoftFever/OrcaSlicer#4609]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

My machine: Creality K1
I have limited time to work on these projects so if this is a known issue I apologize for submitting a redundant note, The issue I have been working with is that Orca will not arrange a part on the print bed to allow enough room for tree supports. I shortened my model a few times hoping that it would generate some good 'n' tasty gcode. but it hasn't. I went from a 14' x 1' to a 12' x 1' model and I can not get a reliable tool path without manually moving the part to  accommodate the tree supports. I am manually arranging the model on the build plate to generate useful gcode. Thank you for everything you do.

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

I didn't know these fields were here. Do you like reeses or kitkat?

### Describe alternatives you've considered

I like reeses

### Additional context

I love you, but probably not in person.

**Comment by DougJoseph** [comment]
I think my issue is the same or very similar. I have a large part that fits on the print bed (Flashforge AD5M, 220x220) with room to spare for supports, which are needed for this model. I really want to use tree supports. However, the slicing operation insists on basing the tree supports outside the printable area.
