### ISSUE TITLE
Under extrusion on Hilbert curve first layer with small area flow compensation.

### ISSUE THREAD

**Issue by lamtranBKHN** [SoftFever/OrcaSlicer#4617]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

The Hilbert curve first layer is under extrusion when I turn on "Small area flow compensation"

### Which printers will be beneficial to this feature?

Klipper

### Describe the solution you'd like

Disable small area flow compensation on Hilbert curve first layer

### Additional context

![image](https://github.com/SoftFever/OrcaSlicer/assets/61534619/09c049bf-9013-48dc-aca3-ffc249626a51)

**Comment by TocNoc** [comment]
Can confirm this behavior on  OrcaSlicer_Linux_V2.0.0
I do a lot of first layers with Hilbert Curve and after accidentally enabling this option I started having under-extrusion on almost any small details. 
Disabling this option fixed the problem.
![image](https://github.com/SoftFever/OrcaSlicer/assets/42242188/32e23eeb-c001-46e9-98f1-891c78a4da89)
On the left you have flow compensation disabled, on the right flow compensation enabled.

**Comment by TheSlashEffect** [comment]
I managed to reproduce this with some similar shapes to the latter one. I can clearly see the difference in the GCode. @TocNoc , @lamtranBKHN could you kindly link me to your stl's (provided they're free) so I can have some more reference material to work on this? Thank you in advance.
