### ISSUE TITLE
scarf seam

### ISSUE THREAD

**Issue by Rhoenbussard** [SoftFever/OrcaSlicer#4618]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

OrcaSlicer_Windows_V2.0.0-beta_portable - latest nightly build

### Operating System (OS)

Windows

### OS Version

win 10

### Additional system information

AMD Radeon

### Printer

Sovol SV01

### How to reproduce

add Cube with one layer
choose "scarf joint seam" - "contour and hole"
slice with "classic" or "Arachne"

### Actual results

there is no solid infill

### Expected results

generate infill

### Project file & Debug log uploads

[Shape-Box.zip](https://github.com/SoftFever/OrcaSlicer/files/14704306/Shape-Box.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by DVSVIDEO** [comment]
More precisely worded headline....!
Screenshot of the problem?
