### ISSUE TITLE
Add Ability to change to 12 HR clock instead of 24 HR for the Time Completion

### ISSUE THREAD

**Issue by DennAgain** [SoftFever/OrcaSlicer#4620]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I know how to read a 24 HR Clock but not everyone may know how to and i prefer 12 HR and it would be nice to be able to change it.

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

The Ability to Change the Time Estimate Completion of Print to 12 HR, so people who have a preference can choose whichever.
![Capteure](https://github.com/SoftFever/OrcaSlicer/assets/12225108/7a49bed7-0a70-42b3-9600-46ae13085c13)

**Comment by jimmy1970** [comment]
I also would like this.
