### ISSUE TITLE
[Feature Request] - Add Arc Overhangs to Orcaslicer

### ISSUE THREAD

**Issue by mpawood** [SoftFever/OrcaSlicer#4621]
### Is there an existing issue for this feature request?

- [x] I have searched the existing issues

### Is your feature request related to a problem?

Printers use a lot of material sometimes for larger overhangs when printing supports, a way to not need to print those supports would be very beneficial to anyone using a 3D printer.

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

It should incorporate Arc Overhangs, a technique described by Steven McCulloch. 

This has already been somewhat incorporated as an addon to prusaslicer, however the Superslicer version includes Corner Support as the Arc Overhangs have a tendancy to warp after the 2nd or 3rd layer built on top of them.

Another tendancy of Arc Overhangs is to have slight drooping when starting a new semi-circle, a possible solution to this would be to, instead of having the overhang become a part of the final print, but to have a transitional layer between the arc overhang and the underside of the piece in order to make the overhang removable and leave a clean underside as if it had been printed with normal supports.

**Comment by jtatum** [comment]
Dupe of #902
