### ISSUE TITLE
small area flow compensation interfere with extrusion rate smoothing

### ISSUE THREAD

**Issue by vgdh** [SoftFever/OrcaSlicer#4634]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0-beta

### Operating System (OS)

Windows

### OS Version

win 10

### Printer

kingroon kp3s

### How to reproduce

1. make cylindrical primitive 
2. enable Extrusion rate smoothing 
3. enable small area flow compensation

### Actual results

sudden change in flow where is no really change should be
![jpg](https://github.com/SoftFever/OrcaSlicer/assets/15322782/2bed11c1-92d2-4f5e-9933-9740e58e9354)

### Expected results

smooth flow rate

### Project file & Debug log uploads

[proj and logs.zip](https://github.com/SoftFever/OrcaSlicer/files/14718576/prog.and.logs.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by vgdh** [comment]
how it looks in prusa
![2](https://github.com/SoftFever/OrcaSlicer/assets/15322782/8e490a3a-9b3d-424d-a4a2-cc046b1c871c)

**Comment by vgdh** [comment]
It's interfere with **small area flow compensation**
when I turned it off, extrusion flow smoother rate works well.

**Comment by vgdh** [comment]
most likely it occurs because  small area compensation applied before flow smoother. And flow smoother process stumble upon very small very low flow path and do its thing.
@mjonuschat what do you think?

**Comment by igiannakas** [comment]
> most likely it occurs because small area compensation applied before flow smoother. And flow smoother process stumble upon very small very low flow path and do its thing. @mjonuschat what do you think?

That is exactly it. The infill pattern creates small extrusions at the 90 degree mark of the large line segments where the nozzle changes direction. These are set to significantly less flow than the primary extrusion. Hence the extrusion rate smoothing feature kicks in and reduces the flow. 

Suggest you use monotonic lines as your solid infill of choice - it gives a better finish as these small extrusions can cause over extrusion and it also avoids this slowdown issue.

**Comment by igiannakas** [comment]
The infill pattern creates small extrusions at the 90 degree mark of the large line segments where the nozzle changes direction. These are set to significantly less flow than the primary extrusion. Hence the extrusion rate smoothing feature kicks in and reduces the flow.

Suggest you use monotonic lines as your solid infill of choice - it gives a better finish as these small extrusions can cause over extrusion and it also avoids this slowdown issue.

**Comment by vgdh** [comment]
> Suggest you use monotonic lines as your solid infill of choice - it gives a better finish as these small extrusions can cause over extrusion and it also avoids this slowdown issue.

Monotonic lines definitely helps
And it doesn't have print time penalty. I wonder why it's not a default infill?

**Comment by igiannakas** [comment]
Think it’s just a carry over legacy from prusa and Bambu slicer.

**Comment by SoftFever** [comment]
I got different result with the attached project(changed Top Surface pattern to Monotonic)
Although, I don't see the wrong doing
![image](https://github.com/SoftFever/OrcaSlicer/assets/103989404/7ccdd22e-75b7-4ccc-9821-bc558aac184c)

**Comment by SoftFever** [comment]
From your screenshot, it seems fine.
It's indeed not necessary for the smoothing action in this case, but it's probably caused by the relatively small smoothing parameter(I noticed you set it to 10)?

![image](https://github.com/SoftFever/OrcaSlicer/assets/103989404/9f414bf3-12d7-46ed-9aca-71fdc49faa5b)

**Comment by vgdh** [comment]
yeah
When i switched to monotonic line the problem has gone.
So should I close the issue then?

**Comment by Rickthebig** [comment]
> yeah When I had switched to monotonic line the problem has gone. So should I close the issue then?

No, I think the issue would still be there. If there are any incompatibilities when using flow smoothing with certain infill patterns, the software should at least prevent the user setting those patterns. It is no good idea to create a software that implies that you are acquainted with its quirks.

The clean solution would be to fix the bug allowing any infill pattern.
