### ISSUE TITLE
Extrusion rate smoothing is wrong on infiil

### ISSUE THREAD

**Issue by vgdh** [SoftFever/OrcaSlicer#4635]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0-rc

### Operating System (OS)

Windows

### OS Version

win 10

### Printer

kingroon kp3s

### How to reproduce

1.  make cylinder
2. enable extrusion rate smoother
3. gyroid infill

### Actual results

on some layer it's not smoothing the extrusion rate on infiil start and on the other layer it does.
![1](https://github.com/SoftFever/OrcaSlicer/assets/15322782/11c8f38a-1f01-4507-b067-f6275cb9e307)
![2](https://github.com/SoftFever/OrcaSlicer/assets/15322782/150a54bd-9306-495c-a901-ac1ef67cc0a9)

### Expected results

smooth extrusion rate at infill path start on every layer.

### Project file & Debug log uploads

[Cylinder.zip](https://github.com/SoftFever/OrcaSlicer/files/14719826/Cylinder.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by igiannakas** [comment]
It depends on the travel distance between the end of the last extrusion and the start of the next one. If it is over a few mm it will consider the pressure equalised naturally hence no need to run the algorithm as the nozzle is at 0 pressure.

**Comment by vgdh** [comment]
> It depends on the travel distance between the end of the last extrusion and the start of the next one. If it is over a few mm it will consider the pressure equalised naturally hence no need to run the algorithm as the nozzle is at 0 pressure.
> 
> So this is a feature, not a bug.

So it will do zero to maximum pressure at infill start point. It not what pressure equalizer should do. 
In prusa slicer it works correctly and do it on every layer at any distance.

**Comment by vgdh** [comment]
prusa sliced
every extrusion part at start has some pressure equalized path.
![1](https://github.com/SoftFever/OrcaSlicer/assets/15322782/2bd10c20-ea56-499e-aa6e-0d7c8d8897d8)

**Comment by igiannakas** [comment]
It zeroes when:
1. There is a retraction
2. There is a travel above a certain minimum threshold

in both these cases there is no pressure in the nozzle so there is nothing to equalize. The prusa alpha release from a few days ago implements this as well.

**Comment by igiannakas** [comment]
You can read more here: https://github.com/prusa3d/PrusaSlicer/pull/9622

**Comment by vgdh** [comment]
> You can read more here: [prusa3d/PrusaSlicer#9622](https://github.com/prusa3d/PrusaSlicer/pull/9622)

Wow thank you for pointing that PR. Now it's clear why it's working that way!

> The main issue with existing code is not accounting for travel moves. You could travel move across whole build plate and pressure equalizer would still try to make a smooth transition from flow rates at each end. Extruder pressure drops to zero after a few mm of travel without extruding, and longer moves will retract on top of that. So it doesn't make sense to smooth flow between extrusions separated by a travel move more than a few mm.

**Comment by vgdh** [comment]
Feature, not a bug.
