### ISSUE TITLE
prime tower position

### ISSUE THREAD

**Issue by loutwice** [SoftFever/OrcaSlicer#4638]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

Windows

### OS Version

10

### Printer

Flsun v400

### How to reproduce

seems impossible to relocate prime tower on circular build plate only
https://github.com/SoftFever/OrcaSlicer/assets/7931460/9e51cd87-8326-427f-9883-d54e4c98d4fd

### Actual results

cannot change the prime tower position

### Expected results

be able to move the prime tower on cirtcular build plate

### Project file & Debug log uploads

[Uploading joker test.zip…]()

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by WimVDK** [comment]
Maybe that's related to an issue i reported 2 months ago https://github.com/SoftFever/OrcaSlicer/issues/3776

**Comment by loutwice** [comment]
bump @SoftFever

**Comment by WimVDK** [comment]
don't think the tower size has anything to do with that, you can modify that to a degree under prime tower settings

**Comment by loutwice** [comment]
@WimVDK  yup but same settings different behavior ...

**Comment by loutwice** [comment]
still cannot relocate prime tower so i cannot print ... is there a parameter to play with?
![image](https://github.com/SoftFever/OrcaSlicer/assets/7931460/cb455265-bf69-4315-964e-68b5501857dd)
