### ISSUE TITLE
SET_PRESSURE_ADVANCE command insert multiple times with MMU Print

### ISSUE THREAD

**Issue by abstractFlo** [SoftFever/OrcaSlicer#464]
**Describe the bug**
When I start an MMU print and look at the generated GCode, it has the instruction in it at each layer change that it sets the Pressure Advance. Although the filament was not changed. I think this is a bug. It's not really bad, I just noticed it when I looked in the mainsail console and saw that it was setting the command repeatedly.

**3mf File for This Bug**
Gcode and 3mf inside the zip file

**To Reproduce**
Slice the Project and look at generated gcode

**Expected behavior**
I think it would be good if it only executes the command when changing the filament and otherwise leaves everything as before.

**Screenshots**
![image](https://user-images.githubusercontent.com/4614586/224431302-4c14da8a-357c-488f-ac7d-e7ce11614b1a.png)

**Printer model**
Voron 2.4 250mm with 9 Slot ERCF

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10
 
 Studio Version Stable and Nightly

[3mf_and_gcode.zip](https://github.com/SoftFever/BambuStudio-SoftFever/files/10946208/3mf_and_gcode.zip)

**Comment by hliebscher** [comment]
if  printed with a purge tower, it is correct like this. In your model, there are 2 different filament ends with different PA values.  The slicer has to reset the value in every layer based on the filament, so there's no bug."

**Comment by abstractFlo** [comment]
but if i print like 25 layers with same filament, there is no need to set the PA on every layer change. I know, if i change the filament, setup the PA is correct. But not for Layers with the same filament
