### ISSUE TITLE
orcasliceropen stopped working in 2.0.0 beta

### ISSUE THREAD

**Issue by LordBoos** [SoftFever/OrcaSlicer#4645]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0 beta

### Operating System (OS)

Windows

### OS Version

Windows 11

### Additional system information

not relevant

### Printer

Bambulab X1C

### How to reproduce

1. Edit windows registry and register orcaslicer://open to open files in Orca Slicer
2. Open some link like the following (this one has expiration time, so it might not work anymore once someone reviews this issue, you can replace the link after file= to any stl or 3mf link): orcaslicer://open?file=https://makerworld.bblmw.com/makerworld/model/US6b22f37c2643f/55783278/instance/model.3mf?at=1711119246&exp=1711119546&key=8a5c6a43a335f986163b3f4357a44abc&uid=1577422717&name=BenchViseBuildPlate.3mf
3. Orca slicer opens with this error:
![image](https://github.com/SoftFever/OrcaSlicer/assets/939813/0130932d-3c4f-4aa6-bd93-329467a38142)

### Actual results

Error appears:
![image](https://github.com/SoftFever/OrcaSlicer/assets/939813/ed09576a-91d1-4335-8772-0a6651ebfc8f)

### Expected results

Model should be downloaded and loaded. Model downloads and loads correctly in 1.9.1.
There are errors in the attached log file.

### Project file & Debug log uploads

[debug_Thu_Mar_21_14_55_40_42880.log](https://github.com/SoftFever/OrcaSlicer/files/14724837/debug_Thu_Mar_21_14_55_40_42880.log)

### Checklist of files to include

- [X] Log file
- [x] Project file

**Comment by xtreye** [comment]
I seems to be having the same problem with 2.3.0
