### ISSUE TITLE
Custom names for the bed type plates.

### ISSUE THREAD

**Issue by vgdh** [SoftFever/OrcaSlicer#4655]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Here's the corrected version of your text:

Would it be cool to be able to use custom-named plate types? 
I personally want only two plates: Glass and PEI. 
The rest of the plates are useless for me personally. 

I think some of us have our own plates and may have more and different types like:
1. Spring Steel Sheet with PEI
2. Glass Build Plates
3. Polypropylene (PP)
4. Garolite Build Plates

Some even have several different glass plates and different bed mesh profiles for them in Klipper. 
If you can choose custom names, you can use them in Klipper macros. Automation and making it easier to print is good.

### Which printers will be beneficial to this feature?

Klipper

### Describe the solution you'd like

The structure may be inherit like.

- **Glass** (it would appear at all profiles as a plate name)
|---- **favorite glass** (doesn't apper at profiles but this will be sent to klipper as placeholder)
|---- **rough glass** (doesn't apper at profiles but this will be sent to klipper as placeholder)
- **PEI** (it would appear at all profiles as a plate name)
|---- (name isn't chosen so 'PEI' will be sent to klipper as placeholder)

**Comment by TexZeTech** [comment]
I too would like to see this added.

**Comment by driest** [comment]
As an interim solution I'd already be happy to rename the 4 pre-existing ones. That helps prevent mistakes when building custom g-code, as it's easy to forget that and then scrape your bed when you put in the actual "Engineering Plate", after using that slot for a POM plate with custom z-offset, for example.

**Comment by vgdh** [comment]
up

**Comment by AJolly** [comment]
This would be great

**Comment by RoBoT24-web** [comment]
This would be great

**Comment by GabrielMASU** [comment]
UP,UP,UP

**Comment by masterjuggler** [comment]
Are there any plans to implement this? I also have several different bed types that have nothing to do with bambu lab, and need to cross reference the names on a chart.

**Comment by DoctorWiz** [comment]
Ditto.
I have 6 different types of build plates.  Three of them correspond to the four predefined types, although I'm not happy with how they are named.  That leaves one useless predefined type I never use, and 3 more plate types I can't select (cuz they don't exist).

Can you at least tell me what .json file they are defined it, so I can edit it?

**Comment by DoctorWiz** [comment]
With the utmost gratitude and respect for all the wonderful developers that volunteer their time to this great project...   
... I also think this is a needed feature.  Build plates and their coatings is still an area of active research and development and new types are released often (admittedly, not all of them great).  And each printer manufacturer seems to have their own names for them.
I personally have: Smooth PEI, lightly textured PEI, heavily textured PEI, Epoxy, Cold, FR4/Garolite, Holographic (multiples), and even Glass.  And there are several sub-types for some of those.

**Comment by Rodamyot** [comment]
I would also love to have this feature. Personally, I have 4 types of texture in my plates and each requires a different Z offset depending on the type of filament.

**Comment by Franchester3D** [comment]
Another supporter of adding this. Current naming makes little sense to how I call them, just having the option to rename the current ones would be amazing.

**Comment by Catriks** [comment]
I would like to have this as well.

On some printers it takes very long to heat up the bed, up to 10 minutes, so you want to have a low temp setting for smaller prints that don't need much heat. Currently you have to manually change it every time, arbitrarily use random beds for each temperature or have two filament profiles for each different filament type - none very optimal. 

Being able to rename bed types would solve this. 

It would also be great being able to remove or hide unnecessary beds, I'm sure a lot of people only use two beds, like smooth and textured.

**Comment by Rusty-Danger** [comment]
Still looking for this addition.  Would make my offset selections so much easier

**Comment by kens96** [comment]
I support this idea and would love to see it implemented.
