### ISSUE TITLE
Option to disable the bed coordinates

### ISSUE THREAD

**Issue by ramosglauco** [SoftFever/OrcaSlicer#4666]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

It would be great to have an option to disable the bed's XYZ coordinates. These coordinates make it a bit difficult to fully visualize the model when a round bed is used. And also with the 3d Navigator view active, the coordinates on the bed become redundant. Thanks!

![image](https://github.com/SoftFever/OrcaSlicer/assets/88552877/720c6b8f-c790-4983-9ec8-5c9ebc589663)

### Which printers will be beneficial to this feature?

Marlin

### Describe the solution you'd like

There could be an option to disable it in the view option menu.

**Comment by githubber4ever** [comment]
This not only affects round beds but also all rectangular beds with centered origin in profiles like Flashforge 5M (Pro). So an easy way to (temporary) hide or disable coordinate system axes visualization would really be nice 👍
