### ISSUE TITLE
3D Navigator auto centering

### ISSUE THREAD

**Issue by ramosglauco** [SoftFever/OrcaSlicer#4667]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

It would be great if every time we select one of the 3D Navigator faces it automatically realigns the view to the center of the bed, as SolidWorks/Inventor does for example.

https://github.com/SoftFever/OrcaSlicer/assets/88552877/6ae96cfd-9197-4aa6-ae30-21d8884058f6

### Which printers will be beneficial to this feature?

Marlin

### Describe the solution you'd like

3D Navigator automatically realigns the view to the center of the bed.

**Comment by kylek29** [comment]
I'd say it should center to bed if there's no selected object, otherwise center on the object?
