### ISSUE TITLE
Please add profile for Creality Ender 3 S1 Plus

### ISSUE THREAD

**Issue by Gozania** [SoftFever/OrcaSlicer#4669]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

The entire S1 line has been added except for the often left out S1 Plus.

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

The entire S1 line has been added except for the often left out S1 Plus.

### Describe alternatives you've considered

1. I have modified a S1 Pro profile to have a print size of 300x300x300.

**Comment by cochcoder** [comment]
How well does the profile work when you edit the S1 Pro profile to have a print size of 300x300x300? Are there any values that should be changed for speed, acceleration, retraction, etc?

**Comment by vgdh** [comment]
If the mechanical side of the printers is the same. You should be ok.

**Comment by cochcoder** [comment]
@vgdh Let me know if PR #4674 works for you, let me know if you need a download link

**Comment by Gozania** [comment]
> How well does the profile work when you edit the S1 Pro profile to have a print size of 300x300x300? Are there any values that should be changed for speed, acceleration, retraction, etc?

I havent printed anything with orca yet.  Still in the process of moving print profiles & filaments over to Orca from Prusa.  I know there is a script that does this, but I'm hesitant due to my lack of CLI skills.  If something goes wrong, I wont know how to recover.

**Comment by cochcoder** [comment]
What is the script called/located? Also if you can run a test print with the PR I created to make sure that everything works, that would be awesome!

**Comment by Gozania** [comment]
> @vgdh @Gozania Let me know if PR #4674 works for you, let me know if you need a download link

I just tried to import the creality.json file, but it did not take.
<img width="563" alt="Screenshot 2024-03-24 103756" src="https://github.com/SoftFever/OrcaSlicer/assets/83924000/d8a580e6-a9d9-4640-8dcf-db7eeaa25c65">


![Screenshot 2024-03-24 103821](https://github.com/SoftFever/OrcaSlicer/assets/83924000/2db8f25e-3c2c-41e5-a4b2-772f6a0a7bfe)

**Comment by Gozania** [comment]
https://github.com/SoftFever/OrcaSlicer/discussions/1636

I wonder why softfever decided on json rather than .ini which is what Prusa uses...

________________________________

**Comment by cochcoder** [comment]
> I just tried to import the creality.json file, but it did not take.

That won't work as there are 14 other files that were added/changed, here are a few download links for what main would be once merged: [Windows portable](https://github.com/cochcoder/OrcaSlicer/actions/runs/8407801159/artifacts/1353391984), [Linux Appimage](https://github.com/cochcoder/OrcaSlicer/actions/runs/8407801159/artifacts/1353390677), [Mac Arm](https://github.com/cochcoder/OrcaSlicer/actions/runs/8407801159/artifacts/1353373818), and [Mac x64](https://github.com/cochcoder/OrcaSlicer/actions/runs/8407801159/artifacts/1353396764)

**Comment by Gozania** [comment]
Not quite I understand what ya mean by "once main would be once merged"  Please forgive the ignorance, I'm just a roughneck who enjoys CNC & lasers....  Do you mean if I am on the beta version instead of 1.9.1 my printer will be there?  I poked around in the windows mobile zip & found the S1 Plus 0.4 Json and tried to import that, but still no dice.  Same error window as before.

I do appreciate ya trying to help me out.

**Comment by cochcoder** [comment]
Because of the way that the program is setup I am 98% sure that you can't copy the .json file as you would have to also compile the software. What you need to do is to extract the Windows portable.zip and run orcaslicer.exe, which should show the Ender-3 S1 Plus. I don't recommend using this version of OrcaSlicer on a day to day biases due to still being developed. You'll see the Ender-3 S1 Plus in the stable release once that comes out and my PR has been merged.

**Comment by Gozania** [comment]
Gotcha, so if I wanted to see the printer now, I would just run the portable app through a "container" (forgive my incorrect verbage), until the stable release comes out.

I think I will just wait a while until things are ironed out & there is also a native way to simply import settings from Prusa directly into orca.  I tried that script I mentioned with zero success.  All my installations are in default locations, so dont understand nor skilled enough to know why it failed.

Will continue to use prusa until I am really bored & actually have time for the monotonous task of transferring all my settings manually to orca.

Hopefully softfever can find some sort of a solution to transfer settings via a few simple clicks for non-cli/git boneheads like myself.

Again, thank you for all your help!
________________________________

**Comment by cochcoder** [comment]
> Gotcha, so if I wanted to see the printer now, I would just run the portable app through a "container"

Yes, that is correct

> Will continue to use prusa

That is fine, however if you or @vgdh can do a test print with this new profile that would be greatly appreciated so that I can fix any simple issues that might arise when you or someone else uses this profile.

**Comment by cochcoder** [comment]
I changed a few things: [Windows portable](https://github.com/cochcoder/OrcaSlicer/actions/runs/8411678737/artifacts/1353945086)

**Comment by Gozania** [comment]
For whatever reason it was zipped inside of a zip, but I did get the latest version you sent working.  I'm moving over my "fast" profile from prusa to orca manually, will slice a benchy and let ya know how it turns out.

Side note... I only checked the box for .4 nozzle, but it added all the nozzle sizes.  Also the bed is model & texture is off.  It is looking like a standard S1/E3v2 rather than a S1 Plus.  The bed on the S1 Plus is exactly like this & is PC than PEI  https://www.amazon.com/Ender-Frosted-Magnetic-Flexible-310x315mm/dp/B0B8HDRSYF/ref=sr_1_1?crid=1XEAG8YC8NGSW&dib=eyJ2IjoiMSJ9.mXQZtPbjqthoaGM6ok7ZoAxkmKsWXODYOe_bMxPeWLuDKfmu_9xMQmwTyM1FeBJpPcpfJ-XkCAkvSnRveOjrkkxV4CeYUJQ3BadtZ1jo0xMa3BYtiaoAPm0ZylyJyUmlTXIQSZXMvC4MEEONhuaKih-5t8ifR3eXaaKx8X_6RCuY-bcIm2oucr6AVd1L3mpjTvJd0Rsd1FKRIrFA4sdrmTtULWQxX5PI3ajJrfAus-c.SYd5tWdRJD-lODMaXqLhtuFgTtEQg7Xh0cxEh-xr5_w&dib_tag=se&keywords=s1+plus+bed&qid=1711324329&sprefix=s1+plus+be%2Caps%2C176&sr=8-1

It would be even better if you a 300x300 border can be added outside the bed grid to show limits.
________________________________

**Comment by cochcoder** [comment]
> Side note... I only checked the box for .4 nozzle, but it added all the nozzle sizes.  Also the bed is model & texture is off.  It is looking like a standard S1/E3v2 rather than a S1 Plus.  The bed on the S1 Plus is exactly like this & is PC than PEI  https://www.amazon.com/Ender-Frosted-Magnetic-Flexible-310x315mm/dp/B0B8HDRSYF/ref=sr_1_1?crid=1XEAG8YC8NGSW&dib=eyJ2IjoiMSJ9.mXQZtPbjqthoaGM6ok7ZoAxkmKsWXODYOe_bMxPeWLuDKfmu_9xMQmwTyM1FeBJpPcpfJ-XkCAkvSnRveOjrkkxV4CeYUJQ3BadtZ1jo0xMa3BYtiaoAPm0ZylyJyUmlTXIQSZXMvC4MEEONhuaKih-5t8ifR3eXaaKx8X_6RCuY-bcIm2oucr6AVd1L3mpjTvJd0Rsd1FKRIrFA4sdrmTtULWQxX5PI3ajJrfAus-c.SYd5tWdRJD-lODMaXqLhtuFgTtEQg7Xh0cxEh-xr5_w&dib_tag=se&keywords=s1+plus+bed&qid=1711324329&sprefix=s1+plus+be%2Caps%2C176&sr=8-1

Thx, I'll look into it, I think I fixed the issue with all four nozzles being added with only one chosen. 

> It would be even better if you a 300x300 border can be added outside the bed grid to show limits.

Do you mean fixing the bed model/texture?

**Comment by Gozania** [comment]
Yes the bed model/texture.  Prusa used to have an exact replica, but dissapeared somehow.   I made my own less desirable one using a CR10 model & ender 3 texture.  Does the job, but Prusa's initial one was much better.

________________________________

**Comment by cochcoder** [comment]
> Yes the bed model/texture. Prusa used to have an exact replica, but dissapeared somehow. I made my own less desirable one using a CR10 model & ender 3 texture. Does the job, but Prusa's initial one was much better.

How does the Ender-3 V3 SE bed model/texture look? 
![Screenshot_20240324_203639](https://github.com/SoftFever/OrcaSlicer/assets/103969142/f6c28f70-9618-4faf-a3fb-ef86c777c7fe)

**Comment by Gozania** [comment]
LOVE IT!

I'm having trouble navigating.  I am searching for how to modify the output of my gcode.  Also is there a way I can send the gcode to my printer directly into a specific directory but not print yet?  This was easily done through PS.
________________________________

**Comment by Gozania** [comment]
Looking for this....
________________________________

**Comment by Gozania** [comment]
FOUND IT!
________________________________

**Comment by Gozania** [comment]
Now this is the last thing I am after before I send it to be printed....


________________________________

**Comment by cochcoder** [comment]
I am currently compiling a new version of the software and hopefully, it fixes all the issues you found so far

**Comment by Gozania** [comment]
I found the output section and I see the upload section just like PS...  However I did have an issue with just copying my PS output string to Orca.  It didnt work and thats howcome I was pestering about the directory.   The output string I use in PS is as follows.

{input_filename_base}_{print_time}_${total_cost}_{total_weight}g_{temperature[0]}C_{filament_type[0]}_{printer_model}.gcode

Where did my original string go wrong in orca?
________________________________

**Comment by cochcoder** [comment]
> Where did my original string go wrong in orca?

It may be the ".gcode" string at the end, I don't know much when it comes to that area of the slicer, I recommend asking around if you don't find a solution. Also, the Bed Mesh leveling may not happen when you start a print as I just found that issue and it takes around 40 minutes for the code to recompile.

**Comment by Gozania** [comment]
TY for letting me know that, allthough I use BED_MESH_PROFILE LOAD=default in my start gcode.

First print didnt stick and failed right away.  I also noticed movement is much slower compared to the settings I have in PS which I copied over.
________________________________

**Comment by Gozania** [comment]
One thing that would be MASSIVELY helpful is a search function like PS.  It comes in soooo handy to find the setting you want.
________________________________

**Comment by cochcoder** [comment]
> One thing that would be MASSIVELY helpful is a search function like PS. It comes in soooo handy to find the setting you want.

Orca Slicer does have a search function, although it is broken up into three different setting locations. I'll keep it in mind though, might add an overall search function if I get time ;)

**Comment by Gozania** [comment]
Yeah a simple magnifying glass in the tool bar, totally sufficient.

I think I found my speed issues...  It seems you have to have a higher speed rate in machine limits rather than just telling the slicer to ignore them.

Reslicing, re-doing z-offset and will see what happens.
________________________________

**Comment by cochcoder** [comment]
> First print didnt stick and failed right away.  I also noticed movement is much slower compared to the settings I have in PS which I copied over. 

If you have any changes to suggest making to the profile, please let me know! (As long as they are not too exorbitant (the majority would be fine with them))

**Comment by Gozania** [comment]
I should have mentioned it earlier.... I'm running it on klipper and a sonic pad, since I purchased it a year ago, my settings wouldnt be ideal for a stock deployment.
________________________________

**Comment by cochcoder** [comment]
> I think I found my speed issues... It seems you have to have a higher speed rate in machine limits rather than just telling the slicer to ignore them. 

I'll look into it when I can as I just copied the S1 Pro's profiles 

> I should have mentioned it earlier.... I'm running it on klipper and a sonic pad, since I purchased it a year ago, my settings wouldnt be ideal for a stock deployment.

Thank you for mentioning this! This does limit the settings that you can reliably give feedback on, however, speed and acceleration are on of the categories that you can give feedback on for the stock deployment

**Comment by Gozania** [comment]
I can surely do that!  The profiles I use are the same slightly modified ones that creality provided with the initial launch of the sonic pad.  They are pretty much stock other than changing layer heights UP .01 to make it an even number.  I also swapped the accelertations between their normal and fast profiles as it looked like they had them swapped... A slower accel was present on the faster profile, i.e. 1500 accel was on the fast and 2500 accel was on the normal.

I have attached a copy of creality's profiles for the S1 Line & Ender3v2.  Please keep in mind the accel swapping I had to do earlier when implementing them....



________________________________

**Comment by Gozania** [comment]
One thing I strongly dislike is my maximum acceleration for travel in machine limits is capped to 1000 mms.  I have no issues with this being 5k mms in PS.
________________________________

**Comment by cochcoder** [comment]
> I have attached a copy of creality's profiles for the S1 Line & Ender3v2

This copy didn't come through for whatever reason, also I just finished compiling the newest [version](https://github.com/cochcoder/OrcaSlicer/actions/runs/8413560744/artifacts/1354256341)

**Comment by Gozania** [comment]
odd...  take 2

Another thing...  I love the way Orcas thumbnails look over PS, however it would be nice if the thumbnail was the same color as selected for the filament.   Or is there a way to customize this for each print before uploaded?
________________________________

**Comment by cochcoder** [comment]
> it would be nice if the thumbnail was the same color as selected for the filament. Or is there a way to customize this for each print before uploaded?

I haven't seen a way for this to be customized, however, I don't use thumbnails so take it with a hundred-pound bag of salt. You may want to look around for a existing issue or create a new issue for this

**Comment by Gozania** [comment]
Copy....

I have a benchy going with my speed settings for klipper.  If youd like I can try to print one just using a stock profile provided.
________________________________

**Comment by cochcoder** [comment]
> Copy....
> 
> 
> 
> I have a benchy going with my speed settings for klipper.  If youd like I can try to print one just using a stock profile provided.


I'd like to make a few more changes to the profile tomorrow, before you do a test print with stock settings

**Comment by Gozania** [comment]
Roger that...

Benchy is looking pretty good.  However I do see my accell & deccel is being capped by orca.  I dont do anything crazy, the max I go is 5K accel & 2500 for deccel.  Orca is capping me at 2.5k accel & 750 decell.  Is there a way to overcome this?  My machine runs the latter no problems at all.
________________________________

**Comment by cochcoder** [comment]
> Orca is capping me at 2.5k accel & 750 decell. Is there a way to overcome this?

In the printer's settings (printer profile) you can edit the max motion values, like acceleration. Then in the print profiles (Draft, Optimal, etc) you can change those motion values to whatever you want, as long as it is below the printer's max

**Comment by cochcoder** [comment]
> My machine runs the latter no problems at all.

Great! Is the issue with the bed model/texture fixed as well?

**Comment by Gozania** [comment]
Oh I havent used the newst compilation.  I am running on what ya initially gave me when I said it was zipped within a zip.
________________________________

**Comment by cochcoder** [comment]
Sorry I got a bit confused

**Comment by Gozania** [comment]
No worries!
      In the printer's settings (printer profile) you can edit the max motion values, like acceleration. Then in the print profiles (Draft, Optimal, etc) you can change those motion values to whatever you want, as long as it is below the printer's max

I have everything edited the way I want EXCEPT for travel, which it wont let me edit.
I would love travel to be 5K which is what I travel at.
________________________________

**Comment by Gozania** [comment]
First orca benchy came out looking great!
________________________________

**Comment by Gozania** [comment]
So new discovery... My PS Fast profile uses The same printing accell & decel that orca was showing me.  However I am indeed being capped by Orca ONLY for my travel speed which I would like to be 5K (I have no issues) as I do in PS.  The last screen shot I showed you has only travel speed greyed out & un-editable.
________________________________

**Comment by Gozania** [comment]
Can you send me a link to the latest version you have compiled?  I tried to export my configs and the program crashes.

I however was succesfull importing my filaments into Orca via that script.
________________________________

**Comment by Gozania** [comment]
After running that perl script, all my filament colors from PS were added into Orca & the thumbnails now reflect the assigned color!
________________________________

**Comment by cochcoder** [comment]
Here is the new [version](https://github.com/cochcoder/OrcaSlicer/actions/runs/8424675278/artifacts/1356791088), I changed the max travel acceleration to 5,000 and the default print profiles should be ready for testing!

**Comment by Gozania** [comment]
TY!  I'm printing some parts at the moment, so machine is tied up.  I tried adaptive mesh, probed fine but nozzle dragged across bed after purge I know adaptive purge is available, but not sure if I can get it on Sonic Pad as crapality likes to lock down open source software for their own use.

After I am done with these parts (will take a while) I will delete the old version and download/extract this new build and give it a go.  Side note, I am not getting the modified bed yet after installing a different version you provided.

Is it possible to add new beds?  Or does the bed get reset during every project.  Ideally I would like to have my S1 Plus be smooth PC/PEI & My Ender3v2 have a Textured PEI & Smooth PEI each saved & named.  Forgive the ignorance still learning how to navigate.  I also found the search tool in the print settings section.
________________________________

**Comment by cochcoder** [comment]
> Is it possible to add new beds?  Or does the bed get reset during every project.  

Do you mean this? 
![Screenshot_20240325_171303](https://github.com/SoftFever/OrcaSlicer/assets/103969142/adcfbb8a-21a1-412a-a08a-a708e6a5016a)

> Ideally I would like to have my S1 Plus be smooth PC/PEI & My Ender3v2 have a Textured PEI & Smooth PEI each saved & named.

Do you mean that you want different bed textures? I'm not sure what you're asking for. 

> Forgive the ignorance still learning how to navigate.

Don't worry about it! If you need a visual guide, [Teaching Tech](https://youtu.be/cquTCpz1V74?si=RpU6gzZ-OAsrWugd) made a fantastic video walking through Orca Slicer and its advance features

**Comment by Gozania** [comment]
YES!
      "Do you mean this?
      Screenshot_20240325_171303.png (view on web)<https://github.com/SoftFever/OrcaSlicer/assets/103969142/adcfbb8a-21a1-412a-a08a-a708e6a5016a>"

Yes, only for one of my machines since it has a dual sided bed and I do use both sides.
      "Do you mean that you want different bed textures? I'm not sure what you're asking for."

TY for that!  Gonna give that a watch while this print is going!
      "Don't worry about it! If you need a visual guide, Teaching Tech<https://youtu.be/cquTCpz1V74?si=RpU6gzZ-OAsrWugd> made a fantastic video walking through Orca Slicer and its advance features" 
________________________________

**Comment by cochcoder** [comment]
@Gozania  Just letting you know that I am making a small change in the profiles that could greatly reduce print times (depending on the model size/infill needed), so you may want to wait 40 minutes before doing another test print if you were about to do one

**Comment by Gozania** [comment]
LOL!!!!   TY for telling me!  I just installed the latest you provided & tested out the export function before removing my S1 Plus entirely & it still crashes right after I click export configs.
________________________________

**Comment by cochcoder** [comment]
> Yes, only for one of my machines since it has a dual sided bed and I do use both sides.

If you go into your Printer's settings you can enable multiple bed types and then you can change the bed type on the main page, hope this helps!

> I just installed the latest you provided & tested out the export function before removing my S1 Plus entirely

Talk about timing! 

> it still crashes right after I click export configs

Weird, I'll keep a eye on that

**Comment by Gozania** [comment]
I'll try this with your next compile

      If you go into your Printer's settings you can enable multiple bed types and then you can change the bed type on the main page, hope this helps!

Side note, would be awesome if you added a couple more common filament manufacturer profiles i.e. Proto Pasta  & Hatchbox offerings.

________________________________

**Comment by cochcoder** [comment]
> Side note, would be awesome if you added a couple more common filament manufacturer profiles i.e. Proto Pasta  & Hatchbox offerings.

Make a new issue if there isn't one, link it here, and I'll look into it when I get time

**Comment by Gozania** [comment]
Will do!  Again, TY for that video.  I now understand how the plates work.
________________________________

**Comment by cochcoder** [comment]
> Again, TY for that video.  I now understand how the plates work.

No problem, it is my pleasure!

**Comment by cochcoder** [comment]
Thank you for waiting, the new download with combine infill enabled by default and added draft profiles is [here](https://github.com/cochcoder/OrcaSlicer/actions/runs/8428192242/artifacts/1357594305). Please let me know what the results are and if you know of any changes that should be made to the default profiles. Thank you again for your testing!

**Comment by Gozania** [comment]
Will do!  I will extract it & run a couple of benchies with your stock profile.  I will be concentrating on quality rather than speed since its with marlin in mind 🙂
________________________________

**Comment by Gozania** [comment]
I'm still printing, but intalled the latest version and tested exporting right away.  Still crashes.  No dialog box, just crash.  Also not sure if you implemented the bed design you showed me, but that hasnt transferred over either.

I also Re added a S1 Plus with only .04 & again all were added.  Havent gotten to checking the profiles yet.
________________________________

**Comment by cochcoder** [comment]
Did you extract the zip to an entirely new folder? If not, that may be why, as you could be accidentally combining the old and new version

**Comment by Gozania** [comment]
That may be it.  I'll put it in a new folder and check it tmw morning.  I'll also check both the stock profiles afterwards.
________________________________

**Comment by Gozania** [comment]
That didnt help.  Tried a new folder & tried to drag the orca slicer folder directly to root of my main ssd.  Bed issue remains aswell as export issue.

Will test the stock profiles in the morning.
________________________________

**Comment by Gozania** [comment]
I thought this may be a bit helpful with the extruder section for the S1 Plus for the machine profile.  This was in the box when I recieved my printer & is also actually perfect for a feeler gauge for Z offsets.

I run these retract & detract speed settings no problem however I set my retract to 0.4 as per the klipper cura profile Creality provided (The creality.zip I sent you).

Will be printing with the stock 0.2 & 0.16 profiles shortly.


________________________________

**Comment by cochcoder** [comment]
I hope to have a new version that will fix the bed issues and potentially the export crashes by the end of today. Also, I haven't been able to replicate the issue of all the nozzle sizes being added when only .4 is chosen, hopefully, this resolves itself.

**Comment by Gozania** [comment]
Also, I figured it may be worth a mention, all the while testing new RC's I have had 1.9 full/stable installed.  Will this cause any issues?
________________________________

**Comment by cochcoder** [comment]
It shouldn't as you are using a portable version of Orca Slicer, while I haven't used Windows in a couple of years, it shouldn't affect the main installation.

**Comment by cochcoder** [comment]
Linux has come a long way in the past few years, I can't wait for when it gets to a place where you don't need the terminal for almost every task, even if it is the most efficient way of doing things

**Comment by Gozania** [comment]
I love that its soooo lean resource wise.  Love before you do potentionlly harmful things you have to sudo. It would be amazing if it wasnt heavily terminal based & more programs were developed for it.  I'd jump ship.

________________________________

**Comment by Gozania** [comment]
About to slice and print a benchy using totally stock settings in the .02 profile.

________________________________

**Comment by cochcoder** [comment]
Ok, I am not currently changing anything in the profiles so you're good to go

**Comment by Gozania** [comment]
Correction, I am gonna use stock machine settings except for retract and detract speed as this is what creality suggests.  I have had ZERO issues with PLA.  Also going to be printing with black elegoo PLA.


________________________________

**Comment by cochcoder** [comment]
What are the retract and detract speeds you're using? I'll implament them into the profiles (at least a average between the two numbers)

**Comment by cochcoder** [comment]
I am going to try and use 45/45 speed and 0.4 retraction length in all of the profiles. (I'm doing this as making a new profile for every filament type just for this printer is warrented in my opionion for only minor changes in retraction)

**Comment by cochcoder** [comment]
Do you think that 45/45 speed will be ok for PLA, as it usally is 40/40?

**Comment by Gozania** [comment]
Shouldnt cause any issues. IMO.  Also the profiles I just recently sent, it appears they fixed the acceleraton swaps from normal to fast.   They are as I use them, except for travel accel, which I use 5K for and have no issues.
________________________________

**Comment by Gozania** [comment]
I can reslice the benchy and print stock, but with 45 if youd like?
________________________________

**Comment by cochcoder** [comment]
> I can reslice the benchy and print stock, but with 45 if youd like?

That would be helpful if you don't mind, you can cancle your current print if you want to.

**Comment by Gozania** [comment]
First layers going down great!  Not really a fan of Z-hop being enabled by default, but thats preference.

ITS SOOOOO SLOW!!!!!  LOL
________________________________

**Comment by cochcoder** [comment]
The intail layer speed is 35% of the total speed

**Comment by Gozania** [comment]
Sure thing!  I'll cancel and make it 45 and re print using this .02 profile.

Side note, I am using pressure advance as with klipper its kinda needed.
________________________________

**Comment by Gozania** [comment]
Oh i know... just messing about....

First layers of 45 0.2 lookin good.
________________________________

**Comment by cochcoder** [comment]
Sounds good, let me know how it turns out!

**Comment by cochcoder** [comment]
FYI, it seems that I can't add retraction, detraction, and retraction length in printer profiles/processes. You don't need to restart the print, we'll just need to keep that in mind.

**Comment by Gozania** [comment]
First benchy just finished.  Looks great other than some minor stringing that is filament based. (Elegoo's pla isnt pure pla something else in there.)  Rear name tag is actually legible in sunlight.

Gonna print the 0.16 with some tried and true hatchbox.  Will let you know how it comes out.

________________________________

**Comment by Gozania** [comment]
Ok, so I'm a good portion through the 0.16 benchy with good filament.  I am still getting stringing (I RARELY get stringing in any of my prints.)  I will put money (im not a betting man.) on its happening due to z-hop being enabled natively.  I dont normally use z-hop unless I am trying to avoid dragging across a top somewhere in the print.

My personal suggestion.... Keep Z-hop off by default.  Use a check box to enable, keeping distance fields.  Also add an addition check box to only Z-hop on top surfaces. (Thats actually my only application for zhop is to avoid nozzle drag on a specific surface.

________________________________

**Comment by cochcoder** [comment]
Do you want z-hop to only work on the top surfaces?

**Comment by Gozania** [comment]
Yes on an as needed basis.

I usually keep it turned off for the most part, however there are times when I do need to enable it.  I usually set an above & below, but a simple check box for top surfaces only (regardless of layer height i.e. 3 separate tops at different heights would all have zhop on for that layer, but then turned off after that layer has been cleared by the nozzle.)
________________________________

**Comment by Gozania** [comment]
However I do feel it should remain OFF by default.
________________________________

**Comment by cochcoder** [comment]
> I usually keep it turned off for the most part, however there are times when I do need to enable it.  I usually set an above & below, but a simple check box for top surfaces only (regardless of layer height i.e. 3 separate tops at different heights would all have zhop on for that layer, but then turned off after that layer has been cleared by the nozzle.)


I'll add it into the profile, also there is a drop down checkbox in the main printer profile that allows you to change were z-hop is used.

**Comment by Gozania** [comment]
About 10mins left on the 2nd benchy...
________________________________

**Comment by cochcoder** [comment]
> However I do feel it should remain OFF by default.

I'll do that instead

**Comment by Gozania** [comment]
Benchy is done, other than the forementioned issues.  The print turned out great!  Should give a newb a great baseline and able to get a quality print straight away without tweeking anything.

My only MAJOR gripe thus far is that I am unable to edit my travel acceleration to my desired rate.  Its kinda like, its my machine let me do what I want especially if its within machine limits.

________________________________

**Comment by cochcoder** [comment]
> My only MAJOR gripe thus far is that I am unable to edit my travel acceleration to my desired rate.  Its kinda like, its my machine let me do what I want especially if its within machine limits.

So, to change your machine's max travel acceleration in the slicer, you need to have Marlin 2 on your printer. However, as you have Klipper installed, you need to make sure that your G-Code flavor is Klipper and you then can edit the travel acceleration under the speed tab once you set the value of "Normal Printing" acceleration. Klipper handles the maximum acceleration in the printer.cfg file.

**Comment by cochcoder** [comment]
> Benchy is done, other than the forementioned issues.  The print turned out great!  Should give a newb a great baseline and able to get a quality print straight away without tweeking anything.

Great! I should have a new version that I can give you tomorrow before I mark the PR as ready to be merged. This new version should change retraction/detraction speed, and retraction length, and hopefully disable z_hop. I'll work with SoftFever or someone else to fix the weird bed texture/model issues.

**Comment by Gozania** [comment]
I did have klipper flavor selected as marlin would give me annoying errors in the console & well I am flashed to klipper.  Also in my printer.cfg my max accel is 5k.

My max print limit is 2.5K, however I want to travel at 5k.  Orca does not allow me to do this and caps my speeds... Prusa Does allow it right off the bat.

Upon your suggestion I switched to marlin2, entered 5K, then switched back to klipper and it seems to have stuck.

Im currently messing with my printer.cfg after installing new parts so machine will be down for a bit.  I just wanted to get those 2 benchies done for you so you can get a profile in place for stock users.
________________________________

**Comment by Gozania** [comment]
One last bug I did notice... in the device area, If I went full screen cam mode I could not get it normal size again either by clicking the screen arrow icon (dunno what its called) or by pressing esc.  I only got out of it by clicking my klipper logo.
________________________________

**Comment by cochcoder** [comment]
> One last bug I did notice... in the device area, If I went full screen cam mode I could not get it normal size again either by clicking the screen arrow icon (dunno what its called) or by pressing esc. I only got out of it by clicking my klipper logo.

Strange, hopefully, this gets fixed soon. 

Let me know if you still get the error of all nozzle versions being added when you only select one in this new [version](https://github.com/cochcoder/OrcaSlicer/actions/runs/8446088886/artifacts/1361693771)

**Comment by cochcoder** [comment]
I think that'll be best to limit any possible issues, make sure to make a backup of any profiles you made so they don't get lost.

**Comment by Gozania** [comment]
That the thing... I CANT!!!! remember my export bug I was having? LOL
________________________________

**Comment by Gozania** [comment]
I can copy/replace the file if you can provide a path.
________________________________

**Comment by cochcoder** [comment]
Oh yea, lol, you can still take pictures if that would help you. The export bug should hopefully be fixed before the stable release of 2.0

**Comment by cochcoder** [comment]
> I can copy/replace the file if you can provide a path.

I don't recommend that as when ever I tried to do that the program ended up bugging out

**Comment by Gozania** [comment]
Copy....  Screenshots it is then I guess....
________________________________

**Comment by Gozania** [comment]
Great news upon opening it up.... The bed shape has now changed!  However there is a weird step like artifact in the upper left...

My printer profile im not worried about loosing as I can re enter that from memory...  Its the Print profiles (layers, speed, strenghth etc) that would suck to have to re enter.  Should I screenshot/remove those as well before re-adding the printer?
________________________________

**Comment by cochcoder** [comment]
If they are based off the profiles that are being worked on, then yes. As you'll need to remove those profiles, which will most likely remove anything built off of them, before extracting and trying the new version.

**Comment by cochcoder** [comment]
> However there is a weird step like artifact in the upper left

That is part of the original model  that I sized up for some reason. It shouldn't be noticeable once I get the texture working.

**Comment by Gozania** [comment]
😭 Why wont you work export?!?!?!
________________________________

**Comment by cochcoder** [comment]
The unfortunate ordeals of a development build 😔

**Comment by Gozania** [comment]
I'm gonna be stepping away for a bit as I have to deal with some credit card fraud commited against me....  Be back in touch in a bit.
________________________________

**Comment by cochcoder** [comment]
> I'm gonna be stepping away for a bit as I have to deal with some credit card fraud commited against me.... Be back in touch in a bit.

Take all the time you need! Get that money!

**Comment by Gozania** [comment]
Ii'm back....

Unfortunately no dice with the single nozzle.

This was my process...  Delete all printers & print profiles for the S1 Plus (I left my Ender 3 V2 installed as all I have done with it is connect to moonraker its totally stock settings other than connection and a 230mm height).  closed the program.  Deleted the entire orca folder.  Created a new folder on my C drive rather than D.

Unpacked the archive in new folder.  Executed the program went to add the S1 Plus 0.4 nozzle and once again all nozzle sizes appeared in the pulldown.

I was able to however Create a new machine using creality vendor and s1 plus model using a 0.4 nozzle.  I was also able to load the S1plusbed.stl to get the bed shape. (Adding a S1plus normally also produces the correct bed shape.) However regardless, the SVG texture is not showing up on top of the bed surface, but rather the bottom of the bed.
________________________________

**Comment by cochcoder** [comment]
Ok, I think I fixed all the remaining issues. It should be ready to merge after I do one last check! Thank you for all of your help!

**Comment by Gozania** [comment]
Awesome!  Glad I could lend a hand in development of software I will surely use.

________________________________
