### ISSUE TITLE
Slicer doesn't change bed temperature for upper layers

### ISSUE THREAD

**Issue by vgdh** [SoftFever/OrcaSlicer#4676]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1 dev

### Operating System (OS)

Windows

### OS Version

win 10

### Printer

kingroon kp3s

### How to reproduce

make two objects with different colors
slice

### Actual results

in the gcode absent change bed temperature gcode after the first layer done.

### Expected results

change bed temp for other layers

### Project file & Debug log uploads

[project.zip](https://github.com/SoftFever/OrcaSlicer/files/14735136/Tmp.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by kayboy-bebop** [comment]
Replicated in 2.0rc Linux X64 build
