### ISSUE TITLE
Bad way to calculate internal bridge flow

### ISSUE THREAD

**Issue by TheTesla** [SoftFever/OrcaSlicer#4683]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0-rc (and older versions)

### Operating System (OS)

Linux

### OS Version

Ubuntu 23.10

### Additional system information

Lenovo Thinkpad p14s Gen3 Intel/Nvidia

### Printer

Creality K1

### How to reproduce

1. Load model without external bridges, but internal bridges
2. Slice model with some default settings
3. check the calculated amount of filament used for the internal bridges
4. change the "Bridge flow ratio"
5. slice again
6. check the calculated amount of filament used for the internal bridge again

### Actual results

The amount of filament used for the internal bridges depends on the "Bridge flow ratio".

### Expected results

The amount of filament for the internal bridges should be the same, because it should only depend on "Internal bridge flow ratio"
![Bildschirmfoto vom 2024-03-24 16-11-00](https://github.com/SoftFever/OrcaSlicer/assets/2584345/f405ce2e-8826-4f8e-ba81-1bb7689a4bb0)
![Bildschirmfoto vom 2024-03-24 16-10-28](https://github.com/SoftFever/OrcaSlicer/assets/2584345/fc018504-d168-4e96-ad5e-866c07be9792)

### Project file & Debug log uploads

[bugbridge.zip](https://github.com/SoftFever/OrcaSlicer/files/14735891/bugbridge.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Anything else?

The "Bridging" settings are implemented in a bad way. The parameter "Internal Bridge flow ratio" is not the only parameter influencing the internal bridge flow ratio. Actually, it is the product of "Bridge flow ratio" and "Internal Bridge flow ratio". This should be independent. There should be an "Internal bridge flow ratio" and an "External bridge flow ratio" parameter.

The multiplication approach is very bad, because the values are limited. Currently, the "Internal bridge flow ratio" can be set at most to 2. That means, if the "Bridge flow ratio" is below 0.5, because external bridges should have this value, there is no way to get the target internal bridge flow ration to 1.

**Comment by igiannakas** [comment]
I agree that there is some room for improvement there. Basically the internal bridge flow is a multiplier over the "bridge flow". So say if you set bridge flow to 2, and set internal bridge flow to 0.5, it means you get 1.0 internal bridge flow.

@SoftFever something that we may need to re-work to make the two features work a bit better for 2.1
