### ISSUE TITLE
Can not open on Mac.  Says the file is damaged.  Have tried all versions. on a Mac Studio running Ventura

### ISSUE THREAD

**Issue by umpmanjoe** [SoftFever/OrcaSlicer#469]
**Describe the bug**

**3mf File for This Bug**
If it is related to slicing, please append the 3mf file. It could be extremely helpful to solve the issue.

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**

**Printer model**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Windows]

**Comment by thewildmage** [comment]
This looks like a duplicate of #427. There's a [comment on that issue](https://github.com/SoftFever/OrcaSlicer/issues/427#issuecomment-1463891503) with a workaround that I think will help here.

**Comment by SoftFever** [comment]
duplicated
