### ISSUE TITLE
Custom notification - at layer pause (Bambu Lab)

### ISSUE THREAD

**Issue by tlhintoq** [SoftFever/OrcaSlicer#4695]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Not related to a bug

### Which printers will be beneficial to this feature?

Others

### Describe the solution you'd like

Bambu Lab machines like the X1 Carbon or P1P will raise a notification from the printer to the app on your phone.  So you get an alert like "Job completed Successfully" or "AMS failed to retract material" etc.

It would be great if we could get a message at layer pause, and thus the app on the user's phone would ping them that the machine had paused and they should come do whatever is they need to do.

![image](https://github.com/SoftFever/OrcaSlicer/assets/11351506/9dfa63d0-c225-4c0a-8f00-d41a5fa3bc56)

**Comment by kylek29** [comment]
This would require firmware changes by BambuLab to implement a custom GCode that triggers their notification function.

**Comment by tlhintoq** [comment]
Bot nudge.
