### ISSUE TITLE
Add "Export as... BambuStudio" would be nice so Orca users could contribute to MakerWorld.

### ISSUE THREAD

**Issue by tlhintoq** [SoftFever/OrcaSlicer#4696]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

No

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

If a job is for a BambuLab printer it would be nice to export the 3mf such that it is recognized as a BambuStudio file so users can contribute to MakerWorld.

![image](https://github.com/SoftFever/OrcaSlicer/assets/11351506/79e70e69-9fb7-4e75-9237-97d8b654b4b9)

![image](https://github.com/SoftFever/OrcaSlicer/assets/11351506/c8ad0fb2-49a5-4892-bbe1-995574197815)

**Comment by DannyH3103** [comment]
I would love to see this feature too.

**Comment by tlhintoq** [comment]
Keep alive.  Problem still exists in current 2.0 nightly as of 15apr2024

**Comment by tlhintoq** [comment]
Bot nudge.

**Comment by Kaympe20** [comment]
Seconding this.

**Comment by Kaympe20** [comment]
Bot nudge.
