### ISSUE TITLE
Mix AMS and External spools?

### ISSUE THREAD

**Issue by SwagDad99** [SoftFever/OrcaSlicer#47]
**Is your feature request related to a problem? Please describe.**
Right now, I am limited to either using the AMS, or an external spool, not both.  Also, if using an external spool, and want to do a color change by inserting a pause in the code, the entire layer needs to be the new color.  It would be nice if you could have the option to insert a manual color from the exterior spool.  That way, you could mix standard colors/materials with something like GID without worry.  Or, a 5th, 9th 13, or 17th or more color...

**Describe the solution you'd like**
When the print gets to the non-AMS color, retract/unload the current color as if to change to a different slot, but instead, give the message 'Insert manual color', or 'load exterior spool', or something.  Then, the user would insert the exterior color, just as if printing the full model with it, manually purge the old color, and hit the 'resume' button.  The printer would continue printing with the external spool.  When it is time to change to a different filament, whether external, or back into the AMS, it would cut the filament, retract what it could, and then give the opposite message, 'remove manual filament', or something, and the user would pull back the filament from the tubing, and re-connect the junction from the AMs to the machine.  Then hit 'resume'.

**Describe alternatives you've considered**
Right now, I am limited to either using the AMS, or an external spool, not both.

**Additional context**
I can see it being very labor intensive if there are very many changes, but it could be useful in some cases.

**Comment by psiberfunk** [comment]
I'm not sure how this might even work without firmware support... it might be something better directed at the bambu folks ?
