### ISSUE TITLE
Increased Print Speed Shows an Increase in Print Time

### ISSUE THREAD

**Issue by sleewok** [SoftFever/OrcaSlicer#4708]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0-dev

### Operating System (OS)

Windows

### OS Version

Windows 11

### Printer

K1C / Ender 3 Pro

### How to reproduce

Let's say I have my outer wall print speed at 200mm/s. I slice and get an outer wall time of 9m12s as seen in the image. 
![image](https://github.com/SoftFever/OrcaSlicer/assets/304940/52e7b577-3493-4b7b-9249-03d1a0cad1d2)

I then increase the outer wall speed to 600mm/s

### Actual results

The sliced estimated print time increases to 10m18s rather than decreases.

![image](https://github.com/SoftFever/OrcaSlicer/assets/304940/4348b914-15b1-4b4d-85a8-813f19a156bd)

### Expected results

I would expect the print time to decrease, or at least stay the same if there was another limiting variable.

### Project file & Debug log uploads

[log.zip](https://github.com/SoftFever/OrcaSlicer/files/14749431/log.zip)
[Nozzle temperature test.zip](https://github.com/SoftFever/OrcaSlicer/files/14749434/Nozzle.temperature.test.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Anything else?

I am using high acceleration (up to 20k). I can set the max outer wall acceleration to 20k and increasing the outer wall speed adds about 1 min of time regardless.

**Comment by BruffyT** [comment]
I just had a look at this and cannot recreate, can you try in latest stable release please.
