### ISSUE TITLE
[FR]Extra Perimiter on overhangs

### ISSUE THREAD

**Issue by tome9111991** [SoftFever/OrcaSlicer#471]
hi
im lookig for the feature Extra Perimiter on overhangs from PS.
because on some overhangs i have air print.
this feature will fix the issue
![Screenshot 2023-03-12 083757](https://user-images.githubusercontent.com/57866234/224531071-9f09bd04-d103-4e15-90fa-8563b1e03648.png)

Project:
[air print.zip](https://github.com/SoftFever/OrcaSlicer/files/10950244/air.print.zip)

**Comment by SoftFever** [comment]
Do you mind sharing some prints with extra perimeters on the overhang enabled?
I wonder how well it will work for this model. From the gcode preview, I bet the bridging is a better approach.
Unless we print these extra perimeters super slow like the arc overhang ;)
![image](https://user-images.githubusercontent.com/103989404/225655041-79a23bba-9644-41fa-af5a-f5fe73200ef7.png)
