### ISSUE TITLE
Add free floating parts

### ISSUE THREAD

**Issue by DiegoTheWolf** [SoftFever/OrcaSlicer#4717]
### Is there an existing issue for this feature request?

- [x] I have searched the existing issues

### Is your feature request related to a problem?

I have free form part that has to be fitted somewhere.
When i want to print it normally one point always has to touch the buildplate.
The part - due to is curvature - is build fully on supports.
However since (in normal orientation) all 4 corners touch the ground it's sometimes tricky to remove.
Removing the support is easy though.
If it would had support all around, the part would be better to print.
Currently i have to create a "sacrificial cube" (add part) after importing my part. this cube sits at zero height and will be removed (add negative part). This construct then allowes me to raise the original part 1mm to have the support structures around.

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

Be able to place parts not only on faces but give them a additional z-height so they are free floating (like SLA printers).
Add a parameter for "additional z-height" so we don't mess with the basic code for positioning.
This way you could use the lay down tool to have some face oriented at 0°, then orient it the way you need and lift the print to be printed fully on supports.

**Comment by vgdh** [comment]
may be using raft is the solution?

**Comment by levleon13** [comment]
i'd like that feature too

**Comment by DiegoTheWolf** [comment]
> may be using raft is the solution?

No, it's just easier to remove a millimeter or two of supports.
If the supports are at the edges you only have one layer of support and this can really bind with the part.
