### ISSUE TITLE
Weird Gcode Wall Artefacts

### ISSUE THREAD

**Issue by Ibot-11** [SoftFever/OrcaSlicer#4720]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0 beta

### Operating System (OS)

Windows

### OS Version

Windows 10

### Printer

Voron 2.4R2 250mm

### How to reproduce

Slice the 3mf file with the profiles

### Actual results

![image](https://github.com/SoftFever/OrcaSlicer/assets/84148069/c3437a47-2a4e-43fd-aecf-4a86eea0e794)

### Expected results

I don’t think I have to explain this.

### Project file & Debug log uploads

[Housing.zip](https://github.com/SoftFever/OrcaSlicer/files/14756958/Housing.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Anything else?

Switching to Classic wall generator fixes this issue.

**Comment by levleon13** [comment]
This happened to me as well with two objects on the plate.  but then somehow fixed, not sure.
