### ISSUE TITLE
Artillery Sidewinder X1 machine profile has too high default "Maximum Accelleration Z"

### ISSUE THREAD

**Issue by githubber4ever** [SoftFever/OrcaSlicer#4722]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

1.9.1

### Operating System (OS)

Windows

### OS Version

Windows 10

### Printer

Artillery Sidewinder X1

### How to reproduce

1. Add the X1 printer from printer selection screen with 0.4 nozzle size
2. Check printer settings on tab "Motion ability"
![X1 Stock Printer Settings Limits 01](https://github.com/SoftFever/OrcaSlicer/assets/99887737/223718db-2342-45c8-8184-2c1a0e2462ac)

### Actual results

Default accelleration values are overwritten by the settings in Orca Slicer (as expected), but default value 1000 for "Maximum Accelleration Z" is too high, see Marlin defaults from Artillery:
![X1 Marlin Default Acc](https://github.com/SoftFever/OrcaSlicer/assets/99887737/a54cdc67-1597-4e6b-ac93-300d51d72888)
Since this "Emit limits to G-Code" is also enable by default.
This creates very lound banging noise while printing on Z-hops since its 10 times the value the machine is build for.

### Expected results

"Maximum Accelleration Z" schould be set to 100 by default.

### Project file & Debug log uploads

not needed

### Checklist of files to include

- [x] Log file
- [x] Project file

**Comment by cochcoder** [comment]
Does [this](https://github.com/cochcoder/OrcaSlicer/actions/runs/8445513335) fix your issue?
