### ISSUE TITLE
Un-called sudden flow and speed changes where speed and flow should be uniform

### ISSUE THREAD

**Issue by Rickthebig** [SoftFever/OrcaSlicer#4723]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0 Beta

### Operating System (OS)

Windows

### OS Version

Windows 10

### Printer

DIY CoreXY 3D printer (BLV Cube) based on Troodon (RRF)

### How to reproduce

Load the attached project (an egg form printed in spiral vase mode) and look at the bottom layers as in the pictures.

### Actual results

Both flow and speed change unexpectedly while building the first layers. The change is very obvious while looking at the piece during printing time. These are planned changes in the slicers, so the defective lines can be recognized:
![image](https://github.com/SoftFever/OrcaSlicer/assets/151161212/3b4f5485-0fad-43e7-853d-fb3a32f394ee)

![image](https://github.com/SoftFever/OrcaSlicer/assets/151161212/7ff204d2-7457-4a97-86ba-af213c8e2d79)

![image](https://github.com/SoftFever/OrcaSlicer/assets/151161212/4399c4d0-4800-4bbe-9f26-40e18f22f084)

![image](https://github.com/SoftFever/OrcaSlicer/assets/151161212/414d0a60-4169-488a-80c7-63def428ad8c)

![image](https://github.com/SoftFever/OrcaSlicer/assets/151161212/f9406074-130a-4df2-83d8-7698d9797353)

There are no other conditions like overhangs, gaps, geometric irregularities etc. that would explain these changes. A sudden flow change is generally undesireable.

### Expected results

The layer lines should be laid with regular, constant speed.

### Project file & Debug log uploads

[Easter_Egg_PATTERN_-_KRAKEN.zip](https://github.com/SoftFever/OrcaSlicer/files/14758341/Easter_Egg_PATTERN_-_KRAKEN.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Anything else?

See also related issue:
Inconstant flow #1360

**Comment by vgdh** [comment]
may be related https://github.com/SoftFever/OrcaSlicer/issues/4634

**Comment by vgdh** [comment]
I've disabled **small area flow compensation** and your project sliced with consistent flow.

**Comment by vgdh** [comment]
monotone line helps as well

**Comment by Rickthebig** [comment]
> I've disabled **small area flow compensation** and your project sliced with consistent flow.

OK, then let's ditch this "small are flow compensation" feature :-)

**Comment by igiannakas** [comment]
I’m guessing you have extrusion rate smoothing enabled? If so this is to be expected as together with small area infill compensation you get variations in flow that need to be compensated for.

**Comment by perpleksed** [comment]
> I’m guessing you have extrusion rate smoothing enabled? If so this is to be expected as together with small area infill compensation you get variations in flow that need to be compensated for.

Resulting flow is not desired though, I think, maybe Small Area Flow Compensation should be applied **after** Extrusion Rate Smoothing? Look at this example:

ERS only (looks reasonable):
![Screenshot_11](https://github.com/SoftFever/OrcaSlicer/assets/141807129/cd6685e7-669a-432a-b507-353018cc9177)

SAFC only (flow adjustments not even visible here):
![Screenshot_16](https://github.com/SoftFever/OrcaSlicer/assets/141807129/12a99a92-ee6b-4e68-a612-1155586c8789)

ERS+SAFC (wow, suddenly we are barely moving at 60mm\s for solid infill!):
![Screenshot_17](https://github.com/SoftFever/OrcaSlicer/assets/141807129/ff3d3dfa-7af0-488f-ad3e-9d3249bd5d70)

**Comment by igiannakas** [comment]
I think you’ve got your ers value a bit too low. In any case small area flow compensation together with ers works best with monotonic lines, not monotonic due to the constant small segments that monotonic generates.
