### ISSUE TITLE
File locks after closing SF

### ISSUE THREAD

**Issue by officiallymarky** [SoftFever/OrcaSlicer#473]
I am noticing after I exit SF on Windows 10 x64 Pro I cannot delete STL files frequently as they are locked.  If I explore what is locking the file, it is dllhost that persists after closing SF.

**Comment by SoftFever** [comment]
Did it release the stl file eventually?

**Comment by officiallymarky** [comment]
I had to manually release it, but it didn't release it until rebooted or manually intervened.
