### ISSUE TITLE
Weird intersection between top layer and following wall

### ISSUE THREAD

**Issue by martinrosolino** [SoftFever/OrcaSlicer#4737]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

Windows

### OS Version

11

### Printer

Ender 2 Pro

### How to reproduce

Load a model with any kind of step, preferably in a rounded shape, set Ensure Vertical Shell Thickness to Critical Only (for every other print feature it works amazing, but in this particular case I've to set it to All to get a nice result, wasting time/material on every other place it's being applied)

### Actual results

![20240327_114112](https://github.com/SoftFever/OrcaSlicer/assets/68257548/6aad2a88-b60b-40bf-8040-c40b916df0d0)
the top layer "ends" before the wall, so it leaves a tiny gap

### Expected results

Maybe add a parameter "Top layer - Next wall Overlap"?

### Project file & Debug log uploads

NA

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by gregmatic** [comment]
i came here to ask about my own issue but spotted your post first. i wonder if we are having the same issue? you'll have to look at the slicer preview to tell. orca is not slicing a full top layer if the next layer has structures above it. 
![image](https://github.com/SoftFever/OrcaSlicer/assets/60957555/fbc40fa1-9223-4629-8e9f-70a98720f50a)



![image](https://github.com/SoftFever/OrcaSlicer/assets/60957555/e2d79824-91b3-4d0f-afb2-04105ab52447)

**Comment by martinrosolino** [comment]
I don't think that's exactly the same issue, but yeah results should be similar. In your case, the top structure is rather thin so a full "red" layer would be a great option, in my case I don't think it makes sense to print a full layer before a big top structure, I believe that about 2mm in is enough, that's what I get when I set Ensure Vertical She'll Thickness to All, but that doesn't give me good results in other parts of the print.

**Comment by MaroonOut09** [comment]
I'm having the same issue, and, in my case at least, it looks like the top infill isn't extending to the interior perimeters.

![image](https://github.com/SoftFever/OrcaSlicer/assets/34607974/a26f1947-7b28-441b-9204-07553f00c3ce)

When I slice the same stl with the same settings in PS or SS, this gap isn't present.

**Comment by foreachthing** [comment]
Could you please upload your models? I cannot reproduce with cubes and cylinders.

**Comment by foreachthing** [comment]
I don't see any of that issue. But, again, you should upload your 3mf file (zip it first).

![MoldCactus](https://github.com/SoftFever/OrcaSlicer/assets/10420187/a81929ae-f8d1-4819-b4da-f9bc77244b8b)

[Mold_cactus_n10_nucleo.zip](https://github.com/SoftFever/OrcaSlicer/files/15489522/Mold_cactus_n10_nucleo.zip)

**Comment by MaroonOut09** [comment]
[Meter Base-RC2.zip](https://github.com/SoftFever/OrcaSlicer/files/15492666/Meter.Base-RC2.zip)
Attached is the stl I'm experiencing the issue with.

**Comment by foreachthing** [comment]
Please attach your *.3mf (zip it first). That way, we can all see your settings, the orientation of your model and everything else relevant.

**Comment by MaroonOut09** [comment]
Attached is the .3mf as requested.
[Meter Base-RC2 (2).zip](https://github.com/user-attachments/files/15523774/Meter.Base-RC2.2.zip)
