### ISSUE TITLE
no support on the outer edge of the top layer

### ISSUE THREAD

**Issue by HAndreasH** [SoftFever/OrcaSlicer#4740]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0-rc

### Operating System (OS)

Windows

### OS Version

Win 11

### Printer

Ender 3 pro

### How to reproduce

i have noticed that the top layer has no support on the outer edge, noticed this problem with several objects
the behaviour occurs when the top layer is not connected to a wall

### Actual results

![test1](https://github.com/SoftFever/OrcaSlicer/assets/98119968/986a7370-f68b-443e-8ceb-7d6b2361c5fd)
![test2](https://github.com/SoftFever/OrcaSlicer/assets/98119968/0a7762d2-26e6-43cb-bb72-b6e64e56045c)

### Expected results

perhaps it would be possible to add a contour to the outside of the infill or on the lower layer

### Project file & Debug log uploads

[dust-cover-project.zip](https://github.com/SoftFever/OrcaSlicer/files/14779455/dust-cover-project.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by Matszwe02** [comment]
I have the same issue with 3dbenchy model.

![image](https://github.com/SoftFever/OrcaSlicer/assets/49353902/7d77e8df-6076-475e-b6d2-b1d7db2ae9b9)
> look from the bottom

That bug causes my benchy to look suboptimal

![image](https://github.com/SoftFever/OrcaSlicer/assets/49353902/cd8af2ce-1e86-46ec-b921-42bb61dfc901)
