### ISSUE TITLE
Add Hexagon to 'add primitive' options

### ISSUE THREAD

**Issue by markusastone** [SoftFever/OrcaSlicer#4743]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Adding hex nut inserts on parts that are made for brass heated inserts would be made significantly easier if there was a hexagon primitive option under the right-click 'add primitive' menu.

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

Allow the option for users to right click > add primitive > hexagon, and have a hexagon primitive added to the build space, equal to how you can currently add cubes, cylinders, etc.

**Comment by phntsm** [comment]
I'm surprised there wasn't any interest in this. I've been hoping for more primitives since I got my p1s, hexagon being one of them. Or at least some type of primitives plugin to add your own basic shapes.
