### ISSUE TITLE
Improve support generation

### ISSUE THREAD

**Issue by gitterman** [SoftFever/OrcaSlicer#4747]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I'm always frustrated when I need to use support on my bambu P1S with AMS, as changing the filament needs to be done on every other layer. 
This takes a long time and is a waste of material.
Thus, I would like to have support trees which only use the support filament at the top and/or bottom edge and in the middle use the same filament as the rest of the shape. 
This way, printing could be much faster and the overall quality of the shape would be much better.

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

Generate sophisticated support trees as described in the feature request.

**Comment by vgdh** [comment]
I suppose that will be useful feature for that kind of task.
Currently you only can set a filament for the top the interface and support itself.
It would be useful to have an ability choose a filament for the base interface of the support.
![Снимок](https://github.com/SoftFever/OrcaSlicer/assets/15322782/ca3c146f-9af0-4f3b-ad2f-b9ded75ef85c)
