### ISSUE TITLE
Seam-Staggered inner seams problem

### ISSUE THREAD

**Issue by olcayoren** [SoftFever/OrcaSlicer#4752]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

1.9.1

### Operating System (OS)

macOS

### OS Version

14.2.1 Sonoma

### Additional system information

Macbook M1 Arm

### Printer

Elegoo Neptune 4 Pro

### How to reproduce

On->Staggered inner seams
<img width="320" alt="Ekran Resmi 2024-03-28 19 18 32" src="https://github.com/SoftFever/OrcaSlicer/assets/33813227/bde33e12-79c4-4771-bff6-99104d854577">

### Actual results

Once the gradual inseams are opened, the inseams remain aligned. Gaps are forming.

### Expected results

None

### Project file & Debug log uploads

[Uploading test2.3mf.zip…]()

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by olcayoren** [comment]
Hi, is this a display or printing issue? Can you comment? @igiannakas 

The situation is the same in both stable versions.
1.9.1 - 2.0.0

<img width="261" alt="Ekran Resmi 2024-03-30 12 45 10" src="https://github.com/SoftFever/OrcaSlicer/assets/33813227/ec5bc662-ed24-44af-be21-efa4ff0352c7">

**Comment by igiannakas** [comment]
Struggling to understand the issue. Could you give a bit more detail please?

also try it on a simple cylinder to see what the result is.

**Comment by olcayoren** [comment]
> Struggling to understand the issue. Could you give a bit more detail please?
> 
> also try it on a simple cylinder to see what the result is.

The problem is seen when the inner wall gradual seam is opened. He does the stitches elsewhere. I added the video.


https://github.com/SoftFever/OrcaSlicer/assets/33813227/6d73bbac-4998-464b-be8b-194092374de8

**Comment by olcayoren** [comment]
> Struggling to understand the issue. Could you give a bit more detail please?
> 
> also try it on a simple cylinder to see what the result is.

I think I misinterpreted the image. I think the seams only occur on the outer wall. When I hid the outer wall, I expected it to be hidden at the seams on the outer wall.

**Comment by igiannakas** [comment]
Correct. The seam line shows if you select it on the visualiser irrespective of if the outer walls are visible or not.

**Comment by olcayoren** [comment]
> Correct. The seam line shows if you select it on the visualiser irrespective of if the outer walls are visible or not.

There are no seams on the interior walls, right? Increasing the seam gap causes weakness in the inner wall. Wouldn't it be better if the inner wall seam gap was a separate area instead?

<img width="260" alt="Ekran Resmi 2024-03-30 13 42 07" src="https://github.com/SoftFever/OrcaSlicer/assets/33813227/e5b972b8-b127-41a9-85ce-309476cd5f55">

**Comment by igiannakas** [comment]
Of course there are seams on the internal part as the loops need to start somewhere. To mitigate the effect (part weakness) enable staggered inner seams as you’ve done. This way the seams are offset from each other between layers by a small amount. Also enabling wipe before external wall helps a bit as it extrudes a little bit of material internally strengthening the part. Finally setting your seam gap to 0-10% at most will allow the seams to fuse together (basically tune your seam gap). 

The gaps you see in the visualiser won’t occur in real life as the hot end extrudes a tiny bit of material at the end of the wall travel, closing the seam off.
