### ISSUE TITLE
Make "monotonic line order" a separate feature the way it is made in CURA

### ISSUE THREAD

**Issue by acritum** [SoftFever/OrcaSlicer#4762]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Currently the top/bottom infill pattern can be selected Monotonic Line or Aligned Rectilinear. I find Aligned Rectilinear infill very useful in many cases but it draws the lines in random directions and makes the final look ugly. To prevent this, Monotonic Line pattern can be used, but it doesn't care of the infill directions in the lower levels the way Aligned does.

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

 I think the only reasonable way is implemented in CURA. There is a checkbox "Monotonic top/bottom order" and it can be used with ANY type of infill (concentric, line, zigzag). I think the same thing should be made in OrcaSlicer, to be able to use the advantages of both  Monotonic Line infills and any other type of infill, such as Aligned Rectilinear.

### Describe alternatives you've considered

I can't find except using CURA :)

**Comment by SoftFever** [comment]
Looks like you looking for "Monotonic" pattern which is already there.
Pls pay attention, there are Monotonic and Monotonic line in the option

**Comment by acritum** [comment]
It feels you don't understand what I mean. I need  Aligned Rectilinear pattern, but printed in monotonic line order. Neither  Monotonic nor Monotonic line care about the infill direction in previous top layers the way Aligned Rectilinear does, At the same time, Aligned Rectilinear cannot use monotonic infill in top layers. Please compare the images, I hope you understand what I mean. You can see that both monotonic and monotonic lines have horizontal and vertical infill in different top surfaces while alligned rectilinear has only horizontal infill (as I need), but the lines are not monotonic, they are printed partially from up to down and from down to up, and I can see the visual transition in the places they meet in the final surface.
**Aligned Rectilinear** 
![1-alligned_rect](https://github.com/SoftFever/OrcaSlicer/assets/6622765/d7870bd4-0987-4822-9646-3352b5e196ee)
**Monotonic** 
![2-monotonic](https://github.com/SoftFever/OrcaSlicer/assets/6622765/d7827637-43eb-4f73-a1f1-a89f9a240245)
**Monotonic line**
![3-monotonic_line](https://github.com/SoftFever/OrcaSlicer/assets/6622765/b2c86fcb-2c24-45ba-b59f-f1c83741eff7)
