### ISSUE TITLE
Grid Cut or cut into segements Feature.

### ISSUE THREAD

**Issue by Maki9009** [SoftFever/OrcaSlicer#4779]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

it would be nice to have a feature that can cut models into multiple pieces or in a grid form, to print each part by it self in segments. in the case of wanting print in large scale and then put them together after printing. 

### Which printers will be beneficial to this feature?

Klipper, All

### Describe the solution you'd like

the planar cut but add the ability to grid based on how many cuts you want x and y and maybe  even z if possible.  i kinda want this to print large scale topography maps and i want to cut them into piece the size of my bed to get large print when i put it together.

**Comment by hatkidchan** [comment]
i also want that feature, or at least having more granular control over cut plane (sorry, but dragging a yellow ball is not convenient in any way when you need to cut at exact coordinate)


stalebot is a menace to society, can this be reopened?
