### ISSUE TITLE
Option to exclude hole x-y compensation from the text or add hole compensation to per part configuration

### ISSUE THREAD

**Issue by szafranski** [SoftFever/OrcaSlicer#4780]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

When you add a text to the model and use hole compensation it messes up letter like Q, O etc

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

As stated in the name of the issue

**Comment by ctadlock** [comment]
I wrote up a bug about this well over a year ago. Nobody cared.
