### ISSUE TITLE
Models off plate are visibly cut off - like draw distance

### ISSUE THREAD

**Issue by ndevenish** [SoftFever/OrcaSlicer#4787]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0-beta (although present on earlier)

### Operating System (OS)

macOS

### OS Version

14.1 (23B74)

### Additional system information

M2 Pro. 16GB Memory.

### Printer

Bambu P1S

### How to reproduce

Add STL out of bounds. Rotate Camera.

### Actual results

When models are placed off of the plate, they are cut off by what appears initially to be Z view distance. This happens with even a few objects. Anything a certain distance off of the plate gets effectively invisible.
![image](https://github.com/SoftFever/OrcaSlicer/assets/529963/59150bf2-5542-4d35-a20a-aac798576a2c)
And even the plate control widgets appears to get cut off when at shallow angles:
![image](https://github.com/SoftFever/OrcaSlicer/assets/529963/62fc7585-e6e7-4144-b6a1-ed97b5c70f62)
However, it's not a direct view distance effect, because deliberately moving far off the plate (so it is invisible) and rotating the camera makes it appear, but appears to be cut off on the near side:
![image](https://github.com/SoftFever/OrcaSlicer/assets/529963/a73c072f-2f3a-41f0-8468-ef469c827af8)

### Expected results

I expect the STL to be always visible. Here is a screenshot showing the same model and configuration (on Bambu Studio):
![image](https://github.com/SoftFever/OrcaSlicer/assets/529963/78918b26-04f0-4cc9-b720-de9be761444a)

### Project file & Debug log uploads

[random_bin_video_cutoff.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/14812501/random_bin_video_cutoff.3mf.zip)
[debug_Sat_Mar_30_15_33_12_64198.log.0.zip](https://github.com/SoftFever/OrcaSlicer/files/14812505/debug_Sat_Mar_30_15_33_12_64198.log.0.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by cosmith71** [comment]
I'm seeing something very similar. Windows 11, Orca version 2.0.0 release version, RC, and Beta.
![Screenshot 2024-04-01 101305](https://github.com/SoftFever/OrcaSlicer/assets/4393089/79e9b4b0-f30d-4baf-ae3e-edf6af89529c)

**Comment by kylek29** [comment]
Yes, it's been this way since either 2.0 or 1.9 iirc. It's really prevalent on my laptop where I can't even view some models. They don't have to be off the plate, it seems to have a really small view distance.

**Comment by ndevenish** [comment]
Still present in 2.1.0-beta 
![image](https://github.com/SoftFever/OrcaSlicer/assets/529963/dea902ea-5b88-4156-ae99-0462642282bb)

**Comment by ListerD000169** [comment]
Also still seeing this in 2.1 beta.  Can confirm that this was also in at least 2.0.  Running on Windows 11

**Comment by ndevenish** [comment]
Definitely still here in 2.1.1

![image](https://github.com/user-attachments/assets/279bec99-bcfe-4196-8afa-dd32c0787b2a)

**Comment by ndevenish** [comment]
And 2.2.0-beta
![image](https://github.com/user-attachments/assets/9e4bfe53-ad27-4724-99b7-f97e29801817)

**Comment by ndevenish** [comment]
From released binaries, this was introduced between v1.7.0 and v1.8.0-beta1.

**Comment by ndevenish** [comment]
I have bisected this down and the commit causing the error is bbfb9d77fadc63ca84d70b09aa1efa6d90889736

**Comment by ndevenish** [comment]
I have bisected this down and the commit causing the error is bbfb9d77fadc63ca84d70b09aa1efa6d90889736 ; this makes some sense as it does feel related to models outside the bounds of the current plate being cut off.

**Comment by xsynatic** [comment]
Full 2.2.0 release

![image](https://github.com/user-attachments/assets/9733cce3-9e41-45d2-a84d-581ffe4fdde5)

**Comment by ndevenish** [comment]
At some point in the past year while I wasn't printing much, this seems to have been fixed.
