### ISSUE TITLE
Missing Printers

### ISSUE THREAD

**Issue by ThadudeIntheCorner** [SoftFever/OrcaSlicer#4795]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

V2.0.0

### Operating System (OS)

Windows

### OS Version

Windows 11

### Printer

Most Creality printers

### How to reproduce

Go to the "Printer Selection" tab and scroll down to the Creality section.

### Actual results

There are only two printers in the Creality section: the CR-10 V2 and the CR-10 Max. 
![Screenshot 2024-03-30 100702](https://github.com/SoftFever/OrcaSlicer/assets/165500818/4de1b55c-d1b4-435b-a255-256d8591c77f)

### Expected results

I'd like to have an option for my printer (Ender 5 S1) so that I can actually use it.

### Project file & Debug log uploads

Nothing to add.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by TexZeTech** [comment]
I just checked on my windows vm and linux vm, this isn't an issue I see.

I would recommend at the minimum uploading your log files and try the check for updates button?

<img src="https://github.com/SoftFever/OrcaSlicer/assets/7254540/8c499468-13fa-4c13-be95-47b59e2eed63" width=80% height=80%>

Beyond that I don't know.

**Comment by ThadudeIntheCorner** [comment]
It's the newest version. When I updated to V2.0.0, that's when my printer disapeared.

**Comment by ThadudeIntheCorner** [comment]
Redownloaded it, everything was there. Wierd.
