### ISSUE TITLE
Anti virus program deletes current 2.0 version

### ISSUE THREAD

**Issue by Skyl-Orca** [SoftFever/OrcaSlicer#4798]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0

### Operating System (OS)

Windows

### OS Version

Windows 10

### Printer

Bambulab X1

### How to reproduce

Unfortunately, my antivirus program still deletes the exe of the current stable version 2.0 :-( something still seems to be recognized as a "threat".

### Actual results

![Norton](https://github.com/SoftFever/OrcaSlicer/assets/136186216/f9384110-a2e2-459d-a842-23ab481dc07c)

### Expected results

-

### Project file & Debug log uploads

-

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by TexZeTech** [comment]
Whats the Anti-virus?

**Comment by Skyl-Orca** [comment]
Norton

**Comment by TexZeTech** [comment]
If you are truly concerned email NortonAV and get them to check the file.

I would say it's most likely a false positive and I would just hit ignore, however if you are even slightly concerned that your file has been compromised check the SHA256 of OrcaSlicer_Windows_Installer_V2.0.0.exe and verify it.

I just downloaded the exe from https://github.com/SoftFever/OrcaSlicer/releases/tag/v2.0.0 .

SHA256: `58b400ec976d1e38f8876d75b6e7c6ac9945cb5f231705b71c96d10e474ad32c`

<img src="https://github.com/SoftFever/OrcaSlicer/assets/7254540/0a5396b1-3d6f-4e5a-8353-15a33763f940" width=80% height=80% alt="SHA256: 58b400ec976d1e38f8876d75b6e7c6ac9945cb5f231705b71c96d10e474ad32c">

[VirusTotal](https://www.virustotal.com/gui/file/58b400ec976d1e38f8876d75b6e7c6ac9945cb5f231705b71c96d10e474ad32c) says its clean.

<img src="https://github.com/SoftFever/OrcaSlicer/assets/7254540/8d904ad1-4bed-4fef-be0b-13e2d9a02100" width=80% height=80%>

**Comment by justanotheruser4once** [comment]
Aside from Norton, there are 2 additional AV engines that mark the Installer (but not the portable version) as malicious. These are the Bkav (report from VirusTotal) and the HybridAnalysis (CrowdStrike Falcon sandbox), and the hash is correct - 58b400ec976d1e38f8876d75b6e7c6ac9945cb5f231705b71c96d10e474ad32c. I've seen this a fair amount with installers specifically. There is a currated list of contacts for the different AV vendors - [AV False Positive Help](https://github.com/yaronelh/False-Positive-Center)

Bkav / VirusTotal Report
- False Positive Reports Contact: [fpreport@bkav.com](mailto:fpreport@bkav.com), [bkav@bkav.com](mailto:bkav@bkav.com)
- https://www.virustotal.com/gui/file/58b400ec976d1e38f8876d75b6e7c6ac9945cb5f231705b71c96d10e474ad32c
![VT_Bkav](https://github.com/SoftFever/OrcaSlicer/assets/171855524/c0419c41-a4b0-417b-8dc7-d57dceb954bc)

CrowdStrike Falcon / HybridAnalysis Report
- False Positive Reports Contact: [VTscanner@crowdstrike.com](mailto:VTscanner@crowdstrike.com)
- https://hybrid-analysis.com/sample/58b400ec976d1e38f8876d75b6e7c6ac9945cb5f231705b71c96d10e474ad32c/660c58399878e649e9000fe9
![HA_Falcon](https://github.com/SoftFever/OrcaSlicer/assets/171855524/4e64cac7-428d-4a06-97ba-476642523d5c)

Specifically for Norton, they have provided a link:
[Norton FP Submissions](https://submit.norton.com/)

Anyone can reach out, but I think FP submissions would be better received from developers that may be able to answer any question that arises.

**Comment by liamwerk7676** [comment]
for me it got 8 / 10 malware score https://tria.ge/240805-tpk5wa1fjp/behavioral2 i dont know if i can trust it 
![image](https://github.com/user-attachments/assets/09da530f-9485-496f-9e23-623f0fbc4424)

**Comment by liamwerk7676** [comment]
update: i think its safe i am using it rn and i havent yet had any isues and malware detection on my pc didnt go VIRUS !!! and delted it so i think its safe

**Comment by TexZeTech** [comment]
> for me it got 8 / 10 malware score https://tria.ge/240805-tpk5wa1fjp/behavioral2 i dont know if i can trust it ![image](https://private-user-images.githubusercontent.com/112199156/355175409-09da530f-9485-496f-9e23-623f0fbc4424.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMzc4ODEsIm5iZiI6MTcyMzEzNzU4MSwicGF0aCI6Ii8xMTIxOTkxNTYvMzU1MTc1NDA5LTA5ZGE1MzBmLTk0ODUtNDk2Zi05ZTIzLTYyM2YwZmJjNDQyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQxNzE5NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMjI2OTkwNGI3ZmU5NmE3MTBmOWY5NzVlOTU5ZmFhNmNiMTEwMGYzNjVhMDljYmI0NWEwNDVlZDE0MmQ5OTVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.15IVSbedhxjyiUToq7OzDgMx66_WwzXElFzNodWc8v4)

Why even comment on this? You checked the 2.1.1 version not the 2.0 version. 

That's like someone talking about a home that was burnt down the previous year then you come back and say "Yep looks like there is no fire here." after the home has been remade.

I request this ticket gets closed.

**Comment by justanotheruser4once** [comment]
> > for me it got 8 / 10 malware score https://tria.ge/240805-tpk5wa1fjp/behavioral2 i dont know if i can trust it ![image](https://private-user-images.githubusercontent.com/112199156/355175409-09da530f-9485-496f-9e23-623f0fbc4424.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMzc4ODEsIm5iZiI6MTcyMzEzNzU4MSwicGF0aCI6Ii8xMTIxOTkxNTYvMzU1MTc1NDA5LTA5ZGE1MzBmLTk0ODUtNDk2Zi05ZTIzLTYyM2YwZmJjNDQyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQxNzE5NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMjI2OTkwNGI3ZmU5NmE3MTBmOWY5NzVlOTU5ZmFhNmNiMTEwMGYzNjVhMDljYmI0NWEwNDVlZDE0MmQ5OTVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.15IVSbedhxjyiUToq7OzDgMx66_WwzXElFzNodWc8v4)
> 
> Why even comment on this? You checked the 2.1.1 version not the 2.0 version.
> 
> That's like someone talking about a home that was burnt down the previous year then you come back and say "Yep looks like there is no fire here." after the home has been remade.
> 
> I request this ticket gets closed.

Although I agree, it would have been better for the user to report the issue with 2.1.1, adding it to an open issue for 2.0 is not useless. It helps other users who are trying to make an informed risk accessment about using the software. Just because you don't value security to the same extect of others, does not make the issue any less relevant to the project.

Version 2.0 is the latest release that has been digitally signed, and people that value using FOSS while trying to address possible supply chain concerns depend of this. Additionally, the 2.1.1 installer is also identified malicious on VirusTotal so upgrading to it does not resolve the issue.

The issue is not with the project itself, but the installer. Reviewing Hybrid Analysis reports lead me to believe it's likely a false positive just due to the nature of installers. However, reviewing the log analysis of tria.ge makes me question my initial assumption. The developers have not given a response to indicate they checked to verify the installer was not tampered with before distribution, neither for 2.0 nor 2.1.1. Since 2.0 was digitally signed, I would like to think the code changes were reviewed before being signed, but I would just like confirmation what was used to create the installer was not tampered with. 

If I had the capability to compile from source, I would be able to confirm it either way. So really we are asking for comfirmation that the installer was verified as not being tampered with, but working with AV vendors to get the matter resolved would solve the problem for future releases.
