### ISSUE TITLE
Make a Clone STAY a Clone

### ISSUE THREAD

**Issue by SwagDad99** [SoftFever/OrcaSlicer#48]
**Is your feature request related to a problem? Please describe.**
If I select an object, and make some clones of it, then later decide to make a small tweak to the object, it would be nice to have all of the clones update themselves to have the tweak.  When a lot of clones are made, and time is taken to fit them to the plate, it would really save time to have them auto-update instead of deleting them all, re-cloning them, and having to re-fit them to the plate.

There could be a check box to have them 'keep current' to the original, or not, if you wanted each to be different colors, etc...

**Describe the solution you'd like**
Described above

**Describe alternatives you've considered**
Clone, arrange, change, delete, re-clone, re-arrange.

**Additional context**

**Comment by halofx** [comment]
In PrusaSlicer you have Copy/Paste, which is like what Bambu is doing with clone. There is also the Add Instance feature, which would make another instance (linked clone) of the same item. There is a plus and minus sign to add/remove instances. Copy/Pasting of an instance would break the link. This works really well in PrusaSlicer, and I use it all the time!

Bringing this feature back into Bambu Slicer would solve the above problem, and be much appreciated.
