### ISSUE TITLE
layer_num variable starts at 0 instead of 1

### ISSUE THREAD

**Issue by JCBond** [SoftFever/OrcaSlicer#4804]
### OrcaSlicer Version
2.0.0

### Operating System (OS)
Windows

### OS Version
11

### Printer
Voron 2.4

### How to reproduce

According to the description of the "layer_num," variable the first Layer should be layer number 1
![PS2995](https://github.com/SoftFever/OrcaSlicer/assets/48573000/75d90e51-f1f9-4a45-9aae-090c6555cd69)

But when I use this variable in the "Layer Change G-code," it seems that the first Layer is number 0.

### Actual results
layer_num starts at layer 0

### Expected results
layer_num should start at layer 1

**Comment by foreachthing** [comment]
I agree.
But please don't just change it without notice. I have post processing scripts replying on that number.

**Comment by JCBond** [comment]
> Uhm, why the double post? #4802
Sorry for the double post. I initially thought of putting it only on the discussion side, but then figured it was actually an issue.

**Comment by Klober81** [comment]
Unfortunately, layer_num actually starts at -1 if used in "Change filament G-code" of the Machine G-code in the Printer settings. It would make more sense if the same starting number is used for all portions of the first layer regardless of which custom G-code section it's being used in. The following screenshot is an example of the result of using ";Layer#=[layer_num] - Z=[layer_z]" in "Change filament G-code".
![image](https://github.com/SoftFever/OrcaSlicer/assets/20543393/d90fbc20-cd9f-41cf-8d2a-67c0779bc378)
