### ISSUE TITLE
Customized Filaments under devices

### ISSUE THREAD

**Issue by marcuswitt** [SoftFever/OrcaSlicer#4811]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

Windows

### OS Version

Windows 11

### Printer

Bambulab P1S

### How to reproduce

In version 1.9.1 no problem to select my filaments under Devices

<img width="636" alt="Screenshot 2024-03-30 180506" src="https://github.com/SoftFever/OrcaSlicer/assets/1307493/90b83ea8-98d0-4c26-9d98-f360653450e1">
<img width="438" alt="Screenshot 2024-03-30 181136" src="https://github.com/SoftFever/OrcaSlicer/assets/1307493/7de70f9c-4792-43a0-a38f-1dbc1a15ebf2">

### Actual results

I have this display error in version 2.0.0. The red border is normally red and the pen for editing is missing. 
Furthermore, I cannot select my filaments in this version as I can in version 1.9.1. 

<img width="356" alt="Screenshot 2024-03-30 180526" src="https://github.com/SoftFever/OrcaSlicer/assets/1307493/2cca6458-f37f-4e88-ad7d-64cca52599e6">

### Expected results

..

### Project file & Debug log uploads

[debug_network_Sun_Mar_31_11_22_40.log.zip](https://github.com/SoftFever/OrcaSlicer/files/14814908/debug_network_Sun_Mar_31_11_22_40.log.zip)

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Anything else?

What is very strange is that when I do a resync under prepare my filaments are synchronized, but as written, I cannot select them under devices in the ams. there are only the standard filaments.

**Comment by skvarel** [comment]
Der Stift ist noch da. Man sieht ihn nur nicht, da er auch Weiß ist. Ich habe hier das gleiche Problem.

**Comment by TexZeTech** [comment]
Going off what skvarel said: google translation: "The pen is still there. You just can't see him because he's also white. I have the same problem here.".

I think what needs to happen is an outline that is black or white of said pen or a color change of the pen depending on the colour. 

@marcuswitt can you confirm if the pen is there?

**Comment by marcuswitt** [comment]
> Going off what skvarel said: google translation: "The pen is still there. You just can't see him because he's also white. I have the same problem here.".
> 
> I think what needs to happen is an outline that is black or white of said pen or a color change of the pen depending on the colour.
> 
> @marcuswitt can you confirm if the pen is there?

![photo_2024-04-02_08-42-43](https://github.com/SoftFever/OrcaSlicer/assets/1307493/dccd6415-03b3-4128-a927-f2de6bf90ddc)

i'm not sure if there is a pen there

**Comment by marcuswitt** [comment]
i changed the color from red to green to test.... that worked and it was then displayed completely green and the pen is also visible. but the problem is that i still can't select my custom filaments

**Comment by ichisaur** [comment]
I have the same problem here. No issues with the edit button color, but the custom filament options were working in 1.9.1, completely gone in 2.0.0. 

I can still select them via the handy app, just not OrcaSlicer. Bambu Slicer does not show the custom filaments either, though I'm not sure if it ever did.

**Comment by marcuswitt** [comment]
i have just installed it on a completely new pc as a test, unfortunately exactly the same that it is not displayed correctly and i can't select my custom filaments in the ams settings either

**Comment by Crossfire1189** [comment]
same problem with custom filaments here. worked in v1.9.1.

**Comment by jeremydthomas** [comment]
I also cant select custom filaments in the ams device tab, I never could actually

**Comment by marcuswitt** [comment]
i have opened a ticket with bambu the last few days because the user-defined filaments cannot be selected in the studio in the ams because it works with the P and A. Bambu apparently has a "bug" and wants to fix this problem with the next firmware. maybe this is also the reason 
i have added my filaments in the ams with version 19.1 and opened the 2.0.0 version on another device, synchronized and noticed that the filaments are apparently entered in the ams, but are not displayed in the selection menu. 

if you do a "resync" in the 2.0.0, they are read out correctly from the ams, as written only the display itself is missing in the selection list in the ams

![Screenshot_20240410-124858](https://github.com/SoftFever/OrcaSlicer/assets/1307493/6d1a06aa-3af9-4b51-8335-3ef60b35a4ce)

**Comment by ichisaur** [comment]
What firmware version is this and would you mind posting the notes? I’m in the beta program but I don’t see a pending update.

**Comment by marcuswitt** [comment]
![Screenshot 2024-04-23 071053](https://github.com/SoftFever/OrcaSlicer/assets/1307493/16a1e869-daa3-4463-8ec4-59bfd801fd2f)
![Screenshot 2024-04-23 071104](https://github.com/SoftFever/OrcaSlicer/assets/1307493/4cf518e9-2418-4b10-bbf8-963ce11f0766)
