### ISSUE TITLE
Layer number is not shown (-)

### ISSUE THREAD

**Issue by witchcraftsman** [SoftFever/OrcaSlicer#4819]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

macOS

### OS Version

mac os 12.7.4

### Printer

Qidi x-max 3

### How to reproduce

1. Load project
2. Preview/Slice
3. Start printing 
4. Switch to device tab

### Actual results

Current printed layer shown as '-' (dash)

### Expected results

Current layer number should be shown instead in device tab

### Project file & Debug log uploads

[log.zip](https://github.com/SoftFever/OrcaSlicer/files/14817144/log.zip)

### Checklist of files to include

- [x] Log file
- [ ] Project file

### Anything else?

The issue was actually with previous major version of the app.
NOTE: The workaround is to close OrcaSlicer and start again, layer number gets shown.

**Comment by TexZeTech** [comment]
Add a screen shot please?

you can also resize the image in question with `<img src="image.jpg" width=200px height=200px>` or `<img src="image.jpg" width=80% height=80%>`


<img src="https://github.com/SoftFever/OrcaSlicer/assets/7254540/135e0967-20e6-4789-a35a-0368d52dcff4" width=80% height=80%>

**Comment by witchcraftsman** [comment]
[
<img width="1512" alt="Screenshot 2024-04-17 at 22 04 42" src="https://github.com/SoftFever/OrcaSlicer/assets/60239912/b3033f4f-d17e-4a97-9d58-510ab3a31d7c">
](url)

**Comment by witchcraftsman** [comment]
And finish time calculation (which is also wrong) is possibly related
