### ISSUE TITLE
mosaic palette 2s compatibility

### ISSUE THREAD

**Issue by Cesare16** [SoftFever/OrcaSlicer#4820]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

it wouldn't be bad to have the compatibility of the mosaic palette 2\2s and others to manage the multicolored ones inside the printer, compatibility with klipper is already present but to date to be used you have to spend whole days configuring slicers such as ultimaker cura or prusa slicer to obtain mediocre and tedious prints.

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

Implementing a plug-in or slicer feature to configure the mosaic palette with a printer already present in the slicer.  automatic management of color change (without the infinite initial configuration of the Palette if this is possible).

**Comment by mikepersson** [comment]
+1
