### ISSUE TITLE
macOS x86-64: User-added printers disappear sometimes

### ISSUE THREAD

**Issue by odonnell944** [SoftFever/OrcaSlicer#4823]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

macOS

### OS Version

Ventura 13.6.4

### Additional system information

Macbook Pro 2015, 2.8 GHz i7, 16 gb RAM, 1TB SSD, nothing weird with the system in any other way

### Printer

Custom printer / Klipper machine based on Ender 3 V2

### How to reproduce

1. Add a new printer and spend a lot of time setting it up perfectly
2. Save the machine as a new User Preset or as a new printer
3. Quit Orcaslicer
4. Re-open it, and look for that printer as an option in the "Printer" sidebar

### Actual results

Half of the time, it's not there.
The JSON and INFO files are still there in the 'Application Support' directory, but are not being recognized.
Quitting and re-opening sometimes works. But I have had set up the same printer 4 times now, because it keeps disappearing and won't come back.

### Expected results

Printer does not disappear from available printer list, after initial setup and saving.

### Project file & Debug log uploads

[Example.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/14818664/Example.3mf.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by ZinovievOleg** [comment]
[pen holder](https://github.com/SoftFever/OrcaSlicer/issues/4792)

**Comment by ZinovievOleg** [comment]
The problems are [similar.](https://github.com/SoftFever/OrcaSlicer/issues/4792)
