### ISSUE TITLE
V2.0.0 is out and still no Kingroon printers on Linux version, but they exists opening the AppImage

### ISSUE THREAD

**Issue by mechano** [SoftFever/OrcaSlicer#4827]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

Linux

### OS Version

Ubuntu 23.10

### Printer

None I can't select the Kingroon KP3S Pro

### How to reproduce

Trying to add a printer, Kingroon are not listed and not selectable. On Windows version they exists. If the AppImage is opened using appimage tool the folders are there. 
It's the case sensitive problem already discovered and not fixed with the new version.

### Actual results

No Kingroon printers selectable.

### Expected results

Kingroon printers have to be listed between other brands.

### Project file & Debug log uploads

Create Printer section -> Select Vendor = No Kingroon brand printers

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by TexZeTech** [comment]
It seems to be though?
<img src="https://github.com/SoftFever/OrcaSlicer/assets/7254540/26d7a754-f73b-453d-9ad2-c372162a2067" width=80% height=80%>
