### ISSUE TITLE
End of scarf seam shows white seam dot using Apple MacOS

### ISSUE THREAD

**Issue by thomasschoenfeld** [SoftFever/OrcaSlicer#4830]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

macOS

### OS Version

14.4 / 12.7.4

### Additional system information

MacOS 14.4 on Apple MBP 16 M1
MacOS 12.7.3 on Apple MBP 13 intel

### Printer

Voron 2.4

### How to reproduce

using any scarf seam will produce the white gap dot at the end (comparing it to teaching tech's video where this is not the case with windows)

first picture is "teaching tech's" as reference about the expected result...
second picture is mine of how it looks in any of my tests.

<img width="1899" alt="scarf_seams_as_per_video" src="https://github.com/SoftFever/OrcaSlicer/assets/10574643/cc82d1f7-67b9-4b59-a417-ec015ef5a3eb">
<img width="1254" alt="scarf_seam_on_my_appleMacOS_Machines" src="https://github.com/SoftFever/OrcaSlicer/assets/10574643/3f2b90e8-ea40-4081-870f-23a8f6cf28cd">

### Actual results

seam gap white end dot is always created instead of omitted like it should be using scarf seam

### Expected results

white dot for seam gap should not be shown using scarf seam

### Project file & Debug log uploads

any object will do, tested on my on models as well as primitives, cylinder and cubes...

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Anything else?

any object will do, tested on my on models as well as primitives, cylinder and cubes...

**Comment by Noisyfox** [comment]
This is expected. TT's video uses an older version which does not show the scarf seam.
