### ISSUE TITLE
There are many cut off labels in the Keyboard Shortcuts window

### ISSUE THREAD

**Issue by danik-ik** [SoftFever/OrcaSlicer#4837]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

Linux

### OS Version

Linux Mint 21.3 Cinnamon

### Additional system information

System:
  Kernel: 6.5.0-26-generic x86_64 bits: 64 compiler: N/A Desktop: Cinnamon 6.0.4 tk: GTK 3.24.33
    wm: muffin vt: 7 dm: LightDM 1.30.0 Distro: Linux Mint 21.3 Virginia base: Ubuntu 22.04 jammy
Machine:
  Type: Desktop Mobo: ASRock model: A520M-ITX/ac serial: <superuser required>
    UEFI: American Megatrends v: P1.10 date: 08/24/2020
CPU:
  Info: 8-core model: AMD Ryzen 7 PRO 4750G with Radeon Graphics bits: 64 type: MT MCP
    smt: enabled arch: Zen 2 rev: 1 cache: L1: 512 KiB L2: 4 MiB L3: 8 MiB
  Speed (MHz): avg: 1985 high: 4266 min/max: 400/4454 cores: 1: 400 2: 400 3: 400 4: 2889
    5: 4169 6: 4266 7: 400 8: 2769 9: 400 10: 3851 11: 2976 12: 400 13: 400 14: 4046 15: 3599
    16: 400 bogomips: 114978
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm
Graphics:
  Device-1: AMD Renoir driver: amdgpu v: kernel pcie: speed: 8 GT/s lanes: 16 ports:
    active: DP-1,HDMI-A-1 empty: DP-2 bus-ID: 07:00.0 chip-ID: 1002:1636 class-ID: 0300
  Device-2: Logitech Webcam C270 type: USB driver: snd-usb-audio,uvcvideo bus-ID: 3-2:2
    chip-ID: 046d:0825 class-ID: 0102 serial: <filter>
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: amdgpu,ati
    unloaded: fbdev,modesetting,vesa gpu: amdgpu display-ID: :0 screens: 1
  Screen-1: 0 s-res: 3840x1080 s-dpi: 96 s-size: 1016x285mm (40.0x11.2") s-diag: 1055mm (41.5")
  Monitor-1: DisplayPort-0 mapped: DP-1 pos: right model: Philips PHL 243V7 serial: <filter>
    res: 1920x1080 hz: 60 dpi: 93 size: 527x296mm (20.7x11.7") diag: 604mm (23.8") modes:
    max: 1920x1080 min: 720x400
  Monitor-2: HDMI-A-0 mapped: HDMI-A-1 pos: primary,left model: Philips PHL 243V7
    serial: <filter> res: 1920x1080 hz: 60 dpi: 93 size: 527x296mm (20.7x11.7") diag: 604mm (23.8")
    modes: max: 1920x1080 min: 720x400
  OpenGL: renderer: AMD Radeon Graphics (radeonsi renoir LLVM 15.0.7 DRM 3.54 6.5.0-26-generic)
    v: 4.6 Mesa 24.1~git2404010600.3d68dd~oibaf~j (git-3d68dd7 2024-04-01 jammy-oibaf-ppa)
    compat-v: 4.6 direct render: Yes
Audio:
  Device-1: AMD Renoir Radeon High Definition Audio driver: snd_hda_intel v: kernel pcie:
    speed: 8 GT/s lanes: 16 bus-ID: 07:00.1 chip-ID: 1002:1637 class-ID: 0403
  Device-2: AMD Family 17h HD Audio vendor: ASRock driver: snd_hda_intel v: kernel pcie:
    speed: 8 GT/s lanes: 16 bus-ID: 07:00.6 chip-ID: 1022:15e3 class-ID: 0403
  Device-3: Logitech Webcam C270 type: USB driver: snd-usb-audio,uvcvideo bus-ID: 3-2:2
    chip-ID: 046d:0825 class-ID: 0102 serial: <filter>
  Sound Server-1: ALSA v: k6.5.0-26-generic running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet vendor: ASRock driver: r8169
    v: kernel pcie: speed: 2.5 GT/s lanes: 1 port: f000 bus-ID: 03:00.0 chip-ID: 10ec:8168
    class-ID: 0200
  IF: enp3s0 state: up speed: 1000 Mbps duplex: full mac: <filter>
  Device-2: Intel Dual Band Wireless-AC 3168NGW [Stone Peak] driver: iwlwifi v: kernel pcie:
    speed: 2.5 GT/s lanes: 1 bus-ID: 04:00.0 chip-ID: 8086:24fb class-ID: 0280
  IF: wlp4s0 state: up mac: <filter>
  IF-ID-1: br-440a152ade08 state: down mac: <filter>
  IF-ID-2: br-68923040f141 state: down mac: <filter>
  IF-ID-3: br-6b8a6516ba64 state: down mac: <filter>
  IF-ID-4: br-b6e2661fdbba state: down mac: <filter>
  IF-ID-5: br-e4275738629e state: up speed: 10000 Mbps duplex: unknown mac: <filter>
  IF-ID-6: cscotun0 state: unknown speed: 10000 Mbps duplex: full mac: N/A
  IF-ID-7: docker0 state: down mac: <filter>
  IF-ID-8: veth550f046 state: up speed: 10000 Mbps duplex: full mac: <filter>
  IF-ID-9: vethe3da193 state: up speed: 10000 Mbps duplex: full mac: <filter>
Bluetooth:
  Device-1: Intel Wireless-AC 3168 Bluetooth type: USB driver: btusb v: 0.8 bus-ID: 1-9:5
    chip-ID: 8087:0aa7 class-ID: e001
  Report: hciconfig ID: hci0 rfk-id: 0 state: down bt-service: enabled,running rfk-block:
    hardware: no software: yes address: <filter>
Drives:
  Local Storage: total: 447.13 GiB used: 337.3 GiB (75.4%)
  ID-1: /dev/sda vendor: Kingston model: SA400M8480G size: 447.13 GiB speed: 6.0 Gb/s type: SSD
    serial: <filter> rev: K1B3 scheme: GPT
Partition:
  ID-1: / size: 218.95 GiB used: 153.29 GiB (70.0%) fs: ext4 dev: /dev/sda2
  ID-2: /boot/efi size: 486 MiB used: 6.1 MiB (1.2%) fs: vfat dev: /dev/sda1
  ID-3: /home size: 218.57 GiB used: 184.01 GiB (84.2%) fs: ext4 dev: /dev/sda3
Swap:
  ID-1: swap-1 type: file size: 2 GiB used: 256 KiB (0.0%) priority: -2 file: /swapfile
USB:
  Hub-1: 1-0:1 info: Hi-speed hub with single TT ports: 9 rev: 2.0 speed: 480 Mb/s
    chip-ID: 1d6b:0002 class-ID: 0900
  Device-1: 1-3:2 info: Logitech Keyboard K120 type: Keyboard,HID driver: hid-generic,usbhid
    interfaces: 2 rev: 1.1 speed: 1.5 Mb/s power: 90mA chip-ID: 046d:c31c class-ID: 0300
  Device-2: 1-4:3 info: Logitech M105 Optical Mouse type: Mouse driver: hid-generic,usbhid
    interfaces: 1 rev: 2.0 speed: 1.5 Mb/s power: 100mA chip-ID: 046d:c077 class-ID: 0301
  Device-3: 1-8:4 info: ASRock LED Controller type: HID driver: hid-generic,usbhid interfaces: 1
    rev: 1.1 speed: 12 Mb/s power: 100mA chip-ID: 26ce:01a2 class-ID: 0300 serial: <filter>
  Device-4: 1-9:5 info: Intel Wireless-AC 3168 Bluetooth type: Bluetooth driver: btusb
    interfaces: 2 rev: 2.0 speed: 12 Mb/s power: 100mA chip-ID: 8087:0aa7 class-ID: e001
  Hub-2: 2-0:1 info: Super-speed hub ports: 3 rev: 3.1 speed: 10 Gb/s chip-ID: 1d6b:0003
    class-ID: 0900
  Hub-3: 3-0:1 info: Hi-speed hub with single TT ports: 4 rev: 2.0 speed: 480 Mb/s
    chip-ID: 1d6b:0002 class-ID: 0900
  Device-1: 3-2:2 info: Logitech Webcam C270 type: Video,Audio driver: snd-usb-audio,uvcvideo
    interfaces: 4 rev: 2.0 speed: 480 Mb/s power: 500mA chip-ID: 046d:0825 class-ID: 0102
    serial: <filter>
  Hub-4: 4-0:1 info: Super-speed hub ports: 2 rev: 3.1 speed: 10 Gb/s chip-ID: 1d6b:0003
    class-ID: 0900
  Hub-5: 5-0:1 info: Hi-speed hub with single TT ports: 4 rev: 2.0 speed: 480 Mb/s
    chip-ID: 1d6b:0002 class-ID: 0900
  Hub-6: 6-0:1 info: Super-speed hub ports: 2 rev: 3.1 speed: 10 Gb/s chip-ID: 1d6b:0003
    class-ID: 0900
Sensors:
  System Temperatures: cpu: N/A mobo: N/A gpu: amdgpu temp: 58.0 C
  Fan Speeds (RPM): N/A
Repos:
  Packages: 3448 note: see --pkg apt: 3430 flatpak: 18
  No active apt repos in: /etc/apt/sources.list
  No active apt repos in: /etc/apt/sources.list.d/additional-repositories.list
  Active apt repos in: /etc/apt/sources.list.d/appimagelauncher-team-stable-jammy.list
    1: deb [signed-by=/etc/apt/keyrings/appimagelauncher-team-stable-jammy.gpg] https: //ppa.launchpadcontent.net/appimagelauncher-team/stable/ubuntu jammy main
  Active apt repos in: /etc/apt/sources.list.d/git-core-ppa-focal.list
    1: deb http: //ppa.launchpad.net/git-core/ppa/ubuntu jammy main
  Active apt repos in: /etc/apt/sources.list.d/google-chrome.list
    1: deb [arch=amd64] http: //dl.google.com/linux/chrome/deb/ stable main
  Active apt repos in: /etc/apt/sources.list.d/nodesource.list
    1: deb [signed-by=/usr/share/keyrings/nodesource.gpg] https: //deb.nodesource.com/node_19.x focal main
    2: deb-src [signed-by=/usr/share/keyrings/nodesource.gpg] https: //deb.nodesource.com/node_19.x focal main
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list
    1: deb http: //packages.linuxmint.com virginia main upstream import backport
    2: deb http: //archive.ubuntu.com/ubuntu jammy main restricted universe multiverse
    3: deb http: //archive.ubuntu.com/ubuntu jammy-updates main restricted universe multiverse
    4: deb http: //archive.ubuntu.com/ubuntu jammy-backports main restricted universe multiverse
    5: deb http: //security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
  Active apt repos in: /etc/apt/sources.list.d/oibaf-graphics-drivers-jammy.list
    1: deb [signed-by=/etc/apt/keyrings/oibaf-graphics-drivers-jammy.gpg] https: //ppa.launchpadcontent.net/oibaf/graphics-drivers/ubuntu jammy main
  Active apt repos in: /etc/apt/sources.list.d/skype-stable.list
    1: deb [arch=amd64] https: //repo.skype.com/deb stable main
  Active apt repos in: /etc/apt/sources.list.d/sublime-text.list
    1: deb https: //download.sublimetext.com/ apt/stable/
  Active apt repos in: /etc/apt/sources.list.d/tensor.list
    1: deb https: //update.sbis.ru/Sbis3Plugin/24.1232.33/linux/deb_repo ./
  Active apt repos in: /etc/apt/sources.list.d/winehq.list
    1: deb [signed-by=/usr/share/keyrings/winehq.gpg] http: //dl.winehq.org/wine-builds/ubuntu/ jammy main
Info:
  Processes: 578 Uptime: 7h 27m wakeups: 0 Memory: 30.73 GiB used: 23.67 GiB (77.0%) Init: systemd
  v: 249 runlevel: 5 Compilers: gcc: 11.4.0 alt: 11/12/8/9 Client: Cinnamon v: 6.0.4 inxi: 3.3.13

### Printer

Doesn't mean

### How to reproduce

Open the Keyboard Shortcuts dialog. Explore tabs content.

### Actual results

There are many labels that cut off.
![image](https://github.com/SoftFever/OrcaSlicer/assets/17652575/b28773c4-4c8c-465c-9410-e240a7e1b920)
![image](https://github.com/SoftFever/OrcaSlicer/assets/17652575/2406606e-0122-4fa1-a434-a04726633c02)
![image](https://github.com/SoftFever/OrcaSlicer/assets/17652575/d07e24fb-e93a-4668-a490-9732c908c9a2)
![image](https://github.com/SoftFever/OrcaSlicer/assets/17652575/cc2564ec-1feb-4426-a3f9-379c6109cb1e)
Other languages:
![image](https://github.com/SoftFever/OrcaSlicer/assets/17652575/4b6a5ea9-935d-49b9-9ee1-2fc7cabc32c9)
etc

### Expected results

There are no cut off labels

### Project file & Debug log uploads

Any project or an empty project

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by danik-ik** [comment]
Also in many other places, in other linux distribitions (Kubuntu for example)
![image](https://github.com/SoftFever/OrcaSlicer/assets/17652575/f09bf77f-ab3e-47e3-bc56-87dfc12d3a74)
Operating System: Kubuntu 20.04
KDE Plasma Version: 5.18.8
KDE Frameworks Version: 5.68.0
Qt Version: 5.12.8
Kernel Version: 5.4.0-173-generic
OS Type: 64-bit
Processors: 4 × Intel® Core™ i5-3320M CPU @ 2.60GHz
Memory: 7,6 ГиБ

**Comment by rotech** [comment]
I know this has been marked stale, but is still a present issue, but only in some dialogs, as per the shots below.


![Image](https://github.com/user-attachments/assets/3f24b759-8b0e-4b7a-9b06-9de868f92071)

![Image](https://github.com/user-attachments/assets/933e2743-c265-45cd-aae7-0ec92dd7eb56)
