### ISSUE TITLE
How can I print this shell with open hole

### ISSUE THREAD

**Issue by djonasdev** [SoftFever/OrcaSlicer#484]
I have the following shell (https://anonfiles.com/g17110e8za/shell_stl)

![shell](https://user-images.githubusercontent.com/17551597/225285881-096d46f1-c646-41da-8e2b-7ce5511d530c.gif)

I have already touched all the slicer settings, but every time, the hole is closed. Can someone please help me and tell me where to set the magic hook?

Thank you very much!

**Comment by Pmant** [comment]
This is most likely a problem with your STL.
![grafik](https://user-images.githubusercontent.com/5005155/225488045-853852a9-23b7-4201-a014-8a35edd68ffd.png)

**Comment by dojo90** [comment]
Thank you for your answers.
The problem is not with the STL file. When I repair the file, the slicer closes the hole with a lid. Just like the "bridge".

I also have the same problem when importing the *.STEP file.

I have also used some other models and everywhere I have the same phenomenon.

**Comment by SoftFever** [comment]
Can you check with 1.5.0?
![Screenshot 2023-03-18 004910](https://user-images.githubusercontent.com/103989404/225967902-0d61cbd1-d2e7-4248-9faa-0072a90a18c6.jpg)
Looks fine.
If you still got issues with 1.5.0, please save it to 3mf project file and share it here.
