### ISSUE TITLE
Printer profile for Artillery Sidewinder X4 PRO

### ISSUE THREAD

**Issue by bednarekpiotr** [SoftFever/OrcaSlicer#4849]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I cannot find profile for this printer

### Which printers will be beneficial to this feature?

Others

### Describe the solution you'd like

I would like to have profile for Artillery Sidewinder X4 PRO

**Comment by Cookie-fighter** [comment]
Same goes for the X4 plus. Of course they are very new.
But clearly it would be benefical to have a base profile.

**Comment by hybotics** [comment]
Please add the X4 Pro and X4 Plus profiles.

**Comment by dan4ik3d** [comment]
**I NEED IT cz Cura much better than @prusia**
