### ISSUE TITLE
Scarf seam: a G-Code path goes beyond the max print height

### ISSUE THREAD

**Issue by superfloh247** [SoftFever/OrcaSlicer#4853]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

c663f43

### Operating System (OS)

macOS

### OS Version

14.3.1

### Additional system information

apple silicon arm64

### Printer

Bambu P1P

### How to reproduce

slice example file

### Actual results

Scarf seam produces incorrect G-Code

### Expected results

correct G-Code

### Project file & Debug log uploads

[Scraf-seam-error.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/14849617/Scraf-seam-error.3mf.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by superfloh247** [comment]
might be related to #4754

**Comment by vgdh** [comment]
try PR https://github.com/SoftFever/OrcaSlicer/pull/4843

**Comment by superfloh247** [comment]
#4843 seems to fix this
