### ISSUE TITLE
Outer wall wiping removed by elephant foot compensation + other settings

### ISSUE THREAD

**Issue by czlr** [SoftFever/OrcaSlicer#4859]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

Windows

### OS Version

Windows 10 Education

### Printer

Bambu P1S

### How to reproduce

1. Start from the attached project file
2. Slice with [Elephant foot compensation] enabled. E.g., 0.15mm to see the issue

### Actual results

On layer 1, the outermost wall isn't ended with a wipe operation. Note: "wipe" in this case means the wiping associated with retractions, via [Wipe while retracting].

![image](https://github.com/SoftFever/OrcaSlicer/assets/37885627/f83f5e91-559d-44cb-acf1-73cf09a83e71)

**Other things I noticed:**
1. The issue might be from a combination of [Avoid crossing walls]=ON and [Elephant foot compensation]>0. Since the issue doesn't happen with [Avoid crossing walls]=OFF and [Elephant foot compensation]=0.
2. As mentioned, setting [Elephant foot compensation]=0 fixes the issue. However, then setting [Seam position]=Nearest (previously "Aligned") seems to break it again. This shouldn't be related to Extruder [Travel distance threshold], since the z-hop still gets generated. Furthermore, setting [Arc fitting]=OFF (previously "ON") fixes the issue again. So there are some weird interactions here...
3. Not sure if related: "Inner/Outer/Inner" wall order doesn't generate correctly on Layer 1 with 2 walls. My attached settings have [Only one wall on first layer]=ON, but if you disable that, you'll see that "Inner/Outer/Inner" prints the inner wall before the outer wall. (Expected: with 2 walls, it should be printing the outer wall before inner wall, like "Outer/Inner") So at the very least, it seems to have special logic for layer 1.

### Expected results

Outer wall paths should be generated with wipes regardless of most other settings: [Elephant foot compensation], etc. In my mind, perhaps the only reason it'd be disabled would be if the next movement falls below the retraction [Travel distance threshold]. But whenever a z-hop + retraction is generated, I'd expect there to always be a corresponding wipe (when configured) too.

### Project file & Debug log uploads

[elephant_foot_wiping_bug.zip](https://github.com/SoftFever/OrcaSlicer/files/14857171/elephant_foot_wiping_bug.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by frech-tech** [comment]
Hey,
I have the same issue. With "elephant foot compensation" + "Avoid crossing walls" the wipe movment is missing. This leads to strange blobs near the seam. 
"elephant foot compensation = 0" + "Avoid crossing walls : Off" 
![Default](https://github.com/SoftFever/OrcaSlicer/assets/40495803/e6f93271-72be-4e1b-a782-f7fe9064968e)
"elephant foot compensation = 0.16" + "Avoid crossing walls: On" 
![EFC-on_ACW-on](https://github.com/SoftFever/OrcaSlicer/assets/40495803/69cc07d3-d804-4ad2-bcc7-c203c278b7cf)

**Comment by will-flaugher** [comment]
Seems potentially related to the issue in #4226, in case it helps to either consolidate work or have more data to review.

**Comment by CDFER** [comment]
Just to add few datapoints to help debug this I have basically the same issue with the 2.1.0 beta, (but I had the same problem in 2.0.0 too).  

### Simple Cube Test
#### Wipe working correctly with avoid crossing walls off:
![image](https://github.com/SoftFever/OrcaSlicer/assets/24196189/a116cb62-f433-4f5d-908d-40b27b0962df)


#### Wipe missing with avoid crossing walls on:
![image](https://github.com/SoftFever/OrcaSlicer/assets/24196189/61ad065a-c4cf-4e15-ae28-d06e42866ef8)


Here is the test file:
[Cube_0.2mm_PETG_MINI_8m52s.zip](https://github.com/user-attachments/files/15523394/Cube_0.2mm_PETG_MINI_8m52s.zip)


### Shape Test
### Wipe works correctly with a cube but doesn't work with circular objects (10% infill)
![image](https://github.com/SoftFever/OrcaSlicer/assets/24196189/4a5101bd-3ad0-44f0-bcb1-ac38ff92439f)

### Wipe works on all objects (0% infill)
![image](https://github.com/SoftFever/OrcaSlicer/assets/24196189/02c8ac6f-9091-4325-9b7f-0c8cd4106c29)


Anyways this is beyond my programming skills but hopefully it helps you guys figure it out. I've really been impressed with OrcaSlicer, thanks for the amazing work you all have done :)
