### ISSUE TITLE
Variable line width at overhang.

### ISSUE THREAD

**Issue by vgdh** [SoftFever/OrcaSlicer#4863]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Because a wide line is better at overhang wouldn't it be great to have an automatic increasing width of the line at overhang while other lines are the same size.

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

Imagine the advantage of an automatic widening of lines specifically at overhangs, while maintaining consistent widths elsewhere. This dynamic adjustment in line width would optimize performance, particularly in instances of steeper overhangs, ensuring greater stability and precision in the output.
Steeper overhang - wider line.

**Comment by vgdh** [comment]
bump

**Comment by vgdh** [comment]
bump

**Comment by KeadonM** [comment]
This would be great
