### ISSUE TITLE
Orca Slicer not using Dedicated GPU on Laptop - Results in poor performance in Preview tab.

### ISSUE THREAD

**Issue by BloodSteyn** [SoftFever/OrcaSlicer#4865]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

Windows

### OS Version

Windows 11 Pro

### Additional system information

MSI Katana Laptop
CPU: i7-11800H 
RAM: 32GB DDR4 RAM 
dGPU: RTX 3060
iGPU: Intel UHD
[MSI-KATANA.txt](https://github.com/SoftFever/OrcaSlicer/files/14865407/MSI-KATANA.txt)

### Printer

Creality K1

### How to reproduce

1. Own a laptop with Dedicated GPU (dGPU) and Integrated GPU (iGPU)
2. Add "Primitive > Cylinder" to build plate.
3. Scale to 150x150x150
4. Slice Model and go to Preview Tab
5. Click/Drag Model around rapidly to check the rendering performance. Change to Flow view for even heavier GPU load.
6. Look at Task Manager to see that Orca Slicer is only using a single CPU Core and the iGPU instead of the dGPU 
![image](https://github.com/SoftFever/OrcaSlicer/assets/12842756/2fe4e7e7-edbb-43f6-ab5b-23b202715656)

7. Open Prusa/Creality Print (Cura), do the same steps above, and see in Task Manager that these slicers make use of the dGPU and more than one CPU Core. 
![image](https://github.com/SoftFever/OrcaSlicer/assets/12842756/0aae5040-db1f-40b6-b4c0-46d4471c88f5)

### Actual results

The performance in the Preview tab is terribly slow, even on simple models, as Orca Slicer does not seem to be making use of the available system resources, or Dedicated GPU as other Slicers do.

When viewing Task Manager's CPU Graphs, it is obvious that Orca Slicer is primarily making use of a single CPU thread while manipulating the model in the Preview tab:
![image](https://github.com/SoftFever/OrcaSlicer/assets/12842756/3b0f7009-3a6b-4b49-a23e-3b5a7b743bc6)

Whereas with PrusaSlicer you can see that more CPU Threads are being used: 
![image](https://github.com/SoftFever/OrcaSlicer/assets/12842756/46cb72b6-fc70-414b-b94e-cc7c91a3548f)

PrusaSlicer and Creality Print (Cura) is also using the Dedicated GPU, the RTX 3060, while Orca Sicer and Bambu Slicer are using the Integrated Intel UHD GPU.

The problem is present in Bambu Slicer (latest version tested), to a lesser extent however, as the rendering is much smoother, even though the iGPU is also being used instead of the dGPU.

### Expected results

The Preview tab should be rendering smoothly, with minimal delays when manipulating the view. Ideally, making use of the Dedicated GPU and more CPU Threads, instead of the weaker Integrated GPU.

### Project file & Debug log uploads

[TEST_Cylinder.zip](https://github.com/SoftFever/OrcaSlicer/files/14865789/TEST_Cylinder.zip)
[log.zip](https://github.com/SoftFever/OrcaSlicer/files/14865790/log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by lbibass** [comment]
you can go into windows settings and force the use of the discreet graphics. You'd want to go to system->display->graphics, and find orcaslicer in that menu. then change the GPU to High Performance. 

I'm not sure about the threading utilization.

**Comment by avxmw** [comment]
I'm having the same problem as @BloodSteyn , however for me it is under Linux.

Hardware: (2x) Xeon E5-2643v4, 128gb RAM, nvme drives, Nvidia GTX 960 (under nouveau drivers)
Debian 12.5, kernel 6.1.0-23, X11,Plasma 5.27.5/5.103.0, Orca Slicer 2.1.1 (.AppImage)

Everything works fine up to slicing and preview, preview itself is sluggish at best while resource usage is low/basically doesn't get used.

As they are related I tried Prusa Slicer 2.8 (Flatpak) and that is smooth as expected.

Running a virtual machine on that host, using Windows 10 and passing through 1 CPU and a RTX2060 the Windows version of Orca runs absolutely normal/smooth.

**Comment by SethPDA** [comment]
Hello @avxmw ,just a heads up: what @lbibass said works great.

**Comment by avxmw** [comment]
> Hello @avxmw ,just a heads up: what @lbibass said works great.

That sadly doesn't help me, as described my version on Windows runs fine, the Linux version is giving me trouble.

**Comment by clively** [comment]
Is there a solution for Win10?

**Comment by big-vl** [comment]
It is very strange that Orcaslicer still does not know how to slice on CUDA ))

**Comment by cdvankammen** [comment]
I am curious about this issue myself over the last couple years of using it I find that it only utilizes the cpu on almost every mac, windows and linux i work with it on especially when it comes to slicing and doing algorithms. Understanding this code is so many forks of older code, is there thoughts from the community on the possability of initiating this as becoming a thing? 

I would love to help, just have very little knowledge on HARDWARE/firmware type drivers and code stuff.
