### ISSUE TITLE
"FlyingBear Reborn3" is a mistake

### ISSUE THREAD

**Issue by ilko-k** [SoftFever/OrcaSlicer#4866]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

There are two problem with that profile. 1, the picture is wrongly mirrored. 2, its name is Reborn 2, not Reborn3. Also, there is a missing space in brand's name, _Flying Bear_.
Orca's picture
![image](https://github.com/SoftFever/OrcaSlicer/assets/5411848/da4f636a-015c-47f1-86bd-7d77a71fe01b)

Official picture
![image](https://github.com/SoftFever/OrcaSlicer/assets/5411848/e9ee6862-5e1d-4329-8407-480388333e06)

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

- Replace printer's image preview
- Rename "FlyingBear Reborn3" to "**Flying Bear Reborn 2**"
- Eventually, rename all occurences of "FlyingBear" to "**Flying Bear**" (brand name contains a space)
![image](https://github.com/SoftFever/OrcaSlicer/assets/5411848/6760c31a-21ad-4d6b-b955-1a17a9a16fd1)

Here is the png I've cut out and edge smoothed ready to use
[Reborn_2_preview.zip](https://github.com/SoftFever/OrcaSlicer/files/14871574/Reborn_2_preview.zip)

**Comment by cochcoder** [comment]
> 2, its name is Reborn 2, not Reborn3.

How are you sure about this? The bed size matches Reborn 3's size mentioned on their [website](https://3dflyingbear.com/collections/reborn-3/products/flying-bear-3d-printer-reborn-3-new-arrival).

**Comment by ilko-k** [comment]
> How are you sure about this? The bed size matches Reborn 3's size mentioned on their [website](https://3dflyingbear.com/collections/reborn-3/products/flying-bear-3d-printer-reborn-3-new-arrival).

Well, officially, there was no Reborn 3. Orca's preset was present before this printer was even released. The preview picture was wrong too (even now) because the official R3 has a logo and its name visible on front. Actually, [they removed](https://3dflyingbear.com/collections/reborn-3) the R3 for some reasons 
![Screenshot_20240502-145338_Firefox~01](https://github.com/SoftFever/OrcaSlicer/assets/5411848/e5fd0cf2-85b3-456b-a9e1-aa3ea7adf65d)
