### ISSUE TITLE
Obico server support (on-prem)

### ISSUE THREAD

**Issue by nikallass** [SoftFever/OrcaSlicer#4873]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Obico server on-prem installations doesn't support oauth (there is no such endpoint). So connecting fails.

### Which printers will be beneficial to this feature?

Klipper, Marlin

### Describe the solution you'd like

Please add another way to connect to obico home install.

### Additional context

Obico server: https://github.com/TheSpaghettiDetective/obico-server

**Comment by DVSVIDEO** [comment]
Obico has nothing to do with OrcaSlicer, or any slicer for that matter....
Obico must be installed on the system running the clipper (raspberry pi, linux).
It can be opened from a browser, even outside the local Wi-Fi range, using mobile net...

**Comment by nikallass** [comment]
> Obico has nothing to do with OrcaSlicer, or any slicer for that matter....
> 

Sorry, but what about sending files to print with klipper+obico installed (without OctoPrint).
