### ISSUE TITLE
Adaptive bed mesh generates unusable probe count on large machines

### ISSUE THREAD

**Issue by jan3ll3** [SoftFever/OrcaSlicer#4875]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

Windows

### OS Version

windows 10

### Printer

Custom 500mm based on ratrig profile - running klipper

### How to reproduce

I sliced an object that is 267mm by 72mm. 
mesh min to 25,45  
mesh max to 480,480
probe point distance 40,40
mesh margin 5

### Actual results

the output from this: 

BED_MESH_CALIBRATE mesh_min=104.192,204.609 mesh_max=390.808,296.61 ALGORITHM=lagrange PROBE_COUNT=8,3 ADAPTIVE=1 ADAPTIVE_MARGIN=0

to which klipper gives error :  
!! bed_mesh: cannot exceed a probe_count of 6 when using lagrange interpolation. Configured Probe Count: 7, 3

if forcing bicubic there is also a probe count error for a difference reason

### Expected results

I would expect it wouldnt be difficult to force a certain probe count to make klipper happy

### Project file & Debug log uploads

[Cube_0.16mm_PETG_2h11m.zip](https://github.com/SoftFever/OrcaSlicer/files/14878211/Cube_0.16mm_PETG_2h11m.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by igiannakas** [comment]
A PR with a potential fix has been posted - please test the code build there and report back
