### ISSUE TITLE
OrcaSlicer deletes printer profile if its start gcode have backslash char at the very end

### ISSUE THREAD

**Issue by fifonik** [SoftFever/OrcaSlicer#4877]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

1.9.1

### Operating System (OS)

Linux, Windows

### OS Version

Windows 10, Linux Mint

### Printer

does not matter

### How to reproduce

Backup printer profile you testing it with as the profile will be deleted.

1. Open OrcaSlicer
2. Open Printer Profile
3. Add backslash character at the very end of start gcode
4. Save Printer Profile
5. Exit OrcaSlicer
6. Check that the Printer Profile file is still exist
7. Start OrcaSlicer. Printer Profile is not visible in dropdown and its file deleted

### Actual results

The edited Printer Profile will be lost (profile file deleted on OrcaSlicer start)

### Expected results

The edited Printer Profile not lost

### Project file & Debug log uploads

[log.zip](https://github.com/SoftFever/OrcaSlicer/files/14879314/log.zip)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by JCraftHeart** [comment]
Having same issues right now..
