### ISSUE TITLE
Base pattern not working for support infill

### ISSUE THREAD

**Issue by neilricketts** [SoftFever/OrcaSlicer#4883]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

Windows

### OS Version

windows 10

### Printer

zerog mercury one.1

### How to reproduce

when i select base pattern in the support tab, advanced section. When I select any of the base patterns Rectanglar, Rectanglar grid, octagon or lightning and slice a file. When i check the support infill it is always hollow regardless of what support base pattern i use. I currently have it set to 2.5mm spacing but this has no effect either

### Actual results

![Capture](https://github.com/SoftFever/OrcaSlicer/assets/166138941/c3cbe64a-855e-468a-8d42-ae9f9d819ad0)
![Capture1](https://github.com/SoftFever/OrcaSlicer/assets/166138941/7bcc8cca-7d9b-46e6-8325-6f1865ad23f7)
Has seen in the screen captures not base pattern has been created. This feature works fine in bambu studio slicer but not the latest orcaslicer.

### Expected results

It should create a hexagon infill pattern within the organic support. I have included the bambustudio screen capture to show what should happen.
![Capture2](https://github.com/SoftFever/OrcaSlicer/assets/166138941/6ebd2579-4065-41bb-9558-a5619493eaa6)

### Project file & Debug log uploads

[V5 Airbrush.zip](https://github.com/SoftFever/OrcaSlicer/files/14885820/V5.Airbrush.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by DVSVIDEO** [comment]
Just choose another type of support and it works.
No padding for default and organic
For Slender wood, Strong wood and Hybrid wood, the default infill works:
![Fa](https://github.com/SoftFever/OrcaSlicer/assets/96373457/cddecd42-2396-4e4c-b79c-e552cce1d02b)
