### ISSUE TITLE
Add profile for Artillery Sidewinder X3 Pro

### ISSUE THREAD

**Issue by mirczas** [SoftFever/OrcaSlicer#4884]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Profile for Artillery Sidewinder X3 Pro does not exist.

### Which printers will be beneficial to this feature?

Others

### Describe the solution you'd like

I would like a profile for Artillery Sidewinder X3 Pro to be available.

**Comment by F1CU** [comment]
Any chance of a profile for the Artillery Sidewinder X3 Pro printer?
