### ISSUE TITLE
Bed temp drops from 100 to 50 when using support material

### ISSUE THREAD

**Issue by DimitryNechaev** [SoftFever/OrcaSlicer#4889]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0

### Operating System (OS)

Windows

### OS Version

Windows 11

### Printer

Snapmaker J1

### How to reproduce

Slice with 2 filaments: extruder 0 hi temp (abs etc) and extruder 1 support (pva etc)
The support material has "is support" ticked in the properties

While printing it starts with bed temp 100 and then drops to 50. 
If support filament has bed temp set to 0 it will drop to 0

The workaround is to set the support filament bed temp to the main filament temp

### Actual results

In the beginning of the file it sets bed temp to the support filament temp.
Here is an example with support set to 0

![image](https://github.com/SoftFever/OrcaSlicer/assets/12892631/e478e539-5f46-4011-bda9-309f72023a7f)

### Expected results

Support filament does not have it's own bed temperature. It is removable part of the print.
When printing 2+ filaments the bed temp has to stay at the highest, otherwise the model will curl and peel off.

### Project file & Debug log uploads

[Orca.zip](https://github.com/SoftFever/OrcaSlicer/files/14891560/Orca.zip)
[Right_R3c_0.16mm_2h24m.gcode.zip](https://github.com/SoftFever/OrcaSlicer/files/14891562/Right_R3c_0.16mm_2h24m.gcode.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by vgdh** [comment]
Sometimes I have a temperature issue when print with multiple materials. 
The bed temp is not set to second temperature after the initial layer is done.
