### ISSUE TITLE
Creality K1C - {"code":"key61, "msg":"Unknown command:M191", "values": ["M191"]}

### ISSUE THREAD

**Issue by Scootworks** [SoftFever/OrcaSlicer#4904]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

macOS

### OS Version

Sonoma 14.4.1

### Printer

Creality K1C

### How to reproduce

During every print, this message pops up (in Fluidd)

### Actual results

the print continues without an issue

### Expected results

the print continues without an issue

### Project file & Debug log uploads

[github.zip](https://github.com/SoftFever/OrcaSlicer/files/14895070/github.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by vgdh** [comment]
You have enabled chamber temperature control enabled in filament settings.
Disabling it will solve your problem.

**Comment by Scootworks** [comment]
> You have enabled chamber temperature control enabled in filament settings. Disabling it will solve your problem.

thank you very much for your feedback. You are right.
