### ISSUE TITLE
The word "Timelapse" is not well translated into English.

### ISSUE THREAD

**Issue by AlcaDroid** [SoftFever/OrcaSlicer#4907]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

1.9.1

### Operating System (OS)

Windows

### OS Version

Windows 11 Pro

### Additional system information

Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz   3.19 GHz
Nvidia 3060
32,0 GB

### Printer

Bambu Lab X1 Carbon

### How to reproduce

1.- By clicking on "Print Tray".
2.- The send print job window appears with the error.
![Captura](https://github.com/SoftFever/OrcaSlicer/assets/128694930/2d637558-0428-4fdf-91e3-4414af5b6ae8)

### Actual results

The word "Timelapse" is translated as "Interval".

### Expected results

This word is used in Spanish as it is in its original language... "Timelapse".

It should not be translated. 

### Project file & Debug log uploads

It's just a translation error.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Rickthebig** [comment]
Timelapse is not a Spanish word. Of course it should be translated. Abide by the chosen language. Mixing languages is frawn upon in all spanish speaking societies known to me.

**Comment by AlcaDroid** [comment]
Ok... I respect your opinion.
But I see that you don't know the Spanish language very well... our language has many English words added to the dictionary as its own and they are not translated, words Football, Banner, Casting, etc.
Nobody understands that translation or what it refers to... I'm tired of explaining it in Spanish forums.
But hey, it's your software and you decide.
Greetings.

**Comment by Rickthebig** [comment]
Ustéd está confundido, usando esas palabras de idioma extraño sin necesidad. El idioma Español no escaza de palabras apropriadas para describir lo que sea. 
Yo digo simplemente:
fútbol, bandelora, fundido. No hay dificultad y el significado no cambia.
Se toman fotos en intervalos de tiempo. "Intervalo" es una buena aproximación y es inequívoca en ese contexto (a menos que no conozcan esa función, entonces no ayuda tampoco el idioma Inglés).

Exagerando esa postura suya, hay personas que intentan usar muchas palabras del idioma Inglés, porque se sienten mas cultivados - porque no lo son. Una moda deplorable.

**Comment by AlcaDroid** [comment]
Ok... I respect and understand your position.
I don't want you to feel bad about my comment, it's simply an idea that I have told you seeing that they asked many times on the Spanish bambulab channel on Telegram where the "timelap" was activated that they couldn't find.
I'm glad to know that you are here to listen to all the ideas even if some don't seem right like mine.
Thank you and I'm sorry.

Greetings, and congratulations on the program.

**Comment by AlcaDroid** [comment]
By the way... and just as a detail.
(I just saw it right now..)
Can you check what it says in Bambu Studio...?

It's curious right..?

![Captura](https://github.com/SoftFever/OrcaSlicer/assets/128694930/233b33f3-4b25-471e-8515-388876cb4058)
![Captura](https://github.com/SoftFever/OrcaSlicer/assets/128694930/57eae7e9-2ece-4b0e-9a23-79551cc246e1)
