### ISSUE TITLE
Brim Height

### ISSUE THREAD

**Issue by FraserJB** [SoftFever/OrcaSlicer#4910]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Warping occours with some materials (especially ABS). 
It would be useful to be able to secure some models more firmly to the bed. 
The brim works well for this, but is limited to a single layer.

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

Add an option for additional Brim layers (similar to the skirt height option that is already implemented).

### Describe alternatives you've considered

1. Use of skirt...however cannot be attached to the model, where multiple objects are being printed.

**Comment by Evixone** [comment]
An adjustable layer height for the edges would be extremely useful, especially for those who have a cold plate or other with very good adhesion and who use PETG for example, at the end of printing to remove the edges of a single layer is a very difficult mission...
being able to select the number of layers of the edge, especially for tree supports, would be a great help in removing them from the plate.
