### ISSUE TITLE
BambuSource.dll FAILED to load - Windows 11

### ISSUE THREAD

**Issue by Dochartaigh** [SoftFever/OrcaSlicer#4922]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0 - newest on GitHub

### Operating System (OS)

Windows

### OS Version

Windows 11 arm, just installed today, NOTHING else on PC...

### Printer

Bambu Labs X1 Carbon Complete

### How to reproduce

1. Install Orca Slicer from the newest V2.0 on this GitHub
2. Choose your printer and filaments from the list (X1)
3. Click on "user/login" to log into web with your password
4. Go to "Device Tab"
5. Click on Camera icon to see a live feed
6. Tells you you'll have to accept 2x registry edits (which went fine), then this DLL error pops up:

### Actual results

[Error](https://github.com/SoftFever/OrcaSlicer/assets/23370177/59c036bf-b498-41bc-b613-c1bcc12ddcdd)
 

### Expected results

not have a .DLL error so I can use OrcaSlicer with my Bambu X1C properly. 

### Project file & Debug log uploads

[EMPTY Orca Slicer file.zip](https://github.com/SoftFever/OrcaSlicer/files/14900619/EMPTY.Orca.Slicer.file.zip)
[Debug_Logs.zip](https://github.com/SoftFever/OrcaSlicer/files/14900620/Debug_Logs.zip)

The orca file is empty of an object/model... but you said to upload it so there it is.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Anything else?

nothing else

**Comment by ItsJupiter21** [comment]
Installing Bambuslicer fixed it for me as a hotfix
