### ISSUE TITLE
Monotonic ordering for all top/bottom layer patterns

### ISSUE THREAD

**Issue by C705** [SoftFever/OrcaSlicer#4924]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Only "Monotonic Line" follows monotonic ordering when printing a top/bottom layer. For all other top/bottom layers, the tool head follows what ever random path the slicer comes up with. It leads to unsightly top/bottom layers. Why does the tool head make a print move and then stop at an obstacle such as a hole and switch to the opposite end of the object for no logical reason to continue there only to come back to where it started. Hilbert Curve and concentric are the worst for this which leaves visible imperfections in the top/bottom layer. Unless there is only one obstacle or no obstacle, it is not possible to force the tool head to print top/bottom layers in an ordered fashion that would to avoid the tool head printing the top/bottom layer in random sections.

Cura has a feature called "monotonic ordering for top/bottom layers". It would be super if Orca Slicer could provide this feature.

I've added in image to explain.

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

For top layers specifically, Orca Slicer should be able provide a lock (tick box) that allows the user to control the path the tool head follows when completing the top layer.

Currently, Orca generates an ordered path for the tool head if the top layer has no obstacles around which to print. But, if the top layer has multiple objects around which to print, the slicer generates g-code that sends the tool head in a random un-ordered path resulting in the printing of the top layer in disconnected sections. Eventuality it all comes together but due to the nature of cooling, you can clearly see the tool head didn't follow a "locked" path from one side of the part to the opposite end as it prints the top layer. 

Suppose there are 20 moves to complete the top layer. The ideal would be to allow "top/bottom layer ordering" which would force the tool head to print each move in order irrelevant of any obstacles it may encounter, so 1, 2, 3, 4 etc, instead of 1, 2, 5, 14, 6 etc. 

In the example shown in the attached picture, you'll see holes around which the tool head had to print. It did not complete the top layer print moves in order. Instead, when it encountered the holes, it moved to a completely different location to complete print moves there, and eventually came back to where it left off. By that time, the material deposited there will have had such a long time to cool, any newly deposited material doesn't look like it was printed directly after the previous print move. 

### Describe alternatives you've considered

1. Use Cura - Not interested, I prefer Orca.
2. Use Monotonic line, since it seems to be the only top layer pattern to follow an ordered path to completion.

![IMG_20240331_135322_edit_428392914787204](https://github.com/SoftFever/OrcaSlicer/assets/76010902/d02add0c-d1e9-4772-941b-150fa731a148)

**Comment by idallenz** [comment]
I would like to see the same setting added!

**Comment by dosdroid** [comment]
Please Cura has this for ages and it works beautifully.
