### ISSUE TITLE
Almost infinitely high layer that randomly occurs.

### ISSUE THREAD

**Issue by Justinhirsh** [SoftFever/OrcaSlicer#4934]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

Windows

### OS Version

Windows 11

### Printer

Bambu Lab P1S

### How to reproduce

I'm really not sure, it just randomly happens

### Actual results

![Screenshot 2024-04-08 172814](https://github.com/SoftFever/OrcaSlicer/assets/108744039/9a0ed821-b7ef-4e8c-a808-9b61173b3627)

### Expected results

This layer with a height of 925440.00 randomly appears, causing errors.

### Project file & Debug log uploads

[https://drive.google.com/file/d/1XquywELTbihvlTIT0E5SFXWynOoLzr2k/view?usp=sharing](url)

In terms of Project files, I didn't save the original project so I tried my best to replicate it but im not totally sure if its exact.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Anything else?

This has happened before to other projects in the last version.

**Comment by Noisyfox** [comment]
Same as #4853 and has been fixed in the latest nightly build.
