### ISSUE TITLE
Incorrect slicing  of holes when import model from stp file

### ISSUE THREAD

**Issue by DrBlast** [SoftFever/OrcaSlicer#4942]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

Linux

### OS Version

Ubuntu 23.04

### Additional system information

CPU: Intel 13600k
Mem: 32gb

### Printer

Ender 3 S1 (klipper)

### How to reproduce

Model has a variable diameter hole
Add stp and stl of the same model and run slice

### Actual results

Without slicing both models looks like the same
![image](https://github.com/SoftFever/OrcaSlicer/assets/3791587/58d57178-ea96-4bef-9ede-cec9cb397eb5)

Wrong slicing on layer where hole diameter changes,  
stp - upper model
stl - bottom one
![image](https://github.com/SoftFever/OrcaSlicer/assets/3791587/251c6d2e-947e-4d34-917e-86d0c2769115)

### Expected results

Both models slices corrently

### Project file & Debug log uploads

[debug_Tue_Apr_09_17_08_52_82806.log.zip](https://github.com/SoftFever/OrcaSlicer/files/14919620/debug_Tue_Apr_09_17_08_52_82806.log.zip)
[WD-40_Big_Blast_Replacement_Nozzle.zip](https://github.com/SoftFever/OrcaSlicer/files/14919623/WD-40_Big_Blast_Replacement_Nozzle.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Anything else?

Original model downloaded from: https://www.thingiverse.com/thing:6548786/files

**Comment by foreachthing** [comment]
Well, after importing this STEP, one thing was clear: I was faulty from the begin with.
![image](https://github.com/SoftFever/OrcaSlicer/assets/10420187/735c4285-2832-43a5-8a2d-acaf345634f3)

After fixing it:
![image](https://github.com/SoftFever/OrcaSlicer/assets/10420187/616b059f-073a-4877-9aa3-000dda71a3c0)
