### ISSUE TITLE
Live camera feed to match camera aspect ratio

### ISSUE THREAD

**Issue by MrDB42** [SoftFever/OrcaSlicer#4946]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I really don't like the cinematic black bars at the top and bottom of my live video feed from my camera on the "Device" tab. It would be nice to have the aspect ratio to match the camera's aspect ratio.

Bambu Lab corrected this their "1.9.0 Public beta2" build.

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

The solution would be to just take the video feed and display in its native aspect ratio as sent.

**Comment by mordhau5** [comment]
is this also causing all elements in the device tab to the right of the camera to get shoved over (and off screen)?
