### ISSUE TITLE
Incorrect, strange icon

### ISSUE THREAD

**Issue by GP3D84** [SoftFever/OrcaSlicer#496]
**Describe the bug**
in list view the icon is not visible
this does not happen in other views

**To Reproduce**
by selecting list view

**Screenshots**
![Screenshot 2023-03-17 alle 19 07 27](https://user-images.githubusercontent.com/120025021/225985501-376bf292-33c7-4914-a04f-cc10b1ce5bfe.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Version Ventura (intel)
 - Latest OrcaSlicer (Release)

**Comment by mmackowiak** [comment]
Still present in 1.6.1.

**Comment by richard-scott** [comment]
I've just noticed this on 1.6.4-beta3.

**Comment by richard-scott** [comment]
Still there in 1.6.6.

![Screenshot 2023-08-24 at 14 01 30](https://github.com/SoftFever/OrcaSlicer/assets/5149834/2dfe21c0-880a-42d8-baca-c93711712e2b)
