### ISSUE TITLE
Unnecessary movements for adjacent walls slicing cause severe stringing issues

### ISSUE THREAD

**Issue by ualinker** [SoftFever/OrcaSlicer#4963]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

macOS

### OS Version

macOS X 14.4.1 Sonoma

### Additional system information

M1 Max 32GB

### Printer

Bambu Lab P1

### How to reproduce

Using default settings for process "0.2mm Standard @ BBL X1C"
Filament: Generic PETG
Mind unnecessary jumps to other side while slicing walls here (gif 1):
![CleanShot 2024-04-10 at 03 18 47](https://github.com/SoftFever/OrcaSlicer/assets/918275/f09c3309-11da-42b4-8647-f4f2f9dbd254)

Surprisingly, if you cut the bottom part, same region is sliced properly (next adjacent wall is started where the previous finished) (gif 2):
![CleanShot 2024-04-10 at 03 16 58](https://github.com/SoftFever/OrcaSlicer/assets/918275/35404750-d73b-455c-ae5e-b43ad0e5114b)

Also, if you set 0.6 for all line widths - the first model is sliced properly as well. Also same model sliced properly in Bambu Studio 1.8.4.51 with same settings.

These jumps cause severe stringing issues during print. Compare sliced in the manner of gif 1 on the left and sliced as depicted in gif 2 on the right:
![IMG_5862 — велике](https://github.com/SoftFever/OrcaSlicer/assets/918275/bb0d8886-9991-4e3a-a9bb-9b655b3b6879)

### Actual results

- Unnecessary jumps during slicing of adjacent walls

### Expected results

- No unnecessary jumps (the next adjacent wall starts where the previous finished)

### Project file & Debug log uploads

[orca_bug.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/14938406/orca_bug.3mf.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by Naninani** [comment]
same issue I have. PA/retraction tuning has no effect.
