### ISSUE TITLE
Unable to reconnect to server after mac wakes from sleep without restarting orca slicer

### ISSUE THREAD

**Issue by realien-OG** [SoftFever/OrcaSlicer#4974]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

macOS

### OS Version

Ventura 13.6.6

### Additional system information

Mac Book Pro 16" 64Gb ram.

### Printer

Bambu X1 Carbon

### How to reproduce

Start Orca slicer
Print something
allow mac to go to sleep (must be asleep for at least 5 minutes)
Wake Mac
Select "device" tab
"connecting to server" is displayed and you can't reconnect without restarting orca slicer

### Actual results

Unable to connect to the printer to print or view the device status

### Expected results

Earlier versions of Orca Slicer reconnected after mac woke from sleep.

### Project file & Debug log uploads

This has nothing to do with a project file; it happens with anything.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by realien-OG** [comment]
Changing my steps. if the printer is actively printing and orca slicer is on the device tab, it appears to stay connected.  If the printer is idle and no. model is being printed, that is when it appears to be unable to re-connect after wake from sleep.

**Comment by aamanley** [comment]
I'm having this issue as well. Constantly getting the failed to reconnect error after waking the Mac from sleep. I have been using the log out out of my account and logging back in method to get the printers to be recognized.

**Comment by batkov** [comment]
2.2.0 issue persists

**Comment by zxaos** [comment]
This is extremely annoying. A side effect of this for me is that orcaslicer will be unable to print if the printer is running while the sleep occurs until I fully close it (and I sometimes have to re-open Bambu Studio to "unstick" it)!

This is still an issue, please re-open.

**Comment by D00mkitty** [comment]
I am dealing with this as well 2.3.0

**Comment by aamanley** [comment]
I am as well, this issue never went away for me.
