### ISSUE TITLE
Possibility to remove the purge in the chute at the start of everyprint

### ISSUE THREAD

**Issue by meilleur102** [SoftFever/OrcaSlicer#498]
Printer => P1P
OrcaSlicer => 1.5.0
Os => W11

Title pretty tell it all. 
Having a option to disable the purge, 
The purge line at the start is good enought if you don't change the filament imo.

**Comment by hliebscher** [comment]
witch printer witch version of orca and os ?

**Comment by meilleur102** [comment]
Sorry My bad. Ill Edit the first post
