### ISSUE TITLE
PA Pattern test in Orcaslicer 2.0.0 doesn't respect filament VFR

### ISSUE THREAD

**Issue by psiberfunk** [SoftFever/OrcaSlicer#4998]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0 release

### Operating System (OS)

Windows

### OS Version

Windows 11

### Printer

Bambu X1C

### How to reproduce

1) New project
2) Pick default bambu 0.2 standard profile.
3) Set your filment VFR Flow max to 9.7.
4) Setup a PA "Pattern" test
5) Slice

### Actual results

Observe that the PA pattern test does not respect the flow rate limits properly, and shows PA lines printing faster than the VFR max limit set in the filament.  Here, shown as hitting 10.42, when it should be limited to 9.7!

![image](https://github.com/SoftFever/OrcaSlicer/assets/19777571/3b2f9421-146b-4a70-9658-551296f7fd47)

### Expected results

The max speed of the calibration lines should be equal to or slightly less than the max VFR.

### Project file & Debug log uploads

[Pressure Advance Test.zip](https://github.com/SoftFever/OrcaSlicer/files/14969175/Pressure.Advance.Test.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by SoftFever** [comment]
I can't repro it in 2.1.0 beta.
To update the maximum print volume setting, please ensure that you save your current filament profile and then re-run the test. This will apply the new max volume value.

**Comment by psiberfunk** [comment]
I will check the latest beta later today

**Comment by psiberfunk** [comment]
Just checked , loaded the project file in Beta 2.1 @SoftFever  and it still happens !

**Comment by psiberfunk** [comment]
Reproduction screenshot:  
![image](https://github.com/SoftFever/OrcaSlicer/assets/19777571/19007b4e-f88b-4053-816a-2d3a806e84f0)
