### ISSUE TITLE
Option to Change Solid Infill Pattern

### ISSUE THREAD

**Issue by djngnear** [SoftFever/OrcaSlicer#50]
It would be great to port over Superslicer's solid infill pattern settings option. And also add a skirt height option. I like using a skirt but when it's only 1 layer tall, it can be tough to remove at times. I usually make mine 3 layers tall.

**Comment by SoftFever** [comment]
The skirt height has been added in the dev branch. #20 

Please add more details and use scenarios for the feature you are asking for.
This shall help me or other potential contributors to evaluate it.

-SoftFever

**Comment by ShryuKt** [comment]
I don't know if that's what @djngnear  talking about, but one option I like on superslicer is the "Not Connected" infill
![image](https://user-images.githubusercontent.com/115975090/209578968-d19e1918-4d7e-4c3d-b134-c48436532abe.png)
with an infill_overlap of 25%
![image](https://user-images.githubusercontent.com/115975090/209579143-aeb96c4e-3021-41dd-9f21-124ff2b56eb0.png)
this is one (or the only) option that prevents me from switching to bambu studio full time

**Comment by djngnear** [comment]
Yeah I was just talking about changing the pattern of the solid infill

![Bambu Studio Infill Settings Screenshot](https://user-images.githubusercontent.com/87901234/210125885-6e564a6e-224a-4564-96e0-f68c2508f793.png)
