### ISSUE TITLE
Slow down for internal solid infill overhangs

### ISSUE THREAD

**Issue by Ataraxia-Mechanica** [SoftFever/OrcaSlicer#5003]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

For sloped external surfaces, the inner surface effectively becomes an overhang, but the innermost part of the infill is printed at full speed with fan off. This causes them to curl up and form surface defects.
![aaaaaaaaaa](https://github.com/SoftFever/OrcaSlicer/assets/111327195/8dcfe6a9-1a6a-439e-b21b-4c6d52242d9d)

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

Slow down and enable fans for internal solid infill if they form an overhang

### Describe alternatives you've considered

Turning off detect narrow infill seems to lessen the impact of printing on mid air, but it slows the printer down, especially when it comes to low acceleration machines.

**Comment by igiannakas** [comment]
Enable the dont filter out small internal bridges (beta) option. Set it to Limited filtering. This should create a bridge layer in areas where internal overhangs are present (which is the right way to solve this). If you are still not getting bridges, set it to No filtering

![image](https://github.com/SoftFever/OrcaSlicer/assets/59056762/878e698f-383a-44ae-864c-5db69cdc4f8f)

**Comment by Ataraxia-Mechanica** [comment]
But it slows down further than no narrow infill detection :( 50% speed and 100% fan should make the overhang in the image printable.
Limited internal bridge filtering also causes bumps on steeper internal surfaces at least on both of my printers, which I solved by bumping the infill percentage up instead.

**Comment by hsinyu-chen** [comment]
have same issue on 20 degree gentle slopes ,the Limited filtering option not work seems only No filter works

**Comment by igiannakas** [comment]
> have same issue on 20 degree gentle slopes ,the Limited filtering option not work seems only No filter works

For very shallow slopes only the no filter gives the desired result. Not much that can be done for this unfortunately as allowing bridging for shallow slopes results in side effects for regular overhangs inside the models.

**Comment by ph0tic** [comment]
This issue and issue https://github.com/SoftFever/OrcaSlicer/issues/3847 are something that need to be done
