### ISSUE TITLE
OrcaSlicer AppImage shows 2 title bars

### ISSUE THREAD

**Issue by Kaympe20** [SoftFever/OrcaSlicer#5009]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

Linux

### OS Version

Fedora 39

### Additional system information

OS: Fedora 39
Desktop Environment: KDE Plasma

### Actual results

App shows 2 title bars
![Screenshot_20240414_150404](https://github.com/SoftFever/OrcaSlicer/assets/117483128/81224db6-ec07-4cff-b04c-30db055941cf)

### Expected results

Only 1 title bar should be shown at a time

### Project file & Debug log uploads

[log.zip](https://github.com/SoftFever/OrcaSlicer/files/14971857/log.zip)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by Firnthon** [comment]
Same on Ubuntu 24.04

**Comment by PollastreGH** [comment]
Same on EndeavourOS on KDE Plasma here

**Comment by MathisP75** [comment]
This is still an issue

**Comment by realRicFlair** [comment]
Seriously can someone please just fix this. its been litteral eons. Like how hard can it possibly be
