### ISSUE TITLE
Preferences Window - Incorrect Translation for associate files to Orca Slicer in German

### ISSUE THREAD

**Issue by Launert** [SoftFever/OrcaSlicer#501]
**Describe the bug**
In the preference window, the subsection where you can select the filetypes to associate with Orca Slicer, in German translation the text still states to associate to Bambu Studio

**To Reproduce**
Select Language as German in setting windows.

**Expected behavior**
Files should be associated to Orca Slicer, not Bambu Studio. Description should reflect that fact.

**Screenshots**
English:
![grafik](https://user-images.githubusercontent.com/47757241/226047922-ec7b573d-a06b-43b9-be1c-93cdda9b134e.png)

German: 
![grafik](https://user-images.githubusercontent.com/47757241/226048404-fc7b0e1d-ebcf-42a4-b167-699aebf5edf9.png)

**Printer model**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 21H2

**Comment by hliebscher** [comment]
sorry is fixed now is only in windows version i use mac

**Comment by Launert** [comment]
Perfect, no big deal anyways, just thought to report it.

**Comment by hliebscher** [comment]
@Launert  i have chenge the translation again if you fine pls close the bug request
look at 
#515

**Comment by Launert** [comment]
New translation look good. Thanks for the swift work!
