### ISSUE TITLE
☻Adjustable direction of successive layers lines

### ISSUE THREAD

**Issue by DVSVIDEO** [SoftFever/OrcaSlicer#5011]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

When I wanted to print a highly transparent object (LED diffuser) with transparent filament, I realized that I couldn't do it.
Each subsequent layer will have the only adjustable direction offset by 90 degrees.
This is useful 80% of the time because it enhances the object. However, in some cases this is not good (like the case mentioned above, where a lenticular lens-like effect would be needed)
https://www.youtube.com/watch?v=9qb25Gi4Jv0

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

Similar to Cura's solution, it should be possible to specify multiple values for the fill direction.
Eg: **Fill direction: 45;45** (would fill all layers in the same direction)
or:  **Fill direction: 45;0;23** (in this case, after three different directions, it would repeat)
and then **Direction of fill: 45;0** (would give the now default behaviour)
https://youtu.be/9qb25Gi4Jv0?si=caRIeX4IlOV8m7_I&t=715

**Comment by Ataraxia-Mechanica** [comment]
![image](https://github.com/SoftFever/OrcaSlicer/assets/111327195/5ac31a2b-d691-49ce-a0fa-63af1f4ec769)

Have you tried aligned rectilinear?

**Comment by DVSVIDEO** [comment]
> ![image](https://private-user-images.githubusercontent.com/111327195/322344379-5ac31a2b-d691-49ce-a0fa-63af1f4ec769.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyMDc4OTQsIm5iZiI6MTcxMzIwNzU5NCwicGF0aCI6Ii8xMTEzMjcxOTUvMzIyMzQ0Mzc5LTVhYzMxYTJiLWQ2OTEtNDljZS1hMGZhLTYzYWYxZjRlYzc2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNVQxODU5NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMzBiNWRjMGYzYzY4YjIwMmEzMmYxNGY0MGM1OTgxYjI2Njk0ODBhNzlkZDhjMDY2YzI2Y2M0ZmI5NzVmYWIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pTEVmLjhf1V9CaQx331nuOHwmAkWJLBzqiFuDzKVFaU)
> 
> Have you tried aligned rectilinear?

I'm not sure you understand the problem...
It's not the type of fill that matters, it's that two consecutive layers are made rotated exactly 90 degrees.
There is currently only one setting: the direction of the first layer fill. The next layer will be perpendicular to this set direction.
I would like to have a printout where all layers have the same orientation...

**Comment by DVSVIDEO** [comment]
Wow!

I didn't understand what the adjusted line was until now....
Thank you!
I guess I can close this one...

**Comment by DVSVIDEO** [comment]
A Suggested setting makes my suggestion unnecessary...
