### ISSUE TITLE
Please add a calibration test routine wizard

### ISSUE THREAD

**Issue by ph-zero** [SoftFever/OrcaSlicer#5014]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

No

### Which printers will be beneficial to this feature?

Klipper, Marlin, All

### Describe the solution you'd like

I would like if possible a script containing a calibration test routine in order for easier calibration steps for non-experienced users in a Wizard-like manner.

1 - The user selects his printer and FIrmware
2 - Select Filament
3 - Wizard offers a selection of tests to be run in order
4 - Generates G-codes for the tests automatically and waits for inputs from test results if needed, then generates further G-code, waits for further inputs
5 - After completing it automatically generates a calibrated profile for the selected printer.

*Would be nice:
1 - If the user could select which tests are to be done
2 - If the user could run the wizard for filaments alone as well (Temp tower, retraction, etc...)
3 - If the user could export the calibrated configuration in JSON format
4 - Suggestions for hardware adjustments based on certain results and failures (Like belt tensioning, wheel were-off, etc...)for

### Describe alternatives you've considered

While running the tests is easy on OrcaSlicer I noticed some new users do have several questions on how, which order, and to what they must re-do de calibrations. This feature would also allow an easier method for new users to get familiarized with different aspects of printer calibration.
While trying to explain that online to different friends some tend to mix things up and find it too difficult.
Most tutorials that are on YouTube are not always easy to follow, nor are in good digestible content, remembering the goal is to simplify things for new-comers to the community

**Comment by JaneSmith** [comment]
+1. Bambu Studio has this feature. Could it just be pulled from there?
