### ISSUE TITLE
Allow clamping min/max for adaptive layer height

### ISSUE THREAD

**Issue by eddydas** [SoftFever/OrcaSlicer#502]
**Is your feature request related to a problem? Please describe.**
I'd love to use adaptive layer height, but right now it would use crazy thin layers that my filament/temperature settings may not work with easily. I'd like to specify a range of layer height that it would adapt with, e.g. 0.12 - 0.25mm

**Describe the solution you'd like**
In the adaptive layer UI, allow us to put a min/max value there.
While we're at it, also make the remaining UI/boxes easier to understand since I really don't get what those other boxes are for...

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by domik82** [comment]
I guess you could limit the extruder settings in the printer preset settings.

![2023-03-26_20-58-50](https://user-images.githubusercontent.com/2431071/227797939-64444347-007b-4dc6-8ee4-5a42eea74bd6.png)
