### ISSUE TITLE
"Make Overhanges Printable" -> Highlight geometry that was changed in slice preview

### ISSUE THREAD

**Issue by fooshards** [SoftFever/OrcaSlicer#5024]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

This feature is sweet, but it's sometimes hard to determine when the feature is modifying a surface.  I've shamefully been comparing screenshots of "Sliced with on" and "Sliced with off" in a photo diff tool from static camera angles.  And using color scheme "Speed" from an underside view to see if overhang slowing is modified/appropriate.   It's real subtle for things like screws and wobbly organic shapes that are designed to fit together.

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

It would be nice somehow to use a filter in the "Color Scheme" dropdown that would show color A for normal and color B for modified walls.  Bonus points for gradienting the "severity" of the change but honestly it tells the right story even if its only A/B.

The option wouldnt need to be in the color scheme dropdown by default, only when Make Overhangs Printable was enabled.  Or it can hang out in the menu, that's fine too.

### Describe alternatives you've considered

Screenshotting the preview pane as a png to diff against to see if any outer wall line geometry changed between slicing the two variants.
Using a very slow 85%_overhang speed temporarily to highlight areas of the model that are still Very Overhung© before and after the feature is toggled and sliced.  

### Additional context

As someone who prints mostly-other-people's-designs, I really like using the feature as part of troubleshooting, especially when the "first print failed".

**Comment by WilliamKWusik** [comment]
I can't believe more people didn't request this, as it's really important. <3
