### ISSUE TITLE
Top/bottom shell layers limited to a maximum of 1.

### ISSUE THREAD

**Issue by LeppysGold** [SoftFever/OrcaSlicer#5036]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0

### Operating System (OS)

Windows

### OS Version

Windows 11

### Printer

Ender 3 V3 SE

### How to reproduce

Try to input or increase number of top or bottom shell layers. 0 will still disable, and the system accepts any number input, but only slices 1 layer

### Actual results

Top/ bottom shell layers are limited to a maximum of 1 when the object is sliced

### Expected results

Top and bottom shell layers should slice at the input value

### Project file & Debug log uploads

Every project I've used since the update. 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by vgdh** [comment]
2.1 dev works fine

**Comment by LeppysGold** [comment]
I uninstalled and reinstalled the latest version, it still doesn't work.

**Comment by hliebscher** [comment]
@LeppysGold it works no issues

**Comment by LeppysGold** [comment]
It only works in that it lets you type in whatever number. Once you hit
slice, the model only has 1 shell layer on top or on bottom. Prints with
only the one layer, as well.

**Comment by ciradrak** [comment]
I see the same problem here.   Both "Top shell layers" & "Bottom shell layers" have no effect.  Only the very top & very bottom layers are given solid infill.  This behavior is not present in Bambu Studio 1.9.1.67

Problem observed on: Orca Slicer 2.1.0-beta   MacOS 14.4.1

Perhaps the 3mf file exhibiting the error would be helpful?
[the+absurd+two-planet+gear+bambu+mini.orca.3mf.zip](https://github.com/user-attachments/files/15523191/the%2Babsurd%2Btwo-planet%2Bgear%2Bbambu%2Bmini.orca.3mf.zip)
