### ISSUE TITLE
Please add a profile for the anycubic kobra 2 pro printer

### ISSUE THREAD

**Issue by Novichek-13** [SoftFever/OrcaSlicer#5048]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Please add a profile for the anycubic kobra 2 pro printer. ORCA has a profile for anycubic kobra 2, but these versions are controlled by marlin. And they also have other technical indicators. There is an official configuration file for PrusaSlicer, but unfortunately not in orca. also, when I cut a project in ORCA, the printer display does not display data about the filament, the time, the length of the filament used, the type of filament, and there is no graft model

### Which printers will be beneficial to this feature?

Klipper

### Describe the solution you'd like

add a profile for the Anycubic kobra 2 pro printer
adding project data - data about the filament, the printing time, the length of the filament used, the type of filament and the shape of the model

**Comment by sduford** [comment]
Hi, still no Kobra 2 Pro profile?

**Comment by keybl** [comment]
yep, you definitely need to add kobra 2 pro to the orc, there are already profiles k2 max, plus

**Comment by cochcoder** [comment]
> If you download and install Anycubic Slicer Next (a rebranded Orka Slicer) you cat get config files for additional Anycubic printers. You should copy `resources\profiles\Anycubic` folder to your OrkaSlicer folder as `resources\profiles\Anycubic2` and `Anycubic.json` as `Anycubic2.json`. You should edit it and modify `"name"` entry to `"name": "Anycubic2",` and the `"description"` entry to `"description": "More Anycubic configurations",` and you are ready :)

Would you be able to upload these files? I can't install this slicer on my system

**Comment by soosp** [comment]
Yes, it is here: [Anycubic2.zip](https://github.com/user-attachments/files/17338250/Anycubic2.zip)
I had to look at the license first, but since OrcaSlicer is under the GPL Affero license, all derivative works are covered by that too, including Anycubic Slicer Next.

**Comment by cochcoder** [comment]
Thanks, I'm currently implementing all the missing profiles into Orca Slicer. I noticed that while the profiles have a small area infill flow compensation model, it's not enabled by default. What are all of your personal experiences with this setting?
