### ISSUE TITLE
OrcaSlicer Warning:  Error running JavaScript...

### ISSUE THREAD

**Issue by marinesimulation** [SoftFever/OrcaSlicer#505]
**Describe the bug**
The following warning appears after launching OrcaSlicer in Linux Mint 21:
OrcaSlicer Warning
Error running JavaScript: file:///tmp/.mount_OrcaSlRud2UO/resources/web/homepage/index.html:1:9:ReferenceError: Can't find variable: _wxOut0

**To Reproduce**
Launch OrcaSlicer 1.5 in Linux Mint and error will appear after the application opens.

**Expected behavior**
It should open without error messages.

**Screenshots**

**Printer model**
Bambu Labs P1P

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Version 21
 
![Error 1](https://user-images.githubusercontent.com/17232608/226065210-490401b7-9f94-406c-a8e7-d1979c19219a.png)

**Comment by bojangles86** [comment]
you only get one pop up? i get two... [1st](https://imageshack.com/i/pmxE18Tsp) and [2nd](https://imageshack.com/i/pnme0lqVp)
