### ISSUE TITLE
Add purge volume variable

### ISSUE THREAD

**Issue by Gr33n5murf** [SoftFever/OrcaSlicer#5052]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I was trying to write a filament change gcode for a MMU printer with purge bucket/poop chute, similar to what bambu labs printers have. Unfortunately the first flush volume and second flush volume place holders dont scale with flush multipliers amd colour, the flush length 1 to 16 place holders dont work in general for non bambu printers, the variable is left empty, so if i was to copy the x1c filament change gcode to another printer, fixing the gcode first due to parsing issues, the gcode wouldn't have any flushing. Having a possibility to purge into a bucket or opening would help with material waste (prime tower requires less structure than purge towers for layers without material change) as well as be more space efficient, which helps especially smaller printers as the purge tower can get quite large. With multi colour printing getting more popular and accessible as well as mods like the blobifier popping up which could make use of this variable i can imagine that this will be a quite useful addition and would certainly manifest orcaslicer as the most flexible slicer for multi material printing. 

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

Orcaslicer already knows how much you have to purge, either from the purge tower or from the bambu studio inherited flushing. I would like it to be a paceholder just like the other already existing variables, so you can either pass it over into a macro or directly use it in the filament change gcode for more accurate filament usage and time estimations. 

### Describe alternatives you've considered

Unfortunately i couldn't think much of an alternative. I also dont have enough understanding of coding, i can write klipper macros no problem but that's about it, so i cant estimate how much work my request is.

**Comment by bavery79** [comment]
Would love to see this as well, and would be very helpful to allow full use of OrcaSlicer's flush-to-infill options as more and more multi-color printers come along with off-the-bed type purge methods. Currently, flushing to infill only works if you use orcaslicer's built in purge tower since there's no way to pass dynamic purge amounts for each filament change via gcode, so purging macros are limited to only the information build from an initial purge volume table at the beginning of the gcode file

**Comment by scarmain** [comment]
If you want to add volume to tool changes, you actually can with a gcode macro (looks like it was introduced in v2.3, from https://github.com/OrcaSlicer/OrcaSlicer/commit/508d0e6334b9ae362f156f9a1b82612450e4f5d2).  You must have "Manual Filament Change" on (aka you are responsible to make the tool change call in the "Change Filament G-Code" section).
`T{next_extruder}` (or equivalent tool change macro)
`; EXTERNAL_PURGE R{first_flush_volume+second_flush_volume}`

If you don't have "Manual Filament Change" on, it will put the purge numbers on the filament BEFORE the tool change, and the flushes will be for the previous toolhead (flipped purge lengths on a 2 color print, crazy on 3+).

I cross compared this answer with the one Creality Print gave for it's CFS, and they matched.  I also checked [extruded flush length in m] versus [num flushes * flush volume per flush / filament area (2.4052 on 1.75mm filament)], and the math works.

(sorry to bring up this old issue, but it comes up on Google as a top result)
