### ISSUE TITLE
Tree support wall loops setting missing...

### ISSUE THREAD

**Issue by TerennGarok** [SoftFever/OrcaSlicer#5055]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

Windows

### OS Version

Windows 10

### Printer

Bambu Labs P1S

### How to reproduce

When enabling Tree Supports, the Tree wall loop setting is missing.  It shows up in the settings search, but when clicked it brings you to an area in settings without it.
![Settings Screenshot](https://github.com/SoftFever/OrcaSlicer/assets/109039825/8072108d-1181-466a-9f02-80d0b5fc9cfb)

### Actual results

Nothing

### Expected results

To be able to change the number of walls printed in a tree support.

### Project file & Debug log uploads

N/A - Applicable on all files.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Sergutss** [comment]
If you set the tree type to “hybrid” it will show the options to change the tree wall loop setting
