### ISSUE TITLE
Flow option disappearing from the menu

### ISSUE THREAD

**Issue by lepapapa** [SoftFever/OrcaSlicer#5061]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

Windows

### OS Version

10

### Printer

Neptune 4 Pro

### How to reproduce

1. Delete user data from the pc
2. Setup printer as normal
3. Enter advance mode for process
4. Go to "Walls and surfaces" and their find "Flow ratio" option than change it
5. Change things up and save few profiles for custom materials and processes
6. Restart slicer
7. There is no longer "Flow ratio" option in the "walls and surfaces" menu (but i think that a value that was put there is save somewhere)

### Actual results

![after saving profiles ](https://github.com/SoftFever/OrcaSlicer/assets/167336618/3a475058-22be-448d-b8c0-0beca32f2635)
![befor saving profiles](https://github.com/SoftFever/OrcaSlicer/assets/167336618/805e6638-6ae2-4f8c-9846-f77fb3cd8da8)

I was able to reproduce the effect on both of my computers

### Expected results

Nothing should change when doing things like that. 

### Project file & Debug log uploads

[before and after 3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/15013335/before.and.after.3mf.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by JWalter1337** [comment]
I'm having this exact same issue too: no option for "Flow ratio" just top and bottom show. Mac OSX (ARM) ORCA 2.1

**Comment by taureau123** [comment]
Hello, me too, I'm having this issue ! And I'm finding a temporary solution for the moment. Change the language in preferences and it's magic this option re-appear !

**Comment by miceanite** [comment]
Same issue here. It's there one minute, and gone the next.
