### ISSUE TITLE
Some unknown/unnecessary perimeters appearing.

### ISSUE THREAD

**Issue by rednaxal** [SoftFever/OrcaSlicer#5064]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

Windows

### OS Version

Windows 10

### Printer

Bambu Lab P1S

### How to reproduce

Open the attached project. Slice it. See it. 

### Actual results

For whatever reason the slicer adds some unwanted/unexplained/unnecessary internal perimeters on some flat surfaces:
![1](https://github.com/SoftFever/OrcaSlicer/assets/64834712/7d1d73af-ed04-4537-a942-42352cef824a)
![2](https://github.com/SoftFever/OrcaSlicer/assets/64834712/80298f69-2113-40f3-b837-f082b6791809)

### Expected results

It should not add those strange unnecessary internal perimeters at all. The vanilla Prusa Slicer 2.7.4 is not having this issue. 
The following nice and clean result is from Prusa Slicer 2.7.4
![3](https://github.com/SoftFever/OrcaSlicer/assets/64834712/fc0bd86e-b495-4f90-a686-f77fc3ad1e26)

### Project file & Debug log uploads

[hex SC__trading_yellow.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/15016475/hex.SC__trading_yellow.3mf.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by vgdh** [comment]
I confirm strange behavior. 
When I choose different printer profile it's slice ok.

**Comment by Jeevus3D** [comment]
Same issue here. v2.0 - issue seems to be caused by "Only one wall on top surfaces" setting. With the setting disabled, the perimeter issue goes away regardless of arachne or classic generation.

**Comment by igiannakas** [comment]
Set your single line top detection to 100%. It’s 300% by default and on some models it causes this artefact.

**Comment by rednaxal** [comment]
As @igiannakas mentioned to get rid of this defect it is necessary to lower the value of the line top detection.
