### ISSUE TITLE
Wiki not public

### ISSUE THREAD

**Issue by zimivanende** [SoftFever/OrcaSlicer#5065]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

macOS

### OS Version

/

### Printer

bambu

### How to reproduce

click on smooth spiral 

### Actual results

<img width="1474" alt="Screenshot 2024-04-18 at 01 35 05" src="https://github.com/SoftFever/OrcaSlicer/assets/44968400/9f7c24e7-2f07-4b60-89ee-17f2a620dc91">

### Expected results

to see the wiki

### Project file & Debug log uploads

/

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by vgdh** [comment]
wiki desperately needed help of volunteers to fill all the help gaps in the wiki

**Comment by zimivanende** [comment]
Unfortunately my knowledge is to limited otherwise I would volunteer. Isnt
there a way to train an open ai model? You put in the code and a
description and it generates it.
