### ISSUE TITLE
slice error

### ISSUE THREAD

**Issue by windyan9** [SoftFever/OrcaSlicer#5067]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

macOS

### OS Version

14.0 

### Additional system information

cpu:M1

### Printer

DIY

### How to reproduce

1.create a new project
2.Add a new model(stl)
3.Click "preview"

### Actual results

<img width="459" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/95895477/104317d0-861e-4944-8655-4e92a426213c">

### Expected results

no error info

### Project file & Debug log uploads

[cubreboquilla_largo_clarinete-report.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/15020914/cubreboquilla_largo_clarinete-report.3mf.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Anything else?

Update from 1.9.x

**Comment by vgdh** [comment]
it's not clear what is wrong

**Comment by windyan9** [comment]
￼

When appear this message, I can`t continue.
This message appear everytime when i slice a model, I can`t print any model

===============================
杨文锋
QQ：3445599
Mobile/WeChat:18601178314

**Comment by vgdh** [comment]
this is a Gcode window. You can disable it by pressing "C" key on english layout keyboard or also in "view:" menu.

**Comment by mrgfonkyfresh** [comment]
meme probleme sur macos ventura en francais. on ne peut pas decouper le plateau sans message d erreur. il faut mettre orca en anglais pour que cela fonctionne.
![IMG_2453](https://github.com/SoftFever/OrcaSlicer/assets/163590068/6d5a05cb-861f-4acf-abd4-534dcf900f36)
