### ISSUE TITLE
Add support for Creality Ender 3 V3 (with no suffixes)

### ISSUE THREAD

**Issue by diegohvanni** [SoftFever/OrcaSlicer#5087]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

No. The printer model is new in not yet supported. 

### Which printers will be beneficial to this feature?

Klipper

### Describe the solution you'd like

Add presets for the Creality Ender 3 V3 machine same as its siblings K1 and K1C

**Comment by bistory** [comment]
I can take care of it since profiles seem similar to K1/K1C, give me some days ;-)
