### ISSUE TITLE
"help"  disappears shortly after launching OrcaSlicer (iMac)

### ISSUE THREAD

**Issue by Manfredo1952** [SoftFever/OrcaSlicer#509]
**Describe the bug**
"help"  disappears shortly after launching OrcaSlicer

Does not come back when logging out/in. 
Visable for a short moment, then gone.

![image](https://user-images.githubusercontent.com/56330568/226082131-cbd47fba-d120-4ba6-bdcd-48135f0c7bf7.png)

 

**Desktop (please complete the following information):**
 - iMac, 
 - OSX 11.7.3

**Comment by SoftFever** [comment]
That's one of the mystery behavior on Mac I have yet to figure out...
