### ISSUE TITLE
Internal bridge flow affected by both ratio settings

### ISSUE THREAD

**Issue by KD7LRJ** [SoftFever/OrcaSlicer#5097]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.0-dev (2024-04-18 nightly)

### Operating System (OS)

Windows

### OS Version

Win 11

### Additional system information

n/a

### Printer

Bambu Lab P1P

### How to reproduce

1. Add a cube primitive and slice with bridge flow ratios set to 1.0
2. Change "Bridge flow ratio" to 0.9 and observe that the flow of internal infill changes when it should not.
3. Change "Internal bridge flow ration" to 0.9 and observe that the flow of internal infill changes as it should.

### Actual results

At best, internal bridges don't support subsequent layers very well.
At worst, the bridges clump together and stick up above the current layer causing head crash failures.

![image](https://github.com/SoftFever/OrcaSlicer/assets/2763408/9484a995-de30-4e62-a545-405e34939002)

![image](https://github.com/SoftFever/OrcaSlicer/assets/2763408/328fddbf-7027-48ad-acdb-eb849edcecfa)

![image](https://github.com/SoftFever/OrcaSlicer/assets/2763408/753fc68b-e130-4452-8cd0-20257c031bca)

### Expected results

It seems like the two flow ratio settings should not stack and should affect the two different bridge types separately.

You'll likely note that in my project file, the line widths are set to 0.6mm even though I am using a 0.4mm nozzle. Layer height is also set rather high at 0.28mm for the same reason. I use this technique with PETG to keep it from pulling loose from previous layers when changing directions and keeping flow rates as high as possible.

### Project file & Debug log uploads

[Internal bridge flow ratio test.zip](https://github.com/SoftFever/OrcaSlicer/files/15049828/Internal.bridge.flow.ratio.test.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by Ohara2208** [comment]
Im seeing the same issue.
Ive set the Internal bridge as a extreme low number and can clearly be seen that it doesnt get effected and follows the bridge flow. It seems to me the Internal flow option just doesnt actually do anything and both Bridge and Internal bridge are linked together.
I normally run these two at different flows as you can then run the internal much faster and be fine with ugly bridges.

![image](https://github.com/SoftFever/OrcaSlicer/assets/149898595/320b9755-07c2-45f9-b1b4-1553b13b710b)
