### ISSUE TITLE
Orca Tree Supports base / top interface patterns broken/not working at all....and there is no infill on tree support either..

### ISSUE THREAD

**Issue by soundtechscott** [SoftFever/OrcaSlicer#5100]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0

### Operating System (OS)

Windows

### OS Version

Windows 10 Pro 64 bit

### Additional system information

Not really Important for this bug as it happens on multiple machines and is not processor/memory related

### Printer

Neptune 4 Max

### How to reproduce

add any object that would use supports
select tree support - any version - default as an example
choose any base base pattern and any interface pattern

### Actual results

the interface patterns never change away from the rectilinear lines no matter what you set them to
![image](https://github.com/SoftFever/OrcaSlicer/assets/51548286/501ab014-f12a-47a7-ba25-6c0146c9745b)

![image](https://github.com/SoftFever/OrcaSlicer/assets/51548286/be4768d1-749b-402e-994e-d3d2fc1ba963)

there is also no infill in the tree supports and there needs to be
![image](https://github.com/SoftFever/OrcaSlicer/assets/51548286/de69b0fa-ce40-4b11-b5cd-11747f6442bb)

### Expected results

I expect that if I select Honeycomb, or grid, that it actually gives me the pattern I have selected
I expect that the tree support is not hollow but that it follows the infill the same as the part, or at least would have its own infill parameters that I could use

### Project file & Debug log uploads

I dont have the ability to upload a project file at this time

use literally any file that has an overhang that a tree support would work on

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Jason-Weber-UC** [comment]
Can confirm.
Creality K1 Max + Orca 2.0.0
Add model. Select Tree support. Slice. Not generating any interface layers.

**Comment by soundtechscott** [comment]
Still broken...
I've given up on using orca slicer for anything
in Cura, all my prints work with no issues
in orca, I get spaghetti mess with almost everything I print
especially if it needs supports, guaranteed to fail with the supports not working like they should

**Comment by crookz** [comment]
Still broken. I have to move to cura also to do anything requiring tree supports that touch the model. Same issue on Bambu slicer with many complaints. No one address this basic issue that has been there a long while yet we get scarf seams. Can we just have moderte functions of supports working. See bambu slicer issue here also: [https://forum.bambulab.com/t/slicer-not-generating-bottom-support-interfaces/36327](url)

**Comment by crookz** [comment]
Also related to this issue: [ https://github.com/SoftFever/OrcaSlicer/issues/5357](url)

**Comment by Milopapa** [comment]
Facing the same issue. How do you get an issue to reopen here?

**Comment by TMTYD** [comment]
can confirm

<img width="1344" height="919" alt="Image" src="https://github.com/user-attachments/assets/e4115187-1258-4cfc-a85d-5ffea992fbab" />
<img width="1356" height="931" alt="Image" src="https://github.com/user-attachments/assets/e43db0e7-88d6-4205-8906-183d19784305" />
