### ISSUE TITLE
Macros filament retraction length

### ISSUE THREAD

**Issue by rzVeber** [SoftFever/OrcaSlicer#5104]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

Windows

### OS Version

Win10

### Printer

Creality Ender 3 V1.5

### How to reproduce

I use G10/G11 (FWRETRACT) in my printers. In order to load rollback settings from the slicer to the printer, I use this macro: {
M207 S[filament_retraction_length] F[filament_retraction_speed] Z[filament_z_hop]
M208 S[filament_retract_restart extra] F[filament_deretraction_speed] 
M209 S0
}
![image](https://github.com/SoftFever/OrcaSlicer/assets/53709639/07f16b20-c83e-4281-84ab-08be83ed5509)

Но если я не настрою Retraction, материала Generic то слайсер в местах где должны быть значения просто напишет nil.
![image](https://github.com/SoftFever/OrcaSlicer/assets/53709639/dcfc8d37-d05c-4bb3-b324-d81dcd72606c)

### Actual results

When I export G-code I expect to see the values in place of the variables
but i get:{
M207 Snil Fnil Znil
M208 Snil Fnil 
M209 S0
}
![image](https://github.com/SoftFever/OrcaSlicer/assets/53709639/33d2daab-adfa-42c7-9884-70ebda04d38a)

### Expected results

But if the values are unlocked and specified. G-code is output correctly:
{
M207 S0.8 F30 Z0.4
M208 S0 F0 
M209 S0
}
![image](https://github.com/SoftFever/OrcaSlicer/assets/53709639/d9fce849-56ce-4583-bb88-258e3a0b8e5f)
![image](https://github.com/SoftFever/OrcaSlicer/assets/53709639/99be94ee-7a65-4eb2-a6bb-00948b45b72f)

### Project file & Debug log uploads

[Dice_face_Bed_leveling.zip](https://github.com/SoftFever/OrcaSlicer/files/15052791/Dice_face_Bed_leveling.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Anything else?

In addition, I would like to ask the developer to add the ability to switch the rollback speed from seconds (speed mm/second) to minutes (speed mm/min). My Marlin is edited to accept seconds speed, but by default the Marlin2 uses the minute feed option. What causes the conflict.
![image](https://github.com/SoftFever/OrcaSlicer/assets/53709639/e03d16af-56ba-4ddf-b39d-bd420b6e17c3)

P.S. I am not a native English speaker, and to report errors, I use a translator, and the translation may not be accurate.

**Comment by bmbanker** [comment]
@rzVeber I am able to use the placeholders as follows, they seem to default to the printer settings whenever filament settings are not overwritten. This way I am able to use firmware retraction and still have my retraction update during filament changes.

SET_RETRACTION RETRACT_LENGTH=[retraction_length]
SET_RETRACTION RETRACT_SPEED=[retraction_speed]
SET_RETRACTION UNRETRACT_SPEED=[deretraction_speed]
SET_RETRACTION UNRETRACT_EXTRA_LENGTH=[retract_restart_extra]

Here are screenshots of the gcode generated with these commands set in my start and change-filament printer gcode templates:

![image](https://github.com/SoftFever/OrcaSlicer/assets/16403152/32d8f934-3b91-4c1f-841c-9c134a7ac617)

![image](https://github.com/SoftFever/OrcaSlicer/assets/16403152/d05b776c-8dcd-4882-be22-9e930e04b332)
