### ISSUE TITLE
If I disenble wipe tower filament ramming,there will still travel to the wipe_tower_xyz before toolchange.

### ISSUE THREAD

**Issue by SeaNyanko** [SoftFever/OrcaSlicer#5128]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0

### Operating System (OS)

Windows

### OS Version

Windows11

### Printer

Voron2.4 & Ender3

### How to reproduce

 disenble wipe tower filament ramming
![orca_preview](https://github.com/SoftFever/OrcaSlicer/assets/132672027/337189b9-572a-4a18-9860-28c21408d1aa)

### Actual results

![orca_wipe_tower_seting](https://github.com/SoftFever/OrcaSlicer/assets/132672027/432d0f95-d706-46b0-bd1a-8827ce78a0ec)

### Expected results

If I disenble wipe tower filament ramming,there will l travel to the toolchange_xyz.

### Project file & Debug log uploads

[sider_notcher_light_barrier.zip](https://github.com/SoftFever/OrcaSlicer/files/15079135/sider_notcher_light_barrier.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by igiannakas** [comment]
![image](https://github.com/SoftFever/OrcaSlicer/assets/59056762/73f61f8c-035a-4384-87e0-296f4660aa53)

disable your prime tower
