### ISSUE TITLE
New User filament settings not properly loaded after app launch 

### ISSUE THREAD

**Issue by wojteksz128** [SoftFever/OrcaSlicer#5138]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

Windows

### OS Version

Windows 11

### Printer

Anycubic Kobra 2 Neo

### How to reproduce

1. During prepare get some user defined filament profile
2. Make some change in this profile (eg. Default color, vendor)
3. Save as new profile with different name
4. Exit app
5. Run app again
6. Check settings of defined in 2nd and 3rd step filament profile

### Actual results

Only changes applied in 2nd step are the same as before restart the app

### Expected results

Changes applied in 2nd step and inherit profile changes should be the same before and after restart the app

### Project file & Debug log uploads

[user_filament_profiles.zip](https://github.com/SoftFever/OrcaSlicer/files/15099061/user_filament_profiles.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Anything else?

[user_filament_profiles.zip](https://github.com/SoftFever/OrcaSlicer/files/15099061/user_filament_profiles.zip)

**Comment by Aasikki** [comment]
Also having the same problem. Have to give a new name every time I save, or the settings wont be kept. Very frustrating issue.
