### ISSUE TITLE
Don't slow down external walls when enforcing minimum layer time

### ISSUE THREAD

**Issue by Ataraxia-Mechanica** [SoftFever/OrcaSlicer#5147]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Printer slows down, external wall glossiness/ringing pattern/corner sharpness changes, making prints ugly.

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

Slow down internal parts only and don't slow down outer walls.

### Describe alternatives you've considered

Use a layer height modifier to slow down inner parts manually on fast layers.

**Comment by igiannakas** [comment]
That's an interesting request - basically what you're saying is reduce internal features to the minimum print speed before touching the external features, right?

**Comment by igiannakas** [comment]
Try this build here:https://github.com/SoftFever/OrcaSlicer/pull/5148

Seeking testers and feedback for this before I invest any more time in polishing this and making it a feature.

**Comment by Ataraxia-Mechanica** [comment]
Yep, printing inner features slower feels weird but it makes sense when trying to make outer surface more consistent. I'm going to test this the moment the build completes.

**Comment by Ataraxia-Mechanica** [comment]
I don't think it's working for me. In some layers, travel speed is applied to the outer wall while on some it's 10mm/s.
![image](https://github.com/SoftFever/OrcaSlicer/assets/111327195/9127d56c-2331-4c1a-b4f7-36627bd173cb)
![image](https://github.com/SoftFever/OrcaSlicer/assets/111327195/12f6d815-86d6-4910-9ae2-982cb5efd6bd)

**Comment by Ataraxia-Mechanica** [comment]
This is the same model, in 2.0. 
![image](https://github.com/SoftFever/OrcaSlicer/assets/111327195/2b282b44-aff2-4b88-b0bd-c1faecb9eced)

**Comment by igiannakas** [comment]
Fixed: 
![image](https://github.com/SoftFever/OrcaSlicer/assets/59056762/bd9d37bb-7f1f-49ab-adf9-368048d40cd0)

**Comment by igiannakas** [comment]
Latest build is here: https://github.com/SoftFever/OrcaSlicer/actions/runs/8832248258

**Comment by Ataraxia-Mechanica** [comment]
Weird. Looks like if dropping the inner lines' speed doesn't slow it down enough, it immediately sets the outer wall's speed to a very low value instead of gradually slowing it down. Or was this feature a special case and not implemented yet?
![image](https://github.com/SoftFever/OrcaSlicer/assets/111327195/d668f001-d09f-4004-94b4-4d72c02ce66e)

**Comment by igiannakas** [comment]
> Weird. Looks like if dropping the inner lines' speed doesn't slow it down enough, it immediately sets the outer wall's speed to a very low value instead of gradually slowing it down. Or is this feature a special case and isn't implemented yet? ![image](https://private-user-images.githubusercontent.com/111327195/325642863-d668f001-d09f-4004-94b4-4d72c02ce66e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNTg5MDgsIm5iZiI6MTcxNDA1ODYwOCwicGF0aCI6Ii8xMTEzMjcxOTUvMzI1NjQyODYzLWQ2NjhmMDAxLWQwOWYtNDAwNC05NGI0LTRkNzJjMDJjZTY2ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNVQxNTIzMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYTk4NjE3NjIzYjlkMjU1MjI1YjY4NjIyM2VkZWVlOGU4MjE0OWJkMjczMGQ4NjgxMGZlMjY1MTk1ZDRkMDM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lIz4SycO-e3RG5vTAjWcLnNPrWIHI9HC_AMw8T4-nYk)

Drop me your project file as a zip file here to take a look.

also try slicing with slowdown for overhangs disabled - there maybe some interference there

**Comment by Ataraxia-Mechanica** [comment]
Yeah, even with class mode it's acting weird. Currently thinking about what to print that has no overhangs and is small enough that the artifact due to slower outer wall would be obvious.

**Comment by igiannakas** [comment]
> Yeah, even with classic mode it's acting weird. Currently thinking about what to print that has no overhangs and is small enough that the artifacts due to inconsistent outer wall speed would be obvious.

A benchy works well ;)
