### ISSUE TITLE
BambuSource.dll Crashes new microsoft teams. Still experiencing with OrcaSlicer 2.0.0

### ISSUE THREAD

**Issue by MinnesotaMean** [SoftFever/OrcaSlicer#5150]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0

### Operating System (OS)

Windows

### OS Version

Win 11

### Printer

X1C

### How to reproduce

https://github.com/bambulab/BambuStudio/issues/1877
https://github.com/SoftFever/OrcaSlicer/issues/1576
https://github.com/bambulab/BambuStudio/issues/1748

These are all marking this issue as fixed, but the new MS teams pulls that DLL and causes a crash every 15 minutes exactly.

### Actual results

N/A

### Expected results

N/A

### Project file & Debug log uploads

N/A

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by eschreiner** [comment]
same here - I am on Orca Slicer 2.1.1
