### ISSUE TITLE
Model is sliced with huge gaps

### ISSUE THREAD

**Issue by Rickthebig** [SoftFever/OrcaSlicer#5156]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

Windows

### OS Version

Windows 10

### Printer

DIY BLV Cube based on Troodon (Reprap) as template

### How to reproduce

Slice following model:
![image](https://github.com/SoftFever/OrcaSlicer/assets/151161212/cadeccae-1628-46a3-80ef-7da9e77d3fa3)

### Actual results

Result of slicing:
![image](https://github.com/SoftFever/OrcaSlicer/assets/151161212/1ed30711-9cd3-4029-abc6-b62fd1701094)

Note the gaps in the walls.

### Expected results

The model should be sliced without gaps.

### Project file & Debug log uploads

[Uploading Chev_Express.zip…]()

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by vgdh** [comment]
May be STL is broken, try use repair tool.

**Comment by Rickthebig** [comment]
> May be STL is broken, try use repair tool.

Does Orca have a repair tool? If not, which one would you recommend?

**Comment by buzzhuzz** [comment]
Orca does have model repair tool in its Windows build. Unfortunately, I can't help much there as I'm only use Linux.

Also, sometimes exporting STL back from Orca into the file and re-import it again helped me with slightly broken models (like a dozen of open edges).

**Comment by Rickthebig** [comment]
I can confirm that the model is broken. This is not a bug in Orca.
