### ISSUE TITLE
Flowrate Test tiles. Dual purpose?

### ISSUE THREAD

**Issue by DARKFiB3R** [SoftFever/OrcaSlicer#5164]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Flowrate Test tiles create a lot of waste.

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

- Change the Flowrate Test tile models to be dual purpose.
- Designs should be created on the first layer, so the test is not negatively affected.
- Dimentions of the tiles could be changed slightly, to suite the secondary purpose.

Probably not something that will be at the top of the list of new features to be considered, but it would be nice if the Flowrate Test tiles were designed to be useful for something else, after they have served their main purpose.

It also seems like the kind of "cute little feature" that would create a lot of attention on social media, which could attract lots of new users to Orcar Slicer, as well as encouraging all users to actually calibrate their filament (more often or ever), while reducing waste by being dual purpose.

Just a thought :)

### Describe alternatives you've considered

Dominoes
Chess
Playing cards
Naughts and Crosses
???

### Additional context

**Comment by DVSVIDEO** [comment]
Tudod az az akadálya ennek, hogy a Flow rate befolyásolja a tárgyak méretét. Ha az áramlási arány is változna és a méret is, akkor nem egyértelmű, hogy az eredmény melyik változás oka.
Személy szerint nem szeretnék olyan teszteket az alapfunkcióknál amik egynél több paramétert változtatnak....
(Ha beteg leszel és két különböző gyógyszert veszel be, majd jobban leszel, akkor honnan tudod melyik hatott?)

**Comment by DARKFiB3R** [comment]
@DVSVIDEO 

The idea is that only the first layer or 2 would need to change, in order to create markings.

The flow rate of the top x layers would not need to change.
