### ISSUE TITLE
[Bug]  - New Project Still asks to save / transfer setting even if no is selected

### ISSUE THREAD

**Issue by ondrovic** [SoftFever/OrcaSlicer#519]
**Describe the bug**
When creating a new project and selecting no to save, still being prompted to transfer settings to new project, this might be how it's always been just now noticing it.

**3mf File for This Bug**
If it is related to slicing, please append the 3mf file. It could be extremely helpful to solve the issue.

**To Reproduce**
* Seelct File Menu
* Select New Project
  * When the save dialog pops up asking if you like to save before continuing
    * select No
  * Observer the Create a new project: unsaved changes dialog appears

**Expected behavior**
I would expect if you hit `No` no other prompts to save changes would occur and it should revert to base profile

**Screenshots**
![image](https://user-images.githubusercontent.com/3682042/226117754-56252a10-a5ff-4c42-8bec-2f696c8ff32c.png)
![image](https://user-images.githubusercontent.com/3682042/226117799-d4cfe440-e786-4186-8be4-133524e7ab03.png)

**Printer model**
Bambu Carbon X1

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Version: 22H2

**OrcaSlicer Version**
1.5.0 Based on BambuSudio 01.05.00.61

**Comment by SoftFever** [comment]
I can't repro it.
Can you consistently preproduce it?
