### ISSUE TITLE
Missing wiki article

### ISSUE THREAD

**Issue by Fredrik81** [SoftFever/OrcaSlicer#5193]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0

### Operating System (OS)

Windows

### OS Version

na

### Additional system information

na

### Printer

na

### How to reproduce

From settings menu go to Support and hover over "Top Z distance" and it will show a URL to wiki.
Click on "Top Z distance" and it will navigate to that page but it does not exist.
![image](https://github.com/SoftFever/OrcaSlicer/assets/21292774/ecb71f09-938e-4fa2-bc26-cb5fdfa2e6b2)

### Actual results

You will arrive in the start wiki page not the desired support page.

### Expected results

Get information and instructions for the desired settings option

### Project file & Debug log uploads

N/A

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by vgdh** [comment]
related https://github.com/SoftFever/OrcaSlicer/issues/5065
