### ISSUE TITLE
"Stealth Mode" Ambiguity in OrcaSlicer Preferences

### ISSUE THREAD

**Issue by dstulken** [SoftFever/OrcaSlicer#5198]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

When configuring OrcaSlicer, most of the configuration items have helpful tooltip descriptions.

For example, "Zoom to mouse position" has the tooltip text "_Zoom in towards the mouse pointer's position in the 3D view, rather than the 2D window center"_ - which nicely clarifies what happens when that option is checked.

However, the tooltip for "Stealth Mode" simply repeats the text "Stealth Mode".
This doesn't explain what Stealth Mode does, which is a significant omission as this option controls how your data is exchanged with cloud services - which may be in other countries with different privacy regulations.    

Additionally, there is likely to be confusion from users new to OrcaSlicer, as "Stealth Mode" in PrusaSlicer has an entirely different meaning:  https://help.prusa3d.com/article/power-modes_2213#

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

Ideally, two small changes would be made:
1) The "Stealth Mode" checkbox would be renamed to something directly descriptive, such as "Disable Bambu Cloud".
 _(Or "Bambu Cloud Stealth Mode" if preservation of the "Stealth Mode" terminology is important.)_
2) The tooltip text updated to reflect that when the checkbox is NOT checked, data will be communicated with Bambu Lab servers.

**Comment by cochcoder** [comment]
Would this description suffice? `This stops the transmission of data to Bambu's cloud services. Users who don't use BBL machines or use LAN mode only can safely turn on this function.`

**Comment by jahnj0584** [comment]
> Would this description suffice? `This stops the transmission of data to Bambu's cloud services. Users who don't use BBL machines or use LAN mode only can safely turn on this function.`

yes it does suffice.

**Comment by dstulken** [comment]
Thank you @cochcoder!  Yes, that is significantly better. 

Do you have any thoughts on also modifying the "Stealth Mode" checkbox text?  As I mentioned, the primary concern is that users migrating to OrcaSlicer from PrusaSlicer will have a different expectation of what "Stealth Mode" does, and whether it should be checked or not - possibly never even giving it a second thought.   Having the tooltip fixed will help clarify, but only if the user knows to look that deep.    Adjusting the main checkbox text would also help address this.

**Comment by cochcoder** [comment]
> Thank you @cochcoder!  Yes, that is significantly better. 
> 
> 
> 
> Do you have any thoughts on also modifying the "Stealth Mode" checkbox text?  As I mentioned, the primary concern is that users migrating to OrcaSlicer from PrusaSlicer will have a different expectation of what "Stealth Mode" does, and whether it should be checked or not - possibly never even giving it a second thought.   Having the tooltip fixed will help clarify, but only if the user knows to look that deep.    Adjusting the main checkbox text would also help address this.

When you say main checkbox you mean the words right next to the checkbox it's self right? If so, I'm not entirely sure about that change as it may be unnecessary, as it's hard to miss the tooltip, especially if you're unsure what it does.

**Comment by jahnj0584** [comment]
there is no tooltip.
![2024-05-06 17_32_04-Preferences](https://github.com/SoftFever/OrcaSlicer/assets/17396492/118761ac-865b-4253-9e21-3a13a8355acb)

**Comment by dstulken** [comment]
> When you say main checkbox you mean the words right next to the checkbox it's self right? If so, I'm not entirely sure about that change as it may be unnecessary, as it's hard to miss the tooltip, especially if you're unsure what it does.

Yes, that is the text I'm referencing.  But that's exactly the point I'm making - the tooltip *is* easy to miss if you already think you know what it is - which is a very real possibility since OrcaSlicer (by way of Bambu Studio) is a fork of PrusaSlicer - which has had an entirely different "stealth mode" since before OrcaSlicer existed.  

If a PrusaSlicer user intentionally doesn't use Stealth Mode, then comes over to OrcaSlicer and sees that Stealth Mode is unchecked, they will simply say "Ok, that's how I wanted it" and never hover to read the tooltip to know that the name has been repurposed.

**Comment by cochcoder** [comment]
Ahh, I understand what you're saying, sorry for the miscommunication. I'll leave it up to @SoftFever as they own the project.

**Comment by cochcoder** [comment]
> there is no tooltip.
> 
> ![2024-05-06 17_32_04-Preferences](https://github.com/SoftFever/OrcaSlicer/assets/17396492/118761ac-865b-4253-9e21-3a13a8355acb)
> 
> 

https://private-user-images.githubusercontent.com/103969142/328169024-d6be7877-a1cb-4ef0-af53-a4504669ec55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwMzEzMjQsIm5iZiI6MTcxNTAzMTAyNCwicGF0aCI6Ii8xMDM5NjkxNDIvMzI4MTY5MDI0LWQ2YmU3ODc3LWExY2ItNGVmMC1hZjUzLWE0NTA0NjY5ZWM1NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNlQyMTMwMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNTMyYjcwMDVjNTE1YTZmNDJjYTJlOTBkNDljMWYyMmNkOTEyZTIxM2M4MmQzYjUyZmJiNTFlNTc1OTc1ZWJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gy7bC1M1DsQtahN1sWn1Z1fObmlHELRy7vCoMvUa3T0
