### ISSUE TITLE
Jump to device window when print starts

### ISSUE THREAD

**Issue by Padawg** [SoftFever/OrcaSlicer#520]
Previous versions would jump to device window when you sent the print to the printer.  That seems to stop working.

**Comment by hliebscher** [comment]
witch OS ? witch version ?

**Comment by Padawg** [comment]
Windows 10, Orca 1.50

**Comment by mckellar11** [comment]
This is also the same for me, it just stays on the preview screen

**Comment by enewun** [comment]
Seems like a widespread issue with Orca 1.50. I am on an M1 Mac and am also having this issue.

**Comment by spali** [comment]
Confirm to happen also with 1.50 on win 11.
