### ISSUE TITLE
Orca using G1 for travel moves instead of G0 - bad for postprocessing

### ISSUE THREAD

**Issue by Rickthebig** [SoftFever/OrcaSlicer#5200]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

Windows

### OS Version

Windows 10

### Printer

DIY CoreXY 3d printer 

### How to reproduce

Look at the gcode generated by Orca for any model and identify the travel moves. 

### Actual results

All travel moves are generated using G1, which is just wrong.

### Expected results

You will see G1 instead of the expected G0 in all travel moves.

Travel moves should be using G0 - this is a standard and it is being infringed by the uncritical adoption of unrevised legacy code from predecessors (Prusa etc.).

For example, using a G1 for travel moves on firmware for laser cutters will enable the laser... not good. Do not provoke such serious mishap!

The particular reason for me to raise this question is that this G1 quirk in Orca prevents postprocessor scripts to recognize travel moves. Authors of such scripts won't even consider to adapt their work to such a whim by allegedly amateur developers - they are not willing to propagate the balderdash in their own work, even if travel moves can still be identified by lacking the [E]xtrusion option.

Besides, this G1 aberrance bears the danger for Orca to become potentially incompatible with future applications, enhancements and environments that abide by the standards.

So much the worse as this is so easy to fix.

### Project file & Debug log uploads

[Retract_Test.zip](https://github.com/SoftFever/OrcaSlicer/files/15155920/Retract_Test.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Anything else?

You can ignore the appended project file since it is possible to retrace the issue in every Orca gcode file.

**Comment by shledge** [comment]
I think the reason it hasn't been changed, because it's... a fairly niche thing.
