### ISSUE TITLE
Hole compensation paint

### ISSUE THREAD

**Issue by DVSVIDEO** [SoftFever/OrcaSlicer#5212]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I have a suggestion for the phenomenon reported by the following error flags: 
https://github.com/SoftFever/OrcaSlicer/issues/5102
https://github.com/SoftFever/OrcaSlicer/issues/4236
https://github.com/SoftFever/OrcaSlicer/issues/3990
https://github.com/SoftFever/OrcaSlicer/issues/2770

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

You could use a brush to paint the parts to be compensated (like the support, or to paint the seam.)
The brush could act like a paint pot for the support: it would select the area to be compensated with a single click.
You would enter the amount of compensation in an interactive window and then paint with that value. You could have a different value with a different colour when painting, so you can see the different compensation.

This could also be a solution to the request of someone who asked for a variable compensation according to the size of the hole: https://github.com/SoftFever/OrcaSlicer/issues/3532

A global compensation, like the current one, could remain and painting could only be an option for those who need exact and different compensation on the same model.

![Hole comp_paint](https://github.com/SoftFever/OrcaSlicer/assets/96373457/3191be4b-6a8b-4955-a825-2b1e38d6168b)

**Comment by foresterr** [comment]
A note on printing precise holes, the "convert holes to polyholes" option improves dimensional accuracy quite a bit (I still had to add 0.1 mm of tolerance in CAD for a close fit with a matching part of same diameter, but that value seemed independent of the hole size, which is already a big win), and with "rotate polyhole" option turned on, the result wasn't visually distinguishable from a round hole to me (might be different for very small holes, the smallest I tried was 5mm which got turned into a 12-sided polygon).

This is of course not a replacement for this request, but a potential alternative to try in the meantime - polyhole option is not very well described in the UI and for a long time I had no idea it's about dimensional accuracy.
