### ISSUE TITLE
Camera view non-functional on nightly

### ISSUE THREAD

**Issue by jsondag** [SoftFever/OrcaSlicer#5219]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.0-dev

### Operating System (OS)

Windows

### OS Version

Windows 10 Pro, 22H2. Build 19045.4291

### Additional system information

Core i7 9700k
16GB Memory
RTX 2080ti

### Printer

Bambu X1C

### How to reproduce

Goto device tab, click play button.

### Actual results

No video loads. See the following "Please check the network and try again, you can restart or update the printer if the issue persists. [2:-10]"

### Expected results

Video stream will begin

### Project file & Debug log uploads

[log.zip](https://github.com/SoftFever/OrcaSlicer/files/15173327/log.zip)
[Untitled.zip](https://github.com/SoftFever/OrcaSlicer/files/15173447/Untitled.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Anything else?

![image](https://github.com/SoftFever/OrcaSlicer/assets/13071956/575a52eb-8d66-4dcb-a003-42fbff2b5d14)

Works in V2.0

**Comment by KD7LRJ** [comment]
Seems like a duplicate of #5170

**Comment by pgifford** [comment]
Yes, it is.  The error code indicates it's a certificate error (see [my comment](https://github.com/SoftFever/OrcaSlicer/issues/5170#issuecomment-2088766511) on other issue).

**Comment by mydevpeeps** [comment]
still broke in GA 2.1.1 see https://github.com/SoftFever/OrcaSlicer/issues/5754#issuecomment-2209553656 for workaround.
