### ISSUE TITLE
Modell slicing by height for different layer height, like Simplify3D

### ISSUE THREAD

**Issue by DVSVIDEO** [SoftFever/OrcaSlicer#5225]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

It is currently not possible to specify different layer heights within a model.
Missing layer height, seam position, when splitting a body with a modifier or a plane cut.
This is the only thing missing since I switched from Simplify3D...
https://github.com/SoftFever/OrcaSlicer/issues/5118

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

When a model is cut parallel to the bed (horizontally) using the flat cut option (preparation top menu bar)
Then there is nothing to prevent you from setting a different layer height or even a different seam placement above and below the cut.
Quite understandably, if the cut crosses layers, this is not possible.

In Simplify 3D Slicer there is an option to divide into sections by specifying the heights and this is exactly what you can do.
Each layer can change everything.

![cut](https://github.com/SoftFever/OrcaSlicer/assets/96373457/01230704-127d-4d2c-953f-fd28d952f80e)

### Describe alternatives you've considered

1. Loading the model
2. Select the cut (c) menu icon
3. Select the planar option
4. Specify the plane in mm in the window or by grabbing and dragging on the model
5. Tick the box for cutting into parts
6. Press the Cut button
7. Next to Process, select Object
8. select one of the objects from Model name_A and Model name_B
9. change the height of the selected model section layer (or the seam position)
10. Slicing

### Additional context

This is how Simplify 3D does it:

![Simplify cut](https://github.com/SoftFever/OrcaSlicer/assets/96373457/158f381b-ca4b-4a9c-ad34-8b6c75cd6942)

**Comment by Arakon** [comment]
Do you mean the height range modifier that is available via right-click on the model?
![pasted-from-clipboard](https://github.com/SoftFever/OrcaSlicer/assets/12016360/75839b3f-a881-4138-9e31-82d678e18a16)

**Comment by DVSVIDEO** [comment]
Oops...
When did this get in?  I didn't notice the change.
As the only feature that is not translated into my native language, it was added sometime later...
thanks for your reply!
I'll close the request.

**Comment by DVSVIDEO** [comment]
Already solved.
