### ISSUE TITLE
Wrong first_layer_print_min/max when project has multiple plates

### ISSUE THREAD

**Issue by Ibot-11** [SoftFever/OrcaSlicer#523]
When using multiple buildplates the coordinates for the start and end area are wrong since it ignores that every plate does have its own origin point.
Therefore you can’t use adaptive mesh with multiple lates.
This bug already got patched but is back in version 1.5.0

**Comment by hliebscher** [comment]
OS? Mac or WIN?

do you have a sample 3mf as zip file? for me ist works with MAC M1  V.1.5
i use the coordinates for the start and end area for bed mesh
Sample 3. Plate M557 X118.7:161.3 Y108.7:151.3 S25. the g code is correct

**Comment by SoftFever** [comment]
It does look like it regressed for multi plates.

**Comment by SoftFever** [comment]
fixed

**Comment by hliebscher** [comment]
@SoftFever 
Now  the bug is back again !!! it works before we have fixed tis in older version now i get wrong values for 

M557 X-213.388:-176.704 Y87.9964:108.58 S25
M557 X{first_layer_print_min[0]}:{first_layer_print_max[0]} Y{first_layer_print_min[1]}:{first_layer_print_max[1]}
