### ISSUE TITLE
Add Interface shells when using Multi Color / Multimaterial. 

### ISSUE THREAD

**Issue by CyberManiaK** [SoftFever/OrcaSlicer#5233]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

The problem is that when using multimaterial the top shell layer instead of making a solid layer it leaves the space for the next object. So instead of having straight uninterrupted movements, it needs to stop the movement producing an uneven top layer. 
![Orca-TopLayer](https://github.com/SoftFever/OrcaSlicer/assets/952352/c2a9c9d3-ef6b-42a9-95e5-ef76940982e7)

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

The solution is to add the option of "interface shells" like Prusa/SuperSlicer have it. This option gives a nice continuous solid layer, ready to receive the next object.   
![20240221_140634](https://github.com/SoftFever/OrcaSlicer/assets/952352/491cead9-bd49-4b2c-ab94-6b3c9a468ceb)
![Screenshot 2024-02-21 135805](https://github.com/SoftFever/OrcaSlicer/assets/952352/0ffc198c-9129-4465-b3b6-c6479fd63588)

**Comment by Alkerion** [comment]
I join this request, I was looking for this exact feature too.

**Comment by igiannakas** [comment]
Is this it here?
![image](https://github.com/SoftFever/OrcaSlicer/assets/59056762/d74c3b37-30d0-4ca4-bd7c-91864f60aecc)

**Comment by ramorimdias** [comment]
This feature is already present on bambustudio when developper mode is activated. I can find many "interface shells" strings on the .po but cannot make it appear on Orca even with Developper Mode on. It's weird. It works flawlessly on bambustudio. This is a must if you print coaester, keychains or logos to have a smooth top layer before changing color.

**Comment by soxhi8** [comment]
This feature would be very useful.

**Comment by exen904** [comment]
Any updates on this?

**Comment by rinkek** [comment]
Would like to see this as well.
Works very good in both PrusaSlicer and Bambu Studio (when developer mode is enabled)
