### ISSUE TITLE
Unable to set brim width for temp tower

### ISSUE THREAD

**Issue by eddydas** [SoftFever/OrcaSlicer#525]
I want to set brim width for temp tower but the setting is not respected.

1. Calibrate -> Temperature
2. Brim Width -> 20mm
3. Slice

Expected: the tower has 20mm brim
Actual: the tower has 5mm brim

Sometimes we need a much wider brim because we know that the print won't stick strong enough for the material we're printing with (e.g. P1P printing polycarbonate on textured PEI sheet - when the tower cools down it shrinks and would pull in slightly to make the bottom surface + around 5mm around it unstick, so we need extra brim to keep it stay on the bed)

**Comment by hliebscher** [comment]
i think it is not a bug it is hard codet in source

("brim_type", new ConfigOptionEnum<BrimType>(btOuterOnly));
("brim_width", new ConfigOptionFloat(5.0));
("brim_object_gap", new ConfigOptionFloat(0.0));

and for all Temp Tower the same

**Comment by SoftFever** [comment]
You can change them in object setting
![image](https://user-images.githubusercontent.com/103989404/226165037-79c32ee0-63bd-444a-aed2-069b1404eabc.png)

**Comment by skintigh** [comment]
This issue still exists, should I open a new ticket? @hliebscher would it be a feature request?

I lean towards bug given the menu that @SoftFever highlighted. The brim size **cannot** be adjusted from the menu shown. No matter what type or size brim I choose (or even if I choose no brim) the slicer preview shows a brim that is 5mm. I tried setting it to 10mm and printing it but it was still 5mm. That wasn't enough to adhere to my smooth plate.

**Comment by skintigh** [comment]
Also, unsure if this is related, but each time I printed with a different sized brim in that setting, Orca slicer crashed after successfully sending the file to my Bambu X1C. But that could be a coincidence, I need to use Orca more to be sure.

**Comment by SamLR** [comment]
This still seems to be a problem and makes it tricky to print large brims for filaments like PHA which are very prone to curling on the first layer
