### ISSUE TITLE
Keyboard shortcuts for Prepare, Preview, Device, Project tabs

### ISSUE THREAD

**Issue by Stooovie** [SoftFever/OrcaSlicer#527]
**Is your feature request related to a problem? Please describe.**
Please add keyboard shortcuts for the main UI tabs (Prepare, Preview, Device, Project tabs) as well as the Slice command. Using mouse to navigate is is tiresome and slow.

**Describe the solution you'd like**
PrusaSlicer has numbers (1,2,3...) for views and ctrl (or cmd)-numbers (cmd-1, cmd-2...) for UI panels. I like that solution.

**Comment by jbjhjm** [comment]
Second that! In general it seems difficult to find out what shortcuts even exist in Orca. Seems there's no documented list available at all? Some of the PrusaSlicer Shortcuts work, others are not. -> https://help.prusa3d.com/article/keyboard-shortcuts_1764
Using TAB to switch between prepare and preview is great already.
But I cannot find a shortcut for executing slicing.
The top bar commands may be the most pressed buttons / actions and I think they should have a shortcut!

**Comment by nevack** [comment]
@SoftFever Can you reopen it? Issue is definitely present :)

**Comment by SoftFever** [comment]
@nevack @Stooovie 
Do you got a chance to try it in the latest release?
While the shortcuts are not exactly same as PS, it works too.

https://github.com/SoftFever/OrcaSlicer/assets/103989404/754223d6-faf5-4ae1-80ac-4ccb891c68bf


You can check what shortcuts are available here:
![image](https://github.com/SoftFever/OrcaSlicer/assets/103989404/1e35c212-251e-482c-9f10-24c95b6e5523)
![image](https://github.com/SoftFever/OrcaSlicer/assets/103989404/64b1dd44-1409-459c-9cce-c8a3b4276f11)

**Comment by nevack** [comment]
> Do you got a chance to try it in the latest release?

Yep, I know about Cmd+num to change view, use them regularly.

But this issue is about topmost toolbar.

While you can change between Prepare and Preview with Tab key, Device tab cannot be accessed with keyboard. I think PrusaSlicer doesn't have Device tab at all, it's from Bambu one.

**Comment by SoftFever** [comment]
Please see my video, you can use ctrl+tab to circle through all views

**Comment by nevack** [comment]
> Please see my video, you can use ctrl+tab to circle through all views

Oh, sorry, now I see.

Unfortunately, Cmd+Tab is a system shortcut for app switching, so OrcaSlicer cannot handle it properly.

<img width="460" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/8330119/967197d6-2457-4886-ba32-4b8cc41850a7">

I think many shortcuts with Ctrl by default are mapped to Cmd ones.
In this particular case this is wrong.
Ctrl+Tab is conventional for changing tabs in window even on macOS.
At least this works like this with Chrome and Finder on a mac.

**Comment by nevack** [comment]
@SoftFever ping you here, as I still think this issue was closed wrongfully.

**Comment by jbjhjm** [comment]
@SoftFever sorry to interrupt, but I too think this issue was closed wrongfully.
Application tabs should have good accessibility by keyboard.
Same goes for Process Global/Objects switch. 
(having the objects list hidden in there is my single PITA coming from Prusa/SuperSlicer btw.)
