### ISSUE TITLE
z_hop_types parsing error

### ISSUE THREAD

**Issue by vr6syncro** [SoftFever/OrcaSlicer#528]
**Describe the bug**
G-Code für ungültigen benutzerdefinierten G-Code konnte nicht erzeugt werden.
change_filament_gcode Parsing error at line 3: Not a variable name
{if toolchange_count > 1 && (z_hop_types[current_extruder] == 0 || z_hop_types[current_extruder] == 3)}
                             ^
Bitte überprüfen Sie den benutzerdefinierten G-Code oder verwenden Sie den standardmäßigen benutzerdefinierten G-Code.

**To Reproduce**
Just Slice any part

**Screenshots**
![image](https://user-images.githubusercontent.com/27892314/226165527-483e6b24-cf86-4340-bbb7-08de78beebc9.png)

I replaced gcode with the original but it is the same and the erros stays,

**Comment by SoftFever** [comment]
Does it work before?

**Comment by vr6syncro** [comment]
Yes, and on another PC it works fine. Maybe i try a clean install on this one later.  It seems there is something not right at my side.

**Comment by SoftFever** [comment]
Okay.
Keep up posted.

**Comment by vr6syncro** [comment]
new install fixed the problem. dont know what happend on this machine. 
Checked Gcode few times and it was exact the same.
