### ISSUE TITLE
2.1 最新开发板的 Default Page 设置无效，不管设置为home还是准备，打开都是准备页面

### ISSUE THREAD

**Issue by iBral** [SoftFever/OrcaSlicer#5309]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1

### Operating System (OS)

Windows

### OS Version

win10

### Printer

Voron 2.4

### How to reproduce

2.1 最新开发板的 Default Page 设置无效，不管设置为home还是准备，打开都是准备页面

### Actual results

2.1 最新开发板的 Default Page 设置无效，不管设置为home还是准备，打开都是准备页面

### Expected results

2.1 最新开发板的 Default Page 设置无效，不管设置为home还是准备，打开都是准备页面

### Project file & Debug log uploads

2.1 最新开发板的 Default Page 设置无效，不管设置为home还是准备，打开都是准备页面

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by SoftFever** [comment]
谢谢
已修复
