### ISSUE TITLE
Include Sovol SV08 printer profile

### ISSUE THREAD

**Issue by sebastian-stumpf** [SoftFever/OrcaSlicer#5310]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Sovol just released the profiles for their new SV08 printer: https://wiki.sovol3d.com/en/SV08 - Their instructions state that these files should be copied over to `resources/profiles`, but that is just not possible with the AppImage on Linux (unless you extract the image and launch the application always from there outside of the AppImage binary). Would it be possible to include these new profiles in OrcaSlicer? Then we wouldn't have to resort to workarounds. :slightly_smiling_face: 

### Which printers will be beneficial to this feature?

Klipper

### Describe the solution you'd like

Include the profiles for the SV08.

**Comment by cochcoder** [comment]
@sebastian-stumpf I've added all the files in the given link, can you conform that this [build](https://github.com/cochcoder/OrcaSlicer/actions/runs/9311397608) works for the Sovol SV08?
