### ISSUE TITLE
Remove any filament, not only the last one

### ISSUE THREAD

**Issue by Alkerion** [SoftFever/OrcaSlicer#5316]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

When we have a multicolored models and we want to remove a color that isn’t the last one it’s not possible without loosing the color on the model and that’s really annoying

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

Let us remove the filament we want in the list instead of only the last one

**Comment by Alpha12o** [comment]
Upvote. Would be great to add this option

**Comment by Xeldin** [comment]
Please implement, would be extremely useful
