### ISSUE TITLE
Assign fuzzy skin to a specific color

### ISSUE THREAD

**Issue by Alkerion** [SoftFever/OrcaSlicer#5318]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

fuzzy skin is all or nothing, or require usage of modifiers, that's not very practical.

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

Will be nice to be able to assign fuzzy skin to as specific color.

That way we will be able to create surface effect exactly where we want by just painting objects.

**Comment by vgdh** [comment]
Would be great to have some surface selection tool to apply fuzzy skin.

**Comment by gogsi1** [comment]
I would like to see several features such as support for "spheres", "Fills" and adding only internal perimeters.

**bug**
If the outer contour is selected so that it does not pass into the inner contour, if there are holes on the model

**Comment by ph0tic** [comment]
we seriously need this. if we can "apply by painting" at least it would solve some of this issue.
