### ISSUE TITLE
Allow addition/removal of handy models

### ISSUE THREAD

**Issue by Alkerion** [SoftFever/OrcaSlicer#5322]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

No, more a limitation

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

Allow us to add our own handy models and remove the unwanted one.

Location : ...\Orca\resources\handy_models

And don't overwrite when new Orca version installed, or better, let us define an external folder to store our own handy models.

**Comment by foreachthing** [comment]
Bump.
