### ISSUE TITLE
Allow discrete fan speed on outer perimeter

### ISSUE THREAD

**Issue by mvsteen** [SoftFever/OrcaSlicer#5328]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

We always have this battle where less cooling allows for more speed and better adhesion where more cooling will allow for better print quality and dimensional accuracy.

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

Just as we are able to change speed, acceleration and extrusion width for the outer perimeter to aid in making this layer nice and pretty we should be able to do the same with fan speed. I don't need the fan at all for infill most of the time, so why do I need to force it on the entire layer, affecting adhesion, just to have a pretty outer shell.

It could present very simply like a checkbox 'turn off cooling inside outer perimeter', of it could go the other way around and offer options specific to the outer perimeter.

### Additional context

Perhaps in the future there can also be options for the second perimeter, because if you're pushing it internally in terms of flow rate, extrusion width, speed, then the outer layer can be affected by the roughness of those perimeters. so a buffer zone could be nice.  But being able to at least lower the fan speed on the inside will help a lot here.

**Comment by locki-cz** [comment]
I need this!
