### ISSUE TITLE
The software won't open.Double clicking on the software causes a crash

### ISSUE THREAD

**Issue by 1019157263** [SoftFever/OrcaSlicer#5329]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0

### Operating System (OS)

Windows

### OS Version

win11

### Additional system information

设备名称	G15
处理器	Intel(R) Core(TM) i7-10870H CPU @ 2.20GHz   2.21 GHz
机带 RAM	16.0 GB (15.8 GB 可用)
设备 ID	AE87FC09-3DE4-4110-8205-0943A21DEDF2
产品 ID	00330-80000-00000-AA561
系统类型	64 位操作系统, 基于 x64 的处理器
笔和触控	没有可用于此显示器的笔或触控输入

显卡 RTX 3060

### Printer

软件

### How to reproduce

The software won't open.
![image](https://github.com/SoftFever/OrcaSlicer/assets/31230637/0e0a0f6f-2312-4025-9135-f520a46f4cda)

### Actual results

![image](https://github.com/SoftFever/OrcaSlicer/assets/31230637/b1ece995-a874-412b-8df5-d842b05d8919)
![image](https://github.com/SoftFever/OrcaSlicer/assets/31230637/9a825d9a-d0c7-4103-b64a-3f1de9ecd783)

### Expected results

![image](https://github.com/SoftFever/OrcaSlicer/assets/31230637/b1ece995-a874-412b-8df5-d842b05d8919)
![image](https://github.com/SoftFever/OrcaSlicer/assets/31230637/9a825d9a-d0c7-4103-b64a-3f1de9ecd783)

### Project file & Debug log uploads

The software won't open.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Anything else?

The software won't open.

**Comment by Pedrogtc23** [comment]
Me pasa lo mismo, no puedo abrirlo mismo mensaje
