### ISSUE TITLE
RatRig printer profile has wrong pause command.

### ISSUE THREAD

**Issue by valentt** [SoftFever/OrcaSlicer#5336]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0

### Operating System (OS)

Windows

### OS Version

Windows, Linux, Mac

### Printer

RatRig V-Core 500 (But any klipper based machine will have same issue)

### How to reproduce

Add pause in OrcaSlicer, slicer adds M601 command which is not know by Klipper, so it just skips it.
![M601](https://github.com/SoftFever/OrcaSlicer/assets/620901/795168ab-1f5c-45c7-b912-97f5e961294b)

Klipper uses "PAUSE" as pause command.

### Actual results

Machine doesn't pause.

### Expected results

Machine should pause.

### Project file & Debug log uploads

![M601](https://github.com/SoftFever/OrcaSlicer/assets/620901/dc68e848-b3be-40a2-a7e2-7a85b7ecf07e)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Anything else?

I created pull request to fix this issue:
https://github.com/SoftFever/OrcaSlicer/pull/5335

**Comment by xBoKoBx** [comment]
Same issue for FLSUN V400..

**Comment by cochcoder** [comment]
> Same issue for FLSUN V400..

This should be fixed with PR #5469
