### ISSUE TITLE
ender 3 v3 profile not working

### ISSUE THREAD

**Issue by bhast2** [SoftFever/OrcaSlicer#5344]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.0

### Operating System (OS)

Windows

### OS Version

Windows 11

### Printer

Creality Ender 3 V3

### How to reproduce

Go to add printer. 
Pick Creality Ender 3 V3 

### Actual results

Printer profile for Creality Ender 3 v3 doesn't show up in the drop down list

### Expected results

Creality Ender 3 v3 profile shows up in the list and can be chosen to use.

### Project file & Debug log uploads

Don't have a project file to share

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by jeremyb31** [comment]
Try the daily/dev version, it has the Ender 3 V3 there
