### ISSUE TITLE
Bottom Interface Layers not always recognized

### ISSUE THREAD

**Issue by ThinkBigPrintHuge** [SoftFever/OrcaSlicer#5357]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

Windows

### OS Version

11 Home

### Additional system information

CPU: i9-13900k
GPU: RTX 3070Ti (Laptop)
Ram: 32 Gigs

### Printer

Any

### How to reproduce

It's hard to consistently reproduce. However, when defining Bottom Interface Layers at let's say 0, sometimes it will still have 2 bottom interface layers. When changing from 0 to 2, it doesn't always make me reslice. It's really hard to describe this because it seems like it's happening at random.

### Actual results

Sometimes it just decides to have 2 bottom interface layers even though I sliced it at 0. Sometimes it slices correctly.

### Expected results

If I tell it "X" interface layers, it should have that many interface layers.

### Project file & Debug log uploads

Happens on almost every file. Cannot upload due to NDA. Here's a screenshot showing 0 interface layers selected, yet it still adds them.
![Screenshot 2024-05-13 121220](https://github.com/SoftFever/OrcaSlicer/assets/148880524/eae9d316-e1f7-4e05-a1e9-890bb354969c)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Bumblebiber** [comment]
I have a similar issue.

![image](https://github.com/SoftFever/OrcaSlicer/assets/78353703/faa85969-80ab-4477-af75-b5355455f92c)

I set it to 2 interface layers, but only the first one is being printed with my support material while the second interface layer is being printed with my normal filament.
