### ISSUE TITLE
Device IP changes not automatically saved/ after manual save on exit

### ISSUE THREAD

**Issue by victorlu0071** [SoftFever/OrcaSlicer#537]
**Describe the bug**
The bug happens when your printer IP address changes on an existing printer profile
The change of IP address on the printer profile doesn't get saved after exit.
Reopening the app shows the old IP address unless you save the printer profile as a new one(not overwriting the old one)

**3mf File for This Bug**
If it is related to slicing, please append the 3mf file. It could be extremely helpful to solve the issue.

**To Reproduce**
Change an existing machine's ip address.
Close the App
Reopen it and check the ip address

**Expected behavior**

**Screenshots**

**Printer model**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Windows]

**Comment by Fl0ken** [comment]
Same thing happens for me when adding an IP address for the first time. The IP is not saved through sessions, work around is saving a new profile.
