### ISSUE TITLE
"Sacrifical Layer" option for counterbore holes creates infill-based layer when 0 bottom layers chosen

### ISSUE THREAD

**Issue by RickKross** [SoftFever/OrcaSlicer#5374]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

Linux

### OS Version

Ubuntu 22.04.4 LTS

### Additional system information

Doesn't matter

### Printer

Any

### How to reproduce

1. Go to Quality -> Bridging
2. Set "Bridge counterbore holes" to "Sacrificial layer" ("Partially bridged" also has similar bug)
3. Go to Strength -> Top/bottom shells
4. Set Top and Bottom shell layers to zero

### Actual results

Counterbore hole sacrificial layer consists of infill 

### Expected results

Counterbore hole sacrificial layer is solid bridge

### Project file & Debug log uploads

[Printhead base.zip](https://github.com/SoftFever/OrcaSlicer/files/15323778/Printhead.base.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Anything else?

Look at layer 21 at smaller part
![image](https://github.com/SoftFever/OrcaSlicer/assets/7055620/478d157c-2ed3-4bde-9832-a122efd1a8e3)

**Comment by discip** [comment]
Just change the number of **`Bottom shell layers`** to a value greater than **`0`** & use a modifier to remove the bottom shell layers as a workaround. 😊
