### ISSUE TITLE
Wall Loops number Override Bridge and cause failiure. 

### ISSUE THREAD

**Issue by lhndo** [SoftFever/OrcaSlicer#5376]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

Windows

### OS Version

Windows 10

### Printer

LH Stinger

### How to reproduce

Slice model attached
Look at the bridging on the fan ducts.
The more perimeters you have, the worse it is. Works with only one 😹

### Actual results

Perimeters floating instead proper supported bridge lines  
![2024_05_15_5489_orca-slicer](https://github.com/SoftFever/OrcaSlicer/assets/42773937/f6cbdc15-53ea-4275-bb37-3b20fda394dc)
![2024_05_15_5490_orca-slicer](https://github.com/SoftFever/OrcaSlicer/assets/42773937/774fdfe3-0195-4c4e-be35-58e3de314733)

### Expected results

Internal bridges are anchored properly. Perimeters not printed in air when the bridge can expand to a solid point underneath.

### Project file & Debug log uploads

[bridge error toolhead.zip](https://github.com/SoftFever/OrcaSlicer/files/15324435/bridge.error.toolhead.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by lhndo** [comment]
Some more examples of perimeters "growing" into the bridge area
![image](https://github.com/SoftFever/OrcaSlicer/assets/42773937/74d1f68f-c39e-4415-b246-003f0e92bf1d)
With one wall the bridge can actually bridge
![image](https://github.com/SoftFever/OrcaSlicer/assets/42773937/90d87a68-fe00-4613-b5bb-031e07967f2a)

**Comment by lhndo** [comment]
[Impossible Cube.zip](https://github.com/SoftFever/OrcaSlicer/files/15326666/Impossible.Cube.zip)
![2024_05_15_5497_bambu-studio](https://github.com/SoftFever/OrcaSlicer/assets/42773937/9e1fb1d0-55a5-4d82-8f5c-3a75299e2dce)

Curious if anyone can make a successful bridge layer when setting the perimeters above 4 on this impossible model.

**Comment by discip** [comment]
I know it's not a real solution, but as a temporary workaround you could change the **`Walls printing order`** to **`Outer/Inner`**.

**Comment by buzzhuzz** [comment]
@lhndo, another workaround may be enabling "Bridge counterbore holes" to either partially bridged or sacrificial layer:
![Screenshot from 2024-05-17 05-11-10](https://github.com/SoftFever/OrcaSlicer/assets/46728448/5a188030-3e00-49b7-9413-01e193a79f4d)

However, this might compromise part strength if your wall is too thin and bridge density (or flow) less than 100% as vertical wall will be fully covered by the bridge layer added:
![Screenshot from 2024-05-17 05-11-25](https://github.com/SoftFever/OrcaSlicer/assets/46728448/e381cbf6-375b-4aa1-abed-bdee54fb6e48)

**Comment by lhndo** [comment]
@buzzhuzz that's a good trick! I managed to do something similar in SuperSlicer by using custom settings and bridge orientation. That only worked in one direction sadly. 
<br>
Unfortunately, for me, it doesn't apply in the original case. 
The main point for the latter example was to create a simple test case to illustrate the original issue, and maybe help the testing process if anyone has a go at tackling this issue. 
<br>
In my case I have a dozen variations of this toolhead, which is used for the LH Stinger, and are being printed by other people.

**Comment by lhndo** [comment]
Another example of the same issue:
![2024_05_19_5532_orca-slicer](https://github.com/SoftFever/OrcaSlicer/assets/42773937/1f8d896c-897a-4ce0-aa93-beaf668db9b4)

**Comment by BlackNet** [comment]
Been dealing with this same issue for the past 2 weeks.

**Comment by lhndo** [comment]
Another example: 
![image](https://github.com/user-attachments/assets/d795c400-4c87-464b-a33d-c6966a4a3ce4)

A possibly smarter implementation of "Remove perimeters on bridges" from SuperSlicer which would leave the anchored perimeters segments in place would be welcomed. 
![image](https://github.com/user-attachments/assets/db83af68-c67a-4368-9893-363b32e59602)

**Comment by andrewleek** [comment]
Howdy everyone,
I have made a PR regarding overhangs and bridges and it may solve some of the issues in this thread. In particular the 
tensioner_error example.

It would be great to get some testing and feedback to make sure it works correctly and there aren't any unforeseen side-effects.

PR:
https://github.com/SoftFever/OrcaSlicer/pull/10565

You can download the builds under "artifacts":
https://github.com/SoftFever/OrcaSlicer/actions/runs/17304272227?pr=10565

Thank you

**Comment by lhndo** [comment]
Thanks a lot for looking into this @andrewleek! I'll give it a go for sure
