### ISSUE TITLE
Slicing inconsistencies between versions

### ISSUE THREAD

**Issue by SavouryMonkey** [SoftFever/OrcaSlicer#538]
![Bildschirm­foto 2023-03-19 um 20 04 53](https://user-images.githubusercontent.com/41338731/226202731-b1a66d38-1af8-4cf9-9dfc-f0fb2e9f9651.png)

I took the same part, and slices it with exact the same setup (Material, Printer, etc).. By exact i mean 1:1
It shows 1.5 got slower then 1.4.5 - and also shows inconsities between the windows and arm version of 1.5 (look at the infill).. 

Maybe someone could have a look at it.

**Comment by hliebscher** [comment]
you have new features in 1.5  ... i think the speed settings are different between 1.4.5  and  slow down at overhangs
pls send the 3mf files as zip or look at the g-code for differences.
overhang walls  is twice the time looks like speed reduce 50% 
ist this classic mode or arachne?

**Comment by SavouryMonkey** [comment]
> you have new features in 1.5 ... i think the speed settings are different between 1.4.5 and slow down at overhangs
> pls send the 3mf files as zip or look at the g-code for differences.
> overhang walls is twice the time looks like speed reduce 50%
> ist this classic mode or arachne?

It's Arachne in all 3 versions. Also I made sure that i compared every single setting, in every possible tab. They're identical, as are the material profiles and the printer with its settings. I'll upload the files in the morning.

**Comment by mckellar11** [comment]
Pretty sure this is precise walls, notice the most stark difference is inner wall time, which I think got changed a bit or is just generating differently now

**Comment by SavouryMonkey** [comment]
Like you've whished, here's the STL i tried on my comparison. It originated from here:
https://www.thingiverse.com/thing:4548782/files

Also i made sure to not overlook anything, every setting is, at least on the frontend, the same. Even the experimental precise wall option is turned off in all 3 instances of the slicer. 
[Landroid_Wheel_spike_slip-on.stl.zip](https://github.com/SoftFever/OrcaSlicer/files/11014761/Landroid_Wheel_spike_slip-on.stl.zip)

**Comment by hliebscher** [comment]
we need your 3mf as zip to compare the settings

**Comment by SavouryMonkey** [comment]
> we need your 3mf as zip to compare the settings

There ya go. 
[Archiv.zip](https://github.com/SoftFever/OrcaSlicer/files/11015048/Archiv.zip)

**Comment by hliebscher** [comment]
i found the difference :-)
in Printer z Hop Type is in 1.5 at Spiral it takes more time.  if off than the time at all is equal

![1](https://user-images.githubusercontent.com/9274162/226273629-0feb7b1e-8db6-4c20-b151-5c9668d53c0d.jpg)
![2](https://user-images.githubusercontent.com/9274162/226273631-c4627450-ce45-426b-b9a7-09e580ee5663.jpg)

**Comment by SavouryMonkey** [comment]
![Bildschirm­foto 2023-03-20 um 08 40 23 2](https://user-images.githubusercontent.com/41338731/226276701-bc5a964f-7ee9-4fcb-8580-758824b886a7.png)
![Bildschirm­foto 2023-03-20 um 08 38 38](https://user-images.githubusercontent.com/41338731/226276704-10e1ff0d-1b7b-4a1d-b6c0-21588565f498.png)


There's no spiral turned on.. It's weird, i did the same again, now with the corrected value of 20mm/s. Still different between mac and win. Also, i compared the project_settings.config - no difference (well, on the 1.5 versions) apart from the machies name. Yet one is faster then the other. 

Wir könnten auch deutsch reden :D 

[Archiv 2.zip](https://github.com/SoftFever/OrcaSlicer/files/11015370/Archiv.2.zip)

**Comment by hliebscher** [comment]
ok ;-) mein Vergleich was zwischen 1.4.5 und 1.5 lade mir gerade die 3mf  alleine der G code ist 2000 Zeilen länger
bin dabei  zwischen mac und win wird es immer ein paar unterschiede geben. die Zeit ist ja auch nur geschätzt !
wir können auch gerne mal telefonieren ;-)

**Comment by hliebscher** [comment]
> ok ;-) mein Vergleich was zwischen 1.4.5 und 1.5 lade mir gerade die 3mf alleine der G code ist 2000 Zeilen länger bin dabei zwischen mac und win wird es immer ein paar unterschiede geben. die Zeit ist ja auch nur geschätzt ! wir können auch gerne mal telefonieren ;-)

Hab übrigens auch den Landroid aber leider größere Räder und suche das File dafür ist ein 1500

**Comment by SavouryMonkey** [comment]
> 

https://www.thingiverse.com/search?q=Landroid+L&page=1&type=things&sort=relevant

Da sind einige für den L dabei. :D 

Es ist schon irgendwie verwirrend, wieso ist in der config die spirale, obwohl im frontend der z hop offensichtlich auf normal steht? Das ist doch ein Bug oder? 

Klar, wenn du mir noch irgendwie nen hinweis gibst wie wir unsere Kontaktdaten austauschen, ohne das sie für hinz und kunz ersichtlich sind. :D

**Comment by hliebscher** [comment]
hliebscher@gmail.com lösche ich gleich wieder
