### ISSUE TITLE
bug with X - Y hole compensation 

### ISSUE THREAD

**Issue by blazzsss** [SoftFever/OrcaSlicer#5390]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

Windows

### OS Version

windows 10

### Printer

hypercube

### How to reproduce

create a model with wholes on the sides or along z axis. create a x-y compensation under quality>percesion X - Y hole compensation. (i have mine to 0.15 makes wholes perfect) but it creates lines in the walls of the part that mess with dimensions
![Screenshot (114)](https://github.com/SoftFever/OrcaSlicer/assets/170156439/f7df8599-e1d1-4d89-98df-3c7100401bba)
![Screenshot (115)](https://github.com/SoftFever/OrcaSlicer/assets/170156439/afce49a9-8b8c-4d07-955d-a0b97778a1ee)

### Actual results

it creates lines in the walls of the part that mess with the dimensions
![Screenshot (115)](https://github.com/SoftFever/OrcaSlicer/assets/170156439/4421bdd0-4e6e-4238-8a74-e3bebe41c010)

### Expected results

no lines to the outer wall
![Screenshot (114)](https://github.com/SoftFever/OrcaSlicer/assets/170156439/a2c5b246-e60c-40d9-9fde-f98ab6d8324a)

### Project file & Debug log uploads

[WithItONandOff.zip](https://github.com/SoftFever/OrcaSlicer/files/15359687/WithItONandOff.zip)
zip

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by DVSVIDEO** [comment]
I have experienced the same problem, but I have not figured out that this is the cause.
Thank you.
