### ISSUE TITLE
Final compensation factor for small area infill flow compensation model must be 1.0

### ISSUE THREAD

**Issue by lennoxdk** [SoftFever/OrcaSlicer#5392]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0 and 2.1

### Operating System (OS)

Windows

### OS Version

windows 11

### Printer

voron 2.4 pro

### How to reproduce

slicing a stl with the folloing  flow compensation model 

0, 0
0.2, 0.4444
0.4, 0.6145
0.6, 0.7059
0.8, 0.7619
1.5, 0.8571
2, 0.8889
3, 0.9231
5, 0.9520
10, 1.0

### Actual results

error "Final compensation factor for small area infill flow compensation model must be 1.0"

### Expected results

slice with out the error popping op

### Project file & Debug log uploads

[log.zip](https://github.com/SoftFever/OrcaSlicer/files/15362901/log.zip)
[Voron_Design_Cube_v7.zip](https://github.com/SoftFever/OrcaSlicer/files/15362905/Voron_Design_Cube_v7.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by Manu512** [comment]
When I activated compensation and try to slice I have "A fatal error occurred: "Acces Violation" Save and Restart Needed".
