### ISSUE TITLE
Feature request: Print order of objects

### ISSUE THREAD

**Issue by Prutsium** [SoftFever/OrcaSlicer#540]
Would it be possible to get similar implementation in Orca Slicer (damn will never get used to that name :) ) like SuperSlicer / PrusaSlicer that you can sort what file would be printed first?
The idea behind is that i often put a small square of 0.2 high to ensure nozzle offset is ok before the actual print starts.

In PS/SS this was done by just moving the concerning object in the top of the list and that one would be printed first.
SuperSlicer screenshots:
![image](https://user-images.githubusercontent.com/42968695/226274265-1e6b9be5-fac6-4a81-9717-172498be9de8.png)
![image](https://user-images.githubusercontent.com/42968695/226274315-0b27795d-6525-41f8-ac77-1cf73e2ad692.png)

**Comment by ab3dgeek** [comment]
Yeah that would be great 👍🏻🤓

**Comment by H4kunaM4tata** [comment]
I have requested this a few months ago, perhaps my explanation was broken.
Glad to see this being implemented.

**Comment by mrThe** [comment]
Bump. Can we please reopen this? That may not only solve OP issue, but also speedup print when you are printing a lot of objects at a time, because user can optimize part placement in a way it will require much less travel moves.
cc @SoftFever

**Comment by Felix14-v2** [comment]
> GitHub bot: This issue was closed because it has been inactive for 7 days since being marked as stale.

WTH?

The most stupid bot ever made. The issue is still relevant.

**Comment by mrThe** [comment]
@Felix14-v2 While bot is stupid for sure, issue is actually resolved: https://github.com/SoftFever/OrcaSlicer/pull/3685

But you need a nightly build of orca.

**Comment by Felix14-v2** [comment]
> issue is actually resolved: #3685 
Not resolved. I still can't reorder parts of the model when printing them by layer.

**Comment by HakunMatat4** [comment]
> > issue is actually resolved: #3685 
> 
> Not resolved. I still can't reorder parts of the model when printing them by layer.

It's resolved. I've been using for some time now on 2.0.0 nightly releases, I can print on the order I want by dragging the models around.
You need to change to object view tho.

**Comment by Felix14-v2** [comment]
> I can print on the order I want by dragging the models around.

Dragging a model in the list does nothing when printing by layer is selected.

**Comment by HakunMatat4** [comment]
> > I can print on the order I want by dragging the models around.
> 
> Dragging a model in the list does nothing when printing by layer is selected.

Yes, it does and I use it everyday.
In fact, I opened similar ticket myself in the past to solve this and it has been working just fine for releases now. Noisefox worked on it 

I'm on Linux and printing by layer NOT object, I can alter the order it is being printed by dragging the parts in the list.

**Comment by Felix14-v2** [comment]
> Yes, it does and I use it everyday.

At least for me it doesn't work. 2.0.0 beta
https://github.com/SoftFever/OrcaSlicer/assets/75726196/0c4a91c1-1977-4921-af31-95c4661f708d

**Comment by SoftFever** [comment]
> > Yes, it does and I use it everyday.
> 
> At least for me it doesn't work. 2.0.0 beta
> 
>  2024-03-27.15-50-19.trim.mp4

You need to change the setting here:
![image](https://github.com/SoftFever/OrcaSlicer/assets/103989404/1e8bdb16-7a68-4101-bacf-8fdaec38ddbd)

**Comment by Felix14-v2** [comment]
> You need to change the setting here:

Still doesn't work.

https://github.com/SoftFever/OrcaSlicer/assets/75726196/01780066-1b52-4d16-b1a8-3ff0feaee296

I suspect it only works for individual models, not for the model parts.

**Comment by mrThe** [comment]
>  it only works for individual models, not for the model parts.

It is. Don't load models as a single model. Or split it using built in split feature. It's sure not very convenient, but it is how it is.

**Comment by Felix14-v2** [comment]
I have to load models with parts because this buggy software doesn't support moving individual models upper to print them in floating position. Orca forces your models to lie on a plate. But I need to reorder floating parts. пятница, 10 мая 2024г., 17:06 +03:00 от mr.The  ***@***.*** :

**Comment by the-relentless-epee** [comment]
Any updates to this feature @SoftFever ?
