### ISSUE TITLE
Add Calibration for Ironing

### ISSUE THREAD

**Issue by markleaf131313** [SoftFever/OrcaSlicer#5411]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Usually need to do some sort of calibration for the ironing setting depending on filament and creating a test print with a range of settings can be a bit tedious, especially adding things like text that correspond to the setting used to make the geometry a bit more complex to test the ironing.

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

Add ironing to calibration with settings to choose the line spacing and pattern along with a range of speed and flow rate. With iteration step. Then generate test print geometry using the settings and ranges adding text to the print that corresponds with the setting used. I was thinking blocks with the percentage of flow on it as embedded text. Then connected by 2-3 layers for the corresponding speeds to help choose better ironing settings.

**Comment by kylek29** [comment]
Came here to suggest this as I've seen it pop up in numerous places lately, seems to be a new trend for people to want to calibrate it.

**Comment by JaneSmith** [comment]
Why is this not planned? It would be a really useful feature, and (unless I'm missing something) seems like it would be really easy to add to the already-existing calibration menu?
