### ISSUE TITLE
Question about wall line width 

### ISSUE THREAD

**Issue by olcayoren** [SoftFever/OrcaSlicer#5417]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Why does the filament coming out of the 0.4mm nozzle appear to be 0.45? What is the mathematical formula for this?
![width](https://github.com/SoftFever/OrcaSlicer/assets/33813227/61e12c39-015c-452a-b36e-d590eaf17bd4)

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

None

**Comment by buzzhuzz** [comment]
https://manual.slic3r.org/advanced/flow-math

**Comment by olcayoren** [comment]
> https://manual.slic3r.org/advanced/flow-math
> 
> Just realized that question not about math itself, but regarding settings handling.
> 
> In your case better to express width in percentage: set it 100% to explicitly make it to be deducted from the nozzle size.
> 
> Seems like setting it to 0 exposes some bug in configuration.

Yes, your determination is correct, when you set the default width to 0, the width is 0.45mm. But when I set it to 100% it shows 0.40mm.

@SoftFever Is this a bug?

**Comment by SoftFever** [comment]
0 means automatic or default in this case. When you put a absolute non zero value or percentage, Orca will calculate it accordingly
