### ISSUE TITLE
Since 1.5 the printer config isnt saved correctly

### ISSUE THREAD

**Issue by tommy536** [SoftFever/OrcaSlicer#542]
**Describe the bug**
After using 1.5, at every new start of the program the printer settings are an old / default one. When i saved the changes new, restart the program, the olf values registered on closing the program.

**Printer model**
Voron 2.4

**Desktop (please complete the following information):**
 - OS: Windows
 - 10

**Comment by magicsoccer** [comment]
Same problem here.

Even if you rename the old directory and remove the duplicate entries in the new directory, they still appear when you start OrcaSlicer again.

**Comment by MitjaHenner** [comment]
Deleting the default user folder helped.

Windows 11

**Comment by tommy536** [comment]
How exactly do I have to proceed to avoid the problem? I deleted the Windows/User/DefaultUser folder but the problem persists.

**Comment by magicsoccer** [comment]
My solution:

I deleted:
C:\Users\usernaem\AppData\Local\BambuStudio-SoftFever\
C:\Users\username\AppData\Roaming\BambuStudio-SoftFever\

I edited:
C:\Users\Andreas\AppData\Roaming\OrcaSlicer\user\1234567890\
