### ISSUE TITLE
Profile for Creality Ender-3 V3 CoreXZ

### ISSUE THREAD

**Issue by 3printed** [SoftFever/OrcaSlicer#5424]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I tried to modify the SE profile, but i gets this error, "Error key 502 main board execption".

(Pardon me if i made the request on wrong area, as this is first time i am requesting something)

This image is not of my printer, but I got the same error.
![image](https://github.com/SoftFever/OrcaSlicer/assets/149824624/e59dae3b-2350-42ce-8646-a876f999d1fc)

### Which printers will be beneficial to this feature?

Others

### Describe the solution you'd like

Pre Built Profile for this printer

**Comment by RipperGOT** [comment]
https://github.com/SoftFever/OrcaSlicer/issues/5344#issuecomment-2108838295

Try the daily/dev version, it has the Ender 3 V3 there
https://github.com/SoftFever/OrcaSlicer/releases/tag/nightly-builds
