### ISSUE TITLE
Implement "Device View - reload"

### ISSUE THREAD

**Issue by MoppelMat** [SoftFever/OrcaSlicer#543]
My Klipper Mainsail device view stops working sometimes and I need to reload the web page. 

Sadly the Device view in OrcaSlicer has no reload option. I tried F5 and everything, but cannot get it to work. 

I have to restart the slicer to get the view to work again.

<img width="1070" alt="image" src="https://user-images.githubusercontent.com/55950637/226314154-f0e531ea-3304-45e1-b425-b3a01c32cce7.png">

**Comment by SoftFever** [comment]
Done.
F5 is shortcut key in 1.60

**Comment by asychev** [comment]
Does not work on OSX

**Comment by therick0996** [comment]
i've found changing the printer, and then changing it back, refreshes it

**Comment by negativesupply** [comment]
I've been having this issue too, on OSX. F5 doesn't work. CMD+R would be a good option because it matches safari for reloading pages.

**Comment by hugoalves6** [comment]
Hello, i just got this problem too.
![image](https://github.com/SoftFever/OrcaSlicer/assets/4621600/147ddb9e-af2f-4c05-9224-9181eaf46a61)

**Comment by SoftFever** [comment]
> Hello, i just got this problem too. ![image](https://private-user-images.githubusercontent.com/4621600/317762181-147ddb9e-af2f-4c05-9224-9181eaf46a61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MzYwNjAsIm5iZiI6MTcxMTYzNTc2MCwicGF0aCI6Ii80NjIxNjAwLzMxNzc2MjE4MS0xNDdkZGI5ZS1hZjJmLTRjMDUtOTIyNC05MTgxZWFmNDZhNjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjhUMTQyMjQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmIwZDdmYjNlMWVkYzU5ZDE3ZWFmODk2NjE4YzlmM2ExNWQxMzhiMDFmNjQ4YjJhZTEyMDJjZWYwYmE4NjczYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.qijKTSi4cnQv9eZK_QJodhXg7trBlvwhE25Fkd-Ddh4)

You can use right click menu to reload the page

**Comment by ekle** [comment]
With the "Host Type" "CrealityPrint" right click does not work on linux.

Any other ways to force a reload?
