### ISSUE TITLE
OrcaSlicer installed on network drive makes it super slow

### ISSUE THREAD

**Issue by Bumblebiber** [SoftFever/OrcaSlicer#5432]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

Windows

### OS Version

-

### Printer

BambuLab X1E

### How to reproduce

Store your OrcaSlicer folder on a network drive.
I've done this so all my colleagues can use the same settings. It used to work with SuperSlicer and PrusaSlicer pretty well.

### Actual results

When making a change on any setting, it takes around 5-10 seconds until it's set. During that time I can't do anything. Some features, like setting purge volumes even take much longer. I don't know why this all takes so long. Maybe because all settings changes made are being stored into some backup file? 

### Expected results

Changed settings should be stored in RAM first, only when you leave OrcaSlicer these settings should be saved. 

### Project file & Debug log uploads

None

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by pluciorx** [comment]
sounds like the same problem as #997 and #3899

**Comment by istyszy** [comment]
Nothing??? No fix?
