### ISSUE TITLE
UI xfce4

### ISSUE THREAD

**Issue by big-vl** [SoftFever/OrcaSlicer#5433]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

Linux

### OS Version

Archlinux

### Printer

Flashforge m5 Flyingbear Ghost 6

### How to reproduce

![Screenshot_2024-05-23_11-21-44](https://github.com/SoftFever/OrcaSlicer/assets/60448373/b16acd71-c8a3-418f-b6cb-f7dbf911cf80)
![Screenshot_2024-05-23_11-21-24](https://github.com/SoftFever/OrcaSlicer/assets/60448373/462c9b30-d302-4f44-a990-6f19eac3914c)

### Actual results

no visible text

### Expected results

visible text

### Project file & Debug log uploads

That is unnecessary

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by MathieuIko** [comment]
I might add this issue only appears when using a **dark theme** on Xfce4, e.g. Greybird-dark or Adwaita-dark; on light themes, all texts are visible.
It also strangely affects only _some_ texts, such as labels on modals (like screenshot in OP post) or title of _some_ tabs in Printer settings, while other texts are visible.

SuperSlicer and PrusaSlicer are not affected by this issue (same OS configuration with Xfce4 and dark theme).

**Comment by big-vl** [comment]
update orcaslicer, fix
