### ISSUE TITLE
Auto-Arrange placing objects off the edge of circular build plates instead of centred

### ISSUE THREAD

**Issue by StarkRG** [SoftFever/OrcaSlicer#5434]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

Linux

### OS Version

Pop!_OS 22.04 LTS

### Printer

FLSun Super Racer

### How to reproduce

1. Create new project
2. Add part (even just a primitive is fine)
3. Click auto arrange button (either the one on the plate or the arrange all button at the top and then "arrange" in the pop-up window)

### Actual results

Part gets moved to the lower left corner which, because it's a circular build plate, is off the edge of the printable area.

### Expected results

Parts should be arranged around the center of the plate. Ideally in a radial pattern for circular plates, but grid is acceptable too as long as it's not pushing items outside the printable area.

### Project file & Debug log uploads

[trolleywheelbase.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/15414142/trolleywheelbase.3mf.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Anything else?

![image](https://github.com/SoftFever/OrcaSlicer/assets/451657/ee906601-0129-4c04-a601-de28c3fe5490)

This might be the same bug as #3515 however that issue causes the object to be moved entirely off any of the printable areas, this one seems to be attempting to place objects in the front left corner of a rectangular region surrounding the circular build plate.

**Comment by StarkRG** [comment]
This is definitely still happening.

**Comment by karol2149** [comment]
Hello, 
try to set "Best object position" to X:0.5 and Y:0.5. This parameter is located in "printer settings" in "basic information" tab.  For me this was fix for the issue.

**Comment by LucianBuzzo** [comment]
Thanks @karol2149 that fixed the issue for me 👍
