### ISSUE TITLE
Make View->Show Overhang "Sticky"

### ISSUE THREAD

**Issue by jcgperry** [SoftFever/OrcaSlicer#5437]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I like having "Show Overhang" enabled. The issue is that it doesn't get saved as a configuration item, so every time I restart Orca Slicer I have to enable it again in the View Menu.

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

Add it to the "app": {... section in OrcaSlicer.conf

**Comment by theonlytruth** [comment]
Please reopen this request as I would also like to see this feature which should be added easily.
