### ISSUE TITLE
After Upgrade - Requires The Application To Be Opened Twice Before User Profiles For Printers And Filament Are Available

### ISSUE THREAD

**Issue by arch3angel** [SoftFever/OrcaSlicer#5438]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

Windows

### OS Version

Microsoft Windows 10 Pro - v10.0.19045 Build 19045

### Additional system information

System Type: x64-based PC
Processor: Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz, 2304 Mhz, 8 Core(s), 16 Logical Processor(s)
Physical Memory (RAM): 64.0 GB
Graphics: NVIDIA GeForce RTX 2070 Super With Max-Q (8 GB GDDR6)

### Printer

Creality K1 Max - But Happens With All 18 Printers I have (Mix Match Of Printers)

### How to reproduce

1. Go to start menu, click the OrcaSlicer icon to start the application
2. OcraSlicer opens and when you go to the drop down for the printers, no User Presets are visible.
3. Close the application
4. Reopen the application
5. when you go to the drop down for the printers, everything visible.

This is not an issue with a project, it happens even when trying to start a new project.

### Actual results

All User Presets are visible

### Expected results

All User Presets become visible

### Project file & Debug log uploads

This is not an issue with a project, it happens even when trying to start a new project.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Anything else?

N/A

**Comment by winbard** [comment]
Hi,

I have the same problem. Orca Slicer 2 with Windows 10 Pro. I unistall Orca, delete all files on pc, clear regedit.
New install the same problem.
After the instalation i chose one printer (K1max) and after that i load my profiles from orca slicer back.
In the version from orca slicer before i had not this problem.

**Comment by epicylon** [comment]
I also have the same problem on 2.1.0-beta

**Comment by mindkill666** [comment]
Same here, i went back to version 1.9.1. 
No problems with that version.

**Comment by sam0622** [comment]
I have the same issue on 2.0.0 and 2.1.0-beta

**Comment by VANHEKENT** [comment]
As do i. I have had the issue since the last two official updates.
