### ISSUE TITLE
Add Creality Print API to connect and send g-code to printer

### ISSUE THREAD

**Issue by zdybo** [SoftFever/OrcaSlicer#5457]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

It would be great if support for sending g-code to Creality printers was added. Currently, this can be circumvented by generating a local g-code and sending it through the Creality GUI. Another option is to root the printer and install mainsail/fluidd. However, these options are not convenient and are not easy for everyone. In addition, Orca supports Creality printers profiles, it would simply make sense for this support to be comprehensive. For this reason, please add direct printing functionality from the “Print” button.

### Which printers will be beneficial to this feature?

Klipper

### Describe the solution you'd like

Add direct printing functionality from the “Print” button for Creality Printers.

**Comment by samohd** [comment]
>> generating a local g-code and sending it through the Creality GUI.

[zdybo](https://github.com/zdybo), I presume by Creality GUI, you mean Creality Print? On Windows, I'm trying to figure out how to send an stl file exported by a FreeCAD macro into an already running Creality Print. I don't want Creality Print to send it to the printer. Note that additionally, I may also want to be able to tell Creality Print to delete all currently objects. Is this something you know how to do?
