### ISSUE TITLE
Only one wall on top surfaces Arachne issue

### ISSUE THREAD

**Issue by blonestar** [SoftFever/OrcaSlicer#547]
**Only one wall on top surface does not work correctly in Arachne mode**
Single wall mode does work for every top layer but not for the all of the top ~~layers~~ sufaces.

**3mf File for This Bug**
It is easy to replicate, I think no need for 3mf.

**To Reproduce**
Just switching between Arachne and Classic wall mod with the single wall option turned on.

**Expected behavior**
I guess all top ~~layers~~ surfaces should have single wall in Arachne mod as well, as it has in Classic wall mode.

**Screenshots**
![image](https://user-images.githubusercontent.com/5240133/226322686-f4928ea0-7c42-43f9-b864-899411b7769c.png)
![image](https://user-images.githubusercontent.com/5240133/226322710-79d6d2ca-7388-4617-bf6d-d4f3c669d01f.png)

**Printer model**
Voron Trident 250 #VT.976

**Desktop:**
 - OS: up-to-date Windows 10

**Comment by Photogad** [comment]
Workign as intended, top layer is top layer. There is only one top layer.

**Comment by blonestar** [comment]
I disagree. Have you look into my both screenshots btw?

**Comment by blonestar** [comment]
When I said top layer I meant to say top surfaces, as the option is called.

**Comment by blonestar** [comment]
![image](https://user-images.githubusercontent.com/5240133/226476773-f1e09638-07ee-45d9-ab85-d85fe97a1a2c.png)

**Comment by npoulos** [comment]
”Surfaces” is plural which means there can be many top surfaces no matter the height.

**Comment by blonestar** [comment]
Just confirming the issue in the v1.6.1

![image](https://user-images.githubusercontent.com/5240133/230446132-350f2e7b-0c3a-43a8-a424-fd2f90df214d.png)
