### ISSUE TITLE
I found the reason why "Raft contact Z distance" missing in Process - Is an advisory needed?

### ISSUE THREAD

**Issue by Ergonomicmike** [SoftFever/OrcaSlicer#5478]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.0-alpha

### Operating System (OS)

Windows

### OS Version

Win10

### Printer

Ender 3 v2

### How to reproduce

In Orca,
Process - Global - Advanced
Search for "Raft." Among the entries will be "Raft contact Z distance." 
Click on it.

### Actual results

Nothing happens. It doesn't take you to a "Raft contact Z distance" setting. And there is no "Raft contact Z distance" setting in the Raft section under Support.

### Expected results

I expect to be able to go "Raft contact Z distance" to be able to set a distance.

If Raft distance has been combined with some other support distance, then either 1) the Search function shouldn't return "Raft contact Z distance," or 2) the Search function should take you to the pertinent support setting.

### Project file & Debug log uploads

[ziptie_150mm_for_Orca_report.zip](https://github.com/SoftFever/OrcaSlicer/files/15455916/ziptie_150mm_for_Orca_report.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by buzzhuzz** [comment]
Set number of raft layers to non-zero value and you'll see "Raft contact z distance" config entry.

**Comment by Ergonomicmike** [comment]
It's set to "1" now. I tried increasing it (2, 3, 4) before reporting the issue. No change here.

**Comment by Ergonomicmike** [comment]
![Orca_no_raft_distance](https://github.com/SoftFever/OrcaSlicer/assets/15025888/d7cc3c20-208d-426b-9ae0-125f737f2531)

**Comment by kisslorand** [comment]
This is what I have in Win11 with latest 2.1.0-alpha.

![image](https://github.com/SoftFever/OrcaSlicer/assets/50251547/2e9ca2ce-5c8c-4ad3-8493-a64fc0239f5e)

**Comment by Ergonomicmike** [comment]
Tnx. I have the portable alpha from two days ago. (Latest, AFAIK.) I'll try again when the next update is released.

**Comment by Ergonomicmike** [comment]
I just now downloaded the latest portable alpha. (5 hours old.) Still no Raft contact Z distance showing here.

Not even a placeholder for it. (So it doesn't appear to be a graphic card/driver problem on my end.)

Anyone able to reproduce this issue?

**Comment by Ergonomicmike** [comment]
Just downloaded 2.1.0-beta. Still no Raft contact Z distance for me.

Can someone please load my project file and report what they see? Perhaps this issue is related to some other settings that I set in that project?

**Comment by Ergonomicmike** [comment]
I just downloaded 2.1.0-beta_portable nightly, 7 hours old as of this writing. 

Raft contact Z distance works for a new project. (When raft layers > 0.) But still not working on the project that I uploaded here. (A zip-tie.)

So apparently there must be some setting in my project file that prevents/is incompatible with Raft contact Z distance. Or the model itself?

I'll try to experiment by toggling/trying other settings and report back.

**Comment by Ergonomicmike** [comment]
Okay, I found what causes "Raft contact Z distance" to disappear.

I had set "Top Z distance" to 0 in my project.

"Raft contact Z distance" will show with any number > 0.

Should there be an advisory about this in the pop up for "Top Z distance"? 

I've edited the Title. I'll let the dev's close this "issue" after deciding its merits.

**Comment by Ergonomicmike** [comment]
FWIW, choosing the (Experimental) Tree Slim style support sets "Top Z distance" to 0. 

But unchoosing it doesn't return Top Z distance to nominal.
