### ISSUE TITLE
"other layers" bed temperature don't apply when disabling supports or disabling brims

### ISSUE THREAD

**Issue by SilencedFrost** [SoftFever/OrcaSlicer#5485]
### Is there an existing issue for this problem?

- [ ] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

Windows

### OS Version

11 Pro

### Additional system information

CPU: Ryzen 3 3300x
GPU: Asus Rog Strix 1070ti

### Printer

Neptune 4 Max

### How to reproduce

1. Go to filament settings, set first layer bed temperature to 70 degree, set other layers to 60 degree
2. In process, turn turn off supports/disable auto brim
3. Slice
4. Check gcode preview at the start of layer 2/end of layer 1

### Actual results

M104 is present (Nozzle temp), but M140 is not (Bed temp)
Printer does not lower temps after first layer because the gcode is not present

### Expected results

M140 S60 should be present
Printer should lower bed temperature to 60 after first layer

### Project file & Debug log uploads

[No bed temp change bug report.zip](https://github.com/SoftFever/OrcaSlicer/files/15467252/No.bed.temp.change.bug.report.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Anything else?

![image](https://github.com/SoftFever/OrcaSlicer/assets/54757660/1b75ad69-1575-4a02-b376-e52792cf6151)

**Comment by vgdh** [comment]
related
https://github.com/SoftFever/OrcaSlicer/issues/4676
https://github.com/SoftFever/OrcaSlicer/issues/3015

**Comment by igiannakas** [comment]
@SoftFever 
I've come across this issue too today and I've been trying to fix this over the last couple of days but it's so difficult to reproduce. I currently have two Orca windows open - one run from Xcode and one compiled binary and the Xcode one just doesnt do it for some reason!

Smells like some race condition somewhere likely in the function below. It checks if the desired bed temperature is equal to the last bed temperature. However I notice that this variable is not initialised in the constructor, unless I'm missing something?

![image](https://github.com/SoftFever/OrcaSlicer/assets/59056762/40d85d9f-392c-4ff6-b2e9-47cd92fa7cd2)

Constructor:
![image](https://github.com/SoftFever/OrcaSlicer/assets/59056762/ef41d9c5-f71a-416c-b835-159fd36304f4)

I'll try debugging this but it's almost impossible to replicate in my dev system vs. the operating binary. 

A workaround could be to disable the check and always emit the set bed temperature on each layer. That is not elegant but not the end of the world either? Assuming that the reason its not being set is that its failing that check, which I cannot prove :P

**Comment by igiannakas** [comment]
PR pushed. Initialising the bed temperature variable with 0 in the constructor seems to have resolved this. Testers needed in the PR.
