### ISSUE TITLE
Exclude Object

### ISSUE THREAD

**Issue by LoboThirteen** [SoftFever/OrcaSlicer#549]
EDIT: The file is called "preprocess_cancellation_windows.exe". That has worked so far. I have now changed the name to: "preprocess_cancellation.exe" and now it works again.

The Exclude Object function no longer works correctly. I always get the following error message in the screenshot. The script is of course in the Orca folder, just like in Soft Fever. In Soft Fever, the feature works as it should.

**Printer model**
RatRig V-Core3

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: OrcaSlicer 1.5.0

![Screenshot 2023-03-20 170910](https://user-images.githubusercontent.com/76623273/226401276-98c8f5dd-ce3c-4a44-becb-5545ec448940.png)

**Comment by SoftFever** [comment]
It looks like you have solved the issue.
Closing it now.

FYI, OrcaSlicer will support Klipper `exclude_object` natively soon.

**Comment by rkarlsba** [comment]
Any idea when "soon" will be?
