### ISSUE TITLE
Variable Layer High does not work with cleaning tower when there are different Objects

### ISSUE THREAD

**Issue by Lummsky** [SoftFever/OrcaSlicer#5493]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I am using variable layer high on an multicolor Object and ad put other objects to the bed. 
Then Orca says: Cleaning Tower is not possible when the objects have different Layer high. 

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

It would be nice if its possible to have a button like "put the varibale layer high to all objects"

**Comment by 16gadge** [comment]
yes that would help so much

**Comment by Lummsky** [comment]
Perfect. Thank you a lot!
In the project I am using this function it woked perfectly fine.
