### ISSUE TITLE
Stack Objects. Put different material to devide parts.

### ISSUE THREAD

**Issue by Lummsky** [SoftFever/OrcaSlicer#5494]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I trie to stack parts(PLA-Tough). So in my case it´s possible to print at leat 100 parts during one night instead of just 30.

So I put the on top of each other and am using a third part to devide and support them. This part is printed with PETG. This makes it possible to have clean surfaces and seperate these parts easily. But When I stack these three(or more parts) to a tower Orca makes them to one part while printing and does not print top-layers to the end of Objects.

I do this with 100% infill settings in the seperating layers put the printer does not slow down speed or fan for the new 1st layer withe new material and it does not fill gaps like on top or groundlayers.

<img width="1916" alt="Screenshot1" src="https://github.com/SoftFever/OrcaSlicer/assets/158855622/99d7faaf-d6e9-4034-a877-25d7d4b59062">
<img width="1918" alt="Screenshot2" src="https://github.com/SoftFever/OrcaSlicer/assets/158855622/46e6bcea-599b-433c-9872-8a7a1fb66e6a">
<img width="1920" alt="Screenshot3" src="https://github.com/SoftFever/OrcaSlicer/assets/158855622/381ac078-b280-4ce1-8a48-50b99a2afb2a">
![Stapeln1](https://github.com/SoftFever/OrcaSlicer/assets/158855622/d08a4ebb-eb09-4f71-aa49-9bf508395fdb)

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

I want to have the option to stack parts and print them like if they where laying on the bed. 
Including first layer settings like speed and cooling and closing gaps etc.

There is enormous potential to make series parts on small printers.

![Stapeln2](https://github.com/SoftFever/OrcaSlicer/assets/158855622/50a1bd48-3008-49f6-bfe6-cb4bc0042b92)

**Comment by rsglobal** [comment]
That works in most cases, even without support material. Just creating a gap between objects is enough. For PETG - 1 layer gap is good. For the ABS - you need less than that, like half a layer gap.

There's no issue to stack them together in slicer by grouping it into an assembly and using move command.

Usually, parts can be separated by bare hands using a little force.

However, it would be nice to be able to select a gap between parts in millimeters, not in layers, because you may want to find the sweet spot for your material and printing parameters.

**Comment by GavinHanson** [comment]
Can this be re-opened? with the rise of tool changing printers this feature would be invaluable to be able to easily 'stack' STL's with a pre-defined support material.

Whilst yes its possible via workarounds its not ideal and is very time consuming.
