### ISSUE TITLE
Multiple Filament Large Temperature Differences

### ISSUE THREAD

**Issue by Durahl** [SoftFever/OrcaSlicer#5501]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

Windows

### OS Version

Windows 11

### Printer

Voron 2.4 with ERCF running HappyHare Software

### How to reproduce

1. Import / create a Multi Material File
2. Assign one Part with `ASA` and another with `PLA`
3. OrcaSlicer will immediately report issue:
![Screenshot 2024-05-30 091648](https://github.com/SoftFever/OrcaSlicer/assets/10585968/1f4c3e40-52de-4c93-af51-96a238a90eee)

### Actual results

My issue with this Error Message / Limitation is it not being tied to the actual Temperatures ( Range / Nozzle / Bed ) but rather the Material Selection ( ASA / PLA / PETG / etc... ).

I like to use a particular `PLA` Color for small Inlays ( not available in `ABS` / `ASA` ) despite the majority of the Part being done in `ASA` and while trying to dodge the Error Message by raising all the Temperatures of the `PLA` I noticed the Error Message persisting only to be finally resolved once I changed the `Material Type` from `PLA` to `ASA` even solving the issue with the Temperatures having been reverted back to `PLA` levels completely circumventing the purpose of the Error Message.

The way how this Safety Feature is implemented ( tied to the Material Type instead of the Temperatures ) is technically in my favor but still kinda wrong.
Perhaps change it to the actual Temperatures with the option to ignore the Error Message **_AND_** a value being display as to how close the temperatures need to be within range? 🤔

### Expected results

Error Message being caused by actual Temperature Differences between the selected Materials, not the Material Type.

### Project file & Debug log uploads

Shouldn't be necessary.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Anything else?

Nuffin...

**Comment by fabio-s-franco** [comment]
/reopen

still an issue
