### ISSUE TITLE
Linux -- g-code window doesnt show up

### ISSUE THREAD

**Issue by TexZeTech** [SoftFever/OrcaSlicer#551]
**Version**
OrcaSlicer V1.50 Appimage

**Describe the bug**
I have tried to use the new g-code window and have not had any success in having it show up.

**To Reproduce**
Run the appimage and load up a .stl of choice and slice. When done slicing press the 'c' key.
I have also tried toggling the "Show g-code window" in the Preferences dialog.

**Expected behavior**
For the gcode window to show up.

**Other notes**
I have also tried this in a Ubuntu 22.04.2 LTS VM and had the same result.

**Desktop & hardware:**
Operating System: Manjaro Linux
KDE Plasma Version: 5.26.5
KDE Frameworks Version: 5.103.0
Qt Version: 5.15.8
Kernel Version: 5.15.102-1-MANJARO (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-3770K CPU @ 3.50GHz
Memory: 15.6 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1080/PCIe/SSE2

**Comment by SoftFever** [comment]
The g-code window will only show up after you move the horizontal slider bar

**Comment by TexZeTech** [comment]
Ah I tried the vertical one and assumed both would trigger but didn't try the horizontal. Could it be triggered by both?

**Comment by TexZeTech** [comment]
Closed as not a bug. Just PEBKAC
