### ISSUE TITLE
Prime tower doesnt honer size specified

### ISSUE THREAD

**Issue by Prutsium** [SoftFever/OrcaSlicer#5515]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

Windows

### OS Version

Win11

### Printer

Vcore4 IDEX

### How to reproduce

See attached .3mf

### Actual results

When specifying a prime tower of 10mm with a purge volume of 3mm3 it creates a rather large prime tower (see image)
![image](https://github.com/SoftFever/OrcaSlicer/assets/42968695/63fa71ca-20ce-4818-8ffc-adb9dd5682b4)

When the 10mm parameter is set to 2 it honors the requested size
![image](https://github.com/SoftFever/OrcaSlicer/assets/42968695/05c186c5-d518-4498-b746-bad95148ce77)

### Expected results

A prime tower of 10x10mm

### Project file & Debug log uploads

[VC4-300-IDEX-ORCA-Cubes.zip](https://github.com/user-attachments/files/15512179/VC4-300-IDEX-ORCA-Cubes.zip)

### Checklist of files to include

- [ ] Log file
- [x] Project file

**Comment by hiltpatr** [comment]
I too have noticed the size of the prime tower being very inconsistent. I try to shrink the width to 10mm on the snapmaker J1 and the prime tower goes thin until I slice the model or try to adjust the width again. Then the tower stretches out across the build plate. I am trying to cut down the prime tower size for Idex printing where you don't need as much purge.

**Comment by Prutsium** [comment]
Found the issue and its not the slicers fault. Reduce purge volume for
color changes.

**Comment by MIIB1** [comment]
me to same problem

**Comment by traxman25** [comment]
The prime tower is using purge volume settings from single nozzle multi color printing. However this setting should be disabled when using a prime tower with multi tool printing as each tool/filament has a setting for it's own prime volume.

**Comment by MIIB1** [comment]
Hello,

So for my Snapmaker A350 dual extruder should I disable it correct?

Thank you
