### ISSUE TITLE
STP file reader turns concave/hole geometry to convex

### ISSUE THREAD

**Issue by spamwax** [SoftFever/OrcaSlicer#5523]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0

### Operating System (OS)

Windows

### OS Version

Windows 11

### Printer

Creality CR-6

### How to reproduce

1. Import the attached STEP files in Orca
2. Inspect the parts

[Block-with-spherical-holes.zip](https://github.com/user-attachments/files/15516989/Ball-0.95.zip)

### Actual results

Spheres/holes created using "Revolve" feature of CAD software are randomly(?) presented as protruded solid spheres.

![orca1](https://github.com/SoftFever/OrcaSlicer/assets/1251233/a6b8ad20-104a-4764-a313-3a476427d996)
![orca2](https://github.com/SoftFever/OrcaSlicer/assets/1251233/1b933ef3-a61c-4939-9c67-ecafcb93cc6f)

### Expected results

There should be 2 carved-out spheres in each part.

![fusion](https://github.com/SoftFever/OrcaSlicer/assets/1251233/31dafb66-667d-4718-990f-e8cc1a24525a)

### Project file & Debug log uploads

[log.zip](https://github.com/user-attachments/files/15516967/log.zip)

[step-file-bug.zip](https://github.com/user-attachments/files/15516975/step-file-bug.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Anything else?

1. I have opened the attached STEP files in other viewers such as *Open STEP Viewer* and they are rendered correctly.
2. This can also be reproduced in PrusaSlicer (v2.7.4)

**Comment by foreachthing** [comment]
Funky STEP files you got there....
I opened them in SolidWorks (looked as you showed) and exported those as STEP again and it worked as expected:

![image](https://github.com/SoftFever/OrcaSlicer/assets/10420187/e05df5b4-973c-4e0f-a6ec-7282e6f58b35)

What CAD have you been using?

**Comment by spamwax** [comment]
> Funky STEP files you got there.... I opened them in SolidWorks (looked as you showed) and exported 
> What CAD have you been using?
They are exported by AutoDesk Fusion 360. As mentioned, all of online STEP viewers I tried (plus *Open STEP Viewer* software on Windows) render the funky files correctly.

**Comment by foreachthing** [comment]
I agree with you that Orca can improve on the STEP import. I said "funky" because ir looks good in SolidWorks and "inverted" in Orca...

**Comment by foreachthing** [comment]
Might be related:  https://github.com/SoftFever/OrcaSlicer/issues/6560

**Comment by marcosikkens** [comment]
I closed my issue because it has the same problem as this one. So the issue still persists.
