### ISSUE TITLE
Cannot place objects on build plate or move to a build plate. Cannot print anything, everything is stuck "outside"

### ISSUE THREAD

**Issue by amicloud** [SoftFever/OrcaSlicer#5528]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.0-beta

### Operating System (OS)

Linux

### OS Version

Ubuntu 23.10

### Printer

FLSUN Super Racer w/ Klipper

### How to reproduce

1. Start a New Project
2. Import a .stl file

### Actual results

The .stl file is placed in the "outside" area and we are unable to move it to Plate 1 thru any method. 

### Expected results

The .stl file should be on the Plate 1 plate. 

### Project file & Debug log uploads

[debug_bug_report_53124.zip](https://github.com/user-attachments/files/15518045/debug_bug_report_53124.zip)
[bug_report_project_file_53124.zip](https://github.com/user-attachments/files/15518046/bug_report_project_file_53124.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by igiannakas** [comment]
Try adding a couple of plates and clicking autoarrange
