### ISSUE TITLE
Associate web links to Orcaslicer not working.

### ISSUE THREAD

**Issue by Avpman2** [SoftFever/OrcaSlicer#5529]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.0 beta

### Operating System (OS)

Windows

### OS Version

Win 11

### Printer

Flashforge

### How to reproduce

Go to the Printables, Maker, or Thingiverse and click the icon to open in Prusaslicer, Bamboo, or Cura  The settings in Orcaslicer are set correctly:

![orca-associate](https://github.com/SoftFever/OrcaSlicer/assets/3275462/09801691-aff8-4f26-a8b8-bb32cff1169b)

### Actual results

The message to open Prusa, Bamboo, or Cura appears, saying the respective program is not installed,

### Expected results

Orcaslicer should run, and it does not.

### Project file & Debug log uploads

n/a

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by SoftFever** [comment]
can you check if the the association is correct? You can check the full path of the associated application by hovering on the text

**Comment by Avpman2** [comment]
It turns out the prompt from the model's website says Cura, Prusa, etc., and you just have to accept that prompt before the slicer prompt appears and specifies Orcaslicer. So it's not a bug; just needs clarification in the docs. Example (confusing) prompt from the model's website:

![os1](https://github.com/SoftFever/OrcaSlicer/assets/3275462/a792f062-f54e-4707-bf55-e7c1e01d127e)

**Comment by JimmysDev** [comment]
I am currently experiencing this with Thingiverse. Running 2.1.0 on macOS. If I click the link it tells me I need to download Cura. If I say "Download Cura" it takes me to the download page. If I say "Okay" it closes the dialogue. For the life of me I can't find the settings in the screenshot originally posted, so I don't know if they are enabled or not.

**Comment by Avpman2** [comment]
In Orcaslicer hit Ctrl-P for the preferences page. Scroll down until you get to the settings I posted yesterday above.

**Comment by JimmysDev** [comment]
> In Orcaslicer hit Ctrl-P for the preferences page. Scroll down until you get to the settings I posted yesterday above.

On macOS it's Cmd+, and this is all I see. There isn't a scroll bar to go further down:
![image](https://github.com/SoftFever/OrcaSlicer/assets/109320523/e7a84986-5d79-44ab-afc7-7806d5f9be27)

Definitely using the beta:
![image](https://github.com/SoftFever/OrcaSlicer/assets/109320523/668561e5-d6f0-4472-9276-6933eca4cee0)

**Comment by Avpman2** [comment]
Ahhh, per the release notes, it only works on Windows.

**Comment by SoftFever** [comment]
Yeah, Mac is not supported yet.
I haven’t found a way to dynamically register Orca as the default application to handle web link requests. And I don’t want to automatically associate these web links without the user’s explicit consent.

**Comment by Kurre** [comment]
> Yeah, Mac is not supported yet. I haven’t found a way to dynamically register Orca as the default application to handle web link requests. And I don’t want to automatically associate these web links without the user’s explicit consent.

As a side note, macOS users can use e.g. https://github.com/Lord-Kamina/SwiftDefaultApps and manually set those link associations. Tested with all three ones:

![image](https://github.com/SoftFever/OrcaSlicer/assets/1389199/f6945b45-6571-4b8b-92e8-ce59ef495752)
![image](https://github.com/SoftFever/OrcaSlicer/assets/1389199/8ce110b6-63e7-4af6-a587-df182cbc69f3)
![image](https://github.com/SoftFever/OrcaSlicer/assets/1389199/e70a1a48-4412-43bf-aa26-96c65ed21801)

of course this is just a work-around until macOS associations are fully supported by Orca, but for me having these associations is a big deal 🤩 👍

**Comment by ender3** [comment]
@Kurre I have set all three associations, but I receive "malformed url" responses from OrcaSlicer. Did you do anything else to make it work?

**Comment by Kurre** [comment]
> @Kurre I have set all three associations, but I receive "malformed url" responses from OrcaSlicer. Did you do anything else to make it work?

Sorry it took so long to answer.

No, I don't recall doing anything else to make it work 🤔

**Comment by 3DCoded** [comment]
> > Yeah, Mac is not supported yet. I haven’t found a way to dynamically register Orca as the default application to handle web link requests. And I don’t want to automatically associate these web links without the user’s explicit consent.
> 
> As a side note, macOS users can use e.g. https://github.com/Lord-Kamina/SwiftDefaultApps and manually set those link associations. Tested with all three ones:
> 
> ![image](https://private-user-images.githubusercontent.com/1389199/342230214-f6945b45-6571-4b8b-92e8-ce59ef495752.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1ODYzOTgsIm5iZiI6MTcyNDU4NjA5OCwicGF0aCI6Ii8xMzg5MTk5LzM0MjIzMDIxNC1mNjk0NWI0NS02NTcxLTRiOGItOTJlOC1jZTU5ZWY0OTU3NTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjVUMTE0MTM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2U2Y2MzZTMxNDZhZWVjZTA3ZWEyOTc5MGMyM2YyNGFlZTRkYzNiNjBjMmE0ZWVmZTZlMzE2N2JkNWVjODM3NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hS69qmSKgerg_bv7K_1NhzcBCyNNe6EBK6KMkplGPL8) ![image](https://private-user-images.githubusercontent.com/1389199/342230371-8ce110b6-63e7-4af6-a587-df182cbc69f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1ODYzOTgsIm5iZiI6MTcyNDU4NjA5OCwicGF0aCI6Ii8xMzg5MTk5LzM0MjIzMDM3MS04Y2UxMTBiNi02M2U3LTRhZjYtYTU4Ny1kZjE4MmNiYzY5ZjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjVUMTE0MTM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTUyMjYyODExMDFmYWMyMzE4ZjJkZGU0NmE3ZDM5NDc3MWU3MTU1NjE1MGFhNmE5Y2FhMDU4NTkzZTQ3ZGUxZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.MEGXVK69PkvKNCbo2JMTBY6IVImTzV1_Ts5qmPjvtFY) ![image](https://private-user-images.githubusercontent.com/1389199/342230457-e70a1a48-4412-43bf-aa26-96c65ed21801.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1ODYzOTgsIm5iZiI6MTcyNDU4NjA5OCwicGF0aCI6Ii8xMzg5MTk5LzM0MjIzMDQ1Ny1lNzBhMWE0OC00NDEyLTQzYmYtYWEyNi05NmM2NWVkMjE4MDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjVUMTE0MTM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDRkOTY0N2EyNDEyMDM0YzMwMzFlM2MwMzYxZTQwNWIyMjU1MTMyMDVkOWQzMjFiNzlmM2I2MzQxOGZkYTM1NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.tJQ0DQhSJ1V4TF2bCGrfh563Dq2wp6g2YKMk7meOoAM)
> 
> of course this is just a work-around until macOS associations are fully supported by Orca, but for me having these associations is a big deal 🤩 👍

Thank you for this! I have wanted this feature on my Mac for a while. This should be added to the documentation as a workaround for Mac.
