### ISSUE TITLE
Text size inconsistency

### ISSUE THREAD

**Issue by Eldenroot** [SoftFever/OrcaSlicer#5534]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.0beta

### Operating System (OS)

Windows

### OS Version

Win 11

### Printer

A1 with AMS

### How to reproduce

![image](https://github.com/SoftFever/OrcaSlicer/assets/778890/6ec80155-e0f8-4210-8a9d-b80c8e029191)

### Actual results

![image](https://github.com/SoftFever/OrcaSlicer/assets/778890/6d11a4b2-565a-4649-a2ec-5d32562df50b)

### Expected results

Enable AMs should use same font size and be aligned

### Project file & Debug log uploads

---

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Eldenroot** [comment]
There is another - plate edit parameter

![image](https://github.com/SoftFever/OrcaSlicer/assets/778890/09b04aa0-5276-45fd-b5d9-e710ca6d0e9c)

**Comment by yw4z** [comment]
i will look a solution for this but i dont think there is an easy fix.
