### ISSUE TITLE
Transfer settings popup - design improvents

### ISSUE THREAD

**Issue by Eldenroot** [SoftFever/OrcaSlicer#5536]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Would be nice to adapt some changes from latets Bambustudio into Orca

![image](https://github.com/SoftFever/OrcaSlicer/assets/778890/b3202dbb-c703-44df-afa2-9aa9361d80bd)

![image](https://github.com/SoftFever/OrcaSlicer/assets/778890/29dcd2aa-a33b-4dbc-af88-e93cd2426295)

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

It is quite misleading and confusing, at least color and title should be added

**Comment by SoftFever** [comment]
Can you clarify which part is misleading?
I keep it consistent with PrusaSlicer and I find it's more clear/precise in current design

**Comment by Eldenroot** [comment]
https://github.com/SoftFever/OrcaSlicer/issues/4422#issuecomment-2144307140

**Comment by SoftFever** [comment]
Hmm, but that's in 2.0.0, in 2.1.0-beta, I have changed that.
Anyway let's continue the  discussion there instead of creating a duplicated ticket
