### ISSUE TITLE
Cut feature is not working like it does in Bambu

### ISSUE THREAD

**Issue by ccollinscj** [SoftFever/OrcaSlicer#5541]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1

### Operating System (OS)

Windows

### OS Version

Windows 11

### Additional system information

High end MSI laptop Steakth 17 Studio

### Printer

Vorons

### How to reproduce

click on an detailed object, use the cut tool.   Cut across the object that the plan crosses multiple parts of the object.  With bambu slicer you are able to click on the parts of the object to assign to the otherside of the plane by right clicking on the seperate feature and assign it to the otherside.

### Actual results

nothing

### Expected results

be able to have the plane cross the multiple parts of the object and assign the feature to either side of the cut.  like in bambu slicer.
![Bambu](https://github.com/SoftFever/OrcaSlicer/assets/7328824/8c2cd6a6-a5b1-492a-962a-f4efbdae42f8)
![orca](https://github.com/SoftFever

### Project file & Debug log uploads

![Bambu](https://github.com/SoftFever/OrcaSlicer/assets/7328824/0a203325-7176-4b65-a050-15cb7fa5edcd)
![orca](https://github.com/SoftFever/OrcaSlicer/assets/7328824/ee0d8094-442d-4163-82a0-bf629825ab45)

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Anything else?

Please update this,  and if you need more detail you can contact me at cjccollin@hotmail.com.  This is limiting my usage of orca and have to use Bambu or Prusa slicer first then bring it into orca.

**Comment by Revenger** [comment]
This is similar so ill post here as its the same question title.

Can we get more cut features in Orca I can't seem to manually assign orientation values line in bambu which makes it soo much easier of you want a 40' angle cut than having to clumsily try to orientate the cut wheel in Orca with the mouse visually to try to get the numbers right with minimum mouse movement.

Orca cut settings
![Orca Cut](https://github.com/SoftFever/OrcaSlicer/assets/597280/ae850f55-ba99-4c3d-b763-ebceb7d30a7f)

Bambu studio cut settings
![Bambu Cut](https://github.com/SoftFever/OrcaSlicer/assets/597280/579ee1ef-3cf0-4ced-9026-bab4af8c339d)
