### ISSUE TITLE
Add a plate name into the default TaskName before send it to print

### ISSUE THREAD

**Issue by aremishevsky** [SoftFever/OrcaSlicer#5556]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

It would be very useful to have pre-filled the default TaskName (projectName) with a name of a sliced plate (if it's defined) before sending it to the printer

Current:
![Send_print_job_to_and_nis_nakol](https://github.com/SoftFever/OrcaSlicer/assets/32752187/00345cee-e763-4361-99c3-e72ff77ae72c)

Expected:
![Send_print_job_to_and_nis_nakol](https://github.com/SoftFever/OrcaSlicer/assets/32752187/ac9d391f-4369-469e-80d9-21d7eb9913ac)

The main benefit of it is to have a more extended history of prints on a printer (when you're making a lot of copies with different counts of parts on various plates)

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

The default value should be `[definedPlateName]-[projectName]` instead of just a `[projectName]` value

**Comment by tlhintoq** [comment]
Would love this as well
