### ISSUE TITLE
FUZZY SKIN

### ISSUE THREAD

**Issue by McLoop24** [SoftFever/OrcaSlicer#5560]
### Is there an existing issue for this feature request?

- [x] I have searched the existing issues

### Is your feature request related to a problem?

Only few option in fuzzy skina 

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

Add some custom fuzzy skin on particular surface , like in Prusa slicer there is an outside wall only feature, I request to add a custom where to apply fuzzy skin only like your existing feature of (support painting),

**Comment by ph0tic** [comment]
pls do this. its very much wanted .
