### ISSUE TITLE
"Orca Slicer" wrongly translated to "逆戟鲸" in Simplified Chinese

### ISSUE THREAD

**Issue by LaphaeL12304** [SoftFever/OrcaSlicer#5561]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

In `Preference -> Associate files to Orca Slicer`, the word "Orca slicer" have been translated into "逆戟鲸" in Simplified Chinese, which actually means "killer whale", that sounds really funny.
The wrong part:
## Associate files to Orca Slicer
- Associate .3mf files to Orca Slicer
- Associate .stl files to Orca Slicer
- Associate  .step/.stp files to Orca SIicer
![屏幕截图 2024-06-03 143811](https://github.com/SoftFever/OrcaSlicer/assets/169073130/1bb1b34b-3815-4de6-a9ee-e868c4745bd6)

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

Directly use "Orca Slicer" instead of translating to "逆戟鲸".

**Comment by SoftFever** [comment]
Hi @LaphaeL12304 
The Chinese name of Orca Slicer is 逆戟鲸切片，so I think the translation here is accurate.
