### ISSUE TITLE
Print fails with error "Move out of range: 29.916 1.367 331.092 [-2.000]" 

### ISSUE THREAD

**Issue by bbinnard** [SoftFever/OrcaSlicer#5567]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.0-Beta

### Operating System (OS)

Windows

### OS Version

Windows11/64 Ver 23H2

### Additional system information

No performance problem - everything runs OK with PrusaSlicer. My printer is running the current version of Klipper.

### Printer

FLSun SuperRacer

### How to reproduce

1.Start print

### Actual results

Print fails with error "Move out of range: 29.916 1.367 331.092 [-2.000]" immediately

### Expected results

Print completes

### Project file & Debug log uploads

[disk.zip](https://github.com/user-attachments/files/15534814/disk.zip)
[klippy.log](https://github.com/user-attachments/files/15534815/klippy.log)
[debug_Mon_Jun_03_06_27_58_6056.log.zip](https://github.com/user-attachments/files/15535266/debug_Mon_Jun_03_06_27_58_6056.log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Anything else?

This is the 3rd time I'm reporting this problem. I received no useful result on prior 2 reports. Everything works OK when I slice with PrusaSlicer. For this trial I used the Orca definition for the new SuperRacer printer type and tried to print with Printable Area set to 300.0001 (which I think came from the Orca definition for my FLSun SuperRacer printer) and also with Printable Area set to 265 which was suggested by a Facebook user. 

My guess is there is some interaction between Klipper and Orca, but I've got no idea what that might be.

**Comment by SoftFever** [comment]
Can you share the .3mf project file as well as the .gcode file?

**Comment by bbinnard** [comment]
The print file is an STL file, not 3MF.
[disk.zip](https://github.com/user-attachments/files/15536033/disk.zip)
I can recreate it as a 3MF if you need that.

**Comment by bbinnard** [comment]
This problem still exists with Ver. 2.1.0-beta. The error message is Move out of range: 29.916 1.367 331.092 [-2.000]. No changes were made to printer since I opened this issue.

**Comment by SoftFever** [comment]
Please share the project file(3mf file with settings).

**Comment by bbinnard** [comment]
[disk.zip](https://github.com/user-attachments/files/15792752/disk.zip)

I don't know what settings you refer to - I don't think Orca has a way to export it's internal settings.

**Comment by SoftFever** [comment]
You can export to a 3mf project in OrcaSlicer file menu

**Comment by bbinnard** [comment]
1. The disk.zip file I uploaded above does contain the Orca 3MF file with the test part I tried to print.

**Comment by bbinnard** [comment]
Oh well, I guess I'll stick with FLSunSlicer.  Or maybe go back to PrusaSlicer.
