### ISSUE TITLE
Device MicroSD Card File Options Between Delete and Download Have a BAD Boundry Box for Button Selection

### ISSUE THREAD

**Issue by nmcandrews** [SoftFever/OrcaSlicer#5569]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

Windows

### OS Version

Windows 11

### Printer

Bambu Lab P1S

### How to reproduce

Open OrcaSlicer.
Print part, with Timelapse on. 
Finish printing.
Go to and select DEVICE horizontal tab. 
Select MicroSD Card option. 
Select download while hovering over any of the letter D O or W in DOWNLOAD. 
Selected area for DELETE highlights, and is pressed if clicked.

### Actual results

When clicking while hovering over any of the letters D O or W in DOWNLOAD, the DELETE button gets highlighted and applies that action to the mouse click response, instead of the boxed-in option for download as it should. 

![OrcaSliver Bug - Over Nlowd](https://github.com/SoftFever/OrcaSlicer/assets/167692029/a6a8a872-53ce-4a15-9b8c-dd424707d3cb)
![OrcaSliver Bug - Over Dow](https://github.com/SoftFever/OrcaSlicer/assets/167692029/8fbe0934-f3cf-4c32-bee0-66b9ec7ebfa2)

### Expected results

Anywhere within the DOWNLOAD option box button, the file should download. 
Anywhere within the DELETE option box button, the file should delete. 
Sections should not be shortened or overlapping into another box's space. 

### Project file & Debug log uploads

.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Anything else?

The next menu screen for Download Finished and the options mouse-over for 'Delete', 'Play', 'Open Folder' appear to be perfectly fine.

**Comment by poppinfresh69** [comment]
Can confirm this is still an issue in 2.1.1. You need to click right of the Print button or it pops the delete function instead.
