### ISSUE TITLE
fatal error: Access violation / object has zero size - if part is mirrored

### ISSUE THREAD

**Issue by sledwina** [SoftFever/OrcaSlicer#5578]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.0-beta

### Operating System (OS)

Windows

### OS Version

Windows 11 Pro

### Additional system information

Prozessor	AMD Ryzen 9 5950X 16-Core Processor               3.40 GHz
RAM	64,0 GB
AMD Radeon VII
Nvidia RTX 3070 Ti

### Printer

Voron 2.4

### How to reproduce

Import DDBDOuterNeckRight.stl - Clone the part - Mirror along x or y axis - hit "arrange" button - 
gives error "object xxx.stl has zero size and can't be arranged"

<img width="1921" alt="zero size" src="https://github.com/SoftFever/OrcaSlicer/assets/95303738/2f61d0d8-369e-4676-878e-e913dcc37227">

Or:
Import DDBDOuterNeckRight.stl - Clone the part - Mirror around x or y axis - rotate part to fit on the build plate - hit "slice plate" - gives the error "fatal error: Access violation"

<img width="1921" alt="fatal error" src="https://github.com/SoftFever/OrcaSlicer/assets/95303738/424c3c59-80e9-4a04-998f-fe0210907f3d">

### Actual results

See above...

### Expected results

Mirror a part and slice without errors.

### Project file & Debug log uploads

[DDBDOuterNeckRight.zip](https://github.com/user-attachments/files/15550375/DDBDOuterNeckRight.zip)
[debug_Tue_Jun_04_12_55_12_27044.log.zip](https://github.com/user-attachments/files/15550400/debug_Tue_Jun_04_12_55_12_27044.log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by GoldenGorilla123** [comment]
I've got a similar issue, but I can clone, mirror(by x axis) and arrange, but when I go to slice it I get 'access violation' 
![image](https://github.com/SoftFever/OrcaSlicer/assets/50293108/c20ddb6b-fbf5-45b7-b01f-a9a0e07c3fd6)



Mirroring by y-axis seems to work around the issue for me temporarily

2.1.0-beta
Windows 11

Intel i7-1185g7
16gb RAM
Integrated Graphics

Voron 2.4 300mm

[Project file.zip](https://github.com/user-attachments/files/15722376/Project.file.zip)
[debug_Fri_Jun_07_09_03_38_7692.log.zip](https://github.com/user-attachments/files/15722379/debug_Fri_Jun_07_09_03_38_7692.log.zip)

**Comment by daijoubu** [comment]
Same issue here.  Selecting "Fix Model" before arranging seems to solve the issue with arranging, but it still raises an exception when slicing.

2.1.0-beta
Windows 11
AMD Ryzen 7 5800X3D
32GB Ram
Nvidia RTX 4070

Creality K1C rooted.

[HornetMountMirrored.zip](https://github.com/user-attachments/files/15756078/HornetMountMirrored.zip)
[debug_Sat_Jun_08_14_28_37_6216.log.zip](https://github.com/user-attachments/files/15756111/debug_Sat_Jun_08_14_28_37_6216.log.zip)

**Comment by mattddonnelly** [comment]
I'm also having this issue, with the attached file.

I can slice just fine with one object, or with two objects, but if I mirror either one or both objects, I get an access violation error and am unable to slice.

2.1.0-beta
Windows 11
AMD Ryzen 9 5900X 12-Core Processor               4.20 GHz
Installed RAM 64.0 GB
Nvidia RTX 3080

[clamp_handle.zip](https://github.com/user-attachments/files/15856028/clamp_handle.zip)

**Comment by sledwina** [comment]
For me the issue is fixed with the 2.1.0 RC.

**Comment by sledwina** [comment]
For me the issue is fixed with the 2.1.0 RC.
