### ISSUE TITLE
Browser Plugin

### ISSUE THREAD

**Issue by jonathanalevi** [SoftFever/OrcaSlicer#5580]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I've noticed some folks who want to open bambustudio:// links into OrcaSlicer, but that is only part of the solution, IMO. We'd like to be able to open models from Printables, Thingiverse, OR MakerWorld directly into OrcaSlicer, and I think there's a pretty quick/easy way to do it all in one fell swoop. 

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

I suggest building a Chrome and Safari extension, which will simply replace the "open in prusaslicer" or "open in bambu studio" links, similar to how a content blocker would work. This should be pretty rudimentary to build, and I've seen another 3D printing company do it (I can't share who, unfortunately).

This would solve the problem for all 3 websites, plus Thangs, etc....

### Describe alternatives you've considered

Defaults in the computer, but, that will not solve it as easily or holistically. 

### Additional context

N/A

**Comment by JMcrafter26** [comment]
Maybe I understood you wrong, but there is an option in OrcaSlicer to add "deeplinks" to orcaslicer.

In Orcaslicer settings:

![image](https://github.com/SoftFever/OrcaSlicer/assets/77780772/52de7adf-e0cd-4e67-bf9a-2207bc89d07e)
