### ISSUE TITLE
[Feature Request] send external command at start / end

### ISSUE THREAD

**Issue by ludal13** [SoftFever/OrcaSlicer#5618]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

No.

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

Hey !
Wonder if it's possible to add a new feature which will allow us to send external feature on specific event (start, stop, fail, run out of filament, etc).

My main goal here is to turn on an connected plug (Tapo P110M) to turn on a LED light strip, but it could be used for litteraly anything else (notification, email, camera control, etc).

Thanks :-)

### Describe alternatives you've considered

1. add a feature to send HTTP requests on specific event

**Comment by kylek29** [comment]
For your light, you could get an inline PIR sensor (~$7 on Amazon) and mount it so it turns on with tool head motion. That's what I did. You'd just need to make sure to get one with the right voltage (mine was 24v).
