### ISSUE TITLE
Slow down the solid infill the layer below internal bridges

### ISSUE THREAD

**Issue by Ataraxia-Mechanica** [SoftFever/OrcaSlicer#5639]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

The extra solid infill the layer before internal bridges are printed at very high speeds, causing them to detach from the walls and causing internal infill on the next layer to droop down, causing artifacts on the top surface.
![image](https://github.com/SoftFever/OrcaSlicer/assets/111327195/69ae7b33-71fd-4827-98a6-4b4fa8dea4ba)
![Untitled](https://github.com/SoftFever/OrcaSlicer/assets/111327195/507933ff-5518-4a95-aa90-8acb147d66d2)

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

Slow down this ring of solid infill, or categorize it under a different line type, so it can be slowed down.
An extra mechanic to detect solid infill that's unsupported or form an overhang, and slow then down would also be useful, while also solving this problem.

**Comment by vovodroid** [comment]
I would also apply bridge cooling to such solid infill.
