### ISSUE TITLE
Still having an issue. Please don't close a report before it is actually solved.

### ISSUE THREAD

**Issue by roboduid** [SoftFever/OrcaSlicer#564]
**Describe the bug**
I'm still getting an issue where I have a constant blank screen when I launch the app. I can't even close the app without using task manager.
![226500966-2a4f22a7-caef-48c8-9383-a0292580f053](https://user-images.githubusercontent.com/89250364/226774091-00085e23-b26a-49a3-ba44-a3a0af565542.png)

**Desktop (please complete the following information):**
 - OS: Ghost Spectre Windows 11 Superlite
 - Version 22H2

**Comment by hliebscher** [comment]
i think the problem is your OS can you change the color ? or some packages are not in your lite  version

**Comment by TexZeTech** [comment]
Well I'm dumb and put my answer in https://github.com/SoftFever/OrcaSlicer/issues/555#issuecomment-1479889834

Can someone merge the two I think its also solved but *shrug*

**Comment by roboduid** [comment]
Actually this is fixed now. It was as simple as running as administrator
