### ISSUE TITLE
cose per hour not working

### ISSUE THREAD

**Issue by riteshauk** [SoftFever/OrcaSlicer#5643]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.0 beta

### Operating System (OS)

Windows

### OS Version

windows 11

### Additional system information

Processor	11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz   2.40 GHz
Installed RAM	16.0 GB (15.7 GB usable)
System type	64-bit operating system, x64-based processor

### Printer

SOVOL SV07 PLUS

### How to reproduce

No mater to what value i change "Time cost" in printer settings, the total cost doesn't change at all, This used to work before the update, i had version 1.9.0.
![Screenshot 2024-06-09 001602](https://github.com/SoftFever/OrcaSlicer/assets/126483031/7ee934ee-08c3-4605-8419-7496857eeb9b)

### Actual results

the value doesnt change

### Expected results

the price used to change

### Project file & Debug log uploads

![Screenshot 2024-06-09 001602](https://github.com/SoftFever/OrcaSlicer/assets/126483031/dd013b86-1868-481d-be25-e697c998b69b)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Sethi85** [comment]
already has a thread -> https://github.com/SoftFever/OrcaSlicer/issues/5582

But yeah, not working on mine either.
