### ISSUE TITLE
Temperature Tower: Config Temperature Step

### ISSUE THREAD

**Issue by bemasher** [SoftFever/OrcaSlicer#5644]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

The temperature step in the temperature tower dialog is fixed.

https://github.com/SoftFever/OrcaSlicer/blob/aa692b815ea01e84d93c88a8467c6ebdfa5615c9/src/slic3r/GUI/calib_dlg.cpp#L291

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

Would be nice to make this value configurable. I don't often need a temperature tower with 5C resolution, 10C is usually good enough.

### Describe alternatives you've considered

I could create a custom temperature tower, but the built-in temperature tower calibration is really convenient.

**Comment by hho** [comment]
I'd also love to have a 10°C step.

It's also **really** sad that people are putting in time to write these issues, when all that happens is that they get closed by a bot.

**Comment by ForbiddenEra** [comment]
+1

**Comment by Volko61** [comment]
Same
