### ISSUE TITLE
Fan speed not changing in gcode

### ISSUE THREAD

**Issue by Ergonomicmike** [SoftFever/OrcaSlicer#5645]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.0-beta portable nightly build

### Operating System (OS)

Windows

### OS Version

Win10

### Printer

Klipperized Ender 3 v2

### How to reproduce

Import my project file.
Slice.
View Fan Speed in Color Scheme and note that fan speed is supposed to change during the print.
View the gcode and search for M106.
![Fan speed changes Orda issue](https://github.com/SoftFever/OrcaSlicer/assets/15025888/404f5e26-1b9b-434a-beda-5abf28255fb1)

### Actual results

Fan speed stays at 50% for the actual print.

### Expected results

Fan speed should change, as high as 70%.

### Project file & Debug log uploads

[TickRemover_M._Fan Speed Issue Orca.zip](https://github.com/user-attachments/files/15750546/TickRemover_M._Fan.Speed.Issue.Orca.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Anything else?

So, I might a total idiot. If so, please close this issue.

(But  https://github.com/SoftFever/OrcaSlicer/issues/5606 might be related? Also https://github.com/SoftFever/OrcaSlicer/issues/4596 )

In the gcode, I see mostly M106 S127. 

It doesn't change. This would be consistent with the 50% fan speed that I actually see during printing.

**Comment by discip** [comment]
No issue here:

![image](https://github.com/SoftFever/OrcaSlicer/assets/53649486/6cffe64a-26e5-42a5-92f8-e331015e1326)

**Comment by Ergonomicmike** [comment]
@discip Thanks for checking. I reloaded the project and now my M106's are changing.

Arrgh. I don't know why it's working now. 

But closing this issue.
