### ISSUE TITLE
Gaps in perimeters.

### ISSUE THREAD

**Issue by user32rtu** [SoftFever/OrcaSlicer#5646]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

v2.1.0-beta, v2.1.0-dev, v2.0.0

### Operating System (OS)

Windows

### OS Version

Windows 10 Pro 22H2

### Additional system information

AMD FX(tm)-8150 Eight-Core Processor  3.60 GHz
16,0 ГБ

### Printer

Sapphire Pro

### How to reproduce

1. Open a project from an attachment.

### Actual results

Gaps appear in some external and internal perimeters.
In places where there are breaks in the G code, the filament is retracted.

### Expected results

Perimeters should not have unpredictable discontinuities.

### Project file & Debug log uploads

[bolt.zip](https://github.com/user-attachments/files/15752470/bolt.zip)

### Checklist of files to include

- [ ] Log file
- [x] Project file

### Anything else?

![1](https://github.com/SoftFever/OrcaSlicer/assets/48878798/4d9449e4-e9a5-4c41-9395-5f3e431718cd)
![2](https://github.com/SoftFever/OrcaSlicer/assets/48878798/083856c2-6ebd-4a09-b2fd-7cdea12688af)
![3](https://github.com/SoftFever/OrcaSlicer/assets/48878798/9b46d136-9ca3-4ae7-afaf-723a4f1f273b)
![4](https://github.com/SoftFever/OrcaSlicer/assets/48878798/6518e018-58fd-43b2-a861-aadfa7d52590)

**Comment by thhdragon** [comment]
the issue disappears if you uncheck retraction and detraction speed in the filament profile overrides. doesnt seem to like having a really low speed like 4.5mm/s

**Comment by user32rtu** [comment]
> the issue disappears if you uncheck retraction and detraction speed in the filament profile overrides. doesnt seem to like having a really low speed like 4.5mm/s

Yes, adjusting the retraction speed has an effect on this problem. Some breaks disappear, others don't.

**Comment by user32rtu** [comment]
When you set the "Use relative E distances" parameter in the printer profile, the gaps disappear.
