### ISSUE TITLE
Linear fan speed wrt overhang angle

### ISSUE THREAD

**Issue by dbuezas** [SoftFever/OrcaSlicer#5647]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I use remote cooling, and setting mid fan speed for overhangs is too much for < 30% overhangs but insufficient for > 50%.

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

Ideally a step function like the one for overhang printing speed, but to control fan speed.

<img width="389" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/777196/47efec8c-79e0-48a1-bef7-baf295b7069b">

**Comment by Boerny41** [comment]
Was about to open up a feature request and found this. I normally have my fans at 20% to get better layer adhesion, but I just printed some stuff which has overhangs that are too steep for 20% fan speed but not steep enough for the existing "cooling overhang threshold" to kick in. 

A more granular way to set the fan speed would fix this.
