### ISSUE TITLE
Sliding dovetail cut connector 

### ISSUE THREAD

**Issue by jbowers01** [SoftFever/OrcaSlicer#5649]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

A sliding dovetail connector option would be extremely beneficial for cutting parts with thick walls or features and reconnecting them with the highest mechanical strength and precision, example large speaker enclosures that need to be glued together in sections could be glued together without clamps 

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

It should generate part modifiers to allow for automatic sliding dovetail geometry on a cut line

### Describe alternatives you've considered

1. Post processing script
2. Stand-alone app or online file modifier prior to importing the file
3. Manually designing the feature into the part

**Comment by discip** [comment]
@jbowers01
This is already implemented: 😊

![image](https://github.com/SoftFever/OrcaSlicer/assets/53649486/2b417ebe-a42f-43b2-b69d-764fee1076b7)

Please close this issue.
