### ISSUE TITLE
[Issue] Adding custom printer

### ISSUE THREAD

**Issue by esc247** [SoftFever/OrcaSlicer#565]
I am facing issues when trying to create a custom printer for OrcaSlicer. I have attached the json files as an attachment to the last post.

**Comment by esc247** [comment]
Thanks for the info, but for some reason I cannot see the WiFI icon in Orca, so I cannot add the IP. I ended up creating a full profile (edited from the Voron profile) for the VzBoT. I cannot find where to add the image of the VzBot 330 though...

**Comment by esc247** [comment]
[VzBoT.zip](https://github.com/SoftFever/OrcaSlicer/files/11052812/VzBoT.zip)
I've added the config files that I based off of the demo printer from the Bambu Slicer wiki. When I added the demo printer to the config, I ran OrcaSlicer just to check if it loads, and it did. However, once I made the changes for my printer it wouldnt load. Cant figure out what I am doing wrong... :(

**Comment by esc247** [comment]
I think I solved this. I'll add the latest version of the file for reference. Not sure if the VzBoT can be added to the list of supported printers for Orca (at least this should be a decent starting point) for others looking to add the VzBoT to the list :)

**Comment by esc247** [comment]
Is there a way to do this so that I can be confident that all the references that I am replacing with my custom printer name are correct? I have a feeling that this issues is due to human error, where I am messing up the naming for the ref files... It can also be that it isn't loading as I am trying to set up a profile for a 0.6mm nozzle when the default is for 0.4mm?

**Comment by TexZeTech** [comment]
I'm taking a look at this right now and see what I can do for ya.

**Comment by esc247** [comment]
Great thanks!

**Comment by esc247** [comment]
@TexZeTech any updates on this please? Thanks!

**Comment by TexZeTech** [comment]
@esc247 I'm sorry about the slow reply I've been rather busy this week I did start looking at it but again haven't had the time to just crunch it out, so do not wait on me. When I get some free time I will continue.

**Comment by TexZeTech** [comment]
@esc247 looks like there is a [beta release](https://github.com/SoftFever/OrcaSlicer/releases/download/v1.6.2-beta/OrcaSlicer_V1.6.2-beta-VzBot_Linux.zip) with it.
