### ISSUE TITLE
Painting doesn't flow inward, it just paints top layers 2.1.0 Official

### ISSUE THREAD

**Issue by pennystockss** [SoftFever/OrcaSlicer#5650]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.0 Beta

### Operating System (OS)

macOS

### OS Version

14.4.1

### Additional system information

2021 Macbook M1 Pro 14"

### Printer

Any

### How to reproduce

Paint an object

### Actual results

Paints only top surfaces

### Expected results

Paint to slice like previous version

### Project file & Debug log uploads

[Text.3mf.zip](https://github.com/user-attachments/files/15753534/Text.3mf.zip)
[debug_Sun_Jun_09_12_45_48_60886.log.0.zip](https://github.com/user-attachments/files/15753541/debug_Sun_Jun_09_12_45_48_60886.log.0.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Anything else?

<img width="1033" alt="Orca Painted Unsliced" src="https://github.com/SoftFever/OrcaSlicer/assets/60720749/8af35e23-1013-4321-b189-91fb7a6d2e0f">
<img width="947" alt="Orca 2 1 0 Beta Sliced" src="https://github.com/SoftFever/OrcaSlicer/assets/60720749/a29443cb-3cd1-49a4-9858-40bd7ef911bd">
<img width="744" alt="Orca 2 0 0 Sliced" src="https://github.com/SoftFever/OrcaSlicer/assets/60720749/a04b1899-bd9d-4be4-b6ec-a3d1265a454f">

**Comment by igiannakas** [comment]
Do you have shrink compensation in your filament settings enabled?

**Comment by pennystockss** [comment]
Negative. Used default profile and default Bambu PLA filament settings.

**Comment by tlhintoq** [comment]
How did you paint?  What painting tool?  If you paint with the `Height Range` tool it paints full layer for me.
![image](https://github.com/SoftFever/OrcaSlicer/assets/11351506/dd13ab7b-185c-430b-818c-745b91254854)

If you paint with the circle tool, then you're only painting the exterior surface.

**Comment by pennystockss** [comment]
Yes I did the height range in that example, I assumed it paints like regular just in flat lines across. Here's an astronaut example. Slices fine in 2.0. Circle I assume is the same as 2.0, paint in a flat circle with whatever pixels are on your screen not on the model like the sphere but it should still fill to the inside. Mine's only slicing the top most layer, on all existing projects and if there isn't any top layer, it skips painting all together.

<img width="674" alt="Screenshot 2024-06-12 at 8 09 50 PM" src="https://github.com/SoftFever/OrcaSlicer/assets/60720749/0e181d82-c6a1-4d3b-a04e-bcf841c5c69f">
<img width="672" alt="Screenshot 2024-06-12 at 8 09 43 PM" src="https://github.com/SoftFever/OrcaSlicer/assets/60720749/276af5d1-8034-4868-b1cc-4d9b62141ebc">

**Comment by pennystockss** [comment]
Here's in 2.0. Exact same project. Are you on Mac? I wonder if it's a Mac thing, surely if it were everyone it would get a lot more attention.
<img width="706" alt="Screenshot 2024-06-12 at 8 15 31 PM" src="https://github.com/SoftFever/OrcaSlicer/assets/60720749/d04bd2fd-105d-4217-8ed8-186aec6c2064">

**Comment by pennystockss** [comment]
Bump, 2.1.0 official still does it.
<img width="1134" alt="Screenshot 2024-06-22 at 12 37 31 PM" src="https://github.com/SoftFever/OrcaSlicer/assets/60720749/5a4af850-e194-4398-baef-a6e8c6bee01c">
<img width="871" alt="Screenshot 2024-06-22 at 12 39 08 PM" src="https://github.com/SoftFever/OrcaSlicer/assets/60720749/01d396d2-d888-4855-ab49-86e33721cd60">

**Comment by igiannakas** [comment]
Looks like we may have found the issue - if you build the binaries locally the issue doesn’t occur. So it’s somewhere in the GitHub build chain that produces the release binary.

fix hopefully coming soon as we kind of know where the issue now comes from.

**Comment by azocarf** [comment]
same problem  en orca for Mac

**Comment by igiannakas** [comment]
Latest Mac build should solve the non shrinkage related MMU issue. Download from the nightly and use this command to "sign" it so it opens.

`xattr -dr com.apple.quarantine /Applications/OrcaSlicer.app`

**Comment by pennystockss** [comment]
I grabbed the latest one, didn't need command this time (tried before on another build that did). And it works!

**Comment by jthomeo** [comment]
Hi guys. Has anyone managed to solve the problem? I'm using Orca Slicer 2.1.1 and I'm facing the same issue. Is there a work around?

![image](https://github.com/user-attachments/assets/daffa7f4-bca6-4e30-b0b4-d538c11b9bca)
![image](https://github.com/user-attachments/assets/8905ece1-e268-412b-812a-c30a771c3469)

**Comment by igiannakas** [comment]
Yes - 2.2 nightly solved this I believe. This is the PR that was merged yesterday.
