### ISSUE TITLE
Preview First Layer Temperature

### ISSUE THREAD

**Issue by bamber11999** [SoftFever/OrcaSlicer#5651]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.0-beta

### Operating System (OS)

Windows

### OS Version

Windows 10

### Printer

Voron 2.4

### How to reproduce

1. Start New Project
2. Import stl file (in this case the voron cube stl)
3. Set Nozzle print temperature.   First layer 215, Other Layers 195
4. Go to Preview, select temperature.

First layer temperature will show as 0 deg, further layers will show as correct temperature of 195 deg

### Actual results

![Capture](https://github.com/SoftFever/OrcaSlicer/assets/135086141/0d6f2ae9-ed42-49b9-9ee4-6a14583d8331)

Preview will show the first layer as 0Deg.

### Expected results

Preview should show correct temperature settings.

### Project file & Debug log uploads

[Orca_Voron_Design_Cube_v7 (1).zip](https://github.com/user-attachments/files/15755619/Orca_Voron_Design_Cube_v7.1.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Anything else?

Reviewing the G-code,  Orca correctly calls the print_start macro with the first layer temperatures (the printer, if the macro has been modified to use those parameters, will correctly set the temperature.) However, as the g codes are not inserted directly, Orca preview interprets them as 0degs until the second layer when the M104, M140 commands are called.

**Comment by Ergonomicmike** [comment]
I was about to report this issue myself. (Note to self: First, check to see if someone else has reported the issue before wasting an hour gathering screen shots/assets for a new Report.)

I spend a few hours doing comparisons between my custom Printer preset (which gives this bug) and the vanilla Ender 3 v2 Printer preset supplied by Orca, which works.

I isolated the problem to "Machine start G-code." (This is when G-code flavor is set to Klipper. If Marlin, the initial layer temp displays correctly.)

As a first matter, if you don't have any start G-code, then you will get this bug.

As a minimum, you need to have 
`M104 S[nozzle_temperature_initial_layer] ; set final nozzle temp`
in the Machine start G-code for the display to show a non-zero initial layer temp.
