### ISSUE TITLE
Slicing behavior

### ISSUE THREAD

**Issue by SolberLight** [SoftFever/OrcaSlicer#5653]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

Windows

### OS Version

11

### Printer

Elegoo Neptune 4 Plus

### How to reproduce

Using the given file slicer with normal 1.6 layer height

### Actual results

Walls aren't perfectly straight it's adding geometry from nowhere
![WhatsApp Image 2024-06-10 at 12 19 46_559cf9fe](https://github.com/SoftFever/OrcaSlicer/assets/61121160/528e54dc-d067-49c9-b7d2-9890725053f8)
![WhatsApp Image 2024-06-10 at 12 19 46_c7377274](https://github.com/SoftFever/OrcaSlicer/assets/61121160/47f731ee-b789-423f-ae00-4b1469a9f906)

### Expected results

Straight walls

### Project file & Debug log uploads

[A4p.zip](https://github.com/user-attachments/files/15763817/A4p.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by foreachthing** [comment]
Disable Arc-fitting will help. I don't you need that anyway. If you do need it, do it in post with ArcWelder.

**Comment by discip** [comment]
@SolberLight

Try this:
[A4p.3mf.txt](https://github.com/user-attachments/files/15777645/A4p.3mf.txt)

If you print it laying flat on the bed, the thin fins will definitely break off.
Hence the angled position, just in case you wonder.

**Comment by SolberLight** [comment]
Thanks for your suggestion, actually i've already printed many of these and they infact aren't straight due to the slicing.
thins are plenty strong so not the issue there.

The issue I'm seeing is that Orca is adding material where it shouldn't

![Screenshot_43](https://github.com/SoftFever/OrcaSlicer/assets/61121160/6ea2f22c-a31d-4dc4-90ac-f0ffba7199ba)

**Comment by SolberLight** [comment]
Can be seen here :
![WhatsApp Image 2024-06-10 at 20 54 55_a1592aa2](https://github.com/SoftFever/OrcaSlicer/assets/61121160/6646feeb-c5f4-4378-ad07-5f333c3d6b38)

**Comment by SolberLight** [comment]
I've tried your settings. It's clearly better, but not perfect, what should I changed next ?
![Screenshot_44](https://github.com/SoftFever/OrcaSlicer/assets/61121160/d5ff305e-0d9f-40b3-b499-912f10495ca2)

**Comment by discip** [comment]
What is the diameter of you nozzle 0.4 mm or 0.6 mm ... ?

**Comment by discip** [comment]
What is the diameter of your nozzle 0.4 mm or 0.6 mm ...?

**Comment by discip** [comment]
What is the diameter of your nozzle? 0.4 mm or 0.6 mm ...?

**Comment by SolberLight** [comment]
.4 yes

**Comment by discip** [comment]
Is it possible to attach the whole file?

**Comment by discip** [comment]
Is it possible to attach the whole project file?

**Comment by discip** [comment]
Try reducing layer height to at least 1.3 mm.

**Comment by discip** [comment]
Try reducing layer height to at least 0.13 mm.

**Comment by discip** [comment]
Try reducing layer height to at least 0.13 mm.
Preferably 0.1 mm.

**Comment by SolberLight** [comment]
That's a good point that should help. Still there should be a warning or something in orca in this case. print shouldn't start without advice

**Comment by discip** [comment]
@SolberLight
Have you tried the latest commit?
Maybe your issue has already been solved . 😊
