### ISSUE TITLE
Line infill is aligned and does not criss-cross

### ISSUE THREAD

**Issue by WallK** [SoftFever/OrcaSlicer#5655]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.0-beta

### Operating System (OS)

Windows

### OS Version

10

### Printer

Custom

### How to reproduce

Select "Line" sparse infill pattern
Slice
Observe

### Actual results

The infill pattern is aligned between layers
![image](https://github.com/SoftFever/OrcaSlicer/assets/4513545/ac01502f-8eef-40ed-9f5b-83d6b64bb337)

### Expected results

The infill pattern should be generated at an angle between layers
![image](https://github.com/SoftFever/OrcaSlicer/assets/4513545/d6509b04-3bee-40d5-bb0e-65a7dba6e646)
(screenshot from SuperSlicer)

### Project file & Debug log uploads

[line-infill.zip](https://github.com/user-attachments/files/15765179/line-infill.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Anything else?

This issue was not present in 2.0.0

**Comment by discip** [comment]
@kisslorand
Could you please have a look at this?
Seems to be similar to #5285.

**Comment by kisslorand** [comment]
Thanks for the heads-up, fixed it. Will push a PR shortly.
