### ISSUE TITLE
Slicing issue colour loss

### ISSUE THREAD

**Issue by eriko411** [SoftFever/OrcaSlicer#5664]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1beta

### Operating System (OS)

macOS

### OS Version

Monterey 12.6.8

### Printer

Bambu a1

### How to reproduce

![IMG_6517](https://github.com/SoftFever/OrcaSlicer/assets/135646696/1f781ad5-b218-4f3f-bda3-28b3737a1d82)
Skull has black eyes for multi colour but this is removed when slicing 

### Actual results

![IMG_6516](https://github.com/SoftFever/OrcaSlicer/assets/135646696/15aba8fc-7e9a-47fa-a358-fa1e3ce4d153)

### Expected results

Eyes should stay black

### Project file & Debug log uploads

[orca skull colour issue.3mf.zip](https://github.com/user-attachments/files/15784979/orca.skull.colour.issue.3mf.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by Vantage-DS** [comment]
Just noticed this on a project too.
Set base colour to gold in slot 4.
Painted 2/3 upper model blue in slot 1, using height range.

Sliced model only shows absolute top layer as blue.

**Comment by eriko411** [comment]
This worked last month only change is no fourth colour on the AMS.

iv another issue with making overhangs printable now messes up the models base it mixes colours into the overhang 🙈

**Comment by tlhintoq** [comment]
Maybe related... maybe not...
Bring in a model that's all painted for one printer like Bambu X1C.
Decide you want to print it on the Bambu P1S (totally compatible machine), so you change printers and all the painting is lost.
Maybe something happening to re-load the printer at slice time causing the same loss??

**Comment by rplanier** [comment]
Same problem here.  Painting a height range a particular color results in only the top layer actually being sliced with that color.  All other layers lower in the painted range are sliced in the original color.

**Comment by tlhintoq** [comment]
Last night's nightly in Windows 10: Paint by layer is correctly painting all layers that color.
![image](https://github.com/SoftFever/OrcaSlicer/assets/11351506/958cf06f-3955-436a-9431-c9f276bf68c1)

Come down partway through the painted black range... Black all the way through
![image](https://github.com/SoftFever/OrcaSlicer/assets/11351506/6859e87c-8868-42d3-832f-8caf19a0f4d8)

Come down partway through the painted gold range... Gold all the way through
![image](https://github.com/SoftFever/OrcaSlicer/assets/11351506/a89eb22d-b305-4941-badd-e6c5fa294ccd)

**Comment by igiannakas** [comment]
Can you please test this fix here? https://github.com/SoftFever/OrcaSlicer/pull/5774

**Comment by Maximizer18** [comment]
I tried the build linked, and still having the same issue as everyone else, and have skrinkage set to 100%.
<img width="350" alt="Screen Shot 2024-06-23 at 6 15 09 PM" src="https://github.com/SoftFever/OrcaSlicer/assets/121817448/9b43a689-c52e-43db-a6e0-43b1e2d9092f">
<img width="444" alt="Screen Shot 2024-06-23 at 6 14 27 PM" src="https://github.com/SoftFever/OrcaSlicer/assets/121817448/1653a7b6-d92a-46a3-9a87-e266939c2eae">
<img width="774" alt="Screen Shot 2024-06-23 at 6 14 15 PM" src="https://github.com/SoftFever/OrcaSlicer/assets/121817448/0087e9aa-f2b8-4d36-a17e-dd914359b1a5">

**Comment by Maximizer18** [comment]
And a simple cube, clearly is painted with 4 colors, yet only sliced with 2.
<img width="735" alt="Screen Shot 2024-06-23 at 6 19 07 PM" src="https://github.com/SoftFever/OrcaSlicer/assets/121817448/617a8b44-0c6e-4fb7-98ed-e398e8be0b9e">
<img width="797" alt="Screen Shot 2024-06-23 at 6 19 00 PM" src="https://github.com/SoftFever/OrcaSlicer/assets/121817448/25cdea69-ce34-4565-b891-57aa7d697fdd">

**Comment by igiannakas** [comment]
Separate issue has been identified with the Mac builds in GitHub. If you build it locally it works but the GitHub build doesn’t. Under investigation.
