### ISSUE TITLE
Corrected Buildplate Model for Ender-3 S1Pro available

### ISSUE THREAD

**Issue by Teufelauto** [SoftFever/OrcaSlicer#5674]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Buildplate model for Creality Ender 3 S1 Pro is smaller than reality. When running Klipper, the printable area of 230x230 is larger than the old model. 

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

Replace file with new file I've created.

File of interest:    creality_ender3s1pro_buildplate_model.stl
In this folder:      OrcaSlicer/resources/profiles/Creality

Correctly modeled .stl file may be downloaded from my Google Drive. https://drive.google.com/file/d/1BvGqzZi3KUoFD0LDvDQtvwxUI8RxYRtO/view?usp=drive_link

### Describe alternatives you've considered

Letting the extra build area hover over adjacent empty space is what I've been doing until now. 

### Additional context

I have tested model in Orca Slicer 2.1.0-beta. Dimensions were recorded from my own machine with calipers and verified by toolhead positioning.

Yellow model below is the current version placed on top of correctly modeled plate for comparison.
![old_in_yellow_comparison](https://github.com/SoftFever/OrcaSlicer/assets/110637430/47dbaa6d-0b61-409e-8795-759b7d5a612b)

The corrected model provided on Google Drive. Optional 230x230 printable area shown.
![without_heater](https://github.com/SoftFever/OrcaSlicer/assets/110637430/638cafd0-48c1-4285-8b0e-16a849016e87)

I modeled the plate with the heater cord, but it covered the title above upper left corner in the Slicer. This feature was therefore rolled back for final version.
![with_heater](https://github.com/SoftFever/OrcaSlicer/assets/110637430/b6f6ca0c-89b8-42f0-b77e-3991f48f3aac)

Photo for reference.
![20240611_204121](https://github.com/SoftFever/OrcaSlicer/assets/110637430/84ac995c-9407-4d06-81df-0ad3271e7923)
I'm a mechanical engineer, not a software engineer. Sorry.

**Comment by cochcoder** [comment]
I've implemented the given model, thanks for making it!
