### ISSUE TITLE
Javascript Error Message

### ISSUE THREAD

**Issue by ckvsoft** [SoftFever/OrcaSlicer#569]
**Describe the bug**
Javascript Error after start of Slicer

**To Reproduce**
Start OrcaSlicer Linux

**Screenshots**
![grafik](https://user-images.githubusercontent.com/16374447/227029520-4ad9eeb6-2304-4b68-a8af-ba8463b204cc.png)

**Desktop (please complete the following information):**
 - OS: Linux Kubuntu 22.04
 - Version OrcaSlicer 1.5.0

**Comment by ChaosBlades** [comment]
Duplicate of https://github.com/SoftFever/OrcaSlicer/issues/219
