### ISSUE TITLE
Dark Mode. When exporting settings the checkbox is not visible

### ISSUE THREAD

**Issue by sergeyfatman** [SoftFever/OrcaSlicer#5695]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.0-beta

### Operating System (OS)

Windows

### OS Version

Windows 11

### Additional system information

CPU Core I7 13-gen, RAM 64Gb

### Printer

Anycubic Mega S

### How to reproduce

1. go to 'File'
2. go to 'Export'
3. choose 'Export Preset Bundle'
4. Check 'Process presets(.zip)

<img width="700" alt="Снимок экрана 2024-06-14 015251" src="https://github.com/SoftFever/OrcaSlicer/assets/6974449/787da4a6-ef9d-4c7d-b54d-46fe3f359757">

### Actual results

<img width="700" alt="Снимок экрана 2024-06-14 015251" src="https://github.com/SoftFever/OrcaSlicer/assets/6974449/009d6f28-afef-449f-8417-a4ffdb4a29b0">

### Expected results

when I move the mouse to this area, a checkbox is showing

<img width="699" alt="Снимок экрана 2024-06-14 015325" src="https://github.com/SoftFever/OrcaSlicer/assets/6974449/c8d1b764-48fd-4fe5-96ce-b1795f8cfafb">

### Project file & Debug log uploads

[debug_Fri_Jun_14_01_17_18_8336.log.zip](https://github.com/user-attachments/files/15829527/debug_Fri_Jun_14_01_17_18_8336.log.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by discip** [comment]
@jamincollins
Could you please have a look?
Since you are quite familiar with this kind of issue after all what you have achieved in this regard. 😊

**Comment by HAndreasH** [comment]
noticed same issue on latest 2.0.1-rc (21-06-2024)
all checkboxes in the export dialog in dark mode are not visable
