### ISSUE TITLE
Extra Perimeters on overhangs disables briding

### ISSUE THREAD

**Issue by tome9111991** [SoftFever/OrcaSlicer#5706]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1 Beta

### Operating System (OS)

Windows

### OS Version

10

### Printer

Voron 2.4

### How to reproduce

Open the Project and slice.

on layer 177 you can see overhangs instead of bridges
![overhang](https://github.com/SoftFever/OrcaSlicer/assets/57866234/5782ea11-c206-434a-a5d4-a3ea7e776748)

### Actual results

Too many overhangs where bridges would actually make more sense.

### Expected results

Extra Perimeters on overhangs disabled to many bridges.
it should look like this:
![bridging](https://github.com/SoftFever/OrcaSlicer/assets/57866234/f3ccde3e-c5b1-4eee-9271-2cd50330c6d8)

### Project file & Debug log uploads

[project.zip](https://github.com/user-attachments/files/15841082/project.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by tome9111991** [comment]
Same issue with Prusaslicer.

But Extra perimeter on overhangs with latest Superslicer version works well.

**Comment by vovodroid** [comment]
Actuall SS has this feature only for Classic generator. Probably it was somehow broken when extending it to Arachne. Simplest solution is to split code and make it work correct in Classic for now.

Did you open bug in for Prusa?

**Comment by tome9111991** [comment]
thanks for the hint you are right only work correct with Classic  in SS.

No i'dont open bug in Prusa maybe i should
