### ISSUE TITLE
Horizontal Wall and Top/Bottom shell thickness Calculation and Display

### ISSUE THREAD

**Issue by Ohara2208** [SoftFever/OrcaSlicer#5708]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Horizontal Wall and Top/Bottom shell thickness can only be computed through putting in the exact amount numerically requested.
Display of the thickness of the shells not shown. 

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

Using different nozzles, layer heights and extrusion width percentages will result in different shell thicknesses with the same entered shell quantitys. 

A feature in SuperSlicer takes a Milimeter input and will adjust the Shells to ensure the requested mm thickness is achieved.  For the Top/Bottom Shells it seems to get as close as possible and then +1 if it is under the desired amount obviously the layer height will effect how close to this valve it can achieve.
This ensures you keep a similar thickness across layer heights , Ie Less shells needed on larger layer heights and more on smaller to maintain a similar strength.

The wall thickness input takes both quantity of shells and mm input, the extrusion width will be adjusted to hit the shell mm that is closest to the quantity of shells. Example below Im requesting 5 shells and 5mm walls. With a 0.5 nozzle it has adjusted to achieve exactly 5mm wall using 5 shells and a 0.5 spaceing to compensate for the layer line overlap.
Im not a bit fan of this and it would be better if it followed the same calculation as the Top/bottom shell. So you input the requested mm thickness and the Shell quantity is adjusted automatically to achieve at minimum the requested thickness taking into account the line width and not adjusting it.

SS will display the thickness that you are achiveing also, examples below.

Ive had some customers request thicknesses rather than shells and nozzle widths. ie so I can use any layer height and nozzle I like but they will recieve a consistant thickness part. 
My suggestions above would eliminate the manual calculation and automate it.
thanks

### Describe alternatives you've considered

1. Manually calculating the qantity of shells
2. creating multiple profiles for each layer height and nozzle size to ensure shells are precalculated

### Additional context

![image](https://github.com/SoftFever/OrcaSlicer/assets/149898595/df815585-95ae-4869-bf10-4377f8758b8d)
![image](https://github.com/SoftFever/OrcaSlicer/assets/149898595/28715e1f-1cc7-4d77-8258-1fa55da2f981)
![image](https://github.com/SoftFever/OrcaSlicer/assets/149898595/3191554e-94df-40ca-a20b-4ceebe0ad93e)

**Comment by buzzhuzz** [comment]
Duplicates https://github.com/SoftFever/OrcaSlicer/issues/5634
