### ISSUE TITLE
New feature: Time Cost

### ISSUE THREAD

**Issue by DiomedesDominguez** [SoftFever/OrcaSlicer#571]
In SuperSlicer we count with "Time cost" to help us to have a better estimation for the total cost of printing. It is a simple double data type field in the printer configuration used to calculate the total cost, alongside with the filament cost, of the printed job.

![image](https://user-images.githubusercontent.com/4379316/227207627-76d7ba4d-3256-412a-a677-fa13e1160580.png)

**Comment by niklasb22** [comment]
I will have a look at this.
