### ISSUE TITLE
Mouse orbit on middle button?

### ISSUE THREAD

**Issue by cskilbeck** [SoftFever/OrcaSlicer#5710]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

It would be really nice to have the option to use the middle mouse button for mouse orbit rather than the left mouse button. I often select objects when I want to orbit and then move them when I don't want to.

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

An option in the settings dialog to choose left/right/middle mouse button for orbit mode

**Comment by markaudacity** [comment]
+1
