### ISSUE TITLE
Generic Linux Build Instructions with Pre-Requirement libs listed

### ISSUE THREAD

**Issue by A-nglea** [SoftFever/OrcaSlicer#572]
Great that ubuntu users can compile this. 

I use Fedora on cloning found it wouldn't build, despite changing apt for dnf, commenting out sections checking which gtk but still came up against library issues.
libgstreamerd-3 couldn't be found in Fedora's reps so I bailed.

The feature request is this: Ubuntu is a fine distro to start your Linux journey but many of us move on. Could your developers please recognise and address that and please provide for the four major Linux distros.

**Comment by emelbardis** [comment]
Fedora user here. Agreed

**Comment by nelsongraca** [comment]
I'm on the same boat but with Gentoo, it may be possible but knowing the devs don't seem to care doesn't make me very willing to make it work.

Even the AppImage that is supposed to be distro agnostic refuses to run.

**Comment by TexZeTech** [comment]
The AppImage kinda sorta works on Manjaro and I did find an [AUR package](https://aur.archlinux.org/packages/orca-slicer) but I too agree.

**Comment by nelsongraca** [comment]
@TexZeTech yep saw that one, and considered creating an ebuild for it, but the dependency on Wayland kills it for me as I'm on XFCE that has yet no Wayland support.

**Comment by nelsongraca** [comment]
@chron0 No clue about wayland deps, I gave up on it and went to PrusaSlicer the devs don't seem to care much for proper Linux support other than Ubuntu, because of that I decided that I won't waste my time making an ebuild for it, would be different if there was developed interest.
