### ISSUE TITLE
We NEED speed adjustment settings for material layed down on top of bridges

### ISSUE THREAD

**Issue by wbagnall** [SoftFever/OrcaSlicer#5722]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

When printing bridges, the bridged material is very vulnerable to damage, especially for large bridged areas. Printing too fast (150mm/s+) directly on top of bridges causes them to sag, and in the worst case scenario, the bridge can be ripped completely off (ex. Printing at 300mm/s) which causes the print to fail.

Printing at a slower speed on top of bridges is crucial for bridge quality and print success with faster printers for two reasons:
1. A slower speed above bridges increases the time the material is being cooled, reducing sagging and helping bridge quality.
2. The slower speed also reduces the chance of the nozzle accidentally ripping apart the bridge.

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

There are a few solutions I can think of. 
1. Print the material on top of bridges at the bridge speed or internal bridge speed.
2. Add a setting specifically for the material printed on top of bridges.

The first solution I think is the easiest, but I have no experience with slicer development. 

### Describe alternatives you've considered

You can reduce the speed of the entire print, but that completely ruins the point of having a fast printer.

There is no alternative setting in OrcaSlicer, you are forced to use a different slicer such as SuperSlicer or Cura if you need this setting, which is why I believe this feature is crucial, because you shouldn't have to use another slicer solely because it has a setting Orca doesn't.

**Comment by lhndo** [comment]
I concur. It would be very useful to have, especially for fast printing.
