### ISSUE TITLE
Add ability to remove default color from filament settings (Windows)

### ISSUE THREAD

**Issue by markaudacity** [SoftFever/OrcaSlicer#5740]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

There doesn't seem to be a way to remove a default color once one is selected in v1.9.1 on Windows. I tried right-clicking on the color button and clicking it, closing the color picker, and hitting Delete while the color button is highlighted, but neither seems to work. The Windows color picker does not let you select no color.

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

Some method of removing the default color once assigned. I realize this is somewhat limited by the archaic Windows color picker dialog; perhaps highlight the color button and hit Delete? 

### Additional context

![image](https://github.com/SoftFever/OrcaSlicer/assets/62250787/cb8706f4-1c61-4434-a29b-db7d0f94cc3a)

**Comment by SoftFever** [comment]
For now, you will have to go to %appdata%/OrcaSlicer/user folder and find your filament profile(it's json file)
Then delete the `default_filament_colour` entry

    "default_filament_colour": [
        "#800040"
    ],

**Comment by adobni** [comment]
Can this issue be reopened?

**Comment by BlasterGales** [comment]
please someone with permission reopen this

**Comment by radfordwill** [comment]
Agreed, this should be reopened. It is an issue that should be addressed.
