### ISSUE TITLE
Add chamber preheating for Bambu enclosed printers

### ISSUE THREAD

**Issue by markaudacity** [SoftFever/OrcaSlicer#5742]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

The Bambu printer firmware has no concept of chamber preheat, but moving the bed to just below the nozzle and heating it with the aux part fan on does a pretty good job of heating the chamber. Currently, the print will happily start with the chamber temperature far too low to prevent part warping for materials like ABS and Nylon.

### Which printers will be beneficial to this feature?

Others

### Describe the solution you'd like

It should be simple to add starting Gcode that heats the bed, moves it to position, turns on the aux fan, and runs it until chamber temp equals the chamber temp set in filament options. There is an existing request upstream in the Bambu Slicer forums, but Bambu seems to be rather slow to respond to such requests.

### Describe alternatives you've considered

Manually executing the above

**Comment by kylek29** [comment]
Can't you add this sequence to the Machine Start G-Code? If you use if statements on the filament type variable, you could even make it semi-automatic based on that.

Is this the sequence you're looking for?

1. Post homing (to prevent Z-crash)
2. Move bed up to just below the home position.
3. Turn hotbed on ..
4. Aux fan to 100% 
5. Chamber Exhaust fan to 0%
6. Wait for chamber temp to be reached (using chamber temp filament setting).
7. Proceed ....

**Comment by markaudacity** [comment]
That's a route I'm pursuing now, but it would be nice if just setting the temperature and clicking the box made it happen.

**Comment by kylek29** [comment]
So I tested this at the very end of the Machine G-Code, seems the X1C (my printer) doesn't do anything with the chamber temperature it has access to. 

`;--- Chamber Heat ---

; Check if the activate_champer_temp_control flag is set in the Filament Settings

{if activate_chamber_temp_control[initial_no_support_extruder]}

	; Chamber Temperature Control Activated	
	M106 P2 S255 ; turn Aux (Big) fan to 100%
	M106 P3 S0 ; reconfirm chamber fan is off
	M109 F S{chamber_temperature[initial_no_support_extruder]-5} ; Wait for the chamber heat to be reached
	M106 P2 S0 ; turn the Aux fan back off as the X1C's starting point

{endif}

;--- /Chamber Heat ---`

**Comment by SoftFever** [comment]
This required the firmware to support M191 command: https://github.com/SoftFever/OrcaSlicer/wiki/Chamber-temperature

**Comment by markaudacity** [comment]
I know that M191 is necessary to send this as a self-contained command, but since the X1 has a chamber-temp sensor that Orca Slicer can read, can't that be used as a variable in a conditional in the startup Gcode?

**Comment by markaudacity** [comment]
Based on @kylek29's code (needing to call the number of the extruder to make the chamber temp variable a scalar instead of a vector is something I never would have figured out), I am using this code which positions the bed right below the aux fan nozzle for best effect, then puts everything back how it was:

`{if activate_chamber_temp_control[initial_no_support_extruder]}
    M106 P3 S0              ;verify chamber fan off
    M106 P2 S255          ;turn aux fan on max
    G28 Z P0                   ;home Z with low precision
    G90                           ;set absolute positioning
    G1 Z10 F1200           ;lower bed 10mm to place it in the path of aux fan flow
    M140 S120               ;set bed temp
    M190 S120               ;wait for bed temp
    M400 S300               ;wait 5 min for chamber heat
    M106 P2 S0              ;turn off aux fan
    M1002 gcode_claim_action : 2
    M140 S[bed_temperature_initial_layer_single] ;set bed temp
    M190 S[bed_temperature_initial_layer_single] ;wait for bed temp
{endif}`

**Comment by movinimage** [comment]
You can read the chamber temp w/ MQTT. I wrote a python app that turns bed to max, aux to max, and waits until chamber meets the temp set in the script. Works perfectly. 

You can’t do it with pure gcode, but would Orca consider including an MQTT based pre-heat routine?
