### ISSUE TITLE
Improve overhang performance with adaptive outer wall line width

### ISSUE THREAD

**Issue by Ataraxia-Mechanica** [SoftFever/OrcaSlicer#5746]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

When printing objects with steep overhangs, using a thicker outer wall line width could increase overhang performance. This is due to more materials being deposited on top of previous layer.

![image](https://github.com/SoftFever/OrcaSlicer/assets/111327195/4153a580-ba86-4457-9c58-950d4b5ac4b5)

But thicker outer walls make sharp details look worse. I wonder whether if it would be possible to detect overhangs and make them thicker, but make non-overhang areas use the original line width.

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

![image](https://github.com/SoftFever/OrcaSlicer/assets/111327195/fc58c5d4-9220-4640-a88a-2b6cbccc6892)

Detect overhangs and use thicker outer wall width on them, while not changing non-overhang wall line width.

**Comment by vgdh** [comment]
That would be a great improvement!
I wonder what @SoftFever @Noisyfox @igiannakas  think about it.

**Comment by igiannakas** [comment]
Without trying it we can’t say for sure what it will do, but from first looks it will improve step over and overhang performance for sure - I personally run 0.48 external wall line width in my profiles and 0.42 internal.


However varying line widths on a single surface may cause appearance inconsistencies - my theory is that you want the extrusion to be as consistent as possible between layers. 

So I’m presuming that the other side of the overhangs will appear slightly worse than if you just kept a larger line width throughout all the external walls.

But won’t be sure unless we test it!!

**Comment by Noisyfox** [comment]
> However varying line widths on a single surface may cause appearance inconsistencies

And also make it harder to implement too. Pretty much like traditional wall generator with a thicker wall width vs Arachne.

**Comment by Ataraxia-Mechanica** [comment]
>However varying line widths on a single surface may cause appearance inconsistencies
I'm thinking about only increasing line width for the overhang part, then revert to normal width immediately after. Could probably still cause inconsistencies and artifacts on the corner of the width change though.

**Comment by Ataraxia-Mechanica** [comment]
I also think this feature should only be enabled when it comes to extreme overhangs that can't be handled normally, e.g. 60 degree overhangs at 0.2mm layer height, using 0.8mm line width to make it printable.

**Comment by SoftFever** [comment]
I doubt this would work.
The unsupported part remains unchanged, and your nozzle position remains unchanged.
Only changing layer height would reduce the unsupported part

**Comment by Ataraxia-Mechanica** [comment]
![image](https://github.com/SoftFever/OrcaSlicer/assets/111327195/f086ddae-de06-4ef0-b744-85e9e1060a3c)

One test, coming up!
Hope the aux fans I installed on both side have the same power...

**Comment by Ataraxia-Mechanica** [comment]
Currently suffering from success. Both cases worked even with aux fan off. Just gimme a bit more time...

**Comment by igiannakas** [comment]
Up to a point it does - there is a big difference going from 0.4 to 0.48 in my experience. 

After that it starts tapering off and above 0.5-0.6 or so it starts creating other artefacts as the overlap isn’t as much and the plastic just gets pushed out on the overhanging side if that makes sense. 

Personally I run all my print profiles with 0.45-0.48 external perimeters for this reason - to get good step over for inner outer inner wall ordering. But I haven’t felt the need to dynamically change this as the fixed line width works well enough without any consequences. It also increases part strength quite nicely.

Stefan had a video showing line width impacts on print quality here: https://www.cnckitchen.com/blog/the-effect-of-extrusion-width-on-strength-and-quality-of-3d-prints?format=amp

**Comment by Ataraxia-Mechanica** [comment]
At extreme angles, thicker line width actually has performs worse on my printer, as the thicker lines are easier to sag down and getting separated from inner walls, while 0.4mm lines literally drips down, gets blown by the fans, shrinks and grows back up, then sticks on the lower side firmly. However, I think I already mentioned a situation that makes thicker walls strictly better 2 posts before: concave overhangs.
![image](https://github.com/SoftFever/OrcaSlicer/assets/111327195/e5ee3b00-7de3-4d5e-96ca-32aabf4d9568)

**Comment by Ataraxia-Mechanica** [comment]
![all](https://github.com/SoftFever/OrcaSlicer/assets/111327195/a9322b82-51fe-4d56-a105-5cc2fa24cfe1)
Guess which one is 0.8mm outer wall and which is 0.4
