### ISSUE TITLE
Bridges don't slice correctly - Bridges don't anchor to perimeters correctly.

### ISSUE THREAD

**Issue by wbagnall** [SoftFever/OrcaSlicer#5747]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.0-beta

### Operating System (OS)

Windows

### OS Version

Windows 11

### Printer

Voron 2.4

### How to reproduce

I just spend an hour writing this up and getting all the screenshots, and then the page decided to refresh and reset all the prompts. Oh well. Here I go again.

To reproduce, slice the project files I uploaded. I have played around with various settings to try and fix the issue, but with no positive results. I cannot guarantee that every single profile will produce these results, but it seems to happen no matter what settings I change. 

### Actual results

As said in the title, bridges don't anchor to perimeters correctly, leaving empty gaps or gaps of (imo useless) sparse infill instead of fully anchoring to all the perimeters. Occasionally bridges decide not to anchor to anything at all.

In this example, you can see the bridges don't anchor completely over the perimeters. See The Expected results section for what should happen.
<img width="599" alt="embossed text" src="https://github.com/SoftFever/OrcaSlicer/assets/65498026/cc23ff6f-9a5f-4315-be4a-cda1596ab7c9">

In this example, bridges print over nothing (as well as not completely anchoring over perimeters). See the expected results section
<img width="805" alt="ksr_fdmtest" src="https://github.com/SoftFever/OrcaSlicer/assets/65498026/57d941c4-f459-4ed6-af58-55c3749bbc32">
"ksr_fdmtest_v4.3mf"

In these examples, bridges don't anchor correctly, causing the bridge to fail.
![Screenshot 2024-06-18 013038](https://github.com/SoftFever/OrcaSlicer/assets/65498026/72cce01b-744b-4608-a9ab-a6d1cb7dc7b7)

![Screenshot 2024-06-18 013211](https://github.com/SoftFever/OrcaSlicer/assets/65498026/146076db-be05-4881-865c-81f77194c8a2)

![Screenshot 2024-06-18 013551](https://github.com/SoftFever/OrcaSlicer/assets/65498026/79856a35-51f9-41ab-b831-9a137e01d593)
"incorrect bridging.3mf" "incorrect bridging 2.3mf"

In this example of the OrcaCube, the bridges don't completely anchor, leaving a gap for the next layer.
![Screenshot 2024-06-18 013833](https://github.com/SoftFever/OrcaSlicer/assets/65498026/18b308d1-12ca-4eb5-85a4-5ec1e759c88a)

In this example of the 3D Benchy, a bridge is generated where an overhang should be
![Screenshot 2024-06-18 014229](https://github.com/SoftFever/OrcaSlicer/assets/65498026/27534e19-a7fb-4ae5-b508-7df40e91cdef)

Here you can see the incomplete anchoring with the sparse infill. I believe this is intentional, but it reduces bridge quality because the lines are only anchored to 1 perimeter instead of completely.
![Screenshot 2024-06-18 014323](https://github.com/SoftFever/OrcaSlicer/assets/65498026/bf151986-e5b1-4a42-a7fe-5125a0024fc2)

In this temp test, you can see the bridge isn't anchored completely, leaving a gap for the next layer.
<img width="965" alt="temp test" src="https://github.com/SoftFever/OrcaSlicer/assets/65498026/866c1309-ad22-4243-8ba5-e6a9d858aa9d">

### Expected results

Bridges should anchor entirely to perimeters without leaving any gaps for the next layer. The area of the gaps and weird sparse infill should be bridge anchors instead to improve bridge quality and reduce chance of failure. I suggest adding a setting that allows the user to select how many perimeters a bridge anchors into. Bridges should also anchor to _something_ instead of being printed mid air.

Here is an example of OrcaSlicer correctly slicing bridges without leaving any gaps or printing over nothing. "correct bridging.3mf" layer 4.
![Screenshot 2024-06-18 015452](https://github.com/SoftFever/OrcaSlicer/assets/65498026/cbf34de6-2012-4431-8c7b-cfd7c24821a1)

EDIT:

Here is how Prusaslicer handles some of these cases. You can see how the bridges properly anchor to the perimeters.
![Screenshot 2024-06-18 031133](https://github.com/SoftFever/OrcaSlicer/assets/65498026/1b78d90d-3a45-4088-80d9-179d914dd948)

![Screenshot 2024-06-18 030719](https://github.com/SoftFever/OrcaSlicer/assets/65498026/8e2c17d0-97e3-4274-9016-c2f3c43de3a6)

### Project file & Debug log uploads

[Project Files.zip](https://github.com/user-attachments/files/15881429/Project.Files.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by wbagnall** [comment]
Here is how prusaslicer handles the ksr_fdmtest file.
![Screenshot 2024-06-18 030719](https://github.com/SoftFever/OrcaSlicer/assets/65498026/69e8089a-2b54-43ef-b591-0fec075755a5)

**Comment by wbagnall** [comment]
Here is how PrusaSlicer handles the "incorrect bridging.3mf" file. You can see that it properly anchors the bridges to the perimeters.
![Screenshot 2024-06-18 031133](https://github.com/SoftFever/OrcaSlicer/assets/65498026/76d8b8df-0bcc-415c-bf84-6f2915a25abc)

**Comment by foreachthing** [comment]
One thing I've found with "incorrect bridging.gcode" -> **Ensure vertical shell thickness: All**

![image](https://github.com/SoftFever/OrcaSlicer/assets/10420187/f3faec38-eea3-4411-8d52-56b7f689922a)

Compare to your screenshot:
![image](https://github.com/SoftFever/OrcaSlicer/assets/10420187/f2668580-3a5d-4c29-987a-a63c5d4a13c1)

**Comment by Ataraxia-Mechanica** [comment]
You have bridge counterbore holes set to partial which doesn't play well with holes that aren't counterbored:
![image](https://github.com/SoftFever/OrcaSlicer/assets/111327195/7644b0b0-f651-47ff-995f-ddc94a6818ef)

This doesn't fix the long bridging on the outside though, you can offset a part of it to be a layer higher to break up the bridging area.

**Comment by SoftFever** [comment]
You will need to make some manual adjustment for some models.
For example, it would be better to set the bridging direction to 135 degree for the following model
Also, I suggest start with default settings, a lot of advanced features in Orca have very specific use cases.
It's not recommended to have them on if you don't need it. E.g. we don't bridge counterbore feature on in this case it you don't have counterbore sink holes and this will interfere normal bridges.
![image](https://github.com/SoftFever/OrcaSlicer/assets/103989404/63966698-4128-4707-b700-9e0c8ef5b03a)

![image](https://github.com/SoftFever/OrcaSlicer/assets/103989404/96c81fe4-15b3-4ff6-bc1b-1d7892faa25e)
![image](https://github.com/SoftFever/OrcaSlicer/assets/103989404/57251f8b-a3e1-4f35-99f1-07fc2c7a9d29)
