### ISSUE TITLE
[Feature Request] : Import Print Config from Gcode file

### ISSUE THREAD

**Issue by jhenley01** [SoftFever/OrcaSlicer#575]
Both PrusaSlicer and SuperSlicer have a feature that allows you to re-import all of the print settings from a previous gcode file. 

You can go to File > Import > Import Config and choose the gcode file. As long as the gcode file was generated from Prusaslicer or Superslicer it will import all of the print settings that were used. This is useful if you want to use the same settings that were used on a previous print but don't have the profile saved or the 3MF file.

It looks like OrcaSlicer is already outputting all the settings at the end of the the gcode file but there isn't a way to re-import them. If you go to File > Import > Import Config you aren't allowed to select a gcode file.

I've used this feature many times and it would be great to see it added to OrcaSlicer.

**Comment by simpat1zq** [comment]
Is there any chance to get this feature on the roadmap?

**Comment by foreachthing** [comment]
Just lost all my settings due to SSD-failure ... this would really be a life-saver right now 😢 
(_reminder to me to save all settings to "cloud" - only wish that `--data-dir` would work already_)

**Comment by PJawZK** [comment]
The settings are in the g-code file at the bottom, like with previous renditions of this slicer, thinking of for instance PrusaSlicer.
So one can retrieve the info manually, but not automatically.

So the basis is there to be implemented, we just need to get SoftFever to find value in implementing it into OrcaSlicer.

**Comment by www-dot-com** [comment]
It would be awesome if @SoftFever could implement this into Orca. I lost all my settings from Orca but I have them in g-code. It's a bummer that I can't just import them.

**Comment by Aurasphere-au** [comment]
Was this ever implemented?

**Comment by simpat1zq** [comment]
> Was this ever implemented?

No. So far it hasn't gotten any attention from any dev so it's unlikely to happen in the near future. I'm almost starting to think that some sort of script that passes the gcode and spits out a config file might be an option if someone is good with that type of stuff.
