### ISSUE TITLE
Pressure advance speed limited to 40mm/s

### ISSUE THREAD

**Issue by adolfotregosa** [SoftFever/OrcaSlicer#5755]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0 to 2.1-rc

### Operating System (OS)

Linux

### OS Version

Manjaro

### Printer

Voron 2.4

### How to reproduce

prepare, calibration, pressure advanced.

### Actual results

speeds are limited to 40mm/s

### Expected results

limited to 100mm/s

### Project file & Debug log uploads

[Pressure Advance Test.zip](https://github.com/user-attachments/files/15891804/Pressure.Advance.Test.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Anything else?

The image explains it all. I don't know what makes this happen but it happens. 

![image](https://github.com/SoftFever/OrcaSlicer/assets/7437931/f5372768-1d0d-44f6-896f-e40ba44eee98)

OR

This happens. Isn't it supposed to be 100mm/s everywhere ?

![image](https://github.com/SoftFever/OrcaSlicer/assets/7437931/0304ddbd-35a1-428a-aa5a-02279ecf5068)

and I think the issue is this settings is not being applied.

![image](https://github.com/SoftFever/OrcaSlicer/assets/7437931/1258c18b-e8a7-4b6b-bc33-9910f318f30e)

**Comment by evilDave** [comment]
It works as usual for me. Do you have some other setting that is limiting the speed? volumetric flow, speed limit of printer... Maybe try an "out of the box" profile and see if it uses the correct speed, then compare your profile against it to see what is different.
