### ISSUE TITLE
Multicolor not slicing correctly

### ISSUE THREAD

**Issue by adolfotregosa** [SoftFever/OrcaSlicer#5756]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0 - 2.1 rc

### Operating System (OS)

Linux

### OS Version

manjaro

### Printer

voron 2.4

### How to reproduce

open stl, paint something , slice

### Actual results

![image](https://github.com/SoftFever/OrcaSlicer/assets/7437931/293a6f9e-1e59-44bd-bb54-236bc3863b39)

### Expected results

![image](https://github.com/SoftFever/OrcaSlicer/assets/7437931/946138d7-b118-4ea6-a6fc-4207f4b32f22)

### Project file & Debug log uploads

[Voron_Design_Cube_v8.zip](https://github.com/user-attachments/files/15892838/Voron_Design_Cube_v8.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Anything else?

Quick test with latest appimage of bamboo studio
![image](https://github.com/SoftFever/OrcaSlicer/assets/7437931/7663bdea-a80a-4181-9d8f-00d8674e5324)

**Comment by igiannakas** [comment]
Set shrinkage to 100% for your filaments. It will slice correctly then. Multicolour printing and shrinkage compensation are not compatible with each other at this point in time.

![image](https://github.com/SoftFever/OrcaSlicer/assets/59056762/2b44f547-744d-412e-8830-8549eb001a38)

**Comment by igiannakas** [comment]
Please test this fix here: https://github.com/SoftFever/OrcaSlicer/pull/5774

**Comment by BrinksDaniel** [comment]
Having same issue, shrinkage already is 100%

**Comment by igiannakas** [comment]
@BrinksDaniel please post your project file. Also which OS are you running, it’s version and what computer it’s on (Mac M series, Mac intel, PC).

**Comment by igiannakas** [comment]
Latest Mac build should solve the non shrinkage related MMU issue. Download from the nightly and use this command to "sign" it so it opens.

`xattr -dr com.apple.quarantine /Applications/OrcaSlicer.app`
