### ISSUE TITLE
Add Option To Select Which Changes To Be Saved

### ISSUE THREAD

**Issue by cubitik** [SoftFever/OrcaSlicer#5758]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

No.

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

It would be great if it was just like PrusaSlicer which gives us options to select what changes we want to save by ticking and unticking.

**Comment by cubitik** [comment]
![image](https://github.com/SoftFever/OrcaSlicer/assets/111056006/4f3c4fea-7cbe-4a61-a4b3-89d72b7e9a79)

**Comment by tlhintoq** [comment]
Merge with https://github.com/SoftFever/OrcaSlicer/issues/5749 ??

**Comment by cubitik** [comment]
> Merge with https://github.com/SoftFever/OrcaSlicer/issues/5749 ??

Similar but not the same, I think this is better. Or both could be added but this is still my side.
