### ISSUE TITLE
Settings not saving

### ISSUE THREAD

**Issue by agipson91** [SoftFever/OrcaSlicer#5759]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.0

### Operating System (OS)

Windows

### OS Version

10

### Printer

SV06

### How to reproduce

1. Edit settings
2. Save settings
3. Exit program
4. Open Program

### Actual results

Random settings don't save. Line width, wall order, skirt loops, buncha random stuff.

### Expected results

The settings should save when I save them.

### Project file & Debug log uploads

not doing this

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Anything else?

this is an insane issue to have

**Comment by EvilGremlin** [comment]
Linux Appimage, no user presets are being saved. All fine, no eroors, next launch all user profiles are lost. Along with other issues, 2.x verions are just unusable.
