### ISSUE TITLE
Printables.com support/import opens a new Orca instance for each file - Import to open instance

### ISSUE THREAD

**Issue by PhilBaz** [SoftFever/OrcaSlicer#5762]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1 RC

### Operating System (OS)

Windows

### OS Version

windows 10

### Additional system information

Nothing important.

### Printer

Voron 2.4

### How to reproduce

Go to printables
use open in Prusaslicer button next to a file
repeat

### Actual results

Each time 'open in Prusaslicer' button is used a new separate instance of Orcaslicer is opened with just the one file.

### Expected results

Each time 'open in Prusaslicer' button is used 

1) If Orca slicer is **not** open it should open Orca slicer
2) If one instance of Orca slicer **is** open it should open the file in the running instance of Orca slicer.
3 If more than one instance of Orca slicer is open it should open in the last used instance of Orca slicer.

### Project file & Debug log uploads

[Q-2585 (Order).zip](https://github.com/user-attachments/files/15895057/Q-2585.Order.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by foreachthing** [comment]
You'll need to enable the option "allow only one OrcaSlicer instance":

![image](https://github.com/SoftFever/OrcaSlicer/assets/10420187/d61e07b1-7d4b-41b3-9428-08626f508319)

> 'open in Prusaslicer' ❓❓❓

**Comment by olcayoren** [comment]
This feature does not work on macos. Is there a way to adjust this?

**Comment by olcayoren** [comment]
> You'll need to enable the option "allow only one OrcaSlicer instance":
> 
> ![image](https://private-user-images.githubusercontent.com/10420187/340938351-d61e07b1-7d4b-41b3-9428-08626f508319.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3ODU2NjEsIm5iZiI6MTcxODc4NTM2MSwicGF0aCI6Ii8xMDQyMDE4Ny8zNDA5MzgzNTEtZDYxZTA3YjEtN2Q0Yi00MWIzLTk0MjgtMDg2MjZmNTA4MzE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDA4MjI0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyMmJkODAzMjUwNDEzZmZiMWY0ZjcyNmUzNmE1MDE1YTY1YjZhMTUzNWM5YjJhY2EzMjcyMjdkZWVmNWFkMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sq6WDtd36nJ8bbmsVho9D-kQz53hXE0XMjz6u27mo-c)
> 
> > 'open in Prusaslicer' ❓❓❓

This feature does not work on macos. Is there a way to adjust this?

**Comment by PhilBaz** [comment]
@foreachthing Okay, good to know.... But I like to have multiple instances of Orca slicer open. For different machines and materials etc. 

It would be nice if this feature was somehow compatible with multiple instances of Orca.

**Comment by PhilBaz** [comment]
Maybe there can be a use one instance of Orca for Import option where it will import to the same instance as long as there is only one instance open? Any hacky solution would be good. 

It would just be too bad to have to choose between imports and multiple instances.

**Comment by foreachthing** [comment]
@PhilBaz, well, I don't like "hacky solutions" to a problem that really isn't one. Just _import_ [CTRL+I] your 3mf to begin with - don't double click it.  That's just my opinion... 😉

**Comment by PhilBaz** [comment]
@foreachthing This is only with regard to the printables import button, where you click the button right on the webpage. Not for files on the PC. I think the [CTRL+I] vs double click if for files on the PC.

It really will be a shame if you have to choose between printables import working in a way that's helpful, vs only ever having one instance of Orca open. For those of us with multiple printers having more than one instance open is critical. But then the way its currently implemented that means the printables import function will not really be helpful since each button push will launch a new instance of Orca.
