### ISSUE TITLE
Print Log with Tagging (also filament tracking)

### ISSUE THREAD

**Issue by g3gg0** [SoftFever/OrcaSlicer#5766]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I am now and then printing stuff for friends, for my work, for the house or for kids.
Especially when printing a few parts for friends or I simply want to check where my filament has gone,
the slicer could have helped me with (relatively) low effort.

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

The slicer's "print plate" button is a good place to also add some log entry, be it some CSV,
or even a small DB, HTML or even XML (with XSLT for visual appearance) with history of what has been printed.

Lets check this great and concise statistics screen:
![grafik](https://github.com/SoftFever/OrcaSlicer/assets/479231/9a92870d-90aa-42cf-9808-f794700a45bd)

When I now could simply have a dropdown / list field where I could enter "Johns MPCNC" or "Toys"
and it would write these values into a file, that would be great.

Maybe this is also good to be combined with #4840 which also aims towards "being aware" of the costs and print time.

Dont get me wrong - It's a slicer, not SAP. But it's about properly exporting the metadata of a print as OrcaSlicer even
knows the serial number of the (currently) inserted filament spool.

Thanks for your great work!

### Describe alternatives you've considered

1. i could copy a screenshot of every print job
2. or write the numbers manually

still i would be missing the spool S/N and probably the thumbnail of the print

**Comment by kylek29** [comment]
Certain values are exposed in the G-Code placeholders, you could use a post-processing script call to extract those and push them to a database. It wouldn't show in the UI, but you'd at least get your stats out in a more automated way.

I know there's codes for:
- extruded_value (per extruder)
- extruded_volume_total (sum of all)
- extruded_weight (per extruder)
- extruded_weight_total (sum of all)
- total_layer_count (all)
- In Prusa, there's also a print time one, but I don't see it listed in Orca -- I imagine it's there though.

But I don't think they expose any of the slicing statistics in the breakdown.
