### ISSUE TITLE
Arrange on Round Beds do not work correctly

### ISSUE THREAD

**Issue by Cascadier1** [SoftFever/OrcaSlicer#5767]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.0 rc

### Operating System (OS)

Windows

### OS Version

Win11

### Printer

Kossel Linear Plus

### How to reproduce

arrange a few objects

### Actual results

![Screenshot 2024-06-19 165803](https://github.com/SoftFever/OrcaSlicer/assets/138386572/c4d8d9ea-588f-45ed-bf75-ecac5a2f7151)

### Expected results

arranged to the missle of the Bed

### Project file & Debug log uploads

[arrange.zip](https://github.com/user-attachments/files/15902830/arrange.zip)

### Checklist of files to include

- [ ] Log file
- [x] Project file

**Comment by bruce98101** [comment]
I have the same issue using OrcaSlicer_Linux_AppImage_V2.3.0.AppImage. Mentioned it in another issue, but this would be the correct one. 

![Image](https://github.com/user-attachments/assets/0114bfcf-b1f0-4fdd-be9d-4274f453a76d)
