### ISSUE TITLE
Messages blocked from veiw

### ISSUE THREAD

**Issue by thisnyjared** [SoftFever/OrcaSlicer#5768]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.0

### Operating System (OS)

Windows

### OS Version

Windows 11

### Printer

Ender 3

### How to reproduce

On a smaller screen no matter what you do the gcode bar always blocks the message.
<img width="634" alt="Screenshot 2024-06-18 182426" src="https://github.com/SoftFever/OrcaSlicer/assets/65688066/cc8135a5-ec6e-4fbe-9cbb-f2e67ed1a907">

### Actual results

I can't see the message or act based on what it says
<img width="634" alt="Screenshot 2024-06-18 182426" src="https://github.com/SoftFever/OrcaSlicer/assets/65688066/92b3d3f3-c169-4595-8f37-e83974c500d2">

### Expected results

I should be able to see the message and click links I think it is because I have a small laptop screen with a resolution of 1280 x 720

### Project file & Debug log uploads

n/a

### Checklist of files to include

- [X] Log file
- [X] Project file

### Anything else?

It happens reguardless of any thing I do including the project or even clicking the button there.
<img width="634" alt="Screenshot 2024-06-18 182426" src="https://github.com/SoftFever/OrcaSlicer/assets/65688066/3aee92be-52ff-4b14-b2e6-edf3b013ee72">
<img width="638" alt="Screenshot 2024-04-29 191202" src="https://github.com/SoftFever/OrcaSlicer/assets/65688066/2b77f16f-9f80-4c62-bbe1-c1a4de1a6833">

**Comment by foreachthing** [comment]
Yeah, I hate that, too! Just press [C] on your keyboard to hide the gcode window.
I wish for the notification to be on top of the gcode window.  :crossed_fingers:

**Comment by shashachu** [comment]
> Yeah, I hate that, too! Just press [C] on your keyboard to hide the gcode window. I wish for the notification to be on top of the gcode window. 🤞

Thank you for this tip! I'm a new Orca user from Bambu Studio and I could not figure out how to hide that window.
