### ISSUE TITLE
Weird wall route that leads to issues

### ISSUE THREAD

**Issue by abrilevskiy** [SoftFever/OrcaSlicer#5769]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

macOS

### OS Version

Sonoma 14.5 (23F79)

### Printer

Ultimaker 2+

### How to reproduce

Slice attached file [Cover.3mf.zip](https://github.com/user-attachments/files/15904062/Cover.3mf.zip)

### Actual results

<img width="922" alt="Screenshot 2024-06-19 at 18 04 10" src="https://github.com/SoftFever/OrcaSlicer/assets/7629383/9c131828-60d7-49e0-8701-0841021b0dff">
A lot of isolated disconnected walls that leads to issues

### Expected results

The grid pattern is recognized and printed as lines

### Project file & Debug log uploads

[log.zip](https://github.com/user-attachments/files/15904117/log.zip)
[Cover.dbg.3mf.zip](https://github.com/user-attachments/files/15904118/Cover.dbg.3mf.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by discip** [comment]
Try this:
Just rename by deleting **`.txt`**.
[Cover.dbg.3mf.txt](https://github.com/user-attachments/files/15938325/Cover.dbg.3mf.txt)

**Comment by abrilevskiy** [comment]
> Try this: Just rename by deleting **`.txt`**. [Cover.dbg.3mf.txt](https://github.com/user-attachments/files/15938325/Cover.dbg.3mf.txt)

It does the trick, but it is barely possible to define precisely the size of the grid. Thank you for the workaround, but it would be nice to have a fix since it might affect at different cases.

**Comment by discip** [comment]
This should be almost identical to your original file.
[Cover.dbg.3mf.txt](https://github.com/user-attachments/files/15980011/Cover.dbg.3mf.txt)
