### ISSUE TITLE
Max volumetric speed test doesn't go above 20mm3/s

### ISSUE THREAD

**Issue by auradata** [SoftFever/OrcaSlicer#577]
If you set up a calibration of max flowrate with a max rate over 20mm3/s, it creates a model the correct height but any height which should be above 20mm3/s is only showing flow rates of 20.58 in the slicer

**Comment by Prutsium** [comment]
Check the max flow setting in the Filament at that is default 20.
![image](https://user-images.githubusercontent.com/42968695/227613830-a5f8b955-d15b-4f08-81b6-abebc6e2609b.png)

**Comment by auradata** [comment]
The calibration script automatically sets that to 200, I've tried setting it manually too but it still won't go above 20 in the test print

**Comment by Prutsium** [comment]
Strange i can push it over 60
![image](https://user-images.githubusercontent.com/42968695/227713846-9ed8bc0b-4115-4e37-88ed-31d0ff24c8db.png)

**Comment by auradata** [comment]
The part was set to the wrong filament which still had a 20mm3/s limit
