### ISSUE TITLE
STL MESH ERROR

### ISSUE THREAD

**Issue by Frank-EBLUE** [SoftFever/OrcaSlicer#5770]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

v2.1 Beta

### Operating System (OS)

Windows

### OS Version

Windows 11

### Additional system information

Device name	DESKTOP-O75NO12
Processor	Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz   1.80 GHz
Installed RAM	8,00 GB
Device ID	BA3539D8-2031-4755-A5D0-E98A5DA4F02C
Product ID	00342-23706-60015-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	Pen and single touch support

### Printer

ITOPI REPRAP CREALITY 4.27 board

### How to reproduce

1: STL Loaded into Orca
2: Sliced
3: sent to printer

### Actual results

Gcode and file preview is correct however the printed part prints as if it has mesh errors. This happend to a few diferent STLs i uploaded.  This specific one, part on the right fails whilst the one on the left prints perfectly.
![Screenshot 2024-06-19 194058](https://github.com/SoftFever/OrcaSlicer/assets/173293666/d110384b-c245-44c3-a60e-30b94b3bddaa)
![image](https://github.com/SoftFever/OrcaSlicer/assets/173293666/ded13964-38a5-41b1-bbab-2e392f31c1e7)

### Expected results

Both files should print the same. Did a test on a another slicer and came out perfect. 

### Project file & Debug log uploads

[Uploading ORCA-MESH-BUG.zip…]()

### Checklist of files to include

- [X] Log file
- [X] Project file

### Anything else?

I had around 4 STLs with the same type of issue regarding the mesh.

**Comment by discip** [comment]
Have you by any chance the **`Arc fitting`** feature enabeled?

![image](https://github.com/SoftFever/OrcaSlicer/assets/53649486/ac3cad87-9d46-428d-81ed-89fae96e4e2d)

If so, your machine is most likely not able to process **`G2 / G3`** commands.

Please try again without that box checked.

**Comment by discip** [comment]
@Frank-EBLUE
Have you by any chance the **`Arc fitting`** feature enabeled?

![image](https://github.com/SoftFever/OrcaSlicer/assets/53649486/ac3cad87-9d46-428d-81ed-89fae96e4e2d)

If so, your machine is most likely not able to process **`G2 / G3`** commands.

Please try again without that box checked.

**Comment by discip** [comment]
@Frank-EBLUE
Have you by any chance the **`Arc fitting`** feature enabled?

![image](https://github.com/SoftFever/OrcaSlicer/assets/53649486/ac3cad87-9d46-428d-81ed-89fae96e4e2d)

If so, your machine is most likely not able to process **`G2 / G3`** commands.

Please try again without that box checked.
