### ISSUE TITLE
Spacenav functionality

### ISSUE THREAD

**Issue by ARDev1161** [SoftFever/OrcaSlicer#5772]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I have 3dconnexion mouse & I see that you use libspnav in CMake. But I can't rotate anything. Please, fix it =)

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

Bind movement and rotation in the same way as a regular mouse.

**Comment by discip** [comment]
@ARDev1161
Please see this issue #5204.
Maybe you could close this issue in favor of the one I mentioned above.
