### ISSUE TITLE
Fast  fan speed change  on cooling overhang   

### ISSUE THREAD

**Issue by pterodaktil02** [SoftFever/OrcaSlicer#5776]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

If there are small overhangs, the program adds many short changes to the fan speed. 
This makes no physical sense: the fan will not be able to accelerate in hundredths of a second

Moreover, an error occurs on working equipment https://klipper.discourse.group/t/mcu-sb2040-shutdown-timer-too-close/16413/366

[Untitled.zip](https://github.com/user-attachments/files/15916872/Untitled.zip) 

Fill the table with this model and slice with the Force Cooling overhangs and bridges option enabled

### Which printers will be beneficial to this feature?

Klipper

### Describe the solution you'd like

Add an option to ignore small changes in fan speed.

**Comment by TheUnlimited64** [comment]
Maybe the Spinup time fixes that? In the printer settings you can set 2 settings regarding the fan. I dont know the english terms because my Orcaslicer is german, but try searching for "fan spinup time" or something like that. Its in the general printer settings (atleast for bambulabs)

**Comment by pterodaktil02** [comment]
> Maybe the Spinup time fixes that? In the printer settings you can set 2 settings regarding the fan. I dont know the english terms because my Orcaslicer is german, but try searching for "fan spinup time" or something like that. Its in the general printer settings (atleast for bambulabs)

1. This makes no physical sense - the fan will not have time to change the speed and air flow in a tenth of a second
2. It creates redundant and dirty G-code
3. This leads to a DOS attack on the printer hardware: the printer is forced to process many meaningless commands. 
4. In some cases, this may cause printing to fail.

**Comment by TheUnlimited64** [comment]
?
The 2 settings target the issue that the fan has no infinite acceleration. If you set spin up time to 1s, I believe it turns it on 1s before it's needed.

That would potentially fix the problem, but I'm with you, that sections with 0.1s fan of, Should be ignored for example 

But try it first, maybe that fixes your issue entirely

**Comment by pterodaktil02** [comment]
In principle, it is possible to solve the problem at the printer level, but this is not correct. 
Because  the printer must honestly process the commands it receives. Otherwise it's a bad printer. 
The task of making the right set of commands is the task of the slicer.

**Comment by TheUnlimited64** [comment]
I think we're talking past each other, in orca slicer you can tell the slicer, that the printer has not infinite spin up time, that way the slicer knows that it needs to spin up the fan beforehand 

So the printer itself has nothing to do, just execute gcode as normal and the fan gcode command is just a few commands beforehand

**Comment by pterodaktil02** [comment]
Apparently I don't know Orca slicer that well. Tell me where to adjust the fan spin-up time in Orca

**Comment by TheUnlimited64** [comment]
![image](https://github.com/SoftFever/OrcaSlicer/assets/51420498/9d7c4beb-9683-408f-a9f6-1d13a43c0363)
Press there

![image](https://github.com/SoftFever/OrcaSlicer/assets/51420498/10f6b766-884f-4767-8625-f41c956d670d)
Theres the settings, i didnt tempered with it yet, but i believe it would fix it

**Comment by pterodaktil02** [comment]
![image](https://github.com/SoftFever/OrcaSlicer/assets/65681281/a19f2eda-d711-4772-96cf-2bc19360f5d9)
That  was a problem -  in  my  model  was  long  overhang - small no overhang  - small   overhang  - small no overhang -     long  overhang 
and   it  give    picture  like this 
![image](https://github.com/SoftFever/OrcaSlicer/assets/65681281/8173caa1-d925-4da9-9c20-4e453e3e35c7)
Problem solved  -remove  checkbox   and  all  become  fine
