### ISSUE TITLE
Autoarrange object placement

### ISSUE THREAD

**Issue by rkarlsba** [SoftFever/OrcaSlicer#578]
If I load three objects and press A, the objects are placed in the upper right corner
<img width="937" alt="Skjermbilde 2023-03-24 kl  19 56 08" src="https://user-images.githubusercontent.com/4253147/227615723-83181422-2887-4a2a-ac55-ae1aa9ebbd48.png">

Pressing shift+A, however, places them in the centre, which I've always seen before
<img width="897" alt="Skjermbilde 2023-03-24 kl  19 56 16" src="https://user-images.githubusercontent.com/4253147/227615735-cdd4a034-657f-4e1a-bbd2-b80daffcde51.png">

If I only load one object and press A, it's placed in the centre

Any reason of this change? I can't see why placing them in a corner will do anything good.

This is on OrcaSlicer 1.5 on mac intel

**Comment by bojangles86** [comment]
odd. i can load 5 objects on the plate and arrange them and they all sort themselves in the middle (more or less). 
orca 1.5 on linux.

**Comment by rkarlsba** [comment]
I dug a bit further into this and found this: I started a new project and added two elementaries, cubes. Pressed a and they autoarrange in the middle. Then, if I change one part to using tree supports (which it obviously doesn't need, but the other parts earlier, did), both cubes gets placed in the corner with a.
