### ISSUE TITLE
Preferences Window Does Not Scale Properly in Multi-Monitor Setup

### ISSUE THREAD

**Issue by ElectricalBoy** [SoftFever/OrcaSlicer#5782]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.0-rc

### Operating System (OS)

Windows

### OS Version

Windows 11 23H2 (build 22631.3737)

### Additional system information

Monitor resolutions
- Primary monitor: 3840 x 2160 (4K)
- Secondary monitor: 1920 x 1080 (FHD)

### Printer

Irrelevant

### How to reproduce

1. Launch OrcaSlicer.
2. Move the OrcaSlicer window to the secondary monitor.
3. Open up the Preferences menu (or just hit `Ctrl+P`).
4. Observe the Preferences popup.

### Actual results

![popup_too_big](https://github.com/SoftFever/OrcaSlicer/assets/15651807/ba8872eb-688c-4a49-82bf-a917f280b0a6)

The opened popup does not fit the secondary monitor and gets "cut out" from the screen.

### Expected results

Preferences popup is opened with a scroll bar, as it would on a single-monitor 1080p setup.

### Project file & Debug log uploads

Irrelevant

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by SckyzO** [comment]
Yes, same bug but only with 2 screens that have the same resolution. 

I think it will be a good idea to open the Preferences in a new tab for better readability :)

![image](https://github.com/SoftFever/OrcaSlicer/assets/683678/7577379b-f189-4f9c-9f13-bcb943bb8b4b)

**Comment by lin-ycv** [comment]
This is a issue on single monitor too
![image](https://github.com/SoftFever/OrcaSlicer/assets/60565737/aa0bf31e-378e-4ab6-a260-48816396555c)
