### ISSUE TITLE
FR: Fix Model on Linux

### ISSUE THREAD

**Issue by tim-gromeyer** [SoftFever/OrcaSlicer#5785]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Im always frustrated when there is a broken modem and they are telling me I need to go to Windows to use the "Fix Model" function 

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

An cross platform implementation of "fix model"

### Describe alternatives you've considered

-

### Additional context

-

**Comment by sperdev54** [comment]
Please make this feature cross-platform. It’s very useful, and since I’m already on Linux, I can’t use Microsoft 3D Builder, which was also great for quick fixes.
