### ISSUE TITLE
does not generate bed temperature or filament temperature for printing

### ISSUE THREAD

**Issue by skyguynca** [SoftFever/OrcaSlicer#5798]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

Windows

### OS Version

Windows 10

### Additional system information

Cpu i5 7600k 64gb ram 1050 gpu

### Printer

voron switchwire

### How to reproduce

it appeared when after tuning for ABS filament and PLA filament profiles

### Actual results

When slicing temperatures are not in the Gcode, I have to enter all m190 and m109 into the gcodes generated to print

### Expected results

I need it to put the printing temps according to the filament profiles into the gcode
[Califlower_v29_ABS_2h7m.txt](https://github.com/user-attachments/files/15933890/Califlower_v29_ABS_2h7m.txt)

### Project file & Debug log uploads

[Califlower_v29.zip](https://github.com/user-attachments/files/15933918/Califlower_v29.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Anything else?

nothings

**Comment by inspectionsbybob** [comment]
I am having the same issue.  I had to wait for the Bed Level and Homing to finish and then manually set the temperature.

Enclosed is my Project file and the resulting Gcode file

[OrcaToleranceTest.zip](https://github.com/user-attachments/files/16091612/OrcaToleranceTest.zip)
