### ISSUE TITLE
Export Config stop working on V1.5.0

### ISSUE THREAD

**Issue by TechDude23** [SoftFever/OrcaSlicer#580]
With Softfever 1.4 you could export your configs but after installing Orca silicer 1.5 you can not export any new configs made. 

If you have any past configs with same name in the folder then it will overwrite and update that profile fine.

My work around for now has been to use soft fever until 1.5 is fixed for exporting my configs. 

It would be nice to also have a option to ( export all configs ) for backing up all your profiles with just one click.  

Thank you for the great slicer :)

**Comment by TechDude23** [comment]
Window 64 version

**Comment by superceleron** [comment]
i can confirm this it does not export or import, on 1.5.0.

**Comment by markuswarlich** [comment]
i can also confirm. It does not export or import, on 1.5.0.

**Comment by DanielGroot** [comment]
i can also confirm. It does not export or import, on 1.5.0.

**Comment by TechDude23** [comment]
Thank you for Fixing it
