### ISSUE TITLE
Setup Wizard does not load on Arch

### ISSUE THREAD

**Issue by CitrusIntellect** [SoftFever/OrcaSlicer#5802]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.0

### Operating System (OS)

Linux

### OS Version

Arch Linux

### Additional system information

OS: Arch Linux
KERNEL: 6.9.5-arch1-1
CPU: 13th Gen Intel Core i7-13700F
GPU: NVIDIA GeForce RTX 4060
GPU DRIVER: NVIDIA 550.90.07
RAM: 32 GB
DE: Kde Plasna 6.1.0 (Wayland)

### Printer

Software Side

### How to reproduce

Use appimage in terminal to open OrcaSlicer, nothing loads

### Actual results

Nothing Loads

### Expected results

Setup Manager should come up so I can do setup.

### Project file & Debug log uploads

LOG:
----START OF LOG----
[2024-06-22 00:02:16.492588] [0x000079e7eca9cb80] [trace]   Initializing StaticPrintConfigs
add font of HarmonyOS_Sans_SC_Bold returns 1
add font of HarmonyOS_Sans_SC_Regular returns 1
add font of NanumGothic-Regular returns 1
add font of NanumGothic-Bold returns 1

(orca-slicer:20391): GLib-GObject-CRITICAL **: 00:02:17.232: invalid cast from 'wxPizza' to 'GtkCellLayout'

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:17.232: gtk_cell_layout_get_cells: assertion 'GTK_IS_CELL_LAYOUT (cell_layout)' failed

(orca-slicer:20391): GLib-GObject-CRITICAL **: 00:02:17.233: invalid cast from 'wxPizza' to 'GtkCellLayout'

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:17.233: gtk_cell_layout_get_cells: assertion 'GTK_IS_CELL_LAYOUT (cell_layout)' failed

(orca-slicer:20391): GLib-GObject-CRITICAL **: 00:02:17.235: invalid cast from 'wxPizza' to 'GtkCellLayout'

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:17.235: gtk_cell_layout_get_cells: assertion 'GTK_IS_CELL_LAYOUT (cell_layout)' failed

(orca-slicer:20391): GLib-GObject-CRITICAL **: 00:02:17.236: invalid cast from 'wxPizza' to 'GtkCellLayout'

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:17.236: gtk_cell_layout_get_cells: assertion 'GTK_IS_CELL_LAYOUT (cell_layout)' failed

(orca-slicer:20391): GLib-GObject-CRITICAL **: 00:02:17.237: invalid cast from 'wxPizza' to 'GtkCellLayout'

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:17.238: gtk_cell_layout_get_cells: assertion 'GTK_IS_CELL_LAYOUT (cell_layout)' failed

(orca-slicer:20391): GLib-GObject-CRITICAL **: 00:02:17.239: invalid cast from 'wxPizza' to 'GtkCellLayout'

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:17.239: gtk_cell_layout_get_cells: assertion 'GTK_IS_CELL_LAYOUT (cell_layout)' failed

(orca-slicer:20391): GLib-GObject-CRITICAL **: 00:02:17.241: invalid cast from 'wxPizza' to 'GtkCellLayout'

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:17.241: gtk_cell_layout_get_cells: assertion 'GTK_IS_CELL_LAYOUT (cell_layout)' failed

(orca-slicer:20391): GLib-GObject-CRITICAL **: 00:02:17.242: invalid cast from 'wxPizza' to 'GtkCellLayout'

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:17.242: gtk_cell_layout_get_cells: assertion 'GTK_IS_CELL_LAYOUT (cell_layout)' failed

(orca-slicer:20391): GLib-GObject-CRITICAL **: 00:02:17.244: invalid cast from 'wxPizza' to 'GtkCellLayout'

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:17.244: gtk_cell_layout_get_cells: assertion 'GTK_IS_CELL_LAYOUT (cell_layout)' failed

(orca-slicer:20391): GLib-GObject-CRITICAL **: 00:02:17.245: invalid cast from 'wxPizza' to 'GtkCellLayout'

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:17.246: gtk_cell_layout_get_cells: assertion 'GTK_IS_CELL_LAYOUT (cell_layout)' failed
libEGL warning: egl: failed to create dri2 screen

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:17.609: gtk_window_resize: assertion 'height > 0' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:17.621: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:17.621: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:17.621: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:17.621: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:17.622: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:17.622: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:17.622: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:17.622: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:17.636: gtk_window_resize: assertion 'height > 0' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:17.640: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:17.640: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:17.866: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:17.866: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:17.884: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:17.884: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:17.890: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:17.890: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:17.901: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:17.901: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:17.911: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:17.911: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:17.921: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:17.921: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:17.932: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:17.932: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:17.941: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:17.941: gtk_widget_set_size_request: assertion 'width >= -1' failed

** (orca-slicer:20391): CRITICAL **: 00:02:18.025: Cannot register URI scheme wxfs more than once

** (orca-slicer:20391): CRITICAL **: 00:02:18.025: Cannot register URI scheme memory more than once

** (orca-slicer:20391): CRITICAL **: 00:02:18.204: Cannot register URI scheme wxfs more than once

** (orca-slicer:20391): CRITICAL **: 00:02:18.204: Cannot register URI scheme memory more than once

** (orca-slicer:20391): CRITICAL **: 00:02:18.212: Cannot register URI scheme wxfs more than once

** (orca-slicer:20391): CRITICAL **: 00:02:18.212: Cannot register URI scheme memory more than once

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:18.238: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:18.238: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:18.238: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:18.238: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:18.238: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:18.238: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:18.271: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:18.271: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:18.271: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:18.271: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:18.271: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:18.271: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:18.273: gtk_window_resize: assertion 'width > 0' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:18.273: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:18.428: gtk_window_resize: assertion 'height > 0' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:18.429: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:18.429: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:18.431: gtk_window_resize: assertion 'height > 0' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:18.432: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:18.432: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:18.434: gtk_window_resize: assertion 'height > 0' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:18.435: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:18.435: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:18.436: gtk_window_resize: assertion 'height > 0' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:18.436: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:18.436: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:18.445: gtk_window_resize: assertion 'height > 0' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:18.446: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:18.446: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:18.711: gtk_window_resize: assertion 'height > 0' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:18.711: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:18.711: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:18.713: gtk_window_resize: assertion 'height > 0' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:18.713: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:18.713: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:18.715: gtk_window_resize: assertion 'height > 0' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:18.715: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:18.715: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:18.716: gtk_window_resize: assertion 'height > 0' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:18.716: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:18.716: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:18.720: gtk_window_resize: assertion 'height > 0' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:18.720: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:18.720: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:19.092: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): GLib-GObject-CRITICAL **: 00:02:19.093: invalid cast from 'wxPizza' to 'GtkCellLayout'

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:19.093: gtk_cell_layout_get_cells: assertion 'GTK_IS_CELL_LAYOUT (cell_layout)' failed

(orca-slicer:20391): GLib-GObject-CRITICAL **: 00:02:19.094: invalid cast from 'wxPizza' to 'GtkCellLayout'

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:19.094: gtk_cell_layout_get_cells: assertion 'GTK_IS_CELL_LAYOUT (cell_layout)' failed

(orca-slicer:20391): GLib-GObject-CRITICAL **: 00:02:19.102: invalid cast from 'wxPizza' to 'GtkCellLayout'

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:19.102: gtk_cell_layout_get_cells: assertion 'GTK_IS_CELL_LAYOUT (cell_layout)' failed

(orca-slicer:20391): GLib-GObject-CRITICAL **: 00:02:19.103: invalid cast from 'wxPizza' to 'GtkCellLayout'

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:19.103: gtk_cell_layout_get_cells: assertion 'GTK_IS_CELL_LAYOUT (cell_layout)' failed

(orca-slicer:20391): GLib-GObject-CRITICAL **: 00:02:19.138: invalid cast from 'wxPizza' to 'GtkCellLayout'

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:19.138: gtk_cell_layout_get_cells: assertion 'GTK_IS_CELL_LAYOUT (cell_layout)' failed

(orca-slicer:20391): GLib-GObject-CRITICAL **: 00:02:19.140: invalid cast from 'wxPizza' to 'GtkCellLayout'

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:19.140: gtk_cell_layout_get_cells: assertion 'GTK_IS_CELL_LAYOUT (cell_layout)' failed

(orca-slicer:20391): GLib-GObject-CRITICAL **: 00:02:19.140: invalid cast from 'wxPizza' to 'GtkCellLayout'

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:19.140: gtk_cell_layout_get_cells: assertion 'GTK_IS_CELL_LAYOUT (cell_layout)' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:19.253: gtk_window_resize: assertion 'height > 0' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:19.253: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:19.253: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:19.255: gtk_window_resize: assertion 'height > 0' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:19.283: gtk_window_resize: assertion 'height > 0' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:19.284: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:19.284: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:19.284: gtk_window_resize: assertion 'height > 0' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:19.285: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:19.285: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:19.285: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:19.285: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:19.290: gtk_window_resize: assertion 'height > 0' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:19.291: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:19.291: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:19.299: gtk_window_resize: assertion 'height > 0' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:19.300: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:19.300: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:19.301: gtk_window_resize: assertion 'height > 0' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:19.313: gtk_window_resize: assertion 'height > 0' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:19.313: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:19.313: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:19.314: gtk_window_resize: assertion 'height > 0' failed

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:19.322: gtk_widget_set_size_request: assertion 'width >= -1' failed
Failed to get GBM device

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:19.702: gtk_widget_set_size_request: assertion 'width >= -1' failed
Failed to get GBM device
No such file or directory

(orca-slicer:20391): GLib-GObject-CRITICAL **: 00:02:21.955: invalid cast from 'wxPizza' to 'GtkCellLayout'

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:21.955: gtk_cell_layout_get_cells: assertion 'GTK_IS_CELL_LAYOUT (cell_layout)' failed

(orca-slicer:20391): GLib-GObject-CRITICAL **: 00:02:21.955: invalid cast from 'wxPizza' to 'GtkCellLayout'

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:21.955: gtk_cell_layout_get_cells: assertion 'GTK_IS_CELL_LAYOUT (cell_layout)' failed

(orca-slicer:20391): GLib-GObject-CRITICAL **: 00:02:21.966: invalid cast from 'wxPizza' to 'GtkCellLayout'

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:21.966: gtk_cell_layout_get_cells: assertion 'GTK_IS_CELL_LAYOUT (cell_layout)' failed

(orca-slicer:20391): GLib-GObject-CRITICAL **: 00:02:21.966: invalid cast from 'wxPizza' to 'GtkCellLayout'

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:21.966: gtk_cell_layout_get_cells: assertion 'GTK_IS_CELL_LAYOUT (cell_layout)' failed

(orca-slicer:20391): GLib-GObject-CRITICAL **: 00:02:21.971: invalid cast from 'wxPizza' to 'GtkCellLayout'

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:21.971: gtk_cell_layout_get_cells: assertion 'GTK_IS_CELL_LAYOUT (cell_layout)' failed

(orca-slicer:20391): GLib-GObject-CRITICAL **: 00:02:21.976: invalid cast from 'wxPizza' to 'GtkCellLayout'

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:21.976: gtk_cell_layout_get_cells: assertion 'GTK_IS_CELL_LAYOUT (cell_layout)' failed

(orca-slicer:20391): GLib-GObject-CRITICAL **: 00:02:21.976: invalid cast from 'wxPizza' to 'GtkCellLayout'

(orca-slicer:20391): Gtk-CRITICAL **: 00:02:21.976: gtk_cell_layout_get_cells: assertion 'GTK_IS_CELL_LAYOUT (cell_layout)' failed

** (orca-slicer:20391): CRITICAL **: 00:02:22.011: Cannot register URI scheme wxfs more than once

** (orca-slicer:20391): CRITICAL **: 00:02:22.011: Cannot register URI scheme memory more than once
Failed to get GBM device
Failed to get GBM device
Failed to get GBM device
Failed to get GBM device
----END OF LOG----

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by darrellenns** [comment]
I believe this is an bug with webkit2gtk and nvidia drivers. You can work around it by setting the environment variable WEBKIT_DISABLE_DMABUF_RENDERER=1.

Similar issues are reported in multiple places. For example:
https://gitlab.archlinux.org/archlinux/packaging/packages/webkit2gtk/-/issues/1
https://github.com/tauri-apps/tauri/issues/9304
https://bugs.archlinux.org/task/79783 (same issue happened with an older webkit2gtk version)
https://bugs.webkit.org/show_bug.cgi?id=261874 (same issue happened with an older webkit2gtk version)

**Comment by CitrusIntellect** [comment]
That did the trick! Thanks
