### ISSUE TITLE
Update bug 2.1.0

### ISSUE THREAD

**Issue by kris0725pl** [SoftFever/OrcaSlicer#5809]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

bug in update 2.1.0

### Which printers will be beneficial to this feature?

Others

### Describe the solution you'd like

hi i have 2.1.0 beta version on windows. today i got popup screen with update to....2.1.0! Always download 2.1.0 and got the same version...please check this

**Comment by tlhintoq** [comment]
Installed fine for me.  I always run the installer with "Run as administrator" so it has full rights to replace things like the graphics for the popups.

I'll admit it would help if the application information was updated so we didn't have to rely on the `About...` dialog.  When you get the info for the executable the version and file information is blank.

![image](https://github.com/SoftFever/OrcaSlicer/assets/11351506/e30d9e02-5542-4e19-a72b-713b4ac79446)
