### ISSUE TITLE
closed box slices open 

### ISSUE THREAD

**Issue by bendelathouwer** [SoftFever/OrcaSlicer#5819]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.0

### Operating System (OS)

Windows

### OS Version

Win 10

### Printer

ender 3 v3 se

### How to reproduce

 slice a simple rectangular box 
![normal model](https://github.com/SoftFever/OrcaSlicer/assets/6255058/3db8240c-0727-4831-8f50-943af3328f42)

### Actual results

![image_2024-06-23_105800570](https://github.com/SoftFever/OrcaSlicer/assets/6255058/30e919d4-58a8-4e77-8034-8685e70570ca)
 hollow box 

### Expected results

a solide box 

### Project file & Debug log uploads

[Desktop.zip](https://github.com/user-attachments/files/15943936/Desktop.zip)
[Desktop.zip](https://github.com/user-attachments/files/15943939/Desktop.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by Arakon** [comment]
It's doing EXACTLY what you set it up to do.
No top surface, no infill. This is not a bug.
![image](https://github.com/SoftFever/OrcaSlicer/assets/12016360/bc1305f6-f3e2-4730-aad9-8bdbe560300e)

**Comment by bendelathouwer** [comment]
Still never worked with a slicer that uses defaults like that , so might be worth changing that especially for the beginners  :)
