### ISSUE TITLE
"Only 1 wall on top surfaces" only works for top-most surface when Arachne is used

### ISSUE THREAD

**Issue by npoulos** [SoftFever/OrcaSlicer#582]
Tested in regular bambu slicer vs orca and it only seems to be an issue in orca.

If you add a primitive cube it will slice correctly with 1 wall at the top. but if you add a any model with more than 1 top surface, onnly the very top surface in the model has 1 wall while the other top surfaces keep whatever the wall loops is set to.

You can test this with make 2 cubes, one bigger than the other, assemble them and then slice.

*macOS

**Comment by npoulos** [comment]
<img width="782" alt="image" src="https://user-images.githubusercontent.com/58903683/227697872-38d6924f-6ff4-4df4-b53d-fc1b71bcd5b1.png">

**Comment by hliebscher** [comment]
is open here again #547

**Comment by liftbag** [comment]
> here

And here #379

**Comment by npoulos** [comment]
@SoftFever any thoughts on fixing this one? The issue doesn't seem to appear in BambuStudio

**Comment by dantetemp** [comment]
@SoftFever any updates on this?

**Comment by npoulos** [comment]
Hi @SoftFever is there a reason all the tickets re: this issue are being ignored?

**Comment by SoftFever** [comment]
Hold your horses, boys.
I'm not a super man

**Comment by SoftFever** [comment]
FYI, this is an issue for the Arachne generator only.
You can switch to "Classical wall generator" if you want a true 1 wall top surface for now.

**Comment by npoulos** [comment]
Woops! Sorry to put pressure on you! Just wasn’t sure if these were being “ignored” or just not yet gotten to! Thanks for all you do mate 😊 will sit tight!

**Comment by Noisyfox** [comment]
> @SoftFever any thoughts on fixing this one? The issue doesn't seem to appear in BambuStudio

If you look more closely you'll notice that when Arachne is selected the "Only one wall on top surfaces" options is disabled in BBS.
