### ISSUE TITLE
Need wiki and settings explanations

### ISSUE THREAD

**Issue by otede** [SoftFever/OrcaSlicer#5822]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

1. From an end-user perspective, if considered in yes or no manner, Orca settings are undocumented. The user has to know what a setting does from non-Orca-related resources. 
2. If there's an Orca-specific handling of a setting user is at a loss. Example https://www.reddit.com/r/OrcaSlicer/comments/1dm89rx/support_threshold_angle_ignored/
3. Orca's interface is full of clickable setting names that lead to nowhere (no actual wiki articles as suggested by popups)
4. Orca's wiki is virtually non-existent

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

1. Establish a wiki or link to an external one. As an interim measure maybe something like this https://3dprinterly.com/cura-settings-ultimate-guide-settings-explained-how-to-use/
2. Create in-Orca equivalent to https://github.com/Ghostkeeper/SettingsGuide - an in-app illustrated guide that pops up on hover for individual slicer settings

### Describe alternatives you've considered

Cura. Can't use anymore with new printer from Bambu Lab.

My experience with discovering there's no wiki:

How to reproduce

    Go to https://github.com/SoftFever/OrcaSlicer/wiki/
    Click on any of the 3 links there

Actual results

Links not opening any new pages. The site reloads.
Expected results

A wiki of some sort maybe... When I manually edited the link I got to
https://github.com/SoftFever/OrcaSlicer/wiki/Print-settings
where just the following is listed:
[Seam](https://github.com/SoftFever/OrcaSlicer/wiki/seam)
[Axiliary fan](https://github.com/SoftFever/OrcaSlicer/wiki/auxiliary-fan)
[Chamber temperature](https://github.com/SoftFever/OrcaSlicer/wiki/chamber-temperature)
[Air filtration/Exhaust fan](https://github.com/SoftFever/OrcaSlicer/wiki/air-filtration)
[Single Extruder Multimaterial](https://github.com/SoftFever/OrcaSlicer/wiki/semm)
[Precise wall](https://github.com/SoftFever/OrcaSlicer/wiki/Precise-wall)
Is that it?

**Comment by sharky98** [comment]
I really like the https://github.com/Ghostkeeper/SettingsGuide in-app documentation. Here how I would see a multi-step implementation of this.

1. Create a Markdown file for each setting, organized by folder.
2. Create a Github Page site, using the [default Jekyll](https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll) static site generator.
3. Create a viewer inside Orca Slicer to show the Github Page site of the specific setting.
4. Evolve the viewer inside Orca Slicer to show a local rendered view of the Markdown files.
