### ISSUE TITLE
Low-resolution 3MF associated icon on macOS

### ISSUE THREAD

**Issue by khoanguyen-3fc** [SoftFever/OrcaSlicer#5823]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.0

### Operating System (OS)

macOS

### OS Version

macOS 14.5

### Printer

N/A

### How to reproduce

Open Finder at the location containing a `.3mf` file. Additionally, I have a `.gcode` file for comparison.

![image](https://github.com/SoftFever/OrcaSlicer/assets/16377833/7c513cf1-d6c1-4ddf-8480-53e2fb08abd3)

### Actual results

The .3mf file icon appears blurry

### Expected results

The .3mf file icon should match the clarity of other file icons in the Finder.

### Project file & Debug log uploads

N/A

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Ferbez** [comment]
It's not only blurry, it doesn't fit macOS design guidelines. I've made new high-res (current .3mf icon is only 64x64 for some reason, and .stl one is 256x256) ones which fit macOS better in #5897
