### ISSUE TITLE
OrcaSlicer ignoring the color of raised text despite painting.

### ISSUE THREAD

**Issue by jonathanalevi** [SoftFever/OrcaSlicer#5828]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.0 Beta

### Operating System (OS)

macOS

### OS Version

Sonoma 14.4.1

### Printer

AnyCubic Kobra 3 / Bambu Lab P1S

### How to reproduce

Please see attached video, you'll see that despite the painting on the edges of letters, it ignores them and plans to print them in the model color. 

### Actual results

Color painted on small edges is ignored. 

### Expected results

Color should be as painted. 

### Project file & Debug log uploads

[Patreon V3.3mf.zip](https://github.com/user-attachments/files/15944861/Patreon.V3.3mf.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Anything else?

https://github.com/SoftFever/OrcaSlicer/assets/1540530/c286a04c-b227-42a6-af67-9c6d455bde23

**Comment by igiannakas** [comment]
There is a bug right now with the Mac version having issues with painted wall surfaces. 

are you using a Mac?
