### ISSUE TITLE
Import Orientation Method from Prusa Slicer

### ISSUE THREAD

**Issue by cromine11** [SoftFever/OrcaSlicer#5836]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

The Arrange tool doesn't seem to be very effective. I have had incidents of overlap between parts and odd angles.
![Screenshot 2024-06-24 144450](https://github.com/SoftFever/OrcaSlicer/assets/75935020/b8a6e842-4065-4e34-a7fd-3f431d7da01a)

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

PrusaSlicer has already implemented a very good Arrange tool that puts things in a good orientation and never overlaps. I will typically arrange in PrusaSlicer just to have a good arrangement and then import to Orcaslicer. 
![Screenshot 2024-06-24 144558](https://github.com/SoftFever/OrcaSlicer/assets/75935020/e0de2b76-8333-422d-861b-ed4ebf54089e)

Additional suggestion:
Something that could also be added is print order organizer to optimize the order the parts are printed based off the arrangement so the tool head travels a reasonable distance to the next part or even do have it go to a part that is not right next to the one that was just printed so it has time to cool evenly. Give it a couple options.

**Comment by discip** [comment]
This should be combined with #5830.

**Comment by Arakon** [comment]
Seems to be the same issue as https://github.com/SoftFever/OrcaSlicer/issues/4719?
