### ISSUE TITLE
removed my profiles

### ISSUE THREAD

**Issue by TheJoyofPrinting** [SoftFever/OrcaSlicer#584]
profiles were removed. there is nothing explaining how to get it back...so this is just a paperweight on my desktop atm....you should add something somewhere thats easy to find that says how to get it back.

**Comment by Ibot-11** [comment]
When you delete a profile it of course gets deleted.
You can find all your profiles in the Roaming folder:
C:\Users\YOUR USERNAME\AppData\Roaming\BambuStudio-SoftFever\user

Please describe the issue more precisely. I don’t really understand what the problem is.
