### ISSUE TITLE
Slope angle for slope zhop

### ISSUE THREAD

**Issue by SilencedFrost** [SoftFever/OrcaSlicer#5845]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Slope zhop is really good to cut down print time and stringing according to my testing because it doesn't give time for material to ooze out

My filament is properly dried and kept in a drybox at 10% relative humidity for the matter

slope zhop is amazing in most cases, but for really long travels that passes through alot of printed parts, parts like curled edges, slight over-extrusion can get caught in the way because the slope is too shallow and gradual

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

A parameter named "slope angle" should be added it will ascend at that slope until it reaches the desired zhop height, if the slope is too shallow to reach that height within the distance, let zhop height take over

This will make it reach the desired zhop height much sooner for long travels, and depending on the user's wish

**Comment by vovodroid** [comment]
Implemented and merged in  Add travel_slope option #5873, will be available in the next release.
