### ISSUE TITLE
Unable to print on Bambu printers with nozzles sizes other bambu supported nozzles

### ISSUE THREAD

**Issue by davidjdixon** [SoftFever/OrcaSlicer#5849]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.0

### Operating System (OS)

macOS

### OS Version

14.5

### Printer

Bambu X1 Carbon

### How to reproduce

1. Create a printer profile and configure with a nozzle size larger than 0.8mm (eg, in my case a 1.4mm Revo)
2. Print plate of any model

### Actual results

An error is returned about not matching the nozzle size of the printer, without any option to use the nozzle configuration.

![Screenshot 2024-06-24 at 21 34 06@2x](https://github.com/SoftFever/OrcaSlicer/assets/452007/b3a21e98-c878-438b-8dd4-79063d07a878)

### Expected results

in version <= 2.0, a warning was produced, but with options to ignore.

![Screenshot 2024-06-24 at 21 37 17@2x](https://github.com/SoftFever/OrcaSlicer/assets/452007/87c34e51-cae9-4bb1-bf0b-a28e0ffe24ad)

### Project file & Debug log uploads

N/A

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by jjleto** [comment]
same situation here work partially in 2.1 beta 
![Screenshot 2024-06-26 alle 19 51 08](https://github.com/SoftFever/OrcaSlicer/assets/4290761/57326cfd-a532-40c5-9b98-01d65b987ade)

**Comment by tlhintoq** [comment]
Windows give me the option to confirm and continue as shown by @jjleto 
2.1.0 latest on 01jun2024

![image](https://github.com/SoftFever/OrcaSlicer/assets/11351506/e2a2fd16-9946-4331-bf82-0cbefc21f1dc)

![image](https://github.com/SoftFever/OrcaSlicer/assets/11351506/e323addf-bfd9-403b-9a18-20b647d07fab)

**Comment by davidjdixon** [comment]
@tlhintoq If your build is from 1st June, then you will be using the 2.1.0 beta (not 2.1.0 as that wasn't released until 21st June), which indicates the related code was either introduced in 2.1.0 RC or 2.1.0.

**Comment by tlhintoq** [comment]
@davidjdixon   My bad.  01jul2024  (yesterday)

**Comment by davidjdixon** [comment]
@SoftFever is there any chance this recent change can be reverted? This issue prevents using custom nozzle sizes at all with Bambu Lab printers.

**Comment by Highlander-bdj** [comment]
In my opinion, #5877 should be listed as a bug not an enchantment.

**Comment by Anfernee12345** [comment]
> @SoftFever is there any chance this recent change can be reverted? This issue prevents using custom nozzle sizes at all with Bambu Lab printers.

Still having the same problem.
Cant find any way around it either.

**Comment by davidjdixon** [comment]
> > @SoftFever is there any chance this recent change can be reverted? This issue prevents using custom nozzle sizes at all with Bambu Lab printers.
> 
> Still having the same problem. Cant find any way around it either.

Have a try of the latest nightly. While theres been no updates here, it seems that the nightly has reverted this (at least for the moment).

**Comment by Anfernee12345** [comment]
> > Still having the same problem. Cant find any way around it either.
> 
> Have a try of the latest nightly. While theres been no updates here, it seems that the nightly has reverted this (at least for the moment).

Yes, thank you.
The latest nightly works, for now at least.

**Comment by anselor** [comment]
So, just to clarify for some people. This was a change that Bambu made to block non-standard nozzle diameters. It was patched out in the 2.1 beta but then prior to release another pull from the Bambu code undid the fix so 2.1 was released with this broken. It has subsequently been patched again and is waiting on another release.

**Comment by davidjdixon** [comment]
This has been resolved by #5900 and now part of [2.2.0-Beta](https://github.com/SoftFever/OrcaSlicer/releases/tag/v2.2.0-beta)
