### ISSUE TITLE
Model sketches have disappeared in Gcode since version 2.1( BIGTREETECH tft v3.1) 

### ISSUE THREAD

**Issue by Rsoft1976** [SoftFever/OrcaSlicer#5855]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1

### Operating System (OS)

Windows

### OS Version

windows 11

### Printer

Artillery SX1

### How to reproduce

starting from version 2.1 the picture disappeared in the settings, I also can’t select a type

there were settings
2.0
![1](https://github.com/SoftFever/OrcaSlicer/assets/65666155/620b601c-a3cb-4110-8d16-f4a708869847)

2.1 
![2](https://github.com/SoftFever/OrcaSlicer/assets/65666155/6b7ca5a4-3398-4946-a378-ee922083b1ec)

### Actual results

are added at the beginning of the line that does not work with Gcode
![3](https://github.com/SoftFever/OrcaSlicer/assets/65666155/6a790ecf-2950-4a60-aae8-d41b2cd735a7)

### Expected results

remove these lines at the very beginning
![5](https://github.com/SoftFever/OrcaSlicer/assets/65666155/8bcef82a-5841-4aee-83b3-a894ee9c629b)

### Project file & Debug log uploads

no

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by blackadar** [comment]
Also missing thumbnails with the latest release

**Comment by blackadar** [comment]
Ended up resolving this by modifying my printer config in Orca, it was missing the thumbnail size option. Once I put that back thumbnails started generating again.

**Comment by Rsoft1976** [comment]
what screen model?

**Comment by blasksun** [comment]
artillery genius pro, same problem after updating osca to 2.1 or latest GitHub thumbnails wont show up on the printer

**Comment by Rsoft1976** [comment]
Dear developer, will you fix this problem or not?
