### ISSUE TITLE
Make the window title editable and unify the "Send Print Job To" default popup job title 

### ISSUE THREAD

**Issue by evolutionlures** [SoftFever/OrcaSlicer#5859]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Yes, there appears to be no way to change the job name at the project level. I send prints to multiple printers in the farm, but each time I click the "Print Plate" button, the popup shows a default job name that is wrong and must be edited again for each job sent. There appears to be no way to change this job name before the popup happens. I never save projects because my files evolve sometimes and I have 100s of different stls to print. I just need a way to change the name of the job one time before sending the print to 10 different printers. Right now i have to re-edit the job name to be the correct name each time i click send. 

The benefit of naming the job correctly becomes important in bambu handy when you are trying to print from history. 

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

I would like to see an "Edit Job Name" interface in the project fields or always make the plate name become the job name by default.  

### Describe alternatives you've considered

The only alternative now is to edit the job name before sending it each time because its wrong if you opened a different file after your first print.

### Additional context

Title of the window showing birdman name but plate was cleared and the current model has nothing to do with that model anymore.
<img width="479" alt="Screenshot 2024-06-25 at 9 58 54 AM" src="https://github.com/SoftFever/OrcaSlicer/assets/170131087/906563e6-0109-451c-bc73-4cd4e90f6fb3">

Title of job still being adopted from an unchangable default name that was picked up the first time a file was imported.
<img width="1710" alt="Screenshot 2024-06-25 at 9 58 17 AM" src="https://github.com/SoftFever/OrcaSlicer/assets/170131087/8ae76ae1-567a-4a58-8356-a9ff6c38c0ec">

**Comment by RollingGecko** [comment]
That would be a big add on to the send function!
