### ISSUE TITLE
Small area flow compensation no longer working in 2.1.0

### ISSUE THREAD

**Issue by eusor-cp8** [SoftFever/OrcaSlicer#5864]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.0, 2.1.0-rc

### Operating System (OS)

Windows

### OS Version

Windows 10

### Printer

Bambu Lab A1 Mini

### How to reproduce

1. Add primitive cube in default scene
2. Enable "Small area flow compensation", default flow compensation model. I use : Bambu Lab A1 mini 0.4 nozzle, Bambu PLA Basic, 0.20mm Standard @BBL A1M.
4. Slice and look at flow speed around the cube corners, the flow rate isn't reduced in short segment. 

The same procedure in 2.1.0-beta works (both 2.1.0 and 2.1.0-rc are affected)

### Actual results

In 2.1.0, the flow speed of short segment isn't reduced. In 2.1.0-beta, it is. I've included two screenshot of the result in both 2.1.0 (broken) and 2.1.0-beta (working).
![OrcaSlicer210-safm](https://github.com/SoftFever/OrcaSlicer/assets/173865430/8f38ee1b-653c-4d77-9eac-61615f04e640)
![OrcaSlicer210beta-safc](https://github.com/SoftFever/OrcaSlicer/assets/173865430/23046feb-bc0e-4475-ae25-97d5ad665c44)

### Expected results

I'd expect for the flow speed to be reduced in short segment, like in the 2.1.0-beta version. It really helped reduces the impact of certain flow rate artifacts on some prints.

### Project file & Debug log uploads

[debug_Tue_Jun_25_22_38_54_28400.log.0.zip](https://github.com/user-attachments/files/15981643/debug_Tue_Jun_25_22_38_54_28400.log.
[Cube.zip](https://github.com/user-attachments/files/15981648/Cube.zip)
0.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by Noisyfox** [comment]
Have you tried the latest nightly build? I believe it has just been fixed yesterday.
