### ISSUE TITLE
Orca 2.1.0 starts loop in mid air

### ISSUE THREAD

**Issue by Rickthebig** [SoftFever/OrcaSlicer#5868]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.0

### Operating System (OS)

Windows

### OS Version

Windows 10

### Printer

DIY BLV Cube

### How to reproduce

Slice the model in the attached project file.
![image](https://github.com/SoftFever/OrcaSlicer/assets/151161212/119ba105-61aa-4a61-aeaf-bc05989e9ac1)

Go to Gcode line 193@48295 and see how Orca tries to extrude beginning in mid air if "Bridge counterbore holes" set to "Partially bridged".

### Actual results

With "Bridge counterbore holes" set to "Partially bridged":
![image](https://github.com/SoftFever/OrcaSlicer/assets/151161212/a9376f50-216e-40b8-ae40-9aa19f82a290)

### Expected results

With "Bridge counterbore holes" set to "None" the layer looks like it should:
![image](https://github.com/SoftFever/OrcaSlicer/assets/151161212/1ec4c0c8-a741-4be6-8e13-bb7c9a59d056)

### Project file & Debug log uploads

[Printing_in_mid_air_bridge_counterbore_hole.zip](https://github.com/user-attachments/files/15986670/Printing_in_mid_air_bridge_counterbore_hole.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Anything else?

A slicer should never start a loop in mid air.

**Comment by kylek29** [comment]
I observed this with another model as well.

**Comment by tlhintoq** [comment]
You see it with `organic` supports too.  Sometimes it makes a partial second/interior wall of the support just out in the middle of the air.
