### ISSUE TITLE
V1.50 windows zip missing Exe files, contains DLLs only

### ISSUE THREAD

**Issue by nicwilson58** [SoftFever/OrcaSlicer#588]
**Describe the bug**
V1.50 windows zip missing Exe files, contains DLLs only

**3mf File for This Bug**
N/A

**To Reproduce**
N/a

**Expected behavior**
N/A

**Screenshots**
N/a

**Printer model**
N/A
**Desktop (please complete the following information):**
N/A

**Comment by derpicknicker1** [comment]
There is an `orca-slicer.exe` in the zip file. That is all you need.
If it is in the archive but is missing after extraction of the archive, then check your anti malware software if it has any issue with the executable.
