### ISSUE TITLE
Calibration tab disappears when switching to non-Bambu printer and does not return

### ISSUE THREAD

**Issue by poppinfresh69** [SoftFever/OrcaSlicer#5880]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1 and 2.1.1

### Operating System (OS)

Windows

### OS Version

10

### Printer

Various

### How to reproduce

1) Start Orca and have Bambu printer selected
2) Note calibration tab next to Project tab
3) Select non-Bambu profile- I selected one of my two Ender profiles
4) Note Calibration tab disappears
5) Switch back to Bambu profile
6) Note Calibration remains missing requiring restart to get it back

### Actual results

Calibration tab disappears and does not return when re-selecting a Bambu printer. Restart of app required. You do not even have to have a model loaded to get this behavior.

### Expected results

Calibration tab should return without restart up selecting a Bambu profile.

### Project file & Debug log uploads

[debug_Wed_Jun_26_14_17_14_3340.log.zip](https://github.com/user-attachments/files/15993833/debug_Wed_Jun_26_14_17_14_3340.log.zip)

Project not needed to replicate

### Checklist of files to include

- [X] Log file
- [X] Project file

### Anything else?

![Bambu](https://github.com/SoftFever/OrcaSlicer/assets/142692274/8375221a-be24-47c2-9814-3d77e1188c44)
![Creality](https://github.com/SoftFever/OrcaSlicer/assets/142692274/ff5b8a83-dd7b-45d9-a89e-fe8c79dbb9f7)
![Bambu2](https://github.com/SoftFever/OrcaSlicer/assets/142692274/705e6586-d08e-433a-b5d4-e95ceaf4621b)

**Comment by tlhintoq** [comment]
+1 
Yep, does it for me too
