### ISSUE TITLE
2.1.1 Crashes when saving filament or creating filament profiles

### ISSUE THREAD

**Issue by justinr54321** [SoftFever/OrcaSlicer#5884]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

Windows

### OS Version

Windows 11

### Additional system information

Processor	13th Gen Intel(R) Core(TM) i7-13700HX   2.10 GHz
Installed RAM	32.0 GB (29.7 GB usable)
1GB SSD
GEFORCE RTX 4060 GPU

### Printer

Merc One Plus

### How to reproduce

Open or create a filament profile
Make changes
Click on save

### Actual results

Orca 2.1.1 freezes and crashes

### Expected results

Profile saved and able to move on

### Project file & Debug log uploads

[log.zip](https://github.com/user-attachments/files/15995154/log.zip)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by SoftFever** [comment]
Can you profile more info like how to reproduce it step by step?
I can't reproduce it

**Comment by justinr54321** [comment]
I do apologize, meant to close this ticket, as it started to work about an hour after I posted this. But when I did was made a change to filament color and flow rate and then save it,  it would freeze and crash. When I tried to do a new filament profile and save it, same thing. Gotta love software sometimes. Lol

**Comment by justinr54321** [comment]
Closing issue

**Comment by Noisyfox** [comment]
Could you send me your entire %AppData%\OrcaSlicer folder?

**Comment by justinr54321** [comment]
[OrcaSlicer.zip](https://github.com/user-attachments/files/16007878/OrcaSlicer.zip)
[OrcaSlicer.zip](https://github.com/user-attachments/files/16007882/OrcaSlicer.zip)

**Comment by Noisyfox** [comment]
Could you tell me which profile you have that could trigger this crash?

**Comment by justinr54321** [comment]
> Could you tell me which profile you have that could trigger this crash?

It was the COEX Metallic Silver ABS

**Comment by Noisyfox** [comment]
Does the same issue occur on 2.1.0?

**Comment by justinr54321** [comment]
It didn't. Happened after I updated, almost as if it had difficulties
communicating with the directory that held the filament profiles.
