### ISSUE TITLE
Travel accelerations are not getting emitted to GCode when default_jerk is not set.

### ISSUE THREAD

**Issue by Struxee** [SoftFever/OrcaSlicer#589]
Hi :)
I noticed that on the stock Voron 2.4 Profile with all stock settings that the travel_acceleration is not emitted into the Gcode.
You can search any sliced Gcode for "" M204 S(specified travel_acceleration) "" and find no results. 

After messing around with all kinds of settings i found out that the slicer will not emit the travel_acceleration into GCode if the default_jerk setting is set to 0 (disable Jerk control).

Once default_jerk is specified, the Gcode to set the travel_acceleration appears in the Gcode File

Jerk disabled:
![jerk_control_disabled](https://user-images.githubusercontent.com/48525970/227767418-c2e016ce-51c1-40f7-a45a-375af5f23de8.PNG)

Jerk enabled:
![jerk_control_enabled](https://user-images.githubusercontent.com/48525970/227767446-59890295-d636-45f2-875f-235edfe2efb6.PNG)

I have now configured my jerk control settings but i wanted to report it anyway because is can't imagine that behaviour is intended.

Thank you for your time :)
Love your Slicer ;)

**Comment by Chodec80** [comment]
Thanks for your report. I have the same issues and I couldn't figure out why.
(Orca 1.6.1)
