### ISSUE TITLE
Simple shapes dont work no more

### ISSUE THREAD

**Issue by Viking420** [SoftFever/OrcaSlicer#5898]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

Windows

### OS Version

Windows 11

### Additional system information

Haha Dont worry, its pulls lol 

I9 14900k
3090
64gb ddr5 7800mhz
10.000/10.000mbps ssd

Its your update, not my pc lmao

### Printer

It has nothing to do with any printer.. Its your software

### How to reproduce

Load one simple shape.. Change it size and then add a shape to the already made on

### Actual results

SHIT! Really bad update!

### Expected results

Get it fixed!! What els 
![Skærmbillede 2024-06-27 172654](https://github.com/SoftFever/OrcaSlicer/assets/155201040/c25ba098-032a-4e78-a060-69397f1c0e54)

### Project file & Debug log uploads

![Skærmbillede 2024-06-27 172654](https://github.com/SoftFever/OrcaSlicer/assets/155201040/233e3595-993f-4b4f-ab25-7a49c046358c)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by tlhintoq** [comment]
Looks like you added one part **TO** the other part, and so they became an assembly.
When you manipulate the assembly you manipulate both parts as one.
If you select just one object out of the assembly you can manipulate it individually.
I don't think its a bug.  I think you just didn't realize you made an assembly.
![image](https://github.com/SoftFever/OrcaSlicer/assets/11351506/c450cb21-cf1c-4c21-8958-8cf867c81fb5)
