### ISSUE TITLE
[Bug] OrcaSlicer does not embed text

### ISSUE THREAD

**Issue by esc247** [SoftFever/OrcaSlicer#590]
**Describe the bug**
When you use the add text tool in OrcaSlicer, you cannot embed the text. As per the screenshot: 
![image](https://user-images.githubusercontent.com/2703225/227771397-04e695f1-6ccd-4f3d-9745-44fbab35dfcf.png)

**To Reproduce**
After adding an object, select the Text embed tool and set the embedded depth value. Changing the value has no effect.

**Expected behavior**
When setting the value of the embedded depth, I was expecting that the text would be embedded into the object, however it does nothing.  I have added screenshots of thickness value changed as well. The min value that is automatically set is 0.10, even if I put in a negative value.

**Screenshots**
![image](https://user-images.githubusercontent.com/2703225/227771516-2122a55a-353c-46bf-8e72-41accb824693.png)
![image](https://user-images.githubusercontent.com/2703225/227771575-bab4c498-6e5f-4966-a1b3-c5fd9cccece1.png)

**Printer model**
VzBoT330

**Desktop (please complete the following information):**
 - OS: Mac
 - Version 13.2.1

**Comment by Cactus1906** [comment]
I don't know how this should work. 
Maybe the following is a workaround.
Right click on the "text_shape" in "objects view" and "Change Type" to "Negative Part" then the text is embossed.
In addition you can move the object "into" the object. In my example it's a 50mm cube with 9 mm thick negative text.
Hope it helps.
![grafik](https://user-images.githubusercontent.com/108296681/228784430-2d5c7e4a-3862-4439-8700-43d6a9fe6b3d.png)
![grafik](https://user-images.githubusercontent.com/108296681/228789191-67474cda-4977-416e-80e9-45521971c05c.png)

**Comment by esc247** [comment]
Thanks will try that out

**Comment by esc247** [comment]
I tried this, but my I still does not do what you did.
![image](https://user-images.githubusercontent.com/2703225/230067419-0d1972bd-2ef5-422b-9e28-0a9cd7bd045a.png)
![image](https://user-images.githubusercontent.com/2703225/230067603-298d9db7-cd6a-4f4b-ac6d-f63226ddcfb1.png)
![image](https://user-images.githubusercontent.com/2703225/230067774-8976e86b-8a8b-4efc-bfaf-b74e48aefe26.png)

**Comment by esc247** [comment]
Oh wait.... It worked! I had to slice it to see it :) Thanks very much!
