### ISSUE TITLE
[Feature Request] Custom Variables

### ISSUE THREAD

**Issue by wiggywoosaa** [SoftFever/OrcaSlicer#591]
It would be nice to have custom variables like superslicer has in the 'filament section - notes - custom variables'

**Comment by TexZeTech** [comment]
![image](https://user-images.githubusercontent.com/7254540/230512761-c0c681e4-c1a9-41dd-9da9-711cf872f310.png)

something for macros to use. 

@wiggywoosaa You should add your use case and add a screen shot at the least.

**Comment by voidtrance** [comment]
I second this request.

In my case, I assign a unique ID to every filament brand that I can then use to uniquely identify the filament in my macros and set various settings accordingly.

**Comment by kylek29** [comment]
I think it'd be a very useful feature port. Can we also get the Filament Notes section? Seems like it'd be useful for keeping those oddly specific filament tips/notes in a good place.
