### ISSUE TITLE
Crashes on start

### ISSUE THREAD

**Issue by fredjohnston** [SoftFever/OrcaSlicer#5915]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

macOS

### OS Version

11.0.1 Big Sur

### Additional system information

Hardware Overview:

  Model Name:	MacBook Air
  Model Identifier:	MacBookAir7,2
  Processor Name:	Dual-Core Intel Core i5
  Processor Speed:	1.6 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	3 MB
  Hyper-Threading Technology:	Enabled
  Memory:	8 GB
  System Firmware Version:	424.0.0.0.0
  SMC Version (system):	2.27f2
  Serial Number (system):	CPWRM5J4H3QD
  Hardware UUID:	1703A383-4F56-5791-8B7D-35F521508D22
  Provisioning UDID:	1703A383-4F56-5791-8B7D-35F521508D22

### Printer

NA

### How to reproduce

After install, run and get message 
![Screen Shot 2024-06-28 at 10 34 09 AM](https://github.com/SoftFever/OrcaSlicer/assets/28265553/32d1a2f8-5860-460a-aced-a2b8e96b3239)

### Actual results

![Screen Shot 2024-06-28 at 10 34 09 AM](https://github.com/SoftFever/OrcaSlicer/assets/28265553/108d68a0-44b5-4308-afbf-0e10c2aceec2)

### Expected results

Run ORCA

### Project file & Debug log uploads

NA

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Anything else?

NA

**Comment by k3d3** [comment]
Your screenshots don't work. You might need to re-upload them.
