### ISSUE TITLE
Windows build fails using CMake 3.30

### ISSUE THREAD

**Issue by DavePutz** [SoftFever/OrcaSlicer#5916]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

Windows

### OS Version

Windows 10

### Printer

Any

### How to reproduce

After installing CMake 3.30; running build_release_vs2022.bat after a clean clone of OrcaSlicer will throw an error.
A similar error will be hit in VisualStudio 2022.
Using CMake 3.28 results in a correct build.

### Actual results

The following error is thrown:
```
  CMake Error at libs/numeric/odeint/CMakeLists.txt:15 (target_link_libraries):
    The link interface of target "boost_numeric_odeint" contains:
       Boost::mpi

     bn_nist.c
 
     but the target was not found.  Possible reasons include:
 
       * There is a typo in the target name.
       * A find_package call is missing for an IMPORTED target.
       * An ALIAS target is missing.
```
 

### Expected results

Build should complete.

### Project file & Debug log uploads

```
   CMake Error at libs/numeric/odeint/CMakeLists.txt:15 (target_link_libraries):
     The link interface of target "boost_numeric_odeint" contains:
 
       Boost::mpi
   bn_nist.c
 
     but the target was not found.  Possible reasons include:
 
       * There is a typo in the target name.
       * A find_package call is missing for an IMPORTED target.
       * An ALIAS target is missing.

```
### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Anything else?

This looks to be due to a deliberate change by CMake.
The 3.30 Release Notes list the Boost change at:
https://cmake.org/cmake/help/v3.30/release/3.30.html#deprecated-and-removed-features
With a description of the reason for the policy change at:
https://cmake.org/cmake/help/v3.30/policy/CMP0167.html#policy:CMP0167

**Comment by c2h5oh** [comment]
This is also a problem on Arch Linux.
