### ISSUE TITLE
Gcode go away to To infinity and beyond

### ISSUE THREAD

**Issue by Hectorajm2001** [SoftFever/OrcaSlicer#5920]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

Windows

### OS Version

Windows 11 Home

### Additional system information

CPU: i7 12th gen
GPU:3050ti laptop
RAM:16gb

### Printer

Ender 3 v3 se

### How to reproduce

IDK what i did
![image](https://github.com/SoftFever/OrcaSlicer/assets/143116877/6b22192e-e86c-4026-94f7-a13ad7fe957b)
i change the retraccion in mi TPU config, thats it
![image](https://github.com/SoftFever/OrcaSlicer/assets/143116877/11dbd9c6-1074-4334-87dd-2630ec4925d9)

### Actual results

The final slice gets bug

### Expected results

To infinity and beyond

### Project file & Debug log uploads

[Case bug.zip](https://github.com/user-attachments/files/16039027/Case.bug.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by jorgon** [comment]
I found this with the temp tower. I fixed it by setting the "Internal solid infill pattern" from "Monotonic" to "Concentric"
