### ISSUE TITLE
Internal structures not printing unless flipped

### ISSUE THREAD

**Issue by Hayvosh** [SoftFever/OrcaSlicer#5923]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

Windows

### OS Version

Win10

### Printer

Creality Ender 3 S1 Pro modified

### How to reproduce

1. Import STL with an internal structure that has a feature from the bottom, in my case a horizontal stabiliser from an airplane.
2. Place it on the bed the correct way
3. Slice it, it will not slice the internal structure where the carbon fiber spar will go
4. Flip the model 180 degress and slice it again, this time it will work.

### Actual results

![image](https://github.com/SoftFever/OrcaSlicer/assets/385028/45adfe1b-d756-4591-811f-f46915c55c44)
Here you can see the shape of the vertical hole structure in the middle where the carbon fiber spar will go.
![image](https://github.com/SoftFever/OrcaSlicer/assets/385028/1a9446e3-1595-4a6c-8fb2-97901ce52935)
Here you can see that it is not sliced with the feature.

![image](https://github.com/SoftFever/OrcaSlicer/assets/385028/ec155420-20ec-4c2e-92f6-893ec29bb19a)
Now when the model is flipped 180 degrees and sliced, you can see that the feature is sliced properly.

### Expected results

It should slice the features no matter the orientation

### Project file & Debug log uploads

[rudder.zip](https://github.com/user-attachments/files/16039371/rudder.zip)
[debug_Sat_Jun_29_10_04_00_133584.log.zip](https://github.com/user-attachments/files/16039376/debug_Sat_Jun_29_10_04_00_133584.log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by Ataraxia-Mechanica** [comment]
You have make overhangs printable which wrongly modified your models shape so the hole is gone. Also this model doesn't seem to need supports at all especially for the small holes.
