### ISSUE TITLE
Javascript error on startup

### ISSUE THREAD

**Issue by WZ9V** [SoftFever/OrcaSlicer#593]
![image](https://user-images.githubusercontent.com/8654919/227802522-d3b80ebd-a598-47c3-bc19-24c71e381c86.png)

This happens on Linux Mint 21.1

![image](https://user-images.githubusercontent.com/8654919/227802638-e0aea5f3-e85d-4f68-94aa-c907b4568a0d.png)

**Comment by ChaosBlades** [comment]
Duplicate of https://github.com/SoftFever/OrcaSlicer/issues/219
