### ISSUE TITLE
Reduce Max Y acceleration as Z position increases

### ISSUE THREAD

**Issue by mherbold** [SoftFever/OrcaSlicer#5931]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

With printers getting faster and faster, the acceleration of the print bed makes tall thin prints wobble / vibrate quite a bit.  We need to reduce down the max Y acceleration (note - not speed! speed is fine, leave it alone - it's acceleration that makes things wobble) as the print nozzle climbs up on Z.

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

Under the prepare tab, under process settings, under the speed sub-tab, under the acceleration settings group, add a "Y acceleration ramp-downs to" with the value being in mm/s^2 or a %, then also another related setting "Y acceleration ramp-down height" with the value being in mm.

The max Y acceleration for each layer should then be lerp( maximum_acceleration_y, y_acceleration_ramps_down_to, clamp( current_layer_z / y_acceleration_ramp_down_height, 0, 1 ) ) where maximum_acceleration_y is from the "motion ability" tab of the printer settings.

**Comment by czlr** [comment]
If you also wanted an immediate solution, this would be doable with some [on layer change] custom gcode.

For compatibility with variable layer height slicing, it might be slightly better to use the current layer Z vs. max Z rather than current LH vs. max LH.
