### ISSUE TITLE
FLSun S1 printer profile

### ISSUE THREAD

**Issue by Waffull** [SoftFever/OrcaSlicer#5936]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Not a problem so much as a needed profile.  Other FLSun printer profiles are available, but not the S1.

### Which printers will be beneficial to this feature?

Klipper

### Describe the solution you'd like

Please add profile for FLSun S1.  

Thank you.

### Describe alternatives you've considered

Starting with v400 profile...  But I couldn't find enough specs

**Comment by alexzogh** [comment]
S1 base profile for Orcaslicer is available directly from FLSUN here: https://wiki.flsun3d.com/en/OrcaimportS1configurationfile
unfortunately, I couldn't get it to load in the latest 2.1.1 - because its in Chinese?
