### ISSUE TITLE
Remove "Detect ovehang walls" option and use threshold

### ISSUE THREAD

**Issue by vovodroid** [SoftFever/OrcaSlicer#5947]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

"Detect overhang walls" has its own detection algorithm `m_lower_slices_polygons = offset(*this->lower_slices, float(scale_(+nozzle_diameter / 2)));`, interfering with **Reverse threshold** option and also affecting overhang speed, that has its own setting including "Classic mode" (does it necessary?).

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

Use **Reverse threshold** as common overhang detection method for **Reverse on even** and "**Extra perimeters on overhangs**".
Also it can be used for printing internal perimeters first on overhangs. I made such feature, but it also collides with **Detect overhang walls**

**Comment by tome9111991** [comment]
Btw.
i think "Extra perimeters on overhangs" works not very well, it is ported from Prusaslicer.
I have some issues. with superslicer no issue

Look at:
https://github.com/SoftFever/OrcaSlicer/issues/5706
