### ISSUE TITLE
Disable "Auto-record Monitoring" by default and store files on local computer

### ISSUE THREAD

**Issue by Alkerion** [SoftFever/OrcaSlicer#5950]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

The "Auto-record Monitoring" is turned ON by default.

This create a HUGE memory usage on the printer SD Card, something really unwanted.

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

The "Auto-record Monitoring" must be turned OFF by default.

The files must be stored on local computer, not on printer SD card.

Add an option to choose the file location.

**Comment by Alkerion** [comment]
32Gb on ipcam folder after 18h of print :
![image](https://github.com/SoftFever/OrcaSlicer/assets/34811376/d621f2df-8544-4cfe-b101-1726dc99cd09)

**Comment by Noisyfox** [comment]
You can turn that off via bambu handy or here
![image](https://github.com/SoftFever/OrcaSlicer/assets/1537155/76c05d96-062e-4ca6-8461-b6076017331a)

**Comment by Alkerion** [comment]
I know thanks, it's not the purpose of this ticket to learn how to turn it OFF.

**Comment by Noisyfox** [comment]
Then raise a ticket to BambuLab, not here.
