### ISSUE TITLE
wrong layer number in the preview

### ISSUE THREAD

**Issue by fegato** [SoftFever/OrcaSlicer#596]
**Describe the bug**
The slider doesn't show the right layer number, and is inconsistent on all the slider, 
if you move the bar of 1 layer the number raise by 2 or 5 or more, and at some point close to the top it's back to normal.

**Screenshots**
on the first screenshot you see number 750
![orca-1](https://user-images.githubusercontent.com/16136579/227998995-997e498c-2730-445e-a964-7e73f70f3033.jpg)
and the next show 264
![orca-2](https://user-images.githubusercontent.com/16136579/227999033-1201fd32-b373-47af-91d8-4f2e5a8aaa18.jpg)

**Printer model**
Bambu Lab X1 Carbon + AMS

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 1.5.0

**Comment by hliebscher** [comment]
for Mac M1 it works fine  OS 1.5.x
