### ISSUE TITLE
GCODE is not generated when you set the Auxiliary part cooling fan to 100% 

### ISSUE THREAD

**Issue by kaushikbm** [SoftFever/OrcaSlicer#5965]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

Windows

### OS Version

Windows 11/64-bit

### Printer

Creality K1

### How to reproduce

1. Goto to filament settings
2. Select cooling
3. Scroll down to **Auxiliary part cooling fan**
4. Set **Fan speed** to 100%
5. Save and exit dialog.
6. Now slice a object and save the GCODE to check if you can get a **M106 P2 S255**
7. But if you set the value to 99% you get **M106 P2 S252**

### Actual results

The auxiliary fan does not start at desired layer.

### Expected results

The fan should start at the desired layer and speed.

### Project file & Debug log uploads

[GCODE-Files.zip](https://github.com/user-attachments/files/16054205/GCODE-Files.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Anything else?

![image](https://github.com/SoftFever/OrcaSlicer/assets/5709898/27a346da-9edc-44c2-aed6-dcf97142e0db)

**Comment by kylek29** [comment]
I just tested, it seems to work for me (for X1C, so not the same printer).

I do know that PrusaSlicer & OrcaSlicer don't convert the values to 0-255 if using custom G-Code on those variables, are you using any of those? Example:

`M106 P2 S{additional_cooling_fan_speed[current_extruder]}`

With the value set at 100%, you'd think it'd output M106 P2 S255, but it outputs the literal 100. So it becomes M106 P2 S100.
