### ISSUE TITLE
Full calibration option

### ISSUE THREAD

**Issue by Salteedogg** [SoftFever/OrcaSlicer#5967]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

No, just frustrated having to do flow dynamics and flow rate calibration separately! 

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

Should have a full calibration option that allows calibration of flow dynamics first, then move up to do flow calibration next. This would shorten the total time from 30 minutes to just above 15 minutes! The bambu bed is plenty big enough to do 4 flow calibrations, and 4 flow dynamic calibrations all in the same session!

### Describe alternatives you've considered

Always have to do one at a time which takes twice as long considering the bed leveling time a long with all the other checks it has to go through!

**Comment by kylek29** [comment]
This is most likely something you'd want to post on https://forum.bambulab.com/c/bambu-lab-software/feature-requests/100 .
