### ISSUE TITLE
Bad slicing results

### ISSUE THREAD

**Issue by elektrofreakz** [SoftFever/OrcaSlicer#5972]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

Windows

### OS Version

Windows 10 home

### Additional system information

Intel(R) Core(TM) i5-2300 CPU @ 2.80GHz   2.79 GHz 16GB

### Printer

Bambu lab P1s

### How to reproduce

Slicing files gets stranger and stranger. Some weird faults happened the first thime. The second time slicing the model was completely broken

### Actual results

![Knipsel](https://github.com/SoftFever/OrcaSlicer/assets/37225664/58f60408-1a1d-40bc-857f-8ce6de3c9cf9)

### Expected results

Clean sliced model

### Project file & Debug log uploads

[weird model.zip](https://github.com/user-attachments/files/16057715/weird.model.zip)
[log.zip](https://github.com/user-attachments/files/16057765/log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by foreachthing** [comment]
Set your Z-Offset value back to zero:
![image](https://github.com/SoftFever/OrcaSlicer/assets/10420187/f5359ba9-2199-4c28-ab6a-ce414c2993d2)
