### ISSUE TITLE
"Can't add prime tower if variable layer height is not the same"... but variable layer height is not active

### ISSUE THREAD

**Issue by Arakon** [SoftFever/OrcaSlicer#5978]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

Windows

### OS Version

Win 11

### Printer

Bambu A1

### How to reproduce

- Load the project file
- Note the error message

### Actual results

![image](https://github.com/SoftFever/OrcaSlicer/assets/12016360/468e147d-35ba-42a5-9e0a-e7d8edada507)

### Expected results

It should slice as no variable layer height is selected. Manually resetting layer height also seems to make no difference. This might be related to this issue in original BS code: https://github.com/bambulab/BambuStudio/issues/3641

### Project file & Debug log uploads

[A1toolBOX (1).zip](https://github.com/user-attachments/files/16061718/A1toolBOX.1.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by DBendit** [comment]
I'm running into the same issue (on the same project file, funnily enough). Notably, it loads fine in Bambu Studio v1.9.3.50, which backs up the theory that it's related to the linked upstream issue.

**Comment by 53Aries** [comment]
I have this issue if I'm using a layer height modifier on a print with multiple parts of different colors.

**Comment by adminmat** [comment]
Having the same issue today. Tried aligning the layer heights still erroring. Orca 2.1.1

**Comment by pm0u** [comment]
This is still happening to me on 2.3.1, it appears someone noted it happening upstream on 2.3.0 - not sure if this is related to that or something else in orca.

If all objects on the plate are the same it seems to work. If there is a different object somewhere in there, it fails - even if the modified height and settings are the same across all objects on the plate.
