### ISSUE TITLE
SBS filament type

### ISSUE THREAD

**Issue by AbrieViljoen** [SoftFever/OrcaSlicer#5980]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

No SBS filament type to select from the "Type" dropdown under Basic information section of Filament settings.

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

Under Filament settings menu, on the Filament tab in the Basic Settings area where it says "Type", could an option please be added for "SBS" filament type ?

**Comment by AbrieViljoen** [comment]
If possible also add "PLA+"

**Comment by dgauche** [comment]
@AbrieViljoen I have added SBS for Bambu printers and will soon create a pull request for that.

Please let me know what printers you have.

**Comment by dgauche** [comment]
@AbrieViljoen see pull request [here](https://github.com/SoftFever/OrcaSlicer/pull/6278).

**Comment by AbrieViljoen** [comment]
> @AbrieViljoen I have added SBS for Bambu printers and will soon create a pull request for that.
> 
> Please let me know what printers you have.

Thanks for helping with this request. I have the Creality K1C and a Creality V3 KE. Can you also add the PLA+ profile for these two printers?

**Comment by dgauche** [comment]
Hi @AbrieViljoen this pull request should allow you to create your own custom filaments based on SBS.

![Screenshot 2024-07-28 at 21 19 28](https://github.com/user-attachments/assets/2b7fd523-0a30-474b-9e2b-8ceb924f2229)

I will add SBS to more printers as soon as I have some time.

I am however not sure that it makes sense to have PLA+ as a separate filament.  It is after all just PLA with some additives. If you start adding PLA+ then perhaps PLA-HF (High flow) should also be added?

Does your settings for PLA vs PLA+ change significantly?

From a user experience I can see that it makes sense to be able to select the exact filament type that you have, but it may have the opposite effect by overwhelming users with too many filaments and there is no material difference between them.
