### ISSUE TITLE
Manual preparation time

### ISSUE THREAD

**Issue by Lardram** [SoftFever/OrcaSlicer#5997]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I use a printer that runs on Klipper, so all my preparation goes under the print_start macro, it would be nice to be able to say to the slicer “this is how much it will take to start", so it don't show 1s after slicing.

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

 I know nothing about programming, but seeing this is already implemented in the multimaterial section where you can tell the slicer how much it takes to load and unload the filaments, and it calculates it pretty good using that.

### Additional context

![Captura de pantalla 2024-07-02 215842](https://github.com/SoftFever/OrcaSlicer/assets/89814148/c0c22067-6bae-4b39-9427-0ad67a35f67f)

**Comment by chimcen** [comment]
Bump this...

**Comment by DeepReef11** [comment]
Should Klipper provide that preparation time?
