### ISSUE TITLE
Tree support crosses into model

### ISSUE THREAD

**Issue by lin-ycv** [SoftFever/OrcaSlicer#5999]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

Windows

### OS Version

Windows 11 22621.3810

### Printer

FLsun V400

### How to reproduce

1. Open project file
2. change printer to flsun v400
3. slice

### Actual results

![image](https://github.com/SoftFever/OrcaSlicer/assets/60565737/04f83ca3-a979-4f3d-8d26-a343eec264aa)

### Expected results

supports to be generated without crossing into model

### Project file & Debug log uploads

[SubCompactSimpleGenericv3.zip](https://github.com/user-attachments/files/16076932/SubCompactSimpleGenericv3.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by foreachthing** [comment]
Your project does not slice with tree supports...
But, to solve your issue; You have to "assemble" all the parts that are interfering with supports of other parts.
Easiest solution: Assemble all the parts. Done.

**Comment by lin-ycv** [comment]
@foreachthing while that does work, assembling parts together mean i can't use exclude object feature. I do think the slicer should be able to know if supports are coliding with prints without assembling?

Here's the proper project with tree support
[SubCompactSimpleGenericv3_withTrees.zip](https://github.com/user-attachments/files/16233673/SubCompactSimpleGenericv3_withTrees.zip)
