### ISSUE TITLE
Filament Shrinkage Variant affects Multi Color Printing Walls

### ISSUE THREAD

**Issue by HEROofTIME1337** [SoftFever/OrcaSlicer#6013]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

Windows

### OS Version

11

### Printer

Bambu Lab P1s w/ AMS

### How to reproduce

When slicing a multi color model while the selected base filament has a Shrinkage modifier of <100%, colored walls will lose their color. Shrinkage increases the size of the model prior to slicing in order to compensate for filament shrinkage. The below model is has gray filament selected with several faces painted black. 
![Screenshot 2024-07-03 182132](https://github.com/SoftFever/OrcaSlicer/assets/174667571/37bf9c5e-f792-4e1a-af49-f99d1e24944c)

### Actual results

The model sliced with the gray filament on a Shrinkage modifier of 99.8% and black filament on 99.6%. As you can see the grey walls have overridden the black walls.
![Screenshot 2024-07-03 182112](https://github.com/SoftFever/OrcaSlicer/assets/174667571/0baccd1a-c9e6-48a2-972c-e227eff4cebb)

### Expected results

When sliced with both filaments on 100% Shrinkage (default), black walls are generated normally. 
![Screenshot 2024-07-03 182218](https://github.com/SoftFever/OrcaSlicer/assets/174667571/7c78de32-822b-47d3-bb36-0d0eecd06c99)

### Project file & Debug log uploads

[Barbette and ELX - Barbette.zip](https://github.com/user-attachments/files/16092303/Barbette.and.ELX.-.Barbette.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Anything else?

I suspect it has top do with the object scaling larger and covering the coloring. As if the color mask isn't scaling with the object. Only affects walls because Shrinkage is an XY only scaling, not Z.

**Comment by fenhelix** [comment]
Also having this issue on MacOS with @SoftFever 
![Screenshot 2024-07-07 at 6 21 30 PM](https://github.com/SoftFever/OrcaSlicer/assets/7648262/9cb0f96b-dc92-4d76-a8ea-fa14453f1ae2)
![Screenshot 2024-07-07 at 6 21 33 PM](https://github.com/SoftFever/OrcaSlicer/assets/7648262/87b8dc8e-80dc-4ef0-8734-f6c39dd391c2)
[[a]_MFNano_Remix_Cartridge_Lid_Multibody_Logo.3mf.zip](https://github.com/user-attachments/files/16121112/a._MFNano_Remix_Cartridge_Lid_Multibody_Logo.3mf.zip)

**Comment by igiannakas** [comment]
For now disable shrinkage compensation. There is a fix in the works that would attempt to apply scaling to the model as per the latest Prusa release as well but for now, disable shrinkage compensation for multi colour prints and rescale the object manually.
