### ISSUE TITLE
The distance Support/objet xy distance affects to interface objet distance

### ISSUE THREAD

**Issue by amzaldua** [SoftFever/OrcaSlicer#6014]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

macOS

### OS Version

macOS Sonoma 14.5

### Printer

Bambu Lab A1 series

### How to reproduce

In a PLA objet:
1. Go to "Process/Global/Support"
2. Go to "Filament for Support" and define the  "Support raft/interface" like PVA filament
3. Accept the emergent window
4. Slice the plate.

### Actual results

The distance between the interface and the objet is no zero.

### Expected results

I need the distance between the interface and the object to be zero and the distance between the support body and the object to be 0.35mm. The only way to achieve this is by setting the “Support/object XY distance” to zero as well, but if I do that, the support sticks to the object. The correct setup should be a zero distance between the object and the support interface and a 0.35mm distance between the support body and the object.
Would it be possible for the “Support/object XY distance” parameter to not affect the interface/object distance, or to add a new parameter named “Interface/object XY distance”?
<img width="1028" alt="Captura de pantalla 2024-07-04 a las 8 56 24" src="https://github.com/SoftFever/OrcaSlicer/assets/116205677/61948335-dd19-475b-bbde-ca9a43ba9100">
<img width="1009" alt="Captura de pantalla 2024-07-04 a las 8 56 10" src="https://github.com/SoftFever/OrcaSlicer/assets/116205677/c0f12e35-ced4-448d-9281-0d6810fe0794">

### Project file & Debug log uploads

[Puentes y Voladizos v2.3mf.zip](https://github.com/user-attachments/files/16095382/Puentes.y.Voladizos.v2.3mf.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by movinimage** [comment]
Hi! I believe the issue you are raising is the same one that I brought up last year. It is a feature that exists in prusa slicer. It would be great if it were added. 

issue I made: https://github.com/SoftFever/OrcaSlicer/issues/2162
