### ISSUE TITLE
Solid infill line in the air affects bridging

### ISSUE THREAD

**Issue by vovodroid** [SoftFever/OrcaSlicer#6017]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

Windows

### OS Version

Win10x64

### Printer

Custom

### How to reproduce

Slice attached project (two walls, no infill)

### Actual results

For whatever reason solid infill line is added to the wall:

![image](https://github.com/prusa3d/PrusaSlicer/assets/8691781/1d948069-2334-4d7b-a93e-59581a19bb3c)

And bridge on the next layer fails to connect to the same wall:

![image](https://github.com/prusa3d/PrusaSlicer/assets/8691781/a73abdb9-185f-4180-a422-6a01f6a05744)

The same happens in Prusa and Bamboo.

### Expected results

Bridge is attached to wall itself.

### Project file & Debug log uploads

[Shape-Box-orca.zip](https://github.com/user-attachments/files/16100941/Shape-Box-orca.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by Ataraxia-Mechanica** [comment]
relevant: https://github.com/SoftFever/OrcaSlicer/issues/5639

**Comment by vovodroid** [comment]
Probably, but I don't understand why put this line. Regular bridge to wall connection works good.

**Comment by Ataraxia-Mechanica** [comment]
On my machine with this line the bridge can be printed at a higher speed, otherwise it would fail to connect and just fall down, unless printed much slower.

**Comment by vovodroid** [comment]
Probably it allows faster bridging on some cases, but in other it causes bridging to fail completely

**Comment by Ataraxia-Mechanica** [comment]
Since you are using 0.6 nozzles, can you try disabling thick internal bridges? Might be related since it makes bridges as high as the nozzle width

![image](https://github.com/SoftFever/OrcaSlicer/assets/111327195/f8c50b90-7476-4a57-abd0-85c007503f76)

**Comment by vovodroid** [comment]
Project attached to bug is just example. Real model was printed with thick bridges off

![image](https://github.com/SoftFever/OrcaSlicer/assets/8691781/55d0e05e-bb32-4696-bedc-84ecf1b18d4a)

**Comment by Ataraxia-Mechanica** [comment]
Might not be related to my problem of #5639 after all, since my problem is the solid infill itself not sticking and yours is solid infill preventing bridges from sticking.
Also your bridging speed might just be too high for 0.6 nozzles? In the example you posted the speed was 45mm/s and cooling might not be strong enough.

**Comment by vovodroid** [comment]
> my problem is the solid infill itself not sticking and yours is solid infill preventing bridges from sticking.

Actually the first causes the later. I just saw failed bridge.

**Comment by Ataraxia-Mechanica** [comment]
lol, writing a new issue right now suggesting a new feature that would also fix it not sticking, soon™
