### ISSUE TITLE
Unable to export any configurations on a Mac due to a graphics/color issue (i.e. Checkboxes not showing)

### ISSUE THREAD

**Issue by dderbidge** [SoftFever/OrcaSlicer#6019]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.0

### Operating System (OS)

macOS

### OS Version

macOS 11.7.10 (Big Sur)

### Additional system information

MacBook Pro (Retina, 15-inch, Late 2013)

### Printer

Klipper

### How to reproduce

I have been trying to figure this out how to export configurations for a few days now. It appears as though you can't export the config bundles because the dialog box wasn't showing any checkboxes to select. This happens when macOS dark mode is enabled. 

Turn on macOS dark mode
1. Go to the Apple menu
2. Click System Preferences
3. Click General
4. In the Appearance section, click Dark

Open OrcaSlicer:
1. Go to the File menu
3. Go to the Export submenu
5. Click "Export preset bundle"
6. Choose any of the options; I selected "Process presets(.zip)"

### Actual results

At this point, you should notice that there are no visible checkboxes. For me, I didn't know that there should be a checkbox so I tried to click OK. Doing that causes an error message to appear, which says "Please select at least one printer or filament".

All in all, the way the UI looks makes me think that the dialog is cropping off content in the shaded area below (where the nozzle is listed), thus it appears that I'm not allowed to select the nozzle config in that section since it looks like it was cropped because of the way the background is highlighted for just the one line.

The colors need to be adjusted so that the checkbox is visible. I found that I needed to hover the mouse over the checkbox. It would also help, though, if the highlight/hover color were to activate when you hover your mouse over the words next to it.

### Expected results

The checkbox should be visible so you know that it can be clicked. The outline color for any checkboxes should be a different color than the background color.

### Project file & Debug log uploads

N/A

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Anything else?

This file shows the 'invisible' checkbox:
<img width="681" alt="export configs" src="https://github.com/SoftFever/OrcaSlicer/assets/5893335/514495ba-db8b-48a5-85e8-210931b4efa4">

This shows what the user does when they see no checkbox (when they assume that they can simply export what they selected):
<img width="637" alt="clicking ok" src="https://github.com/SoftFever/OrcaSlicer/assets/5893335/1345d41a-2904-459f-b861-2ba7516c7043">

When the mouse hovers over the checkbox, it looks like this:
<img width="681" alt="mouse hovering over the checkbox" src="https://github.com/SoftFever/OrcaSlicer/assets/5893335/4ca672a6-f45d-433a-b525-e814af31c230">

After the checkbox is selected, it is checked and looks fine:
<img width="681" alt="clicked on the checkbox" src="https://github.com/SoftFever/OrcaSlicer/assets/5893335/e9e17f69-5e6a-46c4-9e7f-9bd5069e8e66">

**Comment by AndreaPro** [comment]
Experienced the same issue with Mac and Linux
