### ISSUE TITLE
Strange, unnecessary travel moves ?

### ISSUE THREAD

**Issue by Ergonomicmike** [SoftFever/OrcaSlicer#6024]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

v2.1.1 portable

### Operating System (OS)

Windows

### OS Version

Win10

### Printer

Klipperized Ender 3 v2

### How to reproduce

Import my Project file
Slice
In the Preview, scrub the toolhead along the first layer

### Actual results

This is not a problem, per se, in the sense that the print prints okay. (Although I could argue that maybe there's some unnecessary oozing caused by the delay during unnecessary travel.) It's more of a puzzle.

But you'll see the tool head move to the front (right) of the zip tie a couple of times. It doesn't appear to flow anything.

### Expected results

No unnecessary travel moves.

### Project file & Debug log uploads

[Strange travel moves.Orca github.ZipTie..zip](https://github.com/user-attachments/files/16104375/Strange.travel.moves.Orca.github.ZipTie.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Anything else?

I've noticed unnecessary travel moves before in some of my other prints. But here it seems the worst. So I post it as an example.

I think this only happens on the first layer. Or maybe that's because I'm usually only watching the first layer?

**Comment by Ataraxia-Mechanica** [comment]
You have avoid crossing walls set to 0, so the toolhead wouldn't travel across infill regardless of how long the travel move would be. Set it to something like 40mm could solve the problem.
![image](https://github.com/SoftFever/OrcaSlicer/assets/111327195/f23b9e2b-58ad-4369-8fee-d3253eec3385)

**Comment by Trydnt** [comment]
This is still occuring in 2.2.0, specifically it seems that system cannot easily find the nearest point in the  next loop and so often makes strange travels to other side  of the object before continuing. Terrible stringing.

**Comment by 3d-olympics** [comment]
I get this as well. In Cura there's an "optimize wall printing order" setting, which helps minimize travel by having the toolhead print nearby walls first.

**Comment by Sangra6969** [comment]
I can tell you that the dragging is horrible, and I use the Z  Hop correctly. My prints get layer shifts because of it. I am going to try to do an extreme Z Hop and see what happens.
