### ISSUE TITLE
OrcaSlicer crash on bambulab calibratión dynamic flow if method is "pattern"

### ISSUE THREAD

**Issue by Disttrack** [SoftFever/OrcaSlicer#6028]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

Windows

### OS Version

Windows 11

### Additional system information

CPU: Ryzen 5 5600X
RAM: 32GB
GPU: RTX 3070 ti

### Printer

Bambulab P1S

### How to reproduce

1. Go to Calibration
2. Go to Flow Dynamics
3. Go to Manual Calibratión
4. In method, select pattern

![image](https://github.com/SoftFever/OrcaSlicer/assets/66384045/5d60365e-58ae-4b2e-87f5-7b5755b62421)

### Actual results

OrcaSlicer crash with "Unhandled unknown exception; terminating the aplication".
![image](https://github.com/SoftFever/OrcaSlicer/assets/66384045/ca00c16c-20dc-41be-b447-8d9fd4a8dcb1)

### Expected results

Send calibration to printer

### Project file & Debug log uploads

[logs.zip](https://github.com/user-attachments/files/16107481/logs.zip)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by rmcfadzean** [comment]
I'm also encountering this issue on Linux. Pattern crashes before anything gets sent to the printer but Line works just fine.

### OrcaSlicer Version
2.1.1

### Operating System (OS)
ArchLinux

### OS Version
Linux soba 6.9.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 28 Jun 2024 04:32:50 +0000 x86_64 GNU/Linux

### Additional system information
CPU: i9-13900H
RAM: 32GB
GPU: RTX 4070 / Raptor Lake-P (Iris Xe Graphics)

### Printer
Bambulab A1 Mini

**Comment by Mrroot3r** [comment]
I have been having this issue for a few versions now as well, I want to say it used to work but Im not sure if I always used pattern over line.

OrcaSlicer Version

2.1.1
Operating System (OS)

Windows
OS Version

Windows 10
Additional system information

CPU: Ryzen 5 5900X
RAM: 32GB
GPU: RTX 3090

Printer

Bambulab P1S

**Comment by Hammerfest** [comment]
Can confirm, having this issue with the A1 Mini + AMS Lite
Does with all nozzle sizes, havent tested anything but textured bed.
Also tried different options for values, still crashing.

**Comment by jaeitee** [comment]
Confirming this issue here as well when choosing Pattern for the calibration.
Mac OSX 14.4, MacBook Pro M2 Max, Orca 2.1.1, Bambu Lab P1S + AMS.

Error log:

> [warning]	2024-07-22 13:03:41.422155[Thread 0x00000001ea527ac0]:01:03:41 pm: Error: OrcaSlicer got an unhandled exception: ConfigOptionFloatOrPercent: Assigning an incompatible type
> [error]	2024-07-22 13:03:41.422175[Thread 0x00000001ea527ac0]:Uncaught exception: ConfigOptionFloatOrPercent: Assigning an incompatible type

**Comment by PiotrKrzyzek** [comment]
Same issue here. This has been happening since the last major version, and today I downloaded the new 2.2.0-beta and the issue persists there too.

I likewise think that there are a few related GitHub issues that are more or less the same thing and that can be merged together for easier tracking: 

https://github.com/SoftFever/OrcaSlicer/issues/6249
https://github.com/SoftFever/OrcaSlicer/issues/6128

Maybe others as well.

**Comment by aarbmx6s** [comment]
The same issue.
OS: macOS Sonoma 14.14.1 
OrcaSlicer Version: 2.1.1
