### ISSUE TITLE
AMD Adrenalibe 24.6.1 blackscreen

### ISSUE THREAD

**Issue by robertbigk** [SoftFever/OrcaSlicer#6029]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

Windows

### OS Version

11 23H2 22631.3447

### Additional system information

Onexplayer x1 155h

### Printer

Bambu Lab P1S

### How to reproduce

Install drivers AMD Adrenaline 24.6.1 BlackScreen
Install drivers AMD Adrenaline 24.5.1 No issue

### Actual results

Install drivers AMD Adrenaline 24.6.1 BlackScreen

![orca-slicer_Zgspqta6us](https://github.com/SoftFever/OrcaSlicer/assets/34956477/2b54d95b-4fe4-4e69-aefc-96336ee218c0)

### Expected results

Install drivers AMD Adrenaline 24.5.1 No issue

![orca-slicer_1NgedoQcLd](https://github.com/SoftFever/OrcaSlicer/assets/34956477/f7cc315f-1c02-4bc9-a6dc-dd8364111df0)

### Project file & Debug log uploads

[crash_Tue_Jul_02_00_15_58_0.log](https://github.com/user-attachments/files/16107670/crash_Tue_Jul_02_00_15_58_0.log)

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Anything else?

I write on forum amd no replythe

**Comment by arklan** [comment]
Seeing this in prusaslicer and blender as well, so likely not specific to orca slicer.
