### ISSUE TITLE
[Feature Request] Add X-Y hole compensation on object/parts/modifier level

### ISSUE THREAD

**Issue by Launert** [SoftFever/OrcaSlicer#603]
**Is your feature request related to a problem? Please describe.**
For multi material printing, different X-Y hole compensation values are needed for perfect accuracy for all parts.

**Describe the solution you'd like**
Add X-Y hole compensation to the object view within Orca Slicer to allow different parts of the model to have different settings.
![grafik](https://user-images.githubusercontent.com/47757241/228321744-3cbc881d-af0b-4dcd-b5a9-f1ea6ca094c1.png)

**Describe alternatives you've considered**
Shrinkage compensation on filament settings is a good step, but doesn't help if the outer dimensions of the object are already good.

**Additional context**

**Comment by aleung** [comment]
I see this option in 1.6.2 Linux version.

But the X-Y hole compensation seems to be wrong. The description says "Positive values make holes bigger" but actually positive value makes holes smaller.

![image](https://user-images.githubusercontent.com/271538/236675967-9aeff7de-9f7d-4293-b4d9-72e3d84dc6c5.png)

**Comment by knw257** [comment]
I would also like this feature, to be able to edit the X-Y hole compensation on only part of a model, rather than the whole thing.

@aleung While you can change the X-Y hole/contour compensation at the part level, adding a modifier object to a part does not give this option. I believe this is what OP was requesting, and what I would like to see as well

**Comment by knw257** [comment]
Bump

**Comment by TexZeTech** [comment]
Just went to use the modifier object to tweak the size of one hole and found this to not be there, looking forward to when this feature is added.
