### ISSUE TITLE
2.1.0/2.1.1 are not stable on windows 10

### ISSUE THREAD

**Issue by demosthenes384322** [SoftFever/OrcaSlicer#6031]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

Windows

### OS Version

windows 10

### Additional system information

i7 4790k, gskill ripjawz 8gb ddr3, msi gtx960

### Printer

bambu p1s ams

### How to reproduce

When adding text that is flush with the surface instead of embossed or debossed filament change/colors do not apply at all during slicing. Also crashes frequently. Also when saving, starting with 2.1.0, it will not save to the file that is open, it will only save a duplicate of the 3mf imported into the project.

### Actual results

Flush text does not appear in the final slice as a color change/different color. Saves to a duplicate 3mf of the imported file instead of saving to the current project. Also crash frequently. All issues start with 2.1.0

### Expected results

Should save to the project that is currently open, should handle color changes correctly for flush text.

### Project file & Debug log uploads

![prepare tab view text color error](https://github.com/SoftFever/OrcaSlicer/assets/16627381/7d8b5332-7b43-4f59-98b9-d6dc0ed10614)
![sliced output text color error](https://github.com/SoftFever/OrcaSlicer/assets/16627381/f3772976-c0ac-4762-b2e2-b67966249e46)
![file duplication screenshot](https://github.com/SoftFever/OrcaSlicer/assets/16627381/a4e2436d-5f6d-40f1-b706-116fafe900ee)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by kylek29** [comment]
I triggered this crash the other day, I'll see if I can do it again to grab the logs.
