### ISSUE TITLE
Mk3s profiles: Bad default settings

### ISSUE THREAD

**Issue by Phatcat** [SoftFever/OrcaSlicer#6037]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

If you come from Prusa and you pick one of the standard mk3s profiles for your original prusa mk3s+ then the profile settings are off.
I am not just talking the more trivial stuff like the amount of walls, line and wall width, infill pattern and infill %, no, I am talking about g-code resolution, layer height limits and speed settings. Settings which most people shouldn't be touching, especially people who don't know what they are doing. Why do these values differ from the official profiles in prusa slicer? It is not for better results, nor it is for the longevity of the printer, so why do these settings differ? And why are they different by default for the worse?

I've had to make custom profiles for everything (The printer, the slicing profile, the filament even), just to get it as close to 'original OEM settings' as possible.. And even after painstakingly trying to manually transfer all the settings, there's still about a 1 hour difference between slicing the same plate on the 2 different slicers, with orca coming out the fastest (and I fear it will be to the detriment of the print quality)

### Which printers will be beneficial to this feature?

Marlin

### Describe the solution you'd like

Match the profiles from orca to the official profiles from prusa (as much as possible) - This goes for the whole settings stack (Printer, filament, slicer). ALL profiles are off.

Also Prusa ditched the 'standard' naming some time back, so for .4 nozzles with a .2 layer height they're called 'speed' and 'quality' now, where orcas calls them 'speed' and 'standard' (and has them in the wrong order).

### Describe alternatives you've considered

Accept that the profiles are mismatching with prusa and have horrible print results with orca on an original mk3s+ before you start tinkering - blobbing and failed prints gallore - Which will drive away some of the more novice users who may never come back.

### Additional context

I can provide screenshots by request but this is very easy to confirm. Just compare the profiles in Prusa with the profiles in Orca.

**Comment by pedjas** [comment]
I was considering using OrcaSlicer. Treatment of this issue made me change my mind.
