### ISSUE TITLE
Allow choosing incompatible presets

### ISSUE THREAD

**Issue by vovodroid** [SoftFever/OrcaSlicer#6041]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

If project with embedded presets is open

![image](https://github.com/SoftFever/OrcaSlicer/assets/8691781/06ace4fd-89c1-4278-94b5-2dc9e3b283ca)

and then printer profile changed other profile/printing preset can't be chosen.

![image](https://github.com/SoftFever/OrcaSlicer/assets/8691781/e6db4a69-fee8-48ac-8449-06eb6fee8bf1)

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

Add button/option to allow choosing any existing preset.

**Comment by discip** [comment]
@vovodroid
Instead of _'Allow chosing uncompatinle presets'_ you most likely meant:

**`Allow choosing incompatible presets`**
