### ISSUE TITLE
UI: Wrong options while mirroring the part.

### ISSUE THREAD

**Issue by JaCKoP619** [SoftFever/OrcaSlicer#6047]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

Linux

### OS Version

Ubuntu 24.04

### Additional system information

irrelevant

### Printer

irrelevant

### How to reproduce

get any part
Try mirroring it with right click (i couldn't make a screenshot while at right click menu)
you for what i see, the mirroring options text is reversed, mirror along X axis is along Y and vice versa.  The icon is OK 

### Actual results

everything related is okey, it's just reversing those texts.

### Expected results

everything related is okey, it's just reversing those texts.

### Project file & Debug log uploads

irrelevant

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by gautaz** [comment]
Hello, I can confirm that the issue still exists on version 2.3.2.

**Comment by gautaz** [comment]
> Hello, I can confirm that the issue still exists on version 2.3.2.

Looking back a bit more carefully at the UI, "Along X Axis" means mirroring by using the X axis normal plane.
So both option texts are OK and the bug seems invalid or was fixed in the meantime.

@W0lsZcZ4n Have these option texts been modified between version 2.1.1 and version 2.3.2?
