### ISSUE TITLE
Orca rename gcode files sent to the SD card "qidi-max-advanced-spool-holder-sys..."

### ISSUE THREAD

**Issue by bastus1986** [SoftFever/OrcaSlicer#605]
**Describe the bug**
Orca rename gcode files sent to the SD card "qidi-max-advanced-spool-holder-sys..." This is regardless of model or what I edit the name to before sending. The file briefly shows up under the correct name while it is uploading to the printer, ass soon as ity hits 100% and the thumbnail loads it changes to "qidi-max-advanced-spool-holder-sys..." It also happens ion Bambu Lab Studio but it only started after installing Orca

**3mf File for This Bug**
[adjustable-spool-holder-for-silica-gel-bottom-1_PLA_10h17m.zip](https://github.com/SoftFever/OrcaSlicer/files/11097294/adjustable-spool-holder-for-silica-gel-bottom-1_PLA_10h17m.zip)

**To Reproduce**
slice then send sliced gcode file to printer

**Expected behavior**
The name I choose or Orca assigned to the file should be displayed on the printer, 

**Screenshots**
![Screenshot 2023-03-29 014122](https://user-images.githubusercontent.com/36938793/228447828-99a15c5c-74ee-411d-bd78-e55856ed769b.png)
![Screenshot 2023-03-29 014105](https://user-images.githubusercontent.com/36938793/228447832-4d80d6e8-a37c-44d0-aa6f-9285317f513a.png)

**Printer model**
Bambu XC1

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Windows] Windows 11

**Comment by SoftFever** [comment]
Hi @bastus1986 ,
Orca slicer won't affect BambuStudio in any form.
This change is certainly caused by changes on Bambu cloud or firmware.
You might want to raise a ticket there.
