### ISSUE TITLE
Raft: Doesn't always print perimeter first when using tree supports

### ISSUE THREAD

**Issue by ReinhardC** [SoftFever/OrcaSlicer#6054]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

Windows

### OS Version

Windows 11

### Additional system information

CPU: AMD Threadripper, probably not important for this issue

### Printer

BambLab A1 Mini

### How to reproduce

1) New Project (Bambu Lab A1 Mini, Textured PEI Plate, 0.2mm Standard @BBL A1M)
2) Add Benchy Model
3) Activate Supports (Tree `Hybrid`, `Strong `or `Slim` - - - Tree `Organic` causes no issue!)
4) Set Raft Layers to 2
5) Slice, observe first layer printing order

### Actual results

For some of the raft islands, Orca prints the inside of the islands first, then the perimeter. This can cause print failures because the raft sometimes comes off the build plate when quickly changing directions when it can't attach to the perimeter.

### Expected results

Print the outline of each island/all the islands first 

### Project file & Debug log uploads

Very easy to reproduce, so probably no log/project required?

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Anything else?

![grafik](https://github.com/SoftFever/OrcaSlicer/assets/28957452/ba5eace9-fdb8-4b48-94f6-75f4afd7838a)

**Comment by Saylux** [comment]
PLEASE FIX THIS! This has caused me constant pains and headaches for years! this is the biggest reason I hate orca slicer versus cura. I wish all the new good printers used Cura instead of this half baked software.
