### ISSUE TITLE
Add Flow Rate Cube Calibration

### ISSUE THREAD

**Issue by morgan55555** [SoftFever/OrcaSlicer#6057]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Sometimes when some filaments I'm struggling to determine, which flow rate is the best.
When this happens, I usually do cube Flow Rate Calibration, [like this](https://3dprintbeginner.com/flow-rate-calibration/).
It will be great to add this type of calibration to Orca.

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

Add Hollow Cube Flow Rate Calibration to Orca.

**Comment by kylek29** [comment]
Just for clarity, do you want just the cube or the cube + the calculator? 

I think a lot of the simple calibration models (e.g. they don't require a bunch of scripting/math) could probably be handled in one swoop if the Shape Gallery is ported from the newer versions of PrusaSlicer. It acts like the right-click menu, but queries a folder in the PS folder and the user profile folder (called "shapes" iirc) to import frequent models the user wants.
