### ISSUE TITLE
Viewing the mesh in Paint mode

### ISSUE THREAD

**Issue by Kyrian-29** [SoftFever/OrcaSlicer#607]
[Feature request] When using "Paint" with the "Triangle" tool, have the possibility to visualise the mesh of the part to be coloured.

**Comment by SoftFever** [comment]
Can you elaborate more? 
Screenshots or recordings are helpful

**Comment by Kyrian-29** [comment]
Trimming with the triangle tool is not easy without being able to clearly see the mesh (the triangles).
![Sans titre 01](https://user-images.githubusercontent.com/126974661/228888873-609bf93b-efe8-4ded-94f6-c1596eeb8c78.jpg)

A view of the mesh like with NetFab for example would be easier to do a perfect trimming.
![Sans titre 02](https://user-images.githubusercontent.com/126974661/228889196-02b62e73-9727-431f-bf2d-afb7fbe6c716.jpg)

**Comment by cybrsage** [comment]
I third the request, and second the thanks!!!

**Comment by Noisyfox** [comment]
BBS used to have this feature but then they decided to disable this due to some macOS performance issue:

https://github.com/bambulab/BambuStudio/commit/8b5a49f37870b25623d75336d46065653bd645cc
