### ISSUE TITLE
Add the option to select which filament is used for flow calibration in multi-filament prints

### ISSUE THREAD

**Issue by kvnper** [SoftFever/OrcaSlicer#608]
[Note: I raised this same issue in the official slicer, but will repost here just in case - ignore if not acceptable]

Please add the option to select which filament is used to calibrate filament flow.

I have a project where I am using a different material for the supports, and I'm also using a raft with that material because the contact area of the part to the bed is minuscule. The issue I am having is that the support filament is being used as the flow calibration filament.

Please see the photo below, where the yellow filament is the support material and is being used for filament flow calibration:

![image](https://user-images.githubusercontent.com/47488385/228731759-a918c556-8ec5-455c-ba42-6f6caabacd75.png)

**Comment by kvnper** [comment]
No luck with that unfortunately. My workaround at the moment that works for me is just to print a flat cube with the main filament in order to get auto calibration.

caption: filament 2 is still used, settings included in screenshot
![image](https://user-images.githubusercontent.com/47488385/228809864-4188e2b7-ef67-4414-97aa-73aa9d84ad89.png)

**Comment by SoftFever** [comment]
It looks like no black material is used for the first layer, which may explain it.
But yeah, a small sacrifice block should do the trick.(You can make it only 1 layer high to save filament)
