### ISSUE TITLE
Calibration - Pressure Advance

### ISSUE THREAD

**Issue by RTGRDH** [SoftFever/OrcaSlicer#6082]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

macOS

### OS Version

macOS Sonoma Version 13.6.7

### Printer

Two Trees Sapphire Pro (SP-3) Modified

### How to reproduce

Calibration -> Pressure Advance -> any Extruder Type -> PA Tower or PA Pattern

### Actual results

<img width="470" alt="Screenshot 2024-07-10 at 09 34 21" src="https://github.com/SoftFever/OrcaSlicer/assets/58370642/056717d3-5f07-4e95-ac9c-52424fde548b">
![IMG_1090](https://github.com/SoftFever/OrcaSlicer/assets/58370642/8dd1d7ad-21be-4e45-84b8-f5e594aa3b1b)
![IMG_1090](https://github.com/SoftFever/OrcaSlicer/assets/58370642/0d021ac1-0621-4e40-ac04-d0d590f82b73)

### Expected results

Selecting PA Tower, a tower is expected, although Orca Slicer crashes

Selecting PA Pattern, a pattern is expected after slicing. Only a square is shown. Sent to printer and only a square was printed, no pattern at all.
<img width="406" alt="Screenshot 2024-07-10 at 09 57 25" src="https://github.com/SoftFever/OrcaSlicer/assets/58370642/708f3b71-b6b7-480a-bf68-e0b4688f639b">

### Project file & Debug log uploads

[log.zip](https://github.com/user-attachments/files/16157480/log.zip)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by RTGRDH** [comment]
It is the preview attached to the ticket.
I tried printing the sliced object, only a tiny square were produced.

**Comment by Noxandrys** [comment]
Ran into the same issue. Changing the 'Print Sequence' setting to 'By layer' fixed it for me. Looks like 'By object' causes some issues.

**Comment by RTGRDH** [comment]
> Ran into the same issue. Changing the 'Print Sequence' setting to 'By layer' fixed it for me. Looks like 'By object' causes some issues.

Tried it out and it worked! Thanks a lot! I'll close this ticket.
