### ISSUE TITLE
There is no Orca-Slicer.exe file in the Zip

### ISSUE THREAD

**Issue by StevenWoodword** [SoftFever/OrcaSlicer#609]
There is no Orca-Slicer.exe file in the Zip

**Comment by SoftFever** [comment]
Did you download this one? [OrcaSlicer_V1.5.0_Win64.zip](https://github.com/SoftFever/OrcaSlicer/releases/download/v1.5.0/OrcaSlicer_V1.5.0_Win64.zip)

There is 
![image](https://user-images.githubusercontent.com/103989404/228801173-5a33616a-a82d-486e-b98f-4209e2076309.png)
