### ISSUE TITLE
Regression of "fix model" option in orca nightly

### ISSUE THREAD

**Issue by Ataraxia-Mechanica** [SoftFever/OrcaSlicer#6095]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1 nightly 

### Operating System (OS)

Windows

### OS Version

Windows 10

### Printer

All

### How to reproduce

1. Install Orca nightly on windows 
2. The "fix model" option in the right click menu disappears

### Actual results

No fix model option in nightly

### Expected results

In 2.1.1 release version, right clicking shows the fix model option

### Project file & Debug log uploads

Should work with any project file

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by RcrossF** [comment]
This is not present for me in 2.1 but 2.2.0-dev gives me this issue. I'm also running Windows 10
