### ISSUE TITLE
Stop changing default Infill pattern every release.

### ISSUE THREAD

**Issue by irebane** [SoftFever/OrcaSlicer#6096]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Second release with Orca slicer default Sparse Infill has been changed on Release 2.1.1 it's Cross Hatch.
Both MacOS and Windows version of the slicer affected.

I have a lot of models saved as 3MFs for my business and it's 2rd release when default infill has changed and ruined already tuned profiles.

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

Lets pre-program default infill pattern.

### Describe alternatives you've considered

It's never happened on Bamboo Slicer so it's something related only to Orca Slicer.

**Comment by wociscz** [comment]
I'd rather save all values to the 3mf and not only the non-default changes. When you load your 3mf project to the new version with changed profile defaults, you'd see the orange changes instead of silent new-defaults.
