### ISSUE TITLE
Incompatibility with older davinci printers 

### ISSUE THREAD

**Issue by Bexin3** [SoftFever/OrcaSlicer#6097]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Hello, I am currently using a davinci 1.1 plus, and I as able to generate code and get it working on it from slic3r using a simple script that removes empty lines and adds some info - https://github.com/chrislondon/Convert_GCode_To_3W script but standalone, however for an some reason this doesn’t work with Orca slicer. The files as such are not accepted but after removing some of the images and such I was able to put it on the printer. However it wasn't entered and didnt seem to be printing.

Too left edge by deleted

### Which printers will be beneficial to this feature?

Others

### Describe the solution you'd like

Would be great to see this fixed or an outright possibility to generate .3w code

**Comment by Bexin3** [comment]
Specifically here you can see how the file looks when imported int XYZware from orca compared to slic3r
![Screenshot 2024-07-11 at 14 41 06](https://github.com/SoftFever/OrcaSlicer/assets/88098139/4f72fad3-e6dc-413d-b7a7-e71bd21d4e50)
![Screenshot 2024-07-11 at 14 40 45](https://github.com/SoftFever/OrcaSlicer/assets/88098139/e37ccd1d-74a3-4378-809c-ef867742a0c9)

**Comment by Bexin3** [comment]
Weirdly enough no, all behave the same

**Comment by discip** [comment]
@Bexin3
Have you tried disabling **`Arc fitting`**?

![image](https://github.com/user-attachments/assets/368498a4-0d6b-498d-8691-03af1feeff46)

**Comment by Bexin3** [comment]
@discip 
Hello, sadly no luck
I had it disabled already, so tired enabling it, and while no luck, it seems to make it worse;
<img width="779" alt="Screenshot 2024-07-21 at 16 15 53" src="https://github.com/user-attachments/assets/0b704743-3c13-4d8b-b29a-791bed6ca79b">
