### ISSUE TITLE
Implement hotfix for https://github.com/bambulab/BambuStudio/releases/tag/v01.05.00.61

### ISSUE THREAD

**Issue by Emperornero** [SoftFever/OrcaSlicer#611]
**Describe the bug**

3rd party logins can have an issue with sending prints to printers over the cloud or network.

**To Reproduce**
Steps to reproduce the behavior

Unsure.  Experienced this just now.  Had to disconnect printer from my account, reconnect it, and then log in and out of Orca Slicer to print over Cloud/Network again.

**Expected behavior**

The print is sent and then the page is moved to the Device tab.

**Screenshots**

**Printer model**

X1-Carbon

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Windows]

**Comment by SoftFever** [comment]
OrcaSlicer 1.5 includes this hotfix

**Comment by Emperornero** [comment]
> OrcaSlicer 1.5 includes this hotfix

I am on 1.5 and just experienced this. 

Should I be wiping the entire folder when upgrading, or is only overwrite good enough?
