### ISSUE TITLE
Snapmaker J1 Printer Profile

### ISSUE THREAD

**Issue by Learoy1** [SoftFever/OrcaSlicer#612]
Please can you add the Snapmaker J1 IDEX printer to the 3rd party list. 

Snapmaker Luban is just horrible, Cura is terrible at multicolour and crashes constantly and I'd love to be able to use Orca for all my printers.. 

Hopefully the info below is what is required.

Snapmaker J1 config files for PrusaSlicer
https://github.com/leandrolima-nyc/SnapmakerJ1

https://forum.snapmaker.com/t/great-sharing-prusaslicer-profiles-by-dylan-and-mcgybeer/28796

**Comment by hliebscher** [comment]
i have this  running including postprocessor and send to printer

**Comment by hliebscher** [comment]
wait for the PR idex J1  now working #663

**Comment by Learoy1** [comment]
> wait for the PR idex J1 now working #663

Thank you I appreciate this so so much.

**Comment by Learoy1** [comment]
Ok just tried to start a print sliced from orca and nothing happens.
