### ISSUE TITLE
A Creality Ender-3 V3 preset?

### ISSUE THREAD

**Issue by foxos21** [SoftFever/OrcaSlicer#6122]
### Is there an existing issue for this feature request?

- [x] I have searched the existing issues

### Is your feature request related to a problem?

Creality didn't update their linux slicer for a year now and the printer i bought is ONLY in the newest windows version. I am running it with Wine but it is slow and resource intesive. 

### Which printers will be beneficial to this feature?

Others, All

### Describe the solution you'd like

I would be surprised if a smaller creator was more reliable than a company. My solution would be to add it as a preset to a update. If there is a way to import the preset for the Ender-3 V3 into orca slicer i would be happy if someone could guide me.

**Comment by QuietWindUponTheMoor** [comment]
Last I checked, there already was a preset/profile for Creality Ender-3 V3? At least, there was for the CoreXZ model.
