### ISSUE TITLE
Strange artefacts when slicing model

### ISSUE THREAD

**Issue by Surion79** [SoftFever/OrcaSlicer#6123]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

Windows

### OS Version

Win 11

### Additional system information

AMD CPU, AMD GPU 64 GB RAM

### Printer

Voron 2.4R2

### How to reproduce

get file from Galileo 2 repo "[a] xl_stepper_plate_right x2.stl" or respective left. and lisce it

### Actual results

![image](https://github.com/user-attachments/assets/4284caac-d42b-4821-950d-a902ef28d82f)

### Expected results

![image](https://github.com/user-attachments/assets/2659abc7-855a-4764-bdb2-4efcb2922595)

This (expected result) has been sliced with superslicer 2.5.59.12

### Project file & Debug log uploads

[debug_Sat_Jul_13_10_26_52_7844.log.zip](https://github.com/user-attachments/files/16201442/debug_Sat_Jul_13_10_26_52_7844.log.zip)

[Issue_Slicing.zip](https://github.com/user-attachments/files/16201445/Issue_Slicing.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by Ergonomicmike** [comment]
related? https://github.com/SoftFever/OrcaSlicer/issues/5288

**Comment by Surion79** [comment]
nope, it is not a single line, the additional layer/heigt is ~50% and not single lines.
also it is not a pure rendering issue. it really prints that way

**Comment by YozenPL** [comment]
I also have some strange behavior with top visible layer.
BambuStudio:
![obraz](https://github.com/user-attachments/assets/a411a3d3-fa02-4b1e-a54e-b5dfa912ebe3)

OrcaSlicer:
![obraz](https://github.com/user-attachments/assets/a7534d84-fa89-4b1a-9ce3-4aa8e9fd47ea)

This is exact the same 3mf file (I removed some letters to not make any promotion)
File: [logo_part.zip](https://github.com/user-attachments/files/16674012/logo_part.zip)
