### ISSUE TITLE
Calibration - Flow Dynamics - Crashes - Bambu P1S

### ISSUE THREAD

**Issue by cprice-lci** [SoftFever/OrcaSlicer#6128]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

Windows

### OS Version

11 - 23H2

### Additional system information

Device name	framework
Processor	12th Gen Intel(R) Core(TM) i7-1260P   2.10 GHz
Installed RAM	64.0 GB (63.7 GB usable)
Device ID	D0C5AB38-11D1-4E94-84AD-3A6B3221AABA
Product ID	00330-81621-53524-AA161
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

### Printer

Bambu Lab P1S

### How to reproduce

1. Click on tab Calibrate
2. Click on button Manual Calibrate
3. Select any filament for calibration (in my case I'm selecting Bambu Matte PLA)
4. Under Method select Pattern
5. Click on the button Calibrate
6. Dialog appears with the message
"Unhandled unknown exception: terminating the application"
7. Orca Slicer closes.

### Actual results

Orca Slicer crashes

### Expected results

After clicking on the button Calibrate.  The pattern should be sent to the printer.

### Project file & Debug log uploads

[crash_Thu_Jul_11_19_22_12_0.log](https://github.com/user-attachments/files/16203665/crash_Thu_Jul_11_19_22_12_0.log)
[OrcaSlicerLogs.zip](https://github.com/user-attachments/files/16203668/OrcaSlicerLogs.zip)

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Anything else?

![image](https://github.com/user-attachments/assets/8ecb4d4b-e807-4c78-88ca-eda57c5fb633)

**Comment by noderat** [comment]
Duplicate of #6028
