### ISSUE TITLE
Changing default bridging direction

### ISSUE THREAD

**Issue by DusekM98** [SoftFever/OrcaSlicer#6145]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I feel like it would make more sense to have the default direction for bridging so they are made in the shorter way.

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

At least check some orientations for possible best one before generation.

### Additional context

![Snímek obrazovky 2024-07-14 212143](https://github.com/user-attachments/assets/4e1aec47-9362-4cdd-985a-fac64e91a5bb)

**Comment by vovodroid** [comment]
Isn't this option you are looking for?

![image](https://github.com/user-attachments/assets/000bfce8-9371-4080-99b3-913d2c1160ba)

**Comment by DusekM98** [comment]
I know about this option. I meant it as an improvement to the generative algorithm. I feel like checking at least a few angles (eg. increments of 15) and choosing the best of them shouldn't take that much more time during slicing.

**Comment by DusekM98** [comment]
I had it on zero and it gave me the result posted above, so maybe some improvements could be made.

**Comment by vovodroid** [comment]
And 180?

**Comment by DusekM98** [comment]
180 overrides the angle as intended by this setting. But then it does not use the automatic direction optimization I was talking about.
