### ISSUE TITLE
Top/Bottom solid infill overlap bug

### ISSUE THREAD

**Issue by simonvez** [SoftFever/OrcaSlicer#6149]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

Windows

### OS Version

windows 11

### Printer

VzBoT330

### How to reproduce

Set your top/bottom solid infill overlap to something really high like 250%, and your sparse infill overlap to like 50-75%. To test, set 0 top/bottom layer. 

### Actual results

sparse infill on first and last layer to go 250% overlap instead of 75%.

### Expected results

Since the 250% setting is set for top and bottom SOLID infill, it should not affect SPARSE infill I think.

### Project file & Debug log uploads

[infill overlap issue.zip](https://github.com/user-attachments/files/16235851/infill.overlap.issue.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Anything else?

![image](https://github.com/user-attachments/assets/0fc28d24-9aee-44bd-bba4-8a2a7fcaa3da)

**Comment by igiannakas** [comment]
Try printing with more than 1 perimeter. Does it still happen?
