### ISSUE TITLE
'Arrange all objects' does not take into account the possibility of placing the objects inside each other.

### ISSUE THREAD

**Issue by djonasdev** [SoftFever/OrcaSlicer#615]
**Describe the bug**
I have the following model file and would like to place it on the print bed and print it as often as possible.

If I now duplicate the object and execute "arrange all objects", the slicer does not place them inside each other, but from the 4th part onwards a new plate is used.

![grafik](https://user-images.githubusercontent.com/17551597/229087543-69a507b0-32b3-4abd-9481-2878687ccff4.png)

![grafik](https://user-images.githubusercontent.com/17551597/229087606-e16ac6ef-d094-476d-a427-c5e363d1a027.png)

**3mf File for This Bug**

[ArrangeBug.zip](https://github.com/SoftFever/OrcaSlicer/files/11120619/ArrangeBug.zip)

**Expected behavior**
If possible, the parts should be positioned as follows:

![grafik](https://user-images.githubusercontent.com/17551597/229089144-e16b08d8-f494-4c15-b680-b68c2555963f.png)

![grafik](https://user-images.githubusercontent.com/17551597/229089213-b13acbdd-21ef-4e9f-a519-2876b9495510.png)

**Comment by Ibot-11** [comment]
Prusaslicer does a much better job arranging objects. They improved the algorithm or something. Also it doesn't rotate the models by 45° anymore which causes that infill is not 45° anymore.

Maybe it’s an option to port the new arrangement algorithm from Prusaslicer?

Orca:
![image](https://github.com/SoftFever/OrcaSlicer/assets/84148069/04041b11-a15c-4c15-8199-3821f4ead07e)


Prusaslicer:
![image](https://github.com/SoftFever/OrcaSlicer/assets/84148069/12848f98-f0dd-457a-a23c-f08a7fdea436)

Both with 1mm model distance and rotation enabled.

**Comment by djonasdev** [comment]
Still relevant. Can you please reopen it?
