### ISSUE TITLE
Underextrude the first layer of the skirt so it can be easily removed

### ISSUE THREAD

**Issue by Ataraxia-Mechanica** [SoftFever/OrcaSlicer#6154]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Skirt stuck to the bed, need scraping to remove

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

Add a flow multiplier setting for the first layer of the skirt so it can be removed easier

**Comment by vovodroid** [comment]
Or add skirt width, that essentially is the same. But if you has such strong adhesion you can reduce it in a few ways.

**Comment by kisslorand** [comment]
...or use the existing "skirt height", make it more than 1 single layer (I use 3 layers for skirt height)

**Comment by Ataraxia-Mechanica** [comment]
I have it on 2 loops and 5 layers and it's still too strong with PETG.

**Comment by Luke56784** [comment]
If you underextrude the skirt you will probably have the problem that you cannot remove it in one piece because it will break.

If you are using a PEI sheet I would recommend switching to a fiberglass (G10 / FR4 / Garolite) plate for PETG.
Same for TPU.

This two filament types often sticking too well to the PEI surface.

**Comment by vovodroid** [comment]
> I have it on 2 loops and 5 layers and it's still too strong with PETG.

And what about printed model? Try to reduce bed and first layer temperature,  clean the bed.


> If you are using a PEI sheet I would recommend switching to a fiberglass (G10 / FR4 / Garolite) plate for PETG.

No problems with textured PEI and PETG.

**Comment by Ataraxia-Mechanica** [comment]
> If you underextrude the skirt you will probably have the problem that you cannot remove it in one piece because it will break.
Nah, just underextrude the first layer and keep other layers normal.


> And what about printed model? Try to reduce bed and first layer temperature, clean the bed.
Bed is cleaned and new, any lower and parts would warp.

**Comment by Ataraxia-Mechanica** [comment]
I'm going to write a post-processing script just for myself if yall think this is unnecessary smh, just making a suggestion that might be useful
