### ISSUE TITLE
Letters

### ISSUE THREAD

**Issue by renemosner** [SoftFever/OrcaSlicer#616]
**Describe the bug**
Please correct or add some letters, see  photo.  I am translating cs_CZ into Czech and these characters are unwanted.  Another question is whether it is possible to add pom_merger in the future as used by SuperSlicer to make translation easier.  Thank you and best regards, Mošner
( ě š č ř ž ů)

![Snímek obrazovky 2023-03-31 093911](https://user-images.githubusercontent.com/99507763/229117233-7c5aac3e-237a-48ed-9e26-336bd1bfa8b1.png)
![Snímek obrazovky 2023-03-31 094121](https://user-images.githubusercontent.com/99507763/229117248-3d5b7ae0-c8fa-4aee-901a-6b225094e437.png)

**Printer model**
Own construction

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: OrcaSlicer v1.5.0_Win64

**Comment by hliebscher** [comment]
you have to make a seperate directory cz with file Orcaslicer_cz.po based on Orcaslicer.pot
then translate all msgstr "????" into you language

**Comment by renemosner** [comment]
Yes, I understand it.
But it is the font in the options on the left that is supported, but not in the places marked in the picture.
I'm working on the translation, but I can't visually check it.

**Comment by hliebscher** [comment]
pls send your  cz.po file  the i check this with header you use

for  german ... the "Content-Type: text/plain; charset=UTF-8\n" is important !

msgid ""
msgstr ""
"Project-Id-Version: Orca Slicer\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2023-03-16 21:34+0800\n"
"PO-Revision-Date: \n"
"Last-Translator: Heiko Liebscher <hliebschergmail.com>\n"
"Language-Team: \n"
"Language: de\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n==1) ? 0 : 1;\n"
"X-Generator: Poedit 3.2.2\n"

**Comment by renemosner** [comment]
Here it is.
all changed files are there. In the text.json file I changed the .de translation to cz just to test the menu translation.
Only the OrcaSlicer cs_CZ translation is not yet 100% complete.

[OrcaSlicer.zip](https://github.com/SoftFever/OrcaSlicer/files/11126881/OrcaSlicer.zip)

**Comment by hliebscher** [comment]
we have to fix the truetype font settings ... and fix some other gui points 
i have no windows but i integrate this and than we add again you translation file

**Comment by renemosner** [comment]
OK:
Thank you for your willingness and time.
I will look forward to the results.

**Comment by hliebscher** [comment]
i have a pr #654

**Comment by renemosner** [comment]
Yes, I know about that.
But it's only basic machine translation. I incorporated translations from PrusaSlicer and SuperSlicer into my translation for a better understanding of the user.
And as I wrote, it's not 100% finished yet.
And in the text.json file, the translation to the main menu is just under the (de .)heading. which can be used for cs localization.

**Comment by renemosner** [comment]
Yes, I looked at it, but the characters are still wrong with letters with hooks and circles.  As I wrote in the original message.

**Comment by renemosner** [comment]
Hello. 
 I want to ask how it will be with bad characters, I haven't noticed any improvement.  Will you solve it somehow in the future? 
 Thank you.
