### ISSUE TITLE
A1 AMS Lite in OrcaSlicer says it Sup.PLA and not normal PLA. 

### ISSUE THREAD

**Issue by williamrehndell** [SoftFever/OrcaSlicer#6160]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

Windows

### OS Version

19045.4651

### Printer

Bambulab A1 + AMS Lite

### How to reproduce

I dont now if its possible.

### Actual results

PLA shows up as a support material when it’s regular PLA. It's possible to select like normal in Bambu Studio, but not in OrcaSlicer.
![orca-slicer_vu2f8thdzv]
![orca-slicer_vu2f8thdzv](https://github.com/user-attachments/assets/e7d17e7b-26ae-4829-8ffe-68263b77ce37)

### Expected results

Select normal material.

### Project file & Debug log uploads

[crash_Wed_Jul_10_23_43_06_0.log](https://github.com/user-attachments/files/16263328/crash_Wed_Jul_10_23_43_06_0.log)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by williamrehndell** [comment]
Tried loggin out and in, reseting the printers. Nothing solves the issue.

**Comment by arushe0805** [comment]
I have the same issue.
Bambu Studio shows it as PLA but Orca as Support PLA:
<img width="308" alt="image" src="https://github.com/user-attachments/assets/67ca5249-abe8-4d2b-aba4-60a82efc39a1">
<img width="344" alt="image" src="https://github.com/user-attachments/assets/a03e9239-75bd-4d6b-8f0d-24f5ce5e2d91">

Orca 2.2 and AMS Lite 00.00.07.94
