### ISSUE TITLE
[BUG 2.1.1] Visual bug

### ISSUE THREAD

**Issue by TinyMito** [SoftFever/OrcaSlicer#6167]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

macOS

### OS Version

14.5

### Printer

P1S

### How to reproduce

Visual bug in Prepare view; please see video here. I just started using Orca from 2.1.1 - I don't know if this bug was introduced in earlier build.

https://github.com/user-attachments/assets/8f66113a-1760-4098-96d9-fc53acbb8730

https://github.com/user-attachments/assets/1e223790-4baa-43bb-8223-24c9cf1ee050

### Actual results

n/a

### Expected results

n/a

### Project file & Debug log uploads

n/a

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by kylek29** [comment]
This has been there since (estimate) ~1.8 and previously reported (can't find the reports). It seems to be some form of render culling cube that is smaller than it needs to be which results in things being cut off.

It's kinda like the assembly/slice-plane view was left active.
