### ISSUE TITLE
Add Inner Wall to Internal Solid Infill

### ISSUE THREAD

**Issue by TheAtomicSoul** [SoftFever/OrcaSlicer#6179]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Currently Internal Solid Infill "floats" without anything to attach the inside of the edges to. 
Add an internal Wall to support the inside edges of Internal Solid Infill.
![image](https://github.com/user-attachments/assets/43b23a43-8aa3-401d-baea-5daab1dd044c)
![image](https://github.com/user-attachments/assets/165bd8f7-67db-4003-888b-d72abf87b137)

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

Add an internal Wall to support the inside edges of Internal Solid Infill.
 This should improve the results by it not hanging in space and having something to attach to.

**Comment by henrivdr** [comment]
Thanks for reopening this one.

I'm thinking now that the feature which I'm planning to get implemented (Internal Fillets) might rely on this working.
I just wish C++ didn't look completely different form when last I used it.
