### ISSUE TITLE
CF Materials - Nozzle Upgrade Issue

### ISSUE THREAD

**Issue by mtt-3d** [SoftFever/OrcaSlicer#6185]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

macOS

### OS Version

Sonoma 14.5 (23F79)

### Additional system information

Macbook Air M2 2022

### Printer

BambuLab P1S

### How to reproduce

Already setted HS HotEnd on printer settings
<img width="1209" alt="Screenshot 2024-07-19 alle 12 23 01" src="https://github.com/user-attachments/assets/e074b545-d9e9-4f3e-b9b1-6e99cba57bb3">

Trying to send a print through Ext Spool (already loaded into hotend), this warning show up
![image](https://github.com/user-attachments/assets/471a6b43-5772-43d6-add7-ea311be71794)

And i can't go forward.

### Actual results

.

### Expected results

.

### Project file & Debug log uploads

.

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by TinyMito** [comment]
Go to your device tab, click **Printer Parts** and set the printer hardware here:

![Screenshot-July-46KPBYiD](https://github.com/user-attachments/assets/224d98e8-334c-4bb9-88c5-eb4f799d00bd)
