### ISSUE TITLE
Proflie Anycubic Kobra 2 Pro

### ISSUE THREAD

**Issue by keybl** [SoftFever/OrcaSlicer#6200]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

For a long time there was no Kobra 2 Pro profile in Orca

### Which printers will be beneficial to this feature?

Klipper

### Describe the solution you'd like

These profiles were made by Anycubic for the Anycubic Beta slicer which is based on the Orca Slicer. I just copied them from Beta and tested them. Prints great
![Anycubic Kobra 2 Max_cover](https://github.com/user-attachments/assets/edecf16b-ec48-42a9-b810-6072dcc19654)
![Anycubic Kobra 2 Pro_buildplate_texture](https://github.com/user-attachments/assets/14e7be9d-db68-4abf-a246-4d5726639689)
![Anycubic Kobra 2 Pro_cover](https://github.com/user-attachments/assets/aec6dc6e-45ce-48c5-a12a-074d655f0645)
![Anycubic Kobra 3_buildplate_texture](https://github.com/user-attachments/assets/61a22e0c-d8d7-48c3-992e-31315830fd1f)
![Anycubic Kobra 3_cover](https://github.com/user-attachments/assets/8e87324d-038f-485d-bb1a-a6418c004302)

### Additional context

[Anycubic Kobra 2 Pro 0.4 nozzle.json](https://github.com/user-attachments/files/16323352/Anycubic.Kobra.2.Pro.0.4.nozzle.json)
[Anycubic Kobra 2 Pro.json](https://github.com/user-attachments/files/16323353/Anycubic.Kobra.2.Pro.json)
[0.20mm Standard @Anycubic Kobra 2 Pro 0.4 nozzle.json](https://github.com/user-attachments/files/16323354/0.20mm.Standard.%40Anycubic.Kobra.2.Pro.0.4.nozzle.json)
![Anycubic Kobra 2 Max_buildplate_texture](https://github.com/user-attachments/assets/c8bfd2ba-da78-4749-8d74-f91c2badea06)

**Comment by soosp** [comment]
See: https://github.com/SoftFever/OrcaSlicer/issues/5048#issuecomment-2389296161
