### ISSUE TITLE
Wrong color in "Send to printer" preview

### ISSUE THREAD

**Issue by FelixBuehler** [SoftFever/OrcaSlicer#6203]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

Windows

### OS Version

Windows 10 x64

### Printer

Bambu Lab P1S Combo

### How to reproduce

1. Probably at some point had/have multiple colors in AMS available.
2. Have a single color model.
3. Slice the file
4. Hit "Print plate"
5. See the color of the model change

### Actual results

The modell will appear in the correct selected filament for around 1 second, then change to the next color in order.

### Expected results

The color to stay the same.

### Project file & Debug log uploads

[3DBenchy.zip](https://github.com/user-attachments/files/16324085/3DBenchy.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Anything else?

![step1](https://github.com/user-attachments/assets/57448326-5a2e-468c-8653-5e00052be14a)
![step2](https://github.com/user-attachments/assets/35eff1fe-0c0e-4431-aa10-c34801bb6312)
![step3](https://github.com/user-attachments/assets/9b3b0a76-090f-4f43-b41e-3468f057d69e)

**Comment by tlhintoq** [comment]
Dupe of older ticket for same issue
https://github.com/SoftFever/OrcaSlicer/issues/5765
