### ISSUE TITLE
OrcaSlicer V2.1.1 Official Release Format of G-code thumbnails

### ISSUE THREAD

**Issue by ipod9138** [SoftFever/OrcaSlicer#6215]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

Windows

### OS Version

10

### Printer

Qidi Xmax 3

### How to reproduce

1- download orca slicer V2.1.1   upload a file to printer, no thumbnail, in printer settings in orca, no thumbnail g-code flavour (colpic)

### Actual results

No G-code flavour for thumbnail

### Expected results

I should have thumbnail on my printer screen

### Project file & Debug log uploads

Any file needed

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by xx0metalgurl0xx** [comment]
Im having the same issue as well
