### ISSUE TITLE
Unable to Export Config Files

### ISSUE THREAD

**Issue by MiscPrinter** [SoftFever/OrcaSlicer#622]
**Describe the bug**
When trying to export the custom config file it silently fails. I have set the profiles to non-system profiles but the export function reports 0 profile exported as it only exports non-system files. It seems to treat all profiles as system files. I have tried with several printer, filament, and print profiles. A few days prior I was able to get some but not all of the configurations exported after restarting the app. Restarting the app no longer helps the config files export. 

**3mf File for This Bug**
If it is related to slicing, please append the 3mf file. It could be extremely helpful to solve the issue.

**To Reproduce**
File->Export->Export Configs ->prompt to select an output designation->open-> confirmation window shows that 0 config files were exported as only non-system files are exported. 

**Expected behavior**
File->Export->Export Configs ->prompts to select an output designation->open-> confirmation window shows that 3 config files were exported

**Screenshots**

![bug1](https://user-images.githubusercontent.com/118319603/229334290-2b0910ed-3aef-45fe-a9c3-d3784fefe9e7.jpg)
![bug2](https://user-images.githubusercontent.com/118319603/229334292-bbeb8537-7fcf-4dfb-8214-ce7e5668ee4c.jpg)

**Printer model**

X1CC

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 1.5.0

**Comment by SoftFever** [comment]
Fixed.
Will include the fix in next update

**Comment by MiscPrinter** [comment]
Thanks for the great work.

**Comment by SoftFever** [comment]
Fixed
