### ISSUE TITLE
CalibPressureAdvancePattern does z-hop before retraction, z-hop cannot be adjusted or disabled

### ISSUE THREAD

**Issue by gregmatic** [SoftFever/OrcaSlicer#6232]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

Windows

### OS Version

10

### Additional system information

N/A

### Printer

Ender 3

### How to reproduce

- Use built-in Pressure Advance: PA Pattern Tool. any setting will do
- Slice and inspect Gcode at retraction at the end of each chevron. e.g top layer

### Actual results

1. z-hop of 0.2mm is hardcoded before every travel move between a completed chevron and the next chevron to be printed, and cannot be disabled or modified by any associated setting
2. if retraction is enabled, the hardcoded z-hop is inserted before the retraction instead of after. i.e. z-hop->retract->move.  this provokes unnecessary stringing in the PA Pattern Cal because it creates a vertical string/ooze at the end of a chevron and then drags it across to the other side where it is deposited on previously completed chevrons and/or the start of the new chevron.
3. this is opposite of how z-hop is typically executed in the slicer outside of PA Pattern Cal, i.e. retract->z-hop->move.
4. below i have 3 examples of the same PA Pattern config. 

4A. First on the left, Orca PA Pattern Cal wizard with hardcoded z-hop and ooze/blobs all over the place. 
4B. Second in the middle from [Ellis Pattern Generator](https://ellis3dp.com/Pressure_Linear_Advance_Tool/) with z-hop enabled and set to 0.2mm (the hardcoded value in Orca PAPC), with reduced ooze/blobs. This is because in Ellis Generator, the retraction is performed first before the z-hop
4C. Third on the right is also Ellis Generator but with z-hop disabled. Significantly less stringing and very minor zits deposited randomly. i just added this to show that on my machine i don't need z-hop for this. it's just worse.

 ![Untitled](https://github.com/user-attachments/assets/54c93445-91e5-400e-bc22-7b28280bfcda)
(A) Orca PAPC doing z-hop before retract
![image](https://github.com/user-attachments/assets/0663cc13-579c-4320-8c6c-72215da48f90)
(B) Ellis Generator doing retract before z-hop
![image](https://github.com/user-attachments/assets/eb99d230-cb35-496f-92b7-2d297986bc72)
(C) Ellis with z-hop disabled (something i wish Orca PAPC can allow
![image](https://github.com/user-attachments/assets/56c72669-ded9-4456-9766-b3e47cdcb5f2)

5. In OrcaSlicer/src/libslic3r/calib.cpp the z-hop is hardcoded before every travel move and undo z-hop after. this block is found several times in void CalibPressureAdvancePattern::generate_custom_gcodes()
```
- gcode << m_writer.travel_to_z(zhop_height, "z-hop before move");
- gcode << move_to(Vec2d(to_x, to_y), m_writer, "Move to pattern start");
- gcode << m_writer.travel_to_z(layer_height, "undo z-hop");
```
6. But retraction is already inside the move_to function, which means it gets priority to be directly next the move_to command. any z-hops added from 5. can only be inserted before the retraction.

```
std::string CalibPressureAdvance::move_to(Vec2d pt, GCodeWriter &writer, std::string comment)
{
    std::stringstream gcode;

    gcode << writer.retract();
    gcode << writer.travel_to_xy(pt, comment);
    gcode << writer.unretract();

    m_last_pos = Vec3d(pt.x(), pt.y(), 0);

    return gcode.str();
}
```
7. So 5. & 6. result in z-hop being done before retraction.

### Expected results

1. z-hop should obey its associated setting in the slicer. i.e. allow enable/disable, allow height adjustment of z-hop 
2. then move all the z-hop and undo z-hops into std::string CalibPressureAdvance::move_to() 

```
std::string CalibPressureAdvance::move_to(Vec2d pt, GCodeWriter &writer, std::string comment)
{
    std::stringstream gcode;
    gcode << m_writer.travel_to_z(zhop_height, "z-hop before move");
    gcode << writer.retract();
    gcode << writer.travel_to_xy(pt, comment);
    gcode << writer.unretract();
    gcode << m_writer.travel_to_z(layer_height, "undo z-hop");
    m_last_pos = Vec3d(pt.x(), pt.y(), 0);

    return gcode.str();
}
```
3. then all of this
```
- gcode << m_writer.travel_to_z(zhop_height, "z-hop before move");
- gcode << move_to(Vec2d(to_x, to_y), m_writer, "Move to pattern start");
- gcode << m_writer.travel_to_z(layer_height, "undo z-hop");
```
can be replaced with this
```
gcode << move_to(Vec2d(to_x, to_y), m_writer, "Move to pattern start");
```

but this only results in fixing z-hop/retraction order of operation. i don't actually know how to make z-hop obey settings.

Why not just use Ellis Generator? It can't do certain things that Orca PAPC can do, such as slice preview to see flow rate immediately and also customize line width, layer height, and customize accelerations. all things i needed to be able to do repeatedly while trying to test adaptive PA enhancement feature.

### Project file & Debug log uploads

N/A

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Ergonomicmike** [comment]
I concur that the Orca version of the Ellis pattern isn't as good as an original Ellis pattern.

I don't have a photo, but I tried the Orca PA pattern last week. Twice. Both prints tore apart on my printer. Whereas the original Ellis always printed well.

**Comment by igiannakas** [comment]
I've pushed a PR with a fix for this here: https://github.com/SoftFever/OrcaSlicer/pull/6245

You can download and test it here:
https://github.com/SoftFever/OrcaSlicer/actions/runs/10091976362

Feedback appreciated :)

**Comment by igiannakas** [comment]
@gregmatic As you're testing the adaptive PA feature, and since we don't merge PR's into each other for code management sake, you can download a consolidated build including both the above PA pattern z hop and retraction fix plus the adaptive PA (and other enhancements that are currently PR's that I've consolidated for my day to day use) from my dev branch here: https://github.com/igiannakas/OrcaSlicer/actions/runs/10092022209

**Comment by gregmatic** [comment]
> @gregmatic As you're testing the adaptive PA feature, and since we don't merge PR's into each other for code management sake, you can download a consolidated build including both the above PA pattern z hop and retraction fix plus the adaptive PA (and other enhancements that are currently PR's that I've consolidated for my day to day use) from my dev branch here: https://github.com/igiannakas/OrcaSlicer/actions/workflows/build_all.yml

really appreciate it man!

**Comment by igiannakas** [comment]
Adaptive PA is now merged in the nightly so you can just download the action build from the PR above ;)
