### ISSUE TITLE
dark mode is messed up (probably after sleep)

### ISSUE THREAD

**Issue by domik82** [SoftFever/OrcaSlicer#624]
Hi,

This happened to me few times already so I guess it's worth reporting.
Dark mode seems to be messed up like on screenshots - I think it's happening after laptop is put in sleep. 

In my case I was planning to print 2 plates (each ~5-6h). So I scheduled first  - left laptop overnight with plan to schedule second print in the morning.

Slicer looked like on screenshots.
![2023-04-02_13-51-24](https://user-images.githubusercontent.com/2431071/229351289-54873892-b85f-4498-9319-1cdc3d34b395.png)

This is 1.5 version

**Comment by Quick-Flash** [comment]
I get this same problem. Its an issue I have had on BambuSlicer as well. Its happened with every version of a BambuSlicer based slicer that I have used. So its not just an OrcaSlicer issue.

**Comment by bdistin** [comment]
This also occurs when RDPing into the machine with the slicer.

**Comment by aow99** [comment]
Same, noticed it on Bambu Studio a few months ago. Seems to happen after my pc is unlocked.
