### ISSUE TITLE
PA calibration crashes with pattern

### ISSUE THREAD

**Issue by LumberZvch** [SoftFever/OrcaSlicer#6249]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

Windows

### OS Version

11

### Additional system information

Processor	12th Gen Intel(R) Core(TM) i9-12900H   2.50 GHz
Installed RAM	64.0 GB (63.7 GB usable)
System type	64-bit operating system, x64-based processo
Graphics: RTX 3070

### Printer

Bambu P1S

### How to reproduce

Calibration -> flow dynamics -> manual calibration -> calibrate (look at image to see how it was set up)

![2024-07-25 18_21_50- PA pattern application close](https://github.com/user-attachments/assets/5d8d0804-3917-4cb3-8716-5157e2ce9269)

### Actual results

orca crashes 
![Uploading 2024-07-25 18_21_50- PA pattern application close.png…]()

### Expected results

Should run PA calibration for new filament 

### Project file & Debug log uploads

[log.zip](https://github.com/user-attachments/files/16385451/log.zip)

There is no project file except the one that is generated automatically from orca. 

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by Serial-Hobbyist** [comment]
Can confirm also still an issue in 2.2.0-rc
