### ISSUE TITLE
Shrinkage setting shrinks model even more!

### ISSUE THREAD

**Issue by umut885** [SoftFever/OrcaSlicer#625]
**Describe the bug**

The newly added "Shrinkage" option in filament setting shrinks the model. I tried 100% and 102%. I expected that the tolerance of 102% is higher to fit a round object into a cylindric hole.

100%: The round object fits (a little tight) into the cylindric hole
102%: The round object does NOT fit into the cylindric hole. The shrinkage option did shrink the hole instead adding more tolerance for an easy fit!

Probably 98% would bring the desired result (did not test). But that would be really counter-intuitive

**Desktop (please complete the following information):**
 - OS: iOS intel Chip
 - Version 1.5.0 Based on BambuStudio 01.05.00.51

**Comment by netweaver1970** [comment]
It's not a bug, it's as it's supposed to work. Read the tooltip for this parameter carefully. So a shrinkage value <100% will actually cause the part to be scaled UP to compensate. And scaled DOWN for shrinkage value>100%. Hence, the behaviour you see. It might be counter-intuitive, but that's the way the parameter is defined. It's also like this in SuperSlicer, in fact this option came straight from SuperSlicer, on special request.

![image](https://user-images.githubusercontent.com/18028618/229380359-c6ccb141-565b-4dab-9083-e8c6998aee80.png)

The abover parameter is only for external perimeter/dimension compensation, for X-Y holes **inside** the part, one might need also the hole compensation
![image](https://user-images.githubusercontent.com/18028618/229380475-f575f600-8a13-4f96-83f4-1244127c1a47.png)

**Comment by umut885** [comment]
Oh okay. Now I understand it. The tooltip takes really long time to appear. At least in my case. But now it makes perfectly sense. Also thank you for the hint regarding X-Y hole compensation. As mentioned before, without playing with X-Y hole compensation ( I hadn't seen this even until now) the Shrinkage option had definitely an impact on the hole size.

I will close the issue-
