### ISSUE TITLE
Part not printing as sliced

### ISSUE THREAD

**Issue by aideym** [SoftFever/OrcaSlicer#6251]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

Windows

### OS Version

Windows 11 pro

### Additional system information

Intel i7 8850h Nvidia Quadro Pro

### Printer

Bambulabs X1c

### How to reproduce

3 parts of 1 assembly imported to slicer
Sliced and sent to printer
2 parts print as expected 
1 part is dimensionally incorrect

### Actual results

![RDT_20240726_0802536245678776674349979](https://github.com/user-attachments/assets/b308d03e-cd64-4a03-89ac-d7a715c44598)
![RDT_20240726_0803084713315184168382208](https://github.com/user-attachments/assets/e14daee1-2ce9-4162-ac35-0f7f4fd831e1)
![RDT_20240726_0803192045884166687870848](https://github.com/user-attachments/assets/13d322f3-913a-4b14-8ef1-c0a1b44d793d)

### Expected results

All three expected to be ptinted as sliced. The incorrect item is Part studio 1 - retainer

### Project file & Debug log uploads

[Part Studio 1 - pusher.zip](https://github.com/user-attachments/files/16387787/Part.Studio.1.-.pusher.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Anything else?

I sliced the same file in Bambuslicer using the same settings and got the expected result

**Comment by ItsJupiter21** [comment]
can you share the project 3mf and the onshape link/the step file?

**Comment by aideym** [comment]
Of Course:
https://cad.onshape.com/documents/47ef673d6732d8ce394de945/w/15f495752a1eb6dbbeb95b4f/e/5b7019d8bb341658c566e81a?renderMode=0&uiState=66a6452f0c9a7537dc971f88

[Part Studio 1(2).zip](https://github.com/user-attachments/files/16403873/Part.Studio.1.2.zip)
