### ISSUE TITLE
Tree support on big prints print internal floating in air things inside support

### ISSUE THREAD

**Issue by xTremePower** [SoftFever/OrcaSlicer#6259]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

Windows

### OS Version

11

### Printer

Elegoo Neptune 4 Max

### How to reproduce

Slice a big model and see internal volumes of the tree supports

### Actual results

The slicer generate floating tree parts, totally non sence in mid air or even more annoying, reduce the tree branch diamter directly and print in mid air (see pics)

### Expected results

A tree is not supposed to print with nothing under, and I have no way to reduce this, if I lower the branche angle, with a 400mm print, tree will become weak
![Capture d'écran 2024-07-26 200208](https://github.com/user-attachments/assets/76cc2c47-d018-4e52-80ec-669b09ac0d75)
![Capture d'écran 2024-07-26 195923](https://github.com/user-attachments/assets/6cccf6be-f7a8-462e-82e2-324589c06750)
![Capture d'écran 2024-07-26 195912](https://github.com/user-attachments/assets/3af90fb3-bd59-428d-a80d-b463f2bbe7f6)
![Capture d'écran 2024-07-26 195546](https://github.com/user-attachments/assets/57c3d7d4-86bc-4191-8826-b894cbffddbf)
![Capture d'écran 2024-07-26 191415](https://github.com/user-attachments/assets/2fe02f56-9b1f-4331-a016-1b8762c68bb4)
![Capture d'écran 2024-07-26 191054](https://github.com/user-attachments/assets/2f00f2e1-0eeb-41df-8324-7812df91ecac)
![Capture d'écran 2024-07-26 190253](https://github.com/user-attachments/assets/8b334ac9-6f92-41d1-8d3a-89321bbd372d)
![Capture d'écran 2024-07-26 190240](https://github.com/user-attachments/assets/5693f167-5b5c-47d2-8b32-0caa69d11c1d)
![Capture d'écran 2024-07-26 200413](https://github.com/user-attachments/assets/c9769394-a079-46e1-83f9-6293dfd95230)

### Project file & Debug log uploads

not needed, make this with any big parts

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by xTremePower** [comment]
![Capture d'écran 2024-07-26 200930](https://github.com/user-attachments/assets/99ae9bb2-010a-4e1f-a3b7-b3fd90c30b22)

**Comment by empirebuilder1** [comment]
also having this issue. Tree supports seem to have no enforcement for Z-axis layer continuity. When printing parts with small overhangs that then have a tree above it, it seems to "shift" the tree over causing a print-in-air problem and other nonsensical geometry. 

Example below, showing a part that has a horizontal lip that the tree must then support above- the layer shift occurs slightly before when the tree tries to "shift over" to accomodate the lip. 
[https://i.imgur.com/3EH5HRw.png](url)

Files attached exhibiting the problem.
[90pipe_WINDOWtoHOSE_V3_SlicedFilesWithError.zip](https://github.com/user-attachments/files/16423074/90pipe_WINDOWtoHOSE_V3_SlicedFilesWithError.zip)
