### ISSUE TITLE
Avoid crossing walls feature removes some retraction wipes

### ISSUE THREAD

**Issue by bernarden** [SoftFever/OrcaSlicer#6266]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

Windows

### OS Version

Windows 11

### Printer

Creality Ender 5 S1

### How to reproduce

1. I used the following default profiles `Creality Ender-5 S1 0.4 nozzle`, `Creality Generic PLA` and `0.20mm Standard @Creality Ender5S1` but pretty sure it can be reproduced with other profiles.
2. Generate `Retraction test` model (start: 0mm, end: 2mm, step: 0.1mm/mm).
3. Change retraction wipe distance on printer setting to 10mm so it's very obvious when the bug occurs.
![image](https://github.com/user-attachments/assets/e689181f-3692-4caa-bc3c-ac1ed137e510)

5. No overrides on filament level.
6. Tick `Avoid crossing walls`
7. Optionally set `Max detour length` to some value other than 0. (No impact changing this value)
8. Slice the model and enable `Travel` line type in preview.

### Actual results

On **some** layers one of the sides does not have a retraction wipe gcode generated. The results are very sporadic. When looking at any 10 layers at the time this issue could affect 0-2 lines but sometimes more like 7-8 lines. In any case this was leading to constant stringing no matter what retraction setting changes I did. 
[2024-07-27.webm](https://github.com/user-attachments/assets/378962da-6e82-4c36-8662-def99a778557)

Also, you can observe on the side where the wipe gcode is generated the nozzle still crosses the walls anyway, but this perhaps is related more to #5217.

### Expected results

Retraction wipe gcode is generated for both sides of the model. 

### Project file & Debug log uploads

[Retraction test.zip](https://github.com/user-attachments/files/16399006/Retraction.test.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Anything else?

I've tested a few previous versions to see if it ever worked and got the following results:
1.6.6 - works
1.8.1 - works
1.9.0  alpha - does not work
1.9.0 - does not work
1.9.1 - does not work
2.0.0 - does not work
2.1.1 - does not work

**Comment by discip** [comment]
# Thank you figuring this out. 👍🏻
I was often wondering why some of my prints had the issue you described.

**Comment by discip** [comment]
# Thank you figuring this out. 👍🏻
I was often wondering why some of my prints had the issue you described.

@vovodroid
@igiannakas
Could you please have a look?

**Comment by vovodroid** [comment]
Actually I don't use either of these options...

**Comment by discip** [comment]
@vovodroid
This helps quite a bit when printing materials that are prone to stringing (e.g. PETG).

Any idea how **`Avoid crossing walls`** affects retraction wipes?
<br>
**`Avoid crossing walls`** disabled:

![image](https://github.com/user-attachments/assets/5f3a9e22-45a2-4942-ad80-9ce134c2de1d)
<br>
**`Avoid crossing walls`** enabled:

![image](https://github.com/user-attachments/assets/467995f7-ab10-46fb-abf4-507001bc6339)

**Comment by igiannakas** [comment]
PR raised: https://github.com/SoftFever/OrcaSlicer/pull/6518

If you fancy, please give it a test.

**Comment by igiannakas** [comment]
The odd part is that this whole code segment plus all the code that executes the avoid crossing walls functionality is basically unchanged since the orca first fork. So seeing this behave differently between versions is unexplained but may need to be examined further.

I would expect the model shown above to show similar behaviour across all versions. It is a good test, if anyone fancies checking against 1.8.1.

**Comment by bernarden** [comment]
@igiannakas You are correct that the issue is present in 1.8.1. I haven't noticed it since only a few layers were missing the wipe operation. Since that version the issue kept getting worse though.
![1 8 1-no-crossing](https://github.com/user-attachments/assets/2d7f3698-4250-47e5-bafd-0abf9faa27e1)
![1 8 1-crossing](https://github.com/user-attachments/assets/ecfc043c-bdc9-464f-950c-3230a2e8dac9)
![1 9 0-alpha-no-crossing](https://github.com/user-attachments/assets/16c19a40-961e-4416-92f2-50cd48d46068)
![1 9 0-alpha-crossing](https://github.com/user-attachments/assets/93102f78-3d47-46ea-a023-6a992af2abf1)
![2 1 1-no-crossing](https://github.com/user-attachments/assets/d1708fd6-3116-4929-9693-7c790e52c874)
![2 1 1-crossing](https://github.com/user-attachments/assets/ebdd7dd8-58fc-41df-afd6-efad5d4762eb)

**Comment by igiannakas** [comment]
Hm this makes no sense as the immediate code has been unchanged - I even compared it against the curent prusa slicer code and it’s functionally identical 🤔 

In any case the fix above should sort this once and for all as it enforces a wipe move when a retraction is being done, just like what the slicer does when avoid crossing walls is disabled.

I’d appreciate if you could test the build in the PR above and offer feedback please.
