### ISSUE TITLE
Icon not showing

### ISSUE THREAD

**Issue by kwagnitz** [SoftFever/OrcaSlicer#6276]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

OrcaSlicer_Linux_V2.1.1.AppImage

### Operating System (OS)

Linux

### OS Version

Ubuntu 24.04

### Additional system information

PRETTY_NAME="Ubuntu 24.04 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04 LTS (Noble Numbat)"
VERSION_CODENAME=noble

Kernel version Linux 6.8.0-39-generic

NVIDIA GeForce RTX™ 3060 Laptop GPU
X11 screen manager.
Gnome version 46

### Printer

Bambulab P1S

### How to reproduce

Run the appimage.

### Actual results

Shows a gear icon on the dock.

### Expected results

Should show the Orca icon.

### Project file & Debug log uploads

[OrcaFiles.zip](https://github.com/user-attachments/files/16405059/OrcaFiles.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Anything else?

The icon that lands on the dock is the gear icon.

From https://github.com/TheAssassin/AppImageLauncher/issues/653 :
the OrcaSlicer desktop file is incorrect. They need to specify their StartupWMClass so that the window manager can associate the running program's windows with the pinned entry.
~> xprop WM_CLASS
WM_CLASS(STRING) = "orca-slicer", "OrcaSlicer"
Thus, the desktop file needs to be amended with either
StartupWMClass=orca-slicer
alternatively
StartupWMClass=OrcaSlicer

References:
https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html
https://specifications.freedesktop.org/startup-notification-spec/startup-notification-0.1.txt

**Comment by gernoteger** [comment]
seems that StartupWMClass is not set in the .desktop file
in `src/dev-utils/platform/unix/build_appimage.sh.in`
