### ISSUE TITLE
A simple tetrahedron obj was found non-manifold

### ISSUE THREAD

**Issue by MartinChan3** [SoftFever/OrcaSlicer#6293]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

V2.1.1

### Operating System (OS)

Windows

### OS Version

Windows 11

### Printer

Bambu Studio A1

### How to reproduce

1. import the tetrahedron  in the zip
2. Orca says that it has non-manifold
![image](https://github.com/user-attachments/assets/e2a59896-0618-414e-939f-476f5b8d6c8a)

### Actual results

Shows 12 non-manifold edges

### Expected results

Shows no non-manifold edges

### Project file & Debug log uploads

[tetrahedron.zip](https://github.com/user-attachments/files/16421469/tetrahedron.zip)
[tetrahedron_3mf.zip](https://github.com/user-attachments/files/16421485/tetrahedron_3mf.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Anything else?

I  know it may due to repeated points , but it should be more  convient to remove them when we load mesh

**Comment by foreachthing** [comment]
> I know it may due to repeated points ...

Well, yeah!!

Even Blender "thinks" your tetrahedron is not manifold - so, it must be non-manifold.

![image](https://github.com/user-attachments/assets/c39666e9-622a-429e-8d8e-9b72ecd70f81)

After cleaning it up, in Blender, it's now manifold  😄
