### ISSUE TITLE
Menu Bar blurs when moving mouse (MacOS)

### ISSUE THREAD

**Issue by alidaf** [SoftFever/OrcaSlicer#6295]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

macOS

### OS Version

Ventura 13.6.7

### Additional system information

Intel i7, 16GB, Radeon Pro 580 8GB

### Printer

Voron 2.4, Voron 0.2, Bambu Lab X1C

### How to reproduce

Move mouse around screen. Try to select a menu bar icon.

### Actual results

The menu bar rapidly expands and contracts lengthwise (x-direction) until the mouse is stationary, causing the icons to blur and become indistinguishable. This only happens when the side bar is extended.

### Expected results

Stationary menu bar with clear icons when moving mouse.

### Project file & Debug log uploads

[debug_Mon_Jul_29_12_20_46_80573.log.0.zip](https://github.com/user-attachments/files/16425637/debug_Mon_Jul_29_12_20_46_80573.log.0.zip)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by buzzhuzz** [comment]
Should be fixed by https://github.com/SoftFever/OrcaSlicer/pull/6230

**Comment by alidaf** [comment]
Great, thanks
