### ISSUE TITLE
Only first 9 of the 18 projects listed in 'Recent Projects' open

### ISSUE THREAD

**Issue by SwagDad99** [SoftFever/OrcaSlicer#63]
**Describe the bug**
When you click on 'File/Recent Projects', 18 most recent projects are listed.  Clicking on 10-18 in the list do nothing.  The first 9 open.

**3mf File for This Bug**
None

**To Reproduce**
1. Have 18 recent projects listed in the 'Recent Projects' list under the 'File' menu.  I am not sure it behaves the same with less recent projects
2. Click on any project in the list, between numbers 10 and 18
3. The screen just returns to the Prepare tab

**Expected behavior**
The selected project should open

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Windows]

**Comment by SoftFever** [comment]
Works fine on my machine?
![image](https://user-images.githubusercontent.com/103989404/210059395-7b1dba3a-0140-4e6f-8785-7d34ab7647fc.png)

**Comment by SwagDad99** [comment]
From the home screen mine works fine.  If you open a project, and then go to the ‘File’, ‘Recent Projects’ menu option, it fails from there.

Don

**Comment by SoftFever** [comment]
I'm not able to repro it.
Can you provide more info?
