### ISSUE TITLE
这款切片软件能否加入无限z的切片配置？

### ISSUE THREAD

**Issue by yang6991906** [SoftFever/OrcaSlicer#630]
这款切片软件能否加入无限z的切片配置？
加入角度切片的功能的难度大么？

**Comment by TexZeTech** [comment]
> 这款切片软件能否加入无限z的切片配置？ 加入角度切片的功能的难度大么？


谷歌翻译成英文：
Google translate to english: 
Can this slicing software add unlimited z-slice configuration? Is it difficult to add the function of angle slicing?


I'm assuming they want to use something like the [CR-30](https://www.creality.com/products/creality-cr-30-3d-printer)

I wouldn't mind that implemented as well.
