### ISSUE TITLE
Tree support always applies adaptive layer despite parameter setting

### ISSUE THREAD

**Issue by S1lentA0** [SoftFever/OrcaSlicer#6300]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

Windows

### OS Version

Windows 10

### Printer

Bambu P1S

### How to reproduce

When turning on treesupports, adaptive layer height is applied to the tree supports, despite turning this off in the slicer. Treesupports will break mid-print with failed prints as a result. 

After testing a bit more I noticed that adaptive layer heights for supports don't apply to Organic Tree Supports.

After searching, [this seems to be an old bug](https://github.com/SoftFever/OrcaSlicer/issues/5272), which still hasn't resolved.

### Actual results

As seen in the screenshots, gaps will form between the layer, because the slicer skips 1 layer for every 2 layers on the print itself.

![Schermafbeelding 2024-07-31 085104](https://github.com/user-attachments/assets/446f9e08-0a29-4ccd-bca3-348608c02759)

![Schermafbeelding 2024-07-31 085635](https://github.com/user-attachments/assets/30823277-2ffc-460a-8299-f9296d0869c4)

### Expected results

By disabling adaptive layers for supports, I expect that this happens as intended.

### Temporary "fix"

To avoid treesupports breaking off, adding 1 or 2 extra Support Wall Loops seems to work. Switching to Organic Tree Supports instead of Slim/Strong/Hybrid gives me the best results.

### Project file & Debug log uploads

[2.zip](https://github.com/user-attachments/files/16437550/2.zip)
[log.zip](https://github.com/user-attachments/files/16437552/log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by S1lentA0** [comment]
> Did you find any workarounds to make the supports work until this bug is fixed?

Adding more walls to the tree support seems to work. Last print the supports with 3 walls didn't fail.

**Comment by tlhintoq** [comment]
There's two settings that do basically the same thing.  I couldn't tell ya what the difference is but they read the same and seem to do the same thing.  I always turn them both off and both on together.
![image](https://github.com/user-attachments/assets/897e900e-709a-430c-992c-2931f6019000)

**Comment by S1lentA0** [comment]
> There's two settings that do basically the same thing. I couldn't tell ya what the difference is but they read the same and seem to do the same thing. I always turn them both off and both on together. 

What version are you using? I checked every version of tree support, but the option "independent support layer height" doesn't show up for me.

**Comment by tlhintoq** [comment]
Currently 2.1.1 - but its been there a while

**Comment by S1lentA0** [comment]
> Currently 2.1.1 - but its been there a while

Yeh, I just found out it will only appear if you have the Prime Tower disabled, which I never have. I made 4 slices comparing the settings and found out that the adaptive layer height does get disabled when disabling Independent Support Layer Height, and it still doesn't apply for Adaptive Layer Height, though there is difference in how the Tree Supports are generated. In this example I used Hybrid Tree Supports and all the settings, aside from these 4, remained the same.

![Both on](https://github.com/user-attachments/assets/40a8115a-9945-49dc-88d3-87b49e75ddd0)

![independent off adaptive on](https://github.com/user-attachments/assets/808a9acf-f19c-4a9b-bba0-324754bb8eb9)

![independent on adaptive off](https://github.com/user-attachments/assets/ab575cf4-7553-4a59-a4d6-61a3334a8db5)

![Both off](https://github.com/user-attachments/assets/5fd31a8f-2724-4541-9e5b-7e926cea9380)

**Comment by Cilsor** [comment]
Which do you think would print the best? The very first almost looks as if you can just tell there is going to be delamination/warping on the trees. All the other trees look uniform and great. 



> > Currently 2.1.1 - but its been there a while
> 
> Yeh, I just found out it will only appear if you have the Prime Tower disabled, which I never have. I made 4 slices comparing the settings and found out that the adaptive layer height does get disabled when disabling Independent Support Layer Height, and it still doesn't apply for Adaptive Layer Height, though there is difference in how the Tree Supports are generated. In this example I used Hybrid Tree Supports and all the settings, aside from these 4, remained the same.
> 
> ![Both on](https://private-user-images.githubusercontent.com/134236161/354802835-40a8115a-9945-49dc-88d3-87b49e75ddd0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2OTU2MzIsIm5iZiI6MTcyMjY5NTMzMiwicGF0aCI6Ii8xMzQyMzYxNjEvMzU0ODAyODM1LTQwYTgxMTVhLTk5NDUtNDlkYy04OGQzLTg3YjQ5ZTc1ZGRkMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwM1QxNDI4NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zM2U0ZTVhZWU5MjcyZmRjNWYwYzBjN2NkYjdkMGQ3MzE2MWE2N2YwNjZlOTU5NmIwYTUzMzE2NzI5MGNkM2NiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZriwXjEdUDzmtSWXXksPQ-DXlF4rQSRSvkC2iQFNYDY)
> 
> ![independent off adaptive on](https://private-user-images.githubusercontent.com/134236161/354802838-808a9acf-f19c-4a9b-bba0-324754bb8eb9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2OTU2MzIsIm5iZiI6MTcyMjY5NTMzMiwicGF0aCI6Ii8xMzQyMzYxNjEvMzU0ODAyODM4LTgwOGE5YWNmLWYxOWMtNGE5Yi1iYmEwLTMyNDc1NGJiOGViOS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwM1QxNDI4NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMDRjNzgzMjFjNWI1MzZmNGM3ZTY3N2JjM2M0MTViYzEyMmQwN2Q2YjliNTIzODg2YmQ5M2IxNmMwYzUwOTc4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hoOFWqCupQwgvPzfQ82-lSbE5HPBOyYkW1mREcYTIHI)
> 
> ![independent on adaptive off](https://private-user-images.githubusercontent.com/134236161/354802842-ab575cf4-7553-4a59-a4d6-61a3334a8db5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2OTU2MzIsIm5iZiI6MTcyMjY5NTMzMiwicGF0aCI6Ii8xMzQyMzYxNjEvMzU0ODAyODQyLWFiNTc1Y2Y0LTc1NTMtNGE1OS1hNGQ2LTYxYTMzMzRhOGRiNS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwM1QxNDI4NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZGI4YmM0MGM0NTdlNTJlZGIzNzZlM2MxNjZjZmNhNzExMmU5MWNiYzIxYjU3NjQwNmNhNTQxZmFmZjZmMjliJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tDF0J_AZVUd4dLPXs53QH0IPWLcoXudBwkxN0yiEd9Q)
> 
> ![Both off](https://private-user-images.githubusercontent.com/134236161/354802846-5fd31a8f-2724-4541-9e5b-7e926cea9380.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2OTU2MzIsIm5iZiI6MTcyMjY5NTMzMiwicGF0aCI6Ii8xMzQyMzYxNjEvMzU0ODAyODQ2LTVmZDMxYThmLTI3MjQtNDU0MS05ZTViLTdlOTI2Y2VhOTM4MC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwM1QxNDI4NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YTk3N2MxMTRmYmFhZTBhOTJmNGI1YWRlNzMyOThhOTg4NmJjYjA3NjBkZjM0OTAyNTEwMTYzNWVkOTc3NWU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6rzRRddIhihvEpB7Zeu7b52c15oYnkJ0wl3TiM_MKcY)
