### ISSUE TITLE
Adding random layer

### ISSUE THREAD

**Issue by KennerCarter** [SoftFever/OrcaSlicer#6310]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

Windows

### OS Version

Windows 11

### Printer

K1C

### How to reproduce

Insert a 3D file I made
slice
random extra layer between two tubes

### Actual results

![Screenshot 2024-07-31 133040](https://github.com/user-attachments/assets/f1b1a5a9-0458-4d42-be1d-d0bdf324645f)
![Screenshot 2024-07-31 133131](https://github.com/user-attachments/assets/bbfc7ddb-5012-4db0-bcf0-92c5ae13c5de)

### Expected results

Slice with no extra thing between the two tubes

### Project file & Debug log uploads

[Yeti back half.zip](https://github.com/user-attachments/files/16446381/Yeti.back.half.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by Arakon** [comment]
Your object is non-manifold, this is not a slicer problem.
![image](https://github.com/user-attachments/assets/b8c2ce4e-b752-45a6-bb05-7e2d5746c059)
Once repaired, it slices just fine.
![image](https://github.com/user-attachments/assets/b6f094c4-a754-43d0-bb5b-4f4fb8f3be01)
