### ISSUE TITLE
Stuck in wizard on filament page

### ISSUE THREAD

**Issue by burbilog** [SoftFever/OrcaSlicer#6319]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

Linux

### OS Version

Debian 12

### Additional system information

PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

### Printer

KP3S 3.0

### How to reproduce

1. Run Orca slicer for first time
2. Accept certificate
3. Select region
4. Select KP3S 3.0
5. Be greeted with empty filament selection, no way to go to next step. 

### Actual results

Dialog box pops up "At least one filament must be selected. Do you want to use default filament ?", but neither "yes" nor "no" answer work, it just closes the error message and that's all.

### Expected results

Continuing the wizard. 

### Project file & Debug log uploads

there is no project and no debug, can't pass 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by undecided** [comment]
Was just coming to report the same. First time using orca. Same 3d printer.

Found a workaround: Select both the kingroon, and a generic (I chose the generic marlin, but I suspect any of them would work)
Install all the generic filaments, then it seems you can delete the original printer.
I'm guessing the only reason some filaments are printer-dependent is that some printers do nasty drm things with their approved spools?
