### ISSUE TITLE
where is the wall thickness information like in prusa slicer

### ISSUE THREAD

**Issue by moth4017** [SoftFever/OrcaSlicer#6338]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

in prusa slicer when you set number of perimeters it calacltes the wall thickness where is this in orca slicer
![image](https://github.com/user-attachments/assets/3792b6b2-b5e9-40ce-9a31-eab066621b8d)

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

![image](https://github.com/user-attachments/assets/3fafd8a6-0912-4b83-87f0-e05db794eb1a)

**Comment by igiannakas** [comment]
Second tab, first setting.

**Comment by moth4017** [comment]
Hi it does not give you the wall thickness measurement  as it does in prusa slicer as per my screen shot.

E.g  2 walls = 1.59 mm  wall thickness

We use this wall thickness measurement  when designing  in CAD

Regards

Mark
________________________________

**Comment by igiannakas** [comment]
Can you post a screenshot of the said setting in prusa slicer?

**Comment by moth4017** [comment]
[cid:1082ddce-8214-46b0-aa95-d3ca804ab598]

________________________________

**Comment by moth4017** [comment]
i dont want to open up prusa slicer  to get the dimensions, please could you add this info back in , thank you
