### ISSUE TITLE
Parts colored in black are very low contrast, making it difficult to use the slicer

### ISSUE THREAD

**Issue by kubark42** [SoftFever/OrcaSlicer#635]
**Describe the bug**
The color of imported parts is black. This sets up a situation with very low contrast and as a result it is very difficult to use OrcaSlicer.

**Expected behavior**
The default parts color should be high contrast. 

There could also be a means to change the part color, but the default should still be something with high contrast.

**Screenshots**
<img width="1567" alt="Screenshot 2023-04-03 at 5 13 15 PM" src="https://user-images.githubusercontent.com/1118185/229628814-3bf714d6-199c-4b29-bf71-99ea8000b807.png">

**Comment by SoftFever** [comment]
Next version will assign a better default color c7dbf848a62b56ea83fa5cc169b961f31d42b979

For now, you can manually change the color by clicking the :
![image](https://user-images.githubusercontent.com/103989404/229648026-99ab1013-91ce-4ed1-bc91-1a6aff4569d5.png)

**Comment by kubark42** [comment]
Wonderful!
