### ISSUE TITLE
Separate speed settings for crossing and non-crossing infill

### ISSUE THREAD

**Issue by Ataraxia-Mechanica** [SoftFever/OrcaSlicer#6366]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

New feature in prusa slicer 2.8.0, the speed for crossing and non-crossing infill can be set differently. Maybe also make this true for acceleration?
![image](https://github.com/user-attachments/assets/c8c57137-4fdb-4e78-8a45-49e0a1de232d)

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

Add this feature so it's a bit more convenient when switching infill types

**Comment by igiannakas** [comment]
Isn’t the same thing achieved by just slowing down the sparse infill print speed? What am I missing?

**Comment by Ataraxia-Mechanica** [comment]
This is about e.g. setting non-crossing infill's speed to 400, crossing's speed to 300, then just by changing the infill type from rectlinear to cubic, the sparse infill's speed get reduced automatically to 300, saving a bit of time.
