### ISSUE TITLE
Filament Aux fan speed ignored

### ISSUE THREAD

**Issue by npoulos** [SoftFever/OrcaSlicer#637]
**Describe the bug**
Tested on 3 different Bambus, 2x X1C's and 1x P1P and happens on all.

Basically the Aux fan never turns on. I've got the filament setting the Aux fan to 40% after 1 layer but it never comes on.

**Comment by SoftFever** [comment]
Please double check if the Aux Fan is enabled in the printer settings.

If it still happens, please attach a project file that can reproduce the issue.

**Comment by npoulos** [comment]
Aux fan is enabled in both the X1's, i can't see a setting to "enable" it in the P1P but i can control the Aux fan from the app/slicer so i imagine it's enabled.

Attached a project. You'll see in filament settings Aux fan is set to 40% and "No cooling for first" is set to 1 layer.

[noauxfan.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/11155039/noauxfan.3mf.zip)

**Comment by npoulos** [comment]
.. okay i'm stupid. There's an "Auxillary part cooling fan" at the bottom of the "Basic information > Accessory" section.

Potentially it's worth adding a note, or disabling the aux fan speed on the filament setting to indicate it's turned off?

Totally my bad.

**Comment by SoftFever** [comment]
Yeah, in the recent nightly build I have added this check.

**Comment by npoulos** [comment]
Awesome! Thanks for all your hard work 😊
