### ISSUE TITLE
Opening file from thingiverse issue

### ISSUE THREAD

**Issue by GTreaper** [SoftFever/OrcaSlicer#6382]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

Windows

### OS Version

Win 10

### Printer

Voron 2.4 350

### How to reproduce

1. go to https://www.thingiverse.com/thing:6076779/files
2. press open in orca slicer
3. receive orca slicer warning "The download has failed:
You are not allowed to use robots, spiders, scraping, or other technology to access or use
Content or any Sites to obtain any information"

### Actual results

![orcaerror](https://github.com/user-attachments/assets/7fddb4d9-5a71-4fd3-8e80-9760ae22d027)

### Expected results

open file in orca 

### Project file & Debug log uploads

cant

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by TheDuke22** [comment]
Same problem happen to me on Arm Mac (same orca version)

**Comment by boromyr** [comment]
same problem

**Comment by NuclearCreations** [comment]
Same problem.

**Comment by ZAKsPop** [comment]
Yeah, what gives? Orca had the option to do this in previous version which I thought was cool but now it doesn't work.

**Comment by astanix** [comment]
I can confirm that this is happening for me as well.

**Comment by awdev1** [comment]
Can confirm this is happening here.

**Comment by Faellatv** [comment]
Did the same for another file, same problem here.

**Comment by 3DCoded** [comment]
Same problem here. It looks like it might be Thingiverse that is blocking the download?

**Comment by awdev1** [comment]
Maybe the user agent orca slicer uses?

**Comment by eacxx** [comment]
Another one bites the dust...
Orca 2.2.0_dev
Mac ARM, Sonoma 14.6.1

**Comment by pickanothername** [comment]
This has been resolved for me. M3 Macbook Pro Sonoma

**Comment by awdev1** [comment]
Working now @GTreaper can close
