### ISSUE TITLE
Calibration Retraction and other tests issue on Mac 

### ISSUE THREAD

**Issue by Knase** [SoftFever/OrcaSlicer#6385]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

macOS

### OS Version

Sonoma

### Additional system information

MacBook Air M1, 2020

### Printer

Bambu Lab A1 mini

### How to reproduce

New Project
Calibration
Retraction Test -> OK
Error

### Actual results

Both calibrations use models with non-manifold edges. This is a minor annoyance in Windows, requiring an extra click to repair. I'm not sure how MAcOS or Linux handle this without Windows' repair capability.

### Expected results

It will work as in Creality Print App

### Project file & Debug log uploads

[debug_Thu_Aug_08_20_35_16_9147.log.0.zip](https://github.com/user-attachments/files/16551590/debug_Thu_Aug_08_20_35_16_9147.log.0.zip)
<img width="980" alt="Знімок екрана 2024-08-08 о 20 24 22" src="https://github.com/user-attachments/assets/1c635d26-e39a-46e5-a737-398ea4f3828c">
<img width="383" alt="Знімок екрана 2024-08-08 о 20 24 18" src="https://github.com/user-attachments/assets/58480859-3e49-45ee-a1cc-57a7b2103ebb">

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by igiannakas** [comment]
You can still successfully slice and print them. Mac user here, have used them all and they have worked just fine.
