### ISSUE TITLE
SafeZone

### ISSUE THREAD

**Issue by RNGIllSkillz** [SoftFever/OrcaSlicer#6394]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

No

### Which printers will be beneficial to this feature?

Klipper

### Describe the solution you'd like

Implement a safe zone for printers with toolchanger, so tool docks will be displayed in the UI as a bounding box.

**Comment by adrianbear** [comment]
+1 From me
