### ISSUE TITLE
Can't import config profiles properly, and can't delete them either? 

### ISSUE THREAD

**Issue by nirurin** [SoftFever/OrcaSlicer#641]
**Describe the bug**
I have a couple of config profiles from the bambu discord. Try to install them. They import, but they don't appear in the config dropdowns. 
If I try and import them again, the message 'A config exists with the same name: Polymaker PETG, do you want to override it." pops up. I say yes, but it's still not showing in the config list. 

If I go to appdata/roaming/orcaslicer I can find the config files in there. I delete them.
But if I then load up the app, they get added back into the folder auttomatically. So they must be also saved somewhere else??

**Printer model**
P1P

**Desktop (please complete the following information):**
 Windows 11 current

**Comment by SoftFever** [comment]
Do you have the config profile to test?
