### ISSUE TITLE
Crash while want to send the print

### ISSUE THREAD

**Issue by smooth-baking-powder** [SoftFever/OrcaSlicer#6429]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

Linux

### OS Version

Ubuntu 22.04 Tuxedo Linux

### Additional system information

CPU: Ryzen 7800X3D
GPU: Nvidia RTX 4080 Super
RAM: 32 GB

X11 Session on this Device

Second test on Laptop:
CPU: Ryzen 5500U
GPU: CPU Integrated
RAM: 16 GB

Wayland Session

### Printer

Bambu Lab X1C

### How to reproduce

1. Do your Print on the Plate
2. set all
3. slice
4. click on "print plate"
5. the popup dialog opens with choosing printer and "use ams" and more

### Actual results

Printer is not useable, Program freeze and a popup came with "Orca slicer not react. want to terminate?"

### Expected results

I can choose my printer and send the print

### Project file & Debug log uploads

[File.zip](https://github.com/user-attachments/files/16575581/File.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Anything else?

Side Note on PC:
I cant see the Live Cam on this Device. I click on Play Button and the screen stay black. On Laptop i can see the Livecam.

On PC with X11:
![2024-08-11_19-42](https://github.com/user-attachments/assets/eade036b-6acd-4657-818f-abf60ec17172)

On Laptop with Wayland:
![Bildschirmfoto_20240811_192431](https://github.com/user-attachments/assets/3a6ef56a-72c2-4b80-a08e-3189e5d876b8)

I check the logs, but i didnt see any entry of Orca Slicer with tail or live journal, while using.

Thanks

**Comment by dadealus** [comment]
Im running Debian 12, KDE X11.

have been using orca just fine for the last week or so, went to click print plate today.... now mine is doing the same as above.
![image](https://github.com/user-attachments/assets/888ddec3-0d80-48cd-a4ea-a0abf7d1a171)

I am also unable to use the send feature as well
![image](https://github.com/user-attachments/assets/8a89392e-f0b4-4e08-a2b3-dfd6953e7494)
