### ISSUE TITLE
Add used filament length info in gcode at layer_change

### ISSUE THREAD

**Issue by przemowcf** [SoftFever/OrcaSlicer#6444]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I'm missing this for planning for spool change - especially for longer prints that will use more filament than I have on a spool.

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

Here is example how I'd see the part of gcode file with `;LAYER_CHANGE`:
*(total filament used up to this layer change)*
```gcode
...
;LAYER_CHANGE
;Z:19.6
;HEIGHT:0.2
;FILAMENT_USED:1185.8mm
;BEFORE_LAYER_CHANGE
;19.6
...
...
...
;LAYER_CHANGE
;Z:19.8
;HEIGHT:0.2
;FILAMENT_USED:1212.1mm
;BEFORE_LAYER_CHANGE
;19.8
...
```

### Describe alternatives you've considered

none.

### Additional context

I think it should not be to difficult to add this info to gcode, since the filament length is counted already (at end file there is total).

**Comment by digitalresistor** [comment]
Anyway to re-open this feature request without re-creating the feature request entirely? This would be great to get a better idea for how much filament will be used by what time in the print, so that I can estimate when a spool is about to run out and at about what time into the print.
