### ISSUE TITLE
`Open Containing Folder` opens the actual file instead of the folder

### ISSUE THREAD

**Issue by discip** [SoftFever/OrcaSlicer#6449]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

https://github.com/SoftFever/OrcaSlicer/commit/7082e945b12f2e37584c3aa1dc68f513c8b4eee0

# System Details Report
---
- **Date generated:**                              2024-08-13 15:47:20

## Hardware Information:
- **Hardware Model:**                              ASUS ROG STRIX X670E-E GAMING WIFI
- **Memory:**                                      32,0 GiB
- **Processor:**                                   AMD Ryzen™ 9 7950X3D × 32
- **Graphics:**                                    AMD Radeon™ RX 7900 XTX
- **Disk Capacity:**                               2,0 TB

## Software Information:
- **Firmware Version:**                            2007
- **OS Name:**                                     Manjaro Linux
- **OS Build:**                                    rolling
- **OS Type:**                                     64-bit
- **GNOME Version:**                               46
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.8.12-3-MANJARO

### How to reproduce

1. Launch Orca and navigate to the Home screen,
2. right click on any project file and
3. click **`Open Containing Folder`**

### Actual results

Instead of the containing folder, the actual file is opened in another instance of **Orca**.

### Expected results

The folder containing the project file should open.

**Comment by discip** [comment]
@Noisyfox
There seem to be even more Linux specific quirks.
Any idea on that one?

**Comment by Noisyfox** [comment]
Yeah, linux does not have a common "open containing folder" command. I think the best option is to open the folder without the file been seleceted automaically.

**Comment by discip** [comment]
So, ... is there anything that could be done to solve this?

**Comment by Noisyfox** [comment]
> I think the best option is to open the folder without the file been seleceted automaically, instead of using a disto-specific command.

This.

**Comment by discip** [comment]
Sorry, I'm not able to follow.😅
What exactly do you mean?

**Comment by discip** [comment]
> So, instead, for Linux I think it's much easier to just do step 1 without step 2,

I totally agree, but I don't know how to achieve the following:

> which should be achieved by a `std::filesystem::path::parent_path` then an `xdg-open` command.
