### ISSUE TITLE
Missing RFID support for PETG-HF

### ISSUE THREAD

**Issue by oernster** [SoftFever/OrcaSlicer#6451]
### Is there an existing issue for this feature request?

- [ ] I have searched the existing issues

### Is your feature request related to a problem?

I have been reliably informed (I can't test this as I don't have said filament) but they don't want to raise a PR, that PETG HF RFID tags that are supported on Bambu Studio are not supported on Orca Slicer. 

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

I would like PETG-HF RFID Bambu spool tags to be recognised by Orca Slicer, please.

### Describe alternatives you've considered

N/A

### Additional context

SORRY I misunderstood the original party's issue and searched for PETG-CF and only updated to HF later which already has a great issue raised with profiles attached.  Therefore you can ignore this request.

**Comment by Choku81** [comment]
Bambu Studio doesn't even support PETG HF, I've only gotten PETG HF to work on the mobile app.

I'd like to upvote this as Printing with PETG HF seems tough right now.

**Comment by inhumantsar** [comment]
@Choku81 i don't have it installed but bambu studio apparently does support it. comes down in a configuration update that's offered at startup.

thankfully a kind soul in this [thread](https://forum.bambulab.com/t/petg-hf-print-profiles/88834/11) diffed the generic PETG and official PETG-HF profiles in case anyone wants to create a custom profile for now:

![image](https://github.com/user-attachments/assets/40cbf479-b45f-4ccc-95e0-d701461cd04c)
