### ISSUE TITLE
Weird inner wall placements and overhang walls sticking out

### ISSUE THREAD

**Issue by Azio-Pantheon** [SoftFever/OrcaSlicer#6472]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

Windows

### OS Version

Windows 11

### Printer

Anker M5 0.6 nozzle(and some other printers)

### How to reproduce

Using the following settings:
- Printer: Anker M5 0.6 nozzle
- Filament: Anker Generic PLA+
- 0.20mm Optimal 0.6 nozle @Anker.json

1. import the STL
2. Slice

### Actual results

Some inner walls stick out and there are long overhang walls attached to them.
![image](https://github.com/user-attachments/assets/38f9c7e4-3263-4008-8510-b69a9839f67c)

### Expected results

G-code should look good. No obvious errors.

### Project file & Debug log uploads

[innerwall_overhang_bug.zip](https://github.com/user-attachments/files/16629593/innerwall_overhang_bug.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Anything else?

1. This issue exists on other printer settings too, but not all of them. I tried MyKlipper 0.4 nozzle/My Generic ABS/0.20mm Standard @MyKlipper. It also has the bug.
2. Scaling the part has an effect on the bug. Sometimes it makes the bug appear more, sometimes less:
![image](https://github.com/user-attachments/assets/9f386d5f-a05b-4000-bb43-b1a1687f02ed)
3.  Rotating the object around Z fixes the bug completely. I tried many angles, only the default angle has this bug.

**Comment by Ergonomicmike** [comment]
Confirmed here using 0.20mm Standard Creality Ender 3V2 Process. Similar to what the OP posted.

(I had only one "stick out" when using my custom Process.) 

Running the stl thru the online stl repair tool didn't change this behavior.

**Comment by igiannakas** [comment]
Cannot replicate on 2.2-dev. Could you download the nightly and test with it please? Also attaching a project file is important to recreate your specific settings please.

My project file with your model attached: 
[innerwall_overhang_bug.3mf.zip](https://github.com/user-attachments/files/16677556/innerwall_overhang_bug.3mf.zip)

![image](https://github.com/user-attachments/assets/6f96f5ba-b6a7-4a02-a624-e02c60486415)

**Comment by igiannakas** [comment]
OK replicated. Enable one wall top surface and the issue should be gone but this is an STL issue - 200+ degeneracies identified by mesh inspector.com

Attached is the repaired file which slices correctly with default settings.

[innerwall_overhang_bug_repaired.stl.zip](https://github.com/user-attachments/files/16677682/innerwall_overhang_bug_repaired.stl.zip)

**Comment by igiannakas** [comment]
![image](https://github.com/user-attachments/assets/fc05730b-34e5-4d84-8a74-bd29118c095e)

**Comment by Ergonomicmike** [comment]
@igiannakas I had wondered if it was a problem with the model. So I ran it thru the [free on-line stl repair tool](https://www.formware.co/onlinestlrepair) and ran the fixed version. No change. So I suppose I should be using mesh inspector instead?

**Comment by igiannakas** [comment]
Yeah I personally find that to be a decent tool for repairs. However ideally it should be prevented during cad in the first place, if possible…
