### ISSUE TITLE
Top layer only partially generated

### ISSUE THREAD

**Issue by mikljohansson** [SoftFever/OrcaSlicer#6489]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

Linux

### OS Version

Ubuntu

### Printer

Elegoo Neptune 4 Plus

### How to reproduce

The attached ZIP file contains the STL and machine, filament and process configurations. Just import the model, config and slice it to see the issue on the top layer.

### Actual results

Importing the STL in OrcaSlicer 2.1.1 and slicing it with the configuration produces a partial top layer. See the screenshots and the gcode file contained in the ZIP

### Expected results

The top and bottom surfaces of the model are parallel, so I'd expect the top layer to be full

### Project file & Debug log uploads

[orca-partial-layer-bug-report.zip](https://github.com/user-attachments/files/16647869/orca-partial-layer-bug-report.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Anything else?

![Screenshot from 2024-08-18 11-23-17](https://github.com/user-attachments/assets/c61ee823-7f5e-4a29-8e45-cfbbe58a8b78)
![Screenshot from 2024-08-18 11-21-33](https://github.com/user-attachments/assets/6712106b-37d6-40cb-b9be-a3c4d996b779)
![Screenshot from 2024-08-18 11-21-21](https://github.com/user-attachments/assets/10a97d66-8930-4f80-87ad-560165e8c9f4)
![Screenshot from 2024-08-18 11-21-00](https://github.com/user-attachments/assets/e1848c7b-7058-4fa4-a041-ec0ce660a100)

**Comment by DVSVIDEO** [comment]
I downloaded your model, sliced and diced it and experienced no problems.
This could be your problem.
Setup or placement problem. It happens when the surface is slanted.
![gear](https://github.com/user-attachments/assets/e74a6aa5-efe4-473c-a3f9-cc651bc5178e)

**Comment by mikljohansson** [comment]
Thanks for the feedback! I notice that you're using a 0.2mm layer height and not the config I attached. I can only reproduce this issue when setting the layer height to 0.12mm or 0.16mm, perhaps you could try adjusting your layer height?

The top and bottom surfaces of the model are 100% parallel in the CAD program (I've even measured it there now), but I guess perhaps the STL export could be off (I'm using OnShape).

**Comment by mikljohansson** [comment]
Indeed, it seems that the OnShape export was the issue. When exporting with Y-axis up the issue disappears, so it was some vertices that were bad in the STL. Thanks for helping me figure this out
