### ISSUE TITLE
Remove auto-save as default and do not allow new printers to be imported when importing .3mf files and/or make a default printing template

### ISSUE THREAD

**Issue by Barringtonink** [SoftFever/OrcaSlicer#6497]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

If I download a .3mf file from makers world or somewhere else because I like the design, but it has not been designed specifically for my printer, if I drag it to Orca slicer, Orca slicer will import all of the settings, including the printer (that I don't have) AND/OR the AMS unit that I don't have.  The worst part is that it changes the bed size (I have a mini and not many .3mf files are specifically for the mini, so I will download whatever is available.  Now my bed size has changed but I really didn't notice until I go to print and now I found out all my settings and tweaking have to be redone)

Further compounding issues is that "Auto backup" is set as default so it automatically saves all of these settings for a a printer/AMS/bed I don't have, and now my slicer thinks I have several printers when in reality I don't.

Also I like being able to select all my latest downloads and drag them into the slicer directly from explorer without every object retaining all the different printers and settings.

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

I understand that part of the .3mf file format is the ability to save precise settings for your printer and/or filament, but if I just happen to like the model and I am ok with using my own settings, I should be able to bring in the file and have the option to not also import the settings.

Acceptance criteria:

- A pop up message asking to import settings or just .stl file(s)
- A pop up message asking to switch to AMS or multi-filament printing or just import everything as the same color
- A pop up message asking whether to change the filament (Handy if you do want to use AMS but pick your own filament, OR if the model specifically requires TPA, PETG, etc)
- An ability to use a default import template, possibly even a standard .3mf file that has everything you've already customized for whenever you are creating a new project and/or opening a .3mf or multiple .3mf files at once that will not change based on the settings contained in .3mf
- Turn off default auto-save (auto backup) so that I can go back to my file if I made some crazy changes or importing did something I did not intend.  
- Alternatively, Split auto backup into "auto-recovery" and "auto-save" to be more like MS Office, where it backs up a separate file that you can then recover if necessary, but does not save the current  one.  And then auto-save will save the current file for people who enjoy that feature.
- Enhance the language when a .3mf will change the settings.  As a new user I did not understand what current or new template meant, or that it was changing my default settings.  I couldn't figure out which one was changing.  I think a simple clarification in each language would help.  

### Describe alternatives you've considered

Right now I have a default .3mf file that I created that has all of my regular settings that I must open when I load the slicer.  From there if I drag in any .3mf files I **do** get a popup asking if I just wish to load the geometry.  (So I know the tech already exists).  

However for the first 2 weeks as a brand new user I had no idea I could do this or needed to do this and kept wondering why all my settings kept changing and the files were being saved and I was unable to go back, and why new printers were being saved, and how I had to keep deleting filament colors because I only have one color.

If any of these options currently exist please let me know.  Again I am a fairly new user.  The software is great I think it could just use some additional options for someone who only has one printer, one nozzle, one filament.

Thank you so much for your consideration

**Comment by igiannakas** [comment]
What I typically do is add a cube on the platter, then drag the 3mf file that I want to open in the platter. It will ask whether to open the project or just import geometry. I simply choose to import the geometry only. Thatway my settings remain unchanged and the object is imported correctly.

(not sure if the cube is needed any more but its a habit I've developed :)).
