### ISSUE TITLE
Changing Filament doesn't change object's color

### ISSUE THREAD

**Issue by dumuzi262** [SoftFever/OrcaSlicer#6509]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

Windows

### OS Version

Windows 11

### Printer

CRS10S (with Enraged Rabbit)

### How to reproduce

1.  Have an entire collection of filaments with their colors specified
2.  Switch to a different filament
3.  The object color does not switch to match the new filament

### Actual results

The object color has to be manually changed to match the filament color every time

### Expected results

In prior versions of Orca Slicer, when the filament changed, the object color changed to match the filament.  This made setting up elaborate multi-color prints much easier and made sure color matching was as close as possible without having to manually go in and match up custom colors between filament and object display.

### Project file & Debug log uploads

This appears to just be the default operations now with the slicer.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by zv0n** [comment]
I can confirm this behavior as well. Some additional notes for my case:

- this only happens with custom filament
  - if I switch to a copy of a "Generic" filament, the color changes
  - if I switch to a custom filament, the color doesn't change
- color changes when I switch to a custom filament in "Filament settings" dialog
