### ISSUE TITLE
Add ability to increase numbers of extruders, for IDEX support

### ISSUE THREAD

**Issue by GiantGlory** [SoftFever/OrcaSlicer#653]
No support of two of more extruders/tools, for example cant have two diffrent print tempetures. Like how it works in PS or SS

**Comment by hliebscher** [comment]
i have running no problem .... add a second filament with other temp that work fine

**Comment by GiantGlory** [comment]
Tempeture is just an example, cant run diffrent nozzle sizes for example or tempeture/ fan offset

**Comment by hliebscher** [comment]
no ... different nozzle sizes  is with filament settings not possible only flow ratio  but the line size  not
