### ISSUE TITLE
Setting Retraction Length when switching material crashes nightly build

### ISSUE THREAD

**Issue by ansonl** [SoftFever/OrcaSlicer#6531]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.2.0-dev

### Operating System (OS)

Windows

### OS Version

Windows 10

### Printer

Ultimaker 2

### How to reproduce

1. Open printer profile settings
2. Change Length under Retracting when switching material to 16mm
3. Click somewhere else to unfocus the textbox

### Actual results

OrcaSlicer crashes

### Expected results

OrcaSlicer doesn't crash and you can go edit other printer settings

### Project file & Debug log uploads

[crash_Wed_Aug_21_21_46_50_0.zip](https://github.com/user-attachments/files/16705491/crash_Wed_Aug_21_21_46_50_0.zip)
[ddg-coupler-Body.zip](https://github.com/user-attachments/files/16705494/ddg-coupler-Body.zip)

### Checklist of files to include

- [x] Log file
- [x] Project file

**Comment by Ergonomicmike** [comment]
Already reported. Search the Issues for the word "crash."
https://github.com/SoftFever/OrcaSlicer/issues/6486
