### ISSUE TITLE
custom settings not saving after closing application 

### ISSUE THREAD

**Issue by Peewee0512** [SoftFever/OrcaSlicer#6545]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

Windows

### OS Version

windows 11 

### Printer

elegoo neptune 4 plus 

### How to reproduce

go to filament settings and change something then closes the application and its gone or how when I add Bambu filament it won't let me use it with the elegoo and it defaults to abs filament also the slicer closes after i change the flow to one and try to slice the flow test 

### Actual results

well i have to input the same data i need to everything all the time 

### Expected results

I wish I could like to have a account and it's all saved and use Bambu default filament setting with thee elegoo printer 

### Project file & Debug log uploads

N/A

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by mojamuto** [comment]
Hi, I have the same problem on linux, I am using the latest dev version, but the problem still exists.
