### ISSUE TITLE
Perspective view get strange on very large printer (Elegoo Giga)

### ISSUE THREAD

**Issue by tlhintoq** [SoftFever/OrcaSlicer#6556]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.2.0 - dev

### Operating System (OS)

Windows

### OS Version

Win10x64

### Additional system information

![StealthDeck_DeviceManager](https://github.com/user-attachments/assets/4ef54624-434e-4207-b1fc-d9faf1f2eae0)

### Printer

Elegoo giga

### How to reproduce

Machine definition of 800x800x1000
Printable height 1000
Lid height (as there is no lid) is 1000

Start any job then scroll, pan etc.  
The more you rotate, pan and generally fly around the more the perspective view goes out of whack

### Actual results

The more you rotate, pan and generally fly around the more the perspective view goes out of whack
![2024-08-25_10-11-37](https://github.com/user-attachments/assets/429a0810-e9a9-49d6-ba09-4ec48099a7f2)

### Expected results

Not to go so out of whack

### Project file & Debug log uploads

You can do this with any part - its not model specific

### Checklist of files to include

- [X] Log file
- [X] Project file

### Anything else?

You can do this with any part - its not model specific

**Comment by TNTBA** [comment]
https://github.com/TNTBA/OrangeStorm-Giga-Profile-for-Orca
