### ISSUE TITLE
OrcaSlicer (latest version) incompatible and unusable after macOS 14.5 upgrade

### ISSUE THREAD

**Issue by loganclear** [SoftFever/OrcaSlicer#6559]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

macOS

### OS Version

14.5

### Additional system information

Mac mini M2

### Printer

Creality K1C

### How to reproduce

Software disappears from the application list

### Actual results

-

### Expected results

-

### Project file & Debug log uploads

-

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by TinyMito** [comment]
Make sure you download the ARM version.

![Screenshot-August-d0fXI4BE](https://github.com/user-attachments/assets/957c105d-dbd8-48d5-b990-065b3a709064)

**Comment by loganclear** [comment]
Prior to the macOS upgrade, Orca Slicer was functioning correctly. However, immediately following the system update, macOS generated an error related to Orca Slicer. As a result, the application became inoperable and simultaneously disappeared from the list of installed applications. This issue occurred on both my Mac mini and MacBook Pro.

**Comment by Noisyfox** [comment]
Try the latest nightly build.

**Comment by loganclear** [comment]
Same Error：
The operation could not be completed because one or more required items could not be found.
(Error code -43)

**Comment by Noisyfox** [comment]
Also, maybe try upgrading to macOS 14.6?

**Comment by loganclear** [comment]
I found a solution. Placing Orcaslicer outside of the "Applications" folder allows it to work, as the current version cannot be dragged into the "Applications" folder.

**Comment by Noisyfox** [comment]
> I found a solution. Placing Orcaslicer outside of the "Applications" folder allows it to work, as the current version cannot be dragged into the "Applications" folder.

That's even more mysterious...
