### ISSUE TITLE
Sub top layer defective (2.2.0-dev)

### ISSUE THREAD

**Issue by TinyMito** [SoftFever/OrcaSlicer#6569]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.2.0-dev

### Operating System (OS)

macOS

### OS Version

14

### Printer

X1C

### How to reproduce

1. I attached the 3MF file.
2. Go to layer 15.
3. That is the top surface before the text layers.
4. You can see all the random nozzle movement over the top layer (sub top layer).

### Actual results

![Screenshot-August-BhHKK75f](https://github.com/user-attachments/assets/307acc67-c586-47a5-bb3e-c52e31462364)

![Screenshot-August-Np9ZbCxx](https://github.com/user-attachments/assets/e616e211-fc65-48a6-a92e-cadcda27bb57)

### Expected results

This is from Bambu Studio.

![Screenshot-August-imO181nK](https://github.com/user-attachments/assets/9fb230c3-3c65-494b-9823-34adac1a6675)

### Project file & Debug log uploads

[KeyTag_Test.3mf.zip](https://github.com/user-attachments/files/16750005/KeyTag_Test.3mf.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by igiannakas** [comment]
Try the build from this PR here: https://github.com/SoftFever/OrcaSlicer/pull/6236
