### ISSUE TITLE
Texture placement doesn't match the bed model, previous version 1.9.0 made more sense

### ISSUE THREAD

**Issue by SO-cyk** [SoftFever/OrcaSlicer#6576]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

Windows

### OS Version

no

### Printer

Creality K1/ InfiMech TX

### How to reproduce

In the previous version 1.9.0, textures could be displayed on the outside of the platform area, matching the manufacturer's stl model.
Whereas in version 2.1.1, textures can only be displayed on the inside of the platform area, offset from the factory stl model. The display is not as good as it could be
![K1 1 9 0](https://github.com/user-attachments/assets/3cb1f44f-ade4-4680-b811-2d4369e8e0e2)
![k1 2 1 1](https://github.com/user-attachments/assets/3bfe0901-79a1-4ab8-b17a-f01f3fc47be4)
![INFIMECH 1 9 0](https://github.com/user-attachments/assets/41160f2e-b621-42f0-b4d4-69b6dee9771d)
![INFIMECH 2 1 1](https://github.com/user-attachments/assets/a61906c2-eb87-4787-8bc9-3c7e5d8bb69f)

### Actual results

The display can be optimised to be more aesthetically pleasing. Conformity with reality

### Expected results

The display can be optimised to be more aesthetically pleasing. Conformity with reality

### Project file & Debug log uploads

[Untitled.zip](https://github.com/user-attachments/files/16758898/Untitled.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Hammerfest** [comment]
"more aesthetically pleasing"

If your aligning to grid lines, its more then just aesthetically pleasing, that is actually kinda nuts, ive kept my profiles from 1.8 or 1.9, ill have to force clear to see this to find out if my printers are impacted as well

**Comment by ilko-k** [comment]
same as https://github.com/SoftFever/OrcaSlicer/issues/5883 ?

**Comment by SO-cyk** [comment]
> same as #5883 ?

Related to this issue, this issue all feeds back that the bed model and textures are shifted.
What I'm trying to feed back is that the logic for texture placement is glitching, and through observational testing the current version of the textures only show up within the print platform area. Although this does not affect slicing, just aesthetics.
