### ISSUE TITLE
Extend options 'Reverse on odd' to apply to all walls, not just overhangs

### ISSUE THREAD

**Issue by ImagineerNL** [SoftFever/OrcaSlicer#6581]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I'm printing a lot in Nylon, ASA and ABS.
All of these materials are very prone to warping.
The explanation that is given in the tooltips under Overhangs --> Reverse on Odd / Reverse only internal perimeters describes the usefulness for reverse perimeters for better overhangs, but ALSO for reducing internal stresses and thus reducing warping.
(ps; the tooltip under 'only internal' is more descriptive than 'reverse on odd', while the 'only internal' can only be enabled _after_ you first select the 'reverse on odd'.

![image](https://github.com/user-attachments/assets/97303b82-98f2-4fd4-9a4e-4c05bc205626)

![image](https://github.com/user-attachments/assets/da977bf5-b305-4dbf-9082-f00318d5e708)

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

It would be great if the option to reverse the wall direction on odd layers could be enabled for normal printing as well.
The option could then be under Walls and surfaces:
- Reverse wall on odd | ☐
- Reverse only internal perimeters | ☐
- Reverse only Overhang perimeters | ☐

or where it currently is under Overhangs:
- Reverse wall on odd | ☐
- Reverse only internal perimeters | ☐
- Reverse ALL wall perimeters | ☐

### Describe alternatives you've considered

I've tried a lot to counter warping; it just seems a hit and miss and if the theory is correct, it might probably help against warping

**Comment by discip** [comment]
@ImagineerNL
What you are asking for is already there, you just need to set the **`Reverse threshold`** to **`0`**.
For reference see the 'tooltip' of **`Reverse threshold`**.

Please close this issue as what you are requesting is already present. 😊

**Comment by impeeza** [comment]
> [@ImagineerNL](https://github.com/ImagineerNL) What you are asking for is already there, you just need to set the **`Reverse threshold`** to **`0`**. For reference see the 'tooltip' of **`Reverse threshold`**.
> 
> Please close this issue as what you are requesting is already present. 😊

Sorry for reply on a closed issue, but on Orca Slicer 2.3.1  The «Reverse on Odd» setting now is called «Reverse on even».

But I can not find the «Reverse threshold» setting, if you search for the setting on the magnification glass at right of process profile

<img width="421" height="92" alt="Image" src="https://github.com/user-attachments/assets/3432dae5-1fa0-41e0-850d-7b73874ae62a" />


<img width="434" height="225" alt="Image" src="https://github.com/user-attachments/assets/89936017-b1d7-44a3-87dc-120410678e21" />


the most near is: «Overhangs : Overhang reversal threshold»

but selecting it on the list take you to the correct section but no setting with that name is shown:

<img width="401" height="692" alt="Image" src="https://github.com/user-attachments/assets/9bf99c9b-1a43-44cd-bb86-5ca7202adcbc" />

How that setting is edited? or, It is a setting you need to edit manually on the file?

**Comment by discip** [comment]
@impeeza
If you don't tell the planer to reverse layers, what would the threshold be good for, even if you were able to set it? 😊

First enable **`Reverse on odd`** and then you will be able to set the relevant threshold.

**Comment by discip** [comment]
@impeeza
If you don't tell the planer to reverse layers, what would the threshold be good for, even if you were able to set it? 😊

First enable **`Reverse on even`** and make sure that **`Reverse only internal perimeters`** is disabled, as the threshold is not relevant otherwise, because the outermost perimeter is not affected, as the name implies.
