### ISSUE TITLE
Ability to change colors of pre-painted 3mf

### ISSUE THREAD

**Issue by Doogle03** [SoftFever/OrcaSlicer#6603]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Pre-painted 3mf files have pre-set tool numbers.  Would like ability to change which tool is applied to painted areas. (everything painted white, I now want painted black, but black is already loaded on tool 4 and file is painted with tool 1)

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

Would like the ability to change which tools are applied to pre-painted 3mf files.  

Eg. File comes pre-painted with 3 colors, selecting tool 1 through tool 3, but want to use the colors on other tools.  Have option to change all portions painted with tool 'x' and replace with tool 'y' without needing to repaint or attempting to complete a manual recolouring with the fill tool in slicer.

### Describe alternatives you've considered

Manually trying to re-paint file could result in some areas not properly being changed, fill tool does not catch all portions of previous color.  It is very tedious and prone to error

### Additional context

![image](https://github.com/user-attachments/assets/ce1bcba7-1640-4754-b4d7-11ae3beed68f)

Pre-painted file, want to change colors to different tools via drop-down box.  Change all white to black, change all yellow to white, change all pink to brown

**Comment by adrianbear** [comment]
I'd like to give this a +1 please

**Comment by buergi** [comment]
I think this issue is already implemented. In color painting mode click "Remap filaments" to re-map the filament colors

<img width="241" height="565" alt="Image" src="https://github.com/user-attachments/assets/95bdda5e-b84b-4fa1-a7fb-74fdc5b0b207" />

Has been introduced by https://github.com/OrcaSlicer/OrcaSlicer/pull/10303
