### ISSUE TITLE
CLI Assembly process fails with Segmentation fault: 11

### ISSUE THREAD

**Issue by rizwansarwar** [SoftFever/OrcaSlicer#6611]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

macOS

### OS Version

Sonoma 14.5

### Additional system information

Apple MAC M1

### Printer

Prusa MK3S

### How to reproduce

Could not attach STL's but it is just disc primitive exported from OS. 

1) Run the attached command using the attached, generic_pla_p1p.json, process_mk3s_0.2.json, machine-MK3S.json.json and Assembly-Orca.json.
/Applications/OrcaSlicer.app/Contents/MacOS/OrcaSlicer --export-3mf Desktop/test.3mf --load-settings="machine-MK3S.json;process_mk3s_0.2.json" --load-filaments="generic_pla_p1p.json" --filament-colour="#000000" --load-assemble-list="Assembly-Orca.json" --debug 5

[Assembly-Orca.json](https://github.com/user-attachments/files/16819755/Assembly-Orca.json)
[process_mk3s_0.2.json](https://github.com/user-attachments/files/16819765/process_mk3s_0.2.json)
[machine-MK3S.json](https://github.com/user-attachments/files/16819769/machine-MK3S.json)
[generic_pla_p1p.json](https://github.com/user-attachments/files/16819771/generic_pla_p1p.json)

2) 
The process fails with Segmentation Fault 11.

### Actual results

The process fails with Segmentation Fault 11. See crash log
[orca_crash.log](https://github.com/user-attachments/files/16819775/orca_crash.log)

### Expected results

It should generate a test.3mf file. 

Please note that this process works in bambu studio. 

### Project file & Debug log uploads

[orca_crash.log](https://github.com/user-attachments/files/16819790/orca_crash.log)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Anything else?

**The above process works in Bambu Studio 1.9.5.51. I have also tried the Nightly Orca release with same error.**

**Comment by rizwansarwar** [comment]
No comments on this? Surely this at least deserves curiosity?

**Comment by SANCHES-Pedro** [comment]
@rizwansarwar did you find a solution?
