### ISSUE TITLE
Color sequence not respected when print sequence is by object

### ISSUE THREAD

**Issue by andreaselias** [SoftFever/OrcaSlicer#6615]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

macOS

### OS Version

Sonoma 14.4.1

### Printer

Bambu A1

### How to reproduce

Add 2 different models to the plate, one with multiple colors.
On the plate settings set the print sequence by object
Select the color sequence

### Actual results

First model that has a solid color prints as expected
Second model print with a color different from the one selected

On the attached image we can see that the green color is printed first then the yellow and red last even though I set to print the red first

![Screenshot 2024-08-30 at 19 36 19](https://github.com/user-attachments/assets/076d6aa3-53d5-4e3d-9373-5bec4ef0b079)

### Expected results

Print the defined sequence as bambu studio does

![Screenshot 2024-08-30 at 19 50 20](https://github.com/user-attachments/assets/0bdc7f5b-2a56-4fdd-95ff-d270dde99fd2)

### Project file & Debug log uploads

[debug_Fri_Aug_30_19_02_00_9758.log.0.zip](https://github.com/user-attachments/files/16822593/debug_Fri_Aug_30_19_02_00_9758.log.0.zip)
[Mathematicus little 1x1.3mf.zip](https://github.com/user-attachments/files/16822595/Mathematicus.little.1x1.3mf.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by Noisyfox** [comment]
Could you provice the 3mf from BBS as well?

**Comment by Noisyfox** [comment]
![image](https://github.com/user-attachments/assets/28d635bf-21a1-42ef-8579-15a0f0ebe2e7)
As you can see, BBS has the same issue as Orca unfortunately.

**Comment by andreaselias** [comment]
Well I thought I was going crazy but I found why it showed the correct print sequence in my original post. If I set the correct order in the filament section it slices correctly. So it looks like that the color order is been ignored when the print sequence is by object.

Wrong order in the filament section
![Screenshot 2024-09-06 at 10 35 52](https://github.com/user-attachments/assets/31b4fa09-36e3-4508-8c51-3dd7cae45992)

Correct order in the filament section
![Screenshot 2024-09-06 at 10 33 20](https://github.com/user-attachments/assets/43bfe6d6-1294-4c47-b9b0-b590a9ef7888)

**Comment by Noisyfox** [comment]
Could you try the PR build and see if that solves your problem?

**Comment by chrpoe** [comment]
Hey there,
I was searching and trying and testing - and I can confirm:
When "Print by Object", rather than "Print by Layer", the "First Layer Filament Sequence" is ignored.

The filament sequence for other layers works as specified.

So the bug only happens for:
/ Print by Object
/ First Layer Filament Sequence
