### ISSUE TITLE
Tree Support - Hybrid not supporting flat overhangs properly?

### ISSUE THREAD

**Issue by Arakon** [SoftFever/OrcaSlicer#6618]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

Windows

### OS Version

Win 11

### Printer

Bambu A1

### How to reproduce

- Enable Tree Supports Hybrid
- Slice a model with 90° overhangs
- The result is a barely supported surface

### Actual results

The overhang is barely supported, with lots of tiny support tips that are highly likely to get torn off when bridging.
![image](https://github.com/user-attachments/assets/103ebdad-0b58-49cb-9d8c-16db9cfc94ef)

### Expected results

Similar to Tree Organic, a full and supported top interface should be created between layer and supports:
![image](https://github.com/user-attachments/assets/c9398db7-2eb2-4023-b866-b1e5849f7a0f)

### Project file & Debug log uploads

[treesupport.zip](https://github.com/user-attachments/files/16824056/treesupport.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by ichisaur** [comment]
I can confirm that this weirdly deviates from Bambu Studio.

Hybrid support in Bambu Studio produces a standard style support for the flat area and square tree supports with "On Build Plate Only" Disabled
![image](https://github.com/user-attachments/assets/8ff32987-9a24-4709-adbb-aa53d7f26fdb)
![image](https://github.com/user-attachments/assets/c9ed2288-e555-4450-8423-ad2bce329e9b)

In Orcaslicer, with "On Build Plate Only" enabled, you get a forest of tree branches. 
![image](https://github.com/user-attachments/assets/3a7ddc8e-8c1c-4ea6-b2c0-ba0159e3050c)


In Orca, with "On Build Plate Only" Disabled, it is a more standard grid, but no square trees, and standard grid for levels. 
![image](https://github.com/user-attachments/assets/9857e72d-7cc8-46dc-93d1-79eebdec01dd)

The "On Build Plate Only" behavior is not replicated in Bambu Studio.

**Comment by roxorplox** [comment]
This needs to be re-opened. Hybrid Tree supports arent functioning properly.
