### ISSUE TITLE
[Feature Request] "reload from disk" shortcut

### ISSUE THREAD

**Issue by FillPavS** [SoftFever/OrcaSlicer#662]
Hello! I just switched from superslicer. And I did not find that the F5 hotkey responsible for updating the model on the table (reboot from disk) does not work. I very often make changes to the model and then watch how it is sliced to select the best result or when you just need to increase the gap. Now, to update the model, you need to switch the tab from global to objects, right-click on the object and select update, or in the preparation window, right-click on the model and select this item. Please make it possible to update with one button. It was very convenient to press F5 and Ctrl+R right in the preview window to instantly get an update

![fb457ca009bb6cf20d57746168d94f03fc8db954_2_690x388](https://user-images.githubusercontent.com/17209082/230304373-260771b1-9897-4c4d-bd77-c3cf903d5987.png)

**Comment by radicalgale** [comment]
This is a very good idea. I use "Reload from disk" feature a lot. It shouldn't be that hard to update the model. Cura detects changes automatically, SuperSlicer allows updating the mesh by pressing F5. It is very useful for rapid prototyping.

**Comment by jbjhjm** [comment]
With the objects explorer view being hidden within Process > objects, such a shortcut becomes even more important. I too think it should be reintroduced.
