### ISSUE TITLE
Add the ability to unset the default color in a filament profile

### ISSUE THREAD

**Issue by Chewieez** [SoftFever/OrcaSlicer#6629]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Bambu Studio does not let you unset the default color selection in a filament profile. This has been reported in the Bambu Labs Github page since Sept 2023 but no fix has been released. I think this could be a great improvement that Orca could offer. 

Bambu Lab Github Issue: https://github.com/bambulab/BambuStudio/issues/2545

### Which printers will be beneficial to this feature?

Others

### Describe the solution you'd like

You should able to delete the selected color from the UI.

### Additional context

Currently the only method I've found to unset a default color selection in a filament profile is to locale the .json file and delete the lines required.

**Comment by verkligheten** [comment]
Any updates on this?
