### ISSUE TITLE
multitool head temperature is always 0 degrees.

### ISSUE THREAD

**Issue by suno7z** [SoftFever/OrcaSlicer#6630]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.2.0-dev

### Operating System (OS)

Windows

### OS Version

windows 11

### Printer

voron tridex

### How to reproduce

When selecting the second tool head

### Actual results

![220](https://github.com/user-attachments/assets/c421e055-2bb8-46c7-bbfe-33383e64dc63)

The first tool head is normal

### Expected results

idex!!! 

### Project file & Debug log uploads

[bedmesh.zip](https://github.com/user-attachments/files/16829269/bedmesh.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by SoftFever** [comment]
Multi tool machine need some special "start machine gcode" to handle the preheat logic.
You can use the built-in MyToolChanger profile for your IDEX machine
Or copy start gcode to your profile
