### ISSUE TITLE
Arachne printing midair

### ISSUE THREAD

**Issue by rocketman768** [SoftFever/OrcaSlicer#6655]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

macOS

### OS Version

23G93

### Printer

Bambu x1 carbon

### How to reproduce

Open attached 3mf, slice, go to layer 106. See midair print.

![midair](https://github.com/user-attachments/assets/3e34aa95-8af4-4d47-bab4-f607214bf6a1)

### Actual results

There is a line printed completely in midair.

### Expected results

Not printing in midair.

### Project file & Debug log uploads

[midair.3mf.zip](https://github.com/user-attachments/files/16883552/midair.3mf.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by boromyr** [comment]
![image](https://github.com/user-attachments/assets/2b99660e-4cec-47a1-b953-7a3a5c7515b0)
found by me too
