### ISSUE TITLE
Post-processing is being processed twice

### ISSUE THREAD

**Issue by H4kunaM4tata** [SoftFever/OrcaSlicer#667]
I have klipper_estimator like so: `klipper_estimator --config_moonraker_url http://192.168.1.36 post-process`

And a script to fetch the new time and add to the file like so: ` ./time.sh fan_0.32mm_PLA_TIME_170g.gcode`

But the name gets all weird.

![2023-04-06_20-09](https://user-images.githubusercontent.com/35049512/230346873-91de0de1-79ce-49c8-a3d7-3ee2862be714.png)

As you can see, it is being processed twice
The others were sliced with PS and they are just fine.

![2023-04-06_20-07](https://user-images.githubusercontent.com/35049512/230346963-0a1991d0-133d-4ccb-8392-0558ab3b16a1.png)

With PS it works just fine. Delete the file, slice it and run the script.
One change only, not twice.

![image](https://user-images.githubusercontent.com/35049512/230347644-8044f82f-c180-42ca-8185-ea83a12a7985.png)

**Comment by H4kunaM4tata** [comment]
The work around to avoid manual stuff is to filter only the first line like so: `cat fan_0.32mm_PLA_TIME_170g.gcode | grep normal | awk '{print $8 $9}' | head -n 1`

**Comment by SoftFever** [comment]
What does it look like without using klipper_estimator ?

**Comment by H4kunaM4tata** [comment]
> What does it look like without using klipper_estimator ?

The file name as usual: `fan_0.32mm_PLA_TIME_170g.gcode`

The script does nothing more than check the gcode for the time that klipper_estimator adds to the file and append it to the filename.

**Comment by H4kunaM4tata** [comment]
> What does it look like without using klipper_estimator ?

@SoftFever I think that I didn't reply to your question properly.

With or without having the klipper estimator, OrcaSlicer GCODE file have both lines:

![image](https://user-images.githubusercontent.com/35049512/230808940-8cffa936-a9f2-4be4-8971-aa40ec5f799d.png)

![image](https://user-images.githubusercontent.com/35049512/230808963-32ea1ad4-255b-4d82-93c4-affa2aa18fe1.png)

PrusaSlicer GCODE it is only present once

![image](https://user-images.githubusercontent.com/35049512/230809005-0763c154-f956-45c1-b9d6-24287456ffc9.png)

Fix: remove the extra time from the start file, that is the extra piece of information and it is not needed. 

**For what matters, ignore the time difference. Totally not relevant here.**

**Comment by SoftFever** [comment]
Thanks for reporting it.
The estimation comment is written twice. It will be fixed in the update.

**Comment by H4kunaM4tata** [comment]
Awesome, thank you for checking this.
