### ISSUE TITLE
GPU coil whine still present in 2.2.0 prepare window (unusually high GPU usagee)

### ISSUE THREAD

**Issue by dfbpurcell** [SoftFever/OrcaSlicer#6676]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.2.0

### Operating System (OS)

Windows

### OS Version

Win 11 Pro Latest patch

### Additional system information

CPU- AMD 5950x 
GPU - 6900xt
32gb ddr4 

### Printer

k1 max

### How to reproduce

This was a problem in previous versions in the preview window. It is still present in the prepare window when performing certain actions like hovering the mouse over the toolbar (the toolbar above the bedplate for manipulating objects)

### Actual results

GPU spikes and makes coil whine-ish sounds 

### Expected results

Fix high GPU usage, sound should not be present

### Project file & Debug log uploads

Does it on any project

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by MallocArray** [comment]
I also notice high GPU usage and temperatures if I let my computer idle and turn on the screensaver when on the Preview pane.  Going to Prepare does not result in the same issue.
