### ISSUE TITLE
Object skirt problem

### ISSUE THREAD

**Issue by GlauTechCo** [SoftFever/OrcaSlicer#6688]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.2.0-beta

### Operating System (OS)

macOS

### OS Version

14.2.1 Sonoma

### Additional system information

Macbook Air M1

### Printer

FlashForge M5p

### How to reproduce

Create two objects close together

### Actual results

Skirts should not overlap.
It should give a warning about overlapping.

### Expected results

Skirts overlap.

### Project file & Debug log uploads

<img width="567" alt="Ekran Resmi 2024-09-09 06 03 14" src="https://github.com/user-attachments/assets/d67f512a-b309-47b4-93f5-f03cd832695a">
<img width="469" alt="Ekran Resmi 2024-09-09 06 09 04" src="https://github.com/user-attachments/assets/1cd4233c-9d54-4c9d-a157-e416518c54a5">
<img width="673" alt="Ekran Resmi 2024-09-09 06 10 16" src="https://github.com/user-attachments/assets/77df4eea-8b38-4e9d-b40d-47c8ad0a4632">
<img width="395" alt="Ekran Resmi 2024-09-09 06 09 21" src="https://github.com/user-attachments/assets/f722d489-fb7f-4377-b2d8-2bf4fd41c772">

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by foreachthing** [comment]
This has been discussed many times before. Over on [PrusaSlicer](https://github.com/prusa3d/PrusaSlicer/issues/316) too.
You'd have to "assemble" your parts first. 
Or, don't put them so close together or change skirt distance 🙄

**Comment by GlauTechCo** [comment]
> This has been discussed many times before. Over on [PrusaSlicer](https://github.com/prusa3d/PrusaSlicer/issues/316) too. You'd have to "assemble" your parts first. Or, don't put them so close together or change skirt distance 🙄

The operation may be considered correct, but for amateur users, a pop-up warning should appear to make the conflict visible.
