### ISSUE TITLE
1.6.1 enables aux fan cooling by default on P1P, is this correct behavior?

### ISSUE THREAD

**Issue by dagnarf** [SoftFever/OrcaSlicer#669]
Per release notes - "Enable aux part cooling fan by default for Bambulab P1P, as the aux fan is a standard part of P1P now."

Is this in response to Bambu's offer to extend the P1P early bird items of LED strip and Camera to all P1P buyers? Some buyers have already received their packages from Bambu and there is not an Aux fan included in this bundle, so I believe that component should still be optional. Although, I don't think any harm in trying to run a fan that isn't there?

**Comment by SoftFever** [comment]
There won't be any harm.
It's just a no-op  in that case
