### ISSUE TITLE
Model URL in Project Basic Info

### ISSUE THREAD

**Issue by chaugan** [SoftFever/OrcaSlicer#670]
**Is your feature request related to a problem? Please describe.**
No problem, just new feature so it's easier to remember where the model was from when saving a project

**Describe the solution you'd like**
Add this new line of info, and a "Go!" link at the end so that the url specified opens in the users default browser.

![image](https://user-images.githubusercontent.com/17846743/230431887-877843f8-1db0-4cd4-9e07-3510ca649eed.png)

**Comment by SoftFever** [comment]
I like this idea.
Thanks.

**Comment by bitflung** [comment]
We've regressed: now in OrcaSlicer 1.6.3 the Project tab no longer allows for editing any of the expected fields (this matches the broken behavior of Bambu Studio 1.6.2.4)
