### ISSUE TITLE
Positive part feature to exclude everything else

### ISSUE THREAD

**Issue by Rickthebig** [SoftFever/OrcaSlicer#6701]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I'am always frustrated when...
I have to put and align several negative parts in order to isolate the portion of the model that I wish to print.

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

Allow to add a *positive* part. This means that only the intersection of this part with the current model will be considered for printing. It would be a huge simplification.

**Comment by kylek29** [comment]
I can see where that'd be very useful. As a workaround; if this is a model you made; you can create the negatives in the same CAD software and export them separately with the same origin point. That way you can do a simple import and set it to be negative.

**Comment by Ataraxia-Mechanica** [comment]
In Blender this is called Boolean Intersect if you want to search this technique up.

**Comment by Rickthebig** [comment]
> In Blender this is called Boolean Intersect if you want to search this technique up.

Thus proving that my idea is not so awkward.

I am even surprised that this has not been implemented yet, since it would save a lot of work creating a number of negative parts around, which would be shifted if reloaded (bug?) and would need to be re-aligned...

It is so obvious, and should not overburden the developers.

**Comment by tralston** [comment]
Yes, please do this. Sometimes others post models online and several people who print them say certain parts don't mate/fit well. I will often just print part of a model to test if it fits something else so I don't have to waste time and filament printing the whole thing. It's overkill to have to take someone else's model (especially if .3mf) back into Fusion or another software just to do the boolean intersection operation. Orca already has boolean subtract (negative part), so why not do a boolean intersect?
