### ISSUE TITLE
Auto-reload part from disk on source file change

### ISSUE THREAD

**Issue by mike1808** [SoftFever/OrcaSlicer#6711]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I'm using OnShape as my CAD and the workflow for exporting the parts to the slicer is to export them as STL (or other format) and import them to OrcaSlicer. When iterating on the model I export the parts under the same name and in OrcaSlicer I go to objects browser and click on "Reload from disk" to get the newer version of the part.

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

I want to mark parts to auto-reload them as soon the source file that was used to import them changes. Upon the file change I want the part to get reloaded from the disk.

### Describe alternatives you've considered

1. Manually reload the part on every file change.

**Comment by matti125** [comment]
I added a PR https://github.com/OrcaSlicer/OrcaSlicer/pull/15777 for this. Perhaps this request could be re-opened?
