### ISSUE TITLE
Variable Layer Height resets when manually painting bottom layers

### ISSUE THREAD

**Issue by ZedOud** [SoftFever/OrcaSlicer#6722]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

macOS

### OS Version

Sonoma 14.6.1

### Additional system information

CPU: Intel

### Printer

Elegoo Neptune 4 Max

### How to reproduce

1. Add a primitive
2. Open the Variable Layer Height menu
3. Either click the Adapt button or manually paint (anywhere but the bottom 5%) on the layer representation side bar
4. Manually paint on the bottom most 5% part of the layer representation side bar

### Actual results

Whether layer heights were added from the auto settings (Adaptive + Smooth) or from painting manually, it will reset if you select the bottom most 5% or so to manually paint from the layer representation side bar.

### Expected results

Ideally, it would be selected, modified, and not reset the values already changed.

### Project file & Debug log uploads

[TorusX4 adaptive.3mf.zip](https://github.com/user-attachments/files/16950016/TorusX4.adaptive.3mf.zip)

### Checklist of files to include

- [X] Project file

### Anything else?

I've included a screenshot where you can see (on the right hand side) that I have painted in as much as I could before it resets at the bottom in the area that is still white.
This occurs whether I am using left-click (more layers) or right-click (fewer layers).
<img width="2672" alt="Screenshot 2024-09-10 at 12 19 14 PM" src="https://github.com/user-attachments/assets/5cff6df8-a986-4630-af7b-1bfc72a90bb5">

**Comment by ZedOud** [comment]
Seems to be partly fixed in 2.2.0-beta, as it no longer resets, but the bottom most portion is still not selectable, see #6798

**Comment by SoongJr** [comment]
I just got the same behavior in Orca Slicer 2.3.1
Additionally, the adaptive layers had reset randomly without even being in adaptive layer mode. That's what prompted me to try and re-paint them.
So they were painted before, then suddenly lost that (I was re-positioning, copy-pasting, setting object-specific process values to enable a raft), and from then on trying to do the same painting  provoked the issue described here.

Saving, closing Orca and re-loading the project restored the adaptive layers, and also fixed the resetting. This might actually be a display issue!
Actually, then enabling raft for one of those objects disables adaptive layers:

<img width="498" height="638" alt="Image" src="https://github.com/user-attachments/assets/064005c2-ee14-44ab-a655-e06e07652253" />

The issue also arises again. So for me at least it's reproducible with a raft!
Also means it's probably not the same cause, I should open a new issue, but I'm low on time right now
