### ISSUE TITLE
Pressure Advance Values from the Lidar Scan Displayed

### ISSUE THREAD

**Issue by steezyprintz** [SoftFever/OrcaSlicer#673]
Would be great to get hold of the Pressure Advance Values from the Lidar Scan Displayed in some way.
If it was possible to use the slicer to get hold of it and then display it somehow?

**Comment by LordBoos** [comment]
Yea this will be great! With this it would be possible to do automatic lidar pressure advance and flow calibration and use those values in filament profiles without having to do manual calibration.
