### ISSUE TITLE
"Bed temperature: first/other layer" ws "Print sequence: by object"

### ISSUE THREAD

**Issue by leonchuk** [SoftFever/OrcaSlicer#6731]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

The temperature of the first layer is important for the adhesion of the part. When printing the first layer, it should be as indicated

### Which printers will be beneficial to this feature?

Marlin

### Describe the solution you'd like

If bed temperature for the first level is different, when starting to print a new object, need to use the M190 command instead of M140

**Comment by tome9111991** [comment]
Maybe same issue like

https://github.com/SoftFever/OrcaSlicer/issues/6309

You should set
Bed temperature for other Layer to same like first layer.

**Comment by leonchuk** [comment]
> Maybe same issue like
> 
> #6309
> 
> You should set Bed temperature for other Layer to same like first layer.
Yes, it seems that the source of the problem is also the same.
But in fact the temperature slowly changes while the first layer is being printed, and returns from the second.

Before printing the first layer, need to use the M190 command to change the temperature

**Comment by Maokaman1** [comment]
As a workaround, you can use the following G-code:

Navigate to [Printer Settings] > [Machine G-code] > [Layer change G-code] and add:
```
{if layer_z == first_layer_height}
M109 S[nozzle_temperature_initial_layer]
{endif}
```
