### ISSUE TITLE
Temp calibration wrong start and end temps for TPU

### ISSUE THREAD

**Issue by bjeromin** [SoftFever/OrcaSlicer#6737]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.2.0-beta

### Operating System (OS)

Windows

### OS Version

Windows 10

### Printer

K1C

### How to reproduce

1. Open temp calibration menu
2. Select TPU

### Actual results

TPU start and end temps are showing the PA-CF temps (320 start, 280 end)

### Expected results

Adjust temps for usual TPU print temp range

### Project file & Debug log uploads

[debug_Wed_Sep_11_20_21_57_3280.log](https://github.com/user-attachments/files/16976046/debug_Wed_Sep_11_20_21_57_3280.log)
[debug_Wed_Sep_11_20_21_57_3280.log](https://github.com/user-attachments/files/16976050/debug_Wed_Sep_11_20_21_57_3280.log)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by tlhintoq** [comment]
Dupe of this ticket from 3 weeks ago
https://github.com/SoftFever/OrcaSlicer/issues/6555
