### ISSUE TITLE
Measurement copy to clipboard improvement

### ISSUE THREAD

**Issue by obbert42** [SoftFever/OrcaSlicer#6747]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Yes, while using the Measurment tool in Prepare mode, one is given the option to copy the measurements to clipboard (SS1). Currently this will copy it as a string (i.e. "Distance: 61.242 mm"). The problem lies in when trying to use that copied information elsewhere inside or outside of Orca Slicer. If one attempts to paste the copied measurement to the move feature the resulting paste includes characters which are not accepted as valid inputs (SS2). The only input that feature will accept is either an integer or floating-point number (i.e. "61.242"). Trying to paste the measurement, as is, to an outside program like Windows Calculator results in an Invalid Input error for the same reason.

SS1 - ![Screenshot 2024-09-13 075156](https://github.com/user-attachments/assets/de8921e3-c881-4cc0-bb11-25f348bde225)
SS2 - ![Screenshot 2024-09-13 075352](https://github.com/user-attachments/assets/48dd9b09-f3db-4288-8e60-8d3d11f018c1)

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

Change the way in which this information is copied to the clipboard so that the information is more useful to work with as a number rather than as a string.

### Describe alternatives you've considered

The only alternative is to manually edit the pasted data to make it work with whatever operation one wishes to perform with it, in the case of Windows Calculator this requires one to first paste the data to notepad or similar, manually edit the data, then finally copy/paste it to wherever it was needed.

**Comment by foreachthing** [comment]
Since I use Qalculate!, I'd like to keep the units as well 😉 
But, yeah, get rid of "Distance" and "Angle" and others... Value + unit is all I need 😄
