### ISSUE TITLE
Custom Filament Types in Filament Profile creation

### ISSUE THREAD

**Issue by mmcnair91** [SoftFever/OrcaSlicer#6749]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

When creating a new filament profile you are forced to select from the preset filament types and unable to write in your own. I often used custom or unusual filaments and I used to be able to bypass this by typing in the filament type but these seems to have been disabled.

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

Be able to full customize filament profiles without forcing the user to select from a limited drop down menu

**Comment by Big-Channie** [comment]
Totally agree, with filament sellers offering so my variations of pla (pla+, pla pro, pla tough, pla marble, pla wood, pla HS), custom filament types are needed.
