### ISSUE TITLE
【BUG】Prime Tower dangling appears. a series of bugs.

### ISSUE THREAD

**Issue by funnygeeker** [SoftFever/OrcaSlicer#6755]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.2.0-Beta

### Operating System (OS)

Windows

### OS Version

Windows11

### Additional system information

i5-12450 RAM 16GB

### Printer

Snapmaker J1s

### How to reproduce

Add model：3DBenChy
![image](https://github.com/user-attachments/assets/6389bf01-c2bf-4f20-9438-a03eddb4396e)
![image](https://github.com/user-attachments/assets/7f9da329-90d5-4e90-a50e-133c604e1cd7)

when upgrading from some old versions（v2.1.1） to new versions. The amount of material cleaning in the prime tower may not be correct.
prime tower will be higher prime volume.
![image](https://github.com/user-attachments/assets/73264e3a-83c0-4476-8dea-0971f96f1f30)
![e5cdbada96d7a69a3670ce513cb75be0_720](https://github.com/user-attachments/assets/3f9fe0b5-a32e-4042-be14-6cb267e7b67c)

（Please forgive me for using translation software to translate these contents. ThenI don't have enough time now, so I can only briefly report it, but I can't provide more detailed information.I'll add it in the follow-up. I'm very sorry.）

### Actual results

![image](https://github.com/user-attachments/assets/dbec30aa-46fd-4aee-82f5-67dc724495e6)

### Expected results

.

### Project file & Debug log uploads

.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by SoftFever** [comment]
Thanks
Can you attach a sample project to reproduce the issue?

**Comment by funnygeeker** [comment]
> 谢谢您能否附上示例项目来重现该问题？

Okay, I have time today. The file is as follows:
[BUG_3DBenchy.zip](https://github.com/user-attachments/files/17011772/BUG_3DBenchy.zip)

**Comment by funnygeeker** [comment]
@SoftFever It seems that you forgot to reply. I tested it again in the latest Beta2, but the problem persists. 
[BUG_3DBenchy.zip](https://github.com/user-attachments/files/17011772/BUG_3DBenchy.zip)
