### ISSUE TITLE
Z-seam is present in Spiral Vase mode in OrcaSlicer

### ISSUE THREAD

**Issue by sensaurabh** [SoftFever/OrcaSlicer#676]
Whenever 'Spiral Vase' mode is selected in the 'Others' tab and an object is sliced, there is a z-seam present instead of smooth transition in the layers.

Can be easily reproduced by selecting a 'Cylinder' primitive from the right click menu and then slicing it after selecting the 'Spiral Vase' checkbox

Expected behavior would be a sliced single walled object with no z-seam

![image](https://user-images.githubusercontent.com/7408980/230464386-d6f36883-bb27-4b35-9aca-80ccb9be3907.png)

**Printer model**
KP3S Pro S1
**Desktop (please complete the following information):**
 - OS: [MacOS Ventura]
 - Version [1.6.1]

Notes:

- could be happening because of there is no option to disable the 'Timelapse' mode?
- There is no option to disable the 'z-hop' in the printer menu?
- Have tried changing 'Seam gap' value, but it has had no effect on the seam generation.

### **New EDIT**

- I disabled retractions in the Filament menu and the seam went away. Ideally even with retractions ON, if Spiral Vase mode is enabled, there should be no retractions or z-seam present in the model.

### **Update2**
Spoke too soon. Disabling retractions cause "!! Invalid speed in 'G1 E0 F0'" error in Klipper.

**Comment by hliebscher** [comment]
Mac M1   OS 1.6.1 it works

**Comment by sensaurabh** [comment]
Strange, for me I cannot get rid of the seam or the retractions at the white points you see in the included pictures. It's not just in the preview either.

**Comment by hliebscher** [comment]
![seam](https://user-images.githubusercontent.com/9274162/230679894-9b9975e1-e2c6-4ca1-97e1-e670964ca490.jpg)
![ok](https://user-images.githubusercontent.com/9274162/230679896-859d6966-6977-4486-9683-a96d7e8d0f24.jpg)

can you send your 3mf  as zip?

**Comment by sensaurabh** [comment]
Here it is...  [Cylinder-zSeamInVaseMode.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/11182268/Cylinder-zSeamInVaseMode.3mf.zip)

Does the 3mf also carry over the Filament settings? Do you have retractions enabled in your filament settings?

**Comment by rcxrbt** [comment]
Solved?

**Comment by andrewboktor** [comment]
I've been slicing in vase mode a lot and never saw this. Must be specific to config.
