### ISSUE TITLE
Configure Leyer Height by Heigth 

### ISSUE THREAD

**Issue by feliperiffel** [SoftFever/OrcaSlicer#6761]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I would like a way to configure the quality of different `Leyer Heigth` by height in mm.

This would be useful to improve printing time without necessarily affecting quality, for example, I have some gears to print I don't care how high it prints in the bottom or middle of the gear but for the teeth, I would like to decrease the layer height to better precision/strength.

Take this example:
In this gear, if I use 0.2 layer height the teeth of the gear are in the last 3 layers of the print
![image](https://github.com/user-attachments/assets/7945d73b-31df-403f-b5bd-ed829f310010)

if I change it to 0.08 it has 8 layers, 
![image](https://github.com/user-attachments/assets/3268cc65-2451-49bc-ac6e-f6df39332975)

I know I could print all in 0.08, but if I could say that from the base to 6mm I would like a layer height of 0.2, and just the last 0,06 mm use a 0.08 layer hight I would be able to have a faster printer without necessarily mess with the quality.

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

In the left panel, it would be nice to have the ability to break the layer height by global height, giving the possibility to in the same print I have different qualities at the same time.

![image](https://github.com/user-attachments/assets/b2f215be-6038-4bdf-8135-206a124310ac)
to

**Comment by henrivdr** [comment]
Have you tried the Variable Layer Height option?

**Comment by SoftFever** [comment]
You can use Height Range Modifier  
<img width="414" alt="Screenshot 2024-09-15 at 2 24 07 PM" src="https://github.com/user-attachments/assets/e58af4f3-0c94-48b7-acd4-ac0379ccfb13">

 or Variable Layer height tool to do this. 
<img width="523" alt="Screenshot 2024-09-15 at 2 23 44 PM" src="https://github.com/user-attachments/assets/b9ae3186-c0e0-48c8-9a41-81e02356694e">

**Comment by feliperiffel** [comment]
Thank you! I searched on the web before sending the request but really did not find it.
