### ISSUE TITLE
Bambu P1S Doesn't have Lidar, slicer goes for scan

### ISSUE THREAD

**Issue by H4fkas** [SoftFever/OrcaSlicer#6767]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.2.0 Beta

### Operating System (OS)

Windows

### OS Version

Windows 11

### Printer

Bambu Lab P1S

### How to reproduce

Put object
slice object
Go to 1st layer
Go to 20th move - It is going for Lidar QR scanning position (P1S doesn't have LIDAR)

### Actual results

![image](https://github.com/user-attachments/assets/0b31c70c-4266-44a0-af34-1b3d581ce8ef)

### Expected results

Delete this from P1S

### Project file & Debug log uploads

[bug.zip](https://github.com/user-attachments/files/17003701/bug.zip)

### Checklist of files to include

- [ ] Log file
- [x] Project file

**Comment by SoftFever** [comment]
I don't think it's a bug.
It goes to that position after drawing the purging line.
It didn't do any laser stuff.

I don't believe it has any negative impact hence won't change it.
