### ISSUE TITLE
Better brims

### ISSUE THREAD

**Issue by rkarlsba** [SoftFever/OrcaSlicer#6769]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Current brims aren't always that efficient

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

I saw this video on https://www.youtube.com/watch?v=4GxZXxNraY0 and he obviously hates slicer brims, but what he proposes doing in the modelling instead of using slicer brims, looks to be rather easy to implement in a slicer. Has anyone looked into this?

### Describe alternatives you've considered

1. Just see named video and it'll be self-explainatory

### Additional context

It's just a suggestion, after all

**Comment by DVSVIDEO** [comment]
OrcaSlicer mouse ear?
Why is that not good for you?
