### ISSUE TITLE
When custom profile is chosen colour is always orange

### ISSUE THREAD

**Issue by domik82** [SoftFever/OrcaSlicer#677]
Orca slicer 1.6.1 

When custom filament profile is chosen - colour is always orange. 
Earlier it worked in a way that colour is preserved.

![image](https://user-images.githubusercontent.com/2431071/230466424-41aa499d-de06-48a9-b107-530a33ab0699.png)

![image](https://user-images.githubusercontent.com/2431071/230466663-ecb4d3d0-87c5-4468-87cc-8343756c750e.png)

**Comment by pl4nkt0n** [comment]
Confirm that, experiencing the same issue since version 1.6.1

**Comment by Padawg** [comment]
Same problem here.
