### ISSUE TITLE
New Language appear in the drop down in preferences but doesn't work 

### ISSUE THREAD

**Issue by AbdElhalim12** [SoftFever/OrcaSlicer#6771]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.2.0

### Operating System (OS)

Windows

### OS Version

windows 11

### Printer

all

### How to reproduce

create new language and add the mo file to i18n folder 

### Actual results

I followed the localization wiki page to create a new language that doesn't exist in orcaslicer, then I modified the preferences.cpp file to add add it. The Language now appears in the dropdown in preferences window but when I choose it the orcaslicer needs to be restarted as normal but after restart the language still English. 
I tried to move the mo file to the en folder to test whether it works or not, and it appears correctly. 

### Expected results

new language should take over the UI

### Project file & Debug log uploads

![image](https://github.com/user-attachments/assets/8b7e2568-27a1-4479-bfe0-d332c669b7c6)
![image](https://github.com/user-attachments/assets/a1d0d417-704b-40d1-ac7f-91235ecc639d)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Noisyfox** [comment]
You could try raising a draft PR so I could take a better look at what you've got so far.

**Comment by AbdElhalim12** [comment]
https://github.com/AbdElhalim12/OrcaSlicer/pull/2
@Noisyfox

**Comment by AbdElhalim12** [comment]
https://github.com/SoftFever/OrcaSlicer/pull/6815

**Comment by Noisyfox** [comment]
The reason it doesn't work is this:
https://github.com/SoftFever/OrcaSlicer/blob/587e83939777b44c13ca26223fbb3ffe6b2e6863/src/slic3r/GUI/GUI_App.cpp#L5091-L5094

**Comment by Noisyfox** [comment]
> but when I replace the english mo file with the arabic one to test it, it worked ![image](https://private-user-images.githubusercontent.com/14279227/368606653-75b4c5cd-25db-4f47-a91d-76425147a054.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MDcxOTIsIm5iZiI6MTcyNjcwNjg5MiwicGF0aCI6Ii8xNDI3OTIyNy8zNjg2MDY2NTMtNzViNGM1Y2QtMjVkYi00ZjQ3LWE5MWQtNzY0MjUxNDdhMDU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDAwNDgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwNjg1YzZlMTQwYzBjMzY0N2IxNzMyNjJiMzcxYzc5MzlhZmUzZTJiNGU1OTNhNjFmYWMyNDk4NWVlMGE1NjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RZqfzq_haUvk5lI_2Iz8MlB9nNYwMEelOFxalmkWE8s)

Because in that case the app believes it's English not Arabic, which bypassed this check.

**Comment by AbdElhalim12** [comment]
Okaaay, So it there a way to exclude Arabic from that condition, since it's working correctly?

**Comment by Noisyfox** [comment]
You can just change the line I mentioned above, (or even delete that check)

**Comment by AbdElhalim12** [comment]
Hey, Ive tried couple things but all I got is the whole UI turned Right to left
![image](https://github.com/user-attachments/assets/9dce5890-212d-4a05-8a23-ec6ad22d24c2)
![image](https://github.com/user-attachments/assets/ef15c934-34a4-44f2-9a64-124cecf893e2)

**Comment by Noisyfox** [comment]
Ah... I guess that's how wxwidgets handles right-to-left languages.
