### ISSUE TITLE
Top layer has a small 1 layer island

### ISSUE THREAD

**Issue by wired2000000** [SoftFever/OrcaSlicer#6772]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1-2.2.0

### Operating System (OS)

Windows

### OS Version

Windows 10 Pro 22H2

### Additional system information

CPU: AMD Ryzen 5 2600, RAM: 16GB GRAPHICS CARD: NVIDIA GT710

### Printer

KLIPPER modified Artillery Hornet

### How to reproduce

Open the attached project file.
Slice it.

### Actual results

![εικόνα](https://github.com/user-attachments/assets/17a789a6-04c5-413c-bfc1-534161cdf513)

### Expected results

![εικόνα](https://github.com/user-attachments/assets/4193d380-2eca-4df7-877e-ae9b571ac77a)

### Project file & Debug log uploads

[reader helper.zip](https://github.com/user-attachments/files/17005002/reader.helper.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Anything else?

![εικόνα](https://github.com/user-attachments/assets/0d9a41e9-02c6-4a5d-85a3-802a1a086b08)

That artifact on the top layer should not exist, the stl file does not have it.
![εικόνα](https://github.com/user-attachments/assets/286b5b36-9a2a-4624-9e21-47972bb757bd)
It is not affected by "wall generator settings" neither by "precision" settings
If z axis scale is other than 100% (even 100.1% or 99.9%) then the bug does not appear. I suspect some floating point arithmetics shenanigans.
![εικόνα](https://github.com/user-attachments/assets/c5caf3b8-4a22-448c-8a2b-8012377cab98)

**Comment by discip** [comment]
@wired2000000
Unfortunately your model is corrupted.

Right click your model and choose **`Fix Model`**. 😊

**Comment by discip** [comment]
@wired2000000
This is no bug!
Unfortunately your model is corrupted.

Right click your model and choose **`Fix Model`**. 😊

**Comment by discip** [comment]
@wired2000000
This is not a bug in Orca!
Unfortunately your model is corrupted.

Right click your model and choose **`Fix Model`**. 😊

**Comment by discip** [comment]
@wired2000000
This is not a bug in Orca!
Unfortunately your model is corrupted.

Right click your model and choose **`Fix Model`**. 😊

![image](https://github.com/user-attachments/assets/63a9d075-ef9c-4b0e-97eb-81912f7c44da)
