### ISSUE TITLE
Choice of number of walls in the first and last layer

### ISSUE THREAD

**Issue by Dani7710** [SoftFever/OrcaSlicer#6775]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

the problem is that some prints, especially with multicolored filaments, to be more beautiful need many walls on first and last layer, unfortunately, now you have to do the whole print with the desired number of walls in the first and last layer. making prints too slow and too heavy.

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

the solution would be to replace "only one wall on top surfaces" and "only one wall on first layer" with numbers of wall on top surfaces and numbers of wall on first layer.  I attach screenshots of how it is now and with my idea
![Screenshot 2024-09-15 122545](https://github.com/user-attachments/assets/0c1e9f7d-addc-47bb-ab9e-f35a5d5de53e)
![Screenshot mod](https://github.com/user-attachments/assets/87e78a26-2a51-4cb3-8ac9-16909a9d2259)

**Comment by mxxmxxm2** [comment]
would be indeed a nice feature. for now we can use for example a thin modifier to adjust number of walls, but the feature would be much convenient
