### ISSUE TITLE
[Feature Request] filament AND printer specific profiles

### ISSUE THREAD

**Issue by pl4nkt0n** [SoftFever/OrcaSlicer#678]
**Is your feature request related to a problem? Please describe.**
with the current print profiles every filament  is always visible. But not every profile is compatible with every filament.
For example - a high speed profile with a layer height of 0.2 is usable with PLA, but may not with TPU.
But it often happens, that the wrong profile is choosen, because ever filament/material is chooseable with every profile.

Same thing with different printers - a Voron V0 may print much faster than a V2 350. so a "0.20mm STANDARD @voron" profile may fit for one but not for the other printer.

**Describe the solution you'd like**
For example in prusa slicer it is possible to configure filaments or material types exclusive for explicit print profiles.
So if you choose a ABS profile, there will only be ABS, ABS+ and eventually ASA filament visible.
It is possible to filter profiles for a filament configuration via dropdown menu,
or with syntax. One possibility with syntax is, to look for a specific text within the "description" field of the print profile.
so you can write "ABS" and search for this term with the syntax of the filament configuration.

For the printer topic its the same - every profile should be configurable for one (or more) printers. Not compatible profile should be invisible. (PrusaSlicer has also the possibility to always show "incompatible" profiles, which than would be equal to the behavior of Bambu/Orca right now)

**Describe alternatives you've considered**
currently no alternative solutions with bambu or forks are known

**Additional context**
the prusa slicer solution is still a bit exhausting - while the syntax was hard to find, it may not be usable for beginners generally. It would be more convenient, if there's just a dropdown menu or checkboxes in the print profiles,
where you can choose one or more related filament types, so every other type is not longer visible.
![filament_filter_syntax](https://user-images.githubusercontent.com/76616529/230478108-a817b9aa-146c-4022-8cae-bea33044d406.png)
![print_profile](https://user-images.githubusercontent.com/76616529/230478113-19fe3317-6713-42f5-8204-c5e801e82123.png)
![only_compatible(filtered)_filaments_visible](https://user-images.githubusercontent.com/76616529/230478111-9ae825d3-2b81-457c-af4b-293c85264819.png)

**Comment by ChaosBlades** [comment]
Would also like this feature. Some of my printers are enclosed others are open. So if I print PETG on both types of printer I am going to need different amounts of part cooling. So I end up having to label the same PETG filament profiles differently for each printer. Would be nice if I could only have certain profiles available for certain printers. This only works with Bambu and Non-Bambu printers but not between different Non-Bambu printers.
