### ISSUE TITLE
Estimated endtime

### ISSUE THREAD

**Issue by foxmckraut** [SoftFever/OrcaSlicer#679]
Feature Request for Estimated endtime like evey frontend(mainsail/fluid/octoprint) hast.

shows the time when the print is done.

Bonus: shows the dissadvantege betwen sliced time printing time an real printing time.

**Comment by TexZeTech** [comment]
It does though?

![image](https://user-images.githubusercontent.com/7254540/230520435-3af2ffcc-60d0-43d0-a463-443e861fbeae.png)

**Comment by shauneccles** [comment]
I'm guessing they're after:
Total time	22m21s
Estimated endtime	{now + 22m21s}

**Comment by foxmckraut** [comment]
> I'm guessing they're after: Total time 22m21s Estimated endtime {now + 22m21s}

^this

it only shows the time it needs not when its done (like 14:42oclock or something) and it didnt show how much more it takes than sliced f.e. 6h sliced takes 8hours in reality.
