### ISSUE TITLE
Top surface flow also changes line width, in effect cancels out the flow.

### ISSUE THREAD

**Issue by Gizmo6** [SoftFever/OrcaSlicer#680]
**Describe the bug**
Top surface flow ratio
found in: Quality/advanced/top surface flow ratio. When editing this value for a cleaner top surface it auto adjusts the line width to compensate for the change which in effect cancels out the flow compensation. 

**To Reproduce**
load 2 identical printable files, eg cubes. edit Top surface flow ratio, say 0.5 value and slice. you will see under the preview the line width of the edited one has also changed, but it isn't refected in the top surface line width option. 

**Expected behavior**
when editing top surface flow ratio, I would expect only the amount of material to change but to keep to the line width as specified in the top surface line width option.

**Screenshots**
attached

**Printer model**
bambu lab x1c

**Desktop (please complete the following information):**
 - OS: windows
 - Version 11
![top surface flow ratio example](https://user-images.githubusercontent.com/36663947/230500246-8c163c78-4995-43c9-8155-2e7f7a82a484.png)

**Comment by SoftFever** [comment]
@Gizmo6, can you try the classic wall generator? 
Does it happen on older versions too?

**Comment by Gizmo6** [comment]
Thanks for replying. I can confirm that both Arache and classic both display the same behavior.
I can also confirm versions 1.45 and 1.34 also exhibited the same behavior. 

Your calibration tools are fantastic but as the flow samples are so flat for some reason it gives a perfect result. But in order to test my theory I made the 9 flow tests 5mm tall and the top surface was again poor. 

![orca top surface issue](https://user-images.githubusercontent.com/36663947/230587758-b137c6c8-02b5-4071-9f69-484a19a068e7.jpeg)

**Comment by netweaver1970** [comment]
I recognize the flat vs real size behavior too. Tuned to the flat pieces perfectly but when printing real life objects, the top level is never that nice.

**Comment by SoftFever** [comment]
The top surface top flow is a bug.

For the flow rate calibration, please move to https://github.com/SoftFever/OrcaSlicer/discussions for suggestions/ideas/discussions.

**Comment by SoftFever** [comment]
And it's just a gcode preview/rendering bug.
The actual g-code is fine.

**Comment by Gizmo6** [comment]
The render is exactly the behaviour of the actual print as you can see from the photos. I have tried to manually play with the adjusting the top surface line width to compensate for the behaviour but its just abit of a mess. 

Just wanted to say absolutely love your work on the slicer. The top surface flow was my main reason to switch in the beginning and i am sure it did work in the original. I am trying to find the original version now to test the behaviour.

**Comment by SoftFever** [comment]
> 

yeah, it's a legit bug.

**Comment by Gizmo6** [comment]
Amazing job will get it on the printer for testing once first print is done.

**Comment by sylanc3** [comment]
Hello together, I'm not a developer, but I want to report something:
I use 1.62 beta and the Top Surface flow ratio shows no effect on actual print. Is there maybe another bug?
![image](https://user-images.githubusercontent.com/76587995/233671441-2b25e612-c212-4b6d-91ef-5efabc5d013a.png)
left to right
1.0 1.05 1.1 1.2

**Comment by SA7BNT** [comment]
Still having that issue that it is not possible to adjust the Top Surface flow ratio.
Running 1.6.3 Mac Intel Version
