### ISSUE TITLE
Unable to overwrite .stl correctly

### ISSUE THREAD

**Issue by Ricocn** [SoftFever/OrcaSlicer#6801]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.0

### Operating System (OS)

Windows

### OS Version

windows 11

### Printer

Bambu P1S

### How to reproduce

1. Load a 'test.stl' file

2. Right click - Export as 'test.stl'

3. A dialog box pops up: The file already exists, whether to replace it, select 'Yes'

### Actual results

The final result is that it will not be replaced, but a new .STL.stl file will be generated  (Using Bambu Studio, it can be overwritten, and this bug will not occur)

### Expected results

The .stl file should be overwritten

### Project file & Debug log uploads

![3](https://github.com/user-attachments/assets/cb2e1cf7-e81e-4204-bc83-8afbccd551f0)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Noisyfox** [comment]
It seems to be a issue with upper cased file extension.
