### ISSUE TITLE
Custom filaments in the AMS

### ISSUE THREAD

**Issue by rkarlsba** [SoftFever/OrcaSlicer#681]
When configuring filaments in the AMS, which may be replicated with "sync filament list from AMS", I cannot choose any custom filament types. I have setup my own default profiles, since I don't like the original ones, but these aren't visible from the AMS. Could this be mended, please?

**Comment by nirurin** [comment]
I just reported a similar (or the same?) issue, I can't believe this has been broken for 5 months...
