### ISSUE TITLE
Add the "Improved G-code Viewer' feature(s) from PS 2.8.0 Alpha 5 and onwards.

### ISSUE THREAD

**Issue by MrBlackmidi** [SoftFever/OrcaSlicer#6813]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

https://github.com/prusa3d/PrusaSlicer/releases/tag/version_2.8.0-alpha5 in the "Improved G-code Viewer" tab

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

Add said feature(s)

### Describe alternatives you've considered

There is none as far as i know

**Comment by as-com** [comment]
Not stale

See: #10735
