### ISSUE TITLE
Presets have fixed colour

### ISSUE THREAD

**Issue by rkarlsba** [SoftFever/OrcaSlicer#682]
Now, if I choose filament type to a preset, it also changes its colour to an ugly orange-like thing. Is this a new bug or did a Prusa fan sneak in here somewhere? ;)

**Comment by bryancrea** [comment]
Please fix this, most annoying!

**Comment by Padawg** [comment]
Happening to me too.. it is very annoying.

**Comment by SoftFever** [comment]
dup with https://github.com/SoftFever/OrcaSlicer/issues/651
