### ISSUE TITLE
[BUG] Custom bed shape design doesn't apply changes 

### ISSUE THREAD

**Issue by H4kunaM4tata** [SoftFever/OrcaSlicer#685]
For context:
Slice done with PrusaSlicer:

![image](https://user-images.githubusercontent.com/35049512/230523592-b2fffab3-0c88-45d3-a334-c56710cc2991.png)

Slice done with OrcaSlicer:
I believe because there is no bed shape design set, the thumbnail looks so raw.

![image](https://user-images.githubusercontent.com/35049512/230523647-f7c1fc80-709f-4723-b2ee-888ae2d86d9c.png)

![image](https://user-images.githubusercontent.com/35049512/230523697-2861c9f9-f58f-4a3c-baa3-5c35013c7456.png)

I did find the path to set it but it does not seem to accept the PNG file, nothing really happens.
The PrusaSlicer thumbnail looks a lot better, it is also better to see on the display and home assistant.
This is not the end of the world but would be nice to have this working.

![image](https://user-images.githubusercontent.com/35049512/230523837-c9852c77-9992-45f6-860a-add44e4a21c0.png)

Thank you

**Comment by hliebscher** [comment]
you can add this self in your json config file... like ratrig

**Comment by H4kunaM4tata** [comment]
> you can add this self in your json config file... like ratrig

I see, well, the settings is right there so it makes more sense to try get it working instead of workarounds. 
Workarounds get messy with time. After releases you might or might not have to manually change it again etc.

**Comment by atl285** [comment]
@hliebscher, I've tried this with a Ender 3. But the changings in the json file were ignored.

**Comment by hliebscher** [comment]
pls send the stl or svg as zip i integrate this for testing

**Comment by atl285** [comment]
Here are the files for my Ender 3 (V1). I've got them from PrusaSlicer.
[ender3_files.zip](https://github.com/SoftFever/OrcaSlicer/files/11183314/ender3_files.zip)

**Comment by SoftFever** [comment]
Fixed in 1.6.2 beta

**Comment by atl285** [comment]
Hi, if I load a custom Bed Shape in v. 1.6.2 it is possible, but the point (0,0) is set to middle of plate.
![custom_shape](https://user-images.githubusercontent.com/15815417/233218258-c385f3c2-d48d-4664-bde1-e70669d10521.png)
Is there a way to set manually the point (0,0) to the front left corner? Else any print will fail, because the front left corner is defined as negativ coordinate. I use the bed shape from my earlier comment.

**Comment by sdylewski** [comment]
I have the latest orcaslicer and can't load a .png file of a bed image either.  This would be helpful to show a keep out region for stealtthchanger...
