### ISSUE TITLE
Deactivated tool head cool down temps set high in slicer 2024

### ISSUE THREAD

**Issue by Hooglabah** [SoftFever/OrcaSlicer#6854]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.2

### Operating System (OS)

Windows

### OS Version

windows 10

### Additional system information

CPU: AMD ryzen 7 7600x
36gb ddr4 ram
amd radeon:6950xt 24gb vram

### Printer

Scratch built IDEX cartisian

### How to reproduce

Use provided generic tool changer printer.
Use the inbuilt shapes tool to make a sqaure.
set temps to 0 for all layers (bed and hotends).
Have at least one tool change.

### Actual results

All gcode is correct except the inbuilt end filament Tool cool down.
gcode thats at fault :
; 
stop printing object Cube id:0 copy 0
G1 E-2 F1800
**_M104 S4294967271 T0 ; set nozzle temperature ;cooldown_**
T1
M109 S15 T1 ; set nozzle temperature and wait for it to be reached
; printing object Cube id:2 copy 0

The cool down is input at every tool change.

### Expected results

User defined or default idle tempreature set for the deactivated tool head.

### Project file & Debug log uploads

[Sample for devs.zip](https://github.com/user-attachments/files/17083459/Sample.for.devs.zip)
[klippy.log](https://github.com/user-attachments/files/17083464/klippy.log)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Anything else?

![screen shot showing issues](https://github.com/user-attachments/assets/da71a54f-b62a-447c-8bad-ec407b7cc6c0)

**Comment by Felix14-v2** [comment]
> gcode thats at fault :
> ;
> stop printing object Cube id:0 copy 0
> G1 E-2 F1800
> **_M104 S4294967271 T0 ; set nozzle temperature ;cooldown_**

I managed to reproduce the issue in OrcaSlicer 2.3.1 (trying to slice your project in 2.3.2 causes an access violation; UPD: reproduced in 2.3.2 as well). The issue with temperatures is that temperature in your material profile is set to 15°C, and ooze prevention delta is -40. So you get negative value (stack underflow?) as a result. Expected result of such an insane settings combination, to be honest. Maybe there should be a sanity check in the ooze delta input.
