### ISSUE TITLE
Inconsistent speed for overhanging

### ISSUE THREAD

**Issue by R4toLoko** [SoftFever/OrcaSlicer#688]
I am trying to understand some differences between PS and OS.
OS overhanging for some reason does not have consistent slow speed.
It is a mix of slow with fast speed and that is messing things up,

![image](https://user-images.githubusercontent.com/35049512/230531526-f2060049-0ae3-4537-a880-0ff7543187ac.png)

Both slicers share the same setup

![image](https://user-images.githubusercontent.com/35049512/230531944-e87ab4a4-13e2-4b7c-98fe-81d75360d074.png)
![image](https://user-images.githubusercontent.com/35049512/230531993-fdbe8765-c4a1-4af6-9acd-8ed245843088.png)

**Comment by SoftFever** [comment]
Can you share the project file?

**Comment by H4kunaM4tata** [comment]
@SoftFever definitely.

This is a piece of a bigger part, cut to size just to test the overhang stuff as I am setting OS with PS profiles.

[fan(8).stl.zip](https://github.com/SoftFever/OrcaSlicer/files/11188589/fan.8.stl.zip)

Thank you

**Comment by jmlott** [comment]
I believe this is related to the bug I was about to open, so I'll just leave my comment here instead. In 1.6.1, it seems like something broke with overhang detection. If I slice a standard benchy with overhang detection enabled, it doesn't show the front bottom part of the boat as an overhang and therefore doesn't adjust for it. It was properly showing as an overhang in 1.5.0.

**Comment by H4kunaM4tata** [comment]
> I believe this is related to the bug I was about to open, so I'll just leave my comment here instead. In 1.6.1, it seems like something broke with overhang detection. If I slice a standard benchy with overhang detection enabled, it doesn't show the front bottom part of the boat as an overhang and therefore doesn't adjust for it. It was properly showing as an overhang in 1.5.0.

I see. I haven't used SoftFever for while after returning my X1C, I didn't even knew it had changed the name.
I have been moving away from PrusaSlicer to OrcaSlicer with my Voron ( bringing some folks along with me haha ) and have noticed it.
SoftFever is a lovely slicer, clean, organized and very active. Bugs get sorted out very quick which is awesome.

**Comment by H4kunaM4tata** [comment]
Is there an ETA for a fix??

At the moment, I am being forced to go back to PrusaSlicer to get the prints to be printed properly
OS, left side printed just right, right side with greater overhang printed like...

![image](https://user-images.githubusercontent.com/35049512/233755075-ee2dbb31-c5d9-4d1b-b3c1-052d1e8395f5.png)

What is this 170mm/s doing here??

![image](https://user-images.githubusercontent.com/35049512/233755088-aec4f6db-a861-494b-aa81-b4307761f613.png)

Same model, same profile, different behavior.
Notice how the PS external walls keep a lower speed so better cooling, there is no fast speed mixed up.
OS external walls mixes fast and slow speed.

![image](https://user-images.githubusercontent.com/35049512/233755485-19e742b2-0b17-481b-b4cf-73ef5c9c63bd.png)


I have been using OrcaSlicer as my main slicer for my Voron but these bugs makes it harder to keep using it :(

**Comment by H4kunaM4tata** [comment]
Both slicers are using Classic wall generator. Arachne does not fill gaps properly.

The only way OrcaSlicer will generate the walls with the right sleep is by setting it with Arachne which makes no sense.

**Comment by H4kunaM4tata** [comment]
Edit: Giving OrcaSlicer another try.
I had `Detect thin walls ` disabled since 2 months ago when I still had my X1C.

This feature is or was broken, if a model had letters on it, it would just delete the whole letters and other crazy inconsistencies.
Giving this slicer another try, will report back.

**Comment by R4toLoko** [comment]
Overhang logic has been improved and already released.
