### ISSUE TITLE
M572 command multi-tool support

### ISSUE THREAD

**Issue by tyh4n** [SoftFever/OrcaSlicer#6888]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

The automated pressure advance setting (M572 in gcode) only applies to driver 0 (Driver 0). Previously, I turned off the pressure advance setting in the filament tab and type in the gcode in advanced - filament start gcode. Since now we are introducing multi-tool support, I'm hoping this issue can be fixed. Thanks.

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

Assign the pressure advance value to the right tool number (extruder/driver number). Maybe fix the pressure advance tunning code as well :)

**Comment by hagre** [comment]
is still an issue
