### ISSUE TITLE
Mullticolor print without prime tower results in insanely long print time

### ISSUE THREAD

**Issue by lygris** [SoftFever/OrcaSlicer#689]
**Describe the bug**
Went to print a multicolor print today after upgrading to 1.6.1 and put in a filament change at a layer. Looking at the model print time after slicing shows35583992d72h49m. Trying to print it anyway the toolhead just stops at that layer change and sits there. tried to cancel the print but the printer remained unresponsive. using a prime tower fixing the time issue.

**3mf File for This Bug**
3mf zipped and uploaded
[bug.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/11175828/bug.3mf.zip)

**To Reproduce**
Steps to reproduce the behavior
on a layer in the prepare tab add a filament color change

**Expected behavior**
AMS pulls back current filament and changes to desired color. (the ams did change the filament, but the print didn't continue)

**Screenshots**
<img width="842" alt="Screenshot 2023-04-06 at 10 16 49 PM" src="https://user-images.githubusercontent.com/22260038/230534625-d3455edf-3dee-4cd8-a194-ea1d8db0f5ae.png">

**Printer model**
Bambu X1C
**Desktop (please complete the following information):**
 - OS: macbook pro m2
 - Version latest macos

**Comment by shlagwuk** [comment]
Same problem, voron printer, mac mini M1.
![image](https://user-images.githubusercontent.com/17025174/230614694-b1ffcecf-c018-4e29-8813-365cdd90e73c.png)

**Comment by shlagwuk** [comment]
It seems like it's fixed on 1.6.2 beta
![image](https://user-images.githubusercontent.com/17025174/234391506-5148e73b-ac16-47f7-a1fc-14eb76f4f988.png)

**Comment by shlagwuk** [comment]
The bug is still here in 1.7.0
![image](https://github.com/SoftFever/OrcaSlicer/assets/17025174/e820c012-3831-4dd1-85a7-2ced30d0bc81)

Print is stopped after the first fillament swap:
`Extrude only move too long (92233720368547.766mm vs 110.000mm)`
That's a lot of filament ;-)
