### ISSUE TITLE
Unable to parse the received print job

### ISSUE THREAD

**Issue by qgerome** [SoftFever/OrcaSlicer#690]
**Describe the bug**
I'm trying to print the Orca cube https://www.printables.com/model/444132-orca-cube/files using the latest version OrcaSlicer (1.6.1). When I send the print to my printer (Bambulab X1C @ 01.04.01.00) it failed after the upload to the cloud service with the error "Failed to start printing", "Unable to parse the received print job. Please update the firmware to the latest version and try again. [0500 4002 0954131]".

I tried the same 3MF file on BambuStudio and it works.

**3mf File for This Bug**
[OrcaCubev2_bug.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/11177161/OrcaCubev2_bug.3mf.zip)

**To Reproduce**
Load the 3mf file in OrcaSlicer (latest version or 1.5)
Send it to the printer
When the soft tries to change to the device page it shows the message that it failed

**Expected behavior**
It prints

**Screenshots**
<img width="1593" alt="Screenshot 2023-04-07 at 09 57 46" src="https://user-images.githubusercontent.com/1607549/230568026-021de497-6fc9-49bd-8da6-9f6006e56ef3.png">

**Printer model**
Bambulab X1C @ 01.04.01.00

**Desktop (please complete the following information):**
 - MacOS M2 Pro @ 13.2.1 
 - OrcaSlicer @ 1.6.1

**Comment by SoftFever** [comment]
It is most likely a glitch in Bambu's cloud service.
Can you try again after a few minutes?

**Comment by qgerome** [comment]
It's been like this since at least a week now :/ It's been already a few prints that I have to go back to Bambu Studio to print. Could I do something to give more logs ?

**Comment by julie777** [comment]
It happens regularly to me and I use LAN only all the time. 
It must not be a cloud issue.

**Comment by chuckkay** [comment]
> 

Did renaming the file fix the issue?

**Comment by qgerome** [comment]
I updated to OrcaSlicer 1.6.2 and tested multiple things:

**The "faulty" file from this ticket**

It worked without problems

**A file with a URL encoded filename**

It failed with the same error as the one described here.

**The same file as above but with the filename corrected (no %20 in it)**

It worked.

Not sure if we can conclude that it is fixed or if we should fix it when it is sent to the cloud service.

**Comment by chuckkay** [comment]
Definitely a bug Orca should be made aware of…
