### ISSUE TITLE
Orca Slicer does not Launch on Arch

### ISSUE THREAD

**Issue by CitrusIntellect** [SoftFever/OrcaSlicer#6908]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1-1

### Operating System (OS)

Linux

### OS Version

Arch linux

### Additional system information

Nvidia 4060

### Printer

None

### How to reproduce

install orca-slicer-bin from aur (using paru & yay), launch orca-sclier

### Actual results

[2024-09-25 16:53:49.725148] [0x000074adee955c40] [trace]   Initializing StaticPrintConfigs
add font of HarmonyOS_Sans_SC_Bold returns 1
add font of HarmonyOS_Sans_SC_Regular returns 1
add font of NanumGothic-Regular returns 1
add font of NanumGothic-Bold returns 1
[1]    202507 segmentation fault (core dumped)  orca-slicer

### Expected results

Orca Slicer launches and goes through setup.

### Project file & Debug log uploads

Launched Here

[2024-09-25 16:53:49.725148] [0x000074adee955c40] [trace]   Initializing StaticPrintConfigs
add font of HarmonyOS_Sans_SC_Bold returns 1
add font of HarmonyOS_Sans_SC_Regular returns 1
add font of NanumGothic-Regular returns 1
add font of NanumGothic-Bold returns 1
[1]    202507 segmentation fault (core dumped)  orca-slicer

Ended Here

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Anything else?

It was working just fine before updating orca-slicer, tried to reinstall and it did not work.

**Comment by CitrusIntellect** [comment]
It found out it was patched in Beta 2.2

**Comment by esistgut** [comment]
```
$ Downloads/OrcaSlicer_Linux_V2.2.0-rc.AppImage 
[2024-10-14 00:07:07.608166] [0x00007be3405fdc40] [trace]   Initializing StaticPrintConfigs
add font of HarmonyOS_Sans_SC_Bold returns 1
add font of HarmonyOS_Sans_SC_Regular returns 1
add font of NanumGothic-Regular returns 1
add font of NanumGothic-Bold returns 1
Segmentation fault (core dumped)
```

The issue seems to be still affecting 2.2.0-rc.

**Comment by CitrusIntellect** [comment]
The issue does still exist, #7099 Nvidia cards are the issue here

**Comment by CitrusIntellect** [comment]
I can no longer get Orca slicer to crash, I used the 2.2.0 rc with this command:

__EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/50_mesa.json

And it just wont crash

**Comment by trebory6** [comment]
> I can no longer get Orca slicer to crash, I used the 2.2.0 rc with this command:
> 
> __EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/50_mesa.json
> 
> And it just wont crash

So I tried this solution and it opens, however it still crashes when viewing the "Home" tab and the "Device" tab.

Also, while this issue might be related to having Nvidia cards, Nvidia cards are not the issue.

The fact that there are solutions using Environmental Variables means this is a software issue. These are bugs. The cards aren't the issue, the bugs that cause the incompatibility with one of the most widely used graphics cards brands are the issue.

**Comment by CitrusIntellect** [comment]
I reinstalled arch because another OS messed up everything, it will crash

**Comment by kohbo** [comment]
> The issue does still exist, #7099 Nvidia cards are the issue here

I have this issue and I'm using an AMD 7900xtx

**Comment by kohbo** [comment]
Switching to the latest version on Github (2.2.0 beta 2) is working for me

**Comment by CitrusIntellect** [comment]
I just compiled OrcaSlicer from nothing and it is working great! I would suggest that first.

**Comment by padcom** [comment]
It fixed Orca for me too. I was able to not only upload but also the device tab shows up again and actually works. Thank you!

**Comment by quartzar** [comment]
It is still woefully broken on Arch.

**Comment by BunnySilly** [comment]
still completely broken for me too damn

**Comment by ghost** [comment]
> still completely broken for me too damn
> It is still woefully broken on Arch.

This necro posting, please don't, make a new issue instead of reopening an issue.

Also I would recommend using paru -S orca-slicer-bin

**Comment by bora89** [comment]
I have installed `orca-slicer-bin` and it finally started
