### ISSUE TITLE
no more thumbnails

### ISSUE THREAD

**Issue by AIIrounder** [SoftFever/OrcaSlicer#691]
**Describe the bug**

**3mf File for This Bug**
If it is related to slicing, please append the 3mf file. It could be extremely helpful to solve the issue.

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**

**Printer model**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Windows]

**Comment by AIIrounder** [comment]
I see no thumbnail and info more with version 1.6.1
![Screenshot (42)](https://user-images.githubusercontent.com/83362264/230625182-878ce983-c844-4ad0-a9f1-737c51f91946.png)

**Comment by hliebscher** [comment]
@AIIrounder  bei welchem Drucker ? Klipper ? welches Betriebssystem?

**Comment by AIIrounder** [comment]
Drucker ist ein Voron mit der Firmware Klipper und Betriebssystem wäre dann Win 10.

**Comment by hliebscher** [comment]
sollte gefixt sein in der aktuellen 1.6.1  bei mir sind die zu sehen und im Gcode auch drin... gab einen fix 
fix Malformed command issue for Klipper am 6.4 9:23
oder der alte Mainsail bug...
und wichtig 
If you're running Klipper, it's recommended to add the following configuration to your `printer.cfg` file.
```
# Enable object exclusion
[exclude_object]

# Enable arcs support
[gcode_arcs]
resolution: 0.1
```

**Comment by SoftFever** [comment]
Please update Moonraker to the latest version.
I put a note on 1.6.0 release page.
Let me put this message in 1.6.1 release page as well.
![image](https://user-images.githubusercontent.com/103989404/230635164-d90c7c87-17f2-45f5-ab0c-023af4a285e6.png)

**Comment by AIIrounder** [comment]
it was moonraker
