### ISSUE TITLE
support issue

### ISSUE THREAD

**Issue by bayc3d** [SoftFever/OrcaSlicer#6919]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.0 and 2.2.0-beta

### Operating System (OS)

Windows

### OS Version

windows10

### Additional system information

CPU: 10900K RAM 32GB GRAPHICS CARD2070SUPER  3TB SSD

### Printer

2 PIECES PRUSA MK2/3 DIY CLONE

### How to reproduce

I downloaded the parts from https://www.thingiverse.com/thing:3020026. I wanted to print spool holder for diy clone prusa mk2 printer. While printing the file named “3DPNFilHoldRoller.stl” in the zip file I downloaded, I positioned it vertically and activated the support. 
![Ekran Alıntısı0](https://github.com/user-attachments/assets/c1c07dd0-5065-4400-a6be-64721100ed86)

### Actual results

Whichever support style I choose, the support expands upwards on the lower protrusion where the 608 bearing is to be installed. For this reason, the 608 bearing was printed in such a way that it could not be installed. I only noticed this when I was removing the supports after printing. 
![Ekran Alıntısı](https://github.com/user-attachments/assets/a4e21c34-5d0f-4d2f-98d9-be4e01db6f98)

### Expected results

No matter what I try. Since the result didn't change, I decided to report it here. THIS could be a bug or I could be missing something. But I have tried many times.
![Ekran Alıntısı2](https://github.com/user-attachments/assets/f74abc4d-ceae-4020-937d-d9c470860030)
![Ekran Alıntısı3](https://github.com/user-att
![WhatsApp Image 2024-09-26 at 21 54 13(1)](https://github.com/user-attachments/assets/0d8889e9-012b-4570-969b-92ff422b79da)
![WhatsApp Image 2024-09-26 at 21 54 13](https://github.com/user-attachments/assets/ef162a9e-b96c-46f2-a72d-f37e351cd5da)
achments/assets/4c461ed4-0fa7-4430-aed4-49327149ada8)
![Ekran Alıntısı4](https://github.com/user-attachments/assets/6d0ce23c-1ee6-426b-89ad-2f5ba895f375)
![Ekran Alıntısı5](https://github.com/user-attachments/assets/2cd50489-fb94-4967-9374-b2354a7ef4df)

### Project file & Debug log uploads

[3DPNFilHoldGuide.zip](https://github.com/user-attachments/files/17154520/3DPNFilHoldGuide.zip)
![Ekran Alıntısı_last](https://github.com/user-attachments/assets/ed00df97-e88e-4caf-b51d-f585fcdf5dea)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by discip** [comment]
@bayc3d

Just deactivate **`Make overhangs printable`**. 😊

![image](https://github.com/user-attachments/assets/6c8f184d-4d13-44cb-a18a-affb313c863b)

**Comment by bayc3d** [comment]
Thank you very much. I thought I turned off “make overhang printable”. in fact, I'm sure I did. then I saw that every time I closed and opened the project, it was also selected. problem solved. thanks to everyone who contributed.
