### ISSUE TITLE
Detect overhang walls incorrectly limits reverse on odd/even and has a misleading description

### ISSUE THREAD

**Issue by jpa00** [SoftFever/OrcaSlicer#6920]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Currently it seems the only way to limit the problems with bridging, slowing for overhangs and perimeter speeds seems to be to disable "Detect overhang walls" and using the classic wall generator. (Neither of which is great btw., but bugs happen...)

While figuring out these tweaks I noticed that "detect overhang walls" description says it will affect overhang printing speeds, but at least with the classic wall generator it does not appear to affect them at all. (Except for the notable and exception of bridge perimeters' printing and fan speeds, for which it utilizes the 75-100% overhang speeds, but that's besides the point on this issue.) So this text should probably be fixed...

At the same time, detect overhang walls is a dependency of reverse on even (which seems to have been renamed from reverse on odd?), which seems wrong when there is a very legitimate use for reversing on every other layer, overhang or not by setting the threshold to 0%. I find this especially useful when printing PETG to help limit curling, which with that material only seems to need a sharp enough corner.

So currently due to this one feature it's a choice between really bad bridges or curling sharp corners, which is less than optimal.

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

Fix the description of "Detect overhang walls" to describe what it actually affects, and either remove the dependency between it and "Reverse on even" or add an option to simply always reverse on even, when Detect overhang walls is unchecked.

### Describe alternatives you've considered

There are a couple of issues that would make this one far less important, but as they seem to require much more work, I figured this would be a quicker one to take care of. The issue #5724 seems to aim at fixing the perimeter speeds on bridges, and #3078 would allow for customizing bridges in general, including possibly printing them with no perimeters at all. Although if the latter customization is already present in SuperSlicer, I suppose there is a chance it might not require too much work.

**Comment by Noisyfox** [comment]
You are right, the "reverse on even" should not depends on the detect overhang wall (except the overhang threshold option)
