### ISSUE TITLE
Quote character in plate name causes print job failure

### ISSUE THREAD

**Issue by mikedixonphoto** [SoftFever/OrcaSlicer#694]
**Describe the bug**
When a **quote character** (") is used in the **Plate name** setting it causes a "**Failed to send the print job.**" error.

**To Reproduce**
1. Click on the Plate Settings icon to open the Plate Settings dialog.
2. Create a plate name with the " character, for example: 4" Mount
3. Slice and Print the plate.
4. Observe error: "Failed to send the print job. Please try again.[-23][code=10, error=Internal processing failed]
5. Change 4" to 4-inch and the print will complete fine.
![PlateSettings](https://user-images.githubusercontent.com/60845343/230651267-ed254276-96dc-4e9c-bf31-4cd76d14a46b.jpg)

**Expected behavior**
Print should start

**Screenshots**
![QuoteError](https://user-images.githubusercontent.com/60845343/230650891-f8c9e14c-14c4-4961-ad6b-edcf8c48f378.jpg)

**Printer model**
Bambu Lab X1C

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Version OrcaSlicer 1.6.1

**Comment by ditomaso** [comment]
To add to this -- a quotation mark in the plate name also prevents the .3mf file from opening again.
