### ISSUE TITLE
Arachne leaves print area

### ISSUE THREAD

**Issue by EXOgreen** [SoftFever/OrcaSlicer#6949]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

Windows

### OS Version

Windows 10

### Printer

Bambu P1S

### How to reproduce

1. Switch Classic Generator to Arachne Generator
2. slice file

### Actual results

Phantom lines extend off to infinity.
![Screenshot 2024-09-27 233915](https://github.com/user-attachments/assets/0a9ba37d-677d-4373-b421-a315d4e6d798)
![image](https://github.com/user-attachments/assets/d0cb996c-a40b-4261-b060-2188aebc21d3)

### Expected results

No phantom lines are created.
![image](https://github.com/user-attachments/assets/84710c2f-7ccf-449b-82f9-2ef3ccf0f5e5)

### Project file & Debug log uploads

[Block52 3D Print ARACHNE-ERROR.zip](https://github.com/user-attachments/files/17172934/Block52.3D.Print.ARACHNE-ERROR.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Anything else?

This does not happen in 
- PrusaSlicer 2.8.1
- Bambu Studio 1.9.7.52

tested in OrcaSlicer 2.2.0-beta and 2.1.1

When switching wall generator from classic to Aranche, I get (in this one model) phantom lines that extend out of the printers build volume. In this example, the inner wall starts printing, then around line 387598 turns around, prints to X3624.45, and then comes back to the model and meets with the start of its inner wall.

**Comment by Noisyfox** [comment]
Not sure why PS and BBS don't have this issue, but you could try fixing the model first.

**Comment by EXOgreen** [comment]
Using Fix Model does make the issue go away. I was more concerned with why it only affects OrcaSlicer.

**Comment by Noisyfox** [comment]
https://github.com/SoftFever/OrcaSlicer/pull/7330 should fix the issue:
![image](https://github.com/user-attachments/assets/3984eb4e-2cdc-4a7d-ada8-7141bfa4ba10)

**Comment by EXOgreen** [comment]
You're awesome! Thanks!
