### ISSUE TITLE
volumetric flowrate model has errors

### ISSUE THREAD

**Issue by julie777** [SoftFever/OrcaSlicer#697]
**Describe the bug**

The model that is generated for the max flowrate test has errors.

![image](https://user-images.githubusercontent.com/5090005/230661435-c8116098-d6ac-4fae-ab8c-91e81f4b99f2.png)

**To Reproduce**
Steps to reproduce the behavior
1. select calibration/more/max flowrate
2. model will load and error appear

**Expected behavior**
model should not have errors 

**Screenshots**

**Printer model**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Windows]

**Comment by steezyprintz** [comment]
I have had that issue but also that the flow change doesnt get applied and also the VFA speed version too, have to close and restart a few times to get it to work again

**Comment by Navyguy330** [comment]
> I have had that issue but also that the flow change doesnt get applied and also the VFA speed version too, have to close and restart a few times to get it to work again

yeah, came here for that.  When I use the Max Volumetric speed test, it does not actually do anything. I have had it to 50mms/3 and it came out the same as at 5 lol.
