### ISSUE TITLE
Can you add k1 SE to orca ?

### ISSUE THREAD

**Issue by oomichalekoo** [SoftFever/OrcaSlicer#6984]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Can you add k1 SE to orca ?

### Which printers will be beneficial to this feature?

Others

### Describe the solution you'd like

Can you add k1 SE to orca ?

**Comment by cochcoder** [comment]
I've made a profile for this printer, that I'll be opening a pull request for very soon. Do you happen to be able to test the printer with these profiles to make sure everything works?
