### ISSUE TITLE
data_dir and opening associated files

### ISSUE THREAD

**Issue by XEGARE** [SoftFever/OrcaSlicer#6987]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.2.0-beta2

### Operating System (OS)

Windows

### OS Version

Windows 11

### Printer

Flying Bear Ghost 6

### How to reproduce

1. Use data_dir
2. Set up associations
3. Open stl/step/3mf file.

### Actual results

data_dir is not used, the OrcaSlicer folder is created in AppData and the initial application configuration window appears

### Expected results

data_dir should be used

### Project file & Debug log uploads

No logs

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by DonutCables** [comment]
I'm encountering the same issue when sending a file to Orca from the 3DPrintPlus plugin in Fusion. It seems like opening Orca indirectly is causing it to not look for `data_dir`.

**Comment by SoftFever** [comment]
should be fixed now
