### ISSUE TITLE
Incorrect cooling fan speed sent to printer

### ISSUE THREAD

**Issue by DTDakin** [SoftFever/OrcaSlicer#704]
**Describe the bug**
Fan speed set to 15% in OrcaSlicer.
Printer ran fan at 10%

**3mf File for This Bug**
Zipped and attached.

**To Reproduce**
Slice file in OrcaSlicer. Print plate on BBL X1C.

**Expected behavior**
Cooling fan should be at 15% during print. Printed at 10% fan speed.

**Screenshots**
Attached shot of OrcaSlicer Fan setting
Attached shot of X1C fan speed during print.

**Printer model**
BBL X1 Carbon, firmware version 01.04.00.00

 - OS: MacOS 13.2.1
 
[Test Sample 0.6Noz PETG 15Fan.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/11182458/Te
<img width="1920" alt="Screenshot 2023-04-07 at 8 33 08 PM" src="https://user-images.githubusercontent.com/130200725/230702184-e8105c79-aefc-42f9-b805-df492e5bb3ea.png">
st.Sample.0.6Noz.PETG.15Fan.3mf.zip)
![IMG_9221](https://user-images.githubusercontent.com/130200725/230702168-6d79b015-89fd-4bf8-844d-6b2e82eb053e.jpg)

**Comment by Yathani** [comment]
Bambu X1 won't show 15% but only every 10%. So 10%, 20% and so on.

If you click on the fan icon on bambu screen you will get another screen to increase fan speed but only +10%
