### ISSUE TITLE
Pressure Advance for different line types and the Z seam

### ISSUE THREAD

**Issue by steezyprintz** [SoftFever/OrcaSlicer#705]
Pressure Advance for different line types would be really useful but also the Z seam a separate value to control too please.

**Comment by mattsiri** [comment]
I second this. It seems that at the higher speeds we are all wanting to print with, 3 distinct PA values would help. With high wall acceleration, the corners tend to develop oscillations. A sufficiently low value for PA can mitigate this to some extent (slowing down an adjustable distance before the corner combined with a separate corner PA would completely resolve the edge oscillations). However, this PA value results in bulging seams and over-extruded edges on top layers and solid infill layers. I've found that the PA needed to clean up the top layers and to hide the seam are also two different values (at least for Braskem FL105PP; other materials may have coincidentally require the same PA value for both or all three even).

Calibration for this sort of thing could be an array of rectangular prisms 5mm tall or so with sides long enough to reach the wall speed (given the wall acceleration) with a seam 10mm or so from one corner. Top layers would show PA_solid, the corners would show PA_corner, and the seam would show PA_seam.
