### ISSUE TITLE
Wipe randomly disabled with Avoid Crossing walls

### ISSUE THREAD

**Issue by Travis90x** [SoftFever/OrcaSlicer#7061]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

Windows

### OS Version

Windows 10 22H2

### Additional system information

Ryzen 4600G + 32GB RAM + SSD M.2

### Printer

Bambulab A1 + AMS

### How to reproduce

using a hollow sphere, wipe distance 1mm + wipe while retracting

### Actual results

the wipe randomly is skipped when avoid crossing wall is enabled

### Expected results

the wipe may still the same if avoid crossing wall is enabled

### Project file & Debug log uploads

[Sfera cava.zip](https://github.com/user-attachments/files/17319782/Sfera.cava.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Anything else?
Avoid crossing walls enabled
![immagine](https://github.com/user-attachments/assets/1e8b9f3d-7e17-4106-a411-4aeb0f20c445)

Avoid crossing walls disabled
![immagine](https://github.com/user-attachments/assets/07a9dfb6-448c-4199-9fb3-1b05ee9b5d17)

**Comment by discip** [comment]
Please test the latest build, as this issue was already addressed!

**Comment by Travis90x** [comment]
> Please test the latest build, as this issue was already addressed!

Thanks, 2.2.0 RC seems to work fine!
