### ISSUE TITLE
One Wall On Top Surfaces inconsistent

### ISSUE THREAD

**Issue by EFlynn7778** [SoftFever/OrcaSlicer#709]
**Describe the bug**
One Wall On Top Surfaces inconsistent. Only doing so part of the time. 

**3mf File for This Bug**
Remove .txt extension from file
[fan_duct_one_wall.3mf.txt](https://github.com/SoftFever/OrcaSlicer/files/11184197/fan_duct_one_wall.3mf.txt)

**To Reproduce**
Unknown. Happens randomly.

**Expected behavior**
One wall perimeters to be generated on all top surfaces.

**Screenshots**
As you can see, one wall being enables, the slicer adheres to the wall count on top surfaces rather than generating a single wall perimeter.

![one_wall](https://user-images.githubusercontent.com/23545711/230741345-8adb0e64-c72a-40b5-aeb1-b78ddb832294.JPG)

**Printer model**
Home built running Klipper, Octopus Max EZ.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by liftbag** [comment]
It's not random behavior. The single wall, with Arachne enabled, is only generated on the topmost layer. The bug is already reported many times. Issues: 379, 459, 547 and 582
