### ISSUE TITLE
no video available for x1c

### ISSUE THREAD

**Issue by crushedpadding** [SoftFever/OrcaSlicer#710]
**Describe the bug**
x1c video feed not available in lan mode. thought this fork allows this for the x1c but get a not supported error

**3mf File for This Bug**
n/a

**To Reproduce**
connect in lan mode and try to start video

**Expected behavior**
live video available to x1c user

**Screenshots**

**Printer model**
x1c

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Windows] windows
 - Version [e.g. 22] 10

**Comment by SoftFever** [comment]
Thanks.
Bambu machines don't support video on LAN.
We are unable to access their proprietary resources. It's best to submit a feature request to their repository.
