### ISSUE TITLE
plate labels not in preview

### ISSUE THREAD

**Issue by crushedpadding** [SoftFever/OrcaSlicer#711]
**Describe the bug**
1.5.0 showed plate type in preview, ex cool plate, high temp, etc.
1.6.1 does not and caused error when printer trying to level and prep to print. in screenshot see label on left missing along with bottom.

**3mf File for This Bug**
n/a

**To Reproduce**
open orca, change plate time, look at preview

**Expected behavior**
plate preview shows expected plate image like old version

**Screenshots**
new:

![screenshot_2023-04-08_192106](https://user-images.githubusercontent.com/130258714/230747964-b2b60c44-15dc-44f1-ba36-54eeafac8d7a.png)

old:

![screenshot_2023-04-08_192227](https://user-images.githubusercontent.com/130258714/230747987-b2f56a41-4986-4077-8b25-913d3d7a6d7d.png)

**Printer model**
x1c

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Windows] windows
 - Version [e.g. 22] 10

**Comment by crushedpadding** [comment]
@SoftFever i think is bug not enhancement since this was old behavior in 1.5 and removal not in change notes.

**Comment by SoftFever** [comment]
You can switch back to the older behavior by turning off "Show auto-calibration marks" in printer settings.
Which will display plate type
