### ISSUE TITLE
G29 command not working from Tronxy X5SA 400

### ISSUE THREAD

**Issue by BahamutWolf** [SoftFever/OrcaSlicer#713]
I renamed the Tronxy X5SA 400 printer profile to D01 PLUS and saved it. Nothing was changed except the print area from 
400x400mm to 330x330mm. When printing, it moves to the middle of the print bed at G29 and only moves up and down the Z axis several times instead of traveling and measuring the print bed.

Printer Model: D01 PLUS

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 22H2 (22621.1485)

**Comment by SoftFever** [comment]
There is nothing I can do about such bug reports.
Please do due diligence/investigation by yourself before raising a ticket.
If you do think it's a bug please provide more details and reproducible steps.
If you are looking for help, please move to the [discussion](https://github.com/SoftFever/OrcaSlicer/discussions)
