### ISSUE TITLE
exe/msi installer for windows

### ISSUE THREAD

**Issue by crushedpadding** [SoftFever/OrcaSlicer#714]
**Is your feature request related to a problem? Please describe.**
not a problem

**Describe the solution you'd like**
included a exe or msi installer for windows to not be just unzip to location

**Describe alternatives you've considered**
b/a

**Additional context**
linux probs could use real nonapp image package too for non ubuntu but i mostly use windows

**Comment by pcout** [comment]
+1
The exe/msi would allow the app to upgrade itself to the newest version.
