### ISSUE TITLE
Fuzzy Skin Modifiers attempting to connect to one another through model. (BUG 2.2.0-rc)

### ISSUE THREAD

**Issue by theboee** [SoftFever/OrcaSlicer#7160]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.2.0-rc

### Operating System (OS)

Windows

### OS Version

Windows 10 22H2

### Additional system information

Ryzen 9 5900X, 6900XT, 32GB DDR4 3200, NVME

### Printer

Creality K1 Max, Ender 3 S1 Pro

### How to reproduce

1. Slice the PY2A Glock frame
2. Enable Fuzzy Skin in global settings and have them be 0.1 on both options
![agagagggg](https://github.com/user-attachments/assets/eb1f25d6-3dc0-439d-a647-fd891d075a5e)
4. Add 2 modifiers on opposite sides of the grip with 0.5 on both options (any number seems to do it)
5. Slice and get the two modified areas attempting to connect through the model
![9846541986](https://github.com/user-attachments/assets/52352954-f238-4114-9de3-d79899f9955b)

### Actual results

![agagagggg](https://github.com/user-attachments/assets/e007beba-3cda-4b39-be83-d9d322c8ec34)
![9846541986](https://github.com/user-attachments/assets/c0dbc0df-a243-4b19-be22-1366a1d9c5be)
![abbabab](https://github.com/user-attachments/assets/550b12bf-ae01-43a0-9d3e-cb4ef804dd1c)

### Expected results

The areas marked by the modifiers should be rougher and not attempt to connect to each other through the model

### Project file & Debug log uploads

[Problem with fuzzy skin.zip](https://github.com/user-attachments/files/17431097/Problem.with.fuzzy.skin.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by Noisyfox** [comment]
Yeah that's odd. Will take a look soon.
