### ISSUE TITLE
[FEATURE REQUEST] Measure tool

### ISSUE THREAD

**Issue by R4toLoko** [SoftFever/OrcaSlicer#717]
Is there any chance of having this measure tool implemented on OS??

It allows you to select a vertex, an edge, radios or a whole face, making it easier to use the slicer itself to make precise boolean operations without having to use a 3D tool such as FreeCAD or Blender.

![image](https://user-images.githubusercontent.com/35049512/230852130-f2bca100-5ee8-4e02-b6eb-872a186694ef.png)
![image](https://user-images.githubusercontent.com/35049512/230852968-5dffc7a2-585e-49f2-9ecd-8509cf834139.png)
![image](https://user-images.githubusercontent.com/35049512/230853244-3f27aa0b-024e-417b-8076-eb2e63bb87bb.png)
![image](https://user-images.githubusercontent.com/35049512/230853381-f72573b3-0356-41a3-9c1e-214f8c5ca7d3.png)

Thank you

**Comment by chrbratt** [comment]
+1 for this.

Very useful when rescaling models and still want to achieve a certain fit for something. :)

**Comment by cybrsage** [comment]
I would LOVE this - I dislike trying to guesstimate this stuff...I am usually slightly wrong.

**Comment by DrKlipper** [comment]
This is also a perfect tool if you reverse engineer some STL files. 
Especially when you measure distances between two holes.

**Comment by JurajMik** [comment]
I have Prusa Slicere just for that. Would be happy to have this in Orca.

**Comment by R4toLoko** [comment]
This is currently being worked on, beta version is available and almost ready for the stable release.
Any issue, testing is being added to that PR.
Closing this ticket.
