### ISSUE TITLE
Fan speed incorrect for first layer after filament change

### ISSUE THREAD

**Issue by psiberfunk** [SoftFever/OrcaSlicer#7171]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.2.0

### Operating System (OS)

macOS

### OS Version

15.0.1

### Additional system information

N/A , slicing issue, not crash/render issue.

### Printer

Bambu X1C

### How to reproduce

1.  Slice attached project.
2. Inspect Layer 200, notice normal fan speed of 18%.
3. Inspect layer 201 , with abnormal fan speed of 100%, which should be ~18-19%.

### Actual results

Notice that layer 201 improperly has 100% fan speed, as inherited from the filament start GCODE sequence, but the normal "on layer change set fan speed" logic doesn't not appear to trigger, leaving the fan @ 100% for the whole layer, until the following layer.    This results in very weak layer bonding in this PETG print (but problem also would apply to most non-PLA/TPU prints).
<img width="1245" alt="Screenshot 2024-10-20 at 11 23 23 AM" src="https://github.com/user-attachments/assets/a7931227-cf80-41c3-917d-277549aad253">

This is bad because it can result in prints looking like this, with an "easy break" layer inserted in by mistake, where the print will likely be extremely weak:
<img width="615" alt="Screenshot 2024-10-20 at 11 43 12 AM" src="https://github.com/user-attachments/assets/ea9c69f5-6742-4c9b-83b8-3b1d1b0c45a3">

And here's the offending filament start GCODE that doesn't get clobbered (like it should) by a layer-change fan instruction:

<img width="1249" alt="Screenshot 2024-10-20 at 11 23 09 AM" src="https://github.com/user-attachments/assets/00d1b015-30bb-4447-a272-c8db4b8dd910">

### Expected results

Fan speed should be normally set according to the filament cooling rules, not according to filament start code during a filament change.  The proper result here would be a fan speed of ~18-19% based on subsequent layers.

### Project file & Debug log uploads

[FanSpeedLayerChangeIssue.3mf.zip](https://github.com/user-attachments/files/17450875/FanSpeedLayerChangeIssue.3mf.zip)

### Checklist of files to include

- [x] Log file
- [X] Project file

### Anything else?

Nasty bug that's hard to notice unless you happen to look at the fan speed preview!

**Comment by psiberfunk** [comment]
Note: this was sliced originally in 2.2.0-beta2 , I just downloaded and verified that this is still a problem with 2.2.0-rc

**Comment by Noisyfox** [comment]
This is in fact caused by the difference in layer time, due to color change.

**Comment by psiberfunk** [comment]
> This is in fact caused by the difference in layer time, due to color change.

I'm not sure that makes any sense here since the nominal layer time due to change of filament is LONGER , not shorter.  Longer layer times result in less cooling... which is obviously not what's happening here.  The key is that there appears to be no per-layer cooling set in the GCODE so that the filament-change GCODE (useful during purging) is clobbering the intended layer-time based fan speed setting.

![image](https://github.com/user-attachments/assets/697a8581-0247-430a-a104-043d2c633fb5)

**Comment by Noisyfox** [comment]
Yeah you're right. Will take a closer look.

**Comment by Noisyfox** [comment]
I think I've noticed something.
If you look at https://github.com/SoftFever/OrcaSlicer/blob/cc8d90c224f6381d2fe68f7f3316275f299c87ea/src/libslic3r/GCode.cpp#L602-L616
there is a `_FORCE_RESUME_FAN_SPEED` after the tool change in func `append_tcr`.
However in func `append_tcr2` there is no such thing.

**Comment by Noisyfox** [comment]
The issue is actually caused by the fan mover. Somehow it removed the `M106 S25` command after color change.

**Comment by Noisyfox** [comment]
![image](https://github.com/user-attachments/assets/9d9a418e-166d-4b05-bd07-277f882d7581)
Fan speed is correct now after disabling fan mover
![image](https://github.com/user-attachments/assets/13261c9c-d0e1-4c8c-a2d1-156d3090178e)

**Comment by psiberfunk** [comment]
Well, that's an evil bug!

  It's still setting the cooling for the wrong layer though.. the long layer time (and hence no need for lots of cooling) should be for the layer before the change, right ?

**Comment by Noisyfox** [comment]
> Well, that's an evil bug! Is it easy to fix for the mover so that kickstart/speedup can still be used?
> 
> Even without the mover, however, It's still setting the cooling for the wrong layer though.. the long layer time (and hence no need for lots of cooling) should be for the layer before the change, right ?

The plan is to exclude the toolchange time at the beginning of each layer, which should work relatively well. Though the better option will be to add that time into previous layer, but that's not possible at current situation due to how each layer is processed individually.

**Comment by psiberfunk** [comment]
> > Well, that's an evil bug! Is it easy to fix for the mover so that kickstart/speedup can still be used?
> > Even without the mover, however, It's still setting the cooling for the wrong layer though.. the long layer time (and hence no need for lots of cooling) should be for the layer before the change, right ?
> 
> The plan is to exclude the toolchange time at the beginning of each layer, which should work relatively well. Though the better option will be to add that time into previous layer, but that's not possible at current situation due to how each layer is processed individually.

Yeah, I recall being told about this kind of linear GCODE generation approach that doesn’t allow look back easily.  It would have to be some kind of post-processing hack or something , and that feels like a nasty bit of tech debt to add here.  I agree that just blowing away the filament swap time from the current layer estimate is “good enough”
