### ISSUE TITLE
Multiple volumetric flow settings per filament

### ISSUE THREAD

**Issue by Ennar1991** [SoftFever/OrcaSlicer#718]
**Is your feature request related to a problem? Please describe.**
Some filaments, especially cheaper filaments, require an extra profile made for them to slow down the printing process to help it flow at a more acceptable rate, maintaining outer perimeter sizes accurately without holes. This was discussed in detail in CNC Kitchen's video titled: "Fast 3D printing is bad for Strength! (and how to fix it!)" (see https://www.youtube.com/watch?v=qBvTWFEd7rk)

**Describe the solution you'd like**
I would like to suggest having multiple volumetric flow settings per feature in a filament (perimeter walls, infill, solid infills) so the speeds are automatically limited by volumetric flow per feature, not just one global volumetric flow rate. E.g. an internal infill can have a much higher volumetric flow than a perimeter wall, when it is not required to be structurally or dimensionally accurate. 

**Describe alternatives you've considered**
A wizard creating a speed profile based on volumetric flow rates is also possible if multiple volumetric rates are not applicable.

Thank you for considering this suggestion.

**Comment by leddhedd** [comment]
SuSl lets you do this by setting default speed to 0, which pulls the autospeed mm3 limit, and then scaling features with % of default. this could be an easy way to implement
