### ISSUE TITLE
[Frature Request] BedLevelVisualizer

### ISSUE THREAD

**Issue by Obicom** [SoftFever/OrcaSlicer#719]
Problem:
In regards of curved heat beds untortunately the auto bed leveling values are not visible
Solution:
If  possible it would be great to get values or better a bed visualisation to be ble to align the bed.
Example:
Take a look how it cloud look like:

https://github.com/jneilliii/OctoPrint-BedLevelVisualizer

**Comment by wociscz** [comment]
I'd say this is not possible, due to encrypted logs from the printer - basically we haven't such data from the printer (bed mesh) available - only Bambulab staff are available to "debug" it from it's logs.
Unless someone decrypt the log files (find the way how to decrypt them).

**Comment by hliebscher** [comment]
i think this is an printer independent slicer and is in most printer interfaces
