### ISSUE TITLE
can't get past filament select 

### ISSUE THREAD

**Issue by thomllama** [SoftFever/OrcaSlicer#723]
**Describe the bug**
Setup locks at "select filament" .. there isn't anything to select but ALL  (Mac M1 version of app)

**To Reproduce**
try and start app, won't get past the setup wizard 

**Expected behavior**
see a list of filament?  I got no clue? 
**Screenshots**
<img width="1213" alt="Screenshot 2023-04-10 at 3 36 23 PM" src="https://user-images.githubusercontent.com/22606587/230982914-5cfcb8f5-00db-4790-bc1e-c448a2969702.png">

**Printer model**
I had to select a rat rig as there is no place to select a custom setup 

**Desktop (please complete the following information):**
 - OS:  Mac mini M1  -  OS Ventura 
 - Version 13.2.1

**Comment by thomllama** [comment]
fixed, guess you just need to restart the computer after install.. sorry to bother you!

**Comment by hliebscher** [comment]
@thomllama  pls close the issue
