### ISSUE TITLE
Ender 5 Plus Config

### ISSUE THREAD

**Issue by SaturnsVoid** [SoftFever/OrcaSlicer#727]
Would be great if OrcaSlicer had a Ender 5 Plus profile, right now i am using SuperSlicer and the development has stagnated.

**Comment by asoderberg** [comment]
I second this request. Thanks!

**Comment by SaturnsVoid** [comment]
It would be great if there was a easy to use way to add custom printers to the configs.

**Comment by hliebscher** [comment]
the easy way is take other ender printer and save as ender 5 plus and change the profile settings.
x y z and speed and accel 

that's it  

then it's easy to add your custom printer json file

**Comment by SaturnsVoid** [comment]
I just took the time to take the stock Ender 3 profile and edit the settings to mach (at least the best i could) to my custom Ender 5+ settings from my SuperSlicer profile, Giving it a test now to see.
