### ISSUE TITLE
OrcaSlicer appImage crashes once physical printer is added

### ISSUE THREAD

**Issue by sanchosk** [SoftFever/OrcaSlicer#7287]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

OrcaSlicer_Linux_Ubuntu2404_V2.2.0_d22db43ebbdfc71078881446efefbb3c.AppImage

### Operating System (OS)

Linux

### OS Version

Debian trixie x86_64

### Additional system information

    description: Computer
    width: 64 bits
    capabilities: smp vsyscall32
  *-core
       description: Motherboard
       physical id: 0
     *-memory
          description: System memory
          physical id: 0
          size: 31GiB
     *-cpu
          product: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
          vendor: Intel Corp.
          physical id: 1
          bus info: cpu@0
          version: 6.140.1
          size: 2612MHz
          capacity: 4700MHz
          width: 64 bits
          capabilities: fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp x86-64 constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l2 cdp_l2 ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves split_lock_detect dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req vnmi avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid movdiri movdir64b fsrm avx512_vp2intersect md_clear ibt flush_l1d arch_capabilities cpufreq
          configuration: microcode=182
     *-pci
          description: Host bridge
          product: 11th Gen Core Processor Host Bridge/DRAM Registers
          vendor: Intel Corporation
          physical id: 100
          bus info: pci@0000:00:00.0
          version: 01
          width: 32 bits
          clock: 33MHz
        *-display
             description: VGA compatible controller
             product: TigerLake-LP GT2 [Iris Xe Graphics]
             vendor: Intel Corporation
             physical id: 2
             bus info: pci@0000:00:02.0
             logical name: /dev/fb0
             version: 01
             width: 64 bits
             clock: 33MHz
             capabilities: vga_controller bus_master cap_list rom fb
             configuration: depth=32 driver=i915 latency=0 resolution=2256,1504
             resources: iomemory:600-5ff iomemory:400-3ff irq:203 memory:605c000000-605cffffff memory:4000000000-400fffffff ioport:3000(size=64) memory:c0000-dffff memory:4010000000-4016ffffff memory:4020000000-40ffffffff
        *-generic:0
             description: Signal processing controller
             product: TigerLake-LP Dynamic Tuning Processor Participant
             vendor: Intel Corporation
             physical id: 4
             bus info: pci@0000:00:04.0
             version: 01
             width: 64 bits
             clock: 33MHz
             capabilities: bus_master cap_list
             configuration: driver=proc_thermal latency=0
             resources: iomemory:600-5ff irq:16 memory:605d180000-605d19ffff
        *-pci:0
             description: PCI bridge
             product: 11th Gen Core Processor PCIe Controller
             vendor: Intel Corporation
             physical id: 6
             bus info: pci@0000:00:06.0
             version: 01
             width: 32 bits
             clock: 33MHz
             capabilities: pci normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:126 memory:7a300000-7a3fffff
           *-nvme
                description: NVMe device
                product: WDS100T3X0C-00SJG0
                vendor: Sandisk Corp
                physical id: 0
                bus info: pci@0000:01:00.0
                logical name: /dev/nvme0
                version: 111110WD
                serial: 21101V446605
                width: 64 bits
                clock: 33MHz
                capabilities: nvme nvm_express bus_master cap_list
                configuration: driver=nvme latency=0 nqn=nqn.2018-01.com.wdc:nguid:E8238FA6BF53-0001-001B444A46D9722F state=live
                resources: irq:16 memory:7a300000-7a303fff memory:7a304000-7a3040ff
              *-namespace:0
                   description: NVMe disk
                   physical id: 0
                   logical name: hwmon2
              *-namespace:1
                   description: NVMe disk
                   physical id: 2
                   logical name: /dev/ng0n1
              *-namespace:2
                   description: NVMe disk
                   physical id: 1
                   bus info: nvme@0:1
                   logical name: /dev/nvme0n1
                   configuration: wwid=eui.e8238fa6bf530001001b444a46d9722f
        *-pci:1
             description: PCI bridge
             product: Tiger Lake-LP Thunderbolt 4 PCI Express Root Port #0
             vendor: Intel Corporation
             physical id: 7
             bus info: pci@0000:00:07.0
             version: 01
             width: 32 bits
             clock: 33MHz
             capabilities: pci normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:127 ioport:4000(size=12288) memory:7c000000-881fffff ioport:6000000000(size=469762048)
           *-pci
                description: PCI bridge
                product: JHL7540 Thunderbolt 3 Bridge [Titan Ridge DD 2018]
                vendor: Intel Corporation
                physical id: 0
                bus info: pci@0000:02:00.0
                version: 06
                width: 32 bits
                clock: 33MHz
                capabilities: pci normal_decode bus_master cap_list
                configuration: driver=pcieport
                resources: irq:16 ioport:4000(size=12288) memory:7c000000-87ffffff ioport:6000000000(size=404750336)
              *-pci:0
                   description: PCI bridge
                   product: JHL7540 Thunderbolt 3 Bridge [Titan Ridge DD 2018]
                   vendor: Intel Corporation
                   physical id: 1
                   bus info: pci@0000:03:01.0
                   version: 06
                   width: 32 bits
                   clock: 33MHz
                   capabilities: pci normal_decode bus_master cap_list
                   configuration: driver=pcieport
                   resources: irq:132 ioport:4000(size=4096) memory:7c000000-822fffff ioport:6000000000(size=270532608)
                 *-display
                      description: VGA compatible controller
                      product: TU116 [GeForce GTX 1660]
                      vendor: NVIDIA Corporation
                      physical id: 0
                      bus info: pci@0000:04:00.0
                      version: a1
                      width: 64 bits
                      clock: 33MHz
                      capabilities: vga_controller bus_master cap_list rom
                      configuration: driver=nvidia latency=0
                      resources: iomemory:600-5ff irq:207 memory:7e000000-7effffff memory:6000000000-600fffffff memory:7c000000-7dffffff ioport:4000(size=128) memory:7f000000-7f07ffff
                 *-multimedia
                      description: Audio device
                      product: TU116 High Definition Audio Controller
                      vendor: NVIDIA Corporation
                      physical id: 0.1
                      bus info: pci@0000:04:00.1
                      logical name: card1
                      logical name: /dev/snd/controlC1
                      logical name: /dev/snd/hwC1D0
                      logical name: /dev/snd/pcmC1D3p
                      logical name: /dev/snd/pcmC1D7p
                      logical name: /dev/snd/pcmC1D8p
                      logical name: /dev/snd/pcmC1D9p
                      version: a1
                      width: 32 bits
                      clock: 33MHz
                      capabilities: bus_master cap_list
                      configuration: driver=snd_hda_intel latency=0
                      resources: irq:18 memory:7f080000-7f083fff
                    *-input:0
                         product: HDA NVidia HDMI/DP,pcm=3
                         physical id: 0
                         logical name: input21
                         logical name: /dev/input/event17
                    *-input:1
                         product: HDA NVidia HDMI/DP,pcm=7
                         physical id: 1
                         logical name: input22
                         logical name: /dev/input/event18
                    *-input:2
                         product: HDA NVidia HDMI/DP,pcm=8
                         physical id: 2
                         logical name: input23
                         logical name: /dev/input/event19
                    *-input:3
                         product: HDA NVidia HDMI/DP,pcm=9
                         physical id: 3
                         logical name: input24
                         logical name: /dev/input/event20
                 *-usb
                      description: USB controller
                      product: TU116 USB 3.1 Host Controller
                      vendor: NVIDIA Corporation
                      physical id: 0.2
                      bus info: pci@0000:04:00.2
                      version: a1
                      width: 64 bits
                      clock: 33MHz
                      capabilities: xhci cap_list
                      configuration: driver=xhci_hcd latency=0
                      resources: iomemory:600-5ff iomemory:600-5ff irq:177 memory:6010000000-601003ffff memory:6010040000-601004ffff
                 *-serial UNCLAIMED
                      description: Serial bus controller
                      product: TU116 USB Type-C UCSI Controller
                      vendor: NVIDIA Corporation
                      physical id: 0.3
                      bus info: pci@0000:04:00.3
                      version: a1
                      width: 32 bits
                      clock: 33MHz
                      capabilities: cap_list
                      configuration: latency=0
                      resources: memory:7f084000-7f084fff
              *-pci:1
                   description: PCI bridge
                   product: JHL7540 Thunderbolt 3 Bridge [Titan Ridge DD 2018]
                   vendor: Intel Corporation
                   physical id: 2
                   bus info: pci@0000:03:02.0
                   version: 06
                   width: 32 bits
                   clock: 33MHz
                   capabilities: pci normal_decode bus_master cap_list
                   configuration: driver=pcieport
                   resources: irq:133 memory:82300000-823fffff
                 *-usb
                      description: USB controller
                      product: JHL7540 Thunderbolt 3 USB Controller [Titan Ridge DD 2018]
                      vendor: Intel Corporation
                      physical id: 0
                      bus info: pci@0000:18:00.0
                      version: 06
                      width: 32 bits
                      clock: 33MHz
                      capabilities: xhci bus_master cap_list
                      configuration: driver=xhci_hcd latency=0
                      resources: irq:178 memory:82300000-8230ffff
              *-pci:2
                   description: PCI bridge
                   product: JHL7540 Thunderbolt 3 Bridge [Titan Ridge DD 2018]
                   vendor: Intel Corporation
                   physical id: 4
                   bus info: pci@0000:03:04.0
                   version: 06
                   width: 32 bits
                   clock: 33MHz
                   capabilities: pci normal_decode bus_master cap_list
                   configuration: driver=pcieport
                   resources: irq:134 ioport:5000(size=4096) memory:82400000-877fffff ioport:6010200000(size=2097152)
        *-pci:2
             description: PCI bridge
             product: Tiger Lake-LP Thunderbolt 4 PCI Express Root Port #1
             vendor: Intel Corporation
             physical id: 7.1
             bus info: pci@0000:00:07.1
             version: 01
             width: 32 bits
             clock: 33MHz
             capabilities: pci normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:128 ioport:7000(size=4096) memory:6e000000-7a1fffff ioport:6020000000(size=469762048)
        *-pci:3
             description: PCI bridge
             product: Tiger Lake-LP Thunderbolt 4 PCI Express Root Port #2
             vendor: Intel Corporation
             physical id: 7.2
             bus info: pci@0000:00:07.2
             version: 01
             width: 32 bits
             clock: 33MHz
             capabilities: pci normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:129 ioport:8000(size=4096) memory:60000000-6c1fffff ioport:6040000000(size=469762048)
        *-pci:4
             description: PCI bridge
             product: Tiger Lake-LP Thunderbolt 4 PCI Express Root Port #3
             vendor: Intel Corporation
             physical id: 7.3
             bus info: pci@0000:00:07.3
             version: 01
             width: 32 bits
             clock: 33MHz
             capabilities: pci normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:130 ioport:9000(size=4096) memory:52000000-5e1fffff ioport:6060000000(size=469762048)
        *-generic:1 UNCLAIMED
             description: System peripheral
             product: GNA Scoring Accelerator module
             vendor: Intel Corporation
             physical id: 8
             bus info: pci@0000:00:08.0
             version: 01
             width: 64 bits
             clock: 33MHz
             capabilities: bus_master cap_list
             configuration: latency=0
             resources: iomemory:600-5ff memory:605d1d8000-605d1d8fff
        *-generic:2
             description: Signal processing controller
             product: Tigerlake Telemetry Aggregator Driver
             vendor: Intel Corporation
             physical id: a
             bus info: pci@0000:00:0a.0
             version: 01
             width: 64 bits
             clock: 33MHz
             capabilities: cap_list
             configuration: driver=intel_vsec latency=0
             resources: iomemory:600-5ff irq:0 memory:605d1c0000-605d1c7fff
        *-usb:0
             description: USB controller
             product: Tiger Lake-LP Thunderbolt 4 USB Controller
             vendor: Intel Corporation
             physical id: d
             bus info: pci@0000:00:0d.0
             version: 01
             width: 64 bits
             clock: 33MHz
             capabilities: xhci bus_master cap_list
             configuration: driver=xhci_hcd latency=0
             resources: iomemory:600-5ff irq:160 memory:605d1b0000-605d1bffff
        *-usb:1
             description: USB controller
             product: Tiger Lake-LP Thunderbolt 4 NHI #0
             vendor: Intel Corporation
             physical id: d.2
             bus info: pci@0000:00:0d.2
             version: 01
             width: 64 bits
             clock: 33MHz
             capabilities: usb4_host_interface bus_master cap_list
             configuration: driver=thunderbolt latency=0
             resources: iomemory:600-5ff iomemory:600-5ff irq:16 memory:605d140000-605d17ffff memory:605d1d7000-605d1d7fff
        *-usb:2
             description: USB controller
             product: Tiger Lake-LP Thunderbolt 4 NHI #1
             vendor: Intel Corporation
             physical id: d.3
             bus info: pci@0000:00:0d.3
             version: 01
             width: 64 bits
             clock: 33MHz
             capabilities: usb4_host_interface bus_master cap_list
             configuration: driver=thunderbolt latency=0
             resources: iomemory:600-5ff iomemory:600-5ff irq:16 memory:605d100000-605d13ffff memory:605d1d6000-605d1d6fff
        *-communication:0
             description: Serial controller
             product: Tiger Lake-LP Integrated Sensor Hub
             vendor: Intel Corporation
             physical id: 12
             bus info: pci@0000:00:12.0
             version: 20
             width: 64 bits
             clock: 33MHz
             capabilities: 8250 bus_master cap_list
             configuration: driver=intel_ish_ipc latency=0
             resources: iomemory:600-5ff irq:16 memory:605d1a0000-605d1affff
        *-usb:3
             description: USB controller
             product: Tiger Lake-LP USB 3.2 Gen 2x1 xHCI Host Controller
             vendor: Intel Corporation
             physical id: 14
             bus info: pci@0000:00:14.0
             version: 20
             width: 64 bits
             clock: 33MHz
             capabilities: xhci bus_master cap_list
             configuration: driver=xhci_hcd latency=0
             resources: irq:168 memory:7a400000-7a40ffff
        *-memory UNCLAIMED
             description: RAM memory
             product: Tiger Lake-LP Shared SRAM
             vendor: Intel Corporation
             physical id: 14.2
             bus info: pci@0000:00:14.2
             version: 20
             width: 64 bits
             clock: 33MHz (30.3ns)
             capabilities: bus_master cap_list
             configuration: latency=0
             resources: iomemory:600-5ff iomemory:600-5ff memory:605d1cc000-605d1cffff memory:605d1d5000-605d1d5fff
        *-serial:0
             description: Serial bus controller
             product: Tiger Lake-LP Serial IO I2C Controller #0
             vendor: Intel Corporation
             physical id: 15
             bus info: pci@0000:00:15.0
             version: 20
             width: 64 bits
             clock: 33MHz
             capabilities: bus_master cap_list
             configuration: driver=intel-lpss latency=0
             resources: irq:27 memory:4017000000-4017000fff
        *-serial:1
             description: Serial bus controller
             product: Tiger Lake-LP Serial IO I2C Controller #1
             vendor: Intel Corporation
             physical id: 15.1
             bus info: pci@0000:00:15.1
             version: 20
             width: 64 bits
             clock: 33MHz
             capabilities: bus_master cap_list
             configuration: driver=intel-lpss latency=0
             resources: irq:40 memory:4017001000-4017001fff
        *-serial:2
             description: Serial bus controller
             product: Tiger Lake-LP Serial IO I2C Controller #3
             vendor: Intel Corporation
             physical id: 15.3
             bus info: pci@0000:00:15.3
             version: 20
             width: 64 bits
             clock: 33MHz
             capabilities: bus_master cap_list
             configuration: driver=intel-lpss latency=0
             resources: irq:30 memory:4017002000-4017002fff
        *-communication:1
             description: Communication controller
             product: Tiger Lake-LP Management Engine Interface
             vendor: Intel Corporation
             physical id: 16
             bus info: pci@0000:00:16.0
             version: 20
             width: 64 bits
             clock: 33MHz
             capabilities: bus_master cap_list
             configuration: driver=mei_me latency=0
             resources: iomemory:600-5ff irq:204 memory:605d1d1000-605d1d1fff
        *-pci:5
             description: PCI bridge
             product: Tiger Lake-LP PCI Express Root Port #10
             vendor: Intel Corporation
             physical id: 1d
             bus info: pci@0000:00:1d.0
             version: 20
             width: 32 bits
             clock: 33MHz
             capabilities: pci normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:131 memory:7a200000-7a2fffff
           *-network UNCLAIMED
                description: Network controller
                product: Wi-Fi 6E(802.11ax) AX210/AX1675* 2x2 [Typhoon Peak]
                vendor: Intel Corporation
                physical id: 0
                bus info: pci@0000:aa:00.0
                version: 1a
                width: 64 bits
                clock: 33MHz
                capabilities: cap_list
                configuration: latency=0
                resources: memory:7a200000-7a203fff
        *-isa
             description: ISA bridge
             product: Tiger Lake-LP LPC Controller
             vendor: Intel Corporation
             physical id: 1f
             bus info: pci@0000:00:1f.0
             version: 20
             width: 32 bits
             clock: 33MHz
             capabilities: isa bus_master
             configuration: latency=0
           *-pnp00:00
                product: PnP device PNP0303
                physical id: 0
                capabilities: pnp
                configuration: driver=i8042 kbd
           *-pnp00:01
                product: PnP device PNP0f03
                physical id: 1
                capabilities: pnp
                configuration: driver=i8042 aux
           *-pnp00:02
                product: PnP device PNP0c02
                physical id: 2
                capabilities: pnp
                configuration: driver=system
           *-pnp00:03
                product: PnP device PNP0c02
                physical id: 3
                capabilities: pnp
                configuration: driver=system
           *-pnp00:04
                product: PnP device PNP0c02
                physical id: 4
                capabilities: pnp
                configuration: driver=system
           *-pnp00:05
                product: PnP device PNP0c02
                physical id: 5
                capabilities: pnp
                configuration: driver=system
        *-multimedia
             description: Audio device
             product: Tiger Lake-LP Smart Sound Technology Audio Controller
             vendor: Intel Corporation
             physical id: 1f.3
             bus info: pci@0000:00:1f.3
             logical name: card0
             logical name: /dev/snd/controlC0
             logical name: /dev/snd/hwC0D2
             logical name: /dev/snd/pcmC0D3p
             logical name: /dev/snd/pcmC0D7p
             logical name: /dev/snd/pcmC0D8p
             logical name: /dev/snd/pcmC0D9p
             version: 20
             width: 64 bits
             clock: 33MHz
             capabilities: bus_master cap_list
             configuration: driver=snd_hda_intel latency=32
             resources: iomemory:600-5ff iomemory:600-5ff irq:16 memory:605d1c8000-605d1cbfff memory:605d000000-605d0fffff
           *-input:0
                product: HDA Intel PCH HDMI/DP,pcm=3
                physical id: 0
                logical name: input25
                logical name: /dev/input/event21
           *-input:1
                product: HDA Intel PCH HDMI/DP,pcm=7
                physical id: 1
                logical name: input26
                logical name: /dev/input/event22
           *-input:2
                product: HDA Intel PCH HDMI/DP,pcm=8
                physical id: 2
                logical name: input27
                logical name: /dev/input/event23
           *-input:3
                product: HDA Intel PCH HDMI/DP,pcm=9
                physical id: 3
                logical name: input28
                logical name: /dev/input/event24
        *-serial:3
             description: SMBus
             product: Tiger Lake-LP SMBus Controller
             vendor: Intel Corporation
             physical id: 1f.4
             bus info: pci@0000:00:1f.4
             version: 20
             width: 64 bits
             clock: 33MHz
             configuration: driver=i801_smbus latency=0
             resources: iomemory:600-5ff irq:16 memory:605d1d0000-605d1d00ff ioport:efa0(size=32)
        *-serial:4 UNCLAIMED
             description: Serial bus controller
             product: Tiger Lake-LP SPI Controller
             vendor: Intel Corporation
             physical id: 1f.5
             bus info: pci@0000:00:1f.5
             version: 20
             width: 32 bits
             clock: 33MHz
             capabilities: bus_master
             configuration: latency=0
             resources: memory:50400000-50400fff
  *-sound
       description: Seri
       physical id: 1
       logical name: card2
       logical name: /dev/snd/controlC2
       logical name: /dev/snd/pcmC2D0c
       logical name: /dev/snd/pcmC2D0p
  *-input:0
       product: AT Translated Set 2 keyboard
       physical id: 2
       logical name: input0
       logical name: /dev/input/event0
       logical name: input0::capslock
       logical name: input0::numlock
       logical name: input0::scrolllock
       capabilities: i8042
  *-input:1
       product: Video Bus
       physical id: 3
       logical name: input10
       logical name: /dev/input/event5
       capabilities: platform
  *-input:2
       product: Logitech USB Receiver
       physical id: 4
       logical name: input11
       logical name: /dev/input/event7
       logical name: input11::capslock
       logical name: input11::compose
       logical name: input11::kana
       logical name: input11::numlock
       logical name: input11::scrolllock
       capabilities: usb
  *-input:3
       product: Logitech USB Receiver Mouse
       physical id: 5
       logical name: input12
       logical name: /dev/input/event8
       logical name: /dev/input/mouse3
       capabilities: usb
  *-input:4
       product: Logitech USB Receiver Consumer Control
       physical id: 6
       logical name: input13
       logical name: /dev/input/event9
       capabilities: usb
  *-input:5
       product: Logitech USB Receiver System Control
       physical id: 7
       logical name: input14
       logical name: /dev/input/event10
       capabilities: usb
  *-input:6
       product: Logitech USB Receiver
       physical id: 8
       logical name: input15
       logical name: /dev/input/event11
       capabilities: usb
  *-input:7
       product: Logitech USB Receiver
       physical id: 9
       logical name: input16
       logical name: /dev/input/event12
       logical name: /dev/input/mouse4
       capabilities: usb
  *-input:8
       product: Plantronics Plantronics Blackwire 3220 Series
       physical id: a
       logical name: input17
       logical name: /dev/input/event13
       capabilities: usb
  *-input:9
       product: Lid Switch
       physical id: b
       logical name: input18
       logical name: /dev/input/event14
       capabilities: platform
  *-input:10
       product: Power Button
       physical id: c
       logical name: input19
       logical name: /dev/input/event15
       capabilities: platform
  *-input:11
       product: PC Speaker
       physical id: d
       logical name: input20
       logical name: /dev/input/event16
       capabilities: isa
  *-input:12
       product: ImExPS/2 Generic Explorer Mouse
       physical id: e
       logical name: input3
       logical name: /dev/input/event6
       logical name: /dev/input/mouse2
       capabilities: i8042
  *-input:13
       product: FRMW0001:00 32AC:0006 Wireless Radio Control
       physical id: f
       logical name: input4
       logical name: /dev/input/event1
       capabilities: i2c
  *-input:14
       product: FRMW0001:00 32AC:0006 Consumer Control
       physical id: 10
       logical name: input5
       logical name: /dev/input/event2
       capabilities: i2c
  *-input:15
       product: PIXA3854:00 093A:0274 Mouse
       physical id: 11
       logical name: input8
       logical name: /dev/input/event3
       logical name: /dev/input/mouse0
       capabilities: i2c
  *-input:16
       product: PIXA3854:00 093A:0274 Touchpad
       physical id: 12
       logical name: input9
       logical name: /dev/input/event4
       logical name: /dev/input/mouse1
       capabilities: i2c
  *-network
       description: Ethernet interface
       physical id: 13
       bus info: usb@8:1.1.4
       logical name: enxaa2018100947
       serial: aa:20:18:10:09:47
       size: 1Gbit/s
       capacity: 1Gbit/s
       capabilities: ethernet physical tp mii 10bt 10bt-fd 100bt 100bt-fd 1000bt 1000bt-fd autonegotiation
       configuration: autonegotiation=on broadcast=yes driver=ax88179_178a driverversion=6.11.4-amd64 duplex=full ip=10.10.10.53 link=yes multicast=yes port=MII speed=1Gbit/s
WARNING: output may be incomplete or inaccurate, you should run this program as super-user.

### Printer

Sovol SV08

### How to reproduce

1. Start OrcaSlicer
2. Configure Sovol SV08 0.4mm nozzle
3. import STL
4. slice
5. export G-code
6. go to Prepare
7. click on "wifi" icon to connect physical printer
8. provide DNS name of the printer
9. test the connection
10. click OK

### Actual results

From that moment on, OrcaSlicer crashes and I can no longer start it - it starts, shows the initial screen and crashes again.
The error message in shell only states "No such file or directory".

### Expected results

The slicer should work and show printer interface.

### Project file & Debug log uploads

Unable to save project file - the app crashes before I manage to do anything.
[debug_Tue_Oct_29_12_23_39_22000.log.0.zip](https://github.com/user-attachments/files/17556062/debug_Tue_Oct_29_12_23_39_22000.log.0.zip)

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Anything else?

I need to delete the whole config and start again to be able to use the slicer.

**Comment by sanchosk** [comment]
Tried GDB and this was the outcome:
```
[Inferior 1 (process 60993) exited normally]
(gdb) ERROR: WebKit encountered an internal error. This is a WebKit bug.
./Source/WebKit/WebProcess/Network/WebLoaderStrategy.cpp(562) : internallyFailedLoadTimerFired
ERROR: WebKit encountered an internal error. This is a WebKit bug.
./Source/WebKit/WebProcess/Network/WebLoaderStrategy.cpp(562) : internallyFailedLoadTimerFired
ERROR: WebKit encountered an internal error. This is a WebKit bug.
./Source/WebKit/WebProcess/Network/WebLoaderStrategy.cpp(562) : internallyFailedLoadTimerFired
ERROR: WebKit encountered an internal error. This is a WebKit bug.
./Source/WebKit/WebProcess/Network/WebLoaderStrategy.cpp(562) : internallyFailedLoadTimerFired
ERROR: WebKit encountered an internal error. This is a WebKit bug.
./Source/WebKit/WebProcess/Network/WebLoaderStrategy.cpp(562) : internallyFailedLoadTimerFired
ERROR: WebKit encountered an internal error. This is a WebKit bug.
./Source/WebKit/WebProcess/Network/WebLoaderStrategy.cpp(562) : internallyFailedLoadTimerFired

```

**Comment by CitrusIntellect** [comment]
At least you somewhat loaded it, #6908 #6520

**Comment by sanchosk** [comment]
Closing as duplicate as #7210 is describing the same issue and includes a workaround. Thanks! For some reason, browsing issues did not display this one, probably because mine does not Segfaults...
