### ISSUE TITLE
A G-code path goes beyond plate boundaries in Orca for Bambu printers; Same 3MF in Bambu Studio slices with no issues.

### ISSUE THREAD

**Issue by lexadevelop** [SoftFever/OrcaSlicer#7321]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.2.0

### Operating System (OS)

Linux

### OS Version

Ubuntu 24 / Windows 10 (happens on both)

### Printer

Bambu Lab X1C; Bambu Lab P1S (same result for both)

### How to reproduce

1. Download 3MF attached
2. In Orca Slicer:
- set either Bambu Lab X1C or Bambu Lab P1S printer.
- choose 0.2 or 0.4 nozzle
- set the '0.20mm Standard' profile' (for 0.4 nozzle)
- choose No-brim (otherwise it will go out of the plate boundaries, but the SUBJ error is not brim related)
4. Slice
5. Observe the error. 

### Actual results

A SUBJ error is displayed. 

### Expected results

Slicer completes the plate without the errors. NOTE: Bambu Studio does that with the exact same model and settings without the issues.

### Project file & Debug log uploads

[Project.zip](https://github.com/user-attachments/files/17589294/Project.zip)
[debug.log.zip](https://github.com/user-attachments/files/17589298/debug.log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Anything else?

See screenshots below.
NOTE 1: this MIGHT have been my local issue, like some filament/profile related, but I NEVER used 0.2 nozzle and I only enabled it for the testing purposes, yet I get the same error for 0.2 nozzle. Interesting enough, error does not appear for 0.6 and 0.8 (never used them either).
NOTE 2: if right pane is set to Line Type and Display checkbox for the Internal Solid Infill is checked, there are visible purple travels (lines) somewhere far far away from the model/plate boundaries.
NOTE 3: Bambu Studio does that with the exact same model and settings without the issues.
NOTE 4: Despite the logs saying 1.9.5.1, I sure DO have 2.2.0, at least thats what it says on About screen (Attached).

![Screenshot from 2024-10-31 15-49-22](https://github.com/user-attachments/assets/4eba1b67-a738-4c2a-ae41-956994111129)
![Screenshot from 2024-10-31 15-42-48](https://github.com/user-attachments/assets/d13debf3-e16c-43cc-922d-3bea7f80a4cc)
![Screenshot from 2024-10-31 15-42-20](https://github.com/user-attachments/assets/5b67c93d-da54-4dc5-8d7e-329b85e434e0)
![Screenshot from 2024-10-31 15-41-26](https://github.com/user-attachments/assets/0dac386c-7467-4a40-8bf8-3f5784404d70)

**Comment by kcorbett95** [comment]
I am having the same issue, was not present with this exact .3mf file on the previous version of orca
![Screenshot 2024-10-31 111827](https://github.com/user-attachments/assets/e7eefd3c-eefd-4fae-a02a-687567855270)

**Comment by Noisyfox** [comment]
This issue is introduced in 9b2c2bff1db5f3958f35f4423167dd24f1f12b1d 
Will take a look.

**Comment by Noisyfox** [comment]
Please try build from PR #7330

**Comment by lexadevelop** [comment]
Still getting the same issue with PR7330. I got the AppImage (see the attachment), and sliced the same drawer, still getting the same GCode message (see the second attachment). 

BUT what's different is that I get 3 new lines going nowhere, which were not there before and which are visible on the attachment (those which are going north-west on the screen).

![Screenshot from 2024-11-02 15-53-43](https://github.com/user-attachments/assets/4a8963af-954f-426b-a18e-b79f6bf6bd1e)
![Screenshot from 2024-11-02 15-54-13](https://github.com/user-attachments/assets/e217a703-a81f-410f-bd52-5d62d524144e)

**Comment by Noisyfox** [comment]
Odd... Will take a look

**Comment by Noisyfox** [comment]
I tested on Ubuntu 24.04 and I no longer get the error when using Arachne mode, but get the same issue with classic mode instead... Weird.

**Comment by Noisyfox** [comment]
Ok so I misunderstood your original post since I thought it's the same issue as #6949 so I only debuged the issue using Arachne wall generator (and I couldn't reproduce the issue with the Windows machine I used daily). Will try fixing the classic mode next.

**Comment by Noisyfox** [comment]
As a workaround, you could try disable the "Detect narrow internal solid infill" and see if that helps.

**Comment by Noisyfox** [comment]
Could you give the new build another try?

**Comment by lexadevelop** [comment]
I can confirm the original issue with the drawer is gone with the latest 7330 build.
Thank you.

**Comment by ElForastero** [comment]
2.3.0-dev, unfortunately, the issue is still there.

<img width="1128" alt="image" src="https://github.com/user-attachments/assets/61e34c32-388e-4798-b3ff-86696e7043c0">
