### ISSUE TITLE
Stop using <username.local> to access printer

### ISSUE THREAD

**Issue by EaglePPP** [SoftFever/OrcaSlicer#7348]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I was frustrated when I tried to connect Orca to my printer(octopi) 
somehow when i click the device, it redirected to another service i am running on my local network.
After using Wireshark, I figured Orca was not using X.X.X.X:5000 to access my octopi but <username.local>
(i am wondering if this might be THE problem)
This is due to that i am using the same username in my home server and octopi.

Now it's either change my Ubuntu homeserver's username
or
investigate nginx rp problem
or
change username in Octopi

### Which printers will be beneficial to this feature?

Others

### Describe the solution you'd like

stop using it <username.local>(at least give a warning)
or
add a possibility to change that

**Comment by Jomik** [comment]
You should be able to set this yourself..?
![image](https://github.com/user-attachments/assets/3ecb7cda-e22c-4e9b-8a00-bf698f28e74e)
Set the `Hostname, IP or URL` field to whatever you want.
If you have set it to `username.local` like I have, then of course it will ask your DNS (router) to resolve that to an ip to know where to go. If your DNS points at something wrong, then that's its fault.
The only thing OrcaSlicer can do is to ask for the IP and then use that, which it does. You may fix it by explicitly using your IP though :)

**Comment by Jomik** [comment]
Can you show your Physical printer config dialogue? The one I linked above.

**Comment by Jomik** [comment]
Ohh, you are right. `Device UI` seems to be the URL to your Device's web-ui if it is not default.
So try and remove that `iggz` (why do you have that there?
Ref: https://github.com/SoftFever/OrcaSlicer/blob/1088d0a6c713250ee3d14da791e27b76b4339363/src/slic3r/GUI/MainFrame.cpp#L3707

**Comment by Jomik** [comment]
> Oh ok now it works,

Awesome! Glad that we solved it 💪 maybe you can suggest a change to the translation - don't know if they'll accept it, I'm not a contributor, just saw this issue 😁
