### ISSUE TITLE
Models Appear solid black

### ISSUE THREAD

**Issue by K32design** [SoftFever/OrcaSlicer#735]
When loading a new .stl file the model appears on screen in a black colour and it is impossible to see any details of the model.

I have tried several different .stl files and models of varying geometry and complexity and get the same result

<img width="884" alt="image" src="https://user-images.githubusercontent.com/130550909/231410014-80ebb1f2-b6fc-439b-bbbe-15dc23929e28.png">

**Describe the bug**

**3mf File for This Bug**
If it is related to slicing, please append the 3mf file. It could be extremely helpful to solve the issue.

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**

**Printer model**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Windows]

**Comment by Ibot-11** [comment]
Change the filament color
![image](https://user-images.githubusercontent.com/84148069/231661882-7628f890-0856-4ecc-96e5-95987bfa1091.png)
or
![image](https://user-images.githubusercontent.com/84148069/231661969-957bcb09-5cbc-42c1-b374-b6db6e37372b.png)

**Comment by K32design** [comment]
I have tried this and it doesnt change anything.
tried several colours, tried selecting the part and then the filament colour, tried changing filament type and colour but its always black

<img width="956" alt="image" src="https://user-images.githubusercontent.com/130550909/231676827-c288c67a-c91f-4c7d-8e8d-cde4001e2947.png">
