### ISSUE TITLE
some filament profiles not showing in orca

### ISSUE THREAD

**Issue by steven850** [SoftFever/OrcaSlicer#739]
Some of my filament profiles are not showing in orca after updating from softfever 1.4.5
it seems any profile that had a PA value is not showing up in the UI anymore. 

Below is a screenshot showing the folder vs whats showing in orca. 
the matte blue I just added in orca and it shows in the folder. The matte black was added in softfever 1.4.5 and is not showing in the slicer. 
![filament](https://user-images.githubusercontent.com/43098060/231443442-3d27e09c-ce2a-421b-bc1e-297d412264a4.png)

Orca 1.61 on windows 10. 
Bambu X1 Carbon w AMS
Filament JSON shows  "version": "1.4.1.4"

**Comment by DanagaMoose** [comment]
Any workaround on getting the profiles added back into Orcaslicer other than downgrading the install?
