### ISSUE TITLE
Nozzle scratch top layer/surface

### ISSUE THREAD

**Issue by rcxrbt** [SoftFever/OrcaSlicer#741]
**Describe the bug**
I'm new in OrcaSLicer and I'm not sure if this is a bug or I'm wrong, but whit other slicer,  I don't have it.
Nozzle scratch top layer/surface on travel... please, see the pic.

**3mf File for This Bug**
[nozzle_scracth.zip](https://github.com/SoftFever/OrcaSlicer/files/11215049/nozzle_scracth.zip)

**To Reproduce**
Normale slicing

**Expected behavior**
Add some behavior to lift Z axis during travel on top layer/surface or not travl on surface (like Cura)
![image](https://user-images.githubusercontent.com/64079048/231561242-911a61ef-cde5-47c9-a843-540a9b5b7a13.png)

**Screenshots**
![top_layer](https://user-images.githubusercontent.com/64079048/231560345-5858ba85-12b0-4784-8d33-f3bac4d25652.JPG)

**Printer model**
Sapphire Plus - SP5 (modded)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 1.6.1

Tnx!

**Comment by hliebscher** [comment]
@rcxrbt  in printer settings you have z-hop = 0 set to 0,4

**Comment by rcxrbt** [comment]
> 

ok, but this is always involved? like every retraction or only in top surface?

**Comment by rcxrbt** [comment]
> @rcxrbt in printer settings you have z-hop = 0 set to 0,4

Do you refer this?

![image](https://user-images.githubusercontent.com/64079048/232412036-dcda5f85-82ed-4035-b75a-212e21c8058a.png)

I dont want to z-hop every retraction...
