### ISSUE TITLE
Project File doesn’t load properly

### ISSUE THREAD

**Issue by Ibot-11** [SoftFever/OrcaSlicer#742]
When I open a 3MF project Orcaslicer is not able to load it properly. Everything looks fine until I save the file and restart / reopen the project. 
Some models have very poor mesh quality and many multicolor prints are shifted. When exporting them as a generic 3mf everything works fine.

[A_Drive_Lower.zip](https://github.com/SoftFever/OrcaSlicer/files/11215246/A_Drive_Lower.zip)
![image](https://user-images.githubusercontent.com/84148069/231566680-4ac17838-b0f6-4f4e-90bf-74962e594034.png)

**Comment by SoftFever** [comment]
Seems I can't download the file

**Comment by Ibot-11** [comment]
Okay for me the download works.
Here is a reupload:
[A_Drive_Lower.zip](https://github.com/SoftFever/OrcaSlicer/files/11225494/A_Drive_Lower.zip)
You have to unzip the file since I can’t upload a 3MF file to github.

**Comment by hliebscher** [comment]
sometimes i have the same issue if the stl's are very big ... an many plates 
Mac M1  but it is since V 1.5 but not to reproduce
