### ISSUE TITLE
Diferrent and weird gcode after saving and reopening project

### ISSUE THREAD

**Issue by szymswiat** [SoftFever/OrcaSlicer#7437]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.2.0

### Operating System (OS)

Linux

### OS Version

Ubuntu 24.04

### Printer

Bambu Lab A1

### How to reproduce

1. Create new project and add [attached](https://github.com/user-attachments/files/17692439/test_cyl_thread.stl.zip) object to a plate
2. I set preset to 0.08mm extra fine however the issue occured with other presets as well
3. Slice plate and observe the result

![2024-11-10_17-38](https://github.com/user-attachments/assets/10f463c8-7093-4f8c-874d-669a0c69aeae)
![2024-11-10_17-39](https://github.com/user-attachments/assets/1b06c664-9452-45bb-b738-c8f4bd0707cb)

5. Save project and close Orca Slicer
6. Open it and slice again

### Actual results

After reopening a project and slicing a plate Orca Slicer adds weird bridge and top surface layers.

![2024-11-10_17-41](https://github.com/user-attachments/assets/eaafe8d1-6b57-4b47-bc98-06083bef22e8)

### Expected results

Unwanted bridge in the air should not appear.

### Project file & Debug log uploads

[test_cyl_thread2.3mf.zip](https://github.com/user-attachments/files/17692467/test_cyl_thread2.3mf.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by Arakon** [comment]
The STL is not manifold. Is it possible you repaired it the first time, but the repair gets lost when reloading the project?
[test_cyl_thread-repaired.zip](https://github.com/user-attachments/files/17692922/test_cyl_thread-repaired.zip)
Can you try the same thing with this repaired version of the stl?

**Comment by szymswiat** [comment]
Repaired? According to the pop-up notification, repair is not supported under Linux.
