### ISSUE TITLE
[Feature Request] - Port over the add / edit text from Prusa Slicer 2.6

### ISSUE THREAD

**Issue by ondrovic** [SoftFever/OrcaSlicer#744]
**Is your feature request related to a problem? Please describe.**
Prusa slicer allow you to add a `text` object to an item, once you save the `.3mf` you can then go back later and edit it need be 

**Describe the solution you'd like**
Grab this functionality from Prusa slicer

**Describe alternatives you've considered**
Using Prusa slicer to add / edit text, save then bring into Orca Slicer

**Additional context**

1. In Prusa Slicer (2.6) add an object / stl / etc
2. Right Click on object
3. Select Text (the below pops up)
![image](https://user-images.githubusercontent.com/3682042/231594660-33bfe20b-6234-4d2b-bf2f-4380f6ed20ae.png)
![image](https://user-images.githubusercontent.com/3682042/231594765-e60ff6ee-569b-420e-a842-a31fd7c12ba3.png)
4. Edit your text, save project / stl

**Comment by SoftFever** [comment]
Yes, PrusaSlicer 2.6 has quite a few nice features.
I will start to merge them when it's in the stable release(beta or official).
