### ISSUE TITLE
Remove limit on nozzle size

### ISSUE THREAD

**Issue by gaiosa** [SoftFever/OrcaSlicer#752]
Currently, the nozzle diameter size is limited to a maximum of 1.0 mm. Sometimes I want to use a nozzle diameter that is larger than 1.0 mm, so I can make strong parts with large layer widths and heights. However, if I am using a 1.4 mm nozzle, I have to set the machine to a 1.0 mm nozzle. This means I can't set the layer height any higher than the nozzle size of 1.0 mm, but I like to run the 1.4 mm nozzle with a layer height of 1.12 mm (80% of nozzle size). Could the maximum nozzle size limit be removed?

![image](https://user-images.githubusercontent.com/117310091/232046290-69a6f504-e7a8-4864-ab6c-370c53f61116.png)

**Comment by SoftFever** [comment]
will relax the limitation in next build

**Comment by gaiosa** [comment]
Great, thanks!

**Comment by FlowForm** [comment]
Awesome, gonna test my 1.8 very soon :-)

**Comment by SoftFever** [comment]
1.8mm nozzle go go go!
:)

![image](https://user-images.githubusercontent.com/103989404/232936576-3f9fc6fd-6710-4b91-a561-48d96e2f97c3.png)

**Comment by MoiRam14** [comment]
I was able to print with 1.4mm nozzle using custom preset I made like 2 or 3 months ago after I upgraded to the biqu panda hottend and bought some revo nozzles. But now I see that I get stuck on the nozzle not matching the size set on printer parts setting. Can't add any new sizes to that list. So effectively I can't use my 1mm, 1.2mm or 1.4mm nozzle anymore.
