### ISSUE TITLE
building on ubuntu

### ISSUE THREAD

**Issue by agesagem** [SoftFever/OrcaSlicer#753]
**Describe the bug**
the make end in this error:
OrcaSlicer/src/libslic3r/ArcFitter.cpp:130:48: error: incomplete type ‘Slic3r::MultiPoint’ used in nested name specifier
  130 |             straight_or_arc_part = MultiPoint::_douglas_peucker(straight_or_arc_part, tolerance);

**3mf File for This Bug**
app is not build yet

**To Reproduce**
git clone this one and cd into it
sudo ./BuildLinux.sh -udisr
cd deps ; mkdir build ; cd build
cmake .. -DDEP_WX_GTK3=ON
make
cd ../..
mkdir build
cd build
cmake .. -DSLIC3R_STATIC=1 -DSLIC3R_GTK=3 -DSLIC3R_PCH=OFF -DCMAKE_PREFIX_PATH=$(pwd)/../deps/build/destdir/usr/local
make -j4

**Expected behavior**
 binary is build

**Screenshots**

**Printer model**

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Version 22.04.2 LTS

**Comment by SoftFever** [comment]
Please move to discussion for build helps
