### ISSUE TITLE
Slicing produces broken GCODE

### ISSUE THREAD

**Issue by Ohmarinus** [SoftFever/OrcaSlicer#7538]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.2.0

### Operating System (OS)

Windows

### OS Version

Windows 10 22H2

### Additional system information

AMD Ryzen 7 4800H with Radeon Graphics
Nvidia GeForce RTX 2060
32Gb

### Printer

Bambu Lab X1C

### How to reproduce

Slice, and see this result:
![image](https://github.com/user-attachments/assets/eae6aa45-bdbc-4546-a4ad-9fc9b6c4451a)

I get this result with the specific settings I've used. But if I change settings around I get a result that is not broken. The mesh reports as ok.

### Actual results

See 'How to reproduce', the issue is clear.

### Expected results

The expected result is no error in the generated GCODE.

### Project file & Debug log uploads

Project file:
[roci_error.zip](https://github.com/user-attachments/files/17848054/roci_error.zip)

Debug:
[debug_Thu_Nov_21_16_11_12_35504.log.zip](https://github.com/user-attachments/files/17848106/debug_Thu_Nov_21_16_11_12_35504.log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by discip** [comment]
@Ohmarinus
You forgot the **`%`**.

![image](https://github.com/user-attachments/assets/a7e81ca1-7071-4470-b302-11f0aa53f1db)

**Comment by Ohmarinus** [comment]
> @Ohmarinus You forgot the **`%`**.
> 
> ![image](https://private-user-images.githubusercontent.com/53649486/388596434-a7e81ca1-7071-4470-b302-11f0aa53f1db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyMDYxMjMsIm5iZiI6MTczMjIwNTgyMywicGF0aCI6Ii81MzY0OTQ4Ni8zODg1OTY0MzQtYTdlODFjYTEtNzA3MS00NDcwLWIzMDItMTFmMGFhNTNmMWRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDE2MTcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkMTM5NWYwNjJhOTRhNzk2OGIxNDI1NjI1YTUxNGI1MWQyNGNmNjJhMTI4OWY3MDM2YjhhNWM5YzIyYjQ5NWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.l-4SicEjsMOBKWTcmjvMmCANAruExeKedvX8jUAKxZ8)

Thanks, that was it.. Now I feel so dumb haha. Okay, that was indeed the issue, and not a bug in Orca. Thanks a lot!

**Comment by discip** [comment]
Nevermind.
You are welcome!
