### ISSUE TITLE
Is it possible to tie profiles to dependencies (i.e. Nozzle size?)

### ISSUE THREAD

**Issue by jonathanalevi** [SoftFever/OrcaSlicer#754]
I would very much like for there to be a way to "pair" profiles to nozzles, so that they only show when that nozzle is selected. 
When I am using the printer profile that has a 0.8mm nozzle, it shouldn't show me 20 other profiles... only the ones that match 0.8mm nozzle...

**Comment by hliebscher** [comment]
look at snapmaker j1 profile for 0.4 and 0.6 mm nozzle the profile 0.6 works only with j1 0.6

**Comment by jonathanalevi** [comment]
How do I do that with my own profiles, though?
