### ISSUE TITLE
Slow filament change display after failover.

### ISSUE THREAD

**Issue by vicpylon** [SoftFever/OrcaSlicer#755]
**Describe the bug**
When the printer fails over to another roll of identical filament when the first roll empties, the display takes 10-15 minutes to update to show it has switched to the new roll.

**To Reproduce**
Let the machine fail over and watch the status screen. This took about 15 minutes to appear. It started on the third roll and then eventually showed the fourth roll being  used.

![image](https://user-images.githubusercontent.com/35160110/232087107-e3d60d4c-36fc-47c8-9dd9-93632c40e64c.png)

**Expected behavior**
Should change the display much faster, since a manual check of the printer indicated it was using the new roll. 
**Screenshots**

**Printer model**

**Desktop (please complete the following information):**
Mac M1 
Ventura 13.2.1

**Comment by SoftFever** [comment]
Thank you for submitting the ticket. 
However, since this issue requires interaction with Bambu's proprietary firmware, it would be best to submit a request on their repository.

**Comment by SoftFever** [comment]
Closing it as explained.
