### ISSUE TITLE
Reverse on odd does not work when reverse threshhold is set to 0

### ISSUE THREAD

**Issue by Mental-Inferno** [SoftFever/OrcaSlicer#7555]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.2.0

### Operating System (OS)

Windows

### OS Version

Windows 11

### Printer

Prusa Mini+

### How to reproduce

1. Turn on "Reverse on odd"
2. Set "Reverse threshold" to 0

### Actual results

The perimeters do not alternate extrusion directions (clockwise vs counter-clockwise).

### Expected results

The perimeters should alternate extrusion directions (clockwise vs counter-clockwise).

### Project file & Debug log uploads

[Voron_Design_Cube.zip](https://github.com/user-attachments/files/17893852/Voron_Design_Cube.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Anything else?

![image](https://github.com/user-attachments/assets/15cf8606-dda2-426a-a99d-7393d03e3ebc)

**Comment by MxBrnr** [comment]
Update software. This issue has been fixed in OrcaSlicer v2.2.0.

**Comment by Brendan-Lobo** [comment]
Just updated, this problem persists

**Comment by Mental-Inferno** [comment]
Updated and tired again, this problem persists

**Comment by Mental-Inferno** [comment]
Interesting, it seems to be working after I restarted my computer. I didn't know OrcaSlicer requires a computer restart for the update to take effect, I'd assumed that restarting the application would be enough. Closing the issue.

**Comment by Mental-Inferno** [comment]
Interesting, it seems to be working after I restarted my computer. I didn't know OrcaSlicer requires a computer restart for the update to take effect, I'd assumed that restarting the application would be enough. Closing the issue.

**Comment by MxBrnr** [comment]
It is weird that is what it needs sometimes; don't know why. Glad we got it worked out for you though.
