### ISSUE TITLE
Set maximum speed in filament

### ISSUE THREAD

**Issue by Murolack** [SoftFever/OrcaSlicer#7567]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I have filaments from different vendors and sometimes I even mix them together in one print. But the filaments has different maximum print speeds. I can only set it in the print profile and not in the profile for the filament, so I would so down other filaments, too.

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

It would be really helpful if I could set the maximum print speed in the filament profile. So even if I set a higher speed in the print profile the filament maximum will cap it.

**Comment by VigilantGardener** [comment]
This protection already exists.

In the filament profile, the filament tab, at the bottom is "Max volumetric speed"(MVS).  This limits the max volume of the filament in mm^3/sec.  If the print speed set in the process would exceed the value set for MVS, the speed will be throttled so that extrusion does not exceed the MVS.

This is a facet of a filament profile that should be tested and set correctly.  There is no one size fits all value for MVS, it will vary by filament type, print temperature, hot end design, nozzle design, maybe other factors too.  For my setup 10mm^3/sec at 210C is great for PLA, but again there are NO one size fits all values.

CNC Kitchen, and others, have tutorials on youtube on how to determine MVS.

At least one one of the filament profiles I had was set to an MVS of 200mm^3/sec, which is ridiculous, and that excessive and unrealistic value did cause problems with prints until it was found and corrected.

**Comment by VigilantGardener** [comment]
> But I'm not talking about the mm³/s. I'm talking about the mm/s. As an example I've testet that for my filament a MVS of 18mm³/s with a speed of 170mm/s is perfect. But for other filament I can go up to 250mm/s with even higher MVS. If I set the speed to 250mm/s my "bad" filament is not throttled. I will get bad results. If I'm using only one filament I can set it in the print profile. But if I'm using both together I've so slow down the speed for both.

I think I understand what you're saying, but I do have a question.

Are you using the same filament profile for two different filaments?

**Comment by Murolack** [comment]
No, I have two profiles for the filaments. More concrete:
1. filament profile -> Bambu Lab Filament | MVS is set to 21 mm³/s
2. fialment profile -> Redline Filament MVS is set to 18 mm³/s

1. filament can be printed at 250mm/s and 2. only at 170mm/s. 

The other profile I meant is the print profile, where you set you quality, strength, support and the different types of speed. Like first layer speed, outer wall speed and so on.
But this profile is not per filament it is per print.

**Comment by VigilantGardener** [comment]
What's the typical nozzle size, line width, and layer height that you print at?

**Comment by Murolack** [comment]
Mostly with:
nozzle: 0.4mm
line width: ~0.4mm
layer height: 0.2mm

**Comment by MxBrnr** [comment]
Sounds like this is not an enhancement, but rather a bug, where the lower MVS is being ignored. It should be throttling the speed to not exceed the MVS for whichever filament is currently in use.

**Comment by VigilantGardener** [comment]
![Print Speed Controlled by MVS](https://github.com/user-attachments/assets/bd8b8697-8878-41aa-8488-1c37d63c370f)

I think that this is just a matter of settings.  In this image filament 1 has an MVS of 13.6 and filament 2 has an MVS of 20

All that I had to do to accomplish the change in speeds was to set the MVS correctly and then crank the speeds and acceleration until the max speeds were achieved.  To be honest, I just cranked speed and acceleration until the desired results were achieved.  This is something that needs to be really tuned in properly to make sure that the end prints are of good quality.

The formula for MVS based on speed is as follows:
Line Width(mm) x Layer Height(mm) x speed(mm/s)
0.4 x 0.2 x 170 = 13.6
0.4 x 0.2 x 250 = 20.0

**Comment by Murolack** [comment]
I think you're totally right. I tried it out and it seems to work. My thought was that these values are completely independent, because if I print with a certain speed and I'm just pushing more filament out it should work. It maybe doesn't make sense, but should work.
So it was my fault and I'm closing this ticket and thank you for clarification.

**Comment by VigilantGardener** [comment]
> I think you're totally right. I tried it out and it seems to work. My thought was that these values are completely independent, because if I print with a certain speed and I'm just pushing more filament out it should work. It maybe doesn't make sense, but should work. So it was my fault and I'm closing this ticket and thank you for clarification.

I'm glad its working for you
