### ISSUE TITLE
Crash when changing line width of Pressure Advance Pattern Calibration

### ISSUE THREAD

**Issue by Finnitio** [SoftFever/OrcaSlicer#7569]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.2.0

### Operating System (OS)

Windows

### OS Version

Windows 11 latest

### Additional system information

Ryzen 9 5900X
B450 ROG STRIX Gaming
64 gb DDR4 3200 MHz
Quadro P2000

### Printer

CR-10 Pro V2

### How to reproduce

Create Pressure Advance Pattern Calibration
Change line width to standard
Click Slice Plate

### Actual results

Crash

### Expected results

Preview of sliced model

### Project file & Debug log uploads

[Cube.zip](https://github.com/user-attachments/files/17901326/Cube.zip)
[crash_Mon_Nov_25_11_24_42_0.zip](https://github.com/user-attachments/files/17901327/crash_Mon_Nov_25_11_24_42_0.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Anything else?

![image](https://github.com/user-attachments/assets/cc5de5bb-d9b7-4167-96fd-ff24eebbe893)

**Comment by Noisyfox** [comment]
The crash is caused by having the default line width to be a percentage.
