### ISSUE TITLE
Incorrect display of Cyrillic fonts when trying to translate (Russian, Ukrainian, Bulgarian)

### ISSUE THREAD

**Issue by Andrewvs599** [SoftFever/OrcaSlicer#757]
**Describe the bug**
When trying to create a translation of the program interface into Russian, Ukrainian or Bulgarian, Cyrillic characters are displayed as ?????? in some application areas. The main interface is displayed correctly. There is also a problem with Cyrillic characters described in #671.

**To Reproduce**
Create a translation file for the specified languages and replace the translation file of any language in the i18n folder with it. Select the replaced language in the program properties.

**expected behavior.**
Correct display of Cyrillic

**Printer model**
Bambu Lab X1 Carbon Combo

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 21H2
 
![orca3](https://user-images.githubusercontent.com/112972902/232190511-12f265af-8bc8-4cdd-b61d-0895717e48c2.JPG)
![orca1](https://user-images.githubusercontent.com/112972902/232190514-77617a89-f456-43b9-ab9d-a302738458e5.JPG)
![orca2](https://user-images.githubusercontent.com/112972902/232190517-e2935e6d-6ba7-4b47-a5fc-643a09373e94.JPG)

**Comment by SoftFever** [comment]
@Andrewvs599 
Can you create a PR for this so that I can take a look what could be wrong?

**Comment by gogsi1** [comment]
> @Andrewvs599 Can you create a PR for this so that I can take a look what could be wrong?

Please write if you are going to fix this problem?
