### ISSUE TITLE
Slicer generates artifacts 

### ISSUE THREAD

**Issue by voland696** [SoftFever/OrcaSlicer#7600]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.2.0

### Operating System (OS)

Windows

### OS Version

Windows 10

### Printer

Generic Klipper printer

### How to reproduce

Slice model with manual tree support, 5 walls
![orca model1](https://github.com/user-attachments/assets/642fb654-88ab-426e-91f8-e3231a3c94a3)
![orca model2](https://github.com/user-attachments/assets/dcd0cab4-0f2b-480c-bb33-7bcfe88ba225)

### Actual results

artifacts on overhungs 
![orca preview2](https://github.com/user-attachments/assets/aa2ec7ca-cc55-4b1a-9018-b750255c45d0)
![orca preview1](https://github.com/user-attachments/assets/fa116cd9-557b-459e-9266-9cd4ee11e165)

### Expected results

Artifacts are not expected.

### Project file & Debug log uploads

[artifacts.1.zip](https://github.com/user-attachments/files/17940059/artifacts.1.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by discip** [comment]
@voland696
Those are no artifacts.
It is what you instructed Orca to do by enabling **`Make overhangs printable`**.

Just disable **`Make overhangs printable`**. 😊

**Comment by voland696** [comment]
OMG Thank you so much! I did not expect it will make it printable this way. My bad.
