### ISSUE TITLE
The 'line method' pressure advance is deprecated - add the new method please

### ISSUE THREAD

**Issue by nirurin** [SoftFever/OrcaSlicer#761]
https://ellis3dp.com/Print-Tuning-Guide/articles/pressure_linear_advance/pattern_method.html

This seems to be an updated method of working out pressure advance. Much better than the line method, if only because it can be cleaned off the plate in one piece, rather than having to scrape up dozens of lines of individual filament pieces.

**Comment by jagr200** [comment]
Imagine thinking this is a worthwhile addition and time in coding. The current method suffices just fine. Far more important changes.

**Comment by Ibot-11** [comment]
#373

**Comment by SoftFever** [comment]
Duplicated.
Also PR is welcomed.
