### ISSUE TITLE
Only one wall on top surfaces needs refinement

### ISSUE THREAD

**Issue by Rigattoni** [SoftFever/OrcaSlicer#764]
### Discussed in https://github.com/SoftFever/OrcaSlicer/discussions/763

<div type='discussions-op-text'>

<sup>Originally posted by **Rigattoni** April 16, 2023</sup>
Well, to have only one wall on visible surfaces is a nice feature, but what I miss is, that visible surfaces in between of the print are not handled like that.
They are marked in the slicer as top surface, but the slicer shows all walls. 
![Slicer1](https://user-images.githubusercontent.com/15564938/232307599-4a6f9aed-3adc-4477-a5ea-23a5c254664d.png)
</div>

**Comment by liftbag** [comment]
I think you missed some duplicates: #379 #459 #547 #582 #709
