### ISSUE TITLE
Changing filament is not possible when the support interface is selected

### ISSUE THREAD

**Issue by DokuKaefer** [SoftFever/OrcaSlicer#766]
As soon as you select something in the support interface, it is no longer possible to change the filament above a certain layer height.
Same problem is also in the original Bambu Studio https://github.com/bambulab/BambuStudio/issues/1615

In my opinion, only the layer height in which the support interface is used should be blocked.

![image](https://user-images.githubusercontent.com/11537653/232330478-e0711211-f203-4f01-a476-b689ea44ee97.png)

**Comment by SoftFever** [comment]
Thanks @DokuKaefer 
Double posting tickets is waste of development effort(duplicated).
In this case, I suggest let BL handle this.
