### ISSUE TITLE
Flow Calibration Setting

### ISSUE THREAD

**Issue by jagr200** [SoftFever/OrcaSlicer#769]
I would LOVE it if "flow calibration" could be toggled in settings. So we can set it to default to off and we have to manually check it. If I have done all of the calibrations I do not want to run flow calibration. I would also love the same for "Bed Leveling" as I only run it when I have powered my machines down.

Thank you!

**Comment by SoftFever** [comment]
OS will remember your last choice so that basically covers your use case.

**Comment by jagr200** [comment]
> OS will remember your last choice so that basically covers your use case.

How is this complete? When I go send it to my machine I have to toggle the setting every single time. Would a toggle in preferences be too hard to setup so we don’t have to toggle that every time?

**Comment by SoftFever** [comment]
OS should remember your last toggle state of these settings.
If that doesn’t work on your machine, a video to show how to repro the issue will be helpful

**Comment by jagr200** [comment]
> OS should remember your last toggle state of these settings.
> If that doesn’t work on your machine, a video to show how to repro the issue will be helpful

The video wouldn’t show anything. 

I slice the plate. I hit send to printer. All 4 boxes are checked. Leveling, flow calibration, Timelapse and enable AMS. 

I want to be able to go into preferences and turn off leveling and flow permanently.
