### ISSUE TITLE
Filament Profile Not Populated in Print Options

### ISSUE THREAD

**Issue by stainlessray** [SoftFever/OrcaSlicer#771]
**Describe the bug**
After preparing a print project and slicing is complete, when I click "Print Plate" the selected filament profile for the object is never populated and the AMS is overrided with a different filament than the one chosen for the current project. If I do not manually change this mapping the wrong material is used every time.

**3mf File for This Bug**
n/a

**To Reproduce**
AMS loaded with four filaments, yet only one is selected for the project. Slice your project and click "Print Plate". Eithe filament will display as empty, or will display a filament from the AMS which was not included in the project.

**Expected behavior**
I expect the project filament choice to be effective throughout the project context, unless overridden by the user.

**Screenshots**
![orca-bug-1](https://user-images.githubusercontent.com/4843366/232463865-0f8e5588-c548-4c57-92e5-9f4383803429.png)
![orca-bug-2](https://user-images.githubusercontent.com/4843366/232463891-a90926c3-c53a-4d09-a081-f9e91ad2bd04.png)

**Bambu P1P**

**Desktop (please complete the following information):**
 - OS: Windows 11 64
 - Version 22H2

**Comment by SoftFever** [comment]
Thanks @stainlessray .
It's up Bambu to improve their close sourced firmware/network service.
OS has no plan to work these features.(also has no access to their close sourced resources)

**Comment by stainlessray** [comment]
> Thanks @stainlessray .
> It's up Bambu to improve their close sourced firmware/network service.
> OS has no plan to work these features.(also has no access to their close sourced resources)

This did not occur until I switched to the orca slicer. The choices for filament type of the print object automatically populated in this menu.
