### ISSUE TITLE
[BUG] - no Use ASM for BambuLab A1 settings

### ISSUE THREAD

**Issue by DrumClock** [SoftFever/OrcaSlicer#7718]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.2.0

### Operating System (OS)

Windows

### OS Version

Windows 10

### Printer

BambuLab A1 + AMS lite

### How to reproduce

![Bez názvu](https://github.com/user-attachments/assets/43030a44-3d3f-45d2-936a-3b0f93e67a8c)

### Actual results

-

### Expected results

-

### Project file & Debug log uploads

Project + Gcode
[BAMBU A1.zip](https://github.com/user-attachments/files/18086049/BAMBU.A1.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Anything else?

I wanted to print 4-colors on Bambulab A1 with AMS lite. Unfortunately, even though T0,T1,T2 and T3 are in the g-code,
the filament will not be replaced. The printer is not on WLAN but I print from an SD card.

"USE AMS" is not displayed 

Display
![7c661215-0bd8-4d0f-852d-eec0074bd542](https://github.com/user-attachments/assets/2e30414b-dc1a-40a3-9f73-8ec6d95028df)

**Comment by DrumClock** [comment]
I figured out that this option is needed:

'Export plate sliced ​​file' and save as 'xxx.gcode.3mf' on SD card

Again Bambulab (China) must have something extra and not standard G-code.
They simply will not comply with any standards.

**Comment by kekkodance** [comment]
the AMS doesn't conform to any standards simply because there's no standards that accomodate it, if BBL didn't want to comply to anything they could have made every G-Code operation different from other printers, instead they're similar

**Comment by DrumClock** [comment]
Hi,
the point is that there are printers that have multiple heads or a material changer
and they don't need the entire 3mf project to print. They just need the standard g-code from T0,T1...

But not BBL, they just have to have something extra. It's nothing else.
It just doesn't support pure G-code with T0,T1,T2 ..etc.
