### ISSUE TITLE
Prime volume field missing

### ISSUE THREAD

**Issue by pgifford** [SoftFever/OrcaSlicer#7751]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.3.0-dev (14 Dec 2024)

### Operating System (OS)

Windows

### OS Version

10

### Printer

A1 Mini, P1P

### How to reproduce

1. Create a new project
2. Click on Prepare
3. Click on Multimaterial tab

### Actual results

Prime volume field is not present
<img width="298" alt="v2 3 0-dev" src="https://github.com/user-attachments/assets/8fc4beb6-af60-469a-84b0-dbee27a636cb" />

### Expected results

Prime volume field is present (screenshot from v2.2.0 stable)
<img width="293" alt="v2 2 0-stable" src="https://github.com/user-attachments/assets/eecd5aa9-acdd-4859-942a-52aea501cd0a" />

### Project file & Debug log uploads

Not relevant, the Prime volume field is missing from the most recent Windows v2.3.0-dev portable.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Anything else?

Prime volume shows up in search and if selected the UI will switch to the Multimaterial tab.
<img width="291" alt="v2 3 0-dev-search" src="https://github.com/user-attachments/assets/16469310-0181-48b4-80cb-6191afe08643" />

**Comment by igiannakas** [comment]
This has been fixed in PR #7789

Can you please test and confirm? thank you!!

**Comment by Noisyfox** [comment]
Try #7808

**Comment by aaron-crocker** [comment]
Has anyone found a solution to this yet.  Prime volume is missing from my most recent version of Orca slicer.  It shows up in the search field and even snaps over to the Multimaterial tab.  But there is no prime volume option.  :(

**Comment by igiannakas** [comment]
Spot on. It won’t use priming if the prime tower is used for purging :)
