### ISSUE TITLE
running v1.6.2-beta creates a notification to download v1.6.2.beta

### ISSUE THREAD

**Issue by julie777** [SoftFever/OrcaSlicer#777]
**Describe the bug**

I unzip and run v1.6.2-beta. It opens a notification dialog.

![image](https://user-images.githubusercontent.com/5090005/232572878-cc610297-581c-492c-a4d8-5e661f7cf4e7.png)

I don't think a notification should appear unless there is a newer version than the one running.

**3mf File for This Bug**
If it is related to slicing, please append the 3mf file. It could be extremely helpful to solve the issue.

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**

**Printer model**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Windows]

**Comment by tsmith35** [comment]
Seeing the same here. I selected the box to not remind me about this version again, but perhaps it's an easy fix. :-)

**Comment by SoftFever** [comment]
Yeah, a wrong tag name was created previously.
It should have been fixed now.
Thanks for reporting it.
