### ISSUE TITLE
Outer wall line width not changing

### ISSUE THREAD

**Issue by TechDude23** [SoftFever/OrcaSlicer#783]
I have been testing the line width setting and the outer wall will not adjust it will always be @ .4 the fist layer line width is working ok.

So I did some custom g code for another slicer and I can change the line width so I know its not the Bambu Lab hardware.

Orca Slicer V 1.6.1 

Bambu Lab X1

Window OS: 10

Thank you for fixing the export bug :)

**Comment by SoftFever** [comment]
![image](https://user-images.githubusercontent.com/103989404/232803732-777741eb-54ab-4bbc-ac65-75422e8651e6.png)
@TechDude23 Works fine in 1.6.2
Please attach a sample project if you still find the issue in 1.6.2

**Comment by TechDude23** [comment]
Just tested it out with version 1.6.2 and it is fixed woohoo :)

Thank you so much
