### ISSUE TITLE
Multi Coloring does not work correctly

### ISSUE THREAD

**Issue by ccomtest** [SoftFever/OrcaSlicer#785]
**Describe the bug**
When painting a model with a color, it uses first color often/does not fill complete wall/object.
Print doesn't look as expected in full color. It seems only Top Layer works as expected. Walls doesn't even have any color change.

**3mf File for This Bug**
If it is related to slicing, please append the 3mf file. It could be extremely helpful to solve the issue.
[EMPACT_Logo_Color_Issue.zip](https://github.com/SoftFever/OrcaSlicer/files/11260496/EMPACT_Logo_Color_Issue.zip)

**To Reproduce**
Color a model (text) with more than one color. When you slice it, you see your set color is not fully painted and will also print like this.

**Expected behavior**
When i color a wall, it should print the whole wall in this color. I am not sure, the Fusion Modell has an impact on this. It seems, there a lot of shapes in a Text modell. But when i incease fill angle to possible maximum it also does not color the whole wall, which should be not the case. Also the painting looks like, it has painted all. When sliced, it shows how the print really will look like.
**Screenshots**
![Unbenannt1](https://user-images.githubusercontent.com/3010164/232743128-1d9c8266-41c9-4fcb-a5c9-e72927e1bd7c.PNG)
![Unbenannt2](https://user-images.githubusercontent.com/3010164/232743177-62ba2622-8217-4bdd-88fe-be9093f88f3d.PNG)
![IMG_20230418_120718](https://user-images.githubusercontent.com/3010164/232745713-6a6162d2-828b-4185-8d07-22ea3d69c073.jpg)

**Printer model**
Bambu Lab X1C

**Desktop (please complete the following information):**
 - Windows 10, Orca Slicer 1.6.1

**Comment by ccomtest** [comment]
See also "one layer deep coloring only". Which descibes my issue a bit better i think as an inssue in Bambu Slicer.
Coloring does not behave like in Super Slicer.

**Comment by ccomtest** [comment]
It seems there are more bugs according to color printing (no one else has these issues?).

When i set a top layer in the middle for color difference, it seems the color underneath is also changed, but not for walls.
![Unbenannt3](https://user-images.githubusercontent.com/3010164/232759745-f353c2bf-1a1f-4cf7-9d3d-3ac1cd4b51f2.PNG)
![Unbenannt4](https://user-images.githubusercontent.com/3010164/232759740-97edd370-286b-4fda-a18d-0cf119c28f13.PNG)

Leasing into more color changes and wrong prints.

**Comment by SoftFever** [comment]
Thanks @ccomtest .
In that case, hopefully they may have been already working on this.
Closing it.

**Comment by FloodedZebra0** [comment]
I am having this same problem as well, has anyone or orca/bambu slicer fixed this yet?
