### ISSUE TITLE
Some parts not receiving "top layer" processing.

### ISSUE THREAD

**Issue by chmarr** [SoftFever/OrcaSlicer#790]
**Describe the bug**
With a particular STL, the top layer of certain sections are terminating with the normal "inner wall" rather than "top layer infill". Note that this problem does _not_ occur with Bambu Studio 1.5.0.60

**3mf File for This Bug**
3mf file attached.
[chainmail_flowalistik_sample.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/11268014/chainmail_flowalistik_sample.3mf.zip)

**To Reproduce**
* Load 3MF
* Use the standard "0.20mm, Standard" setting. (albeit problem occurs at most settings)
* Slice
* Observe that about half the components have their inner walls showing, rather than "top surface".

**Expected behavior**
The tops of all components show the red "Top Surface" indication.

**Screenshots**
Screenshot attached.
<img width="627" alt="Screenshot 2023-04-18 at 19 46 20" src="https://user-images.githubusercontent.com/523669/232953878-aafad1a0-bbb4-4a3f-9e7a-e78c66b431ba.png">

**Printer model**
Bambu X1C

**Desktop (please complete the following information):**
 - OS: MacOS 13.3.1
 - OrcaSlicer Version: 1.6.1

**Comment by chmarr** [comment]
A quick addition. The parts that aren't receiving the Top Layer processing are indeed shorter than the parts that are. That shouldn't stop them receiving the processing, I would think.

**Comment by defcrash** [comment]
I have the same problem, if i fill a model with only walls i get no top layers:
![1](https://user-images.githubusercontent.com/21699647/234297261-b9cd1620-4a93-45b8-a1dd-14c229694641.jpg)

Now sliced with only 3 walls (it looks better, it seems if a specific part only have walls it dosent add top layers):
![2](https://user-images.githubusercontent.com/21699647/234297714-ccc6e99a-6872-4cf2-bea7-c7689212b5eb.jpg)

This only happens with Arachne enabled, if i switch to Classic mode it will slice correctly:
![3](https://user-images.githubusercontent.com/21699647/234298402-1a6fca1e-f896-4cca-b14c-c646574ddd8c.jpg)

**Comment by To0wnn** [comment]
Hi,

This issue is still there in classic mode. The toplayer is not looking nice when printing
![image](https://github.com/SoftFever/OrcaSlicer/assets/25762347/05321684-1444-4d9d-a148-b86b71d442b1)
With superslicer it is ok but maybe that is just an oppinion.
![image](https://github.com/SoftFever/OrcaSlicer/assets/25762347/446e1464-4903-461d-8c07-5e2b9e4a0def)
Hoopfully it can be fixed in the new release or did i miss a setting?
