### ISSUE TITLE
Device tab empty if using printers hostname instead of the ip address

### ISSUE THREAD

**Issue by ffavero** [SoftFever/OrcaSlicer#791]
The device tab doesn't show anything if in the physical printer configuration the hostname of the printer is used instead of the ip address (in my case device ip can change, I base assignments on hostnames).
Using the hostname to connect with the printer works out of the box to upload gcodes.

To reproduce just replace the printer ip with the hostname, chack if the test passes correctly (it should), and try to upload a file to the printer (it should). Device tab is empty though

**Screenshots**

With hostname

<img width="841" alt="image" src="https://user-images.githubusercontent.com/444109/233008115-4b347ff1-b25b-44f1-bc66-d31f93f34764.png">
<img width="1092" alt="image" src="https://user-images.githubusercontent.com/444109/233008353-60591629-3e19-42c0-9ef2-1e46246f054e.png">

With IP
<img width="832" alt="image" src="https://user-images.githubusercontent.com/444109/233008750-516dc8b7-7d11-4d0b-a0fb-18d0d0d80f6e.png">

<img width="897" alt="image" src="https://user-images.githubusercontent.com/444109/233009084-6d00939e-14f1-4cd0-8781-797dc3180abe.png">

**Printer model**
ZeroG Mercury One.1

**Desktop (please complete the following information):**
macOS silicon M1

**Comment by fire1ce** [comment]
@ffavero can confurme same behavior.

**Comment by SoftFever** [comment]
@fire1ce what OS do you use?

**Comment by fire1ce** [comment]
@SoftFever macOS silicon M1

**Comment by gargamel778** [comment]
Can confirm similar behavior on x86 MacOS version

**Comment by ammmze** [comment]
I can confirm the same thing. However, I did find that if I run it through a TLS terminating proxy ( just tested with ngrok), giving me an http**s** connection instead of http, then it would work.

**Comment by SoftFever** [comment]
I've seen similar issues on Windows when I port printer network support from PrusaSlicer.
Later I found an solution/workaround in PS for Windows 10/11.
Might be the same cause.

> #ifdef WIN32
>     // Workaround for Windows 10/11 mDNS resolve issue, where two mDNS resolves in succession fail.
>     if (m_host.find("https://") == 0 || test_msg_or_host_ip.empty() || !GUI::get_app_config()->get_bool("allow_ip_resolve"))
> #endif // _WIN32
>     {
>         // If https is entered we assume signed ceritificate is being used
>         // IP resolving will not happen - it could resolve into address not being specified in cert
>         url = make_url("api/files/local");
>     }
> #ifdef WIN32
>     else {
>         // Workaround for Windows 10/11 mDNS resolve issue, where two mDNS resolves in succession fail.
>         // Curl uses easy_getinfo to get ip address of last successful transaction.
>         // If it got the address use it instead of the stored in "host" variable.
>         // This new address returns in "test_msg_or_host_ip" variable.
>         // Solves troubles of uploades failing with name address.
>         // in original address (m_host) replace host for resolved ip 
>         info_fn(L"resolve", test_msg_or_host_ip);
>         url = substitute_host(make_url("api/files/local"), GUI::into_u8(test_msg_or_host_ip));
>         BOOST_LOG_TRIVIAL(info) << "Upload address after ip resolve: " << url;
>     }
> #endif // _WIN32

**Comment by ammmze** [comment]
I've got a fix for this coming soon...just doing some final testing then will open a PR.

**Comment by ammmze** [comment]
PR is up now #1157

**Comment by ammmze** [comment]
I'm still kind of on the fence whether we should disable ATS as discussed in the PR, but for those looking for a workaround to get this working today with your existing version, you can add a security exception for your domain like this. Open up a terminal window and run the following command, but replace "printer.lan" with the hostname of your printer. (And if the path to OrcaSlicer.app is different, change that as well)

```shell
plutil -replace NSAppTransportSecurity -json '{"NSExceptionDomains": {"printer.lan": {"NSExceptionAllowsInsecureHTTPLoads": true}}}' /Applications/OrcaSlicer.app/Contents/Info.plist
```
