### ISSUE TITLE
New PA/LA Tool

### ISSUE THREAD

**Issue by thetoadsage** [SoftFever/OrcaSlicer#794]
It would be awesome to see the newer Ellis3DP PA/LA tool incorporated into your calibration feature set. I really like this one and find I have great results with it. I have linked it below. Keep up the great work!

https://ellis3dp.com/Print-Tuning-Guide/articles/pressure_linear_advance/pattern_method.html

**Comment by magic-happenz** [comment]
I came here to suggest the same. The existing methods are unfortunately far from being accurate which is really important for calibrating PA/LA.

**Comment by magic-happenz** [comment]
Agreed, lines method is outdated and inaccurate at its best.
