### ISSUE TITLE
Disabling acceleration control persists single M204 command in gcode

### ISSUE THREAD

**Issue by mmunchinski** [SoftFever/OrcaSlicer#795]
When attempting to disable Acceleration Control by setting the "Normal printing" acceleration variable to "0", all other acceleration variables become grayed out.  When slicing the gcode, it is observed that a single M204 command persists that is either placed at the end of the first layer or beginning of second layer that appears to correlate to the "Travel" acceleration variable.  Its placement appears to correlate with the next SQUARE_CORNER_VELOCITY set after the first layer printing is complete.

3mf file attached, command is on line 2807 of gcode..

Reproduced on Orca Slicer 1.6.2-beta using the FLSun v400 profile.

1) Set "Normal printing" to a non 0 value (this allows setting of other acceleration parameters)
2) Set all acceleration parameters to unique values (this allows you to identify which acceleration parameter is being placed, in the example attached "Travel" is set to 900 which is what appears on line 2807)
3) Set "Normal printing" to 0, all acceleration parameters will be grayed out.
4) Load any object to print and slice.
5) Either use gcode browser within OrcaSlicer, or export gcode to file and search for M204 commands.

Expected behavior is that with "Normal printing" acceleration set to 0 no M204 commands are transmitted and Klipper handles all aspects of acceleration control.

Screenshot attached

Printer Model:  FLSun V400
Desktop:  Windows 10

![Capture](https://user-images.githubusercontent.com/24701793/233077670-493678ee-ac03-4e87-a14f-d5a272376a55.GIF)

[3DBenchy.zip](https://github.com/SoftFever/OrcaSlicer/files/11273095/3DBenchy.zip)

**Comment by SoftFever** [comment]
fixed.
