### ISSUE TITLE
NUMBER OF SLOW LAYERS in the beginning of the print.

### ISSUE THREAD

**Issue by RudiKleinSA** [SoftFever/OrcaSlicer#796]
Please add NUMBER OF SLOW layers in the beginning of the print.

This is vital for ABS not to Warp. 
I print x10 slow layers.

SLOW INITIAL LAYERS guarantees my print not to warp.

Currently I now manally slow down my speed to 40% in klipper, and then after layer line 10 to 15 I increase the speed.

The problem is that I cannot always do it, because it could take up to three hours to reach those layer heights.

Thank You 

![Picture1](https://user-images.githubusercontent.com/93178003/233673249-35ce9cbe-5aa4-4adc-bbe6-22064f1414b3.png)

**Comment by SoftFever** [comment]
Added in 1.6.3 beta

**Comment by RudiKleinSA** [comment]
SoftFever,

Thank you very much.

I am using Windows - How can I get 1.6.3 beta?  
Just wait until it is released?

**Comment by SoftFever** [comment]
@RudiKleinSA 
You can download the 1.6.3 beta release here: https://github.com/SoftFever/OrcaSlicer/releases/tag/v1.6.3-beta

**Comment by RudiKleinSA** [comment]
![image](https://github.com/SoftFever/OrcaSlicer/assets/93178003/eb94a89d-58ec-4056-9563-23fca5d4fd59)

SoftFever, 

Thank you for replying.

I downloaded the new 1.6.3 beta release, and WAU, amazing. 

Thank you very much!!

I love ORCA Slicer.

Well done.
