### ISSUE TITLE
Jerk is not calculated in printtime

### ISSUE THREAD

**Issue by foxmckraut** [SoftFever/OrcaSlicer#797]
Model printing time is not including jerk
on 1 jerk its the same as on 1000 jerk.
<img width="300" alt="Bildschirm­foto 2023-04-19 um 20 14 15" src="https://user-images.githubusercontent.com/101701200/233163859-3cdb7345-56b1-4015-a0c2-7aa4e8c27fcb.png">
<img width="358" alt="Bildschirm­foto 2023-04-19 um 20 14 22" src="https://user-images.githubusercontent.com/101701200/233163886-da014b5d-5414-4b87-adbc-71aae0e66c65.png">

1000 jerk:
<img width="312" alt="Bildschirm­foto 2023-04-19 um 20 14 44" src="https://user-images.githubusercontent.com/101701200/233163975-d838256e-3bec-41b6-8a61-db6301399a57.png">
<img width="387" alt="Bildschirm­foto 2023-04-19 um 20 14 52" src="https://user-images.githubusercontent.com/101701200/233164004-b9272d3d-767f-46ca-8786-4e5550ac8340.png">

Tried the same on Superslicer and works there.

**Comment by SoftFever** [comment]
What printer/gcode-favor is this?

**Comment by SoftFever** [comment]
Do take note though, I cap the max jerk value based on machine limits.
If your machine limits is set to 9, then it will cap to 9 even you set to 999 in speed settings.

**Comment by foxmckraut** [comment]
that makes sense thanks for the explanation

**Comment by SoftFever** [comment]
It looks like this has been resolved.
Feel free to re-open it if it's still doesn't work
