### ISSUE TITLE
Please add retratction calibration

### ISSUE THREAD

**Issue by MarisKay** [SoftFever/OrcaSlicer#802]
Would be a great help if we could also print a test object and find the best retraction, wipe settings for a certain fixed temperature. Right now i do it manually, by printing same object over and over again and looking whether retraction/wipe does not cause a gap in perimeter where it retracts /wipes on layer change. Adjust the settings, print again. I believe this could have been automatized in one calibration print to see how filament reacts to different retractions and wipes. Thank you!

**Comment by SoftFever** [comment]
It is planned.

**Comment by pirate** [comment]
Bump
