### ISSUE TITLE
Pressure Advance bug for FLSun v400

### ISSUE THREAD

**Issue by wagzledz** [SoftFever/OrcaSlicer#803]
**Describe the bug**
when slicing and generating the PA tuning test via orca, the sliced model isn't drawn properly. 

**3mf File for This Bug**
I have the 3mf, but cannot add it

**To Reproduce**
Make a new plate and add PA TUNING line test and then slice file. it will show issue

**Expected behavior**
proper pa line test?    Might not work due to bed shape and size?  

**Screenshots**
<img width="1642" alt="Screen Shot 2023-04-20 at 10 36 12 AM" src="https://user-images.githubusercontent.com/101683623/233400443-d903d57d-cb51-4c85-b320-1058c9be5187.png">

**Printer model**
FLSun v400
**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Windows]. MacOS 
 - Version [e.g. 22]. Big Sur 11.6

**Comment by SoftFever** [comment]
Fixed in 1.6.2
