### ISSUE TITLE
Failed to save G-code file.

### ISSUE THREAD

**Issue by JamesKR3D** [SoftFever/OrcaSlicer#808]
**Describe the bug**
Every once in a while, especially with large prints, I get this error when trying to export the gcode file and saving over an existing filename.   Then I save it with a new name, and it exports fine.

**To Reproduce**
Export G-code file after slicing

**Expected behavior**
I expect it to save without issue.

**Screenshots**
![image](https://user-images.githubusercontent.com/61016916/233477603-4e75f812-3a80-4d31-b3ed-1d58f4925ce0.png)

**Printer model**
P1P

**Desktop (please complete the following information):**
Windows 10 Pro 22H2

**Comment by SoftFever** [comment]
Hi @JamesKR3D 

Insufficient disk space in the C drive could cause such an error.
Can you check you free space in C?

**Comment by JamesKR3D** [comment]
there's over 300GB of free space on C.

**Comment by JamesKR3D** [comment]
Looks like it's related to filenames with spaces that's causing the issue.  I was able to export the gcode with filenames with underlines instead of spaces and can do repeatedly without issue.

**Comment by SoftFever** [comment]
Looks like the problem has been solved.
Closing
