### ISSUE TITLE
Default process crashes on startup when default process contains a layer height not in printer's limits

### ISSUE THREAD

**Issue by mdbijl** [SoftFever/OrcaSlicer#812]
**Description/Reproduction**
When the layer height in the process profile is not within the limits of the printer profile (as specified in Layer Height Limits / Min/Max) as popup message will appear saying "Too large layer height. Reset to x.xx". Additionally, when the layer height in de **default** selected process profile is not within the limits, it will display the popup too (just after the splash screen appear).  However when you close the popup, it will crash the app.

**Workaround**
Edit the process or printer profile JSON manually and restart app.

**Possible cause of the crash**
It looks like the UI did completely start, maybe after closing the popup some dependencies on the UI are not there yet.

**Related problem: changing the default printer not possible**
If you have copied a printer profile as a User Preset, it will always use the default process profile from the printer it inherits from. Adding a default process profile in the user preset's JSON will only work until restarting the app. See issue #813 

**Affected versions**
OrcaSlicer 1.6.1 and 1.6.2 beta have been tested by me, both show the same problem.

**Suggestion**
**Desktop (please complete the following information):**
 - MacOS Monterey 12.6

**Comment by derx05** [comment]
This bug drives me crazy and is "critical" in my opionion. It can easily break the software with hobbyists not knowing how to fix it.

**Comment by Vindikkator** [comment]
Yes I have this problem and don't know which profile has the issue to change... So no fix other than that?

**Comment by Vindikkator** [comment]
How do I reset my profiles. Can't use even older versions of orca slicer?

**Comment by Buzut** [comment]
Real pain in the butt. Especially since I have several printers and had to go and modify all the .json pref files as I had no idea which printer file it was loading…

**Comment by katech35** [comment]
Same issue on OrcaSlicer 1.7.0....Unable to launch the program and not able to locate which JSON file to edit to restore functionality.   @mdbijl can you share the location of the JSON file?

**Comment by rchacker** [comment]
same issue, still broken, where is the json file?  MacOs.

**Comment by rchacker** [comment]
no luck with a re-install.

**Comment by rchacker** [comment]
/Users/yourusername/Library/Application Support/OrcaSlicer

Deleted this folder and restarted however you will lose all your settings.

**Comment by aaronmrosenthal** [comment]
My machine has a 1.4mm nozzle the machine I copied had a max of 1.2mm nozzle. Slicer is dead on start. Same issue. 

Why is 1.4mm not in the drop down list?

**Comment by DBShrill** [comment]
Had same issue here with 1.91 and 2.0.0

**Comment by wr45** [comment]
Same issue here with 1,91 to 2.0.0
