### ISSUE TITLE
Option for different profiles for different plates

### ISSUE THREAD

**Issue by Gizmo6** [SoftFever/OrcaSlicer#814]
**Is your feature request related to a problem? Please describe.**
The ability to assign different filament/ profile to different plates would be good for big multi-material projects.

**Describe the solution you'd like**
Just as you now have the ability to name the plates it would be good to be able to have everything i needed printed in tpu on one plate. Then on a separate plate have all my abs parts. This would make it easier rather than having to save a bunch of different files.

**Describe alternatives you've considered**
Even the ability to change this via the by object option is a very good idea.

**Comment by BounceG** [comment]
Fully Support this idea.

**Comment by mattiasthalen** [comment]
I was just about to suggest this. It’s exactly the challenge I’m facing now.

**Comment by Fabietto996** [comment]
It is precisely the function I was looking for .... we hope they do this addition
