### ISSUE TITLE
Unable to disable timelapse

### ISSUE THREAD

**Issue by pointon242** [SoftFever/OrcaSlicer#816]
The "none" option from the timelapse drop down box is missing from the V1.6.2 beta vzbot download. The only options available to select are Traditional and Smooth

**Comment by Coma-patient** [comment]
+1 one have this issue aswell

**Comment by Coma-patient** [comment]
@pointon242 
So I was using my ender 3. I just needed a don't make timelaps option in the slicer settings. 
Kind regard Coma

**Comment by tlhintoq** [comment]
> This would be resolved in #2471

FYI:  As of the nightly build version 2 06FEB2024 - Its not fixed, at least for Bambu Labs X1Carbon

![image](https://github.com/SoftFever/OrcaSlicer/assets/11351506/e7654c83-4f90-40a9-9e7b-f4d3d98ef950)

WindowsX64
Bambu X1Carbon

cc: @Noisyfox  @SoftFever

**Comment by HumbleDeer** [comment]
> > This would be resolved in #2471
> 
> FYI: As of the nightly build version 2 06FEB2024 - Its not fixed, at least for Bambu Labs X1Carbon
> 
> ![image](https://private-user-images.githubusercontent.com/11351506/302950259-e7654c83-4f90-40a9-9e7b-f4d3d98ef950.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMTIyMzYsIm5iZiI6MTcwNzMxMTkzNiwicGF0aCI6Ii8xMTM1MTUwNi8zMDI5NTAyNTktZTc2NTRjODMtNGY5MC00MGE5LTllN2ItZjRkM2Q5OGVmOTUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDEzMTg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkMDFjZGVkNzQ1YTgxOWEwNzViZTlkYjA1MzQzMGYzYzVlZjU2NTJlNzAzZDEyMzc1OWFhNTM1ZjBhYzZkMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oVeIbwkHQYkJ0N9Z43A5fNLB2FzHY-8mTJR6Tj5P71w)
> 
> WindowsX64 Bambu X1Carbon
> 
> cc: @Noisyfox @SoftFever

@ anyone

Would be curious to know whether this is just its own Gcode or if Orca will also recognize currently present timelapse Gcodes in the pre-print Gcode settings.

**Comment by franciscomirasg** [comment]
The issue persist on 2.2.0 and the default is on when sending plate to the microSD.
![image](https://github.com/user-attachments/assets/9fc06771-bf3f-4b8a-9d5d-e4da7d37cae0)
