### ISSUE TITLE
Slicer crashes consistently when slicing the second plate of this model

### ISSUE THREAD

**Issue by MiscPrinter** [SoftFever/OrcaSlicer#818]
**Describe the bug**
I am slicing this model (attached below)and when it try to slice the second plate, it immediately crashes. Slices the first plate without issue. I can have the only the first plate sliced and send that to the printer but the second plate fails. I have tried several filament profiles and print profiles with it failing on the second plate each time. The uploaded 3mf is the desired filament and print profile. 

**3mf File for This Bug**

[5g Bucket Desiccant Holder v2.3mf.zip] (https://github.com/SoftFever/OrcaSlicer/files/11299411/5g.Bucket.Dessiccant.Holder.v2.3mf.zip)

Github would not allow a 3mf file so I zipped the 3mf to give it a new container that Github would allow uploaded. 

**To Reproduce**

Open the 3mf in Orca and slice all plates. The printer, filament, and print profiles are set and should be my custom X1C .4mm Nozzle, IIIDMAX ASA, and Draft with the infill changed. 

**Expected behavior**

The slicer should slice both plate and prepare the gcode for printing. 

**Screenshots**

**Printer model**

X1CC

**Desktop (please complete the following information):**

MacOS 12.6.3
Orca 1.6.2-beta

**Comment by hliebscher** [comment]
the 3mf file is corrupt no data  loding model failed
