### ISSUE TITLE
estimated end time

### ISSUE THREAD

**Issue by Tomek5111** [SoftFever/OrcaSlicer#820]
Hello 
I use the OrcaSlicer with my sidewinder x2 and klipper.  Unfortunately, the print time of the slicer is wrong and is wrong by about an hour for small prints and even several hours for large ones.  Can someone tell me what is wrong?  Is it because of the Klipper or the slicer?  The slicer controls the acceleration and speed..
![Screenshot_2023-04-22-06-53-26-140_com android chrome-edit](https://user-images.githubusercontent.com/100441425/233765344-35ad6165-5481-4d85-80d3-bad4b84bd2e9.jpg)

**Comment by uvalml** [comment]
have you solved it?

**Comment by discip** [comment]
@Tomek5111 See #2003.

**Comment by RyanDevineD** [comment]
Is there a way to add an offset to the estimated time, I find Orca is off by about 20% in most cases for me.
