### ISSUE TITLE
M73

### ISSUE THREAD

**Issue by Ziv831** [SoftFever/OrcaSlicer#822]
**Describe the bug**
Hi
I have an home made cr-10 like printer, the problem is whene the g-code is generated M73 is give me error while printing, but the printer is still printing perfectly, is there's a way to cancel the M73 code in the slicer while generating the g-code?
10x
Ziv

**3mf File for This Bug**
If it is related to slicing, please append the 3mf file. It could be extremely helpful to solve the issue.

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**

**Printer model**
Home made like cr-10
**Desktop (please complete the following information):**
 - OS: windows 11
![IMG_20230421_215249](https://user-images.githubusercontent.com/54476592/233766482-095f303f-92ba-4dbf-b5e3-f88bb99cbfd7.jpg)

**Comment by zerog2k** [comment]
+1
I also have Artillery Sidewinder X1 with the newer Digant firmware (marlin 2.x), and the g-code output from orcaslicer seems to add regular M73, but this makes for annoying status popups and audible beeps every layer.
I'm struggling where to find how to disable in orcaslicer settings (I'm very new to this lineage of slicer, coming from Cura).

**Comment by gerards** [comment]
Same issue with the BIQU BX, very annoying having the frequent beep and unknown command message. 

In SuperSlicer 2.4 I've disabled the M73 gcode by un-checking the "Print remaining times" option. Would be great if this can be implemented in Orca Slicer,

**Comment by viruha** [comment]
Same issue with the Artillery Genius.

**Comment by GBPrinting** [comment]
I am having the same problem on Biqu BX. Is there a soultion?

**Comment by gerards** [comment]
@GBPrinting My work around on the BIQU BX was tweak Luke's firmware which I've been using (https://github.com/looxonline/Marlin).

The compiled file https://github.com/gerards/Marlin/blob/BIQUBX_ALMOST_STOCK/firmware_GS_Tweaked.bin is here as well as the changes to Configuration_adv.h and Configuration.h should you want to compile it yourself.

I enabled M73 and tweaked a few other bits for myself while there, installed it and have been using Orca ever since, love it!

You can modify the gcode file produced by Orca and remove all the M73 lines also but that gets old quick...

**Comment by Prop3r** [comment]
Same here. Get frequent M73 echo messages, stating the remaining time. Please provide an option to turn off M73 remaining time in Gcode. 

Prusaslicer has this function, "supports remaining times" under Printer settings:
![image](https://github.com/SoftFever/OrcaSlicer/assets/83347314/8e9da1e7-533f-45d0-ba0b-9df4a7edfd31)

**Comment by Armageddit** [comment]
This massive sound on the Sidewinder X1 of every M73 is very annoying!
pleas make a setting point to turn it off!

**Comment by Prop3r** [comment]
If you're using Bigtreetech TFT firmware on your touchscreen, it's VERY easy to turn off ECHO messages:

MENU -> SETTINGS -> SCREEN -> UI -> ACK NOTIFICATIONS STYLE : OFF

**Comment by ManniAT** [comment]
Unfortunately this also disables other (possibly important) notifications.

**Comment by MBlackmagic** [comment]
I have written a python script and a windows droplet for this purpose. You can drop your gcode file onto the M73exDroplett and it removes all M73.
https://github.com/MBlackmagic/M73ex/tree/main

**Comment by MBlackmagic** [comment]
![orca_slicer_disable_m73](https://github.com/SoftFever/OrcaSlicer/assets/39409854/3faa3be0-0300-4f95-910a-36528a360a28)

Orca Slicer V1.9

**Comment by robinson01** [comment]
The issue is still present in 2.2.0
