### ISSUE TITLE
plate is missing

### ISSUE THREAD

**Issue by docemiel** [SoftFever/OrcaSlicer#824]
good morning. I'm using linux mint 21.1 vera. After configuring the application, what happens is that, I don't have any table, whatever printer I use. I leave here a picture of the printscreen, I would like to have some help to resolve this issue. thanks

![Captura de ecrã de 2023-04-21 00-16-23](https://user-images.githubusercontent.com/105605043/233778918-f7f62548-acf4-4e42-9908-920b7e78bf57.png)

**Comment by docemiel** [comment]
Good afternoon, After reading in another post that it could be a graphics problem, I decided to change the graphics drivers instead of using the nvidia ones, I opted for the open-source ones... and now it works! But it's still a bug or software conflict
![Captura de ecrã de 2023-04-22 13-45-14](https://user-images.githubusercontent.com/105605043/233787048-fa43f773-d83b-439c-8863-bc714e7bb994.png)
![Captura de ecrã de 2023-04-22 14-03-37](https://user-images.githubusercontent.com/105605043/233787052-384ffee5-ae6f-43e2-875a-74fde02ff53b.png)

**Comment by SoftFever** [comment]
Thanks @docemiel 
However, I'm afraid that GPU driver compatibility on Linux is beyond the scope of this slicer.
Remember Linus's middle finger towards Nivida? @@
