### ISSUE TITLE
Square tree supports?

### ISSUE THREAD

**Issue by vibinzthegreat** [SoftFever/OrcaSlicer#830]
Hey there, been trying to use orcaslicer for some time. i use organic supports to save on filament and they have been working fine on prusaslicer. same file i use on prusaslicer now has the tree supports as square on orcaslicer?
 

**To Reproduce**
I do not know how to reproduce it. I'm just using the stock ender 3 config on orcaslicer 1.6.1
[4trax gas valvev2.zip](https://github.com/SoftFever/OrcaSlicer/files/11302627/4trax.gas.valvev2.zip

**Expected behavior**
round supports like the organic supports in prusaslicer? it gave me round tree supports on other models with the same config

**Screenshots**

![image](https://user-images.githubusercontent.com/110127855/233814590-64e9ba67-212b-499d-a36d-84ad9aa685eb.png)

**Printer model**
Modded ender 3 pro(klipper firmware)

**Desktop (please complete the following information):**
 - OS: windows 11
 - Version idk

**Comment by KD7LRJ** [comment]
I'm getting this also. I've had it happen on two or three projects now and I think I've found a workaround, but I'm hoping you can find and fix the issue with this info.

![image](https://user-images.githubusercontent.com/2763408/235066736-265294bd-b5e9-464f-9e3f-18e56456502b.png)

The top part (1.3mf) was sent to me to print. I believe it was exported from Solid Works as a .3mf and I imported it into a new Orca Slicer project.

The bottom part (2.stl) was created by exporting the first part (1.3mf) as a .STL file from Ocra Slicer and then imported into the project. That is the only difference between the files. I did not change any setting on either object individually, they are both using the project's settings.

The attached file is a renamed .3mf file (not an actual .zip file).

[Square Tree Supports.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/11350424/Square.Tree.Supports.3mf.zip)

**Comment by bonjorno7** [comment]
I've had this problem too.
Increasing "Tree support branch distance" seems to help.

**Comment by Dustmuffins** [comment]
I'm not sure if it's possible to reopen this or not, but I'm having issues with this randomly popping up. I'm having a difficult time reproducing it though. If I have any more info I'll add it here.

![image](https://github.com/SoftFever/OrcaSlicer/assets/17961638/dbaf8681-2723-4a92-bf5d-a01c6d971656)
