### ISSUE TITLE
Gap between outer wall and brim

### ISSUE THREAD

**Issue by Chodec80** [SoftFever/OrcaSlicer#834]
**Describe the bug**
A gap between outer wall and brim in case, that Elephant foot compensation is active. 

**To Reproduce**
Set Elephant foot compensation and activate brim. Set Brim-object gap to zero.

**Expected behavior**
No gap between outer wall and brim. Like Superslicer.

**Screenshots**
![Snímek obrazovky 2023-04-23 v 19 06 34](https://user-images.githubusercontent.com/61891781/233854059-eac57722-ca27-4f89-b277-0175582bd8fb.png)

**Desktop (please complete the following information):**
 - OS: MacOS 13.3.1
 - Orca: 1.6.2 Beta

**Comment by tito** [comment]
Got the same issue, brim gap to 0, while the brim is perfectly disconnected of the whole object after printing.
![image](https://github.com/SoftFever/OrcaSlicer/assets/37904/1aee1b64-1ffe-47c1-993c-39107aa24bf1)

**Comment by LowRunneR** [comment]
The issue is also in 1.6.3 Official.
Is a fix possible?
please :-)

**Comment by b3n3d1k7** [comment]
The issue is still there in 2.0.0
