### ISSUE TITLE
Acceleration stuck at 500mm/s after first layer

### ISSUE THREAD

**Issue by harriettubgirl** [SoftFever/OrcaSlicer#837]
I'm not sure if anyone else is having this same issue but my ender 3 v2 klipper printer changes the accel speeds for top surface and first layer to 500mm/s. After those layer types, it's supposed to go back to 3000mm/s. It stays stuck at 500mm/s until I hit the little refresh/undo button. Picture after I refreshed it back to 3000mm/s: https://i.imgur.com/kQAZZwq.png 

I have all the settings as I thought they should be: https://i.imgur.com/QgeeZVR.png
Maximum accels:
https://i.imgur.com/dCB7cMC.png

Here's the g-code for the file if it's helpful at all: https://drive.google.com/file/d/1_GPqIKSp_KG7mZtvxeZztLQe-1lU_p8F/view?usp=share_link

If anyone is able to help out I'd really appreciate it! Thanks

edit: When I go through the g-code file I only see one instance where it changes the accel at the beginning with m204,  then nothing else? Though I'm not sure I know how to read all of the code.

**Comment by SoftFever** [comment]
@harriettubgirl 
You have set `maximum acceleration for extruding` to 500 which is the cause. Usually, we can set it to the same value as `Maximum acceleration X`.
Also in the future, you can paste images here directly, which will be much easier

![image](https://user-images.githubusercontent.com/103989404/234465177-e1a941a9-d07d-486e-8acf-dd153c1e528d.png)

**Comment by harriettubgirl** [comment]
Thank you! I don't know why I read that as maximum acceleration for the extruder haha. Appreciate all your hard work!

**Comment by 1-ashraful-islam** [comment]
Maybe a tooltip can be added to this setting or change the description - After going through many different trials, online resources - this is what solved my slow print speeds! Wouldn't have guessed..

**Comment by xBEAVISx** [comment]
Thanks. I have been searching for hours to figure this out. I use PrusaSlicer and its labeled even worse. They call it feedrate which doesn't make any sense to me.

<img width="631" height="158" alt="Image" src="https://github.com/user-attachments/assets/e528285f-5fba-4d07-9553-4ed24c304856" />

**Comment by malhar-c** [comment]
> [@harriettubgirl](https://github.com/harriettubgirl) You have set `maximum acceleration for extruding` to 500 which is the cause. Usually, we can set it to the same value as `Maximum acceleration X`. Also in the future, you can paste images here directly, which will be much easier
> 
> ![image](https://user-images.githubusercontent.com/103989404/234465177-e1a941a9-d07d-486e-8acf-dd153c1e528d.png)

Thanks! This needs to be renamed or tool tiped as the phrasing is somewhat confusing, and the thread also shows I'm not alone.
