### ISSUE TITLE
Thumbnails not working in Mainsail

### ISSUE THREAD

**Issue by jonathanalevi** [SoftFever/OrcaSlicer#840]
**Describe the bug**
For some reason, when I switched to OrcaSlicer, thumbnails stopped showing in Mainsail

**3mf File for This Bug**
Uploading 
[LDO_Main_Plate.zip](https://github.com/SoftFever/OrcaSlicer/files/11309079/LDO_Main_Plate.zip)

**To Reproduce**
Configure thumbnails, try to send to mainsail

**Expected behavior**
Thumbnail shows

**Screenshots**
<img width="933" alt="image" src="https://user-images.githubusercontent.com/1540530/233964136-db8d6922-eaff-47fe-8472-0c55cc4264b3.png">
**Printer model**

**Desktop (please complete the following information):**
 - OS: macOS but it's not relevant

**Comment by frankt2012** [comment]
I am having this issue also. I am using Fluid on the Sonic Pad. It shows the thumbnail on the Sonic Pad but not in Fluid.

**Comment by Sofronio** [comment]
Same here. No picture, and layer number stuck on 0 of 0.

**Comment by CarpeNecopinum** [comment]
I have tracked this down using some older files where the preview worked.
The older files contained the following lines between the `HEADER_BLOCK` and the `THUMBNAIL_BLOCK`: 

```
; hack-fix: write fake slicer info here so that preprocess_cancellation can process.
; generated by SuperSlicer 1.5.0 on 2023-04-21 at 13:13:47
```

If I just copy&paste them into the new files, the thumbnail shows up again. This sounds like it's not really OrcaSlicer's "fault" for breaking the thumbnails, yet still the effect only surfaces because emitting those two lines was disabled in a recent version...

**Comment by hliebscher** [comment]
@jonathanalevi 

Have you read this?

NOTE:
1. Please check [here ](https://github.com/SoftFever/OrcaSlicer#how-to-install)for installation instructions.
2. If your profiles didn't show up after updating, please restart OrcaSlicer
3. Klipper users, please update Moonraker to the latest version so that it can recognize OrcaSlicer and parse metadata like thumbnails.
4. If you're running Klipper, it's strongly recommended to add the following configuration to your printer.cfg file.

# Enable object exclusion
[exclude_object]

# Enable arcs support
[gcode_arcs]
resolution: 0.1

**Comment by CarpeNecopinum** [comment]
@hliebscher I can confirm this works for me. I updated moonraker (to current master) yesterday, but it wouldn't show the thumbnails until I changed the .gcode file via the editor (today; just a trivial edit to cause the file to be considered "changed").

**Comment by TonyK54** [comment]
The bug and the "hack" can be confirmed. I pasted the 2 lines in from @CarpeNecopinum. On saving the file the thumbnail showed up and the items layer height, filament usage, filament weight, etc, were displayed. Previously the thumbnail and the data was missing. 

@SoftFever , the 2 lines may need to be emitted again in the gcode that is rendered. 

```
; hack-fix: write fake slicer info here so that preprocess_cancellation can process.
; generated by SuperSlicer 1.5.0 on 2023-04-21 at 13:13:47
```

**Comment by CarpeNecopinum** [comment]
>  the 2 lines may need to be emitted again in the gcode that is rendered.

@TonyK54 you don't need the hack anymore if you update Moonraker to the latest version, restart it and reupload your gcode files (or do a trivial change).

**Comment by TonyK54** [comment]
Not everyone has or is willing to flash their systems and may have stock FLSun firmware. Hence there is a bug for a lot of people to be resolved. 

> > the 2 lines may need to be emitted again in the gcode that is rendered.
> 
> @TonyK54 you don't need the hack anymore if you update Moonraker to the latest version, restart it and reupload your gcode files (or do a trivial change).

**Comment by frankt2012** [comment]
> Not everyone has or is willing to flash their systems and may have stock FLSun firmware. Hence there is a bug for a lot of people to be resolved.
> 
> > > the 2 lines may need to be emitted again in the gcode that is rendered.
> > 
> > 
> > @TonyK54 you don't need the hack anymore if you update Moonraker to the latest version, restart it and reupload your gcode files (or do a trivial change).

This is true. I use the Sonic Pad and you are unable to update moonraker currently. I have to wait until Creality updates it. All the other slicers work fine with thumbnails on the older moonraker version.

**Comment by frankt2012** [comment]
> The bug and the "hack" can be confirmed. I pasted the 2 lines in from @CarpeNecopinum. On saving the file the thumbnail showed up and the items layer height, filament usage, filament weight, etc, were displayed. Previously the thumbnail and the data was missing.
> 
> @SoftFever , the 2 lines may need to be emitted again in the gcode that is rendered.
> 
> ```
> ; hack-fix: write fake slicer info here so that preprocess_cancellation can process.
> ; generated by SuperSlicer 1.5.0 on 2023-04-21 at 13:13:47
> ```
> 
> I have updated file GCode.cpp in method "export_thumbnails_to_file" to put these 4 lines (there is a blank line above and below this block) and will test it later today or early Friday morning.

I can confirm this fixes the thumbnail issue on the Sonic Pad.

**Comment by hliebscher** [comment]
@TonyK54 @CarpeNecopinum 
you can add this 2 lines with post processing script....
or write this in start g-code

**Comment by TonyK54** [comment]
> @TonyK54 @CarpeNecopinum
> you can add this 2 lines with post processing script....
> or write this in start g-code

We have to update the application C++ code to fix this.

**Comment by TonyK54** [comment]
Have submitted a pull request to the "main" branch at https://github.com/SoftFever/OrcaSlicer/pull/878. Hopefully it will be reviewed and added to 1.6.2.

**Comment by SoftFever** [comment]
Hi everyone,

I believe that the better solution would be to push printer and pad manufacturers to provide updates. Klipper, Moonraker, Fluidd, and Mainsail are constantly improving, and being locked into an outdated version is the last thing we want in my humble opinion.

As a workaround for those who cannot or do not want to upgrade Moonraker, you can try adding a fake slicer ID in the start G-code.
![image](https://user-images.githubusercontent.com/103989404/235134809-b520bf90-9c02-4cd2-9280-63fbe9978f15.png)

**Comment by TonyK54** [comment]
Yes, adding them to the starting gcode does the same thing. thank you

**Comment by blazecoding2009** [comment]
So I added the lines to my start gcode and it still isn't working. 
![image](https://github.com/SoftFever/OrcaSlicer/assets/56598575/ab7335fc-f977-4c0c-92b8-a7862002e395)
![image](https://github.com/SoftFever/OrcaSlicer/assets/56598575/e9b617e6-7913-4ff5-83d6-aa41bb69032c)
I have a sonic pad

**Comment by invidtiv** [comment]
![image](https://github.com/SoftFever/OrcaSlicer/assets/35193719/367bef48-b728-4046-bcf5-636ffd06e155)
just remove empty line and it works
