### ISSUE TITLE
Provide support for gcode print modifier variables

### ISSUE THREAD

**Issue by julie777** [SoftFever/OrcaSlicer#845]
## Is your feature request related to a problem? Please describe.

There are times when being able to specify printing options at print time is desirable.
For example, you can already choose to run calibration or not. (And thankfully Orca remembers this setting.)

There are a large number of print control variables defined by Bambu Lab already. BL calls them [Placeholders](https://wiki.bambulab.com/en/software/bambu-studio/placeholder-list).

But, there are also many that are either not defined or not surfaced for the user to change.

## Describe the solution you'd like

I would like to see the print dialog expanded to show more of the print variables so that the user can change them when sending the print. This adds flexibility, and prevents the need to create variations on printer profiles. For example, with my P1P I have the stock/default .4mm nozzle P1P profile. I have also created a modified profile that optimizes the bed heating so that the startup time is over 1 minute faster (submitted to Bambu Studio to replace the default profile). I also have a profile that is my fast start profile that I use when I have just finished printing a model and wish to print another using the same filament. This profile is extremely minimal (slicer estimates it at 11 seconds, although it does take more time if the bed has cooled down.)

The forums are full of requests to change this or that when printing. I think that this would solve the problem for users, and be easier to maintain.

I don't know where this is done in the Slicer, but I would implement it as a table of placeholders (names, and values) in order to attach those values to the print job.

I would mark in the table which are user settable, and show the user settable placeholders as a table in the print dialog allowing the user to enable/disable or change the value for this print job.

@SoftFever I haven't gone through the entire list to come up with a list of candidates yet. I wanted to get your response first.

## support for printer variations

At the time of printing, the user chooses the printer to send to. What if the user wants to send to the same type of printer (meaning that the gcode is correct) but the printer has a different build plate. Currently they have to change the build plate in the slicer and re-slice. The build plate type is already a placeholder, so it would be reasonable to just change the build plate type in the print dialog and send it. In fact, the print dialog could automatically change the placeholder if they choose a printer with a different build plate.

## Additional thoughts

I realize that BL designed the printer and the standard gcode to be as bulletproof as possible to provide a good experience out of the box for all users. But, many if not most users are much more knowledgeable and want to be able to do things that they know work, such as not calibrate the bed before each print, because they have not done anything to change it, such as move the printer or change to a different build plate.

BL seems reluctant to support the advance user in many cases. I am not sure why, as that support is an option, just like selecting expert mode in the slicer.

### Printing time estimates

I have always been amazed that the slicer can process the gcode and produce a good estimate of the print time. I have noticed that it doesn't account for changes made when sending the print (placeholders) or for heating time for the bed, which can be the longest part of startup. 

I wonder if there is a way to modify the estimate from the slicer during the print dialog to account for changes in placeholders and even the bed heating time based on the current temp. It retrieves the temp information while preparing to send.

### Future Ideas

There are so many follow up ideas to expand this type of enhancement. @SoftFever That is why I have been pressing your for project goals and asking you to contact me. I have a vision, and I think Orca could be the place to implement it, but only if it matches your vision. (Message me at https://www.reddit.com/user/julie777 if you are interested in talking about it.)

**Comment by SoftFever** [comment]
Thanks @julie777 
BL has its own commands to instruct the firmware to ignore specific blocks of custom G-code which you can send before sending the print.
However, as the firmware is closed-source, we have no idea of which placeholders are supported. 
Despite requesting a document or manual outlining the supported commands, I have not received one. 
While it may be possible to guess and use a trial-and-error approach to make some placeholders work, this is not where my interests or motivations lie.

**Comment by julie777** [comment]
The BL placeholders are documented at https://wiki.bambulab.com/en/software/bambu-studio/placeholder-list

**Comment by SoftFever** [comment]
These are placeholders used when generating g-code. They are different than the ones used to tell the machine to do bed_leveling/camera/AMS/Flow calibration etc...

**Comment by kylek29** [comment]
Re: Bambu's commands/functions

For some reason, I went through that last week. I think what they do is have a specific Mcode combined with a string function name that is placed in the gcode (you can see it at various areas) which corresponds to a function call that triggers the printer to do it's sequence and then pick back up again. 


But what I think Julie might be after is a more UI approach to adding these if/else/conditions to a print project? Not so much the existing special function conditions Bambu has. Like the ability to add a checkbox to the final print dialog (where you send it) and have that correspond with some conditional in the model, without having to manually add the conditionals? 

Right now, you can add the conditionals during start, during end, and I think on layer change -- but I believe you do them in the filament or printer config.

**Comment by julie777** [comment]
> Thanks @julie777 BL has its own commands to instruct the firmware to ignore specific blocks of custom G-code which you can send before sending the print. However, as the firmware is closed-source, we have no idea of which or how placeholders are supported. Despite requesting a document or manual outlining the supported commands, I have not received one. While it may be possible to guess and use a trial-and-error approach to make some placeholders work, this is not what I am personally interested in doing though.

I had not spent enough time looking at the placeholder documentation. You are correct of course. 

I have made some progress toward understanding the communication during the print process.

I'm sure you knew, but I did not realize that all the macros and placeholders are expanded by the slicer before sending the gcode to the printer.

What seems to be left is the print time modifiers such as skip calibration.

Print time variables seem to be handled in gcode with 
```
;===== bed leveling ==================================
M1002 judge_flag g29_before_print_flag
M622 J1
    M1002 gcode_claim_action : 1
    G29 A X94.298 Y107.298 I67.4039 J41.4039
    M400
    M500 ; save cali data
M623
```
which is even formatted to look like M622 is evaluating a condition.

So more on the communication (which is so much more convoluted than just using klipper/moonraker).

It appears that when the user selects print a plate
- the print dialog opens and the user can select options for printing
- when the user selects send, Studio sends a 3mf file (that it constructs including the gcode for the plate) using ftp to the SD card (for P1P).
- Studio sends the command to print using MQTT and telling the printer which file from the SD card and providing values for print time variables, such as perform_calibration.
- when the printer receives the job command it unzips the 3mf file, extracts the gcode file, and saves the gcode file to the SD card.
- then it starts running the gcode.

This could explain why reprinting a model from the sd card seems to run calibration even though when I originally printed from the slicer I told it not to calibrate.


I have not yet reproduced running a print job without using the networking dll. That is the next step.

**Comment by julie777** [comment]
I just successfully sent a print job to the printer without using any BL code.

**Comment by julie777** [comment]
I will continue to press BBL to provide documentation for the G codes they added.

**Comment by wglockner** [comment]
+1
