### ISSUE TITLE
Port new vertical shell thickness algorithm from PrusaSlicer 2.6

### ISSUE THREAD

**Issue by eugenmeltis3pg** [SoftFever/OrcaSlicer#848]
**Is your feature request related to a problem? Please describe.**
 PrusaSlicer 2.6 removed the ensure vertical shell thickness checkbox and completely replaced the algorithm that handles the logic with a better one.

The solid infill that represents the vertical shell thickness is now generated with circular pattern regardless of the type of infill selected.

This reduces vibrations in the printer because it is no longer doing those short zig-zag moves, and also reduces the time by a small amount.

**Describe the solution you'd like**
Port the logic from PrusaSlicer 2.6 or implemented it directly using the description from above.

**Describe alternatives you've considered**
using PrusaSlicer 2.6

**Additional context**
N/A

**Comment by meltiseugen** [comment]
Any feedback on this?
