### ISSUE TITLE
Unable to remove user presets (Filament and/or Printer)

### ISSUE THREAD

**Issue by rcxrbt** [SoftFever/OrcaSlicer#849]
**Describe the bug**
Trying to remove user presets (Filament and/or Printer), this are still presents after software restart

**To Reproduce**

1.  Remove a user presets (Filament and/or Printer)
2.  Ok, presets are removed :)
3.  Restart sofware
4.  The presets are still here :)

This beavior also happen if I try to modify and save the preset whit same name...
In this case, the preset still show old values...

**Expected behavior**
Really remove presets

**Screenshots**
![preset01](https://user-images.githubusercontent.com/64079048/234368081-14d41b73-5efd-449f-a3f1-0cfae4fde85d.JPG)
![preset02](https://user-images.githubusercontent.com/64079048/234368108-8cca9ff8-a1ce-4e48-91a2-0fe143255bad.JPG)

**Printer model**
TwoTrees Sapphire

**Desktop (please complete the following information):**
 - OS:  Windows
 - Version 1.6.1

**Comment by rcxrbt** [comment]
Trying to export, the slicer export only some presets  of all user presets showed in the menu (as like a gost preset).

Example:
 two preset in menu:
TwoTrees Generic PLA+ 
TwoTrees Generic PLA++

Export only TwoTrees Generic PLA++

![image](https://user-images.githubusercontent.com/64079048/235295372-6ea2c112-c423-4fe2-beb0-30aa10f478a5.png)

**Comment by diaudio** [comment]
Me too - cannot figure out how to remove printer

**Comment by drumstick77** [comment]
same here

**Comment by Jax1er** [comment]
did this ever get figured out

**Comment by iamlite** [comment]
also stuck with this.

**Comment by allanwrench28** [comment]
Yep this has annoyed me, still cant figure it out

**Comment by fredluetkemeier** [comment]
Why is this closed? This is still an issue

**Comment by drumstick77** [comment]
try this...if you go to the printer section on top left and click on the edit
![image](https://github.com/SoftFever/OrcaSlicer/assets/1726110/bdf22435-64ae-4b17-9c76-74507c17b1e7)

then click on the X
![image](https://github.com/SoftFever/OrcaSlicer/assets/1726110/1293e494-4f67-4149-966c-a4ea0111e3d2)

I think that will deleted your printer's preset along with all the settings for it...

**Comment by Gurba667** [comment]
I think you are right. 👍👍

4. mai 2024, 10:07 kl. 10:07 skrev drumstick77 ***@***.***>:

**Comment by drumstick77** [comment]
glad can help. I think all of users' presets have got the X that you can click to delete. Not very obvious.....i know, cuz took me a while to find it....lol

**Comment by fredluetkemeier** [comment]
> try this...if you go to the printer section on top left and click on the edit 
> then click on the X 

Thank you! This is exactly what I was looking for. Wish they would make this more obvious

**Comment by Jax1er** [comment]
> > try this...if you go to the printer section on top left and click on the edit
> > then click on the X
> 
> Thank you! This is exactly what I was looking for. Wish they would make this more obvious

This is fantastic!  Thanks

**Comment by PolGuixe** [comment]
I've created a printer config that make Orca Slicer crash. 

Do delete the printer I need to access it and it crashes every time.  It would be nice to be able to delete it without having to access it. 

Thanks

**Comment by drumstick77** [comment]
if you're on windows, I believe all profiles are save in your appdata folder --> C:\Users\[username]\AppData\Roaming\OrcaSlicer
I've never delved into this, so I'm not too sure exactly where they are, but perhaps you might be able to find the corrupted profile here and delete it?

**Comment by xdevs23** [comment]
> try this...if you go to the printer section on top left and click on the edit ![image](https://private-user-images.githubusercontent.com/1726110/327934296-bdf22435-64ae-4b17-9c76-74507c17b1e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MTc3NzMsIm5iZiI6MTcxNjcxNzQ3MywicGF0aCI6Ii8xNzI2MTEwLzMyNzkzNDI5Ni1iZGYyMjQzNS02NGFlLTRiMTctOWM3Ni03NDUwN2MxN2IxZTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjZUMDk1NzUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTdmNjY1YjQ5NTgzYTc4Y2UyNDMwODczMTkzNDYxMDUyNTg5NDM5OWM4OTNjMzJhOWEwODAyMWExNTliMjA2MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.r3pD24d44R9zi2Z9L0oPVXwbqx1Z6l0R8OnPRBMpzZ4)
> 
> then click on the X ![image](https://private-user-images.githubusercontent.com/1726110/327934316-1293e494-4f67-4149-966c-a4ea0111e3d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MTc3NzMsIm5iZiI6MTcxNjcxNzQ3MywicGF0aCI6Ii8xNzI2MTEwLzMyNzkzNDMxNi0xMjkzZTQ5NC00ZjY3LTQxNDktOTY2Yy1hNGVhMDExMWUzZDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjZUMDk1NzUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTk3NGQxOTcxM2M1MWU4YTE1NjVlMDcyNmJkMWQ4YTQ2NTVlZDNjMzg5NGNmMjBiYzBkNmFjMDljZjEzNGVmYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.xG8xpN_1mF7JT0MN0v74vsEhsz9S4alj_TBCXVukwtE)
> 
> I think that will deleted your printer's preset along with all the settings for it...

I don't have an X... Just Save and Search. I removed all printers in the "Select/Remove printers(system presets)" dialog and confirmed it but the printers are still there.

**Comment by fabiovix** [comment]
Hi!   I can confirm this issue on my Ubuntu 24, version:   OrcaSlicer 2.2.0   (executable:   "OrcaSlicer Linux Ubuntu 2404 V2.2.0.AppImage").  There is no button to delete the printer profile, so once configured, it remains. It's a VERY annoying bug

**Comment by Boerny41** [comment]
> I don't have an X... Just Save and Search. I removed all printers in the "Select/Remove printers(system presets)" dialog and confirmed it but the printers are still there.

Same problem here
