### ISSUE TITLE
Add ability to ramp up fans over specified number of layers.

### ISSUE THREAD

**Issue by halofx** [SoftFever/OrcaSlicer#85]
**Problem**
PrusaSlicer and Cura both have the ability to delay the fan for the first X number of layers, and then ramp up to a specified speed at another given layer height. This can be very helpful when printing PLA on a textured PEI sheet, as the default is on the P1P. Too much cooling at lower heights can shock the print off the PEI. 

**Solution**
Restore the default behavior from PrusaSlicer.

**Workaround**
In the meantime, I have been having to manually add in M106 custom gcode commands to manually ramp up the fan speeds to avoid blasting small PLA parts off the textured PEI.

**Comment by pirate** [comment]
Bump
