### ISSUE TITLE
"Send" does not respect changed plate name in dialogue

### ISSUE THREAD

**Issue by pandel** [SoftFever/OrcaSlicer#850]
Hi!

If you hit the "Send" button after you sliced your file you normally can change the name of the plate in the middle of the dialogue. But this actually does not work. It always sends the gcode named after the original filename even though you gave it a new name in this dialogue. This is not very helpful, let's say, you want to send the plate multiple times with different print settings, only the last one sent will survive.

Perhaps this can be fixed :-) - keep up the good work and many thanks!

Regards,
Holger

**Comment by SoftFever** [comment]
@pandel 
I don't quite understand the issue.
What printer are you referring to? 
Some screenshots to explain the problem will be very helpful.

**Comment by pandel** [comment]
Ok, here comes the screenshot... as you can see, the 3mf file itself is named "Bambu Spool Holder", but I renamed the plate to "Bambu Spool Holder blabla". When I send the plate, the file is still being named "Bambu Spool Holder" on the SD card, missing my added "... blabla". So atm I am unable to send the same file multiple times with different names.

<img width="509" alt="Bildschirmfoto 2023-04-28 um 14 04 04" src="https://user-images.githubusercontent.com/12460002/235142819-01d99e75-5ae2-440b-af93-952c71a5fc2c.png">

**Comment by SoftFever** [comment]
@pandel 
Unfortunately, this is BL firmware/cloud service issue.

**Comment by pandel** [comment]
Mmmhh... ok. Thanks.
