### ISSUE TITLE
504 Gateway timeout nginx - Klipper Voron

### ISSUE THREAD

**Issue by disan87** [SoftFever/OrcaSlicer#857]
Hi,
I got a 504 timeout, when I am uploadin bigger files to my voron. I says 504 timeout error.
It is not happing all the time. The funny thing, file is sended anyway and I can print it, but print will suddenly end. I think not all gcode is sended.

**To Reproduce**
Slice a plate with lots of items. Try it many times. You need a printer running moonraker and klipper. Printer is connected to network over the air wirelss.

**Screenshots**
![Screenshot 2023-04-26 161145](https://user-images.githubusercontent.com/1998195/234602961-d5689308-65b2-4f2f-961e-df4dc2e9c716.jpg)

**Printer model**
Voron

**Desktop (please complete the following information):**
Windows

**Comment by racerxdl** [comment]
It's not an issue with orcaslicer, but with nginx on the printer. If the gcode is too big and object_processing is enabled, the request can take more than 1 minute which is the default timeout for nginx. To change it, edit `/etc/nginx/nginx.conf` and at the end of http section, add:

```
       proxy_send_timeout 500s;
        proxy_read_timeout 500s;
        fastcgi_send_timeout 500s;
        fastcgi_read_timeout 500s;
```

And restart nginx.

**Comment by MrRobotikMex** [comment]
Hi, did you manage to solve your problem?
I have the same error using the latest version of CURA no matter how I send to print,
By Moonraker,
By CURA
Or by the Fluidd web interface.
I get the same error, 504 Gateway Time Out,  I'm not an expert, I use a Creality Sonic pad to have klipper, I read above that you can modify nginx, but I have no idea how to do that, any help? I only have this problem when I print large pieces
