### ISSUE TITLE
fix typo DE

### ISSUE THREAD

**Issue by zwoemti** [SoftFever/OrcaSlicer#859]
https://github.com/SoftFever/OrcaSlicer/blob/8df5b79a6ee70ecf35c3d872a85c1c2aca28e3ca/bbl/i18n/de/OrcaSlicer_de.po#L2284

`"Prime Tower funktioniert nicht, wenn Adaptive Schichthöhe aktiviert ist.\n"`

https://github.com/SoftFever/OrcaSlicer/blob/8df5b79a6ee70ecf35c3d872a85c1c2aca28e3ca/bbl/i18n/de/OrcaSlicer_de.po#L2327

`msgstr "Heizbett vorheizen"`

**Comment by hliebscher** [comment]
ist gefixt. ;-)

**Comment by hliebscher** [comment]
@zwoemti pls close the bug ;-)

**Comment by SoftFever** [comment]
Closing as problem solved.
