### ISSUE TITLE
Use "Motion ability" only for time estimate

### ISSUE THREAD

**Issue by rfnovo** [SoftFever/OrcaSlicer#867]
Add the option to use Motion ability numbers only to estimate print time, instead of always emitting to Gcode, similar as we have in PS and SS: 
![image](https://user-images.githubusercontent.com/11941836/234865573-697468df-a0f8-4cf4-bec0-676b7d7d1ee0.png)

**Comment by mikebcbc** [comment]
+1 to this!

**Comment by Grex3D** [comment]
+1 ! :)

**Comment by bonjorno7** [comment]
I would like to expand this idea to include not just machine limits, but speed/acceleration/jerk settings in print profiles too.
Preferably as separate options, because I would emit speed settings to G-code, and use acceleration and jerk only for time estimate.

**Comment by bonjorno7** [comment]
I didn't think the bot would actually close it.
I this would still be a nice feature and should remain open until someone implements it.
