### ISSUE TITLE
Hide GCODE preview when not in use

### ISSUE THREAD

**Issue by rfnovo** [SoftFever/OrcaSlicer#869]
When previewing the layers, the GCODE windows is hidden by default:
![image](https://user-images.githubusercontent.com/11941836/234881838-782d4eb6-e778-4a82-9fc4-5728637453cc.png)

And it will appear whenever the horizontal bar is touched, to show the specific GCODE:
![image](https://user-images.githubusercontent.com/11941836/234882151-9f34a5e4-5ad7-48f8-94f9-f44555223755.png)

But once this GCODE preview window appears it will no longer disappear, as it happens in other slicers where moving the vertical layer bar will make the GCODE preview window auto-hide:
![image](https://user-images.githubusercontent.com/11941836/234882687-aa1505e9-9ce5-45fe-94d0-a490f2384599.png)

**Comment by SoftFever** [comment]
Hi @rfnovo 
you can press `c` hotkey to hide it

**Comment by Dynom** [comment]
Hi,

I'd like to re-open this issue. As the OP states, albeit a bit cryptic, the Gcode window only appears when clicking on the horizontal slider. The hotkey-C shortcut doesn't show/hide the window, prior to clicking this slider.

**Comment by Dynom** [comment]
@rfnovo ping

**Comment by Shaolo** [comment]
This hotkey should be added to the view menu.
