### ISSUE TITLE
Make the speed adjustment on the main screen a slider

### ISSUE THREAD

**Issue by SwagDad99** [SoftFever/OrcaSlicer#87]
**Is your feature request related to a problem? Please describe.**
Sometimes 'Normal' isn't fast enough, and 'Sport' is too fast

**Describe the solution you'd like**
It would be nice if you could just adjust a slider to choose a speed.  From like %75 - %200 or something.

**Describe alternatives you've considered**
While the speeds CAN be adjusted individually before slicing, it would be nice to be able to do it on the fly like with the current option buttons.

**Additional context**

**Comment by eriroh** [comment]
I second that. It would also be nice to have a slider for the infill density as well.
