### ISSUE TITLE
Bug missing file Snapmaker J1

### ISSUE THREAD

**Issue by Frelidon** [SoftFever/OrcaSlicer#870]
**Describe the bug**
The following text is displayed: The configgured post-processing script does not exist: /Users/hliebscher/smfix_bs-darwin-arm64

**3mf File for This Bug**
If it is related to slicing, please append the 3mf file. It could be extremely helpful to solve the issue.
https://drive.google.com/drive/folders/1nhNQly_PCtsUed0oq-DFHpmh4_tONGHy?usp=sharing

**To Reproduce**
eliminate error !

**Expected behavior**
Would be nice if you can fix it would like to use the OrcaSlicer because it is very easy to use.

**Screenshots**
![Orca Slicer Frelidon](https://user-images.githubusercontent.com/131987119/234903317-497382c9-3c91-4d3a-811b-732dca428d31.png)

**Printer model**
Snapmaker J1

**Desktop (please complete the following information):**
 - OS: [Windows11 & Linux Mint]
 - Version [W11 & Mint21.1LTS]

**Comment by hliebscher** [comment]
its not a bug you have to select your own script....
you can read here 

https://github.com/SoftFever/OrcaSlicer/discussions/782

https://github.com/SoftFever/OrcaSlicer/pull/663

you find all files that you need here pls select your os version...

https://github.com/hliebscher/Snapmaker2Slic3rPostProcessor/releases

**Comment by Frelidon** [comment]
Hi hab gesehen du bist auch aus Deutschland. Kannst du mir bitte per Discord erklären was ich machen muss. Geht immer noch nicht.

**Comment by MarvDarf** [comment]
Hallo, hab bereits einige Stunden damit verbracht Orca Slicer zum laufen zu bekommen . Aber ich verzweifel leider daran .Hätte jemand der Deutsch kann vllt eine gute Anleitung oder Zeit zum Telefonieren bzw. Um mir bei meinen Problemen zu helfen ?
