### ISSUE TITLE
TPU retractions setting get disabled

### ISSUE THREAD

**Issue by TechDude23** [SoftFever/OrcaSlicer#874]
If you put your filament settings type as TPU the retractions settings get disabled so I have to put it on like petg for them to work.

Bambu Lab X1
Orca Slicer 1.6.2-beta 
Window 10

**Comment by SoftFever** [comment]
Can you provide a sample project?

**Comment by TechDude23** [comment]
Yes and I will retest on the newest orca version 1.6.2 and update you.

Thank you for the outstanding slicer and the hard work you put into it I think Bambu should contract you to the team :) $$
