### ISSUE TITLE
Feature request to add calibration lines to pre sliced build plate

### ISSUE THREAD

**Issue by keenzkustoms** [SoftFever/OrcaSlicer#88]
I have created this svg and stl for the bambulab plate to show the calibration lines before slicing to help you position objects on the plate before you slice it to prevent an overlap in the first layer. 
![Screenshot_20230101_172803_Chrome](https://user-images.githubusercontent.com/107819210/210162772-8b7cbe22-7230-4b68-b773-67278315e955.jpg)

https://www.printables.com/model/321899-bambulab-slicer-bed-texture-with-calibration-marke

Would be good it we could get like a toggle switch to turn it on and off. 
Cheers

**Comment by SoftFever** [comment]
I like your idea and work!
I will add this in the next release and credit you.

**Comment by keenzkustoms** [comment]
@SoftFever any update on this? cheers

**Comment by SoftFever** [comment]
@keenzkustoms Done! Thanks for creating the texture!

**Comment by Learoy1** [comment]
> I have created this svg and stl for the bambulab plate to show the calibration lines before slicing to help you position objects on the plate before you slice it to prevent an overlap in the first layer. ![Screenshot_20230101_172803_Chrome](https://user-images.githubusercontent.com/107819210/210162772-8b7cbe22-7230-4b68-b773-67278315e955.jpg)
> 


oh wow you used my model in the photo 🥇

**Comment by keenzkustoms** [comment]
@learoy1 yes I did thankyou! Shows it really well how useful it is when trying to line up your part with the calibration lines 😀

**Comment by CoryCharlton** [comment]
I noticed that when this feature is enabled in 1.6.0+ the plate name is replaced with the black cross hatch. Not sure if this is the intended behavior or if anything could be done about it but I figured I'd mention it. Let me know if you'd prefer I opened a new issue

**Comment by keenzkustoms** [comment]
@CoryCharlton yea might be worth making a separate bug report
