### ISSUE TITLE
Plate name says "Untitled" in orange

### ISSUE THREAD

**Issue by chuckkay** [SoftFever/OrcaSlicer#880]
**Describe the bug**
Each plate has a plate number in in the front right corner, but the the back left corner has the word "untitled"
the 3md file is saved with a name, the objects and assembly's have names, I even went to the project tab and gave the model a name, yet i cannot seam to find anyway to get rid of "Untitled" 

**Bambu x1**

 - OS: windows 11
 - Version orca 1.6.2 beta
![Screenshot 2023-04-28 101922](https://user-images.githubusercontent.com/10617746/235173178-1a7b4079-1ec5-4335-b4a0-0bde453faa0b.png)

**Comment by SoftFever** [comment]
You can find more information about plate name here: https://github.com/SoftFever/OrcaSlicer/releases/tag/v1.6.0

**Comment by chuckkay** [comment]
The simpler answer was “hit the gear icon at the corner of the plate”
