### ISSUE TITLE
mutated vowel in EXCLUDE_OBJECT_DEFINE NAME (STL-filename) pauses print

### ISSUE THREAD

**Issue by adooze** [SoftFever/OrcaSlicer#882]
**Describe the bug**
When a STL file has a mutated vowel (and maybe other special characters) the print pauses and can not be continued.

Example:

EXCLUDE_OBJECT_DEFINE NAME=Körper4.stl_id_1_copy_0 (....)

Fusion for instance names every unsaved body = Körper....

**To Reproduce**
Add a mutated vowel to the stl-filename

**Expected behavior**
change special characters in the code to uncritical characters

**Printer model**
random

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 1.6.2

**Comment by SoftFever** [comment]
Hi @adooze 

Make sure you migrate Klipper to Python3 for better Unicode support.
