### ISSUE TITLE
(Linux) Dark mode Checkbox missing

### ISSUE THREAD

**Issue by TexZeTech** [SoftFever/OrcaSlicer#883]
Version: [Orcaslicer V1.6.2 Stable Linux ubuntu](https://github.com/SoftFever/OrcaSlicer/releases/download/v1.6.2/OrcaSlicer_V1.6.2_Linux_ubuntu.zip)

**Describe the bug**
The checkbox for dark mode seems to not exist in the preference window.

**To Reproduce**
Run appimage -> down arrow menu -> Preferences

**Expected behavior**
A checkbox to exist there.

**Screenshots**
![image](https://user-images.githubusercontent.com/7254540/235225293-b13ba925-1c98-4efb-aa4b-5a2e04a78b6f.png)

**Desktop:**
 - OS: Ubuntu
 - Version: 22.04.2 LTS

I can also replicate this on my Manjaro Desktop.

**Comment by DonutCables** [comment]
Also noted in my usage of 1.6.2. Most of the window follows the system dark theme, but the portion displaying the build plate does not, and there is no checkbox available.

OS: Mint 21.1

**Comment by FedorZa** [comment]
Ubuntu, 22.04, 23.04 - Invisible text and no ability to change that
![image](https://github.com/SoftFever/OrcaSlicer/assets/126013/37ef1492-538c-4c14-b8f0-8c2175cb3df6)
![image](https://github.com/SoftFever/OrcaSlicer/assets/126013/7e22bb29-2c2b-45a3-935d-032a86e947f2)

**Comment by RobRobM** [comment]
Very annoying. This has been one of my main gripes for a while. Bambu Studio has the same problem.

**Comment by TexZeTech** [comment]
the above issue(s) are still present in 1.6.3

**Comment by TexZeTech** [comment]
> Still an issue on 1.6.4-beta3
> 
> Only issue I have on Pop_OS is the build plate background still being white.

I just add `"dark_color_mode": "1",` to the OrcaSlicer.conf under the `"app": {` somewhere.

**Comment by slashbeast** [comment]
I can confirm that adding `"dark_color_mode": "1",` in the `app` section of `OrcaSlicer.conf` fixes the invisible text when one uses dark version of GTK theme.

**Comment by TexZeTech** [comment]
> fixes the invisible text

I find it's hit and miss depending on where in the interface you are at. Mind you I'm running Manjaro KDE so *shrug*

**Comment by kesor** [comment]
> I can confirm that adding `"dark_color_mode": "1",` in the `app` section of `OrcaSlicer.conf` fixes the invisible text when one uses dark version of GTK theme.

I actually had the problem when the value was `"dark_color_mode": "1"` in `~/.config/OrcaSlicer/OrcaSlicer.conf` but changing it to be `"dark_color_more": "0"` or removing the line altogether fixed the text color. The theme still remained dark like the system theme.

**Comment by TexZeTech** [comment]
> > I can confirm that adding `"dark_color_mode": "1",` in the `app` section of `OrcaSlicer.conf` fixes the invisible text when one uses dark version of GTK theme.
> 
> I actually had the problem when the value was `"dark_color_mode": "1"` in `~/.config/OrcaSlicer/OrcaSlicer.conf` but changing it to be `"dark_color_more": "0"` or removing the line altogether fixed the text color. The theme still remained dark like the system theme.

What is the background color of the model area after? 
As I noticed a change in that, admittedly I would have to check if that interaction has changed since.

**Comment by TexZeTech** [comment]
LOL, I just tried to remove that line, and its persisting.

**Comment by kesor** [comment]
> LOL, I just tried to remove that line, and its persisting.

I ended up just forcing OrcaSlicer to use light mode for now, but exporting `GTK_THEME=:light` in a shell script that starts the slicer.

**Comment by hidara2000** [comment]
[](url)Finally got this working on Fedora using an AppImage

1. install Gnome Tweaks
2. add .themes folder to home
3. download adiwaita-dark and extract to .themes
![Screenshot from 2024-05-03 15-29-22](https://github.com/SoftFever/OrcaSlicer/assets/15170494/f38c99df-9dd5-43c8-9c8a-82aad35293e0)
3. log out and back in again and open gnome tweaks. and select adwaita dark
![Screenshot from 2024-05-03 15-30-22](https://github.com/SoftFever/OrcaSlicer/assets/15170494/3c34c999-f4ca-47e7-8303-9358033dbd83)

Dark mode is working and GCODE is visible
![Uploading Screenshot from 2024-05-03 15-31-40.png…]()

**Comment by Stortag** [comment]
> Finally got this working on Fedora using an AppImage
> 
>     1. install Gnome Tweaks
> 
>     2. add .themes folder to home
> 
>     3. download adiwaita-dark and extract to .themes
>        ![Screenshot from 2024-05-03 15-29-22](https://private-user-images.githubusercontent.com/15170494/327653157-f38c99df-9dd5-43c8-9c8a-82aad35293e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4OTI2ODMsIm5iZiI6MTcxOTg5MjM4MywicGF0aCI6Ii8xNTE3MDQ5NC8zMjc2NTMxNTctZjM4Yzk5ZGYtOWRkNS00M2M4LTljOGEtODJhYWQzNTI5M2UwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDAzNTMwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiYTkyY2QwNGI4NTI5ZWQxOGQxOGM2ZDk4NjkwOGU4YmE2NzA0YWY1Zjg1YmJjODU3OTQ1MWMyMzNiYjFhZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OV81gfAmWHdFH3gPOjrzI-98MAIZuGYG_sD8VxBmOmo)
> 
>     4. log out and back in again and open gnome tweaks. and select adwaita dark
>        ![Screenshot from 2024-05-03 15-30-22](https://private-user-images.githubusercontent.com/15170494/327653322-3c34c999-f4ca-47e7-8303-9358033dbd83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4OTI2ODMsIm5iZiI6MTcxOTg5MjM4MywicGF0aCI6Ii8xNTE3MDQ5NC8zMjc2NTMzMjItM2MzNGM5OTktZjRjYS00N2U3LTgzMDMtOTM1ODAzM2RiZDgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDAzNTMwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzMmYzYjMxMTVkZDk3MjkwMTViZWY2ODVhZTJmNTJlYWVjMmNlMjlkMWViZWUzNTcxNDUzZjllMjlhN2ZkMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.njULO9y05bUwiIECpmG1imreAazvtISmiqJt0giHY0s)
> 
> 
> Dark mode is working and GCODE is visible ![Screenshot from 2024-05-03 15-31-40](https://private-user-images.githubusercontent.com/15170494/327653548-8b2141f2-512e-4954-8218-5944d06cf21a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4OTI2ODMsIm5iZiI6MTcxOTg5MjM4MywicGF0aCI6Ii8xNTE3MDQ5NC8zMjc2NTM1NDgtOGIyMTQxZjItNTEyZS00OTU0LTgyMTgtNTk0NGQwNmNmMjFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDAzNTMwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2NGU3MjhkNWU1NTFiN2Q4NmQ4N2FhMjBhMjU0ZDU1YWUxZjdkODcwYWZhOWIxMzg0Mjg3ZDMwNGEwMjZhYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YabLV20E_7WR6KNlmRxykJac0E5gPmFiPOFyVbMAQbk)

This is the way. Can confirm it works perfectly on Ubuntu 22.04 as well

**Comment by Prazgreen1** [comment]
This really should not be closed as the original issue raised of no checkbox is still yet to be addressed. Not everyone will use GNOME, so a checkbox would be a quick patch to many issues about this. Considering it works on windows, I don't see why this would be an issue for Mac and Linux. I use the compiled version where there should be no issues with permissions, yet this issue persists. It wouldn't be that difficult to see if the gtk theme is dark or light, but just a toggle would be the easiest fix with dark being the default as it is most popular like how discord is dark by default. From a web frontend perspective, switching dark and light themes with a toggle is pretty easy as it can really be an item that when clicked will change the color scheme. It is relatively simple to implement on a web frontend, so this should be even easier to implement on orca as with c++, variables and logic exist in a very nice manner.

**Comment by Prazgreen1** [comment]
> > Finally got this working on Fedora using an AppImage
> > ```
> > 1. install Gnome Tweaks
> > 
> > 2. add .themes folder to home
> > 
> > 3. download adiwaita-dark and extract to .themes
> >    ![Screenshot from 2024-05-03 15-29-22](https://private-user-images.githubusercontent.com/15170494/327653157-f38c99df-9dd5-43c8-9c8a-82aad35293e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4OTI2ODMsIm5iZiI6MTcxOTg5MjM4MywicGF0aCI6Ii8xNTE3MDQ5NC8zMjc2NTMxNTctZjM4Yzk5ZGYtOWRkNS00M2M4LTljOGEtODJhYWQzNTI5M2UwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDAzNTMwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiYTkyY2QwNGI4NTI5ZWQxOGQxOGM2ZDk4NjkwOGU4YmE2NzA0YWY1Zjg1YmJjODU3OTQ1MWMyMzNiYjFhZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OV81gfAmWHdFH3gPOjrzI-98MAIZuGYG_sD8VxBmOmo)
> > 
> > 4. log out and back in again and open gnome tweaks. and select adwaita dark
> >    ![Screenshot from 2024-05-03 15-30-22](https://private-user-images.githubusercontent.com/15170494/327653322-3c34c999-f4ca-47e7-8303-9358033dbd83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4OTI2ODMsIm5iZiI6MTcxOTg5MjM4MywicGF0aCI6Ii8xNTE3MDQ5NC8zMjc2NTMzMjItM2MzNGM5OTktZjRjYS00N2U3LTgzMDMtOTM1ODAzM2RiZDgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDAzNTMwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzMmYzYjMxMTVkZDk3MjkwMTViZWY2ODVhZTJmNTJlYWVjMmNlMjlkMWViZWUzNTcxNDUzZjllMjlhN2ZkMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.njULO9y05bUwiIECpmG1imreAazvtISmiqJt0giHY0s)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Dark mode is working and GCODE is visible ![Screenshot from 2024-05-03 15-31-40](https://private-user-images.githubusercontent.com/15170494/327653548-8b2141f2-512e-4954-8218-5944d06cf21a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4OTI2ODMsIm5iZiI6MTcxOTg5MjM4MywicGF0aCI6Ii8xNTE3MDQ5NC8zMjc2NTM1NDgtOGIyMTQxZjItNTEyZS00OTU0LTgyMTgtNTk0NGQwNmNmMjFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDAzNTMwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2NGU3MjhkNWU1NTFiN2Q4NmQ4N2FhMjBhMjU0ZDU1YWUxZjdkODcwYWZhOWIxMzg0Mjg3ZDMwNGEwMjZhYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YabLV20E_7WR6KNlmRxykJac0E5gPmFiPOFyVbMAQbk)
> 
> This is the way. Can confirm it works perfectly on Ubuntu 22.04 as well

This should no longer be the solution as .themes is legacy with the modern solution being ~/.local/share/themes. It is an admittedly dumb change, but it seems to be the norm now for some reason.

**Comment by trankillity** [comment]
Another call to re-open this. Plasma 6.4.5 here and 2.3.0 was fine and detected system level dark mode, but 2.3.1 does not.

**Comment by parkerlreed** [comment]
> Another call to re-open this. Plasma 6.4.5 here and 2.3.0 was fine and detected system level dark mode, but 2.3.1 does not.

AppImage works for me with latest Plasma (Using the Orca nightly). But yeah Flatpak doesn't detect at all.

**Comment by JamesG3D** [comment]
Please reopen this, it is not fixed...

**Comment by Quick-Flash** [comment]
Still a problem. I've even gone into the .conf file and changed things only for it to be overwritten every time I open orcaslicer. Running orcaslicer via this command `GTK_THEME=Adwaita:dark ./OrcaSlicer.AppImage` does fix the issue for me though.

**Comment by wytr** [comment]
Issue persists with [OrcaSlicer V2.4.0 Alpha](https://github.com/OrcaSlicer/OrcaSlicer/releases/tag/v2.4.0-alpha)

OS: Fedora Linux 44 (KDE Plasma Desktop Edition) x86_64
Kernel: Linux 7.0.9-205.fc44.x86_64
Theme: Breeze (Dark) [Qt], Breeze-Dark [GTK2], Breeze [GTK3]
Icons: breeze-dark [Qt], breeze-dark [GTK2/3/4]
Font: Noto Sans (10pt) [Qt], Noto Sans (10pt) [GTK2/3/4]

Should be reopened
