### ISSUE TITLE
Inner/Outer wall order incorrect on arachne

### ISSUE THREAD

**Issue by nirurin** [SoftFever/OrcaSlicer#884]
**Describe the bug**
On classic mode it works fine. 
On arachne mode, if I select Inner/Outer/Infill, it instead does Outer/Inner/Infill. 

**3mf File for This Bug**
[untitledCylinder.zip](https://github.com/SoftFever/OrcaSlicer/files/11356759/untitledCylinder.zip)

**To Reproduce**
Arachne -> outer/inner/infill -> check layer print preview

**Expected behavior**
Obvious.

**Screenshots**
![Screenshot 2023-04-28 202926](https://user-images.githubusercontent.com/3751273/235236948-cd8be3a5-b6e9-4113-8a7f-90aacb12ac18.png)

**Printer model**
P1P

**Desktop (please complete the following information):**
Windows 11

This is on the new 1.62 release of orca, but it was the same on 1.60 too.

**Comment by nirurin** [comment]
It does seem to depend, there's a lot of weird wall-ordering issues when there are both convex and concave external walls like in this tube model. If the model is thicker, it does half the internal walls first, then an outer wall, then more internals. 
This model has no infill lines according to the preview key, so it's not an infill thing. Very odd.

**Comment by SoftFever** [comment]
I think it's dup with #745

**Comment by julie777** [comment]
I just discovered this trying to understand why my print keeps failing. The bottom chamfer of 5mm is printing outer-inner.

To add additional information, if I drop a primitive cube on the plate and set for two walls and slice, the order is inner-outer in the middle where there is just a hollow square of 2 layer walls. However, if I create a model in CAD that is just a hollow square (and some other shapes), then the wall order is outer-inner.

This is the shape that will show the wrong order. 
![image](https://github.com/SoftFever/OrcaSlicer/assets/5090005/cba0a7a2-63b9-47c2-b1ee-840045c280fd)

I also verified that Bambu Studio does not have this bug.

**Comment by julie777** [comment]
The light bulb just hit me on the head and broke.
In the case that is causing print failures for me, and in the above test with 2 walls, they are all outside perimeters. The object has a thickness of 2 perimeters which makes them both outside. 

Where this causes problems for me in when that ordering does the outer outside perimeter first, when printing a chamfer that is overhanging. It prints the overhang before printing the inside perimeter that would provide the anchor for it.

Classic showing the order that works.
![image](https://github.com/SoftFever/OrcaSlicer/assets/5090005/d7dd2fa8-d817-4f4e-88eb-e27d1fa4c170)

and arachne showing why my print fails.
![image](https://github.com/SoftFever/OrcaSlicer/assets/5090005/aedb14a7-9f96-49e1-8920-58a8a79ca9ec)

**Comment by julie777** [comment]
I tried using Classic as a work-around to get my print to succeed. It quickly fails, because on layer 3 it create a single perimeter, instead of two. That perimeter is overhang, and printed before the infill, so it has nothing to really attach to.

![image](https://github.com/SoftFever/OrcaSlicer/assets/5090005/be09416b-59d2-45dc-b46c-186379513791)

**Comment by julie777** [comment]
> I also verified that Bambu Studio does not have this bug.

After much more searching for a way to fix my print, I found that Bambu Studio does print the outermost perimeter of the overhang first in at least some cases. (using arachne)

**Comment by lynxzp** [comment]
Just for case, bug present for 2.2.0-beta
![image](https://github.com/user-attachments/assets/a73192e8-bb44-42ca-b6bd-59dcb54b9712)

**Comment by tripletto** [comment]
Orca Slicer 2.1.1 here. Just encountered the same bug.

No matter what I select (outer/inner, inner/outer, inner/outer/inner), Orca Slicer uses the outer/inner option to configure the toolpath, when I use arachne.

**Comment by OriginalSlarm** [comment]
> Orca Slicer 2.1.1 here. Just encountered the same bug.
> 
> No matter what I select (outer/inner, inner/outer, inner/outer/inner), Orca Slicer uses the outer/inner option to configure the toolpath, when I use arachne.

This thread was stale and closed - I created a new thread #7145 which is live for the newer version of OS. If you don't mind bumping that thread, let's keep it from getting stale too!
