### ISSUE TITLE
Profile deletes with Post Processing Script

### ISSUE THREAD

**Issue by frankt2012** [SoftFever/OrcaSlicer#889]
**Describe the bug**
When I add a post processing script my profile is deleted on restart.

**To Reproduce**
Create profile and add post processing script. Profile will be deleted when Orca restarts.

**Expected behavior**
It should save it.

**Printer model**
Ender S1 with Sonic Pad

**Desktop (please complete the following information):**
Windows 11

**Comment by SoftFever** [comment]
Can you find the process file(.json) under %appdata%/OrcaSlicer/user/*/process?
If so, can you share it?

**Comment by frankt2012** [comment]
> Can you find the process file(.json) under %appdata%/OrcaSlicer/user/*/process? If so, can you share it?

Here it is. Works fine when I make the profile. But as soon as I exit the slicer and restart it instantly deletes itself.

[Ender S1 Klipper 0.20mm Standard @MyKlipper.zip](https://github.com/SoftFever/OrcaSlicer/files/11359320/Ender.S1.Klipper.0.20mm.Standard.%40MyKlipper.zip)

**Comment by SoftFever** [comment]
@frankt2012 
It seems that the double quote is causing trouble with the JSON format. As a workaround, could you put the "klipper_extimator.exe" file in a path that does not contain any whitespaces? 
Then in OrcaSlicer, don't double quote the path:
![image](https://user-images.githubusercontent.com/103989404/235307446-464da1aa-357b-4ad6-a0eb-c36b1bb2d66a.png)

This should fix you problem

**Comment by frankt2012** [comment]
> @frankt2012 It seems that the double quote is causing trouble with the JSON format. As a workaround, could you put the "klipper_extimator.exe" file in a path that does not contain any whitespaces? Then in OrcaSlicer, don't double quote the path: ![image](https://user-images.githubusercontent.com/103989404/235307446-464da1aa-357b-4ad6-a0eb-c36b1bb2d66a.png)
> 
> This should fix you problem

I will try that. The only reason for the quotes was because I couldn't get it working without. Will try again.

**Comment by frankt2012** [comment]
> @frankt2012 It seems that the double quote is causing trouble with the JSON format. As a workaround, could you put the "klipper_extimator.exe" file in a path that does not contain any whitespaces? Then in OrcaSlicer, don't double quote the path: ![image](https://user-images.githubusercontent.com/103989404/235307446-464da1aa-357b-4ad6-a0eb-c36b1bb2d66a.png)
> 
> This should fix you problem

Ok that worked. I don't know why but I thought I did that in the beta. Thank you.
