### ISSUE TITLE
Bambu Studios Pluging Download Failed

### ISSUE THREAD

**Issue by Tyler8299** [SoftFever/OrcaSlicer#89]
Program Crashes about 3x before it launches. when it does it fails to download Bambu Plugin. I disabled all Windows antivirus still did not work. was able to continue using the last version without issues. thank you and happy new year and thank you for everything

![Screenshot_20230101_095743](https://user-images.githubusercontent.com/121695166/210175141-30abcb79-1e7b-4d29-8e1f-1952abefa4c5.png)

**Comment by SoftFever** [comment]
@Tyler8299 I have no idea why it failed to download plugin on some machines.
As a temporary workaround, You can try to copy %appdata%\BambuStudio\plugins folder to %appdata%\BambuStudio-SoftFever\plugins manually.

**Comment by davidja92** [comment]
Mine was failing and i force quit microsoft teams and then the plugin downloaded. i do not know the correlation but i can replicate it every time

**Comment by Tyler8299** [comment]
force quitting teams did the trick thank you!!

**Comment by Tyler8299** [comment]
BTW i have a Creality CR10V3 and Ender 3 S1 profile preset for Bambu Labs
works amazing.

**Comment by hliebscher** [comment]
can you check in CURL.cmake

if (WIN32)
  #set(_curl_platform_flags  ${_curl_platform_flags} -DCMAKE_USE_SCHANNEL=ON)
  set(_curl_platform_flags  ${_curl_platform_flags} -DCMAKE_USE_OPENSSL=ON -DCURL_CA_PATH:STRING=none)

edit pls and recompile ... i can't check no windows

that is the difference to org Bambu

**Comment by Tyler8299** [comment]
I do not know how to do this
________________________________

**Comment by Tyler8299** [comment]
I know you are a busy person, id be willing to let you rummage around on my machine using a remote desktop to help your Software if we are both available. Thank you again your Software is amazing
________________________________

**Comment by davidja92** [comment]
@hliebscher this issue is also persistent with the normal bambu studio closing teams still fixes it.

**Comment by WareWolfSoftworks** [comment]
For anyone else with this issue I had already uninstalled Teams. I force closed the Edge program that was running in the background. I don't use Edge but apparently it starts a service no matter what. So if you don't have Teams give that a shot.

**Comment by SoftFever** [comment]
Closing as problem solved.
