### ISSUE TITLE
[Feature Request] Enforce Z-Hop On Top Surfaces Option

### ISSUE THREAD

**Issue by mikebcbc** [SoftFever/OrcaSlicer#892]
**Is your feature request related to a problem? Please describe.**
I have been loving OrcaSlicer so far, however, one crucial setting from SuperSlicer that drastically reduced stringing for me on cheaper filaments is only allowing Z Hop on top surfaces. This reduced stringing while also combatting problems with knocking tall prints down.

**Describe the solution you'd like**
I would love to see this feature implemented in OrcaSlicer - the ability to specify where Z-Hop happens dynamically - only on the top layers.

**Describe alternatives you've considered**
Nothing that I can see so far.

**Additional context**
Related issues from what I can tell:
https://github.com/SoftFever/OrcaSlicer/issues/741

Here's a screenshot of where this feature lives in SuperSlicer - under Printer Settings.

![Capture](https://user-images.githubusercontent.com/15934114/235321234-315f5eed-ec59-4d91-940b-115cd359836d.JPG)

**Comment by OrloDavid** [comment]
Is it possible to get Only Z-Hop on Layer Change?
I don't see it as an option and a search didn't reveal anything in that regard. 

I primarily like to use this option when printing very dense parts, 80-100% infill, it helps with the nozzle drag when zooming across prints during layer change, which is amplified by my large avoid open parts value. If I could just do a little .2 or .4 bump on layer change it would be perfect.

Thank You
