### ISSUE TITLE
(1.6.2) Flush options disabled when Prime Tower is disabled

### ISSUE THREAD

**Issue by Desterly** [SoftFever/OrcaSlicer#894]
**Describe the bug**
When performing a multi-color print, disabling the prime tower also disables the "Flush Options" .   Enabling Prime tower enables these.

This seems to be new to 1.6.2

**To Reproduce**
Enable/Disable Prime Tower Option and see Flush options enabled/disabled

**Expected behavior**
Prime Tower and Flush Options should be separately controllable

**Screenshots**
![image](https://user-images.githubusercontent.com/1772474/235328787-9ea1cccf-12a6-4aa5-a610-7fa335cf1461.png)
![image](https://user-images.githubusercontent.com/1772474/235328790-dcd6c0cb-d2a5-4458-9677-f3f9b22bd3ad.png)

**Printer model**
Bambulabs Carbon X1 

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 1.6.2 of the slicer

**Comment by DHernan** [comment]
Did you ever find out if this is on purpose?

**Comment by Desterly** [comment]
> Did you ever find out if this is on purpose?

It's the same in BambuStudio as well so not sure if it's on purpose but it's an upstream item.  I didn't dig too far though to see if it changes the GCODE when you deselect the prime tower though.

**Comment by Sod-Almighty** [comment]
Why is this bug closed? It is still happening.

**Comment by samster395** [comment]
Any update on this?

I see no reason for there to be restriction on this.

@SoftFever Can we get this reopened?
