### ISSUE TITLE
Add FLSUN V400 printer profile

### ISSUE THREAD

**Issue by robanderson** [SoftFever/OrcaSlicer#9]
I would like to request a printer profile for the popular FLSUN V400 be added to list.

I noticed that when defining the print bed there is currently no circular option that exists in PrusaSlicer. 

I'm happy to donate $100 via PayPal to this project if anybody can add the V400 to this project.

I currently run 2x X1CC 3x Vorons and 1x V400 and would love to use this slicer for all my printers rather than have to maintain and learn Cura (the default V400 slicer)

**Comment by SoftFever** [comment]
A bit of underground work is required to support delta printers.
Those printers have their origin(0,0) point at the center of the bed.
V400 will be added once I fix that first.

**Comment by tokamac** [comment]
That would be wonderful, as I have both an X1-Carbon and a V400! 
Especially, I tried to print a very demanding model with a very important curvy slope but PrusaSlicer and BambuStudio treat differently the top surface layers and their various settings. Even when tuned equally, they produce different outputs. As a result, the file sliced with BambuStudio or your SoftFever fork works on the X1C but fails to print on the V400 (sliced in PS). 
This may be a printer-related issue. But I feel the slicer is the culprit. This is a very specific case I know.

**Comment by cpasoft** [comment]
I'm guessing that's going to be very low on the list of things to develop but, can I ask if there is some kind of deadline for this.

Thanks and congrats for this beautiful piece of software... ;-)

**Comment by Naninani** [comment]
@SoftFever, if you add the support for the circular bed shape, I will submit a pull request to add the V400 config files. I have it dialed in, just need the circular bed shape support.

**Comment by arshish1612** [comment]
Is there any update on this?

**Comment by tokamac** [comment]
Indeed, this request has won the title of the oldest open issue on this Github repo.

**Comment by SoftFever** [comment]
Sorry guys. I know it takes a little bit longer than expected.
Anyway, I spent some time investigating delta printers this weekend, and I think I made some progress.
Hopefully, I can release an alpha build for delta printers this week.
G-code looks right to me. 
I don't have any delta printers so I can't test it by myself.
![image](https://user-images.githubusercontent.com/103989404/230769187-b4dbcbdd-cc71-450f-88ec-a0afbebf9484.png)
![image](https://user-images.githubusercontent.com/103989404/230769402-7505b62d-8709-417a-ad3b-c9a024beb3ec.png)

**Comment by tokamac** [comment]
We will test it :)

**Comment by Jokiblack** [comment]
> Sorry guys. I know it takes a little bit longer than expected. Anyway, I spent some time investigating delta printers this weekend, and I think I made some progress. Hopefully, I can release an alpha build for delta printers this week. G-code looks right to me. I don't have any delta printers so I can't test it by myself. ![image](https://user-images.githubusercontent.com/103989404/230769187-b4dbcbdd-cc71-450f-88ec-a0afbebf9484.png) ![image](https://user-images.githubusercontent.com/103989404/230769402-7505b62d-8709-417a-ad3b-c9a024beb3ec.png)

Send a beta and we'll start testing with v400.

**Comment by MrGnarly90** [comment]
Same i have two heavily modified SRs which makes my circle 265mm and have direct drive. Happy to help test, been WAITING for this! thank you for all your hard work sir!

**Comment by MrGnarly90** [comment]
following up on this :) any word on a test version?

**Comment by MrGnarly90** [comment]
Thank you for the beta release!

**Comment by tokamac** [comment]
Whoohooohoooo 🥳
https://github.com/SoftFever/OrcaSlicer/releases/tag/v1.6.2

**Comment by SoftFever** [comment]
Delta printers are supported now.
Feedbacks or suggestions for the default profiles are welcomed.
Also let’s move on the discussion thread🥰
This ticket will be closed soon

**Comment by robanderson** [comment]
![374C1D9C-9010-4E6D-AE08-C7E008FEB225](https://user-images.githubusercontent.com/907070/232591335-8f8cc703-64b9-4281-bda6-93384d9e045b.png)

**Comment by SoftFever** [comment]
> ![374C1D9C-9010-4E6D-AE08-C7E008FEB225](https://user-images.githubusercontent.com/907070/232591335-8f8cc703-64b9-4281-bda6-93384d9e045b.png)

@robanderson This is nuts! Thank you so much :)
