### ISSUE TITLE
Can't compile on macOS

### ISSUE THREAD

**Issue by Guilouz** [SoftFever/OrcaSlicer#900]
**Describe the bug**
CMake Error at src/libslic3r/CMakeLists.txt:445 (find_package):
  By not providing "FindOpenCASCADE.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "OpenCASCADE", but CMake did not find one.

**Screenshots**
<img width="1012" alt="Capture d’écran 2023-04-30 à 17 15 01" src="https://user-images.githubusercontent.com/12702322/235360956-88b50920-e9a0-432e-84e1-fa04e283de0c.png">

**Desktop (please complete the following information):**
 - OS: macOS 13.4
 - Xcode, Cmake, git, gettext are installed

**Comment by hliebscher** [comment]
witch processor type ?

**Comment by lrsweet** [comment]
The same error occurs when compiling on Windows 11 using Visual Studio 2019. 

CMake Error at src/libslic3r/CMakeLists.txt:447 (find_package):
  By not providing "FindOpenCASCADE.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "OpenCASCADE", but CMake did not find one.

  Could not find a package configuration file provided by "OpenCASCADE" with
  any of the following names:

    OpenCASCADEConfig.cmake
    opencascade-config.cmake

  Add the installation prefix of "OpenCASCADE" to CMAKE_PREFIX_PATH or set
  "OpenCASCADE_DIR" to a directory containing one of the above files.  If
  "OpenCASCADE" provides a separate development package or SDK, be sure it
  has been installed.

**Comment by SoftFever** [comment]
Have you checked the build log deps?
`build_release_macos.sh -d` to build deps

**Comment by Guilouz** [comment]
@SoftFever This is the full logs for building deps : 

[logs.txt](https://github.com/SoftFever/OrcaSlicer/files/11430690/logs.txt)

**Comment by patofoto** [comment]
Any help solving this would be greatly appreciated

[sh build_release_macos.txt](https://github.com/SoftFever/OrcaSlicer/files/11908279/sh.build_release_macos.txt)

**Comment by patofoto** [comment]
@SoftFever Thank you but still not working.
[sh build_release_macos_2.txt](https://github.com/SoftFever/OrcaSlicer/files/11909394/sh.build_release_macos_2.txt)

**Comment by patofoto** [comment]
This is what I changed
[OCCT.txt](https://github.com/SoftFever/OrcaSlicer/files/11909410/OCCT.txt)
