### ISSUE TITLE
[Feature Request] GCode Substitutions or Prevent ozzing after M600 (Non AMS Printer)

### ISSUE THREAD

**Issue by fontenele** [SoftFever/OrcaSlicer#903]
**Is your feature request related to a problem? Please describe.**
When using non AMS printer and we have to use M600 to change filament, to prevent oozing in prusaslicer we have to comment next line after M600 using gcode substitutions. [Reference](https://github.com/prusa3d/PrusaSlicer/issues/8047#issuecomment-1413816569)

**Describe the solution you'd like**
I dont know if Orca have an option for this issue, if already have sorry my mistake here.

**Describe alternatives you've considered**
Prevent retraction after M600.

**Additional context**
Some print about workaround this problem
![image](https://user-images.githubusercontent.com/906710/235365129-8c7e8587-6c64-432a-ab10-dfb2528a0475.png)
![image](https://user-images.githubusercontent.com/906710/235365154-01fccfd6-a109-4c85-bf74-d6ac31e038b7.png)
![image](https://user-images.githubusercontent.com/906710/235365214-621ff178-7862-4a24-9fba-4891eb3e2884.png)

**Comment by SoftFever** [comment]
Orca does do extra retraction for filament change.
The setting is, however read-only in current versions.
Gonna change that
![image](https://user-images.githubusercontent.com/103989404/235486823-f8dd75e9-d951-47a4-9935-c639721a831a.png)
![image](https://user-images.githubusercontent.com/103989404/235486934-c5b1be3c-7d4d-45f9-9d81-db431b0bb57e.png)

**Comment by SoftFever** [comment]
Fixed in 1.6.3 beta
