### ISSUE TITLE
Option to configure "dead time" for print time calculation

### ISSUE THREAD

**Issue by Eliminateur** [SoftFever/OrcaSlicer#904]
Add an option to the printer configuration to set a fixed "dead time" to add to every print, to take into consideration bed heating and zeroing procedures which can take several minutes, superslicer already has this implemented

**Comment by foxmckraut** [comment]
i dont make a new issue cause the goal is the same:

me and some other are getting arround 20% more printing time than estimated...like i startet a print yesterday 1900 and it still says >3h. its not specific its on every print the same :/



<img width="275" alt="Bildschirm­foto 2023-05-03 um 20 21 55" src="https://user-images.githubusercontent.com/101701200/236008821-89d7ed7f-c810-49bc-9693-6e37c496e45e.png">
