### ISSUE TITLE
Remove the limit for layer height

### ISSUE THREAD

**Issue by julie777** [SoftFever/OrcaSlicer#905]
**Describe the bug**

P1P using .4mm nozzle and Bambu Slicer will not let me set layer height to .3 which is very common for a .4 nozzle. Instead it limits the layer height to .28.

![image](https://user-images.githubusercontent.com/5090005/235379392-d1ec9994-c8c8-4904-a99c-55051835d13f.png)

Describe the solution you'd like

Allow me to set the layer height that I choose. The print profiles provides show me what BL thinks is a good setting. I get that. However, there are many reasons to choose a different height.

**Desktop (please complete the following information):**
 - OS: Windows]
 - Version 1.6.2

**Comment by TechDude23** [comment]
Hi Julie777

You can change it in the Printer Settings go to the extruder tab and layer height limits - Max 0.28 and change it to 0.32 and save settings

**Comment by derx05** [comment]
Hey guys,
quick note. This issue can cause an endless  instant crash loop. When I open my slicer I get exactly that error and it instantly crashes. (Version 1.6.2)
Sadly I don't know which config file includes this value so I am stuck!

**Comment by SoftFever** [comment]
> Hey guys, quick note. This issue can cause an endless instant crash loop. When I open my slicer I get exactly that error and it instantly crashes. (Version 1.6.2, MacOS) Sadly I don't know which config file includes this value so I am stuck!

Is there any useful info in the log file?

**Comment by derx05** [comment]
> > Hey guys, quick note. This issue can cause an endless instant crash loop. When I open my slicer I get exactly that error and it instantly crashes. (Version 1.6.2, MacOS) Sadly I don't know which config file includes this value so I am stuck!
> 
> 
> 
> Is there any useful info in the log file?

Will post as soon as I am back home

**Comment by derx05** [comment]
[Crash Logs.zip](https://github.com/SoftFever/OrcaSlicer/files/11375961/Crash.Logs.zip)
 Here are the 2 logs. The one Orca Drops in its logs folder and the one macOS generates. Honestly I didn't spent much time looking into them, cause I am not into this project. Hope it helps

**Comment by hliebscher** [comment]
@derx05  i think softfever needs the log files from /Users/?????/Library/Application Support/OrcaSlicer/log/

**Comment by derx05** [comment]
> @derx05 i think softfever needs the log files from /Users/?????/Library/Application Support/OrcaSlicer/log/

One of the logs provided in the zip is exactly that log file. But I can't find an error in them so either their logging is not working or that crash is not causing a log entry.

**Comment by SoftFever** [comment]
> [Crash Logs.zip](https://github.com/SoftFever/OrcaSlicer/files/11375961/Crash.Logs.zip) Here are the 2 logs. The one Orca Drops in its logs folder and the one macOS generates. Honestly I didn't spent much time looking into them, cause I am not into this project. Hope it helps

I can't find useful info in the log file either.

Anyway, you can manually add the following line in your custom profile(.json). It may fix the issue for you.
I suspect the value in your custom profile is corrupted somehow.
```
    "max_layer_height": [
        "0.3"
    ],
```

**Comment by derx05** [comment]
> > [Crash Logs.zip](https://github.com/SoftFever/OrcaSlicer/files/11375961/Crash.Logs.zip) Here are the 2 logs. The one Orca Drops in its logs folder and the one macOS generates. Honestly I didn't spent much time looking into them, cause I am not into this project. Hope it helps
> 
> I can't find useful info in the log file either.
> 
> Anyway, you can manually add the following line in your custom profile(.json). It may fix the issue for you. I suspect the value in your custom profile is corrupted somehow.
> 
> ```
>     "max_layer_height": [
>         "0.3"
>     ],
> ```

Yeah I couldn't find the paramenter I solved it yesterday by deleting the user folder.

**Comment by SoftFever** [comment]
Closing as problem solved.
