### ISSUE TITLE
reprap firmware (duet wifi)

### ISSUE THREAD

**Issue by broncosis** [SoftFever/OrcaSlicer#906]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by broncosis** [comment]
here is a well built Prusa profile for a railcore 
https://github.com/JohnOCFII/RailCore/tree/master/slicers/PrusaSlicer
would be awesome if I could use the same slicer for both machines

**Comment by hliebscher** [comment]
pls describe  what you want to happen.
duet wifi runs like it is ... you can set your custom printer and under settings HOST TYPE = DUET

**Comment by broncosis** [comment]
Mostly I think after poking around a bit it does support it 
just doesn't have a option from the printer setup menu 

so you have to choose a Marlin printer then edit it from there 
to use Reprap firmware   

its a small thing I know if its a hassle I get it 
but the point of a feature request is to ask and provide Ideas

**Comment by mydevpeeps** [comment]
in cura the duet plug does the exact same thing the x1c does.  send or print (send and print from card). like to see this available for duet as well

**Comment by broncosis** [comment]
This is available in superslicer and prusa aswell would be a decent addon.
