### ISSUE TITLE
Fan speed calibration test/overhangs

### ISSUE THREAD

**Issue by borris345** [SoftFever/OrcaSlicer#919]
Not sure if there is one already available not in the orca slicer. 

With the x1c there are multiple fans.

Overhangs are a specific printer setting so a test to see which fan speeds work best would be good.

Aux fan on the x1c. I don't even use it currently as I have seen problems with using it pulling prints up. Would be good if there were some tests to be done to work things out easier.

**Comment by haynesdavid** [comment]
This would be great supprised there is no response, could have options to change fan speed in the temperature model maybe as a minimum however there are lots of great bridge models.
