### ISSUE TITLE
"Fixed low-resolution Windows icons issue" - Not fixed in 1.6.2

### ISSUE THREAD

**Issue by WanaGo** [SoftFever/OrcaSlicer#921]
**Describe the bug**
V1.6.1 mentioned in Windows "Fixed low-resolution Windows icons issue" however in V1.6.2 the icon is still low resolution compared to say V1.5.0

**Screenshots**
![image](https://user-images.githubusercontent.com/759846/235578842-36568f48-807e-489f-b96d-04fc274ddf31.png)

**Printer model**
Bambu Lab X1C

**Desktop (please complete the following information):**
Windows 10 Pro x64
Version 22H2

**Comment by SoftFever** [comment]
@WanaGo The slight blurriness is intended for the anti-aliasing. Also the shadow contributes a bit here.
Can you verify the icon resolution is right on your computer by temporarily changing large icon view for you desktop as showed bellow?
![image](https://user-images.githubusercontent.com/103989404/235690869-7a429cba-502d-4f70-9a98-94d4b96aa4ae.png)

You should be able see something like this:
![image](https://user-images.githubusercontent.com/103989404/235691279-24aa07dd-8be0-4d5e-a8c7-5bf4c88ec7bd.png)
