### ISSUE TITLE
Max flowrate calibration in 1.6.3 beta

### ISSUE THREAD

**Issue by RaySajuuk** [SoftFever/OrcaSlicer#930]
**Describe the bug**
The max flowrate calibration in v1.6.3 generates a very tall model that takes a few hours to finish printing. I would assume the generated model should be similar dimensions in v1.6.2.

**3mf File for This Bug**
Built-in max flowrate model

**To Reproduce**
Generate max flowrate calibration via the calibration menu in OrcaSlicer any version of v1.6.3.

**Expected behavior**
I would assume the calibration model should be similar to the previous model.

**Screenshots**
![SCR-20230502-rzka](https://user-images.githubusercontent.com/1126364/235829641-16e47664-c2ef-4e65-be76-c7577bdc854b.jpeg)

**Printer model**
BBL X1CC

**Desktop (please complete the following information):**
 - OS: [MacOS]
 - Version [Ventura 13.4]

**Comment by psiberfunk** [comment]
There's a 1.6.3 beta somewhere?  are we talking about nightlies?

**Comment by RaySajuuk** [comment]
Happy to report the issue is resolved.

**Comment by SoftFever** [comment]
> There's a 1.6.3 beta somewhere? are we talking about nightlies?

is referring to the nightly build
