### ISSUE TITLE
Help menu disappears after few seconds

### ISSUE THREAD

**Issue by RaySajuuk** [SoftFever/OrcaSlicer#936]
**Describe the bug**
The help menu disappears after a few seconds.

**To Reproduce**
Launch Orcaslicer help menu will disappear soon after.

**Expected behavior**
The help menu should remain in the menu bar.

**Screenshots**
<img width="609" alt="SCR-20230503-dlsh" src="https://user-images.githubusercontent.com/1126364/235887708-19a092df-a0a0-4681-a283-94dcbfc61999.png">
<img width="486" alt="SCR-20230503-dlux" src="https://user-images.githubusercontent.com/1126364/235887726-c5ba2cf4-1a36-46ac-ba2e-48257159c321.png">

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Version [13]

**Comment by RaySajuuk** [comment]
I am running it on  Macbook Pro notched display, and the menu bar has enough free space to show all items.

**Comment by liftbag** [comment]
I have the same issue.

macos 13.3.1 (a) apple silicon
OrcaSlicer Build Mac AppleSilicon 319: Commit (951293c) pushed by SoftFever


https://github.com/SoftFever/OrcaSlicer/assets/14921654/fb3223d4-577d-448c-a84e-31f5f62cb491

**Comment by RaySajuuk** [comment]
Issue resolved
