### ISSUE TITLE
External Spool feature missing from 1.6.2?

### ISSUE THREAD

**Issue by Photogad** [SoftFever/OrcaSlicer#946]
**Describe the bug**
Not sure if it's a bug or user error but external spool support seems to be missing from OrcaSlicer 1.6.2 (is it not built against Bambu Studio 1.6.2?? They introduced external spool support in 1.6.2)

**Screenshots**
![Screenshot 2023-05-03 205134](https://user-images.githubusercontent.com/18505956/236082857-8ac6f8c6-23b2-4744-b9f8-91a41abe463d.jpg)

**Printer model**
Bambu X1CC

**Desktop (please complete the following information):**
Windows
1.6.2 latest public release as of 5/2/22

**Comment by fr3ak2402** [comment]
This is not a bug, but the feature is not yet included in version V1.6.2. This is currently only included in the nightly build of V1.6.3 and then also in the official V1.6.3 of OrcaSlicer.

**Comment by Photogad** [comment]
> This is not a bug, but the feature is not yet included in version V1.6.2. This is currently only included in the nightly build of V1.6.3 and then also in the official V1.6.3 of OrcaSlicer.

Good to know.
I suggest kindly to @SoftFever to keep naming convention of OrcaSlicer versions to match closer to Bambu Studio. I realize OrcaSlicer is being developed to be its own slicer software, but if it's built against Bambu Studio it can help avoid confusion.

**Comment by fr3ak2402** [comment]
@Photogad 
I have proposed this adjustment. You can take a look at the proposal.
Improvement of the display of the basic version of Bambu Lab Studio in OrcaSlicer and in Github. #961

**Comment by Photogad** [comment]
> @Photogad I have proposed this adjustment. You can take a look at the proposal. Improvement of the display of the basic version of Bambu Lab Studio in OrcaSlicer and in Github. #961
@fr3ak2402 
thank you

**Comment by Photogad** [comment]
I am closing this for now. Question has been answered.
