### ISSUE TITLE
[Voron] Send to print is cutting out the info

### ISSUE THREAD

**Issue by R4toLoko** [SoftFever/OrcaSlicer#948]
First of all thank you, this is freaking awesome, I never used this with X1C because it requires cloud.
With my Voron this works flawlessly, THANK YOU!

I did notice tho the info which appears to inform that if you wanna change the folder level, you must use slashes, isn't being displayed properly.
Nothing wrong with the feature, just "cosmetics"

Thank you

![image](https://user-images.githubusercontent.com/35049512/236088827-ff5e19e6-5378-4a13-87fc-842e2b6836ac.png)
![image](https://user-images.githubusercontent.com/35049512/236089110-563ff69e-8651-4a8b-b20e-dbe4b2b85767.png)

**Comment by hliebscher** [comment]
![dis](https://user-images.githubusercontent.com/9274162/236113937-6dba8750-afe2-4bfb-9632-3b882e3a8e2b.jpg)

For me it works fine...
MAC M1 1.6.3beta

**Comment by H4kunaM4tata** [comment]
> ![dis](https://user-images.githubusercontent.com/9274162/236113937-6dba8750-afe2-4bfb-9632-3b882e3a8e2b.jpg)
> 
> For me it works fine...
> MAC M1 1.6.3beta

Weird, it must be a Linux thing then.
For what matter the feature is working flawlessly.
Thanks for sharing that.

**Comment by R4toLoko** [comment]
This is still a cosmetic issue on Linux @SoftFever 
Not a biggie, can be closed.

![image](https://github.com/SoftFever/OrcaSlicer/assets/35049512/013235a7-773b-42da-b5ba-ba1b95119e36)

**Comment by R4toLoko** [comment]
This is just a cosmetic thin, it isn't fixed and other parts have the same but I am closing it.
