### ISSUE TITLE
The EXCLUDE_OBJECT_DEFINE area emitted in the PA calibration is wrong

### ISSUE THREAD

**Issue by rpls** [SoftFever/OrcaSlicer#955]
**Describe the bug**
The `EXCLUDE_OBJECT_DEFINE` G-Code that is emitted when running a PA calibration only encompasses the "PA Test" string, not the G-Code area of all the printed lines. This isn't problematic, unless you use something like [KAMP](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging), that adapts the mesh leveling and purge lines to the area defined by `EXCLUDE_OBJECT_DEFINE`.

**3mf File for This Bug**
N/A

**To Reproduce**
Just run a PA calibration and observe the area defined in the `EXCLUDE_OBJECT_DEFINE` and compare to what the minimum/maximum G-Code coordinates are.

**Expected behavior**
The `EXCLUDE_OBJECT_DEFINE` of the PA test should encompass all the G-Code moves.

**Screenshots**
N/A

**Printer model**
Voron V0.1 with Klipper and "KAMP" mesh leveling set up.

**Desktop (please complete the following information):**
 - OS: macOS 13.3.1
 - Version 1.6.2

**Comment by jonathanalevi** [comment]
Also having issues with this.
