### ISSUE TITLE
1.6.2 Failed to open G-code file by OrcaSlicer itself

### ISSUE THREAD

**Issue by buckeyestargazer** [SoftFever/OrcaSlicer#958]
**Describe the bug**
Previously exported plate slices created in 1.6.1 will not open in 1.6.2. I just installed 1.6.2 and have opened/closed OrcaSlicer multiple times and it will not open.  Normally I just drag the .3mf file to OS and it open fine.  I have also tried to open the .3mf file from the menu with the same problem. 
Here is the error I get:  "Failed to process the G-code file C:\Users\???\AppData\Local\Temp/orcaslicer_model/Thu_May_04/17_32_15#31604#55/Metadata/plate_1.gcode from previous 3mf"

This would be a real bummer as I have many exported sliced 3mf files.

**3mf File for This Bug**
If it is related to slicing, please append the 3mf file. It could be extremely helpful to solve the issue.

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**

**Printer model**

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 11

**Comment by hliebscher** [comment]
where is the 3mf located and can you zip this and attach this ?

**Comment by buckeyestargazer** [comment]
Well, I spoke too soon.  It seems like some of my exported models work and others don't.  All of these models were sliced in OS and then exported to a folder, so I'm not sure why some work and others don't.  

One problematic 3mf file is attached.  This file opens as expected in OS 1.6.1 but not 1.6.2

[TriBahtinov-C11_PETG_1h13m.zip](https://github.com/SoftFever/OrcaSlicer/files/11408461/TriBahtinov-C11_PETG_1h13m.zip)

**Comment by hliebscher** [comment]
@buckeyestargazer your file is created by bambustudio 1.5xxx   there is no model file in the 3mf is not from 1.6.1
or is modify by other

<metadata name="Application">BambuStudio-01.05.00.61</metadata>
 <metadata name="BambuStudio:3mfVersion">1</metadata>
 <metadata name="CopyRight"></metadata>

you can rename the org 3mf as zip .... extract and then look in ;-) 

i use only save as not export! and pls don't mix the versions or save version in filename

**Comment by SoftFever** [comment]
@hliebscher I think @buckeyestargazer is referring to not able to view generated gcode/.3mf file from older version of OrcaSlicer.
It's a known issue.
I'm looking into it.

**Comment by buckeyestargazer** [comment]
> @buckeyestargazer your file is created by bambustudio 1.5xxx there is no model file in the 3mf is not from 1.6.1 or is modify by other
> 
> BambuStudio-01.05.00.61 1
> 
> you can rename the org 3mf as zip .... extract and then look in ;-)
> 
> i use only save as not export! and pls don't mix the versions or save version in filename

I have never used Bambu slicer.  From day one using the X1C I have always used Orca Slicer.



> @hliebscher I think @buckeyestargazer is referring to not able to view generated gcode/.3mf file from older version of OrcaSlicer. It's a known issue. I'm looking into it.

Yes, you are correct, and it looks like you have already been working on the solution.  Thanks!
