### ISSUE TITLE
Linux - Orca Slicer Configuration window not sizable

### ISSUE THREAD

**Issue by mathewrtaylor** [SoftFever/OrcaSlicer#959]
Unable to open up the configuration window to adjust settings.

- Using Linux distro (Orca Slicer 1.6.2)
- Clicking on Bed Icon
![image](https://user-images.githubusercontent.com/76273795/236371554-b123b418-b979-4be0-adb0-5f28e8a0300e.png)
- Unable to resize and not big enough to read:
![image](https://user-images.githubusercontent.com/76273795/236371288-e92dc1ed-72de-40c1-a9be-ca9e11c9cbfb.png)
- Have switched to another language and back to English

**Comment by TexZeTech** [comment]
I rased this issue here #552

**Comment by mathewrtaylor** [comment]
Searched and did not see 552.  My apologies, indeed same behavior..
