### ISSUE TITLE
QOL Feature - Thumbnail at the end of GCODE

### ISSUE THREAD

**Issue by cron410** [SoftFever/OrcaSlicer#96]
In Superslicer we have the ability to place GCODE Thumbnail data at the end of the file. This moves that giant block of encoded data out of our way when editing the file. Not a big deal, but it really makes things feel nice in Superslicer if I ever have to edit the file between prints.

Here's how Superslicer does it.
![image](https://user-images.githubusercontent.com/3082899/210196953-51c30b9d-5f2d-44ce-89db-23495015689d.png)

I've been looking through the PrusaSlicer and SuperSlicer source code and have yet to track down how this is implemented. Thumbnails seem to be handled by many different parts of the code.

Thank you so much for this project, I'm loving your take on a very ergonomical slicer.

**Comment by CODeRUS** [comment]
+1 I love superslicer so much fopr this option. If i need to look inside gcode, I dont need to scroll.
