### ISSUE TITLE
Compare Preset Dark Mode Color Issue

### ISSUE THREAD

**Issue by ondrovic** [SoftFever/OrcaSlicer#966]
**Describe the bug**
When using compare preset while using dark mode, 

**3mf File for This Bug**
n/a

**To Reproduce**
1. Ensure Dark Mode is enabled in preferences
2. Select Compare Presets
3. Select items to compare
4. Observe that 1/2 the text is highlighted in an almost unreadable white (see screenshot)
    * even closed and reopened no luck
**Expected behavior**

**Screenshots**
Dark Mode
![image](https://user-images.githubusercontent.com/3682042/236550714-72d3b755-38c0-474e-95b7-0632f976e5f9.png)
Light Mode (just for comparison)
![image](https://user-images.githubusercontent.com/3682042/236551355-9e3ca1c6-9663-4fd2-9a72-7f273a5c8c6f.png)

**Printer model**
Bambulabs X1C

**Desktop (please complete the following information):**
Edition	Windows 11 Pro
Version	22H2
Installed on	‎12/‎4/‎2022
OS build	22621.1635
Experience	Windows Feature Experience Pack 1000.22641.1000.0

**Comment by yw4z** [comment]
fixed in https://github.com/SoftFever/OrcaSlicer/pull/10781
