### ISSUE TITLE
Make overhangs printable

### ISSUE THREAD

**Issue by Rhotix** [SoftFever/OrcaSlicer#968]
It would be nice if there is a way to implement a feature like Curas "make overhangs printable"
There are many models which arent designed with the rules for printing in mind. A feature like that could make 90° overhangs which the slicer want to print first remodel to 45° degrees or else.

**Comment by tome9111991** [comment]
Mybe this feature can help too?
https://github.com/users/SoftFever/projects/1/views/1?pane=issue&itemId=23127076
