### ISSUE TITLE
Add support for pressure advance calibration using the new Ellis method

### ISSUE THREAD

**Issue by julie777** [SoftFever/OrcaSlicer#972]
## Is your feature request related to a problem? Please describe.

I have been reading through all of the work that Ellis has done regarding calibration. He discarded the line test and has the tower and the chevron test now.
[Ellis' Pressure Advance](https://ellis3dp.com/Pressure_Linear_Advance_Tool/)

## Describe the solution you'd like

Add the new chevron method of pressure advance calibration.

**Comment by Ibot-11** [comment]
Dupe #640

**Comment by jagerman** [comment]
Fixed by #1547
