### ISSUE TITLE
When running the PA calibration, show numbers is enabled if tower is selected.

### ISSUE THREAD

**Issue by julie777** [SoftFever/OrcaSlicer#975]
**Describe the bug**

When selecting tower as the method for PA calibration, the option to show numbers is enabled and checked, but there are no numbers printed for the tower version of the test.

**3mf File for This Bug**
If it is related to slicing, please append the 3mf file. It could be extremely helpful to solve the issue.

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

Only options that are applicable should be enabled.

**Screenshots**

**Printer model**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Windows]

**Comment by SoftFever** [comment]
It's grayed out.
Though it is not very obvious in some systems.
Gonna make it unchecked for PA tower to avoid confusion.
