### ISSUE TITLE
Generic presets missing/cannot be added in 1.6.2 applesilicon release

### ISSUE THREAD

**Issue by arshling** [SoftFever/OrcaSlicer#981]
**Describe the bug**
Prior filament presets of "Generic PLA, Generic PETG" are no longer present in the add/remove menu. These are replaced by "SecKit Generic PLA/ABS/etc" (despite not having/selecting SecKit in setup). When SecKit generic options are selected in the add/remove menu, they are not added to the drop down box for use.

**3mf File for This Bug**
N/A

**To Reproduce**
Issue is constant and persist in 1.6.2 official despite full uninstall/reinstall, as well as trying to manually copy presets from the Bambu official application files.

**Expected behavior**
Generic preset should show in drop down selection after checked in add/remove menu. Filaments in the add/remove menu presumably should not have SecKit descriptor when not using a SecKit printer. Generic filament presets are listed and function correctly in the prior 1.6.2 beta.

**Screenshots**
<img width="459" alt="Screenshot 2023-05-06 at 7 19 56 PM" src="https://user-images.githubusercontent.com/59721022/236650148-74f3c947-eccf-448e-a164-23a187c53d22.png">

<img width="966" alt="Screenshot 2023-05-06 at 7 20 24 PM" src="https://user-images.githubusercontent.com/59721022/236650153-e84cacb6-5ec0-4dea-b544-d691db21f25f.png">

<img width="505" alt="Screenshot 2023-05-06 at 7 20 33 PM" src="https://user-images.githubusercontent.com/59721022/236650156-162e1798-f135-4854-a471-73d42785fe74.png">

**Printer model**
Bambu X1C

**Desktop (please complete the following information):**
 - OS: MacOS M1
 - Version 1.6.2

**Comment by SoftFever** [comment]
Fixed in 1.6.3 beta
