### ISSUE TITLE
Typo in initial Setup Wizard

### ISSUE THREAD

**Issue by MikeOxlong83** [SoftFever/OrcaSlicer#982]
**Describe the bug**
![Screenshot 2023-05-06 at 5 06 41 PM](https://user-images.githubusercontent.com/77044976/236651283-9086e102-52db-418b-8d90-7f9c1060f025.png)

**3mf File for This Bug**
If it is related to slicing, please append the 3mf file. It could be extremely helpful to solve the issue.

**To Reproduce**
Open the program for the 1st time, or start the Setup wizard manually by adding a printer.

**Expected behavior**
An interface free of typos.

**Screenshots**
See above

**Printer model**
All

**Desktop (please complete the following information):**
 - OS: Mac Intel
 - Version Latest (1.6.2)

**Comment by hliebscher** [comment]
is fixed with my other PR

**Comment by hliebscher** [comment]
@SoftFever @MikeOxlong83  pls close the bug
